Azure/azure-cli

- src/azure-cli-core/azure/cli/core/_identity.py
- src/azure-cli-core/azure/cli/core/_profile.py
> [Identity] Support SP and MSI

- src/azure-cli-core/azure/cli/core/util.py
- src/azure-cli/azure/cli/command_modules/resource/_help.py
- src/azure-cli/azure/cli/command_modules/resource/_params.py
Refine the help doc of `az rest`.
Also use the correct name `URL` instead of `URI` for the HTTP request. See [What is the difference between a URI, a URL and a URN?](https://stackoverflow.com/questions/176264/what-is-the-difference-between-a-uri-a-url-and-a-urn).
```
az rest --help
```
> {REST} az rest: Refine help

- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/recordings/test_vm_availset.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_availset.yaml
https://github.com/Azure/azure-cli/issues/11821
`az vm availability-set list` does not show VM list in each availability set.
Now it can show it.
Before:
```
"virtualMachines": null
```
After:
```
"virtualMachines": [
{
"id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/FYTEST4/providers/Microsoft.Compute/virtualMachines/VM1",
"resourceGroup": "FYTEST4"
}
]
```
```
az vm availability-set create -g rg-n as
az vm create -g rg-n vm1 --image centos --availability-set as
az vm availability-set list
```
You should be able to see VM list in each availability set.
[Component Name 2] az command b: Add some customer-facing …
> [Compute] az vm availability-set list: Support showing VM list

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/acs/_client_factory.py
- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/commands.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
This is a draft PR to allow early feedback. 
This PR updates ARO module to latest API version `2019-10-27-preview`.  It depends on https://github.com/Azure/azure-rest-api-specs/pull/8305 (in the process of being merged) and the consequent sdk-for-python build. 
In the new version vnet-peer has been removed from "create" operation. This is due to latest changes done on Azure side while implementing new API features it is now possible to edit vnet peering after the cluster creation. I have tried deprecation approach (https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#deprecating-commands-and-arguments) but unfortunately in this circumstances we have to remove it now rather than adding a deprecation notice. 
[ACS] BREAKING …
> [ACS] BREAKING CHANGE: ARO remove vnet-peer, upgrade to 2019-10-27-preview API version

- src/azure-cli/azure/cli/command_modules/monitor/_client_factory.py
- src/azure-cli/azure/cli/command_modules/monitor/_help.py
- src/azure-cli/azure/cli/command_modules/monitor/_params.py
- src/azure-cli/azure/cli/command_modules/monitor/commands.py
- src/azure-cli/azure/cli/command_modules/monitor/operations/log_analytics_linked_storage_account.py
- src/azure-cli/azure/cli/command_modules/monitor/operations/log_analytics_workspace.py
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_log_analytics_workspace_linked_storage.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_log_analytics_workspace_public_access.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_log_analytics_workspace.py
- src/azure-cli/azure/cli/command_modules/monitor/validators.py
> [Monitor] az monitor log-analytics workspace linked-storage: supports BYOS features

- .azure-pipelines/templates/automation_test.yml
- azure-pipelines.yml
1. Onboard new azdev to run automation test.
2. Onboard pytest to run Automation Test
3. Deprecate nose test framework
1. test incremental test on network package https://github.com/Azure/azure-cli/pull/13173,
1.1 it ran 132 tests under profile latest
1.2 it ran 71 tests under profile 2018
2. test incremental test on compute package https://github.com/Azure/azure-cli/pull/13175, it ran all tests under latest profile for vm.
3. test incremental test on storage package https://github.com/Azure/azure-cli/pull/13176, it ran all tests under latest profile for storage.
4. test incremental test on keyvault package https://github.com/Azure/azure-cli/pull/13177, it ran all tests under latest profile for keyvault 
5. test incremental test on resource …
> [CI] Onboard pytest and deprecate nose for Automation Test

- doc/extensions/README.md
The extensions README had a stale warning to only use two specific versions of the wheel. The issue linked to  ( #6441 ) has been closed for well over a year. This change removes that stale warning.
---
> {Docs} Remove stale reference in README to closed issue about extensions

- src/azure-cli/azure/cli/command_modules/appconfig/_azconfig/execution_context.py
- src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/export.json
- src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/export_features.json
- src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/export_features_prop.json
- src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/export_features_yaml.json
Now all CI failed due to the following pylint error which is from unchanged code:
************* Module azure.cli.command_modules.appconfig._azconfig.execution_context 
src/azure-cli/azure/cli/command_modules/appconfig/_azconfig/execution_context.py:81:15: E1102: self.next is not callable (not-callable) 
---
> {appconfig} Fix style for next not callable

- .azure-pipelines/templates/automation_test.yml
- azure-pipelines.yml
CI now wrongly run all test on Batched CI mode because of not passing profile value.
Test PR https://github.com/Azure/azure-cli/pull/13221
other profiles (not latest) should run all tests under corresponding profiles instead of the buggy way to run 1936 tests.
---
> {CI} Fix running full test timeout on profile when in batch mode

- src/azure-cli-core/azure/cli/core/_identity.py
- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli/azure/cli/command_modules/profile/__init__.py
- src/azure-cli/azure/cli/command_modules/profile/_help.py
- src/azure-cli/azure/cli/command_modules/profile/custom.py
Support managed identity.
It currently shows a warning about the used managed identity. We can remove it in the official version. 
> Using Managed Identity: {"type": "systemAssignedIdentity", "id_type": "client_id", "tenant_id": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a", "client_id": "263438d4-b108-497e-8400-f9d5172495ae", "object_id": "63bdf800-9003-4644-b23c-0caeabf62a42", "resource_id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourcegroups/xxx/providers/Microsoft.Compute/virtualMachines/xxx"}
Also it shows a warning for deprecating `assignedIdentityInfo`:
> assignedIdentityInfo will be deprecated in the future. Only client ID should be used.
When running `az login --identity` without `--username`, the behavior of **Azure Instance Metadata Service (IMDS)** is 
- Check whether …
> {Identity} Support managed identity login

- src/azure-cli-core/azure/cli/core/extension/__init__.py
With this https://github.com/Azure/azure-cli/pull/12782 merged, the ability to load metadata from a Python Package is enhanced, but the algorithm is to travel all folders under a specific extension home folder.
https://github.com/Azure/azure-cli/blob/69c99339b7b56263eb8167df2eed0c5593963195/src/azure-cli-core/azure/cli/core/extension/__init__.py#L146-L151
The problem is that if there are other folder named with `.dist-info`, it will load their metadata too, which will show a wrong extension version. Such as `azure-iot` and `alias`, as it has dependecies and CLI will place those dependecies inside the same folder for `azure-iot`.
```
$ ll ~/.azure/cliextensions/azure-iot           
total 568K
drwxrwxr-x 3 harold harold 4.0K Apr 28 11:25 attr
drwxrwxr-x 2 harold harold …
```
> [Extension] fix loading wrong metadata for wheel type extension

- src/azure-cli/azure/cli/command_modules/acr/check_health.py
Fix [az acr check-health : Error image operating system "linux" cannot be used on this platform](https://github.com/Azure/acr/issues/328)
Fix the bug that `az acr check-health` always throws "DOCKER_PULL_ERROR" on Windows 
**Before:**
**After:**
`az acr check-health --name myregistry --ignore-errors --yes`
---
> [ACR] `az acr check-health`: Fix "DOCKER_PULL_ERROR" on Windows

- requirements.txt
- src/azure-cli-core/setup.py
wheel should not be needed to run Azure CLI. It is only used in packaging.
To remove wheel from azure-cli-core dependencies, we need to install wheel in packaging scripts. ~~It seems they're already doing this, will check them one by one.~~ Verified that MSI, homebrew and pypi use setup.py to build wheels during packaging, and their script all include a step to install wheel. Other packages use requirements file to install dependency, wheel is not used.
For the packaging of extensions, as azdev has the dependency of wheel, it should be fine.
--- …
> {Packaging} Remove wheel as a runtime dependency

- src/azure-cli-core/azure/cli/core/extension/__init__.py
The fix https://github.com/Azure/azure-cli/pull/13222 here to filter extension's metadata has potention bugs.
https://github.com/Azure/azure-cli/blob/154ecaa0b179b57aed4e9df162d664da2a5e3c46/src/azure-cli-core/azure/cli/core/extension/__init__.py#L141
If some dependecies have longer name and prefix with the extension name, it make still crash. Currently just lucky.
Besides, the current way to filter will still filter out those folders ends with `.egg-info` which contains PKG-INFO instead of METADATA. So, it would crash due to incorrect metadata format for `pkginfo.Wheel`
Fix https://github.com/Azure/azure-cli/issues/13241
Fix https://github.com/Azure/azure-iot-cli-extension/issues/173
Fix https://github.com/Azure/azure-cli/issues/13240
**History …
> {Extension} Enhance the ability to filter extension's dist-info in order to get correct METADATA 

- src/azure-cli-core/azure/cli/core/util.py
Fix https://github.com/Azure/azure-cli/issues/11927: az login uses `cmd.exe` when using WSL which doesn't support UNC paths
`az login` in WSL shows warning:
```
user2@DESKTOP-37TQVO0:~$ az login
'\\wsl$\Ubuntu\home\user2'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
```
This can also be reproduced by running `cmd.exe` directly in WSL:
```
user2@DESKTOP-37TQVO0:~$ cmd.exe
'\\wsl$\Ubuntu\home\user2'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
Microsoft Windows [Version 10.0.18363.720]
(c) 2019 Microsoft Corporation. All rights reserved.
C:\Windows>
```
`powershell.exe` on the other hand doesn't have this problem and can …
> {Profile} az login: In WSL use powershell.exe to open the default browser

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_acr_create_function_app.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_acr_deployment_function_app.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_acr_integration_function_app.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_with_default_app_insights.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_with_no_default_app_insights.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Resolves #13236 
This PR changes `az functionapp create` so that it only sets the `AzureWebJobsDashboard` app setting if AppInsights is disabled. If AppInsights is enabled, `AzureWebJobsDashboard` is ignored so it's not necessary and shouldn't be set. If AppInsights is disabled, then the dashboard is the only way the customer would be able to get logs.
Changed two tests to make sure `AzureWebJobsDashboard` is set in the correct circumstances. Running `azdev test FunctionAppWithAppInsightsDefault` tests it.
[AppService] az functionapp create: AzureWebJobsDashboard will only be set if AppInsights is disabled
---
> [AppService] functionapp: AzureWebJobsDashboard will only be set if AppInsights is disabled

- src/azure-cli/azure/cli/command_modules/backup/custom_afs.py
az backup protection enable-for-azurefileshare cmd was taking uniqueName as input. Added support for friendlyName .
---
> [Backup] Allow FriendlyName in enable protection for AzureFileShare command

- doc/authoring_help.md
- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/batch/_params.py
- src/azure-cli/azure/cli/command_modules/keyvault/_params.py
- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/resource/_params.py
- src/azure-cli/azure/cli/command_modules/role/_params.py
- src/azure-cli/azure/cli/command_modules/vm/_params.py
Fix https://github.com/Azure/azure-cli/issues/10698: `az ad app permission add` description not understandable
The doc for `az ad app permission add` is not rendered correctly, with the value of `--api-permissions` missing. 
https://docs.microsoft.com/en-us/cli/azure/ad/app/permission
The reason is that the doc generator parses `<resource-access-id>` and `<type>` as a possible HTML entities:
https://github.com/Azure/azure-cli/blob/1f34245e83fbb68777c26a764f9cb5e8b86c0051/src/azure-cli/azure/cli/command_modules/role/_params.py#L61
but they don't match up with any entities on the [Docs HTML Whitelist](https://review.docs.microsoft.com/en-us/help/onboard/admin/html-whitelist?branch=master), and the content is discarded. 
**This happens not only to this command but all over …
> {Docs} Quote code in help messages with backticks

- src/azure-cli/azure/cli/command_modules/iot/__init__.py
We need to remove and replace the deprecated IoT extension Id `azure-cli-iot-ext`  with the modern/current extension Id `azure-iot`.
[IoT] az iot: Update the IoT command module first run extension awareness message to the accurate, non-deprecated modern Id `azure-iot`.
> [IoT] Update the IoT command module first run extension awareness message to the accurate, non-deprecated modern Id `azure-iot`

- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
Fix https://github.com/Azure/azure-cli/issues/12804, unintended change ttl value when using `add-record` for an existing dns record.
The default ttl since long time ago it's 3600
---
> [Network] fix ttl value changed unintended for dns add-record

- src/azure-cli/azure/cli/command_modules/acs/custom.py
There was an error introduced in https://github.com/Azure/azure-cli/pull/12240 where AROv3   has been upgraded to latest API version. Fields `name` and `os_type` has been dropped from master pool profile in azure-sdk-for-python: https://github.com/Azure/azure-sdk-for-python/pull/10464/files
create an OpenShift cluster 
`az openshift create -g <group_name> -n <resource_name> --location eastus2`
try show or list command:
`az openshift list`
`az openshift show -g <group_name> -n <resource_name>`
They should execute without error and display the cluster info.
---
This …
> [ACS] bug fix: remove fields cleanup for fields that no longer exist

- src/azure-cli/azure/cli/command_modules/appconfig/_help.py
- src/azure-cli/azure/cli/command_modules/appconfig/_kv_helpers.py
- src/azure-cli/azure/cli/command_modules/appconfig/_params.py
- src/azure-cli/azure/cli/command_modules/appconfig/keyvalue.py
- src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/export.json
- src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/export_features.json
- src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/export_features_prop.json
- src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/export_features_yaml.json
Fix a bug for using ```appconfig kv list``` with both ```--fields``` and ```--resolve-keyvault```. Previously if content type is not included in ```--fields```, it won't resolve any key vault references.  
---
> [AppConfig] Bug fix for list key values with fields

- azure-pipelines.yml
All build fails because of the same reason, the job CredScan is missing
Like this:
The tool set contianing CredScan in Azure SDK account is missing unknowingly.
Temporary disable it for unblocking our development until it's sovled.
---
> {CI} Temporary disable CredScan since ADO bug

- src/azure-cli/azure/cli/command_modules/acr/_docker_utils.py
- src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_commands_mock.py
Add a timeout for any requests to ACR to avoid hang
unit test + manual test
> [ACR] Add default timeout of 5 minutes for any requests to ACR

- src/azure-cli/azure/cli/command_modules/resource/custom.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_group_deployment_thru_uri.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
Issue: #13317 #12890 #12990
This problem is caused by the simultaneous values of the `template` and `template_link` parameters in the `DeploymentProperties` when handling `--handle-extended-json-format`:
The service API returns templateLink only if the request parameter is templateLink.
When both `template_link` and `template` have values in `DeploymentProperties`, the Python SDK will take the data of `template` as the main data, and the request body for service API are:
```
{"properties": {"parameters": {}, "mode": "Incremental", template:{
"$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
"contentVersion": "1.0.0.0",
"resources": [],
"outputs": {
"deploymentOutput": {
"value": "[deployment()]",
"type" : "object"
}
}
}}}
``` …
> [ARM] az deployment: Fix the problem that the templateLink will not be returned when deploying or validating template-uri (#13317)

- src/azure-cli-core/setup.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
Fix https://github.com/Azure/azure-cli/issues/12938: `az login` fails because instance discovery failes with `login.windows.net` in private cloud
This PR bumps ADAL version to 1.2.3 so that private cloud can use `login.microsoftonline.com` to make instance discovery. The old ADAL uses `login.windows.net` to make instance discovery, which fails in a private cloud.
Corresponding ADAL issue: https://github.com/AzureAD/azure-activedirectory-library-for-python/issues/224
Corresponding ADAL PR: https://github.com/AzureAD/azure-activedirectory-library-for-python/pull/227
`az login`
> {Profile} Bump ADAL version to 1.2.3

- azure-pipelines.yml
Replace the hard-coded repo name `Azure/azure-cli` to [`$(Build.Repository.Name)`](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables) so that CI can pass on fork repos.
Variable | Description
-- | --
Build.Repository.Name | The name of the triggering repository.This variable is agent-scoped, and can be used as an environment variable in a script and as a parameter in a build task, but not as part of the build number or as a version control tag.
> {CI} Allow CI to pass on fork repos

- src/azure-cli/azure/cli/command_modules/acs/custom.py
The changes in the original PR were a duplicate of https://github.com/Azure/azure-cli/pull/13315 which got merged recently. I rebased the PR and I updated it so we hopefully reduce the probability of `AttributeError` in the similar cases.
> {ACS} az openshift show/list: Refactoring to reduce the probability of AttributeError

- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_auto_shutdown.yaml
Issue: #12701 #7234
PR: https://github.com/Azure/azure-cli/pull/13199
Remove a validation in client side. @jiasli @triple-it
Let service make the decision. The current behavior of service is that webhook is mandatory. I don't think it is reasonable, either. Maybe the service will update in the future. Anyway, remove this validation in CLI.
---
> {Compute} az vm auto-shutdown: remove a validation

- src/azure-cli-core/azure/cli/core/_identity.py
- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli/azure/cli/command_modules/profile/__init__.py
- src/azure-cli/azure/cli/command_modules/profile/custom.py
Support `az login`. 
This PR changes the behavior of `az logout` and `az account clear` so that they only clear the profiles and legacy cache. 
To clear shared token from MSAL encrypted cache, user will need to specify `--clear-credential`. 
Regardless of whether the user is logged in, CLI will always check the MSAL cache for the specified username or all users, and show warnings accordingly. 
It first checks whether the cache exists (for the username):
- ✔ Yes, check if the command wants to clear the cache
- ✔ Yes, clear the cache and show a warning that the user is also logged out from other SDKs
- ❌ No, show a warning that the credential is still stored in MSAL encrypted cache (ℹ The word **encrypted** is very important and can't be omitted.)
- ❌ No, show a warning that the cache …
> {Identity} az logout

- README.md
- doc/use_cli_effectively.md
- src/azure-cli-core/azure/cli/core/util.py
- Increase visibility of `doc/use_cli_effectively.md`, thus avoiding issues like 
- Output formatting: #8579
- Command chaining: #6821
- Quoting issues: #13208, #13152, #11008, #12970, #11641, #11668, #11003, #10997, #8827, #8070, #7054, #10370, #9228, #8630, #9742
- Proxy/SSL issues: #13032, #12911, #12310, #12122, #11436, #11356, #11166, #11113, #11069, #11068, #10921, #10860, #10463, #10272, #10236, #10079, #11654, #12566, #11806, #9232, #9030 , #8734, #5841
- Generic update arguments: #10287, #10297, #10568, #10073, #1582
- Storage Commands: #12242, #9852
- Add docs for `az rest`
- Add quoting issues for `--query`
- Add quoting issue troubleshooting guide
In order to be consistent with public docs like [Create an Azure service principal with the Azure …
> {Docs} Increase visibility of doc/use_cli_effectively.md

- src/azure-cli-core/azure/cli/core/profiles/_shared.py
- src/azure-cli/azure/cli/command_modules/acs/_client_factory.py
- src/azure-cli/azure/cli/command_modules/acs/commands.py
This PR adds Azure Kubernetes Service (AKS) and Azure Container Registry (ACR) CLI into Azure Stack profile given the AKS and ACR will be private preview around July 2020.
1. Add MGMT_CONTAINERSERVICE and MGMT_CONTAINERREGISTRY in 2019-03-01-hybrid profile
2. Update acs commands to have multi-api support
1. Switch to Azure Stack profile
2. Use AKS and ACR CLI to test
---
> [AzureStack][AKS]Add AKS into AzureStack profile

- src/azure-cli-core/azure/cli/core/profiles/_shared.py
Add Azure Container Registry (ACR) to Azure Stack profile given ACR will be in private preview in July 2020.
1. Switch to Azure Stack Cloud
2. Use ACR command to tests
---
> [ACR] add ACR for azurestack hybrid profile

- src/azure-cli/azure/cli/command_modules/acs/custom.py
Unblock updating minCount in both aks update and aks nodepool update when minCount < actual node count < max Count.
With this, minCount can be greater than the actual node count. Later scale operations equal to or greater than minCount, will respect that minCount in operations.
[CLI-extensions PR
](https://github.com/Azure/azure-cli-extensions/pull/1606)
---
> [AKS] remove range check for updating min count for autoscaler

- src/azure-cli-core/azure/cli/core/_identity.py
- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/authentication.py
Adopt latest changes from Azure Identity https://github.com/Azure/azure-sdk-for-python/pull/10612
As stated in https://github.com/chlowell/azure-sdk-for-python/pull/4#issuecomment-619240415, `UsernamePasswordCredential` doesn't support `authenticate` anymore. When **username+password** is used as authentication method, `AuthenticationRecord` can't be created. Azure CLI can't persist `AuthenticationRecord` and retrieve the refresh token anymore. 
Actually, I think maybe we shouldn't use the name Interactive, but instead, we can flatten `InteractiveCredential` and directly put `InteractiveBrowserCredential`, `DeviceCodeCredential` and `UsernamePasswordCredential` under `PublicClientCredential`.
Created [Teams thread :UsernamePasswordCredential.authenticate is …
> {Identity} Adopt latest changes from Azure Identity #10612

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_ssl_import.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_ssl_import_crossrg.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_ssl_import_resource_id.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Prior to this change, issues were raised #11867 as the command were failing if the key vault was not in the same resource group as the web app. An option existed to provide a resource id, but this was not documented enough to be discoverable. The change allows key vault to be imported across all resource groups in the subscription in context without any change, and if it is not found, a suggestion to provide the full resource id is displayed. Further a help example of using resource id is added.
There are no changes to the parameter list or breaking changes.
The two examples in az webapp config ssl import --help
[AppService] az webapp|functionapp config ssl import: Lookup key vault across resources groups in subscription and …
> [AppService] az webapp|functionapp config ssl import: Lookup key vault across resources groups in subscription and improve help and examples.

- src/azure-cli/azure/cli/command_modules/resource/_formatters.py
- src/azure-cli/azure/cli/command_modules/resource/_params.py
- src/azure-cli/azure/cli/command_modules/resource/custom.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_formatters.py
We found a couple of small issues in the newly added `az deployment sub/group what-if` commands. The PR contains fixes for them:
- Fix a typo in a parameter help message
- Fix alignment for non-empty array in What-If results
- Added error handling for what-if error with 200 status code
To execute a resource group level what-if, run:
```bash
az deployment group what-if --template-file <path-to-template-file>
```
To execute a subscription level what-if, run:
```bash
az deployment sub what-if --template-file <path-to-template-file>
```
---
> [ARM] az deployment sub/group what-if: Fix array alignment and error handling

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
Because the latest `azure.storage.blob` is for track2 without supporting for `BlockBlobService`, `AppendBlobService` ..., which are in track1, using `azure.multiapi.storage` can prevent the breaking change in `azure.stroage.blob`.
The influenced command is `functionapp deployment source config-zip`
---
> {AppService} Use azure.multiapi.storage for storage blob

- src/azure-cli/azure/cli/command_modules/acr/_archive_utils.py
- src/azure-cli/azure/cli/command_modules/acr/_stream_utils.py
- src/azure-cli/azure/cli/command_modules/acr/_utils.py
- src/azure-cli/azure/cli/command_modules/acr/build.py
- src/azure-cli/azure/cli/command_modules/acr/pack.py
- src/azure-cli/azure/cli/command_modules/acr/run.py
- src/azure-cli/azure/cli/command_modules/acr/task.py
- src/azure-cli/azure/cli/command_modules/acr/taskrun.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
Because the latest `azure.storage.blob` is for track2 without supporting for `BlockBlobService`, `AppendBlobService` ..., which are in track1, using `azure.multiapi.storage` can prevent the breaking change in `azure.stroage.blob`.
From my investigation, these changes will influence `az acr build` and `az acr pack build`, but there is no test for these commands.
@yugangw-msft  Can you help test them? And I will recommend you to add test for such commands. 
---
> {ACR} Use azure.multiapi.storage for storage blob service

- src/azure-cli/azure/cli/command_modules/batchai/custom.py
Because the latest `azure.storage.blob` is for track2 without supporting for `BlockBlobService`, `AppendBlobService` ..., which are in track1, using `azure.multiapi.storage` can prevent the breaking change in `azure.stroage.blob`.
`az batchai cluster file list`
---
> {batchai} Change storage dependency

- doc/quoting-issues-with-powershell.md
This PR serves as an extension to https://github.com/Azure/azure-cli/pull/13249. 
PowerShell quoting issues are prevailing in Azure CLI repo: #13340, #13208, #13152, #11008, #12970, #11641, #11668, #11003, #10997, #8827, #8070, #7054, #10370, #9228, #8630, #9742
Since PowerShell quoting issues are not related to Azure CLI but a known bug, separate it to a new doc file for easy management.
> {Doc} Add quoting-issues-with-powershell.md

- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/commands/parameters.py
- src/azure-cli-testsdk/azure/cli/testsdk/base.py
We will support `vnet`/`subnet` for local context by default just as `resource_group` do. If the argument name is defined as `vnet_name` and `subnet`, it will support local context `GET` action automatically.
- `az local-context on`
> Command group 'local-context' is experimental and not covered by customer support. Please use with discretion.
> Local context is turned on, you can run `az local-context off` to turn it off.
- `az network vnet create -g myRG -n my-vnet-1 --subnet-name my-subnet-1`
> Local context is turned on. Its information is saved in working directory D:\code\cli\azure-cli. You can run `az local-context off` to turn it off.
> Command argument values saved to local context: --resource-group: xiaojianxu, --name: xxj-vnet-1, …
> {Core} Load vnet/subnet global definition for local context by default

- src/azure-cli/azure/cli/command_modules/storage/_validators.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_oauth.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_encryption_scope_scenarios.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_oauth.py
Add validator for public access which will transforming "off" to `None` to fix #13373
`az storage container create -n mycontainer --account-name mysa --public-access off `
---
> [Storage] `az storage container create`: Fix #13373 by adding validator for public access

- src/azure-cli/azure/cli/command_modules/acr/_params.py
- src/azure-cli/azure/cli/command_modules/acr/_validators.py
- src/azure-cli/azure/cli/command_modules/acr/commands.py
- src/azure-cli/azure/cli/command_modules/acr/custom.py
- src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_repository_token_create.yaml
- src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_token.py
- src/azure-cli/azure/cli/command_modules/acr/token.py
See history entries below
az acr token create: expose --expiration for accurate time  
az acr token credential generate: expose --expiration for accurate time  
az acr show-endpoints: warn if the dedicated endpoint is not enabled
> {ACR}: expose --expiration from token commands

- src/azure-cli/azure/cli/command_modules/acs/custom.py
This change will help users to validate whether windows-admin-username is set when they want to create a cluster with Windows agent pools.
For example, a user only sets windows-admin-passowrd so a cluster without specifying Windows admin username and password will be created.
```
az aks create --resource-group testcanada --name canada2 --node-count 1 --kubernetes-version 1.14.1 --generate-ssh-keys --windows-admin-password "P@SSW)RD!@#!@" --enable-vmss --network-plugin azure
```
---
> [AKS] Fix that cli doe not fail when user only specifies Windows password

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
https://github.com/Azure/azure-cli/issues/13407
`az vm list-skus` lists details for compute-related resource SKUs.
`--zone` parameter has a wrong behavior.
```
--zone -z
Show all vm size supporting availability zones.
```
**Before:**
```
> az vm list-skus -l uksouth -r hostGroups/hosts -z true -o table
```
**After:**
```
> az vm list-skus -l uksouth -r hostGroups/hosts -z true -o table
ResourceType      Locations    Name        Zones    Restrictions
----------------  -----------  ----------  -------  --------------
hostGroups/hosts  uksouth      DSv3-Type1  1,2,3    None
hostGroups/hosts  uksouth      ESv3-Type1  1,2,3    None
hostGroups/hosts  uksouth      DSv3-Type2  1,2,3    None
hostGroups/hosts  uksouth      ESv3-Type2  1,2,3    None
hostGroups/hosts  uksouth …
```
> [Compute] az vm list-skus: Update --zone behavior, return all type skus now

- .github/CODEOWNERS
- src/azure-cli/azure/cli/command_modules/monitor/_params.py
> {Monitor} az monitor metrics alert: refine severity explanation

- src/azure-cli/azure/cli/command_modules/resource/commands.py
Issue: #13129
The previous `deprecate_info` information is added at the level of `deployment operation`, so all of its subgroups will also be prompted to be discarded. But in fact, the subgroups has not been abandoned.
Therefore, we should change to apply the `deprecate_info` information to each of the operations for `deployment operation` instead of itself.
---
> [ARM] az deployment operation: Modify the deprecate information (#13129)

- src/azure-cli/azure/cli/command_modules/storage/_validators.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_azcopy_scenarios.py
> [Storage] az storage blob sync: Support `--connection-string` (#11880) 

- src/azure-cli/azure/cli/command_modules/storage/azcopy/util.py
Issue: #9576
If the install location in `_get_default_install_location()` is not found, `None` will be returned, resulting in an unreasonable error prompt in the judgment of `os.path.isfile(install_location)` in the subsequent process:
> stat: path should be string, bytes, os.PathLike or integer, not NoneType
So I added the correct exception throw when it couldn't find the install location to help the customers understand the reason for the error.
---
> [Storage] az storage blob sync: Fix the incorrect error message when azcopy cannot find the installation location (#9576) 

- src/azure-cli-core/azure/cli/core/commands/template_create.py
- src/azure-cli/azure/cli/command_modules/network/_params.py
> {Network} az network nic create: Refine help message

- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
> [Network] az network private-endpoint: deprecate --group-ids and redirect to --group-id

- src/azure-cli/azure/cli/command_modules/network/zone_file/parse_zone_file.py
See internal ICM 187136418
We are failing to import zones when domain name in $origin contains hypens.
This is because we don't parse it correctly in the regex (only alphanumeric char are evaluated with "\w" and that doesn't include hypen, like it is for outher resurces like CNAME.
---
> [Network] az network dns zone: support - character

- src/azure-cli/azure/cli/command_modules/aro/_validators.py
CLIError pointed to flag `--worker_vm_disk_size_gb` instead of `--worker-vm-disk-size-gb`
`None`
---
> [ARO]Change CLIError to correct flag for --worker-vm-disk-size-gb

- src/azure-cli/azure/cli/command_modules/redis/_params.py
Updated documentation for Redis create parameter - enable_non_ssl_port to fix #13529 
Only documentation changes
---
> [Redis] Fix #13529: Change documentation of parameter enable_non_ssl_port 

- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
Doc update to jmespath version 0.9.5
Customer has raised a Github issue https://github.com/MicrosoftDocs/azure-docs-cli/issues/1966 to get the doc updated with latest version of jmespath to reflect the issue that was resolved. 
after upgrade Fedora32, run az command wil raises SynataxWarning
```
/usr/lib64/az/lib/python3.6/site-packages/jmespath/visitor.py:32: SyntaxWarning: "is" with a literal. Did you mean "=="?
if x is 0 or x is 1:
/usr/lib64/az/lib/python3.6/site-packages/jmespath/visitor.py:32: SyntaxWarning: "is" with a literal. Did you mean "=="?
if x is 0 or x is 1:
/usr/lib64/az/lib/python3.6/site-packages/jmespath/visitor.py:34: SyntaxWarning: "is" with a literal. Did you mean "=="?
elif y is 0 or y is 1:
/usr/lib64/az/lib/python3.6/site-packages/jmespath/visitor.py:34: …
```
> {Core} Bump to jmespath==0.9.5

- src/azure-cli-core/azure/cli/core/_identity.py
- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli/azure/cli/command_modules/profile/custom.py
~~Currently can't test in Cloud Shell due to the lack of Python 3.6+. See internal email: Python 3.6+ support in Cloud Shell~~
Use [`pyenv`](https://github.com/pyenv/pyenv) to install Python 3.6+ in Cloud Shell. See https://stackoverflow.com/a/61890236/2199657. Special thanks to @NullMDR for this fascinating solution. 
Log in to Cloud Shell.
```
$ az login --identity
Using Cloud Shell Managed Identity: {"tenant_id": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a", "unique_name": "xxx@microsoft.com"}
[
{
"environmentName": "AzureCloud",
"homeTenantId": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a",
"id": "0b1f6471-1bf0-4dda-aec3-cb9272f09590",
"isDefault": true,
"managedByTenants": [
{
"tenantId": "2f4a9838-26b7-47ee-be60-ccc1fdec5953"
}
],
"name": "AzureSDKTest",
"state": "Enabled",
"tenantId": …
```
> [Identity] Support Cloud Shell login

- src/azure-cli-core/azure/cli/core/_identity.py
Due to the removal of `UsernamePasswordCredential.authenticate`, when **username+password** is used as the authentication method, Azure CLI **can't persist user's `AuthenticationRecord` and utilize refresh tokens stored in MSAL cache**. In such case, Azure CLI will have to **save user's password** by itself, which is absolutely not a good idea from a security perspective. See https://github.com/Azure/azure-sdk-for-python/issues/11449, https://github.com/Azure/azure-sdk-for-python/issues/11546
This PR solves the above issue by incorporating the changes from https://github.com/Azure/azure-sdk-for-python/pull/11528
⚠ However, using this `AuthenticationRecord` correctly remains unsolved: https://github.com/Azure/azure-sdk-for-python/issues/11448. We use …
> {Identity} Support UsernamePasswordCredential.authenticate

- src/azure-cli/azure/cli/command_modules/appconfig/_format.py
- src/azure-cli/azure/cli/command_modules/appconfig/_params.py
- src/azure-cli/azure/cli/command_modules/appconfig/_utils.py
When users specify --fields to filter some output fields, the "content_type" and "last_modified" fields are not displayed in tabular output format.
az appconfig kv list --key * --label *
az appconfig kv list --key * --label * -o table
az appconfig kv list --key * --label * --fields key content_type last_modified
az appconfig kv list --key * --label * --fields key content_type last_modified -o table
---
> {AppConfig} Fix ContentType display in table format when filtering fields

- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/operations/azcopy.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_azcopy_scenarios.py
> [Storage] az storage copy: Add parameter `--follow-symlinks` to support symlinks (#12037)

- src/azure-cli/azure/cli/command_modules/resource/custom.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_tag_update_by_patch.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
Issue: #13255
The properties of `ServiceUri` for `Microsoft.ContainerRegistry/registries/webhooks` must be filled, and a `PUT` request that passes back to properties will fail due to the lack of properties, so the `PATCH` type should be used.
---
> [ARM] az resource tag: Fix the problem of tagging resources with resource type `Microsoft.ContainerRegistry/registries/webhooks` (#13255)

- src/azure-cli/azure/cli/command_modules/role/custom.py
- src/azure-cli/azure/cli/command_modules/role/tests/latest/recordings/test_create_for_rbac_with_right_display_name.yaml
- src/azure-cli/azure/cli/command_modules/role/tests/latest/test_role.py
Signed-off-by: Davin Taddeo <davin@chef.io>
This is an update to the change made in #13357 in the hopes of fixing issue #13625.  I updated the new _random_password() method to avoid special characters that can cause problems in a lot of scripting languages.
az ad sp credential reset -n test
Expected Result: password/secret should be a string with at least one special character, but whose first character is alpha-numeric and does not contain dangerous special characters like !$#;\/
[RBAC] `az ad sp credential reset`: modify credential generation to avoid troublesome special characters
---
> [RBAC] `az ad sp credential reset`: modify credential generation to avoid troublesome special characters

- src/azure-cli-core/azure/cli/core/extension/tests/latest/test_dev_type_extension.py
- src/azure-cli-core/azure/cli/core/extension/tests/latest/test_wheel_type_extension.py
Test files/modules are not installed. Import from the current directory, or they will
fail when running in detached mode (eg: autopkgtest in Debian/Ubuntu).
> {Extensions} tests: do not import from absolute path

- scripts/release/debian/Dockerfile
- scripts/release/debian/build.sh
> {Packaging} Upgrade python version to 3.6.10 in deb package

- src/azure-cli/azure/cli/command_modules/appservice/_client_factory.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_list_locations_free_sku.yaml
`az appservice list-locations` command is returning more locations than what is actually available.
Currently we are calling the /appservice/listgeoregions endpoint and returning those results. We should actually be calling that endpoint as well as the /resources/providers/get endpoint with resourceType = "sites", and returning the intersection of the two lists of regions.  
The list should match the list of regions options shown in the Azure Portal when you create a new App Service resource.
For example, running the command `az appservice list-locations --sku=FREE` should not be returning the location "UAE Central", since the "UAE Central" region is not an available option when creating a new App Service resource on the Portal. 
--- …
> [AppService] Fix #12739 az appservice list-locations returns some invalid locations

- src/azure-cli/azure/cli/command_modules/acs/custom.py
This PR fixes a bug that if the cluster is an MSI cluster and uses subnet, it will fail to create role assignment on the service principal as the service principal does not exist.
---
> [AKS]Fix creating role assignment for MSI clsuter plus custom subnet

- src/azure-cli/azure/cli/command_modules/keyvault/_help.py
Fix: #13548 
The previous help message for `az keyvault key download` has insufficient information. Users may think it can be used to download private keys.
Make it consistent with `az keyvault key show`:
1. `show`: Gets the public part of a stored key.
2. `download`: Downloads the public part of a stored key.
---
> {KeyVault} `az keyvault key download`: refine help message 

- src/azure-cli/azure/cli/command_modules/keyvault/_params.py
Fix: #13013 
The previous doc was inherited from [Swagger](https://github.com/Azure/azure-rest-api-specs/blob/fc44ee327ea1ef5ea3cb999e9c54c4198dd10b27/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L4457), it's a plaintext: `Elliptic curve name. For valid values, see JsonWebKeyCurveName.` And it doesn't act as a hyperlink in the [docs page](https://docs.microsoft.com/en-us/cli/azure/keyvault/key?view=azure-cli-latest#az-keyvault-key-create-optional-parameters).
---
> {KeyVault} Add hyperlinks for `JsonWebKeyType` and `JsonWebKeyCurveName`

- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_url_path_map_edge_case.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Fix #13189 
we have two arguments called `--address-pool` and `--redirect-config` and three corresponding arguments with `default` prefix. The current behavior is when user doesn't input argument, the default value would be used to set it by Azure CLI. But server refuses rest call with both two arguments. Such behavior caused issue #13189. Since the telemetry shows that no one can call it with two arguments. I would raise error for such usage.
---
> {Network} az network application-gateway url-path-map rule: fix edge case

- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/commands.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
az aks upgrade command should support --yes to avoid the tty exception. This fixes issue 
https://github.com/Azure/azure-cli/issues/11099
---
> [AKS] support --yes for az aks upgrade

- src/azure-cli/azure/cli/command_modules/network/_help.py
This is a fix to refine the help message and adding an example for #12934 
The --servers parameter should contain the entire list of IP Addresses/DNS Names to be added to the backend pool. The explanation for this is not clear in the help and causes confusion. That has been fixed.
There is no example provided for the --add optional parameter. This commit adds an example for this. Adding this example would help understand this parameter and its syntax better. 
The  documentation for this also needs to reflect this change: https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/address-pool?view=azure-cli-latest#az-network-application-gateway-address-pool-update . Not sure how that is updated.
This change has been discussed with @MyronFanQiu in …
> [Network]: Refine help message and add examples for az network application-gateway address-pool update

- src/azure-cli/azure/cli/command_modules/aro/_help.py
- src/azure-cli/azure/cli/command_modules/aro/_params.py
Add Public, Private to params for help with ingress/apiserver visibility
Add to Public, Private to describe parameters accepted to --apiserver-visibility and ingress-visibility 
`src/azure-cli/azure/cli/command_modules/aro/_params.py`.
Add an example to `src/azure-cli/azure/cli/command_modules/aro/_help.py` to demonstrate how to create a private cluster when executing `az aro create --help`
Resolves https://github.com/Azure/azure-cli/issues/13530
None
---
> [ARO] Add Public, Private to params for help with ingress/apiserver visibility

- src/azure-cli/azure/cli/command_modules/monitor/_help.py
- src/azure-cli/azure/cli/command_modules/monitor/commands.py
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_log_analytics_cluster.py
- src/azure-cli/azure/cli/command_modules/monitor/validators.py
This PR covers the following issues:
- #13593: Expose `--no-wait` for command `az monitor log-analytics cluster create`
- #13754: Remove preview comment for cluster commands
- #13570: Add explanation for linked services
---
> [Monitor] Support no wait for cluster creation

- src/azure-cli-core/setup.py
- src/azure-cli/azure/cli/command_modules/profile/__init__.py
- src/azure-cli/azure/cli/command_modules/profile/custom.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
1. Rename `auth_only` to a better name `tenant_access`, indicating bare tenant-level access.
2. Deprecate `--allow-no-subscriptions`, because:
1. Even with `--allow-no-subscriptions`, `az login` fails when ARM request is blocked.
2. Depending on whether the tenant has subscriptions, the `id` property in `az account list/show` is ambiguous: it can mean either tenant ID or subscription ID. 
```
> az login -h
--allow-no-subscriptions [Deprecated] : Support access tenants without subscriptions.
It's uncommon but useful to run tenant level commands,
such as `az ad`.
Option '--allow-no-subscriptions' has been deprecated and will be removed in version
'3.0.0'. Use '--tenant-access' instead.
--tenant-access                       : Only log in to the home …
```
> [Identity] Rename auth_only to tenant_access

- src/azure-cli-core/azure/cli/core/_identity.py
- src/azure-cli-core/azure/cli/core/_profile.py
Fix regression introduced in https://github.com/Azure/azure-cli/pull/13567. Use MSAL-style `authority` to build the `PublicClientApplication`.
```
az login
az logout
```
> {Identity} Fix logout

- src/azure-cli-core/azure/cli/core/_identity.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
- src/azure-cli-testsdk/azure/cli/testsdk/patches.py
1. Fix recording playback to adapt to Azure Identity `get_token` pattern 
2. Add tests for logout
1. Use unittest/pytest/`azdev test` to run any test case in playback mode
2. Run `test_logout` and `test_logout_all`
> {Identity} Fix playback tests and add tests for logout

- src/azure-cli/azure/cli/command_modules/acs/_client_factory.py
- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/commands.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
This PR reverts OSA support for `2019-10-17-preview` API version and private clusters. The reason is that in order to use these features the customer's subscription either has to be whitelisted, or feature gate to be removed. Since we have GA'ed ARO v4, we are encouraging customers to use private clusters in v4 rather than v3, hence reverting this change which was broke the client for some customers.  
https://github.com/Azure/OpenShift/issues/183
create an OpenShift cluster
`az openshift create -g <group_name> -n <resource_name> --location eastus2`
try show or list command:
`az openshift list`
`az openshift show -g <group_name> -n <resource_name>`
They should execute without error and display the cluster info.
[Component Name 1] …
> [ACS] Remove private cluster and 2019-10-27-preview API

- .github/CODEOWNERS
- src/azure-cli-core/azure/cli/core/tests/test_util.py
- src/azure-cli-core/azure/cli/core/util.py
Fix regression introduced in #13225.
`az rest` now only extracts subscription ID for ARM requests, not for AD Graph request.
The ID (`00000002-0000-0000-0000-000000000000`) in an AD Graph request (`https://graph.windows.net/00000002-0000-0000-0000-000000000000/applications/00000003-0000-0000-0000-000000000000?api-version=1.6`) is tenant ID. Using it as a subscription ID will cause failure in `get_raw_token`.
```
> az rest -u https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourcegroups?api-version=2019-07-01 --debug 1>$null
...
Retrieving token for resource https://management.core.windows.net/, subscription 0b1f6471-1bf0-4dda-aec3-cb9272f09590
```
> {REST} Only extract subscription ID for ARM requests

- src/azure-cli-core/azure/cli/core/_identity.py
- src/azure-cli-core/azure/cli/core/_msal.py
- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/authentication.py
> [MSAL]Add AAD error handling, refine SP logout

- src/azure-cli-core/azure/cli/core/parser.py
1. This PR provides support for printing a hint message below when a [--query JMESPATH] value error occurs.
`To learn more about [--query JMESPATH] usage in AzureCLI, visit https://aka.ms/CLIQuery`
2. As a manual hint, the message will be printed behind the command usage and before the ai-did-you-mean-this recommendations (if there).
Any commands with the [--query] argument that can raise an error by an invalid JMESPATH.
E.g. Run the command below, you will get the hint message with this PR.
`az group list --query '.xx'`
---
> {Core} Add a hint message for --query error by an invalid JMESPATH

- src/azure-cli-core/azure/cli/core/extension/_resolve.py
- src/azure-cli-core/azure/cli/core/extension/operations.py
- src/azure-cli-core/azure/cli/core/extension/tests/latest/__init__.py
- src/azure-cli-core/azure/cli/core/extension/tests/latest/test_extension_commands.py
- src/azure-cli-core/azure/cli/core/extension/tests/latest/test_resolve.py
- src/azure-cli/azure/cli/command_modules/extension/__init__.py
Close https://github.com/Azure/azure-cli-extensions/issues/1587.
Azure CLI support install extension from an older version.
`az extension add -n {EXTENSION_NAME} --version {CERTAIN_VERSION}`
Such as azure-firewall, azure-devops, azure-cli-ml
Test Scenario:
1. Install azure-firewall without version, it will install 0.31.0 by default the latest. Then, install with --version 0.30.0, CLI will reject to install.
2. Install azure-firewall with version 0.30.0, it will install 0.30.0 as expected. Then, install without --version, CLI will reject to install.
3. show extension will show the correct version of azure-firewall
[Component Name 2] az …
> [Extension] add --version to support to install from a specific version

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_authentication.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
We want to offer support via the Azure CLI tool to update the runtime version of the App Service Authentication/Authorization module. This is done by exposing a runtime version parameter in the "webapp auth update" command, already offered through the Azure CLI tool.
---
> [AppService] az webapp auth update: Add optional parameter to update runtime-version

- src/azure-cli/azure/cli/command_modules/storage/azcopy/util.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_azcopy_scenarios.py
In previous command, when operation failed, the error message will be printed in terminal but no exception raised.
To help DevOps users leverage the exception information, we should raise error when failed.
Fix issue  #13459 
`az storage remove`
---
> [Storage] `az storage remove`: Fix issue #13459 to raise exception for operation failure

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/commands.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_list_deployment_logs.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_show_deployment_logs.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
**Description** 
closes #13734 
Add support for new webapp commands for deployment logs: `az webapp log deployment show` and `az webapp log deployment list`. 
Create & deploy a web or function app
Run `az webapp log deployment list -g ResourceGroup -n WebappName`. This should give you the same list of deployment logs you see when you go to `https://<webapp>.scm.azurewebsites.net/api/deployments`
Run `az webapp log deployment show -g ResourceGroup -n WebappName`. This should give you the latest deployment log
Copy the Deployment ID from any deployment
Run `az webapp log deployment show -g ResourceGroup -n WebappName --deployment-id DeploymentId`. This should give you the log of that particular deployment.
[App Service] `az webapp log deployment …
> [AppService] Add support for deployment logs for webapp in CLI

- src/azure-cli/azure/cli/command_modules/cosmosdb/_params.py
- src/azure-cli/azure/cli/command_modules/cosmosdb/commands.py
- src/azure-cli/azure/cli/command_modules/cosmosdb/custom.py
- src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_cassandra_keyspace.yaml
- src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_cassandra_table.yaml
- src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_gremlin_database.yaml
- src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_gremlin_graph.yaml
- src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_mongodb_collection.yaml
- src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_mongodb_database.yaml
- src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_sql_container.yaml
- src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_sql_database.yaml
- src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_table.yaml
- src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/test_cosmosdb_commands.py
This change addresses https://github.com/Azure/azure-cli/issues/12668 by adding supports for "exists" in the new commands that replace the deprecated "cosmosdb database" and "cosmosdb collection" commands. It also updates parameter descriptions to address https://github.com/Azure/azure-cli/issues/13096
These commands are added:
az cosmosdb sql database exists
az cosmosdb sql container exists
az cosmosdb mongodb database exists
az cosmosdb mongodb collection exists
az cosmosdb gremlin database exists
az cosmosdb gremlin graph exists
az cosmosdb cassandra keyspace exists
az cosmosdb cassandra table exists
az cosmosdb table exists
(Fill in the following template if multiple notes …
> [Cosmos DB] az cosmosdb: add exists command to database and container groups

- src/azure-cli/azure/cli/command_modules/keyvault/_command_type.py
- src/azure-cli/azure/cli/command_modules/keyvault/_params.py
- src/azure-cli/azure/cli/command_modules/keyvault/_validators.py
- src/azure-cli/azure/cli/command_modules/keyvault/commands.py
- src/azure-cli/azure/cli/command_modules/keyvault/custom.py
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_key.yaml
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
Add commands: `az keyvault key encrypt/decrypt`.
Encrypt a normal string:
```
keyvault key encrypt -n {key} --vault-name {kv} -a RSA-OAEP --value "123456"
You will get a ciphertext (base64-encoded).
keyvault key encrypt -n {key} --vault-name {kv} -a RSA-OAEP --value "{ciphertext}"
result: "MTIzNDU2" (base64-encoded text for "123456")
```
Encrypt a valid base64 string (actually it's a bytes array):
```
keyvault key encrypt -n {key} --vault-name {kv} -a RSA-OAEP --value "YWJjZGVm"  # It's plaintext is "abcdef"
keyvault key encrypt -n {key} --vault-name {kv} -a RSA-OAEP --value "{ciphertext}"
result: "YWJjZGVm" (The input itself)
```
This PR also fix a bug within `keyvault_custom` and `keyvault_command`, which makes adding preview tags for these commands at command level impossible. Added …
> [KeyVault] Support string/bytes encryption and decryption with stored keys

- src/azure-cli/azure/cli/command_modules/acr/custom.py
Fix #13847
BREAKING CHANGE: The `az acr login --expose-token` now raises error if username or password is specified.
`az acr login -n myregistry -u username -p password --expose-token`
Before:
After:
---
> [ACR] BREAKING CHANGE: `az acr login --expose-token` does not accept username and password

- src/azure-cli/azure/cli/command_modules/role/custom.py
This PR is to fix #7441 
Previously if user specify scope with an invalid resource id, CLI will prompt a strange error message just as described in the issue.
We add a check whether it is a valid resource id here.
The reason why I didn't combine it with `scope == ''` is that I don't want to change previous check sequence.
`az ad sp create-for-rbac --name myTestSP --role contributor --scopes /subscriptions/<subscription>/<resource_group>`
Prompt below error:
_Invalid scope. Please use --help to view the valid format._
--- …
> [RBAC] az ad sp create-for-rbac: refine error message when user specify an invalid scope

- src/azure-cli/azure/cli/command_modules/acs/custom.py
Fixes typo in the error text for az aks update, specially to replace --dettach-acr with --detach-acr. 
Fixes #13555
---
> [AKS] Fix typo in az aks update command

- src/azure-cli/azure/cli/command_modules/acs/_help.py
Updated the help text to fix one typo that was missing an 's' on VirtualMachineScaleSets. Fixes #13945 
Snapped all references to Kubernetes versions to one that is currently supported. Fixes #13922 
---
> [AKS] Fix typo on VirtualMachineScaleSets and update references to Kubernetes versions

- src/azure-cli/azure/cli/command_modules/vm/custom.py
Resolve https://github.com/Azure/azure-cli/issues/13931
Show a warning when a user deploys a VMSS pinned to a specific image version rather than latest
```
You are deploying VMSS pinned to a specific image version from Azure Marketplace. Consider using "latest" as the image version.
```
---
> [Compute] Show a warning when a user deploys a VMSS pinned to a specific image version rather than latest

- src/azure-cli-core/azure/cli/core/authentication.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
- src/azure-cli-core/azure/cli/core/tests/test_profile_v2016_06_01.py
> [MSAL]fix data lake scope issue

- src/azure-cli/azure/cli/command_modules/role/_help.py
- src/azure-cli/azure/cli/command_modules/role/_params.py
Close https://github.com/Azure/azure-cli/issues/11031
Improve help message for `az ad sp create-for-rbac` and  `--scopes` parameter:
```
> az ad sp create-for-rbac -h
...
When --skip-assignment is specified, --scopes will be ignored. You may use `az role
assignment create` to create role assignments for this service principal later.
Arguments
...
--scopes           : Space-separated list of scopes the service principal's role assignment
applies to. Defaults to the root of the current subscription. e.g.,
/subscriptions/0b1f6471-1bf0-4dda-aec3-111122223333,
/subscriptions/0b1f6471-1bf0-4dda-aec3-111122223333/resourceGroups/myGroup,
or /subscriptions/0b1f6471-1bf0-4dda-aec3-111122223333/resourceGroups/myGro
up/providers/Microsoft.Compute/virtualMachines/myVM. …
```
> {RBAC} Improve help message for `az ad sp create-for-rbac`

- src/azure-cli-core/azure/cli/core/telemetry.py
- src/azure-cli-telemetry/azure/cli/telemetry/components/records_collection.py
- src/azure-cli/azure/cli/command_modules/feedback/custom.py
When sending telemetry notes to application insight on Cloud Shell, the following error occurs in the step of moving `cache.x` file to a tmp directory:
> telemetry.records : Fail to move file from /home/feng/.azure/telemetry/cache.1 to /tmp/tmpdj9u1r70/cache.1. Reason: [Errno 18] Invalid cross-device link: '/home/feng/.azure/telemetry/cache.1' -> '/tmp/tmpdj9u1r70/cache.1'.
`os.rename` only works if source and destination are on the same file system which is not the case in Cloud Shell. [`shutil.move`](https://docs.python.org/3/library/shutil.html#shutil.move) can handle it well by copying src to dst using copy_function and then remove src.
In addition, I added Cloud Shell info to feedback and telemetry. 
[Component Name 1] …
> {Telemetry} Fix for file move in cloud shell

- src/azure-cli/azure/cli/command_modules/security/_client_factory.py
- src/azure-cli/azure/cli/command_modules/security/_help.py
- src/azure-cli/azure/cli/command_modules/security/_params.py
- src/azure-cli/azure/cli/command_modules/security/commands.py
- src/azure-cli/azure/cli/command_modules/security/custom.py
- src/azure-cli/azure/cli/command_modules/security/tests/latest/recordings/test_security_compliance.yaml
- src/azure-cli/azure/cli/command_modules/security/tests/latest/test_regulatory_compliance_scenario.py
[security] Add regulatory compliance CLI
Add regulatory compliance CLI for assessments, standards and controls ( List and show for all)
- Regulatory Compliance standards- list,show
- Regulatory Compliance controls- list,show
- Regulatory Compliance assessments- list,show
Users can get a list, single (show) of Regulatory compliance standards, controls and assessment: 
az security regulatory-compliance-standards list
az security regulatory-compliance-standards show -n 'Azure-CIS-1.1.0'
az security regulatory-compliance-controls list --standard-name 'Azure-CIS-1.1.0'
az security regulatory-compliance-controls show --standard-name 'Azure-CIS-1.1.0' -n '1.1'
az security regulatory-compliance-assessments list --standard-name 'Azure-CIS-1.1.0' --control-name …
> [Security] Add security regulatory compliance commands

- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
- src/azure-cli-core/azure/cli/core/tests/test_profile_v2016_06_01.py
Make "az account get-access-token" command work for service principal account using sn+issuer auth.
Obviously when we lighted up the auth flow, we forgot this scenario 
added a unit test
> {Auth} Fix #14072: az account get-access-token: Add support of sn+issuer

- src/azure-cli/azure/cli/command_modules/rdbms/_params.py
- src/azure-cli/azure/cli/command_modules/rdbms/custom.py
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mariadb_server_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_server_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_server_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_commands.py
We are currently adding a new capability in our platform Azure Database for MySQL/Azure Database for PostgreSQL called infrastructure encryption. Currently,  Azure Database for MySQL/Azure Database for PostgreSQL are always encrypted at rest using Microsoft’s managed keys. This new optional feature adds a second layer of encryption using 2nd encryption algorithm which protects the data from compromise of the first algorithm and can have performance impact on the workloads
az postgres server update –name <server name>  -g <resoure_group> --infrastructure-encryption Enabled
az mysql server update --name  <server name>  -g <resoure_group> --infrastructure-encryption Enabled
[Component Name 1] BREAKING CHANGE: az command a: Make some …
> [Rdbms] Add Infrastructure Encryption for Azure Postgres and MySQL

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_helpers.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_managed_aad.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
This PR is to portal the support of creating AKS-managed Azure AD cluster from aks-preview extension. It adds a new argument `--enable-aad` to `az aks create` command. Customers can specify the `--aad-admin-group-object-ids` and `--aad-tenant-id` when creating/updating AKS cluster.
* Create an AKS-managed Azure AD cluster
```
az aks create -g MyResourceGroup -n MyManagedCluster --enable-aad [--aad-admin-group-object-ids <id>] [--aad-tenant-id <id>]
```
* Update an AKS-managed Azure AD cluster
```
az aks update -g MyResourceGroup -n MyManagedCluster [--aad-admin-group-object-ids <id>] [--aad-tenant-id <id>]
```
---
> [AKS] az aks create: add --enable-aad argument

- src/azure-cli/azure/cli/command_modules/acr/commands.py
> [acr]: deprecate helm2 commands

- .azure-pipelines/templates/azdev_setup.yml
- azure-pipelines.yml
Add execution performance check on CI via `azdev perf benchmark`, sampling on `version` command and `network vnet` subcommands
Use master branch of azdev to avoid frequently unnecessary release. (https://github.com/Azure/azure-cli-dev-tools/pull/220#issuecomment-652772354)
https://github.com/Azure/azure-cli-dev-tools/pull/222/checks?check_run_id=825286911
After https://github.com/Azure/azure-cli-dev-tools/pull/220 is megred, the CI should be fine.
---
> {CI} Use master branch of azdev and add benchmark sample to show execution time

- src/azure-cli/azure/cli/command_modules/vm/_params.py
We have changed the term "Low Priority" to "Spot". We have already updated the PowerShell commands and now we need to rename the two items in CLI from "Low Priority" to "Spot"
---
> {Compute} Update help message Change the term "Low Priority" to "Spot"

- src/azure-cli-core/azure/cli/core/decorators.py
- src/azure-cli/requirements.py3.windows.txt
Due to a known issue of `pywin32==225` (https://github.com/mhammond/pywin32/issues/1431). Telemetry is broken on Windows with Python 3.8.
This PR fixes this issue by bumping to `pywin32==228`.
Repro: 
```
> azdev setup -c azure-cli -r azure-cli-extensions
> az version --debug
Suppress exception DLL load failed while importing win32file: The specified module could not be found.
```
After the fix:
```
> ppip install pywin32 --upgrade
> az version --debug
telemetry.save : Save telemetry record of length 2466 in cache
telemetry.check : Returns Positive.
telemetry.main : Begin creating telemetry upload process.
telemetry.process : Creating upload process: "D:\cli\env38\Scripts\python.exe D:\cli\azure-cli\src\azure-cli-telemetry\azure\cli\telemetry\__init__.py …
```
> {Packaging, Telemetry} Bump to pywin32==228

- src/azure-cli-core/azure/cli/core/_profile.py
After fixing telemetry in #14202, `az version` becomes slower. It takes about 1 second.
```
python -X importtime -m azure.cli version 2>perf.log
tuna perf.log
```
This is because `telemetry.py` uses `azure.cli.core._profile.Profile`:
https://github.com/Azure/azure-cli/blob/73330f98ceb6082f3462446b1b17831a50495a87/src/azure-cli-core/azure/cli/core/telemetry.py#L398-L400
which imports `BaseHTTPServer` (`http.server` in Python 3) unconditionally:
https://github.com/Azure/azure-cli/blob/c508fa4aa181872c2ed2c7f53712e9d329d7a3f6/src/azure-cli-core/azure/cli/core/_profile.py#L17
This causes the 0.3s delay.
This PR delays importing `http.server` to when `_get_authorization_code_worker` is called.
Before:
```
> Measure-Command {az version}
Days              : …
```
> {Login} Delay importing http.server

- .github/CODEOWNERS
- src/azure-cli/azure/cli/command_modules/profile/custom.py
- src/azure-cli/azure/cli/command_modules/profile/tests/latest/test_profile_custom.py
Currently, `az account get-access-token` shows `"expiresOn": "N/A"` for Managed Identity:
```
> az login --identity
> az account get-access-token
{
"accessToken": "eyJ0eXAi...",
"expiresOn": "N/A",
"subscription": "0b1f6471-1bf0-4dda-aec3-cb9272f09590",
"tenant": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a",
"tokenType": "Bearer"
}
```
It works for a user account:
```
> az login
> az account get-access-token
{
"accessToken": "eyJ0eXAi...",
"expiresOn": "2020-06-29 17:22:16.443545",
"subscription": "a18897a6-7e44-457d-9260-f2854c0aca42",
"tenant": "72f988bf-86f1-41af-91ab-2d7cd011db47",
"tokenType": "Bearer"
}
```
This is because `msrestazure.azure_active_directory.MSIAuthentication`'s token entry has `expires_on`, while ADAL's token entry has `expiresOn`. 
This PRs fixes this by converting the …
> [Profile] az account get-access-token: Show expiresOn for Managed Identity

- .github/CODEOWNERS
- src/azure-cli/azure/cli/command_modules/role/_help.py
Fix #12797: Cannot grant admin consent for an app role permission
If `ad app permission grant` is called for an app without a corresponding service principal, it will fail:
```sh
$ appId=$(az ad app create --display-name "myapp0630" --query appId -o tsv)
$ az ad app permission grant --id $appId --api 00000003-0000-0000-c000-000000000000
Operation failed with status: 'Not Found'. Details: 404 Client Error: Not Found for url: https://graph.windows.net/54826b22-38d6-4fb2-bad9-b7b93a3e9c5a/oauth2PermissionGrants?$filter=clientId%20eq%20%27c9a8ddb5-d410-4de2-a7ca-0c5d55ff3a6b%27&api-version=1.6
```
To fix it, we need to create a corresponding service principal first:
```sh
$ az ad sp create --id $appId
$ az ad app permission grant --id $appId --api …
```
> {Graph} Fix #12797: ad app permission grant: Add prerequisite to the help message

- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/tests/test_command_registration.py
Fix #14175: ai-did-you-mean-this extension is not loaded after a first run
Currently, if no extension corresponds to a command like `az account` in Command Index:
```
"account": [
"azure.cli.command_modules.profile",
"azure.cli.command_modules.resource"
],
```
`_update_command_table_from_extensions` won't be called, thus left `ALWAYS_LOADED_EXTENSIONS` ignored.
This PR fixes this issue by always calling `_update_command_table_from_modules` and `_update_command_table_from_extensions`.
```pwsh
> az extension add -n ai-did-you-mean-this
> az account --debug
> az account --debug
...
[Thoth]: recommend_recovery_options: version: "2.8.0", command: "account", parameters: "['--debug']", extension: "None"
[Thoth]: User must agree to telemetry before failure …
```
> {Core} Fix #14175: Load ALWAYS_LOADED_EXTENSIONS correctly

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_aadv1_and_update_with_managed_aad.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_nonaad_and_update_with_managed_aad.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
This PR is to port https://github.com/Azure/azure-cli-extensions/pull/1898/files from azure-cli-extension to azure-cli, which supports  updating an existing AAD-Integrated cluster to the new AKS-managed AAD experience.
1. Create a AAD-Integrated cluster: https://docs.microsoft.com/en-us/azure/aks/azure-ad-integration-cli.
2. Update the cluster to the new AKS-managed AAD experience.
```
az aks update -g MyResourceGroup -n MyManagedCluster --enable-aad
```
---
> [AKS] az aks update: add --enable-aad argument

- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_blob_scenarios.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_container_immutability_policy.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_container_legal_hold.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_file_rm_scenarios.py
Add allow large response to skip unstable live test result.
---
> {Storage} Fix live test to allow large response

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/commands.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_show_deployment_logs.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
closes #14099 
- az webapp log deployment show should show actual logs instead of the log info
- Mark commands as in preview
`az webapp log deployment show`
Should have output of a list of logs similar to:
[
{
"log_time": "2020...",
"id": "id",
"message": "log message",
"type": 0,
"details_url": null
},
{
"log_time": "2020...",
"id": "id",
"message": "log message 2",
"type": 0,
"details_url": null
}
]
Rather than an object similar to
{
"active": false,
"author": "N/A",
"author_email": "N/A",
"complete": true,
"deployer": "GITHUB_ZIP_DEPLOY",
"end_time": "2020-06-25T19:04:18.8758562Z",
"id": "id",
"is_readonly": true,
"is_temp": false,
"last_success_end_time": "2020-06-25T19:04:18.8758562Z",
"log_url": …
> [Webapp] Bugfix: az webapp log deployment show - return deployment logs instead of log metadata

- src/azure-cli/azure/cli/command_modules/storage/_help.py
Issue: #10020
There are two problems in the existing examples:
1. `xxx storage account 'MyStorageAccount'` This style of writing makes the customers think that it is a name rather than a placeholder, so it's value should follow the limitation of storage account name.
2. In the existing examples, some are written as `storage account 'MyStorageAccount'`, some as `storage account 'mystorageaccount'`, and they should be unified
---
> [Storage] Fix the storage account name in examples

- src/azure-cli-core/azure/cli/core/__init__.py
This PR is to fix #14015 .
PM want to refine some of local context message. 
`az local-context on`
> Command group 'local-context' is experimental and not covered by customer support. Please use with discretion.
Local context is turned off, you can run `az local-context on` to turn it on.
`az group create -g xxj -l westus2`
> Local context is turned on. Its information is saved in working directory D:\code\cli\azure-cli. You can run `az local-context off` to turn it off.
Your preference of: --name: xxj, --location: westus2 are now saved to local context. To learn more, type in az local-context --help
[Component Name 2] az command b: Add …
> {Core} refine local context message

- scripts/release/rpm/test_rpm_in_docker.sh
Some new vm tests are checked in without `--admin-username` for vm/vmss create command, causing issue #14265
As a workaround to fix the tests in docker for rpm package, use a `USERNAME` env var to return as the default admin user name according to: https://github.com/python/cpython/blob/3cbade7d309ab1ea97ec286d19d506df30bd1ab7/Lib/getpass.py#L162-L165
---
> {Test} Fix default admin-username

- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/extension/_index.py
- src/azure-cli-core/azure/cli/core/extension/operations.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
- src/azure-cli-core/azure/cli/core/tests/test_profile_v2016_06_01.py
Fix regressions introduced by
- #14180, which unconditionally imports `check_version_compatibility` and `requests`
- #14187, which unconditionally imports `MSIAuthenticationWrapper` and `azure.core.credentials`
This PR delays the imports and brings `az version` to its normal speed. 
```pwsh
> Measure-Command {az version}
TotalMilliseconds : 1132.3246
> Measure-Command {az version}
TotalMilliseconds : 627.5202
```
> {Perf} Delay importing MSIAuthenticationWrapper and check_version_compatibility

- scripts/ci/credscan/CredScanSuppressions.json
- src/azure-cli-core/azure/cli/core/tests/test_util.py
- src/azure-cli-core/azure/cli/core/util.py
- src/azure-cli/azure/cli/command_modules/util/tests/latest/recordings/test_rest_arm.yaml
- src/azure-cli/azure/cli/command_modules/util/tests/latest/recordings/test_rest_storage.yaml
- src/azure-cli/azure/cli/command_modules/util/tests/latest/test_rest.py
Fix #14152: No subscription ID specified in the URL
#13782 introduced a bug that `az rest` fails for ARM URLs without subscription ID, like `/subscriptions`, `/tenants`:
https://github.com/Azure/azure-cli/blob/62eb25feac0da927d219321538046faee6882886/src/azure-cli-core/azure/cli/core/util.py#L807-L808
This PR makes `az rest` accept such URLs and retrieve token for the current selected tenant instead.
The debug log is also improved:
```pwsh
> az rest -u /subscriptions?api-version=2020-01-01 --debug
DEBUG: No subscription ID specified in the URL https://management.azure.com/subscriptions?api-version=2020-01-01
DEBUG: Retrieving token for resource https://management.core.windows.net/
> az rest -u /subscriptions/{subscriptionId}/resourcegroups/rg1?api-version=2019-10-01 …
```
> [REST] Fix #14152: `az rest`: Accept ARM URLs without subscription ID

- src/azure-cli/azure/cli/command_modules/acs/_help.py
Now that VMSS is the default vm-set-type, we do not need to explicitly set it. Fixes #14283 
---
> [AKS] Remove explicit setting of VMSS in Windows example command since it is now default

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_nonaad_and_update_with_managed_aad.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
This PR is to port https://github.com/Azure/azure-cli-extensions/pull/2017 from azure-cli-extension to azure-cli, which supports migrating a RBAC-enabled non-AAD cluster to a AKS-managed AAD cluster.
1. Create RBAC-enabled non-AAD cluster.
```
az aks create -g MyResourceGroup -n MyManagedCluster 
```
2. Migrate the cluster to the new AKS-managed AAD experience.
```
az aks update -g MyResourceGroup -n MyManagedCluster --enable-aad
```
---
> [AKS] az aks update: Change --enable-aad argument to migrate a RBAC-enabled non-AAD cluster to a AKS-managed AAD cluster

- src/azure-cli/azure/cli/command_modules/storage/azcopy/util.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_azcopy_scenarios.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/testdir/sample.js
Fix issue #10302 
After upgrading to new azcopy version, it will support guessing content-type
---
> [Storage] Fix issue#10302 to support guess content-type when synchronizing files

- .azure-pipelines/templates/automation_test.yml
- .azure-pipelines/templates/azdev_setup.yml
There is a PR https://github.com/Azure/azure-cli/pull/14438 that we have to release azdev and fix CI at the same time. I don't want to create a broken status for our CI system. Let's pin azdev version first.
> {CI} Pin azdev to latest version

- src/azure-cli/azure/cli/command_modules/hdinsight/_help.py
- src/azure-cli/azure/cli/command_modules/hdinsight/_params.py
- src/azure-cli/azure/cli/command_modules/hdinsight/custom.py
- src/azure-cli/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_cluster_with_encryption_in_transit.yaml
- src/azure-cli/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_cluster_with_private_link.yaml
- src/azure-cli/azure/cli/command_modules/hdinsight/tests/latest/test_hdinsight_commands.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
Added 3 parameters to the command `az hdinsight create` to support private link and encryption in transit feature:
- Added paramter `--public-network-access-type` and `--outbound-public-network-access-type` to support creating cluster with private link feature
- Added parameter `--encryption-in-transit` to support creating cluster with encryption in transit feature
[HDInsight] Added 3 parameters to the command `az hdinsight create` to support private link and encryption in transit feature:
- Added paramter `--public-network-access-type` and `--outbound-public-network-access-type` to support creating cluster with private link feature  
- Added parameter `--encryption-in-transit` to support creating cluster with encryption in transit …
> [HDInsight] Support creating cluster with private link and encryption in transit feature

- src/azure-cli-core/azure/cli/core/util.py
- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/_validators.py
Resolve https://github.com/Azure/azure-cli/issues/14265
**Before**
When `--admin-username` is not provided in `az vm create`, the default is to get the current username of the logged in account of OS. Azure has a banned list of usernames. If the current username is invalid, the command will fail.
**After**
Azure CLI will select a valid username if the default one if invalid.
Set your system's username as root, run `az vm create` without `--admin-username`.
---
> [Compute] Select a valid username if the default username is invalid

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/_validators.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_custom.py
This PR is to install `kubelogin` using `az aks install-cli`. The user can use `--kubelogin-version` and `--kubelogin-install-location` to specify the kubelogin version and install location.
1. Run `az aks install-cli`.
2. kubelogin will be installed.
3. Run `kubelogin -h` to check the version.
4. Run `which kubelogin` to check the install location.
---
> [AKS] az aks install-cli: Add --kubelogin-version and --kubelogin-install-location arguments to install kubelogin

- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_cross_tenant_update.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Previously, if the VM is created from a cross tenant image, then `az update` command for this VM will fail.
This change is to add cross tenant support for `az vm update` command, just as `az vmss update` does.
Please follow the test case in change files.
---
> [Compute] az vm update: support cross tenant image

- src/azure-cli/azure/cli/command_modules/role/_help.py
Fix #14043: Create operation example refers to ambiguous `--id` parameter
As `--id` is not a valid parameter of `az ad app create`, it is recognized as `--identifier-uris` due to [Argument abbreviations (prefix matching)](https://docs.python.org/3/library/argparse.html#argument-abbreviations-prefix-matching).
Also because `argparse.py` doesn't check duplicated parameters (same parameter provided twice) in `_StoreAction`,
https://github.com/python/cpython/blob/c82dda1e08c4b74ca24f88d6a549d93108c319cf/Lib/argparse.py#L928-L929
```py
def __call__(self, parser, namespace, values, option_string=None):
setattr(namespace, self.dest, values)
```
the second `--identifier-uris https://mytestapp.websites.net` overwrites the first `--id e042ec79-34cd-498f-9d9f-123456781234`. So …
> {Role} Remove redundant --id parameter from example

- azure-pipelines.yml
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
Yum package test failed because of CLI pinned a lower version of `yarl`. `yarl` is not directly used in Azure CLI (`yarl` used in [azure-multiapi-storage](https://github.com/Azure/azure-multiapi-storage-python/blob/master/azure/multiapi/storagev2/blob/v2019_07_07/_shared/authentication.py#L17)), its version requiremnets should be determined by the dependecies of CLI which depend on it. We should remove the version constraint in `requirements.txt` as long as its new version is not broken.
--- …
> {Packaging} Unpin yarl version

- src/azure-cli-core/azure/cli/core/util.py
- src/azure-cli/azure/cli/command_modules/profile/_validators.py
- src/azure-cli/azure/cli/command_modules/profile/tests/latest/test_profile_custom.py
- src/azure-cli/azure/cli/command_modules/role/custom.py
Resolve #14096
In `az login`, when `--tenant` is not a valid GUID, CLI will try to query the tenant information from AAD - [Fetch the OpenID Connect metadata document](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#fetch-the-openid-connect-metadata-document) (#10418).
If the tenant is not found, CLI shows error
```
> az login -t non-existing-tenant.onmicrosoft.com
usage: az login [-h] [--verbose] [--debug] [--only-show-errors]
[--output {json,jsonc,yaml,yamlc,table,tsv,none}]
[--query JMESPATH] [--username USERNAME] [--password PASSWORD]
[--service-principal] [--tenant TENANT]
[--allow-no-subscriptions] [-i] [--use-device-code]
[--use-cert-sn-issuer]
az login: error: 'issuer'
```
This is not intuitive. 
This PR exposes the real error …
> {Profile} az login: Refine error message when tenant is not found

- src/azure-cli/azure/cli/command_modules/keyvault/_params.py
The service team will disable the ability for users to disable soft delete, which will be always on.
Add deprecate info for `--enable_soft_delete` in this sprint first.
---
> {KeyVault} Add deprecate info for --enable-soft-delete

- src/azure-cli/azure/cli/command_modules/backup/custom_afs.py
Improving AFS container/item discovery experience
* Now Discover protection containers only when it's not already registered/discovered.
* Trigger item inquiry only if it is not already discovered.
az backup protection enable-for-azurefileshare --azure-file-share fileShareName -p policyName --storage-account stAccName -g resourceGroupName -v vaultName
---
- [Yes] The PR title and description has followed the guideline in [Submitting Pull …
> [Backup] Trigger AFS container/item discovery only when needed

- src/azure-cli/azure/cli/command_modules/appservice/_create_util.py
Fixes #14306 
When deploying python apps through `az webapp up`, don't include .env(dotenv) files since they usually contain secrets. 
Clone test app: https://github.com/Azure-Samples/python-docs-hello-world
Go into cloned directory
Add a .env file(s) anywhere in the directory
Run `az webapp up -n WebappName`
Expect: .env files are not included in the zip deploy
---
> {App Service} Bugfix: When deploying python apps, avoid deploying .env file

- doc/authoring_command_modules/README.md
- doc/authoring_command_modules/authoring_commands.md
- doc/configuring_your_machine.md
- doc/debug/debug_in_vs_code.md
- doc/extensions/authoring.md
- doc/install_troubleshooting.md
- doc/onboarding_guide.md
- doc/private_endpoint_connection_command_guideline.md
- doc/use_cli_with_git_bash.md
- doc/version_management.md
Fix typos under `/doc` folder.
> {Docs} Fix typos under /doc folder

- .gitattributes
- build_scripts/windows/scripts/build.cmd
- build_scripts/windows/scripts/setup_msi_test.ps1
- build_scripts/windows/scripts/test_msi_package.py
- src/azure-cli-core/azure/cli/core/tests/test_generic_update.py
- src/azure-cli/azure/cli/command_modules/ams/tests/latest/test_ams_sp_scenarios.py
- src/azure-cli/azure/cli/command_modules/ams/tests/latest/test_ams_streaming_endpoint_scenarios.py
1. Use [embeddable Python](https://docs.python.org/3/using/windows.html#windows-embeddable) + pip to reduce the size of the bundled Python in MSI.
2. Add a script to test MSI package. The test is not added to CI as it needs Admin Permission to set up(#9270). For now it can be run on a local machine when there's major changes in MSI packaging. 
---
> {Packaging/MSI} Use embeddable python for MSI

- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/operations/file.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_share_rm_with_access_tier.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_file_rm_scenarios.py
Support access tier in file share
Today, Azure Files has two tiers: premium, which are served out of the FileStorage storage accounts, and standard, which are served out of general purpose version 2 (GPv2) and general purpose version 1 (GPv1) storage accounts. With this new feature, we're adding two additional new tiers, Hot and Cool, that will be offered from the "standard" (also referred to as "XStore" hardware). Because the Hot and Cool are standard tiers, the existing "standard" tier will be rebranded Transaction Optimized. This means Azure Files will have 4 tiers: 
Tier name | Supported storage account types | Physical storage hardware
-- | -- | --
Premium | FileStorage | StorageFAST   (sometimes called XIO)
Transaction   Optimized | GPv2 and GPv1 | XStore
Hot | …
> [Storage] `az storage share-rm create/update`: add --access-tier to support access tier

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
Fixes #13282, #14055 
Use a better error message string: Explicitly tell user to use --linux flag, to not confuse users
---
> [App Service]: Fix #1382, #14055: Updating error messages for az webapp create and az webapp config container set

- src/azure-cli/azure/cli/command_modules/lab/validators.py
Current documentation marks this as a naive UTC date. 
`az lab vm create --lab-name {LabName} -g {ResourceGroup} --name {VMName} --image "Ubuntu Server 16.04 LTS" --image-type gallery --expiration-date {YYYY-MM-DDThh:mm:ss}`
* current datetime +2 hours
* vm should be created without error
[Component Name 1] Fix #7904: az lab vm create: Fix date validation
---
> [Lab] Fix for issue #7904 date validation bug in lab vm creation

- src/azure-cli-core/azure/cli/core/_profile.py
Fix #14309
Not all clouds have all the cloud endpoints, the previous code may throw `endpoint is not set but is used` error.
For local tests, you can simply set the `sql_management` to `None` for `AzureCloud` in `cloud.py` and run `az ad sp create-for-rbac`. Without this PR, you will see the error described in #14309. After this PR, the error is gone.
---
> {Profile} Fix cloud endpoint not set error

- src/azure-cli/azure/cli/command_modules/extension/__init__.py
- src/azure-cli/azure/cli/command_modules/extension/custom.py
Previously, the command table of `extension` module uses methods from core, but these methods are meant to be shared in other places as well. Corresponding methods are also defined in `custom.py` but not used. Modification of the core methods could impact the command interface without intention.
We should use the methods in `custom.py` in command mapping and modify these methods when we want to change the command interface.
Run any existing extension commands and there should be no regression.
--- …
> {Extension} Fix extension command mapping

- src/azure-cli/azure/cli/command_modules/acs/_help.py
The Virtual Node add-on for AKS was still listed as preview even though it's been GA for some time.
---
> [AKS] Remove preview tag from Virtual Node add-on

- src/azure-cli/azure/cli/command_modules/monitor/actions.py
antlr4 python bindings are scarcely available, so restrict the
import scope to avoid breaking commands that do not need it
when it is not available
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962952
> {Monitor} restrict antlr4 import scope

- src/azure-cli/azure/cli/command_modules/appservice/_appservice_utils.py
- src/azure-cli/azure/cli/command_modules/appservice/_client_factory.py
- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/commands.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tunnel.py
The create-remote-connection and ssh webapp commands are very useful when debugging a poorly running app. However sometimes it is important to be connected to a specific instances. For example, if one instance is responding slower than another, debugging that specific instance is critical even though they should be identical in every way.
This pull request implements a new webapp command `webapp list-instances` and add the `--instance` parameter to ssh and create-remote-connection.
~~One aspect not resolved is when listing instances of a slot, the API version 2019-08-01 does not return a value. This is something specific to that API call and not a fault of the azure-cli codebase.~~
Edit: I forcefully target API version 2018-02-01 when querying the instance information …
> [App Service] Implement webapp list-instances and per-instance SSH and remote connections

- src/azure-cli/azure/cli/command_modules/role/_params.py
- src/azure-cli/azure/cli/command_modules/role/custom.py
- src/azure-cli/azure/cli/command_modules/role/tests/latest/recordings/test_graph_group_scenario.yaml
- src/azure-cli/azure/cli/command_modules/role/tests/latest/test_graph.py
This PR is to fix #13574 
Previously, the user can't specify description for a group when run `az ad group create`. This PR is to add support for this new parameter.
`az ad group create --display-name testgroupxxj --mail-nickname testgroupxxj --description "I am a description"`
>{
"deletionTimestamp": null,
"description": "I am a description",
"dirSyncEnabled": null,
"displayName": "testgroupxxj",
"lastDirSyncTime": null,
"mail": null,
"mailEnabled": false,
"mailNickname": "testgroupxxj",
"objectId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
"objectType": "Group",
"odata.metadata": "https://graph.windows.net/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/$metadata#directoryObjects/@Element",
"odata.type": "Microsoft.DirectoryServices.Group", …
> [RBAC] az ad group create: support specify description when creating a group

- src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_disk_access_private_endpoint.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
**Backgroud** 
Feature Request: CLI Support for private links of managed disks #13917 
This PR is a part of supporting private links for managed disks. Private links for managed disks is a little different from the already supported private links in CLI (e.g, keyvault). It use the disk-access as an intermediate resource rather than connect with the target resource directly. Therefore, to support the private links for managed disks, we have to do the following things. This PR works to support the third step. 
> 1. Support CURD of the new resource disk-access
> 2. Support create/update a disk/snapshot to associate it a disk-access resource
> 3. **Support private links for managed disks**
This PR provides support for:
1. `az network private-link-resource list` for --type …
> [Network] Support private link for managed disks

- src/azure-cli/azure/cli/command_modules/acr/commands.py
- src/azure-cli/azure/cli/command_modules/ams/commands.py
- src/azure-cli/azure/cli/command_modules/appconfig/commands.py
- src/azure-cli/azure/cli/command_modules/appservice/commands.py
- src/azure-cli/azure/cli/command_modules/batch/commands.py
- src/azure-cli/azure/cli/command_modules/botservice/commands.py
- src/azure-cli/azure/cli/command_modules/cognitiveservices/commands.py
- src/azure-cli/azure/cli/command_modules/configure/commands.py
- src/azure-cli/azure/cli/command_modules/cosmosdb/commands.py
- src/azure-cli/azure/cli/command_modules/deploymentmanager/commands.py
- src/azure-cli/azure/cli/command_modules/deploymentmanager/tests/latest/test_deploymentmanager_scenario.py
- src/azure-cli/azure/cli/command_modules/iot/commands.py
- src/azure-cli/azure/cli/command_modules/iotcentral/commands.py
- src/azure-cli/azure/cli/command_modules/managedservices/commands.py
- src/azure-cli/azure/cli/command_modules/monitor/commands.py
- src/azure-cli/azure/cli/command_modules/network/commands.py
- src/azure-cli/azure/cli/command_modules/policyinsights/commands.py
- src/azure-cli/azure/cli/command_modules/redis/commands.py
- src/azure-cli/azure/cli/command_modules/role/commands.py
- src/azure-cli/azure/cli/command_modules/security/commands.py
- src/azure-cli/azure/cli/command_modules/sql/commands.py
- src/azure-cli/azure/cli/command_modules/sqlvm/commands.py
- src/azure-cli/azure/cli/command_modules/storage/commands.py
- src/azure-cli/azure/cli/command_modules/storage/commands_azure_stack.py
- src/azure-cli/azure/cli/command_modules/vm/commands.py
`show` command should use `show_command` or `custom_show_command`.
Compared to `command` and `custom_command`, `show_command` and `custom_show_command` have extra error handler which should be harmless.
> {Linter} replace command with show comamnd and custom command with custom show command

- src/azure-cli/azure/cli/command_modules/role/custom.py
This PR is to fix #13610 
Currently, if the role definition is below json:
>{
"Name": "ACS Resource Provider",
"IsCustom": true,
"Description": "Act as the Azure Communication Services resource provider service",
"Actions": [
"Microsoft.Communication/*/read"
],
"NotActions": [],
"DataActions": [],
"NotDataActions": [],
"AssignableScopes": []
}
CLI will throw an exception and print the stack trace out directly.
The code actually has a check for `AssignableScopes`, however not handle the empty array case.
This fix is just add check for this case.
1. create a json file which has above content, call it `role.json` under current workspace.
2. run `az role definition create --role-deifnition ./role.json`
Expected output:
>please provide 'assignableScopes' …
> [RBAC] az role definition create: print human readable message instead of exception when assignableScope is an empty array

- src/azure-cli/azure/cli/command_modules/role/_help.py
- src/azure-cli/azure/cli/command_modules/role/custom.py
This PR is to fix #13312 
Currently, if user use `az ad sp create-for-rbac --name <name> --create-cert` to generate a cert(.pem) file, the default mod for this file is 644, which is global readable.
This PR is to update the default mod from 644 to 600.
`az ad sp create-for-rbac --name <name> --create-cert` 
> check the mod of created cert file(usually under your home folder, file name example: tmpfdqsp0jg.pem)
---
> [RBAC] BREAKING CHANGE: az ad sp create-for-rbac: change default permission of created certificate

- src/azure-cli/azure/cli/command_modules/appservice/resources/WebappRuntimeStacks.json
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_win_webapp_quick_create_runtime.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Fixes #14758 
az webapp create fails when creating a windows app using a dotnetcore runtime.
- Create windows ASP:
`az appservice plan create -g RG -n Plan`
- Create dotnetcore webapp --runtime "DOTNETCORE|2.1" or "DOTNETCORE|3.1":
`az webapp create -g RG -p Plan -n Name --runtime "DOTNETCORE|3.1"`
Command fails with unexpected error: cli.azure.cli.core.util : 'configs'. Command should have worked successfully
---
> [App Service] Fix #14758: az webapp create errors when creating windows app with --runtime dotnetcore

- scripts/release/rpm/test_rpm_in_docker.sh
The yum package test in `centos8` docker failed because of `gcc` not found, probably caused by a recent update of the image. This PR installs `gcc` during test setup.
Tested in the `build_test` branch: https://github.com/Azure/azure-cli/runs/992224152
---
> {CI} Fix yum package test failure caused by gcc not found

- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/_validators.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
This is the same change brought by: https://github.com/Azure/azure-cli-extensions/pull/2068
This validation is outdated and is done on the backend so there's no point keep this check in CLI.
Closes https://github.com/Azure/azure-cli/issues/12723
---
> [AKS] Remove max pods validation from CLI and let preflight handle it

- src/azure-cli/azure/cli/command_modules/acs/_help.py
Virtual Node is not available as an add-on at cluster creation time.
Source: https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/custom.py#L2578
Trying to create an AKS cluster with Virtual Node:
az aks create -n clusterName -g rgName -l westeurope --enable-addon virtual-node --network-plugin azure
Error message: `"virtual-node" is not recognized by the --enable-addons argument.`
---
> [AKS] Fixing add-ons available in the help message in 'az aks create'

- src/azure-cli/azure/cli/command_modules/hdinsight/_help.py
- src/azure-cli/azure/cli/command_modules/hdinsight/_params.py
- src/azure-cli/azure/cli/command_modules/hdinsight/custom.py
- src/azure-cli/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_cluster_with_encryption_at_host.yaml
- src/azure-cli/azure/cli/command_modules/hdinsight/tests/latest/test_hdinsight_commands.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
This PR adds a new parameter "encryption_at_host" to the cmdlet `az hdinsight create`.
It allows customer to create a cluster with encryption at host feature by running `az hdinsight create .. --encryption-at-host true`
---
> [HDInsight] Support creating cluster with encryption at host

- src/azure-cli/azure/cli/command_modules/appservice/_constants.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
This PR removed the ability to create V2 function apps in specific regions because those regions don't support it. This is an important requirement
[AppService] functionapp create: Removed ability to create 2.x Functions in regions that don't support it
---
> [AppService] functionapp: Removed ability to create 2.x Functions in regions that don't support it

- src/azure-cli/azure/cli/command_modules/role/_help.py
This bug is to fix #13970 .
This is a simple PR, just add a message to indicate what is the default value for `--force-change-password-next-login`.
`az ad user create -h`
>--force-change-password-next-login :
Marks this user as needing to update their password the next time they authenticate. **If omitted, false will be used.**  Allowed values: false, true.
---
> {RBAC} az ad user create: refine --force-change-password-next-login help message

- src/azure-cli/azure/cli/command_modules/cloud/_help.py
- src/azure-cli/azure/cli/command_modules/cloud/custom.py
Resolve #14653
Support registering clouds using the output format of `az cloud show`.
Fix the for loop that modifies the dict. 
Run command `az cloud register -n test --cloud-config @"cloud.json"`
With this PR, it should work with the following 2 formats for `cloud.json`:
```
{
"endpointResourceManager": "https://management.usgovcloudapi.net/",
"endpointActiveDirectory": "https://login.microsoftonline.us",
"suffixAcrLoginServerEndpoint": ".azurecr.us",
"suffixKeyvaultDns": ".vault.usgovcloudapi.net"
}
```
```
{
"endpoint":{
"resourceManager": "https://management.usgovcloudapi.net/",
"activeDirectory": "https://login.microsoftonline.us"
},
"suffix":{
"acrLoginServerEndpoint": ".azurecr.us",
"keyvaultDns": ".vault.usgovcloudapi.net"
}
}
```
Or you can …
> [Cloud] az cloud register: Fix registering clouds with a config file

- src/azure-cli/azure/cli/command_modules/network/_help.py
This PR is to add an example to clarify the backend authentication certificate format returned by the `az network application-gateway auth-cert show` command. The certificate is in Base-64 encoded X.509(.CER) format. The current documentation or help does not mention this anywhere. This is needed for scenarios where we need to retrieve details from the certificate like expiry date etc. Without this information, we have to try different options with the raw data which is returned to get the correct format. 
Adding this example should help clarify the certificate format.
Details with example are in https://github.com/Azure/azure-cli/issues/14522
[Component …
> [Network] `az network application-gateway auth-cert show`: Add example to demonstrate certificate format

- src/azure-cli/azure/cli/command_modules/container/_params.py
This PR updates the help text for `ports` parameter users can specify when using `az container create` 
`az container create -h`
--
> [Container] Fix #6235 update help text for ports parameter in container create

- src/azure-cli-core/azure/cli/core/cloud.py
Add endpoint and suffix for Attestation.
This endpoint will be used in extension Attestation for multi-clouds support: [code](https://github.com/Azure/azure-cli-extensions/blob/8acc80f0c7936a9420bb04672372d0e8c2b8b8cd/src/attestation/azext_attestation/generated/_client_factory.py#L28)
---
> {Core} Add endpoint and suffix for attestation

- azure-pipelines.yml
- scripts/release/debian/test_deb_in_docker.sh
- scripts/release/debian/test_deb_package.py
The Debian package test will be triggered when a PR is merged. 
Refactored the pipeline to use matrix for building debian packages and testing.
Tested in build_test branch: https://dev.azure.com/azure-sdk/public/_build/results?buildId=503495&view=logs&jobId=0ef655ab-0cb9-5a1f-5cf7-70179a0ca9a8&j=91b655fa-e277-54b4-6e7f-39b6e68dea4d
---
> {CI} Add Debian package test

- azure-pipelines.yml
- scripts/release/homebrew/test_homebrew_package.py
Sometimes, when ADO resources are limit in the evening, homebrew package test may fail because of timeout. Extend this value to 3 hours.
Also remove monitor module from parallel running list.
ADO tasks should be passed.
---
> {Package} extend homebrew package test timeout value

- src/azure-cli/azure/cli/command_modules/storage/_validators.py
- src/azure-cli/azure/cli/command_modules/storage/_validators_azure_stack.py
Noticed a typo when running `az storage container create --account-name {} -n {}`
I"m not sure about what triggers both validators, but one can be tested by running `az storage container list --account-name 'STORAGE_ACCOUNT_NAME'` without any environment variables that are listed in `az storage container list --help` to get the warning
[Storage] az storage container: Fix language in logging.warning call
---
> {Storage} `az storage container`: Fix language in logging.warning call

- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/_template_builder.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_appgw_creation_with_public_and_private_ip.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Fix https://github.com/Azure/azure-cli/issues/14494
Fix https://github.com/Azure/azure-cli/issues/14748
Meanwhile, considering there is a quick action to enbale one private link for one IP configuration, I choose to enable it on the public one if public and private IP are provided to not to break existing behavior
---
> [Network] BREAKING CHANGE: Allow to create both public and private IP while creating an Application Gateway

- .azure-pipelines/templates/azdev_setup.yml
- pylintrc
- src/azure-cli/azure/cli/command_modules/appservice/commands.py
- src/azure-cli/azure/cli/command_modules/configure/commands.py
- src/azure-cli/azure/cli/command_modules/hdinsight/commands.py
- src/azure-cli/azure/cli/command_modules/vm/commands.py
`az configure show`, `az cache show` or `az vm monitor show` is not a real show command.
`az functionapp function show` has its own error handler logic
> {CI} Example of bypassing show-command linter rule

- src/azure-cli/azure/cli/command_modules/acs/custom.py
fix: aks cluster create issue mentioned here: https://github.com/Azure/azure-cli/pull/14688#discussion_r476665073
```
`>az aks create -g vsoto-aks-aad-test-rg -n vsoto-aks-aad-test --enable-aad --aad-admin-group-object-id <>
Finished service principal creation[##################################] 100.0000%Property id '' at path 'properties.diskEncryptionSetID' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.
az --version
azure-cli 2.11.0
core 2.11.0
telemetry 1.0.5
Extensions:
azure-devops 0.11.0`
``` …
> [AKS] fix: aks cluster create issue

- src/azure-cli/azure/cli/command_modules/cognitiveservices/custom.py
- src/azure-cli/azure/cli/command_modules/cognitiveservices/tests/latest/test_cognitiveservices_command.py
- src/azure-cli/azure/cli/command_modules/cognitiveservices/tests/latest/test_custom_domain.py
- src/azure-cli/azure/cli/command_modules/cognitiveservices/tests/latest/test_network_rules.py
Show additional legal term for certain APIs
When creating face api, it should show a special legal term.
[Cognitive Services] az cognitiveservices account create: show additional legal term for certain APIs
---
> [Cognitive Services] BREAKING CHANGE: Show additional legal term for certain APIs

- scripts/release/generate_history_notes.py
The script now only checks the content below **History Notes** in PR description for history notes.
It tries to make future component names consistent and more human-readable by comparing historical component names and using customized settings.
To test locally:
`PRE_VERSION=${PRE_VERSION} PAT_TOKEN=${PAT_TOKEN} python scripts/release/generate_history_notes.py`
`PRE_VERSION` is the last version of Azure CLI in the source code. `PAT_TOKEN` is a Github PAT token.
---
> {History} Fix history notes in PR description and optimize component name

- src/azure-cli/azure/cli/command_modules/iot/commands.py
Deprecating command **az iot hub show-connection-string**
Now, we have another command group for connection-string from IoT-Extension that can use instead
---
> [IoT Hub] Deprecated 'show-connection-string' command

- src/azure-cli-core/azure/cli/core/_msal.py
Currently if the `get_msal_token` function fails, it will only print an error "invalid_grant", which is not enough to guide user to do further actions. This PR is to print the error details of it.
Need to test via vmssh extension.
1. install vmssh extension
2. setup vmssh feature in portal
3. configure condition access for a particular VM
4. connect to the VM
current behavior: 
>invalid_grant
expected behavior: 
>Get token failed. invalid_grant: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'ce6ff14a-7fdc-4685-bbe0-f6afdfcfa8e0'.
Trace ID: 0afea3cd-00af-406b-bbd0-959d217f0b00
Correlation ID: ff9bb588-aee5-4f22-9b02-005d98dbe197 …
> {Core} Print error details if fail to get msal token

- src/azure-cli/azure/cli/command_modules/acs/custom.py
Fix bug #13846
Run `az aks get-credentials --resource-group <rg> --name <name>` on an AKS cluster while your local kubeconfig is empty:
```
$ kubectl config view
apiVersion: v1
clusters: null
contexts: null
current-context: ""
kind: Config
preferences: {}
users: null
```
---
> [AKS] CLI should tolerate empty kubeconfig

- scripts/release/debian/test_deb_package.py
- scripts/release/homebrew/test_homebrew_package.py
- scripts/release/rpm/test_rpm_package.py
- src/azure-cli/azure/cli/command_modules/cloud/tests/latest/test_cloud.py
When running cloud tests in parallel, it may fail to revert to the original cloud settings. The tests relies on `setup()` to get the original active cloud and `tearDown()` to set back to the original cloud. But when running in parallel, if the original cloud is A, it is possible that process 1 runs a test to set to cloud B, then process 2 begins and treats cloud B as the original cloud in enviroment. Process 1 finishes and set the cloud back to A, process 2 finishes and set the cloud back to B. Now the cloud of the environemnt changes from cloud A to cloud B. This will cause issues with other tests running afterwards.
This PR modifies package tests to run cloud tests in serial and add `serial_test` mark to run in serial in live test pipeline. …
> {Test} Fix cloud tests

- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/utils.py
Adding support for PremiumV3 pricing tier
`appservice plan create --location westus --resource-group my-resource-group --name -my-new-app-service-plan --sku P1v3`
P1V3 => Premium V3 Small
P2V3 => Premium V3 Medium
P3V3 => Premium V3 Large
---
> [App Service] Add support for Premium V3 pricing tier

- src/azure-cli-core/azure/cli/core/util.py
Print traceback to debug log when `azure.cli.core.util.handle_exception` is called. This can help identify where the exception is generated and thrown.
Notice the location `westu` is wrong (should be `westus`):
```
> az group create -n rg1 -l westu --debug
...
azure.cli.core.util.handle_exception is called with an exception:
File "D:\cli\env38\lib\site-packages\knack\cli.py", line 215, in invoke
File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 654, in execute
raise ex
File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 718, in _run_jobs_serially
File …
```
> {Core} Print traceback to debug log when handle_exception is called

- src/azure-cli/azure/cli/command_modules/monitor/_exception_handler.py
- src/azure-cli/azure/cli/command_modules/monitor/_help.py
> [Monitor] az monitor log-analytics workspace linked-storage: expose detailed error message to customers

- src/azure-cli/azure/cli/command_modules/resource/_formatters.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_formatters.py
The PR contains a minor tweak for the `az deployment group/sub/mg/tenant what-if` commands to let them show "Ignore" resource changes last in outputs (addresses https://github.com/Azure/arm-template-whatif/issues/115).
Before the change:
After the change:
```
az deployment group/sub/mg/tenant what-if -m <mg_id> -f <path_to_deployment_file> -l <location>
az deployment group/sub/mg/tenant create -m <mg_id> -f <path_to_deployment_file> -l <location> -c
```
---
> [ARM] az deployment group/sub/mg/tenant what-if: Show "Ignore" resource changes last

- src/azure-cli/azure/cli/command_modules/vm/_validators.py
This PR fix issue #14897. 
**Before**
When creating a vm with an invalid admin password, the message shows only the current rule the password violates. When user changes the password and try it again, another error may happen showing that the user violates anthoer rule.
**After**
This PR improves the behavior by displaying all the requirements once we found the password is invalid. 
**Before**
```
Admin Password:
Confirm Admin Password:
The password length must be between 12 and 123
Admin Password:
Confirm Admin Password:
Password must have the 3 of the following: 1 lower case character, 1 upper case character, 1 number and 1 special character
```
**After**
```
Your password is invalid for it violates Rule 1
Rule 1: The password length must be …
```
> {VM} Fix #14897: display all requirements for vm admin password when it's invalid

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_custom.py
Azurepolicy addon was supported in AKS through extensions as of now. Since this addon is planned for GA, adding to azure-cli official repo.
az aks create -g <rg> -n <rn> -a azure-policy 
az aks enable-addons -g <rg> -n <rn> -a azure-policy
azure cli extensions PR - https://github.com/Azure/azure-cli-extensions/pull/651/files
---
> [AKS] Support azure policy addon in azure-cli

- src/azure-cli/azure/cli/command_modules/role/_help.py
This PR fix the examples text of `az role definition create` and `az role definition update`. We provide one example using a big JSON string as the value of role-definition argument. As the backslash in a JSON will cause a failure when the JSON is quoted by single quotes. So the backslashes are removed.
examples text before:
```sh
az role definition create -h                                                                   
Command
az role definition create : Create a custom role definition.
Arguments
--role-definition [Required] : Description of a role as JSON, or a path to a file containing a
JSON description.
--debug                      : Increase logging verbosity to show all debug logs.
--help -h                    : Show this …
```
> {Role} az role definition create/update -h: fix the examples text

- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_custom.py
Customer reported dashboard addon can't be disabled. The root cause is in L2359 the select from dict is not case insensitive, so that 2 addon profiles of dashboard with different keys will be added to the addon_profiles and sent in the request.
az aks disable-addons --addons kube-dashboard -g eastus -n testCluster
[AKS] Fixed case sensitive issue for AKS dashboard addon
---
> [AKS] Fixed case sensitive issue for AKS dashboard addon

- src/azure-cli-core/azure/cli/core/adal_authentication.py
Fix issue #15051 
With azure.core, all get_token method will need two addition arguments: *scope and **kwargs.
Here is a fix for msi login.
---
> [Core] Fix issue 15051 for msi login issue in azure.core

- src/azure-cli-core/azure/cli/core/extension/_resolve.py
- src/azure-cli-core/azure/cli/core/extension/operations.py
- src/azure-cli-core/azure/cli/core/parser.py
- src/azure-cli/azure/cli/command_modules/extension/__init__.py
- src/azure-cli/azure/cli/command_modules/extension/_help.py
- src/azure-cli/azure/cli/command_modules/extension/custom.py
Resolve #13930
This PR makes it possible to use `az extension add --upgrade` to install or update an extension. The behavior of `az extension add`(without `--upgrade`) will not change.
**When the extension is not installed**:(the behavior is the same as not providing `--upgrade` option)
`az extension add --upgrade -n anext` will install the latest version of `anext`.
`az extension add --upgrade -n anext --version aversion` will install the specific version of `anext`.
**If the extension is already installed**:
`az extension add --upgrade -n anext` will try to update the extension to the latest version if available.
`az extension add --upgrade -n anext --version aversion` will override the existing version if the specified version is different from it. Otherwise, it …
> [Extension] az extension add: Add --upgrade option to update the extension if already installed

- src/azure-cli/azure/cli/command_modules/profile/custom.py
- src/azure-cli/azure/cli/command_modules/profile/tests/latest/test_profile_custom.py
Inspired by https://github.com/Azure/azure-cli/pull/14718. Fix: `test_get_raw_token` fails on non-UTC machine.
The test `test_get_raw_token` was introduced in #14128.
When using `az account get-access-token` for managed identity, `expiresOn` will be converted from POSIX to datetime in **local timezone**. For example, `1593497681` is converted to 
- `2020-06-30 06:14:41.000000` on a UTC machine
- `2020-06-30 14:14:41.000000` on a UTC+8 machine
The test `test_get_raw_token fails` is written for a UTC machine on DevOps and this test will fail on a non-UTC machine (such as UTC+8).
This PR patches `fromtimestamp` with `utcfromtimestamp` to force `expiresOn` to be converted to UTC to make the test pass on any machine.
> {Profile} Fix: test_get_raw_token fails on non-UTC machine

- src/azure-cli/azure/cli/command_modules/synapse/_help.py
Changed 'myuser@consoso.com' in example provided for commands az synapse role assignment create and delete commands.
> [Synapse] Fixed typo in example of az synapse role assignment create and delete 

- src/azure-cli-core/azure/cli/core/_profile.py
Update comment to be more accurate, as requested by ARM service team: `home_tenant_id` and `managed_by_tenants` are properties _in_ and _after_ `2019-06-01`, not only limited to `2019-06-01`.
> {Profile} Update comment to be more accurate

- src/azure-cli/azure/cli/command_modules/acr/_archive_utils.py
There is currently no way to specify (or override) the .dockerignore file in the acr build command. This prevents multiple Dockerfile(s) to share the same context effectively.
This change allows different Dockerfiles to define different subsets of the context files with different ignore rules.
In case the docker file is not named Dockerfile, the frontend (i.e. acr build) first checks for <path/to/docker_file_name>.dockerignore and if it is found it will be used instead of the root .dockerignore.
This is consistent with the docker behaviour implemented in:
moby/buildkit#901
For more information see the related issue #14811 
No command changes. This PR affects the `acr build` command, when the `-f <docker_file_name>` option is used.  …
> [acr] Fix #14811 Add support for dockerignore override

- src/azure-cli/azure/cli/command_modules/storage/_params.py
In PR , we remove `az storage account create` and previous `--hierarchical-namespace` will be removed. But it is support in main cli with argument `--hns`.
Here is to add `--hierarchical-namespace` option for `az storage account create` command to not break previous customer.
---
> {Storage} `az storage account create`: add one more option for --hns 

- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/util.py
Make the instruction of using `az upgrade` only displayed when there is update for `azure-cli` package to prevent issues like #15133.
This PR also deprecates the `_update_latest_from_pypi` method which uses fuzzy match in package name and package description to search for `azure-cli` in pypi. Lots of packages that contain `azure-cli` in name or in description are returned. So this method is slow. This PR replaces it with `_update_latest_from_github` which searches for the latest versions on Github master branch. Legacy module packages installed before such as `azure-cli-vm` will no longer be listed in `az --version`.
Comparison of `azdev perf benchmark "az --version" --runs 10`:
Before:
```
[
{
"Avg": 3.8947,
"Command": "az --version",
"Max": 4.4901,
"Media": 4.3117, …
```
> {Version} Only show az upgrade instruction when update for azure-cli is available

- src/azure-cli-core/azure/cli/core/telemetry.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
SessionId is used to help us identify whether the users are running their CLI commands in the same terminal. It can help us analysis the user behavior, by which we may be able to cluster the commands and improve CLI error rate measurement. It may also help us separate interactive users from automation scripts.
This PR 
- adds session id  for telemetry
- adds package psutil as azure-cli dependency (except for cygwin)
**Note**
The package **psutil** was remove from CLI dependencies in #11665 because of cygwin incompatibility. In this PR, we reintroduce the package and provide a workaround to avoid installing it in cygwin.
**Known Issue**
For automation script, the sessionIDs of the commands in script will be the same except for the first command. It only occurs on …
> {Core} Add SessionId for telemetry

- src/azure-cli-core/azure/cli/core/commands/query_examples.py
- src/azure-cli-core/azure/cli/core/tests/test_query_examples.py
This PR fix the bug when parsing a JSON with an array in a dict, there is an extra dot in the examples.
For examples, given the JSON as following
```json
{
"list": [
{ "name": "item1" },
{ "name": "item2" },
]
}
```
We may generate the wrong examples such as `.list[?name='item1']`. This PR fix the wrong dot. And this PR will generate the correct examples such as `list[?name='item1']`.
This PR also provide an extra unit test to test this situation.
* Scenario Test
Most `show` commands returns a JSON dict which can be used for test.
```bash
$ az account show --query-examples
Query string                                                             Help
----------------------------------------------------------------------- …
```
> {Core} Fix query-examples bug: extra dot when parsing a JSON with an array in a dict.

- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
Temporarily mark HSM related tests as `record_only` to improve the live test pass rate, because these tests are based on a hardcoded HSM instance, which can be only accessed via my personal account.
Currently, only one HSM instance can be created within a subscription, if one day there is no more quota limitation, I will remove these `record_only` decorators.
---
> {KeyVault} Mark HSM related tests as `record_only`

- src/azure-cli/azure/cli/command_modules/network/_help.py
Fix https://github.com/Azure/azure-cli/issues/14132
`az network application-gateway ssl-cert show` is used to display the SSL certificates of an application gateway. There is no information or examples provided in the help or documentation which mentions the format of the certificate returned or ways to extract information from the certificate like expiry date etc. This PR is add an example to demonstrate the certificate format and fetch the expiry date of the certificate.
The details of the PR and tests/confirmation of the example being added have been discussed in https://github.com/Azure/azure-cli/issues/14132. The certificate information returned is in `PKCS7` format which needs to be converted appropriately and information retrieved from it.
> [Network] `az network application-gateway ssl-cert show`: Add example to demonstrate certificate format and fetch information

- src/azure-cli/setup.py
azure-mgmt-keyvault 7.0.0 has a breaking change due to codegen change, this breaks our CLI:
`TypeError: __init__() missing 1 required keyword-only argument: 'family'`
Lock the version in `setup.py` to avoid the effect.
---
> {KeyVault} Hotfix: Lock the SDK version

- src/azure-cli/azure/cli/command_modules/network/commands.py
As email indicates, the waf-config is not deprecated.
---
> {Network} application-gateway waf-config: Remove deprecation info

- src/azure-cli/azure/cli/command_modules/hdinsight/_params.py
Add deprecation info for argument public_networrk_access_type and outbound_only_public_network_access_type
[HDInsight] : az hdinsight create: add deprecate information for argument --public-networrk-access-type and --outbound-public-network-access-type
---
> [HDInsight] Add deprecation info to old private link's arguments

- src/azure-cli/azure/cli/command_modules/appservice/_create_util.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
Fixes #15202 
Better error messages around the AppService commands
- run `az webapp up -n webappName` in a directory that isn't source code
Better error msg:
- run `az webapp up -n webappName` without administrator privileges in a directory in C:
Better error msg:
---
> [AppService] Bugfix: Better error messages for webapp commands

- scripts/release/homebrew/docker/run.sh
We update the build method to template when doing PEP420. Now it's time to rollback to original `update_existing`.
---
> {Package} Rollback homebrew build method to update_existing

- src/azure-cli/azure/cli/command_modules/acr/commands.py
Update region url to use non-regional aka.ms links 
Before : 
```
az acr helm --help
Group
az acr helm : Manage helm charts for Azure Container Registries.
This command group has been deprecated and will be removed in future release. Use 'helm
v3' instead. For more information go to https://docs.microsoft.com/en-us/azure/container-
registry/container-registry-helm-repos
```
After: 
```
az acr helm --help
Group
az acr helm : Manage helm charts for Azure Container Registries.
This command group has been deprecated and will be removed in future release. Use 'helm
v3' instead. For more information go to https://aka.ms/acr/helm
```
[ACR] NON-BREAKING: az acr helm - deprecation url upate
--- …
> [ACR] Fix helm url with non-regional aka.ms link

- src/azure-cli-core/azure/cli/core/cloud.py
- src/azure-cli/azure/cli/command_modules/keyvault/_validators.py
> {KeyVault} Fix CloudSuffixNotSetException while using `az keyvault` in Azure Stack and Air-Gaped Cloud

- src/azure-cli/azure/cli/command_modules/keyvault/__init__.py
- src/azure-cli/azure/cli/command_modules/keyvault/_client_factory.py
- src/azure-cli/azure/cli/command_modules/keyvault/_command_type.py
- src/azure-cli/azure/cli/command_modules/keyvault/_params.py
- src/azure-cli/azure/cli/command_modules/keyvault/_transformers.py
- src/azure-cli/azure/cli/command_modules/keyvault/commands.py
- src/azure-cli/azure/cli/command_modules/keyvault/custom.py
- src/azure-cli/azure/cli/command_modules/keyvault/security_domain/byte_shares.py
- src/azure-cli/azure/cli/command_modules/keyvault/security_domain/jwe.py
- src/azure-cli/azure/cli/command_modules/keyvault/security_domain/shared_secret.py
Fix: #15144 
Using absolute references would benefit our packaging and debugging work.
FYI, PEP 8 states:
> Absolute imports are recommended, as they are usually more readable and tend to be better behaved (or at least give better error messages) if the import system is incorrectly configured (such as when a directory inside a package ends up on sys.path)
---
> {KeyVault} Use absolute references instead of relative references

- src/azure-cli/azure/cli/command_modules/acs/custom.py
Now all clusters <= 1.18 have kube-dashboard addon profile. If one cluster don't have the profile, it means the cluster is 1.19 and should expect the addon be disabled.
Starting from 1.19, enabling kube-dashboard addon is not allowed, so added the error message.
az aks browse -n test-cluster -g test-rg
---
> [AKS] Expect kube-dashboard addon be disabled by default

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_with_ahub.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
This will allow cx to create/update AKS Clusters to enable Azure Hybrid User Benefit (AHUB) for all AKS Windows nodes.
---
> [AKS] az aks create/update: Add LicenseType support for Windows

- scripts/live_test/.gitignore
- scripts/live_test/CLITest.yml
- scripts/live_test/HISTORY.rst
- scripts/live_test/generate_index.py
- scripts/live_test/sendemail.py
- scripts/live_test/test_data.py
* Update pipeline run title.
* Generate index.html of testing results.
* Design a unique representation of a pipeline run.
* Make storage account container public.
* Fix a tiny DB bug.
* Fix pipe not close problem.
---
> {Test} Pipeline update

- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_oauth.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_oauth_track2.py
- src/azure-cli/azure/cli/command_modules/storage/tests/storage_test_util.py
oauth_cmd is widely used in storage test scenarios. Here is removing it in StorageTestMixin class for ease of use.
---
> {Storage} add oauth_cmd in test scenarios

- src/azure-cli/azure/cli/command_modules/rdbms/_flexible_server_util.py
- src/azure-cli/azure/cli/command_modules/rdbms/_params.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_mysql.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_virtual_network.py
- src/azure-cli/azure/cli/command_modules/rdbms/validators.py
This PR is a hotfix candidate for the recent Ignite Train. It includes :
- Changing Vnet Name and subnet name to exclude server name.( to allow servers to be provisioned with HA enabled )
- Change the MySQL default region to West US2 as MySQL Flexservers do not exist in the current default - EASTUS
- Update the connection string in the postgres create instance response.
- Skip adding special characters in the password
- Convert user supplied servername to lower case.
> [RDBMS] Hotfix: `az postgres flexible-server create` : Update VnetName to exclude servername and update default region for MySQL

- src/azure-cli-core/azure/cli/core/cloud.py
- src/azure-cli-core/azure/cli/core/tests/test_cloud.py
- src/azure-cli/azure/cli/command_modules/keyvault/_validators.py
Pick up the changes in #15298 for hotfix release.
---
> {KeyVault} Hotfix: Fix CloudSuffixNotSetException while using `az keyvault` in Azure Stack and Air-Gaped Cloud

- src/azure-cli/azure/cli/command_modules/role/_validators.py
- src/azure-cli/azure/cli/command_modules/role/custom.py
- src/azure-cli/azure/cli/command_modules/role/tests/latest/test_role.py
Fix #15278: `az role assignment delete` will delete all assignments when `--assignee` is empty string
In `az role assignment list/delete`, when `--assignee`, `--scope`, `--role`, `--resource-group` are accidentally provided as an empty string `""` (especially when in a script), they won't take effect when filtering the role assignments, causing all matched role assignments to be listed/deleted. For example,
```
az role assignment delete --assignee ""
```
removes all role assignments under the subscription.
This PR checks whether these arguments are empty strings and throws `CLIError` accordingly.
```
az role assignment list --assignee ""
az role assignment list --scope ""
az role assignment list --role ""
az role assignment list --resource-group ""
az …
```
> [Role] Fix #15278: az role assignment list/delete: Forbid empty string arguments

- src/azure-cli/azure/cli/command_modules/config/custom.py
- src/azure-cli/azure/cli/command_modules/configure/custom.py
Previously when param persist is already on/off, it will raise an CLIError, which does not make sense. Update it to a warning message.
---
> {Config} Change local context on/off error to warning

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_acs_commands.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
The `RoleBasedServicePrincipalPreparer` returns sp name and needs to be turned into Application ID URI for use in aks commands.
---
> {Test} Fix aks tests

- src/azure-cli-core/azure/cli/core/azclierror.py
- src/azure-cli-core/azure/cli/core/commands/__init__.py
- src/azure-cli-core/azure/cli/core/commands/arm.py
- src/azure-cli-core/azure/cli/core/parser.py
- src/azure-cli-core/azure/cli/core/telemetry.py
- src/azure-cli-core/azure/cli/core/tests/test_util.py
- src/azure-cli-core/azure/cli/core/util.py
This PR provides
- New error types for error improvement. A series of error classes are defined to replace the original enumerated error types.
- Adjustments for exception handler in CLI core. The original raw exceptions from different sources are wrapped by the new defiined error types.
Base class: `AzCLIError`
Main-categories: `UserFault`, `ClientError`, `ServiceError`
Sub-categories:
```
class CommandNotFoundError(UserFault):
""" Command is misspelled or not recognized by AzureCLI. """
pass
class UnrecognizedArgumentError(UserFault):
""" Argument is misspelled or not recognized by AzureCLI. """
pass
class RequiredArgumentMissingError(UserFault):
""" Required argument is not specified. """
pass
class ConflictArgumentError(UserFault):
""" Arguments can not be specfied …
```
> {Core} Define new error types

- src/azure-cli/azure/cli/command_modules/network/_params.py
Fix https://github.com/Azure/azure-cli/issues/15135
---
> {Network} private-link-resource list: Update argument help message to make more clear

- src/azure-cli/azure/cli/command_modules/util/custom.py
Fix #15313
When windows users have a `Microsoft.Powershell_profile.ps1` file in their environment, `powershell.exe` will start by loading it and with the default `Restricted` execution policy, an error will be thrown:
```
File C:\Users\***\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1 cannot be loaded because running scripts is disabled on this system. 
For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
```
This PR adds `-NoProfile` the Powershell command for `az upgrade` to skip loading the profile script. …
> {Upgrade} Run powershell cmd with noprofile

- src/azure-cli-core/azure/cli/core/adal_authentication.py
Reported in https://github.com/Azure/azure-cli/issues/15320
If `AdalError` is created directly with
```py
raise AdalError('More than one token matches the criteria. The result is ambiguous.')
```
The original code fails to extract the error message and returns an empty string `''`. Thus, the original error is lost.
> {Core} Extract error message from AdalError

- src/azure-cli/azure/cli/command_modules/network/commands.py
Fix issue in https://dev.azure.com/azure-sdk/public/_build/results?buildId=557475&view=logs&j=b21ded15-2ef6-5c2b-875f-d00fdf573f12&t=293d8450-9e65-5c81-f34e-5d7d70fd3ffc.
The root cause is that for network module, the default resource type is MGMT_NETWORK and it is applied to `az network dns` if no addition specification.
In previous profile, the issue doesn't happen because MGMT_NETWOR api version is lower than 2018-05-11. But in new 2020-09-01-hybrid profile, it is larger than 2018-05-01 and the command will be loaded but there is no such support in SDK, which will cause error as shown in CI. …
> {Network} Fix dns loading issue in azure stack

- src/azure-cli/azure/cli/command_modules/vm/commands.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_update_image.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Resolve https://github.com/Azure/azure-cli/issues/14924
Resolve https://github.com/Azure/azure-cli/issues/15058
Support partial update of vmss to avoid unnecessary permission check.
How to try it. https://github.com/Azure/azure-cli/blob/dev/doc/try_new_features_before_release.md
---
> [Compute] Fix a vmss update, disk attach/detach, extension set/delete issue

- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_custom.py
AKS server treats addon names and addon config keys as case insensitive, and store them in DB as it is in input. For example, we have both `logAnalyticsWorkspaceResourceID` and `loganalyticsworkspaceresourceid` in our DB and both are valid. However, in the public document we're only giving examples of `logAnalyticsWorkspaceResourceID`. 
This change makes Azure CLI always convert the keys to the name defined in Azure CLI. (The name defined in Azure CLI is the same as public document), so that customer get the right name back.
1. Create a AKS cluster.
2. Run `az aks enable-addons -a kube-dashboard -g testrg -n testcluster`
3. The name of kube-dashboard addon name should be change from "KubeDashboard" to "kubeDashboard"
---
This …
> [AKS] Honor addon names defined in Azure CLI

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
Thread.isAlive is removed since Python 3.9
- see https://bugs.python.org/issue37804
- Fixes #15441
```sh
brew install azure-cli
export PATH="$(brew --prefix)/opt/python@3.9/libexec/bin:$PATH"
az webapp create-remote-connection -g {} -n {}
```
> [AppService] Fixes #15441: az webapp create-remote-connection fails with AttributeError: 'Thread' object has no attribute 'isAlive'

- src/azure-cli/azure/cli/command_modules/storage/_validators.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_logging_operations.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
Fix the issue when there is no --version specified, we should fallback to default version.
`az storage logging update --retention 30 --services t --log r`
---
> [Storage] Fix #15111: `az storage logging update` fails without optional argument

- scripts/release/homebrew/docker/formula_template.txt
- scripts/release/homebrew/docker/run.sh
https://github.com/Homebrew/homebrew-core/pull/62253 migrated to Python 3.9 for Azure CLI, but Azure CLI is not compatible with Python 3.9 yet. ADO has not supported Python 3.9 either and it caused failures when testing homebrew formula, which blocked the release of our packages.
This PR updates the homebrew template to sync the changes with Homebrew master branch except that Python is still 3.8 and build the homebrew formula from the template.
Tested the changes in `build_test` branch: https://dev.azure.com/azure-sdk/public/_build/results?buildId=570383&view=results
--- …
> {Homebrew} Hotfix: Build with template to revert to python 3.8

- Dockerfile
Add bash-completion package for auto completion such as kubectl.
`$ docker build .`
---
> [Docker] Add bash-completion to Dockerfile

- README.md
- scripts/release/debian/README.md
- scripts/release/rpm/README.md
- scripts/release/rpm/pipeline.sh
We publish a legacy docker image `microsoft/azure-cli` and a new `mcr.microsoft.com/azure-cli`. Meanwhile we use some docker images to build the Linux packages, these docker images are used only during packaging and not published. But they are using the same name as the published azure-cli images. To avoid confusion, this PR renames the docker images used for packaging.
---
> {Docker} Rename local docker image tag

- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
MSI package building failed in CI caused by building the latest `yarl` and `multidict` packages from source. Details in below [comment](https://github.com/Azure/azure-cli/pull/15508#issuecomment-708127006).
These 2 packages are implicitly downloaded as they are in the dependency tree of `azure-devtools`. `azure-devtools` is only needed for development and testing and should be removed as a dependency in `requirements.txt` for building `azure-cli` packages. The `setup.py` for `azure-cli` does not contain `azure-devtools`.
`yarl` is used in [`storage-blob-preview`](https://github.com/Azure/azure-cli-extensions/blob/master/src/storage-blob-preview/azext_storage_blob_preview/vendored_sdks/azure_storage_blob/v2019_12_12/_shared/authentication.py#L17), but the code has …
> {Packaging} Remove azure-devtools as a dependency

- src/azure-cli/azure/cli/command_modules/profile/__init__.py
`--tenant` has been introduced for almost a year and has been proven to be stable.
Due to the warning message:
> argument --tenant is in preview, it may be removed/changed in a future release
some users are afraid that `--tenant` will be removed in the future (https://github.com/Azure/azure-cli/pull/11798#issuecomment-706841294). 
We can now make it GA to avoid confusion.
> {Account} az account get-access-token: Remove preview tag for --tenant

- scripts/release/homebrew/docker/formula_template.txt
- scripts/release/homebrew/docker/run.sh
Merge fix #15482 back to `dev`.
> {Branch Management} Merge release 2.13.0 back to dev

- src/azure-cli-core/azure/cli/core/__init__.py
Remove `azext_ai_did_you_mean_this` from `ALWAYS_LOADED_EXTENSIONS` as it has been retired (https://github.com/Azure/azure-cli-extensions/pull/2402).
> {Core} Remove azext_ai_did_you_mean_this from ALWAYS_LOADED_EXTENSIONS

- src/azure-cli/azure/cli/command_modules/iot/_help.py
Adding more examples in help documentation to describe what can be updated with "az iot hub update" command
---
> {Iot Hub} Adding more examples in help documentation to describe what can be updated with "az iot hub update" command

- src/azure-cli/azure/cli/command_modules/resource/_formatters.py
- src/azure-cli/azure/cli/command_modules/resource/_params.py
- src/azure-cli/azure/cli/command_modules/resource/commands.py
What-If will go GA this month. The PR removes the `is_preview` flags for the what-if commands and parameters.
```
az deployment group/sub/mg/tenant what-if ...
az deployment group/sub/mg/tenant create --confirm-with-what-if ...
```
---
> [ARM] Make template deployment What-If commands GA

- src/azure-cli/azure/cli/command_modules/backup/custom.py
- src/azure-cli/azure/cli/command_modules/backup/custom_base.py
- src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_policy.yaml
- src/azure-cli/azure/cli/command_modules/backup/tests/latest/test_backup_commands.py
Added command to create policy for IaaSVM from CLI.
az backup policy create --backup-management-type AzureIaasVM -g {rg} -v {vault} -n {policy_name} --policy {policy_json}
---
> [BACKUP] az backup policy create: Added support for IaaSVM backup policy creation from CLI

- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
`vcrpy` is only needed for testing, it should not be a dependency for the `azure-cli` package.
Tested the packages built with this PR's changes in `build_test` branch: https://dev.azure.com/azure-sdk/public/_build/results?buildId=573786&view=results.
---
> {Packaging} Remove vcrpy as a dependency

- src/azure-cli/azure/cli/command_modules/rdbms/_client_factory.py
- src/azure-cli/azure/cli/command_modules/rdbms/_help.py
- src/azure-cli/azure/cli/command_modules/rdbms/_params.py
- src/azure-cli/azure/cli/command_modules/rdbms/_transformers.py
- src/azure-cli/azure/cli/command_modules/rdbms/commands.py
- src/azure-cli/azure/cli/command_modules/rdbms/custom.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_commands.py
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mariadb_server_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_server_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_server_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_commands.py
1. Added list-skus commands for single server Postgres and MySQL
2. Added table transformers for list-skus and server list commands
3. Added local-context support for single server
1. List-skus command: run with the below commands
- az postgres server list-skus -l eastus -o table
- az mysql server list-skus -l eastus -o table
- az mariadb server list-skus -l eastus -o table
2. server list command: run with the below commands
- az postgres server list -g <group_name> -n <server_name> -o table
- az mysql server list -g <group_name> -n <server_name> -o table
- az mariadb server list -g <group_name> -n <server_name> -o table
3. local context command: 
az config param-persist on
- az postgres -h and run commands to check if server name argument is included …
> [RDBMS] Add List-SKUS Command, Table Transformers, Local Context for Postgres, MySQL, Mariadb Single Server

- src/azure-cli/azure/cli/command_modules/backup/custom.py
Relaxed the client side limit for AzureIaasVM protection from 100 to 1000
---
- [Yes ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).
- [Yes ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).
> [Backup] increasing VM protection limit from 100 to 1000

- src/azure-cli/azure/cli/command_modules/storage/readme.md
Move the doc from extension https://github.com/Azure/azure-cli-extensions/pull/2534
---
> {Doc} add readme for storage module

- src/azure-cli-core/azure/cli/core/command_recommender.py
Fix issue #15465，#15591
This PR fixes the positional arguments parsing issue in failure recommendations. The original logic ignored the positional arguments, which would make CLI crash when running a command with positional arguments if that command failed.
Previously, CLI will crash when running `az acr build`
```
...
azure/cli/core/command_recommender.py, ln 162, in recommend_a_command
normalized_parameters = self._normalize_parameters(parameters)
azure/cli/core/command_recommender.py, ln 244, in _normalize_parameters
standard_form = sorted_options[0]
IndexError: list index out of range
```
Now, it prints the right error messages
```
RequiredArgumentMissingError: the following arguments are required: --registry/-r, <SOURCE_LOCATION>
Try this: 'az …
```
> {Core} Skip positional arguments for failure recommendations

- src/azure-cli/azure/cli/command_modules/vm/commands.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
This PR is to fix #15536 
Previously, the user can't update a vm/image-version if the vm/image-version uses a cross tenant image which he/she has no permission to access.
The root cause is that CLI use the create_or_update API to in `update` command to support generic update. The service will check all the properties in the request body even the property value is not changed.
To fix this, we need to set the `storage_profile.image_reference` / `storage_profile.source` to None in the request body if the user is not updating the image property itself.
There is a similar PR #14992 which created by @qwordy .
Prepare a image, assume its id is <IMGAGE_ID>, and in <subscription_1>
update vm
`az account set -s <subscription_2>`
`az vm create -g <rg> -n …
> [Compute] az vm update / az sig image-version update: Support update vm/image-version even it uses a cross tenant image

- azure-cli2017.pyproj
- src/azure-cli/azure/cli/command_modules/sql/_help.py
- src/azure-cli/azure/cli/command_modules/sql/_util.py
- src/azure-cli/azure/cli/command_modules/sql/commands.py
- src/azure-cli/azure/cli/command_modules/sql/custom.py
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_aadonly.yaml
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
Adding support for a new feature to az cli. Azure Active Directory only allows for only AD users to be admins not traditional username/password combinations. This feature has been added to Azure Python SDK and is now being supported in az cli
Using either a managed instance or server with a ad admin run:
az sql server ad-only-auth enable
az sql server ad-only-auth disable
az sql server ad-only-auth get
az sql mi ad-only-auth enable
az sql mi ad-only-auth disable
az sql mi ad-only-auth get
to enable, disable and show AAD only authentication.
> [SQL] Adding AAD-only Support for SQL Managed Instances and Servers

- src/azure-cli/azure/cli/command_modules/vm/_params.py
Resolve https://github.com/Azure/azure-cli/issues/15610
SKUs are changing actively. Remove validation according to service's suggestion.
---
> [Compute] Remove validation of vm host SKUs

- src/azure-cli/azure/cli/command_modules/vm/_params.py
An improvement of 
https://github.com/Azure/azure-cli/pull/14439
---
> {Compute} Update help of vm create --host --host-group

- src/azure-cli/azure/cli/command_modules/keyvault/_client_factory.py
- src/azure-cli/azure/cli/command_modules/keyvault/_validators.py
- src/azure-cli/azure/cli/command_modules/keyvault/commands.py
When running `az keyvault role assignment delete --hsm-name xxx`, CLI will delete all assignments under that HSM without any confirmation. This is really user-unfriendly.
New behavior: throw an actionable error like this:
`RequiredArgumentMissingError: Please specify at least one of these parameters: --name, --scope, --assignee, --assignee-object-id, --role, --ids`
In addition, this PR fixed a validation bug within track 2 data-plane clients creation.
---
> {KeyVault} Fix a filter bug while deleting role assignments

- src/azure-cli/azure/cli/command_modules/keyvault/_client_factory.py
This function is used for determining whether to enable HSM functionality.
```python
def is_azure_stack_profile(cmd):
return cmd.cli_ctx.cloud.profile in [
'2020-09-01-hybrid',
'2019-03-01-hybrid',
'2018-03-01-hybrid',
'2017-03-09-profile'
]
```
e.g:
```python
def delete_vault_or_hsm(cmd, client, resource_group_name=None, vault_name=None, hsm_name=None, no_wait=False):
if is_azure_stack_profile(cmd) or vault_name:
return client.delete(resource_group_name=resource_group_name, vault_name=vault_name)
assert hsm_name
hsm_client = get_client_factory(ResourceType.MGMT_KEYVAULT, Clients.managed_hsms)(cmd.cli_ctx, None)
return sdk_no_wait(
no_wait, hsm_client.begin_delete,
resource_group_name=resource_group_name,
name=hsm_name
)
```
--- …
> {KeyVault} Add new profile `2020-09-01-hybrid` in function `is_azure_stack_profile`

- src/azure-cli/azure/cli/command_modules/keyvault/custom.py
Supports for the service team's request. Let users not able to disable Soft Delete for vaults.
---
> [KeyVault] Invalidate `--enable-soft-delete false` while creating or updating vaults

- src/azure-cli-core/azure/cli/core/parser.py
Fix #3807
The current default completer only takes one positional argument and will throw an error when invoked in `argcomplete` with keyword argument:
https://github.com/kislyuk/argcomplete/blob/a93a4f4dc785373f320d168d2d5a1a11bdc50315/argcomplete/__init__.py#L452-L454
`completer(prefix=cword_prefix, action=active_action, parser=parser, parsed_args=parsed_args)`
This PR makes the default completer take any number of positional or keyword arguments.
On Ubuntu, turn on argcomplete debug with:
`export _ARC_DEBUG=1`
Type the following command and press tab key.
`az vm show --ids /sub`
You can see the error: `TypeError: <lambda>() got an unexpected keyword argument 'prefix'`
Apply the change in this PR to argcomplete by running:
`eval …
> {Auto Complete} Fix default completer

- src/azure-cli-core/azure/cli/core/tests/test_util.py
- src/azure-cli-core/azure/cli/core/util.py
This PR adds more properties into az rest user-agent, making it align with the python-sdk based requests. This is suggested by our PM Arun so that we can get the python version and os info from the user agents.
Currently, a common user agent from az rest based requests could be
```
AZURECLI/2.11.1 (RPM)
```
a common user agent from python-sdk based requests could be
```
python/3.8.2 (Windows-10-10.0.18362-SP0) msrest/0.6.18 msrest_azure/0.6.3 azure-mgmt-resource/10.2.0 Azure-SDK-For-Python AZURECLI/2.12.1 (PIP)
```
The PR adds the following properties into az rest user agents:
- python-version
- os detail
These properties won't be added because they are not the dependencies of az rest.
- msrest version
- msrest_azure version
Run the az rest command, …
> {Core} Enrich user-agent for az rest

- src/azure-cli-core/azure/cli/core/util.py
HTTPErrors are widely raised in different command groups, while they are not caught in core exception handler. Previously, CLI would crash and users would get the raw traces when these error happen. 
This PR supports 
- catching the HTTPErrors in core exception handler.
- categorizing them into the new defined error types.
Here is a table showing the uncaught HTTPError count in AzureCLI@2.12.0 in last month.
CommandGroup | HTTPError Count
-- | --
NETWORK | 1392
DLS | 208
AD | 123
VM | 77
AKS | 51
LOGIN | 41
CONTAINER | 36
GROUP | 35
PROVIDER | 31
COSMOSDB | 27
DEPLOYMENT | 27
ROLE | 26
ACCOUNT | 20
RESOURCE | 11
STORAGE | 11
DT | 9
TAG | 9
KEYVAULT | 8
IMAGE | 7
ARO | 4
POLICY | 4
SQL | 4
VMSS | 4
BACKUP | 3
SIG | 3
WEBAPP | 3
DISK | 2
FUNCTIONAPP | 2
IOT | 2
ACR | 1 …
> {Error Improvement} Catch and categorize HttpError in core exception handler

- src/azure-cli/azure/cli/command_modules/resource/custom.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_tag_update_by_patch.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
Fix the returned data when tagging multiple resources for [15106](https://github.com/Azure/azure-cli/issues/15106)
Another problem is that it's not easy to fix it in a short time, so just fix this one for the time being.
The data returned after the resource is tagged is `LROPoller`, which needs to be wrapped by `LongRunningOperation` to get the actual result.
When only one resource is tagged, it is handled here [link](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/commands/__init__.py#L698).
However, the process of parsing the results will be omitted when multiple resources are tagged, so add the logic of processing.
Run `az resource tag --tags key=value --ids resource-id1 resource-id2`
Before:
```
[
{},
{}
]
```
After: …
> [ARM] Fixed the returned data when tagging multiple resources

- src/azure-cli-core/azure/cli/core/telemetry.py
- src/azure-cli/azure/cli/command_modules/config/custom.py
Currently, we only have platform system name in telemetry, i.e., `windows`, `linux`, `macos`. This PR adds more platform details in a new property in telemetry, e.g., `windows-10-10.0.19041-sp0`, `Linux-5.0.0-1027-azure-x86_64-with-Ubuntu-18.04-bionic`.
This PR also adds all keys in `az config set/unset` commands in telemetry. For `az config set`, if the section or key is in the allow list (mainly for switch type configs), values will also be recorded. We can better analyze users' preference with this data.
1. Run the following command and config keys and values are recorded.
`az config set auto-upgrade.enable=no extension.run_after_dynamic_install=no`
> "Context.Default.AzureCLI.debug_info":"ConfigSet: auto-upgrade.enable=no …
> {Telemetry} Add platform information and some config values

- src/azure-cli/azure/cli/command_modules/keyvault/_validators.py
- src/azure-cli/azure/cli/command_modules/keyvault/custom.py
Fix #15632 
Old messages:
```
'ManagedHsmsOperations' object has no attribute 'list_deleted'
python3.6/site-packages/knack/cli.py, ln 215, in invoke
cli/core/commands/__init__.py, ln 654, in execute
raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
cli/core/commands/__init__.py, ln 711, in _run_job
six.reraise(*sys.exc_info())
...
cli/core/commands/__init__.py, ln 325, in __call__
return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 784, in default_command_handler
return op(**command_args)
cli/command_modules/keyvault/custom.py, ln 250, in list_deleted_vault_or_hsm
return hsm_client.list_deleted()
AttributeError: …
```
> [KeyVault] Refine error messages for HSM `list-deleted` and `purge`

- azure-pipelines.yml
Pin to Python 3.8 for CI task "Verify src/azure-cli/requirements.*.Windows.txt".
Using the default `3.x` will make ADO use 3.9 and [fail](https://dev.azure.com/azure-sdk/public/_build/results?buildId=593807&view=logs&j=796343fd-f04d-59ce-7e73-c4eab21e4249&t=b60a609a-95c6-5b22-14c7-727fdb51354a&l=626):
```
...
File "c:\hostedtoolcache\windows\python\3.9.0\x64\lib\distutils\dist.py", line 985, in run_command
cmd_obj.run()
File "setup.py", line 159, in run
raise Exception("ERROR: The 'make' utility is missing from PATH")
Exception: ERROR: The 'make' utility is missing from PATH
----------------------------------------
ERROR: Failed building wheel for PyNaCl
ERROR: Could not build wheels for cryptography, PyNaCl which use PEP 517 and cannot be installed directly
```
Not sure …
> {CI} Pin to Python 3.8 for "Verify src/azure-cli/requirements.*.Windows.txt"

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
Fix [13646](https://github.com/Azure/azure-cli/issues/13646)
---
> [AppService]: fix #13646 - Unable to create App Service Plan in a different resource group to App Service Environment

- src/azure-cli-core/azure/cli/core/tests/test_util.py
- src/azure-cli-core/azure/cli/core/util.py
Fix incorrect logic of `resource_to_scopes` and `scopes_to_resource` introduced by #15184.
According to [_Trailing slash and /.default_](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#trailing-slash-and-default),
- For some services, the trailing slash should **not** appear in the resource URI, like `https://managedhsm.azure.com`, and the corresponding `scope` should be `https://managedhsm.azure.com/.default`
- On the other hand, for some other services, the trailing slash is mandatory, like `https://management.azure.com/`, and the corresponding `scope` should be `https://management.azure.com//.default` - note the double slash!
This PR changes the behavior so that no extra logic is performed on the trailing slash - CLI only …
> {Core} Do not append/strip trailing slash in scope

- src/azure-cli/azure/cli/command_modules/role/_params.py
Make `description`, `condition`, `condition_version` preview because the public doc is not ready yet. 
See email: _Detailed document for --condition syntax_
```
> az role assignment create -h
--condition         [Preview] : Condition under which the user can be granted
permission.
Argument '--condition' is in preview. It may be changed/removed in a future
release.
--condition-version [Preview] : Version of the condition syntax. If --condition is
specified without --condition-version, default to 2.0.
Argument '--condition-version' is in preview. It may be changed/removed in a future
release.
--description       [Preview] : Description of role assignment.
Argument '--description' is in preview. It may be changed/removed in a future
release.
```
> [Role] az role assignment create: Make description, condition, condition_version preview

- src/azure-cli/azure/cli/command_modules/batch/custom.py
Add a check for file ending when determining certificate format of certificate uploaded to batch account. When a .pfx-certificate is uploaded without a password, the extra check is needed to not parse it as .cer-file.
---
> [Batch] Fix #15464: Update check for pfx file without password in batch create_certificate

- src/azure-cli/azure/cli/command_modules/storage/_help.py
> [Storage] Fix issue #15706: The examples for storage container create are incorrect

- src/azure-cli/azure/cli/command_modules/backup/_params.py
- src/azure-cli/azure/cli/command_modules/backup/custom_wl.py
Added checks wherever KeyError was happening and raised customized error messages according to the situation. Did some improvements in the help text for a clearer understanding of the user.
---
> [BACKUP] Fix #14976: KeyError fixed and help text improved

- src/azure-cli/azure/cli/command_modules/resource/_formatters.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_formatters.py
The PR contains a simple fix for the user reported issue: Azure/arm-template-whatif#126.
az deployment group/sub/mg/tenant what-if ...
---
> [ARM] Fix an issue where What-If shows two resource group scopes with different casing

- src/azure-cli/azure/cli/command_modules/appconfig/_utils.py
Removing the redundant scope from get_login_credentials call because this functionality has been implemented and merged in #15184 and #15698. 
There will be no change in any command behavior. 
---
> {AppConfig} Stop passing resource to get_login_credentials method

- src/azure-cli-core/azure/cli/core/commands/__init__.py
Allow `exception_handler` to mute exception.
In the current code, 
https://github.com/Azure/azure-cli/blob/2cd62de349e30b7774f116118a62246b88225091/src/azure-cli-core/azure/cli/core/commands/__init__.py#L707-L710
if `cmd_copy.exception_handler(ex)` doesn't throw an exception, `CommandResultItem` will be returned and wrapped again later in another `CommandResultItem`:
https://github.com/Azure/azure-cli/blob/8824e41608cc4fc18d41ed3b37f652ef109c5410/src/azure-cli-core/azure/cli/core/commands/__init__.py#L674-L677
This causes Knack to fail at https://github.com/microsoft/knack/blob/0d0308bc567f2d25654bb39201c02ab262d7ce0a/knack/cli.py#L221
```py
self.output.out(cmd_result, formatter=formatter, out_file=out_file)
```
This PRs returns the result of `exception_handler`, instead …
> {Core} Allow exception_handler to mute exception

- src/azure-cli-core/azure/cli/core/_profile.py
Refine #14505. Remove the extra linebreak from warning message
Before:
```
The default web browser has been opened at https://login.microsoftonline.com/common/oauth2/authorize. Please continue 
the login in the web browser. 
If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-
code`.
```
After
```
The default web browser has been opened at https://login.microsoftonline.com/common/oauth2/authorize. Please continue 
the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow 
with `az login --use-device-code`.
```
> {Core} az login: Remove the extra linebreak from warning message

- src/azure-cli/azure/cli/command_modules/appservice/_params.py
fixes https://github.com/Azure/azure-cli/issues/15670
> {AppService} Docs functionapp create plan property requires resource id if using a plan from a different rg

- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_custom.py
Allow customers with no internet access to customize aks related tool download source path to an internal url.
az aks install-cli --base-src-url <url>
[AKS] az aks install-cli: Support customize download url
---
> [AKS] Add custom download url support for 'az aks install-cli'

- azure-pipelines.yml
CI is broken. Fix python version. An urgent hot fix PR from app service is blocked by this issue.
---
> {CI} Fix python version

- azure-pipelines.yml
- src/azure-cli/azure/cli/command_modules/resource/_packing_engine.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_create_template_specs.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_create_template_specs_with_artifacts.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/template_spec_with_multiline_strings.json
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
Description
Customer reported template specs issue (Azure/template-specs#37) where the contents of multiline strings were replaced with #Azure CLI#. This was the result of the _remove_comments_from_json function used to process the template input. This function is typically used in deployments for processing template inputs; multiline strings are processed to prompt for parameters. The full functionality is not needed for creating a template spec from a template input therefore the function has been replaced by process_template_spec in _packing_engine.py.
Example:
Template Input:
{
"variables": {
"myVar": "[if(equals(parameters('kind'), ''),
variables('resources')[variables('provider')][variables('resourceType')],
variables('resources')[variables('provider')][variables('resourceType')][par …
> {Release} Hotfix: TS Multiline String Support for Template Inputs 

- src/azure-cli-core/azure/cli/core/adal_authentication.py
- src/azure-cli-core/azure/cli/core/tests/test_adal_authentication.py
Refine #15184: {Core} Honor `scopes` specified by Track 2 SDK
The current Track 2 SDK client takes `credential_scopes` with **only one** resource as the `scopes` when calling `get_token`.
https://github.com/Azure/azure-sdk-for-python/blob/27e4203818e227ba2604ff52dcf55ce2293c4c37/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/subscriptions/_configuration.py#L60
```py
self.authentication_policy = policies.BearerTokenCredentialPolicy(self.credential, *self.credential_scopes, **kwargs)
```
Some old Track 2 SDKs generated before https://github.com/Azure/autorest.python/pull/239 don't maintain `credential_scopes` and calls `get_token` with an empty `scopes`.
https://github.com/Azure/azure-cli-extensions/blob/db8ea65eb4afa9358de39e06a8c37c85e862a61c/src/datashare/azext_datashare/vendored_s …
> {Core} Workaround empty and multiple scopes provided by old Track 2 SDKs

- azure-pipelines.yml
- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/setup.py
- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/__main__.py
- src/azure-cli/azure/cli/command_modules/resource/_packing_engine.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_create_template_specs.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_create_template_specs_with_artifacts.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/template_spec_with_multiline_strings.json
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
> {Branch Management} Merge release 2.14.1 back to dev

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
Resolve https://github.com/Azure/azure-cli/issues/15749
--platform-fault-domain-count is required in swagger.
If it is not provided,
Before:
ValidationError: Parameter 'DedicatedHostGroup.platform_fault_domain_count' can not be None.
After:
RequiredArgumentMissingError: the following arguments are required: --platform-fault-domain-count/-c
---
> [Compute] vm host group create: make --platform-fault-domain-count required and update help

- scripts/release/debian/deb_install.sh
The `microsoft.asc` key is dearmored before it's saved locally and we should remove `asc` in the key name. Our [manual instruction](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#manual-install-instructions) has already fixed the name. This PR renames the key in the deb install script to keep consistent.
---
> {Install} Rename gpg key in deb install script

- azure-pipelines.yml
Only keep Focal for Ubuntu package test and Buster for Debian package test as they are the latest stable distros.
This change helps reduce CI failures caused by race conditions for writing the same configuration files with multiple parallel package tests and also reduce ADO resource usages.
---
> {CI} Reduce deb package tests

- src/azure-cli-core/azure/cli/core/parser.py
- src/azure-cli-core/azure/cli/core/tests/test_parser.py
This PR removes the useless codes in core for ai-did-you-mean-this, as the extension was already retired.
- ai-did-you-mean-this is retired: https://github.com/Azure/azure-cli-extensions/pull/2402
- azext_ai_did_you_mean_this is removed from core #15500
> {Core} Remove useless codes in core for ai-did-you-mean-this

- src/azure-cli/azure/cli/command_modules/storage/_help.py
#15842 Fixes typo in az storage blob delete-batch documentation - note on deleting blobs with a pattern references "az stroage remove" command, which should read "az storage remove"
Call: `az storage blob delete-batch -h` and review comment for `--pattern` parameter.
[storage] az storage blob delete-batch: Corrected typo in documentation.
---
> {Storage} Fix #15842: az storage blob delete-batch typo in docs

- src/azure-cli/azure/cli/command_modules/storage/_params.py
Since `auth_mode=login` is not supported when doing CRUD with `az storage queue policy`. (Service can't find queue resource in that case), we just ignore `--auth-mode` argument in this PR.
`az storage queue policy create/delete/update/list/show -h`
> {Storage} az storage queue policy: ignore `--auth-mode` argument

- src/azure-cli/azure/cli/command_modules/appservice/resources/LinuxFunctionsStacks.json
- src/azure-cli/azure/cli/command_modules/appservice/resources/WindowsFunctionsStacks.json
This is a stacks update. We're adding preview support for creating Node 14 apps. We're also taking custom handlers out of preview.
These don't change any functionality, just the json the create function uses to know the available options.
[AppService] az functionapp create: Added Node 14 preview support.
[AppService] az functionapp create: Removed preview flag from custom handlers.
---
> [AppService] functionapp: Added Node 14 preview support. Removed preview flag from custom handlers.

- src/azure-cli-core/azure/cli/core/commands/client_factory.py
- Rename `configure_common_settings_track2` to `_prepare_client_kwargs_track2`
- Add a leading underscore (`_`), because it is a private function which is only used by `_get_mgmt_service_client`
- In Track 1 SDK, `config` is a public member of the client and can be configured later:
https://github.com/Azure/azure-sdk-for-python/blob/azure-mgmt-resource_10.2.0/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/subscriptions/v2019_11_01/_subscription_client.py#L45
```py
self.config = SubscriptionClientConfiguration(credentials, base_url)
```
In Track 2 SDK, `_config` is a private member, so configuration should be done via `kwargs` during `__init__` of the client:
https://github.com/Azure/azure-sdk-for-python/blob/azure-mgmt-resource_15.0.0/sdk/resources/azure-mgmt-resou …
> {Core} Refactor client factory for Track 2 SDK

- src/azure-cli-core/azure/cli/core/adal_authentication.py
`_token_retriever` is only available for `AdalAuthentication` which is designed for **user or Service Principal credential**. It is not available for **Managed Identity** credential `MSIAuthenticationWrapper`. Therefore, calling `_token_retriever` to retrieve a raw token will fail for Managed Identity credential:
```py
return Profile(cli_ctx=cli_ctx).get_login_credentials(resource)[0]._token_retriever()
```
This has already caused 2 buggy command module and extension: #15805, https://github.com/Azure/azure-cli-extensions/issues/2461
This PR adds comments to prevent calling `AdalAuthentication._token_retriever` in the future by developers.
For more detail including correct ways to get a raw token, see https://github.com/Azure/azure-cli/issues/15805#issuecomment-722914070.
> {Core} Add comments to prevent calling AdalAuthentication._token_retriever

- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/adal_authentication.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
This PR is a supplement to #15574 , also works as a part of fixing the none-actionable issues in #14981
Fix the left uncaught errors with `az login`
Fix https://github.com/Azure/azure-cli/issues/15836
see the unit tests in test_profile.py
> {Core} az login: Add error handling when finding subscriptions

- src/azure-cli-core/setup.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
Upgrade azure-mgmt-core to 1.2.1 due to codegen's upgrade, see details in #15766 
---
> [Core] Upgrade azure-mgmt-core to 1.2.1

- src/azure-cli/azure/cli/command_modules/acs/custom.py
“az aks browse” command point to Azure Portal if Kubernetes version >= 1.19.0 or kube-dashboard addon is not enabled.
az aks browse -g resourcegroup -n clustername
---
> [AKS] az aks browse: point to Azure Portal Kubernetes resources view if k8s >=1.19 or kube-dashboard not enabled

- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/commands.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
Resolves #15694
This PR involves changes to the `az functionapp update` command:
We're now requiring a user specify a `--force` flag to their command if they're attempting to migrate a functionapp from Premium -> Consumption. This is a potentially dangerous action if their functionapp uses Premium features that are not available in consumption. 
This also adds an error message if the user tries to migrate a functionapp to or from a Linux plan. Migration will only work on Windows at this time.
I also changed the exception handling slightly to add a helpful message if a migration attempt fails from the backend letting the customer know that some plans are incapable of upgrading.
Most of these changes are warnings and error messages. The rest of these …
> [AppService] functionapp: Added warning if customer tries to switch functionapp from premium to consumption.

- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_dns_commands.py
- src/azure-cli/azure/cli/command_modules/privatedns/custom.py
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/test_privatedns_commands.py
Fix the top 1 non-actionable bug (Azure/azure-cli#14984) 
Raise FileOperationError instead of FileNotFoundError if the zone file doesn't exist and catch more expected file operation related errors 
---
> [Privatedns] az network private-dns zone import: Raise FileOperationError instead of FileNotFoundError if zone file doesn't exist 

- src/azure-cli/azure/cli/command_modules/resource/_help.py
Reported in #15589.
When calling `az account management-group show`, users may use the `displayName` of the management group with `--name` which is not the correct usage and will result in a failure:
```
> az account management-group show --name mg20201111-display
code: AuthorizationFailed - , The client 'test@azuresdkteam.onmicrosoft.com' with object id 
'6d97229a-391f-473a-893f-f0608b592d7b' does not have authorization to perform action 
'Microsoft.Management/managementGroups/read' over scope 
'/providers/Microsoft.Management/managementGroups/mg20201111-display' or the scope is invalid. 
If access was recently granted, please refresh your credentials.
```
Refine the help message for `--name` to avoid confusion.
```
> az account management-group show --help
Command
az account …
```
> {ARM} az account management-group show: Refine help for --name

- src/azure-cli-core/azure/cli/core/util.py
There are other JMESPath exceptions besides the `JMESPathTypeError`. For instance, with `az group list --query "length()"`, the following error will be thrown: 
> jmespath.exceptions.ArityError: Expected 1 argument for function length(), received 0
This PR changes the error type from `JMESPathTypeError` to `JMESPathError` to be processed in exception handler so that more JMESPath errors are wrapped as User Fault.
Run `az group list --query "length()"`, the following error message will be shown:
> InvalidArgumentValueError: Invalid jmespath query supplied for `--query`: Expected 1 argument for function length(), received 0
> To learn more about --query, please visit: 'https://docs.microsoft.com/cli/azure/query-azure-cli?view=azure-cli-latest'
**History …
> {Error Improvement} Catch the more general JMESPathError to cover more exceptions

- src/azure-cli/azure/cli/command_modules/vm/commands.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2018_03_01/test_custom_vm_commands.py
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/test_custom_vm_commands.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_custom_vm_commands.py
As we use the PUT REST API (create_or_update) to update vm/image version, if this vm or image version uses a cross tenant image/disk, the user will fail to update it later if he/she has no permission to the original image/disk.
@qwordy has helped add support for `vmss create/update` in 2.13.0. However there are still some other commands that have such problems.
In 2.14.0, @arrownj has added support for `sig image-version create/update` and `vm create/update`.
In 2.15.0, we need to add support for below commands:
1. `vm disk attach/detach`
2. `vm resize`
3. `vm boot-diagnostics enable/disable`
4. `vm nic add/set/remove`
5. `vm secret add/remove`
6. `vm unmanaged-disk attach/detach`
For `sig image-version create/update`, in 2.14.0, we only support the case when image version …
> [Compute] Support update vm/image version when they use cross tenant images

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/commands.py
The dev-spaces CLI extension, which gets called by the aks submodule, has been deprecated. This change is to indicate this using the help text. 
The change can be validated with: `az aks --help`
[aks submodule]: Deprecate dev-spaces commands
---
> [AKS] az aks use-dev-spaces: Indicate that dev-spaces commands are deprecated

- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/hybrid_2018_03_01/test_network_commands.py
Hi all,
the PR is the fix for the created issue. Fix #15796
To test the PR see the full guide in the issue.
Before the fix the second statement returns an error **NetworkWatcherCountLimitReached**
`az network watcher configure --subscription {} --locations eastus --resource-group {} --enabled {} --debug`
`az network watcher configure --subscription {} --locations Eastus --resource-group {} --enabled {} --debug`
---
> [Network] az network network watcher configure: Fix NetworkWatcherCountLimitReached error caused by case sensitivity of location value

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_update_site_configs_persists_ip_restrictions.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_vnetE2E.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_vnetSameName.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Fixes #14857 
- Create an App Service and a VNET which has one subnet at least.
- Set Access Restriction by the subnet to the App Service
- Execute `az login` using a service principal which has a contributor role of the App Service and doesn't have any role the VNET.
- Execute `az webapp config set --resource-group {} --name {} --always-on {}`
Currently see error: 
User with permissions to webapp should be able to update webapp even if there are access restrictions by subnet where user does not have permissions to subnet
---
> [AppService] Bugfix #14857: Let users update webapp config even with access restriction

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/setup.py
- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/__main__.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
> {Release} HotFix: Release 2.15.1

- src/azure-cli/azure/cli/command_modules/rdbms/custom.py
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mariadb_server_mgmt_public_parameter.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_flexible_server_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_flexible_server_mgmt_validator.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_flexible_server_proxy_resource.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_flexible_server_replica_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_server_mgmt_public_parameter.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_mgmt_validator.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_proxy_resource.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_server_mgmt_public_parameter.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands.py
The motivation of this PR is to update the test servers to be publicly accessible. After every M-train(backend changes for PG and MySQL Flexible Servers), we need to run these tests in the Stage environment in order to validate if these changes are breaking any current functionality. Currently, the test servers are created with private Vnet access and the Stage environment does not support vnet creation. As a result, we are blocked on running these tests in the Stage environment. Every time we run these tests, we have to update the server creation commands to let them have public access instead of private. 
Command usage : 
azdev test rdbms --live
> {RDBMS} Update test servers to be publicly accessible

- src/azure-cli/azure/cli/command_modules/backup/_params.py
- src/azure-cli/azure/cli/command_modules/backup/custom_common.py
- src/azure-cli/azure/cli/command_modules/backup/custom_wl.py
In some cases 'SAPHANA' & 'MSSQL' are shown in the help text as allowed values for workload type argument but when these are given as input the command terminates with Bad Error Request. I've included a map in custom_common.py to map these values to the value that the API is expecting.
az backup item list -g {rg} -v {vault} --backup-management-type AzureWorkload --workload-type SAPHANA
az backup policy list -g {rg} -v {vault} --backup-management-type AzureWorkload --workload-type MSSQL
---
> [BACKUP] Fixed Bad Request Error for Correct Workload Type Input

- src/azure-cli-core/setup.py
- src/azure-cli/setup.py
Currently, pip assumes 2.14.0 is the latest version for all python interpreters and installs that version. This causes errors like this on older python versions:
```
File "<string>", line 1, in <module>
File "/home/confus/.local/share/virtualenvs/specter-yzp-I12c/lib/python3.2/site-packages/azure/cli/core/commands/__init__.py", line 425
def cached_put(cmd_obj, operation, parameters, *args, setter_arg_name='parameters', **kwargs):
^
SyntaxError: invalid syntax
```
This probably a systemic problem in more than one of the azure libraries and because older packages with this error are already on pypi.org and other package repositories (debian, suse, ...), it is hard to solve in retrospect. This PR is just to raise awareness for the issue.
> {Packaging} Add required python version in various setup.py

- src/azure-cli-core/tox.ini
- src/azure-cli-telemetry/azure/cli/telemetry/components/telemetry_client.py
- src/azure-cli-telemetry/tox.ini
Thanks to @fengzhou-msft for the finding. 
Previously, `six` is installed by [packaging 20.4](https://pypi.org/project/packaging/20.4/).
```
> pipdeptree -p six -r
six==1.14.0
- packaging==20.4 [requires: six]
- pytest==6.1.1 [requires: packaging]
- azdev==0.1.28 [requires: pytest>=5.0.0]
- azure-cli-testsdk==0.2.4 [requires: pytest]
- pytest-forked==1.3.0 [requires: pytest>=3.10]
- pytest-xdist==2.1.0 [requires: pytest-forked]
- azdev==0.1.28 [requires: pytest-xdist]
- pytest-xdist==2.1.0 [requires: pytest>=6.0.0]
- azdev==0.1.28 [requires: pytest-xdist]
- tox==3.20.1 [requires: packaging>=14]
- azdev==0.1.28 [requires: tox]
```
Now `six` has been dropped since [packaging 20.5](https://pypi.org/project/packaging/20.5/) (https://github.com/pypa/packaging/pull/331), causing …
> {CI} Remove usage of six

- src/azure-cli/azure/cli/command_modules/role/_help.py
Fix #11354: _List of Graph API permission_
`az ad app permission add`: Add instruction on how to get available permission IDs
```
> az ad app permission add -h
Command
az ad app permission add : Add an API permission.
Invoking "az ad app permission grant" is needed to activate it.
To get available permissions of the resource app, run `az ad sp show --id <resource-appId>`.
For example, to get available permissions for Graph API:
- Azure Active Directory Graph: `az ad sp show --id 00000002-0000-0000-c000-000000000000`
- Microsoft Graph: `az ad sp show --id 00000003-0000-0000-c000-000000000000`
Application permissions under the `appRoles` property correspond to `Role` in --api-
permissions. Delegated permissions under the `oauth2Permissions` property …
```
> {Role} az ad app permission add: Add instruction on how to get available permission IDs

- src/azure-cli-core/azure/cli/core/azclierror.py
- src/azure-cli-core/azure/cli/core/util.py
This PR provides the following error improvements.
- Suppress `UnknownError` in error message.
- Catgorize the uncommon `4xx` HTTP response errors into the `UnclassifiedUserFaults` instead of `UnknownError`
- Fix the untidy error message issue in HttpOperationError #15872
For the untidy error message in HttpOperationError, just type `az account management-group show --name non-existing` for testing.
Previously,
```
code: AuthorizationFailed - , The client 'test@azuresdkteam.onmicrosoft.com' with object id '6d97229a-391f-473a-893f-f0608b592d7b' does not have authorization to perform action 'Microsoft.Management/managementGroups/read' over scope '/providers/Microsoft.Management/managementGroups/non-existing' or the scope is invalid. If access was recently …
```
> {Error Improvement} Error category and error message refining

- src/azure-cli-core/azure/cli/core/commands/client_factory.py
When making any HTTP request, CLI will add some custom headers
- `x-ms-client-request-id` 
- `CommandName`
- `ParameterSetName`
to the request via the SDK client. But `msrest` doesn't print custom headers in the debug log. 
This PR makes CLI print custom headers so that users can know what information is sent to the server and logged in the server-side telemetry. This can also help code-gen team gather more information without checking the server-side telemetry.
```powershell
> az group show -n fy --debug
Adding custom headers to the client:
'x-ms-client-request-id': '220893a8-14e0-11eb-ae06-84a93e63aa78'
'CommandName': 'group show'
'ParameterSetName': '-n --debug'
...
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourc …
```
> {Core} Show custom headers in --debug log

- doc/extensions/README.md
- doc/extensions/authoring.md
- doc/install_troubleshooting.md
- doc/use_cli_in_airgapped_clouds.md
- doc/version_management.md
- src/azure-cli-core/azure/cli/core/parser.py
- src/azure-cli-core/azure/cli/core/util.py
- src/azure-cli/azure/cli/command_modules/storage/docs/Storage Encryption.md
Only changes are to remove the "?view=azure-cli-latest" and "&preserve-view=true" syntax from Azure CLI-related links. I also removed instances 'en-US' from links per current validation guidelines. These guidelines apply to most, but not all content. I can revert if these links are supposed to go specifically to en-US versions. Please see the user story for more details.
User story [1797650](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1797650)
---
> {Misc} Remove '?view=' syntax in links where not necessary

- src/azure-cli/azure/cli/command_modules/acs/_help.py
This PR clarifies the documentation for `az aks get-credentials`. I'm creating it after an AKS customer support incident where there was confusion over the purpose of the --admin flag. This PR:
* Explains how `get-credentials` relates to kubectl (since that explaination is otherwise very hard to find, and not at all obvious to new AKS users)
* Explains `--admin` in an AAD context, as per https://docs.microsoft.com/en-us/azure/aks/managed-aad#troubleshooting-access-issues-with-azure-ad
Make sure `az aks get-credentials --help` looks reasonable.
---
- [Y ] The PR title and description has followed the guideline in [Submitting Pull …
> [AKS ] az aks get-credentials: Clarify documentation for get-credentials

- src/azure-cli-testsdk/azure/cli/testsdk/preparers.py
Sometimes we need to configure vnet location according to requirement
---
> {azure-cli-testsdk} add location parameter for VirtualNetworkPreparer

- src/azure-cli/azure/cli/command_modules/vm/_params.py
Resolve https://github.com/Azure/azure-cli/issues/16004
---
> [Compute] New license type RHEL_ELS_6

- src/azure-cli/azure/cli/command_modules/network/_params.py
Close https://github.com/Azure/azure-cli/issues/15944
--
> [Network] az network private-endpoint create: add more declaration of '--subnet' and '--private-connection-resource-id'

- src/azure-cli/azure/cli/command_modules/aro/_aad.py
- src/azure-cli/azure/cli/command_modules/aro/_help.py
- src/azure-cli/azure/cli/command_modules/aro/_rbac.py
- src/azure-cli/azure/cli/command_modules/aro/_validators.py
- src/azure-cli/azure/cli/command_modules/aro/custom.py
- src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_create.yaml
- src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_delete.yaml
- src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_update.yaml
Upstreams [Azure/ARO-RP#1159](https://github.com/Azure/ARO-RP/pull/1159) which adds RBAC validation on ARO cluster update, unblocking updates when customers remove SPN permissions.  
Upstreams [Azure/ARO-RP#1217](https://github.com/Azure/ARO-RP/pull/1159) which updates error handling in ARO to conform to the guidelines. 
---
> [ARO] az aro update: Add RBAC validation on cluster update

- src/azure-cli-core/azure/cli/core/style.py
- src/azure-cli-core/azure/cli/core/tests/test_style.py
- src/azure-cli/azure/cli/command_modules/util/_help.py
- src/azure-cli/azure/cli/command_modules/util/commands.py
- src/azure-cli/azure/cli/command_modules/util/custom.py
Support style with color.
For a complete demo, see `src/azure-cli/azure/cli/command_modules/util/custom.py` and run `az demo style`.
> {Style} Support style with color

- src/azure-cli/azure/cli/command_modules/monitor/actions.py
One of fix for https://github.com/Azure/azure-cli/issues/14988
To reproduce via run:
```
az monitor metrics alert create -n alert1 -g harold --scopes /subscriptions/0000-0000/resourceGroups/xxxxx/providers/Microsoft.Compute/virtualMachines/xxxx/extensions/MicrosoftMonitoringAgent --condition "avg Percentage CPU > 90" --window-size 5m --evaluation-frequency 1m --description "High CPU Usage"  --action /subscriptions/xxxx/resourceGroups/xxxx/providers/microsoft.insights/actionGroups/xxxx apiKe
```
And the subsequently error output would be like:
```
File "/home/harold/.pyenv/versions/3.7.4/lib/python3.7/argparse.py", line 1969, in _parse_known_args
positionals_end_index = consume_positionals(start_index)
File …
```
> [Monitor] az monitor metrics alert create: improve error message to give more actionable insight

- src/azure-cli/azure/cli/command_modules/storage/operations/file.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_batch_operations.py
- src/azure-cli/azure/cli/command_modules/storage/util.py
Fix #9956
`az storage file download-batch` with `--snapshot`
---
> [Storage] Fix issue #9956: Trying to download a snapshot version of a file share fails with ResourceNotFound

- src/azure-cli-core/azure/cli/core/commands/__init__.py
Pass `cli_ctx` to implicit items to adapt to https://github.com/microsoft/knack/pull/213.
Run any implicitly deprecated/preview/experimental commands.
```
az demo style -h
az demo style
```
> {Core} Pass cli_ctx to implicit items

- src/azure-cli-core/azure/cli/core/__init__.py
This PR requires https://github.com/microsoft/knack/pull/223
Refine and override tag messages from Knack to be more user-friendly.
See email: _Refining our experimental message to be more positive_
```sh
> az account subscription -h
This command group is experimental and under development. Reference and support levels:
https://aka.ms/CLI_refstatus
> az account subscription show -h
Command group 'account subscription' is experimental and under development. Reference
and support levels: https://aka.ms/CLI_refstatus
> az apim -h
This command group is in preview and under development. Reference and support levels:
https://aka.ms/CLI_refstatus
> az apim api -h
Command group 'apim' is in preview and under development. Reference and support levels:
https://aka.ms/CLI_refstatus …
```
> {Core} Use custom tag message

- src/azure-cli-core/azure/cli/core/azlogging.py
- src/azure-cli-core/azure/cli/core/commands/client_factory.py
This PR requires https://github.com/microsoft/knack/pull/221. 
Previously when `--verbose` is specified, only `cli.*` loggers' `INFO` logs are printed. Now all `azure.*` loggers' `INFO` logs are printed, including the CLI loggers which are renamed to `azure.cli.*`.
Example:
```
> az group show -n fy --debug
...
DEBUG: azure.cli.core: Modules found from index for 'group': ['azure.cli.command_modules.resource']
DEBUG: azure.cli.core: Loading command modules:
DEBUG: azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: azure.cli.core: resource                  0.009        35       164
DEBUG: azure.cli.core: Total (1)                 0.009        35       164
...
INFO: azure.core.pipeline.policies.http_logging_policy: Request URL: …
```
> [Core] Print INFO log from SDK

- azure-pipelines.yml
- scripts/release/debian/test_deb_in_docker.sh
- src/azure-cli-core/setup.py
- src/azure-cli/setup.py
pip 20.3 has strict check for dependency versions. In CI the version is modified with a suffix of `devN`, this PR modifies the version  requirements in `setup.py` to make it compatible in this case.
`Ubuntu Eoan` has reached end-of-life and is dropped in this PR.
---
> {CI} Fix dependency version in setup.py, drop eoan package

- src/azure-cli/azure/cli/command_modules/profile/_help.py
- src/azure-cli/azure/cli/command_modules/profile/custom.py
- src/azure-cli/azure/cli/command_modules/role/custom.py
Refine #15825: Add long-summary/warning for commands generating credentials
This PR shows the `CREDENTIAL_WARNING_MESSAGE` for more commands:
- `az account show --help`
- `az account show --sdk-auth`
- `az ad sp create-for-rbac --sdk-auth`
> {Profile} Add CREDENTIAL_WARNING_MESSAGE for more commands

- src/azure-cli/azure/cli/command_modules/role/_params.py
The current description of `--assignee-object-id` is unclear about "graph permission issues":
```
--assignee-object-id          : Use this parameter instead of '--assignee' to bypass graph
permission issues.
```
Replace it with more explicit description:
```
--assignee-object-id          : Use this parameter instead of '--assignee' to bypass Graph API
invocation in case of insufficient privileges.
```
> {Role} az role assignment create: Refine unclear help message of `--assignee-object-id`

- src/azure-cli/azure/cli/command_modules/synapse/_help.py
In previous pr #16095 
The help for `az synapse sql pool classification recommendation` was misdirected to `az sql db classification recommendation`.
This pr is to fix the help entry name and make CI pass for `sql` module.
`az synapse sql pool classification recommendation enable -h`
`az synapse sql pool classification recommendation disable -h`
> {Synapse} fix help file

- src/azure-cli-core/azure/cli/core/util.py
This PR tries to fix the issue https://github.com/Azure/azure-cli-extensions/issues/2793.
For `HttpOperationError`, we can find its error message either in `HttpOperationError.response.text` and `HttpOperationError.message`.  E.g, for the case above, the error message in  `HttpOperationError.message` is
```
Operation returned an invalid status code 'Bad Request'
```
and the error message in `HttpOperationError.response.text` is like below, **which is more explicit**
```
{"Error":{"Code":"ValidationFailed","Message":"Updating immutable properties is not allowed."}}
```
Previously in AzureCLI core, the exception handler firstly tries to parse the `HttpOperationError.response.text` (usually a dict), and when that fails, it falls back to use `HttpOperationError.message`. …
> {Error Handling} Show explicit error messages for HttpOperationError

- src/azure-cli/azure/cli/command_modules/container/_help.py
Documentation change, fixes misspelling "mySubscrpitionId".
n/a
[Container] Fix misspelling in `az container create` CLI example text.
---
> {Doc} Fix spelling (mySubscrpitionId)

- src/azure-cli/azure/cli/command_modules/aro/custom.py
Upstreams [Azure/ARO-RP#1227](https://github.com/Azure/ARO-RP/pull/1227) to ensure that worker_profiles is not None before attempting to access it.  
---
> [ARO] Ensure worker_profile is not None before getting the subnets from

- src/azure-cli/azure/cli/command_modules/resource/_help.py
- src/azure-cli/azure/cli/command_modules/resource/_params.py
- src/azure-cli/azure/cli/command_modules/resource/custom.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_provider_registration_rpaas.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
When registering RPs provided by RPaaS, users must accept the market place terms and service terms. Add `--accept-terms` option in `az provider register` command and make it required when the namespace is in the hard-coded RPaaS map.
The API to accept term can only be called after the RP is registered, so `--accept-terms` implies `--wait`.
1. `az provider register -n "Microsoft.Confluent"` should throw an error: 
> "--accept-terms must be specified when registering the Microsoft.Confluent RP from RPaaS."
2. `az provider register -n "Microsoft.Confluent" --accept-terms` will wait for the register process to succeed.
[Component Name 2] az command …
> [Resource] az provider register: Add --accept-terms for registering RPaaS

- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
- src/azure-cli-core/azure/cli/core/tests/test_profile_v2016_06_01.py
After logging in with a Service Principal using a certificate, 2 commands
- `az account show --sdk-auth`
- `az account list --refresh`
will fail with
```
missing secret or certificate in order to authenticate through a service principal
```
This is because `retrieve_secret_of_service_principal` can only return a `secret`, but `None` for `certificateFile`, causing subsequent `ServicePrincipalAuth` instantiation to fail due to the lack of `password_arg_value`.
This PR fixes these commands by:
- Rename `retrieve_secret_of_service_principal` to `retrieve_cred_for_service_principal` to reflect its actual functionality.
- Let `retrieve_cred_for_service_principal` return `secret` or `certificateFile` of the Service Principal so that `ServicePrincipalAuth` gets what it needs. …
> [Profile] Fix "missing secret or certificate in order to authenticate through a service principal"

- src/azure-cli/azure/cli/command_modules/aro/_validators.py
- src/azure-cli/azure/cli/command_modules/container/custom.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_virtual_network.py
- src/azure-cli/azure/cli/command_modules/servicefabric/custom.py
Here are main changes for Network migration to track2:
- LRO operations are renamed to `begin_xxx_xxx`, for example in track1, the name is `create_or_update`; while in track2, the name is `begin_create_or_update`.
- In track2, use `HttpResponseError` instead of `CloudError`.
---
> {Network} Migrate network SDK that is used by some other modules to track2

- src/azure-cli-core/azure/cli/core/util.py
- src/azure-cli/azure/cli/command_modules/resource/custom.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_resource_group_deployment.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/simple_deploy_multiline.json
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
For more complex multiline strings (such as policies for Azure API Management), `az deploy` will fail with message: ` Failed to parse ... , please check whether it is a valid JSON format`, because multiline string contains block quotes within the string.
This PR adds test case that's failing with current az and naive proposal to improve detection of such situation. I couldn't find a regexp that is solving all cases, that's why I just slightly changed existing one and added check with replacement. The regex is already quite complex and I think it's already on the bridge of being understandable.
Test cases are provided within PR.
[resource] Fix parsing JSON files with multi-line strings  
--- …
> [ARM] `az deployment`: Fix parse errors with multiline strings

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
Fixes #16008
When using `az webapp up` to create an app with existing ASP in a different location, we show the following unhandled error message (notice UnknownError):
This PR is to handle the error msg:
- run `az webapp up --location location1 --name name1`
- re-run using different name and location. plan should be defaulted to the same plan created from the first invocation of the command. `az webapp up --location location2 --name name2`
Should get error message saying ASP exists in different location
cls
---
> [AppService] Bugfix: Better error handling when trying to create duplicate ASP in diff location

- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/_params_azure_stack.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_blob_copy_scenarios.py
> {Storage} Fix issue #13478 to add more information for requires_sync scenaio

- azure-pipelines-full-tests.yml
- azure-pipelines.yml
- scripts/release/pypi/build.sh
We need to use different predefined variables on ADO to get the target branch in a PR triggered CI and push-to-branch triggered CI.
Tested with push-to-branch case with `build_test` branch ([result](https://dev.azure.com/azure-sdk/public/_build/results?buildId=666865&view=results)).
This PR can test the PR CI case.
---
> {CI} Fix branch info

- src/azure-cli/azure/cli/command_modules/storage/operations/fs_file.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_adls_upload_scenarios.py
> [Storage] Fix #16072: Upload file with big size

- .github/CODEOWNERS
We may need service team member as rdbms code owner to ensure the code quality as we CLI team members may not know exactly and explictly how everything works.
For example, network migration need service team's review: #16350 
---
> {RDBMS} Add rdbms code owner

- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_virtual_network.py
Fix the bad name of https://github.com/Azure/azure-cli/pull/15992
---
> [rdbms] Hotfix: `az mysql flexible-server create -l eastus2euap` : Fix for bad input parameters

- src/azure-cli/azure/cli/command_modules/acs/custom.py
There is a small typo in src/azure-cli/azure/cli/command_modules/acs/custom.py.
Should read `satisfy` rather than `satsify`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> {AKS} Fix typo: satsify -> satisfy

- doc/track_2_migration_guidance.md
{Doc} Track 2 Migration Guidance
Azure CLI is built upon Azure Python SDK. Recently Azure Python SDK announced next generation product. It is named Track 2 SDK. The old version of SDK is named Track 1. It claims that it has great advantages than Track 1 SDK. It is not compatible with Track 1 SDK. Azure CLI developers need to spend considerable time and do some work to migrate from Track 1 SDK to Track 2 SDK.
This documentation summarizes typical issues and solutions when adopting Track 2 SDK in Azure CLI.
You are welcome to contribute to this documentation if you have experience of Track 2 SDK. …
> {Doc} Track 2 Migration Guidance

- azure-pipelines.yml
The CI for homebrew package test failed caused by default Python used on ADO becoming python 2.7. Adding a task to use python 3.6/3.8 also has issues, so let's turn off the test temporarily.
---
> {CI} Hotfix: Disable homebrew package test temporarily

- src/azure-cli/azure/cli/command_modules/vm/custom.py
Resolve https://github.com/Azure/azure-cli/issues/15075
The following code is not robust. So, fix it.
```
os_type = vm.storage_profile.os_disk.os_type.value if vm.storage_profile.os_disk.os_type else None
AttributeError: 'NoneType' object has no attribute 'storage_profile'
```
---
> [Compute] Fix issue of none storage_profile

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_ssl_import.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_ssl_import_crossrg.yaml
I am enabling az webapp config ssl import to also import an app service certificate to a webapp. At the moment, it just allows importing a KeyVault cert. With this change, it can be used for both types of certificate. There will be no breaking change, as we are reusing the paramater names 
Parameters remain the same, as show below: the only difference is that now key-vault-certificate-name can also be an ASC
az webapp config ssl import --name webappName --resource-group rgName --key-vault-certificate-name certName --key-vault keyVaultNameOrId
--- …
> [AppService] Fix #13907: az webapp config ssl import: Change command to also import App Service Certificate

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/_help.py
- src/azure-cli-core/setup.py
- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/__main__.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
Release beta 2.17.10.
After #16380 is resolved, the version will be like 3.0.0b2170.
> {Release} Release beta 2.17.10

- src/azure-cli-core/setup.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
Requested by https://github.com/Azure/azure-cli/pull/12477#issuecomment-748666626.
**FreeBSD 13** only ships with [py37-humanfriendly-9.1.txz](https://freebsd.pkgs.org/13/freebsd-i386/py37-humanfriendly-9.1.txz.html).
https://pkgs.org/search/?q=humanfriendly
Bump humanfriendly to `9.1` and limit to `10.0` so that Azure CLI can be installed on **FreeBSD 13** with their own packaging system.
```
> az group delete -n xxx
- Running ..  
```
> {Misc.} Bump humanfriendly to 9.1

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
We currently don't support SSH from a windows client. 
Instead of showing error msg, as a mitigation we should open browser to web-ssh console that is part of every Linux app
Run `az webapp ssh -n {} -g {}` on a windows client
---
> [AppService] Fixes #16125: az webapp ssh if using a windows client, open browser to scm link

- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Fix
azure/cli/command_modules/vm/tests/latest/test_vm_commands.py::VMManagedDiskScenarioTest::test_vm_disk_max_shares_etc
azure/cli/command_modules/vm/tests/latest/test_vm_commands.py::DiskAccessTest::test_disk_access
azure/cli/command_modules/vm/tests/latest/test_vm_commands.py::VMGalleryImage::test_gallery_specialized
---
> {Compute} Fix tests

- src/azure-cli/azure/cli/command_modules/vm/custom.py
Resolve https://github.com/Azure/azure-cli/issues/16391
External tokens in Track 2 SDk have problem. I am still investigating why it is None.
---
> [Compute] Better error handling of external tokens

- src/azure-cli-core/azure/cli/core/commands/__init__.py
- src/azure-cli-core/azure/cli/core/telemetry.py
After the change we could see the following two items in telemetry as shown below in my test env.
---
> {Core} Add polling start time and end time in telemetry 

- src/azure-cli/azure/cli/command_modules/resource/_params.py
- src/azure-cli/azure/cli/command_modules/resource/custom.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/createKeyVaultWithSecret.json
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/resource_group_level_linked_template.json
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/storage_account_linked_template.json
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/subscription_level_linked_template.json
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
Closed : https://github.com/Azure/azure-cli/pull/16400 
Az deployments now supports  --query-string to be used with --template-uri for linked template deployments; --query-string is a SAS token for a storage container that contains the main template and linked template(s).  Support for the --query-string parameter will facilitate the transition to template specs. Like with template specs linked templates are referenced through the relative path field in template link as illustrated below:
"templateLink":  {
"relativePath":"linked_template.json",
"contentVersion":"1.0.0.0"
}
1. Create storage account container and upload files for deployment. 
az storage account create -n {} -g {} -l {} --sku {} --kind {} 
az storage container create -n {} --account-name …
> [ARM] Az Deployments : Add support for --query-string

- src/azure-cli/azure/cli/command_modules/container/custom.py
The backend sends an empty webSocket message after establishing an connection. The removed lines of code interpreted that as an EOL which exits the webSocket read loop.
As the Windows code doesn't do that as well, I removed it here as well now.
The terminal gets closed after the webSocket closes anyway.
Fixes: https://github.com/Azure/azure-cli/issues/15856
As described in https://github.com/Azure/azure-cli/issues/15856 there is currently an issue getting a remote terminal to a container instance with `az container exec` as it immediately closes the connection.
- start a container e.g. with `az container create` with a long living container
- try to execute a shell inside the container with `az container exec --exec-command "/bin/bash" ...`
- currently it …
> {container} Bugfix #15856: az container exec - remove eol check to avoid closing terminal before it even started on linux

- src/azure-cli/azure/cli/command_modules/backup/custom_base.py
When --retain-until parameter value is not provided by the user in backup-now command default retention period is set to 30 days. Till now it was giving 0 days default retention.
az backup protection backup-now -g {rg} -v {vault} -c {container} -i {item}
az backup protection backup-now -g {rg} -v {vault} -c {container} -i {item} --retain-until {dd-mm-yyyy}
---
> [BACKUP] az backup protection backup-now: Set default retention period to 30 days

- src/azure-cli/azure/cli/command_modules/storage/_client_factory.py
In track2 SDK, we have to configure the client to enable logging. Otherwise cx could not see the rest info.
---
> {Storage} Enable logging for track2 data plane operations

- src/azure-cli/azure/cli/command_modules/acr/_params.py
- src/azure-cli/azure/cli/command_modules/acr/custom.py
- src/azure-cli/azure/cli/command_modules/acr/linter_exclusions.yml
- src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_with_public_network_access.yaml
- src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_commands.py
This PR adds the option `--allow-trusted-services` to `az acr create` and `az acr update`. By default ACR allows trusted azure services to access network restricted registries.
```
az acr create -h 
az acr update -h
azdev test test_acr_with_public_network_access
```
[ACR] az acr create / update: add --allow-trusted-services. This parameter determines whether trusted azure services are allowed to access network restricted registries. The default is to allow.
---
> [ACR] add --allow-trusted-services support

- src/azure-cli/azure/cli/command_modules/acr/_errors.py
- src/azure-cli/azure/cli/command_modules/acr/_utils.py
- src/azure-cli/azure/cli/command_modules/acr/check_health.py
- src/azure-cli/azure/cli/command_modules/acr/custom.py
Add CMK configuration check to deflect support case
---
> [acr] add step in "check-health" command to ensure the identity used for CMK does exist

- src/azure-cli/azure/cli/command_modules/storage/commands.py
> [Storage] GA PITR and blob service properties in SRP

- src/azure-cli/azure/cli/command_modules/rdbms/custom.py
- src/azure-cli/azure/cli/command_modules/sql/custom.py
Extend Current Regex matching to include managed hsm URIs since Managed HSM is supported in SQL now.
> [SQL] Add managed hsm regex match to SQL

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/appservice_environment.py
- src/azure-cli/azure/cli/command_modules/appservice/commands.py
This PR adds support for setting Linux as the initial OS support for ASEv3 to fix #16509. This is not relevant for ASEv3.
It also improves the new functionality of az appservice ase create-inbound-services to allow the Private DNS Zone to be created for Internal ASEv2 as well, and to be able to only create the private endpoint for ASEv3 and skip DNS services (to support custom DNS).
The --skip-dns will skip the creation of Private DNS Zone and records
```
az appservice ase create -n <ase-name> -g <resource-group> --subnet <outbound-subnet-name> --vnet-name <vnet-name> --kind ASEv3
az appservice ase create-inbound-services -n <ase-name> -g <resource-group> --subnet <inbound-subnet-name> --vnet-name <vnet-name> --skip-dns
```
Creating an ASEv2 and creating …
> [App Service] Add support for os-preference to fix #16509

- src/azure-cli/azure/cli/command_modules/role/custom.py
`az role assignment list-changelogs` (introduced by #5551) calls [Activity Logs - List](https://docs.microsoft.com/en-us/rest/api/monitor/activitylogs/list) to get all activity logs with `$filter=resourceProvider eq Microsoft.Authorization`.
Then it uses
https://github.com/Azure/azure-cli/blob/00c59c2dc52b9b7c71c63fc423e37c16d8186192/src/azure-cli/azure/cli/command_modules/role/custom.py#L422
to retrieve the subscription ID from mgmt client for Classic Administrator events. This operation is not permitted by Track 2 SDKs, as `config` now becomes a protected `_config` attribute.
Classic Administrator create/delete operation generates 2 types of logs:
CLI currently doesn't show this type, because `operation_name` of the event is `'Microsoft.Authorization/classicadministrators/write'` and …
> {Role} Remove code for classic events

- src/azure-cli-core/azure/cli/core/util.py
Resolve #14656: `az login` WSL 2 Ubuntu 18.04 does not open browser 
This PR makes Azure CLI launch browser in WSL 2.
Following the "official" way of detecting WSL https://github.com/Microsoft/WSL/issues/423#issuecomment-221627364, run `uname -a` to get `release`: 
- WSL 1: `4.4.0-19041-Microsoft`
- WSL 2: `4.19.128-microsoft-standard`
So instead of checking if the `release` string ends with `microsoft`, we should check if it contains `microsoft`.
In WSL 1 and WSL 2:
```
az login
```
ℹ For installing WSL 2 and switching between WSL 1 and WSL 2, see https://docs.microsoft.com/en-us/windows/wsl/install-win10
> [Profile] az login: Launch browser in WSL 2

- src/azure-cli-core/setup.py
Trying to package this for nixpkgs, but I get:
```
ERROR: No matching distribution found for azure-mgmt-core==1.2.1 (from azure-cli-core==2.15.1)
```
when it's being given 1.2.2
Azure-sdk generally follows semver, so no need to pin.
---
> {Core} Use semver for azure-mgmt-core

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
Fix null reference errors in `az webapp up` and `az webapp create`
Closes #15752, #16565, #16061, #16475
- If appservice and appservice plan are in different resource groups, `az webapp up` will try and find appservice plan in the wrong resource group
- Nonetype error when creating windows container app using `az webapp create` if deployment_container_image_name is not supplied
- Create a webapp, then mov ewebapp to another resource group, then run `az webapp up`
- Create a windows container appservice plan, then create a webapp with this appservice plan using `az webapp create`
These two scenarios shouldn't give nonetype error
---
> [AppService] az webapp up/az webapp create: Fix nonetype errors

- src/azure-cli-core/azure/cli/core/_identity.py
- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/credential.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
The [get_msal_token](https://github.com/Azure/azure-cli/blob/bc021765bd012cc3a6c558f54409cb079e09242d/src/azure-cli-core/azure/cli/core/_profile.py#L620) method was added with a hack to use adal refresh token to get msal ssh cert for vm ssh feature used in the ssh extension.
This PR adds back a `get_msal_token` method with the same interface for backward compatibility, but use `azure-identity` to fetch the ssh cert.
1. Create a Ubuntu vm on portal and remember to enable system assigned identity and AAD login in the management tab. 
2. Assign a `Virtual Machine Administrator Login` or `Virtual Machine UserLogin role` over the vm scope for your account.
3. Run `az ssh vm -g <> --vm-name <>`
[Component Name 1] BREAKING CHANGE: az command a: …
> {Identity} Add back get_msal_token

- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/operations/account.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_with_routing_preference.yaml
> [Storage] GA Storage routing reference

- doc/use_cli_in_airgapped_clouds.md
> {Doc} Add more examples and install extensions part for airgapped cloud guide

- src/azure-cli/azure/cli/command_modules/storage/_client_factory.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_list_scenarios.yaml
> {Storage} Configure location mode in client

- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/_validators.py
For `container/blob generate-sas`, if the specified policy already contains expiry or permissions info, add `--expiry` or `--permissions` in `generate-sas` command will generate invalid sas token. 
---
> [Storage] Fix #9158: Cannot generate a working SAS key from a policy

- src/azure-cli/azure/cli/command_modules/keyvault/_params.py
- src/azure-cli/azure/cli/command_modules/keyvault/_validators.py
- src/azure-cli/azure/cli/command_modules/keyvault/custom.py
This PR fixes https://github.com/Azure/azure-cli-pr/issues/121
It provides the `--curve` paramter in `az keyvault key import` command.
```
--curve          : The curve name of the key to import (only for BYOK).  Allowed values:
P-256, P-256K, P-384, P-521.
```
The command below could be used for key importing after the fix.
```
az keyvault key import --vault-name MyVault --name KeyName --byok-file BYOKFilePath --kty EC --curve P-256
```
The behavior of `--kty` and `--curve` paramters.
- `--kty` has the default value `RSA`
- `--curve` should be specified together with `--kty EC` …
> [KeyVault] `az keyvault key import`: Support `--curve` parameter for importing BYOK keys

- src/azure-cli/azure/cli/command_modules/keyvault/custom.py
The `base64.encodestring()` method has been deprecated since Python 3.1 and removed in Python 3.9
This fixes crash for `azure keyvault certificate download`, as described in #16318 
Please verify that `az keyvault certificate download` works as intended.
[Keyvault] az keyvault certificate download: Fix deprecated/removed method call
---
> [Keyvault] Fix #16318: az keyvault certificate download crash on Python 3.9 due to removed method call

- src/azure-cli-core/azure/cli/core/__init__.py
#16301 introduced function `_configure_knack`.
During tests, `AzCli` can be created multiple times in the same process, causing `_configure_knack` to be executed multiple times, resulting in duplicated `'azure'` entries in `cli_logger_names`:
```
['cli', 'azure', 'azure', 'azure', 'azure', ...]
```
This causes huge delay on **CLI Automation Full Test / Automation Test Python38**.
https://dev.azure.com/azure-sdk/public/_pipeline/analytics/duration?definitionId=1623&contextType=build
https://dev.azure.com/azure-sdk/public/_build/results?buildId=697879&view=results
- **Automation Test Python36**: 25m 30s
- **Automation Test Python38**: 56m 1s
Tested with Python 3.7 and it also suffers from the slowness.
This PR utilizes Python's [module …
> {Core} Config knack only once

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/_identity.py
- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/setup.py
- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/__main__.py
- src/azure-cli/azure/cli/command_modules/profile/__init__.py
- src/azure-cli/azure/cli/command_modules/profile/_help.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
- Pass `kwargs` to credentials so that `logging_enable=True` can be passed to credentials to enable unredacted HTTP logging. 
- Hide `--environment` and `--tenant-access` temporarily.
> {Identity} Beta 2.18.0.1

- src/azure-cli/azure/cli/command_modules/acr/_help.py
- src/azure-cli/azure/cli/command_modules/acr/connected_registry.py
ACR_SYNC_TOKEN_USERNAME is being deprecated from the install command group. The new value will be ACR_SYNC_TOKEN_NAME
az acr connected-registry install info -n <connected-registry-name> -r <acr-name>
az acr connected-registry install renew-credentials -n <connected-registry-name> -r <acr-name>
[ACR connected-registry] az acr connected-registry install info: Add new key ACR_SYNC_TOKEN_NAME with the same value as ACR_SYNC_TOKEN_USERNAME. A warning that the latter will be deprecated is displayed.
[ACR connected-registry] az acr connected-registry install renew-credentials: Add new key ACR_SYNC_TOKEN_NAME with the same value as ACR_SYNC_TOKEN_USERNAME. A warning that the latter will be deprecated is displayed.
--- …
> [ACR] az acr connected-registry install: deprecate ACR_SYNC_TOKEN_USERNAME from the output

- scripts/release/debian/Dockerfile
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
Resolve #15735
Tested in [build_test](https://dev.azure.com/azure-sdk/public/_build/results?buildId=700591&view=results) branch for packages.
---
> {Packaging} Bump urllib3

- src/azure-cli-core/setup.py
Fix #16416: `az login --identity` fails: load_pem_private_key() missing 1 required positional argument: 'backend'
The error is caused by a conflicting dependency on `cryptography` from [PyJWT 2.0.1](https://pypi.org/project/PyJWT/2.0.1/)
https://github.com/jpadilla/pyjwt/blob/3993ce1d3503b58cf74699a89ba9e5c18ef9b556/setup.cfg#L55
```py
cryptography>=3.3.1,<4.0.0
```
and Azure CLI
https://github.com/Azure/azure-cli/blob/6f255051203445da73c99687e64f15d58c4006a7/src/azure-cli/setup.py#L134
There is an ongoing PR https://github.com/Azure/azure-cli/pull/15687 to bump `cryptography` to the latest version. 
Also the current [MSAL 1.8.0](https://pypi.org/project/msal/) requires 
https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.8.0/setup.py#L76
``` …
```
> {Packaging} Pin PyJWT to 1.7.1

- src/azure-cli/azure/cli/command_modules/vm/_help.py
Resolve https://github.com/Azure/azure-cli/issues/16669
`vm create` example has a bug.
Create a CentOS VM with a system assigned identity. The VM will have a 'Contributor' role with access to a storage account.
Azure CLI
```
az vm create -n MyVm -g rg1 --image centos --assign-identity --scope /subscriptions/99999999-1bf0-4dda-aec3-cb9272f09590/MyResourceGroup/myRG/providers/Microsoft.Storage/storageAccounts/storage1
```
It should be
```
az vm create -n MyVm -g rg1 --image centos --assign-identity [system] --scope /subscriptions/99999999-1bf0-4dda-aec3-cb9272f09590/MyResourceGroup/myRG/providers/Microsoft.Storage/storageAccounts/storage1
```
```
az vm create -n MyVm -g rg1 --image centos --assign-identity [system] --scope …
```
> {Compute} Update vm create examples

- src/azure-cli/azure/cli/command_modules/storage/azcopy/util.py
> [Storage] Fix #16489: Upgrade azcopy to 10.8.0

- src/azure-cli/azure/cli/command_modules/acs/custom.py
This PR is updating the AKS region to Log Analytics region mapping for the Container Insights service.
Both AKS and Log analytics have added new regions since the last update and this PR makes sure that we don't default to eastus for those new regions and actually map it to its proper location.
This is the final list that has been agreed upon by talking with the AKS, LA, Networking and other teams that use the default workspace naming convention.
Scenario for testing:
Create an AKS cluster in one of the new regions with monitoring enabled (e.g. make sure the resource group is in a new region like: Norway East)
command -> 
az aks create --resource-group myResourceGroup --name myAKSCluster --node-count 1 --enable-addons monitoring
Once this command finishes …
> {AKS} AKS to LA final region map update for Azure Monitor for Containers

- src/azure-cli-core/azure/cli/core/parser.py
Previously we only match users' input command with a complete command (not including options), so command like `az blueprint -h` will not be matched with an extension command and dynamic install of the extension will not be triggered.
This PR adds support for command prefix match so that commands like `az blueprint`, `az blueprint -h` will also trigger the dynamic install of the `blueprint` extension. It also handle cases when the command matches the prefix of multiple extensions. It will prompt to let users select an extension to install.
This PR also fixes the false positive of misspelled commands by checking extension command match first. Previously, if a candidate of close match to core module command is found, the command is considered to be misspelled. It increased …
> [Extension] Support extension command prefix match for dynamic install

- src/azure-cli-core/azure/cli/core/util.py
Fix #16307
Python 3.8+ and [pytest 6.2+](https://docs.pytest.org/en/stable/usage.html#warning-about-unraisable-exceptions-and-unhandled-thread-exceptions) reveal a leaked socket at:
```
if not check_connectivity(max_retries=0):
E    ResourceWarning: unclosed <ssl.SSLSocket fd=1444, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, ...
```
---
> {Core} Don't leak socket on connectivity check

- src/azure-cli/azure/cli/command_modules/sql/_params.py
An existing property was renamed and I missed adding the ignore for the renamed version. 
---
- [x ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).
> {SQL} DW should ignore high_availability_replica_count

- src/azure-cli/azure/cli/command_modules/storage/_validators.py
Fix ICM https://portal.microsofticm.com/imp/v3/incidents/details/224946991/home
In previous code, environment variable value for connection string will have high priority compared with account key which is inputted by user input, which will cause issue for customer.
With current change, user input will be the first one to use and if no input value, we will try to get from config.
---
> {Storage} Hornor user input and add logger infomration

- linter_exclusions.yml
- src/azure-cli/azure/cli/command_modules/backup/_params.py
- src/azure-cli/azure/cli/command_modules/backup/custom_base.py
- src/azure-cli/azure/cli/command_modules/backup/custom_wl.py
Added protectable-item-type as an optional argument to az backup protectable-item list command. Now the users will be able to filter the list using a specific protectable-item-type.
az backup protectable-item list -g {rg} -v {vault} --workload-type {MSSQL/SAPHANA} --protectable-item-type {HANAInstance/SAPHanaDatabase/SAPHanaSystem/SQLAG/SQLDatabase/SQLInstance}
---
> [BACKUP] az backup protectable-item list: Add protectable-item-type as an optional argument

- src/azure-cli/azure/cli/command_modules/botservice/_params.py
- src/azure-cli/azure/cli/command_modules/botservice/tests/latest/recordings/test_update_bot_should_raise_mutuallyexclusiveargumenterror.yaml
- src/azure-cli/azure/cli/command_modules/botservice/tests/latest/test_bot_commands.py
- src/azure-cli/azure/cli/command_modules/botservice/webappv4.template.json
There is a request from BotFramework PM team to rename the argument --encryption-off to --cmk-off which maps to the azure portal experience.
The ARM template for Bot Service is also update to reflect the latest generated schema changes.
```
// Disables CMK encryption.
az bot update --name <BotResourceName> --resource-group <ResourceGroupName> --cmk-off
```
---
> [Botservice] az bot update: Renaming Encryption-OFF arg to CMK-OFF and updating api version

- .github/CODEOWNERS
The current `CODEOWNERS` only has @msyyc for help-related files. In case of out-of-office, PRs requiring approval for help-related files (e.g. https://github.com/Azure/azure-cli/pull/16707) cannot be merged.
Note that 
```
src/azure-cli/azure/cli/command_modules/search/
```
doesn't have an owner, so 
```
src/azure-cli/azure/cli/command_modules/search/_help.py
```
will need approval from @msyyc.
> {Misc.} Update CODEOWNERS - add backup owner for help

- src/azure-cli-core/azure/cli/core/_identity.py
Do not set `logging_enable` for Azure Identity credentials.
```
az login
```
> {Identity} Do not set logging_enable for Azure Identity credentials

- src/azure-cli-core/azure/cli/core/extension/_index.py
We're seeing increasing failures of `Test Extensions Loading Python36` task in CI when downloading the extension index file. Add retry to mitigate the issue while we trying to figure out the root cause.
---
> {Extension} Add retry when getting extension index

- src/azure-cli/azure/cli/command_modules/backup/_format.py
- src/azure-cli/azure/cli/command_modules/backup/commands.py
- src/azure-cli/azure/cli/command_modules/backup/custom.py
- src/azure-cli/azure/cli/command_modules/backup/custom_afs.py
- src/azure-cli/azure/cli/command_modules/backup/custom_base.py
Added start time and end time in UTC format in the output of the show-log-chain command when outputted in table format.
az backup recoverypoint show-log-chain -g {rg} -v {vault} -c {container_name} -i {item_name} -o table
---
> [BACKUP] az backup recoverypoint show-log-chain: Added start/end time in show-log-chain table output

- build_scripts/windows/Product.wxs
This setting will make the installer on Windows go faster. Its used by many other products with lots of files like Visual Studio. I tested it and saw it take 13 seconds off the clean install time on my machine.
> {Misc.} Use MSIFASTINSTALL

- src/azure-cli/azure/cli/command_modules/vm/_actions.py
Resolve https://github.com/Azure/azure-cli/issues/11767
A recent update of Azure Python SDK throws `azure.core.exceptions.ResourceNotFoundError` instead of `msrestazure.azure_exceptions.CloudError`
---
> [Compute] az vm (extension) image list: Make it more robust

- src/azure-cli-core/setup.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
Bump ADAL to 1.2.6 to incorporate 
https://github.com/AzureAD/azure-activedirectory-library-for-python/pull/246: Make ADAL compatible with PyJWT 1 & 2
> {Packaging} Bump ADAL to 1.2.6

- src/azure-cli/azure/cli/command_modules/keyvault/commands.py
- src/azure-cli/azure/cli/command_modules/keyvault/custom.py
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
- `roleName` is the name of a role, which is provided by user as the display name.
- `roleDefinitionName` is the name of a role definition, which is a GUID. It's called `roleDefinitionName` in the request body while is called `name` in response.
**This pr provides two improvements**
1. In the current command output of `az keyvault role assignment list`, the `roleDefinitionName` actually is `roleName`, this pr fixes the problem.
previously
now
2. Besides, the pr provides another column for the table view of command `az keyvault role definition list`, so that users won't be confused by the two names.
previously
now
[Component Name 2] az command b: …
> [KeyVault] BREAKING CHANGE: `az keyvault role assignment/definition list`: `roleDefinitionName` should be `roleName` in command output

- src/azure-cli/azure/cli/command_modules/storage/sdkutil.py
Fix #14054 
In previous design, if `get_sdk` can't find the dependency, the default behavior will return `None`. This will cause follow-up questions if `None` is not handled.
This PR exposes the real exception while getting sdk, which is `ModuleNotFoundError`
- Steps
Rename azure.multiapi.storage package(to azure.multiapi.storagev1 for example) to reproduce issue #14054 
Run `az storage container create -n testing`
- Before:
```
> az storage container create -n ystesting
'NoneType' object has no attribute '__name__'
File "D:\workspace\ysenv\lib\site-packages\knack\cli.py", line 233, in invoke
File …
```
> [Storage] Fix #14054: 'NoneType' object has no attribute '__name__'

- src/azure-cli/azure/cli/command_modules/vm/_validators.py
Resolve https://github.com/Azure/azure-cli/issues/16859
while using license-type in create VMSS, we are getting error
az : ValidationError: usage error: --license-type is only applicable on Windows VM scaleset
---
> [Compute] vmss create: Fix a license type issue

- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/_validators.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_download_directory.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_blob_scenarios.py
Fix #16679 
Add file path validator to `az storage blob download`
`az storage blob download -f /path/of/directory`
---
> [Storage] Fix #16679: `az storage blob download` fails with "Permission denied" if the destination file is a directory

- src/azure-cli/azure/cli/command_modules/backup/custom_base.py
Enabled Alternate Location Restore for SQL/SAPHANA protected items
---
> [Backup] BugFix: Enabled Alternate Location Restore for SQL/SAPHANA protected items

- src/azure-cli/azure/cli/command_modules/monitor/_help.py
- src/azure-cli/azure/cli/command_modules/monitor/_params.py
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_log_analytics_workspace_saved_search.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_log_analytics_workspace.py
closed https://github.com/Azure/azure-cli-extensions/issues/2635
---
> {monitor} Fix `az monitor workspace saved-search` examples

- src/azure-cli/azure/cli/command_modules/monitor/_params.py
> {monitor} Update help message for `--tables` parameter in command group `az monitor log-analytics workspace data-export`

- src/azure-cli-core/azure/cli/core/parser.py
In the case of running `az --debug a`, the `command_str` got with `command_str = roughly_parse_command(args[1:])` is empty so the `_search_in_extension_commands` function will return all extensions with a prefix match.  Users are then prompted to choose an extension to install from all extensions.
To fix the issue, this PR adds empty check for `command_str` to return None for empty value.
Run `az --debug a`.
---
> {Core} Add check for empty command_str in _search_in_extension_commands

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/commands.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
Per request, the deprecation warning for az openshift reference content needs to be updated.
> [OpenShift] update of az openshift deprecation warning

- src/azure-cli/azure/cli/command_modules/ams/_params.py
- src/azure-cli/azure/cli/command_modules/ams/tests/latest/recordings/test_ams_create_show.yaml
- src/azure-cli/azure/cli/command_modules/ams/tests/latest/recordings/test_ams_encryption_set_show.yaml
- src/azure-cli/azure/cli/command_modules/ams/tests/latest/test_ams_account_encryption_scenarios.py
- src/azure-cli/azure/cli/command_modules/ams/tests/latest/test_ams_account_scenarios.py
The prefix `id` is ambigous and usually means resource id in CLI. Use `mi` to represent managed identity.
---
> {AMS} Rename --id-system-assigned to --mi-system-assigned

- .vscode/launch.json
- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/operations/account.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_encryption_scope_scenarios.py
> [Storage] Support double encryption for encryption scope

- src/azure-cli/azure/cli/command_modules/network/_help.py
- src/azure-cli/azure/cli/command_modules/network/_util.py
- src/azure-cli/azure/cli/command_modules/network/commands.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_cross_region_lb_address_pool.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_cross_region_lb_address_pool_addresses.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_address_pool.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_address_pool_addresses.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_nat_pools.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_nat_rules.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_probes.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_rules.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_sku.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_zone.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_load_balancer_ip_config.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_load_balancer_outbound_rules.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic_app_gateway.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic_lb_address_pools.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_private_endpoints.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
https://github.com/Azure/azure-cli/issues/17071
replace 'zone=[1,2,3]' with 'zone=null' to avoid breaking change for existing cmd.
test_network_lb_sku
test_network_private_endpoints
test_network_lb_zone
test_network_cross_region_lb_address_pool
test_network_cross_region_lb_address_pool_addresses
test_network_lb
test_network_load_balancer_ip_config
test_network_lb_nat_rules
test_network_lb_nat_pools
test_network_lb_address_pool
test_network_lb_address_pool_addresses
test_network_lb_probes
test_network_lb_rules
test_network_nic
test_network_nic_app_gateway
test_network_nic_lb_address_pools
[Component Name 2] az command b: Add some customer-facing …
> {Network} workaround for load balancers about change of 'zone'

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_vnetSubnetId.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Fix #12150 by adding support for subnet ID.
az network vnet create -g myresourcegroup -n myvnet --address-prefix 10.0.0.0/16 --subnet-name mysubnet --subnet-prefix 10.0.0.0/24
az appservice plan create -g myresourcegroup  -n myappplan --sku P1V2
az webapp create -g myresourcegroup   -n myuniquewebapp --plan myappplan 
webapp vnet-integration add -g myresourcegroup -n myuniquewebapp  --vnet myvnet --subnet '/subscriptions/[subid]/resourceGroups/myresourcegroup/providers/Microsoft.Network/virtualNetworks/myvnet/subnets/mysubnet'
[AppService] Fix #12150 Support for subnet ID in vnet-integration add
---
> [AppService] Fix #12150 Support for subnet ID in vnet-integration add

- src/azure-cli/azure/cli/command_modules/appservice/resources/LinuxFunctionsStacks.json
- src/azure-cli/azure/cli/command_modules/appservice/resources/WindowsFunctionsStacks.json
This is a stacks update. We're adding taking Node 14 apps out of preview.
Resolves https://github.com/Azure/Azure-Functions/issues/1745
Resolves https://github.com/Azure/azure-cli/issues/15407
These don't change any functionality, just the json the create function uses to know the available options.
[AppService] az functionapp create: Removed preview flag from Node.js 14.
---
> [AppService] functionapp: Take Node.js 14 out of preview

- requirements.txt
Bump [setuptools](https://pypi.org/project/setuptools/) to 52.0.0 for Python 3.9 support.
On Python 3.9, `pip install -e D:\cli\azure-cli/src/azure-cli-telemetry --no-deps` fails with setuptools 40.0.0:
```
Obtaining file:///D:/cli/azure-cli/src/azure-cli-telemetry
ERROR: Command errored out with exit status 1:
command: 'D:\cli\env39\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\cli\\azure-cli\\src\\azure-cli-telemetry\\setup.py'"'"'; __file__='"'"'D:\\cli\\azure-cli\\src\\azure-cli-telemetry\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base …
```
> {Packaging} Bump setuptools to 52.0.0

- build_scripts/windows/scripts/build.cmd
- scripts/release/debian/build.sh
Upgrade pip version to `21.0.1` in bundled Python to solve some extension install/usage issues like https://github.com/Azure/azure-cli/issues/16858
`az devops login` will use CLI's pip to install `keyring` in extension directory and it depends on `cryptography`. On Ubuntu, it can be solved by upgrading pip as shown in this [comment](https://github.com/Azure/azure-cli/issues/16858#issuecomment-776266256).
The package built with the change can be downloaded [here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=753108&view=results). Install the package and test installing an extension that depends on `cryptography` with no upper bound on Ubuntu. For instance:
`az extension add --source …
> {Packaging} Upgrade pip version in bundled Python

- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli/azure/cli/command_modules/util/_params.py
- src/azure-cli/azure/cli/command_modules/util/custom.py
Allow configuring theme from `core.theme`.
```powershell
az config set core.theme=dark
az demo style
az group lsit
az config set core.theme=light
az demo style
az group lsit
```
> [Style] Allow configuring theme

- src/azure-cli/azure/cli/command_modules/appconfig/_params.py
- src/azure-cli/azure/cli/command_modules/appconfig/commands.py
1. Updated the help message for identity commands to clarify default behavior. 
2. Removed preview tags for everything except:
- `--enable-public-network` argument : Need more clarity on the required default behavior.
- `az appconfig feature filter` command group : Waiting for wider adoption and usage for this group.
---
> {AppConfig} Remove preview tags for some commands

- doc/quoting-issues-with-powershell.md
Close #16940
Add instruction on reading from `stdin` in PowerShell so that users can bypass PowerShell's interpretation issues (#15529) and pass JSON to a command more easily.
A debug command `az debug echo` is also added to help debug shell interpretation issues:
```powershell
> az debug echo '{"a":"b"}'
{a:b}
> az debug echo '{\"a\":\"b\"}'
{"a":"b"}
```
> {Doc} Add instruction on reading from stdin in PowerShell

- src/azure-cli/azure/cli/command_modules/backup/_params.py
- src/azure-cli/azure/cli/command_modules/backup/custom.py
- src/azure-cli/azure/cli/command_modules/backup/custom_base.py
az backup protection check-vm command had only --vm-id as input parameter. To make it consistent with other commands added --vm and --resource-group as optional parameters.
az backup protection check-vm --resource-group {rg_name} --vm {vm_name/vm_id}
---
> [BACKUP] az backup protection check-vm: Add vm and resource-group as optional params

- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_virtual_network.py
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands_mysql.py
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands_postgres.py
RDBMS tests frequently fail (like in #17127):
https://dev.azure.com/azure-sdk/public/_build/results?buildId=759999&view=logs&j=74095127-2a27-5370-37ed-15a4193f243f&t=5cf5f89a-09fb-583c-72e4-4e4427c89fb1&l=167520
```
=================================== FAILURES ===================================
_ FlexibleServerVnetMgmtScenarioTest.test_postgres_flexible_server_vnet_mgmt_supplied_vname_and_subnetname _
...
self = <azure.mgmt.resource.resources.v2020_10_01.operations._resource_groups_operations.ResourceGroupsOperations object at 0x7ff337899828>
...
E           msrestazure.azure_exceptions.CloudError: Azure Error: SubscriptionNotFound
E           Message: The subscription '00000000-0000-0000-0000-000000000000' could not be found.
```
When `virtual_networks.begin_create_or_update` is not …
> {RDBMS} Fix tests by waiting for Long Running Operations

- scripts/release/rpm/azure-cli.spec
Upgrade pip version to `21.0.1` in bundled Python to solve some extension install/usage issues like #16858
This PR continues on from the work done in https://github.com/Azure/azure-cli/pull/17091, also upgrading pip for RPM distros such as CentOS.
Verify the new pip version by checking the installation: `/usr/lib64/az/lib/python3.6/site-packages/pip-21.0.1.dist-info`.
You can also verify the issue no longer exists by installing the `azure-devops` extension and using `az devops login`.
---
> {Packaging} Upgrade pip version in RPM

- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/adal_authentication.py
- src/azure-cli-core/azure/cli/core/azclierror.py
Refine the error message reported by #16209, #16641, #17142.
In the current code, wrapping `adal.AdalError` and rephrasing the error message actually doesn't provide more information. Instead, it leaves the original server error unexposed.
| error code | CLI error  | server error |
| - | - | - |
| `AADSTS70008` | Credentials have expired due to inactivity. | https://login.microsoftonline.com/error?code=70008 | 
| `AADSTS50079`	| Configuration of your account was changed. | https://login.microsoftonline.com/error?code=50079
| `AADSTS50173` | The credential data used by CLI has been expired because you might have changed or reset the password. | https://login.microsoftonline.com/error?code=50173
This PR 
1. wraps `adal.AdalError` in `AuthenticationError` with the original server error …
> [Core] Unify ADAL and MSAL error handler

- scripts/ci/dependency_check.sh
- scripts/install_full.sh
- scripts/release/debian/Dockerfile
- scripts/release/debian/build.sh
- scripts/release/debian/prepare.sh
- scripts/release/rpm/Dockerfile.centos
- scripts/release/rpm/Dockerfile.fedora
- scripts/release/rpm/azure-cli.spec
- scripts/release/rpm/build.sh
- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- Revert `scripts/ci/` to make push build pipeline pass (`PyGObject`-related dependencies are currently not installed)
- Fix `get_msal_token` related code corrupted due to merge conflicts
> {Beta} Revert scripts/ci/

- src/azure-cli/azure/cli/command_modules/acr/custom.py
> [acr] output a trace in "az acr login" for self-diagnosing potential docker command latency

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
#17207 
`az webapp log config -n myapp --resource-group myrg --application-logging filesystem --level information`
---
> [AppService]: fix #17207 - for az webapp log config 'level' always defaults to verbose

- src/azure-cli/azure/cli/command_modules/vm/custom.py
Fixes #16585 deserialization error when users pass in multiple instance ids
---
> [Compute] Fix #16585: az vmss deallocate --instance-ids failed

- .github/CODEOWNERS
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns.yaml
> {CI} Update CODEOWNERS(Do not merge)

- src/azure-cli/azure/cli/command_modules/acs/_client_factory.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
This PR fixes two errors:
- Currently, the MSI client is created using current context's subscription, which is incorrect when the identity is in another subscription. 
- The checking for MSI cluster is incorrect when attaching ACR, type "UserAssigned" managed cluster is not treated as MSI cluster.
---
> [AKS] Fix cross-sub assigning identity error and attach acr error

- README.md
Copied the instructions from [vscode-azurecli](https://github.com/microsoft/vscode-azurecli/blob/main/README.md) to the `azure-cli` main REDAME to increase the tool's publicity.
---
> {Doc} Add instructions to write and run commands in VS Code with the Azure CLI Tool

- src/azure-cli/azure/cli/command_modules/util/custom.py
Resolve #16952
The issue was caused by reloading the `azure.cli.core` python module to get the new version after upgrade, it depends on modules in `knack`. The new loaded `azure.cli.core` depends on new code of a new `knack` version: `from knack.util import status_tag_messages`, but `knack.util` is not reloaded, causing the issue of `ImportError`.
There are two ways to solve this issue:
1. Reload all loaded modules in `sys.modules` starting with `knack` such as `knack.util`, `knack.log`. Note that `knack` and `knack.util` are 2 items in `sys.modules`, simply reloading `knack` will not fix the `ImportError` with `from knack.util import status_tag_messages`.
2. Use `subprocess` to get `az version` to avoid calling cached modules in the same Python Interpreter.
This PR uses …
> [Upgrade] Fix 16952: Fix ImportError after upgrade

- src/azure-cli/azure/cli/command_modules/config/_help.py
- src/azure-cli/azure/cli/command_modules/configure/_help.py
1. Users are complaining `az config` can't be found: https://github.com/MicrosoftDocs/azure-docs-cli/issues/2469, https://github.com/MicrosoftDocs/azure-docs-cli/issues/2465
2. Redirect users from `az configure` to `az config`
```
az configure --help
az config --help
```
**Additional Context**
Another issue https://github.com/Azure/azure-cli/issues/17261 is opened to instruct user to upgrade to the latest version if a command (group) is not found.
> {Config} Redirect users from `az configure` to `az config`

- src/azure-cli/azure/cli/command_modules/monitor/operations/metric_alert.py
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_metric_alert_v2_scenario.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_metric_alert_scenarios.py
Closed https://github.com/Azure/azure-cli/issues/17268
`webhook_properties` property has been renamed in SDK. In order to avoid this kind of breaking change, I rewrite the code to eliminate the dependency on this property.
---
> {Monitor} `az monitor metrics alert update`: fix update action issue

- azure-pipelines.yml
- build_scripts/windows/scripts/build.cmd
`azure-cli` does not use `aio` files in azure management SDKs. `dist-info` is not used in MSI for installation or update. Remove them in this PR.
This PR also adds back the MSI test task to resolve #9270
---
> {Packaging} Remove aio and dist-info folders in MSI

- src/azure-cli/azure/cli/command_modules/acr/_stream_utils.py
This pr is to fix #16700 
az acr build --cmd "docker images" /dev/null 
before the fix, the command may output BlobNotFound error sometimes.
after the fix, the command will not output BlobNotFound error.
---
> [ACR] Fix#16700: Use "exists" api to check storage blob existence

- src/azure-cli/azure/cli/command_modules/sql/custom.py
We found out that command `log-replay start` was not working with `-a` flag because of bug. This pr is fixing typo
```auto_complete -> auto_complete_restore```
> {Sql} Fix typo for one of the parameters

- src/azure-cli/azure/cli/command_modules/feedback/custom.py
The previous implementation had 3 bugs:
- `IndexError` when only 1 line in `error_string` [example: #11889];
- infinite loop when repeatedly can't strip down `error_string`;
- ", ln" instead of ", in" in one matching expression that rendered it useless.
Also the logic itself was "magical": it removed 4 lines at a time, starting from a middle line but if possible (never successfully) from a line before that has an exception start in it...
This change should fix all these problems.
> {Feedback} Fix feedback minification

- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/_params_azure_stack.py
> {Storage} Fix 17220: Refine help

- .github/CODEOWNERS
- src/azure-cli/azure/cli/command_modules/backup/custom.py
Fixed --force parameter functionality for az backup vault delete command. Earlier it was only deleting AzureIaaSVM backup management type items. Thereby giving 'Vault cannot be deleted as there are existing resources within the vault' error. Added functionality to delete AzureWorkload and AzureStorage backup management type items and to unregister the respective containers too.
az backup vault delete -n {vault_name} -g {rg_name} --force
---
> [BACKUP] Fix #14776: Fix --force parameter functionality for az backup vault delete command 

- src/azure-cli/azure/cli/command_modules/appconfig/_kv_helpers.py
Fix [#491](https://github.com/Azure/AppConfiguration/issues/491)
PyYAML parser has a default width of 80 characters per line for output dumping. In order to output long string values in the same line without wrapping, we need to set the `width` option to an arbitrarily high number in `yaml.safe_dump()` call.
1. Create a key in AppConfig with a very long string value like ""a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a …
> [AppConfig] Configure max line width for YAML parser to stop wrapping output

- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/commands/__init__.py
- src/azure-cli-core/azure/cli/core/commands/arm.py
- src/azure-cli-core/azure/cli/core/extension/operations.py
- src/azure-cli-core/azure/cli/core/tests/test_add_resourcegroup_transform.py
- src/azure-cli-core/azure/cli/core/tests/test_parser.py
- src/azure-cli-core/azure/cli/core/tests/test_storage_validators.py
- src/azure-cli-core/azure/cli/core/util.py
Because of the deprecation of Python 2 support (https://github.com/Azure/azure-cli/pull/11363), drop `six`.
> {Misc} Drop `six` from core

- src/azure-cli/azure/cli/command_modules/vm/custom.py
Description
Resolve #16824
[Compute] When users use --email but don't use --webhook, remind users that these two parameters need to be set together.
Testing Guide
History Notes
> {Compute} Update function of auto_shutdown_vm

- .azure-pipelines/templates/azdev_setup.yml
- build_scripts/windows/scripts/build.cmd
- scripts/ci/test_extensions.sh
`az extension add -n rdbms-connect` failed with the latest MSI. It's caused by the removal of  `dist-info` folder of `setuptools`, 
failing the installation of the `configobject` package from source code. The `entry_points.txt` file under `dist-info` folder of `setuptools` is needed during python source package installation. Without it, the following error will be thrown:
> Running command python setup.py egg_info
>     C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
>     usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>        or: setup.py --help [cmd1 cmd2 ...]
>        or: setup.py --help-commands
>        or: setup.py cmd --help
>     error: invalid command …
> {Packaging} Hotfix: Only remove `dist-info` for azure packages in MSI

- src/azure-cli/azure/cli/command_modules/resource/_bicep.py
Added a conditional during Bicep CLI installation to send install messages to logger for an "auto install" while still printing messages to stdout for a manual install (az bicep install)
[ARM] Fix #17379: bicep auto install results in invalid json output from deployment
---
> [ARM] Fix #17379: bicep auto install results in invalid json output from deployment

- .github/CODEOWNERS
- src/azure-cli/azure/cli/command_modules/feedback/_help.py
Fix #17393
The current `az feedback` help message is very vague.
```
> az feedback -h
Command
az feedback : Send feedback to the Azure CLI Team!
```
This PR refines the help message to explicitly explain what `az feedback` does.
```
> az feedback -h
Command
az feedback : Send feedback to the Azure CLI Team.
This command is interactive. If possible, it launches the default web browser to open GitHub
issue creation page with the body auto-generated and pre-filled. You will have a chance to
edit the issue body before submitting it.
```
> {Feedback} Explain what `az feedback` does

- src/azure-cli-core/azure/cli/core/azclierror.py
- src/azure-cli-core/azure/cli/core/azlogging.py
- src/azure-cli-core/azure/cli/core/tests/test_parser.py
- src/azure-cli-core/azure/cli/core/util.py
- src/azure-cli/azure/cli/command_modules/feedback/tests/latest/test_feedback.py
Adapt to https://github.com/microsoft/knack/pull/228: [Log] `CLILogging.configure` returns as early as possible
`az feedback` no longer works with knack `dev` branch:
```
> azdev test feedback
src\azure-cli\azure\cli\command_modules\feedback\tests\latest\test_feedback.py:130: in _helper_test_log_contents_correct
self.assertEqual(command_log_files[1].get_command_status(), "SUCCESS")
E   AssertionError: '' != 'SUCCESS'
E   + SUCCESS
```
In `pytest` environment, `pytest` will configure the `root` logger to capture all logs. 
- The old knack always forcibly set `root` logger level to `DEBUG`.
- The new knack can detect that and it leaves `pytest` `root` logger as is (https://github.com/microsoft/knack/pull/228).
In such case, we have to manually set `az_command_data_logger`'s level to …
> {Log} Adapt az_command_data_logger to Knack 0.8.0

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
Fix `az webapp config ssl bind` using the wrong ssl cert to bind
If app has multiple ssl certs, `az webapp config ssl bind` uses the wrong one
---
> [AppService] Fixes #17219: Fix ssl bind bug

- .azure-pipelines/templates/azdev_setup.yml
> {pipeline} Update azdev to version 0.1.30

- scripts/ci/test_extensions.sh
CI failure https://dev.azure.com/azure-sdk/public/_build/results?buildId=801336&view=logs&j=34631516-3f1c-501b-e428-6ea670d20b1c&t=4ecab084-061a-520a-6791-4f5413067b6d&l=1816
```
File "/opt/az/azcliextensions/arcappliance/azext_arcappliance/pkg/resource/logic/util.py", line 5, in <module>
from jsonschema import validate, ValidationError
File "/opt/az/azcliextensions/azure-iot/jsonschema/__init__.py", line 33, in <module>
__version__ = get_distribution(__name__).version
...
File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/pkg_resources/__init__.py", line 784, in resolve
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'jsonschema' distribution was not found and is required by the application
```
This can also be reproed locally. …
> {CI} Restore `az self-test`

- .github/CODEOWNERS
- src/azure-cli-core/azure/cli/core/util.py
Resolve #16931
`interactive` is written in a special way that it is an `azure-cli` module, but it will install the `interative` extension for starting an interactive shell. With the use of [command index](https://github.com/Azure/azure-cli/pull/13294), `interactive` command group only loads the `interactive` module and not `azext_interactive` module as the extension has 0 command. That's why `reload_module` will throw `KeyError` when trying to reload `azext_interactive` after updated. 
This PR adds check whether the module is already imported before reloading it.
1. Install an old version of `interactive`
`az extension add --upgrade -n interactive --version 0.4.3`
2. Run the command to update `interactive`
`az interactive --update` …
> [Interactive] Fix #16931: Fix `KeyError` in `az interactive --update`

- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/commands/__init__.py
- src/azure-cli-core/azure/cli/core/commands/progress.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_custom.py
This PR is one part for progress bar project.
As we already in beta version for several months, I plan to move indeterminate progress bar with spinner to all long running operation in azure cli as shown below:
But I have to mention for commands like `network vnet create`, which is long running operation, but not hornor CLI `LongRunningOperation` class, will not have progress bar.
`az vm create`
---
> [Core] Add spinner progress bar for long running operation

- src/azure-cli-core/azure/cli/core/commands/client_factory.py
- src/azure-cli/azure/cli/command_modules/storage/_client_factory.py
Make `_prepare_client_kwargs_track2` public so that it can be used by Track 2 data-plane SDKs, like `azure-storage`.
> {Core} Make `_prepare_client_kwargs_track2` public

- src/azure-cli/azure/cli/command_modules/rdbms/_client_factory.py
- src/azure-cli/azure/cli/command_modules/rdbms/_params.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_mysql.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_virtual_network.py
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands.py
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands_mysql.py
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands_postgres.py
PG and MySQL servers can allow private access to VNET from different subscription
az postgres flexible-server create -g test-rg -n test-server --subnet /subscriptions/<different_subscription_id>/resourceGroups/<rg>/providers/Microsoft.Network/virtualNetworks/<vneet_name>/subnets/<subnet_name>
---
> [RDBMS] Allowing DB server private access from different subscription

- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_create_delete_backup.yaml
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_delete_account_backup.yaml
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_disable_backup_for_volume.yaml
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_get_account_backup.yaml
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_get_backup_by_name.yaml
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_list_account_backups.yaml
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_list_backup.yaml
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_restore_backup_to_new_volume.yaml
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_update_backup.yaml
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/test_account_backup_commands.py
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/test_backup_commands.py
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/test_vault_commands.py
No changes to the CLI only fixed all Backup tests and gathered new recordings for them. The backup tests have not been functioning correctly due to CBS still being developed. Now they are stable.
---
> [NetAppFiles] Updated backup tests

- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
Enable aadds for file will need Domain Service deployed, which is not easy to deploy successfully via command and only one domain service is allowed in one tenant. Typically if we want to enable it, we will deploy via Portal and then delete it on demand because it is expensive, too.
Here is to mark related tests with `record_only()` to make sure it run on demand with Domain Service configured. 
---
> {storage} Add record_only() for tests needing additional configuration

- .azure-pipelines/templates/azdev_setup.yml
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
Per #16611, bump versions:
- [bcrypt 3.2](https://pypi.org/project/bcrypt/3.2.0/)
- [PyNaCl 1.4](https://pypi.org/project/PyNaCl/1.4.0/)
so that they can be installed on Windows with Python 3.9, without the dependency on **Microsoft Visual C++**.
> {Packaging} Bump bcrypt and PyNaCl

- src/azure-cli-core/azure/cli/core/util.py
- src/azure-cli-core/setup.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
We are seeing countless users complaining they have stumbled on [Quoting issues with PowerShell](https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md).
All issues received: https://github.com/Azure/azure-cli/issues?q=is%3Aissue+label%3A%22Shell+-+PowerShell%22
This PR refines the error message of JSON parsing error:
- Echo the JSON received by CLI
- Provide recommendation for all shells
- Provide recommendation especially for PowerShell
- Use the new `InvalidArgumentValueError` to replace `CLIError`
Before:
```sh
> az monitor diagnostic-settings create --logs '{"category":"QueryRuntimeStatistics"}'
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```
After:
```sh
> az monitor diagnostic-settings create --logs …
```
> [Core] Provide recommendation for JSON parsing error

- .vscode/launch.json
- src/azure-cli/azure/cli/command_modules/servicefabric/_client_factory.py
- src/azure-cli/azure/cli/command_modules/servicefabric/_help.py
- src/azure-cli/azure/cli/command_modules/servicefabric/_params.py
- src/azure-cli/azure/cli/command_modules/servicefabric/_sf_utils.py
- src/azure-cli/azure/cli/command_modules/servicefabric/_validators.py
- src/azure-cli/azure/cli/command_modules/servicefabric/commands.py
- src/azure-cli/azure/cli/command_modules/servicefabric/operations/managed_applications.py
- src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/recordings/test_managed_app_type.yaml
- src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/recordings/test_managed_app_type_version.yaml
- src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/recordings/test_managed_application.yaml
- src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/recordings/test_managed_service.yaml
- src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/test_sf_managed_application.py
- src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/test_util.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
These cmdlets will support a New offering (resource type) - Service Fabric managed clusters for our customers. In this new model, Service Fabric resource provider (SFRP) manages the entire resource group for the essential components of the cluster, including VMSS, VNet/Load Balancer and storage account for diagnostics and bootstrap. These commands are to support the creation and management applications, applicationtypes, applicationtypeversions and services on the new service fabric managed clusters.
see src\azure-cli\azure\cli\command_modules\servicefabric\_help.py for examples and descriptions
- [Service Fabric] Adding commands for managed applications, application types, application type versions and services.
- sf …
> [Service Fabric] Add managed application cli commands

- src/azure-cli/azure/cli/command_modules/appservice/resources/LinuxFunctionsStacks.json
Azure Functions team plan to release Python 3.9 for GA. We want to remove the preview flag for python 3.9 in functionapp create --help.
Test with ```az functionapp create --help```. The help content contains
```
--runtime-version                    : The version of the functions runtime stack. Allowed
values for each --runtime are: node -> [8, 10, 12, 14
(preview)], java -> [8, 11], powershell -> [7.0], python
-> [3.6, 3.7, 3.8, 3.9].
```
[AppService]  Remove preview flag for Python 3.9 in create function app command
---
> [AppService] Remove preview flag for Python 3.9  in functionapp create

- src/azure-cli-core/azure/cli/core/tests/test_util.py
- src/azure-cli-core/azure/cli/core/util.py
`src/azure-cli-core/azure/cli/core/tests/test_util.py::TestUtils::test_open_page_in_browser` fails on WSL:
```py
_mock_self = <MagicMock name='open' spec='function' id='139689703216128'>, args = ('http://foo', 2), kwargs = {}
self = <MagicMock name='open' spec='function' id='139689703216128'>
msg = "Expected 'open' to be called once. Called 0 times."
def assert_called_once_with(_mock_self, *args, **kwargs):
"""assert that the mock was called exactly once and that that call was
with the specified arguments."""
self = _mock_self
if not self.call_count == 1:
msg = ("Expected '%s' to be called once. Called %s times.%s"
% (self._mock_name or 'mock',
self.call_count,
self._calls_repr()))
>           raise AssertionError(msg)
E           AssertionError: Expected 'open' to be …
```
> {Core} Fix `test_open_page_in_browser` on WSL

- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
Fix: `test_credscache_good_error_on_file_corruption` fails when run in parallel with other tests
CI failure:
https://dev.azure.com/azure-sdk/playground/_build/results?buildId=806624&view=logs&j=abe8eae2-a613-5a65-3eeb-3e8a13573181&t=ff49c02d-6a40-524c-c9b1-98f6bb13c7f4&l=2248
```
__________ TestProfile.test_credscache_good_error_on_file_corruption ___________
[gw0] linux -- Python 3.8.8 /home/vsts/work/1/s/env/bin/python
self = <azure.cli.core.tests.test_profile.TestProfile testMethod=test_credscache_good_error_on_file_corruption>
get_file_json_mock = <function get_file_json at 0x7f723502fee0>
@mock.patch('azure.cli.core._profile.get_file_json', autospec=True)
def test_credscache_good_error_on_file_corruption(self, get_file_json_mock):
get_file_json_mock.side_effect = ValueError('a bad …
```
> {Core} Fix: `test_credscache_good_error_on_file_corruption` fails when run in parallel with other tests

- src/azure-cli/azure/cli/command_modules/role/custom.py
Fix [IcM 232405459](https://portal.microsofticm.com/imp/v3/incidents/details/232405459/home): Running az ad sp create-for-rbac results in failure
`az ad sp create-for-rbac` fails with:
```
Error: One or more properties contains invalid values.
```
For example:
```
ad sp create-for-rbac -n sp-prod --skip-assignment
```
CLI first checks the existence of the Service Principal by searching for Service Principal whose `servicePrincipalNames` contains `http://sp-prod`:
https://github.com/Azure/azure-cli/blob/50ccb24528eb36529d1432808f3ff385cc4c04aa/src/azure-cli/azure/cli/command_modules/role/custom.py#L1414
Normally, the result will look like:
```
"servicePrincipalNames": [
"http://sp-prod",
"1f440000-0000-0000-0000-000000000000"
]
```
Under some unknown cases, in AAD's response of a Service …
> {Role} `az ad sp create-for-rbac`: Fix "One or more properties contains invalid values"

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
In some apps with only single publish profile, API doesn't return a list and`az webapp deployment source config-zip` breaks
Run `az webapp deployment source config-zip` on a webapp that only has a single publish profile, the command will error out.
The behaviour will not be changed if the webapp has multiple publish profiles
---
> [AppService] Bugfix: Handle if only single publish profile is returned

- src/azure-cli/azure/cli/command_modules/acr/connected_registry.py
Change the output into connection string for acr connected-registry install command.
Remove old output vars, and check the parent gateway endpoint to use a place holder for an empty string (dynamic parent login server).
az acr connected-registry install info -n -r
az acr connected-registry install renew-credentials -n -r
[ACR] BREAKING CHANGE: az acr connected-registry install info: Replace keys ACR_REGISTRY_NAME, ACR_SYNC_TOKEN_NAME, ACR_SYNC_TOKEN_PASSWORD, ACR_PARENT_GATEWAY_ENDPOINT, and ACR_PARENT_PROTOCOL with a new connected string key, ACR_REGISTRY_CONNECTION_STRING.
[ACR] BREAKING CHANGE: az acr connected-registry install renew-credentials: Replace keys ACR_REGISTRY_NAME, ACR_SYNC_TOKEN_NAME, ACR_SYNC_TOKEN_PASSWORD, …
> [ACR] 'az acr connected-registry install info/renew-credentials': Provide connection string in installation command

- src/azure-cli/azure/cli/command_modules/container/custom.py
This pull request fixes issue [16499](https://github.com/Azure/azure-cli/issues/16499)
The implementation of 'az container create' is expecting the wrong return value from NetworkProfilesOperations.create_or_update().
NetworkProfilesOperations.create_or_update() is documented here:
https://docs.microsoft.com/en-us/python/api/azure-mgmt-network/azure.mgmt.network.v2020_06_01.operations.networkprofilesoperations?view=azure-python#create-or-update-resource-group-name--network-profile-name--parameters----kwargs-
As described in issue 16499, run a command similar to the following using an empty resource group:
`
az container create --registry-username reguser 
--location eastus 
--registry-password regpassword 
--name container-name 
--resource-group …
> [Container] Fix #16499: az container create: fix handling of return value from network_profiles.create_or_update

- src/azure-cli/azure/cli/command_modules/storage/_help.py
- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/_transformers.py
- src/azure-cli/azure/cli/command_modules/storage/commands.py
- src/azure-cli/azure/cli/command_modules/storage/operations/file.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_share_rm_with_snapshot.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_file_rm_scenarios.py
File share management plane operations support snapshot CRD. (_List operation is not covered in this PR because list including both deleted and snapshots is not supported which is a known issue will be resolved in next api version._)
Related swagger: https://github.com/Azure/azure-rest-api-specs/pull/11372
Create: `az storage share-rm snapshot`
Show: `az storage share-rm show --snapshot`
Delete: `az storage share-rm delete --snapshot`
---
> [Storage] `az storage share-rm`: Support create/show/delete snapshots

- src/azure-cli/azure/cli/command_modules/role/custom.py
- src/azure-cli/azure/cli/command_modules/role/tests/latest/test_graph.py
Fix #14767
The retry-able check logic is firstly added by #1499:
https://github.com/Azure/azure-cli/blob/f0dcfcf5eb8413496ad7f3d4f871045d5386a099/src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py#L492
It was later changed by #2567 (not sure why the change):
https://github.com/Azure/azure-cli/blob/67d44a187229f4b3872b8fc1401144492a778f18/src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py#L508
This PR simply adds another retry-able check for 
> When using this permission, the backing application of the service principal being created must in the local tenant
just like what https://github.com/microsoft/onefuzz/pull/716 does.
With new Knack (https://github.com/microsoft/knack/pull/228):
```
> pytest …
```
> {Role} `ad sp create-for-rbac`: Retry Service Principal creation for "must in the local tenant" error

- src/azure-cli/azure/cli/command_modules/resource/_bicep.py
- src/azure-cli/azure/cli/command_modules/resource/_help.py
- src/azure-cli/azure/cli/command_modules/resource/_params.py
- src/azure-cli/azure/cli/command_modules/resource/custom.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/policy_definition_deploy_mg.bicep
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/policy_definition_deploy_sub.bicep
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/role_definition_deploy_tenant.bicep
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_bicep.py
- Closes #17390: Bicep related live test issue.
- Closes https://github.com/Azure/bicep/issues/1562: Validate scope when deploying a bicep file with Azure CLI.
- Partially addresses https://github.com/Azure/bicep/issues/2055: Bicep errors if I've hit my github api rate limit.
- Changes the `--files` parameter to `--file` to only take one file for the `az bicep build/decompile` commands, because we removed the support of multi-file compiling/decompiling support from Bicep CLI.
`az bicep build/decompile --file {bicep_file}`
[ARM] BREAKING CHANGE: az bicep build: Change the parameter --files to --file
[ARM] BREAKING CHANGE: az bicep decompile: Change the parameter --files to --file
[ARM] az bicep build: Add a parameter --outdir for …
> [ARM] BREAKING CHANGE: az bicep build/decompile: Change the --files parameter to --file

- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/msal_authentication.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
- src/azure-cli-core/azure/cli/core/tests/test_util.py
- src/azure-cli-core/azure/cli/core/util.py
Close #17521
- Return a certificate correctly when the current account (`az account show`) is a Service Principal account.
- Create `ServicePrincipalCredential` class that extends `msal.ConfidentialClientApplication` and exposes `get_token` API.
```
az login --service-principal --username <sp_id> --password <secret_or_cert> --tenant <tenant_id>
az ssh vm -g <rg_name> --vm-name <vm_name> --debug
```
> [Compute] `az ssh vm`: Support VM SSH with Service Principal

- src/azure-cli-core/azure/cli/core/extension/operations.py
Existing code will only add `Context.Default.AzureCLI.ExtensionManagementDetail` after the extension is installed. This PR extracts extension name and version from source url and add to telemetry so that these data will be sent by telemetry even when the install of extension fails.
In a virtual env, downgrade pip: `python -m pip -U pip==18.0`.
Run `az extension add -s https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.21.0-py3-none-any.whl -y`. 
The install will fail, check the telemetry record in `~/.azure/telemetry/cache`, you should see `"Context.Default.AzureCLI.ExtensionManagementDetail": "azure-cli-ml@1.21.0"`.
[Component Name …
> {Telemetry} Add telemetry info of extension even when install fail

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/linter_exclusions.yml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_with_policy_setting.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_update_policy.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
> [Compute] add VMSS Rolling Upgrade opt

- src/azure-cli/azure/cli/command_modules/acr/_help.py
- src/azure-cli/azure/cli/command_modules/acr/_params.py
- src/azure-cli/azure/cli/command_modules/acr/_utils.py
- src/azure-cli/azure/cli/command_modules/acr/commands.py
- src/azure-cli/azure/cli/command_modules/acr/connected_registry.py
New repo command to add and delete repository permission to a connected registry. This command will update several scope map resources necessary for functionality and cleanup.
Create a connected registry now verifies that the parent is active and adds all the necessary repo and gateway permissions to its ancestor's sync scope maps.
Delete connected registry now removes the gateway permissions from its ancestor's sync scope map. 
Creating or deleting a child connected registry and verifying that its ancestors' sync scope maps were updated. 
[ACR] az acr connected-registry create: Verifies before the creation of the token and sync scope map that all ancestors are active.
[ACR] az acr connected-registry create: Adds the repository and …
> [ACR] az acr connected-registry create/delete/repo: sync token permissions management.

- src/azure-cli/azure/cli/command_modules/vm/_help.py
- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/commands.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/linter_exclusions.yml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_install_patches.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
New command vm install-patches
Resolve #16790 
***Example***
az vm install-patches -g MyResourceGroup -n MyVm --maximum-duration PT4H --reboot-setting IfRequired --classifications-to-include Critical Security --exclude-kbs-requiring-reboot true
``` python
self.cmd(
'vm create -g {rg} -n vm --image Win2019Datacenter --enable-hotpatching true --admin-username azureuser --admin-password testPassword0 --nsg-rule NONE')
self.cmd('vm install-patches -g {rg} -n vm --maximum-duration PT4H --reboot-setting IfRequired '
'--classifications-to-include Critical Security --exclude-kbs-requiring-reboot true', checks=[
self.check('status', 'Succeeded')
])
```
---
> [Compute] New command: vm install-patches

- src/azure-cli-core/azure/cli/core/parser.py
When the enum validation fails, error message would show the allowed values to improve user experience
Before:
After:
The case in which the candiate list is shown along with the best match candidate:
---
> [Core] Display allowed values in error message when enum validation fails

- src/azure-cli/azure/cli/command_modules/relay/_help.py
> {Relay} Fix typos in azure relay

- src/azure-cli-core/setup.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
Temporary fix for https://github.com/Azure/azure-cli/issues/17625.
Starting from `azure-core` 1.13.0, `Authorization` header is now exposed in DEBUG log (https://github.com/Azure/azure-sdk-for-python/pull/17424).
Temporarily pin `azure-core` to 1.12.0 so that `Authorization` header is redacted.
```
az storage account list --debug
```
> {Packaging} Pin `azure-core` to 1.12.0

- src/azure-cli-core/azure/cli/core/_identity.py
- src/azure-cli-core/azure/cli/core/_msal_patch.py
- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/azclierror.py
- src/azure-cli-core/azure/cli/core/azlogging.py
- src/azure-cli-core/azure/cli/core/cloud.py
- src/azure-cli-core/azure/cli/core/commands/client_factory.py
- src/azure-cli-core/azure/cli/core/credential.py
- src/azure-cli-core/azure/cli/core/tests/test_credential.py
- src/azure-cli-core/azure/cli/core/tests/test_identity.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
- src/azure-cli-core/azure/cli/core/util.py
- src/azure-cli-core/setup.py
- src/azure-cli-testsdk/azure/cli/testsdk/base.py
- src/azure-cli/azure/cli/command_modules/profile/__init__.py
- src/azure-cli/azure/cli/command_modules/profile/_help.py
- src/azure-cli/azure/cli/command_modules/profile/custom.py
- src/azure-cli/azure/cli/command_modules/profile/tests/latest/test_auth_e2e.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
CAE b3 support build upon
- `azure-core` 1.14.0b1
- https://pypi.org/project/azure-core/1.14.0b1/
- https://github.com/Azure/azure-sdk-for-python/tree/azure-core_1.14.0b1
- `azure-mgmt-core` 1.3.0b1
- https://pypi.org/project/azure-mgmt-core/1.3.0b1/
- https://github.com/Azure/azure-sdk-for-python/tree/azure-mgmt-core_1.3.0b1
- `azure-identity` 1.6.0b3
- https://pypi.org/project/azure-identity/1.6.0b3/
- https://github.com/Azure/azure-sdk-for-python/tree/azure-identity_1.6.0b3
This PR is a rework of https://github.com/Azure/azure-cli/pull/17070.
```powershell
> az login
> az storage account list
> az group list
> az account get-access-token
> az rest -m POST -u https://graph.microsoft.com/v1.0/me/revokeSignInSessions
> az storage account list
AADSTS50173: The provided grant has expired …
```
> [Identity] CAE b3

- src/azure-cli/azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py
Modify synapse tests: Use relative path to fetch json files.
Otherwise `azdev test synapse` will fail which will block bump version pipeline.
`azdev test synapse`
---
> {Synapse} Fix file path in tests

- doc/authoring_command_modules/README.md
Current doc page is out of date. Here is to adjust the doc with latest azure cli developer tooling.
---
> {doc} Refine authoring commands doc

- src/azure-cli/azure/cli/command_modules/network/_help.py
https://github.com/Azure/azure-cli/issues/17602
https://github.com/Azure/azure-cli/issues/17572
---
> {Network}`az network application-gateway address-pool update`: Update examples for `--help`

- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/decorators.py
- src/azure-cli-core/azure/cli/core/telemetry.py
> {Telemetry} Fix #16579: Suppress telemetry exception in --debug when there is no valid account login

- src/azure-cli/azure/cli/command_modules/storage/_validators.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_validators.py
Fix issue #16272 and #16853
For command without --auth-mode support, we will not expose related warning message anymore to avoid confuse users.
For command support `--auth-mode`, it will still print out related message.
But for command liek
---
> [Storage] Refine error message

- src/azure-cli/azure/cli/command_modules/resource/_bicep.py
`fromiosformat` and `isoformat` are not available in Python 3.6. This is causing failures for some Bicep users using Azure CLI. The PR updates the Bicep version check code to use Python 3.6 compatible APIs.
Closes https://github.com/Azure/bicep/issues/2243.
Closes https://github.com/Azure/azure-cli/issues/17665.
```
az bicep version
```
---
> [ARM] az bicep: Replace datetime APIs that are not available in Python 3.6

- src/azure-cli-core/azure/cli/core/commands/parameters.py
- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/operations/account.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_extended_location.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
To use this feature, we need to register AzureEdgeZone for your subscription.
Wait for 5/4 release with CRP and NRP.
---
> [Storage] `az storage account create`: Add edge zone support

- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_extension.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
> [Compute] `az vmss extension upgrade` failed

- src/azure-cli/azure/cli/command_modules/vm/custom.py
resolve #17682 
**command**:
`az vm identity assign`
**result**
Before:
```
'NoneType' object is not callable
python3.8/site-packages/knack/cli.py, ln 215, in invoke
cmd_![image](https://user-images.githubusercontent.com/81600993/114687941-d0209580-9d46-11eb-8237-6365b365ea73.png) = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
cli/core/commands/__init__.py, ln 711, in _run_job
six.reraise(*sys.exc_info())
...
cli/command_modules/vm/custom.py, ln 648, in assign_vm_identity
assign_identity_helper(cmd.cli_ctx, getter, setter, identity_role=identity_role_id, …
```
> [Compute] add error message for `vm identity assign`

- src/azure-cli/azure/cli/command_modules/resource/_bicep.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_bicep.py
Hotfix PR to fix #17665
```
az bicep version
```
---
> [ARM] Hotfix: Fix #17665

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
Resolves https://github.com/Azure/azure-cli/issues/13070
There was an issue where during `az functionapp deployment source config-zip`, we were using the local machine's timezone but to create a SAS URI, but the method creating the uri expected UTC (or a timezone to be passed). This resulted in deployment failures for certain timezones because the SAS URI that was being generated was already expired.
[FunctionApp] Fixed issue with zip deploy where local time was provided but UTC was expected
---
> [FunctionApp] Fixed issue with zip deploy where local time was provided but UTC was expected

- .azure-pipelines/templates/automation_test.yml
- .azure-pipelines/templates/azdev_setup.yml
- azure-pipelines.yml
The current `Unit Test for Core and Telemetry` uses `tox` to run `pytest`, making that internal `pytest` uncontrollable.
This PR replaces `tox` with `azdev test` so that core and telemetry use the same test framework as other modules.
> {CI} Use `azdev test` for core and telemetry

- src/azure-cli/azure/cli/command_modules/keyvault/_params.py
- src/azure-cli/azure/cli/command_modules/keyvault/commands.py
This PR removes all the preview tags for MHSM related commands and parameters. This is required by service team as MHSM will GA.
---
> [KeyVault] Hotfix: GA for managed-HSM ralated commands and parameters

- src/azure-cli/azure/cli/command_modules/acr/connected_registry.py
Hotfix PR to consolidate the commits in #17647
---
> {ACR} Hotfix: az acr connected-registry create: Remove ancestors active validation

- src/azure-cli-core/azure/cli/core/azclierror.py
- src/azure-cli-core/azure/cli/core/extension/dynamic_install.py
- src/azure-cli-core/azure/cli/core/extension/operations.py
- src/azure-cli-core/azure/cli/core/parser.py
- src/azure-cli-core/azure/cli/core/tests/test_parser.py
This PR consolidates changes in https://github.com/Azure/azure-cli/pull/17474 and also has the [changes](https://github.com/Azure/azure-cli/pull/17698/commits/020cf2ae1052ff1a7a47b426db0cb815e97bf389) to only allow prefix match for help commands during dynamic extension install to resolve #17696.
`az account -s sub_id set`: not trigger extension install
`az devops --organization org project list`: not trigger extension install
`az devops`: not trigger extension install
`az devops -h`: trigger extension install
`az devops project list --organization org`: trigger extension install
`az devops project list`: trigger extension install
[Component Name …
> {Core} Hotfix: Fix inifite extension install loop

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_update_with_windows_password.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
[AKS] Support updating Windows password
[AKS] az aks update: add --windows-admin-password to support updating Windows password
---
> [AKS] az aks update: Add --windows-admin-password to support updating Windows password

- src/azure-cli/azure/cli/command_modules/backup/_params.py
- src/azure-cli/azure/cli/command_modules/backup/custom.py
Added tags as an optional argument to az backup vault create command. Now the users will be able to create vaults with tags by giving space-separated tags as command-line arguments.
az backup vault create -n {vault_name} --location {location_name} -g {rg_name} --tags DeleteBy=12-9999 Owner=akneema
---
> [BACKUP] az backup vault create: Add tags as an optional argument

- .github/CODEOWNERS
- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/style.py
- src/azure-cli-core/azure/cli/core/tests/test_style.py
- src/azure-cli-core/azure/cli/core/util.py
- src/azure-cli-core/setup.py
- src/azure-cli/azure/cli/command_modules/util/custom.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
Depends on https://github.com/microsoft/knack/pull/238
In Cloud Shell, `SECONDARY` test's color Bright Black (`#555753`) in the color palette **violates** the required Contrast Ratio of **4.5:1**
- In Bash, `#555753` on `#000000` background has Contrast Ratio of [2.87:1](https://webaim.org/resources/contrastchecker/?fcolor=555753&bcolor=000000)
- In PowerShell, `#555753` on `#092457` background has Contrast Ratio of [2.05:1](https://webaim.org/resources/contrastchecker/?fcolor=555753&bcolor=092457)
- Hardcoding RGB values of Cloud Shell-specific theme, as users can't change the color palette of Cloud Shell
- Make `SECONDARY` text's Bight Black lighter
- Refine other colors to make them more pleasing
Cloud Shell theme:
| Style | color
| - | -
| PRIMARY  | `#ffffff`
| SECONDARY| `#bcbcbc`
| …
> [Style] Define theme for Cloud Shell

- src/azure-cli/azure/cli/command_modules/network/_format.py
- src/azure-cli/azure/cli/command_modules/network/commands.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/hybrid_2018_03_01/recordings/test_dns.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/hybrid_2018_03_01/recordings/test_dns_zone1_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/hybrid_2018_03_01/recordings/test_dns_zone2_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/hybrid_2018_03_01/recordings/test_dns_zone3_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/hybrid_2018_03_01/recordings/test_dns_zone4_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/hybrid_2018_03_01/recordings/test_dns_zone5_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/hybrid_2018_03_01/recordings/test_dns_zone6_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/hybrid_2018_03_01/test_dns_commands.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_alias.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_delegation.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_if_none_match.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone1_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone2_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone3_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone4_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone5_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone6_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone7_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone8_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone9_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_dns_commands.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
Changes made for the migration:
- Model: `RecordSetPaged` --> `RecordSetListResult`
- Method: `delete` ---> `begin_delete`
- Property: `arecords` ---> `a_records`
- Exception: `CloudError` ---> `HttpResponseError`
- Property in test checker: `arecords` ---> `aRecords`
[Network] BREAKING CHANGE: az network dns record-set a show: Property `arecords` in output will be changed to `aRecords`.
---
> {DNS} Migrate to track 2

- src/azure-cli/azure/cli/command_modules/network/_help.py
- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/commands.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/linter_exclusions.yml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_with_waf_v2_sku.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
[Network] `az network application-gateway show-backend-health`: support probe operation arguments.
---
> {Network} application gateway 100% support

- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli/azure/cli/command_modules/profile/__init__.py
- src/azure-cli/azure/cli/command_modules/profile/custom.py
Resolve #17551
Add `--scope` to `az login` for Conditional Access MFA support.
> {Core} `az login`: support `--scope`

- src/azure-cli/azure/cli/command_modules/batchai/custom.py
- src/azure-cli/azure/cli/command_modules/batchai/tests/latest/test_batchai_scenario.py
Remove ` az storage account keys list` command usage in batchai test scenarios
---
> {batchai} Refine test with storage account APIs

- src/azure-cli/azure/cli/command_modules/sqlvm/custom.py
Make SqlServerLicenseType optional
Making SqlServerLicenseType optional. We are preventing users to assign license type for their resource in mooncake cloud. In other clouds, if they dont provide license type, we will throw an error in our pre requisite check.
az sql vm create -n sqlvm -g myresourcegroup -l eastus
---
> [sqlvm] Make SqlServerLicenseType as optional

- src/azure-cli/azure/cli/command_modules/keyvault/_completers.py
- src/azure-cli/azure/cli/command_modules/role/custom.py
- src/azure-cli/azure/cli/command_modules/servicefabric/custom.py
- src/azure-cli/azure/cli/command_modules/vm/_vm_utils.py
Split from #17738
As pointed out by #15854, calling the protected method `_token_retriever` is simply wrong. 
This PR replaces `_token_retriever` with `azure.cli.core._profile.Profile.get_raw_token`, as provided by https://github.com/Azure/azure-cli/issues/15805#issuecomment-722914070.
This is also the approach adopted by `azure.cli.command_modules.keyvault._client_factory.keyvault_data_plane_factory`:
https://github.com/Azure/azure-cli/blob/1eed07797b9877fac1703555d25ead43b295376b/src/azure-cli/azure/cli/command_modules/keyvault/_client_factory.py#L128-L137
On the other hand, instead of implementing its own keyvault client factory, **appconfig** directly uses  `azure.cli.command_modules.keyvault._client_factory.keyvault_data_plane_factory` (#15826): …
> {KeyVault} Replace `_token_retriever` with `get_raw_token`

- src/azure-cli-core/azure/cli/core/commands/client_factory.py
- src/azure-cli-core/azure/cli/core/sdk/policies.py
- src/azure-cli-core/setup.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
Resolve https://github.com/Azure/azure-cli/issues/17625
1. Starting from `azure-core` 1.13.0, `Authorization` header is now exposed in DEBUG log (https://github.com/Azure/azure-sdk-for-python/pull/17424).
2. Python SDK decided not to redact `x-ms-authorization-auxiliary` header (https://github.com/Azure/azure-sdk-for-python/issues/17271).
Create a custom policy `SafeNetworkTraceLoggingPolicy` to replace `NetworkTraceLoggingPolicy`. It by default redacts `Authorization` and `x-ms-authorization-auxiliary`. Any client factory calling `prepare_client_kwargs_track2` will have this policy configured.
Any Track 2 mgmt-plane command, like
```sh
> az storage account list
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/414af076-009b-4282-9a0a-acf75bcb037e/pr …
```
> {Logging} Redact headers from SDK HTTP log

- src/azure-cli-core/azure/cli/core/_profile.py
In Cloud Shell, even if `az login` is run with user or Service Principal account, subsequent commands involving cross-tenant authentication fails:
```
$ az network vnet peering create --name myVnetAToMyVnetB --resource-group myResourceGroupA --vnet-name myVnetA --remote-vnet /subscriptions/414af076-009b-4282-9a0a-acf75bcb037e/resourceGroups/myResourceGroupB/providers/Microsoft.Network/VirtualNetworks/myVnetB --allow-vnet-access
Cross-tenant authentication is not supported by managed identity and Cloud Shell. Please run `az login` with 
a user account or a service principal.
```
**Cause**
This bug was introduced by #16797 where only `in_cloud_console()` is checked:
https://github.com/Azure/azure-cli/blob/039fa21db4fdf6dfb22958aaf1c3f614e1fc3b59/src/azure-cli-core/azure/cli/c …
> {Core} Fix: In Cloud Shell, cross-tenant authentication fails for user or Service Principal account

- src/azure-cli-core/azure/cli/core/sdk/__init__.py
`azure.cli.core.sdk` (added by #17671) doesn't have `__int__.py`, so it will not be included in the `whl` file, causing CI failure:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=855815&view=logs&jobId=c846b3e8-69b8-5dbd-1a39-4905d81e6a95&j=1e6fba43-bdcf-51f0-a062-3712c33fbb51&t=a1e787eb-ec67-5c3d-79ec-0c68f4f59d65
```
if 'x-ms-client-request-id' in cli_ctx.data['headers']:
client_kwargs['request_id'] = cli_ctx.data['headers']['x-ms-client-request-id']
>       from azure.cli.core.sdk.policies import SafeNetworkTraceLoggingPolicy
E       ModuleNotFoundError: No module named 'azure.cli.core.sdk'
```
This is because `setup.py` uses [`find_packages`](https://setuptools.readthedocs.io/en/latest/userguide/package_discovery.html#using-find-or-find-packages) to find …
> {Core} Add `__init__.py` to `azure.cli.core.sdk`

- .azure-pipelines/templates/azdev_setup.yml
Bump `azdev` to 0.1.31 to adopt https://github.com/Azure/azure-cli-dev-tools/pull/294 and fix `pylint`.
> {CI} Bump `azdev` to 0.1.31

- src/azure-cli/azure/cli/command_modules/acr/_help.py
- src/azure-cli/azure/cli/command_modules/acr/task.py
Fixes https://github.com/Azure/azure-cli/issues/17618.
Fixes the sample for creating a task with `--auth-mode None`.
1. Create task a valid `--auth-mode` value.
`az acr task create -t hello-world:{{.Run.ID}} -n hello-world -r MyRegistry  -f Dockerfile \
--no-push true --auth-mode None -c https://github.com/Azure-Samples/acr-build-helloworld-node.git \
--git-access-token 000000000000000000000000000000000 --assign-identity`
2. Add custom registry credential 
`az acr task credential add --login-server myotherregistry.azurecr.io --use-identity [system]`
Previously, `az acr task credential add` and `az acr task credential update` crashed. 
---
> [ACR] Fix #17618: Update credential add/update handling for tasks created using --auth-mode

- src/azure-cli/azure/cli/command_modules/acr/check_health.py
Use `from pkg_resources import working_set` is slow (see #14905). And with PR #17432, in MSI installed Azure CLI, we cannot rely on `dist-info` to get package versions.
---
> {ACR} Improve the way to get az version in acr

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/commands.py
- src/azure-cli/azure/cli/command_modules/appservice/static_sites.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_staticapp_commands_thru_mock.py
- src/azure-cli/azure/cli/command_modules/appservice/utils.py
1. az staticwebapp browse -> az staticwebapp show
2. add option of sku for az staticwebapp create --sku
3. add command of az staticwebapp update
Tested commands - working as expected:
1. az staticwebapp show -n my-first-static-web-app
2. az staticwebapp create -n my-second-static-web-app -g rg -s https://github.com/jiansong-msft/my-first-static-web-app -l CentralUS -b main --token github-token --sku Free
3. az staticwebapp update -n my-second-static-web-app --tags "key=value"
4. az staticwebapp update -n static-app-not-exists throws
5. with invalid sku options passed in throws
---
> [AppService]  BREAKING CHANGE: Add support for az staticwebapp show; az staticwebapp create; az staticwebapp update

- src/azure-cli/azure/cli/command_modules/cdn/_help.py
- src/azure-cli/azure/cli/command_modules/cdn/_params.py
- src/azure-cli/azure/cli/command_modules/cdn/custom/custom.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_akamai_delivery_rule.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_endpoint_crud.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_endpoint_different_profiles.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_endpoint_load_and_purge.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_endpoint_start_and_stop.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_private_link.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_rule_engine_crud.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_verizon_delivery_rule.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/scenario_mixin.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_endpoint_scenarios.py
Fix delivery rule creation for non-Microsoft SKU.
Add delivery caching rule for the specific extensions for Akamai/Verizon SKU
> az cdn endpoint rule add -g rg -n ed --profile-name profile --order 1 \
> --action-name CacheExpiration --match-variable UrlFileExtension --operator Any --match-values mp4 mp3 \
> --cache-behavior Override --cache-duration 00:05:00
---
> [CDN] az cdn endpoint rule add: Fix delivery rule creation for non-Microsoft SKU

- src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
Resolve https://github.com/Azure/azure-cli/issues/17904
```
az cloud set -n AzureCloud --profile 2019-03-01-hybrid
az vm create -g fy -n vm --image win2016datacenter --admin-username clitester --admin-password PasswordPassword1!
```
returns
```
Could not find member 'securityProfile' on object of type 'Properties
```
The request body contains `"securityProfile": {}`. It appears that the old version of Compute does not accept this field even it is an empty dict.
---
> [Compute] Fix a compatibility issue of old API version

- linter_exclusions.yml
- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_update_to_msi_cluster.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_update_to_msi_cluster_with_addons.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
This PR add the implementation for supporting updating from SPN cluster to MSI cluster. The feature has been in preview state for a while, and we're going to GA it. The PR is a combination of following two PRs in aks-preview extension: 
- https://github.com/Azure/azure-cli-extensions/pull/2571
- https://github.com/Azure/azure-cli-extensions/pull/2680
[AKS] Support updating from SPN cluster to MSI cluster.
---
> [AKS] Support updating from SPN cluster to MSI cluster

- src/azure-cli/azure/cli/command_modules/backup/custom_afs.py
Made AFS Configure Backup flow Idempotent
---
> [Backup]Made AFS Configure Backup flow Idempotent

- linter_exclusions.yml
- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
az aks create: add enable-encryption-at-host parameter
```console
docker run -v ${HOME}:/root -it andyzhangx/azure-cli:2.22.1
az aks create -g $RESOURCE_GROUP_NAME -n $CLUSTER_NAME --node-count 1 --node-vm-size Standard_DS2_v2 --generate-ssh-keys --kubernetes-version 1.20.2 --enable-encryption-at-host
az aks nodepool add --name nodepool2 --cluster-name $CLUSTER_NAME --resource-group $RESOURCE_GROUP_NAME --enable-encryption-at-host
```
---
> [AKS] az aks create: add enable-encryption-at-host parameter

- doc/use_cli_in_airgapped_clouds.md
`az acr helm install-cli` is deprecated, remove it in doc as requested by doc team.
---
> {doc} Remove deprecated acr command in doc

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
> [AppService] `webapp log tail` Fix #17987: logging.warning call with invalid 'end' argument

- src/azure-cli/azure/cli/command_modules/appservice/_constants.py
- src/azure-cli/azure/cli/command_modules/appservice/_github_oauth.py
- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
- Add function `get_github_access_token` to help users retrieve github access token easier
- Following doc: https://docs.github.com/en/developers/apps/authorizing-oauth-apps#device-flow
This is not exposed in a command yet, as I'm not sure what command to put it under. We will be using this function in webapp commands in the future, and static webapps have use cases as well
---
> [AppService] az appservice: Add function to retrieve users github personal access token

- src/azure-cli-core/azure/cli/core/commands/__init__.py
importing the ABCs from 'collections' instead of from 'collections.abc'
is deprecated since Python 3.3, and in 3.10 it will stop working.
On Python 3.10  running any az commands show the following error:
```console
$ az account list
module 'collections' has no attribute 'Iterable'
File "/usr/local/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
raise ex
File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
results.append(self._run_job(expanded_arg, …
```
> {Core} Use `from collections.abc import Iterable` to support Python 3.10

- .azure-pipelines/templates/azdev_setup.yml
- pylintrc
Require https://github.com/Azure/azure-cli-dev-tools/pull/295
The old `pylint` 2.3.0 is
- not compatible with the latest `astroid` (https://github.com/Azure/azure-cli-dev-tools/pull/294)
- not compatible with Python 3.9 (https://github.com/Azure/azure-cli/pull/17368) 
- Use the latest `azdev` with `pylint` bumped to 2.8.0
- Disable new [checkers](http://pylint.pycqa.org/en/latest/technical_reference/features.html) of the new `pylint` 
All these newly disabled checkers should be fixed one by one in their dedicated PRs:
The list of failed checkers are acquired by running `pylint` with `--msg-template='{symbol}'`:
```
python -m pylint d:\cli\azure-cli\src\azure-cli\azure\cli d:\cli\azure-cli\src\azure-cli-core\azure\cli\core d:\cli\azure-cli\src\azure-cli-telemetry\azure\cli\telemetry …
```
> {pylint} Disable more checkers to comply with pylint 2.8.0

- src/azure-cli/azure/cli/command_modules/appservice/_github_oauth.py
For unknown reason, Pylint 2.3.0 fails to find linter errors in `_github_oauth.py` added by https://github.com/Azure/azure-cli/pull/17826.
After bumping Pylint 2.8.0 (https://github.com/Azure/azure-cli/pull/17861), those errors are revealed.
https://dev.azure.com/azure-sdk/public/_build/results?buildId=880573&view=logs&j=36dd4138-4d53-5e46-00d9-e5cd9744be05&t=1cf3879c-0a42-5ccd-7693-7a4781d739d8&l=107
```
src/azure-cli/azure/cli/command_modules/appservice/_github_oauth.py:20:28: W0613: Unused argument 'cmd' (unused-argument)
```
> {AppService} Fix linter error in `_github_oauth.py`

- src/azure-cli/azure/cli/command_modules/appconfig/_kv_helpers.py
While importing key-values from a file, if the key or value contains a non-ASCII character, we fail to parse the file and throw syntax error. Since AppConfig allows unicode characters in key and values, we should be able to import them from file.
Reported in customer issue [#513](https://github.com/Azure/AppConfiguration/issues/513).
Trying to import this json file with unicode characters should succeed:
```
{
"User’s Name": "John",
"Temperature": "98º",
"Chinese": "汉"
}
```
`az appconfig kv import -s file --format json --auth-mode login --endpoint https://test-appconfig-00.azconfig.io --path <filePath> --yes` 
[Component Name 2] az command b: …
> [AppConfig] Allow importing key-values with unicode characters from file

- src/azure-cli-core/azure/cli/core/azlogging.py
- src/azure-cli-core/setup.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
Fix https://github.com/Azure/azure-cli/issues/17994
Adopt https://github.com/microsoft/knack/pull/247
On Windows with English as the system language (without UTC-8 enabled), the system encoding by default is `cp1252` (Western Europe), and Python will use `cp1252` as the file encoding by default. 
Writing Unicode characters like `汉字` to log file results in error:
```
File "C:\Users\xxx\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 1084, in emit
stream.write(msg + self.terminator)
File "C:\Users\xxx\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 87-88: …
```
> {Core} Always use UTF-8 for command metadata log file encoding

- src/azure-cli/azure/cli/command_modules/acs/custom.py
referring to the issue #17930 , the command will timeout when the "canipull" pod is scheduled on the windows node. The windows node doesn't support host network mode hence the pod will get stuck in container creating 
https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#networking-limitations
Example usage: az aks check-acr -g <RG name>-n <Cluster> --acr xx.azurecr.io
Example YAML of "canipull" pod:
---
> [AKS] az aks check-acr: add the nodeslector linux to avoid the "canipull" pod to be scheduled on the windows node

- src/azure-cli/azure/cli/command_modules/storage/_params.py
I found some words are concatenated by mistake.
"accessedusing" vs. "accessed using":
> ## az storage blob generate-sas & az storage container generate-sas
> 
> ### Optional Parameters
> 
> `--cache-control`  
> Response header value for Cache-Control when resource is **accessedusing** this shared access signature.
> 
> `--content-disposition`  
> Response header value for Content-Disposition when resource is **accessedusing** this shared access signature.
> 
> `--content-encoding`  
> Response header value for Content-Encoding when resource is **accessedusing** this shared access signature.
> 
> `--content-language`  
> Response header value for Content-Language when resource is **accessedusing** this shared access signature.
> 
> `--content-type`  
> Response header …
> {Storage} Split concatenated words in the help message

- src/azure-cli/azure/cli/command_modules/lab/custom.py
Running ```az labs create environment ...``` to produce an environment from an ARM template produces an error on azure-cli 2.23.0 as below
```
cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: __init__() takes 1 positional argument but 3 were given
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__i …
```
> [DevTestLabs] az labs create environment: Fix error creating an environment from an ARM template

- src/azure-cli/azure/cli/command_modules/batch/tests/latest/recording_processors.py
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_application_cmd.yaml
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_certificate_cmd.yaml
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_general_arm_cmd.yaml
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_job_list_cmd.yaml
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_jobs_and_tasks.yaml
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_pool_cmd.yaml
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_pools_and_nodes.yaml
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_task_create_cmd.yaml
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/test_batch_data_plane_commands.py
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/test_batch_mgmt_commands.py
Added a scrubber for account keys and SAS signatures. The previous keys were not live, so there is no security issue, but this change replaces them with obviously fake values (ie: "fakeBatchAccountKey0==")
Run the batch unit tests with the new recordings
---
> {Batch} Add account key and SAS signature replacers for tests

- src/azure-cli/azure/cli/command_modules/appservice/static_sites.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_staticapp_commands_thru_mock.py
This is a fix for this [PR](https://github.com/Azure/azure-cli/issues/17792). You can't set static web app settings if the value contains an equal sign.
`az staticwebapp appsettings set --app-settings foo=bar==` 
That should produce {"foo": "bar=="}
---
> [App Service] az staticwebapp appsettings set issue #17792

- azure-pipelines-full-tests.yml
- azure-pipelines.yml
- src/azure-cli-core/setup.py
- src/azure-cli-telemetry/setup.py
- src/azure-cli-testsdk/setup.py
- src/azure-cli/setup.py
Close #16611
It is time to onboard Python 3.9.
> [Packaging] Support Python 3.9

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_managed_aad_enable_azure_rbac.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
This PR is to port the support of creating and updating AKS-managed cluster with Azure RBAC from aks-preview extension. It adds a new argument --enable-azure-rbac to az aks create command and --enable-azure-rbac and --disable-azure-rbac to the az aks update command
Create an AKS-managed cluster with Azure RBAC
```
az aks create -g MyResourceGroup -n MyManagedCluster --enable-aad --enable-azure-rbac
```
Update an AKS-managed Azure AD cluster
```
az aks update -g MyResourceGroup -n MyManagedCluster  --enable-azure-rbac
```
```
az aks update -g MyResourceGroup -n MyManagedCluster  --disable-azure-rbac
```
---
> [AKS] az aks create and update azure-rbac

- src/azure-cli/azure/cli/command_modules/appservice/static_sites.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_staticapp_commands_thru_mock.py
Fix#18033: az staticwebapp appsettings set of missing positional param app_settings
az staticwebapp appsettings set -n staticwebappname --setting-names foo=bar
---
> [AppService] Fix#18033: az staticwebapp appsettings set of missing positional param app_settings

- .flake8
- pylintrc
Require https://github.com/Azure/azure-cli-dev-tools/pull/301
Due to https://github.com/PyCQA/pylint/issues/2686, `test.*` directories are not ignored. This causes files like `src/azure-cli/azure/cli/command_modules/billing/tests/__init__.py` to be checked which is not desired.
However, `ignore=tests` works because `tests` directories in Azure CLI are actually modules (because they contain `__init__.py`), so `pylint` goes through a different code path of `modutils.get_module_files`:
https://github.com/PyCQA/pylint/blob/8f84dec53d53b8297ef753277fc1d820becd8428/pylint/lint/expand_modules.py#L114-L121
```py
if has_init or is_namespace or is_directory:
for subfilepath in modutils.get_module_files(
os.path.dirname(filepath), ignore_list, list_all=is_namespace
):
if filepath == …
```
> {Pylint} Ignore `tests` folders

- scripts/ci/test_extensions.sh
CI is blocked by
https://dev.azure.com/azure-sdk/public/_build/results?buildId=876833&view=logs&j=cedb4d72-63c2-581b-2274-24a4ef43c946&t=1b7b5e8c-f0d3-504e-ebf4-a86923fb02b9&l=1068
```
Verifying extension: fzf
WARNING: This package of the Batch Extensions module supports Azure Batch up to version 7.1. The current version 10.0.0 has not been tested for compatibility.
WARNING: This package of the Batch Extensions module supports Azure Batch Management up to version 6.1. The current version 9.0.0 has not been tested for compatibility.
WARNING: This package of the Batch Extensions module supports Azure Batch Extensions up to version 6.1. The current version 8.0.0 has not been tested for compatibility.
ERROR: Request to …
```
> {CI} Ignore `fzf` in CI job `TestExtensionsLoading`

- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/commands/__init__.py
- src/azure-cli-core/azure/cli/core/local_context.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_common.py
Resolve #17920
Run the following commands and check the output messages:
```
az config param-persist on
az group create -n test-rg -l westsus
az storage account create -n mytestsa -g test-rg --sku standard_lrs
az config param-persist off
```
---
> {Param Persist} Change term `local context` to `param persist` in customer-facing messages

- src/azure-cli-core/azure/cli/core/commands/progress.py
Fix issue #16798 
As progress bar will write string to stderr and cli command result will write to stdout, two kinds of strings overlapped.
Here is to erase previous stderr stream with empty line, and then the overlap disappears as below:
---
> [Core] Fix issue #16798: Azure CLI output is corrupted!

- src/azure-cli-core/setup.py
The pipeline of extension install pre version of packages https://github.com/Azure/azure-cli-extensions/blob/a0b24e846c3a9d74a5deddac5289753d5187869b/scripts/ci/test_source.sh#L6.
Recently this [PR](https://github.com/Azure/azure-cli-extensions/pull/3374) triggered a issue that the azure-mgmt-core 1.3.0b1 (preview version) conflict with azure-core 1.14.0 (stable version).
This PR will ping the version of azure-mgmt-core <= 1.3.0 in setup.py to workaround above issue.
---
> {Core} Ping azure-mgmt-core version setup.py

- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/operations/account.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_with_default_share_permission.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
Support default share permission in `az storage account create/upudate`.
Customer can set the DefaultSharePermission in create/update storage account , the available value are: None | StorageFileDataSmbShareReader | StorageFileDataSmbShareContributor | StorageFileDataSmbShareElevatedContributor | StorageFileDataSmbShareOwner
---
> [Storage] Support default share permission

- src/azure-cli/azure/cli/command_modules/appservice/_params.py
```
c.argument('force_dns_registration', help="If true, web app hostname is force registered with DNS",
arg_type=get_three_state_flag(return_label=True), deprecate_info=c.deprecate(expiration='3.0.0'))
```
I changed it to a lager version.
---
> {Appservice} Update expire date for some parameters

- src/azure-cli/azure/cli/command_modules/appservice/_client_factory.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_list_locations_free_sku.yaml
Importing `ResourceManagementClient` incorrectly causes it to use latest version of python SDK automatically, instead of the version specified by core CLI
> [AppService] Fix get resource management client properly

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/custom_preparers.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
[Related PR #18035](https://github.com/Azure/azure-cli/pull/18035)
My requirement is to run test cases in all locations where services are available for testing. As far as I know, there is currently no way to change the default location value of the ResourceGroupPreparer provided by azure.cli.testsdk. Thus I would like to implement a custom preparer to achieve this and it will only be used for testing aks commands (acs module). No impact on other modules. Is this acceptable?
---
> {AKS} replace ResourceGroupPreparer with custom preparer in aks command test

- .github/CODEOWNERS
Add @panchagnula as `appservice` code owner so that she can be notified as a reviewer when PRs like https://github.com/Azure/azure-cli/pull/17988 are submitted.
> {Misc.} Change `appservice` codeowner

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/static_sites.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_staticapp_commands_thru_mock.py
Let users get github personal access token interactively using https://github.com/Azure/azure-cli/pull/17826
`az staticwebapp create --login-with-github`
`az staticwebapp reconnect --login-with-github`
---
> [AppService] Add interactive way to get token for staticwebapp

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/custom_preparers.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_default_service_with_virtual_node_addon.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
* Fix the “test_aks_create_default_service_with_virtual_node_addon” test case in ACS module which would fail in live test.
* Provide the same location as the resource group preparer
* Provide a subnet address prefix to avoid conflicts with default AKS cluster cidr
* Add a custom "AKSCustomVirtualNetworkPreparer" to replace class "VirtualNetworkPreparer" to meet the need to provide the above required resources
---
> {AKS} Fix failed live test case and add custom virtual network preparer

- doc/managed_identity_command_guideline.md
The new command interface for managed identity is based on the discussion with Managed Identity team.
---
> {Doc} Add managed identity command guideline

- pylintrc
- src/azure-cli/azure/cli/command_modules/servicefabric/custom.py
- src/azure-cli/azure/cli/command_modules/sqlvm/custom.py
- src/azure-cli/azure/cli/command_modules/synapse/operations/spark.py
Per https://pycodequ.al/docs/pylint-messages/w0127-self-assigning-variable.html, no need to assigned a variable to itself.
> {Pylint} Fix `self-assigning-variable`

- src/azure-cli-core/azure/cli/core/commands/__init__.py
- src/azure-cli/azure/cli/command_modules/appconfig/_kv_helpers.py
- src/azure-cli/azure/cli/command_modules/keyvault/_client_factory.py
- src/azure-cli/azure/cli/command_modules/keyvault/_command_type.py
- src/azure-cli/azure/cli/command_modules/role/custom.py
- src/azure-cli/azure/cli/command_modules/servicefabric/custom.py
- src/azure-cli/azure/cli/command_modules/vm/_vm_utils.py
Fix #11871 
Previously, CX can't succeed to manage keyvault resources in nondefault tenant/subscription because KeyVault Data Plane Client Factory's `KeyvaultAuthentication` didn't honor `--subscription` parameter, it will always use the access token from the login subscription.
First of all, login to SUB_A:
```
> az login
> az account set -s SUB_A
```
Try to list keyvault secrets in SUB_B:
_Before_
```
> az keyvault secret list --vault-name ystestkv --subscription "1c638cf4-608f-4ee6-b680-c329e824c3a8"
AKV10032: Invalid issuer. Expected one of https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/, https://sts.windows.net/f8cdef31-a31e-4b4a-93e4-5f571e91255a/, https://sts.windows.net/e2d54eb5-3869-4f70-8578-dee5fc7331f4/, …
```
> [KeyVault] Fix #11871: AKV10032: Invalid issuer error for operations in nondefault tenant/subscription

- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/commands.py
GA release storage file share NFS and SMB multichannel as service team request
---
> [Storage] GA release storage file share NFS and SMB multichannel

- scripts/release/debian/Dockerfile
- src/azure-cli-core/setup.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
Since `setup.py` doesn't pin `urllib3`
https://github.com/Azure/azure-cli/blob/d1585e356d547fe5adcc4c6651096e8884dcb45e/src/azure-cli/setup.py#L146
[Component Governance alert](https://dev.azure.com/azure-sdk/internal/_componentGovernance/144540/alert/4535820?typeId=2389919) is triggered when `urllib3` 1.26.2 is installed.
The current `urllib3` is 1.26.4, so the alert is no longer valid. 
For security sake, we should force `urllib3` >= 2.26.4.
> {Packaging} Bump `urllib3` and `requests`

- .azure-pipelines/templates/azdev_setup.yml
- src/azure-cli/azure/cli/command_modules/resource/_win_vt.py
Unpin `azdev` so that the latest `azdev` ([0.1.33](https://github.com/Azure/azure-cli-dev-tools/releases/tag/v0.1.33)) can be automatically picked up by the CI.
> {CI} Unpin azdev

- src/azure-cli/azure/cli/command_modules/rdbms/_flexible_server_util.py
- src/azure-cli/azure/cli/command_modules/rdbms/_params.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_common.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_mysql.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_virtual_network.py
- src/azure-cli/azure/cli/command_modules/rdbms/templates/mysql_githubaction_template.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/templates/postgresql_githubaction_template.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_flexible_server_vnet_ha_server_create.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_flexible_server_vnet_mgmt_supplied_vname_and_subnetname.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_flexible_server_vnet_mgmt_supplied_vnet.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_flexible_server_vnet_server_create.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_vnet_ha_server_create.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_vnet_mgmt_supplied_vname_and_subnetname.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_vnet_mgmt_supplied_vnet.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_vnet_server_create.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands.py
- src/azure-cli/setup.py
- Added private dns zone parameter for Postgres restore command
- Added validator for high availability flag
---
> [RDBMS] Private DNS zone parameter added for restore command, high availability validator

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
Closes #17885 
Update webapp create help text. java|11|javase|8 runtime was confusing, as users didn't know if it was java 8 or java 11
Update help text: `az webapp create -h`
---
> {AppService} az webapp create: Update help text

- src/azure-cli/azure/cli/command_modules/storage/operations/blob.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_list_scenarios.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_blob_scenarios.py
Fix issue #18393
`--delimiter` parameter value for `az storage blob list` is always ignored and defaults to `/`.
This is my first time contributing to this repository, I have not directly modified the `HISTORY.rst` as mentioned in the contribution guide because I was unsure of the version in which this would land. I can add it once the the Pull Request is reviewed and approved.
Repro is in the linked issue. I have extended one of the storage blob scenarios test to include a custom delimiter.
[Storage] az storage blob list: --delimiter parameter value will now be honored
---
> [Storage] Fix #18393 - `az storage blob list` --delimiter parameter value is ignored

- src/azure-cli/azure/cli/command_modules/container/custom.py
The websocket response can be a string for text or bytes for an utf-8 string. utf-8 was not handled properly. This pr adds detection of bytes and decoding as utf-8 string before writing to the console.
Fixes: https://github.com/Azure/azure-cli/issues/15856
Fixes: https://github.com/Azure/azure-cli/issues/18251
Fixes: https://github.com/Azure/azure-cli/issues/18275
- start a container e.g. with `az container create` with a long living container
- try to execute a shell inside the container with `az container exec --exec-command "/bin/bash" ...`
- currently it just exits without an error or shell
- 
[container] az container exec: decode received bytes as utf-8 string
--- …
> {container} Bugfix #15856,#18251,#18275: az container exec - decode received bytes as utf-8 string

- src/azure-cli/azure/cli/command_modules/keyvault/custom.py
Service has not yet implemented multi-region HA for hsm yet. They asked us to disable `--secondary-locations` temporarily
`az keyvault update-hsm --hsm-name --secondary-locations`
---
> {Keyvault} `az keyvault update-hsm`: --secondary-location not supported

- src/azure-cli-core/azure/cli/core/profiles/_shared.py
- src/azure-cli/azure/cli/command_modules/appservice/_client_factory.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
Add custom location SDK which will be used in appservice-kube extension. The commands from the appservice-kube extension will eventually be moved to core
The ExtendedLocation model is included in appservice package, however I want to be able to use ExtendedLocation management commands (like get & list: https://docs.microsoft.com/en-us/python/api/azure-mgmt-extendedlocation/azure.mgmt.extendedlocation.v2021_03_15_preview.operations.customlocationsoperations?view=azure-python-preview) in order to verify the ExtendedLocation before using it in our AppService commands
No changes to existing commands, just adding custom location SDK 
---
> {AppService} Add custom location sdk

- src/azure-cli-core/azure/cli/core/commands/command_operation.py
- src/azure-cli-core/azure/cli/core/commands/progress.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_resource_group_no_wait.yaml
Fix #18360 and #18262
In previous design, we are using empty line to clear terminal. But as there are some tools which are sensitive to stderr stream, we will stop writing to stderr now.
---
> [Core] Fix #18360 and #18262: write to stderr issue

- src/azure-cli/azure/cli/command_modules/acr/_params.py
- src/azure-cli/azure/cli/command_modules/acr/connected_registry.py
Fixes a few mistakes with the help and error output. 
> [ACR] az acr connected-registry: Minor bug fixes

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
- src/azure-cli/azure/cli/command_modules/vm/_validators.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_user_data.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_user_data.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/user_data.json
Issue: #17223
- Should allow customer to submit userData as a file.
- User_data must be base64 encoded (CRP will reject any userData that is not based64 encoded).
- CLI can allow customer to pass an empty string as input, it will interpret that as a signal to delete the user_data.
- Allow customers to retrieve value of userData. For that, CLI must make GET request using `$expand=userData`.
---
> [Compute] Support user_data for VM and VM Scale Sets

- src/azure-cli/azure/cli/command_modules/aro/_params.py
Resolves [13531](https://github.com/Azure/azure-cli/issues/13531) by adding CIDR ranges for pod network and service network.
`az aro create --help` shows the cidr range that is applicable for the service (i.e /18)
output: 
```bash
--pod-cidr                     : CIDR of pod network. Must be a minimum of /18 or larger.
--pull-secret                  : Pull secret of cluster.
--service-cidr                 : CIDR of service network. Must be a minimum of /18 or larger.
```
---
> [ARO] add cidr values for pod/service to cli params

- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/profiles/_shared.py
There exists logic in core to patch versioned sdk path for command's operation. For example, it will replace `azure.mgmt.storage.operations.storage_accounts_operations` to `azure.mgmt.storage.operations.v2016_12_01.storage_accounts_operations`.
Here's some small fix on this feature. See my comments for details.
**Background**
Keyvault data plane track2 migration just hit these bugs.
- While getting operation handler, `operation` was replaced wrongly with previous code:
https://github.com/Azure/azure-cli/blob/efb2f359df9035a5b6b1989b763cbe94962bb171/src/azure-cli-core/azure/cli/core/__init__.py#L877-L890
a. `ResourceType.DATA_KEYVAULT`(track1) has `azure.keyvault` as its `import_prefix`
b. `ResourceType.DATA_KEYVAULT_KEYS`(track2) has `azure.keyvault.keys` as its …
> {Core} Small fix on patching versioned sdk path

- src/azure-cli-core/README.rst
- src/azure-cli-core/setup.py
- src/azure-cli/README.rst
- src/azure-cli/setup.py
Fix #18383
Full **Release History** is included in the project description on PyPI: https://pypi.org/project/azure-cli/
With each release, the Release History will grow, making the Azure CLI project description grow.
Even though https://packaging.python.org/specifications/core-metadata/#description says:
> Software that deals with metadata should not assume any maximum size for this field
Azure DevOps has a limit on the package description size of 324608 bytes. The latest Azure CLI's project description already exceeds this limit so can't be installed on Azure DevOps.
This PR removes full Release History from project description and uses a link to point to the full Release History instead.
> {Packaging} Remove full Release History from project description

- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/setup.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
Fix #17939
ADAL already supports PyJWT > 2.0 (https://github.com/AzureAD/azure-activedirectory-library-for-python/pull/246), it is safe for Azure CLI to use PyJWT 2.1.0.
> {Packaging} Bump PyJWT to 2.1.0

- src/azure-cli-core/setup.py
Close #18499
This command will go into almost endless [backtracking](https://pip.pypa.io/en/stable/user_guide/#dependency-resolution-backtracking):
```
pip requests~=2.24.0 azure-cli
```
The conflict comes from `requests~=2.24.0` 
https://github.com/psf/requests/blob/v2.24.0/setup.py#L47
```py
'urllib3>=1.21.1,<1.26,!=1.25.0,!=1.25.1',
```
and `azure-cli-core`
https://github.com/Azure/azure-cli/blob/162be08eefaa1d64974a07b6179babe4c5b2830a/src/azure-cli-core/setup.py#L62
`azure-cli-core` requires the latest `urllib3` due to https://github.com/Azure/azure-cli/pull/18324.
By being more strict on `requests`, `pip` fails more quickly:
```
> pip install requests~=2.24.0 -e src/azure-cli-core
ERROR: Cannot install azure-cli-core==2.25.0 and requests~=2.24.0 because these package versions have …
```
> {Packaging} Be more strict on `requests`

- pylintrc
- src/azure-cli-core/azure/cli/core/commands/__init__.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/batch/_command_type.py
- src/azure-cli/azure/cli/command_modules/cdn/custom/custom_afdx.py
- src/azure-cli/azure/cli/command_modules/monitor/operations/activity_log_alerts.py
- src/azure-cli/azure/cli/command_modules/network/_validators.py
http://pylint.pycqa.org/en/latest/technical_reference/features.html
> use-a-generator (R1729)
> Use a generator instead '%s(%s)'. Comprehension inside of 'any' or 'all' is unnecessary. A generator would be sufficient and faster.
> {Pylint} Fix `use-a-generator`

- src/azure-cli-core/azure/cli/core/extension/operations.py
Fix #17961
Due to https://bugs.python.org/issue33240, there is a very small chance that [`shutil.rmtree`](https://docs.python.org/3/library/shutil.html#shutil.rmtree) fails on Windows. 
(Personally, I have also observed it even when deleting a directory with `explorer.exe` - the contents of the directory is deleted but the directory remains.)
- Add a retry logic to `shutil.rmtree`
- Even if `shutil.rmtree` fails after several retries, the failure doesn't block command execution
> {Core} `az extension`: Retry `shutil.rmtree`

- scripts/release/rpm/test_rpm_package.py
**Test Yum Package** keeps failing with race condition:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=953187&view=logs&j=1e6fba43-bdcf-51f0-a062-3712c33fbb51&s=d654deb9-056d-50a2-1717-90c08683d50a&t=a1e787eb-ec67-5c3d-79ec-0c68f4f59d65&l=1717
```
==================================== ERRORS ====================================
____ ERROR collecting tests/latest/test_devops_build_commands_thru_mock.py _____
/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/tests/latest/test_devops_build_commands_thru_mock.py:10: in <module>
from azure.cli.command_modules.appservice.azure_devops_build_interactive import (
/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/azure_devops_build_interactive.py:31: in <module>
from …
```
> {AppService} Make `appservice` tests serial

- src/azure-cli/azure/cli/command_modules/appservice/access_restrictions.py
Fixes #17850 
Small change to ensure duplicate rules are not created for service endpoints (subnet/vnet) and make remove command case-insensitive.
az webapp config access-restriction add -g <rg> -n <webapp> -p 2 --subnet <subnet-name> --vnet-name <vnet-name>
az webapp config access-restriction add -g <rg> -n <webapp> -p 2 --subnet <subnet-name> --vnet-name <vnet-name>
run twice should throw an exception - even if casing is different
az webapp config access-restriction remove -g <rg> -n <webapp> --subnet <subnet-name> --vnet-name <vnet-name>
rule should be removed - even if casing is different.
[App Service] az webapp/functionapp config access-restriction add: Prevent duplicate rules using service endpoints.
[App Service] az …
> [AppService] Fix #17850 - prevent duplicate rules for service endpoints

- src/azure-cli/azure/cli/command_modules/aro/custom.py
- src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_create.yaml
- src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_delete.yaml
- src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_list.yaml
- src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_list_credentials.yaml
- src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_show.yaml
- src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_update.yaml
If someone calls `az aro delete` on a non-existing resource, print out a helpful error instead of a stack trace.  
#18501 
`az aro delete -g non-existing -n non-existing` should now raise a ResourceNotFoundError
> [ARO] Fail if resource doesn't exist on delete

- src/azure-cli/azure/cli/command_modules/sql/custom.py
We should not pass tenant Id at all times, since if external admin is missing tenant id will block create. Fixed it in the PR.
Fix for regression - **must go in S189**
---
> [SQL] Fix for server create in SQL 0.28

- src/azure-cli/azure/cli/command_modules/appconfig/_kv_helpers.py
While importing Key Vault references from AppService or AppConfig, we were overwriting the KVR content type with user specified content type. If the source key-value is recognized as a Key Vault reference, we should preserve it in destination too.
`az appconfig kv import -s appconfig -n store2 --src-name store1 --content-type text`
This command would import everything from store1 to store2 with content-type 'text'. All Key Vault References in store1 would be converted to regular key-values in store2 with content-type 'text'.
---
> [AppConfig] Stop overwriting KeyVault reference content type during import

- src/azure-cli/azure/cli/command_modules/resource/custom.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_provider_registration_rpaas.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_provider_registration_rpaas_no_accept_terms.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
az provider register: make parameter --accept-term become not required
---
> [ARM] `az provider register`: Make parameter `--accept-term` become not required

- src/azure-cli/azure/cli/command_modules/appservice/_validators.py
Fixes #18500 
When caller does not have read permissions on subscription, an empty service tag list is returned, and validation fails. This will skip validation (ARM backend will do final validation)
[AppService] az webapp config access-restrictions add: Skip validation if user does not have access to get service tag list. 
---
> [App Service] Fix #18500. Add service tag list check.

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
aks: add 'enable-ultra-ssd' parameter
```console
--enable-ultra-ssd                        : Enable UltraSSD on agent node pool.
az aks create -g MyResourceGroup -n MyManagedCluster --enable-ultra-ssd
--enable-ultra-ssd             : Enable UltraSSD on agent node pool.
az aks create -g $RESOURCE_GROUP_NAME -n $CLUSTER_NAME --node-count 2 --generate-ssh-keys --kubernetes-version 1.20.5 --node-vm-size Standard_D2s_v3 --zones 1 2 3 --enable-ultra-ssd
az aks nodepool add -g $RESOURCE_GROUP_NAME --cluster-name $CLUSTER_NAME --node-count 2 --node-vm-size Standard_D2s_v3 -n ultra2 --zones 1 2 3 --enable-ultra-ssd
```
[Component Name 2] az command b: Add …
> [AKS] add UltraSSD support

- src/azure-cli/azure/cli/command_modules/network/_help.py
- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_virtual_hub_router_scenario.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Closed #18571 
Closed https://github.com/Azure/azure-cli/issues/18386
[network] `az network routeserver create`: Add `--public-ip-address` argument.
---
> [network] `az network routeserver create`: Add `--public-ip-address` argument

- src/azure-cli/azure/cli/command_modules/appservice/appservice_domains.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/domain-contact.json
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_domain_create.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Get correct domain agreements for user to acknowledge, in `az appservice domain create` command
Backend is introducing a validation API for domain creates, and domains created through CLI are passing in different agreements than what was expected causing the validation API to fail
Fixes #18651 
---
> [AppService] az appservice domain create: Fix get correct domain agreements

- src/azure-cli/azure/cli/command_modules/appservice/_constants.py
- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/commands.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/resources/WebappRuntimeStacks.json
- src/azure-cli/azure/cli/command_modules/appservice/static_sites.py
- src/azure-cli/azure/cli/command_modules/appservice/utils.py
- src/azure-cli/setup.py
New commands for adding/removing github actions to a webapp
- `az webapp deployment github-actions add`
- `az webapp deployment github-actions remove`
Example usage:
- Add:
Navigate to https://github.com/login/device to enter code
Authorize after entering in code
- Remove:
---
> [AppService] az webapp deployment github-actions add/remove: new commands

- src/azure-cli/azure/cli/command_modules/acs/custom.py
`az aks get-credentials` does not check for the `KUBECONFIG` variable when creating/merging credentials. This PR fixes that and adds a check.
```bash
touch ~/testconfig
export KUBECONFIG=~/testconfig
az aks get-credentials -n <cluster name> -g <resource group>
```
Fixes #18700
---
> [AKS] az aks get-credentials: Add a check for KUBECONFIG environmental variable

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_other_extended_location.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_create_zones.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_extended_location.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_and_modify.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_extended_location.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Issue: #18327
Releated PR: #17522
Make dependent resources of VM/VMSS support edge zone
For VM:
- storageAccount 
- publicIPAddress 
- virtualNetwork 
- networkInterface
For VMSS:
- storageAccount 
- publicIPAddress 
- virtualNetwork 
- loadBalancer 
Because the previous fixed api-version of dependent resources is too old, it does not support edge zone. Therefore, we need to upgrade the api-version used to create dependent resources when users pass in `--edge-zone` parameter *(so as to reduce the risk of upgrading api-version, such as the possibility of breaking change in REST)* …
> [Compute] Make dependent resources of VM/VMSS support edge zone

- doc/install_linux_prerequisites.md
- src/azure-cli/azure/cli/command_modules/vm/_alias.py
- src/azure-cli/azure/cli/command_modules/vm/_validators.py
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2018_03_01/aliases.json
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2018_03_01/test_vm_actions.py
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/aliases.json
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/test_vm_actions.py
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/aliases.json
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/test_vm_actions.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/aliases.json
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_actions.py
Issue: #18484
As CoreOS is deprecated and there is no Image in the marketplace any more, update to use Flatcar linux instead of it.
---
> [Compute] Update from CoreOS to Flatcar

- src/azure-cli/azure/cli/command_modules/vm/custom.py
In the latest profile and the profiles that use the same api-version as latest profile, the default public IP used for VM creation will be expected to be changed from Basic to Standard. 
In order to avoid breaking change which has a big impact on users, we use the hint to guide users to use Standard public IP to create VM in the first stage.
---
> [Compute] Add the hint to suggest users use the standard public IP when creating VM

- src/azure-cli/azure/cli/command_modules/resource/_formatters.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_formatters.py
added missing parameter in method call
Fixes #18720 
`az deployment what-if ...`
[arm] az what-if: Fix output formatting 
---
> [ARM]: Fix ARM What-If formatter

- src/azure-cli-core/LICENSE.txt
- src/azure-cli-core/MANIFEST.in
- src/azure-cli-telemetry/LICENSE.txt
- src/azure-cli-telemetry/MANIFEST.in
- src/azure-cli-testsdk/LICENSE.txt
- src/azure-cli-testsdk/MANIFEST.in
I'm packaging Azure CLI and its dependencies in Fedora, but one of the requirements is that each package has a license file included. This change adds license files to each Python package and includes it in the manifest for each as well.
No testing changes needed.
---
> [Packaging] Add licenses to all Python packages

- src/azure-cli/azure/cli/command_modules/resource/_params.py
Add deprecate info for accept-term
---
> [ARM] `az provider register`: Add deprecate info for `--accept-term`

- src/azure-cli/azure/cli/command_modules/acr/build.py
- src/azure-cli/azure/cli/command_modules/acr/connected_registry.py
- src/azure-cli/azure/cli/command_modules/acr/pack.py
- src/azure-cli/azure/cli/command_modules/acr/run.py
Fix some bugs on uncovered  acr cmds
---
> [ACR] Fix some bugs on uncovered cmds

- src/azure-cli/azure/cli/command_modules/storage/_validators.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_blob_copy_scenarios.py
- src/azure-cli/azure/cli/command_modules/storage/util.py
Fix #18539, #18817
With `copy start` moving to track2 SDK, we need to change the replied validators, too. In previous validator, sas generation is using track1 sdk and now we need to change to track2 SDK.
Test pass locally
---
> [Storage] `az storage blob copy start`: Fix issue in copy from different account

- src/azure-cli/azure/cli/command_modules/acr/build.py
- src/azure-cli/azure/cli/command_modules/acr/connected_registry.py
- src/azure-cli/azure/cli/command_modules/acr/pack.py
- src/azure-cli/azure/cli/command_modules/acr/run.py
- src/azure-cli/azure/cli/command_modules/acr/scope_map.py
Hotfix:
* Fix some parts of `az acr build`, `az acr connected-registry`, `az acr pack`, `az acr run`, `az acr scope-map` didn't migrate to track2 SDK
---
> [ACR] hotfix based on #18786 and #18850

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/cdn/_help.py
- src/azure-cli/azure/cli/command_modules/security/_help.py
- src/azure-cli/azure/cli/command_modules/sql/_help.py
> {Linter} Add missing help to fix linter

- src/azure-cli/azure/cli/command_modules/netappfiles/_help.py
**Description** Update the help description for the `az netappfiles volume pool-change` operation that was incorrect
---
> [NetAppFiles] Update help description for pool-change

- src/azure-cli/azure/cli/command_modules/resource/_help.py
> [ARM] `az lock create/delete`: Add examples for operating different levels of locks

- src/azure-cli/azure/cli/command_modules/synapse/_help.py
- src/azure-cli/azure/cli/command_modules/synapse/operations/artifacts.py
Import notebook to a new workspace Failure due to redundant parameters
---
> [Synapse]Reimport notebook Failure

- src/azure-cli/azure/cli/command_modules/container/_vt_helper.py
- src/azure-cli/azure/cli/command_modules/container/custom.py
There were a few issues with the container exec experience:
1. terminal characters where not being handled correctly. I have added enabling virtual terminal mode to fix this.
2. on windows handling of bytes type messages ran into exceptions. use the stdout.buffer to be able to write bytes directly instead of decoding to str.
3. the logic between linux and windows was too different. Converge on a similar model for both linux and windows.
4. arrow keys and ctrl+c did not work on windows. This is fixed now
az container exec -n {cgname} -g {rgname} --exec-command {/bin/bash or /bin/sh or cmd or pwsh}
Run exec sessions with different images (both linux and windows) and see if the terminal window behaves ok
Arrow keys and ctrl+c should also work in both linux …
> [Container] `az container exec`: Fix and improve terminal experience

- src/azure-cli/azure/cli/command_modules/resource/_params.py
- src/azure-cli/azure/cli/command_modules/resource/custom.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_custom.py
Closes #18481.
Closes https://github.com/Azure/bicep/issues/2923
```
az deployment sub -l westus -f ./deploy.json --what-if
az deployment sub -l westus -f ./deploy.json --confirm-with-what-if --proceed-if-no-change
```
[ARM] az deployment group/sub/mg/tenant create: Add --what-if parameter for invoking What-If with the deployment create commands.
[ARM] az deployment group/sub/mg/tenant create: Add --proceed-if-no-change parameter to skip confirmation when --confirm-with-what-if is set and there's no changes in What-If results.
---
> [ARM] `az deployment group/sub/mg/tenant create`: Add `--what-if` and `--proceed-if-no-change` parameters

- src/azure-cli/azure/cli/command_modules/acr/_archive_utils.py
Fixes #17493
In the .dockerignore file, the leading slash for include (!) files interferes with building the file's path in both Windows and Linux environments. By removing that slash, acr build can correctly compare files in its ignore_list to the files that need to be included.
run ```"acr build --image hello-world --registry <registry_name> --file <filepath> ``` on Dockerfile whos .dockerignore contains folders ignored and files within ignored folders that should be included:
```
main
!/main/main.py
``` 
```
main
!main/main.py
``` 
---
> [ACR] `az acr build`: Make .dockerignore include directories with `!` 

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/appservice_environment.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_app_service_environment_commands_thru_mock.py
For ASEv3 GA, there are some changes, most noticeably that External ASE and Zone redundancy is now supported, and the need for private endpoint for inbound traffic is removed and now using an Azure Load Balancer like ASEv2.
ase create-inbound-services will now only create a Private DNS Zone thus the --skip-dns is not relevant. The API for getting inbound IP for ASEv3 is in azure-mgmt-web 3.0.0 and require an SDK upgrade before this can be supported.
az appservice ase create --kind asev3 [--zone-redundant] ...
[AppService] az appservice ase create: Support for ASEv3 External and Zone redundancy
---
> [App Service] `az appservice ase create`: Command changes for ASE v3 GA

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
Customer requested improved error message when hybrid connection does not exist - as the command will only add an existing hybrid connection and not create a new. Currently the error message is "Parameter 'resource_group_name' must have length greater than 1".
The PR also adds support for Linux, which has been possible for a while.
az webapp hybrid-connection add -g -n --namespace --hybrid-connection
[AppService] az webapp hybrid-connection add: Improve help/error message and unblock Linux
---
> [App Service] `az webapp hybrid-connection add`: Improve error/help message for hybrid connections

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/redis/_params.py
- src/azure-cli/azure/cli/command_modules/redis/commands.py
- src/azure-cli/azure/cli/command_modules/redis/custom.py
- src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_export_import.yaml
- src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_firewall.yaml
- src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_list_keys.yaml
- src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_list_works.yaml
- src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_patch_schedule.yaml
- src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_reboot.yaml
- src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_regenerate_key_update_tags.yaml
- src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_server_link.yaml
- src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_with_mandatory_args.yaml
- src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_with_redisversion.yaml
- src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_with_tags_and_zones.yaml
- src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_with_tlsversion_and_settings.yaml
- src/azure-cli/azure/cli/command_modules/redis/tests/latest/test_redis_scenario.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
Upgrade azure-mgmt-redis library version from 12.0.0 to 13.0.0
Add `--redis-version` param to `az redis create`  and `az redis update` commands
`az redis create -n {name} -g {rg} -l {location} --sku {sku} --vm-size {size} --redis-version {redis_version}`
Add `--redis-version` param to `az redis create`  and `az redis update` commands
---
> [Redis] Add `--redis-version` param to `az redis create` and `az redis update`

- src/azure-cli/azure/cli/command_modules/resource/_formatters.py
When using the Azure CLI to run the ARM template what-if command, there is a link to report noise (unexpected what-if results) in the output. The link directs to https://aka.ms/WhatIfIssues but this is followed by a period. Some UIs, including Azure PowerShell and Windows Terminal, detect this as https://aka.ms/WhatIfIssues. (including the period), which isn't a valid URL and opens Bing instead of the expected location.
This PR simply removes the trailing period, ensuring the link is valid.
Run the `az deployment group what-if` command with a valid resource group and template file, and notice the period is no longer present.
{Resources} az deployment group what-if: Remove trailing period.
--- …
> {Resources} az deployment group what-if: Remove trailing period from URL in output

- src/azure-cli-telemetry/azure/cli/telemetry/tests/test_telemetry_client.py
Mock is deprecated in recent python versions. Try to import `unittest.mock` if it is available on the system.
Fixes: azure/azure-cli#18976
Try to import `unittest.mock` and fall back to importing `mock`. This allows tests to run in Python 3.10 and in older Python versions.
Run the tests as you normally would.
---
> {Telemetry} Import unittest.mock in telemetry test

- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/custom_preparers.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_browse.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
* Add following test cases
* test_aks_browse, cover subcommand `browse`
* test_aks_browse_legacy, cover subcommand `browse`
* test_aks_install_kubectl, cover subcommand `install-cli`
* Refactor the implementation of subcommand `browse` 
To make it easier for the `browse` subcommand to be reused in aks-preview, we have made the following changes
* create a new internal function `_aks_browse`
* add parameter `resource_type`  to function `_aks_browse` to support multi-version api
* Add new option `preserve_default_location` for `AKSCustomResourceGroupPreparer`
* to support those test cases that can only be executed in a specific region
[Component …
> {AKS} Refactor acs module

- src/azure-cli-core/setup.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
Add the extra `[socks]` require for requests to add socks libraries to the
dependancies.
This adds SOCKS Proxy support to requests which allows AZ CLI to operate behind a SOCKS proxy - this fixes #18930 
- `export ALL_PROXY=socks5h://<host>:<port>`
- Run any `az` command that makes a network call
---
> [Packaging] Add SOCKS Proxy Support

- src/azure-cli-core/azure/cli/core/util.py
Fix #14711
Migrate the work from #15361, #15455
When calling `powershell.exe` from WSL, the [PowerShell profile](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-5.1) is executed, causing additional irrelevant PowerShell script to be executed.
This PR adds `-NoProfile` when calling `powershell.exe` so that the PowerShell profile execution is skipped.
To repro
1. Create `C:\Users\<user>\Documents\WindowsPowerShell\Profile.ps1` with
```pwsh
Write-Host test_profile
```
2. Run `az login`. Notice the terminal will show
```
test_profile
```
After the change, `test_profile` is no longer shown.
There was an attempt #15454 to extract a common `start_powershell_process` but it adds more complexity.
> {Core} Add `-NoProfile` when calling `powershell.exe`

- src/azure-cli/azure/cli/command_modules/acs/custom.py
In some cases, the `kubectl` minor version can include non-numeric characters`20+`. (For example, #17769) This causes an issue parsing the minor version. This PR makes it so that all non-numeric characters are stripped out before parsing the version.
`az aks check-acr --name {} --resource-group {} --acr {}`
[AKS] az aks check-acr: Fix issues parsing certain client minor versions
Closes #17769
Closes #18314
Closes #18263
Closes #16936
---
> [AKS] `az aks check-acr`: Fix the crashes when kubectl minor version includes non-numeric chars

- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
We recently received an ICM: the command `az vm list-skus` can't get the SKU with only part of the zones available
The information of this SKU is as follows:
```json
{
...
"locationInfo": [{
"location": "eastus",
"zoneDetails": [{
"Name": [
"2",
"3",
"1"
],
"capabilities": [{
"name": "UltraSSDAvailable",
"value": "True"
}],
"name": null
}],
"zones": [
"2",
"3",
"1"
]
}],
...
"restrictions": [{
"reasonCode": "NotAvailableForSubscription",
"restrictionInfo": {
"locations": [
"eastus"
],
"zones": [
"2",
"3"
]
},
"type": "Zone",
"values": [
"eastus"
]
}],
...
}
```
As we can see, `2` and `3` zone in `restrictions` are restricted for reason `NotAvailableForSubscription`, but `1` zone is still available, So this SKU should be able to get.
However, in the original logic [code …
> [Compute] `az vm list-skus`: Fix the issue that it can't query the SKU which with partially zones available

- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/_params_azure_stack.py
- src/azure-cli/azure/cli/command_modules/storage/operations/azcopy.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_azcopy_scenarios.py
> [Storage] `az storage copy` add new option `--cap-mbps`

- src/azure-cli-core/azure/cli/core/profiles/_shared.py
Without logging the original `ImportError`, it is very difficult to identify the actual cause for a failure, such as #18159:
> ModuleNotFoundError: No module named '_cffi_backend'
In the current code, when `ImportError` occurs, `get_sdk` returns `None`, thus hiding the original error with
> TypeError: 'NoneType' object is not callable
Rename `<venv_name>\Lib\site-packages\_cffi_backend.cp39-win_amd64.pyd` to something else, then run
```
az storage blob list --account-name myst --account-key xxx --container-name test --debug
...
File "D:\cli\py39\lib\site-packages\azure\multiapi\storage\v2018_11_09\blob\__init__.py", line 6, in <module>
from .appendblobservice import AppendBlobService
File "D:\cli\py39\lib\site-packages\azure\multiapi\storage\v2018_11_09\blob\appendblobservice.py", line …
```
> {Core} Log `_get_attr` exceptions

- azure-pipelines.yml
Job `TestYumPackage` keeps timing out:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1025054&view=logs&j=b1448c29-704b-5199-1998-7fb1cec36b60&s=b15d9194-8f26-5328-b47f-5968c76b37e7
```
##[error]The job running on agent Azure Pipelines 18 ran longer than the maximum time of 60 minutes. For more information, see https://go.microsoft.com/fwlink/?linkid=2077134
Agent: Azure Pipelines 18
Started: Today at 5:39 PM
Duration: 1h 0m 6s
```
This seems to be caused by slow agent. It succeeded on `dev` branch:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1024948&view=logs&j=1e6fba43-bdcf-51f0-a062-3712c33fbb51
```
Pool: Azure Pipelines
Image: ubuntu-20.04
Agent: Azure Pipelines 23
Started: Today at 3:30 PM
Duration: 41m 31s
```
This PR increases …
> {CI} Increase TestYumPackage's timeoutInMinutes

- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/custom_preparers.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_autoscaler.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_default_service.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_disable_rbac.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_enable_azure_rbac.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_enable_encryption.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_loadbalancer.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_network_cidr.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_node_public_ip.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_with_custom_monitoring_workspace.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
* Add following test cases for sub-command `create`
* test_aks_create_autoscaler
* test_aks_create_loadbalancer
* test_aks_create_node_public_ip
* test_aks_create_network_cidr
* test_aks_create_attach_acr (live_only, also cover `check-acr`)
* test_aks_create_with_outbound_type_udr (live_only)
* test_aks_create_node_osdisk_diskencryptionset (live only)
* test_aks_create_enable_encryption (need to register feature 'Microsoft.Compute/EncryptionAtHost')
* test_aks_create_enable_azure_rbac
* test_aks_create_disable_rbac
* test_aks_create_with_custom_monitoring_workspace
* Modify following test cases for sub-command `create`
* test_aks_create_default_service
* test_aks_byo_subnet_with_ingress_appgw_addon (live_only)
* Add `AKSCustomRoleBasedServicePrincipalPreparer`
* resolve …
> {AKS} Refactor acs module: add test cases for sub-command `create`

- src/azure-cli/azure/cli/command_modules/cosmosdb/_params.py
The --enable-analytical-storage command line switch when creating or updating CosmosDB accounts is currently labeled as a preview feature, though it is now out of preview.  The change removes the preview label.
---
> {Cosmosdb} GA --enable-analytical-storage

- src/azure-cli/azure/cli/command_modules/resource/_formatters.py
- src/azure-cli/azure/cli/command_modules/resource/_symbol.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_formatters.py
Fixes #19124.
```
az deployment group/sub/mg/tenant what-if ...
```
---
> [ARM] Fix #19124: `az deployment what-if`: Handle unsupported and no effect change types

- src/azure-cli/azure/cli/command_modules/role/_params.py
Fix https://github.com/Azure/azure-cli/issues/18616
`az role assignment create`: Support `ForeignGroup` for `--assignee-principal-type`
Azure CLI overrides `PrincipalType` in #16056 because of REST spec issue https://github.com/Azure/azure-rest-api-specs/issues/11830.
The code is copied from Python SDK `azure.mgmt.authorization.v2020_04_01_preview.models._authorization_management_client_enums.PrincipalType`
```
foreign_group = "ForeignGroup"
```
This PR is still a workaround and the ultimate solution should be the fix for https://github.com/Azure/azure-rest-api-specs/issues/11830.
```
> az role assignment create -h
--assignee-principal-type     : Use with --assignee-object-id to avoid errors caused by
propagation latency in AAD Graph.  Allowed values: ForeignGroup,
Group, …
```
> [Role] `az role assignment create`: Support `ForeignGroup` for `--assignee-principal-type`

- src/azure-cli-core/azure/cli/core/_profile.py
Fix #19048, Email: _Unable to use MSI credentials for logging into a VM_
As discussed with VM team, VM SSH currently doesn't support **managed identity** and **Cloud Shell**.
Currently, with managed identity, the command fails with
```
$ az ssh vm --resource-group vm-ssh-rg --vm-name myvm
No matched service principal found
```
In Cloud Shell, the command fails with
```
$ az ssh vm --resource-group vm-ssh-rg --vm-name myvm
Could not retrieve token from local cache.
```
This PR replaces these obscure error messages with more definitive ones.
Run `az ssh vm` on a VM with managed identity:
```
$ az ssh vm --resource-group vm-ssh-rg --vm-name myvm
VM SSH currently doesn't support managed identity.
```
In Cloud Shell:
```
$ az ssh vm --resource-group vm-ssh-rg --vm-name myvm
VM SSH currently …
```
> [Compute] `az ssh vm`: Raise error for managed identity and Cloud Shell
