- scripts/release/debian/deb_install.sh
Ubuntu releases 2 distros every year. Currently we need to submit tickets to ask Linux Team to add a new repo in `packages.microsoft.com` and modify our release pipeline to add the package which takes some time. Meanwhile, the new distros can often use a package for a previous distro. This PR adds checks for whether the ubuntu/debian distro is supported with a specific package, if not use the latest stable distro package for it. This PR also adds support for the ubuntu-derived LinuxMint distros by using its upstream dist code name.
For other unsupported ubuntu-derived or debian-derived systems, if you know the compatible package you can specify it with the DIST_CODE variable. Run with:
`sudo DIST_CODE=bionic bash deb_install.sh` or 
`curl -sL …
> {Deb Install} Add support for more systems and user provided dist name

- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/_params_azure_stack.py
- src/azure-cli/azure/cli/command_modules/storage/tests/hybrid_2019_03_01/recordings/test_storage_create_default_kind.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_create_default_kind.yaml
For Azure Stack env, it always requires that default kind is Storage.
`az storage account create` in different profile.
---
> {Storage} Make sure default kind is Storage in Azure Stack

- src/azure-cli/azure/cli/command_modules/acr/_params.py
Updating the description for the `--key-encryption-key` command line argument.
---
> [ACR] Update description for KEK param

- src/azure-cli/azure/cli/command_modules/servicefabric/_help.py
Update the documentation for apps, app types, and services calling out explicitly that the support is only for ARM deployed resources.
---
> [ServiceFabric] Update SF app docs. only support for arm deployed resources

- src/azure-cli/azure/cli/command_modules/network/commands.py
Deprecate route table V1, please see details in: #15927
---
> [Network] Deprecate route table V1

- src/azure-cli/azure/cli/command_modules/storage/_params_azure_stack.py
> {Storage} Remove max api for azure stack

- scripts/live_test/CLITest.yml
- scripts/live_test/HISTORY.rst
- scripts/live_test/clean_policy.py
- scripts/live_test/generate_index.py
- scripts/live_test/sendemail.py
* Update index.html and update email content.
* Clean policy automatically.
* Fix "No log output captured" problem.
---
> {Test} Live test pipeline update

- src/azure-cli/azure/cli/command_modules/vm/_help.py
fix broken link. breaking commit: https://github.com/MicrosoftDocs/azure-docs/commit/67dcbf8818752f0013019605945bdef5ea668136
document change
---
> {Compute} src/azure-cli/azure/cli/command_modules/vm/_help.py fix broken link

- scripts/release/homebrew/docker/formula_template.txt
- scripts/release/homebrew/docker/run.sh
Remove the Xcode 11 work around as the issue is fixed.
Revert to build formula by updating the master branch in [homebrew/core](https://github.com/Homebrew/homebrew-core/blob/master/Formula/azure-cli.rb)
---
> {Package} Update homebrew template and revert to build with update_existing

- src/azure-cli/azure/cli/command_modules/storage/_help.py
Simple typo fixes in the the storage/_help.py file
n/a
[storage] Fixed misspelling of "destination"
---
> [storage] Typo fixes in help doc

- src/azure-cli/azure/cli/command_modules/util/commands.py
Mark az upgrade preview, to avoid misleading users.
---
> {Misc} Mark az upgrade preview

- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_mysql.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
This PR updates the error message to show to the user if they pass a server name containing UPPERCASE characters.
> {RDBMS} Update error message if user passes server name in upper case

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
removing an extra word "with". Adding an example for creating a Windows container app service plan with the new PV3 SKU.
removing an extra word "with". Adding an example for creating a Windows container app service plan with the new PV3 SKU. Windows container GA'd over a month ago with the new PV3 SKU.  
1. run the command:
az appservice plan create -g MyResourceGroup -n MyPlan \\
--hyper-v --sku P3V3
2. This will create a new Windows container app service plan
---
> {AppService} Update _help.py with typo and example

- src/azure-cli/azure/cli/command_modules/batch/tests/latest/test_batch_data_plane_commands.py
- src/azure-cli/azure/cli/command_modules/cognitiveservices/tests/latest/test_byox.py
- src/azure-cli/azure/cli/command_modules/cognitiveservices/tests/latest/test_identity.py
Fix cognitiveservices and batch test
Two major problems: (1) time problem. (2) quota limit when test cases are running at same time.
---
> {Test} Fix cognitiveservices and batch test

- .github/CODEOWNERS
> {CODEOWNER} update code owner

- doc/error_handling_guidelines.md
> {Error Improvement} Error handling guidelines for extensions

- azure-pipelines.yml
- scripts/release/debian/test_deb_in_docker.sh
Tested in build_test branch and installed the [package](https://dev.azure.com/azure-sdk/public/_build/results?buildId=638763&view=artifacts&pathAsName=false&type=publishedArtifacts) with groovy docker image. 
---
> [Packaging] Add Ubuntu Groovy package

- src/azure-cli-core/azure/cli/core/profiles/_shared.py
- src/azure-cli/azure/cli/command_modules/resource/commands.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/deployment-scripts-deploy.json
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_delete_deployment_script.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_list_all_deployment_scripts.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_show_deployment_script.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_show_deployment_script_logs.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
This PR removes the preview flag from az deployment-scripts commands, and uses the latest api-version which is 2020-10-01.
Not much changes from before, just added a create and read corresponding to 2020-10-01 api-version.
---
> [ARM] az deployment-scripts: Removed preview flag

- src/azure-cli/azure/cli/command_modules/monitor/_help.py
- src/azure-cli/azure/cli/command_modules/monitor/_params.py
- src/azure-cli/azure/cli/command_modules/monitor/actions.py
- src/azure-cli/azure/cli/command_modules/monitor/commands.py
- src/azure-cli/azure/cli/command_modules/monitor/grammar/metric_alert/MetricAlertCondition.g4
- src/azure-cli/azure/cli/command_modules/monitor/grammar/metric_alert/MetricAlertConditionLexer.py
- src/azure-cli/azure/cli/command_modules/monitor/grammar/metric_alert/MetricAlertConditionListener.py
- src/azure-cli/azure/cli/command_modules/monitor/grammar/metric_alert/MetricAlertConditionParser.py
- src/azure-cli/azure/cli/command_modules/monitor/grammar/metric_alert/MetricAlertConditionValidator.py
- src/azure-cli/azure/cli/command_modules/monitor/operations/metric_alert.py
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_dynamic_metric_alert_multiple_scopes.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_dynamic_metric_alert_v2_scenario.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_metric_alert_condition_create.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_metric_alert_scenarios.py
- src/azure-cli/azure/cli/command_modules/monitor/validators.py
[monitor] az monitor metrics alert create: Support dynamic thresholds for condition parameter.  
[monitor] az monitor metrics alert update: Support dynamic thresholds for condition parameter.  
[monitor] az monitor metrics alert dimension create: Build a metric alert rule dimension.
[monitor] az monitor metrics alert condition create: Build a metric alert rule condition.
---
> [monitor] az monitor metrics alert support dynamic thresholds

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_slb_vmss_with_outbound_ip_prefixes_then_update_msi.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_slb_vmss_with_outbound_ip_then_update_msi.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_express_route_port_generate_loa.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_open_port.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_set_os_disk_size.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_single_placement_group_default_to_std_lb.yaml
Add missing recording file: test_vm_open_port.yaml
---
> {Misc} Add missing recording file

- src/azure-cli/azure/cli/command_modules/iot/_utils.py
- src/azure-cli/azure/cli/command_modules/iot/custom.py
Updated device key generation to use python `secrets.token_bytes`
---
> [iot] Updated device key generation

- src/azure-cli/azure/cli/command_modules/batch/_help.py
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/README.md
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/data/batch-pool-create.json
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_application_cmd.yaml
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_certificate_cmd.yaml
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_general_arm_cmd.yaml
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_job_list_cmd.yaml
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_jobs_and_tasks.yaml
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_pool_cmd.yaml
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_pools_and_nodes.yaml
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_task_create_cmd.yaml
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/test_batch_commands.py
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/test_batch_data_plane_commands.py
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/test_batch_mgmt_commands.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
* Batch data plane (azure-batch) upgraded to 10.0.0
* `az batch job task-counts` now returns a complex object including both task counts as well as task slot counts
* Updated Batch testing README
Upgrades the Batch data plane to 10.0.0 (API version 2020-09-01.12.0) for task slot support
Testing the Batch module is described in the [README file](https://github.com/Azure/azure-cli/blob/feature/batch-data-plane-10.0.0/src/azure-cli/azure/cli/command_modules/batch/tests/latest/README.md).
[Batch] Upgrades data plane to [azure batch 10.0.0](https://pypi.org/project/azure-batch/10.0.0/)
[Batch] BREAKING CHANGE: az batch job task-counts: Change the output from a JSON object returning task counts to a complex JSON object that includes task …
> [Batch] azure-batch 10.0.0 / API v2020-09-01.12.0

- .github/CODEOWNERS
Updates Batch code owners
N/A
N/A
---
> {CODEOWNER} Update code owners for Batch module

- src/azure-cli/azure/cli/command_modules/acs/custom.py
This PR adds back two arguments that were removed in a [previous PR](https://github.com/Azure/azure-cli/pull/15993).
---
> [AKS] fix: add arguments removed by a previous PR

- .github/CODEOWNERS
Update CODEOWNERS to remove @arrownj.
> {Misc.} Update CODEOWNERS

- .github/CODEOWNERS
> {Misc} Update codeowners

- .azure-pipelines/templates/automation_test.yml
Fix https://github.com/Azure/azure-cli/issues/16151 as many of our developers would like to see the summary of the error report in CI instead of the quick speed of discovering flaws.
Verification PR https://github.com/Azure/azure-cli/pull/16191. The output of it shows the modification is correct and would give a summary at the end of log
---
> {CI} Enable --no-exitfirst for automation test in CI

- src/azure-cli/azure/cli/command_modules/aro/_rbac.py
- src/azure-cli/azure/cli/command_modules/aro/custom.py
- src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_delete.yaml
Upstreams https://github.com/Azure/ARO-RP/pull/1126 which adds RBAC validation on ARO cluster deletion, unblocking deletions when customers remove SPN permissions.
---
> [ARO] az aro delete: Add RBAC validation on cluster deletion

- doc/parampersist_localcontext_guidelines.md
Update local context doc for new name param persist
---
> {Misc} Update local context doc for new name param persist

- azure-pipelines.yml
Extensions are getting more many than previous, 10 mins is not enough to load all extensions
---
> {CI} increase the timeout threshold of extension loading job

- src/azure-cli/azure/cli/command_modules/storage/commands.py
Since service will be GA, CLI would remove the preview tag for GA, too
---
> [Storage] `az storage account encryption-scope`: GA support

- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_metric_alert_for_rg_and_sub.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_clone_vm_metric_alerts_scenario.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_log_analytics_workspace_data_export.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_log_analytics_workspace.py
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_private_link_scope.py
Against the latest live test report https://clitestresultstac.blob.core.windows.net/20201211-043721-979918/monitor.report.parallel.html
1. test `test_metric_alert_for_rg_and_sub` is untouched, just pass after rerun. No idea why live test failed.
2. test `test_monitor_clone_vm_metric_alerts_scenario` is untouched, just pass after rerun. No idea why live test failed.
3. test `test_monitor_log_analytics_workspace_data_export` is untouched, just pass after rerun. No idea why live test failed.
4. test `test_monitor_log_analytics_workspace_data_export` failed because service introduce a breaking change without notifying us and it's awarded by the user #15742. @kairu-ms will take care of it.
5. test `test_monitor_private_link_scope_scenario` is buggy due to service problem who …
> {Monitor} Fix monitor test 7/7

- src/azure-cli/azure/cli/command_modules/network/_validators.py
Fix https://github.com/Azure/azure-cli/issues/15976
password is not necessary when using self-signed ssl file
None
---
> [Network] Change validator of application-gateway ssl-cert create

- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_webapp.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
fix https://github.com/Azure/azure-cli/issues/15621
According to the [report](https://clitestresultstac.blob.core.windows.net/20201211-043721-979918/network.report.parallel.html), network already meets the requirement 95%+.
After this fix, network should be able to be close to 100% pass rate
---
> {Network} Fix live test

- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone9_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_dns_commands.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone9.txt
- src/azure-cli/azure/cli/command_modules/network/zone_file/parse_zone_file.py
> {network} fix network dns zone import @ support issue

- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_traffic_manager2.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
add parameter "--max-return " when using "--routing-method MultiValue" (https://github.com/Azure/azure-cli/issues/16195)
azdev test test_network_traffic_manager2 --live
---
> [Network] bugfix for "az network traffic-manager profile create" when using "--routing-method MultiValue" 

- src/azure-cli/azure/cli/command_modules/storage/_help.py
This incorrect example cause Aladdin pipeline fail
After fixing this, Aladdin could generate PR as usual
---
> {Storage} fix help

- README.md
Add the required [Telemetry Notice](https://docs.opensource.microsoft.com/content/releasing/index.html) for an open source project, including:
- instructions to turn off the telemetry;
- data collection notice in the README.md file.
---
> {Doc} Add data collection statement

- src/azure-cli-core/azure/cli/core/telemetry.py
This pr removes the trace stack info in Telemetry, as it may include user sensitive info.
---
> {Telemetry} Reomve trace stack info in Telemetry

- src/azure-cli/azure/cli/command_modules/acs/_help.py
> {AKS} Fix typo: vent -> vnet

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/setup.py
- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/__main__.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
> {Release} HotFix: Release 2.17.1

- azure-pipelines.yml
- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/setup.py
- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/__main__.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_virtual_network.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
Merge `release` back to `dev`.
> {Branch Management} Merge release 2.17.1 back to dev

- azure-pipelines.yml
- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/setup.py
- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/__main__.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_virtual_network.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
> {Release} Release beta 2.17.11

- src/azure-cli/azure/cli/command_modules/rdbms/commands.py
Remove the preview tag for server key and ad admin commands for Postgres and MySql
---
> [RDBMS]Remove the preview tag for server key and ad admin commands for Postgres and MySql

- src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_storage_account.yaml
As you can see in swagger, it is supported. So change to True.
https://github.com/Azure/azure-rest-api-specs/blob/d0deec5d2eeb6169dd24d7943296307d628ec278/specification/storage/resource-manager/Microsoft.Storage/stable/2019-06-01/storage.json#L823
---
> {Network} Support list for storage private endpoint connection

- src/azure-cli/azure/cli/command_modules/vm/_help.py
Adding a link to an article that walks folks through how to get the URN for an image.
---
> {Compute} Update _help.py - add link to article for finding an image URN

- src/azure-cli/azure/cli/command_modules/storage/operations/blob.py
> [Storage] Fix issue #12291: az storage blob generate-sas does not properly encode --full-uri

- NOTICE.txt
The `paramiko` dependency package uses LGPL-2.1 license and needs to be added in the `NOTICE.txt` file.
The content is generated by ADO Component Governance.
---
> {Legal} Add paramiko to notice file

- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_reimage.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Resolve https://github.com/Azure/azure-cli/issues/16465
AttributeError: 'VirtualMachineScaleSetVMsOperations' object has no attribute 'reimage'
There was no test for this command. So it was not revealed in Track 2 SDK upgrade.
---
> [Compute] Fix a vmss reimage issue

- scripts/release/homebrew/docker/formula_generate.py
The released homebrew [formula](https://github.com/homebrew/homebrew-core/blob/master/Formula/azure-cli.rb) removed the version field as it now uses a [url](https://github.com/homebrew/homebrew-core/blob/master/Formula/azure-cli.rb#L6) based on release tag and can extract version from the url. But in the build of azure-cli pipeline, we still use a url based on commit and need to add version explicitly.
This PR adds the version in homebrew foumula when it's built based on the formula from homebrew master branch.
The url will be updated to use the release tag one and the version will be removed in the release pipeline.
For example, the formula generated with CI build looks like:
```
url "https://codeload.github.com/Azure/azure-cli/legacy.tar.gz/7e09fd50c9ef02e1ed7d4709c7ab1a7 …
```
> {Packaging} Patch version in homebrew formula

- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
[Bug report](https://github.com/Homebrew/brew/issues/10152#issuecomment-753334171) for cffi 1.14.0 with Homebrew. It was fixed in brew formula manually in this [PR](https://github.com/Homebrew/homebrew-core/pull/68126).
---
> {Packaging} Bump cffi to 1.14.4

- src/azure-cli/azure/cli/command_modules/storage/__init__.py
Need to remove the suppression when the extension is removed in  https://github.com/Azure/azure-cli-extensions/pull/2903
---
> {Storage} Remove  extension suppression for storage-or-preview because it is removed

- README.md
Fix broken link in readme.md.
---
> {Misc} Fix broken link

- src/azure-cli/azure/cli/command_modules/storage/_client_factory.py
- src/azure-cli/azure/cli/command_modules/storage/_validators.py
> [Storage] Fix #16079: public blob gives error

- doc/track_2_migration_roadmap.md
> {Docs} Roadmap for track2 migration

- src/azure-cli/azure/cli/command_modules/acs/commands.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_stop_and_start.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Add bindings for managed cluster stop/start in core cli, rather than extensions
az aks stop -g "resource group" -n "cluster name"
az aks start -g "resource group" -n "cluster name"
---
> [AKS] Add managed cluster stop/start bindings

- CONTRIBUTING.rst
Fix #16015
Use the link in [knack](https://github.com/microsoft/knack/blob/master/CONTRIBUTING.rst) to fix the broken link.
---
> {Doc} Fix broken link in CONTRIBUTING.rst

- doc/authoring_help.md
- doc/authoring_tests.md
- doc/classic_cli_migration.md
- doc/extensions/authoring.md
- doc/local_context_guidelines.md
- doc/parampersist_localcontext_guidelines.md
- doc/use_cli_in_airgapped_clouds.md
- doc/use_cli_with_git_bash.md
Added missing code tags or changed incorrect code tags (for example, bash to azurecli) as part of an Azure CLI content cleanup. No code changes or major content changes made.
User story [1801203](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1801203)
N/A
N/A
---
> {Doc} Fixed missing or incorrect code tags BULK

- src/azure-cli/azure/cli/command_modules/keyvault/_params.py
Fix #16621: Remove preview tag of `--enable-rbac-authorization` for command `az keyvault create/update`
---
> [KeyVault] `az keyvault create/update`: Remove preview tag for `--enable-rbac-authorization`

- src/azure-cli/azure/cli/command_modules/storage/_help.py
- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/_validators.py
- src/azure-cli/azure/cli/command_modules/storage/operations/account.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_default_service_properties.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
`az storage account blob-service-properties update` with `--default-service-version`
---
> [Storage] `az storage account blob-service-properties`: Support default service version 

- src/azure-cli-core/azure/cli/core/parser.py
Use a short link to prepare for migration to AME subscription. 
The [extension sync pipeline](https://dev.azure.com/azure-sdk/internal/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=1608&view=Tab_Tasks) now builds the extension command tree and upload to storage accounts of both Corp subscription and AME subscription. At some point in the future, we can stop updating the file in the Corp subscription.
---
> {Misc.} Use short link for extension command tree

- src/azure-cli/azure/cli/command_modules/storage/_validators.py
- src/azure-cli/azure/cli/command_modules/storage/azcopy/util.py
- src/azure-cli/azure/cli/command_modules/storage/operations/azcopy.py
> [Storage] Fix #16519: azcopy is given more powerful SAS than needed (has write, only needs read)

- src/azure-cli/azure/cli/command_modules/rdbms/_flexible_server_util.py
- src/azure-cli/azure/cli/command_modules/rdbms/_params.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_virtual_network.py
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_flexible_server_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_vnet_mgmt_supplied_vnet.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands.py
- Users can choose available zone when restoring the PG server.
- The default value for restore time is set to current time. 
- Added password test
- [IMPORTANT] Added Storage service endpoint to vnet/subnet when provisioning a database server with that to address OPAPH issue (restore failure in PROD). 
---
> [RDBMS] Update Postgres restore command to support available zone

- src/azure-cli/azure/cli/command_modules/acs/custom.py
> [AKS] az aks check-acr: Fix Kubernetes version check

- src/azure-cli-core/azure/cli/core/extension/operations.py
- src/azure-cli/az
- src/azure-cli/azure/cli/command_modules/util/custom.py
Resolve #16250.
The `rdbms-connect` extension depends on `pgcli` which eventually depends on [psycopg2](https://pypi.org/project/psycopg2/). `psycopg2` does not release wheels for Linux/macOS, it will be built from source code during installation of the `rdbms-connect` extension. The build process needs extra system dependencies. We need to handle it before the extension is downloaded and installed with pip.
Tested with Ubuntu Focal, CentOS 8, Fedora 30, SLES 15 and macOS, windows.
az extension add -s https://azurecliprod.blob.core.windows.net/cli-extensions/rdbms_connect-0.1.0-py2.py3-none-any.whl -y …
> {Extension} Install system dependencies for rdbms-conenct extension

- src/azure-cli/azure/cli/command_modules/acs/_help.py
Add options for node-os-disktype in help. Fixes #16774 .
---
> {AKS} Add options for Node OS Disk Type in help

- src/azure-cli/azure/cli/command_modules/vm/custom.py
> {Compute} Fix disk busrting default value issue

- NOTICE.txt
- scripts/release/homebrew/docker/requirements.txt
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
Resolve [CVE-2020-28493](https://cve.mitre.org/cgi-bin/cvename.cgi?name=2020-28493)
---
> {Packaging} Bump jinja2

- src/azure-cli-core/azure/cli/core/parser.py
Fix the warning from Pylance that a variable is possibly unbound.
---
> {Core} Fix unbound variable

- src/azure-cli/azure/cli/command_modules/apim/commands.py
> [APIM] GA the command group

- azure-pipelines.yml
- src/azure-cli/setup.py
pip is pinned in #16097 because of failure in CI when installing local builds with a modified version using `pip 20.3`, which is already fixed in #16302, so unpin it.
Revert the `azure-cli-core` version in `setup.py` of `azure-cli` to use the exact version. It can now support released production version (`2.18.0`), edge builds version (`2.18.0.post20210203051742`), and beta version (`2.18.0.1`).
---
> {CI} Unpin pip

- src/azure-cli/azure/cli/command_modules/storage/azcopy/util.py
We need to download azcopy and write to `.azcopy` folder.
So we need to grant write access first.
---
> {Storage} Grant right to azcopy install directory

- src/azure-cli/azure/cli/command_modules/vm/manual/commands.py
> {Compute} Remove wrong experimental label

- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/tests/test_util.py
- src/azure-cli/azure/cli/command_modules/hint/__init__.py
- src/azure-cli/azure/cli/command_modules/hint/custom.py
- src/azure-cli/azure/cli/command_modules/hint/tests/latest/__init__.py
- src/azure-cli/azure/cli/command_modules/hint/tests/latest/test_hint_custom.py
- src/azure-cli/azure/cli/command_modules/util/_help.py
- src/azure-cli/azure/cli/command_modules/util/commands.py
- src/azure-cli/azure/cli/command_modules/util/custom.py
Post-output hint for edge build. Corresponds to the official PR https://github.com/Azure/azure-cli/pull/16242.
> {Hint} Post-output hint for edge build

- doc/track_2_migration_roadmap.md
> {Doc} Update track2 migration roadmap

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/setup.py
- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/__main__.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
HotFix: Release 2.19.1
Pin version for `azure-keyvault-administration`
> {Release} HotFix: Release 2.19.1

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/setup.py
- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/__main__.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
> {Branch Management} Merge release 2.19.1 back to dev

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/setup.py
- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/__main__.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
> {Branch Management} Merge release 2.19.1 to beta

- src/azure-cli/azure/cli/command_modules/storage/_validators.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_validators.py
Fix #16959 
Live test passes and add unit test
---
> [Storage] Fix #16959: az storage copy crashes: ValidationError: local variable 'service' referenced before assignment

- src/azure-cli/azure/cli/command_modules/network/commands.py
`az network route-table` revert deprecation.
---
> {Network} Revert deprecation for network route table

- src/azure-cli/azure/cli/command_modules/storage/tests/latest/mgmt_policy.json
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_management_policy.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
For https://portal.microsofticm.com/imp/v3/incidents/details/224972645, we need to wait for SDK release.
---
> [Storage] Support version in Lifecyle management policy

- .github/CODEOWNERS
> {codeowner} update cosmosdb codeowner

- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/operations/account.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_resource_access_rules.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
> [Storage]`az storage account network-rule`: GA resource access rules

- src/azure-cli/setup.py
When generateRandomAppNames.json file was added, it was not added in the setup file causing some installations to not include it
---
> [AppService] Bugfix: Add generateRandomAppNames.json to setup

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/resources/LinuxFunctionsStacks.json
- src/azure-cli/azure/cli/command_modules/appservice/resources/WindowsFunctionsStacks.json
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_consumption_linux_dotnet_isolated.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_on_linux_app_service_dotnet_isolated.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_windows_runtime_dotnet_isolated.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
This is mainly a stacks update to add support for the new and in preview dotnet-isolated runtime. This is different from dotnet because it runs in a separate process from the functions host. I also had to add a bit of temporary custom code because of a known bug that's being fixed for creating dotnet-isolated linux consumption apps (linuxFxVersion needs to be blank in this scenario). It will be removed as soon as the bug is fixed.
I added 3 news tests to make sure the CLI is able to create dotnet-isolated apps for a variety of scenarios (windows consumption, linux dedicated and consumption).
```
test_functionapp_on_linux_app_service_dotnet_isolated
test_functionapp_consumption_linux_dotnet_isolated
test_functionapp_windows_runtime_dotnet_isolated
``` …
> [AppService] functionapp: Added support for in preview dotnet-isolated runtime.

- src/azure-cli/azure/cli/command_modules/network/_util.py
addition for : https://github.com/Azure/azure-cli/pull/17088
---
> {Network} workaround for load balancers about change of 'zone'

- .azure-pipelines/templates/azdev_setup.yml
- azure-pipelines.yml
> {Pipeline} update azdev version to 0.1.29 in pipline

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
Adding --no-uptime-sla such that a cluster can be turned into free SKU from paid SKU.
---
> [AKS] Add --no-uptime-sla

- src/azure-cli/azure/cli/command_modules/acr/check_health.py
> [acr] fix a bug when run check-health behind corporate proxy

- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_user_update_win.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Resolve https://github.com/Azure/azure-cli/issues/16962
Resolve https://github.com/Azure/azure-cli/issues/16712
Resolve https://github.com/Azure/azure-cli/issues/16392
---
> [Compute] Fix a Windows vm user update bug

- azure-pipelines.yml
To mitigate the impact of broken build trigger on dev branch ([ongoing support](https://developercommunity.visualstudio.com/t/build-pipline-no-longer-automatically-triggered-fo/1329868) from engineering team to fix it), I have set up daily scheduled runs to make edge builds. This PR fills the gap for the packages that are not built in scheduled CI runs. 
---
> {CI} Build packages in scheduled runs for edge builds

- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_frontend_ip_zone.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_public_ip_prefix_zone.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
https://github.com/Azure/azure-cli/issues/15015
workaround only work in internal loadbalancer without 'subnet'
test_network_lb_frontend_ip_zone
test_network_public_ip_prefix_zone
[Network] `az network public-ip prefix  create`: Support `--zone 1 2 3`
[Network] `az network lb  frontend-ip create`: Support `--zone 1 2 3`
---
> {Network}`az network lb frontend-ip create`: Support '--zone 1 2 3'

- src/azure-cli/azure/cli/command_modules/configure/commands.py
https://github.com/Azure/azure-cli/issues/17169
---
> [Cache] GA `az cache`

- src/azure-cli/azure/cli/command_modules/vm/_help.py
- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_open_port.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
az vm open-port now allows comma separated values and ranges, in addition to wildcard or single value.
---
> [VM] Add #16037: az vm open-port accepts list of ports

- src/azure-cli/azure/cli/command_modules/cdn/_help.py
- src/azure-cli/azure/cli/command_modules/cdn/_params.py
Fix rule engine action name parameter's enum type constraint.
az afd rule create --help
---
> [CDN] `az afd rule create`: Fix '--help' message

- src/azure-cli/azure/cli/command_modules/resource/_bicep.py
Closes https://github.com/Azure/azure-cli/issues/17083.
```
az bicep build --files ./foo.bicep
```
---
> [ARM] az bicep build: fix an issue where build warnings are not shown

- src/azure-cli/azure/cli/command_modules/search/commands.py
Closed https://github.com/Azure/azure-cli/issues/17167
---
> [Search] `az search`: GA

- src/azure-cli/HISTORY.rst
An user reported "virtual_machine_extension_type" becomes "type_properties_type" in VM resource
---
> {Compute} Update history notes

- src/azure-cli/azure/cli/command_modules/storage/_params.py
> {Storage} Ignore x-ms-snapshot

- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_image_terms.yaml
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
bump marketplaceordering sdk to Track2
---
> {Misc.} Bump marketplaceordering sdk to Track2

- .github/CODEOWNERS
> {codeowner} add codeowner

- doc/track_2_migration_roadmap.md
> {Doc} Update roadmap for CLI track 2 migration

- .github/CODEOWNERS
Reverts Azure/azure-cli#17313
---
> {CI} Update CODEOWNERS

- .azure-pipelines/templates/azdev_setup.yml
- build_scripts/windows/scripts/build.cmd
- scripts/ci/test_extensions.sh
Merge fix #17432 back to `dev`.
> {Branch Management} Merge release 2.21.0 back to dev

- src/azure-cli/azure/cli/command_modules/network/tests/latest/private_endpoint_arm_templates/search_resource_template.json
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_search.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
Add microsoft.search scenario test for private endpoint connections
azdev test NetworkPrivateLinkSearchScenarioTest --live --discover
---
- [ x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).
- [ x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).
> {Search} Add microsoft.search scenario test for private endpoint connections

- .azure-pipelines/templates/azdev_setup.yml
> {pipeline} Update azdev_setup.yml

- src/azure-cli/azure/cli/command_modules/backup/_help.py
- src/azure-cli/azure/cli/command_modules/backup/_params.py
- src/azure-cli/azure/cli/command_modules/backup/custom_base.py
- src/azure-cli/azure/cli/command_modules/backup/custom_wl.py
Adding optional parameter 'backup-management-type' in 'backup protectable-item list' command
az backup protectable-item list -v "vaultName" -g "rgName" --workload-type MSSQL --container-name "containerName" -o table --protectable-item-type "SQLDatabase" --backup-management-type "AzureWorkload"
---
> [backup] Optional parameter 'backup-management-type' in 'backup protectable-item list' command

- src/azure-cli-core/setup.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
Bump knack to 0.8.0: https://github.com/microsoft/knack/releases/tag/v0.8.0
> {Packaging} Bump knack to 0.8.0

- src/azure-cli/azure/cli/command_modules/acs/_consts.py
- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_fqdn_subdomain.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
This pr copies feature `--private-dns-zone` and `--fqdn-subdomain` from aks extension because we're going to GA these two features.
[AKS] az aks create: add support for --private-dns-zone and --fqdn-subdomain feature
---
> [AKS] az aks create: add support for --private-dns-zone and --fqdn-subdomain feature

- src/azure-cli-testsdk/azure/cli/testsdk/preparers.py
> {Test} Bugfix: rg not found if AZURE_CLI_TEST_DEV_RESOURCE_GROUP_NAME is set

- doc/track_2_migration_roadmap.md
> {Doc} Update track 2 migration roadmap

- doc/track_2_migration_roadmap.md
Update Track2 status in doc.
---
> {Misc.} Update Track2 status

- src/azure-cli/azure/cli/command_modules/backup/custom.py
Fixed policy create with rgNamePrefix and rgNameSuffix.  https://portal.microsofticm.com/imp/v3/incidents/details/233746722/home
az backup policy create --name "TestingPolicy" --resource-group "MABRG02" --vault-name "vault410" --backup-management-type "AzureIaasVM" --policy "testpolicy.json" 
---
> [Backup] fixed policy create with rgNamePrefix and rgNameSuffix

- src/azure-cli/azure/cli/command_modules/acs/_help.py
Fixes the spelling associated with help text for AKS.
```cmd
% az aks -h
```
---
- [✅] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).
- [✅] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).
- [✅] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).
> [AKS] Fix spelling of 'accessible'

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
-Command work with web apps running on Linux.
---
> [AppService]Fixes#16203: az webapp log tail supports webapps running on Linix.

- src/azure-cli-core/setup.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
Fix #17444 by adopting https://github.com/AzureAD/azure-activedirectory-library-for-python/pull/251.
> {Packaging} Bump ADAL to 1.2.7

- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_cosmosdb.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_link_resource_cosmosdb.yaml
> {CI} Fix full test

- .github/CODEOWNERS
Add codeowners for for auth and style.
> {Misc.} Add codeowners for auth and style

- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_extension.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
resolve #17466
update #17711 
---
> [Compute] `az vmss extension upgrade`  test case

- doc/track_2_migration_roadmap.md
> {Docs} Update track 2 migration roadmap

- src/azure-cli/azure/cli/command_modules/storage/_help.py
We will introduce a braking change in next version and here is to announce the incoming breaking change. 
---
> {Storage} Announce incoming breaking change

- src/azure-cli/azure/cli/command_modules/storage/_help.py
Fix https://github.com/Azure/azure-cli/issues/16743
---
> {Storage} Add help example

- src/azure-cli/azure/cli/command_modules/vm/_params.py
Update edge zone help message to be consistent with storage and network commands.
https://docs.microsoft.com/en-us/azure/networking/edge-zones-overview
---
> {Compute} Edge zone

- Dockerfile
Resolve #16748
The docker image built with this change can be downlaoded [here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=858372&view=artifacts&pathAsName=false&type=publishedArtifacts).
---
> [Packaging] Bump python to `3.8.9` in docker image

- .github/CODEOWNERS
Update code owners for command modules: acr and acs (aks).
---
> {Misc.} Update code owners for acr, acs

- src/azure-cli/setup.py
> {rdbms} Fix package version

- src/azure-cli/azure/cli/command_modules/eventhubs/_help.py
Fix typo of namespace
None, just fixed typo
> {EventHubs} az eventhubs eventhub list: Fix typo in help docs

- src/azure-cli/azure/cli/command_modules/servicebus/_help.py
> {ServiceBus} az servicebus: fix typos in help docs

- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_virtual_network.py
> {RDBMS} Fix tests failure by private dns track 2 migration

- scripts/ci/build.sh
AKS tests used a yaml file as test data file in #18051 and it needs to be added in the `azure-cli-fulltest` wheel so that it can be used in package tests.
The same code has been tested in https://dev.azure.com/azure-sdk/public/_build/results?buildId=895412&view=results
---
> {Test} Package data/*.yaml for aks tests

- src/azure-cli/azure/cli/command_modules/kusto/_help.py
> [Kusto] updated command group long summary

- src/azure-cli/azure/cli/command_modules/appservice/appservice_domains.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_slot_appsetting_update.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_slot_swap.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py
Fixes #18074, #18033, #18075
---
> [App Service]: Fixing issues with APIs signature that changed with Track2 update

- src/azure-cli/azure/cli/command_modules/resource/custom.py
> [ARM] `az deployment`: Fix error message for ARM deployment

- .github/CODEOWNERS
> {codeowner} Add rdbms owner

- .github/CODEOWNERS
> {Keyvault} code owners

- src/azure-cli/azure/cli/command_modules/resource/_formatters.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_subscription_level_what_if.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
The What-If formatter doesn't work in Azure CLI 2.24.0. There seems to be behavior changes in deserialization which breaks the What-If formatter. The PR fixes it.
`az deployment what-if ...`
---
> [ARM] Hotfix: Fix deserialization issue in ARM template What-If formatter

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_update_webapp_settings_thru_json.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
#18265 , #18266
When executing the webapp config appsettings set command the result Application Settings in the WebApp Configuration value is set to false for each setting defined in the settings array.
JSON Settings Example
[
{
"slotSetting": false,
"name": "ExampleParameter1",
"value": "@Microsoft.KeyVault(SecretUri=https://xxxxx.vault.azure.net/secrets/ExampleParameter1)"
},
{
"slotSetting": false,
"name": " ExampleParameter2",
"value": "@Microsoft.KeyVault(SecretUri=https://xxxxx.vault.azure.net/secrets/ExampleParameter2)"
}
]
Command Example
az webapp config appsettings set --name $WebAppName --resource-group $ResourceGroup --settings @$settings.json
[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing …
> [AppService] Hotfix: Fix # 18266 - webapp config appsettings set command causing all values to default to "false" in version 2.24.0

- src/azure-cli/azure/cli/command_modules/resource/_win_vt.py
- src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2018_03_01/recordings/test_vmss_create_none_options.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/recordings/test_vmss_create_none_options.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/recordings/test_vmss_rolling_upgrade.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/recordings/test_vmss_create_none_options.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/recordings/test_vmss_rolling_upgrade.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_with_policy_setting.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_update_policy.yaml
1. Issue: https://github.com/Azure/azure-cli/issues/18229
The api-version `2020-06-01` of VMSS service in the `2019-03-01-hybrid` profile does not support these parameters (`enableCrossZoneUpgrade`, `prioritizeUnhealthyInstances`...) currently.
At present, there is a logic that causes these unsupported parameters to be passed as `None` to the service even if they have no value.
https://github.com/Azure/azure-cli/blob/716b10f107c2e410967d7e09e21a0225c78e3cc8/src/azure-cli/azure/cli/command_modules/vm/_template_builder.py#L932-L939
So I add compatibility logic to ensure that these unsupported parameters will not be passed to service in this profile.
2. A new issue (`The value of parameter type is invalid`) was found while executing related test `test_vmss_rolling_upgrade` in …
> [VM] Hotfix: Fix the bad request issue when creating VMSS in Azure Stack

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
- src/azure-cli/azure/cli/command_modules/vm/_validators.py
- src/azure-cli/azure/cli/command_modules/vm/_vm_utils.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/linter_exclusions.yml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_by_attach_os_and_data_disks.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_count.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_existing_options.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_multi_nics.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_actions.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
> [Compute] `az vm create`: Support delete option for NICs and Disks for VMs in Azure CLI

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/custom_preparers.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Fix several aks live test cases.
* Fix “test_aks_create_default_service_with_virtual_node_addon” by adding missing spaces in the parameters
* Fix "test_aks_create_scale_with_custom_nodepool_name" by removing outdated check
* Fix "test_aks_create_scale_with_custom_nodepool_name_msi" by removing outdated check
---
> {AKS} Fix failed live test cases

- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_synapse_workspace.yaml
CI was blocked because synapse bump version missing network tests
---
> {Network} Fix network tests due to synapse bump

- src/azure-cli/azure/cli/command_modules/container/custom.py
Fix CI
https://dev.azure.com/azure-sdk/public/_build/results?buildId=934165&view=logs&j=36dd4138-4d53-5e46-00d9-e5cd9744be05&t=1cf3879c-0a42-5ccd-7693-7a4781d739d8
---
> {container} Fix style in CI

- src/azure-cli/azure/cli/command_modules/storage/_params.py
> [Storage] BREAKING CAHNGE: `az storage account create`: Remove `StorageFileDataSmbShareOwner` option for --default-share-permission

- src/azure-cli/azure/cli/command_modules/eventgrid/custom.py
Update the warning message displayed.
> {EventGrid}: Update warning message

- src/azure-cli/azure/cli/command_modules/synapse/_params.py
- src/azure-cli/azure/cli/command_modules/synapse/tests/latest/recordings/test_spark_job.yaml
- src/azure-cli/azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py
spark configuration '.' is converted to'_', which cause the failure
---
> [Synapse]spark configuration conversion, which cause the failure

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Fix test case "test_aks_create_fqdn_subdomain" by replacing fixed location.
---
> {AKS} Fix test case "test_aks_create_fqdn_subdomain"

- src/azure-cli/azure/cli/command_modules/resource/custom.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_tag_update_by_patch.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
> [ARM] az resource tag: Fix the problem of tagging resources with resource type `Microsoft.Network/publicIPAddresses`

- src/azure-cli/service_name.json
> {Misc} Update service mapping for az term

- .github/CODEOWNERS
- replace @msyyc by @kairu-ms and @jsntcy
---
> {CODEOWNERS} Update CODEOWNERS

- src/azure-cli/service_name.json
> {Reference TOC} fixed Azure service names

- src/azure-cli/azure/cli/command_modules/security/commands.py
this PR is to remove preview from the security module
---
> [security] Remove preview from security module

- src/azure-cli/azure/cli/command_modules/apim/_help.py
- src/azure-cli/azure/cli/command_modules/apim/_params.py
- src/azure-cli/azure/cli/command_modules/apim/custom.py
- src/azure-cli/azure/cli/command_modules/apim/tests/latest/test_apim_scenario.py
Version and version set support is added to apim api import command as requested in issue#15205
---
> [APIM] Added version parameter for apim api import

- src/azure-cli/azure/cli/command_modules/keyvault/commands.py
GA `private-link-resource`, `private-endpoint-connection` and `role` command group since MHSM has been GAed.
Email thread: RE: AKV SDK/PSH/CLI sync
---
> {Keyvault} Remove preview tag for `private-link-resource`, `private-endpoint-connection` and `role`

- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_metric_alert_for_sql_database_scope.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_sql_server.yaml
> {Sql} Fix tests in network and monitor module after sql bump version

- src/azure-cli/azure/cli/command_modules/billing/_exception_handler.py
- src/azure-cli/azure/cli/command_modules/billing/generated/custom.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
- `create_or_update` -> `begin_create_or_update`.
- `ErrorResponseException` -> `ErrorResponse`.
- Some parameters are put in the `parameters` dict for use.
---
> [Billing] Migrate billing to track2 SDK

- src/azure-cli/azure/cli/command_modules/storage/_help.py
- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/operations/account.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_file_delete_retention_policy.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_file_secured_smb.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_file_smb_multichannel.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
The feature is supported in storage-preview extension first. Here is to GA.
---
> [Storage] GA support secured SMB

- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/operations/account.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_with_nfs.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
Support nsf v3
`az storage account create` with `--enable-nfs-v3`
---
> [Storage] `az storage account create`: Support `--enable-nfs-v3` to set NFS 3.0 protocol

- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_cosmosdb.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_link_resource_cosmosdb.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_provider_registration_rpaas_no_accept_terms.yaml
CI failure as you can see in https://dev.azure.com/azure-sdk/public/_build/results?buildId=971614&view=logs&j=74095127-2a27-5370-37ed-15a4193f243f&t=5cf5f89a-09fb-583c-72e4-4e4427c89fb1
---
> {CI} Fix test

- src/azure-cli/azure/cli/command_modules/cdn/_help.py
> {CDN} add missing help

- src/azure-cli/azure/cli/command_modules/sql/_format.py
- src/azure-cli/azure/cli/command_modules/sql/_help.py
- src/azure-cli/azure/cli/command_modules/sql/_params.py
- src/azure-cli/azure/cli/command_modules/sql/_util.py
- src/azure-cli/azure/cli/command_modules/sql/commands.py
- src/azure-cli/azure/cli/command_modules/sql/custom.py
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_db_ledger.yaml
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_ledger.yaml
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
Adding Azure CLI commands for SQL Ledger (az sql db ledger-digest-uploads). 
Adding parameter to az sql db create for ledger database 
See issue here: https://github.com/Azure/azure-cli/issues/18339
enables ledger digest uploading to endpoint and database specified
az sql db ledger-digest-uploads enable --endpoint
[--ids]
[--name]
[--resource-group]
[--server]
[--subscription]
disables ledger digest uploading to database specified
az sql db ledger-digest-uploads disable 
[--ids]
[--name]
[--resource-group]
[--server]
[--subscription]
shows configured ledger digest upload for database specified 
az sql db ledger-digest-uploads show 
[--ids]
[--name]
[--resource-group]
[--server]
[--subscription]
creates a az sql db with ledger enabled
az sql db create -g …
> [SQL] `az sql db ledger-digest-uploads`:  Support SQL Ledger

- src/azure-cli/azure/cli/command_modules/sql/custom.py
This PR contains the fix for system assigned identities for UMI.
---
> [SQL] Fix for IdentityType for UMI

- src/azure-cli/azure/cli/command_modules/storage/_help.py
- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/_transformers.py
- src/azure-cli/azure/cli/command_modules/storage/commands.py
- src/azure-cli/azure/cli/command_modules/storage/operations/blob.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_container_list_scenarios.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_container_soft_delete_scenarios.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_blob_scenarios.py
Support container soft delete, which is supported in storage-blob-preview extension before
`az storage container list` with `--include-deleted`
`az storage container restore`
---
> [Storage] Support container soft delete 

- .github/CODEOWNERS
> {codeowner} adding fuming as the owner of acs module.

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_consumption_linux_powershell.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py
Resolves #18252 
This adds support for powershell on Linux consumption. It also changes the way we generate content share name to make it random. This should guarantee that there are no conflicts if a customer deletes and re-creates an app.
Added checks to existing test `test_functionapp_consumption_linux_powershell`.
---
> [App Service] Add support for Linux Consumption and improve how content share name is generated.

- src/azure-cli/azure/cli/command_modules/appservice/resources/LinuxFunctionsStacks.json
- src/azure-cli/azure/cli/command_modules/appservice/resources/WindowsFunctionsStacks.json
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_acr_create_function_app.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_acr_deployment_function_app.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_acr_integration_function_app.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_consumption_linux.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_on_linux.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_on_linux_functions_version.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_on_linux_version.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_slot_appsetting_update.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_slot_swap.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_windows_runtime.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_windows_runtime_functions_version.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_windows_runtime_version.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py
Node 8 and 10 are EOL and should be removed from list of possible node runtime versions.
Tests that relied on Node 8 or 10 have been updated
---
> [App Service] BREAKING CHANGE: `az functionapp create`: Remove support for EOL Node 8 and 10

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_hybridconnectionE2E.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_vnetE2E.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
> [App Service]: Fix an issue where adding VNET integration & Hybrid connections on a slot is not working

- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_metric_alert_for_sql_database_scope.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_sql_server.yaml
Fix SQL related record file to pass CI
---
> {SQL} Fix SQL related record file to pass CI

- src/azure-cli/azure/cli/command_modules/cdn/_help.py
- src/azure-cli/azure/cli/command_modules/cdn/_params.py
- src/azure-cli/azure/cli/command_modules/cdn/custom/custom.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_microsoft_sku_origingroup_override.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_origin_scenarios.py
az cdn endpoint rule: Add OriginGroupOverride action support
-  Create a rule to distribute requests with "/test1" in its URL path to origin group with name "origingroup1":
>         az cdn endpoint rule add -g group -n endpoint --profile-name profile --order 1
>         --rule-name "origin-groupo-verride" --match-variable UrlPath --operator Contains --match-values /test1
>         --action-name "OriginGroupOverride" --origin-group origingroup1
---
> [CDN] az cdn endpoint rule: Add OriginGroupOverride action support

- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_image_version_vhd.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
> [Compute] Fix issue #18633: az sig image-version create does not support mixing disks, snapshots, and vhd

- src/azure-cli/azure/cli/command_modules/resource/_bicep.py
- src/azure-cli/azure/cli/command_modules/resource/_help.py
- src/azure-cli/azure/cli/command_modules/resource/commands.py
- src/azure-cli/azure/cli/command_modules/resource/custom.py
Closes https://github.com/Azure/bicep/issues/2551.
Closes https://github.com/Azure/azure-cli/issues/18437.
[ARM] az bicep uninstall: Add new command to uninstall bicep
[ARM] az bicep build: Fix an issue where running with --stdout doesn't print any output
---
> [ARM] `az bicep uninstall`: Add new command to uninstall bicep

- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_encryption_at_host.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_update_with_workspace_windows.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
> [Compute] Upgrade package version to fix securityProfile issue in `az vmss update`

- src/azure-cli/azure/cli/command_modules/appconfig/_help.py
- src/azure-cli/azure/cli/command_modules/appconfig/_params.py
- src/azure-cli/azure/cli/command_modules/appconfig/custom.py
- src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/recordings/test_azconfig_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/test_appconfig_commands.py
> [AppConfiguration] Add tags support when creating resource

- src/azure-cli/azure/cli/command_modules/storage/_validators.py
- src/azure-cli/azure/cli/command_modules/storage/azcopy/util.py
Fix the issue caused by jwt and sas token. Tests pass now as below:
[Storage] Fix issue caused by jwt upgrade.
[Storage] az storage fs directory download: Fix the issue with --sas-token to generate valid sas url
---
> [Storage] Fix issues

- src/azure-cli/azure/cli/command_modules/storage/operations/fs_file.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_adls_file_scenarios.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_adls_gen2_scenarios.py
Fix #18352 
`az storage fs file list --file-system --account-name --show-next-marker --exclude-dir`
---
> [Storage] Fix #18352: `az storage fs file list --exclude-dir` breaks with `--show-next-marker`

- src/azure-cli/azure/cli/command_modules/storage/_help.py
- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/_validators.py
- src/azure-cli/azure/cli/command_modules/storage/commands.py
- src/azure-cli/azure/cli/command_modules/storage/operations/blob.py
- src/azure-cli/azure/cli/command_modules/storage/operations/filesystem.py
- src/azure-cli/azure/cli/command_modules/storage/operations/fs_directory.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_fs_generate_sas_as_user.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_fs_generate_sas_full_uri.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_adls_gen2_scenarios.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_sas_scenarios.py
- src/azure-cli/azure/cli/command_modules/storage/util.py
Add `az storage fs generate-sas` support for ADLS gen2 account
---
> [Storage] `az storage fs generate-sas`:  Support generate sas token for file system in ADLS Gen2 account

- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/operations/account.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/mgmt_policy.json
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_management_policy.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_update_last_access.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
GA support last access tracking policy, which is supported in `storage-blob-preview` before.
---
> [Storage] `az storage account blob-service-properties`: Support last access tracking policy

- src/azure-cli/azure/cli/command_modules/synapse/_help.py
- src/azure-cli/azure/cli/command_modules/synapse/operations/workspace.py
update a workspace key failure due to parameter 'is-active-cmk' lost
---
> [Synapse]Workspace key update failure

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_edge_zone.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Adding edge zone support in the `az aks create` command
- Add the extended location parameter to create AKS in the edge zones
- Add a test case for the cluster creation in edge zone
Added the unit test `test_aks_create_edge_zone` as well as manually tested by creating AKS at the edge zones on a test subscription
---
> [AKS] `az aks create`: Add edge zone support

- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/_template_builder.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_with_cert_name.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Closed https://github.com/Azure/azure-cli/issues/18375
---
> [network] `az network application-gateway create`: Added `--ssl-certificate-name` argument

- doc/track_2_migration_guidance.md
- doc/track_2_migration_roadmap.md
> {Docs} Update track2 migration roadmap

- src/azure-cli/azure/cli/command_modules/eventgrid/tests/latest/recordings/test_event_subscription_with_delivery_identity.yaml
> {Eventgrid} Fix eventgrid test api version

- src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_service_bus.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
> [Network] private link add Microsoft.ServiceBus/namespaces provider

- src/azure-cli/azure/cli/command_modules/network/_help.py
Closed https://github.com/Azure/azure-cli/issues/17536
Closed https://github.com/Azure/azure-cli/issues/16610
---
> [Network] `az network application-gateway waf-policy custom-rule match-condition add`: Add examples

- src/azure-cli/azure/cli/command_modules/monitor/operations/metric_alert.py
> {monitor} fix `az monitor alert create`

- src/azure-cli/azure/cli/command_modules/resource/_help.py
> [ARM] Add example for creating site extension to web app

- src/azure-cli/azure/cli/command_modules/network/commands.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_front_ip.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_load_balancer_ip_config.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic_front_ip.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic_subresources.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_event_grid_domain.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_event_grid_topic.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_link_resource_event_grid.yaml
Closed https://github.com/Azure/azure-cli/issues/18600
[Network] `az network lb frontend-ip update`: Support cross tenant for argument `--gateway-lb`.
[Network] `az network nic ip-config update`: Support cross tenant for argument `--gateway-lb`.
---
> {network} gateway loadbalance support cross tenant

- src/azure-cli/azure/cli/command_modules/acr/scope_map.py
- src/azure-cli/azure/cli/command_modules/acr/task.py
- src/azure-cli/azure/cli/command_modules/acr/token.py
Fixes #18903 #18949 #18881 
---
> {ACR} Migrate to Track 2

- src/azure-cli/azure/cli/command_modules/appservice/access_restrictions.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_access_restriction_commands.py
Fix #18947 issue
Adding test to repro and verify fix
Add IP address rules with service endpoint rules and remove service endpoint rule
az webapp config access-restriction add --ip-address
az webapp config access-restriction add --subnet
az webapp config access-restriction add --ip-address
az webapp config access-restriction remove --subnet
[App Service] az webapp config access-restriction remove: Fix #18947 issue removing service endpoint rules
---
> [App Service] `az webapp config access-restriction remove`: Fix the broken caused by AttributeError

- src/azure-cli/azure/cli/command_modules/acr/_help.py
- src/azure-cli/azure/cli/command_modules/acr/_params.py
- src/azure-cli/azure/cli/command_modules/acr/connected_registry.py
Add specifying parent protocol to 'acr connected-registry install' to fetch complete connection string.
Update the help instruction and argument description
Fix some typos.
az acr connected-registry install info -n -r --parent-protocol
az acr connected-registry install renew-credentials -n -r --parent-protocol
[ACR] BREAKING CHANGE: az acr connected-registry install info: Add a new required parameter --parent-protocol.
[ACR] BREAKING CHANGE: az acr connected-registry install renew-credentials: Add a new required parameter --parent-protocol.
---
> [ACR] `az acr connected-registry install info/renew-credentials`: Add new parameter `--parent-protocol` to specify parent protocol

- src/azure-cli/azure/cli/command_modules/acs/_help.py
Makes the possible options for `--node-osdisk-type` more clear for `az aks nodepool add --help`.
`az aks nodepool add --help`
Fixes #19050
---
> [AKS] Improve nodepool help text for OS Disk options

- azure-pipelines.yml
> {Branch Management} Merge `release` back to `dev`

- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/sql/custom.py
Fix CI linter failure (Details: [CI link](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1031697&view=logs&jobId=36dd4138-4d53-5e46-00d9-e5cd9744be05&j=36dd4138-4d53-5e46-00d9-e5cd9744be05&t=1cf3879c-0a42-5ccd-7693-7a4781d739d8)):
---
> {CI} Fix linter failures

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_consumption_e2e.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_consumption_ragrs_storage_e2e.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_move_plan_to_elastic.yaml
`az functionapp update -n {non-existent-appname}` was failing. Added check for non-existent app name.
Tried with non-existent app name. Gives proper error message now.
> {AppService} Fix #17947: az functionapp update fails with Attribute error: checking non-existent app name

- .github/CODEOWNERS
> [Synapse]code owner change

- src/azure-cli/azure/cli/command_modules/sql/custom.py
Due to [Enum Type change ](https://github.com/Azure/azure-cli/blob/dev/doc/track_2_migration_guidance.md#no-enum-type)in track2 Python SDK, we have to fix the corresponding enum name in the SQL commands
Due to this issue, we met `sql mi update` command throws unexpected CLI error info
Pass all the recorded tests
N/A
---
> [SQL] Fix the enum name change in track2 Python SDK

- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_general_operations.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_sig_image_version_cross_tenant.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Related PR: https://github.com/Azure/azure-cli/pull/19159
Use `@ResourceGroupPreparer(... ,subscription=cross_tenant_subscrption)` to ensure that the cross account resource group will be deleted after the test is completed.
---
> {Test} Fix resource group deletion for cross tenant tests

- src/azure-cli/azure/cli/command_modules/appconfig/_validators.py
> [App Config] `appconfig kv import/export`: Add endpoint validation during import and export

- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_front_ip.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
> {Network} fix `network lb frontend-ip update`: unable to delete the reference to gateway load balancer fronted ID

- src/azure-cli/azure/cli/command_modules/appservice/commands.py
#19175 
Remove preview flag for below commands.
az webapp config storage-account add
az webapp config storage-account list
az webapp config storage-account delete
---
> [App Service]: `az webapp config storage-account list/add/update/delete`: Remove preview flag

- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Update test related command output.
---
> {AKS} Update test related command output

- scripts/ci/credscan/CredScanSuppressions.json
- src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/recordings/test_application_related.yaml
- src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/recordings/test_cert_and_ext.yaml
- src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/recordings/test_create_cluster_with_separate_kv.yaml
- src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/test_sf_application.py
- src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/test_sf_cluster.py
- src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/test_sf_managed_cluster.py
When running live tests, it shows error "resource group is `None`", that's because we didn't pass `resource_group` as the parameter for test method.
---
> {servicefabric} Fix live tests regression

- src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/private_endpoint_arm_templates/powerbi_privatelinkservicesforpowerbi_parameters.json
- src/azure-cli/azure/cli/command_modules/network/tests/latest/private_endpoint_arm_templates/powerbi_privatelinkservicesforpowerbi_template.json
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_powerbi_ignoreReject.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
Register Microsoft.PowerBI/privateLinkServicesForPowerBI provider to support private link for PowerBI
Add test cases following this [guideline](https://github.com/Azure/azure-cli/blob/dev/doc/private_endpoint_connection_command_guideline.md)
Add 1 class PowerBINetworkARMTemplateBasedScenarioTest(ScenarioTest) with 2 functions:
1. test_private_endpoint_connection_powerbi: test all the 7 required test cases in guideline, marked as skipped because our test account has a "Subscription is not registered" error, which blocks "az network private-endpoint-connection reject". Since we don't have other usable test account and need to onboard this provider in CLI, I leave this test function skipped. Also we have verified that our service supports reject on backend. …
> [PowerBI] Add private link provider Microsoft.PowerBI/privateLinkServicesForPowerBI

- src/azure-cli/azure/cli/command_modules/network/_help.py
Closed https://github.com/Azure/azure-cli/issues/18304
--
---
> [Network] Fix NSG rule creation example mistake

- src/azure-cli/azure/cli/command_modules/synapse/_params.py
- src/azure-cli/azure/cli/command_modules/synapse/operations/spark.py
> [Synapse]Optimize submit spark job arguments

- src/azure-cli-testsdk/azure/cli/testsdk/constants.py
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_general_operations.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_sig_image_version_cross_tenant.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Since there are many constants that are reused in the current tests, such as `aux_tenant` and `aux_subscription`, so I add a file `constants.py` to store the definitions of common variables with reference to the design of `azure-cli-core` [constants.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/commands/constants.py)
---
> {Test} Add constants file for test SDK

- .github/CODEOWNERS
Update code owner for Compute and Resource
---
> {CODEOWNER} update code owner 

- src/azure-cli/azure/cli/command_modules/keyvault/_help.py
- src/azure-cli/azure/cli/command_modules/keyvault/_params.py
- src/azure-cli/azure/cli/command_modules/keyvault/commands.py
- src/azure-cli/azure/cli/command_modules/keyvault/custom.py
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_hsm_private_endpoint_connection.yaml
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
Feature requested by service team & Breadth coverage
`az keyvault private-endpoint-connection list --hsm-name ystestmhsm`
---
> [Keyvault] `az keyvault private-endpoint-connection list`: Support list mhsm's private endpoint connections

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_with_auto_upgrade_channel.yaml
Update the recording file of test case test_aks_create_with_auto_upgrade_channel to 07-01 api version, because the test case did not exist when the api version was updated before.
---
> {AKS} Update the recording file of test case test_aks_create_with_auto_upgrade_channel to 07-01 api version

- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_mysql.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_commands.py
- src/azure-cli/azure/cli/command_modules/rdbms/validators.py
- Fix maintenance window update issue with MySQL
Maintenance window parameter needs to be only parameter in updated properties. 
- Change restart parameter to be case insensitive
- Recommendation to use 'flexible-server connect' command after server provisioning
---
> [RDBMS] Fix maintenance window update issue with MySQL and Change restart parameter to be case insensitive

- src/azure-cli/azure/cli/command_modules/monitor/_help.py
> {monitor} `az monitor metrics alert condition create`: Add popular command for `--metric`

- src/azure-cli/azure/cli/command_modules/cosmosdb/custom.py
- src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_deleted_account_restore.yaml
- src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/test_cosmosdb_commands.py
There was a bug in the recent release where the command az cosmosdb restore is broken for deleted database accounts
Added the test to cover this deleted account scenario.
---
> {CosmosDB} Hotfix: `az cosmosdb restore`: Fix the restore command for deleted accounts

- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
Refactor part of the create sub-command in acs module.
---
> {AKS} Refactor part of the create sub-command in acs module

- src/azure-cli/azure/cli/command_modules/network/_help.py
Closed https://github.com/Azure/azure-cli/issues/19155
---
> {Network} Fix description of `az network application-gateway waf-policy managed-rule exclusion remove`

- src/azure-cli/azure/cli/command_modules/resource/_help.py
Devs should be aware thet az tag create wipes existing tags and informed by a potential solution.
---
> [ARM] `az tag create`: Add the note for handling existing tag in help

- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
Refactor a second part (agentpool profile) of the create sub-command in acs module.
---
> {AKS} Refactor a second part of the create sub-command in acs module

- doc/track_2_migration_roadmap.md
> {Docs} Update track2 migration status

- .github/CODEOWNERS
> {CodeOwner} Add code owner

- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
* fix typo (defautl -> default)
* replace variable name (mc_property -> value_obtained_from_mc)
* add getter functions and unit tests for enable_cluster_autoscaler, min_count, max_count
---
> {AKS} Refactor a third part of the create sub-command in acs module

- src/azure-cli/azure/cli/command_modules/rdbms/_helptext_mysql.py
- src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py
- src/azure-cli/azure/cli/command_modules/rdbms/_params.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_common.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_mysql.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_virtual_network.py
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_flexible_server_replica_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands.py
- src/azure-cli/azure/cli/command_modules/rdbms/validators.py
- MySQL restore enable change from/to private network <-> public network 
- MySQL replica create enable availability zone selection
- PostgreSQL update high availability server bug fix
[RDBMS] BREAKING CHANGE: az mysql flexible-server create/update --high-availability available parameter is changed from 'Enabled' to 'ZoneRedundant' and 'SameZone' .
[RDBMS] az mysql flexible-server restore command enables network option change from private network  to public network and vice versa.
[RDBMS] Added 'zone' parameter for az mysql flexible-server replica create command.
---
> [RDBMS] MySQL restore network parameter added, replica zone parameter added / PostgreSQL update HA server bug fix

- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
* Set up windows profile.
* Suppress 4 false Credential Scan alerts in unit tests.
---
> {AKS} Refactor a fifth part of the create sub-command in acs module

- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
* Set up service principal profile.
---
> {AKS} Refactor a sixth part of the create sub-command in acs module

- src/azure-cli/azure/cli/command_modules/network/_params.py
> {network} remove preview tag for `--key-vault-secret-id`

- src/azure-cli/azure/cli/command_modules/cdn/_help.py
- src/azure-cli/azure/cli/command_modules/cdn/_params.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_endpoint_compression.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/scenario_mixin.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_custom_domain_scenarios.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_endpoint_scenarios.py
Fix endpoint creation failure with --content-types-to-compress
-  Create a cdn endpoint with compression support for specific MIME types:
`az cdn endpoint create --name mytestendpoint --profile-name cdnbugbash --origin huaiyiztesthost1.blob.core.chinacloudapi.cn --enable-compression --origin-host-header huaiyiztesthost1.blob.core.chinacloudapi.cn --content-types-to-compress text/plain text/html text/css`
---
> [CDN] `az cdn endpoint create`: Fix endpoint creation failure with `--content-types-to-compress`

- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
Upgrade `azure-mgmt-keyvault` from `9.0.0` to `9.1.0` to adopt new Enum definition for `KeyPermissions` 
`az keyvault set-policy -n vault1569 --key-permissions get list release --object-id XXXX`
---
> [Keyvault] `az keyvault set-policy`: `--key-permissions` add new option `release`

- src/azure-cli/azure/cli/command_modules/network/_help.py
> {Network} Update `custom-ip prefix update` example

- src/azure-cli/azure/cli/command_modules/vm/_help.py
> [Compute] Update shared image gallery doc

- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
* process add_role_assignment_for_vnet_subnet
* update docstring
---
> {AKS} Refactor a seventh part of the create sub-command in acs module

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_slot.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Fix #19098
`az webapp deployment slot auto-swap --name --resource-group --slot --disable` gives error.
Fix parameter order  in `update_configuration_slot`.
---
> [App Service]: Fix #19098: `az webapp deployment slot auto-swap `: Fix the AttributeError error for parameters `--slot --disable` 

- src/azure-cli/azure/cli/command_modules/vm/_help.py
- src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
- src/azure-cli/azure/cli/command_modules/vm/_validators.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_create_vm_with_shared_gallery_image.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
> [Compute] `az vmss create`: Support creating VMSS from shared gallery image

- src/azure-cli/azure/cli/command_modules/synapse/_params.py
- src/azure-cli/azure/cli/command_modules/synapse/operations/sparkpool.py
> [Synapse]spark pool remove library requirement

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Fix several test cases.
Replace --generate-ssh-keys with the pre-provided --ssh-key-value.
* test_aks_create_with_ossku
* test_aks_create_with_auto_upgrade_channel
Add pre-provided --ssh-key-value.
* test_aks_nodepool_add_with_ossku
---
> {AKS} Fix several test cases

- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
* add process_attach_acr
* update docstring
---
> {AKS} Refactor a eighth part of the create sub-command in acs module

- src/azure-cli/azure/cli/command_modules/acs/_loadbalancer.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/hybrid_2020_09_01/test_loadbalancer.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/mocks.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_loadbalancer.py
* set up network profile
* update _loadbalancer.py and corresponding unit tests
---
> {AKS} Refactor a ninth part of the create sub-command in acs module

- src/azure-cli-core/azure/cli/core/commands/__init__.py
Related issue: #19365
There is a issue #19365 about the output of progress bar: when the progress bar uses `stderr` as the output stream, the script execution in the automation scenario may be interrupted, such as:
> For example, if az CLI is invoked from PowerShell script with $ErrorActionPreference set to "Stop", then even with stderr -> stdout redirection, PowerShell will stop execution of the script due to an "error" reported via progress controller.
However, this is by design that progress bar uses `stderr` for output, because users may parse the output data from `stdout`, and our design pattern is that only writes the output data to `stdout`.
So we can have two solutions for this problem:
1. Add a global config by `az config` to allow users to disable progress bar …
> [Core] Support disable progress bar

- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
> {AKS} Refactor a tenth part of the create sub-command in acs module

- src/azure-cli/azure/cli/command_modules/keyvault/_params.py
- src/azure-cli/azure/cli/command_modules/keyvault/_validators.py
- src/azure-cli/azure/cli/command_modules/keyvault/custom.py
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_network_rule.yaml
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
Fix #10254 
`--ip-address` previously only supports one value. 
Add capability to accept a list of ip addresses. 
Fix #18479 
`--ip-address` previously allow adding an overlapping ip-address without CIDR suffix.
For example, there is an existing ip-address rule of 1.2.3.4/32
`az keyvault network-rule add --ip-address 1.2.3.4` would still add another rule entry.
Fix #10254 
`az keyvault network-rule add --ip-address 1.2.3.4/32 1.2.3.5 -n {keyvault name}`
Fix #18479 
`az keyvault network-rule add --ip-address 1.2.3.4/32 -n {keyvault name}`
`az keyvault network-rule add --ip-address 1.2.3.4 -n {keyvault name}` should give a warning and not add another rule.
[Keyvault] Fix #10254 : `az keyvault network-rule add --ip-address`: Add capability …
> [Keyvault] BREAKING CHANGE: Fix #10254 & #18479: `az keyvault network-rule add`

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
"az webapp update" description change is related to feedback from this study: https://hits.microsoft.com/Insight/1251147 which asked for a more detailed description for this command.
"az webapp auth" description change is required to inform users that an extension must be added to use certain commands.
Error text update requests can be found here https://msazure.visualstudio.com/Antares/_sprints/taskboard/Antares%20CLI%20and%20PS/Antares/Antares%20CLI%20and%20PS/S194?workitem=10694591 and are related to this study: https://hits.microsoft.com/Insight/1251147 which asked for a more detailed description for this command.
Verify that the help text and error text has been updated and is formatted appropriately.
`az webapp up --help`
`az webapp auth --help` …
> {App Service} Change description and update error message for az webapp commands

- src/azure-cli/azure/cli/command_modules/storage/_params.py
Fix #19059 
Previously point to 
https://review.docs.microsoft.com/en-us/azure/storage/blobs/blob-inventory#inventory-policy.
Now points to
https://docs.microsoft.com/en-us/azure/storage/blobs/blob-inventory#inventory-policy.
---
> [Storage] Fix #19059: Fix doc link to point to public doc website

- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
* remove option "enable_validation"
---
> {AKS} Refactor a remove-options part of the create sub-command in acs module

- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
> {AKS} Refactor a eleventh part of the create sub-command in acs module

- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
* refactor api server access profile
Unit test result:
* "covered_lines": 949,
* "num_statements": 1008,
* "percent_covered": 94.14682539682539,
* "missing_lines": 59,
* "excluded_lines": 0
---
> {AKS} Refactor a twelfth part of the create sub-command in acs module

- scripts/release/generate_history_notes.py
- Print commit ID and subject in `generate_history_notes.py`
- Accept PR body to be `None`
> {CI} Update `generate_history_notes.py`: Print commit ID and subject

- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
* refactor identity & identity profile & auto upgrade profile
Unit test result:
- "covered_lines": 1045,
- "num_statements": 1116,
- "percent_covered": 93.63799283154121,
- "missing_lines": 71,
---
> {AKS} Refactor a thirteenth part of the create sub-command in acs module

- src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_abs_privatendpoint_with_default.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
We have implemented support for private endpoints feature on Microsoft.BotService RP. Since private endpoints protocol and api structure is dictated by the network team for all RP's, our implementation is the same as other RP's. Hence this PR just seeks to allow-list Microsoft.BotService RP to be invoked via the CLI for the standard network commands for private endpoints
Tested the impacted commands on a private subscription, after setting up the CLI dev instructions - 
az network private-endpoint-connection show --id
az network private-endpoint-connection reject
az network private-endpoint-connection list
[Component Name 2] az command b: Add …
> [network] add microsoft.botservice to supported private endpoints operations

- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
* **replace the implementation of `aks_create` with decorator**
* refactor auto_scaler_profile, sku, extended_location and custom headers
* finish `construct_default_mc_profile` and add `create_mc`
* clean up and add more test cases
* backward compatibility
Unit test result:
> "covered_lines": 1168,
> "num_statements": 1184,
> "percent_covered": 98.64864864864865,
> "missing_lines": 16,
Live test result:
* All passed.
---
> {AKS} Refactor a fourteenth part of the create sub-command in acs module

- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_logicapp_e2e.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_logicapp_on_linux.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_logicapp_windows.yaml
> {Appservice} Fix appservice tests after storage bump

- scripts/live_test/sendemail.py
> {live-test} Add receiver `antcliTest@microsoft.com` for live test

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Skip deprecated test case `test_aks_browse_legacy`, since we cannot create a cluster with version lower than 1.19.0 which meets the test requirements anymore.
---
> {AKS} Skip deprecated test case `test_aks_browse_legacy`

- src/azure-cli/azure/cli/command_modules/container/_client_factory.py
- src/azure-cli/azure/cli/command_modules/container/custom.py
- src/azure-cli/azure/cli/command_modules/container/tests/latest/recordings/test_container_attach.yaml
- src/azure-cli/azure/cli/command_modules/container/tests/latest/recordings/test_container_create.yaml
- src/azure-cli/azure/cli/command_modules/container/tests/latest/recordings/test_container_exec.yaml
- src/azure-cli/azure/cli/command_modules/container/tests/latest/test_container_commands.py
Issue: #19585
Migration to Track2 SDK introduced some additional issues, which broke the commands: `logs`, `exec`, `attach `and `delete`. This includes the fixes to address those problems. Additionally, added test cases to cover all of these commands so we can detect such issues prior to release.
Made test changes to cover below commands:
`az container logs`: Retrieves the logs for a container
`az container delete`: Deletes the container
`az container exec`: Executes a command on the container
`az container attach`: Attach local standard output and error streams to a container
---
> [Container] `az container logs`: Fix the attribute error introduced by Track 2 migration

- src/azure-cli/azure/cli/command_modules/acs/_consts.py
az aks check-acr does not work for China/USGov Cloud
Example usage: az aks check-acr -g myResourceGroup -n myAKSCluster --acr myacr.azurecr.io
---
> [AKS] az aks check-acr: Bump canipull to 0.0.3 alpha to support sovereign cloud

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Preserve default location for test cases involving availability zones
* test_aks_availability_zones
* test_aks_availability_zones_msi
* test_aks_enable_utlra_ssd
---
> {AKS} Update several test cases

- doc/modules_owned_by_cli_team.md
> {docs} List modules owned by CLI team

- src/azure-cli/azure/cli/command_modules/acs/_consts.py
- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
* refactor basic structure of `aks_update`.
* refactor auto scaler profile.
Unit Test Results:
- "covered_lines": 1248,
- "num_statements": 1268,
- "percent_covered": 98.42271293375394,
- "missing_lines": 20,
---
> {AKS} Refactor 1st part of the update sub-command in acs module

- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_loadbalancer.py
- change the following two class names
- `AKSCreateModels -> AKSModels`
- `AKSCreateContext -> AKSContext`
- change the optional parameter `decorator_mode` to a mandatory parameter in class `AKSContext`.
Unit Test Results:
- "covered_lines": 1248,
- "num_statements": 1268,
- "percent_covered": 98.42271293375394,
- "missing_lines": 20,
---
> {AKS} Refactor 2nd part of the update sub-command in acs module

- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_batsion_host_create.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Description
Add `--tags` argument to az network bastion create.
Testing Guide
`network bastion create -g {rg} -n {bastion} --vnet-name {vnet} --public-ip-address {ip} --tags a=b`
---
> [Network] `az network bastion create`: Add `--tags` argument

- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_mariadb_private_link_scenario.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_mysql_private_link_scenario.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_postgres_private_link_scenario.yaml
> {network} fix recording files

- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
* refactor attach & detach acr.
Unit Test Results:
- "covered_lines": 1279,
- "num_statements": 1300,
- "percent_covered": 98.38461538461539,
- "missing_lines": 21,
---
> {AKS} Refactor 3rd part of the update sub-command in acs module

- src/azure-cli/azure/cli/command_modules/acs/_consts.py
- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_with_openservicemesh_addon.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_disable_openservicemesh_addon.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_enable_openservicemesh_addon.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
This change implements the commands required to
enable and disable the open-service-mesh AKS addon
as a part of the core azure-cli framework. These
changes are a port of the existing implementation
in the azure-cli-extensions repo and is required
as a part of enabling the addon for GA on AKS.
Also formats the CLI help text for better readability.
---
> [AKS] `az aks enable-addons`: Support open-service-mesh addon

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_autoscaler_then_update.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
Add support for updating tags of the cluster in `aks update`.
---
> [AKS] `az aks create/update`: Add support for updating tags

- src/azure-cli/azure/cli/command_modules/container/_client_factory.py
- src/azure-cli/azure/cli/command_modules/container/_params.py
- src/azure-cli/azure/cli/command_modules/container/_validators.py
- src/azure-cli/azure/cli/command_modules/container/custom.py
- src/azure-cli/azure/cli/command_modules/container/tests/latest/recordings/test_container_attach.yaml
- src/azure-cli/azure/cli/command_modules/container/tests/latest/recordings/test_container_create.yaml
- src/azure-cli/azure/cli/command_modules/container/tests/latest/recordings/test_container_create_with_acr.yaml
- src/azure-cli/azure/cli/command_modules/container/tests/latest/recordings/test_container_create_with_msi.yaml
- src/azure-cli/azure/cli/command_modules/container/tests/latest/recordings/test_container_create_with_msi_scope.yaml
- src/azure-cli/azure/cli/command_modules/container/tests/latest/recordings/test_container_create_with_vnet.yaml
- src/azure-cli/azure/cli/command_modules/container/tests/latest/recordings/test_container_exec.yaml
- src/azure-cli/azure/cli/command_modules/container/tests/latest/recordings/test_container_export.yaml
- src/azure-cli/azure/cli/command_modules/container/tests/latest/recordings/test_container_git_repo_volume_mount.yaml
- src/azure-cli/azure/cli/command_modules/container/tests/latest/test_container_commands.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
Updating to API Version 07-01-2021, which includes:
- Removal of `network_profile`, now replaced with the `subnet_ids` property
- Add support for MSI authenticated ACR image pull with the new parameter `acr_identity`.
Updated tests with live run of new API version
[Container] BREAKING CHANGE: `az container create`: Removing `--network-profile` parameter, property no longer supported
[Container] `az container create`: Add parameter `--acr-identity`  for support of MSI authenticated ACR image pull
---
> [Container] BREAKING CHANGE: `az container create`: Removing parameter `--network-profile` and add new parameter `--acr-identity`

- src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_resourcemanagementprivatelink.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_link_resource_resourcemanagementprivatelink.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
Support private link for Microsoft.Authorization/resourceManagementPrivateLinks provider
> [Network]Private link support for provider Microsoft.Authorization/resourceManagementPrivateLinks

- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
> {Network} Rename args of custom ip status

- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_tag_update_by_patch.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
> {ARM} Fix api-version in yaml

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/_params.py
Issue: #19645 
Update parameter descriptions for `az webapp config storage-account` commands
---
> [App Service] `az webapp config storage-account`: Update parameter descriptions

- scripts/live_test/template.yml
> {CI} specify pool image to `Ubuntu-20.04` for `SendEmail` job of live test

- scripts/live_test/CLITest.yml
- scripts/live_test/generate_index.py
- scripts/live_test/sendemail.py
[Azure CLI Live Test](https://dev.azure.com/azure-sdk/internal/_build?definitionId=1896&_a=summary) keeps failing and whitout any log.
- Add log for send email task.
- Disable write_db function until fix it.
> {CI} Fix Azure CLI Live Test

- src/azure-cli/azure/cli/command_modules/vm/_validators.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_snapshot_copy_start_detection.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
> [Compute] Fix #20182: `az snapshot create`: Fix auto-detection bug for `--copy-start`

- src/azure-cli/azure/cli/command_modules/storage/_help.py
- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/_validators.py
- src/azure-cli/azure/cli/command_modules/storage/commands.py
- src/azure-cli/azure/cli/command_modules/storage/operations/file.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_file_share_handle_scenario.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_file_scenarios.py
Add file handle operations to file share(file and directory). Match powershell commands Get-AzStorageFileHandle and Close-AzStorageFileHandle.
To reproduce the prerequisite steps:
1. Create a file share under a storage account/ resource group
2. Upload file1 to the root dir of the file share, add a dir called dir1 and upload another file file2
3. Create a Python file to open both files and sleep so the file handles are held
4. Create two VMs and ssh to them
5. Mount the file share using the script in the connect tab and run the Python file
`az storage share list-handle --account-name {account1} --name {share-name} --recursive`
Should list all the file handles.
`az storage share close-handle --account-name {account1} --name {share-name} --path 'dir1/file2' …
> [Storage]: add `az storage share list-handle` and `az storage share close-handle`

- src/azure-cli/azure/cli/command_modules/appservice/resources/WindowsFunctionsStacks.json
change netFrameworkVersion from v5.0 to v4.0
---
> {Functions} Fix dotnet-isolated 5 settings

- src/azure-cli/azure/cli/command_modules/resource/custom.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_resource_group.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
Fix  issue https://github.com/Azure/azure-cli/issues/11342
closed https://github.com/Azure/azure-cli/issues/11342
---
> [ARM] `az resource\group list`:  Support querying data only by passing the tag name to `--tag` parameter

- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
* Refactor the update of windows profile
- "covered_lines": 1642,
- "num_statements": 1654,
- "percent_covered": 99.27448609431681,
- "missing_lines": 12,
---
> {AKS} Refactor 8th part of the update sub-command in acs module

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/appservice_environment.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_app_service_environment_commands_thru_mock.py
PR will add support for allowing new private endpoint connections on ASEv3 and support listing outbound addresses.
az appservice ase list-addresses -g -n
az appservice ase update -g -n --allow-new-private-endpoint-connections
[App Service] `az appservice ase update`: Support for allowing new private endpoint connections on ASEv3
[App Service] `az appservice ase list-addresses`: Support ASEv3
---
> [App Service] `az appservice ase update`: Support private endpoint and list addr for ASEv3

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_nodepool_update_label_msi.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_update_labels.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Add support to allow edit label after creation.
ex: 
az aks nodepool update --labels foo=bar
az aks update --nodepool-labels foo=bar
[AKS] `az aks update`: Support edit nodepool label after creation 
[AKS] `az aks nodepool update`: Support edit nodepool label after creation 
---
> [AKS] `az aks update` : Support edit nodepool label after creation 

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
Updates the help text for `az staticwebapp create` with additional guidance for using creating a static web app from a Github repo in a Github organization. 
N/A
---
> [App Service] `az staticwebapp create` : Update help text with guidance for repos in Github organizations

- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
- Update comments & docstring.
- Add internal function for `get_cluster_autoscaler_profile`.
> "covered_lines": 1646,
> "num_statements": 1659,
> "percent_covered": 99.21639541892706,
> "missing_lines": 13,
---
> {AKS} Clean up of the refactor the update sub-command in acs module

- src/azure-cli/azure/cli/command_modules/keyvault/_client_factory.py
- src/azure-cli/azure/cli/command_modules/keyvault/commands.py
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_hsm_key_encrypt_AES.yaml
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_key.yaml
In previous commit https://github.com/Azure/azure-cli/pull/20189/commits/c91418caedc42dba3d1a7b63561962e6327cda9f, I have separated client factories for `azure.keyvault.keys` stable api version `7.2` and preview api version `7.3-preview`. But PM thinks it's better to keep consistent for all `az keyvault key` commands using track2 SDK.
So this PR reverts previous changes and uses `7.3-preview` for all as PM has confirmed.
---
> {Keyvault} Use consistent api version for azure-keyvault-keys

- src/azure-cli/azure/cli/command_modules/network/_help.py
- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/commands.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_express_route_global_reach_config.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
closed https://github.com/Azure/azure-cli/issues/19852
[Network] Add new command set: `az network express-route peering connection ipv6-config set/remove`
---
> [Network] Support for IPv6 Global Reach CRUD operations

- src/azure-cli/azure/cli/command_modules/resource/_utils.py
- src/azure-cli/azure/cli/command_modules/resource/custom.py
Issue: #19213
Before
After
---
> [ARM] `az deployment`: Prettify error output for ARM deployment

- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_express_route_global_reach_config.yaml
> [Network] Fix recording

- src/azure-cli/azure/cli/command_modules/acs/_consts.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
Organize constants and enums.
---
> {AKS} Organize constants and enums

- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
* Refactor updating aad profile.
- "covered_lines": 1704,
- "num_statements": 1718,
- "percent_covered": 99.18509895227008,
- "missing_lines": 14,
---
> {AKS} Refactor 9th part of the update sub-command in acs module

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_hibernation_enabled.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Azure CLI support for VM Hibernate feature https://github.com/Azure/azure-cli/issues/19611
Waiting to register hibernate(done)
---
> [Compute] `az vm create/update`: Add new parameter `--enable-hibernation` to support enabling hibernation capability 

- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
Adopt the enum changes in https://github.com/Azure/azure-rest-api-specs/pull/16536
---
> {Keyvault} Bump `azure-mgmt-keyvault` 9.3.0

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_run_command_v2.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_run_command_v2.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Add Instance view to RunCommand https://github.com/Azure/azure-cli/issues/20155
---
> [Compute] `az vm/vmss run-command show`: Add new parameter `--instance-view` to support tracking the progress of RunCommand

- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
- Refactor updating auto upgrade channel.
- "covered_lines": 1712,
- "num_statements": 1727,
- "percent_covered": 99.13144180660105,
- "missing_lines": 15,
---
> {AKS} Refactor 10th part of the update sub-command in acs module

- src/azure-cli-core/azure/cli/core/profiles/_shared.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_access.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_bursting.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_encryption_set.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_encryption_set_disk_update.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_hibernation.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_trusted_launch.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_image_version_vhd.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_specialized.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_other_extended_location.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_specialized_image.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_by_attach_os_and_data_disks.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_data_disk_delete_option.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_from_unmanaged_disk.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_custom_image_name_conflict.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_create_with_standard_zrs_sku.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_create_zones.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_logical_sector_size.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_max_shares_etc.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_storage_sku.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_upload.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_managed_disk.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_os_disk_swap.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_snapshot_copy_start_detection.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_snapshot_incremental.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_ultra_ssd_disk_update.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_ultra_ssd_storage_sku.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_update_instance_disks.yaml
> {compute} Bump disk 2021-04-01

- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
- Refactor updating identity profile.
> "covered_lines": 1738,
> "num_statements": 1754,
> "percent_covered": 99.08779931584948,
> "missing_lines": 16,
---
> {AKS} Refactor 11th part of the update sub-command in acs module

- scripts/ci/test_extensions.sh
Issue that added the `azure-iot` extension to the ignore_list has long since been resolved https://github.com/Azure/azure-iot-cli-extension/issues/321.
---
> {CI} Remove `azure-iot` from ignore_list in test_extensions.sh

- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/logicapp/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_acr_integration.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_container_webapp_docker_image_name.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_container_webapp_long_server_url.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp_quick_create.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Fixes a bug with the `--deployment-container-image-name/-i` argument on `az webapp create` where if the user passes a url with multiple slashes, the registry server url is assumed to be the substring ending at the last slash. For example, if the user gave the image name as `mcr.microsoft.com/azure-app-service/windows/parkingpage:latest`, the server url would be erroneously parsed as `mcr.microsoft.com/azure-app-service/windows` instead of `mcr.microsoft.com`
Also, an `https://` is prefixed to the server url if the container name is a url and no scheme was detected
`azdev test --live azdev test test_container_webapp_long_server_url`
---
> [App Service] `az webapp create`: Fix container registry server url parsing for `--deployment-container-image-name/-i` argument

- linter_exclusions.yml
- src/azure-cli/azure/cli/command_modules/network/_help.py
- src/azure-cli/azure/cli/command_modules/network/commands.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_address_pool_addresses.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
closed: https://github.com/Azure/azure-cli/issues/19867
---
> {Network} `az network lb address-pool`: support new option `update`

- src/azure-cli/azure/cli/command_modules/vm/_help.py
Updating unmanaged disk section to simply call out max unmanaged disk size and remove the information about preview managed disks. 
---
> [Compute] Update the help description for unmanaged disks

- src/azure-cli/azure/cli/command_modules/acs/_resourcegroup.py
- src/azure-cli/azure/cli/command_modules/acs/_roleassignments.py
- Not long ago, in aks-preview @tilnl-ms helped sorted out the internal operations required by some addons ([PR #3911](https://github.com/Azure/azure-cli-extensions/pull/3911)), and we are gradually synchronizing this part.
- This would also fix a bug in the preparation process of monitoring addon.
- This first PR adds some basic functions, mainly around creating a role assignment.
---
> {AKS} Update addon preparation - part 1

- src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_acfr.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_link_resource_acfr.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
Updating the Redis api version to the latest in private endpoint configuration
Test private endpoint commands over redis resources
example: az network private-endpoint-connection list --id /subscriptions/{subscriptionID}/resourceGroups/{ResourceGroupName}/providers/Microsoft.Cache/Redis/{AzureCacheName}
> {Redis} Updating Redis api version in Private endpoint configuration

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_accelerated_network.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_completion_percent.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_public_network_access.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
[issue link](https://github.com/Azure/azure-cli/issues/19636)
- Customers can set, read and update PublicNetworkAccess, AcceleratedNetwork on Managed Disks and Snapshots.
- Customers can read CompletionPercent on Snapshots.
`az disk create --public-network-access Enabled --size-gb 5 -n {disk} -g {rg}`
`az disk update --public-network-access Disabled --size-gb 5 -n {disk} -g {rg}`
`az disk create --accelerated-network true --size-gb 5 -n {disk} -g {rg}`
`az disk create --accelerated-network false --size-gb 5 -n {disk} -g {rg}`
`az snapshot create --public-network-access Enabled --size-gb 5 -n {snapshot} -g {snapshot}`
`az snapshot update --public-network-access Disabled --size-gb 5 -n {snapshot} -g {snapshot}`
`az snapshot create --accelerated-network true …
> [Compute] `az disk snapshot`: Add `--public-network-access` parameter to control the policy for export on the disk

- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_with_encryption.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
[issue link](https://github.com/Azure/azure-cli/issues/20033)
Add `--enable-encryption` parameter to az network vnet create.
Add `--enable-encryption` parameter to az network vnet update.
Add `--encryption-enforcement-policy` parameter to az network vnet create.
Add `--encryption-enforcement-policy` parameter to az network vnet update.
`az network nic create/update/show/list` can display the **vnetEncryptionSupported** flag
`az network vnet peering create/update/list/show` can display the **remoteVirtualNetworkEncryption** info
`azdev test test_network_vnet_with_encryption --live`
[Network] `az network vnet create`: Add `--enable-encryption` argument to support enable encryption on virtual network
[Network] `az network vnet update`: Add …
> [Network] `az network vnet`: Add `--enable-encryption` parameter to support enable encryption on virtual network

- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_virtual_network.py
> [RDBMS] Fix private DNS zone suffix bug 

- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
closed https://github.com/Azure/azure-cli/issues/20395
---
> {Network} `az network application-gateway http-listener`: rename parameter `--ssl-profile` to `--ssl-profile-id`

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_with_auto_upgrade_channel.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_with_openservicemesh_addon.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_custom_headers.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_disable_local_accounts.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_disable_openservicemesh_addon.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_enable_openservicemesh_addon.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Update several test cases related to `aks update`.
---
> {AKS} Update several test cases related to `aks update`

- src/azure-cli/azure/cli/command_modules/acs/addonconfiguration.py
- Not long ago, in aks-preview @tilnl-ms helped sorted out the internal operations required by some addons ([PR #3911](https://github.com/Azure/azure-cli-extensions/pull/3911)), and we are gradually synchronizing this part.
- This would also fix a bug in the preparation process of monitoring addon.
- This second PR focuses on the file `addonconfiguration.py`, which provides helper functions to process some preparation work for the monitoring, ingress-app and virtual node addons.
This file is basically the same as the [addonconfiguration.py](https://github.com/Azure/azure-cli-extensions/blob/main/src/aks-preview/azext_aks_preview/addonconfiguration.py) file in aks-preview. We replace the error type `CLIError` with `AzCLIError`.
[Component …
> {AKS} Update addon preparation - part 2

- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_common.py
Fixing the invalid json file input handling.
Now malformed jsons are caught at cli layer itself, before sending request to cloud.
---
> {RDBMS}: Handling invalid json input for pg flex server migration.

- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_commands.py
> [RDBMS] remove preview tag

- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/mocks.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
- Refactor updating node labels.
> "covered_lines": 1824,
> "num_statements": 1828,
> "percent_covered": 99.78118161925602,
> "missing_lines": 4,
---
> {AKS} Refactor 13th part of the update sub-command in acs module

- src/azure-cli/azure/cli/command_modules/backup/custom.py
- src/azure-cli/azure/cli/command_modules/backup/custom_wl.py
- src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_archive.yaml
- src/azure-cli/azure/cli/command_modules/backup/tests/latest/test_backup_commands.py
- `az backup protectable-item list/show` AttributeError fixed for server_name (HANADBInstance)
- `az backup recoverypoint list` fixed when using `--recommended-for-archive`
---
> [Backup] `az backup protectable-item list/show`: Fix AttributeError for server_name

- src/azure-cli/azure/cli/command_modules/eventgrid/commands.py
> [EventGrid] GA `az eventgrid system-topic`

- src/azure-cli/azure/cli/command_modules/acs/custom.py
Update the implementation of `aks update` to adopt a new decorator pattern.
---
> {AKS} Update the implementation of `aks update` to adopt a new decorator pattern

- src/azure-cli/azure/cli/command_modules/netappfiles/custom.py
Fixes check on volume create to allow user to create volumes using export policy for NFSv3 volumes
[ICM=272525099 ](https://portal.microsofticm.com/imp/v3/incidents/details/272525099/home) 
---
> [NetAppFiles] `netappfiles volume create`: fix volume export policy

- src/azure-cli/azure/cli/command_modules/synapse/manual/operations/spark.py
Fix existing command: az synapse spark job submit -mainclass
---
> [Synapse] `az synapse spark job submit`: Fix for `--main-class-name`

- scripts/release/debian/deb_install.sh
This is the stable release for almost 3 months by now.
---
> {Packaging} Change default debian repo to bullseye

- scripts/release/homebrew/docker/formula_template.txt
Backport https://github.com/Homebrew/homebrew-core/pull/86758
> {Packaging} Use Python 3.10 in Homebrew formula template

- src/azure-cli/azure/cli/command_modules/vm/_params.py
Fixes typo, clarifies what the "gallery" is (Azure Compute instead of Shared Image).
No testing, just documentation text.
[Storage] az disk create: Fixes typo and clarifies where images originate
---
> {vm} Update the help information of parameter `gallery_image_reference`

- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_sku.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_public_ip_prefix.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
add tests for two network commands
below tests will be affected:
test_network_lb_sku
test_network_public_ip_prefix
---
> {network}add tests for two network commands

- src/azure-cli/azure/cli/command_modules/appservice/resources/LinuxFunctionsStacks.json
- src/azure-cli/azure/cli/command_modules/appservice/resources/WindowsFunctionsStacks.json
Node16 is in preview now - need to unhide azure-cli.
> {FunctionApp} Unhide Node16 Preview for function apps

- src/azure-cli/azure/cli/command_modules/vm/_params.py
> [Compute] `az vm/vmss create/update`: Expand validate license types for `--license-type` parameter 

- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_with_private_ip.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
add tests for five application-gateway commands , below test will be affected:
test_network_app_gateway_with_private_ip
---
> {network} Add tests for five application-gateway commands

- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_access.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_proximity_placement_group.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_by_attach_os_and_data_disks.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_extension.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_host_management.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_extension.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Add/Edit tests for untested vm commands, and record live test.
Commands included:
```
disk-access wait
disk wait
snapshot wait
vm extension wait
vmss wait
vm host group list
vm host group delete
vm host list
vm host update
ppg list
ppg update
ppg delete
```
---
> {Compute} Module tests: cover untested VM commands

- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_url_path_map.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_waf_config.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_waf_policy_with_application_gateway.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Add tests for six application-gateway commands
below tests will be affected:
test_network_ag_url_path_map
test_network_app_gateway_waf_config
test_network_app_gateway_waf_policy_with_application_gateway
---
> {network} Add tests for six application-gateway commands

- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_auth_cert.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_root_cert.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_redirect_config.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
add tests for six commands, below tests will be affected:
test_network_ag_auth_cert
test_network_ag_root_cert
test_network_app_gateway_redirect_config
---
> {network}add tests for six commands

- src/azure-cli/azure/cli/command_modules/synapse/manual/_help.py
Update help.py to show best practice use file input for JSON. Including cmdlets: 
- az synapse linked-service create/update/set
- az synapse dataset create/update/set
- az synapse pipeline create/update/set
- az synapse trigger create/update/set
- az synapse data-flow create/set
- az synapse spark-job-definition create/update
---
> {Synapse} Update help doc to show best practice use file input for JSON

- src/azure-cli/azure/cli/command_modules/profile/__init__.py
This is for consistency with other commands. Should have been done in 2018
Argument change with low impact and low chance of regression, hence manual testing is sufficient
done
---
> [Profile] `az account show/set`: Add `-n`, `--name` argument

- src/azure-cli/azure/cli/command_modules/synapse/manual/_help.py
- src/azure-cli/azure/cli/command_modules/synapse/manual/_params.py
- src/azure-cli/azure/cli/command_modules/synapse/manual/operations/managedprivateendpoints.py
- src/azure-cli/azure/cli/command_modules/synapse/tests/latest/assets/managedprivateendpoints.json
- src/azure-cli/azure/cli/command_modules/synapse/tests/latest/recordings/test_managed_private_endpoints.yaml
- src/azure-cli/azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py
Modify 'az synapse managed private endpoints' cmdlets:
- remove parameter ' --private-Link-Resource-Id'.
- remove parameter ' --group-Id'.
- add parameter ' --definition-file'.
---
> [Synapse] BREAKING CHANGE: `az synapse managed private endpoints create`: Remove `--resource-id` and `--group-id`, use `--file` instead

- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_route_table_operation.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_traffic_manager.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_nat_rule.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vpn_connection_ipsec.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Add tests for five network commands, below tests will be affected:
test_network_route_table_operation
test_network_traffic_manager
test_network_vnet_gateway_nat_rule
test_network_vpn_connection_ipsec
---
> {network} Add tests for five network commands

- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_manage_appgw_private_endpoint.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_manage_appgw_private_endpoint_without_standard.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
Fix bug https://github.com/Azure/azure-cli/issues/20708
---
> {Network} Fix `az network application-gateway private-link add` failed to create resources

- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/mocks.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
- Remove the unnecessary parameter `**kwargs` from all the internal getters.
- Refactor the validation for `private_dns_zone`, `enable_private_cluster` and `api_server_authorized_ip_ranges`.
- Convert the validation function in `AKSContext` to inernal function.
- Fix several typos.
> "covered_lines": 1852,
> "num_statements": 1854,
> "percent_covered": 99.89212513484358,
> "missing_lines": 2,
---
> {AKS} Refine decorator pattern

- src/azure-cli/azure/cli/command_modules/vm/_params.py
Feature request: #20667
The request from https://github.com/Azure/azure-cli/issues/20667#issuecomment-994627630
---
> {Compute} Modify license type

- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_ssh_key.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_extension.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_extension_image.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Add command test coverage and record live test.
Included commands:
```
vmss extension image list
vmss extension image list-names
vmss extension image list-versions
vmss extension image show
vmss extension list
sshkey update
sshkey delete
```
---
> {Compute} module command test

- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_nat_rules_v3.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
add a new parameter backend-pool-name #19688
---
> [Network] `az network lb inbound-nat-pool create`: Add new parameter `--backend-pool-name`

- src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py
Typo "Azure CosmosDB"→"Azure Cosmos DB"
https://docs.microsoft.com/en-us/cli/azure/cosmosdb/locations?view=azure-cli-latest#az_cosmosdb_locations_show
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py
#PingMSFTDocs
---
> {CosmosDB} Typo "Azure CosmosDB"→"Azure Cosmos DB"

- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
- Update error handling when creating cluster.
- Catch both `CloudError` and `HttpResponseError`, which would be raised since we have adopted track 2 SDK.
- Add unit test.
- "covered_lines": 1855,
- "num_statements": 1855,
- "percent_covered": 100.0,
- "missing_lines": 0,
---
> {AKS} Update error handling when creating cluster

- scripts/ci/credscan/CredScanSuppressions.json
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_acfr.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_link_resource_acfr.yaml
> {Network} Fix test_private_endpoint_connection_acfr, test_private_link_resource_acfr

- src/azure-cli/azure/cli/command_modules/vm/_params.py
Added two license_type values RHEL_BASESAPAPPS and RHEL_BASESAPHA
Added two license_type values RHEL_BASESAPAPPS and RHEL_BASESAPHA
The request from #20667 (comment)
Testing Guide
History Notes
---
> {Compute} Add two license_type values

- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_certificate_soft_delete.yaml
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_hsm_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
Add command test coverage and record live test.
Included commands:
```
keyvault certificate list-deleted
keyvault certificate show-deleted
keyvault update-hsm
```
---
> {Keyvault} module command test

- src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_link_endpoint_datafactory.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
Support private endpoint related command for Azure Data Factory
Closed [#20282](https://github.com/Azure/azure-cli/issues/20282)
Support private endpoint related command for Azure Data Factory#20282
---
> [Network]add microsoft.datafactory to supported private endpoints

- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_create_log_profile.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_diagnostic_settings_scenario.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_diagnostic_settings.py
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_log_profile.py
Add tests for four monitor commands , below tests will be affected:
test_monitor_diagnostic_settings_scenario
test_monitor_create_log_profile
---
> {Monitor}Add tests for four monitor commands

- src/azure-cli/azure/cli/command_modules/appservice/resources/LinuxFunctionsStacks.json
Fixes https://github.com/Azure/azure-cli/issues/20631
`az functionapp create -h`
---
> [App Service] `az functionapp create` : Remove preview from PowerShell runtime for linux 

- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_management_group_deployment.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_resource_group_deployment.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
Add command test coverage and record live test.
Included commands:
```
deployment operation mg show
deployment operation group show
```
---
> {Recource} command test coverage

- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_softdelete.yaml
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
Add test for keyvault key get-policy-template, below test will be affected:
test_keyvault_softdelete
---
> {keyvault}Add test for keyvault key get-policy-template

- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_auth_cert.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_root_cert.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_rule.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_with_private_ip.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Add tests for four network commands, below tests will be affected:
test_network_ag_auth_cert
test_network_ag_root_cert
test_network_ag_rule
test_network_app_gateway_with_private_ip
---
> {network}Add tests for four network commands

- src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_instance_failover_group_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_instance_pool.yaml
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_managed_db_long_term_retention.yaml
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_managed_db_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_managed_db_short_retention.yaml
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_managed_deleted_db_restore.yaml
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_managed_instance_create_identity_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_managed_instance_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_mi_failover_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_mi_operation_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_mi_tdebyok.yaml
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_server_trust_groups.yaml
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_virtual_cluster_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
Recorded tests for the managed instance cross-subnet update SLO. As part of the process, a new subscription is used for hosting resources. Because of that, all tests that used the previous subscription were recorded again:
- test_sql_managed_instance_mgmt
- SqlManagedInstanceOperationMgmtScenarioTest::test_sql_mi_operation_mgmt 
- SqlServerTrustGroupsScenarioTest::test_sql_server_trust_groups 
- SqlManagedInstanceMgmtScenarioIdentityTest::test_sql_managed_instance_create_identity_mgmt 
- SqlManagedInstanceDbShortTermRetentionScenarioTest::test_sql_managed_db_short_retention 
- SqlManagedInstanceRestoreDeletedDbScenarioTest::test_sql_managed_deleted_db_restore 
- SqlManagedInstanceDbMgmtScenarioTest::test_sql_managed_db_mgmt 
- …
> {SQL} az sql mi update: Record tests for managed instance cross-subnet SLO

- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/hybrid_2020_09_01/test_acs_commands.py
- src/azure-cli/azure/cli/command_modules/acs/tests/hybrid_2020_09_01/test_aks_commands.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_acs_commands.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Close file descriptors created by temp files after use.
---
> {AKS} Close file descriptors created by temp files after use

- src/azure-cli/azure/cli/command_modules/keyvault/custom.py
We now have more key permissions added day by day.
This PR adds all key/secret/certificate/storage permissions by default on keyvault creation peer PM's ask.
PS. Per my test, `xxxPermissions.all` doesn't contain `xxxPermissions.purge`.
---
> [Keyvault] `az keyvault create`: Add default permissions on keyvault creation

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_size_properties.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Support for VMSizecustomization for VM https://github.com/Azure/azure-cli/issues/20655
Wait for the service to add `Microsoft.Compute/VMCustomizationPreview` to sub for testing. (done)
---
> [Compute] `az vm create/update`: Add new parameters `--v-cpus-available`  and `--v-cpus-per-core` to support  VMSize customization

- scripts/ci/credscan/CredScanSuppressions.json
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_vpn_client_package.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Add tests for vnet-gateway revoked-cert create and delete, below test will be affected:
test_vpn_client_package
---
> {network} Add tests for vnet-gateway revoked-cert create and delete

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
Add support for `--aks-custom-headers` for `aks nodepool add/update/upgrade` commands.
---
> [AKS] Add support for `--aks-custom-headers` for `aks nodepool add/update/upgrade` commands

- src/azure-cli/azure/cli/command_modules/netappfiles/_help.py
- src/azure-cli/azure/cli/command_modules/netappfiles/commands.py
- src/azure-cli/azure/cli/command_modules/netappfiles/custom.py
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_active_directory.yaml
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/test_account_commands.py
Command added to update active directory on NetApp account
[NetAppFiles] az netappfiles account ad update: Command added
---
> [NetAppFiles] Add: az netappfiles account ad update

- scripts/ci/credscan/CredScanSuppressions.json
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_encryption_set_update.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_image_builder_basic.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_snapshot_access.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_convert.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_with_unmanaged_data_disks.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_custom_image_management.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_redeploy.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_image_builder_commands.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Add command test coverage and record live test.
Included commands:
```
vm reapply
vm redeploy
vm unmanaged-disk list
vm convert
image list
image delete
image update
snapshot grant-access
snapshot revoke-access
```
---
> {Compute} command test coverage

- .github/CODEOWNERS
The module container should be owned by container service team. However, since the previous code owner `samkreter` had left the team, and container service team did not reply who is the follow-up owner. In order to review and merge PR, the owner was temporarily replaced by me.
PR link: https://github.com/Azure/azure-cli/pull/14540/files
This PR is to replace the owner to a member from container service team
---
> {Code Owner} Modify code owner for container

- src/azure-cli/azure/cli/command_modules/network/_help.py
- src/azure-cli/azure/cli/command_modules/network/commands.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_peering_sync.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Closed https://github.com/Azure/azure-cli/issues/16654
---
> {Network} `az network vnet peering`: Support new command `sync`

- src/azure-cli/azure/cli/command_modules/rdbms/_params.py
Change the version default value from 12 to13
---
> [RDBMS] change default postgres version

- src/azure-cli/azure/cli/command_modules/serviceconnector/_help.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/custom.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_webapp_appconfig_e2e.yaml
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_webapp_eventhub_e2e.yaml
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_webapp_servicebus_e2e.yaml
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/test_webpp_connection_scenario.py
The PR adds new target resources supports by providing the commands
- az webapp connection create servicebus
- az webapp connection create eventhub
- az webapp connection create appconfig
- az spring-cloud connection create servicebus
- az spring-cloud connection create eventhub
- az spring-cloud connection create appconfig
---
> [ServiceConnector] Support new target resources: servicebus, eventhub, appconfig

- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_defer_only_commands.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_image_template_outputs.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_image_builder_commands.py
At present, three tests operate on the same resource `template01` under the same resource group `img_tmpl_customizers`.
```Python
@ResourceGroupPreparer(name_prefix='img_tmpl_customizers')
def test_image_builder_customizers(self, resource_group, resource_group_location):
......
self.kwargs.update({
'tmpl': 'template01',
```
```Python
@ResourceGroupPreparer(name_prefix='img_tmpl_customizers', location='westus2')
def test_image_template_outputs(self, resource_group, resource_group_location):
......
self.kwargs.update({
'tmpl_01': 'template01',
```
```Python
@ResourceGroupPreparer(name_prefix='img_tmpl_customizers', location='westus2')
def test_defer_only_commands(self, resource_group, resource_group_location):
......
self.kwargs.update({
'tmpl': 'template01',
```
When …
> {Compute} Fix test package issue for image build 

- src/azure-cli/azure/cli/command_modules/appservice/resources/WebappRuntimeStacks.json
> [App Service] `az webapp list-runtimes`: Support node 16-lts runtime for linux and windows 

- src/azure-cli/azure/cli/command_modules/container/_help.py
Removing Windows limitation
---
> {Container} Update help description for `container exec`

- src/azure-cli/azure/cli/command_modules/cosmosdb/_format.py
- src/azure-cli/azure/cli/command_modules/cosmosdb/commands.py
- src/azure-cli/azure/cli/command_modules/cosmosdb/custom.py
Add table format support to an existing api (az managed-cassandra cluster status),
and a minor bugfix inside custom.py
az managed-cassandra cluster create -g $rg -l $location -c $cluster -s $subnet --authentication-method None --debug
az managed-cassandra cluster status -g $rg -l $location -c $cluster --output table --debug
---
> [CosmosDb] az managed-cassandra cluster status: Add table format support to /status api

- src/azure-cli-testsdk/azure/cli/testsdk/patches.py
- src/azure-cli/azure/cli/command_modules/cloud/tests/__init__.py
- src/azure-cli/azure/cli/command_modules/cloud/tests/latest/__init__.py
- src/azure-cli/azure/cli/command_modules/cloud/tests/latest/recordings/test_cloud_scenario.yaml
- src/azure-cli/azure/cli/command_modules/cloud/tests/latest/test_cloud.py
Add tests to `cloud` command module to achieve 100% command test coverage.
> {Cloud} Add tests to `cloud` command module

- .github/pull_request_template.md
- azure-pipelines.yml
- scripts/ci/check_pull_request.py
With this feature, we can automatically verify pull request titel and history notes.
[Component Name 1] BREAKING CHANGE:az command a: Make some customer-facing breaking change.
[Component Name 2] az command b:added some customer-facing feature.
---
> {CI} Verify PR title, history notes to make it more standard to reduce manual effort during release.

- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/_validators.py
> {network} Fix capture limit, size and time validation issue in `az network watcher packet-capture create`.

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
> {appservice} Minor spelling correction to warning message in custom.py

- scripts/ci/check_pull_request.py
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1353660&view=logs&j=a8943ac2-38d7-5792-f2a7-5f4fd06db24e&t=3ed51913-4dd7-564f-a8d8-fda07de13946
---
> {CI} Fix index out of range error and add some comments

- src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_size_properties.yaml
fix issue https://github.com/Azure/azure-cli/issues/21224
---
> [Compute] `az vm create`: Fix the issue that VMCustomization is not enabled

- src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_size_properties.yaml
[Compute] `az vm create`: Fix the issue that VMCustomization is not enabled
---
> {Compute} Hotfix: `az vm create`: Fix the issue that VMCustomization is not enabled

- scripts/ci/check_pull_request.py
> {CI} Bug fixes and add update to verb check

- src/azure-cli/azure/cli/command_modules/identity/_help.py
- src/azure-cli/azure/cli/command_modules/identity/tests/latest/recordings/test_identity_management.yaml
- src/azure-cli/azure/cli/command_modules/identity/tests/latest/test_identity.py
Edit command short-summary
Add test for following commands
```
identity delete
identity list
identity list-operations
```
---
> {Identity} command test coverage

- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_metric_alert_v2_scenario.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_link_resource_webapp.yaml
Related PR: #21057
Blocked CI: [build id](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1365447&view=logs&jobId=15e5eb7c-cf66-5b91-00a2-db9b11b5e0f9&j=15e5eb7c-cf66-5b91-00a2-db9b11b5e0f9&t=845fa2ee-a602-59f5-4e4c-07ee6d0283b9)
---
> {Test} Re-record yaml file for api-version upgrade of `Microsoft.Web/webAppStacks`

- src/azure-cli/service_name.json
> {TOC} Fix Azure service names

- src/azure-cli/azure/cli/command_modules/acr/_params.py
Fixed the description of --cmd parameter. https://docs.microsoft.com/en-us/azure/container-registry/container-registry-quickstart-task-cli.
---
> {ACR} `az acr`: Fix the description of `--cmd-value` parameter

- src/azure-cli/azure/cli/command_modules/backup/custom_help.py
- src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
Add Microsoft.RecoveryServices to supported private endpoints
---
> [Backup] Add private endpoints support for Microsoft.RecoveryServices/vaults

- src/azure-cli/azure/cli/command_modules/serviceconnector/_help.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/_utils.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/_validators.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/action.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/custom.py
This PR adds the following features/improvements for service connector
- Auto register target subscription if not yet registered
- Mark object-id as optional when using service principal as auth type
- Validate appconfig to avoid secret auth type when local auth is disabled
---
> {ServiceConnector} Some user experience improvements 

- src/azure-cli/azure/cli/command_modules/keyvault/_params.py
When importing key from BYOK files, only asymmetric keys(`RSA` and `EC` algorithm) were accepted. This PR adds a new key type `oct` to support symmetric keys(`AES` algorithm)
---
> [Keyvault] `az keyvault key import`: Support `--kty oct` to import AES key

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_trusted_launch.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_trusted_launch_update.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_trusted.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Trusted Launch https://github.com/Azure/azure-cli/issues/21180
block issue https://github.com/Azure/azure-cli/issues/21180#issuecomment-1044077357
---
> [Compute] `az vmss create/update`: Add new parameters `--security-type`, `--enable-secure-boot` and `--enable-vtpm` to support Trusted Launch

- src/azure-cli/azure/cli/command_modules/network/_actions.py
- src/azure-cli/azure/cli/command_modules/network/_help.py
- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_private_endpoint_asg.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_private_endpoint_ip_config.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_private_endpoints.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
RE: CLI Support For Static IP Configurations + Nic Name + ASG:
> Just wanted to follow up for the CLI work. I noticed that on the “Create Private Endpoint” command, there isn’t the ability to also associate an ASG or configure an IP Config. There seems to be a separate command for this.
It might be an oversight on my end, but it should be possible for customers to provide IPs and associate ASGs when they create the PE as well. It is also only possible to add IP Configurations on update when the connected PaaS service is requesting more IP Configs.
--- …
> [Network] `az network private-endpoint`: Associate IP configurations and ASGs when creating PE

- scripts/live_test/CLITest.yml
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1375265&view=logs&j=0daf54e0-6bc4-593d-8412-5e3a5b776b01&t=b7633f07-2eff-5eea-5865-f1236a910292&l=329
The user azureclitest is created by Feiyue Yu, its password has expired.
Reset the password needs to be confirmed by feiyue himself, so we recreate a user azureclilivetest to replace it.
Test screenshot
---
> {CI} Fix live test password is expired error. 

- src/azure-cli/azure/cli/command_modules/acs/_help.py
{AKS} az aks nodepool list fix for #19681
---
Fixes #19681
> {AKS} az aks nodepool list fix for #19681

- src/azure-cli/azure/cli/command_modules/acs/_params.py
Addition to --context description. This fixes #19779
---
fixes #19779
> {ACS} Addition to --context description fixes #19779

- src/azure-cli/azure/cli/command_modules/vm/_help.py
> {Compute} `az vmss run-command invoke`: Fix help message

- README.md
Add contact email which is not easy to find. It is only documented at https://github.com/Azure/azure-cli/blob/dev/doc/onboarding_guide.md
> {Misc.} Add contact email to home page

- src/azure-cli/azure/cli/command_modules/eventhubs/_params.py
Fixed typo for --cluster-arm-id fixes #20416
---
fixes #20416
> {EventHub}Fixed typo for --cluster-arm-id

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_with_windows_gmsa.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_update_with_windows_gmsa.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
`az aks create/update`: Add new parameters `--enable-gmsa`, `--gmsa-dns-server`, `--gmsa-root-domain-name` to support Windows gMSA v2.
---
> [AKS] `az aks create/update`: Add new parameters `--enable-gmsa`, `--gmsa-dns-server`, `--gmsa-root-domain-name` to support Windows gMSA v2

- src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_agentpool_decorator.py
Refactor `aks nodepool create` - part 1.
- Basic structure.
---
> {AKS} Refactor `aks nodepool add` - part 1

- src/azure-cli/azure/cli/command_modules/acs/custom.py
> {AKS} Grant permission to system msi right after the cluster is put

- src/azure-cli/azure/cli/command_modules/vm/_params.py
At present, some enumeration model loading failures will be reported in the debug log:
Therefore, this PR is used to fix the enumeration model loading issues:
For `DiskStorageAccountTypes`, run `az vm create -h`
Before
After
For `EncryptionType`, run `az disk create -h`
Before
After
For `HyperVGeneration`, because `HyperVGenerationTypes` exists, so it has not been used
> HyperVGenerationTypes = HyperVGenerationTypes or HyperVGeneration
---
> {Compute} Fix the bug of loading some models of enumeration in help description

- .github/pull_request_template.md
Already add rule to check the last character.
But forget to change the pull request template.
---
> {CI} Fix pull request template

- src/azure-cli/azure/cli/command_modules/appconfig/_kv_helpers.py
Fix https://github.com/Azure/AppConfiguration/issues/596
---
> [App Config] `az appconfig kv export`: Stop throwing error if no key-values are exported to App Service

- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_agentpool_decorator.py
Refactor aks nodepool add - part 3.
- Add cluster auto scaler settings.
- Add os disk settings.
> "covered_lines": 154,
> "num_statements": 160,
> "percent_covered": 96.25,
> "percent_covered_display": "96",
> "missing_lines": 6,
---
> {AKS} Refactor aks nodepool add - part 3

- src/azure-cli/azure/cli/command_modules/keyvault/_params.py
- src/azure-cli/azure/cli/command_modules/keyvault/_validators.py
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_hsm_key_release_policy.yaml
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/release_policy.json
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
Close #21467 
Also add test for key release policy
---
> [Keyvault] `az keyvault key create`: Support `--default-cvm-policy`

- src/azure-cli/azure/cli/command_modules/eventgrid/custom.py
The fix here is to address a customer reported issue https://github.com/Azure/azure-cli/issues/21521  when trying to update an event subscription with system managed idenity
The issue was due to using wrong vatiable
---
> [Event Grid] Fix #21521: System topic subscription update attribute error

- src/azure-cli/azure/cli/command_modules/keyvault/custom.py
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_network_rule.yaml
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
> [Keyvault] Fix#21330: `az keyvault network-rule remove`: Fix ip address remove issue

- src/azure-cli/azure/cli/command_modules/acs/_consts.py
- src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_agentpool_decorator.py
- Refactor snapshot related properties.
> "covered_lines": 268,
> "num_statements": 274,
> "percent_covered": 97.81021897810218,
> "percent_covered_display": "98",
> "missing_lines": 6,
---
> {AKS} Refactor aks nodepool add - part 6

- src/azure-cli/azure/cli/command_modules/natgateway/custom.py
- src/azure-cli/azure/cli/command_modules/natgateway/tests/latest/recordings/test_natgateway.yaml
- src/azure-cli/azure/cli/command_modules/natgateway/tests/latest/recordings/test_natgateway_empty_create.yaml
- src/azure-cli/azure/cli/command_modules/natgateway/tests/latest/test_natgateway_commands.py
Service Team would like to withdraw this feature:
- https://github.com/Azure/azure-cli/pull/21483
This reverts commit 625f0306bcf016853c67747733d1808c24972c2c.
---
> {Revert} `az network nat gateway`: Validate attaching public IPs

- src/azure-cli/azure/cli/command_modules/servicebus/custom.py
- src/azure-cli/azure/cli/command_modules/servicebus/tests/latest/recordings/test_sb_rules.yaml
- src/azure-cli/azure/cli/command_modules/servicebus/tests/latest/test_servicebus_rules_commands.py
This PR is added to address https://github.com/Azure/azure-cli/issues/14581
servicebus topic subscription rule create --resource-group myrg --namespace-name mynamespace --topic-name {topicname} --subscription-name {subscriptionname} --name {rulename} --filter-type CorrelationFilter --correlation-id r00012d --label myvalue --message-id mid --reply-to reply --session-id ids --reply-to-session-id hi --content-type hi --to hi
[ServiceBus] `az servicebus topic subscription rule create`: Add filter type parameter
---
> [ServiceBus] `az servicebus topic subscription rule create`: Add Filter Type parameter

- .github/CODEOWNERS
> {Code Owner} Add coder owner for linter_exclusions.yaml

- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_agentpool_decorator.py
- Refactor label, tag, taint properties.
> "covered_lines": 298,
> "num_statements": 304,
> "percent_covered": 98.02631578947368,
> "percent_covered_display": "98",
> "missing_lines": 6,
---
> {AKS} Refactor aks nodepool add - part 7

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/commands.py
Sort out parameter declaration.
---
> {AKS} Sort out parameter declaration

- src/azure-cli/azure/cli/command_modules/acs/base_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
- Trying to fix the breaking change (to aks-preview) introduced in PR [#21661](https://github.com/Azure/azure-cli/pull/21661).
- Restore the function signature of `_put_managed_cluster_ensuring_permission`.
---
> {AKS} Restore the function signature of `_put_managed_cluster_ensuring_permission`

- src/azure-cli/azure/cli/command_modules/serviceconnector/_params.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/custom.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_webapp_storageblob_keyvault_ref.yaml
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_webapp_storageblob_vnet.yaml
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/test_webpp_connection_scenario.py
> [Service Connector] `az webapp/spring-cloud connection create/update`: Provide `--service-endpoint` parameter to support vnet scenario

- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_metric_alert_for_sql_database_scope.yaml
https://github.com/Azure/azure-cli/pull/21681 has bumped SQL API version, but rerunning sql test in monitor module failed with:
```
(RegionDoesNotAllowProvisioning) Location 'West US' is not accepting creation of new Windows Azure SQL Database servers at this time.
```
So manually changing the API version in yaml
---
> {Monitor} Fix test for sql bump

- src/azure-cli/azure/cli/command_modules/cosmosdb/_params.py
`--repair-enabled` parameter passed to `managed-cassandra cluster create or update` should be a 'three state flag'.
below commands passes {"repairEnabled": true} in payload
az managed-cassandra cluster update -c cluster-name -g group-name --repair-enabled $true --debug
az managed-cassandra cluster update -c cluster-name -g group-name --repair-enabled "true" --debug
below commands passes {"repairEnabled": false} in payload
az managed-cassandra cluster update -c cluster-name -g group-name --repair-enabled $false --debug
az managed-cassandra cluster update -c cluster-name -g group-name --repair-enabled "false" --debug
az managed-cassandra cluster update -c cluster-name -g group-name --repair-enabled "asdf" --debug
below command passes the previously set …
> [CosmosDB] `az managed-cassandra cluster`: Fix `--repair-enabled` as of type three_state_flag

- src/azure-cli-core/azure/cli/core/extension/operations.py
Fix #21535
Rework https://github.com/Azure/azure-cli/pull/21294: Skip CLI behavior trying to install dependencies with 'sudo' commands in the Cloud Shell
---
> [RDBMS] Fix operations.py file installing dependencies in CloudShell

- src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_apim.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
This PR added support for managing private endpoint in API Management and added test for validation
---
> [APIM] Onboard to private endpoint for API Management

- src/azure-cli/azure/cli/command_modules/acs/_help.py
Fixes GitHub Issue - [21695](https://github.com/Azure/azure-cli/issues/21695)
---
> {ACS} Fix for wrong autoscaler range

- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_batch_account.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_media_service.yaml
For `Microsoft.Batch`: https://github.com/Azure/azure-cli/pull/21705#issuecomment-1082842757
For `Microsoft.Media`: https://github.com/Azure/azure-cli/pull/21795#issuecomment-1082850219
---
> {CI} Fix api-version in yaml

- src/azure-cli/azure/cli/command_modules/cdn/_params.py
- src/azure-cli/azure/cli/command_modules/cdn/custom/custom_afdx.py
- src/azure-cli/azure/cli/command_modules/cdn/linter_exclusions.yml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_afd_origin_crud.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_afd_route_crud.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_afd_origin_scenarios.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_afd_route_scenarios.py
Add enforce_certificate_name_check support for origin
az afd origin create
az afd origin update
---
> {CDN} Add enforce_certificate_name_check support for origin

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_acr_create_function_app.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_acr_integration.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_acr_integration_function_app.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_container_webapp_docker_image_name.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_container_webapp_long_server_url.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_reserved_instance.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_vnetE2E.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_vnet_duplicate_name.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_slot_container_settings_override.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp_multicontainer_slot.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp_quick_create.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_update_webapp_settings_thru_json.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_config.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_slot.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_update_site_configs_persists_ip_restrictions.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_vnetDelegation.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_vnetE2E.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_vnetRouteAll.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_vnetSameName.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_vnetSubnetId.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands_thru_mock.py
issue #19519 
WEBSITES_ENABLE_APP_SERVICE_STORAGE=true will be overwrite to false automatically with below cmdlet
az webapp config set --linux-fx-version
or
az webapp config container set
---
> [App Service] `az webapp config`: Fix for Web App Persistent Storage gets disabled after each deployment

- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_waf_policy_exclusion_rule_set.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
"Rule-group is a collection of rules. Customer don’t need to already have a rule level exclusion for customer to create rule-group level. It is like creating an exclusion that apply to all rules in the rule group. So exclusion is not required and should work the same way as PS cmd."
---
> [Network] `az network application-gateway waf-policy managed-rule exclusion rule-set`: Support pre-rule exclusion creation without exclusion

- src/azure-cli/azure/cli/command_modules/monitor/_help.py
- src/azure-cli/azure/cli/command_modules/monitor/_params.py
Fix doc issues of monitor diagnostic-settings
---
> {monitor}Fix doc issues of monitor diagnostic-settings

- doc/extensions/authoring.md
The link fixed has an extra character at the end which leads to a 404 response from GitHub
---
> {Doc} Incorrect link - Minor fix in extension doc

- azure-pipelines.yml
Change `TestRpmPackage`'s artifact source to `yum`.
See https://github.com/Azure/azure-cli/pull/21887
> {Packaging} Change `TestRpmPackage`'s artifact source to `yum`

- .github/CODEOWNERS
Add @necusjz as some modules' owner
---
> {Code Owner} Add @necusjz as some modules' owner

- src/azure-cli/azure/cli/command_modules/network/_help.py
Hi ,
In Mac and Linux-based OS, BInd to privileged ports (so-called Well-Known Ports: 0-1023) requires root privileges when executed by a not root user, as shown below, and therefore, if you do not execute the command by sudo, a Permission denied error will occur.
I would suggest changing the example to one that uses DYNAMIC AND/OR PRIVATE PORTS (49152~65535).
```
Command group 'network bastion' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
[Errno 13] Permission denied
File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
File …
```
> {Network} `az network bastion tunnel`: Update examples in help message

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Fix test case `test_aks_create_with_node_config`. Use custom header to bypass feature registration validation in aks-rp.
---
> {AKS} Fix test case `test_aks_create_with_node_config`

- src/azure-cli/azure/cli/command_modules/storage/_help.py
- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/_transformers.py
- src/azure-cli/azure/cli/command_modules/storage/commands.py
- src/azure-cli/azure/cli/command_modules/storage/operations/queue.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_message_general_scenario.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_queue_metadata_scenario.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_queue_oauth.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_queue_oauth_track2.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_queue_policy_scenario.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_oauth_track2.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_queue_scenarios.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_sas_scenarios.py
> {Storage} Migrate azure-storage-queue to track2 sdk

- src/azure-cli/azure/cli/command_modules/acr/_params.py
Fixes https://github.com/Azure/azure-cli/issues/21817
---
> {acr} Adding missing remote tarball for the context

- src/azure-cli/azure/cli/command_modules/cdn/custom/custom_afdx.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_afd_route_crud.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_afd_rule_actions.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_afd_rule_complex_condition_creation.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_afd_rule_creation_invalid_match_values.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_afd_rule_creation_invalid_operator.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_afd_rule_crud.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_rule_set_crud.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_afd_route_scenarios.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_afd_rule_scenarios.py
Fixes: https://github.com/Azure/azure-cli/issues/21938
Fixes: https://github.com/Azure/azure-cli/issues/21844
`az afd rule create`: Fix rule creation failure with action type RouteConfigurationOverride
`az afd rule create`: Fix route creation issue with disabled --link-to-default-domain option
*Test rule creation with action type "RouteConfigurationOverride"*
az afd rule create --action-name RouteConfigurationOverride --order 1 --profile-name p-bugbash101 --resource-group bogroup --rule-name rule2204071 --rule-set-name rs0407
*Test route creation with --link-to-default-domain set to Disabled*
az afd route create -g "bogroup" --custom-domains "domain1" --endpoint-name "bugbash101" --profile-name "p-bugbash101" --route-name "test-route" --https-redirect …
> {CDN} Fix rule creation failure with action type RouteConfigurationOverride and route creation issue with disabled --link-to-default-domain option

- src/azure-cli/azure/cli/command_modules/acs/_consts.py
- src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/base_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_agentpool_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_base_decorator.py
- Refactor priority related properties.
- Refactor node network properties.
- Refactor vm properties.
- Refactor model loading mechanism and provide a function to serialize model in `BaseAKSModels`, preparing for split aks commands in a step-by-step build-by-profile manner.
---
> {AKS} Refactor aks nodepool add - part 8

- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_sas_scenarios.py
Add `--encryption-scope`
`az storage account generate-sas --resource-types co --services b --expiry {} --permissions r --https-only --connection-string {} --encryption-scope {}`
`az storage container generate-sas -n {} --https-only --permissions dlrw --expiry {} --encryption-scope {}`
`az storage blob generate-sas -c {} -n {} --https-only --permissions acdrw --expiry {} --encryption-scope {}`
[Storage] `az storage account/container/blob generate-sas`: Add `--encryption-scope`
---
> [Storage] `az storage account/container/blob generate-sas`: Add `--encryption-scope`

- src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_pls.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
Resolves: https://github.com/Azure/azure-cli/issues/19908
> The required type privateLinkServices is part of the cmd allowed values.
I was able to make it work with PowerShell:
Get-AzPrivateEndpointConnection -Name a845698e-xxxxxx -ResourceGroupName xxxxx-aro-rg -ServiceName xxxx-pls
Approve-AzPrivateEndpointConnection -Name a845698e-xxxxxxxxx -ResourceGroupName xxxxxx -ServiceName xxx-pls
---
> [Network] Private link add `Microsoft.Network/privateLinkServices` provider

- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
Fixes: https://github.com/Azure/azure-cli/issues/21811
> A new version of Python SDK with "etag" fix can be found here: https://pypi.org/project/azure-mgmt-loganalytics/13.0.0b4/
It also fixed the CI breaks mentioned in:
- https://github.com/Azure/azure-cli/pull/21988
---
> {Monitor} Bump `azure-mgmt-loganalytics` from 13.0.0b2 to 13.0.0b4

- .github/CODEOWNERS
Add @jiaxuwu2021 @luhan2017 as botservice modules' owner
---
> {CODEOWNERS} Add CODEOWNERS for botservice

- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_restore_file_returns_not_found.yaml
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/test_snapshot_commands.py
Fix for #21954 
Test marked as serial-test to prevent teardown being run in parallel to other tests.
Test inverted since we are not able to mount the volume to create the restore file through CLI (Check for error instead of happy path)
Added return to the custom command in question to make sure the operation finishes before the teardown takes place in the test.
---
> {NetAppFiles} Fix#21954 fix flaky test

- src/azure-cli-core/azure/cli/core/profiles/_shared.py
- src/azure-cli/azure/cli/command_modules/storage/_help.py
- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/commands.py
- src/azure-cli/azure/cli/command_modules/storage/operations/filesystem.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_adls_fs_soft_delete.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_adls_gen2_scenarios.py
This was preview in storage-preview extension https://github.com/Azure/azure-cli-extensions/pull/2877
Now has GAed requested by #21757 
---
> [Storage] GA storage file datalake soft delete

- src/azure-cli/azure/cli/command_modules/acs/_help.py
Signed-off-by: MartinForReal <fanshangxiang@gmail.com>
[acs] `az aks update`: Updated help doc of outbound ip options to eliminate ambiguity
---
> {AKS}`az aks update` update help doc for outbound ip count in aks subcommand

- src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_agentpool_decorator.py
- Refactor upgrade settings
- Refactor mode, scale_down_mode
> - "covered_lines": 578,
> - "num_statements": 578,
> - "percent_covered": 100.0,
> - "percent_covered_display": "100",
> - "missing_lines": 0,
> - "excluded_lines": 0
---
> {AKS} Refactor aks nodepool update - part 2

- src/azure-cli/azure/cli/command_modules/acr/_params.py
Fixes https://github.com/Azure/azure-cli/issues/22020
---
> {acr} Updating reference docs

- src/azure-cli/azure/cli/command_modules/vm/_params.py
> {Compute} Refile help message for `--data-disk-delete-option`

- src/azure-cli/azure/cli/command_modules/storage/tests/latest/blob_inventory_fns.json
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/blob_inventory_hns.json
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_blob_inventory_policy.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_blob_inventory_policy_hns.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
Add missing fields, add excludePrefix in filter
https://msazure.visualstudio.com/One/_workitems/edit/12421012
https://msazure.visualstudio.com/One/_workitems/edit/12421024
---
> [Storage] `az storage account blob-inventory-policy create`: Add missing fields, add excludePrefix in filter

- src/azure-cli/azure/cli/command_modules/acs/_consts.py
skip location check if cname returns only privatelink
---
> [AKS] `az aks check-acr`: Bump canipull to 0.0.4-alpha to skip location check if cname returns only privatelink

- src/azure-cli/azure/cli/command_modules/servicebus/_params.py
- src/azure-cli/azure/cli/command_modules/servicebus/custom.py
- src/azure-cli/azure/cli/command_modules/servicebus/tests/latest/recordings/test_sb_namespace.yaml
- src/azure-cli/azure/cli/command_modules/servicebus/tests/latest/test_servicebus_namespace_commands.py
This PR adds the zone_redundant parameter to az servicebus namespace create
az servicebus namespace create --name {namespacename} -g {resourcegroup}  --zone-redundant
[ServiceBus] `az servicebus namespace create`: Add zone redundant parameter
---
> [Service Bus] `az servicebus namespace create`: Add zone redundant parameter

- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
No API changes, no CLI code changes. Just pick up latest SDK to adopt the [bug fix](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/keyvault/azure-keyvault-keys/CHANGELOG.md#bugs-fixed-1):
> Fixed error that could occur when fetching a key rotation policy that has no defined `lifetime_actions`.
---
> {Keyvault} Upgrade `azure-keyvault-keys` to adopt the fix for no `lifetime_actions`

- src/azure-cli/azure/cli/command_modules/vm/_params.py
Fix: https://github.com/Azure/azure-cli/issues/22069
Improve help message of arguments:
```
--host
--host-group
```
---
> {Compute} `az vm create` & `az vm update`: improve argument help message

- src/azure-cli/azure/cli/command_modules/resource/_help.py
See issue https://github.com/Azure/azure-cli/issues/21906
Improve help message of arguments:
```
--template-file
--template-uri
--template-spec
```
---
> {ARM} `az deployment`: Improve help message for passing in the template data

- doc/storage_data_plane_commands_auth.md
Doc enhancement for customer better understanding and providing auth info for storage data plane commands
---
> {Storage} Doc for storage data plane auth

- src/azure-cli-core/azure/cli/core/profiles/_shared.py
- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/_validators.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/linter_exclusions.yml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_create_image_version_with_region_cvm_encryptio.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_create_image_version_with_region_encryption.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_create_vm_with_shared_gallery_image.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_e2e.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_image_version_vhd.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_specialized.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_image_build_shared_image.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_replication_mode.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_shared_gallery.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_specialized_image.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_max_shares_etc.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_actions.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
CVM security profile Cli extension support request https://github.com/Azure/azure-cli/issues/19754
close https://github.com/Azure/azure-cli/issues/19754
---
> [Compute] `az sig image-version create`: Add new parameter `--target-region-cvm-encryption` to support Confidential VM encrypting the OS disk

- src/azure-cli/azure/cli/command_modules/cdn/custom/custom.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_akamai_delivery_rule.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_endpoint_compression.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_endpoint_crud.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_endpoint_different_profiles.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_endpoint_load_and_purge.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_endpoint_start_and_stop.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_rule_engine_crud.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_verizon_delivery_rule.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_endpoint_scenarios.py
Fixes: https://github.com/Azure/azure-cli/issues/22066
Fix type argument missing issue
az cdn name-exists --name contoso
---
> [CDN] Fix #22066: `az cdn name-exists` missing type argument

- src/azure-cli/azure/cli/command_modules/netappfiles/_client_factory.py
- src/azure-cli/azure/cli/command_modules/netappfiles/_help.py
- src/azure-cli/azure/cli/command_modules/netappfiles/_params.py
- src/azure-cli/azure/cli/command_modules/netappfiles/commands.py
- src/azure-cli/azure/cli/command_modules/netappfiles/custom.py
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_active_directory.yaml
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_create_get_list_delete_volume_group.yaml
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_hrs_volume_groups.yaml
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/test_calculate_throughput_for_vg.py
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/test_calculate_usage_threshold_for_vg.py
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/test_volumegroup_commands.py
Volume Group commands added and logic around it. The logic is based on the ARM templates made for this feature.
[NetAppFiles] `az netappfiles volume-group`: Add command group to manage volume group resources
---
> [NetAppFiles] Add Volume Group commands

- src/azure-cli/azure/cli/command_modules/acr/_params.py
- src/azure-cli/azure/cli/command_modules/cosmosdb/custom.py
PRs should target `dev`, otherwise changes on `main` branch won't get released (we release from `dev` branch). This will also break release CI pipeline's **Merge to master** task.
> {Branch management} Merge `main` to `dev`

- src/azure-cli/azure/cli/command_modules/storage/_client_factory.py
- src/azure-cli/azure/cli/command_modules/storage/_help.py
- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/commands.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_container_operations.yaml
track2 migration
`az storage container lease acquire --lease-duration 60 -c {} --if-modified-since {} --proposed-lease-id {}`
`az storage container lease change -c {} --lease-id {} --proposed-lease-id {}`
`az storage container lease renew -c {} --lease-id {}`
`az storage container lease break -c {} --lease-break-period 30`
`az storage container lease release -c {} --lease-id {}`
---
> {Storage} `az storage container lease`: Track2 migration

- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
* bump PyNaCl from 1.4.0 to 1.5.0 to support arm64 wheel installation.
Ref:
https://github.com/Azure/azure-cli/issues/7368
PyNaCl 1.5.0 provides pre-built wheel installation also form arm64 architecture, so the installation is more efficient than building it every time needed.
---
> {Packaging} Bump PyNaCl from 1.4.0 to 1.5.0 to support arm64 wheel installation

- src/azure-cli/azure/cli/command_modules/network/custom.py
Resolves: https://github.com/Azure/azure-cli/issues/17677
Update ‘az network dns zone export’ 
dns alias: https://docs.microsoft.com/en-us/azure/dns/dns-alias#:~:text=Azure%20DNS%20alias%20records%20are,instead%20of%20an%20A%20record.
---
> [Network] `az network dns zone export`: Support traffic manager resources

- src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
Fix v2 decorator backward compatibility issues.
---
> {AKS} Fix v2 decorator backward compatibility issues

- src/azure-cli/azure/cli/command_modules/acs/_help.py
Fixes https://github.com/Azure/azure-cli/issues/21725
---
> {ACS} Updating default values to the description

- src/azure-cli/azure/cli/command_modules/acs/custom.py
> {AKS} Enable v2 decorator

- src/azure-cli/azure/cli/command_modules/netappfiles/custom.py
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_add_export_policy_with_invalid_rule_index.yaml
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_add_export_policy_with_no_rule_index.yaml
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_create_volume_with_non_default_export_policy.yaml
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/test_volume_commands.py
Validation added to `rule-index` parameter in add export policy and made non required.
[NetAppFiles] `az netappfiles volumes export-policy add`: Fix `rule-index` validation and parameter made non required
---
> [NetAppFiles] Fix validation to parameter `rule-index` in add export policy

- src/azure-cli/azure/cli/command_modules/netappfiles/_help.py
- src/azure-cli/azure/cli/command_modules/netappfiles/custom.py
Added missing parameter to add and update Active Directory named `site`
[NetAppFiles] `az netappfiles ad add`: Add new optional parameter `site`
[NetAppFiles] `az netappfiles ad update`: Add new optional parameter `site`
---
> [NetAppFiles] Add parameter `site` to add and update active directory

- src/azure-cli/azure/cli/command_modules/serviceconnector/_params.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/test_containerapp_connection_scenario.py
`az containerapp connection`
Add service connector for containerapp in command group `az containerapp connection`.
add test: test_containerapp_mysql_e2e, test_containerapp_storageblob_e2e
---
> [Service Connector] `az containerapp connection`: Add new command group to support container app connection

- src/azure-cli/azure/cli/command_modules/acs/_consts.py
- src/azure-cli/azure/cli/command_modules/acs/_graph.py
- src/azure-cli/azure/cli/command_modules/acs/_helpers.py
- src/azure-cli/azure/cli/command_modules/acs/_roleassignments.py
- src/azure-cli/azure/cli/command_modules/acs/commands.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/decorator.py
- src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/hybrid_2020_09_01/test_service_principals.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_service_principals.py
- Remove deprecated code.
- Tidy up the functions in `custom.py`.
- Add annotations to deprecated functions.
- Put together the functions used by `aks` commands.
- Remove all external function dependencies in the decorator architecture.
- Split role assignment and graph related functions into separate files (i.e., `_roleassignments.py` and `_graph.py`).
- The functions reserved in `custom.py` are used to maintain the interface of deprecated commands.
---
> {AKS} Remove deprecated code

- src/azure-cli/azure/cli/command_modules/synapse/manual/operations/sparkpool.py
az synapse spark pool update
With new azure.mgmt.synapse, add spark pool package cmdlets using a new parameter "uploaded_timestamp" to record update time. 
---
> {Synapse} add timestamp to az synapse spark pool update package

- src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_kusto_cluster.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_link_resource_kusto_cluster.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
* added pe support for kusto clusters
* added pe test for kusto clusters
Co-authored-by: Ohad Tayler <t-ohadtayler@microsoft.com>
---
> [Network] Private link add `Microsoft.Kusto/clusters` provider

- src/azure-cli/azure/cli/command_modules/apim/custom.py
`apply_network_configuration_updates` function has been renamed to `begin_apply_network_configuration_updates`
1. Create an APIM instance
2. az apim apply-network-updates --name {servicename} --resource-group {rg} --subscription {sub} --location {location}
3. Ensure that it passed successfully
---
> [API Management] Fix apim's `apply-network-updates` command

- src/azure-cli/azure/cli/command_modules/apim/custom.py
Fixes https://github.com/Azure/azure-cli/issues/21422
---
> {azure-cli} | Update API Revision if API Version is not provided

- src/azure-cli/azure/cli/command_modules/serviceconnector/_params.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/_validators.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/custom.py
`az containerapp connection create`
* Add `--container` parameter in `az containerapp connection create` interactive mode.
* Change default client_type to `none`
[Service Connector] BREAKING CHANGE: `az containerapp connection create`: Default client_type changed to `none`
[Service Connector] `az containerapp connection create`: Add `--container` parameter in interactive mode
---
> [Service Connector] `az containerapp connection create`: Add required parameter for interactive mode

- src/azure-cli/azure/cli/command_modules/storage/operations/table.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_table_main_scenario.yaml
`az storage entity insert`
Fix #22236 
First of all insert an entity
```
az storage entity insert -e PartitionKey=AAA RowKey=BBB Content=test -t $table_name --account-name $account_name
```
Then insert the same entity with `--if-exists fail`
```
az storage entity insert -e PartitionKey=AAA RowKey=BBB Content=test --if-exists fail -t $table_name --account-name $account_name
```
---
> [Storage] Fix #22236: `az storage entity insert`: Fix `--if-exists fail` not working

- src/azure-cli/azure/cli/command_modules/vm/_params.py
Please add SLES
az vm update -g myResourceGroup -n myVmName --license-type **SLES**
New license type added
- [ Y] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).
- [ Y] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).
- [ Y] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).
> [Compute] `az vm update`: Add additional license type SLES for `--license-type`

- src/azure-cli/azure/cli/command_modules/vm/_validators.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_simple_placement.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
VMSS Flex: Enable Single Placement Group https://github.com/Azure/azure-cli/issues/21834
---
> [Compute] `az vmss create`: Support enabling single placement group for Flexible VMSS

- src/azure-cli/azure/cli/command_modules/acs/_consts.py
- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
`az aks check-acr`
[AKS] `az aks check-acr`: Add new option `--node-name` to specify the name of a specific node to perform acr pull test checks
Updated test case `test_aks_create_attach_acr`.
---
> [AKS] `az aks check-acr`: Add new option `--node-name` to specify the name of a specific node to perform acr pull test checks

- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_create_image_version_with_region_cvm_encryptio.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_defer_only_commands.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_encryption_set.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_encryption_set_disk_update.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_encryption_set_snapshot.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_encryption_set_update.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_e2e.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_image_build_managed_image.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_image_build_shared_image.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_image_builder_basic.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_image_builder_basic_sig.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_image_builder_cancel.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_image_builder_customizers.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_image_template_outputs.yaml
See https://github.com/Azure/azure-cli/issues/22174
Re-record vm module tests that include `az ad` or `az role`.
---
> {Graph} Re-record related tests of vm module

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_config_backup_restore.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Fixes issue #18151 where restoring a backup to a slot would fail for the following reason: `'WebAppsOperations' object has no attribute 'restore_slot'`.
az webapp config backup restore
Changing the method from `restore_slot` (which doesn't appear to be a valid method) to [begin_restore_slot](https://docs.microsoft.com/en-us/python/api/azure-mgmt-web/azure.mgmt.web.v2021_02_01.operations.webappsoperations?view=azure-python#azure-mgmt-web-v2021-02-01-operations-webappsoperations-begin-restore-slot) fixes the issue for me. The `restore` method was also updated to `begin_restore` and tested.
[Component Name 2] `az command b`: Add …
> [App Service] Fix #18151: `az webapp config backup restore`: Fix the bug that 'WebAppsOperations' object has no attribute 'restore_slot'

- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
Add pkginfo==1.8.2 to requirements.py3.$(uname).txt.
---
> {CI} Add pkginfo==1.8.2 to requirements.py3.$(uname).txt

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/custom_preparers.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Remove the deprecated pre-process functions for sp. May refer to [PR #22361](https://github.com/Azure/azure-cli/pull/22361).
---
> {AKS} Remove deprecated pre-process functions for sp

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/_validators.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_with_defender.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_update_with_defender.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
Adding support for security profile in aks
The following flags added - 
az aks create --enable-defender --defender-config <path_to_file_contain_configuration>
az aks update --enable-defender --defender-config <path_to_file_contain_configuration>
az aks update --disable-defender
az aks create --enable-defender
Create aks cluster with defender profile enabled 
az aks update --enable-defender
Update aks cluster with defender profile enabled 
az aks update --disable-defender
Update aks cluster with defender profile disabled
---
- [ V ] The PR title and description has followed the guideline in [Submitting Pull …
> [AKS] `az aks create/update`: Add Microsoft Defender security profile support

- src/azure-cli/azure/cli/command_modules/network/custom.py
Resolves: https://github.com/Azure/azure-cli/issues/22366
> That's right, I understand the design. because there is user posted questions about this on the internet, maybe return error msg can be more clear, let user know, in order to use existing subnet, please enter subnet resources ID. thanks.
---
> {Network} `az network application-gateway private-link add`: Refine error message

- src/azure-cli/azure/cli/command_modules/rdbms/_params.py
- src/azure-cli/azure/cli/command_modules/rdbms/custom.py
Adding tls_version parameter for mariadb create and update command per Cx requests
---
> [RDBMS] `az mariadb server create/update`: Support `--minimal-tls-version`

- src/azure-cli/azure/cli/command_modules/serviceconnector/_help.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/action.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/custom.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_containerapp_mysql_e2e_kvsecret.yaml
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_springcloud_mysql_e2e_kvsecret.yaml
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_webapp_mysqlflexible_e2e.yaml
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/test_containerapp_connection_scenario.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/test_springcloud_connection_scenario.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/test_webpp_connection_scenario.py
> [Azure/azure-cli] [Service Connector] `--secret name=xx keyVaultSecretUri=xx`: Add new parameter key value pair to support password from KeyVault

- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_security_partner_provider.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_virtual_appliance.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
The following "live_only" will be removed during bump azure-mgmt-network's PR merged:
- test_network_security_partner_provider;
- test_network_virtual_appliance;
---
> {Fix} temporarily bypass vwan tests

- .azure-pipelines/templates/automation_test.yml
- scripts/ci/automation_full_test.py
> {CI} Only list top 10 slowest durations

- src/azure-cli/azure/cli/command_modules/acs/_helpers.py
- src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_helpers.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
- `az aks update`
- `az aks nodepool update`
Refine v2 decorator.
---
> {AKS} Refine v2 decorator

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_autoscaler_then_update.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_nodepool_autoscaler_then_update.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
> {AKS} Add test case for cluster auto scaler

- src/azure-cli/azure/cli/command_modules/rdbms/_flexible_server_util.py
- src/azure-cli/azure/cli/command_modules/rdbms/_transformers.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_commands.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_mysql.py
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands.py
- src/azure-cli/azure/cli/command_modules/rdbms/validators.py
1. Changing customer facing naming of 'MemoryOptimized' tier to 'BusinessCritical' tier. 
No change in RP and only CLI changes in list-skus, create, update commands
2. Location capabilities API table transformer bug fix
---
> [RDBMS] Change MySQL MemoryOptimized tier name to BusinessCritical

- src/azure-cli/azure/cli/command_modules/apim/_help.py
- src/azure-cli/azure/cli/command_modules/apim/custom.py
`apply_network_configuration_updates` function has been renamed to `begin_apply_network_configuration_updates`
The documentation on the `apply-network-updates` command is wrong. This fixes it.
No testing required.
---
> {API Management} Fix documentation for `apply-network-updates` command

- src/azure-cli/azure/cli/command_modules/security/_help.py
- src/azure-cli/service_name.json
> {Security} `az security`: Changed product name from `Azure Security Center` to `Microsoft Defender for Cloud`

- src/azure-cli-core/azure/cli/core/aaz/__init__.py
- src/azure-cli-core/azure/cli/core/aaz/_arg.py
`has_value` function is required by list command generation. This function was removed by mistake when code clean up.
---
> {Core} aaz add has_value function

- src/azure-cli/azure/cli/command_modules/identity/__init__.py
- src/azure-cli/azure/cli/command_modules/identity/commands.py
- src/azure-cli/azure/cli/command_modules/identity/tests/latest/recordings/test_identity_management.yaml
- src/azure-cli/azure/cli/command_modules/identity/tests/latest/test_identity.py
listAssociatedResources https://github.com/Azure/azure-cli/issues/22112 
---
> [Identity] `az identity list-resources`: Add new command to support list the associated resources for identity

- src/azure-cli/azure/cli/command_modules/vm/_help.py
Description of az vm deallocate was not enough to describe what it does.
---
> {Compute} `az vm deallocate`: Update help message 

- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/tests/hybrid_2018_03_01/recordings/test_network_vnet_peering.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/hybrid_2018_03_01/test_network_commands.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_peering.yaml
`az network vnet peering`
Removed deprecated parameters mentioned in: 
- https://github.com/Azure/azure-cli/issues/21952
---
> {Network} `az network`: Remove deprecated parameters

- src/azure-cli/azure/cli/command_modules/acr/_format.py
`az acr replication list -o table` and `az acr replication show -o table` 
`az acr replication list -o table` and `az acr replication show -o table` do not show regionendpointenabled property. Have updatep the table output to show this property
`az acr replication show --name Myreplication -r MyRegistry -o table`
`az acr replication list -r MyRegistry -o table`
---
> [ACR] `az acr`: Show replication region endpoint status in table output

- src/azure-cli/azure/cli/command_modules/role/msgrpah/_graph_client.py
Merge fix #22565 back to `dev`.
> {Branch Management} Merge release back to dev

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
`network application-gateway create`
Fix aks byo appgw test case `test_aks_byo_appgw_with_ingress_appgw_addon`. See sibling PR [#4894](https://github.com/Azure/azure-cli-extensions/pull/4894) in aks-preview.
---
> {AKS} Fix aks byo appgw test case

- .github/CODEOWNERS
> {.github} Add CODEOWNERS for CDN

- src/azure-cli/azure/cli/command_modules/cdn/_help.py
- src/azure-cli/azure/cli/command_modules/cdn/commands.py
az cdn waf
Deprecate CDN WAF related commands
az cdn waf policy custom-rule list -g afdx-bugbash --policy-name CDBWAFbug
---
> {CDN} Deprecate CDN WAF related commands

- src/azure-cli/azure/cli/command_modules/appservice/_params.py
Fixes https://github.com/Azure/azure-cli/issues/22660
---
> {App Service} Fix typo github, Github to GitHub in the help message

- src/azure-cli/azure/cli/command_modules/storage/operations/blob.py
> [Storage] Fix#22563: `az storage blob upload`: Fix storage blob upload to a through pipe encode error

- src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_resourcemanagementprivatelink.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
Enabling Support for private link for Microsoft.Authorization/resourceManagementPrivateLinks provider
Previous PR to add test and support: https://github.com/Azure/azure-cli/pull/19742
---
> [Network] Enable Private link support for provider Microsoft.Authorization/resourceManagementPrivateLinks

- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone1_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone2_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone3_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone4_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone5_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone6_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone7_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone8_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone9_import.yaml
- src/azure-cli/azure/cli/command_modules/network/zone_file/parse_zone_file.py
Fix : https://github.com/Azure/azure-cli/issues/22097
Command Name
az network dns zone import
Errors:
argument of type 'NoneType' is not iterable
Local\Temp\pip-unpacked-wheel-49qlvzn7\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 654, in execute
azure\cli\core\commands\__init__.py, ln 718, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 711, in _run_job
AppData\Local\Temp\pip-unpacked-wheel-tle01379\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 688, in _run_job
azure\cli\core\commands\__init__.py, ln 325, in __call__
pip-unpacked-wheel-03qxfwck\azure\cli\core\__init__.py, ln 784, in default_command_handler
azure\cli\command_modules\network\custom.py, ln …
> [Network] Fix #22097: `az network dns zone import` cannot import zone files starting with space

- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_public_ip_prefix.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_public_ip_prefix_with_ip_address.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Resolves: https://github.com/Azure/azure-cli/issues/19473
> In general, with an existing public ip prefix, you should not need to call out: Version, Allocation Method, SKU, Tier, or Zonal properties – these all should be assumed to match the prefix. This should be fixed for all cases.
---
> [Network] `az network public-ip create`: Reuse prefix info when creating Public IP

- src/azure-cli/azure/cli/command_modules/monitor/operations/autoscale_settings.py
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_basic.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_autoscale.py
Fix ICM: https://portal.microsofticm.com/imp/v3/incidents/details/311436712/home
---
> {Monitor} `monitor autoscale update`: Support `--count` equal `0`

- src/azure-cli/azure/cli/command_modules/cognitiveservices/custom.py
- src/azure-cli/azure/cli/command_modules/cognitiveservices/tests/latest/recordings/test_cognitiveservices_identity.yaml
`az cognitiveservices account identity remove`
Fix #22545. `client.begin_update` returns a `LROPoller` instance. During instance initialization, a thread named `LROPoller(xx)` is created. If the command's return type is poller, azure core will call `LROPoller.result()` to get the final result. Thus the `LROPoller(xx)` thread is joined and terminated.
Without `return`, azure core will not wait the thread and this thread may be still active when call `tearDown()`.
Create a cognitive services, then
`az cognitiveservices account identity remove -g <rg> -n <service-name>`
You should see the running progress bar and the final json output.
---
> {Cognitive Services} Fix #22545: `az cognitiveservices account identity remove`: Return LROPoller

- .github/CODEOWNERS
Remove Delora from code owner list for internal docs.
---
> {Docs} Remove unnecessary code owner for internal doc

- doc/authoring_tests.md
> {doc} Add `Scenario Test Best Practice` section in `authoring_tests`

- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_guest_attestation_extension_and_msi.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Update VMSS instances with updated VMSS model for Trusted Launch features https://github.com/Azure/azure-cli/issues/22338
---
> {Computue} `az vmss create`: Update VMSS instances for Trusted Launch

- src/azure-cli/azure/cli/command_modules/resource/_bicep.py
Updated URL for Bicep Downloads link to use new Bicep CDN: https://github.com/Azure/bicep/issues/3689
---
> {Bicep} Update the URL for Bicep downloads link

- doc/try_new_features_before_release.md
Update `try_new_features_before_release.md`.
> {Doc} Update try_new_features_before_release.md

- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
`az vm create`
`az vm disk`
`az vmss disk`
azdev test test_vmss_disk_storage_sku
azdev test test_vm_disk_storage_sku2: Service not ready
---
> [Compute] `az vm`: Support a new disk storage SKU Premiumv2_LRS

- src/azure-cli/azure/cli/command_modules/backup/_help.py
- src/azure-cli/azure/cli/command_modules/backup/custom_wl.py
> [Backup] `az backup protectable-item list`: SQLAG container fetch failure bug fix

- src/azure-cli/azure/cli/command_modules/vm/_validators.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_snapshot_incremental.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Should not use CreateOption 'CopyStart' for full snapshot creation https://github.com/Azure/azure-cli/issues/22370
For full snapshot use CreateOption Copy
For incremental snapshot use CreateOption Copy if same region and use CreateOption CopyStart if different region.
---
> {Compute} `az snapshot create`: incremental snapshot should use CreateOption Copy instead of CopyStart

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_ssl_import.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_ssl_import_crossrg.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
> [App Service] Fix #22722: `az webapp config ssl import` fixes to support new GraphAPI for SP queries

- src/azure-cli-core/azure/cli/core/aaz/_arg.py
- src/azure-cli-core/azure/cli/core/aaz/_operation.py
- src/azure-cli-core/azure/cli/core/tests/test_aaz_operation.py
When serialize request content, some properties should use empty value if it's required. This PR is for such usage.
---
> {Core} `aaz`: Fill and verify the required property in request content.

- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_custom_image_debian.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_data_unmanaged_disk_debian.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_extension_debian.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_generalize_debian.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_extension_debian.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_vms_debian.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Add some tests of existing scenarios but replace the image with `Debian`, to test stability.
These are existing scenarios:
```
test_vm_generalize
test_vm_custom_image
test_vm_data_unmanaged_disk
test_vmss_vms
test_vm_extension
test_vmss_extension
```
---
> {Compute} Add scenario tests using `Debian` image

- src/azure-cli-core/azure/cli/core/aaz/_arg_browser.py
- src/azure-cli-core/azure/cli/core/aaz/_base.py
- src/azure-cli-core/azure/cli/core/aaz/_content_builder.py
- src/azure-cli-core/azure/cli/core/aaz/_field_value.py
- src/azure-cli-core/azure/cli/core/aaz/_operation.py
- src/azure-cli-core/azure/cli/core/tests/test_aaz_content_builder.py
This PR fixed the issues when passing `null` value for arguments.
---
> {Core} `aaz`: fix nullable argument behaviors.

- src/azure-cli-core/azure/cli/core/aaz/_arg.py
- src/azure-cli-core/azure/cli/core/aaz/_help.py
> {Core} `aaz`: Correct the word `summary`

- src/azure-cli-core/azure/cli/core/aaz/_arg.py
- src/azure-cli-core/azure/cli/core/aaz/_help.py
> {Core} `aaz`: optimize argument help messages for shorthand syntax.

- src/azure-cli-core/azure/cli/core/aaz/_field_type.py
> {core} `aaz`: fix get_discriminator of AAZObjectType

- scripts/ci/credscan/CredScanSuppressions.json
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_acfr.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_link_resource_acfr.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
az network private-link-resource
az network private-endpoint-connection
Resolved the issue mentioned in:
- https://github.com/Azure/azure-cli-pr/issues/136
Removed previous suppression for credential scan:
- https://github.com/Azure/azure-cli/pull/20867
---
> {Network} Desensitize tests for private link `Microsoft.Cache/Redis`

- src/azure-cli/azure/cli/command_modules/sql/_params.py
Fixes https://github.com/Azure/azure-cli/issues/22729
---
> {sql} Update sample for action parameter

- src/azure-cli/azure/cli/command_modules/resource/_help.py
az provider list --query "[?namespace=='Microsoft.Network'].resourceTypes[].resourceType" instead of az provider list --query [?namespace=='Microsoft.Network'].resourceTypes[].resourceType which results in [ ] results
---
> {ARM} `az provider list`: Add double quotes for `--query` in the help example

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_update_slot.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py
`az functionapp update`
Fixes #20901
---
> [App Service] Fix #20901: `az functionapp update`: Update `--slot` logic to work correctly

- src/azure-cli/HISTORY.rst
> {Doc} Fix `az storage` typo

- src/azure-cli/azure/cli/command_modules/resource/_utils.py
`az deployment sub/mg/tenant/group create`
Issue: #22835 
Related PR: #20238
Fix the error message of ARM deployment to the correct JSON format
Before
After
---
> [ARM] `az deployment`: Fix the error message of ARM deployment to the correct JSON format

- src/azure-cli-core/azure/cli/core/util.py
- src/azure-cli/azure/cli/command_modules/util/tests/latest/recordings/test_rest_unicode.yaml
- src/azure-cli/azure/cli/command_modules/util/tests/latest/test_rest.py
`az rest`
When request body contains Unicode characters like
```
{"displayName": "测试组", "mailNickname": "testnickname", "mailEnabled": false, "securityEnabled": true}
```
`az rest` fails:
```
> az rest --method post --url "https://graph.microsoft.com/v1.0/groups" -b "@body.json" --verbose
Request URL: 'https://graph.microsoft.com/v1.0/groups'
Request method: 'POST'
Request headers:
'User-Agent': 'python/3.10.4 (Windows-10-10.0.19044-SP0) AZURECLI/2.37.0 (PIP)'
'Accept-Encoding': 'gzip, deflate'
'Accept': '*/*'
'Connection': 'keep-alive'
'x-ms-client-request-id': 'aac53775-2979-4962-a30d-40c74636190b'
'Content-Type': 'application/json'
'CommandName': 'rest'
'ParameterSetName': '--method --url -b --verbose'
'Authorization': 'Bearer eyJ0eXAiOiJKV...' …
```
> [Rest] `az rest`: Support Unicode characters in JSON request body

- .github/fabricbot.json
Please merge this PR after we switch to milestone Jul 2022 (2022-08-02).
> {CI} Update milestone from Jun 2022 (2022-07-05) to Jul 2022 (2022-08-02)

- src/azure-cli/azure/cli/command_modules/rdbms/validators.py
Fixes https://github.com/Azure/azure-cli/issues/22968
---
> {rdbms} | None is compared as 'None'

- src/azure-cli-core/azure/cli/core/aaz/_command.py
- src/azure-cli-core/azure/cli/core/aaz/_command_ctx.py
- src/azure-cli-core/azure/cli/core/aaz/_poller.py
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_log_analytics_cluster_default.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_log_analytics_cluster.py
When using `--no-wait` for long running aaz commands, they will be terminated early before service return valid response:
This PR is aimed to fix that issue.
---
> [Core] `aaz`: Fix early exit for long running commands run with `--no-wait` parameter

- src/azure-cli/azure/cli/command_modules/acs/_consts.py
add 5s wait to avoid attach race condition
ran e2e test pipeline
---
> [AKS] `az aks check-acr`: Bump canipull to v0.1.0 to add 5s wait to avoid attach race condition

- src/azure-cli/azure/cli/command_modules/vm/_validators.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_create_image_version_with_region_cvm_encryption_pmk.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_e2e.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
The `--target-region-encryption` and the `--target-region-cvm-encryption` parameters should be independent of one another but right now the `--target-region-cvm-encryption` parameter ONLY works when `--target-region-encryption` is also specified.
https://github.com/Azure/azure-cli/issues/22995
---
> [Compute] Fix #22995: `az image-version create`: Unbind the usage of `--target-region-encryption` and `--target-region-cvm-encryption`

- src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
> [Service Connector] `az spring connection create eventhubs`: Add new param `--client-type kafka-springBoot`

- .github/CODEOWNERS
Add Ethan Yang as code owner of azure-cli-core
---
> {github} Update CODEOWNERS

- src/azure-cli/azure/cli/command_modules/acs/_help.py
Fixes https://github.com/Azure/azure-cli-extensions/issues/2457
---
> [AKS] Fix #2457: Clarify subnet id description to resource id

- src/azure-cli/azure/cli/command_modules/resource/_help.py
Fixes https://github.com/Azure/azure-cli/issues/23246
---
> [ARM] Fix #23246: Fix interchanged policy samples

- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
New SDK generated by [autorest.python 5.16.0](https://github.com/Azure/azure-sdk-for-python/issues/24221) will depend on azure-mgmt-core 1.3.1.
Example: azure-mgmt-web 7.0.0 depends on azure-mgmt-core 1.3.1 (PR is https://github.com/Azure/azure-cli/pull/23213)
---
> {Packaging} Upgrade azure-mgmt-core to 1.3.1

- src/azure-cli/azure/cli/command_modules/sql/_help.py
Fixes https://github.com/Azure/azure-cli/issues/15772
---
> {SQL} Fix #15772: Fix a minor typo

- src/azure-cli/azure/cli/command_modules/sql/_params.py
Fixes https://github.com/Azure/azure-cli/issues/15773
---
> {SQL} Fix #15773: Fix minor typo

- src/azure-cli/azure/cli/command_modules/sql/_params.py
Fixes https://github.com/Azure/azure-cli/issues/17941
---
> {SQL} Fix #17941: Fix minor typo

- src/azure-cli/azure/cli/command_modules/storage/_params.py
Fixes https://github.com/Azure/azure-cli/issues/21073
---
> {Storage} Fix #21073: Fix minor typo

- src/azure-cli/azure/cli/command_modules/synapse/manual/_help.py
Add definition file example in help doc for `az synapse managed-private-endpoints create`
---
> {Synapse}`az synapse managed-private-endpoints create`: Add definition file example in help

- src/azure-cli/azure/cli/command_modules/lab/_help.py
Fixes https://github.com/Azure/azure-cli/issues/11445
---
> {Lab} Fix #11445: Add possible values for disk type parameter

- src/azure-cli-core/azure/cli/core/aaz/__init__.py
- src/azure-cli-core/azure/cli/core/aaz/_arg.py
- src/azure-cli-core/azure/cli/core/aaz/_arg_fmt.py
- src/azure-cli-core/azure/cli/core/tests/test_aaz_arg_fmt.py
> [Core] `aaz`: Support `AAZDurationArg`, `AAZDateArg`, `AAZTimeArg`, `AAZDateTimeArg` and `AAZUuidArg`

- src/azure-cli/azure/cli/command_modules/network/commands.py
mTLS and SSL Profile are now GA - removing preview flag
https://azure.microsoft.com/en-us/updates/general-availability-application-gateway-mutual-authentication/
---
> {Network} `az network application-gateway`: Remove `is_preview` flag within `client-cert` and `ssl-profile` command groups

- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_waf_custom_rule.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Resolves: https://github.com/Azure/azure-cli/issues/22932
az network application-gateway waf-policy custom-rule match-condition add
Similar validation logic in PowerShell: 
- https://github.com/Azure/azure-powershell/blob/network-2022-01-01/src/Network/Network/FirewallPolicy/FirewallCondition/AzureApplicationGatewayFirewallConditionBase.cs#L77
We use `nargs='+'` to ensure that the length of `match_values` is not zero if it exits.
---
> [Network] `az network application-gateway waf-policy custom-rule match-condition add`: Add validation for WAF custom rule condition

- .github/fabricbot.json
Updating the contacts for Cosmos, by request.
> {Bot Rules} Update Cosmos Contacts

- src/azure-cli/azure/cli/command_modules/acr/_utils.py
… a password but no username
fixes https://github.com/Azure/azure-cli/issues/23340
---
> [ACR] Fix #23340: `az acr task credential add`: Fix crashes when given a password but no username

- README.md
> {Packaging} Remove deprecated edge builds

- src/azure-cli/azure/cli/command_modules/advisor/custom.py
…e error
Fixes https://github.com/Azure/azure-cli/issues/11070
---
> [Advisor] Fix #11070: Fix `az advisor recommendation disable` NoneType error

- src/azure-cli/azure/cli/command_modules/network/_params.py
az network vnet subnet create
az network vnet subnet update
`--disable-private-endpoint-network-policies` is used for disabling the policy and the policy is disabled by default. Instead of `--disable-private-endpoint-network-policies` is disabled (set to false) by default, which will lead to policy enabled.
@dbradish-microsoft for awareness.
---
> {Network} `az network vnet subnet`: Update help message for `--disable-private-endpoint-network-policies`

- src/azure-cli/azure/cli/command_modules/network/_help.py
az network private-endpoint create
Guide users to compose a valid request:
---
> [Network] `az network private-endpoint create`: Add an example for creating with ASGs

- scripts/release/debian/deb_install.sh
Change default Ubuntu repo to `jammy`. (Same as https://github.com/Azure/azure-cli/pull/20556)
> {Packaging} Change default Ubuntu repo to `jammy`

- src/azure-cli-core/azure/cli/core/auth/landing_pages/success.html
`az login`
This trivial PR changes "Azure CLI documents" to "Azure CLI documentation" on the login success page, which aligns with the title of the target page (and proper grammar).
---
> {Core} `az login`: Update redirect message

- src/azure-cli/azure/cli/command_modules/monitor/_params.py
Correcting the description colunm to column
NA
Fixes #23161 
NA
NA
---
> {Monitor} Fix #23161: Correcting the description colunm to column

- .github/fabricbot.json
> {CI} Update milestone from Jul 2022 (2022-08-02) to Aug 2022 (2022-09-06)

- src/azure-cli-core/azure/cli/core/aaz/_arg.py
- src/azure-cli-core/azure/cli/core/aaz/_arg_action.py
- src/azure-cli-core/azure/cli/core/aaz/_base.py
> {Core}: 'aaz': Copy default and blank values in arguments

- src/azure-cli/azure/cli/command_modules/vm/commands.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_update_image.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
`az vm run-command invoke`
Add new parameters `--no-wait` 
close https://github.com/Azure/azure-cli/issues/22788
[Compute] `az vm run-command invoke`: Add new parameters `--no-wait` to support not waiting for the long running operation to finish
---
> [Compute] `az vm run-command invoke`: Add new parameters `--no-wait` to support not waiting operation

- src/azure-cli-core/azure/cli/core/aaz/_http_policy.py
> [Core] `aaz`: Fix AAZBearerTokenCredentialPolicy to support MSIAuthenticationWrapper crendital

- src/azure-cli/azure/cli/command_modules/acs/_help.py
Add the below summary for the --node-taint parameter:
"You can update the existing node taint of a nodepool or create a new node taint for a nodepool."
fixes Azure/azure-cli#23510
---
> {ACS} Fix Azure/azure-cli#23510

- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_private_endpoint_asg.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_private_endpoint_ip_config.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
az network private-endpoint create
Mainly resolved the defects mentioned in [an IcM](https://portal.microsofticm.com/imp/v3/incidents/details/324825881/home).
---
> {Network} `az network private-endpoint create`: Refactor keyword arguments by unpacking

- src/azure-cli/azure/cli/command_modules/resource/_bicep.py
`az bicep`
The `az bicep` commands check for the latest version of Bicep by sending an HTTP request, but when it doesn't respect `AZURE_CLI_DISABLE_CONNECTION_VERIFICATION` and always validate SSL certificates. The PR updates the code to check if SSL certificate verification should be skipped.
Run any `az bicep` commands with `AZURE_CLI_DISABLE_CONNECTION_VERIFICATION` set to true.
---
> [ARM] `azure bicep`: Use `AZURE_CLI_DISABLE_CONNECTION_VERIFICATION` when checking Bicep CLI versions

- src/azure-cli/azure/cli/command_modules/signalr/_help.py
Incorrect short summary description for az signalr upstream clear
fixes Azure/azure-cli#23538
---
> {AzureSignalR} fixes Azure/azure-cli#23538

- src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
Add Microsoft.OpenEnergyPlatformto supported private endpoints
---
> [Network] Private link add `Microsoft.OpenEnergyPlatform/energyServices` provider

- src/azure-cli/azure/cli/command_modules/vm/_help.py
Fixes https://github.com/Azure/azure-cli/issues/22901
---
> {VM} Fix #22901 Fix case of lastRunStatus.runState value

- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
> {EnergyServices} Fix api version for energy services

- src/azure-cli/azure/cli/command_modules/monitor/grammar/metric_alert/MetricAlertCondition.g4
- src/azure-cli/azure/cli/command_modules/monitor/grammar/metric_alert/MetricAlertConditionLexer.py
- src/azure-cli/azure/cli/command_modules/monitor/grammar/metric_alert/MetricAlertConditionListener.py
- src/azure-cli/azure/cli/command_modules/monitor/grammar/metric_alert/MetricAlertConditionParser.py
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_metric_alert_v2_scenario.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_metric_namespace_special_character.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_metric_alert_scenarios.py
az monitor metric alert create
user customerized metric namespace would have dash (e.g., `some-namespace.metric`) but cli cannot recognize its namespace and metric part correctly (For now, it would take `some-namespace.metric` as its metric name due to incorrect namespace seperation)
With support of `-` in namespace, the problem above can be resolved.
test_metric_namespace_special_character
[monitor] `az monitor metric alert`: Support metric namespace with dash
---
closed https://github.com/Azure/azure-cli/issues/22724
> {monitor}`az monitor metric alert create`: Support metric namespace with dash

- src/azure-cli/azure/cli/command_modules/ams/_help.py
Fix https://github.com/Azure/azure-cli/issues/23551
---
> {ams} Fix #23551: Add an example for filter parameter

- src/azure-cli/azure/cli/command_modules/monitor/_params.py
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_metric_alert_v2_scenario.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_action_group_basic_scenario.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_action_group_location.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_action_groups.py
- src/azure-cli/azure/cli/command_modules/monitor/validators.py
closed https://github.com/Azure/azure-cli/issues/23002
az monitor action-group
For `az monitor action-group create`, to allow user specify the location, cmd need to accept the `--location` parameter. 
[monitor] `az monitor action-group create`: Add optional `--location` parameter to `create` cmd
---
> {Monitor} `az monitor action-group`: Add an optional location parameter to action-group create/update cmd

- src/azure-cli/azure/cli/command_modules/storage/__init__.py
More Info: https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-index-how-to?tabs=azure-cli#upload-a-new-blob-with-index-tags
fixes Azure/azure-cli#23536
The Blob tags write operation can be performed by "Storage Blob Data Owner". So this role should be listed while the operation fails.
For CLI extensions the PR has been already created.  https://github.com/Azure/azure-cli-extensions/pull/5242
---
> {AzureStorage} fixes Azure/azure-cli#23536

- src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_link_endpoint_deviceupdate.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
No new command. Added Device Update for IoT Hub support to Network Private Endpoint
Added Microsoft.DeviceUpdate/accounts support to Network Private Endpoint
See the added test and recording
---
> {Network} `az network private-endpoint`: Added Device Update for IoT Hub support to Network Private Endpoint

- src/azure-cli/azure/cli/command_modules/sql/_help.py
Fix https://github.com/Azure/azure-cli/issues/17345 and https://github.com/Azure/azure-cli/issues/17337
---
> {sql} Fix #17345: Add note to create the key first

- src/azure-cli-testsdk/azure/cli/testsdk/__init__.py
- src/azure-cli/azure/cli/command_modules/rdbms/_client_factory.py
- src/azure-cli/azure/cli/command_modules/rdbms/_helptext_mysql.py
- src/azure-cli/azure/cli/command_modules/rdbms/_params.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_commands.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_common.py
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_flexible_server_byok_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_flexible_server_identity_aad_admin_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands.py
- src/azure-cli/azure/cli/command_modules/rdbms/validators.py
User identity operations:
- `az mysql flexible-server identity assign`
- `az mysql flexible-server identity list`
- `az mysql flexible-server identity show`
- `az mysql flexible-server identity remove`
AAD Admin operations:
- `az mysql flexible-server ad-admin create`
- `az mysql flexible-server ad-admin list`
- `az mysql flexible-server ad-admin show`
- `az mysql flexible-server ad-admin delete`
We need the ability to add/remove user identities and add/remove Active Directory administrator for MySQL flexible server.
---
> [RDBMS] `az mysql flexible-server identity/ad-admin`: User Identity and AAD Admin for MySQL flexible server

- src/azure-cli/azure/cli/command_modules/sql/custom.py
Fix https://github.com/Azure/azure-cli/issues/18948
---
> {sql} Fix #18948: Remove unnecessary print statement causing confusion

- src/azure-cli-core/azure/cli/core/aaz/_arg.py
- src/azure-cli-core/azure/cli/core/aaz/_arg_action.py
- src/azure-cli-core/azure/cli/core/aaz/_command.py
- src/azure-cli-core/azure/cli/core/aaz/_operation.py
- src/azure-cli-core/azure/cli/core/tests/test_aaz_operation.py
> [Core] `aaz`: Support generic update arguments

- src/azure-cli/azure/cli/command_modules/acr/_params.py
az acr
There's a typo and I don't like typos
N/A
---
> {acr} Fix misspelling of 'repository' in acr subcommands help

- src/azure-cli/azure/cli/command_modules/vm/_help.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_run_command_v2.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
- `az vm run-command show`
- `az vm run-command list`
Issue - close: #23455
Add validation and refine help message for parameter combination. Otherwise, the Python SDK will throw an `ValueError: No value for given attribute` error due to the lack of necessary parameters
---
> [Compute] `az vm run-command show/list`: Add validation and refine help message for parameter combination

- src/azure-cli/azure/cli/command_modules/vm/_help.py
`az sig image-definition create`
Issue - Fix: #23636
---
> {Compute} `az sig image-definition create`: Remove duplicate examples

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
`az functionapp github-actions add` 
Fixes #23417, which causes GitHub actions for java function apps to fail to run 
---
> [App Service] Fix #23417: `az functionapp github-actions add`: Fix the functionapp github actions on java

- src/azure-cli/azure/cli/command_modules/acr/manifest.py
- src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_commands_mock.py
az acr manifest show
Improve performance by eliminating unnecessary REST call
az acr manifest show -h
[ACR] `az acr manifest show`: Improve performance
---
> {ACR} `az acr manifest show`: Improve performance by eliminating unnecessary REST call

- .github/ISSUE_TEMPLATE/Service_team_request.yaml
- If user creates a feature request with the template(`[Microsoft Internal / Service Team] Feature Request`), automatically add the label `feature-request`.
- Modify `Swagger PR link` to `Swagger PR link / SDK link`.
- Add `If you cannot provide, please fill in N/A.` to description.
> {CI} Update `[Microsoft Internal / Service Team] Feature Request` template

- src/azure-cli/azure/cli/command_modules/sql/custom.py
Fix https://github.com/Azure/azure-cli/issues/19731
---
> {sql} Fix #19731: Add condition for SystemAssigned Identity type as well

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
> [App Service] `az functionapp list-runtimes`: Add linuxFxVersion to output

- .github/fabricbot.json
> {CI} Update milestone from Aug 2022 (2022-09-06) to Sep 2022 (2022-10-12) - For Ignite

- src/azure-cli-core/azure/cli/core/util.py
`az upgrade`
Fix grammar error found by https://github.com/Azure/azure-cli/issues/23470: updates -> update(s)
> {Upgrade} `az upgrade`: Fix grammar error: updates -> update(s)

- src/azure-cli-core/azure/cli/core/profiles/_shared.py
- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/_validators.py
- src/azure-cli/azure/cli/command_modules/storage/commands.py
- src/azure-cli/azure/cli/command_modules/storage/operations/filesystem.py
- src/azure-cli/azure/cli/command_modules/storage/operations/fs_directory.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_adls_gen2_encryption_scope.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_encryption_scope_scenarios.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_sas_scenarios.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
`az storage fs create`
`az storage fs generate-sas`
`az storage fs directory generate-sas`
This PR
- Bump Data Plane SDK `azure-multiapi-storagev2-filedatalake`
- Support specifying encryption scope on file system creation
- Support generating sas with encryption scope for file system and directory
[Storage] `az storage fs create`: Support encryption scope
[Storage] `az storage fs directory/fs generate-sas`: Support generating SAS token with specified encryption scope
---
> [Storage] Support encryption scope for ADLS Gen2 file system

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_deploy_zip.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_list_deployment_logs.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_show_deployment_logs.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands_thru_mock.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
- src/azure-cli/azure/cli/command_modules/appservice/utils.py
- `az webapp up`
- `az webapp deployment source config-zip`
Uses the new Web App deployment status API to give the user updates on the their status of their deployments 
[App Service] `az webapp up`: Show status during deployment for linux apps
[App Service] `az webapp deployment source config-zip`: Show status during deployment for linux apps
---
> [App Service] `az webapp up`: Show status during deployment for linux apps

- src/azure-cli-core/azure/cli/core/intercept_survey.py
As @chasewilson suggested in email thread:
> We need to align with PowerShell and remove the survey hyperlink for this iteration. We might add it later after reviewing the response rate. 
---
> {Survey} Don't show survey link in prompt message

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_nodepool_add_with_ossku_windows2022.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Fix test case `test_aks_nodepool_add_with_ossku_windows2022`.
---
> {AKS} Fix test case `test_aks_nodepool_add_with_ossku_windows2022`

- src/azure-cli/azure/cli/command_modules/network/_help.py
- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/_validators.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_watcher_packet_capture.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_watcher_packet_capture_vmss_as_target.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
az network watcher packet-capture create
Azure VMSS support is now available in packet capture. Packet capture can be created with VMSS as a target. 
This change will enable customer to create packet capture with VMSS as source via Azure CLI.
New parameters are added - 
* target - Name/Id of target resource 
* target_type - Defines where target is AzureVM or AzureVMSS. Default value is AzureVM
* include -  Space-separated list of VMSS Instances to include in Packet capture like 0 1 2  
* exclude - Space-separated list of VMSS Instances to exclude in Packet capture like 0 1 2
Note : --vm parameter is no longer mandatory. Packet capture can be created without vm paramter.
Below are few examples how packet-capture will be created.
* `az …
> [Network] `az network watcher packet-capture create`: Add VMSS support in packet capture

- .github/fabricbot.json
> [Synapse] Update Synapse contacts

- scripts/ci/check_pull_request.py
1. Add check to ensure parameters use `--x-x-x` format
2. Exclude all list type, see https://github.com/Azure/azure-cli/pull/23802
```
['app']
['-c', 'a b', 'a b']
["-c"]
[1]
['-c', 'System.Object[] System.Object[]', 'System.Object[] System.Object[]']
```
3. Exclude `[Markdown](url)`
> {CI} Fix check pull request script

- doc/telemetry/README.md
- doc/telemetry/faq.md
- doc/telemetry/kusto_examples.md
Fix format issue in telemetry doc
---
> {Doc} telemetry doc format

- src/azure-cli-core/azure/cli/core/aaz/_arg_action.py
- src/azure-cli-core/azure/cli/core/aaz/_help.py
- src/azure-cli-core/azure/cli/core/util.py
closed https://github.com/Azure/aaz-dev-tools/issues/109
---
> [Core] `aaz`: Support `yaml` file as value for compound arguments

- src/azure-cli/azure/cli/command_modules/serviceconnector/_validators.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/custom.py
az webapp/spring /containerapp connection
Validate connection name user specified before sending the request
---
> {Service Connector} Validate connection name

- src/azure-cli/azure/cli/command_modules/rdbms/_flexible_server_util.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_virtual_network.py
`az mysql/postgres flexible-server create/restore`
- When checking the existence of a resource group we perform a HEAD request to `/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}`, but if the user doesn't have the permission `Microsoft.Resources/subscriptions/resourceGroups/read` it will only return HTTP 403 Forbidden without explaining the reason why it failed. Hence, we add a descriptive error message.
- When checking the existence of a vnet/subnet we make a GET request to the resource, but we only check if there was an `HttpResponseError` exception. Hence, we need to tell the customer (throw a CLIException) if we receive HTTP 403.
- Create a server in a resource group that doesn't exist yet: `az mysql …
> {RDBMS} Add descriptive error messages when user doesn't have read access to resource

- src/azure-cli-testsdk/azure/cli/testsdk/preparers.py
- src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_commands.py
- src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/test_appconfig_commands.py
- src/azure-cli/azure/cli/command_modules/backup/tests/latest/test_backup_commands.py
- src/azure-cli/azure/cli/command_modules/eventhubs/tests/latest/test_eventhub_commands_encryption_test.py
- src/azure-cli/azure/cli/command_modules/eventhubs/tests/latest/test_eventhub_commands_namespace_byok_test.py
- src/azure-cli/azure/cli/command_modules/eventhubs/tests/latest/test_eventhub_commands_namespace_premium_test.py
- src/azure-cli/azure/cli/command_modules/keyvault/_params.py
- src/azure-cli/azure/cli/command_modules/keyvault/custom.py
- src/azure-cli/azure/cli/command_modules/keyvault/tests/hybrid_2018_03_01/test_keyvault_commands.py
- src/azure-cli/azure/cli/command_modules/keyvault/tests/hybrid_2020_09_01/test_keyvault_commands.py
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
- src/azure-cli/azure/cli/command_modules/servicebus/tests/latest/test_servicebus_encryption_commands.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
`az keyvault create/update`
`az keyvault create/update`: Finally remove `--enable-soft-delete` parameter as it doesn't support `False` since long ago
---
> [Keyvault] BREAKING CHANGE: `az keyvault create/update`: Finally remove `--enable-soft-delete` parameter

- src/azure-cli-core/azure/cli/core/aaz/_field_value.py
> [Core] `aaz`: Fix recursion depth exceeded for to_serialized_data of AAZObject

- src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
- az rest 
- network private-endpoint create
- Onboard AgFoodPlatform for PrivateLinkResource
---
> [Network] `az network private-endpoint-connection`: Add Provider `Microsoft.AgFoodPlatform/farmBeats`

- src/azure-cli-core/azure/cli/core/profiles/_shared.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_accelerated_network.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_architecture.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_completion_percent.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_create_image_version_with_region_cvm_encryption.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_create_image_version_with_region_cvm_encryption_pmk.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_access.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_encryption_set_disk_update.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_encryption_set_snapshot.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_trusted_launch.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_image_version_vhd.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_specialized.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_other_extended_location.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_public_network_access.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_snapshot_access.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_snapshot_incremental.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_snapshot_ultra_ssd.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_specialized_image.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_by_attach_os_and_data_disks.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_data_disk_delete_option.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_create_with_standard_zrs_sku.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_max_shares_etc.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_managed_disk.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_snapshot_copy_start_detection.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_snapshot_incremental.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
`az snapshot`
az snapshot not using the latest API version 2022-03-02  https://github.com/Azure/azure-cli/issues/23895
{Compute} Bump up `snapshots` API version to `2022-03-02`
---
> {Compute} Bump up `snapshots` API version to `2022-03-02`

- src/azure-cli/azure/cli/command_modules/netappfiles/_help.py
- src/azure-cli/azure/cli/command_modules/netappfiles/_params.py
- src/azure-cli/azure/cli/command_modules/netappfiles/custom.py
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_export_policy.yaml
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/test_volume_commands.py
`az netappfiles volume create`: Fix `--has-root-access` Boolean parameter
`az netappfiles volume export-policy add`: Fix `--has-root-access` Boolean parameter
A parameter named `--has-root-access` was not declared correctly. Now is has been declared as a Boolean and works correctly.
---
> {NetAppFiles} Fix `has-root-access` parameter for create volume and export-policy add

- src/azure-cli/azure/cli/command_modules/vm/_help.py
- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_restore_point.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
`az restore-point create`
az restore-point create to support consistencyMode parameter https://github.com/Azure/azure-cli/issues/23785
[Compute] `az restore-point create`: Add new parameters `--consistency-mode` to support setting consistency mode
---
> [Compute] `az restore-point create`: Add new parameters `--consistency-mode` to support setting consistency mode

- src/azure-cli-core/azure/cli/core/aaz/_field_value.py
- src/azure-cli-core/azure/cli/core/tests/test_aaz_field.py
> [Core] `aaz`: Fix two AAZObjects or AAZDicts comparison

- .github/CODEOWNERS
> {CodeOwner} Add Compute and Resource owner

- .github/fabricbot.json
> {CI} Update milestone from Sep 2022 (2022-10-12) - For Ignite to Oct 2022 (2022-11-01)

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_deploy_zip.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_list_deployment_logs.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_show_deployment_logs.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands_thru_mock.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
- src/azure-cli/azure/cli/command_modules/appservice/utils.py
az webapp up
az webapp deployment source config-zip
Reverts #23464 due to a bug in the deployment status API causing https://github.com/Azure/azure-cli/issues/23925. 
[App Service] `az webapp up`: No longer show status during linux deployments
[App Service] `az webapp deployment source config-zip`: No longer show status during linux deployments
---
> [App Service] Fix #23925: `az webapp deployment source config-zip`: No longer show status during linux deployments

- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/logicapp/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_asp_ws1_create.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_asp_ws2_create.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_asp_ws3_create.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_autocreate_asp_for_logicapp.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_logicapp_config_appsettings_e2e.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_logicapp_e2e.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_logicapp_https_only.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_logicapp_on_linux.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_logicapp_scale_e2e.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_logicapp_update.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_logicapp_windows.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_update_asp_to_logicapp_sku_fails.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_update_logicapp_asp_sku.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_logicapp_commands.py
> {App Service} Remove the to be deprecated parameters from logicapp create command

- src/azure-cli/azure/cli/command_modules/synapse/manual/operations/workspace.py
Fix az synapse workspace update --sql-admin-login-password bug
This bug is from an icm https://portal.microsofticm.com/imp/v3/incidents/details/337894289/home
---
> {Synapse} `az synapse workspace update`: Fix parameter `--sql-admin-login-password` bug

- src/azure-cli/azure/cli/command_modules/eventgrid/_help.py
fixes Azure/azure-cli#24085
The page has a sentence that says Create a new event subscription for an Azure subscription subscription, using default filters. This PR fixes this description.
---
> {AzureEventGrid} fixes Azure/azure-cli#24085

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
> {AKS} Remove deprecated parameter `--enable-soft-delete` from test case

- src/azure-cli/azure/cli/command_modules/network/commands.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic_ag_address_pools.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic_app_gateway.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
az network vnet create/update
az network vnet subnet create
---
> [Network] BREAKING CHANGE: `az network vnet`: Deprecate parameter `--defer`

- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_with_nat_rule_v2.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Fix the bug that the `--nat-pool-name` parameter does not work for Standard LB SKU
Related PR: #23638
---
> {Compute} `az vmss create`: Fix the bug that the `--nat-pool-name` parameter does not work for Standard LB SKU

- linter_exclusions.yml
- src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py
- src/azure-cli/azure/cli/command_modules/rdbms/_params.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_commands.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_common.py
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/migrationPublic.json
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/migrationVNet.json
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_migration.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands_postgres_migration.py
Added **--offline** and **--online** flags to az postgres flexible-server migration create
Changed az postgres flexible-server migration update --cutover to az postgres flexible-server migration update --cutover **db1 db2 db3**
Added az postgres flexible-server migration update --cancel db1 db2 db3
Removed az postgres flexible-server migration delete 
This PR is a breaking change to how Migrations from Sterling to Meru Platforms is done in Postgres.
This changes the backend tool to shift to FMS(Flexible Migration service).
Added new offline and online modes to create migration with.
Added Cancel and cutover functionality for some/all databases involved in the migration.
Removed the Delete migration activity command and test cases. …
> [RDBMS] BREAKING CHANGE: `az postgres flexible-server migration`: Move to new backend migration tool and add new Commands

- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_security_partner_provider.yaml
```
FAILED src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py::NetworkSecurityPartnerProviderScenarioTest::test_network_security_partner_provider
```
---
> {CI} Fix failure `test_network_security_partner_provider`

- src/azure-cli-core/azure/cli/core/commands/parameters.py
- src/azure-cli/azure/cli/command_modules/vm/_params.py
`az disk create`
`az snapshot create`
`az image create`
`az vm image list`
`az vm image list-offers`
`az vm image list-skus`
`az vm image list-publishers`
`az vm image show`
`az vm create`
Remove Preview Warning for EdgeZone cmds 
close https://github.com/Azure/azure-cli/issues/23904
{Compute} Remove preview warning for `--edge-zone` 
---
> {Compute} Remove preview warning for `--edge-zone` 

- src/azure-cli/azure/cli/command_modules/network/_params.py
Resolves: https://github.com/Azure/azure-cli/issues/23904
---
> {Network} Remove preview warning for `--edge-zone`

- src/azure-cli-core/azure/cli/core/aaz/__init__.py
- src/azure-cli-core/azure/cli/core/aaz/_arg.py
- src/azure-cli-core/azure/cli/core/aaz/_arg_action.py
- src/azure-cli-core/azure/cli/core/aaz/_arg_browser.py
- src/azure-cli-core/azure/cli/core/aaz/_arg_fmt.py
- src/azure-cli-core/azure/cli/core/aaz/_content_builder.py
- src/azure-cli-core/azure/cli/core/aaz/_field_type.py
- src/azure-cli-core/azure/cli/core/aaz/_field_value.py
- src/azure-cli-core/azure/cli/core/aaz/_help.py
- src/azure-cli-core/azure/cli/core/aaz/_operation.py
- src/azure-cli-core/azure/cli/core/tests/test_aaz_arg.py
- src/azure-cli-core/azure/cli/core/tests/test_aaz_arg_fmt.py
- src/azure-cli-core/azure/cli/core/tests/test_aaz_content_builder.py
- src/azure-cli-core/azure/cli/core/tests/test_aaz_field.py
> [Core] `aaz`: Support Featur FreeFormDictType and FreeFormDictArg

- build_scripts/windows/scripts/build.cmd
- scripts/release/debian/Dockerfile
- scripts/release/debian/build.sh
Use Python 3.10.8 in DEB and MSI
---
> {Packaging} Bump Python version to 3.10.8

- src/azure-cli/azure/cli/command_modules/keyvault/_client_factory.py
`az keyvault key rotate/rotation-policy`
GA key rotation feature for Managed HSM
---
> {Keyvault} GA key rotation for MHSM

- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
- az aks list
- az aks nodepool list
Bump SDK version to fix issue [#24188](https://github.com/Azure/azure-cli/issues/24188).
The SDK generated by autorest.python has some problems with pagination handling. Now the generator has been fixed by [#1486](https://github.com/Azure/autorest.python/pull/1486), [#1504](https://github.com/Azure/autorest.python/pull/1504). And the fixes are applied to latest SDK [20.5.0](https://pypi.org/project/azure-mgmt-containerservice/20.5.0/).
[AKS] Fix #24188 `az aks list`: Fix pagination handling error `ContainerServiceClientConfiguration object has no attribute api_version` when there are many list results
[AKS] Fix #24188 `az aks nodepool list`: Fix pagination handling error …
> [AKS] Bump SDK version to fix the SDK issue for pagination handling error 

- src/azure-cli/azure/cli/command_modules/resource/commands.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_tag_incrementally.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
`az resource delete`
Support `--no-wait` on `az resource delete`
close https://github.com/Azure/azure-cli/issues/19487
[Resource] `az resource delete`: Add new parameters `--no-wait` to support not waiting the long-running operation to finish
---
> [Resource] `az resource delete`: Add new parameter `--no-wait` to support not waiting the long-running operation to finish
