Azure/azure-cli

src/azure-cli-testsdk/azure/cli/testsdk/preparers.py
Add `subscription` to allow users to customize subscription for resource group
---
=> {test} Add subscription to resource group preparer

src/azure-cli/azure/cli/command_modules/acs/custom.py
Currently the `az aks install-cli` does not work on M1 Macs (`darwin/arm64`) due to the fact that the wrong release of `kubelogin` is being used. I have recently merged [this PR](https://github.com/Azure/kubelogin/pull/64) which adds `arm64` builds for `kubelogin`. The change here  adds a check to make sure the right arch is used on the Darwin platform.
`az aks install-cli` on an M1 Mac.
Fixes #18993
---
=> [AKS] `az aks install-cli`: Add support for kubelogin darwin/arm64 releases

src/azure-cli/azure/cli/command_modules/acs/custom.py
Bug Fix. Fix incorrectly passed parameter in function "_ensure_cluster_identity_permission_on_kubelet_identity", which affects the use of custom kubelet identity. The cause of the error is the function signature change introduced by PR[#18443](https://github.com/Azure/azure-cli/pull/18443).
---
=> [AKS] Fix incorrectly passed parameter for option `--assign-kubelet-identity` in aks create sub-command

scripts/release/pypi/build.sh
`az self-test` in CI fails with
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1008867&view=logs&jobId=b46c874b-707d-54de-7733-46667ab6d730&j=b46c874b-707d-54de-7733-46667ab6d730&t=e06b2869-1ba8-5188-52df-72c2650a8e19
```
File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 66, in get_op_handler
raise ValueError("The operation '{}' is invalid.".format(op_path))
ValueError: The operation 'azure.mgmt.redis.operations#FirewallRulesOperations.list_by_redis_resource' is invalid.
```
The bug is triggered by below logic:
1. The commit is submitted to main Azure CLI repo on branch [`vkukke/bugfix`](https://github.com/Azure/azure-cli/tree/vkukke/bugfix)
2. -> `BuildPythonWheel` doesn't build the wheel with version `postxxx`
3. -> …
=> {CI} Add `post` to wheel versions except for `release` branch

src/azure-cli-core/azure/cli/core/util.py
Due to the renaming of `master` to `main`, `master` branch is no longer maintained.
`az upgrade` should fetch the version from `main` branch instead.
=> {Upgrade} Retrieve latest version from `main` branch

azure-pipelines.yml
Finish the work of #18224:
1. Use the latest macOS on ADO
2. Use Python 3.9 to generate the formula
=> [Packaging] Use Python 3.9 in Homebrew formula

.gitignore, src/azure-cli/azure/cli/command_modules/synapse/_client_factory.py, src/azure-cli/azure/cli/command_modules/synapse/_help.py, src/azure-cli/azure/cli/command_modules/synapse/_params.py, src/azure-cli/azure/cli/command_modules/synapse/commands.py, src/azure-cli/azure/cli/command_modules/synapse/operations/managedprivateendpoints.py, src/azure-cli/azure/cli/command_modules/synapse/tests/latest/recordings/test_managed_private_endpoints.yaml, src/azure-cli/azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py, src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt, src/azure-cli/setup.py
Add synapse managed private endpoints commands. Included create, show, list and delete managed-private-endpoints.
Add azure-synapse-managedprivateendpoints =0.3.0
[Synapse] az synapse: Add managed private endpoints feature.
---
=> [Synapse] az synapse: Add for managed private endpoints commands

src/azure-cli-core/azure/cli/core/auth/__init__.py
CI fails with 
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1058229&view=logs&j=c846b3e8-69b8-5dbd-1a39-4905d81e6a95&t=9ebb608a-8a51-5834-bad0-46e2c03d2282&l=4756
```
________________ ERROR collecting tests/latest/test_auth_e2e.py ________________
ImportError while importing test module '/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/tests/latest/test_auth_e2e.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/az/lib/python3.6/importlib/__init__.py:126: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/tests/latest/test_auth_e2e.py:8: in <module>
from azure.cli.core.auth.util import …
```
=> {Core} Add `__init__.py` to `azure.cli.core.auth`

Dockerfile, scripts/release/docker/pipeline.sh
Fix #19281
`python:3.9.6-alpine3.14` has 2 CVEs:
```
+-----------+------------------+----------+-------------------+---------------+---------------------------------------+
|  LIBRARY  | VULNERABILITY ID | SEVERITY | INSTALLED VERSION | FIXED VERSION |                 TITLE                 |
+-----------+------------------+----------+-------------------+---------------+---------------------------------------+
| apk-tools | CVE-2021-36159   | CRITICAL | 2.12.5-r0         | 2.12.6-r0     | libfetch before 2021-07-26, as        |
|           |                  |          |                   |               | used in apk-tools, xbps, and          |
|           |                  |          |                   |               | other products, mishandles...         |
|           | …
```
=> {Packaging} Use `python:3.9.6-alpine3.14` as base image

src/azure-cli/azure/cli/command_modules/resource/_packing_engine.py, src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_create_template_specs_with_artifacts.yaml, src/azure-cli/azure/cli/command_modules/resource/tests/latest/template_spec_with_artifacts.json
This PR addresses template spec issue https://github.com/Azure/template-specs/issues/49  - where creating a template spec version that contains at least two inner deployments that each depend on a common template (referenced via a relative path) results in the error "TemplateSpecVersionInvalidArtifactPath: The artifact path 'Microsoft.Resources/deploymentScripts.json' is not supported. An artifact path should be unique and not contain any expressions."
Executing the following command using a template with inner deployments referencing a common template as shown succeed. (For a template please see the file _src/azure-cli/azure/cli/command_modules/resource/tests/latest/template_spec_with_artifacts.json_ included in this PR) 
`az ts create --name …
=> [ARM] `az ts create`: Fix issue where creating a template spec with inner deployments that reference a common template fails

src/azure-cli/azure/cli/command_modules/storage/_validators.py, src/azure-cli/azure/cli/command_modules/storage/tests/latest/quick_query.json, src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_blob_live_scenarios.py
Previously, `az storage blob query` will fail with `--input-format json` like this:
```
> az storage blob query -c yscontainer -n test_blob_query.json  --query-expression "SELECT latitude FROM BlobStorage[*].warehouses[*]" --account-name yssa --input-format json --debug
......
cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
File "d:\workspace\azure-cli\src\azure-cli-core\azure\cli\core\profiles\_shared.py", line 579, in _get_attr
op = getattr(op, part)
AttributeError: module 'azure.multiapi.storagev2.blob.v2020_04_08._models' has no attribute 'DelimitedJson'
cli.azure.cli.core.azclierror: 'NoneType' object is not callable
```
Here is to fix import error.
---
=> {Storage} `az storage blob query`: Fix import error when `--input-format json`

src/azure-cli-core/azure/cli/core/util.py
In WSL, when running `az feedback`, CLI calls `open_page_in_browser` to launch a web browser. The shell gets corrupted:
Pressing <kbd>ENTER</kbd> doesn't make a line break, and any typed text is not echoed back.
If `python` exits before the subprocess `powershell.exe` exits, this can corrupt the WSL shell (https://github.com/microsoft/WSL/issues/7367). 
Call `wait` on `subprocess.Popen` so that CLI blocks until `powershell.exe` exits.
This issue doesn't happen in `az login` even though `az login` also calls `open_page_in_browser`. This is because `az login` waits for the auth code after launching `powershell.exe`, giving `powershell.exe` enough time to exit.
=> {Core} Fix: `open_page_in_browser` corrupts WSL shell

src/azure-cli-core/azure/cli/core/extension/operations.py, src/azure-cli-core/azure/cli/core/util.py, src/azure-cli/azure/cli/command_modules/util/custom.py
Fix #19171, #18566
Directly installing from URL may be blocked by policy: https://github.com/Azure/azure-cli/issues/19171. The exact reason for the failure is unclear, and installing MSI from a URL is always problematic.
Download MSI to a temp folder and install it with `msiexec.exe`. This also gives the user a chance to manually install the MSI in case of `msiexec.exe` failure.
In `upgrade_version`, after retrieving the `installer`:
https://github.com/Azure/azure-cli/blob/c100b8026cdb4261b773c44cb0551285734aac84/src/azure-cli/azure/cli/command_modules/util/custom.py#L62
force
```py
local_version = '2.26.0'
installer = 'MSI'
```
so that `_upgrade_on_windows` can be triggered.
=> {Upgrade} Download MSI to a local file first

src/azure-cli-core/azure/cli/core/style.py, src/azure-cli-core/azure/cli/core/tests/test_style.py, src/azure-cli-core/azure/cli/core/util.py
Fix #19193
When parent or grandparent process path is too long, `psutil` used by Azure CLI fails:
```
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 223, in invoke
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/init.py", line 132, in show_version
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/style.py", line 131, in print_styled_text
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/style.py", line 131, in
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/style.py", line 158, in format_styled_text
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli …
```
=> {Core} Ignore `psutil.AccessDenied` in `_get_parent_proc_name`

src/azure-cli-core/azure/cli/core/util.py
Fix an edge-case bug introduced by #17445
`az functionapp create` fails with `AttributeError: 'NoneType' object has no attribute 'lower'`
The user runs `az functionapp create` in a container but it fails with:
```
cli.azure.cli.core.util: Traceback (most recent call last):
File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 506, in shell_safe_json_parse
return json.loads(json_or_dict_string, strict=strict)
File "/usr/local/python/python3.9/lib/python3.9/json/__init__.py", line 359, in loads
return cls(**kw).decode(s)
File "/usr/local/python/python3.9/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/python/python3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise …
```
=> {Core} Check return value of `get_parent_proc_name`

azure-pipelines.yml
Fix #19313, #18703, #18493, #19235, #18714, #18420, #18356, #17713, #16875, #18542
If a user manually add Azure CLI software repository from Microsoft Linux repo following https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-2-step-by-step-installation-instructions, `/etc/apt/sources.list.d/azure-cli.list` will contain 
```
deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ hirsute main
```
As https://packages.microsoft.com/repos/azure-cli/dists/ doesn't have `hirsure`, `apt update` will fail
```
E: The repository 'https://packages.microsoft.com/repos/azure-cli hirsute Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```
Then when `apt install azure-cli` is …
=> [Packaging] Add Ubuntu 21.04 Hirsute Hippo support

azure-pipelines.yml
Fix #19326, #18654, and possibly #18895, #18804, #18798, #16783
Debian releases and their life cycle can be found at
- https://www.debian.org/releases/
- https://wiki.debian.org/DebianReleases
Similar to https://github.com/Azure/azure-cli/pull/19367, we need to support Debian 11 Bullseye, otherwise the buggy unofficial Azure CLI from https://packages.debian.org/bullseye/azure-cli will be installed.
=> [Packaging] Add Debian 11 Bullseye support 

src/azure-cli/azure/cli/command_modules/acs/decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
* Adjust the input of the default test case in the unit tests to the default value corresponding to the parameter in function aks_create.
* Add docstring for all getter functions.
* Break down get_enable_managed_identity_service_principal_and_client_secret into get_service_principal_and_client_secret  and get_enable_managed_identity.
* Remove all parameter intermediates and introduce an additional "read_only" option to bypass dynamic completion and validation to avoid circulation function calls.
--- …
=> {AKS} Refactor a clean-up part of the create sub-command in acs module

src/azure-cli/azure/cli/command_modules/feedback/custom.py, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/setup.py
`platform.platform()` has some limitations:
- doesn't have the distribution information
- can be the same for different distributions (Ubuntu, Fedora, etc on docker):
```
platform.platform()
'Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.33'
```
To better help us identify packaging problem, the distribution name and version are also shown.
Note: Ubuntu doesn't follow the `PRETTY_NAME = NAME + VERSION` convention:
```
> docker run -it --rm ubuntu cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
```
So on Ubuntu, the code name is missing from `distro.name(pretty=True)`:
```
Ubuntu 20.04.2 LTS
```
Debian does:
```
> docker run -it --rm debian cat /etc/os-release
PRETTY_NAME="Debian …
```
=> {Feedback} `az feedback`: Add distro name and version

src/azure-cli/azure/cli/command_modules/appservice/_help.py, src/azure-cli/azure/cli/command_modules/appservice/_params.py, src/azure-cli/azure/cli/command_modules/appservice/_validators.py, src/azure-cli/azure/cli/command_modules/appservice/commands.py, src/azure-cli/azure/cli/command_modules/appservice/static_sites.py, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_staticapp_commands_thru_mock.py
Fix #16470: add commands to manage deployment secrets
`az staticwebapp secrets list -n {name} -g {resource_group}` to list deployment secrets.
`az staticwebapp secrets reset-api-key -n {name} -g {resource_group}` to reset api key.
---
=> [App Service]: Fix #16470: `az staticwebapp secrets`: Add commands to manage deployment secrets

src/azure-cli/azure/cli/command_modules/appservice/_params.py, src/azure-cli/azure/cli/command_modules/appservice/custom.py
Allows the user to deploy to a (pre-existing) App Service Environment with `az webapp up` through a `--app-service-environment`/`-e` parameter 
```
az webapp up --name <name> -g <group> --app-service-environment <ase_name> --sku I1V2 --plan <plan_name>
```
---
=> [App Service] `az webapp up`: Add support for deploying to an App Service Environment

src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
There is a CI pipeline failed to run due to the lack of generating ssh keys in the test `test_aks_create_with_ossku` and the absence of `~/.ssh` file in the CI pipeline.
Pipeline link: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1080310&view=logs&jobId=ad51cf76-b294-5bde-777e-be77cc5f3050&j=ad51cf76-b294-5bde-777e-be77cc5f3050&t=0e02ab23-4098-514d-f7b9-ab422251bbb2
Error:
> raise CLIError('An RSA key file or key value must be supplied to SSH Key Value. 'You can use --generate-ssh-keys to let CLI generate one for you')
knack.util.CLIError: An RSA key file or key value must be supplied to SSH Key Value. You can use --generate-ssh-keys to let CLI generate one for you
So I skip this test at first
@hbeberman  Therefore, please add the logic of generating ssh …
=> {AKS} Skip test_aks_nodepool_add_with_ossku

src/azure-cli/azure/cli/command_modules/resource/custom.py
Recently, I received an ICM which feed back that the operation of ARM deployment will print the request body after passing in parameter `--verbose`, which may lead to the disclosure of the value for confidential parameters.
Therefore, I submit this PR to fix the issue that it will print the request body in verbose log.
Before
After
---
=> [ARM] `az deployment`: Remove the log of printing request body from custom policy

scripts/release/debian/verify_debian_in_docker.sh
CI task [Verify Debian Package](https://dev.azure.com/azure-sdk/internal/_releaseDefinition?definitionId=79&_a=definition-tasks&environmentId=193) relies on 
- https://raw.githubusercontent.com/fengzhou-msft/azure-cli/release_scripts/scripts/release/debian/verify_debian_in_docker.sh
- i.e. https://github.com/fengzhou-msft/azure-cli/blob/release_scripts/scripts/release/debian/verify_debian_in_docker.sh
This PR moves this script to upstream repo.
=> {CI} Move verify_debian_in_docker.sh to upstream repo

src/azure-cli/azure/cli/command_modules/network/_help.py, src/azure-cli/azure/cli/command_modules/network/commands.py
Add wait command for `network custom-ip prefix`, `network vnet-gateway nat-rule`, `network vnet-gateway packet-capture`, `network vnet-gateway vpn-client ipsec-policy`, `network vpn-connection packet-capture`
---
=> [Network] add wait for network subcommands

NOTICE.txt, src/azure-cli/azure/cli/command_modules/resource/_json_handler.py, src/azure-cli/azure/cli/command_modules/resource/_packing_engine.py, src/azure-cli/azure/cli/command_modules/resource/custom.py, src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt, src/azure-cli/setup.py
Issue: #19468
In order to solve the package conflict introduced by `jsmin`, the `jsmin` code is referenced into `json_min()`
---
=> [ARM] Fix #19468: `pip` installs `azure-cli` 2.0.73 because of the dependency on deprecated `jsmin`

src/azure-cli/azure/cli/command_modules/storage/__init__.py, src/azure-cli/azure/cli/command_modules/storage/_params.py, src/azure-cli/azure/cli/command_modules/storage/_params_azure_stack.py
Fix #19279
`File system name` in help has been changed to File system name (i.e. container name). 
---
=> [Storage] Fix #19279: Add clarification for file system name to also mean container name.

src/azure-cli/azure/cli/command_modules/monitor/_help.py
The `logs` parameter to the create subscription sample contains JSON where the last property in each of the objects has a trailing comma. Removing them.
Cosmetic change 
n/a
n/a
---
Since this is a cosmetic change to the command parameters the above checks do not apply
=> {monitor} `monitor diagnostic-settings subscription create`: JSON should not have a trailing comma after last element

src/azure-cli/azure/cli/command_modules/resource/_help.py
This PR fixes a misleading example from the `az deployment group create` command, see https://github.com/Azure/bicep/issues/4395 for context.
N/A
---
=> [ARM] `az deployment group create`: Fix incorrect scope in the example of creating deployment from template-spec

src/azure-cli/azure/cli/command_modules/keyvault/custom.py
Customers are not aware that deleted managed HSM still incur billing before getting purged, either manually or at the end of the retention period. Add a warning when deleting managed HSM. 
Create a managed HSM
`az keyvault create -g {resource-group-name} --hsm-name {hsm-name} --administrators {oid-of-the-administrator}`
Delete a managed HSM, should see a warning. 
`az keyvault delete --hsm-name {hsm-name}`
---
=> [Keyvault] `az keyvault delete --hsm-name`: Add warning when deleting managed HSM

src/azure-cli/azure/cli/command_modules/backup/_params.py, src/azure-cli/azure/cli/command_modules/backup/custom.py, src/azure-cli/azure/cli/command_modules/backup/custom_help.py, src/azure-cli/azure/cli/command_modules/backup/custom_wl.py
- Fixed the refresh protectable container API call that happens when the protectable container is not found on the first try in az backup container register command. CRI link - [Incident 259315847 : [ARR] [SAP],[DISCOVERY], | [KRKEMA] | [Unable to discovery SAP Hana DB from Azure VM "xub29041431h0" using Azure CLI via ADO pipeline. Getting error message: Container unavailable or already registered.]](https://portal.microsofticm.com/imp/v3/incidents/details/259315847/home)
- Added 'MAB' in the allowed values for backup management type in az backup job/container list command
- Increased the sleep delay while tracking operations to prevent frequent calls.
[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking …
=> [Backup] `az backup container register`: Fix refresh container bug

src/azure-cli-core/setup.py
`azure-common` was introduced when vendoring `azure-mgmt-resource` Track 2 SDK (https://github.com/Azure/azure-cli/pull/15711). It should have been dropped by https://github.com/Azure/azure-cli/pull/18047 but was unintentionally overlooked.
[`azure-common`](https://github.com/Azure/azure-sdk-for-python/tree/azure-common_1.1.27/sdk/core/azure-common) is an interface to create SDK clients with Azure CLI credential. Azure CLI doesn't use it in any way. `azure-common` has now been deprecated.
Leaving it in `azure-cli-core` causes confusion and encourages incorrect usages: https://github.com/Azure/azure-cli/issues/19528
=> {Core} Drop `azure-common` from `azure-cli-core`

src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_common.py
1. In Create migration command, changed the way to read the json file in order to retain double quotes in the json structure. Current code in dev branch is breaking the create migration command.
---
=> {RDBMS}: Fix file read issue to retain double quotes in Properties File

src/azure-cli/azure/cli/command_modules/acs/custom.py
In my local environment, we leverage KUBECONFIG to specify a variety of configuration files. The KUBECONFIG env var is permitted to be colon separated [kubernetes.io reference material](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/)
Definitely on Mac, and presumably on linux ( perhaps Win as well?) the current az cli doesn't comprehend when KUBECONFIG env var is set, and has a colon separated designation. This is the most simple remediation I could think of, no worries if this doesn't meet your expectations for the repo. 
I didn't see any tests related to checking on the kubeconfig file if it came out of the environment, or twiddling of the environment in the test suite.  So noting, I didn't modify the …
=> {ACS} KUBECONFIG env var is allowed to have several paths separated by colons

src/azure-cli/azure/cli/command_modules/appservice/_help.py, src/azure-cli/azure/cli/command_modules/appservice/commands.py, src/azure-cli/azure/cli/command_modules/appservice/static_sites.py, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_staticapp_commands_thru_mock.py
Add command to delete azure static webapp environment.
Related issue: #19514
Example:
```
az staticwebapp environment delete --name swa-name --env environment-name
```
---
=> [App Service] `az staticwebapp environment delete`: Add command to support deleting static app environment

src/azure-cli/azure/cli/command_modules/storage/_params.py, src/azure-cli/azure/cli/command_modules/storage/operations/account.py, src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_create_storage_account_with_public_network_access.yaml, src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_update_storage_account_with_public_network_access.yaml, src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
Add --public-network-access parameter to `az storage account create` and `az storage account update`. The allowed values are  'Enabled' and 'Disabled'
Currently only euap regions have --public-network-access parameter enabled. 
`az storage account create -g {resource group name} -n {storage account name} --public-network-access Enabled`
The created storage account should have the publicNetworkAccess property set to "Enabled"
`az storage account update -g {resource group name} -n {storage account name} --public-network-access Disabled`
The storage account should now have the publicNetworkAccess property update to "Disabled"
---
=> [Storage] `az storage account create/update`: Add --public-network-access parameter

src/azure-cli-core/setup.py
- Fix #19635
Reasons why we can loose the `cryptography` dependency now:
https://github.com/Azure/azure-cli/pull/15687#discussion_r578898876 set an upper bound for `cryptography` due to https://github.com/pyca/cryptography/issues/5771.
By following https://cryptography.io/en/latest/installation/#alpine, I am now able to install `cryptography` 3.4.8 on Alpine Linux (https://github.com/Azure/azure-cli/issues/19591). There is no need to set upper bound now.
Community packagers ask us not to bump the minimum dependency in `setup.py` as this causes trouble for platforms that doesn't support newer versions of `cryptography` (https://github.com/Azure/azure-cli/pull/15687#issuecomment-878819248). By loosing the dependency on `cryptography`, users or packagers themselves are now responsible for …
=> {Packaging} Loosen `cryptography` dependency

src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt, src/azure-cli/setup.py
Derived from https://github.com/Azure/azure-cli/pull/19963
`pytz` was first introduced by 5afb8bd9536d5789a12647d090dc1cfe11dec6a2 related to `keyvault` module, but the reason for it is unknown.
By searching the whole project, we found no place where `pytz` is referenced: https://github.com/Azure/azure-cli/search?q=pytz
Therefore, `pytz` should be dropped from the dependencies.
=> {Packaging} Drop pytz

src/azure-cli/azure/cli/command_modules/acs/decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
* Fix typo
* Use `inspect` to get the parameters of the entry function (`aks_create`) for testing
- "covered_lines": 1579,
- "num_statements": 1591,
- "percent_covered": 99.24575738529226,
- "missing_lines": 12,
Parameter usage statistics (default):
- location 1
- resource_group_name 2
- tags 1
- dns_name_prefix 1
- fqdn_subdomain 3
- name 1
- kubernetes_version 3
- disable_rbac 1
- node_osdisk_diskencryptionset_id 1
- disable_local_accounts 1
- node_count 1
- enable_cluster_autoscaler 1
- min_count 1
- max_count 1
- nodepool_name 1
- nodepool_tags 1
- nodepool_labels 1
- node_vm_size 1
- os_sku 1
- vnet_subnet_id 3
- ppg 1
- zones 1
- enable_node_public_ip 1
- node_public_ip_prefix_id 1
- enable_encryption_at_host 1
- …
=> {AKS} Refine test for `aks create` in decorator pattern

src/azure-cli/azure/cli/command_modules/serviceconnector/_addon_factory.py, src/azure-cli/azure/cli/command_modules/serviceconnector/_transformers.py, src/azure-cli/azure/cli/command_modules/serviceconnector/_validators.py
This PR fixes the issue when users use `-o table` as default output.
---
=> {ServiceConnector} Fix issue when users use `-o table` as default output

azure-pipelines.yml, build_scripts/windows/scripts/build.cmd
As `vs2017-win2016` will be deprecated pretty soon:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1172519&view=results
CI pipeline needs to be updated to use newer versions.
Also see: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software
=> {CI} Use `windows-2019` image in CI pipeline

src/azure-cli-testsdk/HISTORY.rst, src/azure-cli-testsdk/setup.py
Even though we don't release `azure-cli-testsdk` on PyPI, it's better to bump its version to 0.3.0, as breaking change is introduced during https://github.com/Azure/azure-cli/pull/19853.
=> {testsdk} Bump `azure-cli-testsdk` to 0.3.0

scripts/release/pypi/build.sh
Pin `setuptools` to `58.4.0`.
`setuptools` `58.5.2` introduced an _unexpected_ breaking change, making all custom `build_py` subclasses to fail:
https://github.com/Azure/azure-cli/blob/1cf3072bb2e3af3db4f9b3dffc575c7e2c46efc9/src/azure-cli/azure_cli_bdist_wheel.py#L10-L20
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1178162&view=logs&jobId=e725b3e9-648f-510f-a0a1-f18bdc151d12&j=e725b3e9-648f-510f-a0a1-f18bdc151d12&t=7dda8e6e-5520-5cbf-e881-69c151aecb23
<details>
<summary>Full call stack</summary>
```
2021-11-04T03:23:41.8710919Z Traceback (most recent call last):
2021-11-04T03:23:41.8711856Z   File "/home/vsts/work/1/s/src/azure-cli/setup.py", line 160, in <module>
2021-11-04T03:23:41.8712337Z     setup(
2021-11-04T03:23:41.8713101Z   File …
```
=> {Packaging} Temporarily pin setuptools

pylintrc
New `pylint` is more strict. Temporarily disable these checks and we will fix them one by one in separate PRs, like #17861.
=> {Pylint} Adapt to Pylint 2.11.1

azure-pipelines-full-tests.yml, azure-pipelines.yml, src/azure-cli-core/azure/cli/core/_help.py, src/azure-cli-core/setup.py, src/azure-cli-telemetry/setup.py, src/azure-cli-testsdk/setup.py, src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt, src/azure-cli/setup.py
Close #19857
Similar to #17368
=> [Packaging] Support Python 3.10

scripts/release/pypi/build.sh, src/azure-cli/azure_cli_bdist_wheel.py, src/azure-cli/setup.cfg
https://github.com/Azure/azure-cli/pull/20194 pinned `setuptools` to temporarily workaround https://github.com/pypa/setuptools/issues/2849.
As `setuptools` has been fixed by https://github.com/pypa/setuptools/pull/2855, we can use its latest verision.
As indicated by 
https://docs.python.org/3/library/distutils.html
> distutils is deprecated
https://github.com/pypa/setuptools/pull/2855/files#diff-93769fd2dda9046fec77cc3efa634577aac30dd7dce9ef40c48783d1a54aef1fR624-R627
```
"Custom 'build_py' does not implement "
"'get_data_files_without_manifest'.\nPlease extend command classes"
" from setuptools instead of distutils."
```
we make `azure_cli_build_py` inherit from the new `setuptools.command.build_py.build_py`.
=> {Packaging} Adapt to latest setuptools

src/azure-cli-core/azure/cli/core/auth/adal_authentication.py, src/azure-cli-core/azure/cli/core/auth/tests/test_adal_authentication.py
- Close https://github.com/Azure/azure-cli/issues/19480
- Close https://github.com/Azure/azure-cli/issues/20196
- Close https://github.com/Azure/azure-cli/issues/20186
For more details, see https://github.com/Azure/azure-cli/issues/19480#issuecomment-961197625
`msrestazure` still uses `2017-09-01` for [managed identity in App Service container](https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=powershell#rest-protocol-examples). The returned `expires_on` is a datetime string like `"11/05/2021 15:18:31 +00:00"`. This differs from `expires_on` returned by [managed identity on Azure VM](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token):
- epoch in str (VM managed identity endpoint 2018-02-01): …
=> [Core] Support managed identity in App Service container

pylintrc, src/azure-cli/azure/cli/command_modules/appservice/custom.py, src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_afd_security_policy_scenarios.py, src/azure-cli/azure/cli/command_modules/dla/custom.py, src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/test_privatedns_commands.py, src/azure-cli/azure/cli/command_modules/security/actions.py, src/azure-cli/azure/cli/command_modules/storage/_validators.py, src/azure-cli/azure/cli/command_modules/storage/_validators_azure_stack.py
Part of https://github.com/Azure/azure-cli/pull/20192
Fix linter error `R1734`:
```
R1734: Consider using [] instead of list() (use-list-literal)
```
https://pylint.pycqa.org/en/latest/technical_reference/features.html#imports-checker-messages
> use-list-literal (R1734)
> Consider using [] instead of list() Emitted when using list() to create an empty list instead of the literal []. **The literal is faster as it avoids an additional function call.**
=> {Pylint} Fix `use-list-literal`

pylintrc, src/azure-cli-core/azure/cli/core/__init__.py, src/azure-cli-core/azure/cli/core/azclierror.py, src/azure-cli-core/azure/cli/core/command_recommender.py, src/azure-cli-core/azure/cli/core/commands/__init__.py, src/azure-cli-core/azure/cli/core/commands/arm.py, src/azure-cli-core/azure/cli/core/commands/client_factory.py, src/azure-cli-core/azure/cli/core/commands/transform.py, src/azure-cli-core/azure/cli/core/extension/dynamic_install.py, src/azure-cli-core/azure/cli/core/parser.py, src/azure-cli-core/azure/cli/core/telemetry.py, src/azure-cli-core/azure/cli/core/tests/test_telemetry.py, src/azure-cli-core/azure/cli/core/util.py, src/azure-cli/azure/cli/__main__.py, src/azure-cli/azure/cli/command_modules/acs/_validators.py, src/azure-cli/azure/cli/command_modules/backup/custom_base.py, src/azure-cli/azure/cli/command_modules/backup/custom_common.py, src/azure-cli/azure/cli/command_modules/backup/custom_wl.py, src/azure-cli/azure/cli/command_modules/batchai/custom.py, src/azure-cli/azure/cli/command_modules/config/custom.py, src/azure-cli/azure/cli/command_modules/util/custom.py, src/azure-cli/azure/cli/command_modules/vm/_validators.py
Part of https://github.com/Azure/azure-cli/pull/20192
Fix linter error `R0402`:
```
R0402: Use 'from azure.cli.core import telemetry' instead (consider-using-from-import)
```
https://pylint.pycqa.org/en/latest/technical_reference/features.html#imports-checker-messages
> consider-using-from-import (R0402)
> Use 'from %s import %s' instead Emitted when a submodule of a package is imported and aliased with the same name. E.g., instead of `import concurrent.futures as futures` use `from concurrent import futures`
=> {Pylint} Fix `consider-using-from-import`

azure-pipelines-full-tests.yml, azure-pipelines.yml
Python 3.9.8 introduced an unexpected breaking change (https://github.com/python/cpython/pull/28420) that breaks Azure CLI:
- https://github.com/Azure/azure-cli/issues/20269
According to https://bugs.python.org/issue45235, this change will be reverted on 3.9 and withdrawn from future releases for other version like 3.7, 3.8, 3.10.
Azure Pipeline now only has Python 3.9.8, but not old versions like 3.9.7:
- https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version
- https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#python
> #### Python
> - ...
> - 3.9.8
> - 3.10.0
Even if Python releases 3.9.9 which reverts this change, it will take Azure Pipeline weeks to take that version.
To unblock our development and PRs from being …
=> {CI} Use Python 3.10 as the default and disable Python 3.9 tests

src/azure-cli/azure/cli/command_modules/appservice/custom.py
Upon deploying a Function App through the CLI, when the user specifies incorrect parameters, instead of printing a helpful error message the CLI triggers a stack trace because of an AttributeError. This pull request fixes this error.
Deploy a new Function App as shown below.
```
$ az functionapp deployment source config-zip -g myresourcegroup -n myfunctionapp --src sourcecode.zip --build-remote true                                                                                                                   
Getting scm site credentials for zip deployment
'str' object has no attribute 'value'
File "/usr/lib/python3.8/site-packages/knack/cli.py", line …
```
=> [App Service] `az appservice` : Fix AttributeError during user error handling

src/azure-cli-core/azure/cli/core/auth/msal_authentication.py
Previously we thought `msal.application.ClientApplication.get_accounts` can't return multiple accounts because MSAL groups them (https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/349). That's why we added a double check:
https://github.com/Azure/azure-cli/blob/bd081bb9a4449091bfcce50e2b51292d8a1591d8/src/azure-cli-core/azure/cli/core/auth/msal_authentication.py#L46-L48
But now we do see this happening: https://github.com/Azure/azure-cli/issues/20172, https://github.com/Azure/azure-cli/issues/20168.
Even though the root cause is unknown, its better to expose more information in the error message.
=> {Auth} More detailed error message when MSAL returns multiple accounts 

src/azure-cli/azure/cli/command_modules/vm/custom.py
Also #15590. When the console contains non UTF-8 characters, we decode it as
ASCII and log a warning instead of throwing an exception and logging nothing.
Fixes ```az vm boot-diagnostics get-boot-log ``` crashing as reported
Have a VM log some garbage on the console then try reading the boot-diagnostics from the cli.
[Compute] Fix boot diagnostics decoding (#16454)
---
=> [Compute] `az vm boot-diagnostics get-boot-log`: Fix boot diagnostics decoding

src/azure-cli/azure/cli/command_modules/resource/_bicep.py
This pull request fixes issue #19420. 
The old code did not pass the path to the certificate file to request.get() and urlopen(), reulting in a SSL: CERTIFICATE_VERIFY_FAILED error.
On a clean developer pc behind a corporate proxy with a certificate signed by a private root CA, type on a pwsh prompt:
az bicep install
Result:
bicep will be installed
(without the fix, there would be a certificate error)
On a clean regular developer pc, do the same, type
az bicep install
bicep will be installed, just as before the fix.
[Bicep] az bicep install: works now behind a corporate proxy
=> [ARM] Fix #19420: `az bicep install`: Fix the CERTIFICATE_VERIFY_FAILED for generating SSL

src/azure-cli/azure/cli/command_modules/ams/operations/sp.py, src/azure-cli/azure/cli/command_modules/ams/tests/latest/recordings/test_ams_sp_create_reset.yaml, src/azure-cli/azure/cli/command_modules/ams/tests/latest/test_ams_sp_scenarios.py
=> [AMS] Removing deprecated variable 'identifier_uri' from create sp method

src/azure-cli-core/azure/cli/core/auth/identity.py, src/azure-cli-core/azure/cli/core/auth/persistence.py, src/azure-cli-core/azure/cli/core/auth/tests/test_identity.py, src/azure-cli-core/azure/cli/core/tests/test_profile.py, src/azure-cli-core/setup.py, src/azure-cli-testsdk/azure/cli/testsdk/patches.py, src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt
Incorporate MSAL HTTP cache introduced by https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/407, so that HTTP responses can be cached for
- Authority discovery, like https://login.microsoftonline.com/54826b22-38d6-4fb2-bad9-b7b93a3e9c5a/v2.0/.well-known/openid-configuration
- Error responses
This significantly improves MSAL performance in both normal "get access token" calls and AAD server outages..
=> [Core] Use MSAL HTTP cache

src/azure-cli/azure/cli/command_modules/profile/custom.py, src/azure-cli/azure/cli/command_modules/profile/tests/latest/test_profile_custom.py
After MSAL migration, we don’t actively delete ADAL token cache file `accessTokens.json` because we don’t want automations which rely on this file to be broken.
If `az logout` or `az account clear` is run explicitly, `accessTokens.json` will be deleted.
=> [Profile] `az logout`, `az account clear`: Remove ADAL token cache file `accessTokens.json`

src/azure-cli-core/azure/cli/core/commands/__init__.py
Using `--only-show-errors` on root parser fails:
```
> az --only-show-errors
the following arguments are required: _command_package
Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs
```
This PR fixes `--only-show-errors` on root parser, same as https://github.com/microsoft/knack/pull/253.
This issue was found while investigating https://github.com/Azure/azure-cli/issues/20269.
=> {Core} Fix `--only-show-errors` on root parser

src/azure-cli/azure/cli/command_modules/appservice/custom.py, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py, src/azure-cli/azure/cli/command_modules/appservice/tunnel.py, src/azure-cli/azure/cli/command_modules/appservice/utils.py
Add proxy support for `az webapp ssh`, `create-remote-connection`, `log download` and `log tail`. Setting the proxy works like elsewhere in azure cli, as documented here: https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#work-behind-a-proxy .
This fixes the issue in https://github.com/Azure/azure-cli/issues/11818 (which was seemingly closed by accident).
```bash
export HTTPS_PROXY=http://PROXY_HOST:PROXY_PORT
az webapp create-remote-connection --subscription MYSUBSCRIPTION --resource-group MYRESOURCEGROUP --name MYAPPSERVICE -p 39629
ssh root@localhost -p 39629
```
[App Service] `az webapp ssh`: Add proxy support
[App Service] `az webapp create-remote-connection`: Add proxy support
[App Service] `az webapp log …
=> [App Service] Fix #11818: `az webapp ssh`, `az webapp create-remote-connection`, `az webapp log download`, `az webapp log tail`: Add proxy support

src/azure-cli/azure/cli/command_modules/keyvault/_params.py
For commands that use the `--id` argument to identify the vault/HSM, the
vault/HSM's full URI, like `https://vault-name.vault.azure.net/`, needs
to be passed, not the resource's ARM ID, like
`/subscriptions/.../resourceGroups/.../providers/Microsoft.KeyVault/vaults/vault-name`.
Refine the argument help text to use "Full URI" instead of "Id" to try
to minimize confusion.
This only changes help text. No functionality should be affected.
Fixes https://github.com/Azure/azure-cli/issues/17399
---
- The existing commands are not following the "-id should be a GUID" guideline. I did not change that.
- Help text only change.
=> [Key Vault] az keyvault: Revise --id argument help text

src/azure-cli/azure/cli/command_modules/network/_help.py, src/azure-cli/azure/cli/command_modules/network/_params.py, src/azure-cli/azure/cli/command_modules/network/commands.py, src/azure-cli/azure/cli/command_modules/network/custom.py, src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_waf_policy_exclusion_rule_set.yaml, src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
> Closed https://github.com/Azure/azure-cli/issues/19734
Add new subgroup `rule-set` to support per rule exclusions in Application Gateway WAF.
```
$ az network application-gateway waf-policy managed-rule exclusion rule-set add -g {rg} --policy-name {waf} --match-variable RequestHeaderNames --selector-match-operator StartsWith --selector Bing --type OWASP --version 3.2 --group-name {rule_group} --rule-ids 921140 921150
```
---
=> [Network] `az network application-gateway waf-policy managed-rule exclusion`: Add new subgroup `rule-set` to support per rule exclusions

src/azure-cli-core/setup.py, src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt, src/azure-cli/setup.py
Fix #18499, #19682
Bump `requests` and `urllib3` and loosen dependencies in `setup.py`.
Being too strict on versions can frequently leads to endless backtracking in latest `pip` (#18324, #18518) . 
Now we don't want to be too specific on versions. Instead, the user should be responsible for security vulnerabilities in older versions of dependencies, same as https://github.com/Azure/azure-cli/pull/19639.
=> {Packaging} Bump `requests` and `urllib3` and loosen dependencies in `setup.py`

src/azure-cli/azure/cli/command_modules/network/_validators.py
> Closed https://github.com/Azure/azure-cli/issues/20289
Fix invalid validator when `--scale-units` is None.
```
$ az network bastion create --location {} --name {} --public-ip-address {} --resource-group {} --vnet-name {}
```
---
=> [Network] Fix #20289: `az network bastion create` invalid validator when `--scale-units` is None

scripts/ci/test_extensions.sh
CI fails with
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1204020&view=logs&jobId=dec4b9a0-9c0f-52f1-3e08-6456fce2bf62&j=dec4b9a0-9c0f-52f1-3e08-6456fce2bf62&t=98b838e2-1481-5123-a5d1-63f080201667
```
File "/opt/az/azcliextensions/arcdata/azext_arcdata/sqlmi/custom.py", line 15, in <module>
import azext_arcdata.core.kubernetes as kubernetes_util
File "/opt/az/azcliextensions/arcdata/azext_arcdata/core/kubernetes.py", line 15, in <module>
from kubernetes.client.exceptions import ApiException
ModuleNotFoundError: No module named 'kubernetes.client.exceptions'
```
In `scripts/ci/test_extensions.sh`, add a debug line
```
find /opt/az -name kubernetes
```
before
```
az self-test --debug
```
We can see the output to be
```
find /opt/az -name kubernetes …
```
=> {CI} Disable tests for extensions depending on different `kubernetes` versions

src/azure-cli/azure/cli/command_modules/acs/decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
Fix the issue that `--attach-acr` option would raise an error "No service principal provided to create the acrpull role assignment for acr." in `az aks create` when using managed identity or user assigned identity.
The code bug was introduced in [PR #19429](https://github.com/Azure/azure-cli/pull/19429) and [PR #19509](https://github.com/Azure/azure-cli/pull/19509). In the process of refactoring the implementation of `aks create`, we added an additional check when processing the option `--attach-acr` to verify whether service principal exists when managed identity is not enabled. However, when managed identity is enabled, we still check for the existence of service principal by mistake, which resulted in this error.
May refer the hotfix [PR …
=> [AKS] `az aks create`: Fix issue that `--attach-acr` parameter can't work

src/azure-cli-core/setup.py, src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt
The stale [`pyreadline`](https://pypi.org/project/pyreadline/) (last released at Sep 16, 2015) causes failure in PyCharm when using `pytest`:
```
File "C:\Program Files\JetBrains\PyCharm Community Edition 2021.2.3\plugins\python-ce\helpers\pycharm\_jb_pytest_runner.py", line 51, in <module>
sys.exit(pytest.main(args, plugins_to_load + [Plugin]))
File "D:\cli\py310\lib\site-packages\_pytest\config\__init__.py", line 143, in main
config = _prepareconfig(args, plugins)
...
File "D:\cli\py310\lib\site-packages\pyreadline\modes\basemode.py", line 162, in _bind_key
if not callable(func):
File "D:\cli\py310\lib\site-packages\pyreadline\py3k_compat.py", line 8, in callable
return isinstance(x, collections.Callable)
AttributeError: module …
```
=> {Packaging} Bump `humanfriendly` to 10.0

src/azure-cli-core/azure/cli/core/_profile.py, src/azure-cli-core/azure/cli/core/auth/identity.py
Rename option `token_encryption` to `encrypt_token_cache` per the internal discussion email:
- _Naming for the option to disable token encryption_
> While we do store Service Principal credentials, we call the location the **Token Cache** and this would also give an added benefit of an accurate description of what the config is doing. Encrypting the file and not just a token?
⚠ This option is still experimental and subject to change until it is announced at https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration
=> {Auth} Rename option `token_encryption` to `encrypt_token_cache`

src/azure-cli-core/azure/cli/core/_profile.py, src/azure-cli-core/azure/cli/core/tests/test_profile.py
- Fix #20402
After MSAL migration (https://github.com/Azure/azure-cli/pull/19853), `SubscriptionFinder` no longer maintains `user_id`, so `refresh_accounts` should use existing `user_id` instead of reading from `SubscriptionFinder`.
```PowerShell
$env:AZURE_CONFIG_DIR='D:\cli\azure2'
az login
az account list --refresh
```
- https://github.com/Azure/azure-cli/issues/20429
=> {Profile} `az account list`: Fix: `--refresh` returns `user` as `null`

src/azure-cli/azure/cli/command_modules/acs/addonconfiguration.py, src/azure-cli/azure/cli/command_modules/acs/custom.py, src/azure-cli/azure/cli/command_modules/acs/decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/hybrid_2020_09_01/test_custom.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_custom.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
- Not long ago, in aks-preview @tilnl-ms helped sorted out the internal operations required by some addons ([PR #3911](https://github.com/Azure/azure-cli-extensions/pull/3911)), and we are gradually synchronizing this part.
- This would also fix a bug in the preparation process of monitoring addon.
- This third PR focuses on replacing old implementations (in `custom.py`) and adjusting tests accordingly.
- Replace the role assignment helper functions for monitoring, ingress-appgw, virtual node addons.
- Replace log workspace and container insights preparation functions for the monitoring addon.
- Adjust unit tests for `latest` profile, `hybrid_2020_09_01` profile and decorator pattern.
- Sync the latest change -> [PR …
=> {AKS} Update addon preparation - part 3

src/azure-cli/azure/cli/command_modules/vm/_validators.py
Fix #20258 
When creating a snapshot with a vmss os disk, the disk doesn't really exist. But we shouldn't throw `ResourceNotFound` error. We skip autodetect `copy_start` in this situation.
```
az vmss create -g {} -n {} --image Centos
az vmss show -g {} -n {} --instance-id 1 --query storageProfile.osDisk.managedDisk.id
az snapshot create -g {} -n {} --source {vmssosdiskid}
```
---
=> [Compute] Fix #20258: `az snapshot create`: Fix creating a snapshot of a Uniform VMSS OS disk

src/azure-cli/azure/cli/command_modules/appservice/_help.py, src/azure-cli/azure/cli/command_modules/appservice/commands.py, src/azure-cli/azure/cli/command_modules/appservice/static_sites.py, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_staticapp_commands_thru_mock.py
Switches the `az staticwebapp appsettings set/list/delete` commands to use the new SWA app settings SDK methods instead of the function app settings APIs
Also fixes the issue described in https://github.com/Azure/azure-cli/issues/18468 where `az staticwebapp appsettings set` was not functional
`azdev test TestStaticAppCommands`
[App Service] `az staticwebapp appsettings set`: Make set functional (#18468)
[App Service] `az staticwebapp appsettings`: Switch to the new SWA app settings SDK methods
---
=> [App Service] Fix #18468: `az staticwebapp appsettings`: Make set functional

src/azure-cli/azure/cli/command_modules/acs/custom.py, src/azure-cli/azure/cli/command_modules/acs/decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
Two things:
1. For MSI clusters, when attaching ACR, the operation "resolving client ID to object ID" is not necessary. We can directly get the object ID from managed cluster properties. This PR removes this unnecessary operation.
2. Refines the error message when resolving object ID hits error.
---
=> {AKS} Avoid unnecessary graph API call and refine error message

azure-pipelines-full-tests.yml, azure-pipelines.yml
According to 
- https://github.com/actions/virtual-environments
- https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#python
Azure Pipelines' agents have taken Python 3.9.9. We should re-enable Python 3.9 tests disabled by 
- https://github.com/Azure/azure-cli/pull/20287.
=> {CI} Re-enable Python 3.9 tests

src/azure-cli/azure/cli/command_modules/role/custom.py
`az ad sp list` fails in **Azure Stack** environment:
```
> az ad sp list
Error occurred in request., RetryError: HTTPSConnectionPool(host='graph.redmond.azurestack.corp.microsoft.com', port=443): Max retries exceeded with url: /d48c9ef1-e46d-4148-b41e-ca95b463f5a8/servicePrincipals?$filter=&api-version=1.6 (Caused by ResponseError('too many 500 error responses'))
```
This is because `filter=` query string is set but its value is empty string `''`.
```py
>>> ' and '.join([])
''
```
Directly calling AD Graph API gives:
```
> az rest -m get -u '"https://graph.redmond.azurestack.corp.microsoft.com/d48c9ef1-e46d-4148-b41e-ca95b463f5a8/servicePrincipals?$filter=&api-version=1.6"' --verbose
Request URL: 'https://graph.redmond.azurestack.corp.microsoft.com/d48c9ef1-e46d-4148-b41e-ca95b463f5a8/ser …
```
=> {Graph} Only add `filter` query string when its value is non-empty

scripts/release/rpm/azure-cli.spec
See code comments.
- https://github.com/Azure/azure-cli/pull/17491
- https://github.com/Azure/azure-cli/pull/20061
=> {Packaging} Adapt entry script to Mariner

src/azure-cli-testsdk/azure/cli/testsdk/__init__.py, src/azure-cli-testsdk/azure/cli/testsdk/preparers.py
PR is for adding communication resource preparer which will be used in AZ communication CLI tests.
---
=> {test} Add communication resource preparer

src/azure-cli/azure/cli/command_modules/appconfig/_help.py, src/azure-cli/azure/cli/command_modules/appconfig/_kv_helpers.py
* Fixes [#12668922](https://msazure.visualstudio.com/Azure%20AppConfig/_workitems/edit/12668922/) Added validations to the command `az appconfig import` when `appconfig/kvset` profile is used and tags are not in string format.
* Fixes [#12668860](https://msazure.visualstudio.com/Azure%20AppConfig/_workitems/edit/12668860/) Handled cases where optional parameters were present in the import file for `az appconfig import` command and `appconfig/kvset` profile was used for import.
---
=> {App Config} Fix #12668860, #12668922: Fix validations while importing kvset

src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt
Though we have supported Python 3.10 (#20195), `cffi` 1.14.4 doesn't have a pre-built whl for Python 3.10: https://pypi.org/project/cffi/1.14.4/#files
On a machine without VC compiler, installing `cffi` 1.14.4 fails with:
```
> docker run -it --rm python:3.10.0-windowsservercore-1809 powershell
> pip install cffi==1.14.4
Collecting cffi==1.14.4
Downloading cffi-1.14.4.tar.gz (471 kB)
|████████████████████████████████| 471 kB 1.1 MB/s
ERROR: Command errored out with exit status 1:
command: 'C:\Python\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\pip-install-10ccxvh3\\cffi_ebc1e2aaf510
446a836a1cb7719ff09b\\setup.py'"'"'; __file__='"'"'C:\\Users\\ContainerAdministrator\\AppData\\Local\\Tem …
```
=> {Packaging} Bump cffi to 1.15.0

scripts/release/rpm/Dockerfile.mariner
Mariner distro `azure-cli` rpm build is showing issues and not building cleanly because of missing `binutils` and `file` packages:
- `strip` binary which is a part of `binutils` package
- `file` which is present in `file` package are used at `%__os_install_post` phase and required in Mariner image. 
Without them, CI for https://github.com/Azure/azure-cli/pull/20584 shows lots of failures:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1224670&view=logs&j=2d99a3ea-3a85-5049-e806-894016b5c578&t=51344c07-eaf5-5613-2089-f5e3d0d22243&l=732
```
+ /usr/lib/rpm/brp-strip-unneeded /bin/strip
find: 'file': No such file or directory
find: 'file': No such file or directory
find: 'file': No such file or directory
```
Adding required binutils and file packages for Mariner …
=> {Packaging} Fix Mariner docker file to build azure-cli rpm cleanly

azure-pipelines.yml, scripts/release/rpm/azure-cli.spec
After
- #20517
CI task **Build Rpm Package** fails when installing the built `azure-cli-dev.rpm`:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1227167&view=logs&jobId=eefb80ef-df2c-51d4-a735-8b3fa596bf12&j=eefb80ef-df2c-51d4-a735-8b3fa596bf12&t=6f9a8c49-480f-5696-065d-31253d9c4238
```
error: Failed dependencies:
libffi-d58a691e.so.8.1.0(LIBFFI_BASE_8.0)(64bit) is needed by azure-cli-2.31.0-1.el7.x86_64
libffi-d58a691e.so.8.1.0(LIBFFI_CLOSURE_8.0)(64bit) is needed by azure-cli-2.31.0-1.el7.x86_64
The command '/bin/sh -c rpm -i ./azure-cli-dev.rpm &&     az --version' returned a non-zero code: 1
```
Looks like what the built RPM package requires differs from what it provides.
```
config(azure-cli) = 2.31.0-1.el7
ld-linux-x86-64.so.2()(64bit) …
```
=> {Packaging} Pin `cffi` to 1.14.6 for RPM

src/azure-cli-core/azure/cli/core/commands/progress.py
Fix #20607
> DeprecationWarning: humanfriendly.Spinner was moved to humanfriendly.terminal.spinners.Spinner, please update your imports
spinner=humanfriendly.Spinner(  # pylint: disable=no-member
Migrate spinner for progress bar to suppress the DeprecationWarning of spinner in pytest
---
=> {Core} Migrate spinner for progress bar

src/azure-cli/azure/cli/command_modules/synapse/manual/_params.py, src/azure-cli/azure/cli/command_modules/synapse/manual/operations/sqlpool.py, src/azure-cli/azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py
Add "SQL pool create" and "SQL pool restore" command parameters, "SQL pool create" and "storageaccounttype" parameters, and "storageaccounttype" and "args" parameters for "SQL pool restore"
---
=> [Synapse] `az synapse sql pool create/restore`: Add parameters `--storage-type` to support specifying storage account type

src/azure-cli-testsdk/setup.py, src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt
Extension CI fails:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1240705&view=logs&j=59e8686e-5e74-514d-6cad-f7d66c66b425&t=59602323-6717-504d-f2cc-5c81369f935f&l=736
```
ERROR: azext_aks_preview.tests.latest.test_aks_commands (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: azext_aks_preview.tests.latest.test_aks_commands
File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
module = self._get_module_from_name(name)
File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
__import__(name)
File …
```
=> {testsdk} Add `ConfigArgParse` dependency

src/azure-cli-testsdk/azure/cli/testsdk/base.py, src/azure-cli-testsdk/azure/cli/testsdk/scenario_tests/base.py, src/azure-cli-testsdk/azure/cli/testsdk/scenario_tests/preparers.py, src/azure-cli-testsdk/azure/cli/testsdk/scenario_tests/recording_processors.py, src/azure-cli-testsdk/azure/cli/testsdk/utilities.py
`GeneralNameReplacer` from `azure_devtools` is buggy, and is overridden to provide correct functionality. 
Now that we have incorporated `azure_devtools` (#20601), there is no need to override `GeneralNameReplacer`.
=> {testsdk} Fix `GeneralNameReplacer`

src/azure-cli-testsdk/azure/cli/testsdk/scenario_tests/base.py, src/azure-cli-testsdk/azure/cli/testsdk/scenario_tests/recording_processors.py
When the test framework replaces a random name, its length is not preserved:
```diff
- appxxxxxxxxxxxx
+ app000003
```
This make `Content-Length` header in the response not match the actual body, causing failure due to the new `azure-core` check https://github.com/Azure/azure-sdk-for-python/pull/20888.
There are several processors that changes the `Content-Length` of the body:
1. All preparers that inherits from `AbstractPreparer` or `SingleValueReplacer`, like `ResourceGroupPreparer`
2. `AADGraphUserReplacer`
3. `GraphClientPasswordReplacer`
4. etc
This makes it difficult to enforce all processors to rectify the `Content-Length` header. The best place is to rectify `Content-Length` header when all processors are finished.
See
- …
=> {testsdk} Add `ContentLengthProcessor` to fix `Content-Length` header

src/azure-cli/azure/cli/command_modules/appservice/static_sites.py, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_staticapp_commands_thru_mock.py
Fixes the `az staticwebapp users update` issue described by #19550. The command was broken by an update to the static web apps SDK -- the new method for updating user roles expected a slightly different set of arguments. 
`azdev test test_staticapp_commands_thru_mock`
---
=> [App Service] Fix #19550: `az staticwebapp users update`: Allow updating static web app user roles again 

src/azure-cli-testsdk/setup.py
After
- https://github.com/Azure/azure-cli/pull/20601
CI fails:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1244125&view=logs&jobId=c846b3e8-69b8-5dbd-1a39-4905d81e6a95&j=c846b3e8-69b8-5dbd-1a39-4905d81e6a95&t=9ebb608a-8a51-5834-bad0-46e2c03d2282
```
==================================== ERRORS ====================================
_________ ERROR collecting tests/latest/test_acr_agentpool_commands.py _________
ImportError while importing test module '/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/tests/latest/test_acr_agentpool_commands.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/az/lib/python3.6/importlib/__init__.py:126: in import_module
return _bootstrap._gcd_import(name[level:], package, …
```
=> {testsdk} Include `azure.cli.testsdk.scenario_tests` in wheel

src/azure-cli-core/setup.py, src/azure-cli-telemetry/setup.py, src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt
Bump `msal-extensions` to 0.3.1 to incorporate changes from https://github.com/AzureAD/microsoft-authentication-extensions-for-python/pull/105.
Specifically, this will fix 
- https://github.com/Azure/azure-cli/issues/20273
=> {Auth} Bump `msal-extensions` to 0.3.1

scripts/curl_install_pypi/install, scripts/curl_install_pypi/install.py
https://github.com/pypa/virtualenv/pull/2109
https://virtualenv.pypa.io/en/legacy/changes.html#v16-7-11-2021-07-20
Linux install script is not working with Python 3.10  (#20713) due to the fact the version of virutalenv is pinned to 16.7.7, which is not compatible with python 3.10. This PR upgrades virtualenv to 16.7.11.
```
docker run --rm -it python:3.10 bash
curl -o install_old.py https://raw.githubusercontent.com/Azure/azure-cli/azure-cli-2.31.0/scripts/curl_install_pypi/install.py
python install_old.py
curl -o install_new.py https://raw.githubusercontent.com/pallxk/azure-cli/fix-install-script-py-3.10/scripts/curl_install_pypi/install.py
python install_new.py
```
[Packaging] Fix install script on Python 3.10
--- …
=> {Packaging} Upgrade `virtualenv` to 16.7.11 to fix install on python 3.10

src/azure-cli-core/azure/cli/core/_profile.py, src/azure-cli-core/azure/cli/core/commands/arm.py, src/azure-cli-core/azure/cli/core/commands/template_create.py, src/azure-cli-core/setup.py, src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt
Fix #20732 
`msrestazure` is indeed needed by `azure-cli-core` to authenticate with managed identity:
https://github.com/Azure/azure-cli/blob/d7e5ede07748b423d2b03fbb8bd25b8bb2c19023/src/azure-cli-core/azure/cli/core/auth/adal_authentication.py#L8
It works now without declaring `msrestazure` dependency because `msrestazure` is installed by Track 1 SDKs.
`packaging` is needed by extension operations:
https://github.com/Azure/azure-cli/blob/ed6e829554624894d5c94ad71bb85e788d726a43/src/azure-cli-core/azure/cli/core/extension/__init__.py#L283
It works now without declaring `packaging` dependency because `packaging` is installed by `azure-cli`:
https://github.com/Azure/azure-cli/blob/d5314bacaca2b0abc1c884d995f48a130a4261f9/src/azure-cli/setup.py#L144
=> {Packaging} Add missing dependencies for `azure-cli-core`

src/azure-cli/azure/cli/command_modules/acr/_archive_utils.py
Fixes #20075
The `az acr build` command may upload local source code (the "context") to Azure prior to executing a build. In this case, the local build context is uploaded to Azure blob storage. In a slow network environment, customers may see the error `('Connection aborted.', timeout('The write operation timed out'))` during the upload stage of the command. This happens when the customer machine takes too long to connect to Azure storage server. Azure storage Python SDK uses a default client connection timeout of 20s. This change increases that timeout to 300s. 
Queue a local context as a Linux build, tag it, and push it to the registry.
`az acr build -t sample/hello-world:{{.Run.ID}} -r MyRegistry .`
--- …
=> {ACR} Increase client connection timeout with storage when uploading local build context

src/azure-cli-core/azure/cli/core/commands/transform.py, src/azure-cli/azure/cli/command_modules/util/custom.py
- Fix #16286
The logic to add `resourceGroup` properties to the output JSON was added as early as #66.
While it helps (to some extent) in normal ARM commands, it causes trouble in `az rest` as the `GET` result can't be `PUT` back. 
```
$ vnet=$(az rest -m GET -u /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/my-test/providers/Microsoft.Network/virtualNetworks/vnettest?api-version=2021-02-01)
$ echo "$vnet"
{
"etag": "W/\"6edecdf3-4fb4-4b9e-a3a0-bcf184d6caf7\"",
"id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/my-test/providers/Microsoft.Network/virtualNetworks/vnettest",
"location": "centralus",
"name": "vnettest",
"properties": {
"addressSpace": {
"addressPrefixes": [
"10.1.0.0/16"
]
},
"enableDdosProtection": false,
"provisioningState": …
```
=> [Rest] BREAKING CHANGE: `az rest`: Remove `resourceGroup`, `x509ThumbprintHex` transforms

src/azure-cli-core/azure/cli/core/auth/identity.py, src/azure-cli-core/azure/cli/core/auth/tests/test_identity.py
Refinement to #20632
Certificate path can now include `~` which expands to HOME folder:
```
az login --service-principal
--username d0e3a385-0435-4e2d-bc8b-8298daa7e115
--password '~\Desktop\3.pem'
--tenant 54826b22-38d6-4fb2-bad9-b7b93a3e9c5a
```
=> {Profile} `az login`: Support `~` in certificate path

src/azure-cli/azure/cli/command_modules/storage/operations/account.py
If the original storage account doesn't have user identity, update storage account with user_identity will fail like:
```
az storage account create -n testsa -g testrg
az storage account update -n testsa -g testrg --identity-type UserAssigned --user-identity-id testidentityid
```
---
=> {Storage} `az storage account update`: Fix AttributeError when updating user_identity

src/azure-cli/azure/cli/command_modules/storage/_help.py, src/azure-cli/azure/cli/command_modules/storage/_params.py, src/azure-cli/azure/cli/command_modules/storage/azcopy/util.py, src/azure-cli/azure/cli/command_modules/storage/commands.py, src/azure-cli/azure/cli/command_modules/storage/linter_exclusions.yml, src/azure-cli/azure/cli/command_modules/storage/operations/azcopy.py
Feature asked by #20662 #20663 #20666 
This PR:
- Adds positional argument `extra_options` with `experimental` tag for flexibility
- Upgrades `azcopy` from `10.8.0` to `10.13.0`
- Removes `preview` tag for `az storage copy`
`az storage copy -s source_file -d destination_container_url -- --block-size-mb=0.25 --check-length`
---
=> [Storage] `az storage copy`: Add positional argument `extra_options` to pass through options to `azcopy`

src/azure-cli-core/azure/cli/core/_profile.py, src/azure-cli-core/azure/cli/core/auth/identity.py, src/azure-cli-core/azure/cli/core/auth/persistence.py, src/azure-cli-core/azure/cli/core/decorators.py
Fix #20707, #20676, #20720
When invoked by Terraform concurrently, one instance of `az` fails with:
```
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 113, in _load_msal_http_cache
│     persisted_http_cache = pickle.load(f)
│ EOFError: Ran out of input
```
This is because a racing condition happens after the cache file `~/.azure/msal_http_cache.bin` is created but not filled yet:
https://github.com/Azure/azure-cli/blob/713b0edca860a8e4037bfc865d847b945fb12886/src/azure-cli-core/azure/cli/core/auth/identity.py#L117-L121
The second instance will see an empty cache file, resulting in `EOFError`.
This PR adds a retry logic to `_load_msal_http_cache` so that it retries several times in case of failure. If it still fails at last, ignore exceptions and use …
=> {Core} Retry loading MSAL HTTP cache in case of failure

src/azure-cli/azure/cli/command_modules/appservice/_create_util.py, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_up_commands.py
Fixes #20757 
`azdev test --live test_webapp_up_no_plan_e2e `
---
=> [App Service] Fix #20757: `az webapp up`:  Fix list index out of range when no `--plan` argument passed

src/azure-cli/azure/cli/command_modules/iot/custom.py, src/azure-cli/azure/cli/command_modules/iot/tests/latest/recordings/test_hub_file_upload.yaml, src/azure-cli/azure/cli/command_modules/iot/tests/latest/test_iot_commands.py, src/azure-cli/azure/cli/command_modules/role/custom.py
This PR fixes a bug where a hub without a default storage endpoint cannot be updated with `az iot hub update`, and also shows an error if the user attempts to update file upload settings on a hub missing this required endpoint.
Fixes #20004 
If your hub has no default storage endpoint (`properties.storageEndpoints[$default]`), you should still be able to update other properties of the hub using `az iot hub update [--param or --set]`, however if you attempt to update file-upload endpoint-specific settings (container name, connection string, sas_ttl, identity, etc), you will receive the following error:
`This hub has no default storage endpoint for file upload.`
`Please recreate your default storage endpoint by running "az iot hub update --name {hub_name} …
=> [IoT] Error handling of Hubs missing default storage endpoint

src/azure-cli-testsdk/azure/cli/testsdk/__init__.py, src/azure-cli-testsdk/azure/cli/testsdk/preparers.py
Add default connection string required in communication extension in resource preparer file.
NA
---
=> {testsdk} Remove `CommunicationResourcePreparer` from `azure-cli-testsdk`

.github/CODEOWNERS, src/azure-cli/azure/cli/command_modules/serviceconnector/_utils.py, src/azure-cli/azure/cli/command_modules/serviceconnector/custom.py
This PR brings some improvements for ServiceConnector. When users' subscription is not registered for `Microsoft.ServiceLinker`, we will register the subscription for users.
---
=> {ServiceConnector} Support RP auto registering

src/azure-cli/azure/cli/command_modules/storage/_help.py
--deleted-version parameter is mandatory to input in the az storage container restore command, Multiple users were unaware on how to fetch the --deleted-version parameter and there was a confusion if this parameter was related to Blob Versioning. The Deleted Version number is also not visible when you look up the soft deleted container --> properties in azure portal, nor is it present in the response body when initial Delete container API is called.
Suggested these changes to ease the usage of container restore command via Az cli for end users.
--- …
=> {Storage} Updated the usage of az storage container restore

src/azure-cli/azure/cli/command_modules/acs/_params.py, src/azure-cli/azure/cli/command_modules/acs/_validators.py, src/azure-cli/azure/cli/command_modules/acs/decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/hybrid_2020_09_01/test_validators.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_validators.py
Update validator for cluster auto-scaler profile.
- Move the validator for cluster auto-scaler profile from `_validator.py` to `decorator.py`.
- In the validation of the option `--cluster-autoscaler-profile`, the corresponding api model (`ManagedClusterPropertiesAutoScalerProfile`) needs to be loaded, and loading the model in file `_validator.py` requires hard-coding the api version or changing the function signature; if it is placed in file `decorator.py` for validation, no additional changes are required, and this would help us to reuse this part directly in azure-cli-extensions/aks-preview.
- The option `--cluster-autoscaler-profile` is only available in `aks create` and `aks update`, and now the implementation of these two commands are switched to decorator pattern. …
=> {AKS} Update validator for cluster auto-scaler profile

src/azure-cli-core/azure/cli/core/auth/adal_authentication.py
Fix https://github.com/Azure/azure-cli/pull/20215#issuecomment-1002446176
Python 3.6 doesn't recognize timezone `%z` as `+00:00`. It only recognizes `+0000`:
```py
> docker run -it --rm python:3.6
>>> import datetime
>>> datetime.datetime.strptime('12/30/2021 07:53:52 +00:00', '%m/%d/%Y %H:%M:%S %z')
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
tt, fraction = _strptime(data_string, format)
File "/usr/local/lib/python3.6/_strptime.py", line 362, in _strptime
(data_string, format))
ValueError: time data '12/30/2021 07:53:52 +00:00' does not match format '%m/%d/%Y %H:%M:%S %z'
>>> datetime.datetime.strptime('12/30/2021 07:53:52 +0000', '%m/%d/%Y %H:%M:%S %z') …
```
=> {Core} Fix `_normalize_expires_on` on Python 3.6

src/azure-cli/setup.py
Fix https://github.com/Azure/azure-cli/issues/20856
`azure-keyvault-keys==4.5.0b5` made a breaking change for authentication:
- https://github.com/Azure/azure-sdk-for-python/pull/21290
It uses `azure-identity`'s new multi-tenant authentication API `get_token(tenant_id=...)` from
- https://github.com/Azure/azure-sdk-for-python/pull/20940
However, Azure CLI has its own multi-tenant authentication implementation using `CredentialAdaptor.get_auxiliary_tokens`:
- #19853
therefore not compatible with `azure-identity`'s implementation. 
This leads to failure as described in #20856.
=> {Keyvault} Pin `azure-keyvault-keys==4.5.0b4`

src/azure-cli/azure/cli/command_modules/appconfig/_kv_helpers.py, src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/test_appconfig_commands.py
When importing or exporting an app configuration and the destination is an app service, the normal functionality is to use the production slot even when a non-production slot is provided as the app service ID. This change will use the provided slot to import / export instead of production. This has been marked as a breaking change since it will react differently than before if given the app service ID for a slot.
=> [App Config] BREAKING CHANGE: Support app service slots

src/azure-cli-core/setup.py, src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt
Fix https://github.com/Azure/azure-cli/pull/20195#issuecomment-979676353
When installing with `pip install azure-cli`, installing `psutil` 5.8.0 fails without Microsoft Visual C++:
```
ERROR: Command errored out with exit status 1:
command: 'D:\test-envs\test310\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-ds9qtdad\\psutil_edc519ddccee4418ba33c3e0ff32ce49\\setup.py'"'"'; __file__='"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-ds9qtdad\\psutil_edc519ddccee4418ba33c3e0ff32ce49\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = …
```
=> {Packaging} Bump `psutil` to 5.9.0

src/azure-cli/azure/cli/command_modules/storage/commands.py
**Backgrounds**
Storage module support several kinds of credential for data plane commands and `azcopy` commands:
1) `--account-key` with `--auth-mode key`(which can be omited)
2) `--connection-string`
3) `--sas-token`
4) `--auth-mode login`
`azcopy` has two kinds of auth:
a) SAS token auth
b) AAD auth
When customers provide 1) or 2), we generate a SAS token using the credential they give.
So with 1) 2) 3), we call `azcopy` by SAS token auth.
With 4), we call `azcopy` by AAD auth with login `access_token` and `refresh_token` stored in environment variable.
**Problems**
- After CLI core migrates from ADAL to MSAL, we can't get `refresh_token` any more. `azcopy` related commands fail with `--auth-mode login` (#20488)
- Setting `access_token` and `refresh_token` in env virable is unsafe. …
=> [Storage] Stop supporting `--auth-mode login` for `az storage blob sync` and `az storage fs directory upload/download`

src/azure-cli/azure/cli/command_modules/cdn/tests/latest/byoc_cert_policy.json, src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_cdn_custom_domain_byoc_latest.yaml, src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_cdn_custom_domain_crud.yaml, src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_cdn_custom_domain_errors.yaml, src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_cdn_custom_domain_https_akamai.yaml, src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_cdn_custom_domain_https_msft.yaml, src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_cdn_custom_domain_https_verizon.yaml, src/azure-cli/azure/cli/command_modules/cdn/tests/latest/scenario_mixin.py, src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_custom_domain_scenarios.py
Currently, `azdev test cdn` command will fail with the message:
> KeyVaultErrorException('(Unauthorized) Request is missing a Bearer or PoP token.')
The issue is caused by challenge cache conflict  in the key vault authentication process,  test_cdn_custom_domain_byoc_latest and  test_cdn_custom_domain_https_msft used to use the same key vault and they share the challenge cache. When they are launched in the same process, the latter one will reuse the challenge cache and that will cause the previously recorded challenge request to be treated as a regular request in VCR replay model.
This PR aims to use different key vault prefixes to bypass the challenge cache issue.
azdev test cdn
--- …
=> [CDN] Fix test failures in test_custom_domain_scenarios.py caused by key vault authentication challenge cache

src/azure-cli/azure/cli/command_modules/botservice/custom.py
Previously the location parameter as specified by the user in the az bot create command was not actually used. This was okay previously because all bot resources are global. However due to EU data boundary work, we now support creation of Europe and United States regional bots and guarantee data residency for such bots. Because this is not a breaking change, and the lack of propagation of this property is technically a bug, we would prefer to take this change as a hotfix.
Test cases:
To validate existing functionality
- run az bot create without a location
- run az bot create with "global" as the specified location
- (can only be included when the ARM manifest is able to be updated in January for the service) run az bot create with "westeurope" or …
=> [Bot Service] `az bot create`: Add location as specified by user to bot creation for regionality/EUDB

src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt
`certifi` hasn't been bumped since 2019-06-26 (#9785).
Some certificate will expire soon:
```
Certificate:
Data:
Version: 3 (0x2)
Serial Number: 144470 (0x23456)
Signature Algorithm: sha1WithRSAEncryption
Issuer: C=US, O=GeoTrust Inc., CN=GeoTrust Global CA
Validity
Not Before: May 21 04:00:00 2002 GMT
Not After : May 21 04:00:00 2022 GMT
```
We should bump `certifi` to the latest version before it is too late.
In order to view decoded CA bundle, run
```
openssl storeutl -noout -text -certs D:\cli\py310\Lib\site-packages\certifi\cacert.pem
```
See https://serverfault.com/a/1079893/174062
=> {Packaging} Bump `certifi` to 2021.10.8

src/azure-cli/azure/cli/command_modules/vm/_help.py, src/azure-cli/azure/cli/command_modules/vm/_params.py, src/azure-cli/azure/cli/command_modules/vm/_validators.py
As the security team raised the security concern: the permission of  `Contributor` is too high to be used as the default role for the creation of VM and VMSS, so the default value `Contributor` of `--role` will be removed in the future. 
Therefore, the first step is to prompt users that parameters `--role` and `--scope`  should be passed in at the same time when assigning role to the managed identity to reduce the impact of breaking change.
The specific effects are as follows:
---
=> [Compute] `az vm/vmss create`: Add warning log and modify help to inform that the default value `Contributor` of `--role` will be removed

src/azure-cli/azure/cli/command_modules/role/_help.py, src/azure-cli/azure/cli/command_modules/role/custom.py
A temporary warning for https://github.com/Azure/azure-cli/issues/20806
For `az ad sp create-for-rbac`, when `--role` is given, `--scope` defaults  to the subscription:
```
> az ad sp create-for-rbac --role Reader
...
Creating 'Reader' role assignment under scope '/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590'
...
{
"appId": "9eb7e5f0-7a0b-4601-9d72-3f438fcace9f",
"displayName": "azure-cli-2021-12-22-08-39-11",
"password": "",
"tenant": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a"
}
```
Without explicit consent from the user on the `--scope`, this behavior is considered Elevation of Privilege.
This PR adds a warning when `--role` is specified but `--scopes` is not:
```
> az ad sp create-for-rbac --role contributor
In a future release, --scopes argument will become required …
```
=> {Role} `az ad sp create-for-rbac`: Show warning when `--scopes` defaults to subscription

scripts/release/rpm/Dockerfile.fedora
Fedora 29 has been EOL for quite some time and Fedora 35 is the current release. Update the tag to 35, which is the most recent stable release.
No changes to the testing process.
---
=> {packaging} Update Fedora dockerfile to Fedora 35

Dockerfile
Keep the pace with Alpine and some tools are only available on Alpine 3.15, ie : postgresql14-client
"docker build -t azure-cli ." to check the build
Dockerfile is now based on python Alpine 3.15
---
=> [Packaging] Update Dockerfile base image from Alpine 3.14 to 3.15

src/azure-cli/azure/cli/command_modules/rdbms/custom.py, src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_mysql.py
Hi.
This PR fixes bug described in #20563 where connection strings outputted by `az` are wrong for mysql (and mariadb).
Indeed, before this commit, the following was outputted for PHP:
```php
host=foo-mysql-server.mysql.database.azure.com port=3306 dbname={database} user={username}@foo-mysql-server password={password}
```
Now, a connection string which permits connection is printed:
```php
$con=mysqli_init(); [mysqli_ssl_set($con, NULL, NULL, {ca-cert filename}, NULL, NULL);] mysqli_real_connect($con, 'fran92-mysql-server.mysql.database.azure.com, '{username}@fran92-mysql-server', '{password}', '{database}', 3306);
```
You can test it using the following (be sure to be logged to azure before):
```bash
$ rg="fix-php-connection-string${RANDOM}"
$ user='fix'
$ read -s password
$ …
```
=> {RDBMS} Fix PHP wrong connection strings

src/azure-cli/azure/cli/command_modules/redis/custom.py, src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_update.yaml, src/azure-cli/azure/cli/command_modules/redis/tests/latest/test_redis_scenario.py
currently az create is treating the identity field with "None" as an operation whereas it should be treated as no-op
added default value for public network access as None
Please refer the new test "test_redis_cache_update" added in the unit test.
[Redis] `az redis create`: Add default value for identity and public network access as `None`
=> [Redis] `az redis create`: Add default value for identity and public network access as `None`

src/azure-cli/azure/cli/command_modules/iot/_help.py
I found a typo in the documentation of the `az iot hub route update` documentation.  (enpoint must obviously be endpoint).
=> {iot} Fix: typo in az iot hub route update docs

src/azure-cli/azure/cli/command_modules/batch/_params.py
Application package file path is local to the filesystem so that the CLI can upload it to Azure Storage
=> [Batch] `az batch create/activate`: Add clarify application package path help info for argument `--package-file`

src/azure-cli/azure/cli/command_modules/iot/_help.py
iot hub route examples must use the correct arguments.
=> {Iot} Use correct params in iot hub route examples

build_scripts/windows/scripts/build.cmd
An alternative solution to https://github.com/Azure/azure-cli/pull/21143
When building Windows MSI, `_models_py3.py` files are removed to reduce package size.
- `_models.py` are both Python 2 and 3 compatible
- `_models_py3.py` are only Python 3 compatible
Since 2022-01, Python 2 support has been dropped by Python SDK (https://github.com/Azure/azure-sdk-for-python/issues/20691).
- `_models.py` files are removed from new version Python SDKs
- That is, only `_models_py3.py` files are kept in Python SDKs
So far, this change has been done on `azure-mgmt-netapp` and `azure-mgmt-trafficmanager`. 
However, because CLI's build pipeline removes `_models_py3.py` files, no model files will exist in the MSI package. This leads to CI failure: …
=> {Packaging} Keep py3 model files

src/azure-cli-core/azure/cli/core/auth/identity.py
After the change of MSAL
- https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/388
The original statement "The default web browser" is no longer true and it causes user confusion:
- https://github.com/Azure/azure-cli/issues/21136
This PR updates the warning message according to the latest MSAL behavior.
=> {Core} Update warning message for auth code flow

Dockerfile
`jmespath-terminal` no longer installes with latest `setuptools` because it uses very old `urwid==1.2.2` (https://github.com/jmespath/jmespath.terminal/issues/19). This issue was reported in 2018 but per https://pypi.org/project/jmespath-terminal/, the latest version of `jmespath-terminal` was released on Oct 6, 2015.
This causes CI failure and blocks PR (https://github.com/Azure/azure-cli/pull/21057#issuecomment-1031013267):
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1341309&view=logs&j=a3141784-dfa9-5792-78cc-844daee2d774&t=b2b6de04-64e4-5812-4fff-06c02d19f4c2&l=214
```
error in urwid setup command: use_2to3 is invalid.
Couldn't build the extension module, trying without it...
----------------------------------------
WARNING: Discarding …
```
=> [Packaging] BREAKING CHANGE: Drop `jmespath-terminal` from docker image

src/azure-cli/azure/cli/command_modules/network/custom.py, src/azure-cli/azure/cli/command_modules/network/tunnel.py
Clean up the Bastion session established from the az cli after disconnecting.
Azure SSH
1. Connect to an existing VM via `az network bastion ssh`
2. Verify session in the Azure portal
3. Exit the session from the command line by typing `exit` and pressing enter
4. Verify session is no longer present in Azure portal
Azure tunnel + SSH exit
1. Establish a tunnel to an existing VM via `az network bastion tunnel`
2. SSH into the VM (e.g., via putty)
3. Verify session in the Azure portal
4. Exit from the SSH session
5. Verify session is no longer present in Azure portal
Azure tunnel + SSH close tunnel
1. Establish a tunnel to an existing VM via `az network bastion tunnel`
2. SSH into the VM (e.g., via putty)
3. Verify session in the Azure portal
4. Close the …
=> {Network} Close bastion session from cli

azure-pipelines.yml, scripts/release/rpm/test_rpm_in_docker.sh
Since CentOS 8 has been deprecated, `centos8` image no longer works:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1348614&view=logs&j=1e6fba43-bdcf-51f0-a062-3712c33fbb51&t=a1e787eb-ec67-5c3d-79ec-0c68f4f59d65
```
yum --nogpgcheck localinstall /mnt/yum/$YUM_NAME -y
+ yum --nogpgcheck localinstall /mnt/yum/azure-cli-2.33.0-1.el7.x86_64.rpm -y
CentOS Linux 8 - AppStream                      445  B/s |  38  B     00:00    
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```
This PR is only a quick fix to unblock CI by reverting to `centos7` which is still supported. (However, `centos7` has its own complication.)
See https://forums.centos.org/viewtopic.php?f=54&t=78708
=> {Packaging} Fix CI job "Test Yum Package" by using `centos7`

src/azure-cli/azure/cli/command_modules/network/custom.py
The current ssh discovery function only works for Windows. This adds in some logic to find the binary for Darwin and Linux as well.
This allows the use of the Azure Bastion SSH functionality on Mac and Linux, mostly around using:
az network bastion ssh 
[Network] : az command network: Provide support for Bastion SSH access on Darwin and Linux 
---
=> [Network] `az bastion ssh`: Add more platforms

src/azure-cli/azure/cli/command_modules/batch/_command_type.py, src/azure-cli/azure/cli/command_modules/batch/_completers.py, src/azure-cli/azure/cli/command_modules/batch/_exception_handler.py, src/azure-cli/azure/cli/command_modules/batch/_params.py, src/azure-cli/azure/cli/command_modules/batch/_validators.py, src/azure-cli/azure/cli/command_modules/batch/commands.py, src/azure-cli/azure/cli/command_modules/batch/custom.py, src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_certificate_cmd.yaml, src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_job_list_cmd.yaml, src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_jobs_and_tasks.yaml, src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_pool_cmd.yaml, src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_pools_and_nodes.yaml, src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_task_create_cmd.yaml, src/azure-cli/azure/cli/command_modules/batch/tests/latest/test_batch_commands.py, src/azure-cli/azure/cli/command_modules/batch/tests/latest/test_batch_data_plane_commands.py, src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt, src/azure-cli/setup.py
Description
Upgrade the Batch data plane to 12.0.0  (API version 2022-01-01.15).
Testing Guide
Testing the Batch module is described in the [README.md](https://github.com/Azure/azurecli/blob/dev/src/azurecli/azure/cli/command_modules/batch/tests/latest/README.md)
History Notes
[Batch] Upgrade batch data-plane to [azure-batch 12.0.0](https://pypi.org/project/azure-batch/)
=> {Batch} Upgrade api-version to v2022-01-01.15

azure-pipelines.yml
Because package `Microsoft.Security.CredScan` in task `Run Credential Scanner` was upgraded from version `2.1.17` to the new version `2.2.7.8`, a large number of issues were scanned, resulting in CI blocking [pipeline link](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1352821&view=logs&j=90b26e6a-5461-58d0-82ac-76aa6c69f0af&t=cb13b626-29b0-5981-0cad-2f2519bb3c97)
Therefore, pin the version of `Microsoft.Security.CredScan` to the last successfully version `2.1.17` to avoid blocking CI
=> {ADO} Pin version `2.1.17` for cred scan

src/azure-cli/azure/cli/command_modules/apim/custom.py, src/azure-cli/azure/cli/command_modules/apim/tests/latest/recordings/test_apim_core_service.yaml, src/azure-cli/azure/cli/command_modules/apim/tests/latest/test_apim_scenario.py
When performing operations on an API in APIM using Azure CLI like create, import, or update, there are parameters available to set the subscription key header and query param name.
But as brought up in issue #21187, they are flipped. This PR fixes that and updates the tests accordingly.
After regenerating the test recording, I only include the relevant changes since the other changes were just to the `User-Agent` or `etag` values. Hope that is OK.
```
az apim api create --service-name {} -g {} --api-id MyApi --path '/myapi' --display-name 'My API' --subscription-key-header-name 'header' --subscription-key-query-param-name 'query'
az apim api update --service-name {} -g {} --api-id MyApi --subscription-key-header-name 'header' …
```
=> [APIM] Fix #21187: `az apim api create/update/import`: Fix header and query param names being swapped

src/azure-cli/azure/cli/command_modules/acs/_help.py, src/azure-cli/azure/cli/command_modules/acs/_params.py, src/azure-cli/azure/cli/command_modules/acs/custom.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_nodepool_update_taints_msi.yaml, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
=> [AKS] `az aks nodepool update`: Add `--node-taints` to allow modify node taints

src/azure-cli/azure/cli/command_modules/appservice/_validators.py
As per below article for PremiumPlan Max scale out is 100. 
https://docs.microsoft.com/en-us/azure/azure-functions/functions-premium-plan?tabs=portal#region-max-scale-out
---
Fixes #21225
=> [FunctionAPP] `az functionapp plan`: Update the max_val of `--max-burst` to 100

src/azure-cli/azure/cli/command_modules/vm/_params.py
Remove space from SLES_STANDARD license type enum
Remove space from SLES_STANDARD license type enum
az vm update --license-type 'SLES_STANDARD'
Customer got issue: > az vm update: 'SLES_STANDARD' is not a valid value for '--license-type'. 
> Allowed values: Windows_Server, Windows_Client, RHEL_BYOS, SLES_BYOS, 
> RHEL_BASE, RHEL_SAPAPPS, RHEL_SAPHA, RHEL_EUS, SLES_STANDARD , SLES_SAP, 
> SLES_HPC, None, RHEL_ELS_6
---
- [ Y] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).
- [ Y] I adhere to the [Command …
=> {Compute} `az vm update`: Remove space from one license type value 'SLES_STANDARD'

src/azure-cli-core/azure/cli/core/auth/credential_adaptor.py
`azure-keyvault-keys==4.5.0b5` made a breaking change for authentication:
- https://github.com/Azure/azure-sdk-for-python/pull/21290
It uses `azure-identity`'s new multi-tenant authentication API `get_token(tenant_id=...)` from
- https://github.com/Azure/azure-sdk-for-python/pull/20940
However, the current authentication of Azure CLI cannot handle `get_token(tenant_id=...)` because **a credential inherits from an MSAL application**, so `tenant_id` is fixed during the initialization of a credential/MSAL application. In order to support `get_token(tenant_id=...)`, the MSAL application must be created during `get_token`, which requires a total overhaul of the authentication mechanism.
As currently Azure CLI can't automatically get an access token from another tenant for …
=> {Core} Discard `tenant_id` in `get_token`

src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py, src/azure-cli/azure/cli/command_modules/rdbms/_params.py, src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_common.py
1. In create migration, sending {"cutover":"true"} flag always to automatically cutover a migration and not go in logical migration phase.
---
=> {RDBMS}: Switch to Offline migration by default for PG single to flex migrations

Dockerfile, azure-pipelines.yml, scripts/release/rpm/test_rpm_in_docker.sh
Cherry pick from dev branch:
1. https://github.com/Azure/azure-cli/pull/21206
2. https://github.com/Azure/azure-cli/pull/21207
3. https://github.com/Azure/azure-cli/pull/21230
---
=> {Release} Fix CI issue for release branch

src/azure-cli/azure/cli/command_modules/apim/_params.py
updated description for api_id argument
Pull request resolves the bug #18306 with inaccurate description for api_id argument
**az apim api import --help**: check for the description of api-id _" API revision identifier. Must be unique in the current API
Management service instance. Non-current revision has
;rev=n as a suffix where n is the revision number."_
**current change** will change the description of api-id to _"API identifier. Must be unique in the current API Management service instance. Non-current revision has ;rev=n as a suffix where n is the revision number."_
=> [API Management] apim api import: Update api-id description  #18306

.vscode/launch.json
A previous change wrote arguments into launch.json's integrated console debugger.
This change reverts that change and sets the default args collection to execute `--help`.
1. Setup your machine following the Developer Setup: https://github.com/azure/azure-cli#developer-setup
1. Open the repository in Visual Studio Code
1. Debug the Azure CLI
n/a
---
=> {Misc} Restore debugger to execute `--help` out-of-the-box

src/azure-cli/azure/cli/command_modules/sql/_params.py, src/azure-cli/azure/cli/command_modules/sql/custom.py, src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_server_mgmt.yaml, src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
This PR adds server level support for federated client id used in cross tenant CMK scenario
az sql server create --federated-client-id should create a server with corresponding federated client id value
az sql server update--federated-client-id should update a server with new federated client id value
[SQL] `az sql server create/update`: Add federated client id support.
---
=> [SQL] Add federated client id support for sql

src/azure-cli-core/azure/cli/core/_profile.py, src/azure-cli-core/azure/cli/core/auth/identity.py, src/azure-cli-core/azure/cli/core/tests/test_profile.py, src/azure-cli/azure/cli/command_modules/profile/__init__.py, src/azure-cli/azure/cli/command_modules/profile/custom.py
https://github.com/Azure/azure-cli/pull/19414 announced the deprecation of `--sdk-auth` but `--sdk-auth` was kept during MSAL migration (https://github.com/Azure/azure-cli/pull/19872).
`az account show --sdk-auth` compromises the security of MSAL's encrypted service principal credential store, as it can "spit out" / echo the original service principal secrets. This is not a secure behavior - consider you can see your password after you login to Windows or https://outlook.live.com/.
However, `az ad sp create-for-rbac --sdk-auth` is still used by many other services, like GitHub Action (as shown in https://github.com/Azure/azure-cli/pull/19872), it will be kept for now.
=> [Profile] BREAKING CHANGE: `az account show`: Drop `--sdk-auth`

src/azure-cli/azure/cli/command_modules/role/_help.py, src/azure-cli/azure/cli/command_modules/role/custom.py
Refine the warning introduced by #20965 to explicitly call out the breaking change schedule.
Related: https://github.com/Azure/azure-cli/pull/21326
=> {Role} `az ad sp create-for-rbac`: Add version to the warning when `--scopes` defaults to subscription

scripts/ci/check_pull_request.py
It is impossible to judge verb accurately.
Instead, it may cause [pr](https://github.com/Azure/azure-cli/pull/21350) to be blocked.
So we only check the first word after `]` or `:`.
According to our [history release note](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?toc=/cli/azure/toc.json&bc=/cli/azure/breadcrumb/toc.json), can solve most of the verb tense problems.
---
=> {CI} Verb check: Only check the first word after `]` or `:`

src/azure-cli/azure/cli/command_modules/vm/_params.py, src/azure-cli/azure/cli/command_modules/vm/_validators.py
Refine the warning and help message introduced by #20924 to explicitly call out the breaking change schedule.
---
=> {Compute} Add target version to warning and help message for deprecating default value for `--role`

src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_virtual_network.py
Fix for:
Creating private dns zone for Postgres/MySQL server when vnet exists in another subscription fails
Since test recording doesn't support multiple subscriptions (marked to 0000), cannot implement a separate tests for this. 
Live testing will need exposing subscription ID in public repo. 
Manual tests and existing comprehensive vnet / private dns zone tests passed
---
=> [RDBMS] Fix bug for private dns zone provisioning to vnet resource group in different subscription 

src/azure-cli/azure/cli/command_modules/keyvault/_params.py, src/azure-cli/azure/cli/command_modules/keyvault/_transformers.py, src/azure-cli/azure/cli/command_modules/keyvault/_validators.py, src/azure-cli/azure/cli/command_modules/keyvault/commands.py, src/azure-cli/azure/cli/command_modules/keyvault/custom.py, src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt, src/azure-cli/service_name.json, src/azure-cli/setup.py
Apply https://github.com/Azure/azure-rest-api-specs/pull/17270
Add `--immutable` for `az keyvault key create/import/set-attributes`
[Keyvault] `az keyvault key create/import/set-attributes`: Support `--immutable` to mark release policy immutable
---
=> [Keyvault] `az keyvault key create/import/set-attributes`: Support `--immutable` to mark release policy immutable

src/azure-cli/azure/cli/command_modules/cosmosdb/custom.py
managed-cassandra cluster update: bugfix in custom.py in the handling of values passed to --external-seed-nodes and --external-gossip-certificates parameters.
Customer was not able to update external-seed-nodes and external-gossip-certificates because CLI was ignoring the values passed to these parameters. This fix allows these two to be updated.
az managed-cassandra cluster update -g $resourceGroup -c $cluster --external-seed-nodes 10.52.221.2 10.52.221.3 10.52.221.4 --external-gossip-certificates "/path/to/gossipcert.pem" --debug
The --external-seed-nodes and --external-gossip-certificates passed in above command now gets propagated to our RP.
[managed-cassandra] `az managed-cassandra cluster update`: Fix to allow …
=> [CosmosDb] `az managed-cassandra cluster update`: Fix `--external-seed-nodes` and `--external-gossip-certificates`

src/azure-cli-core/azure/cli/core/extension/operations.py
rdbms-connect extension requires dependencies to be installed beforehand in Linux System including Cloud Shell. 
Originally this was prevented since there was no agreement from CloudShell team. 
This change is to enable rdbms-connect extension in Cloud Shell, we are installing the dependencies in cloud shell https://github.com/Azure/CloudShell/pull/143 and remove the existing restriction in CLI
---
=> [RDBMS] enable rdbms-connect extension in Cloud Shell

src/azure-cli/azure/cli/command_modules/appservice/custom.py
Issue in #20808 was already fixed (`az webapp deployment github-actions add` command) but the same bug in the `remove` command wasn't fixed
This PR makes the same change in the `remove` command
---
=> [App Service] Fix `az webapp deployment github-actions remove` bug.

src/azure-cli/azure/cli/command_modules/resource/custom.py, src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_group_deployment.yaml, src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_resource_group_deployment.yaml
Issue: #19743
This error `bytes' object has no attribute 'get'` is due to the bug of `JsonCTemplatePolicy` in the retry operation. 
In the case of retry, because the first request has been processed and converted the type of `request.http_request.data` from string to bytes [code link](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/custom.py#L425)  , so there is no need to process `request.http_request.data` again during retry, 
---
=> [ARM] `az deployment`: Fix the bug of `'bytes' object has no attribute 'get'` for error handling in retry cases

src/azure-cli/azure/cli/command_modules/role/__init__.py
Close https://github.com/Azure/azure-cli/issues/20946
As Azure CLI is  migrating to Microsoft Graph (https://github.com/Azure/azure-cli/issues/12946), this PR adds an in-tool warning to notify the user about upcoming breaking changes in the migration.
Run any `az role` or `az ad` commands, like
```
az ad app list -h
az ad app show --id xxx
az role assignment -h
```
=> [Role] Add warning to `role` and `ad` commands about Microsoft Graph migration

scripts/ci/update_docs.sh
Copy release pipeline task [Release Notes](https://dev.azure.com/azure-sdk/internal/_releaseDefinition?definitionId=79&_a=definition-tasks&environmentId=146) script to main repo and **add more comments** to help us troubleshoot CI failures like https://github.com/MicrosoftDocs/azure-docs-cli/issues/2862.
The release notes are manually fixed by https://github.com/MicrosoftDocs/azure-docs-cli/pull/2866.
=> {CI} Copy release pipeline task "Release Notes"'s script to main repo

src/azure-cli/azure/cli/command_modules/network/_actions.py, src/azure-cli/azure/cli/command_modules/network/_help.py, src/azure-cli/azure/cli/command_modules/network/_params.py, src/azure-cli/azure/cli/command_modules/network/commands.py, src/azure-cli/azure/cli/command_modules/network/custom.py, src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_port_mapping.yaml, src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Closes https://github.com/Azure/azure-cli/issues/21426
Customer should be able to query port mapping after creating inbound NAT rule for the entire backend pool.
Upon creation of inbound NAT rule for backend pool, LB will create port mappings for individual Virtual Machine of the backend pool. Customer can use the assigned frontend port to access a specific Virtual Machine in the backend. Thus they should be able to query the port mappings of the backend pool.
---
=> [Network] `az network lb`: Support inbound NAT rule port mapping query

scripts/ci/check_pull_request.py
Add rule to check extra space character before colon.
Add rule to check extra consecutive spaces.
Add rule to check the last character.
---
=> {CI} add some new rules to check pull request title and history note.

src/azure-cli/HISTORY.rst
When auto generate history notes, Compute component get an extra space.
Can fix this issue by simply delete all the extra space character.
`python generate_history_notes.py` test screenshot:
---
=> {CI} Fix generate history notes error: Compute component get an extra space character

azure-pipelines.yml
Add [ado-sbom-generator-task](https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/secure-supply-chain/ado-sbom-generator) to support Generate SBOM (Software Bill of Materials) manifest for built packages.
We need generate SBOM manifest in every artifacts directory.
But there are two remaining problems：
1. Required packages like azure-mgmt-resource are missing from the built artifact. SBOM team use [component-detection](https://github.com/microsoft/component-detection/blob/main/src/Microsoft.ComponentDetection.Detectors/pip/PipComponentDetector.cs#L18) to detect python packages.
Open two issues in component-detection repo.
[Component detection only find the setup.py file in tools directory.](https://github.com/microsoft/component-detection/issues …
=> {CI} Generate SBOM manifest for built packages

src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt, src/azure-cli/setup.py
This PR aims to bump the version of Websocket-Client from `0.56.0` -> `1.3.1` which is a more recent & python3 compatible version of the library. The version of the WebSocket client  used inside the Azure-CLI (And more specifically, `WebSocketApplication`) relies on functionality from the python2 threading module that is no longer present in version 3. Any project explicitly using websocket-client & azure-cli currently have to use version `0.56.0` and any application using the `WebSocketApplication` from the websocket client will throw with: `AttributeError: 'Thread' object has no attribute 'isAlive'` on the websocket's teardown.
This change doesn't touch any of the Azure-CLI or extensions code & only changes the dependency version of websocket-client …
=> {Packaging} Update websocket-client for python3 compatibility

src/azure-cli-core/setup.py, src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt
Bump MSAL to 1.17.0 (https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/457).
The biggest benefit is that we get better error message for `RuntimeError: 0. The ID token is not yet valid` (https://github.com/Azure/azure-cli/issues/20388).
f
=> {Core} Bump MSAL to 1.17.0

src/azure-cli-core/azure/cli/core/auth/binary_cache.py, src/azure-cli-core/azure/cli/core/auth/identity.py
A refinement to https://github.com/Azure/azure-cli/pull/20722.
Instead of dumping MSAL HTTP cache to a file **every time Azure CLI exits**, MSAL HTTP cache is dumped to a file **only when the cache content is changed**. 
This significantly **reduces the number of disk write operations**, thus reduces the possibility of encountering a corrupted HTTP cache file (`pickle.UnpicklingError`, `EOFError`).
But, the limitation is that this solution only works when MSAL updates the HTTP cache with `__setitem__`. If MSAL directly edits the content of cache items, the operation will slip under `BinaryCache`'s radar.
=> {Core} Introduce `BinaryCache` for MSAL HTTP cache

src/azure-cli/azure/cli/command_modules/cosmosdb/_params.py
Precisely described the validation rules applied by Cosmos DB Resource Provider when it processes this request.
=> {CosmosDB} Improve help for failover-priority-change command

src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt
Address concerns from https://github.com/microsoft/component-detection/issues/74#issuecomment-1061256973
`applicationinsights` dependency was introduced by https://github.com/Azure/azure-cli/pull/9785, but it has different versions on different platforms for unknown reason, possible simply due to a mistake:
https://github.com/Azure/azure-cli/blob/f29ea8ca7355095c5a964437bf37152dad305aa8/src/azure-cli/requirements.py3.windows.txt#L2
https://github.com/Azure/azure-cli/blob/f29ea8ca7355095c5a964437bf37152dad305aa8/src/azure-cli/requirements.py3.Linux.txt#L2
https://github.com/Azure/azure-cli/blob/f29ea8ca7355095c5a964437bf37152dad305aa8/src/azure-cli/requirements.py3.Darwin.txt#L2
This PR unifies `applicationinsights` versions.
`wrapt` is an indirect dependency:
```
> …
```
=> {Packaging} Unify `applicationinsights` versions and remove `wrapt`

src/azure-cli-core/azure/cli/core/util.py
Commit https://github.com/MicrosoftDocs/azure-docs-cli/commit/f8bda76af6ad42ebbc6c8bf1395dde0931869813 removed the referred anchor.
=> {Core} Fix broken anchor in URI referring to quoting issues

src/azure-cli/azure/cli/command_modules/appservice/_help.py
This fixes a typo in an example for [`az webapp deploy`](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-deploy) in its reference doc.
N/A
resolves #21439
=> [App Service] Fix #21439: `az webapp deploy`: Fix `--async` argument value in help message

src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_agentpool_decorator.py
Refactor `aks nodepool add` - part 2.
- Add  set_up_upgrade_settings.
> "covered_lines": 97,
> "num_statements": 103,
> "percent_covered": 94.1747572815534,
> "percent_covered_display": "94",
> "missing_lines": 6,
---
=> {AKS} Refactor aks nodepool add - part 2

scripts/release/rpm/Dockerfile.mariner
According to the mail conversation, Mariner 1.0 is a little outdated. Mariner 2.0 is latest. As public access to cblmariner2preview.azurecr.io has been granted, we should be able to access Mariner 2.0 anonymously.
Email: _Use Mariner 2.0 to build Azure CLI_
=> {Packaging} Build RPM with Mariner 2.0 image

src/azure-cli/azure/cli/command_modules/role/custom.py
- Fix IcM [294632821](https://portal.microsofticm.com/imp/v3/incidents/details/294632821/home), [294421779](https://portal.microsofticm.com/imp/v3/incidents/details/294421779/home)
- Fix #21609
When using `az ad sp create-for-rbac` to create a self-signed certificate in keyvault, Azure CLI by default creates the certificate with validity of `years * 12 + 1`, where `--years` is 1 by default. So the default validity is 13 month.
If a user also has a preview built-in [Azure Policy](https://docs.microsoft.com/en-us/azure/governance/policy/overview) [`Certificates_ValidityPeriod`](https://github.com/Azure/azure-policy/blob/d58633adb7f5c8764cb0541ff0b6cfbf6ba24ae0/built-in-policies/policyDefinitions/Key%20Vault/Certificates_ValidityPeriod.json#L43-L44) configured which enforces the certificate …
=> [Role] BREAKING CHANGE: `az ad sp create-for-rbac`: Change `validity_months` to `years * 12`

src/azure-cli/azure/cli/command_modules/vm/_params.py
--enable-bursting enables/disables _on-demand_ bursting. It does not enable/disable _credit-based_ bursting. Change help text to avoid misinterpretation.
az disk update --help | grep burst
N/A
---
=> [Compute] Change help info of `--enable-bursting` to flag it is for on-demand only

src/azure-cli/azure/cli/command_modules/appservice/_params.py, src/azure-cli/azure/cli/command_modules/appservice/commands.py, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_vnetDelegation.yaml, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_vnetE2E.yaml, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_vnetRouteAll.yaml, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_vnetSameName.yaml, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_vnetSubnetId.yaml
Fixes #21574 , where an unhelpful error + stack trace would be thrown when the command is run on an app that doesn't exist. 
Also extends the preexisting `az functionapp vnet-integration add` validator to cover the webapp equivalent as well. As a result `az webapp vnet-integration add` now validates vnet/webapp locations as well. 
---
=> [App Service] Fix #21574: `az webapp vnet-integration add`: Fix the AttributeError that 'NoneType' object has no attribute 'server_farm_id'

src/azure-cli/azure/cli/command_modules/role/_graph_objects.py, src/azure-cli/azure/cli/command_modules/role/custom.py, src/azure-cli/azure/cli/command_modules/role/tests/latest/test_graph.py
Similar with #21525 
Refine code and tests for ms graph group
---
=> {Graph} Refine code and tests for ms graph group

src/azure-cli-core/setup.py, src/azure-cli/setup.py
Similar to https://github.com/microsoft/knack/pull/257, use proper [PEP 508 environment marker](https://peps.python.org/pep-0508/#environment-markers) for dependencies.
Dependencies added by `DEPENDENCIES.append()` are only added to the list of requirements if the `setup.py` is executed. However, `azure-cli` and `azure-cli-core` are being distributed as a wheel packages and `setup.py` is not executed when installing a wheel package. Instead, dependencies are translated into `azure_cli-2.34.1-py3-none-any.whl/azure_cli-2.34.1.dist-info/METADATA` when building wheels:
```
Requires-Dist: argcomplete
Requires-Dist: jmespath
Requires-Dist: pygments
Requires-Dist: pyyaml
Requires-Dist: tabulate
```
What's in the wheel is determined by the packaging system, which is like taking a …
=> {Packaging} Use proper PEP 508 environment marker for dependencies

azure-pipelines.yml, scripts/release/rpm/Dockerfile.ubi8, scripts/release/rpm/pipeline.sh
- Based on https://github.com/Azure/azure-cli/pull/20918
- Fix #https://github.com/Azure/azure-cli/issues/20719
Since we have get authorization to use [Red Hat Universal Base Image 8](https://catalog.redhat.com/software/containers/ubi8/ubi/5c359854d70cc534b3a3784e), we can now use it, instead of using CentOS Stream 8 which is an upstream of  Red Hat Enterprise Linux 8 and may not be stable.
=> {Packaging} Use Red Hat Universal Base Image 8 to build `el8` RPM package

scripts/ci/check_pull_request.py
Now we check both title and history notes.
Either of them failed, will exit(1) 
exit(1) means there was some issue / error / problem and that is why the program is exiting. 
Bu if edit history notes, we can ignore title check result and just give a warning message.
---
=> {CI} Ignore title check result if edit history notes

src/azure-cli/azure/cli/command_modules/appservice/_params.py, src/azure-cli/azure/cli/command_modules/appservice/static_sites.py, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_staticapp_commands_thru_mock.py
Removes the following properties from the staticwebapp objects returned from the create, show, list, and update commands: 
- allowConfigFileUpdates
- buildProperties
- contentDistributionEndpoint
- keyVaultReferenceIdentity
- kind                                                                                           
- privateEndpointConnections
- repositoryToken
- stagingEnvironmentPolicy
- templateProperties
- sku.capabilities
- sku.capacity
- sku.family
- sku.locations
- sku.size
- sku.skuCapacity
Also changes some default arguments for `az staticwebapp create` to fix #20830
[App Service] `az staticwebapp create` : Change default output location and API location to `None`. Change default app location to "/". Remove unnecessary …
=> [App Service] `az staticwebapp` : Fix #20830 and remove unneeded properties from staticwebapp output

src/azure-cli/azure/cli/command_modules/apim/custom.py
Fixes https://github.com/Azure/azure-cli/issues/21706
---
=> {APIM} Fixes help message description

src/azure-cli/azure/cli/command_modules/appservice/custom.py, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands_thru_mock.py
Correctly pass the slot name through to update app settings when the zip has been uploaded. 
Run the following command with a function against a Linux Consumption plan function with a production and a staging slot.
`az functionapp deployment source config-zip -g "<resource group>" -n "<function app name>" --src "MyFunctionCode.Zip" --subscription "<subscription name>" --slot "staging"`
Before this fix, the deployment targets the production slot no matter what.  After this fix the function should be correctly deployed.
=> [App Service] Fix #20240: `az functionapp deployment source config-zip`: Fix the bug that the parameter `--slot` doesn't work

src/azure-cli/azure/cli/command_modules/acs/_validators.py, src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py, src/azure-cli/azure/cli/command_modules/acs/custom.py, src/azure-cli/azure/cli/command_modules/acs/decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_validators.py
This PR aims to fix the extraction of custom headers and add an option to allow multiple values to be appended to the same key. 
Example: after the change, given the following option
```
--aks-custom-headers AKSHTTPCustomFeatures=Microsoft.ContainerService/Feature1,AKSHTTPCustomFeatures=Microsoft.ContainerService/Feature2
```
the request header would be
```yaml
- request:
headers:
AKSHTTPCustomFeatures: 
- Microsoft.ContainerService/Feature1,Microsoft.ContainerService/Feature2
```
which used to be
```yaml
- request:
headers:
AKSHTTPCustomFeatures: 
- Microsoft.ContainerService/Feature2
```
[Component Name 2] `az command b`: Add some …
=> {AKS} Fix custom header extraction issue

src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/test_pool_commands.py
Using `is` for literal comparison is incorrect and results in `SyntaxWarning` during tests:
```
> azdev test
d:\cli\azure-cli\src\azure-cli\azure\cli\command_modules\netappfiles\tests\latest\test_pool_commands.py:34: SyntaxWarning: "is" with a literal. Did you mean "=="?
assert len(pool_list) is 1
d:\cli\azure-cli\src\azure-cli\azure\cli\command_modules\netappfiles\tests\latest\test_pool_commands.py:38: SyntaxWarning: "is" with a literal. Did you mean "=="?
assert len(pool_list) is 0
d:\cli\azure-cli\src\azure-cli\azure\cli\command_modules\netappfiles\tests\latest\test_pool_commands.py:49: SyntaxWarning: "is" with a literal. Did you mean "=="?
assert len(pool_list) is 0
```
=> {netappfiles} Use `==` for literal comparison

src/azure-cli/azure/cli/command_modules/acs/_helpers.py, src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py, src/azure-cli/azure/cli/command_modules/acs/base_decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_agentpool_decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_base_decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_helpers.py
Introduce a new abstraction layer base decorator, and adjust the details of the agent pool decorator to facilitate subsequent reuse by the managed cluster decorator.
---
=> {AKS} Refactor aks nodepool add - part 4

src/azure-cli/azure/cli/command_modules/acs/_consts.py, src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py, src/azure-cli/azure/cli/command_modules/acs/base_decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_agentpool_decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_base_decorator.py
Introduce a new abstraction layer base decorator, and adjust the details of the agent pool decorator to facilitate subsequent reuse by the managed cluster decorator.
---
=> {AKS} Refactor aks nodepool add - part 5

Dockerfile
CVE-2022-0778 was identified on OpenSSL library: https://nvd.nist.gov/vuln/detail/CVE-2022-0778
Alpine Linux 3.15 has this vulnerability and fixed it in 3.15.1:
https://alpinelinux.org/posts/Alpine-3.15.1-released.html
> This release includes a fix for openssl [CVE-2022-0778](https://security.alpinelinux.org/vuln/CVE-2022-0778).
See https://github.com/alpinelinux/docker-alpine/issues/243
Python 3.10.2 image is no longer updated and 3.10.3 updated its base Alpine Linux image to 3.15.1:
```
> docker run -it --rm python:3.10.3-alpine3.15 cat /etc/os-release
Unable to find image 'python:3.10.3-alpine3.15' locally
3.10.3-alpine3.15: Pulling from library/python
Digest: sha256:7099d74f22c2d7a597875c3084e840846ca294ad01da1e845b0154100a6ac15b
Status: Downloaded newer image for …
```
=> [Packaging] Bump Python image to `3.10.3-alpine3.15`

src/azure-cli/azure/cli/command_modules/role/__init__.py
Finalize the version with Microsoft Graph support to 2.37.0.
=> {Graph} Finalize the version with Microsoft Graph support to 2.37.0

src/azure-cli/azure/cli/command_modules/appservice/_help.py
fixes https://github.com/Azure/azure-cli/issues/10904 
Fix for --scope resourcegroup example
---
=> {WebApp} fix for --scope resourcegroup example

.azure-pipelines/templates/automation_test.yml, azure-pipelines.yml
When shallow fetch is enabled in ADO
https://dev.azure.com/azure-sdk/public/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=246&view=Tab_Tasks
even though its help message says "each remote branch"
the actual commands is 
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1456114&view=logs&j=74095127-2a27-5370-37ed-15a4193f243f&t=3c34c09e-4c00-5f6e-f049-f62c206540eb
```
git init "/home/vsts/work/1/s"
git remote add origin https://github.com/Azure/azure-cli
git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin --depth=1 +bf1b698fea11904607dfff3559b6feb2d5539b5f:refs/remotes/origin/bf1b698fea11904607dfff3559b6feb2d5539b5f
git -c http.extraheader="AUTHORIZATION: …
```
=> {CI} Explicitly fetch PR target branch

src/azure-cli/azure/cli/command_modules/role/custom.py, src/azure-cli/azure/cli/command_modules/role/tests/latest/test_role.py
When creating a self-signed certificate in commands such as `az ad sp create-for-rbac` or `az ad app credential reset`:
1. Create a `temp_file` and use its name for `creds_file`.
2. The certificate and private key are saved to `cert_file` and `key_file`.
3. The contents of `cert_file` and `key_file` are read back and combined into `creds_file`.
4. Change the mode of `creds_file` to `0o600` (`rw-------`).
This procedure exposes problems:
According to https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp:
> Unlike `TemporaryFile()`, the user of `mkstemp()` is responsible for deleting the temporary file when done with it.
At least, the temp file made by `mkstemp` is empty with permission `0o600`, so it doesn't leak any credential. It's just it will be left as trash.
**Solution**: …
=> {Role} Secure `_create_self_signed_cert`

build_scripts/windows/scripts/build.cmd
Fix #21734
#7633 says:
> Use regular python instead of embed version. This should unblock ML extension
This PR switched from using Python from https://www.python.org/ftp/python/3.6.5/python-3.6.5-embed-win32.zip to https://azurecliprod.blob.core.windows.net/util/Python366-32.zip. We don't exactly know what the original ML extension problem is and why the change was made.
But according to our [internal knowledge base](https://microsoft.sharepoint.com/teams/IoTToolingTeam/_layouts/OneNote.aspx?id=%2Fteams%2FIoTToolingTeam%2FShared%20Documents%2FAzure%20Management%20Experience%2FAzure%20Management%20Experience&wd=target%28AZ%20CLI%2FKnowledge%20base.one%7C18BC64EE-9328-497D-804E-6436006CA9A5%2FUpdate%20Embeddable%20Python%20in%20MSI%7C690C9507-65DA-49BE-BA5E-B963BF48F755%2F%29 …
=> [Packaging] Bump MSI embedded Python to 3.10.3

scripts/ci/test_ref_doc.sh
CI failed:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1459759&view=logs&j=715ff7e7-0433-5a80-bbc9-ca9609d2bc48&t=7f464a6b-d59f-566f-20bd-0d339d7433d8&l=831
```
2022-03-25T03:56:05.2026491Z Extension error:
2022-03-25T03:56:05.2028477Z Could not import extension sphinx.builders.latex (exception: cannot import name 'contextfunction' from 'jinja2' (/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/jinja2/__init__.py))
```
This is because `Jinja2` released a new version yesterday which introduced breaking changes, but `sphinx` doesn't have version limits on `Jinja2`, causing the latest `Jinja2` being installed.
This PR is only a workaround, the final solution would be to update `sphinx` to newer versions.
- …
=> {CI} Pin `Jinja2` to 3.0.3

azure-pipelines.yml
Mariner 2.0 has `rpmbuild` 4.17.0 which is very slow while building the RPM (https://github.com/Azure/azure-cli/issues/21820).
This PR adds a `condition` to `BuildRpmPackageMariner` job so that Mariner RPM is not build on `PullRequest` CI.
=> {Packaging} Not build Mariner RPM on PullRequest CI

scripts/ci/build.sh
Fix CI failure: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1464089&view=logs&j=c846b3e8-69b8-5dbd-1a39-4905d81e6a95&t=9ebb608a-8a51-5834-bad0-46e2c03d2282
```
> api_file = open(schemapath, 'r')
E FileNotFoundError: [Errno 2] No such file or directory: '/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/apim/tests/latest/gql_schema.gql'
```
Caused by https://github.com/Azure/azure-cli/pull/21585.
=> {APIM} Add `*.gql` to test packages

linter_exclusions.yml, src/azure-cli/azure/cli/command_modules/acr/_help.py, src/azure-cli/azure/cli/command_modules/acr/_params.py, src/azure-cli/azure/cli/command_modules/acr/commands.py
This PR deprecates the preview `az acr manifest metadata` command group and moves the 3 commands into the parent `az acr manifest` command group. This is essentially a renaming or reorganization of the commands after receiving customer feedback.  **There is no new functionality added**, just name changes.
helps['acr manifest show-metadata'] = """
type: command
short-summary: Get the metadata of an artifact in an Azure Container Registry.
examples:
- name: Get the metadata of the tag 'hello-world:latest'.
text: az acr manifest show-metadata -r MyRegistry -n hello-world:latest
- name: Get the metadata of the tag 'hello-world:latest'.
text: az acr manifest show-metadata MyRegistry.azurecr.io/hello-world:latest
- name: Get the metadata of the manifest …
=> [ACR] Deprecate preview command group and implement same commands in parent command group

src/azure-cli/azure/cli/command_modules/serviceconnector/custom.py
Fix https://github.com/Azure/azure-cli/pull/21766#discussion_r836293266
#21766 together with #21763 causes CI failure:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1464664&view=logs&j=36dd4138-4d53-5e46-00d9-e5cd9744be05&t=1cf3879c-0a42-5ccd-7693-7a4781d739d8&l=94
```
src/azure-cli/azure/cli/command_modules/serviceconnector/custom.py:244:0: R0914: Too many local variables (26/25) (too-many-locals)
```
These PRs' CIs are run separately, but the final merged commit exceeds local variable limitation 25.
=> {Service Connector} Disable `too-many-locals` for pylint

src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py
https://github.com/Azure/azure-cli/pull/21661 added this unused line for unknown reason and it breaks CI (https://github.com/Azure/azure-cli/pull/21661#discussion_r836079211).
Remove it to unblock CI.
=> {AKS} Remove `from tkinter import FALSE` to unblock CI

src/azure-cli/azure/cli/command_modules/storage/_help.py, src/azure-cli/azure/cli/command_modules/storage/commands.py
`az storage remove` needs GA
Add an example for `az storage blob copy start`
---
=> {Storage} Some small feature asks

src/azure-cli/azure/cli/command_modules/network/tests/latest/test_dns_commands.py, src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone1.txt, src/azure-cli/azure/cli/command_modules/network/zone_file/parse_zone_file.py
This is necessary to allow hyphenated SRV records targets to be successfully imported.  Today, such imports fail, as described in #21716 
Without the fix, importing this valid zone file (`db.example.com`) will fail:
```
@                 3600 IN SOA  ns admin ( 2014010800 ; Serial
3600       ; Refresh
3600       ; Retry
3600       ; Expire
300 )      ; Minimum TTL
_sip._tcp.pool 300 IN SRV 20 10 5060 valid-target-1
_sip._tcp.pool 300 IN SRV 20 10 5060 valid-target-2
_sip._tcp.pool 300 IN SRV 20 10 5060 valid-target-3
```
Failure output from import using `az network private-dns zone import --resource-group <RG NAME> --name example.com --file-name db.example.com`:
```
== BEGINNING ZONE IMPORT: example.com ==
(1/4) Imported 1 records of type 'soa' and name …
```
=> [Network] Fix #21716: `az network private-dns zone import`: Allow hyphenated SRV records

src/azure-cli/azure/cli/command_modules/sql/_params.py, src/azure-cli/azure/cli/command_modules/sql/custom.py, src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_db_short_term_retention.yaml, src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
Make diffbackup_hours optional in sql db str-policy set.
We are releasing public preview feature short term retention parity for Very Large Database (VLDB) on May 1st .
We recently noticed a bug in Cli which requires differential backup interval as a required parameter. ([SQL] 'az sql db str-policy set/show': Add Set and Show ShortTermRetentionPolicy by lululilliancoding · Pull Request #14919 · Azure/azure-cli (github.com).
We are changing the parameter diffbackup_hours to be an optional parameter
sql db str-policy set -g WestUS2ResourceGroup -s lillian-westus2-server -n ps5691 --retention-days 7
[SQL] `az command sql db str-policy set`: Make `diffbackup_hours` parameter optional
--- …
=> [SQL] `az command sql db str-policy set`: Make `--diffbackup-hours` parameter optional

src/azure-cli/azure/cli/command_modules/resource/_bicep.py
Azure CLI relies on the requests python package, which allows users to set custom CA bundle paths through two environment variables: `CURL_CA_BUNDLE` and `REQUESTS_CA_BUNDLE`. https://2.python-requests.org/en/master/user/advanced/#ssl-cert-verification
This is useful for cases where the host is behind a MITM proxy that re-signs all SSL traffic for DPI, or due to a corporate policy that defines which CA roots are to be trusted.
Enforcing a hard-coded bundle, like the one provided by the certifi package, only leads users under similar use cases to modify the Python site packages files, which is meant to be controlled only by the package manager and thus it is not a good practice to configure any Python solution.
The proposed change here leverages Python `setdefault` …
=> [ARM] Fix #20842: `az bicep`: Fix to use requests environment variables for CA bundle

src/azure-cli/azure/cli/command_modules/appservice/commands.py, src/azure-cli/azure/cli/command_modules/appservice/static_sites.py, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_staticapp_commands_thru_mock.py
Fixes #21186.
Applies to the commands:
- `az staticwebapp identity assign`
- `az staticwebapp hostname set`
- `az staticwebapp create`
Also fixes #21465 for `az staticwebapp update`
[App Service] `az staticwebapp identity assign`, `az staticwebapp hostname set`, `az staticwebapp create`: Fix #21186: Show detailed error message instead of "bad request"
[App Service] `az staticwebapp update`: Fix #21465: Allow specifying static web app resource group
---
=> [App Service] `az staticwebapp`: Fix #21186: Show detailed error message instead of "bad request"

src/azure-cli/azure/cli/command_modules/resource/_params.py
See issue https://github.com/Azure/azure-cli/issues/21789
"--subscription" parameter works properly, so removed ignore.
---
=> [ARM] `az policy assignment create`: Support `--subscription` parameter

src/azure-cli/azure/cli/command_modules/appservice/custom.py, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands_thru_mock.py
=> [App Service] Fix #21728: `az webapp deployment github-actions add`: Allow passing in runtime with colon delimiter

src/azure-cli-core/azure/cli/core/_session.py
Fix Pylint error:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1472599&view=logs&j=36dd4138-4d53-5e46-00d9-e5cd9744be05&t=1cf3879c-0a42-5ccd-7693-7a4781d739d8
```
ERROR: ************* Module azure.cli.core._session
src/azure-cli-core/azure/cli/core/_session.py:11:0: E0611: No name 'abc' in module 'collections.abc' (no-name-in-module)
```
By comparing this task with a previous successful one like https://dev.azure.com/azure-sdk/public/_build/results?buildId=1470973&view=logs&j=36dd4138-4d53-5e46-00d9-e5cd9744be05&t=1b5debc0-fc94-5266-47f5-73158590dd32, I found:
- There is no version update on `pylint`, `astroid`, etc
- The only difference is Python on the agent is upgraded from 3.10.2 to 3.10.4, but according to …
=> {pylint} Fix `collections.abc` import statement

src/azure-cli/azure/cli/command_modules/appservice/_help.py, src/azure-cli/azure/cli/command_modules/appservice/_params.py, src/azure-cli/azure/cli/command_modules/appservice/appservice_environment.py
ASEv3 support has been pending azure-mgmt-web update to 5.0.0+. With update to 6.1.0 we can unblock this scenario.
az appservice ase create -n MyASEv3Name -g ASEv3ResourceGroup --vnet-name MyASEv3VirtualNetwork --subnet MyASEv3Subnet --kind asev3 --virtual-ip-type Internal
az appservice ase create-inbound-services -n MyASEv3Name -g ASEv3ResourceGroup --vnet-name MyASEv3VirtualNetwork --subnet MyASEv3Subnet
Result: Azure private DNS zone is created with the necessary inbound ILB ip DNS records configured and zone linked to vnet.
---
=> [App Service] `az appservice ase create-inbound-services`: Add support for Azure private DNS zone creation in ASEv3

azure-pipelines.yml
#20918 changed the RPM artifact name from `yum` to `rpm-centos7` to better reflect its content (an RPM built by CentOS 7), but this requires lots of changes in the release pipeline, as well as the RPM archive path, such as https://azurecliprod.blob.core.windows.net/archive/20220301.49/yum/azure-cli-2.34.1-1.el7.x86_64.rpm
This PR reverts the change and keep the name `yum` for backward compatibility, even though it is a not good name.
=> {Packaging} Revert `BuildRpmPackageCentOS7.ArtifactName` to `yum`

src/azure-cli/azure/cli/command_modules/iot/commands.py
Fix https://github.com/Azure/azure-cli/pull/20682#discussion_r840232833
`az iot dps access-policy` command group's deprecation in 2.35.0 caused lots of linter failure after upgrading Azure CLI to 2.35.0:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1475423&view=logs&j=168ccbe3-da49-5c0b-6478-08f7016e4bf5&t=10a595be-4223-5cc7-9a73-012871b6eaee
```
-  FAIL - HIGH severity: faulty_help_example_parameters_rule
Help-Entry: `iot dps access-policy create` - 
There is a violation:
"az iot dps access-policy create --dps-name MyDps --resource-group MyResourceGroup --name MyPolicy --rights EnrollmentRead" is not a valid command.
argument _subcommand: unknown parser 'access-policy' (choices: list, show, create, delete, update, linked-hub, certificate, policy).
...
-  FAIL - HIGH …
```
=> {iot} `az iot dps access-policy`: Defer its deprecation

src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py, src/azure-cli/azure/cli/command_modules/serviceconnector/custom.py, src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_webapp_sql_e2e.yaml, src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_webapp_webpubsub_e2e.yaml, src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/test_springcloud_connection_scenario.py, src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/test_webpp_connection_scenario.py
Adds supports for more target resources: sql and webpubsub.
* `az webapp connection create sql`
* `az webapp connection create webpubsub`
add test: test_webapp_sql_e2e, test_webapp_webpubsub_e2e
---
=> [ServiceConnector] `az webapp connection`: Add command `create sql/webpubsub` to support more target resources 

azure-pipelines.yml, scripts/ci/test_extensions.sh
With the increasing number of Azure CLI extensions, `TestExtensionsLoading` now fails with 
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1475520&view=logs&j=dec4b9a0-9c0f-52f1-3e08-6456fce2bf62
```
##[error]The job running on agent [Azure Pipelines](https://dev.azure.com/azure-sdk/29ec6040-b234-4e31-b139-33dc4287b756/_settings/agentqueues?poolId=&queueId=57) 96 ran longer than the maximum time of 20 minutes. For more information, see https://go.microsoft.com/fwlink/?linkid=2077134
Pool: Azure Pipelines
Image: ubuntu-20.04
Agent: Azure Pipelines 96
Started: Today at 1:13 PM
Duration: 20m 7s
```
This PR increases the timeout threshold.
=> {CI} Increase `TestExtensionsLoading`'s timeout

src/azure-cli/azure/cli/command_modules/network/custom.py
Closes: https://github.com/Azure/azure-cli/issues/21845
fix public IP address validate issue:
The CLI documentation for Azure Route Server lists location and public IP as optional, whereas public documentation and the portal UI indicate both are required. We have seen one customer case where this guide was cited as being incorrect.
To Reproduce*
Attempt to deploy a new ARS via CLI and leave out Public IP and you will get an error:
az network routeserver create --resource-group xxx --name xxx --hosted-subnet xxxx
---
This checklist is used to make sure that common guidelines for …
=> [Network] Fix #21845: `az network routeserver create` required `--public-ip-address` argument

src/azure-cli/azure/cli/command_modules/network/custom.py
Closes: https://github.com/Azure/azure-cli/issues/21829
az network traffic-manager endpoint update --resource-group {} --profile-name {} --name {} --endpoint-status {} will show error as below:
No value for given attribute
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\ …
=> [Network] Fix #21829: `az network traffic-manager endpoint update` required `--type` argument

Dockerfile, build_scripts/windows/scripts/build.cmd, scripts/release/debian/build.sh
Use latest Python:
1. Docker image, Windows MSI: 3.10.4
2. Debian/Ubuntu: 3.8.13
=> {Packaging} Bump Python version to 3.10.4 and 3.8.13

src/azure-cli/azure/cli/command_modules/iot/_help.py, src/azure-cli/azure/cli/command_modules/iot/_params.py, src/azure-cli/azure/cli/command_modules/iot/commands.py, src/azure-cli/azure/cli/command_modules/iot/tests/hybrid_2020_09_01/test_iot_dps_commands.py, src/azure-cli/azure/cli/command_modules/iot/tests/latest/test_iot_dps_commands.py
Replace access-policy with policy in `az iot dps` to align better with other command groups.
The following command was run to test:
`azdev test test_dps_lifecycle test_dps_certificate_lifecycle test_dps_linked_hub_lifecycle`
In addition, the entire iot module was tested:
`azdev test iot`
The command group `az iot dps access-policy` has been deprecated and replaced with `az iot dps policy` .
Related prs:
https://github.com/Azure/azure-cli/pull/20682
https://github.com/Azure/azure-cli/pull/21892
---
=> [IoT] BREAKING CHANGE: `iot dps access-policy`: Deprecate access-policy in favor of policy

src/azure-cli/azure/cli/command_modules/appconfig/_kv_helpers.py, src/azure-cli/azure/cli/command_modules/appconfig/_params.py
- Fixes [#14012055](https://msazure.visualstudio.com/Azure%20AppConfig/_workitems/edit/14012055) Fix feature flag import for missing description when using 'appconfig/kvset' profile.
- Updates help text for a couple of arguments.
---
=> [App Config] Fix #14012055: Fix feature flag import for missing description when using 'appconfig/kvset' profile.

src/azure-cli-core/azure/cli/core/util.py
`rmtree_with_retry` now doesn't ignore `FileNotFoundError`. Then though the directory doesn't exist, `rmtree_with_retry` will retry several times (like in https://github.com/Azure/azure-cli/issues/21964), which is definitely not what we want.
This PR ignores `FileNotFoundError` in `rmtree_with_retry`.
=> {Core} Ignore `FileNotFoundError` in `rmtree_with_retry`

azure-pipelines.yml, scripts/release/debian/pipeline.sh
Close https://github.com/Azure/azure-cli/issues/21857
As the next LTS (Long-Term Support) version of Ubuntu - 22.04 Jammy Jellyfish will be released on April 21, 2022, we use the `devel` docker image to build the preview package.
=> [Packaging] Add Ubuntu 22.04 Jammy Jellyfish support

src/azure-cli/azure/cli/command_modules/netappfiles/custom.py, src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/test_snapshot_commands.py
Fix https://github.com/Azure/azure-cli/issues/21954
`test_restore_file` added by https://github.com/Azure/azure-cli/pull/21712 randomly fails:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1485372&view=logs&j=c846b3e8-69b8-5dbd-1a39-4905d81e6a95&t=9ebb608a-8a51-5834-bad0-46e2c03d2282
```
2022-04-06T09:12:24.1762149Z =================================== FAILURES ===================================
2022-04-06T09:12:24.1762678Z ________ AzureNetAppFilesSnapshotServiceScenarioTest.test_restore_file _________
2022-04-06T09:12:24.1763782Z [gw0] linux -- Python 3.8.13 /opt/az/bin/python3
2022-04-06T09:12:24.1764428Z /opt/az/lib/python3.8/site-packages/azure/cli/testsdk/base.py:139: in tearDown
2022-04-06T09:12:24.1764907Z     super(ScenarioTest, self).tearDown() …
```
=> {netappfiles} Return the result of `SnapshotsOperations.begin_restore_files`

src/azure-cli/azure/cli/command_modules/storage/operations/blob.py
Previously would still use block size of 4MB for large files which results in more than 50,000 blocks.  (ErrorCode:BlockListTooLong)
Use a file larger than 200GB and `az storage blob upload -f {file_path} -c {container_name} -n {blob_name}
Should succeed
[Storage] Fix #21914: `az storage blob upload`: Make block size larger (100MB) for large files (>200GB)
---
=> [Storage] Fix #21914: `az storage blob upload`: Make block size larger (100MB) for large files (>200GB)

README.md
Ubuntu edge builds hasn't been updated since https://github.com/Azure/azure-cli/pull/13597. Now we release edge builds for Ubuntu Focal, Impish, Jammy, el8.
=> {Packaging} Release edge builds for Ubuntu Focal, Impish, Jammy, el8

src/azure-cli/azure/cli/command_modules/acs/custom.py
BugFix: Keep aad profile in PUT request of ManagedCluster. Modified commands are
* `az aks scale`
* `az aks upgrade`
* `az aks enable-addons`
* `az aks disable-addons`
May refer sibling PR [#4638](https://github.com/Azure/azure-cli-extensions/pull/4638) in aks-preview.
---
=> {AKS} Keep aad profile in PUT request of ManagedCluster

src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_commands.py, src/azure-cli/azure/cli/command_modules/resource/tests/hybrid_2019_03_01/test_resource.py, src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py, src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
This PR will speed up our test.
- Our list command is not pagination, it will get all the data.
That is why some recording files are very large.
And in test_show_built_in_policy, we choose to check the first resource instead of check all the resource to speed up.  
- We only mock time.sleep in azure-sdk-tools.
That's why if someone use sleep(xxx), it will not work.
https://github.com/Azure/azure-cli/blob/30216d0268f3491b8af2aa060d90a9e1f94f9b3c/src/azure-cli-testsdk/azure/cli/testsdk/scenario_tests/patches.py#L13
| Profile | Test Case | Before | After | Total saving time |
|--------|------------|---------|-------|--------------------|
| Latest | test_show_built_in_policy | 536.57s | 2.94s |  |
| 2019-03-01 | test_show_built_in_policy | 210.69s | 3.01s |  |
| Latest | …
=> {CI} Fix top N slowest Test

src/azure-cli/azure/cli/command_modules/appservice/_help.py, src/azure-cli/azure/cli/command_modules/appservice/_params.py, src/azure-cli/azure/cli/command_modules/appservice/static_sites.py
Fixes #21058
`az staticwebapp create -g {} -n {}`
---
=> [App Service] `az staticwebapp create`: Allow creating Static Web Apps not connected to a github repo

azure-pipelines-full-tests.yml, azure-pipelines.yml
Python versions used by Azure CLI packages:
1. Docker image, Windows MSI, Homebrew, PyPI: 3.10
2. Debian/Ubuntu DEB: 3.8
3. RPM: 3.6 (We can't drop it now as explained in https://github.com/Azure/azure-cli/pull/20865)
Since Azure CLI has fully supported Python 3.10, we can drop Python 3.9 to save some computation resource in Azure DevOps.
=> {CI} Drop Python 3.9 tests

azure-pipelines.yml, scripts/release/rpm/mariner.dockerfile, scripts/release/rpm/pipeline_mariner.sh
https://github.com/Azure/azure-cli/pull/21245 changed the Mariner image from 1.0 to 2.0.
According to the discussion we had today, Mariner 1.0 is still supported, so we should build images for both 1.0 and 2.0.
=> {Packaging} Build RPMs with Mariner 2.0 and 1.0 images

scripts/ci/build.sh
Git released a fix for CVE-2022-24765 today, making it impossible to run `git` commands in a directory that is not owned by the current user:
- https://github.blog/2022-04-12-git-security-vulnerability-announced/
- https://lore.kernel.org/git/xmqqv8veb5i6.fsf@gitster.g/
- https://nvd.nist.gov/vuln/detail/CVE-2022-24765
This fix was backported to `2.25.1-1ubuntu3.3` on Ubuntu Focal (https://launchpad.net/ubuntu/+source/git/1:2.25.1-1ubuntu3.3), causing CI failure:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1501323&view=logs&j=6a6a2ac0-ff7f-5678-6bf3-3c1acb42be6f&t=9fdc6347-bbbe-562a-7659-31ca5019fc37
```
git checkout src
fatal: unsafe repository ('/azure-cli' is owned by someone else)
To add an exception for this directory, call:
git config --global --add …
```
=> {CI} Add `/azure-cli` as `safe.directory` in docker container

src/azure-cli/azure/cli/command_modules/keyvault/_params.py, src/azure-cli/azure/cli/command_modules/keyvault/custom.py, src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_network_rule.yaml, src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
Fix #20520 `az keyvault network-rule`: Support removing multiple IP
`keyvault network-rule remove --ip-address {ip} {ip2} {ip3} --name {kv} --resource-group {rg}`
Delete multiple IP in one remove command
[Keyvault] Fix #20520 `az keyvault network-rule`: Support removing multiple IP
---
=> [Keyvault] Fix #20520 `az keyvault network-rule`: Support removing multiple IP

src/azure-cli/azure/cli/command_modules/acr/_params.py
Fixes Azure/azure-cli#22003 Updates the documentation for the --name parameter to have just lowercase.
---
=> Fix the description of --name parameter

src/azure-cli/azure/cli/command_modules/storage/_params.py
The `--methods` used to be defined in CLI manually, switch to use SDK Enum definition after SDK bump
---
=> [Storage] `az storage cors add`: Allow `PATCH` for `--methods`

src/azure-cli/azure/cli/command_modules/storage/_params_azure_stack.py, src/azure-cli/azure/cli/command_modules/storage/_validators.py, src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_table_main_scenario.yaml, src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_table_scenarios.py
Support `EdnType` for storage entity to fix #22018 
```
az storage entity insert -e PartitionKey=AAA RowKey=BBBB SizeInBytes=86222504922 SizeInBytes@odata.type=Edm.Int64 binaryProperty=AAECAwQF binaryProperty@odata.type=Edm.Binary -t ystable --account-name yssa --auth-mode login
```
```
az storage entity show --partition-key AAA --row-key BBBB -t ystable --account-name yssa --auth-mode login
```
---
=> [Storage] `az storage entity`: Support specifying `EdmType` for `--entity`

src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_batch_operations.py, src/azure-cli/azure/cli/command_modules/storage/util.py
Fix #21966 
Blob exist:
`az storage blob download-batch -d D:\tmp --pattern policy.json -s yscontainer --account-name yssa --auth-mode login`
Blob not eixst:
`az storage blob download-batch -d D:\tmp --pattern notexist.json -s yscontainer --account-name yssa --auth-mode login`
---
=> [Storage] Fix #21966: `az storage blob download-batch`: Fix failure when `--pattern` is blob name

src/azure-cli/azure/cli/command_modules/vm/_validators.py, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_quick_create_flexible_vmss.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_simple_orchestration_mode.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
This problem comes from ICM. Just as communicating with @fitzgeraldsteele on Teams, CLI needs to fix the following problems:
1. Error handling issue: `'NoneType' object has no attribute 'lower'` when creating Flex VMSS without `--vm-sku` parameter
2. When creating VM/VMSS, if the user does not pass in `--location`, the location from resource group can be used by default *(there is already this logic, but it is not triggered due to this bug)*
3. For creating VMSS, the information of VM profile and SKU should be either passed in or not passed in. Therefore, if users pass in the `--vm-sku` parameter, CLI needs to verify that users must also pass in the `--image` parameter
Because if the `--zone` parameter is added in the test, the recorded file will be very …
=> [Compute] `az vm create`: Fix the bug when creating Flex VMSS without SKU and VM profile

.azure-pipelines/templates/automation_test.yml, scripts/ci/automation_full_test.py
- Add --pytest-args "--durations=0" to record the time spent on each test.
- For module test and full test:
Every module not in serial_modules, enable group worker in pytest, pytest will spawn a number of workers processes equal to the number of available CPUs, and distribute the tests randomly across them.
- For incremental test:
Remain the same
- serial_modules: ['appservice', 'botservice', 'cloud', 'network', 'azure-cli-core', 'azure-cli-telemetry']
---
=> {CI} enable pytest group worker in module test and full test

src/azure-cli/azure/cli/command_modules/network/custom.py
Add hint to public-ip create with standard sku 
Description of the new feature
In the latest profile and the profiles that use the same api-version as latest profile, the default public IP used for creation with "az network public-ip create" will be changed from Basic to Standard. In advance of eventual breaking change, would like to add warning for users.
---
=> {Network} `az network public-ip create`: Add hint to use standard sku

src/azure-cli/azure/cli/command_modules/network/custom.py
Fixes: https://github.com/Azure/azure-cli/issues/22085
Fix 'str' object has no attribute 'is_default' issue
---
=> [Network] Fix #22085: `az network nsg rule create` has no attribute "is_default"

src/azure-cli/azure/cli/command_modules/vm/_validators.py
Fix: https://github.com/Azure/azure-cli/issues/21793
There are two problems with this issue:
1. `--edge-zone` parameter is not converted through `validate_edge_zone`, resulting in the following `InvalidTemplate` error reports:
```
{"error":{"code":"InvalidTemplate","message":"Deployment template parse failed: 'Error converting value "microsoftrrdclab1" to type 'Azure.Deployments.Core.Definitions.Resources.ResourceExtendedLocation'. Path ''.'."}}
```
This PR is used to fix this problem
2. After fixing the first problem, an error will still occur because creating Flex VMSS still does not support edge zone
```
{"code":"BadRequest","message":"{ "error": { "code": "InvalidParameter", "message": "Parameter 'extendedLocation' is not allowed.", "target": "extendedLocation" }}}
``` …
=> {Compute} `az vmss create --orchestration-mode flexible`: fix converting `--edge-zone` to template json 

src/azure-cli-core/azure/cli/core/auth/identity.py, src/azure-cli-core/azure/cli/core/tests/test_profile.py, src/azure-cli/azure/cli/command_modules/rdbms/_client_factory.py, src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt, src/azure-cli/setup.py
https://github.com/Azure/azure-cli/pull/22009 relies on the latest `msal-extensions` 1.0.0, but `azure-identity` will release a new version (https://github.com/Azure/azure-sdk-for-python/pull/24083) as early as 2020-04-22. This will miss our 2022-04-20 code freeze deadline and 2022-04-22 release schedule for [Apr 2022 sprint](https://github.com/Azure/azure-cli/milestone/117).
`rdbms` is the only module using `azure-identity`. https://github.com/Azure/azure-cli/pull/4908 first uses env vars to create `azure.common.credentials.ServicePrincipalCredentials` and passes the credential to client constructor. https://github.com/Azure/azure-cli/pull/17191 migrated to using `azure.identity.ClientSecretCredential`.
Since Azure CLI has migrated to MSAL (https://github.com/Azure/azure-cli/pull/19853), …
=> {RDBMS} Use `ServicePrincipalCredential` with environment credential

src/azure-cli-core/azure/cli/core/util.py, src/azure-cli-core/setup.py, src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt
We see users constantly creating duplicated issues of 
- https://github.com/Azure/azure-cli/issues/20278
- https://github.com/Azure/azure-cli/issues/20231
- https://github.com/Azure/azure-cli/issues/21010
But the root cause for these issues remains unknown.
`msal-extensions` has made these errors catch-able in https://github.com/AzureAD/microsoft-authentication-extensions-for-python/pull/108, but since `azure-identity` has pinned dependency `msal-extensions~=0.3.0`, ~~it is not possible for Azure CLI to use the latest `msal-extensions` which contains that improvement (https://github.com/Azure/azure-sdk-for-python/issues/23927).~~ the dependency on `azure-identity` is removed by https://github.com/Azure/azure-cli/pull/22124.
Raise an `OSError` at …
=> {Auth} Provide GitHub issue links for DPAPI errors

src/azure-cli/azure/cli/command_modules/netappfiles/custom.py, src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_nfsv3_with_no_export_policy_provided_is_successful.yaml, src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/test_volume_commands.py
A fix for creating a default export policy when creating a NFSv3 volume with no export policy provided.
---
=> {NetAppFiles} `az netappfiles volume create`: Fix default export policy creation for NFSv3 volumes

scripts/ci/build.sh
https://github.com/Azure/azure-cli/pull/22056 added some file types that are not included while building the test package:
- `data/assetTrack.ttml`
- `data/sampleIsmFile.ism`
causing CI to fail:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1523127&view=logs&jobId=47870e38-5a53-5929-70f9-c65c4a436be8&j=47870e38-5a53-5929-70f9-c65c4a436be8&t=4b4323e2-b1dc-59ac-6bbb-9f51b3f2dde3
```
ex = FileNotFoundError(2, 'No such file or directory')
def file_related_exception_handler(ex):
from azure.cli.core.azclierror import FileOperationError
if isinstance(ex, FileNotFoundError):
>           raise FileOperationError(ex, recommendation='Please check the file path.')
E           azure.cli.core.azclierror.FileOperationError: [Errno 2] No such file or directory: …
```
=> {CI} Include all files under `data` as `package_data`

src/azure-cli/azure/cli/command_modules/storage/_help.py, src/azure-cli/azure/cli/command_modules/storage/_params.py, src/azure-cli/azure/cli/command_modules/storage/commands.py, src/azure-cli/azure/cli/command_modules/storage/operations/blob.py, src/azure-cli/azure/cli/command_modules/storage/operations/fs_directory.py, src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_fs_directory_generate_sas_as_user.yaml, src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_fs_directory_generate_sas_full_uri.yaml, src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_adls_gen2_scenarios.py
Fix #21819,  use `az storage fs directory generate-sas` to generate SAS for directory, which is equivalent to `sr=d` and `sdd` is inferred from `name` param.
`az storage fs directory create --name dir1/dir2 --file-system <filesystem> --account-name  <account>`
`az storage fs directory generate-sas --name dir1/dir2 --file-system <filesystem> --account-name  <account>`
---
=> [Storage] Fix #21819: `az storage fs directory`: Add new command `generate-sas`

azure-pipelines.yml, scripts/release/debian/Dockerfile, scripts/release/debian/build.sh, scripts/release/debian/prepare.sh, scripts/release/debian/test_deb_package.py
Other packages are already running on Python 3.10:
1. Windows MSI 
2. Homebrew
3. PyPI
4. Docker image
DEB should also use latest Python 3.10. However, Python 3.10 can't be built on 
- Ubuntu 16.04 Xenial
- Debian 9 Stretch
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1526760&view=logs&j=91b655fa-e277-54b4-6e7f-39b6e68dea4d&t=21d122d2-92ba-55a1-c034-df1ef1abfc1e
```
2022-04-25T03:13:20.0783879Z Failed to build these modules:
2022-04-25T03:13:20.0785025Z _hashlib              _ssl                                     
2022-04-25T03:13:20.0785784Z 
2022-04-25T03:13:20.0786409Z 
2022-04-25T03:13:20.0787449Z Could not build the ssl module!
2022-04-25T03:13:20.0788592Z Python requires a OpenSSL 1.1.1 or newer
```
According to their official docs, both systems …
=> [Packaging] Bump embedded Python to 3.10 for deb packages

src/azure-cli/azure/cli/command_modules/vm/_alias.py
This change adds alias for VM images: Win2022Datacenter and Win2022AzureEditionCore.
Note: the word 'datacenter' is in all new images, so there is no reason to repeat it in each alias. I chose to remove it when introducing 'AzureEdition' to try and keep spacing similar to the original alias length.
az vm create -n MyVm -g MyResourceGroup --image Win2022AzureEditionCore
---
=> [Compute] `az vm image list`: Add new server version aliases `Win2022AzureEditionCore` for offline list

.github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/Feature_request.md, .github/ISSUE_TEMPLATE/Service_team_request.md, .github/pull_request_template.md
Now we use keyword to route issue and pr.
However, as more and more modules are managed, the misjudgment rate is also getting higher.
The misjudgment rate is many times larger than the omission rate.
The reasons for misjudgment:
1. The information in the Environment Summary can easily lead to misjudgment
https://github.com/Azure/azure-cli/issues/22224
https://github.com/Azure/azure-cli/issues/21751
https://github.com/Azure/azure-cli-extensions/issues/4562
3. Users description contains multiple keywords
https://github.com/Azure/azure-cli/issues/21822
4. The log pasted by the user contains multiple keywords
https://github.com/Azure/azure-cli/issues/21793
5. Fabric bot supports neither complex regex nor if/else conditional
In the future, az $command will be used for matching.
But this will …
=> {CI} Update issue and pr template

src/azure-cli/azure/cli/command_modules/cosmosdb/custom.py, src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_sql_container_update_analytical_store_migration.yaml, src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_sql_container_update_analytical_ttl.yaml, src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_sql_container_update_disable_analytics.yaml, src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/test_cosmosdb_commands.py
Fix `az cosmosdb sql container update` not picking up analytical-storage-ttl arg. This bug is due to code here lines 522-524 https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/cosmosdb/custom.py . In the case when analytical-storage-ttl is the only container property specified the function will prematurely return without actually updating the value. In this scenario, users are unable to update analytical-storage-ttl using the sql cli. 
CosmosDB has recently GAed the capability for users to disable analytics by setting the analytical-storage-ttl to 0 and enable analytics for existing collections by specifying an analytical-storage-ttl. Therefore, ensuring customers are able to update the analytical-storage-ttl of their containers is …
=> [CosmosDB] `az cosmosdb sql container update`: Fix bug to accept analyticalStorageTTL arg

src/azure-cli/azure/cli/command_modules/storage/operations/queue.py
"az storage message get" crashes when there are no messages in the queue.
Debug error output:
File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/init.py", line 328, in call
return self.handler(*args, **kwargs)
File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
return op(**command_args)
File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/storage/operations/queue.py", line 86, in receive_messages
return list(next(page_iter))
File "/opt/az/lib/python3.8/site-packages/azure/core/paging.py", line 84, in next
self.continuation_token, self._current_page = self._extract_data(self._response)
File "/opt/az/lib/python3.8/site-packages/azure/multiapi/storagev2/queue/v2018_03_28/_models.py", line 288, in …
=> {QueueStorage} Fixes Azure/azure-cli#22268

src/azure-cli/azure/cli/command_modules/network/custom.py
> In the latest profile and the profiles that use the same api-version as latest profile, the default public IP used for creation for an LB frontend with "az network lb create" and/or "az network lb frontend-ip create" will be changed from Basic to Standard. In advance of eventual breaking change, would like to add warning for users.
---
=> [Network] `az network lb create`: Add warnings for default SKU

scripts/ci/automation_full_test.py
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1560515&view=logs&j=1eb45de9-c733-5264-c426-7b7aa2f821f2&t=0cbae84f-4be8-59ee-bab5-cbee55e4301c
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1560514&view=logs&j=15e5eb7c-cf66-5b91-00a2-db9b11b5e0f9&t=845fa2ee-a602-59f5-4e4c-07ee6d0283b9
Automation full test fails but ci does not report an error.
If check is true, and the process exits with a non-zero exit code, a [CalledProcessError](https://docs.python.org/3/library/subprocess.html#subprocess.CalledProcessError) exception will be raised.
After add check=True, ci will report the error.
[Component …
=> {CI} Fix automation full test fails but ci does not report an error

src/azure-cli/azure/cli/command_modules/storage/operations/azcopy.py
`az storage copy`
When building `flags` arg of `azcopy.copy`, there is a typo causing it to error out on type error:
```
+ az storage copy --recursive --account-key <redacted> -s 'public/*' -d https://<redacted>.blob.core.windows.net/public --exclude-pattern '.*'
Positional argument '<EXTRA_OPTIONS>' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
can only concatenate str (not "NoneType") to str
File "/opt/azure-cli/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
File "/opt/azure-cli/lib/python3.10/site-packages/azure/cli/core/commands/__init__.p …
```
=> [Storage] `az storage copy`: Fix `--exclude-path` TypeError

src/azure-cli/azure/cli/command_modules/acs/custom.py
`az aks get-credentials`
`az aks get-credentials`: Raise exception when existing config file is invalid. This will display more explicit error messages and give user suggestions. Tend to resolve issue [#22142](https://github.com/Azure/azure-cli/issues/22142).
---
=> [AKS] `az aks get-credentials`: Raise exception when existing config file is invalid

doc/authoring_command_modules/README.md, doc/azure2az_commands.rst, scripts/release/debian/deb_install.sh, src/azure-cli/HISTORY.rst, src/azure-cli/azure/cli/command_modules/appservice/custom.py
For unknown reason, https://github.com/Azure/azure-cli/pull/15998 added NBSP ([Non-breaking space U+00A0](https://en.wikipedia.org/wiki/Non-breaking_space)) to `scripts/release/debian/deb_install.sh`
PyCharm:
VS Code:
This leads to display issue in Edge browser:
https://azurecliprod.blob.core.windows.net/$root/deb_install.sh
This PR replaces NBSP with normal ASCII space.
We've seen this issue before:
- https://github.com/Azure/azure-cli/pull/19442
- https://github.com/Azure/azure-cli/pull/8785
=> {Misc.} Replace NBSP with normal ASCII space

azure-pipelines.yml, scripts/release/rpm/mariner.dockerfile, scripts/release/rpm/pipeline_mariner.sh
Mariner 2.0 is now GA and available at `mcr.microsoft.com/cbl-mariner/base/core:2.0`.
Now we use the GA image instead of preview to build RPMs.
This also fixed CI failure due to https://github.com/microsoft/CBL-Mariner/issues/2858:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1526709&view=logs&j=e3c62b71-8b77-544e-81f5-f423af72ca92&t=e76499ae-d6f0-5b8b-06ad-e635f5f3b0f4
```
Error(1525) : rpm transaction failed
The command '/bin/sh -c tdnf update -y' returned a non-zero code: 245
```
Email: _azcli | mariner.dockerfile modification_
=> [Packaging] Use Mariner 2.0 GA image to build RPM

src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
`az spring-cloud` will be renamed as `az spring`. https://github.com/Azure/azure-cli-extensions/pull/4770
This pr adds a new command group `az spring connection` to support SC for the migration, and the `az spring-cloud connection` command group will be deprecated along with `az spring-cloud`.
---
=> [Service Connector] `az spring connection`: Add support for `az sping-cloud` renaming

src/azure-cli-core/azure/cli/core/_profile.py, src/azure-cli-core/azure/cli/core/util.py, src/azure-cli/azure/cli/command_modules/util/_help.py, src/azure-cli/azure/cli/command_modules/util/_params.py, src/azure-cli/azure/cli/command_modules/util/commands.py, src/azure-cli/azure/cli/command_modules/util/custom.py, src/azure-cli/azure/cli/command_modules/util/linter_exclusions.yml
Expose public interface for using encrypted `SecretStore` so that command modules or extensions (such as https://github.com/calvinsID/azure-cli-extensions/pull/97) can leverage `msal-extensions` to save custom data such as tokens.
On Windows:
```
> az demo secret-store save "name=Johann Sebastian Bach" job=musician
Data written to C:\Users\username\.azure\secret_store_demo.bin: {'name': 'Johann Sebastian Bach', 'job': 'musician'}
> az demo secret-store load
{
"job": "musician",
"name": "Johann Sebastian Bach"
}
```
Turn off token encryption:
```
> az config set core.encrypt_token_cache=False
> az demo secret-store save "name=Johann Sebastian Bach" job=musician
Data written to C:\Users\username\.azure\secret_store_demo.json: {'name': 'Johann Sebastian …
```
=> {Core} Expose public interface for `SecretStore`

src/azure-cli/azure/cli/command_modules/acs/_help.py, src/azure-cli/azure/cli/command_modules/acs/_validators.py, src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_agentpool_decorator.py
```
az aks nodepool add
az aks nodepool update
```
This PR address 2 changes
- Node Pools can be scaled from 0 to 1000 nodes from the Azure Portal, but the CLI has a check restricting them between 1 and 100
- Only User Node Pools support scaling to 0 nodes, which after the fix for the acceptable range above, results in unintuitive error messages from the ARM endpoint
After the fix for the first, the following commands were tested, resulting in errors from ARM as below
```sh
$ az aks nodepool add --name {} --cluster-name {} --resource-group {} --enable-cluster-autoscaler --node-count 0 --min-count 0 --max-count 1 --mode System
(InvalidParameter) The value of parameter agentPoolProfile.count is invalid. Please see https://aka.ms/aks-naming-rules for more …
```
=> [AKS] Fix #22032: `az aks nodepool add/update`: Fix autoscaler parameters for user node pools

src/azure-cli/azure/cli/command_modules/acs/_format.py, src/azure-cli/azure/cli/command_modules/acs/_validators.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_validators.py
az aks create --kubernetes-version
az aks show
(1) AKS supports ManagedCluster kubernetes version with format major.minor, so remove the original limitation version number must have patch number
(2) AKS has both kubernetesVersion and currentKubernetesVersion, currentKubernetesVersion is the actual version that MC running. We add it in the az aks show command
---
=> [AKS] GA Kubernetes version alias

src/azure-cli/azure/cli/command_modules/sql/_params.py, src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
```sh
az sql server ad-admin create --resource-group {} --server-name {} --display-name {} --object-id {}
```
Both the Display Name and Object ID are required by the underlying ARM API, but are currently misclassified as optional arguments
Fixes #22316
Currently, all of the following commands fail with an error from the REST API instead of clearly stating that a required parameter is missing
```sh
az sql server ad-admin create --resource-group {} --server-name {}
az sql server ad-admin create --resource-group {} --server-name {} --display-name {}
az sql server ad-admin create --resource-group {} --server-name {} --object-id {}
```
With this PR, the command should fail with the Exit Code 2 and message clearly mentioning that the …
=> [SQL] Fix #22316: `az sql server ad-admin create`: Fix Display Name and Object ID to be required

src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt, src/azure-cli/setup.py
`az storage entity insert`
Fix #22209 
Pick up the SDK fix for `odata.type="Edm.Boolean"` in https://github.com/Azure/azure-sdk-for-python/pull/24290
Insert an entity with boolean attribute:
```
az storage entity insert -t ystable --account-name yssa --if-exists replace -e PartitionKey=123 RowKey=456 Active=true Active@odata.type="Edm.Boolean"
```
Query the entity:
```
az storage entity query -t ystable --account-name yssa --filter "PartitionKey eq '123' and RowKey eq '456'"
```
The response should contain `"Active": true` instead of `"Active": "true"`
---
=> [Storage] Fix #22209: `az storage entity insert`: Fix `Edm.Boolean` not working

src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt, src/azure-cli/setup.py
`az monitor`
The current dependency of `antlr4-python3-runtime` is from 2018, but many distributions, including Fedora, are packaging the 4.9.x branch.
The same tests should be run using the same methods.
---
=> {packaging} Update antlr4 to 4.9.3

src/azure-cli/azure/cli/command_modules/vm/_image_builder.py, src/azure-cli/azure/cli/command_modules/vm/_validators.py, src/azure-cli/azure/cli/command_modules/vm/custom.py, src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2018_03_01/test_vm_actions.py, src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/test_vm_actions.py, src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/test_vm_actions.py, src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_actions.py
Since vm module has already been migrated to Track 2 #15750,  `CloudError` should be replaced with `HttpResponseError` or more specifically `ResourceNotFoundError`
Related PR: #22267
---
=> {Compute} Fix `CloudError` in VM module

src/azure-cli/azure/cli/command_modules/acs/addonconfiguration.py
For MSI auth of Monitoring addon, there will be DCR created  with format MSCI-<clusterName>-<clusterRegion>. If the customer tags and this resource exists, in case of customer try to re-onboard the monitoring addon with MSI auth, existing tags (if any) will be used for the PUT to retain the customer tags.
---
=> [AKS] Monitoring addon MSI auth - use existing tags on container insights extension dcr for PUT

src/azure-cli/azure/cli/command_modules/hdinsight/_client_factory.py, src/azure-cli/azure/cli/command_modules/hdinsight/_completers.py
Only two completers are impacted.
This PR migrate ADAL graph SDK to MS graph SDK.
There is not customer impact
---
=> [HDInsight] Migrate adal graph sdk to msgraph sdk in HDInsight module

src/azure-cli/azure/cli/command_modules/vm/custom.py
Fix: https://github.com/Azure/azure-cli/issues/22322
Add hint for `az vmss create`
The default lb will be expected to be changed from Basic to Standard. In order to avoid big impact to users, we use the hint to guide users to use Standard lb to create VMSS in the first stage.
---
=> {Compute} `az vmss create`: Add hint to suggest Standard lb

src/azure-cli-core/azure/cli/core/profiles/_shared.py, src/azure-cli/azure/cli/command_modules/vm/_help.py, src/azure-cli/azure/cli/command_modules/vm/_params.py, src/azure-cli/azure/cli/command_modules/vm/commands.py, src/azure-cli/azure/cli/command_modules/vm/custom.py, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_architecture.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_create_image_version_with_region_cvm_encryptio.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_create_vm_with_shared_gallery_image.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_application.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_application_version.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_e2e.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_image_version_vhd.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_soft_delete.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_specialized.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_image_build_shared_image.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_image_builder_basic_sig.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_replication_mode.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_shared_gallery.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_specialized_image.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_max_shares_etc.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_usage.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Shared gallery replace '--seletct=permissions' with '--expand=sharingProfile/Groups' https://github.com/Azure/azure-cli/issues/22327
---
=> [Compute] `az sig show`: Add new parameters `--sharing-groups` to support query shared gallery group

src/azure-cli/azure/cli/command_modules/acr/manifest.py, src/azure-cli/azure/cli/command_modules/acr/repository.py, src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_commands_mock.py
`az acr manifest` and `az acr repository` command groups
3 bug fixes.
[ACR] Fix some `az acr manifest` commands do not correctly handle `-u/-p` credentials resulting in auth failure when not logged in to `az cli`
[ACR] Fix some `az acr` commands do not handle certain next-link tokens correctly resulting in exceptions when paging
[ACR] Fix some `az acr manifest` commands do not correctly parse some FQDNs resulting in exceptions
---
=> [ACR] Fix: various bug fixes

src/azure-cli/azure/cli/command_modules/acs/_help.py
Following changes from [2022-02-24](https://github.com/Azure/AKS/releases/tag/2022-02-24) this command will output the error bellow.
I'm suggesting a new IP that works.
```
(IngressAppGwAddonConfigInvalidSubnetCIDRNotContainedWithinVirtualNetwork) Subnet Prefix '10.2.0.0/16' specified for IngressApplicationGateway addon is not contained within the AKS Agent Pool's Virtual Network address prefixes '[10.224.0.0/12]'.
Code: IngressAppGwAddonConfigInvalidSubnetCIDRNotContainedWithinVirtualNetwork
Message: Subnet Prefix '10.2.0.0/16' specified for IngressApplicationGateway addon is not contained within the AKS Agent Pool's Virtual Network address prefixes '[10.224.0.0/12]'.
Target: AddonProfiles.IngressApplicationGateway
```
Also change for this reason: …
=> {AKS} `az aks enable-addons`: Update message sample for `--appgw-subnet-cidr`

src/azure-cli-core/azure/cli/core/commands/command_operation.py, src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
When executing `az resource wait` command, calling `_get_provisioning_state()` method can't get provisioning_state.
code link: [command_operation.py](https://github.com/kairu-ms/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/commands/command_operation.py#L459)
Because `instance.properties` is `dict` type at this time, so it can only be obtained through `instance.properties['provisioningState']`
In addition, this problem has **existed since very early CLI versions** and even it may never worked correctly before (there had been no related scenario tests). I even tried the `2.23.0` version of CLI, which relies on the **Track 1** Python SDK, this problem can still be reproduced. 
Therefore, this is a very old legacy problem, so I submitted this PR to add correct parsing …
=> [ARM] `az resource wait`: Fix `--created` keeps waiting even when `az resource show` returns "provisioningState": "Succeeded"

src/azure-cli/azure/cli/command_modules/vm/_params.py
Fix: https://github.com/Azure/azure-cli/issues/22502
---
=> {Compute} `az vm/vmss application set`: improve `--order-applications` help message

src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt, src/azure-cli/setup.py
The `jsondiff` package was recently updated and a 2.0.0 version was released. I'd like to update my `python3-jsondiff` Fedora package to 2.0.0, but `azure-cli` demands a version `>= 1.3` and `<= 1.4`.
For completeness, the bug on the Fedora side is [BZ 2073817](https://bugzilla.redhat.com/show_bug.cgi?id=2073817).
All testing processes should remain the same.
---
=> {packaging} Update jsondiff to 2.0.0

src/azure-cli-core/azure/cli/core/azclierror.py, src/azure-cli-core/azure/cli/core/util.py, src/azure-cli/azure/cli/command_modules/role/msgrpah/_graph_client.py
`az ad`
Currently, all subclasses of `CLIError` are re-raised as `GraphError`. This is not correct and causes failure for `AuthenticationError` handling.
For example, we change `microsoft_graph_resource_id` to an invalid value like `https://graph1.microsoft.com/`, which is then used as a `scope` to get an access token:
https://github.com/Azure/azure-cli/blob/31e396bed780b8db5641d73ba02fb4ce66db194e/src/azure-cli-core/azure/cli/core/cloud.py#L308
The error handling procedure failed:
```
> az ad app show --id 0e33fcf1-8a78-4941-9479-75d29681f4dc
...
result = self._send("GET", "/applications" + _filter_to_query(filter))
File "d:\cli\azure-cli\src\azure-cli\azure\cli\command_modules\role\msgrpah\_graph_client.py", line 40, in _send
raise …
```
=> {Role} Raise `GraphError` only when Graph request fails

src/azure-cli/azure/cli/command_modules/keyvault/custom.py
`az keyvault create`
- Fix #22540
https://github.com/Azure/azure-cli/pull/22203 changed `msrestazure.azure_exceptions.CloudError` to `azure.cli.command_modules.role.GraphError` in `azure.cli.command_modules.keyvault.custom._get_current_user_object_id`.
Some background: **`azure-graphrbac` Python SDK raises inconsistent exceptions for Graph errors**:
`DomainsOperations.get` raises `CloudError`:
https://github.com/Azure/azure-sdk-for-python/blob/dfa109c36598d93aaf74238feded516352c20f4c/sdk/graphrbac/azure-graphrbac/azure/graphrbac/operations/domains_operations.py#L150-L153
```py
if response.status_code not in [200]:
exp = CloudError(response)
exp.request_id = response.headers.get('x-ms-request-id')
raise exp
```
`SignedInUserOperations.get` raises …
=> {Keyvault} Fix #22540: Create keyvault with service principal

src/azure-cli/azure/cli/command_modules/acs/decorator.py, src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
`az aks create --network-plugin azure --pod-cidr 10.224.0.0/12`
Should not need client side validation for specifying network plugin azure and a pod CIDR. With `networkPluginMode` in the aks-preview extension it is possible to set the pod-cidr with network plugin azure.
---
=> {AKS} Let AKS RP handle validation of setting pod CIDR and network plugin 

src/azure-cli/azure/cli/command_modules/role/msgrpah/_graph_client.py
`az ad`
Sovereign clouds' `microsoft_graph_resource_id` may not have a trailing slash `/`.
AzureCloud:
https://github.com/Azure/azure-cli/blob/31e396bed780b8db5641d73ba02fb4ce66db194e/src/azure-cli-core/azure/cli/core/cloud.py#L308
AzureChinaCloud:
https://github.com/Azure/azure-cli/blob/31e396bed780b8db5641d73ba02fb4ce66db194e/src/azure-cli-core/azure/cli/core/cloud.py#L345
AzureUSGovernment:
https://github.com/Azure/azure-cli/blob/31e396bed780b8db5641d73ba02fb4ce66db194e/src/azure-cli-core/azure/cli/core/cloud.py#L376
AzureGermanCloud:
https://github.com/Azure/azure-cli/blob/31e396bed780b8db5641d73ba02fb4ce66db194e/src/azure-cli-core/azure/cli/core/cloud.py#L408
In order to build Microsoft Graph base URL correctly, trailing slash `/` should be …
=> {Graph} Build base URL correctly for sovereign clouds

src/azure-cli/azure/cli/command_modules/network/_params.py
az network application-gateway ssl-policy ...
Application Gateway had introduced new Ssl Policies as a part of NRP release 165. This pr updates the cli to support the customv2 policy and tls1.3 protocol.
az network application-gateway ssl-policy set -g <rg-name> --gateway-name <name> --policy-type CustomV2 --min-protocol-version TLSv1_3 
---
=> [Network] `az network application-gateway ssl-policy`: Support new SSL policy `CustomV2`

scripts/ci/check_pull_request.py
Now we only check history notes when title starts with `[`.
But `scripts/release/generate_history_notes.py` will get all history notes even if the title starts with `{`.
In azure-cli-2.37.0, the following problems were not detected because #22507‘s title starts with `{`：
---
=> {CI} Keep the logic consistent with generate_history_notes.py, always check history notes

NOTICE.txt, scripts/release/homebrew/docker/requirements.txt, src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt
Jinja2 below version 3 is not maintained. In version [3.0.3](https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-0-3), it fixed bugs to support python 3.10 and 3.11.
The lastest version is 3.1.2, we cannot use this version because [3.1.x](https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0) dropped python 3.6 support.
BTW, the version 3.0.3 already been applied in test_ref_doc.sh pipeline in https://github.com/Azure/azure-cli/pull/21798
Version 3.0.3 requires [MarkupSafe>=2.0](https://github.com/pallets/jinja/blob/2a48dd898d72f1a119ee923996e70aa43da04ea4/setup.py#L6).
MarkupSafe [2.1.x](https://markupsafe.palletsprojects.com/en/2.1.x/changes/) drops python 3.6, so I bump it to version 2.0.1.
I've reviewed the usage of Jinja2 in …
=> {Packaging} Bump Jinja2 to 3.0.3

src/azure-cli/azure/cli/command_modules/storage/_validators.py, src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_sas_scenarios.py
`az storage account generate-sas`
`az storage account generate-sas --resource-type sco` will generate a sas with random order of `sco` in `srt` segment, for example:
- `se=2022-05-25&sp=r&sv=2021-06-08&ss=qb&srt=ocs&sig=XXXX`
- `se=2022-05-25&sp=r&sv=2021-06-08&ss=qb&srt=soc&sig=XXXX`
This will cause the sas token invalid for .NET SDK([IcM link](https://portal.microsofticm.com/imp/v3/incidents/details/308892616/home))
This PR fix the random order in output. We will totally honor the input order from `--resource-type`
---
=> [Storage] `az storage account generate-sas`: Fix output sas has random order for `srt` segment

src/azure-cli/azure/cli/command_modules/vm/custom.py, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_encryption_set_disk_update.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
See issue: https://github.com/Azure/azure-cli/issues/22439
Fix following performance:
1. `az disk create`:  if only specified `--encryption-type` but not `--disk-encryption-set`,  `--encryption-type` is actually ignored during processing
2. `az disk update`:  if only specified `--encryption-type EncryptionAtRestWithPlatformKey`, would not remove current disk encryption set(if the disk has it) and only update encryption type, thus may cause response error
[Compute] `az disk create`: Fix the issue that specifying encryption type as `EncryptionAtRestWithPlatformKey` does not take effect when creating a disk
[Compute] `az disk update`: Fix the `(InvalidParameter) Resource xxx encrypted with platform key has disk …
=> [Compute] `az disk create/update`: Fix `--encryption-type` processing

src/azure-cli/azure/cli/command_modules/acs/_client_factory.py, src/azure-cli/azure/cli/command_modules/acs/_graph.py, src/azure-cli/azure/cli/command_modules/acs/custom.py, src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/hybrid_2020_09_01/test_custom.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_custom.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
- Graph module migration.
- Remove most dependencies on graph SDK.
- Only keep the functions that query object id by app id, which is used by role assignments.
- Keep the graph SDK related calls used by the `acs` commands unchanged, and plan to remove the deprecated `acs` command group as a whole during the next breaking change window to eliminate the dependency on the legacy graph SDK.
- Split the global import of legacy graph SDK in `custom.py` into each function, so that even if CLI removes the dependency, import errors should not occur without using these deprecated commands.
- After the changes in this PR, a service principal will no longer be implicitly created for the user when the user has not provided both app id and secret …
=> {AKS} Graph module migration

src/azure-cli/azure/cli/command_modules/role/__init__.py
`az ad`
This warning is only needed in the first version after migration - 2.37.0. We should remove it in 2.38.0.
=> {Graph} Remove the warning for Microsoft Graph migration

scripts/release/rpm/azure-cli.spec, scripts/release/rpm/centos7.dockerfile, scripts/release/rpm/mariner.dockerfile, scripts/release/rpm/ubi8.dockerfile
Red Hat Enterprise Linux (RHEL) 8 now has Python 3.6, 3.8, and 3.9: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/assembly_installing-and-using-python_configuring-basic-system-settings
Since Python 3.6 has been deprecated (#19858), we use Python 3.9 on RHEL 8.
=> [Packaging] Use Python 3.9 in RHEL 8's RPM

src/azure-cli/azure/cli/command_modules/resource/custom.py
v2.37.0 has a regression where `--stdout` stops working for `az bicep build`. The PR fixes it.
Closes #22621.
`az bicep build -f main.bicep --stdout`
---
=> [ARM] `az bicep build`: Fix #22621: `--stdout` does not work

src/azure-cli-core/azure/cli/core/aaz/_command.py
azdev or CI script will pass None value as args. It caused the fail of load_aaz_command_table.
---
=> {Core} `aaz`: fix issue in load_aaz_command_table for azdev and CI

src/azure-cli/azure/cli/command_modules/security/_help.py, src/azure-cli/azure/cli/command_modules/security/_params.py, src/azure-cli/azure/cli/command_modules/security/commands.py, src/azure-cli/azure/cli/command_modules/security/custom.py, src/azure-cli/azure/cli/command_modules/security/tests/latest/recordings/test_security_cosmosdb_atp_settings.yaml, src/azure-cli/azure/cli/command_modules/security/tests/latest/recordings/test_security_storage_atp_settings.yaml, src/azure-cli/azure/cli/command_modules/security/tests/latest/test_atp_scenario.py
```
az security atp cosmosdb show--resource-group MyResourceGroup --cosmosdb-account MyCosmosDbAccount 
az security atp cosmosdb update --resource-group MyResourceGroup --cosmosdb-account MyCosmosDbAccount --is-enabled 
true
```
Adding support for get/set ATP settings (Defender) on Cosmos DB resources.
The REST api supports both Storage accounts and Cosmos DB accounts, but until now, the CLI supported only Storage accounts.
In this PR, we added support for Cosmos DB.
The REST api: 
https://docs.microsoft.com/en-us/rest/api/securitycenter/advanced-threat-protection/get
https://docs.microsoft.com/en-us/rest/api/securitycenter/advanced-threat-protection/create
See related commands section above
--- …
=> [Security] `az security atp cosmosdb`: Add CLI support for ATP settings (Defender) on Cosmos DB

doc/shorthand_syntax.md, src/azure-cli-core/azure/cli/core/aaz/_utils.py, src/azure-cli-core/azure/cli/core/tests/test_aaz_arg.py
In previous design, the escape character `/` is hard to use, customers have to double `/` characters when it appeared in Single Quotes String of shorthand syntax.
For example, when customer passes an url `https://bill.microsft.com/blog`, in previous design, it should be `'https:////bill.microsft.com//blog'` in `Full Value` format. It becomes longer than original, which obeys the goal of shorthand syntax.
This PR simplify the escape character usage in [Single Quotes String](https://github.com/Azure/azure-cli/blob/dev/doc/shorthand_syntax.md#single-quotes-string).
The reason we need escape character in Single Quotes String is that we need to distinguish the normal `'` in string or the end `'` to finish Single Quotes String. There's no reason to escape the …
=> [Core] shorthand syntax: Simplify the escape character usage in Single Quotes String

src/azure-cli/azure/cli/command_modules/keyvault/_validators.py
`az keyvault key set-attributes`
We should alert if users set `--immutable` without providing `--policy`. But `--immutable false` skipped this validation.
This PR wants to fix this.
`az keyvault key set-attributes -n $keyName --hsm-name $hsmName --immutable false`
---
=> {Keyvault} `az keyvault key set-attributes`: Make `--policy` required if `--immutable` provided

src/azure-cli/azure/cli/command_modules/storage/operations/account.py, src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_file_delete_retention_policy.yaml, src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_file_secured_smb.yaml, src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_file_smb_multichannel.yaml, src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
`az storage account file-service-properties update`
Fix #22679 , [IcM 311511171](https://portal.microsofticm.com/imp/v3/incidents/details/311511171/home)
`update_file_service_properties` can't handle properly when `instance.protocol_settings` is `None`.
Previously `get_file_service_properties` would get response `"protocolSettings":{"smb":{}}` from server.
But recently server won't return `"protocalSettings"` property any more. 
Then CLI would crash with `AttributeError: 'NoneType' object has no attribute 'smb'`
---
=> [Storage] Fix #22679: `az storage account file-service-properties update`: Fix `AttributeError: 'NoneType' object has no attribute 'smb'`

src/azure-cli/azure/cli/command_modules/serviceconnector/_params.py, src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py, src/azure-cli/azure/cli/command_modules/serviceconnector/custom.py, src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_webapp_storageblob_vnet_pe.yaml, src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/test_webpp_connection_scenario.py
=> [Service Connector] `az webapp connection create`: Add `--private-endpoint` to support private endpoint connection

src/azure-cli/azure/cli/command_modules/servicefabric/_validators.py, src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/recordings/test_basic_cluster.yaml, src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/test_sf_managed_cluster.py
**az sf managed-cluster**
This PR fixes tags for managed cluster commands. It turns out if a with argument context block has a validator defined, child arguments within the block don't get their validators run, so this is explicitly validating tags which parses them into a dict from a list
{Service Fabric} `az sf managed-cluster create`: Make tags work
---
=> [Service Fabric] `az sf managed-cluster create`: Fix tag parsing for cluster command

src/azure-cli-testsdk/azure/cli/testsdk/utilities.py
Synapse test `src/azure-cli/azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py::SynapseScenarioTests::test_workspace_package` uploads a jar file as the request body:
https://github.com/Azure/azure-cli/blob/85ef3c7e506ccd077f70c0808e6574bb40802d99/src/azure-cli/azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py#L2652-L2657
As the jar is a binary file (`bytes`), `_byte_to_str` will fail to decode `bytes` as `utf-8`:
https://github.com/Azure/azure-cli/blob/cac3f06cf483d8c81f93c9cd556116e27aff2182/src/azure-cli-testsdk/azure/cli/testsdk/utilities.py#L51-L52
causing failure:
```
src\azure-cli-testsdk\azure\cli\testsdk\scenario_tests\base.py:165: in _process_request_recording
request = processor.process_request(request) …
```
=> {Graph} Remove unnecessary logic from `MSGraphClientPasswordReplacer`

src/azure-cli/azure/cli/command_modules/cognitiveservices/custom.py, src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt, src/azure-cli/setup.py
`az cognitiveservices account deployment create`
Update SDK, which container new enum options for scale type
Fix `deployment create` command and make scale capacity optional.
When using `az cognitiveservices account deployment create` command,  --scale-settings-scale-type now support new enums. and --scale-settings-capacity is now optional
Sample command.
`az cognitiveservices account deployment create -n {sname} -g {rg} --deployment-name dpy --model-name ada --model-version "1" --model-format OpenAI --scale-settings-scale-type "Standard"`
[Cognitive Services] `az cognitiveservices account deployment create` now supports standard scale type
{Cognitive Services} Update RP SDK, which container new enum options for scale …
=> [Cognitive Services] Update SDK and fix an optional parameter

src/azure-cli/azure/cli/command_modules/acs/custom.py
`az aks get-credentials`
Background
> I need help on a case where when my customer uses soft link for config file, they get the below prompt :-
> 
> /home/sander_flobbe/.kube/config has permissions '777'. It should be readable and writable only by its owner.
> 
> As per my understanding, customer shouldn’t be getting this prompt, as symlink has by default permissions of 777 which can't be modified.
> 
> ### Steps to reproduce the behavior:
>
> 1)	rm -rf .kube
> 2)	mkdir .kube
> 3)	cd .kube
> 4)	touch my-config
> 5)	ln -s my-config config
> 6)	az aks get-credentials --resource-group (..) --name (..) --subscription (..)
> 
> This gives a (false) error:
> /home/sander_flobbe/.kube/config has permissions "777".
> It should be readable and writable only by …
=> [AKS] `az aks get-credentials`: Fix permission prompt when saving config file to symlink

src/azure-cli/azure/cli/command_modules/vm/_help.py
```sh
az vm -h
```
Helper text for the above command has a small typo: `application            : Manage appliations for VM.`
Instead of "appliations" it should be "appli**c**ations"
Run the command again with `az vm -h` and the helper text output for the `application` subgroup should be correct.
---
=> {Compute} `az vm application`: Fix typo in vm help message

src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt
- SDK generated by new version of autorest (not released yet) will depend on msrest 0.7.0, so CLI needs bump msrest from 0.6.21 to 0.7.0 beforehand to be compatible with those new SDK.
- Remove vsts 0.1.25 which is useless now. Another reason for removing vsts is that dependency conflict: vsts 0.1.25 requires msrest<0.7.0, >=0.6.0.
---
=> {Packaging} Bump msrest from 0.6.21 to 0.7.0

src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py, src/azure-cli/azure/cli/command_modules/serviceconnector/_transformers.py, src/azure-cli/azure/cli/command_modules/serviceconnector/commands.py, src/azure-cli/azure/cli/command_modules/serviceconnector/custom.py
`az spring connection list-support-types`
`az {source} connection validate`
This PR fixes the following issues
- `az spring connection list-support-types` doesn't work
The PR also provides the following improvements
- Support customizing auth info when using `--new` parameter 
- `az {source} connection validate` output improvement, only show useful info
---
=> {Service Connector} Some improvements on command experience

src/azure-cli/azure/cli/command_modules/acs/custom.py
- `az aks command invoke`
- `az aks command result`
- Add support for option `--no-wait` in `az aks command invoke`
- Output command id in `az aks command invoke`
- Handle empty command result
---
=> [AKS] `az aks command invoke`: Add support for `--no-wait`

src/azure-cli/azure/cli/command_modules/role/custom.py, src/azure-cli/azure/cli/command_modules/role/tests/latest/test_graph.py
`az ad app permission add`
Refine the error message per #10718, #15598, #16868, #17057, #18185, #18408, #22826
The correct usage of `--api-permissions` from `az ad app permission add` is `{id}={type}`. The help message and examples are pretty clear about this. They even show how to retrieve `{id}` and `{type}`.
```
> az ad app permission add --help
Command
az ad app permission add : Add an API permission.
Invoking "az ad app permission grant" is needed to activate it.
To get available permissions of the resource app, run `az ad sp show --id <resource-appId>`.
For example, to get available permissions for Microsoft Graph API, run `az ad sp show --id
00000003-0000-0000-c000-000000000000`. Application permissions under the `appRoles` property
correspond to …
```
=> {Role} `az ad app permission add`: Refine error message for incorrect `--api-permissions`

scripts/live_test/generate_index.py
- live test does not generate the latest index.html file.
- storage has a breaking change, need add --overwrite to `az storage blob upload` command to overwrite the old index.html file.
- The password of the azureclilivetest account needs to be updated regularly, otherwise it will expire.
=> {CI} Fix the bug that live test does not generate the latest index.html

Dockerfile, build_scripts/windows/scripts/build.cmd, scripts/release/debian/build.sh
Bump Python version to [3.10.5](https://www.python.org/downloads/release/python-3105/).
=> {Packaging} Bump Python version to 3.10.5

src/azure-cli/azure/cli/command_modules/netappfiles/custom.py, src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_create_account_with_no_location.yaml, src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_create_pool_with_no_location.yaml, src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/test_account_commands.py, src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/test_pool_commands.py
This is a fix for #22690 where location is not properly retrieved from resource group when not sent in.
Pull request where this was added: https://github.com/Azure/azure-cli/pull/21712
[NetAppFiles] `az netappfiles account create`: Change `--location` to an optional parameter
[NetAppFiles] `az netappfiles pool create`: Change `--location` to an optional parameter
[NetAppFiles] `az netappfiles volume create`: Change `--location` to an optional parameter
[NetAppFiles] `az netappfiles snapshot create`: Change `--location` to an optional parameter
[NetAppFiles] `az netappfiles snapshot policy create`: Change `--location` to an optional parameter
[NetAppFiles] `az netappfiles snapshot policy update`: Change `--location` to an optional …
=> [NetAppFiles] Fix #22690 - Fix location retrieval from resource group

src/azure-cli/azure/cli/command_modules/role/_help.py, src/azure-cli/azure/cli/command_modules/role/_msgrpah/_graph_client.py, src/azure-cli/azure/cli/command_modules/role/_msgrpah/_graph_objects.py, src/azure-cli/azure/cli/command_modules/role/_params.py, src/azure-cli/azure/cli/command_modules/role/commands.py, src/azure-cli/azure/cli/command_modules/role/custom.py, src/azure-cli/azure/cli/command_modules/role/tests/latest/recordings/test_app_federated_credential.yaml, src/azure-cli/azure/cli/command_modules/role/tests/latest/test_graph.py
- `az ad app federated-credential`
Close https://github.com/Azure/azure-cli/issues/20582
Support federated identity credential on both 
- Application: https://docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta
- Service Principal: {doc not available yet}
---
=> [AD] `az ad app federated-credential`: Support federated identity credentials

src/azure-cli/azure/cli/command_modules/acr/_docker_utils.py, src/azure-cli/azure/cli/command_modules/acr/_errors.py, src/azure-cli/azure/cli/command_modules/acr/_format.py, src/azure-cli/azure/cli/command_modules/acr/check_health.py
All the changes are within the ACR module and only have impact when the debug flag is turned on.
- Adding timestamps in debug logs when sending HTTP requests or encountering errors in ACR module, which would help investigate customer issues.  
- The changes would have effects on two places. Firstly, the timestamp would be shown in front of ACR error messages.  Secondly, when the debug flag is turned on and sending HTTP requests in ACR module, it will add a log line with the timestamp, request type and the URL.
---
=> {ACR} Add timestamp in error messages and debug logs when sending HTTP requests

src/azure-cli-core/azure/cli/core/aaz/_operation.py, src/azure-cli-core/azure/cli/core/tests/test_aaz_operation.py
=> {Core} `aaz`: fix a bug on serialize content when using serialized_name of required property

src/azure-cli/azure/cli/command_modules/acs/custom.py
`az aks get-credentials`
When KUBECONFIG is empty, keep using the default storage path (`~/.kube/config`) and output warning-level logs; otherwise, use the path in KUBECONFIG to replace the default storage path and output info-level logs. Thanks to @fseldow for reporting this bug.
---
=> [AKS] `az aks get-credentials`: Fix the command error when KUBECONFIG is empty

src/azure-cli/azure/cli/command_modules/rdbms/_params.py
```sh
az mysql server create -g {} -n {}
```
This PR updates the default storage size for `az mysql server create` command from 51200 to 5120.
Resolves #22926
The following command should create a mysql server with the defaults and storage size should be 5GB.
```sh
az mysql server create -g {} -n {}
```
---
=> [RDBMS] Fix #22926: `az mysql server create/update`: Update default value for mysql storage size

src/azure-cli/azure/cli/command_modules/resource/_help.py
az provider list --query [?namespace=='Microsoft.Network'].resourceTypes[].resourceType
Command **without surrounding quotes does not work**. Need to add "" around --query parameter.
Wrong (initial) command syntax:
az provider list --query [?namespace=='Microsoft.Network'].resourceTypes[].resourceType
--> gives [] empty array
Correct command syntax:
az provider list --query "[?namespace=='Microsoft.Network'].resourceTypes[].resourceType"
--> gives proper list of resource types
=> {Docs} Fix query syntax for `az provider list` command

src/azure-cli/azure/cli/command_modules/network/_params.py, src/azure-cli/azure/cli/command_modules/network/custom.py, src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet.yaml, src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_subnet_with_private_endpoint_and_private_Link_options.yaml, src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
az network vnet subnet create
> Depending on that we may need a fix to default this to “Disabled” (we are discussing and closing on it).
Doc: https://docs.microsoft.com/en-us/azure/private-link/disable-private-endpoint-network-policy
Swagger: https://github.com/Azure/azure-rest-api-specs/pull/19577
---
=> [Network] BREAKING CHANGE: `az network vnet subnet create`: Disable `PrivateEndpointNetworkPolicies` by default

src/azure-cli/azure/cli/command_modules/appservice/_help.py, src/azure-cli/azure/cli/command_modules/appservice/_params.py, src/azure-cli/azure/cli/command_modules/appservice/commands.py, src/azure-cli/azure/cli/command_modules/appservice/static_sites.py, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_staticapp_commands_thru_mock.py
`az staticwebapp enterprise-edge enable`
`az staticwebapp enterprise-edge disable`
`az staticwebapp enterprise-edge show`
Moves the commands in the command group `az staticwebapp enterprise-edge` from the extension to the main CLI. The functionality/interface is the same, but the implementation now uses the SDK 
---
=> [App Service] `az staticwebapp enterprise-edge`: Move command group from extension to official CLI

src/azure-cli/azure/cli/command_modules/iot/commands.py
`az iot hub certificate list`
`az iot dps certificate list`
Add a table transformer to the certificate list commands so a user has a better experience when the output is in the table format. Specific issue: https://github.com/Azure/azure-iot-cli-extension/issues/530 
Example usage:
`az iot dps certificate list --dps-name <myDPS> -o table`
Before:
After:
The code aside from table transforms was not changed.
[IoT] `az iot hub/dps certificate list`: Add table transform to certificate list commands
---
=> [IoT] `az iot hub/dps certificate list`: Add table transform to certificate list commands

src/azure-cli/azure/cli/command_modules/acs/_help.py
```sh
az aks update -g {} -n {} --aks-custom-headers WindowsContainerRuntime=containerd,AKSHTTPCustomFeatures=Microsoft.ContainerService/CustomNodeConfigPreview
```
The above command is an example in the [`az aks update` reference doc](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-update) which fails to run because of the `AKSHTTPCustomFeatures` value. This PR removes that, with which the remaining command works as expected.
Resolves #23044
The remaining command should work as expected
```sh
az aks update -g {} -n {} --aks-custom-headers WindowsContainerRuntime=containerd
```
---
=> {AKS} Fix #23044: `az aks update`: Fix example using `--aks-custom-headers` parameter

src/azure-cli/azure/cli/command_modules/resource/_help.py, src/azure-cli/azure/cli/command_modules/resource/_params.py, src/azure-cli/azure/cli/command_modules/resource/commands.py, src/azure-cli/azure/cli/command_modules/resource/custom.py, src/azure-cli/azure/cli/command_modules/resource/tests/latest/sample_params.bicep, src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
```sh
az bicep generate-params --file {bicep_file}
```
The Bicep CLI introduced a [`generate-params`](https://github.com/Azure/bicep/pull/6601) command in [v0.7.4](https://github.com/Azure/bicep/releases/tag/v0.7.4)
This PR adds support for the same.
Resolves #22930 
Using the following bicep file, naming it `sample_params.bicep`
```bicep
param demoString string
param demoInt int
param demoBool bool
param demoObject object
param demoArray array
param location string = resourceGroup().location
```
The following command should work without any error
```sh
az bicep generate-params --file sample_params.bicep # An output.paramters.json file should be created
az bicep generate-params --file sample_params.bicep --outdir . # An …
```
=> [ARM] Fix #22930: `az bicep generate-params`: Add support for bicep generate-params command

src/azure-cli/azure/cli/command_modules/acs/_help.py, src/azure-cli/azure/cli/command_modules/acs/commands.py, src/azure-cli/azure/cli/command_modules/acs/custom.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_nodepool_stop_and_start.yaml, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
```
az aks nodepool stop --resource-group="resource group" --cluster-name="cluster name" --nodepool-name="nodepool name"
```
```
az aks nodepool start --resource-group="resource group" --cluster-name="cluster name" --nodepool-name="nodepool name"
```
Add bindings for nodepool stop/start in core cli, rather than extensions. Enabling nodepool start/stop feature for the GA.
```
az aks nodepool stop --resource-group="resource group" --cluster-name="cluster name" --nodepool-name="nodepool name"
```
```
az aks nodepool start --resource-group="resource group" --cluster-name="cluster name" --nodepool-name="nodepool name"
``` …
=> [AKS] `aks nodepool stop/start`: Add nodepool stop/start bindings

src/azure-cli/azure/cli/command_modules/servicebus/custom.py
…ration
Fixes https://github.com/Azure/azure-cli/issues/23013
---
=> {servicebus} Fix error message raised on a malformed ISO-8601 duration

doc/telemetry/README.md, doc/telemetry/faq.md, doc/telemetry/kusto_examples.md
Currently we have no documentation for CLI telemetry and there's more and more consultation regarding telemetry access and usage
---
=> {Doc} Add telemetry doc

linter_exclusions.yml, src/azure-cli/azure/cli/command_modules/vm/_params.py, src/azure-cli/azure/cli/command_modules/vm/_validators.py, src/azure-cli/azure/cli/command_modules/vm/custom.py, src/azure-cli/azure/cli/command_modules/vm/tests/latest/keyvault/policy2.json, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_confidential_disk_encryption_set.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
See issue https://github.com/Azure/azure-cli/issues/22200
`az disk-encryption-set create`: `--encryption-type` support new value _**ConfidentialVmEncryptedWithCustomerKey**_ 
`az disk create`: add new argument `--secure-vm-disk-encryption-set` to provide DES created with  ConfidentialVmEncryptedWithCustomerKey encryption type
[Compute] `az disk-encryption-set create`: The `--encryption-type` parameter supports new value `ConfidentialVmEncryptedWithCustomerKey` for confidential VM
[Compute] `az disk create`: The `--security-type` parameter supports new value `ConfidentialVM_DiskEncryptedWithCustomerKey` for confidential VM
[Compute] `az disk create`: Add new parameter `--secure-vm-disk-encryption-set` to provide ID or …
=> [Compute] `az disk create` &`az disk-encryption-set create`: Support secure vm CMK

src/azure-cli/azure/cli/command_modules/vm/_arg_client.py, src/azure-cli/azure/cli/command_modules/vm/_help.py, src/azure-cli/azure/cli/command_modules/vm/_params.py, src/azure-cli/azure/cli/command_modules/vm/commands.py, src/azure-cli/azure/cli/command_modules/vm/custom.py, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_community_gallery_operations.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Feature request: #22222
- Add new command to support listing and community gallery by querying ARG REST
- GA shared/community image gallery related feature
Paging tests
[Compute] `sig list-community`: Add new command to support listing community gallery
[Compute] `sig list-community`: GA shared/community image gallery related feature
---
=> [Compute] `sig list-community`: Add new command to support listing community gallery and GA SIG related feature

doc/shorthand_syntax.md
=> {doc} update shorthand_syntax.md

src/azure-cli-core/azure/cli/core/extension/_resolve.py, src/azure-cli-core/azure/cli/core/extension/operations.py, src/azure-cli-core/azure/cli/core/extension/tests/latest/__init__.py, src/azure-cli-core/azure/cli/core/extension/tests/latest/test_resolve.py
`az extension add`
`az extension add --upgrade`
This pull request updates the feedback shown to users when azure cli is unable to install a requested extension, notably making it easier for extension authors to communicate that users may need to upgrade azure cli to use their extension.
Closes #21078
Specifically
* The user is now informed if there exists newer version of an extension that is **_incompatible_** with their version of azure cli and given recommendations to rectify the issue if there are no compatible versions available. This can occur when running:
* `az extension add --name ext_name --upgrade` 
&nbsp;
* `az extension add --name ext_name`
&nbsp;
* When running `az extension add --upgrade --name ext_name`, the user is now informed when …
=> [Core] `az extension add`: Improve feedback shown to users when installation is unsuccessful

azure-pipelines-full-tests.yml, azure-pipelines.yml
Python 3.6 has been deprecated (https://github.com/Azure/azure-cli/issues/19858), so we should drop Python 3.6 tests.
However, this PR can't be merged immediately yet since CentOS 7 only has deprecated Python 3.6 available (https://github.com/Azure/azure-cli/issues/19858#issuecomment-1002842707). 
Update: CentOS 7 RPM will be dropped by https://github.com/Azure/azure-cli/pull/23047
=> {CI} Drop Python 3.6 tests

src/azure-cli/azure/cli/command_modules/acs/_client_factory.py, src/azure-cli/azure/cli/command_modules/acs/_completers.py, src/azure-cli/azure/cli/command_modules/acs/_graph.py, src/azure-cli/azure/cli/command_modules/acs/_helpers.py, src/azure-cli/azure/cli/command_modules/acs/_resourcegroup.py, src/azure-cli/azure/cli/command_modules/acs/_roleassignments.py, src/azure-cli/azure/cli/command_modules/acs/addonconfiguration.py, src/azure-cli/azure/cli/command_modules/acs/custom.py, src/azure-cli/azure/cli/command_modules/acs/proxy.py, src/azure-cli/azure/cli/command_modules/acs/tests/hybrid_2020_09_01/test_aks_commands.py, src/azure-cli/azure/cli/command_modules/acs/tests/hybrid_2020_09_01/test_custom.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_custom.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_helpers.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py, src/azure-cli/azure/cli/command_modules/acs/win_proxy.py
Fix the issue where snapshot is not resolved according to the subscriptions field in the `--snapshot-id` option. Otherwise, when the subscription specified by `--snapshot-id` is inconsistent with the currently logged in subscription, an attempt will be made to obtain the corresponding snapshot through the currently logged in subscription, resulting in an error that the resource cannot be found.
---
=> [AKS] Fix snapshot not resolved according to the subscriptions field in the `--snapshot-id` option

src/azure-cli/azure/cli/command_modules/acs/_params.py, src/azure-cli/azure/cli/command_modules/acs/_validators.py, src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_validators.py
Fix the `NoneType` error that occurs when updating the incomplete addon profile of azure keyvault secret provider. Now its config will be backfilled as
```json
{
"enableSecretRotation": "false",
"rotationPollInterval": "2m"
}
```
A more explicit error is thrown when azure keyvault secret provider is not enabled, instructing the user to enable it via the `az aks enable-addons` command.
Fix issue [#5056](https://github.com/Azure/azure-cli-extensions/issues/5056).
---
This checklist is used to make sure that common guidelines for a pull request …
=> [AKS] `az aks update`: Fix the issue of `NoneType` error when updating the config of keyvault secret provider

doc/command_guidelines.md, doc/debug/debug_in_vs_code.md, doc/extensions/authoring.md, doc/install_linux_prerequisites.md, scripts/ci/build.sh, src/azure-cli-core/setup.py, src/azure-cli-telemetry/setup.py, src/azure-cli-testsdk/setup.py, src/azure-cli/setup.py
Close https://github.com/Azure/azure-cli/issues/19858 
Since we have dropped Python 3.6 tests (https://github.com/Azure/azure-cli/pull/20865), now we remove Python 3.6 from `classifiers` in order to officially announce the deprecation of Python 3.6 support.
=> [Packaging] Drop Python 3.6 support

src/azure-cli/azure/cli/command_modules/network/_help.py, src/azure-cli/azure/cli/command_modules/network/commands.py, src/azure-cli/azure/cli/command_modules/network/custom.py, src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_subnet_list_available_ips.yaml, src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
az network vnet subnet list-available-ips
close #13853 
Add new command 'az network vnet subnet list-available-ips' 
---
=> [Network] `az network vnet subnet list-available-ips`: Get list of available IPs for subnet 

azure-pipelines-full-tests.yml, azure-pipelines.yml
Although indent does not affect the code execution, reformat it to make it looks better.
---
=> {Misc.} Refomat azure pipeline yaml files

src/azure-cli/azure/cli/command_modules/storage/_params.py, src/azure-cli/azure/cli/command_modules/storage/_validators.py, src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_adls_fs_soft_delete.yaml
Fix #23093 
`az storage fs undelete-path -f {file-system-name} --deleted-path-name "t=2021-11-13 06%3A29%3A05.38 - Copy.png" --deletion-id {deletion-id} --account-name {account-name}
[Storage] `az storage fs undelete-path`: Encode `--deleted-path-name` automatically
---
=> [Storage] `az storage fs undelete-path`: Encode `--deleted-path-name` automatically

src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py
Fixes https://github.com/Azure/azure-cli/issues/23108
---
=> {RDBMS} Restoring a flexible server in another resource is currently not supported

src/azure-cli/azure/cli/command_modules/billing/_params.py
fixes Azure/azure-cli#23097
In this command, there is no documentation that shows where I can get the values for the "name" parameter. So this PR mentions to run the 'az billing period list' command to list the name of billing period' and then use this name in the 'az billing period show' command.
---
=> {AzureBilling} fix #23097

src/azure-cli/azure/cli/command_modules/appservice/custom.py
…nces/--number-of-workers option fail
Fixes https://github.com/Azure/azure-cli/issues/23135
---
=> [App Service] Fix #23135: `az functionapp plan create`: Add validation for the valid value of `--number-of-workers` option

src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py, src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
az network commands should support Microsoft.KubernetesConfiguration/privateLinkScopes resource as well for the private Endpoint Types
It added Microsoft.KubernetesConfiguration/privateLinkScopes to the az network supported provider
Added relevant test cases
---
=> [Network] `az network private-endpoint-connection`: Enable private link support for provider `Microsoft.KubernetesConfiguration/privateLinkScopes`

src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
`az aks create --vnet-subnet-id <> --enable-managed-identity`
There was a warning message, not recommend using "BYO vnet + system MSI" because granting permission may have latency. Now the latency is gone so remove the warning message.  
---
=> [AKS] Remove warning message when using "BYO vnet + system MSI"

src/azure-cli/azure/cli/command_modules/vm/custom.py
In `az vm run-command` and `az vmss run-command` groups, parameter `--protected-parameters` does not achieve the desired effect. The value provided by `--protected-parameters` is ignored and the value of `--parameters` is used repeatedly..
[Compute] Fix #22654: `az vm run-command create/update`: Parameter `--protected-parameters` does not achieve the desired effect
[Compute] `az vmss run-command create/update`: Parameter `--protected-parameters` does not achieve the desired effect
---
=> [Compute] Fix #22654: `az vm/vmss run-command`: Fix the bug that `--protected-parameters` does not achieve the desired effect

src/azure-cli-core/azure/cli/core/aaz/__init__.py, src/azure-cli-core/azure/cli/core/aaz/_command.py, src/azure-cli-core/azure/cli/core/commands/command_operation.py
=> [Core] `aaz`: Implement wait command

src/azure-cli/azure/cli/command_modules/profile/_format.py
`az account list`
`TenantId` is one of the most important fields of a subscription account. By adding `TenantId` to table output, this greatly simplifies the experience to check **which token is used to access this subscription** (instead of where the subscription belongs - `homeTenantId`):
```
> az account list --output table
Name                                             CloudName    SubscriptionId                        TenantId                              State    IsDefault
-----------------------------------------------  -----------  ------------------------------------  ------------------------------------  -------  -----------
Azure CLI Tests with TTL = 2 Days                AzureCloud   1c638cf4-608f-4ee6-b680-c329e824c3a8 …
```
=> [Profile] `az account list`: Add `TenantId` column to table output

src/azure-cli/azure/cli/command_modules/keyvault/custom.py
`az keyvault security-domain upload`
When uploading private keys with passphrase, it will raise exception:
```
> az keyvault security-domain upload --sd-exchange-key .\sdem.pem --hsm-name testhsm0713 --sd-file .\testhsm0527-SD.json --sd-wrapping-keys .\certs\ys_pass1.key .\certs\ys_pass2.key .\certs\ys_pass3.key --passwords 12345 1234 54321
password must be bytes-like
```
This PR should fix this.
---
=> [Keyvault] `az keyvault security-domain upload`: Fix `password must be bytes-like` for `--passwords`

src/azure-cli/azure/cli/command_modules/synapse/manual/_help.py, src/azure-cli/azure/cli/command_modules/synapse/manual/_params.py, src/azure-cli/azure/cli/command_modules/synapse/manual/operations/workspace.py
Add a parameter "last_commit_id" for git repo config.
---
=> [Synapse] `az synapse workspace`: Add `--last-commit-id` for git repo config

src/azure-cli/azure/cli/command_modules/synapse/manual/_client_factory.py, src/azure-cli/azure/cli/command_modules/synapse/manual/operations/accesscontrol.py, src/azure-cli/azure/cli/command_modules/synapse/tests/latest/recordings/test_access_control.yaml, src/azure-cli/azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py
az synapse 
Migrating from Azure SDK's AAD Graph to Microsoft Graph
#22174 
---
=> {synapse} az synapse module migration to Microsoft Graph

src/azure-cli-core/azure/cli/core/aaz/_arg_action.py, src/azure-cli-core/azure/cli/core/aaz/_base.py, src/azure-cli-core/azure/cli/core/aaz/_utils.py, src/azure-cli-core/azure/cli/core/tests/test_aaz_arg.py
[Core] `aaz`: Support blank value expression in `full value` of shorthand syntax
[Core] `aaz`: Support `singular quota string` for special property names in `partial value` key of shorthand synatx
---
=> {Core} `aaz`: Improve shorthand syntax

src/azure-cli/azure/cli/command_modules/serviceconnector/_params.py, src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py, src/azure-cli/azure/cli/command_modules/serviceconnector/custom.py, src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_webapp_sql_connection_string.yaml, src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/test_webpp_connection_scenario.py
* `az webapp connection create`
* `az webapp connection update`
Add a preview parameters `--store-connstr` for webapp + all sql, support customers to store their configuration into webapp connection string instead of appsettings.
add `test_webapp_sql_connection_string`
---
=> [Service Connector] `az webapp connection create`: Add `--store-connstr` to support webapp connection string

src/azure-cli/azure/cli/command_modules/storage/_params.py
`az storage fs directory create`
`az storage fs file create/upload`
Add description for setting sticky bit on ADLS Gen2
---
=> {Storage} Update description for setting sticky bit on ADLS Gen2

src/azure-cli/azure/cli/command_modules/iot/_utils.py, src/azure-cli/azure/cli/command_modules/iot/tests/latest/_test_utils.py, src/azure-cli/azure/cli/command_modules/iot/tests/latest/recordings/test_certificate_lifecycle.yaml, src/azure-cli/azure/cli/command_modules/iot/tests/latest/recordings/test_dps_certificate_lifecycle.yaml, src/azure-cli/azure/cli/command_modules/iot/tests/latest/test_iot_certificate_commands.py, src/azure-cli/azure/cli/command_modules/iot/tests/latest/test_iot_dps_commands.py
`az iot dps certificate create`
`az iot hub certificate create`
`az iot dps certificate update`
`az iot hub certificate update`
I am changing how certificates are opened to the older way of just encoding the contents to a b64 string and sending that string to the service. The service accepts more certificates this way. This is a response to a customer issue.
Added a test case to both the iot hub and dps certificate lifecycle tests. An extra certificate, which just has the certificate body copied twice, is created to mimic a chain certificate. This chain certificate is uploaded as a test that the service can handle the certificate (if the certificate body is not encoded in a b64 string, it would fail). 
The test recordings for …
=> [IoT] Change certificate loading to encode to b64 strings by default

src/azure-cli-core/azure/cli/core/commands/tests/test_validators.py, src/azure-cli-core/azure/cli/core/commands/validators.py, src/azure-cli-core/azure/cli/core/util.py
This PR is created according to the feedback on `az ad app federated-credential` (https://github.com/Azure/azure-cli/pull/22727).
`validate_file_or_dict` is used to parse argument that is either a JSON file or JSON string.
If the file exists, but contains invalid JSON string:
```
> az ad app federated-credential create --id 233dd73b-72e3-424a-9367-7588d957267e --parameters 'D:\test\fic-error.json'
Failed to parse D:\test\fic-error.json with exception:
Failed to parse JSON: {
"audiences": [
"api://AzureADTokenExchange"
],
"description": "Updated description"
"id": "f684b731-198c-406e-8c8d-f2dd23d93cdf",
"issuer": "https://token.actions.githubusercontent.com/",
"name": "Testing",
"subject": "repo:octo-org/octo-repo:environment:Production"
}
Error detail: Expecting ',' …
```
=> {Core} Provide error recommendation for `validate_file_or_dict`

src/azure-cli-core/setup.py, src/azure-cli-telemetry/HISTORY.rst, src/azure-cli-telemetry/azure/cli/telemetry/components/records_collection.py, src/azure-cli-telemetry/azure/cli/telemetry/tests/test_records_collection.py, src/azure-cli-telemetry/setup.py, src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt
CLI telemetry will only be uploaded when:
- 10 mins after last sync
- local cache file is larger than 128k and has been rotated with cache.1 cache.2 files
This could cause long time delay for pushing telemetry for customers using CLI not that frequently. It could take several days.
This PR set a threshold for cache file upload. If it has been 24 hours since last push, then cache file will be uploaded even if it's less than 128k.
The threshold can be set manually with `az config set telemetry.push_data_threshold=N`. It only takes effects when N >= 1. Default vaule for N is 24.
---
=> [Core] Support specifying `telemetry.push_interval_in_hours` to force push telemetry cache file

src/azure-cli-core/azure/cli/core/extension/operations.py
This PR fixes a bug when the extension rdbms-connect can't be installed because we need the library **libpq-dev** for Alpine Linux.
---
=> {Extension} Install library libpq-dev for extension rdbms-connect in Docker

src/azure-cli-core/azure/cli/core/profiles/_shared.py, src/azure-cli/azure/cli/command_modules/role/_help.py, src/azure-cli/azure/cli/command_modules/role/_msgrpah/_graph_client.py, src/azure-cli/azure/cli/command_modules/role/_params.py, src/azure-cli/azure/cli/command_modules/role/commands.py, src/azure-cli/azure/cli/command_modules/role/custom.py, src/azure-cli/azure/cli/command_modules/role/linter_exclusions.yml, src/azure-cli/azure/cli/command_modules/role/tests/latest/recordings/test_app_federated_credential.yaml, src/azure-cli/azure/cli/command_modules/role/tests/latest/test_graph.py
`az ad app federated-credential`
Refine `az ad app federated-credential` (https://github.com/Azure/azure-cli/pull/22727) according to [feedback](https://microsoft-my.sharepoint.com/:w:/p/shkhalid/EYLFU4VusuRCmdxF8ptgSvcBdMigy7VWp18mTS3fgDpcog?e=G3etkM):
1. Choose `--credential-id` instead of `--key-id` (see the feedback doc for rationale)
2. Not to have `az ad sp federated-credential` cmds and wait for customer feedback. We’ve mentioned a scenario in the doc where a customer with existing sp may look to add fic and they can do so using `az ad app federated-credential create`, which will add the fic to the backing application. To be consistent across tooling (Az CLI, Az PS, Graph PS), We are trying to gain clarity from MS graph PS team to hide the FIC SP …
=> [AD] `az ad app federated-credential`: Federated identity credential GA

src/azure-cli/azure/cli/command_modules/serviceconnector/_params.py, src/azure-cli/azure/cli/command_modules/serviceconnector/custom.py, src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/test_webpp_connection_scenario.py
* az webapp connection create
After discussion, we would like to change the argument introduced by #23288, from '--store-connstr' to '--config-connstr'.
As it wasn't released, I would change its title after this PR merged.
---
=> {Service Connector} update argument of #23288 

src/azure-cli/azure/cli/command_modules/storage/_params.py, src/azure-cli/azure/cli/command_modules/storage/operations/blob.py, src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_lease_operations.yaml, src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_blob_scenarios.py
`az storage blob metadata show/update`
Fix #23262 
`--lease-id` was missing during track2 migration for `az storage blob metadata`
---
=> [Storage] Fix #23262: `az storage blob metadata`: Add `--lease-id` back

src/azure-cli/azure/cli/command_modules/storage/_params.py, src/azure-cli/azure/cli/command_modules/storage/operations/blob.py, src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_download_directory.yaml, src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_oauth.yaml, src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_upload_small_file.yaml, src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_batch_operations.py
Fix #21875 
Add `--overwrite` to `az storage blob download/download-batch`, default value for download is true, for download-batch is false to match existing behavior. 
`az storage blob download -c {containername} -n {blobname} --account-name {accountname} -f {localfilepath} --overwrite false`
`az storage blob download-batch -s {sourcecontainername} --account-name {accountname} -d {destinationdirectorypath} --overwrite`
[Storage] `az storage blob download/download-batch`: Add `--overwrite`
---
=> [Storage] `az storage blob download/download-batch`: Add `--overwrite`

src/azure-cli/azure/cli/command_modules/acs/_roleassignments.py
Current implementation of checking cluster identity can't check inherited permission. This PR fixes the issue.
---
=> {AKS} Check inherited permission when granting permission to cluster identity

src/azure-cli/azure/cli/command_modules/batch/_params.py
`az batch pool create --help`
Updating help text of command argument `--json-file` to have a link to the json schema
[Batch] `az batch pool create`: Update help text for `--json-file` to point to json schema
=> [Batch] `az batch pool create`: Update help message for `--json-file` argument

src/azure-cli/azure/cli/command_modules/container/custom.py
`az container create`
Fixes #20280
Allows environment variable interpolation in container group yaml. `${MY_ENV}` is replaced with the value of `MY_ENV` environment variable if present and not changed if the environment variable is not present. It works with a prefix or a suffix as well. For example, `secret-${MY_ENV}` or `${MY_ENV}-world` or `secret-${MY_ENV}-world` will work as well.
```bash
export $AZ_RESOURCE_GROUP=azure-cli-dev
export $AZ_LOCATION=centralindia
az group create --location $AZ_LOCATION --name $AZ_RESOURCE_GROUP
export MY_ENV=hello
cat <<EOF > aci-nginx.yml
name: aci-nginx
apiVersion: '2021-10-01'
location: centralindia
properties: 
containers: 
- name: nginx
properties: 
image: nginx
ports: 
- protocol: TCP
port: 80 …
```
=> [Container] Fix #20280: `az container create`: Allow environment variable interpolation in container group yaml

src/azure-cli/azure/cli/command_modules/acs/_help.py
Add a note on how to deploy Windows Server 2022 nodes.
az aks nodepool add
Currently, the description shows the values for --os-type for Linux only, there should be an option for Windows, now that Windows Server 2022 is an option (in addition to Windows Server 2019, which is the default).
az aks nodepool add \
--resource-group myResourceGroup \
--cluster-name myAKSCluster \
--os-type Windows \
--os-sku Windows2022 \ 
--name npwin \
--node-count 1
---
=> {ACS} Update help message to include note on Windows Server 2022 for `--os-type` parameter

linter_exclusions.yml, src/azure-cli/azure/cli/command_modules/acs/_consts.py, src/azure-cli/azure/cli/command_modules/acs/_help.py, src/azure-cli/azure/cli/command_modules/acs/_params.py, src/azure-cli/azure/cli/command_modules/acs/_validators.py, src/azure-cli/azure/cli/command_modules/acs/custom.py, src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_validators.py
az aks create --enable-azure-keyvault-kms --azure-keyvault-kms-key-id {} --azure-keyvault-kms-key-vault-network-access {} --azure-keyvault-kms-key-vault-resource-id {}
This PR allows the customer to enable KMS feature for AKS cluster, which [encrypts the Kubernetes data in etcd using Azure Key Vault with Key Management Service (KMS) plugin](https://docs.microsoft.com/en-us/azure/aks/use-kms-etcd-encryption).
[AKS] `az aks create`: Add Key Management Service feature for AKS to encrypt the Kubernetes data in etcd using Azure Key Vault with KMS plugin
---
=> [AKS] Add Key Management Service feature for AKS to encrypt the Kubernetes data in etcd using Azure Key Vault with KMS plugin

azure-pipelines.yml
According to https://wiki.ubuntu.com/Releases, **Ubuntu 21.10 Impish Indri** will reach its End of Life at July 14, 2022. Azure CLI should drop its support.
=> [Packaging] Drop Ubuntu 21.10 Impish Indri DEB package

src/azure-cli/azure/cli/command_modules/cosmosdb/custom.py
Fixes https://github.com/Azure/azure-cli/issues/23299
---
=> {cosmosdb} Fix #23299: Fix a typo

src/azure-cli/azure/cli/command_modules/vm/_help.py, src/azure-cli/azure/cli/command_modules/vm/_params.py, src/azure-cli/azure/cli/command_modules/vm/commands.py, src/azure-cli/azure/cli/command_modules/vm/custom.py, src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2018_03_01/test_custom_vm_commands.py, src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/test_custom_vm_commands.py, src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/test_custom_vm_commands.py, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_force_detach.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_custom_vm_commands.py, src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Add parameter `--force-detach` in `az vm disk detach` to suppo force-detaching managed data disks from a VM. 
Close #16912
[Compute] `az vm disk detach`: Add parameter `--force-detach` to support force-detaching managed data disks from a VM
---
=> [Compute] `az vm disk detach`: Add parameter `--force-detach` to support force-detaching managed data disks from a VM

src/azure-cli/azure/cli/command_modules/sql/_help.py
Fix https://github.com/Azure/azure-cli/issues/23357
---
=> {SQL} Fix #23357: Fix typo from Directly to Directory

src/azure-cli/azure/cli/command_modules/serviceconnector/_params.py, src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
=> [Service Connector] `Az webapp connection create`: Use webapp name and rg from config

azure-pipelines.yml
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1740378&view=results
We got warning in ADO that `macOS-10.15` is deprecated:
We switch to the latest `macOS-12`.
=> {CI} Use `macOS-12`

src/azure-cli/azure/cli/command_modules/sql/custom.py
Fixes https://github.com/Azure/azure-cli/issues/13600
---
=> {SQL} Fix #13600 Add message for compute model check

src/azure-cli/azure/cli/command_modules/acr/connected_registry.py
az acr connected-registry create
Error states --sync-token-name when the flag is --sync-token
Try to create a connected registry without using sync-token nor repository flags
---
=> [ACR] Connected registry error help command typo

doc/extensions/authoring.md
Found a broken link (extra "b") and change instances of `master` branch to `main` (verified all were correct).
=> {Misc.} Fix links and change master -> main

src/azure-cli-core/azure/cli/core/aaz/_command.py
=> [Core] `aaz`: Support to use cli_ctx to initiate AAZCommand class

src/azure-cli/azure/cli/command_modules/batch/_validators.py
fixes Azure/azure-cli#23445
Getting supported images list for an Azure Batch pool fails with nondescript error 'NoneType' object has no attribute 'startswith'.
This PR fixes this error.
---
=> [Batch] Fix #23445: `az batch pool supported-images list`: Fix the `NoneType object has no attribute startswith` bug for getting supported images list

src/azure-cli/azure/cli/command_modules/netappfiles/_help.py
Fixes https://github.com/Azure/azure-cli/issues/15209
---
=> {netapps} Fix #15209: Update the description of the vnet

src/azure-cli/azure/cli/command_modules/rdbms/_helptext_mysql.py, src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py
Fix Typo in mysql flexibile server cmdlet summary
Fixes [23480](https://github.com/Azure/azure-cli/issues/23480)
---
=> {RDBMS} Fix Typo in mysql flexibile server cmdlet summary

src/azure-cli/azure/cli/command_modules/acs/_params.py, src/azure-cli/azure/cli/command_modules/acs/_validators.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_validators.py
`az aks nodepool wait`
The implementation of the `az aks nodepool wait` command directly calls the operation provided by the SDK, and the parameter name used to identify the nodepool name is `agent_pool_name`, which is different from the parameter name `nodepool_name` in the custom implemented nodepool commands.
The fix is to add a new dedicated validator for the command. Also added some unit tests. See sibling PR [#5219](https://github.com/Azure/azure-cli-extensions/pull/5219).
Fix issue [#23468](https://github.com/Azure/azure-cli/issues/23468).
---
This …
=> [AKS] Fix #23468: `az aks nodepool wait` crashes with error "'Namespace' object has no attribute 'nodepool_name'"

src/azure-cli/azure/cli/command_modules/servicefabric/custom.py
Fix https://github.com/Azure/azure-cli/issues/16717. Though the bug is not directly related to the issue, while debugging this issue surfaces while giving wrong node type as parameter.
---
=> {servicefabric} Fix #16717: Validate an empty array of node types

src/azure-cli/azure/cli/command_modules/acs/_consts.py, src/azure-cli/azure/cli/command_modules/acs/_params.py, src/azure-cli/azure/cli/command_modules/acs/_validators.py, src/azure-cli/azure/cli/command_modules/acs/custom.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_validators.py
`az aks check-acr`
Based on the changes in PR [#23505](https://github.com/Azure/azure-cli/pull/23505), now the acr suffix is appended according to current cloud env. For Germany and air gapped cloud env, since no pre-defined acr suffix provided in [cloud.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/cloud.py#L397), would skip appending suffix.
---
=> [AKS] `az aks check-acr`: Append acr suffix to option `--acr` acording to cloud env

src/azure-cli-core/azure/cli/core/auth/adal_authentication.py, src/azure-cli-core/azure/cli/core/auth/credential_adaptor.py
When command modules such as `resource` or `network` call `get_login_credentials`, it specifies `aux_subscriptions` or `aux_tenants`. The returned `CredentialAdaptor` contains internal credentials for these aux tenants. `_prepare_mgmt_client_kwargs_track2` will then call `get_auxiliary_tokens` to get aux tokens.
However, managed identity is single-tenanted and has no cross-tenant support, so `MSIAuthenticationWrapper` doesn't expose  `get_auxiliary_tokens`.
In Azure CLI Core, we have logic to prevent calling `get_auxiliary_tokens` on `MSIAuthenticationWrapper`:https://github.com/Azure/azure-cli/blob/110f7b402020f3d3ebd2bfb923ac5a01d026cdd1/src/azure-cli-core/azure/cli/core/commands/client_factory.py#L184
`AAZBearerTokenCredentialPolicy` assumes `get_auxiliary_tokens` is …
=> {Auth} Make `MSIAuthenticationWrapper` expose `get_auxiliary_tokens`

src/azure-cli/azure/cli/command_modules/vm/_validators.py, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_ppg_intent_vm_sizes_and_zone.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Issue - close: #23540 
`az ppg create`
This issue was introduced by PR #23167
Because after the command `az ppg create` adds the command level validator `process_ppg_create_namespace`, the original parameter level validator `validate_tags` is overwritten.
https://github.com/Azure/azure-cli/blob/c0aa8c496775a5db27f37fb7504b80a8ccbb5f58/src/azure-cli/azure/cli/command_modules/vm/_params.py#L1413
https://github.com/Azure/azure-cli/blob/c0aa8c496775a5db27f37fb7504b80a8ccbb5f58/src/azure-cli-core/azure/cli/core/commands/parameters.py#L280-L284
https://github.com/Azure/azure-cli/blob/c0aa8c496775a5db27f37fb7504b80a8ccbb5f58/src/azure-cli-core/azure/cli/core/commands/validators.py#L38-L44
Therefore, this PR adds back the `validate_tags` validator.
**Testing …
=> [Compute] Fix #23540: `az ppg create`: Fix the `Parameter tags must be of type dict` error when `--tags` parameter is passed as `key=value` pairs

src/azure-cli/azure/cli/command_modules/profile/_help.py
`az account show`
Remove help message for `--sdk-auth`. `--sdk-auth` was dropped from `az account show` in https://github.com/Azure/azure-cli/pull/21219.
This PR removes the old help message.
See https://portal.microsofticm.com/imp/v3/incidents/details/328318460/home
=> {Profile} `az account show`: Remove help message for `--sdk-auth`

src/azure-cli-core/azure/cli/core/telemetry.py, src/azure-cli-core/setup.py, src/azure-cli-telemetry/HISTORY.rst, src/azure-cli-telemetry/azure/cli/telemetry/__init__.py, src/azure-cli-telemetry/setup.py, src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt
This PR allows command modules & cli extensions to add their own appInsights key to collect all existing cli events.
The cli events sent to CLI's AppInsights are stored in local cache file.
While those sent to dedicated AppInsights will be flushed immediately
We can define a decorator:
```
def add_telemetry_dedicated_key(key=''):
def _decorator(func):
@wraps(func)
def _wrapped_func(*args, **kwargs):
if key:
from azure.cli.core import telemetry
telemetry.add_dedicated_instrumentation_key(key)
return func(*args, **kwargs)
return _wrapped_func
return _decorator
```
And then add the decorator for any command's custom function:
```
@add_telemetry_dedicated_key(key='02b91c82-6729-4241-befc-e6d02ca4fbba')
def create_xxx_func(cmd, client, resource_name,...):
``` …
=> [Core] Allow adding dedicated key for collecting cli telemetry

src/azure-cli/azure/cli/command_modules/vm/_help.py, src/azure-cli/azure/cli/command_modules/vm/_params.py, src/azure-cli/azure/cli/command_modules/vm/custom.py, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_update_gallery_permissions.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
In `az sig update` command, add parameters, which previously only applied to `az sig create` command, to support updating gallery from private to community and from community to private.
Use `az sig share reset` command to support reset gallery to private. 
Close #22223
[Compute] `az sig update`: Add parameters to support updating gallery from private to community
[Compute] `az sig share reset`: Update gallery from community to private
---
=> [Compute] `az sig`: Enable private and community conversion for gallery

src/azure-cli-core/azure/cli/core/telemetry.py
Fix #23409 
We will save cloud name info to telemetry which will be stored in `Context.Default.AzureCLI.CloudName` within `Properties` field
Run any cli command and check local cache file ($home_dir/.azure/telemetry/cache)
Search for `Context.Default.AzureCLI.CloudName`
---
=> {Telemetry} Collect `Context.Default.AzureCLI.CloudName` info

src/azure-cli/azure/cli/command_modules/eventgrid/custom.py
This fix is related to multiple az commands, such as az eventgrid event-subscription update, az eventgrid topic event-subscription update, az eventgrid domain event-subscription update, etc, as these event-subscription update commands all call the same internal method.
Our internal validation method is incorrectly checking for the user to specify both the --deadletter-identity and **--deadletter-endpoint**, when it should be checking for --deadletter-identity and **--deadletter-identity-endpoint**.
az eventgrid event-subscription update --source-resource-id {source_resource_id_with_identity} -n {event_subscription_name} --deadletter-identity-endpoint {deadletter_endpoint_id} --deadletter-identity sytemassigned
--- …
=> {EventGrid} `az eventgrid topic/domain event-subscription update`: Fix validation of deadletter identity parameters

src/azure-cli/azure/cli/command_modules/rdbms/_helptext_mysql.py, src/azure-cli/azure/cli/command_modules/rdbms/_params.py, src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_commands.py, src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_common.py, src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_flexible_server_upgrade_mgmt.yaml, src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands.py
`az mysql flexible-server upgrade`
This PR enables major version upgrades for MySQL flexible server.
Example of how to create a server with version 5.7 and update it to version 8:
- `az mysql flexible-server create -g testgroup -n testsvr --public-access none --tier GeneralPurpose --sku-name Standard_D2ds_v4 --location eastus --version 5.7`
- `az mysql flexible-server parameter set -g testgroup -s testsvr -n sql_mode -v "ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO"`
- `az mysql flexible-server upgrade -g testgroup -n testsvr --version 8`
---
=> [RDBMS] `az mysql flexible-server upgrade`: Add major version upgrade for MySQL flexible server

src/azure-cli/azure/cli/command_modules/acs/addonconfiguration.py
This PR is updating the creation of the DCR to the clusters resource group instead of the workspaces resource group to make it consistent with our new addon experience (managed prometheus azure monitor metrics addon)
az aks enable-addons -a monitoring --enable-msi-auth-for-monitoring -g kaveeshclitest -n kaveesh11
Use the flag '--enable-msi-auth-for-monitoring' to be able to test that the new MSI is being created in the clusters resource group.
---
=> {AKS} update logs DCR to cluster resource group instead of workspace resource group for consistency with Prometheus Addon

src/azure-cli/azure/cli/command_modules/network/_help.py, src/azure-cli/azure/cli/command_modules/network/commands.py, src/azure-cli/azure/cli/command_modules/network/custom.py
```sh
az network bastion create --name {} --resource-group {} --vnet-name {} --public-ip-address {} --no-wait
az network bastion wait --name {} --resource-group {} --created
```
This PR adds `--no-wait` support (and the corresponding `wait` command) to `az network bastion`, allowing for no wait scenarios where one does not need to wait for bastion creation to complete.
Resolves #22594
Follow [this section](https://docs.microsoft.com/en-us/azure/bastion/create-host-cli#createhost) except that the last command should also include the `--no-wait` argument. Then, the following command can be run (typically later in a script as required)
```sh
az network bastion wait --name {} --resource-group {} --created
```
--- …
=> [Network] Fix #22594: `az network bastion create`: Add no wait support for bastion create

src/azure-cli/azure/cli/command_modules/rdbms/_flexible_server_util.py, src/azure-cli/azure/cli/command_modules/rdbms/_params.py, src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py, src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands.py, src/azure-cli/azure/cli/command_modules/rdbms/validators.py
- `az postgres flexible-server create -g testGroup -n testSrv --high-availability SameZone ...`
- `az postgres flexible-server update -g testGroup -n testSrv --high-availability SameZone ...`
We need to add `SameZone` as a possible value for argument `--high-availability` in PostgreSQL flexible server, just as MySQL already does.
---
=> [RDBMS] `az postgres flexible-server create/update`: Add `SameZone` for HA in PostgreSQL flexible server

src/azure-cli/azure/cli/command_modules/rdbms/_client_factory.py, src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_mysql.py, src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_flexible_server_check_name_availability_fallback_mgmt.yaml, src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands.py, src/azure-cli/azure/cli/command_modules/rdbms/validators.py
When we want to check if a server name is available for MySQL flexible server, we make a call to the endpoint `/subscriptions/{subscriptionId}/providers/Microsoft.DBforMySQL/locations/{locationName}/checkNameAvailability`. But if it fails with HTTP 403, we need to fallback to the endpoint without location `/subscriptions/{subscriptionId}/providers/Microsoft.DBforMySQL/checkNameAvailability` as the Portal does.
---
=> {RDBMS} Add check_name_availability_without_location as fallback in MySQL flex

scripts/ci/automation_full_test.py, src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_express_route_port.yaml
There's a strange phenomenon in our dev CI (eg https://github.com/Azure/azure-cli/runs/7969635224) that
- `Automation Full Test` all pass
- `Test XX Package` fail in `test_network_express_route_port`
The `test_network_express_route_port` fails because of keyvault bumping version without rerecording `test_network_express_route_port.yaml`. This failure doesn't show up in [keyvault bump version PR](https://github.com/Azure/azure-cli/pull/23621) either
This PR:
- fix `Automation Full Test` doesn't fail issue
- fix `test_network_express_route_port` recording failure
---
=> {CI} Fix automation full test not failure issue

src/azure-cli-core/azure/cli/core/auth/identity.py
Fix https://github.com/Azure/azure-cli/issues/23320
`az login`
Currently device code message is printed using `logger.warning` which is controlled by `core.only_show_errors` config option. If `core.only_show_errors` is set to `true`, device code message will be hidden.
This PR switches to `print_styled_text` so that device code message is printed directly to `sys.stderr`, regardless of `core.only_show_errors` config option.
```
az login --use-device-code
```
=> {Auth} Show device code message regardless of `core.only_show_errors` config option

src/azure-cli/azure/cli/command_modules/acs/_help.py, src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
- `az aks update`
- `az aks nodepool update`
Add support for calling `az aks update` and `az aks nodepool update` with no optional arguments, which attempts to move the cluster/node pool to its goal state without changing the current cluster/node pool configuration. This can be used to move out of a non-succeeded state.
Sync PR [#4759](https://github.com/Azure/azure-cli-extensions/pull/4759).
---
=> [AKS] `az aks update`: Update without args prompts to reconcile

src/azure-cli/azure/cli/command_modules/rdbms/validators.py
`az mysql flexible-server create/update`
Fixing a condition check for servers with geo-redundant backup enabled: if we are going to create/update a geo-redundant server and touch data encryption properties, we need to set both principal keys and backup keys; but if we don't want to touch that properties and instead update other things the check will fail and ask for backup key anyway when it's not intended. So, the fix is just to detect if **principal key is provided but backup key is not provided**, not only check if the backup key is not provided.
---
=> {RDBMS} Fix check for data encryption for geo-redundant server

linter_exclusions.yml, src/azure-cli/azure/cli/command_modules/backup/_params.py, src/azure-cli/azure/cli/command_modules/backup/custom.py, src/azure-cli/azure/cli/command_modules/backup/custom_base.py, src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_restore_when_storage_in_different_rg.yaml, src/azure-cli/azure/cli/command_modules/backup/tests/latest/test_backup_commands.py
```pwsh
az backup restore restore-disks
```
This PR comes to fix the case when we want to do a restore, but the storage account is in a different resource group than the vault. More information here: #23655 
We now can support this scenario by adding a new param `--storage-account-resource-group` that indicates the resource group of the storage account.
If `--storage-account-resource-group` is not passed, `--storage-account-resource-group` will default to the value of the `--resource-group` parameter.
```pwsh
az backup restore restore-disks \
--resource-group {rg} \
--vault-name {vault_name} \
--container-name {vm} \
--item-name {vm} \
--storage-account {sa} \
--storage-account-resource-group {sa_rg} \
--rp-name {rp}
```
**History …
=> [Backup] Fix #23655: `az backup restore restore-disks`: Support storage account being in a different resource group

src/azure-cli/azure/cli/command_modules/iot/_help.py
Added quotes to the --connection-string command, otherwise the call will fail, and the error message in CLI is not friendly either.
---
=> {IOT} Fix `az iot dps linked-hub create` examples in _help.py

src/azure-cli/azure/cli/command_modules/vm/_vm_utils.py, src/azure-cli/azure/cli/command_modules/vm/custom.py, src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
In `az vm list-skus` command, fix filtering out VM sizes that are available regionally when they are restricted in all zones
Close #23341
[Compute] Fix #23341: `az vm list-skus`: Fix filtering out VM sizes that are available regionally when they are restricted in all zones
---
=> [Compute] Fix #23341: `az vm list-skus`: Fix filtering out VM sizes that are available regionally when they are restricted in all zones

src/azure-cli/azure/cli/command_modules/sql/custom.py
az sql server update
Calling ```az sql server update -n X -g Y -p Y``` output a debug info block that broke parsing for parent script.
I removed the debug output, fixing the problem.
Example of the problem:
```
az sql server update -n sql-[redacted] -g rg-[redacted] -p [redacted] --output jsonc
{'additional_properties': {}, 'user_assigned_identities': None, 'principal_id': '[redacted]', 'type': 'SystemAssigned', 'tenant_id': '[redacted]'}
{
"administratorLogin": "[redacted]",
"administratorLoginPassword": null,
"administrators": {
"administratorType": "ActiveDirectory",
"azureAdOnlyAuthentication": false,
"login": "[redacted]",
"principalType": "Group",
"sid": "[redacted]",
"tenantId": "[redacted]"
},
``` 
Fixed output:
```
az sql server update -n …
```
=> {SQL} `az sql update`: Remove debug output

src/azure-cli/azure/cli/command_modules/acs/_params.py, src/azure-cli/azure/cli/command_modules/acs/_validators.py
fixes Azure/azure-cli#23653
When using 'az aks create' to build an AKS cluster, if you set --network-policy to 'Calico' vs. 'calico', the cluster will successfully create, but there will be system pods in CrashLoopBackOff.
--network-policy = calico  --> works fine.
--network-policy = Calico --> results in CrashLoopBackOff issue.
---
=> [AKS] Fix #23653: `az aks create`: Fix the CrashLoopBackOff issue when set `--network-policy` to 'Calico'

src/azure-cli/azure/cli/command_modules/ams/_validators.py
`az ams job start --account-name accountName --input-asset-name "inputAssetName" --files "fileName" --transform-name "transformName" --output-assets "outputasset" -g rg --name "jobName"`
Related to this stack overflow question: https://stackoverflow.com/questions/73525827/azure-cli-az-ams-job-start-is-returning-index-out-of-range?newreg=ad82ab836d0a4c85a8a95ec008a7df9a
`az ams job start --account-name accountName --input-asset-name "inputAssetName" --files "fileName" --transform-name "transformName" --output-assets "outputasset" -g rg --name "jobName"`
Above command produces new error output
[Component Name 2] `az command b`: …
=> {AMS} `az ams job start`: Update error message

src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Fix monitoring addon related test cases. The resource group for dcr has been changed from workspace rg to cluster rg by PR [#23630](https://github.com/Azure/azure-cli/pull/23630).
---
=> {AKS} Fix monitoring addon related test cases

src/azure-cli/azure/cli/command_modules/role/_help.py
The example for `az ad sp create-for-rbac` specifies scope as `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup1}`. Even though curly brackets denote placeholders in the example, some users may include the curly brackets in the actual scope as `/subscriptions/{e906c0aa-f6b1-4341-8bd4-bf98681c8713}`, which causes failure (#15739, #23160, #23198):
```
KeyError: 'e906c0aa-f6b1-4341-8bd4-bf98681c8713'
```
This PR removes curly brackets to eliminate unnecessary confusion.
Question: Will `$subscription_id` also cause confusion and will some users use it as `/subscriptions/$e906c0aa-f6b1-4341-8bd4-bf98681c8713`?
=> {Role} `az ad sp create-for-rbac`: Remove curly brackets from example command

doc/quoting-issues-with-powershell.md
Since we have now added `ps1` entry scripts for PowerShell and PowerShell 7.3 fixed the dropping-double-quote issue, this document is no longer valid for the latest versions of these tools.
We notify the reader the document is obsolete.
=> {Doc} Update `quoting-issues-with-powershell.md` to reflect recent fixes

src/azure-cli/azure/cli/command_modules/role/_params.py
`az ad`
Close #23812
In in-tool help, the examples appear **below** the argument help.
```
> az ad app create -h
...
JSON property Arguments
--app-roles                    : The collection of roles assigned to the application. With app
role assignments, these roles can be assigned to users, groups,
or service principals associated with other applications.
Should be JSON file path or in-line JSON string. See examples
below for details.
...
Examples
...
Create an application with a role
az ad app create --display-name mytestapp --identifier-uris https://mytestapp.websites.net
--app-roles @manifest.json
("manifest.json" contains the following content)
[{
"allowedMemberTypes": [
"User"
],
"description": "Approvers can mark documents as approved", …
```
=> {AD} Remove "below" from JSON arguments' help message

src/azure-cli-core/setup.py, src/azure-cli/setup.py
Python 3.6 is droped in https://github.com/Azure/azure-cli/pull/23102, so the `python_requires` in `setup.py` should also update.
---
=> {Packaging} Increase minimum python_requires to 3.7

src/azure-cli/azure/cli/command_modules/appconfig/_kv_helpers.py
Exporting a store to a file:
`az appconfig kv export -d file --path outputfile.json --format json --label * --profile appconfig/kvset -n "MyStoreName" --yes`
Prevents MemoryError crash while exporting AppConfig stores by reducing memory allocation from ~5GB to ~1.5GB for config stores containing about 1GB data.
Manual testing with large store using command above.
---
=> [App Config] `az appconfig kv export`: Fix MemoryError while exporting large stores

src/azure-cli/azure/cli/command_modules/storage/_client_factory.py, src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_extended_location.yaml, src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_list_scenarios.yaml, src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
`az storage container`
When use non-standard account URL, account name can't be parsed from URL, thus `ValueError: Unable to determine account name for shared key credential` is raised. In this PR, it will use credential dict if `account_name` is provided.
Close https://github.com/Azure/azure-cli/issues/23702. 
`az storage account create --name <name> --resource-group <rg> --edge-zone microsoftrrdclab1 -l eastus2euap`
`az storage container create -n test --blob-endpoint <blob-endpoint> --account-name <name> --account-key <account-key>`
---
=> [Storage] `az storage blob/container`: Support `--account-name` for non-standard account URL

src/azure-cli/azure/cli/command_modules/cdn/_help.py
In the documentation the definitions of az afd origin-group create and az aft origin-group update commands' descriptions are same which is "Creates a new origin group within the specified profile". Definition of update command needs to be updated.
This PR updates the description of az afd origin-group update command.
fixes Azure/azure-cli#23864
---
=> {Front Door} Fix #23864: `az afd origin-group update` description

src/azure-cli-core/azure/cli/core/_profile.py, src/azure-cli-core/azure/cli/core/auth/identity.py, src/azure-cli-core/azure/cli/core/auth/util.py, src/azure-cli-core/azure/cli/core/azclierror.py, src/azure-cli-core/setup.py, src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt
`az login`
Close #21201
Require https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/415
Rework https://github.com/Azure/azure-cli/pull/22774
On Windows, users can opt in WAM login using:
```
az config set core.allow_broker=true
```
Then run
```
az login
```
Instead of launching a web browser, an account selector will be shown to ask the user to select a Windows account:
[Core] PREVIEW: Support Web Account Manager (WAM) login on Windows. To opt in, run `az config set core.allow_broker=true`
**Additional information**
WAM will be enabled by default in year 2023.
=> [Core] PREVIEW: Support Web Account Manager (WAM) login on Windows

src/azure-cli/azure/cli/command_modules/rdbms/_params.py, src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_mysql.py, src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_flexible_server_georestore_update_mgmt.yaml, src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands.py, src/azure-cli/azure/cli/command_modules/rdbms/validators.py
`az mysql flexible-server update`
This PR enables the argument `--geo-redundant-backup` when updating a MySQL flexible server with possible values `Enabled` and `Disabled`.
- Create MySQL flexible server without geo redundant backup: `az mysql flexible-server create -g resourceGroup -n serverName -l location --public-access none --tier GeneralPurpose --sku-name Standard_D2ds_v4`
- Enable geo redundant backup: `az mysql flexible-server update -g resourceGroup -n serverName --geo-redundant-backup Enabled`
- Disable geo redundant backup: `az mysql flexible-server update -g resourceGroup -n serverName --geo-redundant-backup Disabled`
---
=> [RDBMS] `az mysql flexible-server update`: Expose `--geo-redundant-backup` argument

scripts/release/homebrew/docker/formula_template.txt
---
----
update brew PR template, relates to https://github.com/Homebrew/homebrew-core/pull/109727
=> {Packaging} Update Homebrew template to use python3.10 executable

src/azure-cli/azure/cli/command_modules/rdbms/_helptext_mysql.py, src/azure-cli/azure/cli/command_modules/rdbms/_params.py, src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_mysql.py, src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py, src/azure-cli/azure/cli/command_modules/rdbms/validators.py
`az mysql/postgres flexible-server create/update`
`Enabled` value for `--high-availability` argument in commands `az mysql/postgres flexible-server create/update` will be deprecated by the next release in April 2023. The possible values for that argument will be only `ZoneRedundant`, `SameZone` and `Disabled`, the value `Enabled` is the same as `ZoneRedundant`. For now, we'll still allow to use `Enabled` but we change the warning message to include the date when it will be removed.
---
=> [RDBMS] `az mysql/postgres flexible-server create/update`: Deprecate `Enabled` for `--high-availability` argument

src/azure-cli/azure/cli/command_modules/sql/commands.py, src/azure-cli/azure/cli/command_modules/sql/custom.py
fixes Azure/azure-cli#23885
az sql db import/export commands can take so long to run that it will time out the CLI or DevOps pipeline leveraging AzureCLI.
SO this PR addresses this issue by adding the --no-wait parameter to these commands.
---
=> {SQL} fixes Azure/azure-cli#23885 - commands.py

src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_common.py
`az mysql flexible-server stop`
For MySQL flexible server there was a change that allows the server to stop for 30 days, so we need to change the logging message that still says 7 days. For PostgreSQL there is no change.
---
=> [RDBMS] `az mysql flexible-server stop`: Change stopped time logging message

src/azure-cli/azure/cli/command_modules/storage/operations/account.py
`az storage account update`
Suppose we have a storage account with such file identity auth property:
```
az storage account show -n testsa0923 -g test0923
{
......
"azureFilesIdentityBasedAuthentication": {
"activeDirectoryProperties": {
"accountType": null,
"azureStorageSid": "S-1-5-21-1234567890-1234567890-1234567890-1234",
"domainGuid": "12345678-1234-1234-1234-123456789012",
"domainName": "mydomain.com",
"domainSid": "S-1-5-21-1234567890-1234567890-1234567890",
"forestName": "mydomain.com",
"netBiosDomainName": "mydomain.com",
"samAccountName": null
},
"defaultSharePermission": "None",
"directoryServiceOptions": "None"
},
......
}
```
When updating `defaultSharePermission` under `azureFilesIdentityBasedAuthentication`, `activeDirectoryProperties` …
=> [Storage] `az storage account update`: Fix updating `--default-share-permission` will wipe out other ADProperties issue

src/azure-cli/azure/cli/command_modules/keyvault/_params.py
`az keyvault secret set`
Fix #23527 
Customer would think there's no parameter for setting secret content type, but actually we have `--description` for this.
This PR adds `--content-type` as alternative option for `--description` to reduce confusion
---
=> [Keyvault] Fix #23527: `az keyvault secret set`: Add alias `--content-type` for `--description`

src/azure-cli/azure/cli/command_modules/resource/custom.py
`az deployment group what-if`
The `mode` parameter was hard coded to `increment`, but it should take the value provided by users via `--mode`. The PR fixes the behavior.
`az deployment group what-if ... --mode complete`
---
=> [ARM] `az deployment group what-if`: Fix an issue where `complete` deployment mode does not work

src/azure-cli/azure/cli/command_modules/ams/operations/account.py
fixes Azure/azure-cli#23937
Looking at this test case https://github.com/phcooper/azure-cli/blob/1e7f7962df34f3104db4f2eefdcbdfe46ccd4bc1/src/azure-cli/azure/cli/command_modules/ams/tests/latest/test_ams_account_scenarios.py#L34 
It clearly indicates that the Resource Group and Account name both are required.
Currently the CLI command az ams account show --name <mediaservicename> throws the below error:
File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
show_exception_handler(ex)
File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/arm.py", line 429, in show_exception_handler
raise ex
File …
=> {AzureMediaService} fixes Azure/azure-cli#23937

src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_common.py, src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_flexible_server_identity_aad_admin_mgmt.yaml, src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands.py
`az mysql flexible-server ad-admin delete`
When dropping the AAD admin for a MySQL flexible sever, we should disable automatically **AAD authentication only** because customer won't be able to connect again to the server using username and password. He can disable it manually by setting `aad_auth_only` to `OFF` and connect again, but the idea is to do this automatically to avoid confusion.
- Create an AAD admin for an existing server: `az mysql flexible-server ad-admin create -g resourceGroup -s serverName -u login -i sid --identity userIdentity`
- Enable AAD authentication only: `az mysql flexible-server parameter set -g resourceGroup -s serverName -n aad_auth_only -v ON`
- Delete the AAD admin: `az mysql flexible-server ad-admin …
=> [RDBMS] `az mysql flexible-server ad-admin delete`: Disable `aad_auth_only` when dropping AAD admin

src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py, src/azure-cli/azure/cli/command_modules/rdbms/_params.py, src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_common.py
This PR reverts this PR:
https://github.com/Azure/azure-cli/pull/21231
---
=> {RDBMS}: Switch Back to Online migration by default for PG single to flex migrations using DMS

src/azure-cli/azure/cli/command_modules/acs/custom.py, src/azure-cli/azure/cli/command_modules/acs/tests/hybrid_2020_09_01/test_custom.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_custom.py
Note: A new warning level log message (to stderr) is added to the command.
Fix issue #23779.
After this change, the binary file corresponding to the arch of kubectl/kubelogin that needs to be downloaded will be determined by the result returned by `platform.processor()`.
Sample screenshot
---
=> [AKS] Fix #23779: `az aks install-cli` support to determine the arch of binaries based on system information

src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_common.py, src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_flexible_server_identity_aad_admin_mgmt.yaml, src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands.py
`az mysql flexible-server identity remove`
When customer wants to remove all the user managed identities in a MySQL flexible server, RP will throw an error saying that we can't do that. Instead, when trying to remove all existing identities, we should send only `{"identity": {"type": "None"}}`.
- Assign two identities to an existing server with no identities: `az mysql flexible-server identity assign -g resourceGroup -s serverName --identity testIdentity1 testIdentity2`
- Remove the first identity: `az mysql flexible-server identity remove -g resourceGroup -s serverName --identity testIdentity1`
- Remove the second identity (this now fails but this PR fixes it): `az mysql flexible-server identity remove -g resourceGroup -s serverName …
=> [RDBMS] `az mysql flexible-server identity remove`: Allow removing all identities in a MySQL server

azure-pipelines.yml, scripts/release/rpm/mariner.dockerfile, scripts/release/rpm/pipeline.sh, scripts/release/rpm/pipeline_mariner.sh
Close https://github.com/Azure/azure-cli/issues/22605
Since CBL Mariner 2.0 is now GA, Mariner 1.0 will be fully deprecated roughly by the **end of October**.
We stop building RPM for Mariner 1.0 in 2.41.0 which is a breaking change window.
=> [Packaging] Drop Mariner 1.0 RPM package

src/azure-cli/azure/cli/command_modules/storage/_validators.py, src/azure-cli/azure/cli/command_modules/storage/_validators_azure_stack.py, src/azure-cli/azure/cli/command_modules/storage/operations/azcopy.py, src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_azcopy_scenarios.py
`az storage remove <blob>`
Add/fix support for removing a blob using a connection-string (e.g. from Azurite). See #19311
See reproduce instructions in #19311
[Storage] Fix #19311: `az storage remove`: Add support for connection-string
---
=> [Storage] Fix #19311: `az storage remove`: Add support for connection-string

src/azure-cli/azure/cli/command_modules/cosmosdb/custom.py
**Active customer bug**
When creating a Cosmos DB Gremlin graph, the parameter 'analytical-storage-ttl' currently isn't added to the HTTP payload if it is the only container-specific parameter. This PR fixes the issue.
=> {CosmosDB} Make sure analytical-storage-ttl is applied as only argument for Gremlin graphs

src/azure-cli-core/setup.py, src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt
Use the latest MSAL 1.20.0 which has GA broker/WAM support (https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/502).
=> {Core} Bump MSAL to 1.20.0

src/azure-cli-core/azure/cli/core/auth/identity.py
`az login`
MSAL 1.20.0b1 implicitly sets `enable_msa_passthrough` to `True` for Azure CLI's client ID `04b07795-8ddb-461a-bbee-02f9e1bf7b46` (along with Visual Studio's client ID `04f0c124-f2bc-4f59-8241-bf6df9866bbd`):
https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.20.0b1/msal/application.py#L1746-L1760
```py
enable_msa_passthrough = kwargs.pop(
"enable_msa_passthrough",  # Keep it as a hidden param, for now.
self.client_id in [
"04b07795-8ddb-461a-bbee-02f9e1bf7b46",  # Azure CLI
"04f0c124-f2bc-4f59-8241-bf6df9866bbd",  # Visual Studio
] and data.get("token_type") != "ssh-cert"  # Work around a known issue as of PyMsalRuntime 0.8
)
```
MSAL 1.20.0 removed this behavior and now requires manually setting …
=> {Core} Explicitly set `enable_msa_passthrough` to `True` to allow WAM+MSA login 

.azure-pipelines/templates/variables.yml, azure-pipelines-full-tests.yml, azure-pipelines.yml, build_scripts/windows/scripts/build.cmd, scripts/bump_version/bump_version.yml, scripts/ci/automation_full_test.py, scripts/live_test/CLITest.yml, scripts/live_test/gen.py, scripts/live_test/gen.yml, scripts/live_test/monitor.yml, scripts/live_test/template.yml
Migrate azure cli pipelines to https://dev.azure.com/azclitools
[Azure.azure-cli](https://dev.azure.com/azclitools/public/_build?definitionId=32)
[Azure.azure-cli Full Test](https://dev.azure.com/azclitools/public/_build?definitionId=62)
[Aladdin Document Parser](https://dev.azure.com/azclitools/internal/_build?definitionId=209)
[Azure CLI ARM64](https://dev.azure.com/azclitools/internal/_build?definitionId=208)
[Azure CLI Build SAW MSI](https://dev.azure.com/azclitools/internal/_build?definitionId=225&_a=summary)
[Azure CLI installation benchmark](https://dev.azure.com/azclitools/internal/_build?definitionId=129&_a=summary)
[Azure CLI Live Test Monitor](https://dev.azure.com/azclitools/internal/_build?definitionId=130&_a=summary)
[Azure CLI Live …
=> {CI} Migrate azure cli pipelines

src/azure-cli/azure/cli/command_modules/iot/custom.py, src/azure-cli/azure/cli/command_modules/iot/tests/latest/test_iot_commands.py
`az iot hub create`
This PR adds a more user-friendly error when the user does not add the `--enforce-data-residency` property for `iot hub create`  in the `qatarcentral` region.
In all other regions, the default value of `None` or `False` is accepted.
For creates in `qatarcentral`, we will fail the command at the client level if the user does not add this parameter to enable the setting.
- `az iot hub create --sku s1 --location qatarcentral -g rg --name test-hub` will fail with an error.
- `az iot hub create --sku s1 --location qatarcentral -g rg --name test-hub --edr False` will fail with an error.
- `az iot hub create --sku s1 --location qatarcentral -g rg --name test-hub --edr [True]` will succeed.
[IoT] `az iot …
=> [IoT] Enforce default IoT Hub data residency setting for qatarcentral

src/azure-cli/azure/cli/command_modules/appservice/_help.py
az functionapp config appsettings set
I noticed that both
```
az functionapp config appsettings set
```
and
```
az webapp config appsettings set
```
support syntax where you can pass in a json file containing appsettings with `@file.json`.
However, previously only webapps had this syntax documented. This PR is to add the syntax documentation for the functionapps command.
```
az functionapp config appsettings set -g MyResourceGroup -n MyUniqueApp --settings mySetting=value @moreSettings.json
```
---
=> {App Service} Add to docs: function app appsettings command supports json file input

src/azure-cli/azure/cli/command_modules/cosmosdb/custom.py
fixes Azure/azure-cli#24156
It's possible to input resource id without leading '/' in URI, and this cause Cosmos DB Analytical Store to be unable to identify the mentioned resources and by-pass on network acl checking. Without the leading '/' in resource URI, CLI execution won't report any errors or indicate it's actually an invalid format. Cosmos DB can still store the invalid URI at last, but no help to allow querying from Synapse.
To Reproduce
az cosmosdb update --name MyCosmosDBDatabaseAccount--resource-group MyResourceGroup--network-acl-bypass AzureServices --network-acl-bypass-resource-ids "subscriptions/subId/resourceGroups/rgName/providers/Microsoft.Synapse/workspaces/wsName"
This PR validates the input values of --network-acl-bypass-resource-ids, to ensure customer configuring …
=> {AzureCosmosDB} fixes Azure/azure-cli#24156

src/azure-cli/azure/cli/command_modules/backup/_validators.py, src/azure-cli/azure/cli/command_modules/backup/custom.py
- Adds use_secondary_region to czr validation call
- Allows CZR for all scenarios in ZRS.
- Disallows CZR for zone-pinned primary region CRR restore.
`az backup restore restore-disks`
Cross Zonal Restore is now allowed on all ZRS vaults regardless of zone-pinning, and is disallowed for all primary region CRR restores (regardless of zone pinning). Update on CLI end to reflect the same.
- Cross zonal restore should work for
- Non-zone pinned and zone-pinned VMs in a ZRS vault
- Zone-pinned VMs in a Cross-region restore, on restoring to the secondary region (whether zones are supported in the secondary region or not - in the case of not, the zone defaults to NoZone)
- Cross zonal restore will not work in any other scenario.
The general …
=> [Backup] `az backup restore restore-disks`: Update Cross Zonal Restore behaviour for ZRS vaults and primary region CRR scenarios

src/azure-cli-core/azure/cli/core/intercept_survey.py, src/azure-cli-core/azure/cli/core/telemetry.py
We have implemented intercept survey in https://github.com/Azure/azure-cli/pull/23460. Now PM wants to log how many times the intercept message has been shown to customers in telemetry.
---
=> {Core} Log showing survey message info in telemetry

src/azure-cli/azure/cli/command_modules/vm/_help.py, src/azure-cli/azure/cli/command_modules/vm/_params.py
`az vm run-command create`
`az vm run-command update`
User used `--output-blob-uri` parameter to upload the output of executing a script on a VM to a Blob Storage, this solution worked properly for the past 4 months but something happened and for the past 2 weeks the upload to the --output-blob-uri is not working anymore.
Service team replied that user will need to use SAS URIs for --output-blob-uri to work. This is a recent change since Sep 20 or so. They've stopped auto-generating SAS URIs on behalf of users due to security concerns. Users need to use SAS URI with racw permissions (Read, Append, Create, Write)
Close #24095
[Compute] `az vm run-command create/update`: Change help messages and add examples for `--output-blob-uri` …
=> [Compute] `az vm run-command`: Change help messages and add examples for `--output-blob-uri` parameter

src/azure-cli/azure/cli/command_modules/storage/_validators.py, src/azure-cli/azure/cli/command_modules/storage/commands.py, src/azure-cli/azure/cli/command_modules/storage/operations/account.py
`az storage account show-connection-string`
`az storage account keys renew`
[Storage account REST API for regenerating keys](https://learn.microsoft.com/en-us/rest/api/storagerp/storage-accounts/regenerate-key?tabs=HTTP) is using `key1/key2` as `keyName`'s value
CLI command `az storage account keys renew` is using `primary/secondary` as `--key`'s value
To make things consistent, CLI would allow both `primary/secondary` and `key1/key2` for several sprints and then remove `primary/secondary` in next breaking change window.
`az storage account show-connection-string --key key1/key2/primary/secondary -n {storage_account_name} -g {resource_group_name}`
`az storage account keys renew --key key1/key2/primary/secondary -n …
=> [Storage] `az storage account show-connection-string/keys renew`: Update options for `--key` parameter

src/azure-cli/azure/cli/command_modules/storage/_params.py, src/azure-cli/azure/cli/command_modules/storage/operations/account.py
`az storage account create/update`
Federated client support for storage account was implemented in cli extension during public preview (see https://github.com/Azure/azure-cli-extensions/pull/4498 and https://github.com/Azure/azure-cli-extensions/pull/4881)
This PR moves the extension implementation to main repo for GA
---
=> [Storage] `az storage account create/update`: GA `--key-vault-federated-client-id`

src/azure-cli/azure/cli/command_modules/acs/_help.py
The example will update an existing cluster, not create a cluster (a faulty copy/paste I guess)
`az aks update --help` and search for : `az aks update -g MyResourceGroup -n MyManagedCluster --load-balancer-outbound-ips <ip-resource-id-1,ip-resource-id-2>`
Documentation is wrong (updating instead of creating)
`az aks update --help` shouldn't have "Create a cluster"
---
=> [AKS] Update CLI documentation for `az aks update`

src/azure-cli/azure/cli/command_modules/role/_help.py, src/azure-cli/azure/cli/command_modules/role/_params.py, src/azure-cli/azure/cli/command_modules/role/custom.py, src/azure-cli/azure/cli/command_modules/role/tests/latest/test_role.py
Close #23770
`az role assignment create`
As reported in #23770, `az role assignment create` internally calls ARM RBAC API [Role Assignments - Create](https://learn.microsoft.com/en-us/rest/api/authorization/role-assignments/create?tabs=HTTP).
Even though Azure CLI generates a new GUID each time with Python's built-in [`uuid.uuid4()`](https://docs.python.org/3/library/uuid.html#uuid.uuid4) function:
https://github.com/Azure/azure-cli/blob/98f7865402569ec9a6ae05ccdd0d27d5ea20927c/src/azure-cli/azure/cli/command_modules/role/custom.py#L1563-L1564
RBAC API randomly fails with:
```
ERROR: A hash conflict was encountered for the role Assignment ID. Please use a new Guid.
```
This has been identified as a service issue and RBAC team is working on a fix. …
=> [Role] `az role assignment create`: Support bring-your-own role assignment name

scripts/release/debian/test_deb_package.py, scripts/release/homebrew/test_homebrew_package.py, scripts/release/rpm/test_rpm_package.py
The latest pytest-xdist 3.0.2 (2022-10-25) has [removed](https://pytest-xdist.readthedocs.io/en/latest/changelog.html#removals) `--boxed` argument.
But we still need this functionality, install [pytest-forked](https://pypi.org/project/pytest-forked) separately and use `--forked` instead.
Error log:
```
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --boxed
inifile: None
rootdir: /mnt/vss/_work/1/s/src/azure-cli-core
```
=> {CI} pytest: `--boxed` argument is deprecated, use `--forked` instead

src/azure-cli/azure/cli/command_modules/acr/task.py
This PR changes the logic for task update. It resolves the following issues:
1. The update process missed the `EncodedTaskStepUpdateParameters` to update the values for `EncodedTask`. Issue [#497](https://github.com/Azure/acr/issues/497).
2. If our update cmd has a file arg, then CLI makes the assumption that the step is a FileTaskStep or DuckerBuildTaskStep regardless the existing or intended context [here](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acr/task.py#L414). If we want to update the file for an `EncodedTask`, we will get an error in [#313](https://github.com/Azure/acr/issues/313). The reason is the following: 
In `TasksController`, we will first update the `exisitingTaskRecord` with all of the updated parameters …
=> [ACR] `acr task update`: Fix logic issue for updating encoded task

src/azure-cli/azure/cli/command_modules/hdinsight/_params.py
Remove the allowed TLS version 1.0 and 1.1 in --minimal-tls-version help message
only affect the output of  `az hdinsight create -h`
Azure ARM has enforced TLS 1.2, but in az hdinsight create help message, we still have the allowed version 1.0 and 1.1, we need to remove it from help message. There is not customer impact.
[az hdinsight] BREAKING CHANGE: `az hdinsight create`: Remove the enum value 1.0 and 1.1 from the --minimal-tls-version, HDInsight doesn't support TLS version which is less than 1.2 now.
---
=> {HDInsight}Remove the allowed TLS version 1.0 and 1.1 in --minimal-tls-version help message

scripts/release/debian/test_deb_in_docker.sh, scripts/release/homebrew/test_homebrew_package.sh, scripts/release/rpm/test_rpm_in_docker.sh
The CI pipeline error is as follows:
We run these test scripts in docker.
- scripts/releases/debian/test_deb_package.py
- scripts/release/homebrew/test_homebrew_package.py
- scripts/releases/rpm/test_rpm_package.py
But I only have the latest pytest-forked installed in azdev(Azure/azure-cli-dev-tools#347), which only works when using the `azdev test` command.
We also need to install the latest pytest-forked in docker as well.
=> {CI} Install pytest-forked for docker image

azure-pipelines-full-tests.yml, azure-pipelines.yml, scripts/live_test/CLITest.yml, scripts/live_test/gen.yml, scripts/live_test/monitor.yml, scripts/live_test/template.yml, scripts/regression_test/regression_test.yml
Azure CLI Live Test pipeline will report an error:
```
/scripts/live_test/CLITest.yml: Could not find /scripts/live_test/.azure-pipelines/templates/variables.yml in repository self hosted on https://github.com/ using commit 8444d8686d50a1c1378273efbd05101e02d2c36d. GitHub reported the error, "Not Found"
```
Because the template path uses **relative path by default**, so except for the pipeline script in the root directory, other pipeline scripts cannot find the variable template.
This PR will use absolute path for variable template in all pipeline scripts
=> {CI} Fix template not found error: Use absolute path for variable template

src/azure-cli/azure/cli/command_modules/network/_params.py, src/azure-cli/azure/cli/command_modules/network/custom.py
```sh
az network bastion rdp --name {} --resource-group {} --target-resource-id {}
```
When connecting to bastion via RDP using Native Client, the session defaults to using all available monitors. But this may not always be the prefered by customers as mentioned in #23866.
Currently, customers have to disconnect from the session, either manually edit the RDP file or edit it using the Remote Desktop Connection UI, and then reconnect.
This PR adds a flag, `--configure`, which opens the Remote Desktop Connection UI instead of connecting directly, allowing customers to customize the session as required.
resolves #23866 
```sh
az network bastion rdp --name {} --resource-group {} --target-resource-id {} --configure
```
--- …
=> [Network] `az network bastion rdp`: Allow rdp session customization

README.md, doc/authoring_command_modules/README.md
Add code generation in developer setup
---
=> {docs} Add code generation link in developer setup

azure-pipelines.yml
macOS starts to use 3.11, but Azure-cli is not compatible with 3.11. Pin python version to 3.10 in both macOS and Linux.
```
Found tool in cache: Python 3.11.0 x64
Prepending PATH environment variable with directory: /Users/runner/hostedtoolcache/Python/3.11.0/x64
```
Related failed test: https://dev.azure.com/azclitools/public/_build/results?buildId=12468&view=logs&jobId=537f1e04-c6d5-53b2-3a1f-f7387cc6e02d&j=537f1e04-c6d5-53b2-3a1f-f7387cc6e02d&t=cae9a690-b596-5b1d-0d0e-9efe890cb6db
=> {CI} Pin Python version to 3.10 in Test

src/azure-cli/azure/cli/command_modules/iot/tests/latest/test_iot_dps_commands.py
In `test_dps_certificate_lifecycle` and `test_certificate_lifecycle`, they use same filenames:
```py
VERIFICATION_FILE = "verify.cer"
CERT_FILE = "testcert.cer"
KEY_FILE = "testkey.pvk"
CHAIN_FILE = "testcert-chain.pem"
```
These files will be removed after test. When executed in parallel, the `FileNotFoundError` error sometimes occurs.
Failed test: https://dev.azure.com/azclitools/public/_build/results?buildId=12783&view=logs&j=00feeef1-2e9b-5ce6-e2c5-a2c5a43245ee&t=317d23de-79ee-5aa1-a23a-e6710a3e515f
--- …
=> {IoT} Fix certificate filename conflict in test

src/azure-cli-core/azure/cli/core/extension/operations.py
`az extension add`
Currently, `--upgrade` is ignored when install extension from source. It raises `the extension already exists` rather than upgrade the extension.
I change the logic of `add_extension` to make sure `update_extension` is executed regardless of using `name` or `source`.
Fix https://github.com/Azure/azure-cli-extensions/issues/5491
` az extension add --name azurestackhci --version "0.2.3"  --upgrade`
` az extension add --source "https://hybridaksstorage.z13.web.core.windows.net/SelfServiceVM/CLI/azurestackhci-0.2.5-py3-none-any.whl" --verbose --yes --upgrade`
`0.2.5` should be installed now.
[Component Name 2] …
=> {Extension} `az extension add`: Enable `--upgrade` when install extension from `--source`

src/azure-cli/azure/cli/command_modules/backup/_params.py
Updated documentation that clarifies to the user that under the `--workload-type` flag, `MSSQL` and `SQLDataBase` refer to SQL in Azure VMs, and `SAPHANA` and `SAPHanaDatabase` refer to SAP HANA in Azure VM.
N/A. Existing tests/commands behave the same as the only substantial changes are to documentation code.
Add documentation to specify workload-type mapping to product names
---
=> {Backup} `az backup container register`: Add documentation to clarify workload type

.github/fabricbot.json
Add [automated workflows](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/490/Resolving-Issues) to align with the .NET SDK repo：
1. When work on an issue is believed to be complete, the Azure SDK team member responsible for communicating that status may apply the issue-addressed label.
2. When the bot that monitors the repository detects the issue-addressed label, it will respond with the message:
“Hi @issue-author. Thank you for opening this issue and giving us the opportunity to assist. We believe that this has been resolved. If you believe that further discussion is needed, please add a comment with the text “/unresolve” to remove the "issue-addressed” label and continue the conversation.”
3. For issues where the issue-addressed label was applied:
a. If no action is …
=> {CI} Add resolve issues logic

src/azure-cli-core/azure/cli/core/aaz/_arg.py, src/azure-cli-core/azure/cli/core/tests/test_aaz_arg.py
=> [Core] `aaz`: Fix `has_value` function for list, dict and object arg types

src/azure-cli/azure/cli/command_modules/keyvault/_validators.py
`az keyvault key create`
Close #24488 
Previously, customer can create key using `az keyvault key create` together with `--default-cvm-policy`. CLI will use hard coded cvm policy for creating key for customer.
This PR shift left the policy location to github link provided by service, the hard coded policy is just a fallback for air-gapped cloud.
`az keyvault key create --kty EC-HSM -n test_cvm_policy_pointer --exportable --default-cvm-policy --hsm-name ystesthsm --debug`
---
=> {Keyvault} `az keyvault key create`: Fetch default cvm policy from service, use local policy as fallback

scripts/release/debian/test_deb_in_docker.sh
I am not sure why `libssl1.1` is needed. But it is already installed as dependency when install `git` in previous step.
We can safely remove this step to pass the `DS440000 Generic: Do not hardcode SSL/TLS versions within an application` check.
>This package is part of the OpenSSL project's implementation of the SSL
and TLS cryptographic protocols for secure communication over the
Internet.
It provides the libssl and libcrypto shared libraries.
```
root@2f0a89968088:/# apt install git
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
ca-certificates git-man krb5-locales less libasn1-8-heimdal libbrotli1 libbsd0 libcbor0.6 libcurl3-gnutls libedit2 liberror-perl
libexpat1 libfido2-1 …
```
=> {Packaging} Not install libssl1.1 explicitly in test

src/azure-cli/azure/cli/command_modules/network/_params.py, src/azure-cli/azure/cli/command_modules/network/custom.py, src/azure-cli/azure/cli/command_modules/network/tunnel.py
=> {Network} `az network bastion`: Revert changes to accommodate MFA auth

doc/authoring_command_modules/README.md
closed https://github.com/Azure/azure-cli/issues/24749
Developer Documentation
Removal of outdated argument from developer documentation.
none
---
=> {Misc.} Fix #24749: Remove outdated argument from dev documentation

src/azure-cli/azure/cli/command_modules/storage/_help.py, src/azure-cli/azure/cli/command_modules/storage/_params.py, src/azure-cli/azure/cli/command_modules/storage/commands.py, src/azure-cli/azure/cli/command_modules/storage/operations/account.py, src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_encryption_scope_list.yaml, src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py, src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_encryption_scope_scenarios.py
`az storage account encryption-scope list`
`az storage account failover`
New features for API version 2022-09-01
- Support listing encryption scopes with specific filter/state/pagesize
- Support failover type
[Storage] `az storage account encryption-scope list`: Add `--filter`, `--include`, `--maxpagesize` to support advanced list
[Storage] `az storage account failover`: Add `--failover-type` to support planned failover
---
=> [Storage] New features for listing encryption scope and failover

src/azure-cli/azure/cli/command_modules/acs/_help.py, src/azure-cli/azure/cli/command_modules/acs/_params.py
[AKS] `az aks nodepool`: Unify the option names used to specify the nodepool name and cluster name. For nodepool name, option names are `--nodepool-name`, `--name` and `-n`. For cluster name, option name is `--cluster-name`
---
=> {AKS} `az aks nodepool`: Update nodepool command option names

azure-pipelines.yml
Some jobs reached the default timeout 60min and failed. Increase default timeout to 120 minutes.
```
The job running on agent pool-ubuntu-2004 20 ran longer than the maximum time of 60 minutes. For more information, see https://go.microsoft.com/fwlink/?linkid=2077134 
```
Ref: [Set timeout in Azure Pipeline](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#timeouts)
=> {CI} Increase TestDebPackages job timeout to 120 minutes

src/azure-cli/azure/cli/command_modules/cosmosdb/_params.py
The documentation was lacking information, how to specify a user-assigned identity as the default identity of the CosmosDB account.
az cosmosdb create
Documentation of parameter '--default-identity' improved.
az cosmosdb create ... --default-identity="UserAssigedIdentity=/subscription/<...>/my-user-assigned-identity"
---
=> {CosmosDB} `az cosmosdb create`: Added user-assigned identity spec format to option '--default-identity'

src/azure-cli/azure/cli/command_modules/appservice/custom.py, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands_thru_mock.py
az webapp config snapshot restore
https://learn.microsoft.com/en-us/cli/azure/webapp/config/snapshot?view=azure-cli-latest#az-webapp-config-snapshot-restore
The restore snapshot command is failing to perform operation if the slot parameter is sent.
Sample command : az webapp config snapshot restore --resource-group test_group --name dbapptesttt --slot build --source-resource-group test_group  --source-name dbapptesttt  --source-slot production --time 2022-11-22T09:09:08.6157038  --restore-content-only
Without this fix, the command fails with below error
_The command failed with an unexpected error. Here is the traceback:
('Unable to build a model: ("Unable to deserialize to object: type, AttributeError: \'str\' object has no attribute …
=> [App Service] `az webapp config snapshot restore`: Fix the AttributeError `str object has no attribute get`

src/azure-cli/azure/cli/command_modules/serviceconnector/commands.py
- `az webapp connection create mysql`
- `az spring connection create mysql`
- `az containerapp connection create mysql`
Deprecate the above commands as Mysql Single Server is on the retirement path. https://learn.microsoft.com/en-us/azure/mysql/single-server/single-server-overview
---
=> [Service Connector] `az webapp/spring/containerapp connection create mysql`: Deprecate mysql single server connection command

src/azure-cli/azure/cli/command_modules/appservice/_params.py
`az functionapp keys set/delete`
Fixes #24506. Updates the accepted parameter values for `--key-type` to conform with the API. 
---
=> [App Service] Fix #24506: `az functionapp keys set/delete`: Update the wrong accepted parameter value `systemKey` to `systemKeys` for `--key-type`

src/azure-cli/azure/cli/command_modules/resource/_params.py
`az group lock list`
Issue -close: #24452
---
=> [ARM] `az group lock list`: Mark the `--resource-group` as required in help message

Dockerfile
[Apline 3.17](https://alpinelinux.org/posts/Alpine-3.17.0-released.html) use openssl3 as default openssl.
Current cryptography or pyOpenSSL is not compatible and fails when run `az self-test`
```
ERROR: Error relocating /usr/local/lib/python3.10/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: FIPS_mode_set: symbol not found
File "/usr/local/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
raise ex
File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially …
```
=> {Packaging} Use openssl 1.1 in docker

az.completion
The completion function is loaded into the global shell function namespace, so having a command-related prefix in the name is best practice.
Bash command completion should work identically with this change.
[Misc.] Change name of Bash completion function
---
=> {Misc.} Change name of Bash completion function

src/azure-cli/azure/cli/command_modules/resource/_bicep.py
`az bicep install`
Installing the bicep command on systems using glibc that also have MUSL
installed generate errors at runtime (See https://github.com/Azure/bicep/issues/5040)
This expands the MUSL detection logic to exclude systems with glibc,
which is the primary non-musl libc.
1. Run `az bicep install` on systems with glibc and musl, note that the standard linux bicep gets installed.
2. Run `az bicep install` on systems with glibc and without musl, note that the standard linux bicep gets installed.
3. Run `az bicep install` on systems with musl and without glibc, note that the musl linux bicep gets installed.
[ARM] `az bicep install`: Address issue installing bicep on non-musl default systems with musl
---
=> [ARM] `az bicep install`: Address issue installing bicep on non-musl default systems with musl

src/azure-cli-core/setup.py, src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt
Adopt https://github.com/microsoft/knack/pull/268 to provide a temporary workaround for https://github.com/Azure/azure-cli/pull/24763. This unblocks containerservice (AKS) extension's serialization of [ManagedClusterSecurityProfileCustomCATrustCertificates](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-09-02-preview/managedClusters.json#L6605) object.
=> {Packaging} Bump knack to 0.10.1 to support `bytearray` serialization

src/azure-cli/azure/cli/command_modules/resource/_params.py
Fix to support ARM64 arch for Bicep installation
fixes Azure/azure-cli#24810 
On OSX ARM64 architecture VMs the Bicep install fails because the `bicep_target_platform_type` enum currently has only x64 arch. So this ends up installing x64 version. It eventually fails with the below error:
```
$ az bicep install --target-platform osx-arm64
az bicep install: 'osx-arm64' is not a valid value for '--target-platform'. Allowed values: win-x64, linux-musl-x64, linux-x64, osx-x64.
```
```
> az bicep version
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```
Here is the download URL for the ARM64:
https://github.com/Azure/bicep/releases/latest/download/bicep-linux-arm64
https://github.com/Azure/bicep/releases/download/v0.13.1/bicep-osx-arm64 …
=> [ARM] Fix #24810: Support ARM64 architecture for Bicep installation

Dockerfile
An out-of-courtesy fix for https://github.com/Azure/azure-cli/issues/24836
`openssl` command was replaced by `openssl1.1` in the docker image by https://github.com/Azure/azure-cli/pull/24768.
Some users using Azure CLI docker image directly rely on `openssl` command without explicitly specifying `openssl` dependency. This is not a good practice as a dependency(Azure CLI)'s dependency (`openssl`) is an internal implementation, so the user shouldn't assume the dependency's dependency is always available. 
Even though we don't guarantee the availability of tools or packages in the docker image, we add `openssl` out of courtesy, so that those users can be unblocked quickly without changing their code.
**Additional information**
This hotfix will only be rolled out to the docker …
=> {Packaging} Hotfix: Install OpenSSL 3.0 in the docker image

scripts/release/rpm/mariner.dockerfile
CI job **Build Rpm Package Mariner 2.0** fails:
https://dev.azure.com/azclitools/public/_build/results?buildId=20025&view=logs&j=05d32766-0180-56c9-d65b-603741da4b97&t=199e5dcb-1f4f-59eb-61f9-d8fc896d9ae2
```
Wrote: /usr/src/mariner/RPMS/x86_64/azure-cli-2.43.0-1.cm2.x86_64.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.UNvYKb
+ umask 022
+ cd /usr/src/mariner/BUILD
+ /bin/rm -rf /usr/src/mariner/BUILDROOT/azure-cli-2.43.0-1.cm2.x86_64
+ RPM_EC=0
++ jobs -p
+ exit 0
Executing(rmbuild): /bin/sh -e /var/tmp/rpm-tmp.ShFyrU
+ umask 022
+ cd /usr/src/mariner/BUILD
+ RPM_EC=0
++ jobs -p
+ exit 0
cp: cannot stat '/usr/src/mariner/RPMS/x86_64/azure-cli-2.43.0-1.x86_64.rpm': No such file or directory
```
Previously the package name looks like `azure-cli-2.43.0-1.x86_64.rpm`, …
=> {Packaging} Handle `cm2` in Mariner 2.0 RPM name

src/azure-cli/azure/cli/command_modules/rdbms/_helptext_mysql.py, src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py
`az mysql/postgres flexible-server create/update`
For CMK related commands for MySQL and PostgreSQL flexible server, we add explicitly in the instructions how to get the necessary key identifiers and principalId's for user managed identities.
---
=> {RDBMS} Improve help docs for MySQL and PostgreSQL flexible server CMK

src/azure-cli/azure/cli/command_modules/appservice/_validators.py
az appservice plan create
Close: #23488 #24112
Zone redundant ASP plan creation on an ASE currently does not work on the CLI. It fails with error "Zone redundancy cannot be enabled for I1V2 SKU". This PR adds the ISOLATEDV2 tier to the validation step.
az appservice plan create -g resource-group-name -n plan-name --location westeurope --sku I1V2  --is-linux --app-service-environment asev3-name --zone-redundant
---
=> [App Service] Fix #23488: `az appservice plan create`: Fix zone redundant ASP creation fails for ASEv3

src/azure-cli/azure/cli/command_modules/appservice/utils.py
PR to add the Support for New Isolated v2 (I4v2, I5v2, I6v2) skus
fixes Azure/azure-cli#24858 Support for New Isolated v2 (I4v2, I5v2, I6v2) skus
The below docs talks about the new isolated plan skus:
https://learn.microsoft.com/en-us/cli/azure/appservice?view=azure-cli-latest#az-appservice-list-locations
However, running the command with those skus fails:
>az appservice list-locations --sku I5v2
```
ERROR: az_command_data_logger: az appservice list-locations: 'I5V2' is not a valid value for '--sku'. Allowed values: F1, FREE, D1, SHARED, B1, B2, B3, S1, S2, S3, P1V2, P2V2, P3V2, P1V3, P2V3, P3V3, I1, I2, I3, I1v2, I2v2, I3v2, WS1, WS2, WS3.
```
[Component Name 1] BREAKING CHANGE: `az command a`: Make some …
=> [App Service] Fix #24858: Support for new isolated v2 (I4v2, I5v2, I6v2) SKUs

src/azure-cli-core/azure/cli/core/parser.py
Fix https://github.com/Azure/azure-cli/issues/23015
A rework of #24109
Python 3.11 updated `argparse`'s behavior:
https://docs.python.org/3.11/whatsnew/changelog.html#id50
> bpo-39716: Raise an ArgumentError when the same subparser name is added twice to an `argparse.ArgumentParser`. This is consistent with the (default) behavior when the same option string is added twice to an ArgumentParser.
The PR for this change is https://github.com/python/cpython/pull/18605
Per Git blame,
- `subparser.choices[command_verb] = command_verb` was renamed from `subparser.choices[command_name] = command_name` by https://github.com/Azure/azure-cli/commit/517872af1912ba7a2cd251999e7675546fbd495f
- `subparser.choices[command_name] = command_name` was introduced as early as …
=> {Core} Make parser compatible with Python 3.11's `argparse`

src/azure-cli/azure/cli/command_modules/appservice/_help.py, src/azure-cli/azure/cli/command_modules/appservice/_params.py, src/azure-cli/azure/cli/command_modules/appservice/appservice_environment.py, src/azure-cli/azure/cli/command_modules/appservice/commands.py, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_app_service_environment_commands_thru_mock.py
az appservice ase upgrade
az appservice ase send-test-notification
New commands for ASE to support ASE upgrades and sending test notifications
More information about ase upgrade - https://learn.microsoft.com/en-us/azure/app-service/environment/how-to-upgrade-preference?pivots=experience-azcli#manual-upgrade-preference
More information about sending test notifications -  https://learn.microsoft.com/en-us/azure/app-service/environment/how-to-upgrade-preference?pivots=experience-azcli#send-test-notifications
This command will start upgrade process
az appservice ase upgrade -n ase-name -g resource-group-name
This command will send test notification 
az appservice ase send-test-notification -n ase-name -g resource-group-name
**History …
=> [App Service] `az appservice ase upgrade/send-test-notification`: Add new commands for ASE to support ASE upgrade and sending test notifications

src/azure-cli/azure/cli/command_modules/servicebus/_params.py, src/azure-cli/azure/cli/command_modules/servicebus/custom.py
az servicebus queue update
Adding breaking change alert messages wherever required
{ServiceBus}  `az servicebus queue update`: Add breaking change alerts
---
=> {ServiceBus} `az servicebus queue update`: Add breaking change alert messages

src/azure-cli/azure/cli/command_modules/sql/_params.py
fixes Azure/azure-cli#24980
Fix the Typo in description of `--dest-resource-group` parameter
Typo "resouce"→"resource"
---
=> {AzureSQL} fixes Azure/azure-cli#24980 Fix the Typo in description of --dest-resource-group parameter

src/azure-cli/azure/cli/command_modules/cosmosdb/custom.py, src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_deleted_account_restore.yaml, src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_restore_command.yaml
When performing a PITR restore, if the user was given a specific permission to restore the account, then the permission check might fail due to the "Location" returned by the PITR restorable database API is not normalized.  This PR fixes this by normalizing the location name.
az cosmosdb restore
---
=> {CosmosDB} Normalize location in the restorable database API response

src/azure-cli/azure/cli/command_modules/acs/custom.py
Automatically add the installation directories of the binaries downloaded through the `az aks install-cli` command to the search path (user environment variable `PATH`) on the windows platform.
- In this example, the latest versions of kubectl and kubelogin are downloaded to the corresponding default paths, and these paths are automatically added to the _user_ environment variable `PATH`, so that users can directly use these tools in a new command line session.
- The installation directories are appended to the user environment variable, avoiding the need for administrator privileges to write system environment variables.
- Although the variable `PATH` is updated in append mode, there is still a certain risk that `PATH` will be …
=> [AKS] `az aks install-cli`: Automatically add the installation directories to system path on windows

src/azure-cli/requirements.py3.windows.txt
Bump PyWin32 (to >= 303) so that Azure CLI no longer loads `pywintypes310.dll` or `pythoncom310.dll` from the current working directory (CWD), but always from `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\pywin32_system32\`.
According to https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#standard-search-order-for-desktop-applications, even if `SafeDllSearchMode` is enabled and it places the user's current directory later in the search order, the current directory is still searched by [`LoadLibrary`](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryw) and [`LoadLibraryEx`](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryexw). `LoadLibraryEx` …
=> {Packaging} Bump PyWin32 to 305

src/azure-cli/azure/cli/command_modules/appservice/custom.py, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_vnetE2E.yaml, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_vnet_EP_sku_E2E.yaml, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_vnet_basic_sku_E2E.yaml, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_vnet_duplicate_name.yaml, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_vnet_integration_consumption_plan.yaml, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py
az functionapp vnet-integration add
Currently, we allow virtual network integration in a function app running in a consumption plan. The changes in this PR run a validation to prevent that. This is to resolve issue #19469
1. Create a function app with a consumption plan ( `az functionapp create -g <resource-group-name> -n <function-app-name> -s <storage-account-name> --consumption-plan-location "<location>" --functions-version 4` 
2. When attempting to add virtual network, you should see the error message "Virtual network integration is not allowed for consumption plans" (`az functionapp vnet-integration add -g <resource-group-name> -n <function-app-name> --subnet <subnet-name> --vnet <vnet-name>`)
---
This checklist …
=> [App Service] Fix#19469: `az functionapp vnet-integration add`: Add consumption plan validation

src/azure-cli/requirements.py3.windows.txt
`psycopg2` provided wheel for Windows Python3.11 in 2.9.5.
Related issue: #24494
=> {Packaging} Update psycopg2 to support Python 3.11

src/azure-cli/azure/cli/command_modules/role/_params.py
`az role assignment create`
https://github.com/Azure/azure-cli/pull/24324 introduced `--name` for `az role assignment create` but is unclear about its type. This may lead to incorrect usages (https://github.com/Azure/azure-cli/issues/24919), as user can use invalid role assignment name, resulting in malformed URL and causing confusing service error (https://github.com/Azure/azure-cli/issues/7441).
**Additional information**
That help message originally was
```
The name of the role assignment to create. It can be any valid GUID.
```
https://github.com/Azure/azure-rest-api-specs/pull/16639 updated it for `2020-04-01-preview` API to
https://github.com/Azure/azure-rest-api-specs/blob/cf848c9f570c1157bbad81e214f5bb2993e578bb/specification/authorization/resour …
=> {Role} `az role assignment create`: Refine help message for `--name`

src/azure-cli/azure/cli/command_modules/container/custom.py, src/azure-cli/azure/cli/command_modules/container/tests/latest/recordings/test_container_export_with_identity.yaml, src/azure-cli/azure/cli/command_modules/container/tests/latest/test_container_commands.py
```sh
az container export
```
When running the `az container export` command for a container that has/had managed identity setup on it, this would fail due to the identity object. This was due to a bug in our source code that failed converting the object to a dictionary before passing it to the `yaml` library for serialization. This fixes this.
resolves #24732
resolves #24731
Create a container app, assign managed identity (system and/or user) and run the following command for the same
```sh
az container export
```
---
=> [Container] `az container export`: Fix export when identity is set

.github/fabricbot.json
We have to add required condition `isAction = opened` to all tasks.
Otherwise, even if we remove the label, the bot will add it repeatedly.
`isAction = opened` indicates that it is only executed once when an issue is created, which can avoid repeated execution.
=> {CI} Fix #24973: Add missing required condition `isAction = opened` to appservice routing rules.

src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py
`az aks nodepool add -g {} --cluster-name {} --os-sku Windows2019 -n {} (w/o --os-type Windows)`
Add error message for nodepool add w/o os type for Windows SKU's
`az aks nodepool add -g {} --cluster-name {} --os-sku Windows2019 -n {} (w/o --os-type Windows)`
Fixes GitHub Issue [24966](https://github.com/Azure/azure-cli/issues/24966)
---
=> {AKS} Add error message for nodepool add w/o os type for Windows SKU's

src/azure-cli/azure/cli/command_modules/acr/_constants.py, src/azure-cli/azure/cli/command_modules/acr/_help.py, src/azure-cli/azure/cli/command_modules/acr/manifest.py, src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_commands_mock.py
az acr manifest list-referrers -r myregistry -n myrepo:mytag
- ACR has started to support [OCI Specifications 1.1](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/azure-container-registry-the-first-cloud-registry-to-support-the/ba-p/3708998). [OCI reference types](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#listing-referrers) will supersede [ORAS artifact reference types](https://github.com/oras-project/artifacts-spec/blob/main/manifest-referrers-api.md). The change switches `acr manifest list-referrers` from `ORAS artifact reference types` to `OCI reference types`
- Use [ORAS CLI](https://oras.land/cli/) to attach an OCI artifact to an image, see the …
=> [ACR] `acr manifest list-referrers`: Support OCI reference types and remove ORAS artifact reference types

azure-cli2017.pyproj, src/azure-cli/azure/cli/command_modules/dms/_help.py, src/azure-cli/azure/cli/command_modules/dms/custom.py, src/azure-cli/azure/cli/command_modules/dms/scenario_inputs.py, src/azure-cli/azure/cli/command_modules/dms/tests/latest/recordings/test_task_commands.yaml, src/azure-cli/azure/cli/command_modules/dms/tests/latest/test_service_scenarios.py, src/azure-cli/azure/cli/command_modules/dms/validators.py
az dms project task create
Adding ability to launch Online and ReplicateChanges migrations for MySQL which are currently in preview
az dms project task create -g {resource group} --service-name {service name} --project-name {project name} --source-connection-json {Path Source connection json file} --target-connection-json {Path Target connection json file} --database-options-json {Path to Database options json file} -n {Task name}
[dms] `az dms project task create`: Update DMS MySQL API to support new migration types
---
=> [DMS] `az dms project task create`: Update DMS MySQL API to support new migration types

src/azure-cli-core/azure/cli/core/azclierror.py, src/azure-cli-core/azure/cli/core/util.py
This PR unifies the traceback printing logic into `azure.cli.core.azclierror.AzCLIError.print_error` so that traceback will be printed to debug log for all all subclasses of `AzCLIError`, including `azure.cli.core.azclierror.ResourceNotFoundError` and `azure.cli.core.azclierror.ValidationError`.
This greatly simplifies the troubleshooting for validation failures, such as https://github.com/Azure/azure-cli/issues/24896, as now the debug log reveals which validator fails.
Even though we already print traceback in `azure.cli.core.util.handle_exception`:
https://github.com/Azure/azure-cli/blob/325dfa64d8b77bfddb3b087162ad98acee5037ab/src/azure-cli-core/azure/cli/core/util.py#L68-L70
`ResourceNotFoundError` and `ValidationError` are not handled here, so no traceback is printed.
Instead, …
=> {Core} Print traceback for all subclasses of `AzCLIError`

scripts/ci/automation_full_test.py, scripts/regression_test/extension_regression_test.yml, scripts/regression_test/regression_test.yml
Using `~` directly in ADO pipeline will cause failure, this PR aims to fix the failure. See my comments for detailed explanation
---
=> {CI} Fix home path `~` in regression test pipeline

src/azure-cli/azure/cli/command_modules/network/_format.py, src/azure-cli/azure/cli/command_modules/network/commands.py, src/azure-cli/azure/cli/command_modules/network/custom.py, src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_usage_list.yaml
=> [Network] Fix #25130: `az network list-usages`: `-o table` cannot be used

src/azure-cli/azure/cli/command_modules/storage/_params.py, src/azure-cli/azure/cli/command_modules/storage/_validators.py
`--allow-blob-public-access` defaults to `null`. This used to be equivalent to `true` but will be changed to `false` in the future from server side.
This PR adds a warning in advance to let customers be aware.
---
=> [Storage] `az storage account create`: Ongoing breaking change warning for disallowing blob public access by default

src/azure-cli/azure/cli/command_modules/acs/_help.py
az aks nodepool update
I added a note to the `--node-taints` option in your docs. 
It is not immediately obvious how to delete node taints. [Kubernetes reference](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) tells you to add a hyphen at the end, which does not work on the Azure CLI. This behavior is also different from the `labels` argument.
Unneeded, this is a docs change.
---
=> {AKS} az aks nodepool: Add doc line on how to delete node taints

src/azure-cli/azure/cli/command_modules/network/custom.py
Fixes: https://github.com/Azure/azure-cli/issues/25124
az network vnet-gateway create
**Description** Fix the bug that create network gateway command can only take 1 public ip from arguments while 2 are required
---
=> [Network] Fix #25124: `az network vnet-gateway create`: Active-Active gateway fails with insufficient IP configurations

scripts/live_test/CLITest.yml, scripts/live_test/sendemail.py
Abandoning `Twilio SendGrid` for several reasons:
1. `Twilio SendGrid` is not a Microsoft product
2. The `Twilio SendGrid` we created before sends email and returns 202, but the actual sending is not successful, it may be blocked by `Twilio SendGrid`
3. Creating a new `Twilio SendGrid` needs to add a credit card, so it cannot be created successfully
After many attempts, I decided to use the azure service `Azure Communication Email` instead of `Twilio SendGrid`
TODO:
How can we stop Outlook from recognizing this type of mail as external?
=> {CI} Fix azure cli live test send email

src/azure-cli/azure/cli/command_modules/network/azure_stack/custom.py, src/azure-cli/azure/cli/command_modules/network/custom.py
`az network dns zone export`
Let's say there are two ALIAS records for the same record set name:
www 3600 AZURE ALIAS A    /subscriptions/...
www 3600 AZURE ALIAS AAAA /subscriptions/...
Before this change, export would only emit the last record for any record set name, in this case the AAAA record, because when it processed the second record it would incorrectly clear the array containing the first record.
With this change, the array is only initialized when the first record is processed.
I had this problem with my DNS Zone, so I made the change in my local `azure-cli` installation and verified the export is now correct.
I did not find any checked-in tests for `export_zone`.
--- …
=> [Network] `az network dns zone export`: Fix the export to emit all ALIAS records for a particular record set name

src/azure-cli/azure/cli/command_modules/netappfiles/custom.py
az netappfiles volume update 
Fix an issue where Volumes `DataProtectionProperties`  properties where getting updated (with default values)  in PATCH opertion even when not set on command line for update command.
az netappfiles volume update -g test_rg -a testAccount -p testPool -v test-volume1 --usage-threshold 1000
Just setting `usage-threshold`  should not update `DataProtection `properties
---
=> [NetAppFiles] Fix volume patch dataprotection props

scripts/ci/automation_full_test.py, scripts/regression_test/regression_test.yml
When implementing Extension Regression Test Pipeline, we push all changes to `azclibot` repo
But in CLI Regression Test Pipeline, we support customized repo & branch
Here's a fix to specify `azclibot` repo only for Extension Regression Test Pipeline
---
=> {CI} Fix regression test git push branch

src/azure-cli/azure/cli/command_modules/rdbms/_params.py, src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_mysql.py, src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_flexible_server_paid_iops_mgmt.yaml, src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands.py
We add a new parameter **auto-scale-io** for the server create/update command. This parameter is enum. 
- az mysql flexible-server create/update --auto-scale-io [Enabled/Disabled]
This PR uses latest Python SDK package which in turn uses the latest GA API version 2022-12-01. This PR will allow customers to use the new feature: Auto scale iops when creating and updating servers.
See examples in _helptext_mysql.py.
---
=> [RDBMS] `az mysql flexible-server create/update`: Add `--auto-scale-iops` to enable or disable autoscale of iops

src/azure-cli/azure/cli/command_modules/sql/commands.py
`az sql db threat-policy show`
`az sql db threat-policy show update`
Microsoft.Sql - Change expiration version for `az sql db threat-policy` cmds group to version 2.49.0 (instead of 2.45.0)
The following will replace this cmd group:
`az sql db advanced-threat-protection-setting show -g <resource_group> -s <sql_server_name> -n <db_name>`
Displays the current advancedThreatProtectionSettings state for the SQL Database (Enabled or Disabled)
`az sql db advanced-threat-protection-setting update -g <resource_group> -s <sql_server_name> -n <db_name> --state <Disabled/Enabled>`
Updates the current advancedThreatProtectionSettings state for the SQL Database (Enabled or Disabled)
`az sql db threat-policy show -g <resource_group> -s …
=> [SLQ] `az sql db threat-policy`: Change expiration version for cmd group to 2.49.0

src/azure-cli/azure/cli/command_modules/resource/_bicep.py, src/azure-cli/azure/cli/command_modules/resource/_help.py, src/azure-cli/azure/cli/command_modules/resource/custom.py, src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_bicep.py
`az bicep *`
The `az bicep` commands download Bicep CLI automatically if it does not exist on `$AZURE_CONFIG_DIR/bin`. This is causing an [GitHub API throttling issue](https://github.com/Azure/bicep/issues/3689) if users uses the Azure CLI ADO task, as each task run creates an empty azure config directory. The PR adds two configurations `bicep.use_binary_from_path` and `bicep.check_version` to allow users to reuse the pre-installed Bicep CLI on the CLI runners and to disable version checks for each `az bicep` command run.
Closes https://github.com/Azure/bicep/issues/9452.
Set `bicep.use_binary_from_path` and `bicep.check_version` and run any `az bicep` commands.
[ARM] `az bicep`: Add configuration …
=> [ARM] `az bicep`: Add configs to allow disabling version checks and using Bicep CLI from PATH

scripts/release/homebrew/docker/formula_template.txt
Fix #24788.
`az` start with `python -m` and [`-m`](https://docs.python.org/3.11/using/cmdline.html#cmdoption-m) adds the current directory to the start of `sys.path`.
In #24788, if the working dir has a `brotli` folder, `urllib3` will import it and lead to error.
https://github.com/urllib3/urllib3/blob/0612a53f48f72ab6e9ef58ccf1d6a25b847152fc/src/urllib3/response.py#L17-L23
To remove current dir from path, `-I` is needed.
> [-I](https://docs.python.org/3.11/using/cmdline.html#cmdoption-I) option can be used to run the script in isolated mode where [sys.path](https://docs.python.org/3.11/library/sys.html#sys.path) contains neither the current directory nor the user’s site-packages directory. All PYTHON* environment variables are ignored, too.     ----[Python …
=> [Packaging] Fix #24788: Add `-I` in entrypoint on MacOS

src/azure-cli/azure/cli/command_modules/vm/_params.py, src/azure-cli/azure/cli/command_modules/vm/custom.py, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_reimage.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_reimage_instance_id.yaml, src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
`az vmss reimage`
az vmss reimage should accept multiple instance ids
close https://github.com/Azure/azure-cli/issues/25060
---
=> [Compute] `az vmss reimage`: Change `--instance-id` to support multiple id

src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py, src/azure-cli/azure/cli/command_modules/rdbms/_params.py, src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_common.py
Added --offline and --online flags to az postgres flexible-server migration create
Changed `az postgres flexible-server migration update `--cutover` db1 db2 db3` to `az postgres flexible-server migration update` `--cutover`
Changed `az postgres flexible-server migration update `--cancel` db1 db2 db3` to `az postgres flexible-server migration update` `--cancel`
This PR is a breaking change for FMS based Migrations from Sterling to Meru Platforms in Postgres.
Fixed offline mode for migration creation. The supplied flag was never being passed to the JSON request.
Changed Cancel and cutover functionality to ONLY ALL databases involved in the migration.
**The PR does not break any functionality for the existing customers.**
Did manually …
=> [RDBMS] `az postgres flexible-server migration`: Change behavior of cancel/cutover and added Offline Flag for FMS based migrations

src/azure-cli-core/azure/cli/core/aaz/_arg_action.py, src/azure-cli-core/azure/cli/core/tests/test_aaz_arg.py
Closed https://github.com/Azure/aaz-dev-tools/issues/188
---
=> [Core] `aaz`: Support singular options of `AAZListArg` in shorthand syntax partial value expression

src/azure-cli/azure/cli/command_modules/resource/_formatters.py, src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_formatters.py
`az deployment what-if`
A customer reported an issue where the what-if command throws an exception when formatting nested array changes. The PR fixes the bug.
`az deployment what-if ...`
---
=> [ARM] `az deployment what-if`: Fix an issue where formatting nested array changes throws an exception

src/azure-cli-core/azure/cli/core/command_recommender.py, src/azure-cli-core/azure/cli/core/util.py
If the command is not complete, you will get recommendation.
For example, type `az account` you get
```                                                                                                                                                ─╯
the following arguments are required: _subcommand
Examples from AI knowledge base:
az account list
Get a list of subscriptions for the logged in account. (autogenerated)
az account show
Get the details of a subscription. (autogenerated)
az account set --subscription mysubscription
Set a subscription to be the current active subscription. (autogenerated)
https://docs.microsoft.com/en-US/cli/azure/account#az_account_list
Read more about the command in reference docs
```
In autocomplete mode, it's common that the command is not …
=> {Core} Disable aladdin recommendation in autocomplete mode

src/azure-cli/azure/cli/command_modules/appservice/_help.py, src/azure-cli/azure/cli/command_modules/appservice/_validators.py
=> [App Service] Fix #24285: `az webapp config access-restriction add`: Fix the bug that it does not support more than one Front Door ID in X-Azure-FDID

src/azure-cli/azure/cli/command_modules/appservice/_params.py, src/azure-cli/azure/cli/command_modules/appservice/custom.py, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_powershell_version.yaml, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py
```
az functionapp config set
```
PowerShell Function Apps have a configurable version configuration that can be set from the Azure Portal but isn't exposed in Azure CLI. This PR adds the option for the same.
resolves #23603
```
az functionapp config set --resource-group {} --name {} --powershell-version 7.2
```
---
=> [App Service] Fix #23603: `az functionapp config set`: Add new parameter to set PowerShell version

src/azure-cli/azure/cli/command_modules/acs/_help.py, src/azure-cli/azure/cli/command_modules/acs/_params.py
`az aks create --aad-client-app-id {} --aad-server-app-id {} --aad-server-app-secret {}`
`az aks update-credentials --reset-aad --aad-client-app-id {} --aad-server-app-id {} --aad-server-app-secret {}`
The [legacy way of integrate Azure Active Directory with AKS](https://learn.microsoft.com/en-us/azure/aks/azure-ad-integration-cli) is deprecated. This PR is to make the related properties deprecated in Azure CLI.
[AKS] `az aks create`: Deprecate parameters `--aad-client-app-id`, `--aad-server-app-id` and `--aad-server-app-secret`
[AKS] `az aks update-credentials`: Deprecate parameters `--reset-aad`, `--aad-client-app-id`, `--aad-server-app-id` and `--aad-server-app-secret`
--- …
=> [AKS] Mark AAD-legacy properties deprecated

.github/CODEOWNERS, src/azure-cli/azure/cli/command_modules/servicebus/_params.py, src/azure-cli/azure/cli/command_modules/servicebus/custom.py
CLI 2.45.0 release failed with
```
-  FAIL - HIGH severity: expired_parameter
Parameter: servicebus queue update, `enable_partitioning` - Deprecated parameter is expired and should be removed.
Parameter: servicebus queue update, `requires_duplicate_detection` - Deprecated parameter is expired and should be removed.
Parameter: servicebus queue update, `requires_session` - Deprecated parameter is expired and should be removed.
```
Since `2.45.0` doesn't allow breaking changes, so change the deprecation info to next breaking change window which would be `2.49.0` then
---
This …
=> {ServiceBus} Change expiration version to next breaking change window

src/azure-cli/azure/cli/command_modules/servicebus/commands.py, src/azure-cli/azure/cli/command_modules/servicebus/custom.py
fixes Azure/azure-cli#25161 fix for migration abort issue
Azure CLI command `az servicebus migration abort` fails with the below error:
```
File "/opt/az/lib/python3.10/site-packages/azure/mgmt/servicebus/v2022_01_01_preview/operations/_migration_configs_operations.py", line 766, in revert
request = build_revert_request(
File "/opt/az/lib/python3.10/site-packages/azure/mgmt/servicebus/v2022_01_01_preview/operations/_migration_configs_operations.py", line 251, in build_revert_request
"configName": _SERIALIZER.url("config_name", config_name, 'str'),
File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 652, in url
output = self.serialize_data(data, data_type, **kwargs)
File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 760, in serialize_data
raise …
```
=> {AzureServiceBus} fixes Azure/azure-cli#25161 fix for migration abort issue

src/azure-cli/azure/cli/command_modules/acr/_docker_utils.py
az acr manifest list myregistry.azurecr.io/myrepo
az acr manifest show myregistry.azurecr.io/myrepo:oci-multi-arch
Add [OCI image index](https://github.com/opencontainers/image-spec/blob/main/image-index.md) media-type (`application/vnd.oci.image.index.v1+json`) to registry http request accept header.
For the backward compatibility, the change also adds Docker image `manifest` and `manifest list` media type in the accept header.
Fix #25280 
```
az login
az acr login -n myregistry
docker buildx create --name container --driver=docker-container --bootstrap
echo "FROM hello-world" | docker buildx build --builder=container --progress plain --platform linux/amd64,linux/arm64 -t myregistry.azurecr.io/hello-world:multi-arch-oci --push -
az …
```
=> [ACR] `az acr manifest`: Support oci image index

src/azure-cli-core/azure/cli/core/telemetry.py, src/azure-cli-core/setup.py
Fix #24783 
Currently we use `platform.system()`, `platform.version()` and `platform.platform()` to log OS info in telemetry https://github.com/Azure/azure-cli/blob/060b414d8ac5e4d8f4fc17cc2e23c2154c762226/src/azure-cli-core/azure/cli/core/telemetry.py#L143-L145
But it's not clear in some scenarios for linux distribution like @jiasli mentioned in the linked issue.
In this PR, we import `distro` lib for linux and log detailed info. Another two fields will be added to `Properties` in telemetry:
- `Context.Default.VS.Core.Distro.Name`
- `Context.Default.VS.Core.Distro.Version`
---
=> {Core} Add linux distribution info in telemetry

.flake8
In https://github.com/Azure/azure-cli-dev-tools/pull/351, Flake8 is upgrade to 6.0, and the old `.flake8` is not compatible.
> Flake8 does not support inline comments for any of the keys    -- https://flake8.pycqa.org/en/6.0.0/user/configuration.html
I put comments to new lines.
Without this PR, this error is raised.
```
╰─ azdev style redis                                                                                                                        ─╯
===============
| Style Check |
===============
Modules: redis
Running pylint on modules...
Pylint: PASSED
Running flake8 on modules...
File "C:\Users\kk\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, …
```
=> {CI} Make .flake8 compatible with Flake8 6.0.0

src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_common.py
Earlier, The management URLs were hardcoded because of which the CLI was unusable in the national clouds.
With this change, the CLI will work for all clouds when the user selects the cloud.
Tested manually in the local environment.
---
=> [RDBMS] `az postgres flexible-server migration`: Use Cloud supplied URL's rather than hardcoded management URL's

Dockerfile
Revert #24768, as #24793 is merged and cryptography and pyOpenSSL support openssl3.
Although `openssl1.1-compat` is only available from 2.43.0, it's worth to mention this in changelog.
---
=> [Packaging] Remove openssl1.1-compat and use openssl-dev in docker image

scripts/live_test/CLITest.yml
pytest-rerunfailures released a new version 11.1 on 2023-02-09 and added a new function called pytest_runtest_teardown.
That will cause all live test failed.
Error log:
Email:
After I locked pytest-rerunfailures to 11.0, the tests came back to work.
=> {CI} Fix live test: Lock pytest-rerunfailures to 11.0 

src/azure-cli/azure/cli/command_modules/vm/custom.py
`az sig image-definition list-shared`
Closed #25088
The PR fixes a paging bug in VM to solve the problem that the break will be ignored when `num_results` is not divisible by page number.  Since `num_results` is used to handle the maximum value returned in `result`, here should be `<=`. 
---
=> {Compute} Fix #25088: Fix a paging bug in VM

src/azure-cli/azure/cli/command_modules/storage/__init__.py
`az storage account update`
Closed [#25125](https://github.com/Azure/azure-cli/issues/25125)
The inline help for the argument `--access-tier` is out of date. This PR updates help for `--access-tier` to sync what's in the SDK.
`az storage account create -h` or  `az storage account update -h` 
---
=> {Storage} Fix #25125: `az storage account`: Update help for `--access-tier`

src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_mysql.py, src/azure-cli/azure/cli/command_modules/rdbms/validators.py
az mysql flexible-server create
az mysql flexible-server update
This pr change the validation function. When customers input both --iops and --auto_scale_iops and the --auto_scale_iops is enabled, we should tell the customer that only one parameter take effect.
It has been covered in test_mysql_flexible_server_paid_iops_mgmt
=> {RDBMS} `az mysql flexible-server create/update`: Change auto_scale_iops parameter validation logic

src/azure-cli/azure/cli/command_modules/acs/custom.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
az aks check-acr
mariner node will fail with unknown authority
It is because mariner load cert from different path with ubuntu.
https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/service-fabric/service-fabric-configure-certificates-linux.md
---
=> [AKS] `az aks check-acr`: Fix mariner node missing cert

src/azure-cli/azure/cli/command_modules/storage/_params.py, src/azure-cli/azure/cli/command_modules/storage/commands.py, src/azure-cli/azure/cli/command_modules/storage/operations/account.py
`az storage account failover`
Keep the prompt for unplanned failover but remove for planned failover.
---
=> {Storage} `az storage account failover`: Remove prompt for planned failover

src/azure-cli/azure/cli/__main__.py
In [these issues](https://github.com/Azure/azure-cli/issues?q=is%3Aissue+is%3Aopen+%22name+%27exit_code%27+is+not+defined%22), the error message `Auto upgrade failed. name 'exit_code' is not defined` is useless.
I think `handle_exception` should be able to handle all exceptions, but sometimes it fails (In the above issues, most of them are result from import error). And `knack` raise error in [invoke()](https://github.com/microsoft/knack/blob/11f2454b8e4d977797057231d0850e7935b26fa6/knack/cli.py#L245), and `exit_code` is not defined.
https://github.com/Azure/azure-cli/blob/359a85d804eeac3b7a06407594150faf122977d8/src/azure-cli-core/azure/cli/core/util.py#L56
So I set `exit_code` to None, which makes the logic robust and removes `Name 'exit_code' can be undefined` in Python …
=> {Misc} Fix name 'xxx' is not defined error in __main__.py

src/azure-cli/azure/cli/command_modules/acr/custom.py
`az acr login`
Running `az acr login` with `--debug` outputs the following
```
cli.azure.cli.command_modules.acr.custom: Invoking 'docker --username 00000000-0000-0000-0000-000000000000 --password <redacted> myacr.azurecr.io'
```
The actual command run is `docker login --username ...`, but the `login` portion is missing. This PR adds it
Run `az acr login` with the `--debug` flag and validate that the output includes `Invoking 'docker login --username '`
---
=> {ACR} Fix: `az acr login` Add missing command text to log output

src/azure-cli/azure/cli/command_modules/resource/_help.py, src/azure-cli/azure/cli/command_modules/resource/_params.py, src/azure-cli/azure/cli/command_modules/resource/custom.py
az bicep publish
Fixes https://github.com/Azure/bicep/issues/9775. We added a new optional parameter in bicep publish command. As a part of this PR, updating az bicep publish command to support the same.
```az bicep publish --file {bicep_file} --target "br:{registry}/{module_path}:{tag}"```
```az bicep publish --file {bicep_file} --target "br:{registry}/{module_path}:{tag}" --documentationUri {documentationUri}```
=> [ARM] `az bicep publish`: Update command to support new optional parameter `--documentationUri`

src/azure-cli/azure/cli/command_modules/acs/custom.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_upgrade_kubernetes_version_nodepool.yaml, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
```sh
az aks nodepool upgrade
```
Starting from version 2.45.0, the `az aks nodepool upgrade` version fails when used with the `--kubernetes-version` parameter. This was because of accessing a non-existent property on the `AgentPool` instance object here and here, which has been fixed in this PR.
resolves #25530 
```sh
az aks nodepool upgrade --cluster-name {} --resource-group {} --nodepool-name {} --kubernetes-version {}
```
---
=> [AKS] Fix #25530: `az aks nodepool upgrade`: Fix agent pool property name used for fetching current k8s version

src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt
… and pyOpenSSL to 23.0.0
Azure-CLI dependency: `cryptography` `v38.0.4` has a CVE, this release of cryptography patches the CVE
cryptography v38.0.4 has a CVE and v39.0.1 is no longer compatible with OpenSSL 1.x releases. All users must upgrade OpenSSL to 3.x to continue using the CLI
---
=> {Packaging} Bump cryptography to 39.0.1 and pyOpenSSL to 23.0.0

src/azure-cli/azure/cli/command_modules/serviceconnector/_params.py, src/azure-cli/azure/cli/command_modules/serviceconnector/action.py, src/azure-cli/azure/cli/command_modules/serviceconnector/custom.py, src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_local_appconfig_e2e.yaml, src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_local_confluentkafka_e2e.yaml, src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_webapp_appconfig_e2e.yaml, src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_webapp_confluentkafka_e2e.yaml, src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/test_local_connection_scenario.py, src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/test_webpp_connection_scenario.py
=> [Service Connector] `az connection create`: Add new param `--customized-keys`

src/azure-cli/azure/cli/command_modules/storage/_params.py, src/azure-cli/azure/cli/command_modules/storage/operations/blob.py, src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_blob_copy_scenarios.py
`az storage blob copy start-batch`
Fix [#25305](https://github.com/Azure/azure-cli/issues/25305)
Support `--destination-blob-type` and `--tier` for blob type and tier conversion when copying batched blobs.
`storage blob copy start-batch --account-name {} --account-key {} --destination-container {} --source-container {} --source-account-name {} --source-account-key {} --destination-blob-type {} --tier {}`
[Storage] `az storage blob copy start-batch`: Add `--destination-blob-type` and `--tier`
---
=> [Storage] Fix #25305: `az storage blob copy start-batch`: Add `--destination-blob-type` and `--tier`

src/azure-cli/azure/cli/command_modules/sqlvm/_params.py
az sql vm update --sql-mgmt-type LightWeight/Full/NoAgent
The argument --sql-mgmt-type no longer requires to mode to be sent as just full. We have made changes in our feature and thus it can now accept other modes too like LightWeight/ Full / NoAgent.
az sql vm update --sql-mgmt-type LightWeight/Full/NoAgent
[Sqlvm] `az sql vm update`: Update no longer requires the mode to be sent as full
---
=> [Sqlvm] `az sql vm update`: Update no longer requires the mode to be sent as full

src/azure-cli/azure/cli/command_modules/storage/operations/blob.py
`az storage blob copy start`
Fix #25563 
Fix the bug that cannot use `login` for auth when converting blob type in the command `az storage blob copy start`.
`az storage blob copy start --account-name {} --auth-mode login -c {} -b {} --source-account-name {} --source-container {} --source-blob {} --destination-blob-type {}`
---
=> {Storage} Fix #25563: `az storage blob copy start`: Enable to use `--auth-mode login` when converting blob type

src/azure-cli/azure/cli/command_modules/sql/custom.py, src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
`az sql db show-connection-string`
Updated code to make ADO connection string identical to Azure Portal when using `sql db show-connection-string` cmdlet.
Fixes [GitHub Issue 25546](https://github.com/Azure/azure-cli/issues/25546)
---
=> {sql} Code fix for sql db show-connection-string

src/azure-cli/azure/cli/command_modules/iot/tests/hybrid_2019_03_01/test_iot_certificate_commands.py, src/azure-cli/azure/cli/command_modules/iot/tests/hybrid_2020_09_01/test_iot_certificate_commands.py, src/azure-cli/azure/cli/command_modules/iot/tests/latest/test_iot_certificate_commands.py
Change the certificate deletion to a teardown in certificate lifecycle tests. This will force the teardown to run and delete the certificates.
Change to test regarding:
https://github.com/Azure/azure-cli/issues/25481
Use `azdev test test_certificate_lifecycle` 
No customer facing changes. Internal changes only.
---
=> {IoT} Fix test_certificate_lifecycle

src/azure-cli-core/azure/cli/core/auth/landing_pages/error.html, src/azure-cli-core/azure/cli/core/auth/landing_pages/success.html
`az login`
This PR updates the login success landing page to include an announcement for the date on which WAM broker will be used by default for Azure CLI login, alongside instructions for opt-in.
N/A
---
=> [Core] Add announcement for WAM-based login

src/azure-cli/azure/cli/command_modules/appservice/custom.py
`az functionapp list` cmdlet to list functions only
Code Fix to list functions only when using `az functionapp list`.  It was listing logic apps as well.
Fixes [GitHub Issue 24799](https://github.com/Azure/azure-cli/issues/24799)
---
=> {App Service} Fix functionapp list cmd to list functions only

src/azure-cli/azure/cli/command_modules/acr/_docker_utils.py, src/azure-cli/azure/cli/command_modules/acr/_errors.py, src/azure-cli/azure/cli/command_modules/acr/check_health.py
`az acr`
This PR updates the error message that appears when "CONNECTIVITY_REFRESH_TOKEN_ERROR, Response code: 429" occurs. The original message "Please try running 'az login' again to refresh permissions" is misleading and is now replaced with a more accurate message to ask the user to retry.
Fix #24886 
---
=> [ACR] Fix #24886: `az acr`: Improve the 429 error handling for CONNECTIVITY_REFRESH_TOKEN_ERROR

azure-pipelines.yml
If no timeoutInMinutes is set, the default timeout of the ADO task is 60 minutes.
Check CLI Style has recently timed out several times, so increased the timeout to 120 minutes.
But it's not a long-term solution：
We found that after migrating to the new org, the test time increased significantly.
The test machines are all single-core, and no SSD storage is used.
Running the same tests locally is much faster because tests can be run in parallel.
@YanaXu
- If the billing model is based on the total running time, there will be no additional cost for increasing the number of cores.
- And using SSD ( Solid State Driver ) will also greatly increase the speed of some tests, such as installation tests.
=> {CI} Increase Check CLI Style job timeout to 120 minutes

src/azure-cli/HISTORY.rst
This PR is in response to Issue #[3517](https://github.com/MicrosoftDocs/azure-docs-cli/issues/3517).  Both the command name and the typo are fixed in this PR.  I'm closing the MicrosoftDocs/azure-docs-cli Issue as a result.
=> {Doc} `az netappfiles volume quota-rule`: Fixed typo in release notes

src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_mysql.py
az mysql flexible-server update --storage-auto-grow
--storage-auto-grow cannot be set as expected value, due to false instance property name assignment. This PR modify the property name assignment.
=> [RDBMS] `az mysql flexible-server update`: Fix `--storage-auto-grow` parameter unable to be set

src/azure-cli/azure/cli/command_modules/aro/_help.py, src/azure-cli/azure/cli/command_modules/aro/_params.py, src/azure-cli/azure/cli/command_modules/aro/_validators.py, src/azure-cli/azure/cli/command_modules/aro/custom.py
`az aro`
A name change of the new `az aro create` parameter, introduced in this previous PR: https://github.com/Azure/azure-cli/pull/25211, from `install-version` to simply `version`, before we publish documentation and the multi-version feature goes GA.
Run:
```bash
az aro create --resource-group cluster-rg --name test-cluster --vnet test-vnet --master-subnet test-master-subnet --worker-subnet test-worker-subnet --version 4.10.40
```
The command will not give an error on the `version` argument.
[aro] `az aro create`: Rename the create `install-version` parameter to `version`
---
=> [ARO] `az aro`: Rename install-version argument to version

src/azure-cli/azure/cli/command_modules/acs/custom.py
az aks get-credentials
Use os.pathsep instead of hardcoded ":" that breaks things on Windows. Fixes #22321
---
=> [AKS] Fix #22321: `az aks get-credentials`: Fix path separator for Windows when finding `kubeconfig_path`

src/azure-cli-core/azure/cli/core/profiles/_shared.py, src/azure-cli/azure/cli/command_modules/appservice/_client_factory.py, src/azure-cli/azure/cli/command_modules/appservice/_constants.py, src/azure-cli/azure/cli/command_modules/appservice/_params.py, src/azure-cli/azure/cli/command_modules/appservice/_validators.py, src/azure-cli/azure/cli/command_modules/appservice/custom.py, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py, src/azure-cli/requirements.py3.Darwin.txt, src/azure-cli/requirements.py3.Linux.txt, src/azure-cli/requirements.py3.windows.txt
…nvironment` to support setting the name of container app environment (#25223)
This reverts commit f156109256a6449cf0ac33d3f8a7af7a19b270f0. We are reverting this commit since we intend to have these changes live in the next release, not this one.
az functionapp create
As part of the Centauri effort, we need to add the `--environment` parameter to the `az functionapp create` command so that customers can pass the managed AKS environment where the function app will be deployed.
1. Create an App Service plan (`az functionapp plan create -g <resource-group-name> -n <plan-name> --sku S1`)
2. Create an managed AKS environment(`az containerapp env create -n <managed-environment-name> -g <resource-group-name>`)
3. Create a function app in the …
=> {App Service} `az functionapp create`: Revert PR #25223

src/azure-cli/azure/cli/command_modules/serviceconnector/_utils.py
`az spring connection`
Fix typo in displaying messages.
---
=> {Misc} fix typo in messages

requirements.txt, scripts/release/debian/build.sh, scripts/release/rpm/azure-cli.spec
On windows, the latest `setuptools` is installed, as it use `get-pip.py` to install pip and setuptools.
https://github.com/Azure/azure-cli/blob/3a793a0ae1caa9a361cc626d70a6b3eec359b4d9/build_scripts/windows/scripts/build.cmd#L98
On macOS, it depends on the python3.10 `setuptools` version, brew updates it automatically?
https://github.com/Azure/azure-cli/blob/3a793a0ae1caa9a361cc626d70a6b3eec359b4d9/scripts/release/homebrew/docker/formula_template.txt#L31
On Linux, `setuptools` is installed when create Python virtual [env](https://docs.python.org/3/library/venv.html). It may be an old version.
Update it to latest version to prevent security issue.
Related: https://github.com/Azure/azure-cli/pull/24992#discussion_r1098335454
Close …
=> {Packaging} Use latest setuptools on Linux

src/azure-cli-core/azure/cli/core/aaz/_command_ctx.py, src/azure-cli-core/azure/cli/core/tests/test_aaz_command_ctx.py
=> [Core] `aaz`: Add support for changing subscription of `AAZCommand` in customization code

src/azure-cli/azure/cli/command_modules/appservice/custom.py, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands_thru_mock.py
`az functionapp deployment source config-zip`
Related GitHub issue: #25375 
In order for deployments not to rely on the AzureWebJobsStorage app setting but on managed identity, we would have to make substantial changes in the way we currently handle deployments for Linux consumption in the backend. Since it is currently not supported, we have decided to change the logic such that if customers attempt to deploy a Linux consumption function app (regardless of remote build or non remote build), they would have to do it manually by following documentation.
1. Create a Linux consumption function app: `az functionapp create -g <resource-group-name> -n <functionapp-name> -c <location> -s <storage-account-name> --os-type Linux --runtime dotnet …
=> [App Service] Fix #25375: `az functionapp deployment source config-zip`: Fix the `Could not find a 'AzureWebJobsStorage' application setting` error

azure-pipelines.yml, scripts/release/rpm/test_mariner_in_docker.sh
Other builds have this test, add the same test for Mariner.
---
=> {CI} Add Test Rpm Package Mariner

.azure-pipelines/templates/automation_test.yml, scripts/ci/automation_full_test.py
Add the condition for the pipeline result display feature to avoid error like:
---
=> {CI} Fix `NoneType` error by add condition for pipeline result display feature

src/azure-cli/azure/cli/command_modules/resource/_help.py
fixes Azure/azure-cli#25760 
Fix the typo for Az Bicep CLI description
The word `Format` is misspelled multiple times in the `az bicep format` examples section. Currently says `Foramt` instead of `Format`.
---
=> {ARM} fixes Azure/azure-cli#25760 Fix the typo for Az Bicep CLI description

src/azure-cli/azure/cli/command_modules/cosmosdb/custom.py
az cosmosdb identity assign
This PR aims to bring the cli's identity assignment (and reassignment) to be consistent with the current state of ARM.
Due to system issues or bugs in the communication with MSI, an account's identity might be left stale. This change makes the refresh, via cli, as easy as just readding said identity.
This is all already possible via ARM.
Before: az cosmosdb identity assign just returned the resource as a no op.
after: It should reassign the identity, renewing its properties.
---
=> [CosmosDB] `az cosmosdb identity assign`: Allow refreshing user assigned identities if they're reassigned to an account

src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
N/A, test only
Current cli tests which involves node image upgrades are not meaningful. These tests is relying on a buggish behavior in upgradeNodeImageVersion API to function. If we are upgrading the node image of an agent pool which is already on the latest node image version, upgradeNodeImageVersion API will exit silently after very long validation on the async side.
Existing nodeimageupgrade related cli tests are all trying to upgrade the node image of clusters which is already on the latest image version. And it only checks if the agent pool goes into UpgradingNodeImageVersion provisioningState. It never verifies whether the upgrade succeeded or not, which make these tests meaningless.
After changing upgradeNodeImageVersion API to return 304 when …
=> {AKS} Update cli tests disable upgrade node image related tests

src/azure-cli/azure/cli/command_modules/ams/operations/identity.py
`az ams account identity assign --system-assigned true`
Managed identity assignment (using --system-assigned true) is not working on a newly created media service account.
Fixes [GitHub Issue 25677](https://github.com/Azure/azure-cli/issues/25677)
`az ams account identity assign --system-assigned true`
---
=> {ams} Fix account identity error while assigning system managed identity

README.md
Homebrew stops to install from url in this PR https://github.com/Homebrew/brew/pull/7660 and raises `Non-checksummed download of azure-cli formula file from an arbitrary URL is unsupported!`. 
We should download the formula and install it with ` --build-from-source`.
=> {Doc} Update Homebrew edge installation guide

src/azure-cli/azure/cli/command_modules/sql/_help.py, src/azure-cli/azure/cli/command_modules/sql/_params.py, src/azure-cli/azure/cli/command_modules/sql/commands.py, src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_refresh_external_governance_status.yaml, src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
az sql server refresh-external-governance-status 
The cmdlet allows user to refresh the external governance status on a server. 
az sql server refresh-external-governance-status --resource-group nitgup-canary --server nitgup-donotdelete-canary
---
=> [SQL] `az sql server refresh-external-governance-status`: New command for refreshing external governance status

src/azure-cli/azure/cli/command_modules/storage/operations/blob.py
`az storage blob copy start`
To fix the issue when copying from source uri containing sas token with specific tier:
```
> az storage blob copy start -b test.copy.txt -c tmpcontainer --account-name yssa --source-uri """https://yssa.blob.core.windows.net/tmpcontainer/test.txt?sp=r&st=2023-03-20T04:35:32Z&se=2023-03-20T12:35:32Z&spr=https&sv=2021-12-02&sr=b&sig=y5g%2BkqmQgOiMBS4pCzjPI8Ihd6EG2HcydEhjq0DZiI8%3D"""
--tier Cool
ERROR: Authentication information is not given in the correct format. Check the value of Authorization header.
ErrorCode:None
```
This error is throw from line 1047
https://github.com/Azure/azure-cli/blob/e072af7d6531998637007b36c4af88c89f91027a/src/azure-cli/azure/cli/command_modules/storage/operations/blob.py#L1046-L1055
The …
=> [Storage] `az storage blob copy start`: Fix auth issue when providing source uri containing sas token

src/azure-cli-core/azure/cli/core/aaz/_command.py
closed https://github.com/Azure/azure-cli/issues/25878
Ignore the empty or invalid folders while load aaz, the message will be included in debug logs.
---
=> {core} `aaz`: Ignore empty folders while loading `aaz` in modules

src/azure-cli/azure/cli/command_modules/acs/_roleassignments.py
In version 2.46.0 of azure-cli, due to the [update of the API](https://github.com/Azure/azure-cli/pull/25452) used by the role assignment-related operations, when the role assignment already exists, the returned error message is changed, and the code that previously performed this type of error checking can no longer handle such error, so that the command finally raise an error similar to `Cannot create a role assignment for xxx...`.
The error message of adding exiting role assignment is (sending request with API version `2022-04-01`)
```
(RoleAssignmentExists) The role assignment already exists.
Code: RoleAssignmentExists
Message: The role assignment already exists.
```
Previously the error message is (sending request with API version …
=> {AKS} `az aks update`: Remove the error that could not create a role assignment error when the role assignment already exists

src/azure-cli/azure/cli/command_modules/storage/track2_util.py
`az storage container/blob list`
Fix #25674 
While listing blobs, CLI will get page by page and end up with no continuation token(line 78) or the total length equals the request num(line 83):
https://github.com/Azure/azure-cli/blob/e0cc1bc72fb444f54ded44eeefbeff4e73473d2d/src/azure-cli/azure/cli/command_modules/storage/track2_util.py#L70-L89
But **storage service won't always return the exact number we request**, as documented in [List Blobs (REST API)](https://learn.microsoft.com/en-us/rest/api/storageservices/list-blobs?tabs=azure-ad#uri-parameters):
> In certain cases, the service might return fewer results than specified by maxresults, and also return a continuation token.
This will cause problem in CLI. For example, we request 4000 results and the …
=> [Storage] `az storage container/blob list`: Fix MemoryError when service returns less num than requested

src/azure-cli-core/azure/cli/core/telemetry.py
`az -v --debug` shows this error:
```
File "c:\users\hanglei\developer\azure-cli\src\azure-cli\azure\cli\__main__.py", line 62, in <module>
raise ex
File "c:\users\hanglei\developer\azure-cli\src\azure-cli\azure\cli\__main__.py", line 55, in <module>
sys.exit(exit_code)
SystemExit: 0
During handling of the above exception, another exception occurred:
File "c:\users\hanglei\developer\azure-cli\src\azure-cli-core\azure\cli\core\decorators.py", line 79, in _wrapped_func
return func(*args, **kwargs)
File "c:\users\hanglei\developer\azure-cli\src\azure-cli-core\azure\cli\core\telemetry.py", line 324, in set_custom_properties
actual_value = value() if hasattr(value, '__call__') else value
File …
```
=> {Telemetry} Fix KeyError: 'x-ms-client-request-id'

src/azure-cli/azure/cli/command_modules/appservice/_params.py
fix the description of web app -Name parameter
Fixes Azure/azure-cli#25918
**More Info:** Name of the new web app. Web app name can contain only allow alphanumeric characters and hyphens, it cannot start or end in a hyphen, and must be less than 64 characters.
---
=> {App Service} `az webapp create`: Fix the description of `--name`

src/azure-cli/azure/cli/command_modules/monitor/_help.py
Adjust CLI descriptions and help examples to more accurately reflect what the command does. az monitor activity-log alert refers to operations on activity log alert *rules* and not fired alerts.
This is similar to changes made previously for the same command line for metric alerts
az monitor activity-log alert
[monitor] `az monitor activity-log alert`: Adjust help message
---
=> [Monitor] `az monitor activity-log alert`: Update command and help descriptions

src/azure-cli/azure/cli/command_modules/appservice/_params.py
az webapp up --launch-browser
resolves https://github.com/Azure/azure-cli/issues/25616
az webapp up --launch-browser
---
=> {App Service} Fix #25616: `az webapp up`: Add help message to clarify that the cloud shell is not supported

src/azure-cli-core/azure/cli/core/extension/__init__.py, src/azure-cli-core/azure/cli/core/extension/tests/latest/test_extension_commands.py, src/azure-cli/azure/cli/command_modules/feedback/tests/latest/test_feedback.py
`az extension add`
If a command requires an extension and said extension is not installed, this change adds an actionable error message rather than the current behavior of only stating the error.
Fixes https://github.com/Azure/azure-cli-extensions/issues/4342
`az network bastion ssh ...`
[Extension] `az extension add`: Add actionable message for extension not found error
---
=> {Core} Add actionable message for extension not found error

src/azure-cli-core/azure/cli/core/extension/__init__.py
If the extension installation is corrupted, CLI may break because of [AssertionError](https://github.com/azure/azure-cli/blob/ed6e829554624894d5c94ad71bb85e788d726a43/src/azure-cli-core/azure/cli/core/extension/__init__.py#L308). See https://github.com/Azure/azure-cli/issues/25473
It is an extension convention that there must be an azext_xxx folder in extension directory.
Add the instruction to delete extension folder.
`az extension add -n interactive` and delete `~/.azure/cliextensions/interactive/azext_interactive`
--- …
=> {Core} Add instruction to fix incomplete extension

doc/overwrite_order_in_cli.md, src/azure-cli-core/azure/cli/core/extension/__init__.py
**Instructions for use**
You need to ensure that the extension name of preview is sorted after the extension name of GA
For example：
GA extension name： containerapp
Preview extension name: containerapp-preview
**Testing result**
1. If the command only exists in the ga extension, keep it
2. If the command exists at the same time, the preview command will overwrite ga
3. If the command only exists in the preview extension, keep it
Now, our command table is loaded three times
1. Load the CLI module 
2. Load the wheel extension (az extension add)
3. Load dev extension (azdev extension add)
[Load the modules first and then the extensions](https://github.com/Azure/azure-cli/blob/5a80d3507270cc3b9313a3e6e60daf291489a80d/src/azure-cli-core/azure/cli/core/__init__.py#L424-L426)
``` …
```
=> {Core} Support preview extension to override GA extension

src/azure-cli/azure/cli/command_modules/resource/_bicep.py, src/azure-cli/azure/cli/command_modules/resource/custom.py, src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_bicep.py
```
az bicep install
az bicep upgrade
```
In #25541, we are checking for the current value of `bicep.use_binary_from_path` config value and updating it to `false` when `bicep` is installed via Azure CLI.
This check was missing a default value, throwing an error in the process. This PR fixes this.
resolves #25715, resolves #25710
```
az bicep upgrade
az bicep install
```
---
=> [ARM] Fix #25715: `az bicep install/upgrade`: Fix the `configparser.NoSectionError: No section: 'bicep'`

src/azure-cli/azure/cli/command_modules/acs/_consts.py, src/azure-cli/azure/cli/command_modules/acs/_help.py, src/azure-cli/azure/cli/command_modules/acs/_params.py, src/azure-cli/azure/cli/command_modules/acs/custom.py, src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_with_network_dataplane_cilium.yaml, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
Add the `--network-dataplane` flag to `az aks create` so users can enable [Azure CNI powered by Cilium](https://learn.microsoft.com/en-us/azure/aks/azure-cni-powered-by-cilium).
`az aks create -n testcluster -g testgroup--network-plugin=azure --network-dataplane=cilium --network-plugin-mode=overlay`
[AKS] `az aks create`: Add new parameter `--network-dataplane` to support creating Cilium clusters
---
=> [AKS] `az aks create`: Add new parameter `--network-dataplane` to support creating Cilium clusters

azure-pipelines.yml
`az bicep`
`azure.cli.command_modules.resource._bicep.ensure_bicep_installation` fails to access `https://downloads.bicep.azure.com/` on Mariner 2.0: 
```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1129)
```
This leads to CI failure for `tests/latest/test_resource_custom.py::TestFormatBicepFile::test_format_bicep_file`:
https://dev.azure.com/azclitools/public/_build/results?buildId=45199&view=logs&j=b67de874-13d2-5286-c044-deb7a6e6a9ee&t=f22bcdb8-df09-5097-beed-939fe0350d62&l=13327
```
2023-03-31T04:48:28.2148390Z /usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/resource/custom.py:3749: in format_bicep_file
2023-03-31T04:48:28.2148754Z …
```
=> {CI} Disable job `TestRpmPackageMariner`

src/azure-cli/azure/cli/command_modules/acs/custom.py
Update the architecture detection mechanism before downloading binary files in command `az aks install-cli`. Currently it only supports distinguishing between arm64 and amd64 architectures. The new change is that when an unknown architecture is obtained, an exception will be thrown directly (previously it will only show a warning message).
---
=> {AKS} `az aks install-cli`: Update architecture detection

src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/url_path_map/_create.py
Resolve: https://github.com/Azure/azure-cli/issues/25889
---
=> {Network} `az network application-gateway url-path-map create`: Update document

src/azure-cli/azure/cli/command_modules/botservice/bot_json_formatter.py
Fixes Azure/azure-cli#26037
While running the CLI command `az bot show -n botnaem -g rsourcegroupname --msbot` we get the below error:
```
File "D:\a_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/init.py", line 697, in _run_job
File "D:\a_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/init.py", line 333, in call
File "D:\a_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 363, in handler
File "D:\a_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/arm.py", line 429, in show_exception_handler
File "D:\a_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", …
```
=> {AzureBotService} fix for the AttributeError in 'az bot show' CLI command

src/azure-cli/azure/cli/command_modules/acs/tests/hybrid_2020_09_01/test_custom.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_custom.py
In PR [#26035](https://github.com/Azure/azure-cli/pull/26035), the command `az aks install-cli` starts to support the distinction between arm64 and amd64 architectures, but in some test cases, the mock binary is hardcoded with amd64 arch.
---
=> {AKS} `az aks install-cli`: Fix install-cli related test cases

src/azure-cli-core/azure/cli/core/aaz/_command.py, src/azure-cli-core/azure/cli/core/tests/test_aaz_field.py
=> [Core] `aaz`: Support hidden secret properties of response in output

doc/onboarding_guide.md
=> {doc} Add aaz-dev-tools link in onboarding_guide.md

src/azure-cli-core/azure/cli/core/_session.py, src/azure-cli-core/azure/cli/core/mock.py, src/azure-cli-testsdk/azure/cli/testsdk/base.py, src/azure-cli/azure/cli/command_modules/config/tests/latest/test_config.py, src/azure-cli/azure/cli/command_modules/configure/tests/latest/test_configure.py, src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py, src/azure-cli/azure/cli/command_modules/role/tests/latest/test_role.py
ARM64 machines are multi-core, and some errors occur because of concurrency, as all tests use same config dir.
I add a `random_config_dir` param in `DummyCli`. If it is True, the config dir will be `~/.azure/dummy_cli_config_dir/xxxxxxx`.
If random config is enabled by default, the config file is created for each test, and the performance decrease a lot.
`Azure.azure-cli Full Test` spends 24 min instead of 16min.
I enable `random_config_dir` for the tests which use `az config` or `az configure`.
Example usage:
``` python
class ConfigTest(ScenarioTest):
def __init__(self, *arg, **kwargs):
super().__init__(*arg, random_config_dir=True, **kwargs)
```
```
2023-03-03T11:05:05.5590254Z [gw2] [ 65%] FAILED tests/test_cloud.py::TestCloud::test_remove_known_cloud …
```
=> {Core} Add random_config_dir param in DummyCli

src/azure-cli/azure/cli/command_modules/eventhubs/custom.py
`az eventhubs namespace application-group policy remove`
Removing parameters metric-id, rate-limit-threshold from --throttling-policy-config object only for `az eventhubs namespace application-group policy remove` command.
Additionally changing `throttling-policy-config` name to `policy`,  for `az eventhubs namespace application-group policy remove` command. 
The change will release in Upcoming breaking change cycle i.e May.
---
=> [EventHub] `az eventhubs namespace application-group policy remove`: Add upcoming breaking change notification

src/azure-cli/azure/cli/command_modules/appservice/_help.py, src/azure-cli/azure/cli/command_modules/appservice/_params.py, src/azure-cli/azure/cli/command_modules/appservice/static_sites.py, src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_staticapp_commands_thru_mock.py
`az staticwebapp appsettings`
In the `az staticwebapp appsettings` command today, we do not provide any way for app setting operations to be made against the non-production preview environments of a static web app. This PR surfaces the `--environment-name` parameter on app setting requests to allow for this.
Added unit tests and also ran commands like:
`az staticwebapp appsettings list -n MyAppName -g MyResourceGroup --environment-name preview`
`az staticwebapp appsettings set -n MyAppName -g MyResourceGroup --environment-name preview --setting-names key1=val1 key2=val2`
`az staticwebapp appsettings delete -n MyAppName -g MyResourceGroup --environment-name preview --setting-names key2 missingkey`
--- …
=> [App Service] `az staticwebapp appsettings`: Add `--environment-name` parameter to allow app setting operation on preview environments

src/azure-cli-telemetry/azure/cli/telemetry/components/records_collection.py, src/azure-cli-telemetry/azure/cli/telemetry/tests/test_records_collection.py
We decide to drop CLI telemetry local cache because of
- CLI telemetry local cache strategy has introduced a lot of troubles
- Learning from PSH and VSCode, we know that they don't have any local cache
- Carl from devdiv data team has confirmed that the application insight's quota is highly customizable.
We don't want to drop local cache by one night so things need to change step by step:
1. Shorten the cache push interval from 24 hours to 6 hours
2. Wait for few CLI versions until the usage of 6hours interval grows up to 50% and see if there's any risks
3. Shorten the cache push interval from 6 hours to 1 hour
4. Repeat step 2
5. Totally remove local cache
This PR is for step 1
---
=> {Telemetry} Shorten default push interval from 24h to 6h

src/azure-cli/azure/cli/command_modules/appservice/custom.py
The backend now expects us to set the 'kind' attribute to 'functionapp,linux,container,azurecontainerapps' for Centauri function apps.
Create a new function app and look for the updated 'kind' value for the function app (`az functionapp create`)
---
=> [AppService] `az functionapp create`: Update 'kind' attribute for Centauri function apps

src/azure-cli/azure/cli/command_modules/servicebus/_help.py, src/azure-cli/azure/cli/command_modules/servicebus/_params.py, src/azure-cli/azure/cli/command_modules/servicebus/custom.py
`parameters` argument will be removed from `az servicebus georecovery-alias fail-over` cmdlets in future release.
---
=> {Servicebus} Add Breaking change message for `az servicebus georecovery-alias fail-over` cmdlets

src/azure-cli/azure/cli/command_modules/eventhubs/_params.py, src/azure-cli/azure/cli/command_modules/eventhubs/commands.py, src/azure-cli/azure/cli/command_modules/eventhubs/custom.py, src/azure-cli/azure/cli/command_modules/servicebus/custom.py
We will change the format of this command in Future release. the parameter `vnet-name` will be deprecated in future.
We will offer simultaneous addition and removal of multiple IP rules and subnet rules with the new future release cmdlets.
We are targeting these breaking change in this May breaking change cycle.
We will Replace the following command.
1. `az eventhubs namespace network-rule` with `az eventhubs namespace network-rule-set`
2. `az eventhubs namespace network-rule add` with `az eventhubs namespace network-rule-set ip-rule add`, `az eventhubs namespace network-rule-set virtual-network-rule add`
3. `az eventhubs namespace network-rule remove` with `az eventhubs namespace network-rule-set ip-rule remove`, `az eventhubs namespace …
=> {EventHub} Add Breaking change message for `az eventhubs namespace network-rule` cmdlets.

src/azure-cli/azure/cli/command_modules/dms/_help.py, src/azure-cli/azure/cli/command_modules/dms/scenario_inputs.py
az dms project task create
This change enables database schema migration for MySQL migrations.
---
=> [Dms] `az dms project tack create`: Add support for database schema migration

src/azure-cli-core/azure/cli/core/aaz/__init__.py, src/azure-cli-core/azure/cli/core/aaz/_arg.py, src/azure-cli-core/azure/cli/core/aaz/_arg_action.py, src/azure-cli-core/azure/cli/core/aaz/_prompt.py, src/azure-cli-core/azure/cli/core/tests/test_aaz_prompt.py
Support argument prompt input for AAZCommand args when the value is blank.
Below is the current usage for a command without prompt input for secure arguments like `--password`
Now we can support prompt input for those secure arguments like this way
The password is not appeared in TTY.
For those arguments which supports prompt input, you can see the following message added in their short summary:
Which means if the value of those arguments is blank, the prompt input will be triggered in TTY. 
The there are two prompt input classes: 
- AAZPromptInput: Used for regular arguments. The input will be display in TTY.
- AAZPromptPasswordInput: Used for password kind of arguments. The input will be hidden. And support input confirmation.
The first prompt input …
=> [Core] `aaz`: Support argument prompt input

src/azure-cli-core/azure/cli/core/util.py
Fix #19183
The timeout of checking the latest version from GitHub is 10 seconds. The `az -v` command is extremely slow (20s) if no internet connection.
This PR fixes this issue. It takes about 2s now.
Enable auto upgrade, add `127.0.0.1 raw.githubusercontent.com` in hosts, `time az -v`.
---
=> {Core} Fix #19183: Improve get GitHub latest version speed if no internet connection

scripts/release/debian/test_deb_package.py, scripts/release/rpm/test_rpm_package.py
Add those module to `serial_test_modules` to prevent failure in ARM64 Test because of high concurrency.
It hardcode `cloud.config` path. See https://github.com/Azure/azure-cli/pull/26138
It does not use `random_config_dir`, so the error occurs when write to same config file.
https://github.com/Azure/azure-cli/blob/7a087b14d59296832cbbabe496bef2e0a2557e28/src/azure-cli/azure/cli/command_modules/iot/__init__.py#L14-L29
It consists of tests that install & uninstall same bicep binary file.
`azure/cli/command_modules/resource/tests/latest/test_resource_bicep.py`
---
=> {CI} Use serial test in azure-cli-core, iot, resource

Dockerfile, scripts/release/debian/build.sh, scripts/release/rpm/azure-cli.spec
We have used `trim_sdk.py` and only keep pyc file on Windows. Apply them on Linux and docker to reduce package size.
This is the first part, use trim_sdk on Linux.
Using pyc is https://github.com/Azure/azure-cli/pull/25801
Result:
Ubuntu 22.04 installed size: 965MB -> 576 MB, become 60% of original size. 
RHEL 9 installed size 771MB -> 403 MB, become 52% of original size. 
Docker  1328MB -> 952MB,  become 72% of original size. 
---
=> {Packaging} Optimize Linux package and docker image by trimming SDK

src/azure-cli/azure/cli/command_modules/appservice/custom.py, src/azure-cli/azure/cli/command_modules/appservice/utils.py
```sh
az functionapp deployment source config-zip --name "$(myFuncName)" --resource-group "$(myRg)" --src "myZipFile"
```
Attempt to fix #13655.
Exact error I am seeing:
```
File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
result = cmd_copy(params)
File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
return self.handler(*args, **kwargs)
File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
return op(**command_args)
File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 531, in …
```
=> {App Service} `az functionapp deployment source config-zip`: Increase read timeout

src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
Fix az cli issue for PG public access server for sending empty Network properties in Network object for public access server instead of sending Network object as null
az postgres flexible-server create -g <resource_group_name> -n <server_name> -l <location_name>
In recent M-train we added a String.IsNullOrEmpty check for one of the Network properties PrivateDnsZoneArmResourceId. This resulted into the cli command breaking for public access servers. This is because the CLI was sending Network object instantiated with empty properties "network": {"delegatedSubnetResourceId": "", "privateDnsZoneArmResourceId": ""}.
The fix here is to send the Network object as null in case of public access servers.
Verified public access server creation …
=> {RDBMS} Postgres Flexible server - Fix az cli issue for PG public access server for Network object with recent M-train changes

src/azure-cli/azure/cli/command_modules/storage/_help.py, src/azure-cli/azure/cli/command_modules/storage/_params.py, src/azure-cli/azure/cli/command_modules/storage/_params_azure_stack.py, src/azure-cli/azure/cli/command_modules/storage/linter_exclusions.yml, src/azure-cli/azure/cli/command_modules/storage/operations/azcopy.py, src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_azcopy_scenarios.py
az storage blob sync ... **-- --cap-mbps=1.0**
Adds positional argument extra_options with experimental tag for flexibility, e.g. for setting an upload bandwith limit, for the blob sync command, that then will be passed to `azcopy`. similar to https://github.com/Azure/azure-cli/pull/20702
---
--> the underlying command (azcopy) will give an error if the cap-mbps value is not a number.
=> [Storage] `az storage blob sync`: Add positional argument extra_options to pass through options to azcopy

azure-pipelines.yml, scripts/release/rpm/mariner.dockerfile, scripts/release/rpm/test_mariner_in_docker.sh
Revert https://github.com/Azure/azure-cli/pull/26005
According to https://eng.ms/docs/products/mariner-linux/gettingstarted/containers/marinercontainerimage
> (Mariner) By default containers include a limited set of [root certificates](https://eng.ms/docs/products/mariner-linux/gettingstarted/packages/certificates) specifically for trusting Microsoft specific web sites like packages.microsoft.com. More complete sets of root certificates may be installed if necessary. Click [here](https://eng.ms/docs/products/mariner-linux/gettingstarted/packages/certificates) to read more.
Now we have to manually install `ca-certificates` to allow Azure CLI on Mariner to access addresses such as
https://github.com/Azure/azure-cli/blob/36786c51a5d42ff1b0a197e72a2c12261ff6743b/src/azure-cli/a …
=> {CI} Install `ca-certificates` in Mariner docker container

src/azure-cli-testsdk/azure/cli/testsdk/preparers.py
After adding the new label test: $test_method, we can easily find the test corresponding to this resource group.
---
=> {CI} Update `ResourceGroupPreparer` decorator to support tag test method in resource group

src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py, src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
az aks create
Raise an error instead of logging a warning when using `--pod-cidr` with `--network-plugin azure` without `--network-plugin-mode overlay`
azdev test acs.test_get_network_plugin
[AKS] BREAKING CHANGE: `az aks create`: Specifying `--pod-cidr` with Azure CNI will return an error instead of logging a warning when not use `overlay` mode
---
=> [AKS] BREAKING CHANGE: `az aks create`: Raise error when specifying `--pod-cidr` with `--network-plugin azure` without overlay
