- src/azure-cli-core/azure/cli/core/profiles/_shared.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_community_gallery_operations.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_create_disk_from_diff_gallery_image_version.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_create_image_version_with_region_cvm_encryption.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_create_image_version_with_region_cvm_encryption_pmk.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_create_vm_with_community_gallery_image.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_create_vm_with_shared_gallery_image.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_controller_type.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_e2e.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_image_version_vhd.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_specialized.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_image_build_shared_image.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_image_version_create_for_diff_source.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_replication_mode.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_shared_gallery.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_specialized_image.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_update_gallery_permissions.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_max_shares_etc.yaml
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
Bump up `azure-mgmt-compute` SDK to `29.0.0`
`gallery_image_versions`: `2022-03-03`
{Compute} Bump up `azure-mgmt-compute` SDK to `29.0.0`
---
> [Compute] Fix #24187: `az vm list`: Fix the AttributeError 'ComputeManagementClientConfiguration' object has no attribute 'api_version'

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/linter_exclusions.yml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_extension_list.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
`az vm extension list`
az vm extension list to include support "--ids"
close https://github.com/Azure/azure-cli/issues/22527
[Compute] `az vm extension list`: Add new parameter `--ids` to support listing extensions by VM id
---
> [Compute] `az vm extension list`: Add new parameter `--ids` to support listing extensions by VM id

- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_multiple_ipconfigs_update_with_asg.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
az network nic ip-config update
Fixes: https://github.com/Azure/azure-cli/issues/21551
1. Covered by test case `test_multiple_ipconfigs_update_with_asg`
2. Added alias `--asgs` for easier use
az network nic ip-config update -n {ipconfig_name} -g {rg} --nic-name {nic_name} --asgs {asg_name}
---
> [Network] Fix #21551: `az network nic ip-config update`: ASGs update with multiple IP configurations

- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_waf_policy_exclusion_rule_set.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
az network application-gateway waf-policy managed-rule exclusion rule-set remove
Fixes: https://github.com/Azure/azure-cli/issues/24169
Previous Status:
After Execution:
Covered by test case: `test_network_app_gateway_waf_policy_exclusion_rule_set`
```
az network application-gateway waf-policy managed-rule exclusion rule-set remove -g appGateway --policy-name appGatewayPolicy --match-variable RequestHeaderValues --match-operator Contains --selector kapil --type OWASP --version 3.2 --group-name REQUEST-921-PROTOCOL-ATTACK
```
--- …
> [Network] Fix #24169: `az network application-gateway waf-policy managed-rule exclusion rule-set remove`: Remove exclusion with different matchers

- src/azure-cli/azure/cli/command_modules/serviceconnector/_credential_free.py
> {Service Connector} `az spring connection create postgres`: Update database user permissions

- .github/fabricbot.json
> {CI} Update milestone from Oct 2022 (2022-11-01) to Nov 2022 (2022-12-06)

- .github/CODEOWNERS
> {CodeOwner} Update CodeOwner For service connector

- src/azure-cli/azure/cli/command_modules/acs/_help.py
Update Availability zones summary to add clarification when customer wants to have all 3 zones
--zones 1 2 3
Fixes [24145](https://github.com/Azure/azure-cli/issues/24145)
```
az aks nodepool add --cluster-name   {} --name   {} --resource-group {} --zones 1 2 3
az aks nodepool add --cluster-name   {} --name   {} --resource-group {} --zones 1 2
```
---
> {AKS} Update Availability zones summary

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/public_ip/_create.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/public_ip/_update.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_public_ip_prefix.yaml
Fixes: https://github.com/Azure/azure-cli/issues/24377
---
> [Network] Fix #24377: `az network public-ip create`: Derive Public IPs in different resource group from Public IP Prefix

- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_snapshot_create_with_source_blob_uri.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
`az snapshot create`
IMPORT_ENUM keyError  
close https://github.com/Azure/azure-cli/issues/24263
---
> [Compute] Fix #24263: `az snapshot create`: Fix the KeyError 'IMPORT_ENUM' when creating snapshot from source blob uri

- src/azure-cli-core/azure/cli/core/aaz/_command.py
> [Core] `aaz`: Support configured_default in arguments

- src/azure-cli/azure/cli/command_modules/apim/_params.py
- src/azure-cli/azure/cli/command_modules/apim/custom.py
- src/azure-cli/azure/cli/command_modules/apim/tests/latest/recordings/test_apim_core_service.yaml
- src/azure-cli/azure/cli/command_modules/apim/tests/latest/test_apim_scenario.py
Add parameters to allow users to to set "disable_gateway" and "public_network_access" properties of apim service
[APIM] `apim create/update`: Add `--public-network-access` to support specifying whether or not public endpoint access is allowed for this API management service
[APIM] `apim create/update`: Add `--disable-gateway` to support disabling gateway in the master region
---
> [APIM] `apim create/update`: Add new parameters `--public-network-access` and `--disable-gateway`

- linter_exclusions.yml
- src/azure-cli/azure/cli/command_modules/synapse/manual/_help.py
- src/azure-cli/azure/cli/command_modules/synapse/manual/_params.py
- src/azure-cli/azure/cli/command_modules/synapse/manual/operations/workspace.py
Fix issue https://github.com/Azure/azure-cli/issues/23579
---
> [Synapse] `az synapse workspace create`: Add parameter `--managed-resource-group-name`

- scripts/live_test/CLITest.yml
- scripts/live_test/sendemail.py
Sensitive data should not be exposed in code, even for testing purposes.
This PR will move the sensitive data to Azure Devops variables.
> {CI} Remove hardcoded data to avoid exposing sensitive data

- src/azure-cli/azure/cli/command_modules/appconfig/_kv_helpers.py
- src/azure-cli/azure/cli/command_modules/appconfig/_utils.py
- src/azure-cli/azure/cli/command_modules/appconfig/custom.py
- src/azure-cli/azure/cli/command_modules/appconfig/keyvalue.py
`az appoconfig`
This change is being added to updated the raised errors to more specific errors in `azure.cli.core.azclierror` instead of the base `CLIError` class. Follow up to [PR #24400](https://github.com/Azure/azure-cli/pull/24400)
[App Config] `az appconfig`: Update raised errors in app config command module
---
> {App Config} Update raised errors in app config command module

- azure-pipelines.yml
Integrate the CodeGen Coverage in CI
---
> {CI} Add job for Codegen Coverage

- scripts/live_test/CLITest.yml
- Update timeout to unlimited
- Specify to use 1ES pool
> {CI} Update CLITest.yml to use 1ES agent pool

- src/azure-cli/azure/cli/command_modules/resource/_params.py
- src/azure-cli/azure/cli/command_modules/resource/custom.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_management_group_deployment_create_mode.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
`az deployment mg create` 
az deployment mg create --mode
close https://github.com/Azure/azure-cli/issues/24193
---
> [ARM] `az deployment mg create`: Add new parameter `--mode` to support setting the mode for deploying resources

- src/azure-cli/azure/cli/command_modules/backup/_params.py
- `az backup policy list -h`
- `az backup protectable-item list -h`
- `az backup protectable-item show -h`
- `az backup protectable-item initialize -h`
- `az backup container register -h`
- `az backup protection enable-for-azurewl`
- `az backup protection auto-enable-for-azurewl`
- `az backup protection auto-disable-for-azurewl`
Under the option `--workload-type`, `MSSQL` and `SQLDataBase` refer to the same thing, as do `SAPHANA` and `SAPHanaDatabase`. Under `--protectable-item-type`, `SAPHanaSystem` and `HANAInstance` are duplicates as well. Removing any of the options constitutes a breaking change, and for the time being the course of action is to make it clear to the user through documentation what the various options are.
N/A. …
> {Backup} Add documentation: help text details interchangeable parameter values

- src/azure-cli/azure/cli/command_modules/appservice/logicapp/_constants.py
- src/azure-cli/azure/cli/command_modules/appservice/resources/WebappRuntimeStacks.json
Azure Functions team is going to support Python 3.10 in November, we need to allow customers to create Python 3.10 function app in azure-cli before the Python 3.10 announcement.
This is NOT an official Azure Functions Python 3.10  release.
Customer should be able to create Python 3.10
On Linux Consumption with az functionapp create -g <resource_group> -n <app_name> -c <consumption_plan_location> -s <storage_account> --os-type linux --runtime python --runtime-version 3.10 --functions-version 3
On Linux Dedicated/Premium with az functionapp create -g <resource_group> -n <app_name> -p <dedicated_plan_name> -s <storage_account> --os-type linux --runtime python --runtime-version 3.10 --functions-version 3
{App Service} …
> {App Service} Allow Azure Functions Create to accept Python 3.10 parameters

- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/operations/file.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_file_copy_scenario.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_file_copy_snapshot_scenario.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_file_main_scenario.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_file_upload_content_md5_scenarios.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_share_rm_with_stats.yaml
`az storage file upload-batch --dryrun`
Fix #23216 
Fix `--dryrun` parameter was failing.  Missed model change in track2 migration.
[Storage] Fix #23216: `az storage file upload-batch`: Fix `--dryrun` to show correct file paths
---
> [Storage] Fix #23216: `az storage file upload-batch`: Fix `--dryrun` to show correct file paths

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
Fixes https://github.com/Azure/azure-cli/issues/8889
---
> {App Service} Fix #8889: Update error message to clarify the cause

- src/azure-cli-core/azure/cli/core/aaz/_arg.py
- src/azure-cli-core/azure/cli/core/aaz/_command.py
> [Core] `aaz`: Support argument preview and experimental

- src/azure-cli-core/azure/cli/core/aaz/_arg.py
- src/azure-cli-core/azure/cli/core/aaz/_command.py
- src/azure-cli-core/azure/cli/core/aaz/_help.py
- src/azure-cli-core/azure/cli/core/aaz/exceptions.py
- src/azure-cli-core/azure/cli/core/tests/test_aaz_arg.py
Support to hide argument in command display.
---
> [Core] `aaz`: Add registered property for `AAZBaseArg`

- .azure-pipelines/templates/variables.yml
- azure-pipelines.yml
[Policy Check](https://policheck.microsoft.com/)
PoliCheck contains sensitive terms in over 100 languages and provides guidance to determine the appropriate action depending on context. 
The term data also provides explanations of why certain terms are sensitive or unacceptable.
> {CI} Add policy check to Security Tools

- scripts/regression_test/regression_test.yml
The script path has changed
---
> {CI} Fix regression test

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/commands.py
- src/azure-cli/azure/cli/command_modules/appservice/static_sites.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_staticapp_linked_backends.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_staticapp_commands.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_staticapp_commands_thru_mock.py
az staticwebapp backends
Adding Static Web Apps Linked Backend operation support
Check out _help.py
[App Service] `az staticwebapp backends link`: Link an backend to a static webapp. Also known as "Bring your own Backend."
[App Service] `az staticwebapp backends unlink`: Unlink backend from a static webapp
[App Service] `az staticwebapp backends show`: Show details on the backend linked to a static webapp
[App Service] `az staticwebapp backends validate`: Validate an backend for a static webapp
---
> [App Service] Static Web Apps Linked Backends

- src/azure-cli-core/azure/cli/core/aaz/utils.py
- src/azure-cli-core/azure/cli/core/tests/test_aaz_arg.py
> [Core] `aaz`: Add aazlist and aazdict args transform help functions

- src/azure-cli/azure/cli/command_modules/cdn/_help.py
- src/azure-cli/azure/cli/command_modules/cdn/_params.py
Fixes https://github.com/Azure/azure-cli/issues/24711
---
> {CDN} Fix #24711: `az afd rule`: Add examples for `--match-values`

- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/traffic_manager/endpoint/_create.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/traffic_manager/endpoint/_delete.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/traffic_manager/endpoint/_show.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/traffic_manager/endpoint/_show_geographic_hierarchy.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/traffic_manager/endpoint/_update.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/traffic_manager/profile/_check_dns.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/traffic_manager/profile/_create.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/traffic_manager/profile/_delete.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/traffic_manager/profile/_list.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/traffic_manager/profile/_show.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/traffic_manager/profile/_update.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_alias.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_traffi_manager_always_serve.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_traffic_manager.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_traffic_manager2.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_traffic_manager_subnet_routing.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
az network traffic-manager endpoint create
az network traffic-manager endpoint update
Resolves: https://github.com/Azure/azure-cli/issues/24532
azdev test test_network_traffi_manager_always_serve
---
> [Network] `az network traffic-manager endpoint`: Add `--always-serve` to manage the health check on endpoint

- src/azure-cli/azure/cli/command_modules/sql/_params.py
- src/azure-cli/azure/cli/command_modules/sql/custom.py
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_db_replica_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
az sql db replica set-primary
az sql db replica delete-link
This PR uncomments the tests commented out in https://github.com/Azure/azure-cli/pull/23275
1. Create two geo replicas for a db
2. Failover to one secondary
3. Delete link for any of the geo pairs
---
> {SQL} Update SQL DB replica tests

- src/azure-cli/azure/cli/command_modules/network/_validators.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_public_ip.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Related IcM: https://portal.microsofticm.com/imp/v3/incidents/details/350795563
azdev test test_network_public_ip
---
> [Network] `az network public-ip create`: Fix the issue when using `--ip-tags`

- src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_link_endpoint_ml_registry.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
az network vnet create
Added support to manage Private Endpoint of AzureML Registries with Azure CLI.
See tests in PR, and recordings.
---
- [* ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).
- [ *] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).
- [ *] I adhere to the …
> [Network] `az network private-endpoint-connection`: Add Provider `Microsoft.MachineLearningServices/registries`

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Import `getRegionCodeForAzureRegion` in test cases to align with the resource path at creation time. Fix for PR [#24176](https://github.com/Azure/azure-cli/pull/24176), [#24320](https://github.com/Azure/azure-cli/pull/24320). 
---
> {AKS} Fix several monitoring addon related test cases

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_nodepool_snapshot.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
> {AKS} Reorder one step of aks_nodepool_snapshot recording test in order that it won't be affected by 22.04 switch over at k8s 1.25.2

- .github/fabricbot.json
> {CI} Update milestone from Nov 2022 (2022-12-06) to Dec 2022 (2023-01-03)

- src/azure-cli/azure/cli/command_modules/appservice/_params.py
az appservice plan create
az appservice plan update
Adding new SKU for App Service Environment.
az appservice plan create -g ASEResourceGroupName -n ASEPlanName --app-service-environment ASEName --sku I4v2
---
> [App Service] `az appservice plan create/update`: Add new environment SKU for parameter `--sku`

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/routeserver/peering/_list_advertised_routes.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/routeserver/peering/_list_learned_routes.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_virtual_hub_router_scenario.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
az network routeserver peering list-advertised-routes
az network routeserver peering list-learned-routes
Adapt the swagger changes from:
- https://github.com/Azure/azure-rest-api-specs/pull/21608
azdev test test_network_virtual_hub_router_scenario
---
> {Network} `az network routeserver`: Adapt swagger changes

- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
[`six`](https://github.com/benjaminp/six) is a library for compatibility between Python 2 and Python 3. Although `azure-cli` does not seem to actually use `six`, some of its dependencies do. It's better to upgrade to the latest stable version, in order to maintain compatibility with package managers like Homebrew.
---
> {Dependencies} Upgrade to six 1.16

- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/commands.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_probes.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_automatic_repairs_with_health_probe.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_set_orchestration_service_state.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_update_automatic_repairs_with_health_probe.yaml
az network lb probe create
az network lb probe update
az network lb frontend-ip update
Resolves: https://github.com/Azure/azure-cli/issues/24604
Fix the bug mentioned in https://github.com/Azure/azure-cli/pull/24366#discussion_r1036051313
---
> {Network} `az network lb probe`: Add warnings for `--probe-threshold`

- src/azure-cli-core/azure/cli/core/aaz/_field_type.py
- src/azure-cli-core/azure/cli/core/aaz/_utils.py
- src/azure-cli-core/azure/cli/core/tests/test_aaz_arg.py
- src/azure-cli-core/azure/cli/core/tests/test_aaz_field.py
> [Core] `aaz`: Support camel case key in `AAZObjectType`

- src/azure-cli/azure/cli/command_modules/appservice/_params.py
…or name parameter
Fixes https://github.com/Azure/azure-cli/issues/24822
---
> {App Service} Fix #24822: `az webapp delete`: Fix the command help message

- src/azure-cli-core/azure/cli/core/aaz/__init__.py
- src/azure-cli-core/azure/cli/core/aaz/_arg.py
- src/azure-cli-core/azure/cli/core/aaz/_base.py
- src/azure-cli-core/azure/cli/core/aaz/_command_ctx.py
- src/azure-cli-core/azure/cli/core/aaz/_field_type.py
- src/azure-cli-core/azure/cli/core/aaz/_operation.py
- src/azure-cli-core/azure/cli/core/aaz/_selector.py
- src/azure-cli-core/azure/cli/core/aaz/utils.py
> [Core] `aaz`: Support subresource selector

- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_local_gateway.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
> [Network] `az network vnet-gateway create`: Add parameter `--edge-zone-vnet-id` for local gateway

- src/azure-cli/azure/cli/command_modules/apim/custom.py
- src/azure-cli/azure/cli/command_modules/apim/tests/latest/recordings/test_apim_core_service.yaml
- src/azure-cli/azure/cli/command_modules/apim/tests/latest/test_apim_scenario.py
```
az apim api create --resource-group {} --service-name {} --api-id {} --display-name {} --path {} --service-url {}
```
The subcommand to create a new API in APIM (`az apim api create`) defaults the protocols and api type values to `https` and `http` by default, making the respective flags to be optional. But with support added for websockets, there is a new set of protocols (`ws` / `wss`) and api type (`websocket`) required when adding a new websocket API.
Since both of these can be derived from the service url parameter passed, this PR adds the ability to infer the protocol and api type while still defaulting to the previous behavior if unknown.
resolves #24717
```
az apim api create --resource-group {} --service-name {} --api-id …
```
> [APIM] `az apim api create`: Parse URL to detect Protocol and API type

- scripts/release/rpm/mariner.dockerfile
Cherry pick https://github.com/Azure/azure-cli/pull/24852 to `release` branch.
> {Packaging} Cherry pick #24852: Handle `cm2` in Mariner 2.0 RPM name

- .github/fabricbot.json
Add @bebound as a reviewer to all PR with `CI` label.
Add @yanzhudd as a reviewer to all PR with `AKS` label.
> {CI} Adjust PR review rules

- src/azure-cli-core/setup.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
Fedora Linux (among other distributions) has moved to argcomplete 2.0.0 and older versions of argcomplete are no longer available.
Signed-off-by: Major Hayden 🤠 <major@redhat.com>
---
> {Packaging} Bump argcomplete to 2.0.0

- src/azure-cli/azure/cli/command_modules/synapse/manual/operations/artifacts.py
- src/azure-cli/azure/cli/command_modules/synapse/tests/latest/recordings/test_workspace_package.yaml
- src/azure-cli/azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py
Fix az synapse workspace-package upload bug
https://github.com/Azure/azure-cli/issues/24718
---
> {Synapse} `az synapse workspace-package upload`: Fix bug caused by sdk change

- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
Have trimmed the storage dataplane sdk to include only the versions that are currently being used in CLI. Previously unused packages have been deleted.
https://github.com/Azure/azure-multiapi-storage-python/pull/57
---
> {Packaging} Trim Storage module data plane multiapi sdk

- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
{AKS} Tidy parameter declarations.
---
> {AKS} Tidy parameter declarations

- src/azure-cli/azure/cli/command_modules/eventhubs/_help.py
- src/azure-cli/azure/cli/command_modules/eventhubs/_params.py
- src/azure-cli/azure/cli/command_modules/eventhubs/tests/latest/recordings/test_eventhub_app_group.yaml
- src/azure-cli/azure/cli/command_modules/eventhubs/tests/latest/test_eventhub_namespace_application_group.py
{EventHubs} `az  eventhubs namespace application-group`: `--client-app-group-identifier` doc changes from SASKeyName to NamespaceSASKeyName 
---
> {EventHubs} `az eventhubs namespace application-group`: Change SASKeyName to NamespaceSASKeyName

- .github/fabricbot.json
1. Monitor issue assign to AllyW
2. Monitor PR add reviewer AllyW
> {CI} Adjust monitor rules

- src/azure-cli/azure/cli/command_modules/network/_help.py
az network express-route gateway connection update
Resolves: https://github.com/Azure/azure-cli/issues/24629
---
> {Network} `az network express-route gateway connection update`: Refine help message

- src/azure-cli/azure/cli/command_modules/sql/commands.py
`az sql db threat-policy show`
`az sql db threat-policy show update`
Microsoft.Sql - Declaring deprecation for `az sql db threat-policy` cmds group for version 2.45.0
The following will replace this cmd group:
`az sql db advanced-threat-protection-setting show -g <resource_group> -s <sql_server_name> -n <db_name>`
Displays the current advancedThreatProtectionSettings state for the SQL Database (Enabled or Disabled)
`az sql db advanced-threat-protection-setting update -g <resource_group> -s <sql_server_name> -n <db_name> --state <Disabled/Enabled>`
Updates the current advancedThreatProtectionSettings state for the SQL Database (Enabled or Disabled)
`az sql db threat-policy show -g <resource_group> -s <sql_server_name> -n <db_name>` …
> [SQL] `az sql db threat-policy`: Declaring deprecation for cmd group

- src/azure-cli-core/azure/cli/core/aaz/_field_type.py
- src/azure-cli-core/azure/cli/core/aaz/_field_value.py
- src/azure-cli-core/azure/cli/core/aaz/_operation.py
- src/azure-cli-core/azure/cli/core/tests/test_aaz_field.py
- src/azure-cli-core/azure/cli/core/tests/test_aaz_operation.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
> [Core] `aaz`: Improve generic update arguments to consist with previous behaviors

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/appservice_environment.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_app_service_environment_commands_thru_mock.py
az appservice ase update
Adding two parameters allow-incoming-ftp-connection and allow-remote-debugging to the az appservice ase update command.
This command will enable FTP connections
az appservice ase update -n ase-asedemo-prod-01 -g rg-asedemo-prod-01 --allow-incoming-ftp-connections
This command will enable remote debugging
az appservice ase update -n ase-asedemo-prod-01 -g rg-asedemo-prod-01 --allow-remote-debugging
This command will disable FTP connections
az appservice ase update -n ase-asedemo-prod-01 -g rg-asedemo-prod-01 --allow-incoming-ftp-connections false
This command will disable remote debugging
az appservice ase update -n ase-asedemo-prod-01 -g rg-asedemo-prod-01 --allow-remote-debugging false
[App …
> [App Service] `az appservice ase update`: Add `--allow-incoming-ftp-connections` and `--allow-remote-debugging` parameters

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/waf_policy/custom_rule/_update.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/express_route/port/link/_update.py
az network application-gateway waf-policy custom-rule update
az network express-route port link update
Related to: https://github.com/Azure/aaz-dev-tools/pull/172
---
> {Network} `az network application-gateway waf-policy custom-rule update`: Fix sub-resource selector

- src/azure-cli/azure/cli/command_modules/monitor/_help.py
- src/azure-cli/azure/cli/command_modules/monitor/_params.py
- src/azure-cli/azure/cli/command_modules/monitor/operations/action_groups.py
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_action_groups.py
az monitor action-group test-notifications create
[monitor] BREAKING CHANGE: `az monitor action-group test-notifications create`: Remove notification in resource group and subscription level
---
closed https://github.com/Azure/azure-cli/issues/24809
> [monitor] BREAKING CHANGE: `az monitor action-group`: Remove notification in resource group and subscription level

- src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py
Updated 3rd example of "firewall-rule create" to include --rule-name argument
Updated 3rd example of "firewall-rule create" to include --rule-name argument
Fix for GitHub issue [24757](https://github.com/Azure/azure-cli/issues/24757)
---
> {RDBMS} Updated firewall-rule create Example

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_list_filter.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
`az vm list`
Add az vm list filter for VMSS
close https://github.com/Azure/azure-cli/issues/24609
---
> [Compute] `az vm list`: Add new paramter `--vmss` to support querying VM instances in a specific VMSS

- src/azure-cli/azure/cli/command_modules/storage/operations/blob.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_copy_rehydrate_priority.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_blob_copy_scenarios.py
`az storage blob copy start`
Fix `--tier` when `--destination-blob-type` is `BlockBlob` and inferred from src blob. 
`az storage blob copy start --destination-blob dsttierCool --destination-container {} --source-account-name {} --source-container {} --source-blob srcBlockBlob --destination-blob-type BlockBlob --tier Cool`
[Storage] `az storage blob copy start`: Fix `--tier` to support setting blob tier when copying
---
> [Storage] `az storage blob copy start`: Fix `--tier` to support setting blob tier when copying

- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_assign_backup_policy_to_volume.yaml
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_create_volume_quota_rule.yaml
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_volume_quota_rule_list.yaml
az network vnet subnet create
https://dev.azure.com/azclitools/public/_build/results?buildId=23230&view=results
---
> {CI} `az network vnet subnet create`: Fix failures due to vnet migration

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
[AKS] `az aks create/update`: Add support for KEDA workload auto-scaler
---
> [AKS] `az aks create/update`: Add support for KEDA workload auto-scaler

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/commands.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_cors_credentials.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py
az functionapp cors
This PR allows customers to enable/disable access-control-allow-credentials through the Azure CLI. This is to resolve issue #16478
1. Create an App Service plan (az functionapp plan create -g <resource-group-name> -n <plan-name> --sku S1)
2. Create a function app (az functionapp create -g <resource-group-name> -n <function-app-name> --plan <plan-name> -s <storage-account-name>)
3. Enable the CORS access-control-allow-credentials with `az functionapp cors credentials -g <resource-group-name> -n <function-app-name> --enable true)
4. Disable the CORS access-control-allow-credentials with `az functionapp cors credentials -g <resource-group-name> -n <function-app-name> --enable false)
---
This checklist …
> [App Service] Fix#16478: `az functionapp cors credentials`: Add enable/disable CORS creds command

- .github/fabricbot.json
> {CI} Update milestone from Dec 2022 (2023-01-03) to Jan 2023 (2023-02-07)

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/__cmd_group.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/_create.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/_delete.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/_list.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/_list_mapping.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/_list_nic.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/_show.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/_update.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/_wait.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/probe/_list.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/probe/_show.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_sku.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
az network lb update
Resolves: https://github.com/Azure/azure-cli/issues/25008
---
> [Network] `az network lb update`: Expose parameter `--tags`

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
closes https://github.com/Azure/azure-cli/issues/14694 
closes https://github.com/Azure/azure-cli/issues/21531
az webapp config appsettings set
Adding more details to a parameter based on customer feedback. Linked related GitHub issues.
az webapp config appsettings set -h
---
> {App Service} `az webapp config appsettings set`: Update `--settings` parameter description

- src/azure-cli/azure/cli/command_modules/serviceconnector/_credential_free.py
Fix issue [#24806](https://github.com/Azure/azure-cli/issues/24806)
---
> [Service Connector] Fix #24806: `az webapp connection create mysql-flexible`: Fix mysql connection command with  `--system-identity`

- .github/fabricbot.json
|Label|Command Name|GitHub Account|
|---|---|---|
|app-service-ase|az appservice ase|madsd|
|app-service-authentication|az webapp auth|Hamster-Huey|
|app-service-backup-restore|az webapp config backup|gsethdev|
|app-service-backup-restore|az webapp config snapshot|gsethdev|
|app-service-certs-domains|az appservice domain|yutanglin16|
|app-service-certs-domains|az webapp config ssl|yutanglin16|
|app-service-deployment|az webapp deploy|btardif|
|app-service-general|az appservice list-locations|seligj95|
|app-service-general|az appservice plan|seligj95|
|app-service-general|az webapp browse|seligj95|
|app-service-general|az webapp config|seligj95|
|app-service-general|az webapp connection|seligj95|
|app-service-general|az webapp cors|seligj95|
|app-service-general|az webapp create|seligj95| …
> {CI} Update appservice routing rules

- .github/fabricbot.json
> {CI} Fix #25052: Using the wrong operator, change `or` to `and`

- src/azure-cli/azure/cli/command_modules/vm/_help.py
> {Compute} Add example for creating a VM by attaching to an unmanaged operating disk

- src/azure-cli-testsdk/azure/cli/testsdk/scenario_tests/base.py
> {testsdk} Recording into temp file first when live test run and replace the old recording file after test run success

- src/azure-cli/azure/cli/command_modules/network/_help.py
- src/azure-cli/azure/cli/command_modules/network/commands.py
- src/azure-cli/azure/cli/command_modules/network/operations/__init__.py
- src/azure-cli/azure/cli/command_modules/network/operations/load_balancer.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_cross_region_lb.yaml
> {Network} `az network cross-region-lb`: Migrate commands to codegen v2

- .github/fabricbot.json
> {CI} Update funtionsapp mentionees

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/_update.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_probes.yaml
az network lb probe
Fixes: https://github.com/Azure/azure-cli/issues/25086
---
> [Network] Fix #25086: `az network lb probe`: Expose parameter `--probes`

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/_update.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_probes.yaml
> {Network} `az network lb probe`: Revert exposing parameter `--probes`

- src/azure-cli-core/azure/cli/core/aaz/_arg_action.py
- src/azure-cli-core/azure/cli/core/tests/test_aaz_arg.py
> [Code] `aaz`: Support `AAZListArg` singular options list

- src/azure-cli-core/azure/cli/core/aaz/__init__.py
- src/azure-cli-core/azure/cli/core/aaz/_arg.py
- src/azure-cli-core/azure/cli/core/aaz/_arg_fmt.py
- src/azure-cli-core/azure/cli/core/tests/test_aaz_arg_fmt.py
> [Core] `aaz`: Support AAZFileArg

- doc/telemetry/README.md
- doc/telemetry/faq.md
- doc/telemetry/kusto_examples.md
We have already migrate telemetry docs to engineering hub, so remove the internal links in public docs
---
> {Doc} Remove all internal links in telemetry doc

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
az webapp create-remote-connection
This PR fixes the ssh bug for azure app service webapps
Used the azdev tool to test the command.
---
> [App Service] `az webapp create-remote-connection`: Update the host address of SSH tunnel from 0.0.0.0 to 127.0.0.1

- src/azure-cli/azure/cli/command_modules/network/aaz/2018_03_01_hybrid/network/vnet/peering/__cmd_group.py
- src/azure-cli/azure/cli/command_modules/network/aaz/2019_03_01_hybrid/network/vnet/peering/__cmd_group.py
- src/azure-cli/azure/cli/command_modules/network/aaz/2020_09_01_hybrid/network/vnet/peering/__cmd_group.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/__cmd_group.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/route_filter/__cmd_group.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/route_filter/rule/__cmd_group.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/security_partner_provider/__cmd_group.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/virtual_appliance/__cmd_group.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/virtual_appliance/site/__cmd_group.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/virtual_appliance/sku/__cmd_group.py
> {network} `az network`: Fix command-groups in aaz

- src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_general_arm_cmd.yaml
- Cleanup of test recording
- Testing the Batch module is described in the [README.md](https://github.com/Azure/azurecli/blob/dev/src/azurecli/azure/cli/command_modules/batch/tests/latest/README.md)
[Batch] test recording cleanup
---
> {Batch} test recording cleanup

- src/azure-cli/azure/cli/command_modules/vm/_help.py
Fixes https://github.com/Azure/azure-cli/issues/25201
---
> {Compute} Fix #25201: Fix a spelling mistake in 'az vm --help' command

- .github/fabricbot.json
> {CI} Update milestone from Jan 2023 (2023-02-07) to Feb 2023 (2023-03-07)

- src/azure-cli/azure/cli/command_modules/network/_client_factory.py
- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/public_ip/_create.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/public_ip/_delete.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/public_ip/_list.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/public_ip/_show.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/public_ip/_update.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/public_ip/_wait.py
- src/azure-cli/azure/cli/command_modules/network/commands.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_public_ip_ddos_settings.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Resolves: https://github.com/Azure/azure-cli/issues/24968
---
> [Network] `az network public-ip create`: Add parameter `--ddos-protection-plan`

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/nsg/rule/_create.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_extended_nsg.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
az network nsg rule create
Fixes: https://github.com/Azure/azure-cli/issues/25181
---
> [Network] Fix #25181: `az network nsg rule create`: Use `*` as default value for protocol

- src/azure-cli/azure/cli/command_modules/sql/_help.py
az sql mi list
The doc is wrong
Its a doc. proofread it.
---
> {SQL} az sql mi list fixed example about moving managed instances to a different subnet

- src/azure-cli/azure/cli/command_modules/vm/_help.py
- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_trusted_launch_os_disk_secure_upload.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
`az disk create`
Issue - close: https://github.com/Azure/azure-cli/issues/25308
---
> [Compute] Fix #25308: `az disk create`: Fix help message for creating a standard disk for uploading blobs

- src/azure-cli/azure/cli/command_modules/vm/_help.py
{VM} Fix extension image list-versions example
`az vm extension image list-versions`
Update example of az vm extension image list-versions 
Fixes GitHub issue [24943](https://github.com/Azure/azure-cli/issues/24943)
---
> {VM} Fix extension image list-versions example

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
az webapp create
az functionapp create
az webapp vnet-integration add
To meet Vanguard security requirements and enforce Azure Policy compliance we need to move certain site config properties to site properties. Customers should not be affected by this change and behavior should not change.
{App Service} `az webapp create` Move route all to use site property
{App Service} `az functionapp create` Move route all to use site property
{App Service} `az webapp vnet-integration add` Move route all to use site property
---
> {App Service} `az webapp create`, `az functionapp create`, `az webapp vnet-integration add` Move route all to use site property

- src/azure-cli/azure/cli/command_modules/iot/_help.py
- src/azure-cli/azure/cli/command_modules/iot/commands.py
- src/azure-cli/azure/cli/command_modules/iot/tests/latest/recordings/test_hub_wait.yaml
- src/azure-cli/azure/cli/command_modules/iot/tests/latest/test_iot_commands.py
`az iot hub wait`
`az iot hub delete --no-wait`
Fix issue with `az iot hub delete --no-wait`. Add `az iot hub wait`.
Added test `test_hub_wait`.
[IoT] `az iot hub wait`: Add wait commands
[IoT] `az iot hub delete`: Fix functionality issue for parameter `--no-wait` 
---
> [IoT] `az iot hub wait`: Add wait commands

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_with_max_surge.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Add max surge in vmss rolling upgrade policy configurability
close https://github.com/Azure/azure-cli/issues/24846
---
> [Compute] `az vmss create`: Add new parameter `--max-surge` to support enabling rolling upgrade policy max surge

- doc/extensions/authoring.md
n/a
Minor typo in a doc.
n/a
---
> {Doc} Fix Minor Typo in Sample Command

- src/azure-cli/azure/cli/command_modules/sql/_params.py
- src/azure-cli/azure/cli/command_modules/sql/custom.py
az sql db ltr-backup restore
az sql db geo-backup restore
Added new SLO parameter that was missing
az sql db ltr-backup restore \
--dest-database targetdb --dest-server myserver --dest-resource-group mygroup \
**--service-level-objective SQLDB_HS_Gen5_2**--backup-id "/subscriptions/6caa113c-794c-42f8-ab9d-
878d8aa104dc/resourceGroups/mygroup/providers/Microsoft.Sql/locations/southeastasia/longTerm
RetentionServers/myserver/longTermRetentionDatabases/sourcedb/longTermRetentionBackups/3214b
3fb-fba9-43e7-96a3-09e35ffcb336;132292152080000000"
---
This checklist …
> [SQL] `az sql db geo/ltr-backup restore`: Add service objective parameter to ltr restore and geo restore

- src/azure-cli/azure/cli/command_modules/rdbms/_params.py
- src/azure-cli/azure/cli/command_modules/rdbms/validators.py
```sh
az mysql flexible-server firewall-rule create/show/update/delete
```
The docs, help text, and error message for the firewall rule name doesn't mention the minimum length required. This PR updates the description to include it.
resolves #25337
```sh
az mysql flexible-server firewall-rule create/show/update/delete --help
```
---
> {RDBMS} Update firewall rule name description to clarify constraints

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/commands.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
`webapp config backup delete` is the new command introduced with this PR
The new command enables customers to delete a backup by id
List the web app backups by using the command `az webapp config backup list`
Sample commands :
For the app : `az webapp config backup list -g test_group --webapp-name test-container-appa`
For the app's slot : `az webapp config backup list -g test_group --webapp-name test-container-appa -s dev`
Pick an an backup from the list and delete the backup using the command `az webapp config backup delete`
For the app : `az webapp config backup delete -g test_group --webapp-name test-container-appa --backup-id 89215`
For the app's slot : `az webapp config backup delete -g test_group --webapp-name test-container-appa …
> [App Service] `az webapp config backup delete`: Add new command to delete a backup of the webapp

- .github/CODEOWNERS
- src/azure-cli/azure/cli/command_modules/servicebus/_params.py
- src/azure-cli/azure/cli/command_modules/servicebus/custom.py
Manually merge `dev` into `release`
---
> {ServiceBus} Change expiration version to next breaking change window

- src/azure-cli/azure/cli/command_modules/acs/_help.py
`az aks nodepool update`
Update help message to show how to delete node taints. Cherry-pick the change from PR [#25116](https://github.com/Azure/azure-cli/pull/25116).
---
> {AKS} `az aks nodepool update`: Add doc line on how to delete node taints

- src/azure-cli/azure/cli/command_modules/network/_format.py
> [Network] `az network nsg rule list`: Fix `-o table` cannot be used

- src/azure-cli/azure/cli/command_modules/network/_format.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_nsg.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
az network nsg rule list
continued fix of https://github.com/Azure/azure-cli/pull/25387 
---
> {Network} `az network nsg rule list`: Fix `-o table` cannot be used

- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_deleted_restore_to_existing_site.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_deleted_restore_to_non_existent_site.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_deleted_restore_to_non_existent_site_fails_when_asp_argument_is_not_provided_or_does_not_exist.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
- src/azure-cli/azure/cli/command_modules/appservice/utils.py
az webapp deleted restore
Changes are to improve the deleted restore experience and also to ensure the consistent behavior with PowerShell : https://learn.microsoft.com/en-us/azure/app-service/app-service-undelete
https://github.com/Azure/azure-powershell/blob/main/src/Websites/Websites/Cmdlets/BackupRestore/RestoreAzureDeletedWebApp.cs
---
> [App Service] `az webapp deleted restore`: Add new parameter `--target-app-svc-plan` to support setting app service plan for new azure web app

- build_scripts/windows/scripts/build.cmd
- scripts/release/debian/Dockerfile
- scripts/release/debian/build.sh
Close https://github.com/Azure/azure-cli/issues/25246. As  [jiasli commented](https://github.com/Azure/azure-cli/issues/25246#issuecomment-1427539476), Python 3.10.9 fixes CVE-2022-37454
---
> {Packaging} Bump Python version to 3.10.10

- scripts/ci/cmdcov.yml
Moved the CLI command test coverage configuration to the azure-cli repository to avoid releasing a new version for the package when there is any change.
> {CI} Move CLI command test coverage config to azure-cli repo

- src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_link_endpoint_monitor_accounts_registry.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
az network vnet create
Added support to manage Private Endpoint of Microsoft.Monitor accounts with Azure CLI.
---
> [Network] `az network private-endpoint-connection`: Add Provider Microsoft.Monitor/Accounts

- src/azure-cli/azure/cli/command_modules/serviceconnector/_credential_free.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/_utils.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/custom.py
> {Service Connector} `az webapp connection create sql`: auto install extension `serviceconnector-passwordless`

- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Bump `virtual-wan` extension api version
---
> {Network} Decouple with `virtual-wan` bump API version

- src/azure-cli/azure/cli/command_modules/eventhubs/_params.py
- src/azure-cli/azure/cli/command_modules/eventhubs/custom.py
az eventhubs eventhub create
az eventhubs eventhub update
We would be deprecating this parameter in a future release
---
> {EventHubs} `az eventhubs eventhub`: Add deprecation message to `--message-retention-in-days` 

- src/azure-cli/azure/cli/command_modules/sql/_params.py
- src/azure-cli/azure/cli/command_modules/sql/custom.py
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_instance_failover_group_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
az sql instance-failover-group create
az sql instance-failover-group update
This PR adds a new optional parameter `--secondary-type` to the create and update instance failover group commands. This enables users to designate the type of their secondary managed instance in an instance failover group. Standby type means that the instance is used as a passive replica for disaster recovery only, while Geo means that the instance is used for workloads.
This PR also updates the descriptions for `--location` and `--resource-group` parameters for the az sql instance-failover-group set-primary command to better explain the parameter usage.
`az sql instance-failover-group create -n ifgName -g rgName --mi primaryInstanceName …
> [SQL] `az sql instance-failover-group`: Add `--secondary-type` parameter to create and update commands

- src/azure-cli/azure/cli/command_modules/sql/_params.py
az sql midb restore
Add tags support for managed database restore command.
---
> [SQL] `az sql midb restore`: Add tags parameter

- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/_params_azure_stack.py
- src/azure-cli/azure/cli/command_modules/storage/_validators.py
- src/azure-cli/azure/cli/command_modules/storage/operations/account.py
- src/azure-cli/azure/cli/command_modules/storage/tests/hybrid_2019_03_01/recordings/test_storage_account_service_endpoints.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/hybrid_2020_09_01/recordings/test_storage_account_service_endpoints.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_service_endpoints.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
`az storage account network-rule add`
`az storage account network-rule remove`
Fix [#25402](https://github.com/Azure/azure-cli/issues/25402)
Support adding and removing multiple IP addresses in one command.
`az storage account network-rule add -g {rg} -n {sa} --ip-address {ip} {ip2} {ip3}`
`az storage account network-rule remove -g {rg} -n {sa} --ip-address {ip} {ip2} {ip3}`
[Storage] Fix #25402: `az storage account network-rule`: Support adding and removing multiple IPs
---
> [Storage] Fix #25402: `az storage account network-rule`: Support adding and removing multiple IPs

- src/azure-cli/azure/cli/command_modules/sql/_help.py
- src/azure-cli/azure/cli/command_modules/sql/_params.py
- src/azure-cli/azure/cli/command_modules/sql/custom.py
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_mi_zone_redundancy.yaml
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
`az sql mi create`
`az sql mi update`
Added --zone-redundant parameter to sql mi create and sql mi update operations that allow for creating zone-redundant managed instances and updating existing ones by enabling/disabling zone redundancy. This works currently only on the business-critical edition of managed instances and on locations that support zone redundancy.
`sql mi create -g resourceGroup1 -n managedInstance1 -l westeurope '
'-u username1 -p password1 --subnet subne1 --capacity 8 '
'--storage 64 --edition BusinessCritical --zone-redundant True`
`sql mi update -g resourceGroup1 -n managedInstance1 --zone-redundant false`
[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking …
> [SQL] `az sql mi create/update`: Add `--zone-redundant` to support zone redundancy

- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_ag_rule_default_exists.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
az network application-gateway rule create
Fix: https://github.com/Azure/azure-cli/issues/25408
---
> [Network] Fix #25408: `az network application-gateway rule create`: Creation fails with `--redirect-config` when there are multiple pools

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/nic/ip_config/_update.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_multiple_ipconfigs_update_with_asg.yaml
az network nic ip-config update
It's a potential bug introduced by my previous migration: https://github.com/Azure/azure-cli/pull/25498.
Related model fix: https://github.com/Azure/aaz/pull/126
---
> {Network} `az network nic ip-config update`: All IP configurations must belong to the same ASGs

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_and_update_ipv6_count.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_dualstack_with_default_network.yaml
> {AKS} Update recordings

- .azure-pipelines/templates/automation_test.yml
- scripts/ci/automation_full_test.py
1. Add pull request number to test result json file, becasue github check run event send error pull request number when we create PR from fork repo
2. Rename test_results_{instance_idx}.x.xml to test_results_{python_version}_{profile}_{instance_idx}.x.xml, because test_results_{instance_idx}.x.xml is not unique
---
> {CI} Upload test result xml file to ADO artifacts

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/private_endpoint/_create.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/private_link_service/_create.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_private_endpoint_edge_zone.yaml
> {Network} `az network private-link-service/private-endpoint`: Fix the issue when using `--edge-zone`

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
{webapps} Fix typo in `az webapp deploy` cmdlet. 
Fixes [GitHub Issue 25613](https://github.com/Azure/azure-cli/issues/25613)
---
> {App Service} Fix typo in webapp deploy

- src/azure-cli/azure/cli/command_modules/resource/_params.py
Update policy assignment parameter descriptions and requirements for clarity.
az policy assignment *
Updating help/descriptions [only] based on customer feedback to clarify parameter defaults and requirements. In particular, customers were confused how all parameters to az policy assignment create could be optional (however, this is actually the case).
Requires full release and docs publishing pipeline to run before it can be tested.
---
> {ARM} `az policy assignment`: Change policy assignment parameter descriptions

- src/azure-cli/azure/cli/command_modules/apim/custom.py
`az apim update --name --resource-group --public-network-access`
Fix apim update cmdlet to successfully enable/disable public_network_access for true/false
Fixes [GitHub Issue 25168](https://github.com/Azure/azure-cli/issues/25168)
---
> [APIM] Fix #25168: `az apim update`: Fix the bug that `--public-network-access` doesn't work to disable public network access

- scripts/ci/credscan/CredScanSuppressions.json
- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_ssl_specify_hostname.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
`az webapp config ssl bind`
`az webapp config ssl unbind`
See title. The current implementation uses some complex logic to identify the hostnames to bind/unbind. This change keeps that behavior as the default, but lets the user specify the hostname if they would like. 
Fixes https://github.com/Azure/azure-cli/issues/18490 
Fixes https://github.com/Azure/azure-cli/issues/9804
`azdev test test_webapp_ssl_specify_hostname`
---
> [App Service] `az webapp config ssl bind/unbind`: Allow user to specify hostname to (un)bind with `--hostname`

- src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_mysql_flexible_server.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_link_resource_flexible_server.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_link_resource_mysql_flexible_server.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
> [Network] `az network private-endpoint-connection`: Add provider `Microsoft.DBforMySQL/flexibleServers`

- src/azure-cli/azure/cli/command_modules/sql/_params.py
az sql db
Made help clearer about what service objective applies to.
Tested that the new help text appears.
> {SQL} Update help text for ltr/geo restore params

- src/azure-cli-core/azure/cli/core/telemetry.py
- src/azure-cli/azure/cli/command_modules/vm/_validators.py
- src/azure-cli/azure/cli/command_modules/vm/_vm_utils.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
When there is a recommended region for the region used by customers, it will recommend the better region to users through a warning log
Support using `az config set core.display_region_identified=false` to disable the warning log
Run command: `az vm create -n zhoxing-test -g zhoxing-test --nsg-rule NONE --image SLES --location westeurope --public-ip-sku Standard --security-type TrustedLaunch`
---
> [Compute] `az vm create`: Support recommending more suitable regions through warning log when creating VM

- src/azure-cli/azure/cli/command_modules/eventgrid/_params.py
`az eventgrid domain create`
Push back the deprecation version as `2.46.0` doesn't allow breaking change
---
> {Eventgrid} Change deprecation version

- .github/fabricbot.json
> {CI} Update milestone from Feb 2023 (2023-03-07) to March 2023 (2023-04-04)

- src/azure-cli/azure/cli/command_modules/synapse/manual/commands.py
Make synapse module GA. Synapse service is already GA.
---
> {Synapse} Update Synapse module GA

- .github/fabricbot.json
> {Fabric Bot} Update mentions for Compute services

- .github/CODEOWNERS
Adding the logins of the folks who will be notified of service attention issues.
---
> {Code Owner} Add code owner for VM module

- src/azure-cli/azure/cli/command_modules/acs/_params.py
For the system nodepool created when creating the AKS cluster, it must be a linux nodepool. Could add a windows nodepool after the cluster is created via `az aks nodepool add`. See doc [Create a Windows Server container on an AKS cluster by using Azure CLI - Azure Kubernetes Service | Microsoft Learn](https://learn.microsoft.com/en-us/azure/aks/learn/quick-windows-container-deploy-cli#add-a-windows-node-pool).
---
> {AKS} `az aks create`: Correct help message for option `--os-sku`

- scripts/live_test/CLITest.yml
- scripts/live_test/sendemail.py
Live test job running longer than the maximum time of 180 minutes.
At the same time, the total running time of the live test exceeds 16 hours.
Therefore make the following changes:
1. Modify the maxParallel to 30 (the original value is 5)
2. Modify the maximum time of SendEmail to 360 minutes
3. In order not to affect the task of sending emails, the task of cleaning up resources is separated out.
---
> {CI} Fix live test job running longer than the maximum time of 180 minutes.

- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
These dependencies are introduced by service connector, the related commands have been moved to `serviceconnector-passwordless` extension.
Remove these dependencies to reduce package size.
---
> {Packaging} Remove pyodbc, PyMySQL, psycopg2 from dependency

- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/routeserver/_create.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/routeserver/_delete.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/routeserver/_show.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/routeserver/_update.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/routeserver/_wait.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_virtual_hub_router_scenario.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Resolve: https://github.com/Azure/azure-cli/issues/25213
---
> [Network] `az network routeserver create/update`: Add parameter `--hub-routing-preference`

- scripts/live_test/sendemail.py
Send email raise error:
Recently azure-communication-email service released a new version, there are many breaking changes, so the send email method needs to be updated.
---
> {CI} Fix send email due to breaking change of azure-communication-email service

- src/azure-cli/azure/cli/command_modules/netappfiles/custom.py
az netappfiles volume update
Fix an issue where Volumes DataProtectionProperties properties snapshotPolicyId was not getting updated in PATCH operation
ICM=370786355
---
> [NetAppFiles] Patch assign snapshotpolicyID

- build_scripts/windows/scripts/build.cmd
Remove this help file and saves 2.52 MB disk space.
---
> {Packaging} Remove PyWin32.chm from MSI

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/waf_policy/custom_rule/_create.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/waf_policy/custom_rule/_delete.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/waf_policy/custom_rule/_list.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/waf_policy/custom_rule/_show.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/waf_policy/custom_rule/_update.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_waf_custom_rule.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_waf_policy_with_application_gateway.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Resolve: https://github.com/Azure/azure-cli/issues/25426
[Network] BREAKING CHANGE: `az network application-gateway waf-policy custom-rule`: Rename output property `applicationGatewayIpConfigurations` to `applicationGatewayIPConfigurations` to keep consistent with the name in API
---
> [Network] `az network application-gateway waf-policy custom-rule create/update`: Add parameter `--state`

- scripts/live_test/sendemail.py
> {CI} Fix missing details page when sending live test report

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/commands.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_abort.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_nodepool_abort.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
`aks`
GA'ing the abort feature for AKS on managed cluster, and agentpool.
This PR is simply porting over the following PR from preview:
https://github.com/Azure/azure-cli-extensions/pull/5271
The following changes were made in the conversion from preview to GA:
1. I updated the get_models logic (seems in alignment) with the GA repo
2. removed --aks-custom-headers from both the nodepool, and mc abort operations, as its unneeded for the command, and trimming aware the CLI to be as sleek as possible for GA makes sense to me, even if its breaking between preview and GA
3. abort_latest_operation didn't exist on the client, so switched to begin_abort_latest_operation
4. removed `--nodepool-name` param from the nodepool abort, since its already handled by the …
> [AKS] `az aks operation-abort` and `aks nodepool operation-abort`: Add aks, and nodepool `operation-abort` commands

- scripts/release/rpm/azure-cli.spec
`azure-mgmt-network` is removed in https://github.com/Azure/azure-cli/pull/25451 and `site-packages/azure/mgmt/network/` does not exist anymore.
New trim method is in https://github.com/Azure/azure-cli/pull/25801
---
> {Packaging} Remove trim `azure-mgmt-network` in RPM build

- .azure-pipelines/templates/automation_test.yml
- .azure-pipelines/templates/azdev_setup.yml
- scripts/live_test/CLITest.yml
> {Test} Enable compact aaz in CI tests

- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_private_link_service.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Fix: https://github.com/Azure/azure-cli/issues/25784
---
> [Network] Fix #25784: `az network private-link-service update`: `--lb-frontend-ip-configs` cannot be used

- src/azure-cli/azure/cli/command_modules/appconfig/_kv_helpers.py
`az appconfig kv import --source file`
Related to [Issue 725](https://github.com/Azure/AppConfiguration/issues/725) where the case of boolean values may be changed during string conversion.
[App Config] `az appconfig kv import`: Ensure the case of imported boolean values does not change for string conversion from file
---
> [App Config] Ensure the case of imported boolean values does not change for string conversion from file

- .github/azure-client-tools-bot/config.yml
- .github/fabricbot.json
* Auto choose milestone for issue or pull request
* If the current milestone time is more than expected days (7 days), auto set in current milestone.
* If the current milestone time is less than expected days (7 days):
1. If next milestone exist, auto set in next milestone and reminder user.
2. If next milestone not exist, auto set in current milestone and reminder user.
---
> {CI} Auto manage milestone

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Add a new test case `test_aks_update_attach_acr` to help guard no behavioral changes related to role assignments. More details refer to PR [#25908](https://github.com/Azure/azure-cli/pull/25908).
---
> {AKS} Added test case to detect behavioral changes in role assignments

- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/operations/account.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_create_storage_account_with_dns_endpoint_type.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
`az storage account create`: Add `--dns-endpoint-type` to support partitioned DNS account
This was supported in https://github.com/Azure/azure-cli-extensions/pull/4664 for preview and now it's time to GA
`az storage account create -n $accountName -g $rgName --dns-endpoint-type AzureDnsZone`
---
> [Storage] `az storage account create`: GA partition DNS account support

- .github/azure-client-tools-bot/config.yml
- .github/fabricbot.json
1. Auto manage milestone for pull request
2. Revert auto manage milestone for issue
---
> {CI} Auto manage milestone for pull request

- .github/azure-client-tools-bot/config.yml
support branch check for pull request
---
> {CI} Support check pull request branch

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
`az webapp config ssl import`
Fixes #25876 
---
> [App Service] Fix #25876: `az webapp config ssl import`: Fix the UnboundLocalError `local variable 'cert_name' referenced before assignment`

- src/azure-cli/azure/cli/command_modules/resource/_params.py
az policy
Update to descriptions to clarify parameter usage.
Validate that web documentation gets updated as expected.
---
> {ARM} `az policy assignment create`: Update parameter descriptions to clarify usage

- .github/CODEOWNERS
N/A
This PR updates the code owners of the app configuration command module in azure CLI.
{App Config} Updating app configuration code owners
---
> {App Config} Updating app configuration code owners.

- src/azure-cli/azure/cli/command_modules/resource/custom.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_custom.py
az bicep format
Fix bug
https://github.com/Azure/azure-cli/issues/25706
---
> [ARM] Fix #25706: `az bicep format`: Fix the TypeError `ensure_bicep_installation() missing 1 required positional argument 'cli_ctx'`

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/_validators.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/linter_exclusions.yml
- src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_with_image_cleaner_enabled_with_default_interval_hours.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_with_image_cleaner_enabled_with_interval_hours.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_update_with_image_cleaner.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_validators.py
```
az aks create --subscription $SUB_ID \
-n $CLUSTER_NAME \
-g $RG_NAME \
--enable-image-cleaner \
--image-cleaner-interval-hours 48
az aks update --subscription $SUB_ID \
-n $CLUSTER_NAME \
-g $RG_NAME \
--disable-image-cleaner
```
This PR aims to add az cli changes to support Image Cleaner GA features.
[AKS] `az aks create/update`: Add new parameter `--enable-image-cleaner` to enable Image Cleaner service
[AKS] `az aks create/update`: Add new parameter `--image-cleaner-interval-hours` to set Image Cleaner scanning interval
---
> [AKS] `az aks create/update`: Add Image Cleaner related options

- src/azure-cli/azure/cli/command_modules/acs/_consts.py
- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_with_overlay_network_plugin_mode.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
Graduating `network-plugin-mode` to GA to support Azure CNI Overlay GA.
The parameter was added to aks-preview in https://github.com/Azure/azure-cli-extensions/pull/4855.
More information about CNI Overlay can be found at https://aka.ms/aks/azure-cni-overlay
Live test added to create an overlay cluster with `az aks create -n myCluster -g myRG --network-plugin azure --network-plugin-mode overlay`
[AKS] `az aks create`: Add new parameter `--network-plugin-mode` to support creating Azure CNI Overlay clusters
---
> [AKS] `az aks create`: Add new parameter `--network-plugin-mode` to support creating Azure CNI Overlay clusters

- src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_with_paid_sku.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_with_paid_sku_msi.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_with_standard_sku.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
- `az aks update`
Adopt new sku naming since API version 2023-02-01 (see [rest-api-specs](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-02-01/managedClusters.json#L4863)).
- Change sku.name from `Basic` to `Base`.
- Change the value `Paid` in sku.tier to `Standard`.
---
> {AKS} `az aks create/update`: Adopt new sku naming

- .github/fabricbot.json
Add @FumingZhang to aks pull request reviewer
---
> {CI} Update fabricbot.json for aks pull request

- src/azure-cli/azure/cli/command_modules/cognitiveservices/custom.py
`az cognitiveservices account create`
Remove Face attestation and Bing notice.
`az cognitiveservices account create` will no longer show Face attestation and Bing notice.
{CognitiveServices} `az cognitiveservices account create` will no longer show Face attestation and Bing notice.
---
> {CognitiveServices} Remove Face attestation and Bing notice.

- scripts/trim_sdk.py
Trim all sdk in `trim_sdk.py`. This should save 5M disk space.
Before:
After:
--------
Live test result does not change much after this PR.
This: Pass: 2547, Fail: 515, Pass rate: 83.18%
dev: Pass: 2510, Fail: 550, Pass rate: 82.03% 
---
> {Packaging} Trim all SDKs instead of biggest SDKs

- .github/workflows/AddIssueComment.yml
- .github/workflows/AddPRComment.yml
Note: In public repositories this action does not work in pull_request workflows when triggered by forks. 
Any attempt will be met with the error, resource not accessible by integration. 
This is due to token restrictions put in place by GitHub Actions. 
Private repositories can be configured to [enable workflows](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#enabling-workflows-for-forks-of-private-repositories) from forks to run without restriction. 
See [here](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#restrictions-on-repository-forks) for further explanation. 
Alternatively, …
> {CI} Add auto reply for issue and pull request

- .github/fabricbot.json
> [FabricBot] Update mentions for Azure Deployments team

- src/azure-cli-core/azure/cli/core/telemetry.py
az interative
Create a new field under ”properties“ to store cli recommendation feedback information.
---
> {Telemetry} Add recommendation property to Telemetry

- src/azure-cli/azure/cli/command_modules/advisor/custom.py
`az advisor recommendation list`
Fixes error while executing az advisor recommendation list cmdlet.
Fixes [25657](https://github.com/Azure/azure-cli/issues/25657)
`az advisor recommendation list --category Cost --refresh`
---
> {advisor} Bug fix recommendation list

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_azure_cni_overlay_migration.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
Adds `--network-plugin` and `--pod-cidr` to the aks update command to support migrating an existing
cluster to CNI Overlay.
To update an existing Azure CNI Cluster to Overlay, run the following command:
`az aks update -n myCluster -g myRG --network-plugin-mode overlay --pod-cidr $POD_CIDR`
where $POD_CIDR is an IP range that does not overlap with the cluster's VNet IP space.
[AKS] `az aks update`: Add prameter `--network-plugin-mode` to update the mode of a network plugin
[AKS] `az aks update`: Add prameter `--pod-cidr` to update the pod CIDR for a cluster
---
> [AKS] `az aks update`: Add parameters `--network-plugin-mode` and `--pod-cidr` to Update command to support migrating to Azure CNI Overlay

- .github/fabricbot.json
1. Modify ARM regex pattern
2. Add functionapp pull request responder workflow
3. Modify eventhubs workflow to add label `Event Hubs`
---
> {CI} Update fabricbot.json for `ARM Functionapp EventHubs`

- .github/fabricbot.json
-  `az ts/bicep/private-link` route to CXP team
---
> {CI} Update fabricbot.json for arm

- .github/fabricbot.json
The following modules are involved:
Compute
Monitor
Network
KeyVault
Account
Storage
RBAC
ARM
Interactive
Upgrade
Configure
Portal
Managed Identity
Backup
---
> {CI} Update fabricbot.json to add `Azure CLI Team` and `question` label

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Fix space problem for some test commands in several test cases.
---
> {AKS} Fix space problem in test case

- src/azure-cli/azure/cli/command_modules/network/operations/watcher.py
> {Network} `az network watcher flow-log update`: Fix 'NoneType' object has no attribute 'resource'

- src/azure-cli/azure/cli/command_modules/acs/tests/hybrid_2020_09_01/test_custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_custom.py
> Fix aks install cli test 0407

- src/azure-cli/azure/cli/command_modules/resource/_validators.py
`az resource lock create`
Refine error message for parameter validation
---
> {ARM} `az resource lock create`: Refine error message for parameter validation

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/commands.py
Fix issue for command `az functionapp deployment user show`, currently it's failing. 
Related issues https://github.com/Azure/azure-cli/issues?q=is%3Aissue++%22AttributeError%3A+%27function%27+object+has+no+attribute+%27metadata%27%22
Fix issue for command `az functionapp deployment user show`, currently it's failing. 
N/A
---
> [App Service] Fix #25642: `az functionapp deployment user show`: Fix the AttributeError `'function' object has no attribute 'metadata'`

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_node_public_ip.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_slb_vmss_with_outbound_ip_prefixes_then_update.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_slb_vmss_with_outbound_ip_prefixes_then_update_msi.yaml
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/public_ip/prefix/_create.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/public_ip/prefix/_delete.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/public_ip/prefix/_list.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/public_ip/prefix/_show.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/public_ip/prefix/_update.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/public_ip/prefix/_wait.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_natgateway_basic.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_front_ip.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_load_balancer_outbound_rules.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_public_ip_prefix.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_public_ip_prefix_edge_zone.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_public_ip_prefix_with_ip_address.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_public_ip_prefix_with_ip_tags.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_public_ip_prefix_zone.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
> [Network] `az network public-ip prefix create`: Add parameter `--ip-tags`

- src/azure-cli/azure/cli/command_modules/network/operations/load_balancer.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_cross_region_lb_rules.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
> [Network] `az network cross-region-lb rule create`: Set default value for `--enable-tcp-reset` and `--idle-timeout`

- .github/fabricbot.json
> {CI} Fabric bot support routing `az artifacts`

- .github/CODEOWNERS
Add me as code owner for `/scripts/`
---
> {Misc.} Update CODEOWNERS 

- src/azure-cli/azure/cli/command_modules/vm/custom.py
Fix: https://github.com/Azure/azure-cli/issues/26118
---
> [VM] Fix #26118: `az vm list-ip-addresses`: KeyError when attributes missing in public IP address

- .github/fabricbot.json
> {CI} Fabric bot support route `az k8s-configuration`

- src/azure-cli/azure/cli/command_modules/vm/_params.py
az vm/vmss create/update`
Issue - close: #25987
---
> {Compute} `az vm/vmss create/update`: GA parameters `--ephemeral-os-disk` and `--ephemeral-os-disk-placement`

- src/azure-cli/azure/cli/command_modules/resource/_help.py
> {ARM} `az deployment group create`: Add example for cross tenant deployment

- src/azure-cli/azure/cli/command_modules/apim/_params.py
`az apim product create`
Update approval_required parameter description.
Fixes [26012](https://github.com/Azure/azure-cli/issues/26012)
---
> {APIM} Update parameter description

- src/azure-cli/azure/cli/command_modules/servicebus/_params.py
- src/azure-cli/azure/cli/command_modules/servicebus/commands.py
- src/azure-cli/azure/cli/command_modules/servicebus/custom.py
We will change the format of this command in Future release. the parameter `vnet-name` will be deprecated in future.
We will offer simultaneous addition and removal of multiple IP rules and subnet rules with the new future release cmdlets.
We are targeting these breaking change in this May breaking change cycle.
We will Replace the following command.
1. `az servicebus namespace network-rule` with `az servicebus namespace network-rule-set`
2. `az servicebus namespace network-rule add` with `az servicebus namespace network-rule-set ip-rule add`, `az servicebus namespace network-rule-set virtual-network-rule add`
3. `az servicebus namespace network-rule remove` with `az servicebus namespace network-rule-set ip-rule remove`, `az servicebus namespace …
> {ServiceBus} Add Breaking change message for `az servicebus namespace network-rule` cmdlets

- .github/fabricbot.json
> {CI} Fabric bot support routing `az eventhubs`

- src/azure-cli/azure/cli/command_modules/vm/custom.py
`az vmss update`
Issue - close: #26164
---
> [Compute] Fix #26164: `az vmss update`: Fix unexpected error while running the update instance protection command on VMSS flex instances

- src/azure-cli/azure/cli/command_modules/vm/custom.py
`az sig update`
Issue - Close: #26185
---
> [Compute] Fix #26185: `az sig update`: Fix issues that `is_soft_delete_enabled` may not exist

- src/azure-cli/azure/cli/command_modules/vm/_vm_utils.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
`az vm/vmss create`
`az disk create`
---
> {Compute} `az vm/vmss create`: Update notification message for Trusted Launch by default

- src/azure-cli/setup.py
There's breaking change in version `10.1.0b2`. So lock the version to `10.1.0.b1`.
---
> {Container} Lock `azure-mgmt-containerinstance` to version 10.1.0b1

- .github/fabricbot.json
> {CI} Add cxp attention label

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_deploy_zip.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_download_win_web_log.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_list_deployment_logs.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_show_deployment_logs.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands_thru_mock.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands_thru_mock.py
- src/azure-cli/azure/cli/command_modules/appservice/tunnel.py
> {App Service} Hotfix: Use basic auth with SCM sites if supported, else use AAD auth

- src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_control_plane_user_assigned_identity.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
`az aks update --assign-identity`
Support updating user assigned control plane identity.
---
> [AKS] `az aks update`: Support update user assigned control plane identity for parameter ` --assign-identity`

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_control_plane_user_assigned_identity.yaml
Fix recording file for test case `test_aks_control_plane_user_assigned_identity`.
---
> {AKS} Fix recording file `test_aks_control_plane_user_assigned_identity`

- .github/fabricbot.json
> {CI} Fabric bot support adding CLI label to `az ad`

- .github/fabricbot.json
1. `az container` PR add reviewers and assignees.
2. Support auto-assign for iot PR and issue.
3. Add `cxp` label for `az functionapp` PR.
4. Add [avanigupta](https://github.com/avanigupta) as reviewer to `App Config` PR.
5. Support routing `az network dns` to service team.
---
> {CI} Update fabricbot.json

- .github/workflows/AddPRComment.yml
If pr title contains single quotes, bash will report an error when reading `github.event.pull_request.title`.
According to [github doc](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable)：
We should stored expression in memory and used as a variable, and doesn't interact with the script generation process.
In addition, consider using double quote shell variables to avoid word splitting.
--- …
> {CI} Update AddPRComment.yml

- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py
`az functionapp create` add two new parameters `--min-replicas` and `--max-replicas`  
`az functionapp config container set` add two new parameters `--min-replicas` and  `--max-replicas`
This parameter is required to support create function app running on container app. 
Add unit tests for testing and validation. 
---
> [App Service] `az functionapp create`: Add new parameter `--min-replicas` and `--max-replicas` to support minimum and maximum replicas

- src/azure-cli-testsdk/azure/cli/testsdk/preparers.py
> {CI} Update `ResourceGroupPreparer` decorator to support tag module

- .github/azure-client-tools-bot/config.yml
- .github/azure-client-tools-bot/templates/PRComment.handlebars
- scripts/ci/automation_full_test.py
Now we will directly display the test results of all modules, the comment is too long.
So I add a new level `TestName` to optimize the display effect of azure-cli full test: 
TODO: 
Support only_show_errors.
---
> {CI} Optimize pipeline result

- .github/azure-client-tools-bot/config.yml
> {CI} Support similar bot

- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_dns_commands.py
Fix: https://github.com/Azure/azure-cli/issues/26248
Fix: https://github.com/Azure/azure-cli/issues/26274
Fix: https://github.com/Azure/azure-cli/issues/26379
---
> [Network] Fix #26248: `az network dns record-set cname set-record`: Declare TTL as integer type

- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_subnet_detach_nat_gateway.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Fix: https://github.com/Azure/azure-cli/issues/26326
---
> [Network] Fix #26326: `az network vnet subnet update`: `--nat-gateway` cannot be set to null

- src/azure-cli/azure/cli/command_modules/monitor/operations/log_analytics_workspace.py
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_log_analytics_workspace_table_total_retention_upper_fix.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_log_analytics_workspace.py
az monitor log-analytics workspace table create/update
[Monitor] `az monitor log-analytics workspace table create/update`: `--total-retention-time` fix upper validation
---
closed https://github.com/Azure/azure-cli/issues/25660
> {monitor}`az monitor log-analytics workspace table create/update`: `--total-retention-time` fix upper validation

- .github/fabricbot.json
> {CI} APIM pull request add `yanzhudd` as reviewer

- src/azure-cli/azure/cli/command_modules/appservice/commands.py
`az functionapp deployment source sync`
`az functionapp deployment source show`
`az functionapp deployment source delete`
Add exception handler to these three commands in order to present the error message to the customer.
The three commands should now return the exception message from the backend.
---
> {App Service} `az functionapp deployment source`: Add exception handler

- src/azure-cli/azure/cli/command_modules/synapse/manual/_help.py
Update help doc. Related to #25790 
---
> {Synapse}`az synapse role assignment create`: Add one more example in help

- .github/fabricbot.json
The Serial Contact person needed to be updated because Craig Wiand is no longer on the team and the contact needed to be updated so the appropriate personnel could be notified of any changes that need to occur.
n/a
n/a
---
> {Serial-Console} `serialconsole`: Update serial console contact person

- src/azure-cli/azure/cli/command_modules/sql/_params.py
az sql db copy --zone-redudant
az sql db create --zone-redudant 
Add default value for --zone-redundant parameter. Fixes [issue](https://github.com/Azure/azure-cli/issues/26317)
---
> {sql} Add default value for --zone-redundant parameter

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Fix test case `test_aks_byo_appgw_with_ingress_appgw_addon`.
---
> {AKS} Fix test case `test_aks_byo_appgw_with_ingress_appgw_addon`

- src/azure-cli/service_name.json
Removing an unused service name as instructed in this issue: https://github.com/Azure/azure-cli/issues/26305
---
> {IoT} Remove unused service name

- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_extension.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
`az vm extension set`
Feature - Close: #26252
---
> [Compute] `az vm extension set`: Enable auto-upgrade by default for GuestAttestation extension

- src/azure-cli/azure/cli/command_modules/storage/_help.py
- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/commands.py
- src/azure-cli/azure/cli/command_modules/storage/operations/account.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_blob_cors_rule.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
`az storage account blob-service-properties cors-rule`
We have `az storage cors-rule` to manage blob/file/queue cors rules by calling data plane APIs.
This PR adds `az storage account blob-service-properties cors-rule` command group to manage blob cors rules by calling control plane APIs
See added scenario test
---
> [Storage] `az storage account blob-service-properties cors-rule`: New command group to manage blob cors rules

- .azure-pipelines/breaking-change-tests.yml
- .github/azure-client-tools-bot/config.yml
- .github/azure-client-tools-bot/templates/BreakingChangeTest.handlebars
- scripts/ci/breaking_change_test.py
Support comparing the current PR with the latest dev branch, and display the breaking change report to the github page.
---
> {CI} Breaking change tool integration

- src/azure-cli-core/azure/cli/core/util.py
`az feedback`
Stop prompting `az feedback`.
> {Feedback} Stop prompting `az feedback`

- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_custom_domain_scenarios.py
> {CDN} Skip cdn tests because endpoint names are hardcoded and unavailable, cannot rerun for recording

- src/azure-cli/service_name.json
`az acs`
Remove `az acs` command from `service_name.json`.
---
> {AKS} Remove `az acs` command from service_name.json

- src/azure-cli/azure/cli/command_modules/sql/_help.py
- src/azure-cli/azure/cli/command_modules/sql/_params.py
Typo "Azure SQL managed instance."→"Azure SQL Managed Instance."
fixes Azure/azure-cli#26534
---
> {SQL} Fix the typo from Azure SQL managed instance to Azure SQL Managed Instance

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_update_custom_data.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
`az vmss update`
`az vmss update`: Add new parameter `--custom-data` to support updating custom data
close https://github.com/Azure/azure-cli/issues/26408
---
> [Compute] `az vmss update`: Add new parameter `--custom-data` to support updating custom data

- src/azure-cli-core/azure/cli/core/aaz/_arg.py
> [Core] `aaz`: Add short summary for `--location` when its default value comes from resource group

- src/azure-cli/azure/cli/command_modules/appconfig/_featuremodels.py
- src/azure-cli/azure/cli/command_modules/appconfig/_kv_helpers.py
- src/azure-cli/azure/cli/command_modules/appconfig/feature.py
- src/azure-cli/azure/cli/command_modules/appconfig/keyvalue.py
- `az appconfig feature list`
- `az appconfig feature show`
- This change updates the `list` command to only filter out invalid feature flags and not error out when an invalid feature flag is found in the list. 
- Updates error handling for `show` command when an invalid feature flag is queried. 
[App Config] `az appconfig feature`: Improve error handling for invalid feature flags
---
> [App Config] `az appconfig feature`: Improve error handling for invalid feature flags

- src/azure-cli-core/azure/cli/core/aaz/_error_format.py
> [Core] `aaz`: Handle null property in error response

- src/azure-cli/azure/cli/command_modules/storage/_help.py
> {Storage} `az storage account update`: Add example for changing to user-assigned managed identity

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/waf_policy/policy_setting/_update.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_waf_policy_setting.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_waf_policy_setting_v2.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_waf_policy_with_application_gateway.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Resolve: #26002
Resolve: #26377
[Network] `az network application-gateway waf-policy policy-setting update`: Add support for log scrubbing
[Network] `az network application-gateway waf-policy policy-setting update`: Add support for inspection limit
[Network] BREAKING CHANGE: `az network application-gateway waf-policy`: Rename output property `applicationGatewayIpConfigurations` to `applicationGatewayIPConfigurations` to keep consistent with the name in API
---
> {Network} `az network application-gateway waf-policy policy-setting update`: Add support for log scrubbing and inspection limit

- src/azure-cli-core/azure/cli/core/aaz/_poller.py
Inspired by https://github.com/Azure/azure-cli/issues/26592
Before:
After:
---
> [Core] `aaz`: Explicitly raise TypeError exception during LRO

- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_traffic_manager.yaml
Fix: https://github.com/Azure/azure-cli/issues/24695
---
> [Network] Fix #24695: `az network traffic-manager`: Add command context

- doc/how_to_bump_SDK_version_in_cli.md
- scripts/regression_test/regression_test.yml
With this PR, regression test pipeline can be triggered with a private SDK package by specifying a download link to `CUSTOM_WHL_URL` variable
---
> {Pipeline} Support regression test based on private SDK

- src/azure-cli/azure/cli/command_modules/vm/_help.py
`az sig image-definition create`
Add examples:
- Create an image definition for images that can be used to create Gen2, TrustedLaunch, or Confidential VMs.
- Create an image definition for images that can be used to create Gen2 or TrustedLaunchSupported VMs.
Close: #26632
---
> [Compute] `az sig image-definition create`: Add examples for TrustedLaunchSupported and TrustedLaunchAndConfidentialVmSupported

- src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
`az functionapp connection`
The PR adds a new command group `az functionapp connection` to support service connector for function app.
The experience (commands with their arguments) will be same with `az webapp connection`
All commands work for `az webapp connection` should work in the same way with `az functionapp connection`
https://learn.microsoft.com/en-us/cli/azure/webapp/connection?view=azure-cli-latest
---
> [Service Connector] `az functionapp connection`: Add new command group to support service connector for function app

- src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
`az functionapp connection`
Hide the command group from customers until it is signed off from partner team.
---
> {Service Connector} `az functionapp connection`: Hide the command group from customers until being signed off

- src/azure-cli/azure/cli/command_modules/vm/_help.py
You have a Typo on line 33, you are welcome.
---
> {Compute} `az disk`: Update help message

- doc/authoring_command_modules/authoring_commands.md
> {doc} Add aaz-dev-tools in authoring commands page

- src/azure-cli/azure/cli/command_modules/acs/addonconfiguration.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/data/datacollectionsettings.json
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Extend DataCollectionSettings  JSON object with streams field and update API version for the DCR & DCR-A to version 2022-06-01
---
> {AKS} Extend `--data-collection-settings` with new field "streams"

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/utils.py
az webapp show
Fixes #26647 by removing duplicate IPs
Since this only occurs in very few stamps, the testing would be to ensure that commands return the same list of IPs before and after the change.
---
> [App Service] Fix #26647: `az webapp show`: Remove duplicate IPs from outbound addresses

- src/azure-cli/azure/cli/command_modules/resource/_help.py
`az resource move`
Issue_Close: #26645
---
> [ARM] `az resource move`: Add help example for moving multiple resources

- src/azure-cli/azure/cli/command_modules/vm/custom.py
`az vm create`
Issue - Close: #26516
---
> [Compute] Fix #26516: `az vm create`: Fix warning log for public IP even when no public IP is being created

- src/azure-cli/azure/cli/command_modules/acr/_help.py
> {ACR} `az acr credential show`: Fix typo for help message

- src/azure-cli-core/azure/cli/core/aaz/_operation.py
Inspired by https://github.com/Azure/autorest.python/issues/1984
---
> [Core] `aaz`: Parse and re-serialize query parameters within next link

- azure-pipelines.yml
> {CI} Temporarily set the TestExtensionsLoading task result to always succeed

- doc/private_endpoint_connection_command_guideline.md
> {doc} Fix typo issue

- src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/commands.py
`az functionapp connection`
The PR adds a new command group `az functionapp connection` to support service connector for function app.
The experience (commands with their arguments) will be same with az webapp connection
All commands work for `az webapp connection` should work in the same way with `az functionapp connection`
https://learn.microsoft.com/en-us/cli/azure/webapp/connection?view=azure-cli-latest
---
> [Service Connector] `az functionapp connection`: Add new command group to support service connector on Function App

- scripts/ci/breaking_change_test.py
> {CI} Add rule_link to breaking change test report

- src/azure-cli/azure/cli/command_modules/cdn/_help.py
`az afd origin create --private-link-sub-resource-type`
Parameter name correction on doc example.
Fixes [GitHub Issue 26847](https://github.com/Azure/azure-cli/issues/26847)
---
> {CDN} `az afd origin create`: Correct parameter name on document example

- src/azure-cli-core/azure/cli/core/aaz/__init__.py
- src/azure-cli-core/azure/cli/core/aaz/_arg.py
- src/azure-cli-core/azure/cli/core/aaz/_arg_fmt.py
- src/azure-cli-core/azure/cli/core/aaz/_command.py
- src/azure-cli-core/azure/cli/core/tests/test_aaz_arg_fmt.py
`test_aaz_pagination_token_fmt`
---
> [Core] `aaz`: Add `--max-items` and `--next-token` for pagination

- doc/command_guidelines.md
- doc/debug/debug_in_vs_code.md
- doc/extensions/authoring.md
- doc/install_linux_prerequisites.md
- scripts/ci/build.sh
- src/azure-cli-core/setup.py
- src/azure-cli-telemetry/setup.py
- src/azure-cli-testsdk/setup.py
- src/azure-cli/setup.py
Close #26537.
Drop Python 3.7 because it was end of support on 2023-06-27: https://devguide.python.org/versions/
Ref PR: [Drop Python 3.6 support](https://github.com/Azure/azure-cli/pull/23102)
---
> [Packaging] Drop Python 3.7 support

- azure-pipelines.yml
> {CI} Revert `Temporarily set the TestExtensionsLoading task result to always succeed`

- src/azure-cli/azure/cli/command_modules/resource/commands.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_invoke_action.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
`az resource invoke-action`
Add new parameter `--no-wait` for `az resource invoke-action `
close https://github.com/Azure/azure-cli/issues/21190
---
> [Resource] `az resource invoke-action`: Add new parameter `--no-wait` to support not waiting the long-running operation to finish

- src/azure-cli/azure/cli/command_modules/backup/custom.py
`az backup`
Updated the paired region map that allows for Cross-Region Restore operations in Azure Backup
No testing required - verified earlier on the service side.
Updated the paired region map that allows for Cross-Region Restore operations in Azure Backup
---
> {Backup} Add new secondary region pairings

- .github/azure-client-tools-bot/config.yml
> {CI} Fix regex issue causing incorrect recognition of `Unofficial Azure CLI`

- tools/setup.py
pyyaml 5.4 is not compatible with Cython 3.0, we need to wait for a fixed version, in the meantime pin pyYaml == 5.3.1 as a workaround.
You can see the detailed issue discussion [here](https://github.com/yaml/pyyaml/issues/724).
---
> {CI} Workaround for `error installing pyyaml==5.4, cython_sources`

- tools/setup.py
Due to [CVE](https://github.com/Azure/azure-cli/security/dependabot/29) issue, we need bump to the latest pyyaml.
---
> {CI} Bump pyyaml to latest version 6.0.1

- src/azure-cli/azure/cli/command_modules/keyvault/_help.py
- src/azure-cli/azure/cli/command_modules/keyvault/_params.py
- src/azure-cli/azure/cli/command_modules/keyvault/commands.py
- src/azure-cli/azure/cli/command_modules/keyvault/custom.py
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_key.yaml
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
`az keyvault key sign/verify`
New commands:
- `az keyvault key sign` to support signing with keyvault key
- `az keyvault key verify`: to verify the signature
- `az keyvault key sign -a RS256 --digest 12345678901234567890123456789012 -n testkey --vault-name ystestkv`
- `az keyvault key verify -a RS256 --digest 12345678901234567890123456789012 --signature  "gcjaksz9J736oP2bJ6k1vvhJL5aI6qEHx0HBvDz2jsfuRuaGmLP3VhozVUL7yuqHROHZLw72fnHb3NF1LXGowkniIJJaLb21Jj/DBXhz2rZLRFQr/KaghtIp4P0qWH3tOc0BLEjYNU4ZH6QFDhx0SthOdemEVjPeNXq3RqeZR8MMfx0B21f1SfocgiQJZaDg21D0akummh7EWMQAGVgEu26i78udyrntsJrd4LBhNOP/9m1Giq8YDph6ZnzLW1PF/sOo6OC4Who66uCvVw+0qdFLst19i+beW+EeWtXW/Mbm5oSHVSno4yFRwdUIXSTCrPhUdwMdB0o0GlrErNbEow==" -n testkey --vault-name ystestkv`
--- …
> [Keyvault] `az keyvault key sign/verify`: Add new commands to support signing with keyvault key and verify the signature

- src/azure-cli/azure/cli/command_modules/security/custom.py
- src/azure-cli/azure/cli/command_modules/security/tests/latest/recordings/test_security_pricings.yaml
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
Change the security module from 3.0.0 to 5.0.0 to reflect new APIs
az security {command}
> {Security}: update module version

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/nic/_create.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/nic/_delete.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/nic/_list.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/nic/_show.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/nic/_update.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/nic/_wait.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_multiple_ipconfigs_remove_by_shorthand.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_multiple_ipconfigs_update_with_asg.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_address_pool_addresses.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic_ag_address_pools.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic_app_gateway.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic_auxiliary.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic_edge_zone.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic_front_ip.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic_lb_address_pools.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic_subresources.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_nw_flow_log_create_vnetfl.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_nw_flow_log_delete_vnetfl.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_nw_flow_log_update_vnetfl.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_accelerated_networking.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_custom_ip.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_existing_ids_options.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_existing_nic.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_existing_options.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_multi_nics.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_extended_location.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_asg.yaml
`az network nic create/update`
AAZ model : https://github.com/Azure/aaz/pull/230
---
> [Network] `az network nic create/update`: Add parameters `--auxiliary-mode` and `--auxiliary-sku` to support setting auxiliary mode and sku

- src/azure-cli/azure/cli/command_modules/iot/_help.py
The examples description is confusing. So it needs to be clarified.
- name: Add a new endpoint "S1" of type AzureStorageContainer to "MyIotHub" IoT Hub within the endpoint resource group "MyEndpointResourceGroup".
text: |
az iot hub routing-endpoint create --resource-group MyResourceGroup --hub-name MyIotHub \\
--endpoint-name S1 --endpoint-type azurestoragecontainer --endpoint-resource-group RGS1 \\
--endpoint-subscription-id {SubscriptionId} --connection-string {ConnectionString} \\
--container-name {ContainerName} --batch-frequency 100 --chunk-size 100 \\
--ff {iothub}-{partition}-{YYYY}-{MM}-{DD}-{HH}-{mm}
Docs link: https://learn.microsoft.com/en-us/cli/azure/iot/hub/routing-endpoint?view=azure-cli-latest#az-iot-hub-routing-endpoint-create
fixes Azure/azure-cli#26841
**Related …
> {IOT} Docs clarification for the IOT HUB endpoint create

- src/azure-cli/azure/cli/command_modules/acs/_help.py
Updating text for better readability in [docs](https://learn.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#:~:text=Create%20a%20kubernetes%20cluster%20with%20Azure%20Monitor%20Metrics%20enabled.)
No testing required for this change as its just a document update
---
> {AKS} fix: update short summary for azure monitor metrics for better readability in docs

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/waf_policy/policy_setting/_update.py
> {Network} Add an example in command `az network application-gateway waf-policy policy-setting update`

- src/azure-cli/requirements.py3.windows.txt
Update windows dependency to align with Linux and Mac.
We've created x64 version for windows. Using it to get rid of cryptography warning info.
Related PR:
- https://github.com/Azure/azure-cli/pull/26671
- https://github.com/Azure/azure-cli/pull/26640
---
> {Packaging} Bump cryptography to 41.0.1 and pyOpenSSL to 23.2.0 on Windows

- .github/policies/resourceManagement.yml
> {CI} Update policy config

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_natgateway.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/_validators.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_update_outbound_from_slb_to_natgateway.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_validators.py
Promote outbound type migration feature to azure-cli/acs module. 
[AKS] `az aks update`: Support cluster outbound type migration
---
> [AKS] `az aks update`: Promte outbound type migration to azure-cli/acs

- src/azure-cli/azure/cli/command_modules/vm/_help.py
- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/_validators.py
- src/azure-cli/azure/cli/command_modules/vm/commands.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/linter_exclusions.yml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_soft_delete.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_image_version_create_for_diff_source.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
az sig image-version undelete
Add a new command `az sug image-version undelete` to restore soft deleted images. 
The name, `undelete` is to stay consistent with other soft-delete-recovery commands such as `az storage blob undelete` and `az backup protection undelete.`
#26773 
`az sig image-version undelete -g rgName  --gallery-name galleryName --gallery-image-definition def --gallery-image-version 1.1.1`
---
> [Compute] `az sig image-version undelete`: Add new command to support softdeleted image recovery

- src/azure-cli/azure/cli/command_modules/storage/_client_factory.py
- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_file_main_scenario.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_file_scenarios.py
Fix #26587 
Add `--file-url` to support supplying the url instead of share/file names
---
> [Storage] Fix #26587: `az storage file upload`: Add `--file-url` to support supplying the url instead of share/file name

- src/azure-cli-core/setup.py
- src/azure-cli/setup.py
Update `python_requires` version to align with https://github.com/Azure/azure-cli/pull/26855
---
> {Packaging} Increase minimum python_requires to 3.8

- src/azure-cli-core/setup.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
Bump knack to [0.11.0](https://github.com/microsoft/knack/pull/276) which supports 3.11 and fixes bool default value issue.
```
0.11.0
++++++
* Declare support for Python 3.11 and drop support for Python 3.7 (#275)
* Stop converting argument's `bool` default value to `DefaultInt` (#273)
```
---
> {Packaging} Bump knack to 0.11.0

- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/_validators.py
- src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_and_update_with_managed_nat_gateway_outbound.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_update_outbound_from_slb_to_natgateway.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_validators.py
fix regression bug introduced in #26975
[AKS] `az aks update`: Fix aks network profile update error
---
> {AKS} `az aks update`: Fix aks network profile update error

- src/azure-cli/azure/cli/command_modules/mysql/custom.py
- src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_identity_aad_admin_mgmt.yaml
az mysql flexible-server ad-admin set
add operation for enable AAD on replica when set AAD for source server
---
> [MYSQL] `az mysql flexible-server ad-admin set`: Enable AAD for replica

- azure-pipelines.yml
If x64 version is higher than x86 version, install it will remove x86 version.
Disable it temporarily to release new version.
---
> {Packaging} Temporarily disable Windows x64 installation test

- .azure-pipelines/templates/automation_test.yml
- scripts/ci/automation_full_test.py
> {CI} Add enable traceback

- azure-pipelines.yml
- scripts/ci/codegen_report.py
Run `azdev statistics list-command-table` in the Batch CI stage and collect codegen report data and send it to kusto db.
The table format is as follows:
build_id tyep: int
manual type: int
codegenv1 type: int
codegenv2 type: int
total type: int
is_release: bool
date: datetime (utc+8)
---
> {CI} Send codegen report data to kusto database

- src/azure-cli-core/azure/cli/core/commands/command_operation.py
- src/azure-cli-core/azure/cli/core/profiles/__init__.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/cognitiveservices/commands.py
- src/azure-cli/azure/cli/command_modules/cognitiveservices/custom.py
- src/azure-cli/azure/cli/command_modules/keyvault/custom.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
- src/azure-cli/azure/cli/command_modules/servicebus/_params.py
- src/azure-cli/azure/cli/command_modules/vm/_validators.py
> {CI} Fix E231 missing whitespace after ','

- azure-pipelines.yml
> {CI} Add branch detection to reject PR whose target branch is main

- azure-pipelines.yml
> {CI} Fix codegen report

- src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_event_grid_namespaces.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_event_grid_partner_namespaces.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_link_resource_event_grid.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
az network private end connection related commands
Example:
az network private-endpoint-connection list --id {PrivateLinkResourceID}
This change is to add support for private end connections for new resource type Microsoft.EventGrid/namespaces, Microsoft.EventGrid/partnerNamespaces
N/A
> [Network] `az network private-endpoint-connection`: Add provider `Microsoft.EventGrid/namespaces` and `Microsoft.EventGrid/partnerNamespaces`

- src/azure-cli-core/azure/cli/core/aaz/_content_builder.py
- src/azure-cli-core/azure/cli/core/tests/test_aaz_content_builder.py
> {core} `aaz`: Support to parse discriminator keys which may contain special '.' character

- src/azure-cli/azure/cli/command_modules/serviceconnector/_validators.py
> {Service Connector}: add error message for invalid source resource id

- src/azure-cli/azure/cli/command_modules/acs/_params.py
Fixes Azure/azure-cli#27022
Documentation says below:
>--ca-profile --cluster-autoscaler-profile
Space-separated list of key=value pairs for configuring cluster autoscaler. Pass an empty string to clear the profile.
When I try to pass --ca-profile 'scale-down-delay-after-add=3m,scale-down-unneeded-time=3m' command fails with error
```
The format of 'scale-down-delay-after-add=3m scale-down-unneeded-time=3m' in 'scale-down-delay-after-add=3m scale-down-unneeded-time=3m' is incorrect, correct format should be 'Key1=Value1,Key2=Value2'.
```
So the documentation should be fixed and made comma-separated instead of Space-separated. …
> {AKS} Documentation for aks update/create wrong wording

- scripts/ci/automation_full_test.py
> {CI} Fix enable traceback in azure cli fulltest.

- src/azure-cli/azure/cli/command_modules/rdbms/validators.py
Fixing bug where firewall rules are treated as string. The IP addresses should be converted into integers instead
---
> {RDBMS} Fix firewall rule validator bug

- src/azure-cli/azure/cli/command_modules/privatedns/custom.py
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/recordings/test_PatchLink_LinkExistsRemoveTags_ExpectTagsRemoved.yaml
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/recordings/test_Private_Dns_Zone1_Import.yaml
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/recordings/test_Private_Dns_Zone2_Import.yaml
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/recordings/test_Private_Dns_Zone3_Import.yaml
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/recordings/test_Private_Dns_Zone4_Import.yaml
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/recordings/test_Private_Dns_Zone5_Import.yaml
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/recordings/test_Private_Dns_Zone6_Import.yaml
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/recordings/test_Private_Dns_Zone7_Import.yaml
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/recordings/test_Private_Dns_Zone8_Import.yaml
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/recordings/test_Private_Dns_Zone_Local_Import.yaml
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/test_privatedns_commands.py
> {Network} `az network private-dns`: Fix live test

- doc/shorthand_syntax.md
- src/azure-cli-core/azure/cli/core/aaz/_help.py
> {Doc} Wrap `??` by double quotes in examples for Bash users.

- src/azure-cli/azure/cli/command_modules/batch/_client_factory.py
- src/azure-cli/azure/cli/command_modules/batch/custom.py
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/test_batch_mgmt_commands.py
az batch related commands
fix Batch cloud console authentication issue, use batch_resource_id to request AAD tokens to authenticate with Batch Dataplane APIs.
N/A
---
> [Batch] `az batch`: Fix batch cloud console authentication issue

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/waf_policy/custom_rule/_create.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/waf_policy/custom_rule/_update.py
Resolve: https://github.com/Azure/azure-cli/issues/27160
---
> [Network] `az network application-gateway waf-policy custom-rule`: Add an example of using `--group-by-user-session`

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
`az webapp ssh`
Backport the security fix in #25141 to version 2.38.0
---
> [App Service] `az webapp ssh`: Backport #25141 to 2.38.0

- src/azure-cli/azure/cli/command_modules/network/custom.py
Related IcM: https://portal.microsofticm.com/imp/v3/incidents/details/409366200/home
---
> [Network] `az network express-route update`: Fix `properties.SeriveProviderProperties` unexpected null

- doc/breaking_change_detection_guidelines.md
> {doc} Remove breaking change diff site info

- src/azure-cli-core/azure/cli/core/aaz/_arg.py
- src/azure-cli-core/azure/cli/core/tests/test_aaz_arg.py
> [Core] `aaz`: Support `configured_default` for `AAZBaseArg`

- .github/azure-client-tools-bot/config.yml
Just to make it a little less aggressive when telling you to upgrade if you are not physically able to do so.
> {CI} Update azure-client-tools-bot's auto-reply to be more friendly

- src/azure-cli-core/azure/cli/core/profiles/_shared.py
`az aro`
- Follow-up PR to https://github.com/Azure/azure-cli/pull/27212, update ResourceType.MGMT_ARO property within AZURE_API_PROFILES to point to latest version of ARO API
{ARO} Update AZURE_API_PROFILES ResourceType.MGMT_ARO property to point to latest version of ARO API. 
---
> [ARO] Update ResourceType.MGMT_ARO property to point to latest ARO API

- src/azure-cli/azure/cli/command_modules/mysql/_help.py
- src/azure-cli/azure/cli/command_modules/mysql/_params.py
- src/azure-cli/azure/cli/command_modules/mysql/action.py
- src/azure-cli/azure/cli/command_modules/mysql/commands.py
- src/azure-cli/azure/cli/command_modules/mysql/custom.py
- src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_proxy_resource.yaml
- src/azure-cli/azure/cli/command_modules/mysql/tests/latest/test_mysql_scenario.py
az mysql flexible-server parameter set-batch --resource-group  --server-name  --args key1=value1 key2=value2
1. Add new command for parameter batch update. So that user can update multiple parameters at one command.
2. Remove location validation for geo restore. Just remove this check and no change in input and output
---
> [MySQL] `az mysql flexible-server parameter set-batch`: Add new command to support updating multiple parameters

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/public_ip/_list.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/public_ip/_update.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_public_ip.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Fix: https://github.com/Azure/azure-cli/issues/26730
---
> [Network] Fix #26730: `az network public-ip update`: `--ip-tags` cannot be correctly parsed

- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_waf_policy_with_application_gateway.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Resolve: https://github.com/Azure/azure-cli/issues/26888
---
> [Network] `az network application-gateway waf-policy managed-rule rule-set`: Support Microsoft_BotManagerRuleSet version 1.0

- src/azure-cli-core/azure/cli/core/profiles/_shared.py
- src/azure-cli/azure/cli/command_modules/consumption/__init__.py
- src/azure-cli/azure/cli/command_modules/consumption/_params.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
> {Consumption} `az consumption`: Remove sdk

- src/azure-cli/azure/cli/command_modules/mysql/_params.py
`mysql flexible-server replica create`
Documentation update for optional parameters section to help customer using this "az mysql flexible-server replica create" cli command to have better clarity for in-region and cross region read replica.
Fixes [GitHub Issue 26944](https://github.com/Azure/azure-cli/issues/26944)
NA
---
> {mysql} Document update for mysql flexible-server replica create

- src/azure-cli/azure/cli/command_modules/acs/_loadbalancer.py
- src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_loadbalancer.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
[AKS] `az aks update`: Outbound ip/ outbound ipprefix and managed outbound ip should be mutually exclusive
---
> {AKS} Outbound ip/ outbound ipprefix and managed outbound ip should be mutually exclusive

- src/azure-cli/azure/cli/command_modules/storage/operations/table.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_table_main_scenario.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_sas_scenarios.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_table_scenarios.py
Fix case when using sas token with only `add` permission
Fix #27202 
---
> [Storage] Fix #27202 `az storage entity insert`: Fix case when using sas token with only `add` permission

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
az webapp up --runtime 'PYTHON:3.9' -g my-group-1 --name my-app-1
The message was misleading. This is a simple message change 
from 
Creating AppServicePlan '[plan_name]'
to 
Creating AppServicePlan '[plan_name]' or Updating if already exists
---
> {App Service} change error message

- src/azure-cli/azure/cli/command_modules/sql/_params.py
- src/azure-cli/azure/cli/command_modules/sql/custom.py
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_failover_group_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
az sql failover-group set-primary
Adds a new optional boolean parameter `--try-planned-before-forced-failover (, --tpbff)` to command `az sql failover-group set-primary` to enable users to perform hybrid failover
Case 1 - Planned failover:
az sql failover-group set-primary --name MyFailoverGroup --resource-group MyResourceGroup --server myserver
Case 2 - Forced failover:
az sql failover-group set-primary --name MyFailoverGroup --resource-group MyResourceGroup --server myserver --allow-data-loss
Case 3 - Hybrid failover:
az sql failover-group set-primary --name MyFailoverGroup --resource-group MyResourceGroup --server myserver --try-planned-before-forced-failover
Case 4 - Hybrid failover:
az sql failover-group set-primary --name …
> [SQL] `az sql failover-group set-primary`: Add parameter `--try-planned-before-forced-failover` to enable users to perform hybrid failover

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_private_cluster_update_dns_zone.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
az aks update --private-dns-zone
Support this feature in cli-core
---
> [AKS] `az aks update`: Add new parameter `--private-dns-zone` to support private DNS zone for AKS private cluster

- .github/policies/resourceManagement.yml
> {CI} Update bot policy

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_update_with_windows_gmsa.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
az aks update --resource-group={resource_group} --name={name} --disable-windows-gmsa
Support disabling Windows gMSA in an AKS cluster.
---
> [AKS] `az aks update`: Add new parameter `--disable-windows-gmsa` to support disabling Windows gMSA in an AKS cluster

- src/azure-cli/azure/cli/command_modules/appconfig/_validators.py
This change enables the exclusion of feature flags and keyvault during import and export of kv from a snapshot.
[Component Name 1] [App Config] `az appconfig kv import/export`: Removing skip-features and skip-keyvault restriction for snapshots
---
> [App Config] `az appconfig kv import/export`: Remove `skip-features` and `skip-keyvault` restriction for snapshots

- src/azure-cli/HISTORY.rst
Add changelog for 2.38.1. This version is only released for CentOS 7 and RHEL 7.
Release branch https://github.com/Azure/azure-cli/tree/2.38.1-release
---
> {Doc} Add changelog for 2.38.1

- src/azure-cli/azure/cli/command_modules/serviceconnector/_params.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/_validators.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/custom.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_webappslot_storageblob_e2e.yaml
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/test_webpp_connection_scenario.py
az webapp connection delete/create/show/list/list-configuration/validate/update
Add service connector support for web app slot
---
> [Service Connector] `az webapp connection`: Add new parameter `--slot` to support webapp slot connection

- src/azure-cli/azure/cli/command_modules/storage/operations/blob.py
Fix #27052 
Use utc as default timezone to remove "Datetime with no tzinfo will be considered UTC." warning
[Storage] Fix #27052: `az storage blob delete-batch`: Use utc as default timezone to remove "Datetime with no tzinfo will be considered UTC." warning
---
> [Storage] Fix #27052: `az storage blob delete-batch`: Use utc as default timezone to remove "Datetime with no tzinfo will be considered UTC." warning

- scripts/live_test/CLITest.yml
[pytest-html 4.0.0](https://pytest-html.readthedocs.io/en/latest/changelog.html) modifies the format of the test report, which causes the aggregation of multi-platform test reports to fail. 
This PR will pin the pytest-html version to 3.2.0.
TODO: Support the latest version of pytest-html.
---
> {CI} Pin pytest-html to 3.2.0

- src/azure-cli/azure/cli/command_modules/serviceconnector/_help.py
> {Service Connector}  `az webapp connection`: Add Examples in helper for slot creation

- src/azure-cli/azure/cli/command_modules/resource/_help.py
- src/azure-cli/azure/cli/command_modules/resource/_validators.py
- src/azure-cli/azure/cli/command_modules/resource/custom.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/data/bicepparam/bicepconfig.json
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/data/bicepparam/params_registry.bicepparam
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/data/bicepparam/params_templatespec.bicepparam
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_create_deployment_stack_resource_group_with_bicep.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
In order to support `.bicepparam` files which link directly to Bicep Registry, Template Spec or JSON content, we must relax the requirement for the user to provide the `--template-file` parameter for deployment-related commands. This parameter is currently redundant, as `.bicepparam` files require the user to link to a `.bicep` file via the `using` statement.
To maintain backwards-compatibility, continue to support the "old" command if the user supplies the `--template-file` parameter.
```sh
az deployment group create \ 
-g myRg \
-p .\bicepparam\storage_account_params.bicepparam  
```
**Notes**
- Integration tests in this PR are `LiveScenarioTest` because we need to do a Bicep CLI version check (meaning it has to be …
> [ARM] `az deployment group create`: Make `--template-file` parameter optional when used with `.bicepparam` parameter file

- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/data/source_built_using_acr_task/package.json
None
Update ejs version for test to fix security issue.
```
Package
Affected versions
Patched version
ejs
(npm)
< 3.1.7
3.1.7
The ejs (aka Embedded JavaScript templates) package 3.1.6 for Node.js allows server-side template injection in settings[view options][outputFunctionName]. This is parsed as an internal option, and overwrites the outputFunctionName option with an arbitrary OS command (which is executed upon template compilation).
```
---
> {Containerapp} update ejs version fix security issue

- src/azure-cli/azure/cli/command_modules/acr/custom.py
az acr create
Bad error description when trying to create a registry with capital case. 
Try to create a registry with Capital case
---
> {ACR} Registry name error message fix

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/virtual_appliance/_create.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/virtual_appliance/_delete.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/virtual_appliance/_list.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/virtual_appliance/_show.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/virtual_appliance/_update.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/virtual_appliance/_wait.py
Network
Added support of additional nic in az network virtual-appliance create
//Create Command
az network virtual-appliance create -g RahulTestSetup -n RahulCheckPointNva4  --vhub "/subscriptions/62364504-2406-418e-971c-05822ff72fad/resourceGroups/RahulTestSetup/providers/Microsoft.Network/virtualHubs/RahulTestHub" --vendor "checkpoint" --scale-unit 10 -v latest --asn 64512 --init-config "" --additional-nics "[{name:sdwan,has-public-ip:true}]" --debug
//Help
az network virtual-appliance create --additional-nics ??
Argument
--additional-nics : List<Object>
Details required for Additional Network Interface.
See https://github.com/Azure/azure-cli/tree/dev/doc/shorthand_syntax.md for more about
shorthand syntax.
List Element Properties …
> [Network] `az network virtual-appliance`: Add parameter `--additional-nics`

- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_auth_commands.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_azurefile.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_commands.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_compose_basic.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_compose_command.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_compose_environment.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_compose_ingress.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_compose_registries.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_compose_resources.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_compose_scale.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_compose_secrets.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_compose_transport_overrides.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_env_commands.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_ingress_sticky_session.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_mount_secret_volume.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_scenario.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_up.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_workload_profile_commands.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerappjob_crud.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerappjob_event_triggered_crud.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerappjob_executions.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerappjob_with_identity.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerappjob_with_secrets.py
None
Add random config directory to fix batch CI. Avoiding configure default location with `az configure --default` in containerapp test cases effect other services' test.
---
> {containerapp} add random config directory for test

- src/azure-cli/azure/cli/command_modules/acs/_help.py
az aks addon enable
Remove erroneous indent on long summary 972-982. Docs services was unable to process format correctly:
https://learn.microsoft.com/en-us/cli/azure/aks/addon?view=azure-cli-latest#az-aks-addon-enable 
From bug: https://dev.azure.com/ceapex/Engineering/_workitems/edit/891668
> {AKS} `az aks addon enable`: Update help message

- src/azure-cli/azure/cli/command_modules/containerapp/_params.py
- src/azure-cli/azure/cli/command_modules/containerapp/custom.py
az containerapp env dapr-component create
The sample link for argument `--yaml` is not correct.
---
> [containerapp] `az containerapp env dapr-component create`: Fix the sample link for `--yaml` parameter

- src/azure-cli/azure/cli/command_modules/mysql/_params.py
- src/azure-cli/azure/cli/command_modules/mysql/custom.py
az mysql flexible-server replica create --tier --sku-name --storage-size --backup-retention --geo-redundant-backup --iops
Add new parameters for mysql flexible server replica creation.
---
> [MySQL] `az mysql flexible-server replica create`: Add new parameters to support replica creation

- src/azure-cli/azure/cli/command_modules/mysql/_client_factory.py
- src/azure-cli/azure/cli/command_modules/mysql/_util.py
- src/azure-cli/azure/cli/command_modules/mysql/custom.py
- src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_import_create.yaml
Revert changes for firewall rule migration from single to flex (#27370)
This reverts commit 9f623df5257c5349f6a04ba491797ecf77bf2df9.
The timeline for this feature has been pushed because of a bug identified in the backend code. Will postpone the release.
---
> {Mysql} az mysql flexible-server import create: Revert firewall rule migration changes from single to flex PR

- src/azure-cli-core/setup.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
> {Core} Bump MSAL to 1.24.0b2

- src/azure-cli/azure/cli/command_modules/acs/_loadbalancer.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_loadbalancer.py
`
az aks update -g MyResourceGroup -n MyManagedCluster --load-balancer-outbound-ips "outboundip ids"  --load-balancer-managed-outbound-ip-count 3
`
Custom ips and managed ips can be assigned to aks cluster outbound resources
[AKS] `az aks create/update`: Support custom ips/ipprefixes and managed ips being assigned to aks cluster outbound resources together
---
> [AKS] `az aks create/update`: Custom ips and managed ips can be assigned to aks cluster outbound resources

- scripts/live_test/sendemail.py
Delete error logs in kusto db and stop collecting test error logs.
---
> {CI} Fix ICM issue 

- .github/policies/resourceManagement.yml
> {CI} Take over all CXP Attention issues

- .github/policies/resourceManagement.yml
> {CI} Update policy configuration according to Service-Contact-List wiki

- src/azure-cli/azure/cli/command_modules/privatedns/custom.py
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/recordings/test_add_record_when_record_set_is_empty.yaml
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/test_privatedns_commands.py
> [Network] `az network private-dns record-set a add-record`: Fix record cannot be added when record set is empty

- src/azure-cli/azure/cli/command_modules/vm/commands.py
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2018_03_01/recordings/test_vmss_create_and_modify.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2018_03_01/recordings/test_vmss_create_options.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2018_03_01/recordings/test_vmss_vms.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/recordings/test_vmss_create_and_modify.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/recordings/test_vmss_create_options.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/recordings/test_vmss_nics.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/recordings/test_vmss_update_instance_disks.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/recordings/test_vmss_vms.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/recordings/test_vmss_create_and_modify.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/recordings/test_vmss_create_options.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/recordings/test_vmss_nics.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/recordings/test_vmss_simulate_eviction.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/recordings/test_vmss_update_instance_disks.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/recordings/test_vmss_vms.yaml
`az vmss list-instances`
Close: #27451 
---
> [Compute] Fix #27451: `az vmss list-instances`: Fix API profile to resolve no registered resource provider found error

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/listener/_create.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/listener/_delete.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/listener/_list.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/listener/_show.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/listener/_update.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/listener/_wait.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_ag_rule_default_exists.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_appgw_with_tcp.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_listener.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_listener_with_host_names.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_routing_rule.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
> [Network] `az network application-gateway listener`: Add parameter `--host-names`

- src/azure-cli/azure/cli/command_modules/mysql/_help.py
- src/azure-cli/azure/cli/command_modules/mysql/_params.py
- src/azure-cli/azure/cli/command_modules/mysql/custom.py
az mysql flexible-server create
The defaults for SKU and tier is changed back to Burstable and Standard_B1ms.
---
> {Mysql} az mysql flexible-server import create: Change sku to default for external migration

- src/azure-cli/azure/cli/command_modules/monitor/operations/autoscale_settings.py
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_basic.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_fixed.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_predictive_policy.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_recurring.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_refined.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_rule_with_dimensions.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_rules.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_show_predictive_metric.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_autoscale.py
az monitor autoscale update
[Monitor] `az monitor autoscale update`: Fix update failure with empty notification
---
> [monitor]`az monitor autoscale update`: Fix update failure with empty notification

- src/azure-cli/azure/cli/command_modules/sql/_help.py
- src/azure-cli/azure/cli/command_modules/sql/_params.py
- src/azure-cli/azure/cli/command_modules/sql/custom.py
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_db_free_params.yaml
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
`az sql db create --use-free-limit --free-limit-exhaustion-behavior AutoPause`
`az sql db update --free-limit-exhaustion-behavior BillOverUsage`
Add support for free limit parameters that will allow to create free limit database based on General Purpose Serverless database and allow to specify exhaustion behavior to either AutoPause until the end of the month or BillOverUsage to pay for usage above free limits.
Create new azure sql database on GeneralPurpose serverless database with `--use-free-limit` and `--free-limit-exhaustion-behavior`. Later same parameters can be used to change `--free-limit-exhaustion-behavior` to BillOverUsage or change to billed version by specifying `--use-free-limit False`.
`sql db create -g rgname --server …
> [SQL] `az sql db create/update`: Add `--use-free-limit` and `--free-limit-exhaustion-behavior` arguments

- src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
The PR helps load `az containerapp connection` command even if containerapp extension is not installed. As containerpp now also exists in cli core.
---
> {Service Connector} `az containerapp connection`: Load the command group even if container app extension is not installed

- src/azure-cli/azure/cli/command_modules/servicebus/aaz/latest/servicebus/queue/_create.py
- src/azure-cli/azure/cli/command_modules/servicebus/aaz/latest/servicebus/queue/_update.py
> {Servicebus} `az servicebus queue` documentation update

- src/azure-cli/azure/cli/command_modules/privatedns/custom.py
Fix: https://github.com/Azure/azure-cli/issues/27508
---
> [Network] Fix #27508: `az network private-dns zone import`: Import fails when zone already exists

- src/azure-cli/azure/cli/command_modules/monitor/operations/monitor_clone_util.py
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_clone_public_ip_metric_alerts_scenario.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_clone_storage_metric_alerts_always_scenario.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_clone_storage_metric_alerts_scenario.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_clone_vm_metric_alerts_scenario.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_general_operations.py
az monior clone
{monitor}`az monitor clone`: Migrated to codegen V2
---
> {monitor}`az monitor clone`: Migrate command to codegen V2

- src/azure-cli-testsdk/azure/cli/testsdk/scenario_tests/base.py
A temporary fix for https://github.com/Azure/azure-cli/issues/27641
After this change, in Python 3.11, even if a test fails, the temp recording file replaces the original recording file. This is the original behavior before https://github.com/Azure/azure-cli/pull/25055.
> {testsdk} Fix live test on Python 3.11

- src/azure-cli/azure/cli/command_modules/resource/_bicep.py
- src/azure-cli/azure/cli/command_modules/resource/custom.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/sample_params.bicep
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/sample_params.bicepparam
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
Add support for specifying supplemental inline parameters when using `.bicepparam` files.
```sh
az deployment group create \ 
-g myRg \
-p parameters.bicepparam  \
-p override=test
```
**Notes**
- Integration tests in this PR are `LiveScenarioTest` because we need to do a Bicep CLI version check (meaning it has to be installed) before performing any `.bicepparam` related logic
[ARM] `az deployment group create`: Support supplemental parameters when used with `.bicepparam` parameter file
---
> [ARM] `az deployment group create`: Support supplemental parameters when used with `.bicepparam` parameter file

- src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
> {Service Connector} Add new client type: `dotnet-internal`

- azure-pipelines.yml
Change name from `Build Docker Image Alpine Alpine ARM64` to `Build Docker Image Alpine ARM64`
---
> {CI} Fix build docker image Alpine task name

- src/azure-cli-core/azure/cli/core/aaz/__init__.py
- src/azure-cli-core/azure/cli/core/aaz/_client.py
- src/azure-cli-core/azure/cli/core/aaz/_command.py
- src/azure-cli-core/azure/cli/core/aaz/_command_ctx.py
- src/azure-cli-core/azure/cli/core/cloud.py
> [Core] `aaz`: Support data-plane clients

- src/azure-cli/azure/cli/command_modules/storage/tests/latest/blob_inventory_policy.json
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_blob_inventory_policy.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
Add test for supporting new filter `creationTime.lastNDays` in `az storage account blob-inventory-policy create`
[Storage] `az storage account blob-inventory-policy create`: Add support for new filter `creationTime.lastNDays` in json
---
> [Storage] `az storage account blob-inventory-policy create`: Add support for new filter `creationTime.lastNDays` in json

- scripts/ci/automation_full_test.py
Remove unnecessary printing information in Azure.azure-cli Full Test.
---
> {CI} Remove unnecessary printing information

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_deploy_zip.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_list_deployment_logs.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_show_deployment_logs.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands_thru_mock.py
`az functionapp deployment source config-zip`
Adding the deployer information enables us to improve telemetry.
1. Create a function app with the `az functonapp create` command
2. Deploy code with the `az functionapp deployment source config-zip` command
---
> [App Service] `az functionapp deployment source config-zip`: Adding the deployer information to improve telemetry

- src/azure-cli/azure/cli/command_modules/vm/_vm_utils.py
`az vm create`
Feature_Close: #27284
---
> [Compute] `az vm create`: Format the notification message of recommendation region

- .github/policies/resourceManagement.yml
n/a
Removing myself since I am no longer on the Azure Cognitive Search team.
n/a
n/a
---
> {CI} Remove brjohnstmsft from the auto-responder policy

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/address_pool/_create.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/address_pool/_update.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/address_pool/basic/_create.py
> {Network} `az network lb address-pool`: Add preview warning to `--sync-mode`

- src/azure-cli/azure/cli/command_modules/keyvault/_help.py
az keyvault decrypt 
Simple typos fix in documentation 
---
> {Keyvault} Update _help.py

- alpine.dockerfile
- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
az network lb create
az vm create
az vmss create
close: https://github.com/Azure/azure-cli/issues/27121
close: https://github.com/Azure/azure-cli/issues/27123
close: https://github.com/Azure/azure-cli/issues/27254
close: https://github.com/Azure/azure-cli/issues/27255
[Network] BREAKING CHANGE: `az network public-ip create`: Change default value of `--sku` to standard
[Network] BREAKING CHANGE: `az network lb create`: Change default value of `--sku` to standard
[Compute] BREAKING CHANGE: `az vm create`: Change default value to `Standard` for LB options
[Compute] BREAKING CHANGE: `az vmss create`: Change default value to `Standard` for LB options
--- …
> {Network/Compute} Change default values to `Standard` for LB options

- src/azure-cli/azure/cli/command_modules/network/commands.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_nat_rule.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Fix: https://github.com/Azure/azure-cli/issues/27735
---
> [Network] Fix #27735: `az network vnet-gateway show`: Conflict key when apply client flatten

- src/azure-cli/azure/cli/command_modules/acr/_constants.py
- src/azure-cli/azure/cli/command_modules/acr/_validators.py
`az acr login`
Adds additional parameter validation for `az acr login`
`az acr login -n myregistry` -> good
`az acr login -n myregistry$` -> throw error
[ACR] `az acr login`: Add additional parameter validation to check registry name is valid
---
> [ACR] `az acr login`: Add additional parameter validation to check registry name is valid

- src/azure-cli/azure/cli/command_modules/resource/_params.py
`az deployment create`
Before
After
---
> {ARM} `az deployment create`: Fix warning for `ExemptionCategory`

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/linter_exclusions.yml
Related PR: https://github.com/Azure/azure-cli/pull/27742
[Compute] `az disk create`: Revert new parameter `--optimized-for-frequent-attach`
[Compute] `az disk/snapshot create`: Revert new parameter `--elastic-san-resource-id`
---
> {Compute} `az disk/snapshot`: Revert new params

- src/azure-cli/azure/cli/command_modules/vm/_vm_utils.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_trusted_launch.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Fix bug bash issue of PR #27749
---
> {Compute} `az vm create`: Support Trusted Launch as default deployment option

- src/azure-cli/azure/cli/command_modules/batch/_help.py
`az batch keys renew`
`az batch keys list`
`az batch account identity show`
 
Add help text to highlight these commands output secrets
Verified help output
[Batch] `az batch keys renew`: Update help with security warning
[Batch] `az batch keys list`: Update help with security warning
[Batch] `az batch account identity show`: Update help with security warning
---
> [Batch] `az batch account`: Add warnings about secrets being outputted

- src/azure-cli/azure/cli/command_modules/monitor/aaz/latest/monitor/activity_log/alert/_create.py
- src/azure-cli/azure/cli/command_modules/monitor/aaz/latest/monitor/activity_log/alert/_delete.py
- src/azure-cli/azure/cli/command_modules/monitor/aaz/latest/monitor/activity_log/alert/_list.py
- src/azure-cli/azure/cli/command_modules/monitor/aaz/latest/monitor/activity_log/alert/_show.py
- src/azure-cli/azure/cli/command_modules/monitor/aaz/latest/monitor/activity_log/alert/_update.py
- src/azure-cli/azure/cli/command_modules/monitor/operations/activity_log_alerts.py
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_activity_log_alert_update_action.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_activity_log_alert_update_condition.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_activity_log_alert_update_scope.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_create_default_activity_log_alert.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_create_disabled_activity_log_alert.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_create_full_fledged_activity_log_alert.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_create_update_activity_log_alert_anyof_conditon.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_activity_log_alert.py
az monitor activity-log alert
[monitor] `az monitor activity-log alert`: Upgrade api-version to `2020-10-01` to include `any-of` query condition
[monitor] `az monitor activity-log alert`: Expose parameter `all-of` to enable user modifying query condition specifically
---
closed https://github.com/Azure/azure-cli/issues/24922
closed https://github.com/Azure/azure-cli/issues/27602
closed https://github.com/Azure/azure-cli/issues/25363
closed https://github.com/Azure/azure-cli/issues/26872
> [monitor] `az monitor activity-log alert`: Upgrade api-version to `2020-10-01`

- src/azure-cli/azure/cli/command_modules/containerapp/custom.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_cors_policy.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_commands.py
`az containerapp cors enable`
Currently, for command `az containerapp cors enable`,  if not input argument `--allow-credentials`, for example:
`az containerapp ingress cors enable -g abc-rg -n abc-app --allowed-origins "http://www.contoso.com" "https://www.contoso.com" --allowed-methods "GET" "POST" --allowed-headers "header1" "header2" --expose-headers "header3" "header4" --max-age 100 --debug`
The request body is:
{"properties": {"configuration": {"ingress": {"corsPolicy": {"allowedOrigins": ["http://www.contoso.com", "https://www.contoso.com"], "allowedMethods": ["GET", "POST"], "allowedHeaders": ["header1", "header2"], "exposeHeaders": ["header3", "header4"], **"allowCredentials": null**, "maxAge": "100"}}}}}
It throws error: …
> [containerapp] `az containerapp cors enable`: Set the default value of property `--allow-credentials` to `False`

- src/azure-cli/azure/cli/command_modules/storage/_help.py
{Storage} `az storage container-rm update`: Fix help example name
---
> {Storage} `az storage container-rm update`: Fix help example name

- src/azure-cli/azure/cli/command_modules/acs/_help.py
'az aks update`
remove limitation in description because the feature has been implemented in azure-cli and backend service.
[AKS] `az aks update`: Update outbound ip description and remove limitation
---
> {aks}`az aks update`: Update outbound ip description and remove limitation

- scripts/live_test/CLITest.yml
> {CI} Set some modules as serial tests

- doc/extensions/authoring.md
Update dependency guideline in extensions.
---
> {Doc} Update dependency guideline

- src/azure-cli/azure/cli/command_modules/sql/_help.py
- src/azure-cli/azure/cli/command_modules/sql/_params.py
- src/azure-cli/azure/cli/command_modules/sql/custom.py
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
`az mi create`: Add optional parameter `instance_pool_name`
`az mi update`: Add optional parameters `instance_pool_name`
To equalize the user experience between PowerShell and CLI, I am adding an optional field called `instance_pool_name`. This field is also important for Instance Pool public preview and GA.
---
> [SQL] `az mi create/update`: Add optional parameter `--instance-pool-name` for SQL Managed Server resource

- src/azure-cli/azure/cli/command_modules/containerapp/_help.py
When using the containerapp name `MyContainerapp` in the example of help directly, it will throw following error:
(ContainerAppInvalidName) Invalid ContainerApp name 'MyContainerapp'. A name must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character and cannot have '--'. The length must not be more than 32 characters.
So, we need to update the name in example to legal names.
---
> [Containerapp] `az containerapp`: Change the container-app name and container-app job name in the example to legal names

- src/azure-cli/azure/cli/command_modules/vm/aaz/latest/disk/_delete.py
- src/azure-cli/azure/cli/command_modules/vm/aaz/latest/disk/_list.py
- src/azure-cli/azure/cli/command_modules/vm/aaz/latest/disk/_revoke_access.py
- src/azure-cli/azure/cli/command_modules/vm/aaz/latest/disk/_show.py
- src/azure-cli/azure/cli/command_modules/vm/aaz/latest/disk/_wait.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_accelerated_network.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_access.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_bursting.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_trusted_launch.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_public_network_access.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_by_attach_os_and_data_disks.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_create_zones.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_ultra_ssd_storage_sku.yaml
> {Compute} `az disk show/list/delete/revoke-access`: Bump api-version for disk to support new features

- src/azure-cli-core/azure/cli/core/aaz/_client.py
- src/azure-cli-core/azure/cli/core/cloud.py
- src/azure-cli-core/azure/cli/core/tests/test_aaz_client.py
- src/azure-cli-core/azure/cli/core/tests/test_aaz_command_ctx.py
This PR adds support to retrieve endpoints and suffixes for ARM Cloud Metadata API for __codegen data-plane clients__. It added a mapping between the properties of CloudEndpoints/CloudSuffixes and the retrieve index in API response.
This PR also sorts the properties names of endpoints and suffixes in alphabetical order.
---
> {Core} `aaz`: Support retrieve endpoints and suffixes from ARM Cloud Metadata API by index

- scripts/ci/breaking_change_test.py
> {CI} Regenerating breaking change report with only_break=True to control length within 65535.

- src/azure-cli-core/azure/cli/core/tests/test_extension.py
Task:
Test Rpm Package Mariner
/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/tests/test_extension.py:20: in <module>
from azure.cli.core.extension.tests.latest import IndexPatch, mock_ext
ModuleNotFoundError: No module named 'azure.cli.core.extension.tests'
---
> {Core} Fix core test without extension test package

- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
Close https://github.com/Azure/azure-cli/issues/27995
Update dependencies to compatible with latest `azdev`
---
> {Packaging} Update dependencies

- src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_disk_access_private_endpoint.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_disk_access.yaml
network private-endpoint-connection approve/show/reject
network private-link-resource list
Bump Resource Type `DISKACCESSES/PRIVATEENDPOINTCONNECTIONS` and `DISKACCESSES/PRIVATELINKRESOURCES` API Version to 2023-04-02
{Network} `network private-endpoint-connection approve/show/reject`: Bump DISKACCESSES API Version to 2023-04-02
{Network} `network private-link-resource list`: Bump DISKACCESSES API Version to 2023-04-02
---
> {Network} `network private-endpoint-connection approve/show/reject`/`network private-link-resource list`: Bump DISKACCESSES API Version to 2023-04-02

- src/azure-cli/azure/cli/command_modules/network/_format.py
continuous fix of https://github.com/Azure/azure-cli/pull/25388
---
> [Network] `az network nsg rule list`: Fix ranges and prefixes disappeared with `-o table` option

- .github/policies/resourceManagement.yml
- .github/workflows/AddIssueComment.yml
- .github/workflows/BlockPRMerge.yml
1. Add a new label `Azure Deployments` for `az deployment\bicep\stack\deployment-scripts\ts\group export` issues 
2. Prevent Merge on "do-not-merge" Label
Add "do-not-merge" label
Remove "do-not-merge" label
---
> {CI} Update bot config

- src/azure-cli/azure/cli/command_modules/keyvault/_params.py
`az keyvault create/update-hsm`
`az keyvault backup/restore start`
GA MHSM user assigned managed identity feature
[Keyvault] `az keyvault create/update-hsm`: GA `--mi-user-assigned`
[Keyvault] `az keyvault backup/restore start`: GA `--use-managed-identity`
---
> {Keyvault} GA mhsm user assigned identity

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_kubenet_to_cni_overlay_migration.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
Allow aks clusters to update their `network-plugin` property from the cli. This allows clusters using kubenet
to upgrade to CNI Overlay. See https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay?tabs=kubectl#upgrade-an-existing-cluster-to-cni-overlay for more information.
1. Create an aks cluster with kubenet - `az aks create -n mycluster -g myrg --network-plugin kubenet`
2. Update the cluster to migrate from kubenet to cni overlay - `az aks update -n mycluster -g myrg --network-plugin azure --network-plugin-mode overlay`
[AKS] `az aks update`: Add parameter `--network-plugin` to update the network plugin of the AKS cluster
---
This checklist is used to make sure that common guidelines for a …
> [AKS] `az aks update`: Add parameter `--network-plugin` to Update command to support migrating to Azure CNI Overlay

- src/azure-cli/azure/cli/command_modules/eventhubs/aaz/latest/eventhubs/georecovery_alias/_create.py
- src/azure-cli/azure/cli/command_modules/eventhubs/tests/latest/recordings/test_eh_alias.yaml
- src/azure-cli/azure/cli/command_modules/eventhubs/tests/latest/test_eventhub_commands_alias_test.py
- src/azure-cli/azure/cli/command_modules/servicebus/aaz/latest/servicebus/georecovery_alias/_create.py
[EventHub] `az eventhubs georecovery-alias create`: Name parameter is required
[ServiceBus] `az servicebus georecovery-alias create`: Name parameter is required
---
> [EventHub/ServiceBus] `az eventhubs georecovery-alias create` `az servicebus georecovery-alias create` parameter-name is required for this cmdlets

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_vmss_proxy_agent.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
`az vm create/update`
`az vmss create/update`
VM/VMSS to support Azure Metadata Security Protocol
close https://github.com/Azure/azure-cli/issues/27729
---
> [Compute] `az vm/vmss create/update`: Add new parameters `--enable-proxy-agent` and `--proxy-agent-mode` to support azure metadata security protocol

- doc/extensions/versioning_guidelines.md
> {doc} Add extension versioning doc

- src/azure-cli/azure/cli/command_modules/storage/docs/ADLS Gen2.md
Typo `mymewfilesystem` -> `mynewfilesystem`
---
> {Storage} `az storage fs directory/file move`: Fix typo in ADLS Gen2.md

- src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/custom.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/_test_utils.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_webapp_app_insights_e2e.yaml
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/test_springboot_cosmossql_scenario.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/test_springcloud_connection_scenario.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/test_webpp_connection_scenario.py
az webapp/containerapp/spring connection create/update app-insights --source-id <source-id> --secret --target-resource-group <target-group> --app-insights <app-insights-name> --client-type <client-type>
This PR supports App Insights as target service for Service Connector. 
Create connection: az webapp connection create app-insights --resource-group <group> --name <webapp-name> --target-resource-group <target-group> --app-insights <app-insights-name> --secret --client-type dotnet
Update connection: az webapp connection create app-insights --id <connection-id> --secret --client-type dotnet
[Component Name 2] `az command b`: …
> {Service Connector} `az webapp/containerapp/spring connection create/update app-insights`: Support App Insights as target service

- src/azure-cli/azure/cli/command_modules/monitor/_params.py
{Monitor} `az monitor metrics list`: Fix `--top` help message
---
> {Monitor} `az monitor metrics list`: Fix `--top` help message

- src/azure-cli/azure/cli/command_modules/network/commands.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_nat_rule.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Fix: https://github.com/Azure/azure-cli/issues/28131
---
> [Network] Fix #28131: `az network vnet-gateway list`: Conflict key when apply client flatten

- src/azure-cli/azure/cli/command_modules/serviceconnector/_credential_free.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/action.py
> [Service Connector] `az webapp connection create sql`: Support auto install for serviceconnector-passwordless extension

- src/azure-cli/azure/cli/command_modules/storage/_help.py
> {Storage} Fix #28069: `az storage account file-service-properties update`:  Fix `--channel-encryption` in example

- src/azure-cli/azure/cli/command_modules/network/custom.py
> {Network} `az network vnet subnet`: Refine help messages

- src/azure-cli/azure/cli/command_modules/mysql/_help.py
az mysql flexible-server import create
This PR adds the logic for firewall rule migration from single server to flex server for a public access enabled server.
---
> {Mysql} az mysql flexible-server import create: Fix import cli doc

- src/azure-cli/azure/cli/command_modules/storage/docs/ADLS Gen2.md
Fix capitalization typo `FOr` -> `For` in the docs page [storage/docs/ADLS Gen2.md](https://github.com/Azure/azure-cli/pull/28308/files#diff-450814fc73cb602fe4170b8134a5b8fb3ab9d2817ad84d50221f22eed39b404e).
---
> {Storage} Fix typo (capitalization) in docs/ADLS Gen2.md

- scripts/live_test/CLITest.yml
- scripts/live_test/generate_index.py
- scripts/live_test/sendemail.py
- scripts/live_test/upload.py
> {CI} Modify live test pipeline to use service principal

- src/azure-cli/azure/cli/command_modules/appservice/_params.py
`az appservice plan create`
Update help message of `--hyper-v` parameter in `az appservice plan create` command to make it more intentional and accurate.
Tested locally and made sure new help text shown 
---
> {App Service} `az appservice plan create`: Update help message of `--hyper-v` parameter

- src/azure-cli-core/azure/cli/core/telemetry.py
Fix #28312  See comments for explanation
---
> {Core} Fix #28312: Fix ValueError for getting `clients.show_secrets_warning` config in telemetry

- src/azure-cli/azure/cli/command_modules/vm/aaz/latest/vmss/nic/_list.py
- src/azure-cli/azure/cli/command_modules/vm/aaz/latest/vmss/nic/_list_vm_nics.py
- src/azure-cli/azure/cli/command_modules/vm/aaz/latest/vmss/nic/_show.py
`az vmss nic list`
`az vmss nic show`
`az vmss nic list-vm-nics`
Close: #28342 
aaz PR: https://github.com/Azure/aaz/pull/410
---
> [Compute] `az vmss nic`: Update help messages to guild users to specific commands for Flexible VMSS

- src/azure-cli/azure/cli/command_modules/mysql/commands.py
az mysql flexible-server import create
Removed the preview tag from the command as the feature is GA.
> {Mysql} az mysql flexible-server import create: Remove preview tag

- src/azure-cli/setup.py
This PR is to build packaging error with config.json file missing
---
- [X ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).
- [X ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).
> {RDBMS} Add missing config.json to rdbms package data to fix packaging error

- src/azure-cli/azure/cli/command_modules/cdn/custom/custom_rule_util.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_afd_rule_crud.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_afd_rule_scenarios.py
fix https://github.com/Azure/azure-cli/issues/28240
---
> [CDN] Fix #28240: `az afd rule create`: Cannot create without condition

- src/azure-cli/azure/cli/command_modules/cdn/custom/custom_afdx.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_afd_route_crud.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_afd_route_scenarios.py
Fix https://github.com/Azure/azure-cli/issues/28223
---
> [CDN] Fix #28223: `az afd route create`: Cannot create without `--content-types-to-compress`

- src/azure-cli/azure/cli/command_modules/mysql/_util.py
az mysql flexible-server import
Changed the default message to Running.
Tested locally.
---
> [Mysql] `az mysql flexible-server import create`: Change the default progress message from starting to running

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/express_route/gateway/_create.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/express_route/gateway/_delete.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/express_route/gateway/_list.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/express_route/gateway/_show.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/express_route/gateway/_update.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/express_route/gateway/_wait.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet_gateway/_create.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet_gateway/_update.py
- src/azure-cli/azure/cli/command_modules/network/linter_exclusions.yml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_allow_traffic.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
closed: https://github.com/Azure/azure-cli/issues/27854
[Network] `az network vnet-gateway`: Add parameters `--allow-remote-vnet-traffic` and `--allow-vwan-traffic`
[Network] `az network express-route gateway`: Add parameter `--allow-non-vwan-traffic`
---
> {Network} `az network vnet-gateway`: Add parameters `--allow-remote-vnet-traffic` and `--allow-vwan-traffic`

- src/azure-cli/azure/cli/command_modules/cdn/commands.py
- src/azure-cli/azure/cli/command_modules/cdn/custom/custom_afdx.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_afd_origin_group_crud.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_afd_origin_group_scenarios.py
fix https://github.com/Azure/azure-cli/issues/27744
---
> [CDN] Fix #27744: `az afd origin-group`: Add parameter `--enable-health-probe`

- src/azure-cli/azure/cli/command_modules/vm/_validators.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_trusted_launch.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
`az vm create`
Close: #28397
---
> [Compute] Fix #28397: `az vm create`: Fix creating VM with `--security-type Standard`

- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_show_list_sizes_list_ip_addresses.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_add_application.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_add_application_empty_version_ids.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_add_application_with_config_override.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_add_application_with_order_application.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
> [Compute] `az vmss application set`: Fix upates to the purchase plan are not supported when updating VMSS

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_loadbalancer_then_update.yaml
`az aks` 
Update test artifacts in acs. related pr: #28273
---
> {AKS}:Update test artifacts in acs

- src/azure-cli-core/azure/cli/core/telemetry.py
GDPR may not detect properties which are not `str` type, so this PR switch `Context.Dafault.VS.Core.Istty` and `Context.Default.AzureCLI.SecretsDetected` from `bool` type to `str` type
---
> {Telemetry} Switch telemetry bool properties to str type

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_enable_dapr.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py
`az functionapp config container set`
1. Make HTTP read buffer size and HTTP max request size default to 4 if no values were provided 
2. Set daprConfig to null if it is disabled
3. Throw exception to warn customer that if daprConfig is disabled, the other dapr-related attributes are not valid
1. `az functionapp create ... --enable-dapr false` should set daprConfig to null
2. `az functionapp create ... --enable-dapr true` requires --dapr-app-id to be passed (validation is thrown from the backend)
3. `az functionapp create ... --enable-dapr true --dapr-app-id` will create the daprConfig
4.`az functionapp config container set --enable-dapr false` will set daprConfig to null
5. `az functionapp config container set …
> {AppService} `az functionapp create`: Updating DAPR config to match experience in Portal

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/commands.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_azure_service_mesh_enable_disable.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_azure_service_mesh_get_revisions.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_azure_service_mesh_get_upgrades.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_azure_service_mesh_with_ingress_gateway.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_azure_service_mesh_with_pluginca.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
`az aks create --enable-azure-service-mesh`
Add optional parameter `--revision` to set revision for the Azure Service Mesh addon while creating AKS cluster.
Implicitly enable istio when ingress gateway is enabled for Azure Service Mesh.
`az aks create -g MyResourceGroup -n MyManagedCluster --enable-azure-service-mesh --revision asm-1-18`
`az aks mesh enable-ingress-gateway -g MyResourceGroup -n MyManagedCluster`
> [AKS] `az aks create`: Add optional parameter `--revision` to set revision for the Azure Service Mesh addon while creating AKS cluster

- src/azure-cli/azure/cli/command_modules/sql/_help.py
Update `--database-format` and `--pricing-model` parameters examples in `sql mi` cmdlet.
Fix example values for `--database-format` and `--pricing-model` parameters.
---
> {SQL} `az mi create/update`: Update `--database-format` and `--pricing-model` parameters examples.

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_create.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_list.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_list_by_type.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_show.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_update.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_alias.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_tmlink.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_dns_commands.py
az network dns record-set cname
We are adding new experimental property TrafficManagementProfile for record set APIs. Corresponding commands changes [Azure/aaz#425](https://github.com/Azure/aaz/pull/425)
---
> [Network] `az network dns record-set`: Add `--traffic-management-profile` for TMLink recordset feature

- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_waf_policy_managed_rules.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
closed: https://github.com/Azure/azure-cli/issues/28210
---
> [Network] `az network application-gateway waf-policy`: Change default rule set from CRS3.0 to DRS2.1

- src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/afd/profile/_create.py
- src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/afd/profile/_update.py
- src/azure-cli/azure/cli/command_modules/cdn/custom/custom_afdx.py
- src/azure-cli/azure/cli/command_modules/cdn/linter_exclusions.yml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_afd_profile_crud.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_afd_profile_scenarios.py
> [CDN] `az afd profile`: Add parameter `--identity`

- src/azure-cli-core/azure/cli/core/commands/__init__.py
- src/azure-cli-core/azure/cli/core/telemetry.py
After we add credential detection and warnings in cli core, we want to log which properties are detected as secrets, so add this info in telemetry
---
> {Core} Log the detected secrets' property name in telemetry

- src/azure-cli/azure/cli/command_modules/vm/custom.py
relate: https://github.com/Azure/azure-cli/issues/28557
---
> [Compute] `az sig image-definition create`: Add warning message for Hyper-V generation and Security Type

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
change the location of kms-related test from centraluseuap to westcentralus.
Only for test.
---
> {AKS} change the location of kms-related test from centraluseuap to westcentralus

- .github/workflows/AddPRComment.yml
- .github/workflows/BlockPRMerge.yml
> [CI] Limit workflow target branches

- .github/workflows/BlockPRMerge.yml
blockedLabels = ["do-not-merge", "needs-author-feedback"];
---
> {CI} Block PR merge on blocked labels

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_api_server_authorized_ip_ranges.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_blb_vmas.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_blb_vmas_msi.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_default_setting.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_default_setting_msi.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_slb_vmss_with_default_mgd_outbound_ip_then_update.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_slb_vmss_with_default_mgd_outbound_ip_then_update_msi.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_slb_vmss_with_outbound_ip_prefixes_then_update.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_slb_vmss_with_outbound_ip_prefixes_then_update_msi.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_slb_vmss_with_outbound_ip_then_update.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_slb_vmss_with_outbound_ip_then_update_msi.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_managed_identity_without_service_principal.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_private_cluster.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Fix the load balancer sku in the following test cases.
- test_aks_create_blb_vmas
- test_aks_api_server_authorized_ip_ranges
- test_aks_create_blb_vmas_msi
- test_aks_create_slb_vmss_with_outbound_ip_prefixes_then_update
- test_aks_create_slb_vmss_with_outbound_ip_prefixes_then_update_msi
- test_aks_create_slb_vmss_with_outbound_ip_then_update
- test_aks_create_slb_vmss_with_outbound_ip_then_update_msi
- test_aks_create_default_setting
- test_aks_create_default_setting_msi
- test_aks_create_slb_vmss_with_default_mgd_outbound_ip_then_update
- test_aks_create_slb_vmss_with_default_mgd_outbound_ip_then_update_msi
- test_aks_private_cluster
- test_aks_managed_identity_without_service_principal
Per [API …
> {AKS} Fix load balancer sku in some test cases

- src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
{AKS} Correct error message when updating outbound type. Depending on the current configuration of the cluster, the outbound types that can be migrated to are different.
Related to issue #27990.
---
> {AKS} Correct error message when updating outbound type

- .github/CODEOWNERS
Remove owner longer on project
---
> {RDBMS} Update code owners for rdbms

- src/azure-cli/azure/cli/command_modules/vm/_help.py
> {Compute} `az vm user update`: Add more details in the help message

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
- src/azure-cli/azure/cli/command_modules/vm/_vmss_application_health.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_set_rolling_upgrade_policy_during_creation.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_with_max_surge.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
`az vmss create/update`
Set upgrade policy to Rolling and configure the rolling upgrade policy during VMSS creation, currently only supports Uniform mode, Flexible mode needs to be supported after June, currently it behind an AFEC flag.
After creation, there are other commands that can set the upgrade policy to rolling, and @mimckitt also agrees that it is unnecessary to nest other commands together
https://github.com/Azure/azure-cli/blob/0b94accd014acff4393830e355a1e587334636cf/src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py#L5482-L5511
close https://github.com/Azure/azure-cli/issues/28439
close https://github.com/Azure/azure-cli/issues/28440
[Compute] `az vmss create`: Add support of …
> [Compute] `az vmss create`: Add support of configure the rolling mode upgrade policy during VMSS creation

- .github/policies/resourceManagement.yml
> {CI} Config assignee for modules

- .github/policies/resourceManagement.yml
> {CI} Distinguish `az network/az network bastion/az network dns` and route to the corresponding service team

- src/azure-cli/azure/cli/command_modules/resource/_bicep.py
- src/azure-cli/azure/cli/command_modules/resource/_params.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_bicep.py
`az bicep`
Support additional process architectures with Bicep CLI. Closes #27333.
`az bicep install`
[ARM] `az bicep install`: Support additional process architectures with Bicep CLI
---
> [ARM] `az bicep install`: Support additional process architectures with Bicep CLI

- src/azure-cli/azure/cli/command_modules/serviceconnector/_utils.py
> {Service Connector} `az webapp connection create`: Fix non-json output issue

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/_validators.py
- src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/linter_exclusions.yml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_nodepool_add_with_disable_windows_outbound_nat.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_validators.py
```
az aks nodepool add --name npwin --os-type Windows --disable-windows-outbound-nat
```
[AKS] Add option `--disable-windows-outbound-nat` for `az aks nodepool add` to add a Windows agent pool which the Windows OutboundNAT is disabled
Refer to [aks-preview PR](https://github.com/Azure/azure-cli-extensions/pull/5456/files)
azdev test --live test_aks_nodepool_add_with_disable_windows_outbound_nat
[AKS] Add option `--disable-windows-outbound-nat` for `az aks nodepool add` to add a Windows agent pool which the Windows OutboundNAT is disabled
---
> [AKS] `az aks nodepool add`: Add `--disable-windows-outbound-nat` to add a Windows agent pool which the Windows OutboundNAT is disabled

- src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_link_managed_environment.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
Add private link support for Microsoft.App
---
> [Network] `az network private-endpoint-connnection`: Add Microsoft.App/managedEnvironment for private endpoint connections

- src/azure-cli/azure/cli/command_modules/network/_client_factory.py
- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/_validators.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/zone/_create.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/zone/_list.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/zone/_update.py
- src/azure-cli/azure/cli/command_modules/network/commands.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone_commands_with_dnssec_zone.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone_update.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone_update_if_match.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_dns_commands.py
az network dns zone update
az network dns zone create
az network dns zone list
*  `az network dns zone (create|update)`: Arguments `--zone-type`, `--registration-vnets` and `--resolution-vnets`, which are deprecated are no longer supported.  
*  `az network dns zone update` uses the autogenerated command model, specific test coverage added.
*  `az network dns zone list` updated with autogenerated code, supports pagination arguments. 
* Corresponding aaz change: https://github.com/Azure/aaz/pull/444
* Use this command to create a zone $zone in resource group $rg:
`az network dns zone create -g $rg  -n $zone`
* Use this command to update an existing zone $zone in resource group $rg:
`az network dns zone update-g $rg  -n $zone`
* Use this …
> [Network] BREAKING CHANGE: `az network dns zone`: Deprecate `--zone-type`, `registration-vnets` and `resolution-vnets`

- src/azure-cli/azure/cli/command_modules/mysql/_validators.py
- src/azure-cli/azure/cli/command_modules/mysql/custom.py
az mysql flexible-server import create
This PR adds changes to make sure username is always null in the API. The username is fetched from the single server in the backend.
---
> {Mysql} `az mysql flexible-server import create`: Update username value to be always null

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
`az functionapp deployment source config-zip`
- `az functionapp create` will no longer show the functions version warning for flex apps since that app setting is not relevant for the flex sku
- `az functionapp deployment source config-zip` will show the deployment ID
- `az functionapp deployment source config-zip` will not show an error message if the first `deployment/latest` status response was a 202 and is then followed by a 404 since that is likely just from the kudu pod getting recycled
- [AppService] `az functionapp create`: This command will no longer show the functions version warning for flex apps since that app setting is not relevant for the flex sku
- [AppService] `az functionapp …
> [AppService] `az functionapp`: Update messaging for flex function apps

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_list_show_details.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
`az webapp list`
`az webapp list` is throwing unexpected error while using `--show-details` without specifying parameter `-g`. It is not an expected behavior and this PR is used to fix the bug.
Run test created for the command or run command `az webapp list --show-details`  
---
> [AppService] `az webapp list`: Fix the bug `--show-details` fails while resource group name is not specified

- doc/extensions/versioning_guidelines.md
- src/azure-cli-core/azure/cli/core/extension/operations.py
- src/azure-cli-core/azure/cli/core/tests/test_extension.py
- src/azure-cli/azure/cli/command_modules/util/custom.py
According current analysis for extension modules (May 10 2024), roughly 50% extension modules will fail in first installation try cause they do not have stable release candidates. Default value change from `True` to be `False` would cause huge impact in customer experience and related cli and partner team pipelines, therefore, postponed this default value switch in future release.  See related pr linked.
---
> {doc} `az extension add/update` and `az upgrade`: Update `allow-preview` warning message

- src/azure-cli/azure/cli/command_modules/containerapp/custom.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_ingress_update_http_to_tcp.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_commands.py
Fix issue: https://github.com/Azure/azure-cli/issues/28864
---
> [Container app] Fix #28864: `az containerapp ingress update`:  Fix updating transport from http to tcp with `--transport tcp`

- src/azure-cli/azure/cli/command_modules/keyvault/_validators.py
- src/azure-cli/azure/cli/command_modules/keyvault/commands.py
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_hsm_key_release_policy.yaml
`az keyvault key create`
Close #28720 
---
> [Keyvault] `az keyvault key create`: Update the release policy used for `--default-cvm-policy`

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_on_linux_app_service_dotnet_with_runtime_version.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_on_windows_app_service_dotnet_with_runtime_version.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py
Currently, Windows dotnet apps use the [default netFrameworkVersion from the SDK](https://github.com/Azure/azure-sdk-for-python/blob/9056bd8899e449964bd3ae3b3cff3714ba7318c7/sdk/appservice/azure-mgmt-web/azure/mgmt/web/v2023_01_01/models/_models_py3.py#L20910C1-L20910C1)
The reason why we have to access additionalProperties to fetch netFrameworkVersion is because [netFrameworkVersion is not part of SiteConfigPropertiesDictionary](https://github.com/Azure/azure-sdk-for-python/blob/9056bd8899e449964bd3ae3b3cff3714ba7318c7/sdk/appservice/azure-mgmt-web/azure/mgmt/web/v2023_01_01/models/_models_py3.py#L21252-L21265) in the SDK. 
Resolves #23827
Create Windows dotnet app and make sure that the netFrameworkVersion set …
> [AppService] `az functionapp create`: Use stacks API netFrameworkVersion value

- src/azure-cli/azure/cli/command_modules/containerapp/custom.py
`az containerapp job create`
`az containerapp job update`
This command changes the referenced documentation link.
---
> {Containerapp} Fix documentation links for job yaml

- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
MHSM tests always fail in live test pipeline as there's restrictions that we can't create more than 5 MHSM pools in the same region. This PR marks MHSM tests serial to increase the success rate
---
> {Keyvault} Refine MHSM tests

- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_sig_image_definition_default_value.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
close: https://github.com/Azure/azure-cli/issues/28557
---
> [Compute] BREAKING CHANGE: `az sig image-definition create`: Set the default values for Hyper-V generation and Security Type

- src/azure-cli/azure/cli/command_modules/network/operations/load_balancer.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_rule_backend_address_pools.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_rules.yaml
Fix: https://github.com/Azure/azure-cli/issues/28705
---
> [Network] Fix #28705: `az network lb rule`: Authentication token not being generated

- src/azure-cli/azure/cli/command_modules/sql/_help.py
Improve the import help message. This fixes #14646
---
> {SQL} `az sql db import`: improve help message

- src/azure-cli-core/azure/cli/core/_profile.py
`az login`
When WAM is enabled, `AADSTS` error code is no longer included in `error_description` property of the MSAL error (https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/698). MSAL.PY also has no clear indicator for `InteractionRequired` (https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/701).
So, we no longer detects `AADSTS50076` and tell the user the error is caused by MFA. Instead, we unconditionally prompt for interactive authentication for all silent authentication failures.
`az login` with an account that requires MFA for non-home tenants.
Output:
```
Silent authentication fails for tenant 54826b22-38d6-4fb2-bad9-b7b93a3e9c5a 'AzureSDKTeam': (pii). Status: …
```
> [Core] Prompt for interactive authentication for all silent authentication failures

- src/azure-cli-core/azure/cli/core/_profile.py
`az login`
Refine the warning message from https://github.com/Azure/azure-cli/pull/28966.
Technical details ("silent authentication" and "interactive authentication") are removed from the warning message.
> {Core} Refine warning message for interaction required

- src/azure-cli-core/azure/cli/core/aaz/_arg.py
- src/azure-cli-core/azure/cli/core/tests/test_aaz_arg.py
> {Core} Fix warning message for `support_extension`

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/waf_policy/_create.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/waf_policy/_update.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/waf_policy/policy_setting/_update.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_waf_policy_setting.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
colsed: https://github.com/Azure/azure-cli/issues/28598
---
> [Network] `az network application-gateway waf-policy custom-rule update`: Add parameter `--js-cookie-exp-time`

- src/azure-cli/azure/cli/command_modules/acs/_help.py
{AKS} `az aks create`: Update help message of option `--enable-managed-identity`
---
> {AKS} `az aks create`: Update help message of option `--enable-managed-identity`

- src/azure-cli/azure/cli/command_modules/containerapp/_clients.py
- src/azure-cli/azure/cli/command_modules/containerapp/_help.py
- src/azure-cli/azure/cli/command_modules/containerapp/commands.py
- src/azure-cli/azure/cli/command_modules/containerapp/custom.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_get_customdomainverificationid_e2e.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_commands.py
az containerapp show-custom-domain-verification-id
Move https://github.com/Azure/azure-cli-extensions/pull/6672 to azure-cli due to command is ready for GA.
---
> [Container app] `az containerapp show-custom-domain-verification-id`: Show verification id used for binding custom domain

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
`az vmss update`
VMSS Zonal Expansion
close https://github.com/Azure/azure-cli/issues/28900
---
> [Compute] `az vmss update`: Add new parameter `--zones` to support setting vmss zonal expansion

- src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/amw/helper.py
- src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/amw/tests/test_helper.py
> [AKS] `az aks create/update`: Update AMW resource.location to only accept alphanumeric characters

- src/azure-cli/azure/cli/command_modules/network/operations/load_balancer.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_cross_region_lb_address_pool_addresses.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
close: https://github.com/Azure/azure-cli/issues/28917
---
> [Network] `az network cross-region-lb address-pool`: Add parameter `-- admin-state`

- src/azure-cli/azure/cli/command_modules/containerapp/_clients.py
- src/azure-cli/azure/cli/command_modules/containerapp/_help.py
- src/azure-cli/azure/cli/command_modules/containerapp/_transformers.py
- src/azure-cli/azure/cli/command_modules/containerapp/commands.py
- src/azure-cli/azure/cli/command_modules/containerapp/custom.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_env_usages.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_env_commands.py
* `az containerapp list-usages`: list usages in subscription
* `az containerapp env list-usages`: list usages in environment
We have supported these 2 commands in `azure-cli-extensions` for a while, now they are ready to GA.
---
> [Container app] `az containerapp list-usages`: Support list-usages in subscription

- src/azure-cli/azure/cli/command_modules/containerapp/containerapp_auth_decorator.py
> {Containerapp} Avoid to use same function name with extension containerapp

- azure-pipelines-full-tests.yml
- azure-pipelines.yml
> {CI} Temporarily disable these tasks before migrating to managed identity.

- src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/cdn/endpoint/_update.py
- src/azure-cli/azure/cli/command_modules/cdn/custom/custom_cdn.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_endpoint_compression.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_endpoint_crud.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_microsoft_sku_origingroup_override.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_origin_crud.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_afd_custom_domain_scenarios.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_afd_endpoint_scenarios.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_afd_log_analytic_scenarios.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_afd_origin_group_scenarios.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_afd_origin_scenarios.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_afd_profile_scenarios.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_afd_route_scenarios.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_afd_rule_scenarios.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_afd_secret_scenarios.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_afd_security_policy_scenarios.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_custom_domain_scenarios.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_endpoint_scenarios.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_origin_scenarios.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_profile_scenarios.py
fix https://github.com/Azure/azure-cli/issues/28733
> [CDN] Fix 28733: `az cdn endpoint update`: Cannot update an existing endpoint

- .github/CODEOWNERS
> {AppConfig} Update owners app config owners list

- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_azure_service_mesh_canary_upgrade.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_azure_service_mesh_enable_disable.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_azure_service_mesh_get_revisions.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_azure_service_mesh_get_upgrades.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_azure_service_mesh_with_ingress_gateway.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_azure_service_mesh_with_pluginca.yaml
This reverts commit 3abcc5f8b82e6ccd7f8e47423f2cf86840728c0a.
---
> {AKS} `az aks mesh`: Revert #29096

- azure-pipelines.yml
- scripts/ci/credscan/CredScanSuppressions.json
Last Saturday, this task `ms-codeanalysis.vss-microsoft-security-code-analysis-devops.build-task-credscan.CredScan@2` began failing unexpectedly with the following error message: 
We have sent an email and created an ICM.
But progress is very slow, and many users' PRs have been blocked by this CI task.
And I found out that these two tasks have been deprecated.
- ms-codeanalysis.vss-microsoft-security-code-analysis-devops.build-task-credscan.CredScan@2
- ms-codeanalysis.vss-microsoft-security-code-analysis-devops.build-task-postanalysis.PostAnalysis@1
So we decided to switch to the `securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@3` and `securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@2`
Related …
> {CI} Switch CredScan task

- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_env_certificate_e2e.yaml
> {Containerapp} Fix recording file

- src/azure-cli/azure/cli/command_modules/appconfig/_help.py
- src/azure-cli/azure/cli/command_modules/appconfig/_params.py
This PR updates the app config help messages. It updates the string  "**App Configuration**" to "**App Configuration store**", updates "keyvalues" strings to "key-value" and adds  the actual argument name in the description for the auth-mode. 
---
> [AppConfig] Update appconfig help messages

- .github/policies/resourceManagement.yml
1. Add Bernard Pan as reviewer for CI related PRs.
2. Add keren-shani as owner for Security related issues.
---
> {CI} Update resourceManagement.yml

- CODE_OF_CONDUCT.md
CODE_OF_CONDUCT.md Standard
[aka.ms/opensource/moderation-support](https://aka.ms/opensource/moderation-support)
> {Misc.} Add CODE_OF_CONDUCT.md

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
`az webapp deployment source config-zip`
Due to a regression in Deployment Status API, it is not working as expected for deployments to slots.
Disabling deployment status api support for slots until this is fixed in prod.
We will fallback to kudu deploy status polling for now.
* Deployment to main slot (without using --slot arg in deployment command)
* Deployment to stage slot ( passing --slot stage in deployment command)
Deploying to app slots using CLI with command `az webapp deploy` or `az webapp deployment source-config`
[App Service] `az webapp deploy`: Disable deploymentstatus API for deployments to app slots
[App Service] `az webapp deployment source config-zip`: Disable deploymentstatus API …
> [App Service] `az webapp deploy`: Disable deployment status API for slot deployments

- src/azure-cli/azure/cli/command_modules/rdbms/config.json
Removal of information from public repo. Used for testing purposes, moving forward will be injecting into JSON file. 
Manually
> {RDBMS} Remove cluster information from config file

- src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
- src/azure-cli/azure/cli/command_modules/vm/_validators.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_flexible_vmss_set_automatic_upgrade_policy_during_creation.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
support set upgrade policy to automatic during VMSS creation
close https://github.com/Azure/azure-cli/issues/29191
---
> [Compute] `az vmss create`: Support set upgrade policy mode to automatic during flexible VMSS creation

- src/azure-cli/azure/cli/command_modules/profile/_help.py
- src/azure-cli/azure/cli/command_modules/profile/custom.py
`az login`
Add warning for username password flow according to https://github.com/Azure/azure-cli/issues/28252.
```
az login --username xxx --password xxx
```
> {Profile} `az login`: Add warning for username password flow

- src/azure-cli/azure/cli/command_modules/mysql/_help.py
- src/azure-cli/azure/cli/command_modules/mysql/_params.py
- src/azure-cli/azure/cli/command_modules/mysql/_validators.py
- src/azure-cli/azure/cli/command_modules/mysql/custom.py
az mysql flexible-server deploy/update
az mysql flexible-server deploy run: add input validator to fix security issue.
az mysql flexible-server update: add user confirmation for HA enabled.
---
> [MYSQL] `az mysql flexible-server deploy/update`: Add warning message for HA enabled and input validator

- src/azure-cli/azure/cli/command_modules/compute_recommender/aaz/latest/compute_recommender/_spot_placement_recommender.py
- src/azure-cli/azure/cli/command_modules/compute_recommender/tests/latest/recordings/test_spot_placement_recommender_generate.yaml
…-01-preview version
az compute-recommender spot-placement-recommender
Upgrade az compute-recommender spot-placement-recommender  to 2024-06-01-preview version
testing command:
`az compute-recommender spot-placement-recommender -l eastus --subscription ffffffff-ffff-ffff-ffff-ffffffffffff --availability-zones true --desired-locations '["eastus", "eastus2"]' --desired-count 1 --desired-sizes '[{"sku": "Standard_D2_v2"}]'`
---
> {compute-recommender} Upgrade az compute-recommender spot-placement-recommender  to 2024-06-01-preview version

- src/azure-cli/azure/cli/command_modules/dms/_help.py
`az dms project task --help`
To resolve issues #27770 and #27787.
---
> {dms} `az dms project task`: Fix typo in dms project task help

- src/azure-cli/azure/cli/command_modules/acs/azurecontainerstorage/_validators.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_validators.py
> [AKS] `az aks create/update`: Add and fix existing validations for ephemeral disk support for Azure Container Storage

- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_sig_image_definition_default_value.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
> [Compute] `az sig image-definition create`: Fix bug about default value of Security Type

- .github/policies/resourceManagement.yml
> {doc} Update service contact list

- src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/afd/custom_domain/_create.py
- src/azure-cli/azure/cli/command_modules/cdn/custom/custom_afdx.py
Resolve https://github.com/Azure/azure-cli/issues/27309
> {afd} `az afd custom-domain create`: Update documents

- src/azure-cli/azure/cli/command_modules/cdn/custom/custom_afdx.py
resolve https://github.com/Azure/azure-cli/issues/29073
> {afd} `az afd security-policy update`: Fix unexpected internal error

- src/azure-cli/azure/cli/command_modules/cdn/custom/custom_afdx.py
Resolve https://github.com/Azure/azure-cli/issues/28717
> [CDN] Fix #28717: `az afd secret`: Change the way to access parameter

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/custom_ip/prefix/_create.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/custom_ip/prefix/_delete.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/custom_ip/prefix/_list.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/custom_ip/prefix/_show.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/custom_ip/prefix/_update.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/custom_ip/prefix/_wait.py
- src/azure-cli/azure/cli/command_modules/network/commands.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_custom_ip_prefix_crud.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_custom_ip_prefix_update_state.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
closed: https://github.com/Azure/azure-cli/issues/29164
---
> [Network] `az network custom-ip prefix create`: Add parameter `--is-parent`

- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_create_with_environment_id.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerappjob_eventtriggered_create_with_yaml.yaml
> {Containerapp} Remove secrets in files

- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_container_app_mount_azurefile_e2e.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_compose_create_environment_to_target_location.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_create_with_environment_id.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_create_with_vnet_yaml.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_env_certificate_e2e.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_env_logs_e2e.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_env_p2p_traffic_encryption.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_get_customdomainverificationid_e2e.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_tcp_ingress.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerappjob_create_with_environment_id.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerappjob_create_with_yaml.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerappjob_eventtriggered_create_with_yaml.yaml
> {Containerapp} Remove secrets

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_soft_delete.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
`az sig create/update`
Mail title: Soft Delete information on our public docs
Close: #29358
---
> [Compute] `az sig create/update`: Hide `--soft-delete` parameter in help messages

- src/azure-cli/azure/cli/command_modules/sql/_help.py
- src/azure-cli/azure/cli/command_modules/sql/_params.py
- src/azure-cli/azure/cli/command_modules/sql/custom.py
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_midb_cross_subscription_move_copy.yaml
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
- az sql midb move start
- az sql midb move complete
- az sql midb move cancel
- 
- az sql midb copy start
- az sql midb copy complete
- az sql midb copy cancel
Before this cross subscription db move/copy was not possible because we could not know the subscription of the target managed instance. In order to fix this I am adding optional parameter **--dest-subscription-id**.
This example has DestinationSubscriptionId so we assume that is different from the SourceSubscriptionId
az sql midb copy complete --name mydb --resource-group MyResourceGroup --managed-instance MyInstance --dest-mi DestinationInstance --dest-rg DestinationResourceGroup --dest-subscription-id DestinationSubscriptionId
In this example we leave it out so the …
> [SQL] `az sql midb move/copy`: Add destination subscription Id for managed database move/copy

- .github/azure-client-tools-bot/config.yml
In favor of https://github.com/Azure/azure-cli/pull/29412
> {CI} Disable similar bot

- src/azure-cli-core/azure/cli/core/extension/dynamic_install.py
> [Core] Set `allow-preview` from config for extension dynamic installation

- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/azurecontainerstorage/_helpers.py
- src/azure-cli/azure/cli/command_modules/acs/azurecontainerstorage/_validators.py
- src/azure-cli/azure/cli/command_modules/acs/azurecontainerstorage/acstor_ops.py
- src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_validators.py
> [AKS] `az aks create/update`: Add validations for PremiumV2 disk

- .github/template/non-security-comment.md
- .github/workflows/AddIssueCommentWithLabel.yml
> {CI} Add issue comment with non-security label

- src/azure-cli/azure/cli/command_modules/cdn/custom/custom_afdx.py
Resolve https://github.com/Azure/azure-cli/issues/29406
> {afd} Fix #29406: add blank and default value for enable-private-link in az origin create

- src/azure-cli/azure/cli/command_modules/serviceconnector/_help.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/_utils.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/_validators.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/custom.py
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_aca2aca_e2e.yaml
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_aca2aca_store_in_app_config.yaml
- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/test_containerapp_connection_scenario.py
az containerapp connection create containerapp --source-id <source-id> --target-id <target-id> --client-type <client-type>  --container <container-name>
az containerapp connection create containerapp --rg <source-resource-group> --name <source-app-name> --tg <target-resource-group> --target-app-name <target-app-name> client-type <client-type> --container <container-name>
This PR is to support ACA2ACA connection CLI. Auth info is not needed in this scenario.
az containerapp connection create containerapp --source-id <source-containerapp-id> --target-id <target-containerapp-id> --client-type <client-type> --container <container-name>
[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking …
> [Service Connector] `az containerapp connection create containerapp`: Support ACA2ACA connection

- src/azure-cli/azure/cli/command_modules/vm/_alias.py
This PR is to keep consistent with https://github.com/Azure/azure-rest-api-specs/pull/29870
---
> {Compute} Remove deprecated image alias

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_one_deploy_scm.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_track_runtimestatus_buildfailed.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_track_runtimestatus_runtimefailed.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_track_runtimestatus_runtimesucessful.yaml
`az webapp deployment source config-zip`
For Linux app service, we have been seeing multiple customer issues where the service side logs indicate that the file sent in the deployment request is corrupt. But we do not know the source of these errors - client, network or service.
Adding file checksum to the request header and matching that with the checksum computed on the service side would enable us to identify the root cause of these errors.
This change is only for linux app service and for local file.
Tested the following scenarios using args in launch.json
1.   `az webapp deploy -g sumali-prod-test-2023 -n dotnet-8-3108 --src-path D:\test\net8.0.zip`
2.   `az webapp deployment source config-zip -g …
> {App Service} `az webapp deploy/deployment`: Added checksum header to check file integrity in service, for linux app service

- src/azure-cli/azure/cli/command_modules/netappfiles/aaz/latest/netappfiles/pool/_create.py
- src/azure-cli/azure/cli/command_modules/netappfiles/aaz/latest/netappfiles/pool/_update.py
- src/azure-cli/azure/cli/command_modules/netappfiles/aaz/latest/netappfiles/volume/_create.py
- src/azure-cli/azure/cli/command_modules/netappfiles/aaz/latest/netappfiles/volume/_update.py
- src/azure-cli/azure/cli/command_modules/netappfiles/custom.py
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_volumesize8Tib.yaml
- src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/test_volume_commands.py
az netappfiles
This is a fix for a bug with range of allowed values for `az netappfiles volume create` and `az netappfiles volume update`  `--usage-threshold` argument.
---
> [NetAppFiles] update max for usageThreshold

- src/azure-cli/azure/cli/command_modules/acs/base_decorator.py
Refactor `validate_decorator_mode` changed in #29517
> {AKS} Refactor validate_decorator_mode

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/rule/_update.py
Fix https://github.com/Azure/azure-cli/issues/28829
---
> {network} `az network lb rule update`: Fix invalid escape in network examples

- .github/CODEOWNERS
> {CODEOWNERS} Add AllyW as `monitor` owner in CODEOWNERS

- .github/policies/resourceManagement.yml
Assign issue owner fix:
Under az account:
Only lock and management-group are assigned to XingZhou
All other commands including new commands and `az account` itself are assigned to Jiashuo Li
---
> {CI} assign issue owner

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Fix test case `test_aks_create_and_update_with_http_proxy_config`, need to enable outbound connection for the vnet subnet created in the test case, otherwise, the cluster creation would fail with error
> E           azure.core.exceptions.HttpResponseError: (VMExtensionProvisioningError) Unable to establish outbound connection from agents, please see https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/error-code-outboundconnfailvmextensionerror and https://aka.ms/aks-required-ports-and-addresses for more information.
> E           Code: VMExtensionProvisioningError
> E           Message: Unable to establish outbound connection from agents, please see https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/er …
> {AKS} Fix test case test_aks_create_and_update_with_http_proxy_config

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_nodepool_add_with_ossku.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_update_agentpool_os_sku.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Fix test case `test_aks_nodepool_add_with_ossku`. AKS would stop supporting `CBLMariner` in the near future, see #29699
---
> {AKS} Fix test case `test_aks_nodepool_add_with_ossku`

- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/nat/gateway/_create.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/nat/gateway/_list.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/nat/gateway/_update.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_natgateway_basic.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_natgateway_empty_create.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_natgateway_commands.py
> [Network] Fix #29565: `az network nat gateway create`: Add `--tags` parameter

- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_batch_operations.py
Remove `\` before `/`. 
Fix #28829 
---
> {Storage} `az storage`: Remove invalid escape

- src/azure-cli/azure/cli/command_modules/storage/_help.py
[az storage account blob-inventory-policy create](https://learn.microsoft.com/en-us/cli/azure/storage/account/blob-inventory-policy?view=azure-cli-latest#az-storage-account-blob-inventory-policy-create)
This PR fixes a typo (trough) to be through. No impact to the command, but helps the text.
None needed as this is documentation specific
---
> {Storage} `az storage account blob-inventory-policy/or-policy create`: Fix typos for help

- src/azure-cli/azure/cli/command_modules/monitor/aaz/latest/monitor/diagnostic_settings/subscription/_create.py
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_metric_namespace_special_character.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_metric_alert_scenarios.py
related issue: https://github.com/Azure/azure-cli/issues/28829
---
> {Monitor} `az monitor`: Fix invalid escapes

- azure-pipelines.yml
Use GA image to replace preview image.
Ref: https://mcr.microsoft.com/en-us/product/azurelinux/base/core/about
> {Packaging} Use Azure Linux 3 GA image

- src/azure-cli/azure/cli/command_modules/redis/commands.py
- src/azure-cli/azure/cli/command_modules/redis/custom.py
> [Redis] `az redis update`: Revert "Support `--no-wait` and default to `True`"

- .github/workflows/AddIssueComment.yml
> {CI} Temporary disable AddIssueComment.yml

- .github/workflows/AddIssueComment.yml
> {CI} Revert "Temporary disable AddIssueComment.yml"

- src/azure-cli/azure/cli/command_modules/cdn/custom/custom_afdx.py
Resolve https://github.com/Azure/azure-cli/issues/29753
> {afd} `afd origin create` Change the enable-private-link default value to `False`

- .github/workflows/TriggerReferenceDocsCI.yml
> {CI} TriggerReferenceDocsCI on release

- .github/workflows/TriggerReferenceDocsCI.yml
> {CI} Update TriggerReferenceDocsCI.yml

- src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/afd/endpoint/_purge.py
- src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/afd/origin/_create.py
- src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/afd/origin/_update.py
Resolve https://github.com/Azure/azure-cli/issues/28893
Resolve https://github.com/Azure/azure-cli/issues/29801
Resolve https://github.com/Azure/azure-cli/issues/29475
> {afd} `az afd origin create`,`az afd endpoint purge` parameters documents update

- src/azure-cli/azure/cli/command_modules/acs/_graph.py
{AKS} Remove dependency on `azure.graphrbac`. The removed code is mainly used to help users create a service principal/enterprise application, but it has long been abandoned and is not referenced by any command. In summary, the change will not be noticeable to any user.
Related to [#22649](https://github.com/Azure/azure-cli/pull/22649), [#22174](https://github.com/Azure/azure-cli/issues/22174).
---
> {AKS} Remove dependency on `azure.graphrbac`

- src/azure-cli/azure/cli/command_modules/containerapp/_clients.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_job_custom_executionstest_e2e.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_job_executionstest_e2e.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_stop_job_deprecate_arguments.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerappjob_create_with_yaml.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerappjob_eventtriggered_create_with_yaml.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerappjob_executions.py
az containerapp job stop
The Stop execution API's return format has been updated to sync with swagger spec. With this change the API just returns a 200 OK response, though on cli client, we try to convert the response to Json which causes an error.
az containerapp job stop --resource-group {} --name {} --job-execution-name {}
---
> [containerapp] Fix #29849: `az containerapp job stop`: Fix stop execution response

- linter_exclusions.yml
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet/peering/_create.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet/peering/_update.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_peering_with_params.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
according to **RE: Virtual Network- Subnet peering**
---
> [Network] `az network vnet peering`: Refine command interface of subnet peering

- src/azure-cli/azure/cli/command_modules/keyvault/_validators.py
az keyvault certificate create
Fix a typo of the error message saying an JSON instead of a JSON
There is no need to test this change
---
> {Keyvault} Fix typo

- src/azure-cli/azure/cli/command_modules/containerapp/_compose_utils.py
- src/azure-cli/azure/cli/command_modules/containerapp/_up_utils.py
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_compose_create_with_image_tag_and_use_existing_registry_server_and_password.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_compose_create_with_image_tag_and_use_existing_registry_server_from_image.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_compose_create_without_image_tag_and_use_existing_registry_server_and_password.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_compose_registries.py
`az containerapp compose create`
Fix issue: https://github.com/Azure/azure-cli/issues/29166
Currently, when image in `--compose-file-path {path-to-compose.yml}` contains `tag`, it failed with error:
```
(InvalidInputValue) Some of the properties of 'runRequest' are invalid.. InnerErrors: DockerBuildRequest:Image name 'dev:latest:20240614142829041798' is invalid.
The acceptable patterns are 'repository' or 'repository:tag'.The repository and tag names follow the standardized docker repository and tag naming conventions. Tag templates are supported within '{{' and '}}'.
Please refer to docs for more information on using image name and tag: https://aka.ms/az/acr/az-acr-build
Code: InvalidInputValue
Message: Some of the properties of 'runRequest' are …
```
> [Containerapp] Fix #29166: `az containerapp compose create`: Support image with tag and support get ACR from image

- src/azure-cli-core/azure/cli/core/breaking_change.py
If a developer creates a subcommand or subcommand group without creating its parent command group, the command group is registered as `{}` in the `command_group_table`. Previously, when announcing breaking changes on the command group, this would result in registering breaking changes for all its subcommands and subcommand groups, leading to an inconsistent display with `deprecate_info`.
This PR introduces the creation of an `AzCommandGroup` object in registering breaking changes, which will be registered in the `command_group_table` in such cases. This change ensures a consistent display of breaking changes and improves the overall management of command groups.
As an example, you can create a file `_breaking_change.py` in `dla` …
> {Core} Register Upcoming Breaking Change on Empty Command Group

- pylintrc
Disable too-many-positional-arguments ([R0917](https://pylint.readthedocs.io/en/latest/user_guide/checkers/features.html)):
Too many positional arguments (%s/%s) Used when a function has too many positional arguments.
---
> {CI} Disable too-many-positional-arguments R0917

- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_compose_create_with_image_tag_and_use_existing_registry_server_and_password.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_compose_create_with_image_tag_and_use_existing_registry_server_from_image.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_compose_create_without_image_tag_and_use_existing_registry_server_and_password.yaml
> {Containerapp} Remove secrets from recording files

- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
> {Package} Bump up azure-core to 1.31.0

- src/azure-cli/azure/cli/command_modules/serviceconnector/_transformers.py
Fix https://github.com/microsoft/azure-container-apps/issues/1296
---
> {ServiceConnector}: fix AttributeError with `--no-wait`

- .github/workflows/TriggerReferenceDocsCI.yml
> {CI} Add environment to TriggerReferenceDocsCI.yml for FIC

- src/azure-cli/setup.py
Update azure-mgmt-rdbms version in setup.py
Update azure-mgmt-rdbms version in setup.py
---
> {MySQL} Update azure-mgmt-rdbms version in setup.py

- src/azure-cli/azure/cli/command_modules/rdbms/_params.py
`az postgres flexible-server replica promote`
Fix typo in help text
Manual testing
{RDBMS} Fix typo in parameter help for postgres replica promotion
---
> {RDBMS} Fix typo in parameter help for postgres replica promotion

- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_container_acr.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_container_acr_env_var.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_manualjob_private_registry_port.yaml
- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_manualjob_registry_acr_look_up_credentical.yaml
> {Container App} Remove secrets

- src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_registry_acr_look_up_credentical.yaml
> {Containerapp} Remove secret

- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_waf_policy_with_application_gateway.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
> [Network] `az network application-gateway waf-policy managed-rule rule-set add/update`: Add allowed value `1.1` for `--version`

- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Fix will avoid updating existing data collection rules if non monitoring addon trying to enable through
az aks enable-addons
---
> {aks} Fix bug related to updating DCR when non monitoring add enabled through az aks enable-addons

- src/azure-cli/azure/cli/command_modules/sql/commands.py
az sql db geo-backup restore
Removes the preview tag
---
> [SQL] `az sql geo-backup`: Remove preview tag

- CodeQL.yml
As a client tool exposed for external users similar with SDK, we should be allowed to exclude some codeql rules
---
> {Misc.} Add codeql exclusion

- src/azure-cli/azure/cli/command_modules/extension/_breaking_change.py
- src/azure-cli/azure/cli/command_modules/util/_breaking_change.py
This pr is a pre announcement for pr: https://github.com/Azure/azure-cli/pull/30163
---
> [Core] `az extension add/update` and `az upgrade`: Pre-announcement default value change from `true` to `false` for `--allow-preview`

- src/azure-cli/azure/cli/command_modules/acs/_help.py
Remove an outdated and misleading help message about the option `--service-principal` in command `az aks create`.
---
> {AKS} Update help message

- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_public_ip.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
fix: https://github.com/Azure/azure-cli/issues/29911
---
> [Network] Fix #29911: `az network public-ip update`: IP tags crash with AttributeError

- src/azure-cli/azure/cli/command_modules/storage/_params.py
`az storage account create`, `--enable-nfs-v3` has been GA since 
https://azure.microsoft.com/en-in/updates/azure-blob-storage-nfs-30-protocol-support-generally-available/
---
> {Storage} `az storage account create`: `--enable-nfs-v3` remove preview tag

- src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py
- src/azure-cli/azure/cli/command_modules/rdbms/_params.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_commands.py
- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_backups_mgmt.yaml
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands.py
`az postgres flexible-server backup`
Adding ability to create and delete backups.
Manually
> [RDBMS] `az postgres flexible-server backup create/delete`: New commands to support creating and deleting backups on PostgreSql Flex Server

- src/azure-cli/azure/cli/command_modules/servicebus/tests/latest/recordings/test_sb_auth_rule.yaml
This is to remove secrets checked in from #29987 
---
> {ServiceBus} Remove cred in servicebus test recording

- src/azure-cli/azure/cli/command_modules/compute_recommender/aaz/latest/compute_recommender/__cmd_group.py
- src/azure-cli/azure/cli/command_modules/compute_recommender/aaz/latest/compute_recommender/_spot_placement_recommender.py
az compute-recommender spot-placement-recommender
Change the azure cli doc command status from GA to preview
---
> {compute-recommender} change compute-recommender from GA to preview

- src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/test_kubernetes_connection_scenario.py
> {Service Connector}: update test to unblock appconfig changes

- src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
> [AKS] `az aks create/update`: Fix storage pool name validation for Azure Container Storage

- .azure-pipelines/breaking-change-tests.yml
`persistCredentials: true` leave the OAuth token in the Git config after the initial fetch. The default is not to leave it., which may lead to security risks.
https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelineshttps://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines
---
> {CI} Disable persist credentials

- src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
az network private-endpoint
Update Device Update registration with the stable API version (2023-07-01)
{Network} `az network private-endpoint`: Update Device Update registration with the stable API version
---
> {Network} `az network private-endpoint`: Update Device Update registration with the stable API version

- src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
> [Service Connector] `az connection create mysql-flexible`: Add `--private-endpoint` parameter

- .github/policies/resourceManagement.yml
Update resourceManagement.yml for Synapse, wonner is no longer used by Wan Yang, use wanyang7 instead.
> {Misc.} Update resourceManagement.yml

- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_access_restriction_commands.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Skip the tests temporarily to unblock CI:
---
> {App Service} Skip tests to unblock CI

- src/azure-cli/azure/cli/command_modules/backup/custom.py
`az backup`
Adding a paired region (westus3) for the southeastus region.
---
> {Backup} Update paired region for southeastus

- tools/Github/ParseServiceContactsList.ps1
Sync-alias pipeline: Remove label added trigger as it prevented auto labeled actions to be triggered.
Pipeline test run triggered sync alias PR: https://github.com/Azure/azure-cli/pull/30329/files
---
> {CI} remove added label condition for resourceManagement.yml script

- azure-pipelines.yml
Simplify CVE checks in images.
> {CI} Show installed packages in docker image

- src/azure-cli/azure/cli/command_modules/containerapp/_validators.py
`az containerapp exec`:
Currently, for a containerapp on **connectedEnvironment**, when the ingress enable, with command `az containerapp exec` it got following error when no `--replica` input:
`Not Found({"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.App/managedEnvironments/arc-appint-ea-s-env0' under resource group 'arc-appint-ea-s-rg0' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}})`
Only for containerapp on **managedEnvironment**, we should check if the environment is internal.
---
This …
> [Containerapp] `az containerapp exec`: Fix `ResourceNotFound` error

- pylintrc
- src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/amw/defaults.py
Fix [`raising-bad-type`](https://pylint.pycqa.org/en/latest/user_guide/messages/error/raising-bad-type.html) pylint error.
> {Pylint} Fix raising-bad-type

- pylintrc
- src/azure-cli/azure/cli/command_modules/acs/base_decorator.py
- src/azure-cli/azure/cli/command_modules/botservice/kudu_client.py
Fix `unused-private-member`: https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/use-maxsplit-arg.html
> {Pylint} Fix unused-private-member

- azure-pipelines.yml
- scripts/ci/codegen_report.py
> {CI} Enable CodegenCoverage and drop kusto

- src/azure-cli/azure/cli/command_modules/keyvault/_client_factory.py
`az keyvault key/secret/certificate`
Fix https://github.com/Azure/azure-cli/issues/30352
Follow the guide in https://devblogs.microsoft.com/azure-sdk/guidance-for-applications-using-the-key-vault-libraries/#additional-recommended-actions
---
> {Keyvault} Set `verify_challenge_resource` to `False`

- src/azure-cli/azure/cli/command_modules/storage/commands.py
- src/azure-cli/azure/cli/command_modules/storage/operations/account.py
[Storage] `az storage account migration`: Add warning for long wait, will require confirmation in the future
---
> [Storage] `az storage account migration`: Add warning for long wait, will require confirmation in the future

- azure-pipelines.yml
> {CI} Add continueOnError for CodegenCoverage

- .github/workflows/CCOA.yml
> {CI} Add ccoa announcement

- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2018_03_01/test_vm_image.py
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/test_vm_image.py
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/test_vm_image.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_image.py
Put `test_read_images_from_alias_doc` test into `LiveScenarioTest` instead of `unittest.TestCase` since `list_vm_images` is a heavy operation and requires network access.
Refer to: https://github.com/Azure/azure-cli/pull/26543#discussion_r1577349509
---
> {Compute} Fix tests of VM image

- src/azure-cli-core/azure/cli/core/commands/progress.py
- src/azure-cli-testsdk/azure/cli/testsdk/scenario_tests/base.py
- src/azure-cli/azure/cli/command_modules/acs/_validators.py
> {Misc} Remove __future__ Python 2.7 imports

- pylintrc
- src/azure-cli/azure/cli/command_modules/acs/addonconfiguration.py
- src/azure-cli/azure/cli/command_modules/backup/custom_common.py
- src/azure-cli/azure/cli/command_modules/cdn/custom/custom.py
- src/azure-cli/azure/cli/command_modules/storage/azcopy/util.py
- src/azure-cli/azure/cli/command_modules/vm/_validators.py
- src/azure-cli/azure/cli/command_modules/vm/azure_stack/_validators.py
- src/azure-cli/azure/cli/command_modules/vm/azure_stack/custom.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
Fix [`consider-using-enumerate`](https://pylint.readthedocs.io/en/stable/user_guide/messages/convention/consider-using-enumerate.html) pylint error.
> {Pylint} Fix consider-using-enumerate

- src/azure-cli/azure/cli/command_modules/sql/commands.py
az sql db ltr-policy
az sql db ltr-backup
az sql db str-policy 
Removing the preview tag from the commands mentioned above. 
---
> [SQL] `az sql db ltr-policy`: Remove preview tag

- src/azure-cli/azure/cli/command_modules/acs/custom.py
Workaround for issue #29948, wrapping a specific SSL error to provide more detailed guidance to users on how to resolve issues where requests using an inappropriate cert store are being made.
Related to #19305.
---
> {AKS} `az aks install-cli`: Add error message wrapper

- src/azure-cli/azure/cli/command_modules/rdbms/validators.py
Sort the version number, sku name when displaying the error message
{RDBMS} `az postgres flexible-server create`: Sort version number, sku name when displaying the error message
---
> {RDBMS} `az postgres flexible-server create`: Sort version number, sku name when displaying the error message

- build_scripts/windows/scripts/build.cmd
- scripts/release/debian/build.sh
Backport #30533
[Core] Resolve CVE-2024-50602
> [LTS] Backport #30533

- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_classic_cdn_to_afd.py
skip cdn migration commit ut to fix https://github.com/Azure/azure-cli/issues/30577
> {cdn}skip cdn migration commit ut

- doc/how_to_introduce_breaking_changes.md
The purpose of this PR is to encourage our engineering teams to provide more information in their breaking changes description and detail for easier customer adoption.
*******************************
> {CI} how_to_introduce_breaking_changes.md | add more info on required properties

- src/azure-cli/azure/cli/command_modules/config/_params.py
- src/azure-cli/azure/cli/command_modules/util/_params.py
This pr deals with illegal html tags from **positional arguments** of cli main repo and is a continued effort to fix disallowed html tags in documentation, with following previous prs:
https://github.com/Azure/azure-cli/pull/27752
https://github.com/Azure/azure-cli/pull/29898
https://github.com/Azure/azure-cli/pull/30424
https://github.com/Azure/azure-cli/pull/30611
---
> {doc} Fix disallowed html tags

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_zone_balance.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
`az vmss create/update`
VMSS add zone-balance parameter
close https://github.com/Azure/azure-cli/issues/28939
---
> [Compute] `az vmss create/update`: Add new paramter `--zone-balance` to support setting zone balance

- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
Update CLI to use latest Python SDK version using new package import from: https://pypi.org/project/azure-mgmt-postgresqlflexibleservers/1.1.0b2/
Integration test run
[RDBMS] `az postgres flexible-server update`: Fix for scaling up node count on an elastic cluster
---
> {RDBMS} Update Python SDK for PostgreSQL flexible servers

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_scale_extended_location.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
`az vmss scale`
From edge zone team request: 
User doesnt need to provide extendedlocation. Cli should get the extendedlocation and add it automatically along with location
close https://github.com/Azure/azure-cli/issues/20078
---
> [Compute] `az vmss scale`: Add new logic to support scaling VMSS in edge zone

- src/azure-cli/azure/cli/command_modules/network/_help.py
- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/_validators.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/routeserver/_create.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/routeserver/_list.py
- src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/routeserver/_update.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_virtual_hub_router_scenario.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
`az network routeserver create/update`
resolve https://github.com/Azure/azure-cli/issues/30614
aaz pr: https://github.com/Azure/aaz/pull/677
---
> [Network] `az network routeserver create/update`: Add `--auto-scale-config`

- src/azure-cli/azure/cli/command_modules/acs/_help.py
`az aks approuting`
Fixes a documentation typo in the command short-summary
`az aks approuting --help`
---
> {AKS} `az aks approuting`: Fix short-summary typo

- .github/template/git-hooks-note.md
- .github/workflows/GitHookNotice.yml
> {CI} Add git hook notice

- src/azure-cli/azure/cli/command_modules/appconfig/_help.py
az appconfig export
This updates the help message for the `az appconfig export` command with the right environment variable.
[Appconfig] `az appconfig export`: Update export help message for environment variable
---
> [App Config] `az appconfig export`: Update export help message for environment variable

- src/azure-cli/azure/cli/command_modules/eventgrid/custom.py
Fix https://github.com/Azure/azure-cli/issues/30213#issuecomment-2635597199
---
> {Eventgrid} `az eventgrid domain topic event-subscription delete`: Fix LRO issue

- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
Drop the `azure-mgmt-devtestlabs` track1 dependency since all the usage have been migrated in #29878, #30771
---
> {Misc.} Drop `azure-mgmt-devtestlabs` track1 sdk

- src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
> [Service Connector] `az containerapp connection create redis`: Add `--system-identity` paramter

- src/azure-cli/azure/cli/command_modules/security/aaz/latest/security/api_collection/apim/_offboard.py
- src/azure-cli/azure/cli/command_modules/security/aaz/latest/security/api_collection/apim/_onboard.py
az security api-collection apim onboard
az security api-collection apim offboard
The purpose of this PR is to fix the documentation for two az security api-collection apim commands -- onboard and offboard. Specifically, the example for onboard was incorrect and the example for offboard was missing. We were made aware of this by a customer through https://portal.microsofticm.com/imp/v5/incidents/details/586915494/summary.
N/A
{Security} `az security api-collection apim onboard/offboard`:  Fix the documentation
---
> {Security} `az security api-collection apim onboard/offboard`:  Fix the documentation

- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
Backport #30816
[Core] Resolve CVE-2024-12797
> [LTS] Backport #30816

- src/azure-cli-core/azure/cli/core/aaz/_arg_fmt.py
> {core} `aaz`: Add cross tenants control for `AAZResourceIdArgFormat`

- src/azure-cli/azure/cli/command_modules/hdinsight/_help.py
> {HDInsight} `az hdinsight application`: Add declaration of unusable versions due to deprecation of Api-version 2018-06-01-preview

- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_nodepool_delete_with_ignore_pod_disruption_budget.yaml
{AKS} Fix test `test_aks_nodepool_delete_with_ignore_pod_disruption_budget`. The corresponding recording file was committed by PR #30196 based on an old default API version (2024-09-01). As we've bumped the default API version to 2024-10-01 in #30844, the CI now failed.
---
> {AKS} Fix test `test_aks_nodepool_delete_with_ignore_pod_disruption_budget`

- src/azure-cli/azure/cli/command_modules/servicebus/_help.py
- src/azure-cli/azure/cli/command_modules/servicebus/aaz/latest/servicebus/namespace/_update.py
Example fixed related to bug.
https://github.com/Azure/azure-cli/issues/29310
---
> {Servicebus} `az servicebus namespace update`: Minor Correction in syntax

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/_validators.py
- src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/data/motd.txt
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_add_nodepool_with_motd.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_agentpool_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_validators.py
- az aks create
- az aks nodepool add
Add message of the day option --message-of-the-day to enable users to specify a message of the day for their AKS nodes using GA CLI.
[AKS] `az aks create`: Add `--message-of-the-day` parameter to support message of the day
[AKS] `az aks nodepool add`: Add `--message-of-the-day` parameter to support message of the day
---
> [AKS] `az aks create/az aks nodepool add`: Add message of the day option `--message-of-the-day`

- src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/afd/endpoint/_purge.py
az afd purge
The documentation for az afd purge gives an invalid example for multiple domains.  This updates to a functional example.
---
> {afd purge} Update example of purge command

- src/azure-cli/azure/cli/command_modules/eventgrid/custom.py
> {LTS} Backport #30759

- .github/policies/resourceManagement.yml
- .github/workflows/AddIssueComment.yml
- .github/workflows/AddIssueCommentWithLabel.yml
- Update GitHub workflows to use ubuntu-latest as ubuntu-20.04 will be removed on 2025-04-01. For more details, see https://github.com/actions/runner-images/issues/11101, for ADO pipelines I will create another PR.
- Add auto-assign labels for Quantum issues
---
> {CI} Update GitHub workflows to use ubuntu-latest and add auto-assign labels for Quantum issues

- src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/afd/rule/_list.py
https://github.com/Azure/azure-cli/issues/30761
> {AFD} Fix `az afd rule condition list` example issue

- .github/CODEOWNERS
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_private_link_scope.py
> {Containerapp} Update code owner

- src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/afd/endpoint/_purge.py
Fix https://github.com/Azure/azure-cli/issues/30897
> {afd} Fix 30897 - change docs content

- src/azure-cli/azure/cli/command_modules/rdbms/_help.py
- src/azure-cli/azure/cli/command_modules/rdbms/custom.py
Updated naming convention as per new guidelines https://learn.microsoft.com/en-us/product-style-guide-msft-internal/a_z_names_terms/a/azure-database-for-postgresql.
---
> {RDBMS} Update messages for PostgreSQL to remove hyphenation as per new guidelines

- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
az postgres flexible-server identity update
Cannot disable SAMI when Fabric Mirroring is enabled
Manual testing
{RDBMS} `az postgres flexible-server identity update`: Cannot disable SAMI when Fabric Mirroring is enabled
---
> {RDBMS} `az postgres flexible-server identity update`: Cannot disable SAMI when Fabric Mirroring is enabled

- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_vpn_connection_aux.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
fix https://github.com/Azure/azure-cli/issues/31003
---
> [Network] Fix #31003: `az network vpn-connection create`: Pass auxiliary authorization header for referenced resource IDs

- .azure-pipelines/sync-alias.yml
> {CI} Update sync-alias.yml to push branch to azclibot/azure-cli repo

- src/azure-cli/azure/cli/command_modules/vm/_breaking_change.py
`az sig image-definition list-shared`
`az sig image-version list-shared`
`az sig image-definition list-community`
`az sig image-version list-community`
[Compute] `az sig image-definition list-shared`: Mark `--marker` and `--show-next-marker` as deprecated and will be removed in the upcoming breaking change window
[Compute] `az sig image-version list-shared`: Mark `--marker` and `--show-next-marker` as deprecated and will be removed in the upcoming breaking change window
[Compute] `az sig image-definition list-community`: Mark `--marker` and `--show-next-marker` as and will be removed in the upcoming breaking change windowdeprecated
[Compute] `az sig image-version list-community`: Mark `--marker` and …
> [Compute] Breaking changes pre-announcement

- src/azure-cli/azure/cli/command_modules/vm/_help.py
- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/commands.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
`az vm list-sizes`
Close: https://github.com/Azure/azure-cli/issues/31053
---
> [Compute] `az vm list-sizes`: Mark the command as deprecated

- src/azure-cli/azure/cli/command_modules/storage/_breaking_change.py
`az storage account migration start`
Add upcoming breaking change warning for confirmation during account redundancy change
---
> {Storage} `az storage account migration start`: Add upcoming breaking change warning for confirmation

- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
`packaging` has already released version `24.2` last year and is required by following libs:
1. `tox`
2. `pyproject-api`
3. `setuptools >= 77.0.0`
which will cause dependency conflicts with a lower packaging version `23.2` when setting up the environment.
Therefore upgrade current `packaging` to `24.2`.
---
> {Packaging} Bump packaging to 24.2

- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_slot_clone.yaml
> {App Service} Refresh yaml files for test

- src/azure-cli/azure/cli/command_modules/network/_breaking_change.py
> {Network} `az network vnet subnet`: Pre-announcement of `--default-outbound` removal

- src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
- src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands.py
- src/azure-cli/azure/cli/command_modules/rdbms/validators.py
az postgres flexible-server virtual-endpoint create
Add the name check to see if virtual endpoint name is available
Manual test
{RDBMS} `az postgres flexible-server virtual-endpoint create`: Add the name check to see if virtual endpoint name is available
---
> {RDBMS} `az postgres flexible-server virtual-endpoint create`: Add the name check to see if virtual endpoint name is available

- src/azure-cli/azure/cli/command_modules/acr/_breaking_change.py
`acr login`
Related breaking change PR: https://github.com/Azure/azure-cli/pull/30917
---
> {ACR} `az acr login`: Add Upcoming Breaking Change Announcement

- .github/policies/resourceManagement.yml
Update the people who need to be mentioned in the issue with AKS label. Adding @mbifeld
---
> {AKS} Update AKS issue policy

- .github/CODEOWNERS
Update CODEOWNERS, making sure each module has at least one member from Azure CLI team.
> {Misc.} Update CODEOWNERS: Add CLI team members to each line

- src/azure-cli/azure/cli/command_modules/security/_utils.py
- src/azure-cli/azure/cli/command_modules/security/custom.py
az security automation create_or_update
az security automation validate
As denoted in doc: [Azure CLI Subprocess Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/cli_subprocess_guidelines.md#az-related-command-execution), if target cmd is an operation from SDK, developers should apply corresponding method from SDK directly, to mitigate security issues in `subprocess`
{Security} `az security automation create_or_update/validate`: Replace `subprocess` with client sdk operation for resources group fetch
---
> {Security} Mitigate security risk of `subprocess`

- src/azure-cli/azure/cli/command_modules/advisor/_help.py
Updated content.
`az advisor recommendation disable`
Changed description to match the effect that the command has on the recommendation.
No code changes. Published content only.
{Advisor} `az advisor recommendation disable`: updated the command summary
---
> {Advisor} `az advisor recommendation disable`: updated the command summary

- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
az webapp create-remote-connection
Fixes #20209 
az webapp create-remote-connection -g -n 
You should now see the ssh command displayed in the output
---
> [App Service] Fix: #20209: `az webapp create-remote-connection`: Add ssh command to output

- .github/policies/resourceManagement.yml
> {CI} Add reviewers for acr PR

- src/azure-cli/azure/cli/command_modules/util/custom.py
`az upgrade` is causing issues. Stop displaying auto-upgrade message.
Ref: https://github.com/Azure/azure-cli/issues/30307#issuecomment-2472333084
> {Upgrade} Remove auto-upgrade message

- src/azure-cli-core/setup.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
> {Core} Bump MSAL to 1.32.3

- src/azure-cli/azure/cli/command_modules/ams/_help.py
> {ams} Command examples document

- src/azure-cli-core/azure/cli/core/breaking_change.py
Update the version and date for the next breaking change window, which should align with Ignite.
---
> {Core} Update Next Breaking Change Window version and date

- src/azure-cli/azure/cli/command_modules/acs/addonconfiguration.py
Fix the bug - https://github.com/Azure/azure-cli/issues/31265
---
> [AKS] Fix #31265: `az aks enable-addons`: Fix UnboundLocalError when setting specific dataCollectionSettings

- src/azure-cli/azure/cli/command_modules/acr/_breaking_change.py
- src/azure-cli/azure/cli/command_modules/acs/_breaking_change.py
- src/azure-cli/azure/cli/command_modules/netappfiles/_breaking_change.py
`acr login`
`aks create`
`netappfiles volume create/update`
Remove the expired upcoming breaking change announcements
Now we have only the following announcements:
---
> {ACR/AKS/NetAppFiles} Clear Expired Breaking Change Announcements

- doc/extensions/versioning_guidelines.md
Update doc for `--allow-preview` default value updates for this pr: https://github.com/Azure/azure-cli/pull/30163 
---
> {doc} Update extension versioning doc for default value of `--allow-preview`

- .github/workflows/BlockPRMerge.yml
Fix typo in `.github/workflows/BlockPRMerge.yml` (#28490).
> {CI} Fix typo in `.github/workflows/BlockPRMerge.yml`

- src/azure-cli/azure/cli/command_modules/acr/commands.py
Remove private preview message for `az acr connected-registry`
---
> [ACR] `az acr connected-registry`: Remove private preview message

- src/azure-cli/azure/cli/command_modules/profile/custom.py
`az login`
Update ROPC flow MFA warning message according to https://learn.microsoft.com/en-us/entra/identity/authentication/concept-mandatory-multifactor-authentication?tabs=dotnet#applications
> The date of enforcement for Phase 2 has changed to September 1, 2025.
> {Profile} `az login`: Update ROPC flow MFA warning message

- .github/CODEOWNERS
the codeowner of some inactive modules needs to be updated. after that, we only the approvals from ring-0 owners when bump api version.
---
> {CI} Add codeowner for inactive modules

- src/azure-cli-core/azure/cli/core/profiles/_shared.py
- src/azure-cli/azure/cli/command_modules/network/_format.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
try to drop sdk `azure-mgmt-dns`.
operations are generated by codegen, cannot be RecordSetListResult.
---
> {Packaging} Drop `azure-mgmt-dns`

- src/azure-cli-core/HISTORY.rst
It is better to add #31699 to history notes, similar to https://github.com/Azure/azure-powershell/pull/28193.
The public history notes are also updated: https://github.com/MicrosoftDocs/azure-docs-cli/pull/5411#discussion_r2247094726
---
> {Misc.} Supplement history notes for MFA error recommendation

- .github/policies/resourceManagement.yml
{AKS} Update mentionees of issues with tag containerservice.
---
> {AKS} Update mentionees of issues with tag containerservice

- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_expressroute_with_public_ip.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_expressroute_without_public_ip.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
az network vnet-gateway create
As ExpressRoute gateway supports auto-assigned IP, public ip address should no longer be required in vnet-gateway create. Currently, if public ip address argument is missing, ip configuration is not being created. The change in this PR enables creation of a single IpConfiguration object with only subnet reference when public ip address is not passed by the customer. 
vnet gateway creation with and without public-ip-address argument
`az network vnet-gateway create --resource-group "xxx" --name "xxx" --vnet "xxx" --gateway-type ExpressRoute --sku Standard --location "xxx"`
`az network vnet-gateway create --resource-group "xxx" --name "xxx" --vnet "xxx" --public-ip-address "xxx" --gateway-type ExpressRoute …
> [Network] `az network vnet-gateway create`: Remove public IP requirement in gateway creation
