Azure/azure-cli

src/azure-cli/azure/cli/command_modules/iot/custom.py
src/azure-cli/azure/cli/command_modules/iot/tests/latest/recording_processors.py
src/azure-cli/azure/cli/command_modules/iot/tests/latest/test_iot_commands.py

`az iot hub create`
`az iot hub update`
`az iot hub delete`
For the following commands:
`az iot hub create`
`az iot hub update`
`az iot hub delete`
followed the instructions [here](https://github.com/Azure/azure-cli/issues/25479) and removed polling=True so a separate thread is not created.
Also fixed the recorder so that it replaces the SharedAccessKey correctly. Before, we had to manually fix the recording after rerecording tests.
azdev test test_iot_hub
Ran the test live and then reran it using the recording and both pass.
[IoT] Fix poller issues for `az iot hub create`, `az iot hub update`, `az iot hub delete`
---

{IoT} Fix recorder and poller issues

---

src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py

az aks update
Should check whether `assign_identity`  is `None` or not before comparation. Otherwise in most cases `assign_identity`  is `None` and will prompt for user's input incorrectly.
---

{AKS} Fix unexpected prompt for az aks command

---

src/azure-cli-core/azure/cli/core/extension/dynamic_install.py
src/azure-cli-core/azure/cli/core/tests/test_extension.py

When we run a command in an extension which is not installed, it will show a prompt like this
This will block the script in no-tty environment. This PR use the `yes_without_prompt` mode as default for no-tty environment, so that the missing commands will be installed automatically.
---

[Core] `extension`: Install extensions without prompt as default behavior when it's not in a tty

---

src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py

Fix test case `test_aks_create_with_outbound_type_udr`, the check on property `Network.DNS.EnableProxy` after `network firewall create` broke due to the azure-firewall extension upgrade the API version to 2022-01-01. See [PR #6176](https://github.com/Azure/azure-cli-extensions/pull/6176).
---

{AKS} Fix test case `test_aks_create_with_outbound_type_udr`

---

src/azure-cli-core/azure/cli/core/aaz/_poller.py

closed: #26272
closed: #26297
In python 3.10.10, we encountered import deadlocks in `aaz` LRO which try to load the `requests.models` in two different threads. It's a known issue https://github.com/psf/requests/issues/2925
In this PR, we provide a workaround by importing these modules in the main thread before spawning child threads.
---

{Core} `aaz`: Fix importlib deadlocks while loading `requests.models` in multi threads

---

src/azure-cli/azure/cli/command_modules/network/azure_stack/2017_03_09_profile/operations/vnet.py
src/azure-cli/azure/cli/command_modules/network/azure_stack/2018_03_01_hybrid/operations/vnet.py
src/azure-cli/azure/cli/command_modules/network/azure_stack/2019_03_01_hybrid/operations/vnet.py
src/azure-cli/azure/cli/command_modules/network/azure_stack/2020_09_01_hybrid/operations/vnet.py

Fix: https://github.com/Azure/azure-cli/issues/26318
---

[Network] Fix #26318: `az network vnet subnet create`: `--nsg` and `--route-table` cannot be used as name from Azure Stack

---

src/azure-cli/azure/cli/command_modules/resource/_params.py
src/azure-cli/azure/cli/command_modules/resource/custom.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py

```sh
az bicep format --file {} --newline {} --insert-final-newline
```
The `--insert-final-newline` parameter causes the command to crash because the underlying `bicep` command line has the corresponding parameter as a flag that doesn't take any input unlike what is being executed.
While working on this, I noticed that the `--newline` parameter was set up as the opposite to be a flag instead of taking an input.
This PR resolves both issues.
fixes #26216
```sh
az bicep format --file {} --newline {} --insert-final-newline
```
---

[ARM] Fix #26216: `az bicep format`: Fix the TypeError `expected str, bytes or os.PathLike object, not bool`

---

src/azure-cli-testsdk/azure/cli/testsdk/base.py
src/azure-cli/azure/cli/command_modules/resource/custom.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_bicep.py

```sh
az bicep publish
az bicep restore
az bicep generate-params
```
Some commands require a specific version of `bicep` to function and when trying to check the current version of `bicep` installed, if the `bicep` CLI is not present, the commands fail.
The workaround is to ensure the `bicep` CLI is already installed. This PR ensures it is installed if it is already not before running the checks.
Additionally, to improve test coverage, this extends the `random_config_dir` property introduced in #25796 for `LiveScenarioTest`s as well. @bebound FYI
resolves #26256
```sh
az bicep publish
az bicep restore
az bicep generate-params
```
---

[ARM] Fix #26256: `az bicep publish/restore/generate-params`: Fix version checks without bicep installed

---

src/azure-cli/azure/cli/command_modules/acs/custom.py

Fix issue #26353, fix incorrect architecture detection on Darwin/arm64, should regard the return value (by `platform.machine()`) `arm64` as `arm64` as well.
---

[AKS] Fix #26353: `az aks install-cli`: Fix incorrect architecture detection on Darwin/arm64

---

src/azure-cli/azure/cli/command_modules/rdbms/_params.py
src/azure-cli/azure/cli/command_modules/rdbms/validators.py

`az mysql/postgres flexible-server create/update`
`Enabled` value for `--high-availability` argument in commands `az mysql/postgres flexible-server create/update` will be deprecated. The possible values for that argument will be only `ZoneRedundant`, `SameZone` and `Disabled`, the value `Enabled` was the same as `ZoneRedundant`.
---

[RDBMS] BREAKING CHANGE: `az mysql/postgres flexible-server create/update`: Deprecate `Enabled` for `--high-availability` argument

---

src/azure-cli/azure/cli/command_modules/acr/_params.py

az acr create --sku 
--sku                   [Required] : The SKU of the container registry.  Allowed values: Basic,
**Classic**, Premium, Standard.
ACR has blocked creating new Classic registry for several years. The change removes `Classic` option from the `--sku` command option. 
```
az acr create --sku Classic
az acr create: 'Classic' is not a valid value for '--sku'. Allowed values: Basic, Standard, Premium.
az acr create --help
Command
az acr create : Create an Azure Container Registry.
--sku                   [Required] : The SKU of the container registry.  Allowed values: Basic,
Premium, Standard.
```
[ACR] `az acr create`: Remove `Classic` from `sku` option
--- …

[ACR] BREAKING CHANGE: `az acr create`: Remove `Classic` from `sku` option

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_deploy_zip.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_list_deployment_logs.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_show_deployment_logs.yaml

Fixes #26445 by adding back the Content-Type header for deployments 
---

[App Service] Fix #26445: `az webapp deploy`: Fix deployment failing with HTTP 400

---

src/azure-cli-core/azure/cli/core/profiles/_shared.py
src/azure-cli/azure/cli/command_modules/keyvault/_client_factory.py
src/azure-cli/azure/cli/command_modules/keyvault/_help.py
src/azure-cli/azure/cli/command_modules/keyvault/_params.py
src/azure-cli/azure/cli/command_modules/keyvault/commands.py
src/azure-cli/azure/cli/command_modules/keyvault/custom.py
src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_hsm_role.yaml
src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_hsm_security_domain.yaml
src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_hsm_setting.yaml
src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_role_definition.yaml
src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

`az keyvault setting`
This PR bumps `azure-keyvault-administration` from `4.0.0b3` to `4.3.0`. There're some breaking changes between these two versions.
After bumping to `4.3.0`, new command group `az keyvault setting` is added to support `update/show/list` MHSM settings.
See added scenario test
[Keyvault] BREAKING CHANGE: `az keyvault backup start`: The output will only contain `folderUrl`
[Keyvault] BREAKING CHANGE: `az keyvault restore start`: Nothing will return for successful run
[Keyvault] BREAKING CHANGE: `az keyvault role assignment delete`: Nothing will return for successful run
[Keyvault] `az keyvault setting`: New command group to manage MHSM settings
--- …

[Keyvault] `az keyvault setting`: New command group to manage MHSM settings

---

scripts/ci/install_docker.sh

Sometimes, if the install docker script fails, it still continues running until the last line.
This PR make it exit faster.
```
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal/InRelease  Connection failed [IP: 185.125.190.36 80]
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal-updates/InRelease  Cannot initiate the connection to ports.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to ports.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Could not connect to ports.ubuntu.com:80 (185.125.190.39), connection timed out Could not connect to ports.ubuntu.com:80 (185.125.190.36), connection timed out [IP: 185.125.190.36 80]
...
+ command -v selinuxenabled …
```

{CI} Exit immediately if install docker fails

---

src/azure-cli/azure/cli/command_modules/resource/_packing_engine.py

fix for the TypeError in az ts create CLi command 
fixes Azure/azure-cli#26352
While running the `az ts create` cli command we get the below error:
```
File "/home/sverrir/.local/lib/python3.10/site-packages/azure/cli/command_modules/resource/_packing_engine.py", line 155, in _get_template_links_to_artifacts
deployment_resource_objs = _get_deployment_resource_objects(cmd, template_obj, includeNested)
File "/home/sverrir/.local/lib/python3.10/site-packages/azure/cli/command_modules/resource/_packing_engine.py", line 140, in _get_deployment_resource_objects
if (str(resource['type']) == 'Microsoft.Resources/deployments') is True:
TypeError: string indices must be integers
```
This PR has the fix for this issue. …

[ARM] Fix #26352: `az ts create`: Fix for the TypeError `string indices must be integers`

---

src/azure-cli/azure/cli/command_modules/servicebus/_params.py
src/azure-cli/azure/cli/command_modules/sql/commands.py

`az sql db threat-policy`
`az servicebus queue update`
I have contact @schaudhari6254888 @cohen-uriel-ms to remove their deprecated command/parameter in `2.49.0`. But they somehow didn't make it. So I will remove the expiration version as temporary workaround to unblock `CLI 2.49.0` release 
---

{CI} Remove expiration version `2.49.0` to unblock release pipeline

---

src/azure-cli-core/azure/cli/core/auth/landing_pages/success.html

`az login`
Update the announcement message for WAM-based login (#25416).

{Core} Update the announcement message for WAM-based login

---

src/azure-cli/azure/cli/command_modules/network/custom.py

`az network dns zone import --name … --resource-group … --subscription … --file-name …`
I'm importing a very small zone, but it fails due to the APEX being an (Azure)Alias record?  The zone is generated using `zone export` command and all records are generated by Azure Portal.
Relevant traceback:
```
cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: 'a_records'
File "/Users/…/brew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
File …
```

[Network] `az network dns zone import`: Fix alias records cannot be imported

---

src/azure-cli/azure/cli/command_modules/cdn/_help.py

az cdn endpoint purge --content-paths '/a' '/b'
az cdn endpoint load --content-paths '/a' '/b'
Explicitly describe how to pass multiple values. Otherwise one would have to extract this from the examples.
Aligned with az ad app update --identifier-uris, the same is done over there.
pass multiple values in content-paths:
az cdn endpoint purge --content-paths '/a' '/b'
az cdn endpoint load --content-paths '/a' '/b'
---

{CDN} `az cdn endpoint purge/load`: Describe how to pass multiple content-paths

---

.azure-pipelines/breaking-change-tests.yml
.github/azure-client-tools-bot/config.yml
scripts/ci/breaking_change_test.py

1. Forked repo needs to disable check suit.
Forked repo cannot use the check suit id to find all test jobs of the current PR 
We can only get the the pipeline build url from the check run payload.
3. Need to create a new branch for the merged commit.
Azure devops checkout task is in 'detached HEAD' state.
It will merge source branch to target branch and create a new commit.
So we need to create a new branch to retain the commit.
---

{CI} fix for breaking change tool integration

---

src/azure-cli-telemetry/azure/cli/telemetry/components/records_collection.py
src/azure-cli-telemetry/azure/cli/telemetry/tests/test_records_collection.py

As we planned in #26065, this is the third step to shorten the cache push interval from 6 hours to 1 hour
---

{Telemetry} Reduce default pushing interval for local telemetry cache to 1h

---

src/azure-cli/azure/cli/command_modules/network/custom.py

Fix: https://github.com/Azure/azure-cli/issues/26438
---

[Network] Fix #26438: `az network vnet peering sync`: Doesn't work in cross-tenant scenario

---

src/azure-cli/azure/cli/command_modules/keyvault/_client_factory.py

`az keyvault key/secret/certificate/role`
all data plane commands in keyvault module
Keyvault data plane track2 SDKs (including `azure-keyvault-keys`, `azure-keyvault-secrets`, `azure-keyvault-certificates`, `azure-keyvault-administration`) made a breaking change in 2022-09 release:
> Breaking Changes
Clients verify the challenge resource matches the vault domain. This should affect few customers, who can provide verify_challenge_resource=False to client constructors to disable. See https://aka.ms/azsdk/blog/vault-uri for more information.
This PR handles this breaking change and will fix #26552 
[Component Name 2] `az …

{Keyvault} `az keyvault key/secret/certificate/role`: Skip verifying challenge resource

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tunnel.py

A supplementary PR for #23494
According to https://urllib3.readthedocs.io/en/stable/reference/contrib/pyopenssl.html
> This module was relevant before the standard library ssl module supported SNI, but now that we’ve dropped support for Python 2.7 all relevant Python versions support SNI so this module is no longer recommended.
Since we have dropped support for Python 2 (https://github.com/Azure/azure-cli/pull/11363), we should remove usages of deprecated `inject_into_urllib3`. Otherwise, in the future, `urllib3` v2.1.0 will raise an exception when `inject_into_urllib3` is called (https://github.com/urllib3/urllib3/issues/2680).

{App Service} Remove usages of deprecated `inject_into_urllib3`

---

src/azure-cli/azure/cli/command_modules/vm/_alias.py
src/azure-cli/azure/cli/command_modules/vm/custom.py

az vm image alias
[Add] Breaking change warning to show image aliases will be removed in October 2023: `UbuntuLTS`, `CentOS`, `Debian`, `Flatcar`, `SLES`, `openSUSE-Leap` and `RHEL`
---

{Compute} `az vm create`: Breaking change warning to image alias that will be deprecated

---

src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py

N/A
Update the check in test case `test_aks_create_default_service_with_virtual_node_addon`. Due to the update on the server side, after disable virtual node addon, the return value corresponding to the config field in the addon profile is no longer `None`, but `{}` (empty dictionary) instead.
---

{AKS} Fix test case `test_aks_create_default_service_with_virtual_node_addon`

---

src/azure-cli-core/azure/cli/core/auth/landing_pages/success.html
src/azure-cli/azure/cli/command_modules/backup/custom_wl.py
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_csr.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_wl_hana_container.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_wl_hana_policy.yaml

`az backup protection backup-now`
Compressed backups have been enabled for SAP HANA. The current CLI blocks `backup protection backup-now` calls when the `--enable-compression` flag is set to `true`. This PR unblocks that scenario.
[backup] `az backup protection backup-now`: Allow `--enable-compression` to be set to `true` for SAPHANA Workloads
---

[Backup] `az backup protection backup-now`: Allow `--enable-compression` to be set to `true` for SAPHANA Workloads

---

src/azure-cli/azure/cli/command_modules/keyvault/_client_factory.py
src/azure-cli/azure/cli/command_modules/keyvault/custom.py

In #22432, we migrated AAD Graph to MS Graph. Some related code in Keyvault module was also modified from https://github.com/Azure/azure-cli/blob/1451bd570fd0fe54771cedaecdbd49cdb4b8d69c/src/azure-cli/azure/cli/command_modules/keyvault/custom.py#L681-L689 to https://github.com/Azure/azure-cli/blob/cac3f06cf483d8c81f93c9cd556116e27aff2182/src/azure-cli/azure/cli/command_modules/keyvault/custom.py#L679-L684
Before migration, we need to call `profile.get_login_credentials` to get `cred` and `tenant_id` info.
After migration, we don't need the `cred` anymore but didn't drop `profile.get_login_credentials` just to get `tenant_id` info.
But there's better way to get `tenant_id`, it's a waste to call `profile.get_login_credentials` just for tenant info. Besides, the existing …

{Keyvault} Remove useless AAD endpoint and honor user input `--subscription` to support cross sub operations

---

src/azure-cli-core/setup.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

Bump MSAL to 1.22.0 in order to pick up https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/553/commits/1bb5476fa15d80c44c33915ebe5c8c2b7f7a88d5 released by https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/553.
This allows using higher versions of `cryptography` (https://github.com/Azure/azure-cli/pull/26596).

{Packaging} Bump MSAL to 1.22.0

---

src/azure-cli/azure/cli/command_modules/resource/_help.py

The correct command is `az config set bicep.check_version=True/False`, not `az config set bicep.version_check=True/False`
fixes Azure/azure-cli#26660
---

{ARM} Incorrect command for the bicep check version

---

src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

Bump requests to fix [CVE-2023-32681](https://github.com/advisories/GHSA-j8r2-6x86-q33q)
Also bump urllib3 to latest version
---

{Packaging} Bump requests to 2.31.0 and urllib3 to 1.26.16

---

src/azure-cli/azure/cli/command_modules/storage/util.py

`az storage blob download-batch`
When matching pattern, previously first grabs the full list before trying to filter. Now list blobs with prefix to reduce the number of list calls. Fix #26567 
[Storage] `az storage blob download-batch`: When matching pattern, list blobs with prefix to reduce the number of list calls
---
---

[Storage] Fix #26567: `az storage blob download-batch`: When matching `--pattern`, list blobs with prefix to reduce the number of list calls

---

src/azure-cli/azure/cli/command_modules/vm/_params.py

Submitting request here as suggested in below pull request:
https://github.com/Azure/azure-cli/pull/26350#pullrequestreview-1440820818
--public-ip-address
Name of the public IP address when creating one (default) or referencing an existing one. Can also reference an existing public IP by ID or specify "" for None ('""' in Azure CLI using PowerShell or --% operator).
Description
We have tested with different versions of OS and PowerShell core version 7.3.4 to test the public-ip-address parameter behavior and below is our findings when we have to create VM without public IP:
For PowerShell core version 7.2.* & below === --public-ip-address '""'
For PowerShell core version 7.3.4 ===== --public-ip-address ‘’ or --public-ip-address “” …

{Compute} `az vm create`: Update help message for `--public-ip-address`

---

azure-pipelines.yml

Fix #25750.
Bookworm is released on 2023-06-10.
---

[Packaging] Add Debian Bookworm support

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py

az webapp deploy
Changing the file extension parsing logic to work with file paths that have multiple '.'s. Previous logic was written with the assumption that there would only be a single '.' character that splits the file name from the extension.
Issue_Close: #25497
`az webapp deploy --resource-group [rg-name] --name [app-name] --src-path "[path-to-zip-file]" --type zip`
If `--src-path` has multiple '.'s such as 'test.app.zip' this command used to default to type=static. With this fix, the command will correctly select type=zip when passed the same filename.
---

[App Service] Fix #25497: `az webapp deploy`: Fix extension parsing if `src-path` has multiple '.'s

---

src/azure-cli/azure/cli/command_modules/sqlvm/_validators.py

az sql vm enable-azure-ad-auth
az sql vm validate-azure-ad-auth
There is a regression in Graph API related with server side filtering in retrieving all transitive directory roles a MSI belongs to as detailed in the following IcM ticket and bug. 
https://portal.microsofticm.com/imp/v3/incidents/details/392112435/home
https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2591038
The deployment of a fix from Graph team is around September this year. Since this is a major use scenario of SQLVM AAD authentication feature, we decide to work around this bug in our Azure CLI by retrying the client side filtering when a server side filtering fails. 
I have manually tested all scenarios. It is hard to add automated test here …

[Sqlvm] Fix #2442969: `az sql vm enable-azure-ad-auth/validate-azure-ad-auth`: Workaround Graph API bug by using client side filtering upon failure

---

src/azure-cli/azure/cli/command_modules/eventhubs/aaz/latest/eventhubs/eventhub/authorization_rule/_create.py

`az eventhubs eventhub authorization-rule create`
Fix authorization-rule create example Fixes GitHub Issue [26733](https://github.com/Azure/azure-cli/issues/26733) 
---

{eventhubs} Fix authorization-rule create example

---

src/azure-cli/azure/cli/command_modules/keyvault/_transformers.py

`az keyvault certificate show`
`az keyvault certificate show` would throw
```
cli.azure.cli.core.azclierror: Traceback (most recent call last):
File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/_command_type.py", line 135, in keyvault_command_handler
File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/arm.py", line 429, in show_exception_handler
File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/_command_type.py", line 116, in keyvault_command_handler
File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/_transformers.py", line 285, in …
```

{Keyvault} `az keyvault certificate show`: Fix 'NoneType object is not iterable' error

---

src/azure-cli/azure/cli/command_modules/storage/operations/account.py

`az storage account or-policy create`
`az storage account or-policy create` previously did not print out service error. 
Fix #26673 
[Storage] Fix #26673: `az storage account or-policy create`: Now print out server error
---

[Storage] Fix #26673: `az storage account or-policy create`: Now print out server error

---

linter_exclusions.yml

`az appconfig snapshot list`
This PR removes the linter exclusion that for the snapshot list command parameter `--snapshot-name`. This follows an update to fix a CI issue that was marking an already covered test as missing in test coverage.
{AppConfig} `az appconfig snapshot list`: Remove command test coverage linter exclusion
---

{AppConfig} `az appconfig snapshot list`: Remove command test coverage linter exclusion

---

src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

During the 'webapp vnet-integration remove' call, we enter 20s wait for hit geo and 45s wait on app service side in order for NCs to be deleted successfully on machines.
So add time.sleep(65) for all `az webapp vnet-integration` related commands.
This can avoid resource residue caused by appservice related tests.
---

{CI} Add `time.sleep` to ensure that the live test can delete the resource group

---

scripts/ci/dependency_check.bat
scripts/ci/dependency_check.sh
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt

Rework of https://github.com/Azure/azure-cli/pull/26596
As explained in https://github.com/Azure/azure-cli/pull/26596#issuecomment-1590590291, only bumping `cryptography` is not enough. `pyOpenSSL` should be bumped at the same time.
Close #25913

{Packaging} Bump cryptography to 41.0.1 and pyOpenSSL to 23.2.0

---

src/azure-cli/azure/cli/command_modules/servicefabric/_help.py
src/azure-cli/azure/cli/command_modules/servicefabric/_params.py
src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/recordings/test_basic_cluster.yaml
src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/recordings/test_cert_and_ext.yaml
src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/recordings/test_node_type_operation.yaml

Updating vmSkus to use 2022-Datacenter so that tests are tls compliant for ServiceFabric module
see src\azure-cli\azure\cli\command_modules\help.py for examples and descriptions
[Service Fabric] `az sf managed-node-type create`: creates nodetype with 2022-Datacenter vmSku as default
---

[Service Fabric] `az sf managed-node-type create`: creates nodetype with 2022-Datacenter vmSku as default

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli/azure/cli/command_modules/role/_params.py
src/azure-cli/azure/cli/command_modules/role/custom.py

This PR is going to add alias `--json-auth` for the parameter `--sdk-auth` of the command `az ad sp create-for-rbac`. 
As mentioned in #19872, `--sdk-auth` was deprecated since Python SDK has deprecated the usage of the output JSON file, there are still other places where this JSON file is used, like GitHub Action. To avoid confusion in naming, we introduce the alias `--json-auth` for `--sdk-auth`. 
Some documents should be updated synchronously.
- https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/github/connect-from-azure.md#use-the-azure-login-action-with-a-service-principal-secret
- https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/aks/kubernetes-action.md#create-secrets
- …

[Role] `az ad sp create-for-rbac`: Add alias `--json-auth` for `--sdk-auth`

---

scripts/ci/automation_full_test.py

Now the test is to dynamically allocate the modules that need to be tested for each instance.
PR #26785  adds a module graphservices. Due to the adjustment of dynamic allocation, on instance 7, we will test the cloud and acr modules in turn. There is a test test_get_docker_credentials in acr that will fail, and the error is as follows:
```
E ValueError: OIDC Discovery failed on https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/v2.0/.well-known/openid-configuration. HTTP status: 400, Error: {"error":"invalid_tenant","error_description":"AADSTS900021: Requested tenant identifier '00000000-0000-0000-0000-000000000000' is not valid. Tenant identifiers may not be an empty GUID.\r\nTrace ID: …
```

{CI} Put the cloud module at the end of the serial execution to avoid affecting other tests.

---

src/azure-cli-core/azure/cli/core/aaz/_arg_action.py
src/azure-cli-core/azure/cli/core/tests/test_aaz_arg.py

The blank value is not parsed correctly for compound argument types, because for thouse arguments, the argparser will put empty list in setup_operations call. This PR fixed such issue.
---

[Core] `aaz`: Support blank input for compound argument types

---

src/azure-cli/azure/cli/command_modules/serviceconnector/_addon_factory.py
src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
src/azure-cli/azure/cli/command_modules/serviceconnector/_utils.py
src/azure-cli/azure/cli/command_modules/serviceconnector/_validators.py
src/azure-cli/azure/cli/command_modules/serviceconnector/commands.py
src/azure-cli/azure/cli/command_modules/serviceconnector/custom.py
src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_springboot_cosmossql_secret_e2e.yaml
src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_springboot_cosmossql_smi_e2e.yaml
src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_springboot_cosmossql_umi_e2e.yaml
src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/test_springboot_cosmos_scenario.py
src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/test_springboot_cosmossql_scenario.py

az spring connection create/update cosmos-sql
az spring connection show
az spring connection list-configuration
To enable managed identity and service principal as the auth type when sercie connector connects spring apps and cosmos sql using spring boot as the client type. According to Spring Cloud Azure version 4.0, new configuration properties are included. Warning for migration and new display of the connection config info is added.
Create connection with system identity
az spring connection create cosmos-sql --resource-group <resource-group> --service <spring apps service> --app <app-name> --target-resource-group <target-resource-group> --account <database-account> --database <database> --client-type springBoot
Update connection …

[Service Connector] `az spring connection`: Enable new auth types for Spring Boot and Cosmos SQL connection

---

src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/_list_references.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_create.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_delete.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_list.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_list_by_type.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_show.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_update.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/zone/_create.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/zone/_delete.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/zone/_list.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/zone/_show.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/zone/_update.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_alias.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_delegation.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_dnssec.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_if_none_match.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone10_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone1_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone2_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone3_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone4_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone5_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone6_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone7_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone8_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone9_import.yaml

`az network dns zone`
`az network dns record-set`
* This PR explicitly sets the query_parameter "api-version" to the latest non-preview api-version (2018-05-01) for the zones and the record-set REST calls. This is done to accommodate the high delay in rolling out the preview version of the Networking ARM manifest across all regions.
* This should address the issues where a call to `az network dns zone list` etc. would return `NoRegisteredProviderFound`
* Resolves #26814 #26894 
*Note*: This output of the commands would vary based on the DNS zones in your subscription.
Example commands:
* `az network dns zone list` would return all the zones in your subscription
* ` az network dns record-set  list   --zone-name foo.com --resource-group …

{Network} `az network dns`: Revert to use an older version until rollout is done

---

src/azure-cli/azure/cli/command_modules/acs/_params.py
src/azure-cli/azure/cli/command_modules/acs/custom.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py

`az aks enable-addons`
{AKS} `az aks enable-addons`: Fix the default value of option `--enable-msi-auth-for-monitoring` being overwritten to `False` when specified. Fix issue #26839.
As the option is not declared in `_params.py`, and the default value of the parameter is True, the following config is implicitly generated for this option by argparse 
> {'options_list': ['--enable-msi-auth-for-monitoring'], 'required': False, 'default': True, 'help': None, 'action': '**store_false**', 'dest': 'enable_msi_auth_for_monitoring'}
So, if use specifies the option explicitly, the value would be overwritten to False.
[Component Name 2] …

[AKS] `az aks enable-addons`: Fix the default value of option `--enable-msi-auth-for-monitoring` being overwritten to `False` when specified

---

src/azure-cli/azure/cli/command_modules/security/custom.py

`az security automation create_or_update`
Fixing a bug in `az security automation create_or_update` command, specifically when running it with action of type LogicApp.
The bug prevents the command from completing successfully due to an issue that addressed in this PR
{Security} `az security automation create_or_update` bug fix when using LogicApp action
---

{Security} `az security automation create/update`: Fix bug when using LogicApp action

---

src/azure-cli/azure/cli/command_modules/keyvault/_params.py
src/azure-cli/azure/cli/command_modules/keyvault/custom.py

`az keyvault restore start`
`az keyvault restore start` used to restore the whole HSM. This PR adds an optional parameter `--key-name`, when key name specified, only this key will be restored
---

[Keyvault] `az keyvault restore start`: Add `--key-name` to support selective key restore

---

src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py

{AKS} Fix the check of config field in addon related tests. As addon v2 is gradually enabled, after disabling the addon, its corresponding config field in the response is null instead of empty. Update the check to accept both the value `None` and `{}`(empty dictionary) after deserialization.
---

{AKS} Fix the check of config field in addon related tests

---

scripts/release/debian/deb_install.sh

CLI supports Debian bookworm from 2.50.0, use bookworm as default repo.
Related PR:
- https://github.com/Azure/azure-cli/pull/26690
---

{Packaging} Change default Debian repo to bookworm

---

azure-pipelines.yml
build_scripts/windows/Product.wxs
build_scripts/windows/azure-cli.sln
build_scripts/windows/azure-cli.wixproj
build_scripts/windows/scripts/build.cmd

[Packaging] Support x86 and x64 MSI builds

---

src/azure-cli-core/setup.py
src/azure-cli-telemetry/HISTORY.rst
src/azure-cli-telemetry/azure/cli/telemetry/__init__.py
src/azure-cli-telemetry/azure/cli/telemetry/components/records_collection.py
src/azure-cli-telemetry/azure/cli/telemetry/tests/test_records_collection.py
src/azure-cli-telemetry/azure/cli/telemetry/util.py
src/azure-cli-telemetry/setup.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

We have reduce client telemetry push interval from 24h to 6h in #26065, from 6h to 1h in #26509
Now it's time to fully drop client telemetry cache strategy. All telemetry records will be uploaded immediately.
Run any cli command and check if there's `$HOME_DIR/.azure/telemetry/cache` file anymore
---

[Core] Drop client telemetry cache strategy

---

src/azure-cli/azure/cli/command_modules/storage/_params.py
src/azure-cli/azure/cli/command_modules/storage/operations/blob.py

`az storage container-rm update`: `--default-encryption-scope` and `--deny-encryption-scope-override` should not be specified during update, when specified, server would also ignore. 
[Storage] `az storage container-rm update`: `--default-encryption-scope` and `--deny-encryption-scope-override` should not be specified during update
---

[Storage] `az storage container-rm update`: `--default-encryption-scope` and `--deny-encryption-scope-override` should not be specified during update

---

src/azure-cli/azure/cli/command_modules/vm/custom.py

`az disk create`
https://github.com/Azure/azure-cli/issues/23614#issuecomment-1640056627
Remove the warning shown when creating with `CreateOption = Empty`.
`az disk create  -g ResourceGroup -n DiskName --size-gb 10`
---

{Compute} Remove warning for `CreateOption = Empty`

---

src/azure-cli/azure/cli/command_modules/appconfig/_format.py
src/azure-cli/azure/cli/command_modules/appconfig/_params.py
src/azure-cli/azure/cli/command_modules/appconfig/_snapshotmodels.py

`az appconfig snapshot`
This PR removes the `status_code` property from the snapshot response object. This property is not returned in the API response and is currently always null.
[App Config] `az appconfig snapshot`: Remove status code property from snapshot object
---

[App Config] `az appconfig snapshot`: Remove status code property from snapshot object

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py

`az webapp config ssl bind`
`az webapp config ssl unbind`
`az functionapp config ssl bind`
`az functionapp config ssl unbind`
Fixes #21133 & fixes #13929. Currently the CLI only searches for matching certificates in the web app's resource group and the resource group for the app service plan. This change would add logic to search for a matching cert in the user's subscription as well (filtering on the web app's App Service Plan / serverfarmId)  if no match was found using the previous logic. 
Issue_Close: #21133 #13929
---

[App Service] Fix #21133: `az webapp/functionapp config ssl bind/unbind`: Search for matching certificates in the subscription by App Service Plan Id

---

src/azure-cli-core/azure/cli/core/auth/util.py
src/azure-cli-core/azure/cli/core/telemetry.py
src/azure-cli-core/setup.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

`az login`
Incorporate https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/575 and add `msal_telemetry` from MSAL's response to Azure CLI's client telemetry. (Similar to how `core.allow_broker` configuration is added to client telemetry: https://github.com/Azure/azure-cli/pull/24304)
```
az config set core.allow_broker=true
az login
```
Then 
- Continue the login to trigger the success path, or
- Close the window to trigger the error path

{Core} Add `msal_telemetry` to client telemetry

---

src/azure-cli/azure/cli/command_modules/keyvault/custom.py
src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_certificate_soft_delete.yaml

`az keyvault certificate create`
---

{Keyvault} Fix test failure in `az keyvault certificate create`

---

src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/dc/defaults.py
src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/dc/tests/test_defaults.py

```az aks update -n kaveeshcli22 -g kaveeshcli --enable-azuremonitormetrics --enable-windows-recording-rules```
```az aks create -n kaveeshcli22 -g kaveeshcli --location westeurope --enable-azuremonitormetrics --enable-windows-recording-rules --azure-monitor-workspace-resource-id "{full_id}" --grafana-resource-id "{full_id}"```
The DC* objects can only container alphanumeric characters and '-' so updating the code to reflect it.
DC* refers to [DCRA](https://learn.microsoft.com/en-us/rest/api/monitor/data-collection-rule-associations), [DCR ](https://learn.microsoft.com/en-us/rest/api/monitor/data-collection-rules) and [DCE](https://learn.microsoft.com/en-us/rest/api/monitor/data-collection-endpoints) i.e. Data Collection Rule Association, Data …

{AKS} `az aks create/update`: Update logic to sanitize cluster name for DC* objects

---

src/azure-cli/azure/cli/command_modules/acs/_help.py
src/azure-cli/azure/cli/command_modules/acs/_params.py
src/azure-cli/azure/cli/command_modules/acs/custom.py
src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_migrate_cluster_to_cilium_dataplane.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py

`az aks update --network-dataplane=cilium`
Add the --network-dataplane flag to the az aks update command. This will allow customers to update an existing cluster to enable [Azure CNI Powered by Cilium](https://learn.microsoft.com/en-us/azure/aks/azure-cni-powered-by-cilium)
Note to reviewers: this is the same change I made to the preview CLI in https://github.com/Azure/azure-cli-extensions/pull/6446
```
az aks create -g <resourcegroup> -n <name> --network-plugin=azure --network-plugin-mode=overlay
az aks update -g <resourcegroup> -n <name> --network-dataplane=cilium`
```
[AKS] `az aks update`: Add new parameter `--network-dataplane` to specify the network dataplane used in the Kubernetes cluster
--- …

[AKS] `az aks update`: Add `--network-dataplane` option

---

src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/amw/defaults.py
src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/constants.py

```az aks update -n kaveeshcli -g kaveeshcli --enable-azure-monitor-metrics --enable-windows-recording-rules```
```az aks create -n kaveeshcli -g kaveeshcli --location centraluseuap --enable-azure-monitor-metrics --enable-windows-recording-rules --azure-monitor-workspace-resource-id "{full_id}" --grafana-resource-id "{full_id}"```
centraluseuap will not be a supported region for Azure Monitor Workspace anymore thus we're mapping the creation to the closest euap region i.e. eastus2euap.
This is a bug fix and can be tested by onboarding to the azure monitor for metrics addon using the above mentioned commands with an AKS cluster in centraluseuap.
--- …

{AKS} `az aks create/update`: update logic for euap region mapping

---

src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

`az keyvault show`
Fix #26950 #27109 #27147 
`az keyvault show` calls `vaults_operation.list()` to query for the matched vault if customer only provide `--vault-name` without `--resource-group-name`.
But SDK has API version mismatch issue for `vaults_operation.list()` and it was fixed in https://github.com/Azure/azure-sdk-for-python/pull/31272
This PR aims to bump related SDK `azure-mgmt-keyvault==10.2.3` to pick up the fix from CLI side
---

{Keyvault} Bump `azure-mgmt-keyvault` to `10.2.3` to fix API version mistmatch issue

---

src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/_list_references.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_create.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_delete.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_list.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_list_by_type.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_show.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_update.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/zone/_create.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/zone/_delete.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/zone/_list.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/zone/_show.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/dns/zone/_update.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_alias.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_delegation.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_dnssec.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_if_none_match.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone10_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone1_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone2_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone3_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone4_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone5_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone6_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone7_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone8_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone9_import.yaml

az network dns zone
az network dns record-set
This PR explicitly sets the query_parameter "api-version" to the latest api-version (2023-07-01-preview) for the zones and the record-set REST calls. This reverts back the change done in #26902
Note: This output of the commands would vary based on the DNS zones in your subscription.
Example commands:
* az network dns zone list would return all the zones in your subscription
* az network dns record-set  list   --zone-name foo.com --resource-group hello --query "[?name=='@']" would retrieve all record sets in the zone foo.com
* az network dns zone show  --name google.com --resource-group allhandsdemo -o table
---
This checklist is used to make sure that common guidelines for …

{Network} az network dns: Move forward to use new api version 2023-07-01-preview 

---

.github/policies/resourceManagement.yml

There is a breaking change happening during the automated migration.
The `action: Opened` condition is added by [this PR](https://github.com/Azure/azure-cli/pull/26925) during the automated migration, so policy will not act when someone add labels.
Possible solution: use `action: Labeled`.
https://github.com/Azure/azure-cli-extensions/issues/6653
https://github.com/Azure/azure-cli-extensions/issues/6652
---

{CI} Fix policy migration issue

---

src/azure-cli/azure/cli/command_modules/backup/_params.py
src/azure-cli/azure/cli/command_modules/backup/custom.py
src/azure-cli/azure/cli/command_modules/backup/custom_afs.py
src/azure-cli/azure/cli/command_modules/backup/custom_base.py
src/azure-cli/azure/cli/command_modules/backup/tests/latest/preparers.py
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_afs_backup_container.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_afs_backup_item.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_afs_backup_policy.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_afs_backup_protection.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_afs_backup_restore.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_afs_backup_rp.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_afs_backup_scenario.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_afs_unregister_container.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/test_afs_commands.py

`az backup restore restore-azurefileshare`
Resolving work item <https://msazure.visualstudio.com/DefaultCollection/One/_workitems/edit/24475508/>. Allows users to AFS restore to a storage account that is in a different resource group from the vault, without having to provide the full ARM ID of the Storage Account.
---

[Backup] `az backup restore restore-azurefileshare`: Add `--target-rg-name` parameter to specify the resource group of the destination storage account

---

src/azure-cli/azure/cli/command_modules/acs/_loadbalancer.py
src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py

[AKS] `az aks update`: Retain value in network profile in mc object only when decorator is in update mode
---

{AKS} Retain value in network profile of mc object only when decorator is in update mode

---

src/azure-cli/azure/cli/command_modules/storage/operations/file.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_batch_operations.py

`az storage file upload-batch`
- Why this PR?
- Resolved a pending TODO for improving performance.
- What is changed?
- Uploading files in batch in parallel. 
- What is the effect?
- Faster `az storage file upload-batch` command execution depending on `--max-connections` argument. 
- Default: 1 thread worker for uploading one file at a time.
- `az storage file upload-batch -s "source" -d "destination" --account-name "storage_account_name" --account-key "storage_account_access_key"`
- Parallel: `--max-connections 4` argument -> 4 thread worker -> each worker uploading one file at a time .
- `az storage file upload-batch -s "source" -d "destination" --account-name "storage_account_name" --account-key "storage_account_access_key" …

[Storage] `az storage file upload-batch`: Allow uploading files in parallel to improve performance

---

src/azure-cli/azure/cli/command_modules/cosmosdb/_params.py
src/azure-cli/azure/cli/command_modules/cosmosdb/custom.py
src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_public_network_access_restore.yaml
src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/test_cosmosdb_backuprestore_scenario.py

az cosmosdb restore --target-database-account-name --account-name --restore-timestamp -g --location --enable-public-network <TRUE/FALSE>
This pr is to add a parameter (--public-network-access) to the az cosmos db restore cli command. This change requires NO sdk/api changes as this parameter is already existing and used by (create cosmos db cli command). The change is very minor and I have updated one of our tests to take in the parameter & captured its recording.
self.cmd('az cosmosdb restore -n {restored_acc} -g {rg} -a {acc} --restore-timestamp {rts} --location {loc} --assign-identity {user_id_2} --default-identity {default_id2} --public-network-access "DISABLED"')
This will restore the cosmos db account with Public Network Access as …

[cosmosdb] `az cosmosdb restore`: Support enabling/disabling public network access

---

src/azure-cli/azure/cli/command_modules/cognitiveservices/_params.py
src/azure-cli/azure/cli/command_modules/cognitiveservices/custom.py

`az cognitiveservices account deployment create`
`az cognitiveservices account deployment create` add `--model-source` parameter.
Sample usage
`az cognitiveservices account deployment create --resource-group felixwa-byom --name felixwa-byom-test-2 --deployment-name fromWS1 --model-format OpenAI --model-name felixwamodel1 --model-version 1 --model-source /subscriptions/f9b96b36-1f5e-4021-8959-51527e26e6d3/resourcegroups/felixwa-byom/providers/Microsoft.MachineLearningServices/workspaces/felixwa-byom-test-1
`
UT didn't cover this case as the setup is too complicated to be done in UT.
[Cognitive Services] `az cognitiveservices account deployment create`: Add `--model-source` parameter
--- …

[Cognitive Services] `az account deployment create` support `--model-source` parameter

---

src/azure-cli/azure/cli/command_modules/keyvault/commands.py

`az keyvault storage`
`az keyvault storage` is still using track1 SDK and there's no track2 SDK for `azure-keyvault-storage`.
Service team said they don't maintain keyvault storage related APIs anymore. It's suggested to deprecate related commands in CLI too.
---

[Keyvault] `az keyvault storage`: Announce deprecation since keyvault service doesn't maintain this since long ago

---

scripts/release/homebrew/docker/formula_generate.py

Homebrew does not install pip when create venv in https://github.com/Homebrew/brew/pull/15792, adding `without_pip: false` to install pip.
`pip` also installs `setuptools`, which is also required in namespace package:
```
linuxbrew@794b47da48b2:/down$ az -v
File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/runpy.py", line 187, in _run_module_as_main
mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/runpy.py", line 110, in _get_module_details
__import__(pkg_name)
File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.51.0/libexec/lib/python3.10/site-packages/azure/__init__.py", line 1, in <module> …
```

{Packaging} Install pip in Homebrew virtual env

---

src/azure-cli/azure/cli/command_modules/util/custom.py

`az upgrade`
Currently, if it fails to get latest version from GitHub, latest version becomes `None`. It still prompts for upgrade.
This PR skips the upgrade if latest version is `None`.
---

{Upgrade} Skip upgrade if latest version is None

---

src/azure-cli/azure/cli/command_modules/network/custom.py

Resolve: https://github.com/Azure/azure-cli/issues/27193
---

[Network] `az network vnet peering create`: Mark `--remote-vnet` as required

---

azure-pipelines.yml
build_scripts/windows/scripts/test_msi_installation.ps1

As explained in https://github.com/Azure/azure-cli/pull/17317#discussion_r1277480110, CI job **TestWindowsMSI** never works as expected. The test for x64 MSI is disabled by https://github.com/Azure/azure-cli/pull/27018.
However, that issue doesn't happen if the artifact MSI has higher version, as in that case, the script doesn't append `"REINSTALL=ALL REINSTALLMODE=emus"` and x64 MSI uninstalls x86 MSI (https://github.com/Azure/azure-cli/pull/26640#issuecomment-1645337341).
In order to mimic a clean installation, this PR changes the logic to **uninstall the pre-installed Azure CLI first, then install the artifact MSI**.

{Packaging} Test x86 and x64 MSI installation

---

src/azure-cli/azure/cli/command_modules/vm/_params.py
src/azure-cli/azure/cli/command_modules/vm/custom.py
src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/test_vm_commands.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_proximity_placement_group.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

`az ppg create/update`
Support new value for PPG type parameter https://github.com/Azure/azure-cli/issues/26829
```
Request URL: https://management.azure.com/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Compute/proximityPlacementGroups/ppg1?api-version=2022-11-01
Request body:
{"location": "eastus", "tags": {}, "properties": {"proximityPlacementGroupType": "Ultra"}}`
Response content:
{
"error": {
"code": "InvalidParameter",
"message": "The value of parameter proximityPlacementGroup.properties.proximityPlacementGroupType is invalid.",
"target": "proximityPlacementGroup.properties.proximityPlacementGroupType"
}
}
```
[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking …

[Compute] `az ppg update`: Add new parameter `--type` to support setting proximity placement group type

---

scripts/ci/test_extensions.sh

k8s-extension is rolled back to 1.4.3 in https://github.com/Azure/azure-cli-extensions/pull/6702, which is not compatible with latest azure-cli
---

{CI} Temporarily skip k8s-extension in TestExtensionsLoading

---

scripts/release/debian/test_deb_package.py
scripts/release/homebrew/test_homebrew_package.py
scripts/release/rpm/test_rpm_package.py

`-x, --exitfirst` means exit instantly on first error or failed test.
Remove `--exitfirst` to collect all error information at once so we can fix test issues in one go.
---

{CI} Remove `--exitfirst` to collect all error information at once.

---

src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_custom.py

`az bicep`
Change below tests to live only mode:
- `BicepDecompileParamsTest`
- `BicepBuildParamsTest`
- `test_bicep_generate_params_defaults`
- `test_bicep_generate_params_output_format`
- `test_bicep_generate_params_include_params`
- `test_bicep_build_params_defaults`
- `test_bicep_decompile_params_defaults`
Fix: #26781
---

{ARM} `az bicep`: Change tests to live only mode

---

src/azure-cli-testsdk/azure/cli/testsdk/preparers.py

az containerapp
Create containerapp managed environment needs arguments --logs-workspace-id and --logs-workspace-key.
The --logs-workspace-key is log workspace customerId, --logs-workspace-key is primarySharedKey.
We hope it can be prepared well and the `NoTrafficRecording`, So need to change the `LogAnalyticsWorkspacePreparer` to return multiple parameters include `customerId` and `primarySharedKey`
---

{Test} Support get sharekey in `LogAnalyticsWorkspacePreparer`

---

src/azure-cli/azure/cli/command_modules/storage/_params.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_blob_copy_scenarios.py

Add `--rehydrate-priority` to `az storage blob copy start-batch`
Fix #26732 
[Storage] Fix #26732: `az storage blob copy start-batch`: Add `--rehydrate-priority` to batch copy
---

[Storage] Fix #26732: `az storage blob copy start-batch`: Add `--rehydrate-priority` to batch copy

---

scripts/release/homebrew/docker/formula_generate.py

Revert #27074.
PS: https://github.com/Homebrew/homebrew-core/pull/138921 also moves formula into `a/` subdirectory.
---

{Packaging} Use latest homebrew formula

---

src/azure-cli-core/azure/cli/core/aaz/_command.py

AAZ commands are not loaded when customer use capital letters in command names, like below.
This PR fixed the above issue, it will ignore the case of command names.
---

[Core] `aaz`: Fix command name case issue for aaz command table lazy load

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_on_linux_app_service_java.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_on_linux_app_service_java_with_runtime_version.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_windows_runtime_java.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_with_default_distributed_tracing.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_without_default_distributed_tracing.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py

Currently, in the Azure Portal, full monitoring is enabled by default for non consumption Java function apps that will have deployed code (as opposed to container image). We need to have the same default behavior in the Azure CLI. This is achieved by setting the `APPLICATIONINSIGHTS_ENABLE_AGENT` app setting to true.
1. Create function app with `az functionapp create -g {} -n {} -s {} --plan {} --runtime java --functions-version 4` command
2. Check that `APPLICATIONINSIGHTS_ENABLE_AGENT` is set to true with `az functionapp config apsettings list -g {} -n {}`
**Relevant Documentation**
https://learn.microsoft.com/en-us/azure/azure-monitor/app/monitor-functions#distributed-tracing-for-java-applications-public-previ …

[App Service] `az functionapp create`: Enable distributed tracing for non consumption apps

---

src/azure-cli/azure/cli/command_modules/serviceconnector/_params.py
src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py

`az spring connection`
As https://github.com/Azure/azure-cli/issues/27371 said, we would delete the default value of --deployment. Therefore, we would like to add a deprecated message as warning for customer before the breaking change.
It displays as 
---

[Service Connector] `az spring connection`: Add deprecated message for `--deployment` breaking change

---

src/azure-cli/azure/cli/command_modules/acr/_help.py

`az acr network-rule add` and `az acr network-rule remove`
Remove incorrect examples having `--subnet` parameter from the documentation as this parameter has been deprecated.
Fixes GitHub Issue [27224](https://github.com/Azure/azure-cli/issues/27224)
---

{ACR} Remove incorrect examples from the documentation

---

src/azure-cli/azure/cli/command_modules/acr/_params.py

az acr token create -h
Currently, the order of allowed actions listed in the help text is random and changes every time the -h is invoked. This causes problem for the docs people who are diffing the help text at regular intervals.
az acr token create -h
[ACR] `az acr token create`: Fix random order of repo valid actions and gateway valid actions in the help message
---
- [x ] I adhere to the [Command …

[ACR] `az acr token create`: Fix random order of repo valid actions and gateway valid actions in the help message

---

src/azure-cli-core/azure/cli/core/auth/binary_cache.py

`import collections.abc as collections` raises this error in `azdev style`:
```
ERROR: ************* Module azure.cli.core.auth.binary_cache
src/azure-cli-core/azure/cli/core/auth/binary_cache.py:6:0: E0611: No name 'abc' in module 'collections.abc' (no-name-in-module)
```
This line is introduced in https://github.com/Azure/azure-cli/pull/20847. I guess there is a new rule in flake8 which found this.
It appears that flake8 treats `collections.abc` as `collections` then it can't find `abc` module in it.
--- …

{CI} Fix no-name-in-module style error

---

src/azure-cli/azure/cli/command_modules/vm/_vm_utils.py
src/azure-cli/azure/cli/command_modules/vm/custom.py
src/azure-cli/azure/cli/command_modules/vm/disk_encryption.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_encryption_with_key.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

`az vm encryption enable`
Fix #27446 
The command accepts `--key-encryption-key` to encrypt the disk encryption key.
However, when converting the key name to a URL, a `CertificateClient` is used instead of a `KeyClient`. which causing  an error because the CertificateClient object is meant for managing certificates, not keys.
The bug was introduced in #26991 , which updated `azure-keyvault` package to `azure-keyvault-key`/`azure-keyvault-secret`/`azure-keyvault-certificate`.
--- …

[Compute] Fix #27446: `az vm encryption enable`: Fix using incorrect client when `--key-encryption-key` is specified

---

scripts/release/debian/prepare.sh
scripts/release/debian/test_deb_package.py

This PR fixes some hard-coded path after bump to 3.11 in #26749
1. `dpkg-shlibdeps`'s executable names.
Ref: https://man7.org/linux/man-pages/man1/dpkg-shlibdeps.1.html
2. `command_modules` path
---

{Packaging} Fix DEB package build and test

---

src/azure-cli/azure/cli/command_modules/acs/_help.py

- az aks create
- az aks nodepool add
Update help information for option `--node-osdisk-size`. The disk size specified by this option is actually in GiB (instead of GB). Fix issue #27461
---

{AKS} Fix #27461: `az aks create`: Update help information for option `--node-osdisk-size`

---

src/azure-cli/azure/cli/command_modules/resource/_help.py
src/azure-cli/azure/cli/command_modules/resource/_params.py
src/azure-cli/azure/cli/command_modules/resource/commands.py
src/azure-cli/azure/cli/command_modules/resource/custom.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_custom.py

`az bicep lint` command is added
_"bicep cli"_ has a _lint_ command that lints the given _bicep_ file.
[ARM] `az bicep lint`: Add new command to lint a bicep file
---

[ARM] `az bicep lint`: Add new command to lint a bicep file

---

src/azure-cli/azure/cli/command_modules/storage/azcopy/util.py

Fix #27590 Check user sytem PATH for azcopy and use it if the version is newer than 10.13.0. If not found or has old version, use CLI config directory for azcopy
[Storage] Fix #27590: `az storage fs directory download`: Check user sytem PATH for azcopy and use CLI config directory for new install
---

[Storage] Fix #27590: `az storage fs directory download`: Check user sytem PATH for azcopy and use CLI config directory for new install

---

src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_agentpool_decorator.py

Fix incorrectly specified property name for option `--drain-timeout` in command `az aks nodepool add`. Bug fix for the change in previous PR #27475.
---

[AKS] `az aks nodepool add`: Fix incorrectly specified property name for option `--drain-timeout`

---

src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py

az aks update
support plan could be reset to None during az aks update
az aks create --kubernetes-version 1.27 --k8s-support-plan AKSLongTermSupport --tier Premium
az aks update --tags "a=b"
az aks update --k8s-support-plan KubernetesOfficial --tier Standard
az aks update --tags "c=d"
az aks update --k8s-support-plan AKSLongTermSupport --tier Premium
[AKS] `az aks update`: Fix bug where supportPlan can be reset to None
---

[AKS] `az aks update`: Fix bug where supportPlan can be reset to None

---

scripts/ci/test_extensions.sh
src/azure-cli/setup.py

This PR temporarily fixes the `Test Extensions Loading Python311` error, similar PR: https://github.com/Azure/azure-cli/pull/20436
```
2023-10-30T02:31:59.9288865Z ERROR: az_command_data_logger: cannot import name 'soft_unicode' from 'markupsafe' (/opt/az/azcliextensions/alias/markupsafe/__init__.py)
2023-10-30T02:31:59.9292703Z Traceback (most recent call last):
2023-10-30T02:31:59.9296297Z   File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
2023-10-30T02:31:59.9297243Z     cmd_result = self.invocation.execute(args)
2023-10-30T02:31:59.9299944Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-30T02:31:59.9301257Z   File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/azure/cli/core/comman …
```

{CI} Disable `alias` extension test

---

src/azure-cli/azure/cli/command_modules/mysql/custom.py
src/azure-cli/azure/cli/command_modules/mysql/tests/latest/test_mysql_scenario.py

az mysql flexible-server gtid reset --resource-group {} --server-name {} --gtid-set {} --no-wait {} --yes {}
remove geo backup check when customer want to reset gtid and update warning notification.
---

[MYSQL] `az mysql flexible-server gtid reset`: Remove geo-backup check

---

src/azure-cli/azure/cli/command_modules/vm/_params.py
src/azure-cli/azure/cli/command_modules/vm/_validators.py
src/azure-cli/azure/cli/command_modules/vm/custom.py
src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2018_03_01/test_vm_actions.py
src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/test_vm_actions.py
src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/test_vm_actions.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_msi.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_msi.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_actions.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

As mentioned in the [PR](https://github.com/Azure/azure-cli/pull/25283), we would remove the default value `Contributor` of `--role` parameter in this breaking change window.
---

[Compute] BREAKING CHANGE: `az vm/vmss identity assign`: Remove the default value `Contributor` of parameter `--role`

---

alpine.dockerfile

Trim Alpine docker image by using `RUN --mount`.
The image size drops from **923MB** to **717MB**
Ref: https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md#run---mount
---

{Packaging} Trim Alpine docker image

---

src/azure-cli/azure/cli/command_modules/container/_params.py

Corrected typo (contianer to container)
Corrected documentation typo.

{Container} `az container create`: Fix typo for the `--privileged` parameter

---

src/azure-cli/azure/cli/command_modules/acs/custom.py

az aks install-cli
The word detection had a typo.
Run az aks install-cli
---

{AKS} `az aks install-cli`: Fix typo in warning message

---

src/azure-cli-core/azure/cli/core/auth/identity.py

`az login`
Close #26052
Turn on WAM with
```
az config set core.allow_broker=true
```
Then use service principal to login with `az login --service-principal -u {} -p {} -t {}`. The command fails with `ValueError: allow_broker=True is only supported in PublicClientApplication`.
This is because WAM doesn't support service principal. This issue has also been reported to the MSAL repo: https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/544
This PR changes the behavior by only applying `allow_broker` to `PublicClientApplication`, not to `ConfidentialClientApplication`.
```
az config set core.allow_broker=true
az login --service-principal -u {} -p {} -t {}
```
Observe the `az login` command succeed without raising …

{Core} Only apply `allow_broker` to `PublicClientApplication`

---

src/azure-cli-core/azure/cli/core/auth/msal_authentication.py

`az login`
MSAL 1.23.0 (https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/581) changed the behavior of `acquire_token_for_client` so that it will **automatically look up access tokens from cache**, so there is no need to call `acquire_token_silent` and check the result manually then call `acquire_token_for_client`.
The MSAL example also reflects the same:
https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/95df6086ec186e395186e097f8c9103c4ee74d83/sample/confidential_client_secret_sample.py#L53-L55
```py
result = app.acquire_token_for_client(scopes=config["scope"])
```

{Core} Directly call `acquire_token_for_client` to acquire access token for service principal

---

src/azure-cli/azure/cli/command_modules/profile/_help.py
src/azure-cli/azure/cli/command_modules/profile/custom.py
src/azure-cli/azure/cli/command_modules/profile/tests/latest/test_profile_custom.py

Close #19700
`az account get-access-token`
Returning `expiresOn` as a local datetime is a legacy from the ADAL age. It causes lots of unnecessary complexities. See https://github.com/Azure/azure-cli/issues/19700 for detailed explanation.
This PR makes `az account get-access-token` return `expires_on` as POSIX timestamp which has been supported long ago by Azure CLI Core during the MSAL migration (https://github.com/Azure/azure-cli/pull/19853).
However, as shown in https://github.com/Azure/azure-cli/issues/19700#issuecomment-1729040872, downstream applications that only support 32-bit integer precision timestamp will encounter error in year 2038, but that's not something we can control.
```
az account get-access-token
```
Before:
```
{ …
```

[Profile] `az account get-access-token`: Return `expires_on` as POSIX timestamp

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_deployment_source_update_token.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands_thru_mock.py

`az functionapp deployment source update-token`
`az webapp deployment source update-token`
Currently, these two commands return the tokens as part of the output. In this PR, we are redacting the tokens so prevent accidental security leaks through CI logs.
1. Create functionapp (`az functionapp create`)
2. Update token (`az functionapp deployment source update-token`)
---

[App Service] BREAKING CHANGE: Redact tokens output on deployment source update-token

---

src/azure-cli/azure/cli/command_modules/role/_help.py
src/azure-cli/azure/cli/command_modules/role/_validators.py
src/azure-cli/azure/cli/command_modules/role/custom.py
src/azure-cli/azure/cli/command_modules/role/tests/latest/test_role.py

Close https://github.com/Azure/azure-cli/issues/24753
`az role assignment create`
To adhere to the Principle of Least Privilege and avoid over-scoped role assignment on the subscription, `--scope` is now a required argument.
A warning for this breaking change was announced in https://github.com/Azure/azure-cli/pull/24755.
See https://github.com/Azure/azure-cli/issues/24753 for detailed explanation.
The corresponding change on `az vm/vmss` is https://github.com/Azure/azure-cli/pull/27657.
```sh
az role assignment create --assignee-object-id xxx --scope /subscriptions/xxx/resourceGroups/xxx --role reader
az role assignment create --assignee-object-id xxx --role reader
```
[Role] BREAKING CHANGE: `az role assignment …

[Role] BREAKING CHANGE: `az role assignment create`: `--scope` is now a required argument

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/auth/identity.py

Close https://github.com/Azure/azure-cli/issues/26433
`az login`
Some Azure Stack cloud uses an AAD endpoint that is not well known. The endpoint can't be discovered with `https://login.microsoftonline.com/common/discovery/instance` either.
Running `az login` in such cloud will result in a failure:
```
ValueError: invalid_instance: The authority you provided, https://login.devfabric.azs.microsoft.com/
organizations, is not whitelisted. If it is indeed your legit customized domain name, you can turn 
off this check by passing in validate_authority=False
```
Register a cloud with private AAD endpoint `https://login.devfabric.azs.microsoft.com/` and log in:
```
az cloud register -n myazurestack --endpoint-resource-manager …
```

[Core] Support disabling instance discovery

---

src/azure-cli/azure/cli/command_modules/apim/custom.py

az apim api create
Make --authorization_scope paramter option for setting auth server of an API
"az apim api create --resource-group {} --service-name {} --api-id {} --path {} --authorization-server-id {oAuth2Provider} --display-name {} --protocols {} --service-url {}" should work without --authorization_scope paramter specified
[APIM] `az apim api create`: Make `--authorization-scope` parameter optional for setting auth server
---

[APIM] `az apim api create`: Make `--authorization-scope` parameter optional for setting auth server

---

src/azure-cli/azure/cli/command_modules/appservice/_params.py

Documentation for "--slot-setting" in "storage-account" for webapp should be made clear.
fixes Azure/azure-cli#27343
```
--slot-setting
With slot setting you can decide to make BYOS configuration sticky to a slot, meaning that when that slot is swapped, the storage account stays with that slot.
default value: False
```
---

{App Service} Modify help message for "--slot-setting" in "storage-account" 

---

src/azure-cli/azure/cli/command_modules/rdbms/_client_factory.py
src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py
src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py

az postgres flexible-server geo-restore --resource-group testGroup --name testserverNew --location newLocation --source-server /subscriptions/{sourceSubscriptionId}/resourceGroups/{sourceResourceGroup}/providers/Microsoft.DBforPostgreSQL/flexibleServers/{sourceServerName}
az postgres flexible-server restore --resource-group testGroup --name testserverNew --source-server /subscriptions/{sourceSubscriptionId}/resourceGroups/{sourceResourceGroup}/providers/Microsoft.DBforPostgreSQL/flexibleServers/{sourceServerName}
1. Add support for cross resource group and cross-subscription restore / geo-restore for flexible server
Verified manually.
[RDBMS] `az postgres flexible-server geo-restore`: Add cross subscription …

[RDBMS] PostgreSQL - Add support for cross subscription restore

---

src/azure-cli/azure/cli/command_modules/rdbms/_params.py

az postgres flexible-server upgrade -g testrg -n pg-flex-test-server-14 -v 15
[RDBMS] Add support for PG version 15 for MVU of PostgreSQL flexible server
[RDBMS] `az postgres flexible-server upgrade`: Add MVU support for PG version 15
---
- [X ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).
- [X ] I adhere to the [Error Handling …

[RDBMS] Add support for PG version 15 for MVU of PostgreSQL flexible server

---

src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/virtual_appliance/_create.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/virtual_appliance/_update.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

az network virtual-appliance create
az network virtual-appliance update
This change is to expand support for Identities on Network Virtual Appliances to Create and Update, currently it is only in list and show and now we are expanding it into the create command and update command to reflect what is possible now in portal/PowerShell
**The following command will make an NVA with a User Assigned Identity:**
`az network virtual-appliance create -g GravesTest -n JGIdentityNVATest1 --vhub "/subscriptions/62364504-2406-418e-971c-05822ff72fad/resourceGroups/GravesTest/providers/Microsoft.Network/virtualHubs/TestVHub" --vendor "checkpoint" --scale-unit 2 -v latest --asn 64512 --identity …

[Network] `az network virtual-appliance`: Add parameter `--identity`

---

src/azure-cli/azure/cli/command_modules/network/custom.py

az network watcher configure --locations westeurope -g NetworkWatcherRG --enabled true
This pr fixes the naming of network-watcher to match the default and portal naming when deploying a new network-watcher.
run az network watcher configure --locations westeurope -g NetworkWatcherRG --enabled true
and deploy the same from portal or check the default deployment of network-watcher
---

{Network} `az network watcher configure`: Fix watcher name to match portal naming when new deployment

---

src/azure-cli/azure/cli/command_modules/iot/__init__.py
src/azure-cli/azure/cli/command_modules/iot/_help.py

`az iot`
We are in the process of releasing a new extension for new services. To avoid confusion between the two, the references for the old ones in general help will be removed. Specific commands and sub commands that have a direct connection to an extension command will not be changed.
history sucks so redo of https://github.com/Azure/azure-cli/pull/27721
None. These are help changes.
None.
---

{Iot} Remove general mentions of extension

---

src/azure-cli/azure/cli/command_modules/appservice/_help.py
src/azure-cli/azure/cli/command_modules/appservice/_params.py
src/azure-cli/azure/cli/command_modules/appservice/appservice_environment.py
src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_app_service_environment_commands_thru_mock.py

az appservice ase create
Currently default ASE kind is set to ASEv2. ASEv2 is retiring in August 2024 and creates of ASEv2 will be blocked starting in January. So we need the default to be updated to ASEv3 to prevent errors and ensure customers are getting onto the latest version.
az appservice ase create -g <rg> -n <asename> --vnet-name <vnet> --subnet <subnet> : use this to create an ASEv3 since the default is now set to ASEv3. You no longer need to include the kind parameter for ASEv3 creates.
--- …

[App Service] BREAKING CHANGE: `az appservice ase create`: Update the default App Service Environment to V3

---

src/azure-cli/azure/cli/command_modules/aro/custom.py

`az aro update -n shared-cluster -g shared-cluster --refresh-credentials
GraphError doesn't have message attribute and az tries to access it which causes another error when it gets a GraphError.
https://github.com/Azure/ARO-RP/pull/3093
https://github.com/Azure/azure-cli/blob/41927496c3c682e35b7f436b6f44c8d10b752387/src/azure-cli/azure/cli/command_modules/role/_msgrpah/_graph_client.py#L375-L378
example
```
❯ az aro update -n shared-cluster -g shared-cluster --refresh-credentials
The behavior of this command has been altered by the following extension: aro
'GraphError' object has no attribute 'message'
File …
```

{Aro} fix graph error handling

---

src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_postgres_flexible_server.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_link_resource_postgres_flexible_server.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py

`az network private-endpoint create`
`az network private-endpoint-connection show/approve/list/reject`
This PR onboards the Microsoft.DBforPostgreSQL/flexibleServers RP to use the `az network private-endpoint*` commands. This allows Azure customers to manage private endpoints and private endpoint connections to the flexible server resources using the `az network` module.
Added integration tests and can be tested by running `azdev test NetworkPrivateLinkPostgreSQLFlexibleServerScenarioTest`.
Since the feature is in preview, the subscriptions making use of private endpoint for flexible servers must be whitelisted internally by the RP.
N/A
---
This checklist is used to make sure that common guidelines for a pull request …

[Network] `az network private-endpoint-connection`: Add provider `Microsoft.DBforPostgreSQL/flexibleServers`

---

src/azure-cli/azure/cli/command_modules/keyvault/_help.py
src/azure-cli/azure/cli/command_modules/keyvault/commands.py

`az keyvault create`
The `doc_string_source` settings for keyvault commands didn't take any actual effect because we have full help entries in `_help.py`. Meanwhile, the `doc_string_source` setting for `az keyvault create` would print such warnings in debug log which is quite annoying:
```
cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
File "d:\workspace\azure-cli\src\azure-cli-core\azure\cli\core\profiles\_shared.py", line 651, in _get_attr
op = import_module(full_mod_path)
File "C:\Users\yishiwang\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen …
```

{Keyvault} Clear `doc_string_source` for keyvault commands

---

scripts/ci/automation_full_test.py

The order of modules returned by get_path_table() is not fixed.
However, when generating all test jobs, the order of self.jobs is guaranteed by `self.jobs = sorted(jobs.items(), key=lambda item: -item[1])`, so this issue is not exposed.
But self.jobs only records cli modules before 2022/04/20.
Newly added modules will be assigned to each instance based on the average test time of existing modules.
This may result in a module not being tested by any instance.
For example:
The test load allocated on instance1 is 100 minutes.
The test load assigned on instance2 is 105 minutes
If there is another test, it will definitely be allocated to instance1 first, because the greedy algorithm will give priority to instances with lower load.
Assume that there are two modules at this time, one mysql and …

{CI} Fix full test issue

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py

`az webapp log tail`
While log streaming for a web app, if the connection to the scm logstream endpoint is lost, we currently don't catch the exception properly. This results in the user seeing this error:
```
cli.azure.cli.command_modules.appservice.custom: 2023-08-23T15:39:34 No new trace in the past 1 min(s).
cli.azure.cli.command_modules.appservice.custom: 2023-08-23T15:40:34 No new trace in the past 2 min(s).
cli.azure.cli.command_modules.appservice.custom: 2023-08-23T15:41:34 No new trace in the past 3 min(s).
cli.azure.cli.command_modules.appservice.custom: 2023-08-23T15:42:34 No new trace in the past 4 min(s).
Exception in thread Thread-1 (_get_log):
File …
```

[App Service] `az webapp log tail`: Fix #27189 catch exception when scm connection is lost 

---

src/azure-cli/azure/cli/command_modules/acr/_constants.py
src/azure-cli/azure/cli/command_modules/acr/_validators.py

`az acr login`
Add hyphen to ACR name validation regex to support legacy registry names
`az acr login myregistry-tenant`
[ACR] `az acr login`: Allow registry names with hyphen
---

[ACR] Allow registry names with hyphen in `az acr login` to support legacy registry names

---

azure-pipelines.yml

Fedora 36 is EOL and the build task fails like https://github.com/Azure/azure-cli/pull/25969

{Packaging} Remove Fedora 36 build

---

src/azure-cli/azure/cli/command_modules/security/_params.py

Correct spelling of "Progremmatic" to "Programmatic".
Fixes #27909 
`az security assessment`
Spelling correction for documentation.
N/A
N/A
---

[Security] Fix spelling error in docs for `az security assessment`

---

scripts/ci/automation_full_test.py

GitHub does not allow comments longer than 65535 characters,
When the test report length exceeds 65535, guide the user to get error details in the pipeline log. 
The logic is too complex if calculated through the final result and removed extra characters:
```
<details>
<summary>️✔️Azure CLI Extensions Breaking Change Test</summary>
><details>
> <summary>️✔️Non Breaking Changes</summary>
>
>
></details>
</details>
```
---

{CI} When the test report length exceeds 65535, guide the user to get error details in the pipeline log.

---

src/azure-cli/azure/cli/command_modules/acs/_help.py
src/azure-cli/azure/cli/command_modules/acs/_helpers.py
src/azure-cli/azure/cli/command_modules/acs/commands.py
src/azure-cli/azure/cli/command_modules/acs/custom.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_stop_and_start.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_stop_and_start_private_cluster.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_custom.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_helpers.py

az aks stop: add warning when stopping a private link cluster. 
Add warning when customer stops a private link cluster.
Similar to this change in cli extension repo: https://github.com/Azure/azure-cli-extensions/pull/7019 
---

[AKS] `az aks stop`: Add warning when private link cluster is stopped

---

src/azure-cli/azure/cli/command_modules/acs/_help.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_with_nsg_control.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_nodepool_create_with_nsg_control.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_nodepool_update_with_nsg_control.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py

``` bash
az aks create \
--name ${CLUSTER_NAME} \
--nodepool-asg-ids ${ASG_0_ID} ${ASG_1_ID} \
--nodepool-allowed-host-ports 80/tcp 53/udp 4000-5000/tcp
az aks nodepool add \
--name ${AGENTPOOL_NAME} \
--asg-ids ${ASG_0_ID} ${ASG_1_ID} \
--allowed-host-ports 80/tcp 53/udp 4000-5000/tcp
az aks nodepool update \
--name ${AGENTPOOL_NAME} \
--asg-ids ${ASG_0_ID} ${ASG_1_ID} \
--allowed-host-ports 80/tcp 53/udp 4000-5000/tcp
```
refer: #27900 
Fix the live tests and command descriptions.
- {AKS} `az aks create`: Fix live tests and command description.
- {AKS} `az aks nodepool add`: Fix live tests and command description.
- {AKS} `az aks nodepool update`: Fix live tests and command description.
--- …

{AKS} `az aks create` | `az aks nodepool add/update`: Fix NSG control live tests and cmd description

---

src/azure-cli/azure/cli/command_modules/resource/_help.py
src/azure-cli/azure/cli/command_modules/resource/_params.py
src/azure-cli/azure/cli/command_modules/resource/custom.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_custom.py

`az bicep publish`
This is to expose the new experimental --with-source argument in the Bicep CLI for bicep publish.  See https://github.com/Azure/bicep/issues/11435.
See https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/quickstart-private-module-registry?tabs=azure-cli#publish-modules for instructions on publishing bicep modules to a private registry.
Example: Publishing bicep module in ~/repos/template-examples/complicated/main.bicep to br:myacr.azurecr.io/complicated:v1 and include source code with that module in the ACR.
```sh
az bicep publish -f ~/repos/template-examples/complicated/main.bicep --target br:myacr.azurecr.io/complicated:v1 --with-source
```
--- …

[ARM] `az bicep publish`: Add optional parameter `--with-source` to publish source code with the module (experimental)

---

src/azure-cli/azure/cli/command_modules/resource/custom.py

There is a ICM case reported that Azure CLI commands should make resource group case-insensitive comparison for `az lock delete`. 
ARM already performs case insensitive comparisons for RG names and that is standard across all APIs, so Azure CLI should keep the same logic
---

[ARM] `az lock delete`: Fix the case sensitive comparison issue for resource group name

---

src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_virtual_network.py

To avoid the redundant (y/n) in the prompt in which user is asked to confirm adding client IP address to the firewall, like in:
Do you want to enable access to client 20.82.64.133 (y/n) (y/n)
---

{RDBMS} `az postgres flexible-server create`: Remove duplicate (y/n) in first prompt from prepare_public_network

---

src/azure-cli/azure/cli/command_modules/profile/_validators.py

`az login`
Azure CLI migrated from ADAL to MSAL (https://github.com/Azure/azure-cli/pull/19853) which is powered by AAD v2.0. The tenant resolution logic (added by https://github.com/Azure/azure-cli/pull/10418) should do the same.
https://github.com/Azure/azure-cli/pull/14509 added unit tests `azure.cli.command_modules.profile.tests.latest.test_profile_custom.ProfileCommandTest.test_login_validate_tenant` for `azure.cli.command_modules.profile._validators.validate_tenant`.
`az login --tenant microsoft.onmicrosoft.com`
**Additional information**
Even though MSAL has special logic for handling ADFS:
https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/09d5ff9a71a51c998b83b356047230677825a622/msal/authority.py#L106-L …

{Profile} Use v2.0 authority to resolve tenant ID

---

.github/workflows/AddIssueComment.yml
.github/workflows/AddPRComment.yml

Starting February 1, 2024 the default permission for the GITHUB_TOKEN will change from Read/Write to Read-only for all Open Source GitHub orgs. 
Add permissions block to avoid breaking change to our workflows.
Learn more [here](https://docs.opensource.microsoft.com/github/apps/permission-changes/)
---

{CI} Add permissions block for `Github Action Permission Changes`

---

scripts/release/debian/build.sh

close #27961. After this PR, `/opt/az/lib/python3.11/test` folder is removed and it saves 122MB disk space.
Before:
```
❯ apt info azure-cli
Package: azure-cli
Version: 2.55.0-1~jammy
Priority: extra
Section: python
Maintainer: Azure Python CLI Team <azpycli@microsoft.com>
Installed-Size: 802 MB
```
After:
```
❯ apt info './azure-cli_2.55.0-1~jammy_amd64.deb'
Package: azure-cli
Version: 2.55.0-1~jammy
Priority: extra
Section: python
Maintainer: Azure Python CLI Team <azpycli@microsoft.com>
Installed-Size: 684 MB
```

{Packaging} Exclude Python test from DEB package

---

src/azure-cli/azure/cli/command_modules/keyvault/_validators.py

`az keyvault secret set-attributes`
Fix #28101 
`az keyvault secret set-attributes -n $secretName --vault-name $vaultName --not-before 2024-01-01`
---

[Keyvault] `az keyvault secret set-attributes`: Fix 'Datetime with no tzinfo will be considered UTC' warning

---

src/azure-cli-core/setup.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

`az login`
As https://github.com/Azure/azure-cli/pull/27726 is under debate, we will put `allow_broker`'s renaming on hold and first bump MSAL to the latest version. This will pick up https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/569, so that making WAM the default authentication method in the future (https://github.com/Azure/azure-cli/pull/28085) won't be a breaking change. See https://github.com/Azure/azure-cli/pull/28085#issuecomment-1870093562 for detailed explanation.

{Core} Bump MSAL to 1.26.0

---

src/azure-cli/azure/cli/command_modules/keyvault/custom.py

`az keyvault create`
Keyvault is planning to enable rbac authorization by default in next breaking change window. This PR is to add a warning to notify customers in advance.
---

[Keyvault] `az keyvault create`: Add warning for upcoming breaking change that `--enable-rbac-authorization` will default to `true`

---

src/azure-cli-core/azure/cli/core/commands/arm.py
src/azure-cli-core/azure/cli/core/tests/test_aaz_operation.py
src/azure-cli-core/azure/cli/core/tests/test_generic_update.py

Fix #27054
Partially fix #27056, #27057, #27058
Not fix #27467, #27468
All commands that support generic update arguments `--add`, `--set`, `--remove`.
Specifically:
- `az webpubsub update`
- `az mariadb server update`
- `az mysql flexible-server update`
- `az mysql server update `
- `az postgres flexible-server update`
- `az postgres server update`
As angle brackets `<>` are interpreted as HTML tag by the reference doc generation pipeline, the pipeline treats the help message of generic update arguments as HTML tags and gives error for these invalid HTML tags:
- `<key=value, string or JSON string>`
- `<value>`
- `<indexToRemove>`
They will be discarded from the rendered page, resulting in incorrect documentation:
This PR quotes these help messages with …

{Core} Fix reference doc for generic update arguments

---

build_scripts/windows/scripts/build.cmd
scripts/release/debian/build.sh

CVE-2023-4807 is fixed in Python 3.11.7.
Ref: https://github.com/python/cpython/issues/109991

{Packaging} Bump embedded Python version to 3.11.7

---

src/azure-cli/azure/cli/command_modules/sql/_help.py
src/azure-cli/azure/cli/command_modules/sql/_params.py
src/azure-cli/azure/cli/command_modules/sql/custom.py
src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py

Change ltr-policy and ltr-backup related commands to include new property "backup-storage-access-tier".
---

[Sql] `az sql db ltr-policy/ltr-backup`: Add support for backup storage access tier

---

src/azure-cli/azure/cli/command_modules/appservice/_client_factory.py
src/azure-cli/azure/cli/command_modules/appservice/commands.py

```az
az appservice plan create
```
Cleans outdated error messages related to App Service Plan creation. We no longer append "Plan with Linux worker can only be created in a group which has never contained a Windows worker, and vise versa." because this is no longer true (and has not been true for 2+ years).
We also make a Linux-specific error more generic in `_client_factory.py`, as nothing guarantees that this is only hit while creating a Linux App Service Plan.
I was able to reproduce the original error message with the following commands:
```az
az group create -n testgroup2 -l westus3
az appservice plan create --name windowstestplan --sku p1v3 -g testgroup2 --zone-redundant --number-of-workers 10
az appservice plan create --name …
```

{App Service} Clean error messages relating to ASP creation

---

src/azure-cli/azure/cli/command_modules/appservice/_params.py
src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_hyperv_acr_use_identity.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_linux_acr_use_identity.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

`az webapp create`
Add new parameter `--acr-use-identity` to configure pull image from ACR using MSI when creating a container web app. It allows user to update siteconfig acrUseManagedIdentityCreds while creating webapp, this can significantly reduce steps user needs to have to create a container webapp which pulls image from ACR using MSI.
1. Create webapps by running `az webapp create` command with and without `--acr-use-identity` to make sure webapp can be created successfully with new parameter also changes don't break webapp creation without this new parameter. And check the config of new created webapp by using `az webapp config show` to make sure siteconfig acrUseManagedIdentityCreds is updated as expected.
2. Create test …

[App Service] `az webapp create`: Add new parameter `--acr-use-identity` to configure pull image from ACR using MSI when creating a container web app

---

src/azure-cli/azure/cli/command_modules/vm/_client_factory.py
src/azure-cli/azure/cli/command_modules/vm/_format.py
src/azure-cli/azure/cli/command_modules/vm/custom.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_with_monitor.yaml
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

[Compute] `az vm monitor log show`: Deprecate `azure-loganalytics` and apply `azure-monitor-query`
---
closed https://github.com/Azure/azure-cli/issues/27952

[Compute] `az vm monitor log show`: Deprecate `azure-loganalytics` and apply `azure-monitor-query`

---

src/azure-cli/azure/cli/command_modules/acs/_help.py
src/azure-cli/azure/cli/command_modules/acs/_params.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_with_trustedaccess_rolebinding.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py

`az aks trustedaccess rolebinding create`
remove `az aks trustedaccess rolebinding create` command --source-resource-id parameter alias -r
---

{AKS} `aks trustedaccess rolebinding create`: Remove `--source-resource-id` parameter alias `-r`

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands_thru_mock.py

`az functionapp config container set`
When customers create Centauri function apps through the Portal, the daprConfig is set to null. If customers then try to update the daprConfig, workload profile name, cpu or memory through the CLI with the command `az functionapp config container set`, they will get an exception because we do not currently check that daprConfig is not null. This PR makes sure that daprConfig is not null. 
1. Create Centauri function app through the Portal
2. Attempt to update the workload profile name, cpu and memory. You will get a failure without the changes in this PR. 
---

{AppService} `az functionapp config container set`: Check if dapr config is null before updating settings

---

src/azure-cli/azure/cli/command_modules/appservice/_help.py

`az functionapp config appsettings set`
Based on the feedback from this GitHub issue, the quotation marks in the documentation might confuse customers: https://github.com/Azure/azure-cli/issues/28071
---

{AppService} `az functionapp config appsettings set`: Update example documentation

---

src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/private_link/_add.py

`az network application-gateway private-link add`
This Pull Request addresses the issue of unhelpful error messages when a user inputs a name exceeding 37 characters in the az network application-gateway private-link add command. Currently, the error message for an excessively long name is generic and does not guide the user effectively. This PR aims to implement a more informative error message, clearly stating that the name exceeds the 37-character limit and advising the correct format.
38 characters name test
```console
$ PRIVATELINK_NAME=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKL
$ az network application-gateway private-link add --frontend-ip <your_frontend_ip> --gateway-name <your_appgw_name> --name $PRIVATELINK_NAME --resource-group …
```

{Network} `az network application-gateway private-link add`: Improve error message for excessive name length

---

scripts/regression_test/extension_regression_test.yml
scripts/regression_test/regression_test.yml

After enabling MFA, regression test pipeline keeps failing with :
```
AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'. Trace ID: 7108615d-16d4-4949-ab36-1cc83cfb7900 Correlation ID: 7dd265e3-980e-4065-be5b-a75b9db28359 Timestamp: 2024-01-29 18:09:48Z
Interactive authentication is needed
```
This PR removed the login with username password and use service connection instead
--- …

{CI} Fix regression test pipeline

---

src/azure-cli/azure/cli/command_modules/resource/custom.py

az bicep generate-params
Remove the sending of Bicep install messages to standard output (stdout) during Bicep auto installation when running `az bicep generate-params`
[ARM] Fix #27855: `az bicep generate-params`: Bicep install messages sent to stdout
---

[ARM] Fix #27855: `az bicep generate-params`: Bicep install messages sent to stdout

---

src/azure-cli/azure/cli/command_modules/apim/_help.py
src/azure-cli/azure/cli/command_modules/apim/_params.py
src/azure-cli/azure/cli/command_modules/apim/commands.py
src/azure-cli/azure/cli/command_modules/apim/custom.py
src/azure-cli/azure/cli/command_modules/apim/tests/latest/recordings/test_apim_deletedservice.yaml
src/azure-cli/azure/cli/command_modules/apim/tests/latest/recordings/test_apim_export_api.yaml
src/azure-cli/azure/cli/command_modules/apim/tests/latest/test_apim_scenario.py

az apim api export -g Api-Default-Central-US-EUAP --service-name arpishahtestapim --api-id echo-api --format OpenApiJson --file-path C:\Users\arpishah\examples\cli-examples\exported-results\exported-apim-results
This PR is to add export apim cli command. The import command was already present but the export command was not present. This change exports an API present in the APIM instance to a file based on the format specified or to a link. This is controlled by the format parameter
az apim api export -g Api-Default-Central-US-EUAP --service-name arpishahtestapim --api-id echo-api --format OpenApiJson --file-path C:\Users\arpishah\examples\cli-examples\exported-results\exported-apim-results 
Here the api echo-api present in …

[API Management] `az apim api export`: Add command to export an API Management API

---

src/azure-cli/azure/cli/command_modules/rdbms/_config_reader.py
src/azure-cli/azure/cli/command_modules/rdbms/config.json
src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_virtual_network.py

Add support for OSSHF cluster to fetch private DNS zone domain name
Add support for OSSHF cluster to fetch private DNS zone domain name
az postgres flexible-server create -g cli-test-do-not-delete-rg-southcentralus -n cli-test-server-pg-flex-ha-vnet-southcentralus -l southcentralus --geo-redundant-backup Enabled --high-availability ZoneRedundant --vnet cli-test-osshf-pg-flex-vnet-southcentralus --subnet cli-test-osshf-pg-flex-subnet-southcentralus --private-dns-zone cli-test-osshf-pg-flex-dns-southcentralus.pg.osshf-scus1-a.mscds.com
Checking the existence of the resource group 'cli-test-do-not-delete-rg-southcentralus'...
Resource group 'cli-test-do-not-delete-rg-southcentralus' exists ? : True 
You have supplied a …

{RDBMS} Add support for osshf cluster

---

src/azure-cli/azure/cli/command_modules/storage/_params.py
src/azure-cli/azure/cli/command_modules/storage/_validators.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_batch_operations.py

Support
Fix #28341 `az storage blob upload-batch`: Support `--tags`, make `--overwrite` non-preview, and group up params in Additional Flags Arguments (no functional change)
[Storage] `az storage blob upload-batch`: Support `--tags`, make `--overwrite` non-preview
---

[Storage] Fix #28341: `az storage blob upload-batch`: Support `--tags`, make `--overwrite` non-preview, update arg group

---

src/azure-cli-core/azure/cli/core/commands/__init__.py

In #27929, we add secrets warning for cli commands to warn customers when the command output contains credentials. But the warning message will still show when customers filter out the credential from output using global argument `--query` and `--output`.
This PR fixes this issue by:
- move the warning logic after query filtering logic
- only show warning when `--output` is not `none`
---

{Core} Secrets warning will honor `--query` filter and `--output none`

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/auth/identity.py
src/azure-cli-core/azure/cli/core/auth/landing_pages/success.html
src/azure-cli-core/azure/cli/core/telemetry.py

`az login`
This PR adopts the MSAL change https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/613 where MSAL will deprecate `allow_broker` and use `enable_broker_on_windows`.
```
az config set core.enable_broker_on_windows=true
az login
az config unset core.enable_broker_on_windows
az login
```

{Core} Replace `allow_broker` with `enable_broker_on_windows`

---

src/azure-cli/azure/cli/command_modules/acs/_loadbalancer.py
src/azure-cli/azure/cli/command_modules/acs/_natgateway.py
src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_loadbalancer_then_update.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_loadbalancer.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_natgateway.py

`az aks update --load-balancer-outbound-ports 0`
related: #27071
allow customer to set --load-balancer-outbound-ports, --nat-gateway-managed-outbound-ip-count, --load-balancer-managed-outbound-ipv6-count to 0
create a aks cluster and run following command
`az aks update --load-balancer-outbound-ports 0`
[AKS] `az aks update`: Zero can be set to outbound-ports,outbound-ip-count in loadbalancer profile and outbound-ip-count in natgateway profile in aks
---

{AKS} Support reset default value for loadbalancer profile and natgateway profile

---

azure-pipelines.yml

Temporarily disable Credential Scanner
https://dev.azure.com/azclitools/public/_build/results?buildId=133760&view=logs&j=9a50307c-53e6-51fa-ddad-d8767a4a0ece&t=854f603a-ce91-59a3-a3f0-bfbaa050f0db
```
Attempting to gather dependency information for package 'Microsoft.Security.CredScan.2.1.17' with respect to project 'D:\a\_work\_sdt', targeting 'Any,Version=v0.0'
MSBuild auto-detection: using msbuild version '16.11.2.50704' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin'.
Using credentials from config. UserName: VssSessionToken
WARNING: The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or …
```

{CI} Disable Credential Scanner

---

src/azure-cli/azure/cli/command_modules/rdbms/_transformers.py

az postgres flexible-server list-skus
The `list-skus` sub-command with table output has been giving empty result (reported in #27713). This PR fixes this problem and list the available SKUs for a region.
az postgres flexible-server list-skus --location eastus -o table
az postgres flexible-server list-skus --location norwayeast -o table
---

[RDBMS] Fix #27713: `az postgres flexible-server list-skus -o table`: Fix table output from list-skus command

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/auth/landing_pages/success.html
src/azure-cli-core/setup.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

`az login`
Fix https://github.com/Azure/azure-cli/issues/26573
Fix https://github.com/Azure/azure-cli/issues/28417
Require https://github.com/Azure/azure-cli/pull/27726
After previewing WAM for over a year (https://github.com/Azure/azure-cli/pull/23828), we now use WAM as the default authentication method on Windows.
This PR bumps MSAL to 1.27.0 (https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/669) which raised the upper bound of `pymsalruntime` (https://github.com/AzureAD/microsoft-authentication-library-for-python/commit/59c3000192e92a49f483045071b97aa79929d19f). This fixes the issues with PIM (https://github.com/Azure/azure-cli/issues/26573) and VM SSH (https://github.com/Azure/azure-cli/issues/28417). …

[Core] Use WAM as the default authentication method on Windows

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/auth/landing_pages/success.html
src/azure-cli-core/setup.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

`az login`
Revert #28085: Use WAM as the default authentication method on Windows

{Core} Revert #28085

---

src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/test_cosmosdb_commands.py

az cosmosdb sql container update --account-name account_name --database-name database_name --name container_name --resource-group resource_group_name --analytical-storage-ttl 0
Ignore test_cosmosdb_sql_container_update_disable_analytics which validates cli command to disable analytical storage. This test is currently failing because of a change to block collection requests to disable analytics in production. Once requests to collection requests to disable analytics are supported again we will reinstate this test. In the meantime the change in this PR will ignore the test so it does not block CLI deployments. 
N/a
---

{cosmosdb} Ignore CosmosDb Analytical Storage Disable Test 

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_ssl.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_ssl_specify_hostname.yaml

az webapp config ssl upload
At PR: https://github.com/Azure/azure-cli/pull/28306
azure-cli will update version from pyOpenSSL==23.2.0 to pyOpenSSL==24.0.0
OpenSSL.crypto.loads_pkcs12 is removed in 23.3.0.
Ref: https://www.pyopenssl.org/en/latest/changelog.html
azdev test test_webapp_ssl
azdev test test_webapp_ssl_specify_hostname
---

{AppService} `az webapp config ssl upload`: Remove deprecated `OpenSSL.crypto.loads_pkcs12` for bumping `pyOpenSSL` to `24.0.0`

---

src/azure-cli-core/setup.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

`az login`
MSAL 1.27.0 (https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/669) contains several improvements.
The most significant one is to tolerate ID token time errors (https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/657) which will solve 2 very common issues:
- RuntimeError: 0. The ID token is not yet valid. (https://github.com/Azure/azure-cli/issues/20388)
- RuntimeError: 9. The ID token already expires. (https://github.com/Azure/azure-cli/issues/23223)

{Core} Bump MSAL to 1.27.0 and pin `pymsalruntime` to 0.14.0

---

src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/azuremonitorprofile.py

… 
```az aks create -n kaveeshcli22 -g kaveeshcli --location westeurope --enable-azure-monitor-metrics --azure-monitor-workspace-resource-id "{full_id}" --grafana-resource-id "{full_id}"```
```az aks create -n kaveeshcli22 -g kaveeshcli --disable-azure-monitor-metrics ```
```az aks update -n kaveeshcli22 -g kaveeshcli --enable-azure-monitor-metrics --enable-windows-recording-rules```
block Azure Mnaaged Grafana for managed prometheus addon in air gapped cloud as its not available there yet.
**Scenario (managed prometheus support in air gapped cloud)**:
- Set context to one of the air gapped clouds
- Use the command with the grafana-resource-id parameter similar to `az aks create -n kaveeshcli22 -g kaveeshcli --location westeurope …

[AKS] `az aks create/update`: Block Azure Managed Grafana for managed prometheus addon in air gapped cloud

---

src/azure-cli/azure/cli/command_modules/batch/tests/latest/test_batch_mgmt_commands.py

Fix https://github.com/Azure/azure-cli/issues/28500
---

{Batch} Fix race condition in test

---

build_scripts/windows/scripts/build.cmd
scripts/release/debian/build.sh

Update Windows build to use OpenSSL 3.0.13 which fixes some CVE.
Ref: https://docs.python.org/release/3.11.8/whatsnew/changelog.html#python-3-11-8

{Packaging} Bump embedded Python version to 3.11.8

---

src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/virtual_appliance/_create.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/virtual_appliance/_delete.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/virtual_appliance/_list.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/virtual_appliance/_show.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/virtual_appliance/_update.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/virtual_appliance/_wait.py

Network
Added support for network-profile and internet-ingress-ips in virtual-appliance create, update, show, list
//Create Command
```shell
python C:/azure-cli/src/azure-cli/azure/cli/__main__.py network virtual-appliance create -g vimalcha-2-mnva-erbvt -n vimalcha-2-cli-testing-from-cli-with-np-slb  --vhub "/subscriptions/1feaed13-01fa-4f52-9c74-3b5305513c89/resourceGroups/vimalcha-2-mnva-erbvt/providers/Microsoft.Network/virtualHubs/vimalcha-2-erbvt-vhub" --vendor "fortinet" --scale-unit 2 -v latest --asn 64512 --init-config "echo $hello"  --network-profile "{network_interface_configurations:[{type:PublicNic,ip_configurations:[{name:publicnicipconfig,primary:true},{name:publicnicipconfig-vimalcha2,primary:false}]},{type:PrivateNic,ip …
```

[Network] `az network virtual-appliance`: Add `--internet-ingress-ips` and `--network-profile`

---

src/azure-cli/azure/cli/command_modules/appservice/_constants.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py

1. Add Node 20 support
2. Update default runtimes to be Node 20 and Python 3.11
3. Add MSI support for deployment auth
[AppService] `az functionapp create`: Add support for Node 20 for Flex function apps 
[AppService] `az functionapp create`: Make Node 20 the default for node flex function apps and Python 3.11 the default for python flex function apps
[AppService] `az functionapp create`: Add support for SystemAssignedIdentity and UserAssignedIdentity as the deployment storage authentication type
---

{AppService} `az functionapp create`: Update runtimes and add MSI support

---

src/azure-cli/azure/cli/command_modules/acs/_help.py

`az aks create --help`
This fixes some typos and missing hyphens in the phrase "comma-separated".
[AKS] `az aks create`: Correct use of "comma-separated" in help
---

{AKS} `az aks create`: Correct use of "comma-separated" in help

---

src/azure-cli/azure/cli/command_modules/role/_help.py
src/azure-cli/azure/cli/command_modules/role/_params.py
src/azure-cli/azure/cli/command_modules/role/custom.py
src/azure-cli/service_name.json

`az ad`
This PR renames Azure Active Directory to Microsoft Entra ID following rules defined in
- https://learn.microsoft.com/en-us/entra/fundamentals/new-name
- https://learn.microsoft.com/en-us/entra/fundamentals/how-to-rename-azure-ad
The help messages for `app`, `sp`, `user` and `group` are very inconsistent:
- `app`: Manage applications with AAD Graph.
- `sp`: Manage Azure Active Directory service principals for automation authentication.
- `user`: Manage Azure Active Directory users and user authentication.
- `group`: Manage Azure Active Directory groups.
This PR unifies those help messages to a format of `Manage Microsoft Entra xxx`. ~I don't feel the necessity of prefixing the entities with `Microsoft Entra` as they are already under the `az ad` …

[AD] `az ad`: Rename Azure Active Directory to Microsoft Entra ID

---

src/azure-cli/azure/cli/command_modules/vm/custom.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_soft_delete.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_image_version_create_for_diff_source.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

`az sig image-version create`
close https://github.com/Azure/azure-cli/issues/28488
---

{Compute} `az sig image-version create`: Change `--virtual-machine` parameter map to new VM backend field

---

src/azure-cli/azure/cli/command_modules/resource/custom.py
src/azure-cli/azure/cli/command_modules/resource/tests/hybrid_2018_03_01/param-validation-template-$ref-indirection.json
src/azure-cli/azure/cli/command_modules/resource/tests/hybrid_2019_03_01/param-validation-template-$ref-indirection.json
src/azure-cli/azure/cli/command_modules/resource/tests/latest/nullable_params_are_not_required/main.bicep
src/azure-cli/azure/cli/command_modules/resource/tests/latest/param-validation-template-$ref-indirection.json
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py

Treat nullable parameters as non-required (https://github.com/Azure/bicep/issues/13350)
Closes #28595
```sh
az deployment sub create \ 
--location westus \
--template-file main.bicep
```
[ARM] `az deployment`: Treat nullable parameters as non-required for Bicep deployment
---

[ARM] `az deployment`: Treat nullable parameters as non-required for Bicep deployment

---

src/azure-cli/azure/cli/command_modules/rdbms/custom.py

All commands
Add below warning message for ALL Single Server CLI commands (create, manage, restore etc) and ALL Terraform CLI commands for Single Server : 
Azure Database for MySQL - Single Server is scheduled for retirement (https://go.microsoft.com/fwlink/?linkid=2216041) by September 16, 2024. Migrate (https://go.microsoft.com/fwlink/?linkid=2202255) to Azure Database for MySQL- Flexible Server now.
---

{MYSQL} Add retirement warning for mysql single server and mariadb

---

src/azure-cli-core/setup.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

`az login`
MSAL Python 1.28.0: https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/679

{Core} Bump MSAL to 1.28.0 and PyMSALRuntime to 0.14.2a1

---

src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/azuremonitorprofile.py

```az aks create -n kaveeshcli22 -g kaveeshcli --disable-azure-monitor-metrics ```
Add a warning message to tell the customer that disabling the addon will also delete any custom resource 
**Scenario**:
- Use the command listed above to disable the addon
- It should result in a prompt warning and should continue with the disablement on a yes and raise an exception if cancelled.
---

[AKS] `az aks create/update`: Prompt warning during disablement about CR deletion

---

src/azure-cli-core/azure/cli/core/mock.py
src/azure-cli-testsdk/azure/cli/testsdk/base.py

Resolve #28668
Knack ignores the `config_dir` param when `AZURE_CONFIG_DIR` env is set, and other functions may call `get_config_dir` directly.
So this PR patches `AZURE_CONFIG_DIR` env when `random_config_dir=true` during test

{Core} Fix `random_config_dir` when `AZURE_CONFIG_DIR` is set

---

src/azure-cli/azure/cli/command_modules/rdbms/config.json

Add support for OSSRC cluster to fetch private DNS zone domain name
Add support for OSSRC cluster to fetch private DNS zone domain name
2024-04-02T17:50:12.7503690Z 2024-04-02 17:50:12 [INFO] Started executing command az postgres flexible-server create -g cli-temp-rg-49b85861f5384246995bb3111c5a8597 -n cli-temp-pg-flex-ha-vnet-756c7321cc1744ff9f3f1c31e1be -l southcentralus --high-availability ZoneRedundant --vnet cli-test-pg-flex-vnet-southcentralus39c1cf1fe76a40cf8 --subnet cli-test-pg-flex-subnet-southcentralus39c1cf1fe76a40c **--private-dns-zone cli-test-pg-flex-dns-southcentralus39c1cf1fe76a40c.pg.ossrc-scus1-a.mscds.com** -y
2024-04-02T18:01:06.0212348Z 2024-04-02 18:01:06 [INFO] Result: 0 …

{RDBMS} Add support for ossrc cluster

---

src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/amw/defaults.py
src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/amw/helper.py
src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/azuremonitorprofile.py
src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/helper.py
src/azure-cli/azure/cli/command_modules/acs/tests/test_helper.py

```az aks create -n kaveeshcli22 -g kaveeshcli --location westeurope --enable-azure-monitor-metrics --azure-monitor-workspace-resource-id "{full_id}" --grafana-resource-id "{full_id}"```
```az aks create -n kaveeshcli22 -g kaveeshcli --disable-azure-monitor-metrics ```
```az aks update -n kaveeshcli22 -g kaveeshcli --enable-azure-monitor-metrics --enable-windows-recording-rules```
I am updating the rp registration logic to register the RP on the azure monitor workspace subscription if its provided as a parameter to the command and if it is not provided then it should work on the clusters subscription.
**Scenario (RP registration)**:
- Use the command with and without the azure-monitor-workspace-resource-id parameter similar to `az aks …

[AKS] `az aks create/update`: Udpate RP registration code to work on azure monitor subscription

---

src/azure-cli/azure/cli/command_modules/rdbms/_params.py

`az postgres flexible-server upgrade -g testgroup -n testsvr -v 16`
To GA major version upgrade (MVU) to PG16, allowing passing in 16 to upgrade command argument.
Manually tested
PS C:\Users\nasc\azureCLI\azure-cli>  C:; cd 'C:\Users\nasc\azureCLI\azure-cli'; & 'c:\Users\nasc\azureCLI\azure-cli\env\Scripts\python.exe' 'c:\Users\nasc\.vscode\extensions\ms-python.python-2024.4.0\python_files\lib\python\debugpy\adapter/../..\debugpy\launcher' '65045' '--' 'C:\Users\nasc\azureCLI\azure-cli/src/azure-cli/azure/cli/__main__.py' 'postgres' 'flexible-server' 'upgrade' '--name' 'nasc-canary13' '-g' 'nasc-testfree' '-v' '16' 
Updating major version in server nasc-canary13 is irreversible. The action you're about to take can't be undone. Going …

[RDBMS] Add support for major version upgrade to PG16

---

src/azure-cli/azure/cli/command_modules/mysql/commands.py

az mysql flexible-server advanced-threat-protection-setting
Advanced Threat Protection for Azure MySQL is GA, removed the CLI preview tag.
---

{Mysql} Removed preview tag from Advanced Threat Protection for Azure MySQL

---

src/azure-cli/azure/cli/command_modules/netappfiles/aaz/latest/netappfiles/volume/_create.py
src/azure-cli/azure/cli/command_modules/netappfiles/aaz/latest/netappfiles/volume/_update.py
src/azure-cli/azure/cli/command_modules/netappfiles/custom.py

az netappfiles
Adds `zones` as a convenience argument to `az netappfiles create volume-group` as users had expressed difficulty passing `zones` in with complex paramter `volumes`
[NetAppFiles] `az netappfiles volume-group create`: Add `zones` argument to set Availability Zone for volume group volumes
[NetAppFiles] `az netappfiles volume create`: Update maximum value for `--usage-threshold` to support large volumes
[NetAppFiles] `az netappfiles volume update`: Update maximum value for `--usage-threshold` to support large volumes
---

[NetAppFiles] Add zones to volume-group, update min for usage-threshold volume create

---

src/azure-cli-core/setup.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

Fix https://github.com/Azure/azure-cli/issues/28737
`az login`
`az account get-access-token`
Bump `msal-extensions` to 1.2.0b1 in order to adopt https://github.com/AzureAD/microsoft-authentication-extensions-for-python/pull/128.
```
$ az login --service-principal
$ az account get-access-token
...
"expiresOn": "2024-04-15 19:57:04.000000",
"expires_on": 1713182224,
...
$ az account get-access-token
...
"expiresOn": "2024-04-15 19:57:04.000000",
"expires_on": 1713182224,
...
```
Notice executing `az account get-access-token` twice will return the same `expiresOn` and `expires_on`.
[Core] Fix #28737: Azure CLI tasks can now run longer than 5 minutes utilizing the token cache

{Core} Bump `msal-extensions` to 1.2.0b1

---

src/azure-cli/azure/cli/command_modules/storage/operations/blob.py
src/azure-cli/azure/cli/command_modules/storage/operations/blob_azure_stack.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_blob_copy_scenarios.py

`az storage blob show` when `az storage blob copy start` is in progress with a page blob
`GetPageRange` call would give 409 error code when there is an in-progress copy with a large page blob across regions. (as same region could finish instantly)
`az storage blob show` should still return with result from `GetBlobProperties`. 
Simply give waring if `GetPageRange` fails
https://learn.microsoft.com/rest/api/storageservices/get-page-ranges?tabs=microsoft-entra-id#remarks
Fix #28727 
--- …

{Storage} `az storage blob show`: Use try catch for `GetPageRange` after `GetBlobProperties` in `blob show`

---

src/azure-cli/azure/cli/command_modules/storage/operations/fileshare.py

`az storage share close-handle`
Fix issue #27671. Specifying a handle id with `--handle` fails with a stack trace because the `recursive` argument is sent down in `kwargs` by default, then another `recursive=None` is added because closing a handle cannot be recursive.
Just find a handle on an Azure File share with `az storage share list-handle` and try to close it with `az storage share close-handle --handle ...`.
N/A
---

{Storage} Fix #27671: `az storage share close-handle`: Fix duplicate kwarg error when closing a handle by id

---

src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/azure/cli/core/commands/constants.py

After adding global credential warning in cli core (#27929), `az ad sp create-for rbac` will show duplicate warning messages. It's better to keep the command specific warning and suppress generic warning.
---

{Core} Remove duplicate credential warning

---

src/azure-cli/azure/cli/command_modules/appservice/_validators.py

az webapp config access-restriction add
Fixing an issue where ["values"] was addressed before checking for null. This would cause issues for customers without permissions to read the service tag list (subscription/read)
Add an access restriction without having subscription/read permissions
---

[App Service] Fix #28588: `az webapp config access-restriction add`: Check for null before getting values

---

src/azure-cli/azure/cli/command_modules/appservice/_params.py
src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_list_show_details.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

`az webapp list`
Add new parameter `--show-details` for `az webapp list` to show detailed site configuration in output. For example, after adding this parameter java webapp user can directly query their java related configurations, like java version, java container and java container version when running `az webapp list`
Ran changed command locally and added test for this change
---

[AppService] `az webapp list`: Add parameter `--show-details` to include detailed site configuration of listed webapps in output

---

src/azure-cli/azure/cli/command_modules/resource/_bicep.py
src/azure-cli/azure/cli/command_modules/resource/custom.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py

Return better message on incorrect bicepparam file path
Closes #27989
```sh
az deployment mg create \
--management-group-id mymanagementgroup \
--location westeurope \
--parameters parameters/notfound.bicepparams
```
[ARM] `az deployment`: Return better message on incorrect bicepparam file path
---

[ARM] `az deployment`: Return better message on incorrect bicepparam file path

---

src/azure-cli/azure/cli/command_modules/resource/_help.py
src/azure-cli/azure/cli/command_modules/resource/_params.py
src/azure-cli/azure/cli/command_modules/resource/custom.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_custom.py

- `az bicep format`
- `az bicep publish`
Some of the Bicep CLI and `az bicep format | publish` command arguments use camel case, which violates the convention to use kebab case. The PR deprecates the camel case arguments.
- `az bicep format -f main.bicep --newline LF`
- `az bicep publish -f main.bicep --documentationUri {documentationUri}`
[ARM] `az bicep format`: Replace `--newline` with `--newline-kind`
[ARM] `az bicep publish`: Replace `--documentationUri` with `--documentation-uri`
---

[ARM] Deprecate command arguments for `az bicep format` and `az bicep publish`

---

src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py
src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
src/azure-cli/azure/cli/command_modules/rdbms/validators.py

`az postgres flexible-server migration create --subscription sub --resource-group testGroup --name testserver --migration-name testmigration --properties "migrationConfig.json"`
SDK may not get bumped up in time to include these changes in current milestone.
Revert #28695 
---

{RDBMS} Revert - Add MigrationRuntimeResourceId to properties of creating migration request in CLI

---

src/azure-cli/azure/cli/command_modules/acr/_params.py
src/azure-cli/azure/cli/command_modules/acr/connected_registry.py
src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_connectedregistry_commands.py

az acr connected-registry create
Minor updates on ACR connected registry create:
- mode default value change to readOnly
- if data endpoint disable ask for enabling it instead of throwing an error.
[ACR] BREAKING CHANGE: `az acr connected-registry create`: Mode default value change from ReadWrite to ReadOnly
[ACR] `az acr connected-registry create`: If data-endpoint disabled ask for confirmation to enable it instead of throwing an error
---

[ACR] OnPrem: Connected-registry create: Mode default value changed to readOnly

---

src/azure-cli/azure/cli/command_modules/acs/_params.py
src/azure-cli/azure/cli/command_modules/acs/custom.py
src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_azure_service_mesh_canary_upgrade.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py

`az aks mesh upgrade rollback -g myResourceGroup -n myCluster --revision asm-1-20`
`az aks mesh upgrade complete -g myResourceGroup -n myCluster`
This change allows customers to suppress warnings while using `az aks mesh upgrade rollback` and `az aks mesh upgrade complete` commands. This is particularly helpful with automation of service mesh upgrade revisions.
`az aks mesh upgrade rollback -g myResourceGroup -n myCluster --revision asm-1-20 --yes`
`az aks mesh upgrade complete -g myResourceGroup -n myCluster --yes`
both the above commands should not prompt the users to confirm the operation.
---

[AKS] `aks mesh upgrade rollback/complete`: Add `--yes` parameter to support not prompting the users to confirm the operation

---

.azure-pipelines/templates/azdev_setup.yml
src/azure-cli-core/azure/cli/core/mock.py

Temporally bypass https://github.com/Azure/azure-cli/issues/28848
Final fix should be done by https://github.com/Azure/azure-cli/pull/28849
Running `test_containerapp_manualjob_withsecret_crudoperations_e2e` and `test_hdinsight_application` sequentially fails with 
```
$ azdev test test_containerapp_manualjob_withsecret_crudoperations_e2e test_hdinsight_application --series -a -rP
...
self = <azure.cli.core._session.Session object at 0x7f15c1b06410>
def save(self):
if self.filename:
>           with open(self.filename, 'w', encoding=self._encoding) as f:
E           FileNotFoundError: [Errno 2] No such file or directory: '/home/user2/.azure/dummy_cli_config_dir/mvDaOhlAGfu4OvI6/commandIndex.json'
src/azure-cli-core/azure/cli/core/_session.py:54: FileNotFoundError
```
As …

{testsdk} Copy command index to random config dir

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py

- az functionapp scale config always-ready
For Flex Function App, it sets alwaysReady property to empty array when it is null. It is to avoid the exception which is thrown if the mentioned property is not iterable. 
Create a function app
`az functionapp create -g <resource-group> -n <function-app-name> -s flexeastorage --functions-version 4 --debug --runtime python --runtime-version 3.11 --flexconsumption-location '"eastasia"' --debug --deployment-storage-auth-type storageAccountConnectionString`
Update the scale config of the function app
`az functionapp scale config always-ready set -g <resource-group> -n <function-app-name> --settings http=1 functionfunction1=1`

[App Service] `az functionapp scale config always-ready`: Set alwaysReady property to empty array if it is null

---

src/azure-cli/azure/cli/command_modules/serviceconnector/_transformers.py
src/azure-cli/azure/cli/command_modules/serviceconnector/_utils.py
src/azure-cli/azure/cli/command_modules/serviceconnector/_validators.py
src/azure-cli/azure/cli/command_modules/serviceconnector/commands.py
src/azure-cli/azure/cli/command_modules/serviceconnector/custom.py

az aks connection list
az aks connection show
This PR adds kubernetes resource name to align with Portal behavior. Customers can use `kubernetesResourceName` as key to query in a linker result. 
az aks connection list --source-id {aks-cluster-id}
az aks connection show --id {linker-id}
[Service Connector] `az aks connection list/show': Add kubernetes resource name
---

[Service Connector] `az aks connection list/show`: Add kubernetes resource name

---

src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_agentpool_decorator.py

```
az aks nodepool add --name npwin --os-type Windows --disable-windows-outbound-nat
```
Refer to the [cli-extension/aks-preview PR](https://github.com/Azure/azure-cli-extensions/pull/7548)
- Correct the property `disable_outbound_nat` in `windows_profile`. Since customers cannot directly invoke the logic, there is no external impact.
- Why wasn't the error caught earlier? - Because `self.agentpool` is always `None` in customer usage, the code reads from `self.raw_param.get("disable_windows_outbound_nat")` directly, which means the code was not triggered.
- Add UT to validate the `get_disable_windows_outbound_nat` function when the property had been assigned a value.
- azdev test --live …

{AKS} Correct the property `disable_outbound_nat` in `windows_profile` and add UT

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/auth/landing_pages/success.html

Redo #28085
`az login`
After previewing WAM for over a year (https://github.com/Azure/azure-cli/pull/23828), we now use WAM as the default authentication method on Windows.
```sh
az login
az config set core.enable_broker_on_windows=false
az login
```
[Core] BREAKING CHANGE: `az login`: Use WAM as the default authentication method on Windows. If you encounter any issue and want to revert to the previous browser-based authentication method, run `az account clear`, `az config set core.enable_broker_on_windows=false` and `az login`

[Core] Redo: Use WAM as the default authentication method on Windows

---

scripts/release/debian/deb_install.sh

This PR:
- replaces the One-Line-Style format with the deb822 format, which will be the default in Ubuntu 24.04. See eg https://discourse.ubuntu.com/t/spec-apt-deb822-sources-by-default/29333 and https://repolib.readthedocs.io/en/latest/deb822-format.html
- performs basic shell linting
- is related to, and aligns with, https://github.com/MicrosoftDocs/azure-docs-cli/pull/4106

{Packaging} Use deb822 format in DEB installation script

---

src/azure-cli/azure/cli/command_modules/containerapp/_compose_utils.py
src/azure-cli/azure/cli/command_modules/containerapp/custom.py
src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_compose_create_environment_to_target_location.yaml
src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_compose_basic.py

Fix issue: https://github.com/Azure/azure-cli-extensions/issues/7542
---

[Container app] `az containerapp compose create`: Fix issue where the environment's location is not resolved from `--location`

---

src/azure-cli/azure/cli/command_modules/resource/custom.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py

Support inline parameters with `.bicepparam` in single `--parameters` argument
```sh
az deployment group create \
--resource-group ant-test \
--location westeurope \
--parameters foo.bicepparam override=bar
```
[ARM] `az deployment`: Support inline parameters with `.bicepparam` in single `--parameters` argument
---

[ARM] `az deployment`: Support inline parameters with `.bicepparam` in single parameter `--parameters`

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_consumption_linux_dotnet_isolated.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py

Resolves one of the issues in #28394 
The changes in this PR will use the linuxFxVersion value from the stacks API
[AppService] `az functionapp create`: The linuxFxVersion for dotnet-isolated linux consumption apps will no longer be left empty
---

[AppService] `az functionapp create`: Use linuxFxVersion value from stacks API for dotnet-isolated

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py

`az functionapp config appsettings set`
`az functionapp deployment source config-zip`
`az functionapp config set`
`az functionapp config container set`
Resolves #28394
Resolves #28382 
Resolves #28358 
Currently, we throw an error if we are unable to detect the runtime. However, there are many reasons why a linux app might not have a "conventional" runtime and runtime version (e.g. custom apps, centauri apps, apps running a docker image). For that reason, we should not be blocking command execution but should show a warning for how to set linuxFxVersion if we are unable to detect it and should not even show a warning when it is not applicable (e.g. centauri apps, apps running a docker image)
[AppService] `az …

[AppService] `az functionapp`: Only show warning but not throw error when checking runtime

---

azure-pipelines.yml
scripts/release/debian/build.sh

Ubuntu 18.04 reached its EOL in June 2023.
Drop it to reduce the maintenance efforts as we support 24.04 now.
Ref: https://wiki.ubuntu.com/Releases

[Packaging] Drop Ubuntu 18.04 support

---

src/azure-cli/azure/cli/command_modules/rdbms/config.json

Related command
Add support for Left Shift clusters in region westus3. Needed for Geo restore test.
Description
Add support for Left Shift clusters in region westus3. Needed for Geo restore test.
Testing Guide

{RDBMS} Add support for left-shift clusters in westus3

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/style.py
src/azure-cli-core/azure/cli/core/telemetry.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/azure-cli/azure/cli/command_modules/profile/_subscription_selector.py
src/azure-cli/azure/cli/command_modules/profile/custom.py
src/azure-cli/azure/cli/command_modules/profile/tests/latest/test_subscription_selector.py
src/azure-cli/azure/cli/command_modules/util/custom.py
src/azure-cli/setup.py

`az login`
Interactive commands now prompt the user to interactively select the default subscription and tenant:
- `az login`: Auth code flow/WAM
- `az login --use-device-code`: Device code flow
Automation commands are not affected:
- `az login --username --password`: Username password flow
- `az login --service-principal`: Service principal authentication
- `az login --identity`: managed identity authentication
`az login`
`az login --use-device-code`
Turn off:
```
az config set core.login_experience_v2=off
az login
```
**Additional Information**
Require #28660
[Component Name 2] `az command b`: Add some customer-facing …

{Profile} Login experience v2

---

scripts/release/debian/deb_install.sh

Resolve #28984.
There is [no tty in GitHub runner](https://github.com/actions/runner/issues/241). This error is raised when run `gpg --dearmor -o /etc/apt/keyrings/microsoft.gpg`:
`gpg: cannot open '/dev/tty': No such device or address`
The reason is that this file already exists in the agent:
```
ls -la /etc/apt/keyrings/
total 20
drwxr-xr-x 2 root root 4096 May 16 11:42 .
drwxr-xr-x 8 root root 4096 May 16 11:10 ..
-rw-r--r-- 1 root root 2825 May 16 11:31 github_git-lfs-archive-keyring.gpg
-rw-r--r-- 1 root root 1200 May 16 11:42 kubernetes-apt-keyring.gpg
-rw-r--r-- 1 root root  641 May 16 11:20 microsoft.gpg
```
And `gpg` wants to ask: `File '/etc/apt/keyrings/microsoft.gpg' exists. Overwrite? (y/N)`
This PR reverts to the save method from the previous commit, which overwrites the …

{Packaging} Fix DEB install script

---

src/azure-cli/azure/cli/command_modules/acr/policy.py

az acr login
On AzureStackHub, ACR is using the API version `2019-05-01` in the latest available hybrid profile which is [2020-09-01-hybrid](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/profiles/_shared.py#L315). The `2019-05-01` API version does not have a `azureADAuthenticationAsArmPolicy` object in the registry, and so when that attribute is invoked during an `az acr login` command, this error is thrown:
```
'Policies' object has no attribute 'azure_ad_authentication_as_arm_policy'
File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
File …
```

{ACR} Fix az acr login command on AzureStackHub

---

src/azure-cli/azure/cli/command_modules/rdbms/config.json

Related command
Add support for Left Shift clusters in regions westus2 and eastus2. Needed for capacity.
Description
Add support for Left Shift clusters in regions westus2 and eastus2. Needed for capacity.
Testing Guide

{RDBMS} Add support for left-shift clusters in new regions

---

src/azure-cli/azure/cli/command_modules/acs/custom.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py

Update default value of option `--enable-managed-identity` to `None`. This removes the confusing default value hints in the official documentation. As the help message indicates, even if user doesn't specify this option, it is actually enabled by default.
---

[AKS] `az aks create`: Update default value of option `--enable-managed-identity` to `None`

---

src/azure-cli/azure/cli/command_modules/netappfiles/custom.py

The minimum supported coolness-period value in `az netappfiles volume create` and `az netappfiles volume update`  was changed from 7 to 2.
This change makes it less constraining and is correcting the definition to accurately match the service behavior. The root issue is due to incorrect swagger spec that is being corrected in a separate action. 
Since that takes time we would like to make this change in customization to get this fix out asap to Azure CLI.
---

[NetAppFiles] Coolnessperiod minimum fix

---

src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/azuremonitorprofile.py

… 
```az aks create -n kaveeshcli22 -g kaveeshcli --location westeurope --enable-azure-monitor-metrics --azure-monitor-workspace-resource-id "{full_id}" --grafana-resource-id "{full_id}"```
```az aks create -n kaveeshcli22 -g kaveeshcli --disable-azure-monitor-metrics ```
```az aks update -n kaveeshcli22 -g kaveeshcli --enable-azure-monitor-metrics --enable-windows-recording-rules```
block Azure Mnaaged Grafana for managed prometheus addon in air gapped cloud as its not available there yet.
**Scenario (managed prometheus support in air gapped cloud)**:
- Set context to one of the air gapped clouds
- Use the command with the grafana-resource-id parameter similar to `az aks create -n kaveeshcli22 -g kaveeshcli --location {ussec_location} …

[AKS] `az aks create/update`: Add Azure Managed Grafana support for managed prometheus addon in usnat

---

src/azure-cli/azure/cli/command_modules/acs/_params.py
src/azure-cli/azure/cli/command_modules/acs/custom.py
src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_azure_service_mesh_canary_upgrade.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_azure_service_mesh_enable_disable.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_azure_service_mesh_get_revisions.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_azure_service_mesh_get_upgrades.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_azure_service_mesh_with_ingress_gateway.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_azure_service_mesh_with_pluginca.yaml

`az aks mesh`
This change adds warnings to the `az aks mesh` commands for an out of support asm revision in use in the cluster.
`az aks mesh enable -- revision asm-1-18 -g rgName -n clusterName`
This command should print a warning about asm-1-18 being out of support.
---

[AKS] `az aks mesh`: Add warnings for out of support asm revision in use

---

NOTICE.txt

We use [jp](https://github.com/jmespath/jp) in Alpine docker image.
We need to add it into notice file

{Doc} Add jp to notice

---

src/azure-cli/azure/cli/command_modules/sqlvm/_validators.py
src/azure-cli/azure/cli/command_modules/sqlvm/tests/latest/test_sqlvm_commands.py

az sql vm validate-azure-ad-auth
az sql vm enable-azure-ad-auth
Entra authentication can only be enabled for SQL2022
CLI validates entra auth requests by getting SQL version from SqlImageOffer and checks if the version is SQL2022. But SqlImageOffer is set only once during registration and is not updated when SQL version is changed. As a result, any customer who had previous SQL version and upgraded to SQL2022 will still not be able to configure entra auth.
To avoid this, removing the validation SQL version and rely on the server-side (RP) validation that always happens.
{Sqlvm} az sql vm validate-azure-ad-auth: Change validation for sqlvm Entra authentication
--- …

{Sqlvm} `az sql vm validate-azure-ad-auth`: Change validation for sqlvm Entra authentication

---

src/azure-cli/azure/cli/command_modules/network/custom.py

Don't assume that "id" always exists and check for the value with a default
Command:
az network dns zone export --resource-group <resource_group> --name <dns zone>
The command crashes for my zone with KeyError: 'id' on line 2638, for 2.61.0. With the proposed patch the key is not assumed to exist and the check falls through to the other if/else branches.
az network dns zone export --resource-group <resource_group> --name <dns zone>
This is a bug fix, not likely to cause breaking changes
---

{Network} `az network dns zone export`: Fix KeyError

---

src/azure-cli-core/setup.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

`az login`
Fix https://github.com/Azure/azure-cli/issues/28997
Bump PyMSALRuntime to 0.16.2 to solve https://github.com/Azure/azure-cli/issues/28997. Bump MSAL to 1.28.1 to allow PyMSALRuntime 0.16.2: https://github.com/AzureAD/microsoft-authentication-library-for-python/commit/ddb94b213e31ccc5f1f9ba5f174ccf3b62aeec08
Open Windows Terminal as administrator, run
```
az login
```

{Core} Bump MSAL to 1.28.1 and PyMSALRuntime to 0.16.2

---

src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

Bump requests to fix [CVE-2024-35195](https://github.com/advisories/GHSA-9wx4-h78v-vm56)
Also bump urllib3 to latest version
[Core] Resolve CVE-2024-35195

{Packaging} Bump requests to 2.32.0

---

src/azure-cli/azure/cli/command_modules/appconfig/_params.py

**--import-mode** command under az appconfig kv import
This PR updates the help text for **--import-mode** command under az appconfig kv import
This change was discussed in this PR https://github.com/Azure/AppConfiguration/issues/919 to update the help text for import mode ignore-match
---

[App Config] `appconfig kv import`: Update the help message for ignore-match

---

src/azure-cli/azure/cli/command_modules/rdbms/validators.py

`az postgres flexible-server firewall-rule create`
Help defines that --rule-name is not required argument. If name is omitted, default name will be chosen for firewall name. 
Validator method was return error when arg was not passed. Corrected to only do validation check if rule name arg has value
Addressing bug
#28972 
Bug fix in ip_address_validator to check that only digits are passed in IPV4 format
Manually
Firewall name validator
PS C:\Users\nasc\azureCLI\azure-cli> az postgres flexible-server firewall-rule create --resource-group g --name n --start-ip-address 100.0.00.000
Configuring server firewall rule to accept connections from '100.0.00.000'...
{
"endIpAddress": "100.0.00.000",
"id": …

[RDBMS] `az postgres flexible-server firewall-rule create`: Correct firewall rule name and ip range validators

---

src/azure-cli/azure/cli/command_modules/rdbms/_params.py
src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py

az postgres flexible-server update
Allow being able to update public access flag for Azure PostgreSQL Flexible server through the Azure CLI
Fix #28838 
Manually
`az postgres flexible-server update`: Enable or disable public access flag be setting argument --public-access

[RDBMS] `az postgres flexible-server update`: Add argument to enable or disable public-access

---

src/azure-cli/azure/cli/command_modules/rdbms/_params.py
src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py

postgres flexible-server create
Add a new --create-default-database parameter which defaults to true, so that users who don't like this: behavior can change it, without breaking other existing scenarios.
Fix for #20958 
Manually

[RDBMS] `az postgres flexible-server create`: Add argument `--create-default-database` to support disabling default database creation

---

src/azure-cli/azure/cli/command_modules/mysql/custom.py
src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_common.py

`az postgres flexible-server upgrade --subscription <subscription> --resource-group <resourcegroup> --name <postgresql> --version <version>`
It doesn't make sense that we keep blocking customers to run MVU for Burstable from CLI, when we allow them to run it from REST API and portal UX.
---

[RDBMS] `az postgres flexible-server upgrade`: Unblock MVU for Burstable from CLI

---

src/azure-cli/azure/cli/command_modules/mysql/custom.py

az mysql flexible-server update
this is bug fix. get resource group from replica id for support replica rg different with primary server
---

[MYSQL] `az mysql flexible-server update`: Support replica resource group different with primary server

---

src/azure-cli/azure/cli/command_modules/resource/_help.py

`az bicep restore --help`
The help contents of the command mentioned above contains a (very minor) typo which occurs twice.
N/A
[Bicep restore] `az bicep restore`: Fix typos in documentation
---

[ARM] `az bicep restore`: Fix typos in help messages

---

src/azure-cli/azure/cli/command_modules/appservice/_validators.py

az webapp config access-restriction add
Customer reported issue #29041
az webapp config access-restriction add -g <rg> -n <app> --priority 200 --service-tag AzureCloud
Though it requires a specific set of permissions used by this customer. The condition will not impact existing scenarios but catch this specific condition.
---

[AppService] Fix #29041: `az webapp config access-restriction add`: Fix edge case validating service tags

---

src/azure-cli-core/azure/cli/core/auth/identity.py
src/azure-cli/azure/cli/command_modules/profile/_help.py

`az login`
Fix https://github.com/Azure/azure-cli/pull/28841#issuecomment-2106710296
Update the WAM prompt message after making WAM the default authentication method on Windows (https://github.com/Azure/azure-cli/pull/28841). This information is already in the **history notes** of https://github.com/Azure/azure-cli/pull/28841.
`az login`

{Core} Update WAM-related messages

---

src/azure-cli/HISTORY.rst

Add changelog for 2.38.2. This version is only released for CentOS 7 and RHEL 7.
Release branch https://github.com/Azure/azure-cli/tree/2.38
Related PR: https://github.com/Azure/azure-cli/pull/28821

{Doc} Add changelog for 2.38.2

---

cgmanifest.json

Component Detection can only detect dependencies in `setup.py`.
Add jp to mainifest so that we can generate NOTICE through the Component Governance UI
Ref:
https://docs.opensource.microsoft.com/tools/cg/component-detection/cgmanifest/
https://docs.opensource.microsoft.com/tools/cg/legal/notice/#generate-notice-through-the-component-governance-ui

{Misc.} Add cgmanifest.json

---

src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py

`az postgres flexible-server update --maintenance-window`
Bug found, not properly setting parameters to disable maintenance window
Manually
`az postgres flexible-server update`: Fix ability to disable maintenance window
---

[RDBMS] `az postgres flexible-server update`: Correct setting `--maintenance-window` to be disabled

---

src/azure-cli-core/azure/cli/core/aaz/_arg.py
src/azure-cli-core/azure/cli/core/tests/test_aaz_arg.py

Add completer support in aaz core.
Customer could use custom completer:
```Python
from azure.cli.core.decorators import Completer
@Completer
def _get_supported_languages(cmd, prefix, namespace):
return ["en-us", "es-es", "fr-fr", "de-de"]
class FooCreate(_CreateFoo):
@classmethod
def _build_arguments_schema(cls, *args, **kwargs):
if cls._args_schema is not None:
return cls._args_schema
cls._args_schema = super()._build_arguments_schema(*args, **kwargs)
_args_schema = cls._args_schema
_args_schema.bar._completer = _get_supported_languages
return cls._args_schema
```
[Component Name 2] `az command b`: Add some customer-facing …

[Core] `aaz`: Add argument completer support

---

src/azure-cli/azure/cli/command_modules/keyvault/_params.py

The description of the [CLI az keyvault create --enable-rbac-authorization parameter](https://learn.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest#az-keyvault-create-optional-parameters) currently reads:
> --enable-rbac-authorization
> Property that controls how data actions are authorized. When true, the key vault will use Role Based Access Control (RBAC) for authorization of data actions, and the access policies specified in vault properties will be ignored. When false, the key vault will use the access policies specified in vault properties, and any policy stored on Azure Resource Manager will be ignored. If null or not specified, the vault is created **with the default value of false**. Note that management actions are always authorized with RBAC.
> 
> Accepted values: …

{Key Vault} Update params file to correct default vaule

---

azure-pipelines.yml

Use it to prevent the docker rate limit error:
```
Unable to find image 'debian:bookworm' locally
bookworm: Pulling from library/debian
docker: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
```

{CI} Use MCR docker mirror

---

azure-pipelines.yml

We can't re-run failed task in ADO after enabling `continueOnError`.
Remove it so that we can retry DEB build.

{CI} Remove continueOnError

---

src/azure-cli/azure/cli/command_modules/keyvault/_validators.py

`az keyvault create --default-cvm-policy`
Current default cvm policy used for keyvault creation is
```
{
'version': '1.0.0',
'anyOf': [
{
'authority': attest_uri,
'allOf': [
{
'claim': 'x-ms-attestation-type',
'equals': 'sevsnpvm'
},
{
'claim': 'x-ms-compliance-status',
'equals': 'azure-compliant-cvm'
}
]
}
]
}
```
As @praenubilus reported:
> We have two type of cvm: sevsnp and tdx, if sevsnp is explicitly in the policy, the tdx(new hardware) cannot work
So this PR aims to remove explicit cvm type from the policy template
`az keyvault create --default-cvm-policy`
---

{Keyvault} `az keyvault create`: Remove explicit cvm type from default cvm policy template

---

src/azure-cli/azure/cli/command_modules/resource/custom.py

`az stack group create`
`az stack sub create`
`az stack mg create`
Adjusts the confirmation message when a stack update is about to be applied. Highlights:
- The stack scope is now in the message ("resource group"/"subscription"/"resource group") depending on the scope in the command. Previously it would always say "subscription", even if the stack was an MG or RG stack.
- Adds a "Are you sure you want to continue?" string before the "y/n" portion of the prompt string.
1. `az stack <scope> create ...` to create a stack.
2. Same as 1 again to get the confirmation message.
[ARM] `az stack group/sub/mg create`: Minor improvements to the confirmation message when updating an existing stack
--- …

[ARM] `az stack`: Improve confirmation message when an existing stack is updated

---

src/azure-cli-core/azure/cli/core/tests/test_application.py
src/azure-cli/azure/cli/command_modules/ams/tests/latest/test_ams_content_key_policy_scenarios.py
src/azure-cli/azure/cli/command_modules/ams/tests/latest/test_ams_live_event_scenarios.py
src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/test_appconfig_commands.py
src/azure-cli/azure/cli/command_modules/search/tests/latest/test_admin_key.py

Python 3.12 removes `assertNotEquals`, so we are removing the uses by replacing it by `assertNotEqual`.

{Misc.} Remove all occurrences of assertNotEquals

---

src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

2.32.0 is yanked.
Ref: https://pypi.org/project/requests/#history

{Packaging} Bump requests to 2.32.3

---

src/azure-cli/azure/cli/command_modules/synapse/manual/_params.py
src/azure-cli/azure/cli/command_modules/synapse/manual/operations/spark.py

az synapse spark job submit
Synapse allows users to add Python files to Spark jobs in addition to the main job file.  This may include custom .whl files, addition .py files, or anything else that is needed by the main python script.  This PR allows users to specify the additional python files through the az CLI interface.
See [azure-sdk-for-python SparkBatchJobOptions class](https://github.com/Azure/azure-sdk-for-python/blob/632792345c194c82118bbb7062fcc1df7510ef9a/sdk/synapse/azure-synapse/azure/synapse/spark/models/_models.py#L159)
az synapse spark job submit --name MyJobName --workspace MySynapseWorkspace --main-definition-file "abfs://mymainfile" --python-files "abfs://custom_library1.whl" "abfs://custom_library2.whl"
**History …

[Synapse] `az synapse spark job submit`: Add ability to pass custom Python files to the job

---

src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py

az aks create
the CLI should not own defaulting the network
profile properties. Defaulting should be owned
completely by AKS RP, so if a customer does
not set the `network_plugin` field then the CLI
should treat it as `None`.
Today, the default provided from the SDK
is `kubenet` but in the future, the AKS RP
will change this default value when omitted.
This means that other clients (ARM, bicep,
etc.) that do not set `network-plugin` will
get a different behavior than the CLI because
those clients won't set anything but the CLI
will continue to include the default from the
SDK.
az aks create - without providing a `--network-plugin` should succeed and AKS RP will set the default.
[AKS] `az aks create`: Not set the …

{AKS} `az aks create`: do not set `network_plugin` based on the Python SDK

---

azure-pipelines.yml

CodeQL tasks always timeout in these tasks. https://dev.azure.com/azclitools/public/_build/results?buildId=172894&view=logs&jobId=61bf4700-6d0f-55d3-0cc1-f8d3dd51c404
Usually, `Finalize CodeQL (auto-injected)` takes about 30min. I have no idea why they fail in these 6 tasks.
Luckily, they are all in `azure-pipelines.yml`. Even though we disable it here, **the CodeQL task still runs in `azure-pipelines-full-tests.yml`**. We still meet the security requirements.
PS: CodeQL also make some tasks in PowerShell fail: https://github.com/Azure/azure-powershell/pull/25560
Ref:
https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/codeql/configuring-codeql3000-ado-pipelines
https://portal.microsofticm.com/imp/v5/incidents/details/520675856/summary

{CI} Disable CodeQL task

---

src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/azuremonitorprofile.py
src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/helper.py

```az aks update -n kaveeshcli22 -g kaveeshcli --enable-azure-monitor-metrics --ksm-metric-labels-allow-list "namespaces=[k8s-label-1,k8s-label-n]" --ksm-metric-annotations-allow-list "pods=[k8s-annotation-1,k8s-annotation-n]"```
Updating the behavior of the az aks update command for managed prom to accept KSM parameter updates even when the addon is enabled on the cluster and stopping the error we throw saying that you have to disable the addon first before updating.
Have the Azure Managed Prometheus enabled on a cluster.
Now run : 
```az aks update -n kaveeshcli22 -g kaveeshcli --enable-azure-monitor-metrics --ksm-metric-labels-allow-list "namespaces=[k8s-label-1,k8s-label-n]" --ksm-metric-annotations-allow-list …
```

[AKS] `az aks create/update`: Support in place param updates for managed prom

---

src/azure-cli-core/setup.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

`az ssh`
Fix https://github.com/Azure/azure-cli/issues/29006
MSAL 1.26.0 in Azure CLI 2.58.0 bypasses token cache for SSH cert which is the expected behavior:
```
cli.azure.cli.core.auth.msal_authentication: ServicePrincipalCredential.get_token: scopes=('https://pas.windows.net/CheckMyAccess/Linux/.default',), kwargs={'data': {'token_type': 'ssh-cert', ...
urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com:443
```
But MSAL 1.27.0 (bumped by https://github.com/Azure/azure-cli/pull/28556) in Azure CLI 2.59.0 fetches SSH cert from token cache:
```
cli.azure.cli.core.auth.msal_authentication: ServicePrincipalCredential.get_token: scopes=('https://pas.windows.net/CheckMyAccess/Linux/.default',), kwargs={'data': …
```

{Core} Bump MSAL to 1.30.0

---

src/azure-cli/azure/cli/command_modules/network/_help.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/address_pool/address/__cmd_group.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/address_pool/address/_add.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/address_pool/address/_list.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/address_pool/address/_remove.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/address_pool/address/_show.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/address_pool/address/_update.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/probe/_create.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/probe/_update.py
src/azure-cli/azure/cli/command_modules/network/operations/load_balancer.py

resolve: https://github.com/Azure/azure-cli/issues/29254
resolve: https://github.com/Azure/azure-cli/issues/29103
---

{Network} `az network lb`: Remove useless preview information

---

src/azure-cli/azure/cli/command_modules/feedback/tests/latest/test_feedback.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

`Jinja2` and `MarkupSafe` are not used in CLI.
`pycparser` is a dependency of `cffi`.
We don't need to include them in requirements.txt
Resolve https://github.com/Azure/azure-cli/issues/29421

{Packaging} Remove Jinja2, MarkupSafe and pycparser from requirements.txt

---

src/azure-cli/azure/cli/command_modules/dls/tests/latest/recordings/test_dls_account_mgmt.yaml
src/azure-cli/azure/cli/command_modules/dls/tests/latest/recordings/test_dls_file_access_mgmt.yaml
src/azure-cli/azure/cli/command_modules/dls/tests/latest/recordings/test_dls_file_mgmt.yaml
src/azure-cli/azure/cli/command_modules/dls/tests/latest/test_dls_commands.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

az dls fs *
Update the azure-datalake-store version to 0.0.53. 
Main reason is to removes the dependency on adal and uses msal. There are other small changes that can be found in the change history at https://github.com/Azure/azure-data-lake-store-python/blob/master/HISTORY.rst 
azdev test dls --live
Tests the dls command tests with a live account. Please ask me for any needed access.
---
- [ NA] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).
- [ NA] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.m …

{dls} Update azure-datalake-store dependency

---

src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_virtual_network.py

`az postgres flexible-server create`
Fix unexpected error: File "D:\a_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_virtual_network.py", line 251, in _create_subnet_delegation
KeyError: 'addressPrefix'
Fix #27422 
WARNING: You have supplied a Subnet ID. Verifying its existence...
WARNING: Using existing Vnet "vnet-test-nasc-628" in resource group "nasc-runner"
WARNING: Using existing Subnet "subnet-test-nasc-628-454" in resource group "nasc-runner"
WARNING: Using existing Vnet "vnet-test-nasc-628" in resource group "nasc-runner"
WARNING: Using existing Subnet "subnet-test-nasc-628-454" in resource group "nasc-runner"
WARNING: Using the existing private dns zone …

[RDBMS] `az postgres flexible-server create`: Bug fix for using existing subnet while creating pg flex server

---

src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py

`az postgres flexible-server restore`
Regression introduced: #28975 
az postgres flexible-server restore --resource-group nasc-runner --source-server /subscriptions/x/resourceGroups/nasc-runner/providers/Microsoft.DBforPostgreSQL/flexibleServers/nasc-pg16-722 -n nasc-test-restore510
{
...
"backup": {
"backupRetentionDays": 7,
"earliestRestoreDate": "2024-07-24T21:13:14.296422+00:00",
"geoRedundantBackup": "Disabled"
},
...
"id": "/subscriptions/x/resourceGroups/nasc-runner/providers/Microsoft.DBforPostgreSQL/flexibleServers/nasc-test-restore510",
"name": "nasc-test-restore510",
...
}
[RDBMS] `az postgres flexible-server restore`: Bug fix when using resource id as value for source-server argument

[RDBMS] `az postgres flexible-server restore`: Bug fix when using resource id as value for source-server argument

---

src/azure-cli-core/azure/cli/core/tests/test_command_registration.py

Python 3.12 removed `assertDictContainsSubset`, so we are removing all usages by replacing it with subset assertion.
---

{Misc.} Remove all occurrences of assertDictContainsSubset

---

src/azure-cli/azure/cli/command_modules/rdbms/_params.py
src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py

`postgres flexible-server create`
Default version is 13 which is very old. Want users to move to 16 when provisioning server.
Removed warning label that this change was to come for August 2024 release.
This was agreed upon by CLI team and PostgreSQL Flex PM
Manually
PS C:\Users\nasc\azureCLI\azure-cli> az postgres flexible-server create -n nasc-pg16-722
Checking the existence of the resource group ...
Your server 'nasc-pg16-722' is using sku 'Standard_D2s_v3' (Paid Tier). Please refer to https://aka.ms/postgres-pricing for pricing details
Creating PostgreSQL database 'flexibleserverdb'...
{
...
"skuname": "Standard_D2s_v3",
**"version": "16"**
}
BREAKING CHANGE: `az postgres flexible-server create`: Default version …

[RDBMS] BREAKING CHANGE: Update default value of PG version to be 16 for `postgres flexible-server create`

---

alpine.dockerfile

We always use latest `setuptools` in packages, see https://github.com/Azure/azure-cli/pull/27196.
This PR updates the `setuptools` and `pip` in Alpine docker image.
For Python<3.12, the docker images uses pinned `setuptools`. In 3.12, it uses the latest version by default.
> ENV PYTHON_SETUPTOOLS_VERSION 65.5.1    --https://github.com/docker-library/python/blob/ec14acd6a0830012b4330429bc173247a375857e/3.11/alpine3.20/Dockerfile#L136
For now, the docker-library team does not want to bump the `setuptools` version because of the compatibility concern: https://github.com/docker-library/python/issues/942
[Core] Resolve CVE-2024-6345

{Packaging} Use latest setuptools in Alpine docker image

---

src/azure-cli/azure/cli/command_modules/role/_help.py
src/azure-cli/azure/cli/command_modules/role/_params.py
src/azure-cli/azure/cli/command_modules/role/custom.py

`az role assignment list`
According to https://azure.microsoft.com/en-us/updates/azure-classic-administrator-roles-are-retiring-on-31-august-2024/, Azure Classic Administrator roles will be retired on 2024-08-31.
Azure CLI should announce this in advance:
> Azure classic subscription administrators will be retired on August 31, 2024. After August 31, 2024, all classic administrators risk losing access to the subscription. Delete classic administrators who no longer need access or assign an Azure RBAC role for fine-grained access control. Learn more: https://go.microsoft.com/fwlink/?linkid=2238474
```
az role assignment list -h
az role assignment list --include-classic-administrators
```

[Role] `az role assignment list`: Add warning for classic administrators retirement

---

src/azure-cli-core/setup.py

Relex version constraint in `setup.py` to prevent version conflict when installing from PyPI.
Resolve https://github.com/Azure/azure-cli/issues/29258, resolve https://github.com/Azure/azure-cli/issues/29471

{Packaging} Relex version constraint of `psutil`

---

src/azure-cli-core/azure/cli/core/extension/__init__.py
src/azure-cli/azure/cli/command_modules/acs/_loadbalancer.py
src/azure-cli/azure/cli/command_modules/acs/custom.py
src/azure-cli/setup.py

`az --help`
Remove `distutils` to support Python 3.12
This is related to #27673.
`from distutils.sysconfig import get_python_lib` is slow. This PR also saves about 0.2s for each CLI command on Windows.
On Python 3.12, do `az --help`. If it works, this is fixed.
---

{Core} Remove deprecated usages of distutils to support Python 3.12

---

src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

1.15.1 does not provide wheel for Python 3.12. Bump it. Error log: https://github.com/Azure/azure-cli/issues/29467
Not sure if 1.14.6 is compatible with 3.12. It is stated that cffi 1.16 add 3.12 support: https://cffi.readthedocs.io/en/latest/whatsnew.html
https://github.com/Azure/azure-cli/blob/5f52c83e218f3ddc4d933bd99a88dab9e1864d81/scripts/release/rpm/azure-cli.spec#L55

{Packaging} Bump cffi to 1.16.0

---

src/azure-cli/requirements.py3.windows.txt

PyWin32 305 can't be installed on Python 3.12:
```
> pip install pywin32==305
ERROR: Could not find a version that satisfies the requirement pywin32==305 (from versions: 306)
ERROR: No matching distribution found for pywin32==305
```
Bump PyWin32 to 306 to accomplish https://github.com/Azure/azure-cli/issues/27673.

{Packaging} Bump PyWin32 to 306

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/auth/identity.py
src/azure-cli-core/azure/cli/core/auth/tests/test_identity.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py

`az logout`
Based on https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/666 from MSAL 1.27.0 (adopted by https://github.com/Azure/azure-cli/pull/28556).
```sh
az config set core.encrypt_token_cache=false
az login --service-principal --username xxx --password xxx --tenant xxx
az logout
az login --service-principal --username xxx --password xxx --tenant xxx
az logout --username xxx
```

[Core] `az logout`: Remove service principal access tokens from token cache

---

src/azure-cli/azure/cli/command_modules/acs/_help.py
src/azure-cli/azure/cli/command_modules/acs/_params.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_install_azure_npm.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_install_calico_npm.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_uninstall_azure_npm.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_uninstall_calico_npm.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py

az aks create/update
We are adding --network-policy=none option. "none" is currently the default value when network policy is not specified. This change is needed to support Uninstall Network Policy Engine feature (Azure Network Policy Manager or Calico)
---

[AKS] `az aks create/update`: Add `--network-policy none` option to command

---

src/azure-cli/azure/cli/command_modules/acr/_docker_utils.py
src/azure-cli/azure/cli/command_modules/acr/_params.py
src/azure-cli/azure/cli/command_modules/acr/custom.py
src/azure-cli/azure/cli/command_modules/acr/import.py

`az acr login` and `az acr import`
`az acr login`
added optional resource group argument to skip subscription level resource scan which fans out to all region and can cause failure if any of arm region have outage.
`az acr import`
added a check to avoid subscription scan if source registry is not an ACR registry. no observable changes for customer.
**Testing Guide** 
az acr login -n registry name -g resoucegroup
az acr login -n registryname
az acr import -n myregistry --source sourceregistry.azurecr.io/sourcerepository:sourcetag
az acr import -n myregistry --source docker.io/library/hello-world:latest
[ACR] `az acr login`: Support optional resource group argument to skip subscription resource scan
--- …

{ACR} Change: az acr login support for resource group and skip resource validation for non acr source registry in az acr import

---

src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_up_commands.py
src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_afd_secret_scenarios.py
src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_afd_security_policy_scenarios.py
src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_custom_domain_scenarios.py
src/azure-cli/azure/cli/command_modules/iot/tests/latest/test_iot_central_commands.py
src/azure-cli/azure/cli/command_modules/security/tests/latest/test_security_securityconnectors_devops.py
src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_file_share_scenarios.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_queue_scenarios.py

`assertRaisesRegexp` is removed in 3.12. It's replaced by `assertRaisesRegex`
Ref:
- https://docs.python.org/3/whatsnew/3.12.html#id3

{Misc.} Remove deprecated `assertRaisesRegexp`

---

src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_commands.py
src/azure-cli/azure/cli/command_modules/ams/tests/latest/test_ams_live_event_scenarios.py
src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/test_appconfig_commands.py
src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/test_vm_commands.py

`assertEquals` is removed in 3.12. It's replaced by `assertEqual`
Ref:
https://docs.python.org/3/whatsnew/3.12.html#id3

{Misc.} Remove deprecated `assertEquals`

---

src/azure-cli/azure/cli/command_modules/acs/base_decorator.py

{AKS} Fix enum check in test
---

{AKS} Fix enum check in test

---

src/azure-cli/azure/cli/command_modules/monitor/aaz/latest/monitor/action_group/test_notifications/_create.py
src/azure-cli/azure/cli/command_modules/monitor/aaz/latest/monitor/activity_log/alert/_create.py
src/azure-cli/azure/cli/command_modules/monitor/aaz/latest/monitor/activity_log/alert/_update.py
src/azure-cli/azure/cli/command_modules/monitor/aaz/latest/monitor/autoscale/_create.py
src/azure-cli/azure/cli/command_modules/monitor/aaz/latest/monitor/autoscale/_update.py

Fix https://github.com/Azure/azure-cli/issues/28829
---

{monitor} `az monitor`: Fix invalid escape in examples

---

azure-pipelines.yml
src/azure-cli/azure/cli/__main__.py

Add global warning message to drive the transition to Azure Linux based image.

{Packaging} Add warning message for Alpine-based image

---

src/azure-cli/azure/cli/command_modules/resource/_packing_engine.py

`az ts create`
`az ts create`: Fix incorrect handling of whitespace in string values
Reimplementation of #29437
```sh
az ts create \
--resource-group myrg \
--name myTemplateSpec \
--version 1.0 \
--template-file ./main.bicep
```
[ARM] `az ts create`: Fix incorrect handling of whitespace in string values
---

[ARM] `az ts create`: Fix incorrect handling of whitespace in string values

---

src/azure-cli/azure/cli/command_modules/acs/custom.py

`az aks nodepool upgrade`
When the user specifies a k8s version that is different from the current version of the nodepool, there is no need to prompt the user to confirm that this will be a no-op.
---

{AKS} `az aks nodepool upgrade`: Fix the wrong prompt when specifying the `--kubernetes-version`

---

src/azure-cli/azure/cli/command_modules/vm/_vm_utils.py
src/azure-cli/azure/cli/command_modules/vm/custom.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_enable_trusted_launch_on_v1.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_enable_trusted_launch_on_v2.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

`az vm update`
Gen1 VM to Trusted launch upgrade support
close https://github.com/Azure/azure-cli/issues/29007
---

[Compute] `az vm update`: Add support of Gen1 VM to trusted launch upgrade

---

src/azure-cli/azure/cli/command_modules/acs/_help.py
src/azure-cli/azure/cli/command_modules/acs/_params.py
src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py
src/azure-cli/azure/cli/command_modules/acs/custom.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_update_fips_flow.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_agentpool_decorator.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py

az aks nodepool update --enable-fips-image --disable-fips-image
This PR allows the CLI functionality for the GA AKS feature allowing fips mode to be enabled/disabled after nodepool creation using the cli "az aks nodepool update" with associated flags above.
#! Make sure to use region where AKS RP functionality has been released
az aks nodepool add -g chrislopezrg --cluster-name chrislopezaks -n fipstest2
az aks nodepool update -g chrislopezrg --cluster-name chrislopezaks -n fipstest --enable-fips-image
az aks nodepool show -g chrislopezrg --cluster-name chrislopezaks -n fipstest
az aks nodepool add -g chrislopezrg --cluster-name chrislopezaks -n fipstest3 --enable-fips-image
az aks nodepool add -g chrislopezrg --cluster-name …

[AKS] `az aks nodepool update`: Add `--enable/disable-fips-image` flags for GA mutable fips

---

src/azure-cli/azure/cli/command_modules/appservice/_help.py
src/azure-cli/azure/cli/command_modules/appservice/_params.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_staticapp_commands_thru_mock.py
src/azure-cli/azure/cli/command_modules/appservice/utils.py

`az staticwebapp create`
`az staticwebapp update`
For Static Web Apps, we have recently previewed the Dedicated SKU. Currently, the related staticwebapp commands only support Free and Standard SKU. This PR adds support for the Dedicated SKU, as well as adds it to supported features in help texts.
Added and ran a new unit test `test_create_staticapp_with_dedicated_sku`.
Also ran the following command (with actual values in place of sample values) with this code and verified a Dedicated SKU Static Web App was successfully created:
`az staticwebapp create -n name1 -g rg1 -s https://github.com/Contoso/My-First-Static-App -b dev -l EastUs2 --app-location app --sku Dedicated`
--- …

[App Service] `az staticwebapp create` and `az staticwebapp update`: Add `Dedicated` as supported SKU

---

src/azure-cli-core/azure/cli/core/tests/test_aaz_operation.py

https://github.com/Azure/azure-cli/issues/28829
---

{Core} `aaz`: Fix invalid escape in tests

---

src/azure-cli/azure/cli/command_modules/storage/_help.py

az storage fs directory generate-sas
If a slash is specified at the end of the name parameter, the error message is "<Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is correctly formed including the signature.
We can reproduce the simple way.
a) az storage fs directory generate-sas --file-system test00 --account-name mystorageadlsgen2 --name **directory00** --expiry 2025-07-11T09:46:44Z --permissions cw
b) az storage fs directory generate-sas --file-system test00 --account-name mystorageadlsgen2 --name **directory00/** --expiry 2025-07-11T09:46:44Z --permissions cw
a) is success upload using the generated SAS like using azcopy. On the other hands, Using …

{Storage} `az storage fs directory generate-sas`: Remove ending slash in directory name

---

src/azure-cli-telemetry/azure/cli/telemetry/__init__.py
src/azure-cli-telemetry/azure/cli/telemetry/components/records_collection.py
src/azure-cli-telemetry/azure/cli/telemetry/tests/test_records_collection.py
src/azure-cli-telemetry/azure/cli/telemetry/util.py

This PR is for fixing telemetry lost due to concurrency issue.
At the stage when we still had telemetry local cache, here's the process of uploading telemetry:
1. save cli records in telemetry cache file
2. check telemetry note file
2.1 if it's not enough time since last telemetry uploading time, exit
2.2 if it has been long enough since last telemetry uploading time, start a subprocess for uploading
3. within the uploading subprocess
3.1 check telemetry note file again to ensure it has been enough time since last telemetry sent time
3.2 get `last_sent_time` from telemetry note file
3.3 read all cli records from telemetry cache file where `record_time > last_sent_time`
3.4 remove cache file as it has been loaded in 3.3
3.5 uploading all records from 3.3
3.6 update …

{Telemetry} Fix telemetry lost due to concurrency issue

---

src/azure-cli/azure/cli/command_modules/mysql/_client_factory.py
src/azure-cli/azure/cli/command_modules/mysql/_help.py
src/azure-cli/azure/cli/command_modules/mysql/_params.py
src/azure-cli/azure/cli/command_modules/mysql/_validators.py
src/azure-cli/azure/cli/command_modules/mysql/commands.py
src/azure-cli/azure/cli/command_modules/mysql/custom.py
src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_maintenance_mgmt.yaml
src/azure-cli/azure/cli/command_modules/mysql/tests/latest/test_mysql_scenario.py

az mysql flexible-server maintenance show
az mysql flexible-server maintenance list
az mysql flexible-server maintenance reschedule
Add az command group 'az mysql flexible-server maintenance' which contains above three az commands. These commands will support customers to manage their maintenance on Azure MySQL flexible servers.
`az mysql flexible-server maintenance show --resource-group testgroup --server-name testserver --maintenance-name _T9Q-TS8`
**explanation:**  Get a maintenance of mysql flexible server 'testserver' under resource group 'testgroup', with maintenance name '_T9Q-TS8'
`az mysql flexible-server maintenance list --resource-group testgroup --server-name testserver`
**explanation:** List all of the maintenances of …

[MySQL] `az mysql flexible-server maintenance`: New command group for managing maintenance of MySQL flexible server

---

src/azure-cli/azure/cli/command_modules/storage/__init__.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_upgrade_to_storagev2.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py

[Storage] `az storage account create/update`: Support account cold-tier
---

[Storage] `az storage account create/update`: Support account cold-tier

---

src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/amg/link.py

```az aks create -n kaveeshcli22 -g kaveeshcli --location westeurope --enable-azure-monitor-metrics --azure-monitor-workspace-resource-id "{full_id}" --grafana-resource-id "{full_id}"```
```az aks create -n kaveeshcli22 -g kaveeshcli --disable-azure-monitor-metrics ```
Azure Managed Grafana now has support for UserAssigned Managed Identity and we're adding support for it in the managed prometheus addon.
- Set context to one of the air gapped clouds
- Use the command with the grafana-resource-id parameter similar to `az aks create -n kaveeshcli22 -g kaveeshcli --location {cluster_location} --enable-azure-monitor-metrics --azure-monitor-workspace-resource-id "{full_id}" --grafana-resource-id "{full_id}"` and it should result in a a …

[AKS] `az aks create/update`: Support UserAssigned Managed Identity for grafana linking in managed prometheus

---

src/azure-cli/azure/cli/command_modules/containerapp/custom.py
src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_logstream.yaml
src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_scale_revision_copy.yaml

`az containerapp logs show`
Fix issue: https://github.com/Azure/azure-cli/issues/29711
For `json` format in log, characters in json need to be escaped.
For example `"` in logs,  it should be `\"`. Currently it is not escaped correctly. 
For example, this is not a valid json:
`{"TimeStamp": "2024-08-22T08:37:19.1646828Z", "Log": "INFO:root:UTC time: 2024-08-22 08:37:18.326665+00:00, IST time 2024-08-22 14:07:18.326665+05:30, count: 4817, DEBUG   [16:46:37] -  urllib3.connectionpool (connectionpool _make_request 546) - https://kv-baz.azure.net:443 "GET /secrets/foobar/?api-version=7.5 HTTP/11" 401 97"}`
After fix:
`{"TimeStamp": "2024-08-22T08:37:19.1646828Z", "Log": "INFO:root:UTC time: 2024-08-22 08:37:18.326665+00:00, IST time 2024-08-22 …

[Containerapp] Fix #29711: `az containerapp logs show`: Fix JSON escaping by default or with `--format json`

---

src/azure-cli/azure/cli/command_modules/vm/aaz/latest/capacity/reservation/group/_list.py
src/azure-cli/azure/cli/command_modules/vm/commands.py

`az capacity reservation`
`az capacity reservation group`
Service need remove preview tag
close https://github.com/Azure/azure-cli/issues/29757
aaz https://github.com/Azure/aaz/pull/550
---

[Compute] `az capacity reservation`: GA command group

---

src/azure-cli/azure/cli/command_modules/redis/commands.py
src/azure-cli/azure/cli/command_modules/redis/custom.py

Related command
az redis update
Description
Resolves issue discussed here https://github.com/Azure/azure-cli/pull/24979#discussion_r1450185925
---

[Redis] `az redis update`: Support `--no-wait` and default to `True`

---

src/azure-cli/azure/cli/command_modules/synapse/manual/_params.py

az synapse workspace create&update
Remove parameter help message "https://github.mydomain.com" to fix issue.
https://github.com/Azure/azure-cli/issues/29576
---

{Synapse} Fix #29576: az synapse workspace parameter help message cause doc auto autogenerated build error. 

---

src/azure-cli/azure/cli/command_modules/appservice/_params.py
src/azure-cli/azure/cli/command_modules/appservice/_validators.py
src/azure-cli/azure/cli/command_modules/appservice/access_restrictions.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_access_restriction_commands.py

`az webapp config access-restriction`
We have seen multiple issues raised where caller is challenged with getting the list of service tags. We typically find the cause and ignore it in code, but we have now added a new flag `--skip-service-tags-validation` which will allow the caller to skip the validation of service tags and not have to wait for a new release to fix the issue. This will be helpful for customers who are blocked by this issue and need a quick workaround, and this is only client side validation. Backend will ultimately validate the service tags.
We will also be allowing MSFT internals to use this flag to bypass the validation as well for internal service tags.
az webapp config access-restriction add --priority 200 -g …

[App Service] `az webapp config access-restriction add/remove`: Allow skipping service tag validation

---

src/azure-cli/azure/cli/command_modules/acs/azurecontainerstorage/_helpers.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_validators.py

[AKS] `az aks create/update`: Update the VM SKU regex validation to include larger set of VMs for Azure Container Storage

---

doc/how_to_introduce_breaking_changes.md
src/azure-cli-core/azure/cli/core/breaking_change.py

* Command in azdev to collect upcoming breaking change information will be renamed to `azdev genereate-breaking-change-report`
* Fix a bug when calling `version()` of `ExactVersion`
* Unify the deprecate warning message from `_breaking_change.py`
* Use `target_version` instead of `expiration` when collecting deprecation breaking change message.
---

{Core} Fix display inconsistent and `ExactVersion` definition bug in Upcoming Breaking Change Pre-announcement

---

src/azure-cli-core/azure/cli/core/auth/identity.py
src/azure-cli-core/azure/cli/core/auth/msal_credentials.py
src/azure-cli-core/azure/cli/core/auth/tests/test_identity.py

`az login`
**Change 1: Refactor `UserCredential` and `ServicePrincipalCredential`**
In the current code, 
- `UserCredential` inherits from `msal.PublicClientApplication`
- `ServicePrincipalCredential` inherits from `msal.ConfidentialClientApplication`
This exposes the internal MSAL application instances to the caller SDK which only requires the `get_token()` callback interface. 
This PR stops `UserCredential` and `ServicePrincipalCredential` from inheriting from MSAL, but makes them keep an internal MSAL application instance, in order to greatly reduce MSAL applications' exposure.
**Change 2: Refactor `ServicePrincipalAuth`**
All attributes are set at `__init__()` to avoid frequently calling `getattr()` to check the existence of attributes. The logic …

{Core} Refactor code for MSAL authentication

---

azure-linux.dockerfile
azure-pipelines.yml
scripts/release/docker/pipeline.sh

Azure Linux 3.0 was GA on 07/31/2024
Ref: https://mcr.microsoft.com/en-us/product/azurelinux/base/core/about

[Packaging] Release Docker image based on Azure Linux 3.0

---

src/azure-cli/azure/cli/command_modules/serviceconnector/_addon_factory.py
src/azure-cli/azure/cli/command_modules/serviceconnector/_params.py
src/azure-cli/azure/cli/command_modules/serviceconnector/_transformers.py
src/azure-cli/azure/cli/command_modules/serviceconnector/_utils.py
src/azure-cli/azure/cli/command_modules/serviceconnector/_validators.py
src/azure-cli/azure/cli/command_modules/serviceconnector/action.py

{Service Connector} Add input validation for `run_cli_cmd` 

---

azure-linux.dockerfile

Add `jq` into image because it's widely used and small.
Resolve #29830

[Packaging] Include `jq` in Azure Linux docker image

---

src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py

`az postgres flexible-server migration create`
Document AWS Aurora as now a supported migration source for PostgreSQL Flexible Server. This also fixes a typo, updating `on-premises` to the correct `OnPremises`.
From AWS create either an AWS Aurora database. Then create a "migrationConfig.json" file with the following:
```json
{
"properties": {
"sourceDBServerResourceId": "<<hostname or IP address>>:<<port>>@<<username>>",
"secretParameters": {
"adminCredentials": {
"sourceServerPassword": "password",
"targetServerPassword": "password"
},
"sourceServerUserName": "postgres",
"targetServerUserName": "fspguser"
},
"dBsToMigrate": [
"<<some database name>>, <<some other database name>>"
],
"overwriteDbsInTarget": "true",
"sourceType": …
```

[RDBMS] `az postgres flexible-server migration create` Add AWS_AURORA as a migration source type for PostgreSql

---

src/azure-cli/azure/cli/command_modules/sql/custom.py

`az sql elastic-pool create --db-dtu-min 20`
`az sql elastic-pool create --db-max-capacity 0.5`
Requests to create elastic pools of SKUs that are not serverless should not contain the `min_capacity` property. Hence, this changeset sets it to `None` in those cases.
Create an elastic pool either with the DTU or vCore model and pass the corresponding parameter to set the per-database min_capacity. With this fix, see how that parameter now only applies to the database, as expected.
```
az sql elastic-pool create -g test-rg -s test-svr --name stdpool3 --edition Standard --dtu 1200 --db-dtu-min 20 --db-dtu-max 100 --storage 1200GB
```
```
az sql elastic-pool create -g test-rg -s test-svr --name stdpool4 --edition GeneralPurpose --family Gen5 …
```

[SQL] `az sql elastic-pool create`: Set `min_capacity` to `None` for non-serverless SKUs

---

src/azure-cli/azure/cli/command_modules/dla/commands.py

`az dla`
Azure Data Lake analytics has been retired as of Feb 29, 2024: [migrate-to-azure-synapse-analytics](https://azure.microsoft.com/en-us/updates/migrate-to-azure-synapse-analytics/)
This PR is for deprecate it from CLI
---

[dla] `az dla`: Deprecate azure datalake analytics from CLI

---

src/azure-cli/azure/cli/__main__.py

This code was introduced in https://github.com/Azure/azure-cli/pull/5644 to fix https://github.com/Azure/azure-cli/issues/5184.
Since it's fixed in upstream https://github.com/python/cpython/pull/5254 a long time ago, we don't need it anymore.

{Core} Remove uuid workaround code

---

azure-pipelines.yml

Debian 10 reached its EOL LTS in June 2024.
Ref: https://wiki.debian.org/DebianReleases

[Packaging] Drop Debian 10 support

---

src/azure-cli/azure/cli/command_modules/role/_params.py

```
az role assignment create --help
```
fix typo, currently:
```
--name -n                     : A GUID for the role assignment. It must be unique and different
for each role assignment. If omitted, a new GUID is generetd.
```
---

{Role} Fix typo for `az role assignment create --help`

---

src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/cluster/server/_show.py
src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/configuration/_show.py
src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/configuration/coordinator/_show.py
src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/configuration/coordinator/_update.py
src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/configuration/coordinator/_wait.py
src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/configuration/node/_show.py
src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/configuration/node/_update.py
src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/configuration/node/_wait.py
src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/configuration/server/_list.py
src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/firewall_rule/_create.py
src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/firewall_rule/_delete.py
src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/firewall_rule/_show.py
src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/firewall_rule/_update.py
src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/firewall_rule/_wait.py
src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/role/_create.py
src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/role/_delete.py
src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/role/_show.py
src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/role/_update.py
src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/role/_wait.py

As part of https://github.com/Azure/azure-cli/issues/28829 fix
---

{Cosmos DB} `az cosmosdb postgres` Fix invalid escapes

---

src/azure-cli/azure/cli/command_modules/lab/tests/latest/recordings/test_lab_vm.yaml
src/azure-cli/azure/cli/command_modules/lab/validators.py

`az lab`
This PR depends on https://github.com/Azure/azure-cli/pull/28105.
`lab` command module directly use `azure-graphrbac` SDK to call AD Graph. 
This PR migrates `lab` command module to call Microsoft Graph to address https://github.com/Azure/azure-cli/issues/22174.

{Lab} Migrate `lab` command module to Microsoft Graph

---

src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py
src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py

`az postgres flexible-server replica create`
FSPG replica create help page shall have example about how to create Replica in different resource group.
Correct examples to use all lowercase for server names.
Correct spelling mistakes.
Use id_parts to get resource group.
Proof example works:
az postgres flexible-server replica create **--replica-name nas-503-rep -g rmendizabal** --source-server /subscriptions/s/resourceGroups/nasc-runner/providers/Microsoft.DBforPostgreSQL/flexibleServers/nasc-pg812 --location testlocation
{
...
"id": "/subscriptions/s/**resourceGroups/rmendizabal**/providers/Microsoft.DBforPostgreSQL/flexibleServers/**nas-503-rep**",
...
"sourceServerResourceId": …

{RDBMS} `az postgres flexible-server replica create`: Update replica create help text to show example of cross resource group creation

---

src/azure-cli/azure/cli/command_modules/network/_validators.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/watcher/flow_log/_create.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/watcher/flow_log/_update.py
src/azure-cli/azure/cli/command_modules/network/operations/watcher.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_nw_flow_log.py

This Pr involves making changes in 'network watcher flow-log create' and 'network watcher flow-log update` commands to now include an extra optional field --user-.assigned-identity. With new addition user will be able to create FLowlogs with MI and also delete MI associated with FL..
- az network watcher flow-log create --enabled true --location centraluseuap --name mejaflowlogaug28 --vnet /subscriptions/af15e575-f948-49ac-bce0-252d028e9379/resourceGroups/mejacentralrg/providers/Microsoft.Network/virtualNetworks/vnetaug26 --resource-group NetworkWatcherRG  --storage-account /subscriptions/af15e575-f948-49ac-bce0-252d028e9379/resourceGroups/mejacentralrg/providers/Microsoft.Storage/storageAccounts/mejateststoragecentral --subscription …

{cli} changes for create and update FLowLog with User ManagedIdentity 

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_config_set.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py

`az functionapp config set`
Resolves #29733
There was also a similar IcM (533059748) that was created for it. 
The issue is that we are just passing parameters but not mapping them correctly when calling the internal `update_site_configs` function. 
1. Create function app (`az functionapp create`)
2. Update site configs (`az functionapp config set -g <resourceGroup> -n <functionAppName> --always-on true --http20-enabled true --min-tls-version "1.2" --ftps-state "Disabled" --remote-debugging-enabled false --use-32bit-worker-process`)
[AppService] `az functionapp config set`: Map parameters explicitly for the internal update_site_configs function call
---
This checklist is used to make sure that common guidelines for a …

[AppService] Fix #29733: `az functionapp config set`: Map parameters explicitly for the internal update_site_configs function call

---

src/azure-cli/azure/cli/command_modules/monitor/operations/action_groups.py

When you concatenate a regular string with a multi-line string using the + operator, the multi-line string loses its formatting and is treated as a single line.
To preserve the formatting of the multi-line string, you should use a different approach.
I've updated these to include the entire text within triple quotes without concatenation.
az monitor action-group create
az monitor action-group update
az monitor action-group notification create
There were multi line strings for the additional data for these command parameters that were broken and just showed large blocks of text. 
just the help notes for the create and update commands. 
[Monitor] `az monitor action-group create`: Adjust formatting of `--actions` help …

[Monitor] `az monitor action-group create`: Adjust formatting of `--actions` help message 

---

src/azure-cli-core/azure/cli/core/aaz/_arg.py
src/azure-cli-core/azure/cli/core/tests/test_aaz_arg.py

---
closed https://github.com/Azure/azure-cli/issues/29619
closed https://github.com/Azure/azure-cli/issues/29618
closed https://github.com/Azure/azure-cli/issues/29615
closed https://github.com/Azure/azure-cli/issues/29614
closed https://github.com/Azure/azure-cli/issues/29613
closed https://github.com/Azure/azure-cli/issues/29612
closed https://github.com/Azure/azure-cli/issues/29611
closed https://github.com/Azure/azure-cli/issues/29610
closed …

{Core} Fix help message format for `AAZGenericUpdate`

---

src/azure-cli/azure/cli/command_modules/acr/_help.py

```
az acr credential-set create --help
az acr credential-set update --help
```
The current help message for `az acr credential-set create --help` shows the following example:
```
Examples
Create a credential set.
az acr credential-set create -r myregistry -n MyRule -l docker.io -u
https://MyKeyvault.vault.azure.net/secrets/usernamesecret -p
https://MyKeyvault.vault.azure.net/secrets/passwordsecret
```
There are two problems with above example:
1. The `-n MyRule` flag is misleading, is makes new user think they have to specify the cache rule name here, however the value after `-n` should be the name of the _credential set_ the user is creating.
2. The _username secret_ value has been cut to the next line. It is better to have it directly follow the `-u` …

[ACR] `az acr credential-set`: Improve help message

---

src/azure-cli/azure/cli/command_modules/cdn/_params.py
src/azure-cli/azure/cli/command_modules/cdn/custom/custom_afdx.py
src/azure-cli/azure/cli/command_modules/cdn/custom/custom_cdn.py

Fix https://github.com/Azure/azure-cli/issues/29970

{afd}Fix issue 29970: `az afd rule`, `az cdn rule` fix time format examples

---

.azure-pipelines/templates/variables.yml
azure-pipelines.yml

Test homebrew task fails because macos12 is deprecated.
```
Error: You are using macOS 12.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
```
Homebrew can't be installed on macOS 12: https://github.com/Homebrew/brew/pull/18323
Ref:
- https://dev.azure.com/azclitools/public/_build/results?buildId=192519&view=logs&j=cc48ae93-a624-59ff-8a3e-2ebdb4b89e58&t=acd97aa3-1ffd-5990-e2c3-4ea47f198c07
- https://github.com/orgs/Homebrew/discussions/5603

{CI} Use macOS-14 agent

---

src/azure-cli/azure/cli/command_modules/resource/_params.py

az bicep publish
Removed the is_preview=True flag from the --with-source argument
N/A
---

[ARM] `az bicep publish`: Remove preview flag from `--with-source` parameter

---

src/azure-cli/azure/cli/command_modules/storage/_validators.py
src/azure-cli/azure/cli/command_modules/storage/operations/blob.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_copy_rehydrate_priority.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_blob_copy_scenarios.py
src/azure-cli/azure/cli/command_modules/storage/tests/storage_test_util.py
src/azure-cli/azure/cli/command_modules/storage/util.py

Fix https://stackoverflow.microsoft.com/questions/416326
[Storage] `az storage blob copy start/start-batch`: Fix `--auth-mode login`
---

[Storage] `az storage blob copy start/start-batch`: Fix `--auth-mode login`

---

src/azure-cli/azure/cli/command_modules/vm/_params.py
src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
src/azure-cli/azure/cli/command_modules/vm/custom.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_sku_profile.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_sku_profile_update.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

This change adds skuprofile_vmsizes and skuprofile_allocation_strategy for vmss create and update
vmss create -n vmssName -g rgName --image ubuntu2204 --vm-sku Mix --skuprofile-vmsizes Standard_DS1_v2 Standard_D2s_v4 --skuprofile-allocation-strategy CapacityOptimized
[Compute] `az vmss create/update`: Add new parameter `--skuprofile-vmsizes` to specify a list of VM sizes to use with VMSS Instance Mix
[Compute] `az vmss create/update`: Add new parameter `--skuprofile-allocation-strategy` to update the allocation strategy for VMSS Instance Mix
---

[Compute] `az vmss create/update`: Add `--skuprofile-vmsizes` and `--skuprofile-allocation-strategy` for Instance Mix

---

src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py

`az postgres flexible-server update`
Removes a `print` call to remove a python object being dumped in stout while using the cli
Before fix:
```sh
az postgres flexible-server update \
--name server1 \
--resource-group rg1 \
--private-dns-zone private.postgres.database.azure.com
Using the existing private dns zone private.postgres.database.azure.com in resource group "rg1"
{'additional_properties': {}, 'sku': <azure.mgmt.rdbms.postgresql_flexibleservers.models._models_py3.Sku object at 0x1078f7450>, 'identity': None, 'tags': None, 'administrator_login_password': None, 'version': None, 'storage': <azure.mgmt.rdbms.postgresql_flexibleservers.models._models_py3.Storage object at 0x1078f73d0>, 'backup': …
```

{RDBMS} Removes print of params object in postgres flexible-server update

---

src/azure-cli/azure/cli/command_modules/cloud/custom.py

As part of removing `msrestazure` dependency, we vendor `_populate_from_metadata_endpoint` function for cloud module usage
---

{Cloud} Remove msrestazure call in cloud module

---

src/azure-cli-core/azure/cli/core/aaz/_content_builder.py

Fix None value when its sub property has not linked with arg_key
---

{core} `aaz`: fix aaz content builder `set_prop` for None value

---

doc/cli_subprocess_guidelines.md

This pr is a full guidance doc for executing az-related cmds in cli, including `run_az_cmd` (https://github.com/Azure/azure-cli/pull/29899)
---

{doc} Add security guidance for `az` cmd execution

---

src/azure-cli/azure/cli/command_modules/compute_recommender/aaz/latest/compute_recommender/_spot_placement_recommender.py

az compute-recommender spot-placement-recommender
In order to resolve the cli user confusion, this pr removes the default --ids from the az compute-recommender spot-placement-recommender cli parameters
`az compute-recommender spot-placement-recommender --help`
Now, the help output has no --ids
---

{compute-recommender} Remove default --ids from cli parameters

---

src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

Test Homebrew Formula failed with
```
==> python3.11 -m pip --python=/usr/local/Cellar/azure-cli/2.65.0/libexec/bin/py
Last 15 lines from /Users/runner/Library/Logs/Homebrew/azure-cli/115.python3.11:
File "<string>", line 480, in main
TypeError: 'color' is an invalid keyword argument for print()
error: subprocess-exited-with-error
× Building wheel for psutil (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> See above for output.
note: This error originates from a subprocess, and is likely not a problem with pip.
full command: /usr/local/Cellar/azure-cli/2.65.0/libexec/bin/python /usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /private/tmp/tmp2751l5nz
cwd: /private/tmp/azure-cli--psutil-20241022-14446-ha2qbt/psutil-5.9.5 …
```

{Packaging} Bump psutil to 6.1.0

---

src/azure-cli-core/azure/cli/core/auth/credential_adaptor.py

Azure CLI currently passes `kwargs` received by `get_token()` directly to MSAL. Since SDK is adding more keyword arguments, such as `enable_cae` (https://github.com/Azure/azure-sdk-for-python/pull/37358), this will cause failure as `enable_cae` is not recognized by MSAL.
This PR changes the behavior so that only `data` is passed to MSAL as `kwargs`.
Also see https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/755
1. Follow https://learn.microsoft.com/en-us/entra/identity/devices/howto-vm-sign-in-azure-ad-linux to enable connecting via Microsoft Entra ID and OpenSSH
2. `az extension add --name ssh`
3. `az ssh vm -n xxx -g xxx`

{Core} Only pass `data` to MSAL as `kwargs`

---

azure-pipelines.yml
src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_agentpool_commands.py
src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_connectedregistry_commands.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
src/azure-cli/azure/cli/command_modules/iot/tests/latest/test_iot_commands.py
src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_commands.py

The batched CI suddenly failed with `Message: The subscription '00000000-0000-0000-0000-000000000000' could not be found.` from Sep 25, 2024.
The Test Deb Packages and Test Rpm Package Azure Linux 3.0 fail. Not sure why distro use Python 3.9 still works.
The error is similar to https://github.com/Azure/azure-cli/pull/17185
For more detail, see Jiashuo's analysis at https://github.com/Azure/azure-cli/pull/18853#discussion_r1810260089 and https://github.com/Azure/azure-cli/pull/18611#discussion_r1810284183
Temporarily skip these tests to unblock release.

{CI} Skip some tests

---

src/azure-cli-core/azure/cli/core/keys.py
src/azure-cli-core/azure/cli/core/tests/test_keys.py
src/azure-cli-core/setup.py
src/azure-cli/setup.py

Migrate `generate_ssh_keys` from `paramiko` to `cryptography`.
https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/ contains some useful examples for working with RSA keys.

{Core} Migrate `generate_ssh_keys` from `paramiko` to `cryptography`

---

src/azure-cli/azure/cli/command_modules/profile/__init__.py
src/azure-cli/azure/cli/command_modules/profile/custom.py

`az login`
Update help message for arguments, mainly including
1. Re-order the arguments to group them according to the identity type
2. Rename AAD to Microsoft Entra, similar to #27756
3. Rename MSI to managed identity: https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview
> Managed identities for Azure resources is the new name for the service formerly known as Managed Service Identity (MSI).
`az login -h`

{Profile} Update help message for arguments

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/auth/adal_authentication.py
src/azure-cli-core/azure/cli/core/auth/constants.py
src/azure-cli-core/azure/cli/core/auth/identity.py
src/azure-cli-core/azure/cli/core/auth/msal_credentials.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py

This PR is separated from https://github.com/Azure/azure-cli/pull/25959.
Use MSAL for Cloud Shell authentication (https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/420).
Install Azure CLI in Cloud Shell:
```
git clone https://github.com/jiasli/azure-cli/
cd azure-cli
git switch cloud-shell-auth
python3 -m venv env
. env/bin/activate
pip install azdev
azdev setup -c
```
Log in:
```
az login --identity
```
Some basic testing:
```
az account get-access-token
az group show -n nonexist
```
Test getting SSH certificate:
```
az extension add -n ssh
az ssh vm --resource-group xxx --name xxx --debug
```
Test mgmt-plane Track 1 SDK:
```
az dls account list -g $RG_NAME
```
Test data-plane Track 1 …

[Core] Use MSAL for Cloud Shell authentication

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py

The change ensure that we don't show "Nothing to update" warning message when  `--set` is passed in `az functionapp plan update` command.
`az functionapp plan update --ids [plan-id]`  _(The command shows the warning message. )_
`az functionapp plan update --ids [plan-id] --set zoneRedundant=false`  _(The command doesn't show the warning message)_ 
---

[App Service] `az functionapp plan update`: Do not show warning message with `--set` in command

---

src/azure-cli/azure/cli/command_modules/acs/custom.py

https://github.com/Azure/azure-cli/issues/30101
This PR should fix the initial issue reported. 
Downloading kubectl for latest version of 1.30 and 1.29 returned 404 Not found error. 
The "kubernetes-release" bucket has been deprecated which means its likely the bucket doesn't receive the latest updates anymore (check this - https://github.com/kubernetes/k8s.io/issues/1571)
This is related to kubernetes change (https://github.com/kubernetes/k8s.io/issues/2396) to move away from GCS bucket in GCP project.

{kubectl} Fix kubectl 404 Not Found issue by updating source_url to dl.k8s.io

---

src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

This PR is a supplement to the https://github.com/Azure/azure-cli/pull/30164.
```
2024-10-25T13:00:24.9565306Z =================================== FAILURES ===================================
2024-10-25T13:00:24.9565695Z ____________________ VMSSUpdateTests.test_vmss_update_image ____________________
2024-10-25T13:00:24.9566296Z [gw3] linux -- Python 3.12.7 /opt/az/bin/python3
2024-10-25T13:00:24.9566647Z self = <azure.cli.testsdk.base.ExecutionResult object at 0xffff85571940>
2024-10-25T13:00:24.9567007Z cli_ctx = <azure.cli.core.mock.DummyCli object at 0xffff84dd7ad0>
2024-10-25T13:00:24.9567458Z command = 'vm deallocate -g cli_test_vmss_update_image_000001 -n vm1'
2024-10-25T13:00:24.9567777Z expect_failure = False
2024-10-25T13:00:24.9567882Z 
2024-10-25T13:00:24.9568175Z     def …
```

{CI} Skip test_vmss_update_image

---

src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py

`az postgres flexible-server update`
If you create a server with password authentication disabled and AAD enabled:
_az postgres flexible-server create --resource-group rg-test --name testpostgresqlserver --password-auth Disabled --active-directory-auth Enabled --location eastus --version 16 --high-availability Disabled --tier GeneralPurpose --public-access Enabled_
And then try to enable it using the update command:
_az postgres flexible-server update --resource-group rg-test --name testpostgresqlserver --password-auth Enabled
It fails with this error:
_(EngineCredentialsNotProvided) The admin credentials are required for creating admin role while enabling Password Authentication and must be provided.
Code: EngineCredentialsNotProvided
Message: The …

{RDBMS} `az postgres flexible-server update`: Fix bug not able to enable password authentication during update

---

scripts/release/rpm/test_azurelinux_in_docker.sh
scripts/release/rpm/test_rpm_in_docker.sh

pip can't be upgraded in Azure Linux 3, but it works fine on Mariner 2.0.
Since the pip version does not affect clitestsdk build, use the version installed by `python3-pip` package instead.
```
+ python -m pip install --upgrade pip setuptools
Requirement already satisfied: pip in /usr/lib/python3.12/site-packages (24.2)
Collecting pip
Downloading pip-24.3.1-py3-none-any.whl.metadata (3.7 kB)
Collecting setuptools
Downloading setuptools-75.2.0-py3-none-any.whl.metadata (6.9 kB)
Downloading pip-24.3.1-py3-none-any.whl (1.8 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 31.6 MB/s eta 0:00:00
Downloading setuptools-75.2.0-py3-none-any.whl (1.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 25.8 MB/s eta 0:00:00
Installing collected packages: setuptools, pip
Attempting …
```

{Packaging} Fix test RPM Azure Linux

---

src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_commands.py

This PR is a supplement to the https://github.com/Azure/azure-cli/pull/30164.
```
2024-10-29T04:21:37.3342779Z =================================== FAILURES ===================================
2024-10-29T04:21:37.3343200Z _____________ ReplicationMgmtScenarioTest.test_mysql_replica_mgmt ______________
2024-10-29T04:21:37.3344183Z [gw3] linux -- Python 3.12.7 /opt/az/bin/python3
2024-10-29T04:21:37.3344556Z self = <azure.cli.testsdk.base.ExecutionResult object at 0xffff97ac6180>
2024-10-29T04:21:37.3344963Z cli_ctx = <azure.cli.core.mock.DummyCli object at 0xffff9c62f6e0>
2024-10-29T04:21:37.3345865Z command = 'mysql server replica create -g clitest.rg000001 -n azuredbclirep1000003 -l westus --sku-name GP_Gen5_4 --source-serve...000-0000-0000-000000000000/resourceGroups/clitest.rg000001/prov …
```

{CI} Skip test_mysql_replica_mgmt

---

scripts/release/homebrew/docker/formula_generate.py

This parameter is removed in 3.12 and raises this error: `ArgumentError: virtualenv_create's without_pip is deprecated starting with Python 3.12`
Ref: https://dev.azure.com/azclitools/public/_build/results?buildId=201003&view=logs&jobId=ebe8970d-a8af-5d7e-4086-8f4ce0be006b&j=ebe8970d-a8af-5d7e-4086-8f4ce0be006b&t=3f22f999-770c-5d06-3bb8-1a936f5d8384

{Packaging} Remove `without_pip` in homebrew formula

---

src/azure-cli-core/azure/cli/core/auth/identity.py
src/azure-cli-core/azure/cli/core/auth/tests/test_identity.py
src/azure-cli/azure/cli/command_modules/profile/__init__.py
src/azure-cli/azure/cli/command_modules/profile/_help.py
src/azure-cli/azure/cli/command_modules/profile/custom.py

`az login`
Fix https://github.com/Azure/azure-cli/issues/28839
Require https://github.com/Azure/azure-cli/pull/30090
1. Add `--certificate` for authenticating with service principal certificate
2. Deprecate using `--password` to pass service principal certificate
```sh
az login --service-principal --username xxx --certificate xxx --tenant xxx
az login --service-principal --username xxx --password xxx --tenant xxx
```
[Profile] `az login`: Passing the service principal certificate with `--password` is deprecated and will be removed by version 2.74. Please use `--certificate` instead.

[Profile] `az login`: Add `--certificate` for authenticating with service principal certificate

---

scripts/release/rpm/test_azurelinux_in_docker.sh

Rework for https://github.com/Azure/azure-cli/pull/30211.
In 70.1.0, `wheel` has already been vendored in `setuptools`: https://github.com/pypa/setuptools/pull/4369
However, Mariner uses an old version of setuptools, which can't build wheel without `wheel` package.
Update `setuptools` to latest version to fix the issue.
```
title 'Build Azure CLI and its command modules'
for setup_file in $(find src -name 'setup.py'); do
pushd $(dirname ${setup_file}) >/dev/null
echo "Building module at $(pwd) ..."
python setup.py -q bdist_wheel -d $output_dir
python setup.py -q sdist -d $sdist_dir
popd >/dev/null
done
Build Azure CLI and its command modules
Building module at /azure-cli/src/azure-cli-telemetry ...
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help …
```

{Packaging} Update setuptools in Azure Linux RPM test

---

doc/command_guidelines.md
doc/debug/debug_in_vs_code.md
doc/extensions/authoring.md
doc/install_linux_prerequisites.md
scripts/ci/build.sh
src/azure-cli-core/setup.py
src/azure-cli-telemetry/setup.py
src/azure-cli-testsdk/setup.py
src/azure-cli/setup.py

Drop Python 3.8 because it was end of support on 2024-10-07: https://devguide.python.org/versions/
Drop 3.7 PR: https://github.com/Azure/azure-cli/pull/26855

[Packaging] Drop Python 3.8 support

---

.azure-pipelines/templates/variables.yml
azure-pipelines.yml
scripts/release/debian/test_deb_package.py
scripts/release/rpm/test_rpm_package.py

Use multi-core agent to build and run test for DEB and RPM.
`pytest` can create two workers to run the test now.
Save 20-30% of the time:
`Test Rpm Package Azure Linux 3.0 AMD64` drops from `2h 9m 32s` to `1h 34m 42s`
`Test Deb Packages Focal AMD64` drops from `1h 56m 16s` to `1h 24m 38s`
`Test Rpm Package Mariner 2.0 AMD64` drops from `1h 13m 27s` to `59m 33s`
`Test Rpm Package Red Hat Universal Base Image 8 AMD64` drops from `1h 5m 1s` to `50m 7s`
Known limitation:
1. Some modules are run in serial, such as `network`.
2. Some tests run much slower than others, slowing down the entire testing process. For example: `tests/latest/test_keyvault_commands.py::KeyVaultMgmtScenarioTest::test_keyvault_list_deleted ` takes 6 min.

{CI} Improve CI speed by using multi-core agent

---

src/azure-cli/azure/cli/command_modules/acs/_params.py

az aks trustedaccess rolebinding create
'-r' options used to marked deprecated, now totally remove it
[AKS] BREAKING CHANGE: `az aks trustedaccess rolebinding create`: Remove deprecated '-r' options
---

[AKS] BREAKING CHANGE: `az aks trustedaccess rolebinding create`: Remove deprecated `-r` options

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/auth/msal_credentials.py

- Close #16573
- Require https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/480
This is only a temporary solution.
If Azure Arc is detected, Azure CLI uses MSAL for managed identity authentication. For other platforms, such as VM and App Service, the existing logic is preserved. These platforms' migration will be done in https://github.com/Azure/azure-cli/pull/25959.

[Core] PREVIEW: Support managed identity on Azure Arc-enabled Windows server

---

src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py

Skip the tests temporarily to unblock CI:
---

{App Service} Skip failed tests to unblock CI

---

src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

Resolve https://github.com/Azure/azure-cli/issues/30048
Bump to latest version to eliminate the warning:
```
/usr/local/lib/python3.11/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
"cipher": algorithms.TripleDES,
/usr/local/lib/python3.11/site-packages/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
"class": algorithms.TripleDES,
```
See https://github.com/Azure/azure-cli/issues/30048#issuecomment-2463678148

{Packaging} Bump paramiko to 3.5.0 

---

src/azure-cli-core/azure/cli/core/aaz/_field_value.py

some developers don't wanna input {"type": "None"} for the empty identity, so better not to input.
before:
after:
---

{Core} `aaz`: Empty identity only applies to remove subcommand

---

src/azure-cli/azure/cli/command_modules/storage/_help.py

This command (and anything under storage) shows links to an outdated/unmaintained  version of Python. The update will use the generic https://docs.python.org/3/.... link that always points to the currency version of Python.
```bash
az storage --help 
```
Please see the above. No need to repeat it.

{Storage} `az storage` `--help`: Update Python docs link

---

src/azure-cli/azure/cli/command_modules/rdbms/validators.py

az postgres flexible-server list
This will fix the issue reported [here](https://github.com/Azure/azure-cli/issues/30303) by adding a null check prior to replacing the quotes with empty string.
Visual check on the command, working fine.
{RDBMS} `az postgres flexible-server list`: adding a null check to see if resource group passed is already null
---

{RDBMS} `az postgres flexible-server list`: adding a null check to see if resource group passed is already null

---

src/azure-cli-core/azure/cli/core/breaking_change.py

Update the breaking change release version.
It is recommended to update the version during the breaking change window. This will help avoid any issues with pre-announcements that indicate changes will occur in the current version after relase.
---

{Core} Update Next Breaking Change Release Version Number

---

src/azure-cli/azure/cli/command_modules/acs/addonconfiguration.py

az aks enable-addon -n ingress-appgw
This PR changes the role assigned to the addon identity from `Contributor` to more appropriate `Network Contributor` role.
Main reason to chain this is because the `Contributor` role is now getting flagged on S360 for certain services which use AGIC.
---

[AKS] `az aks enable-addon`: Update AGIC addon to use Network Contributor instead of Contributor

---

src/azure-cli/azure/cli/command_modules/role/_help.py
src/azure-cli/azure/cli/command_modules/role/_params.py
src/azure-cli/azure/cli/command_modules/role/custom.py

- Add examples for using `--cert` to clarify https://github.com/MicrosoftDocs/azure-docs-cli/issues/4734
- Change warning messages for `--create-cert` according to https://github.com/Azure/azure-cli/pull/30091
`az ad sp create-for-rbac -h`

{Microsoft Entra ID} `az ad sp create-for-rbac`: Update examples and warnings

---

src/azure-cli-core/azure/cli/core/_profile.py

`az login`
Refactor code for passing arguments.
Pave way for 
- https://github.com/Azure/azure-cli/pull/30301
- https://github.com/Azure/azure-cli/pull/30302

{Core} Refactor code for passing arguments

---

src/azure-cli/azure/cli/command_modules/network/custom.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_delegation.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_dnssec.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_if_none_match.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_tmlink.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone10_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone2_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone4_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone6_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone7_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone9_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone_commands_with_dnssec_zone.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone_update.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone_update_if_match.yaml

{Network} `az network dns zone`: Fix for the zone import logic

---

pylintrc
src/azure-cli/azure/cli/command_modules/acs/addonconfiguration.py
src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/recordingrules/create.py
src/azure-cli/azure/cli/command_modules/resource/custom.py
src/azure-cli/azure/cli/command_modules/storage/_validators.py
src/azure-cli/azure/cli/command_modules/storage/_validators_azure_stack.py
src/azure-cli/azure/cli/command_modules/vm/_image_builder.py

Fix `used-before-assignment`: https://pylint.readthedocs.io/en/stable/user_guide/messages/error/used-before-assignment.html

{Pylint} Fix used-before-assignment

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/setup.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

- Close https://github.com/Azure/azure-cli/issues/16573
- Require https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/763
This is only a temporary solution.
If Azure Arc is detected, Azure CLI uses MSAL for managed identity authentication. For other platforms, such as VM and App Service, the existing logic is preserved. These platforms' migration will be done in https://github.com/Azure/azure-cli/pull/25959.

[Core] PREVIEW: Support managed identity on Azure Arc-enabled Linux server

---

.github/ISSUE_TEMPLATE/docs_feedback.yml

This PR replaces [#30083](https://github.com/Azure/azure-cli/pull/30083)
*****************************************************
We need an additional GitHub issue template in azure-cli for customer feedback that is recieved on autogenerated reference docs. This template aligns with the Azure PowerShell template found here: https://github.com/Azure/azure-powershell/blob/main/.github/ISSUE_TEMPLATE/4-AZ-DOC-BUG.yml.
Anytime a customer uses the docs or product feedback links in MicrosoftDocs/azure-docs-cli WHEN IN AN AUTOGENERATED REFERENCE DOC, they will be taken to this new template. This will keep MicrosoftDocs/azure-docs-cli GitHub issues about conceptual content, and reference feedback is channeled correctly to the engineering teams.
**MicrosoftDocs/azure-docs-cli [PR …

{CI} New issue template for reference doc's feedback

---

azure-pipelines.yml

If the file path contains space, eg. `storage/doc/ADLS Gen2.md`, the secret scan step will be break. This PR fixes this bug.
---

{CI} Fix invalid file path for secret scan task

---

src/azure-cli/azure/cli/command_modules/vm/_params.py

`az vm/vmss create`
Fix help message: https://github.com/Azure/azure-cli/pull/30363#discussion_r1843266003
In PowerShell, the empty string should be '""' instead of '' or "":
---

[Compute] `az vm/vmss create`: Fix help message for `--public-ip-address` parameter

---

azure-pipelines.yml

Due to the inconsistent versions of jinja2 required by aosm and alias, and the random order of extension installations, installing a lower version of jinja2 can result in the following error:
```
File "/mnt/vss/_work/1/s/env/lib/python3.11/site-packages/jinja2/filters.py", line 13, in <module>
from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/mnt/vss/_work/1/s/env/lib/python3.11/site-packages/markupsafe/__init__.py)
```
Therefore, i want to enforce the use of a higher version of jinja2 for codegen coverage. …

{CI} Fix Codegen Coverage

---

src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/azure/cli/core/util.py
src/azure-cli/azure/cli/command_modules/keyvault/_transformers.py
src/azure-cli/azure/cli/command_modules/keyvault/commands.py

SDK models have changed when we move from swagger generated to typespec generated. This cause issues for `knack.util.todict` to do the formatter over command output. We call https://github.com/Azure/azure-cli/blob/eb55296b4f3280b0df1d557de99f6f9b828180b3/src/azure-cli-core/azure/cli/core/commands/__init__.py#L718 to convert the command result for easier format. Here's how [todict](https://github.com/microsoft/knack/blob/b1164b57d777711fd3954cf11f18ffb06ab1ca5b/knack/util.py#L133-L156) is implemented in `knack`:
```Python
def todict(obj, post_processor=None):  # pylint: disable=too-many-return-statements
"""
Convert an object to a dictionary. Use 'post_processor(original_obj, dictionary)' to update the
dictionary in the process
"""
if isinstance(obj, …
```

{Core} Add dict transformation for typespec generated SDKs

---

src/azure-cli/azure/cli/command_modules/network/azure_stack/_util.py

This code doesn't comply with the linter rules: https://github.com/Azure/azure-cli/pull/30365/files#r1861670755
Remove it as it's not used.

{Misc.} Remove unused function

---

.githooks/pre-commit.sh
azure-pipelines.yml

A supplementary for #30422 
While using for loop to iterate all git diff files, we need to change the `$IFS` from default to `$'\n'` only so that file name with space won't be split.
---

{CI} Fix file name space when iterating git diffs for secret scan task

---

src/azure-cli-core/azure/cli/core/auth/adal_authentication.py
src/azure-cli-core/azure/cli/core/auth/credential_adaptor.py
src/azure-cli-core/azure/cli/core/auth/tests/test_util.py
src/azure-cli-core/azure/cli/core/auth/util.py
src/azure-cli-testsdk/azure/cli/testsdk/patches.py

Resolve https://github.com/Azure/azure-cli/issues/20462
- Track 2 SDKs generated before https://github.com/Azure/autorest.python/pull/239 don't maintain `credential_scopes` and call `get_token` with empty scopes. As a workaround, return `None` so that the CLI-managed `resource` is used.
- Track 2 SDKs generated before https://github.com/Azure/autorest.python/pull/745 extend default `credential_scopes` with custom `credential_scopes`. Instead, `credential_scopes` should be replaced by custom `credential_scopes`. As a workaround, remove the first one if there are multiple scopes provided.
As CLI will no longer manage a `resource` after dropping Track 1 SDK support (https://github.com/Azure/azure-cli/pull/29631), this PR is a prerequisite.
**Testing …

[Core] Drop old Track 2 SDK authentication support

---

src/azure-cli/azure/cli/command_modules/acr/_archive_utils.py
src/azure-cli/azure/cli/command_modules/appconfig/_kv_helpers.py
src/azure-cli/azure/cli/command_modules/containerapp/_archive_utils.py

Taken out from #30368 
Motivation in:
https://docs.astral.sh/ruff/rules/open-alias/
---

{Misc} Don't use aliased io.open

---

src/azure-cli/azure/cli/command_modules/resource/_bicep.py
src/azure-cli/azure/cli/command_modules/security/_utils.py

From the documentation:
> If capture_output is true, stdout and stderr will be captured. When used, the internal Popen object is automatically created with stdout and stderr both set to PIPE. The stdout and stderr arguments may not be supplied at the same time as capture_output. If you wish to capture and combine both streams into one, set stdout to PIPE and stderr to STDOUT, instead of using capture_output.
---

{Misc} Fix UP022. Use capture_output for subprocess.run.

---

scripts/curl_install_pypi/install.py
src/azure-cli-core/azure/cli/core/aaz/_operation.py
src/azure-cli-core/azure/cli/core/keys.py
src/azure-cli-telemetry/azure/cli/telemetry/__init__.py
src/azure-cli-telemetry/azure/cli/telemetry/components/telemetry_client.py
src/azure-cli-telemetry/azure/cli/telemetry/tests/test_telemetry_client.py
src/azure-cli/azure/cli/command_modules/acr/_docker_utils.py
src/azure-cli/azure/cli/command_modules/acr/manifest.py
src/azure-cli/azure/cli/command_modules/acr/repository.py
src/azure-cli/azure/cli/command_modules/acr/tests/hybrid_2020_09_01/test_acr_commands_mock.py
src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_commands_mock.py
src/azure-cli/azure/cli/command_modules/botservice/kudu_client.py
src/azure-cli/azure/cli/command_modules/botservice/web_app_operations.py
src/azure-cli/azure/cli/command_modules/iot/sas_token_auth.py
src/azure-cli/azure/cli/command_modules/lab/validators.py
src/azure-cli/azure/cli/command_modules/resource/_validators.py
src/azure-cli/azure/cli/command_modules/servicefabric/custom.py
src/azure-cli/azure/cli/command_modules/storage/azcopy/util.py
src/azure-cli/azure/cli/command_modules/vm/_image_builder.py
src/azure-cli/azure/cli/command_modules/vm/_validators.py
src/azure-cli/azure/cli/command_modules/vm/_vm_utils.py
src/azure-cli/azure/cli/command_modules/vm/azure_stack/_image_builder.py
src/azure-cli/azure/cli/command_modules/vm/azure_stack/_validators.py
src/azure-cli/azure/cli/command_modules/vm/azure_stack/_vm_utils.py
tools/automation/utilities/pypi.py

Taken from #30368
Remove the various Python 2.7 import fallbacks. This was mostly limited to `urllib`. 
---

{Misc} Remove various Python 2.7 ImportError

---

.githooks/pre-commit.ps1
.githooks/pre-commit.sh

{githooks} improved pre-commit message

---

src/azure-cli-core/azure/cli/core/keys.py
src/azure-cli/azure/cli/command_modules/lab/validators.py

`az vm create`
Created from https://github.com/Azure/azure-cli/pull/30451#discussion_r1868915243
Stop using legacy `base64.decodebytes`.
https://docs.python.org/3/library/base64.html

{Core} Stop using legacy `base64.decodebytes`

---

pylintrc
src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli/azure/cli/command_modules/acr/check_health.py
src/azure-cli/azure/cli/command_modules/appservice/_create_util.py
src/azure-cli/azure/cli/command_modules/containerapp/_up_utils.py
src/azure-cli/azure/cli/command_modules/keyvault/vendored_sdks/azure_keyvault_securitydomain/_serialization.py
src/azure-cli/azure/cli/command_modules/resource/custom.py
src/azure-cli/azure/cli/command_modules/role/custom.py
src/azure-cli/azure/cli/command_modules/serviceconnector/_validators.py

Inspired by https://github.com/Azure/azure-cli/pull/30308
Fix [`consider-using-dict-items`](https://pylint.pycqa.org/en/latest/user_guide/messages/convention/consider-using-dict-items.html) pylint error.

{Pylint} Fix consider-using-dict-items

---

pylintrc
src/azure-cli-core/azure/cli/core/parser.py
src/azure-cli/azure/cli/command_modules/acr/_format.py
src/azure-cli/azure/cli/command_modules/acs/custom.py
src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/vm/azure_stack/custom.py
src/azure-cli/azure/cli/command_modules/vm/azure_stack/disk_encryption.py
src/azure-cli/azure/cli/command_modules/vm/custom.py
src/azure-cli/azure/cli/command_modules/vm/disk_encryption.py

Fix [`use-maxsplit-arg`](https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/use-maxsplit-arg.html) pylint error.

{Pylint} Fix use-maxsplit-arg

---

src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_commands_mock.py
src/azure-cli/azure/cli/command_modules/ams/tests/latest/test_ams_streaming_endpoint_scenarios.py
src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/test_appconfig_commands.py
src/azure-cli/azure/cli/command_modules/botservice/bot_json_formatter.py
src/azure-cli/azure/cli/command_modules/botservice/bot_publish_prep.py
src/azure-cli/azure/cli/command_modules/monitor/grammar/autoscale/AutoscaleConditionParser.py
src/azure-cli/azure/cli/command_modules/monitor/grammar/metric_alert/MetricAlertConditionParser.py
src/azure-cli/azure/cli/command_modules/resource/custom.py

Some of this was also done in #30368 
I see this function in various places. I've edited one instance that didn't have the `in_cloud_console()` check. I left the ones that match this untouched:
```python
def _ssl_context():
if sys.version_info < (3, 4) or (in_cloud_console() and platform.system() == 'Windows'):
try:
return ssl.SSLContext(ssl.PROTOCOL_TLS)
except AttributeError:
return ssl.SSLContext(ssl.PROTOCOL_TLSv1)
return ssl.create_default_context()
```
There's a commented out test in `test_ams_streaming_endpoint_scenarios.py`
--- …

{Misc} Remove misc Python 2.7 fallbacks.

---

src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/test_appconfig_commands.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

Only one case was dubious. The other four were just duplicates.
You should consider replacing `pylint` with `ruff`. It finds more problems, and it appears that most PyLint rules are ported to ruff. PyLint is slow ...
---

{Misc} Fix F601 errors. Duplicate dictionary keys.

---

azure-pipelines.yml

CG only runs in default branch by default.
Set ComponentDetection.ForceScan to enable CG in release branch.
> ComponentDetection.ForceScan - When enabled, the auto-injected build task will execute a scan in your build no matter if the branch is not in scope (e.g. non-default branch)
---https://docs.opensource.microsoft.com/tools/cg/component-detection/variables/
```
##[info]Looking for pipeline information in Product Catalog...
##[info]Evaluating Branch...
##[info]SourceBranch: refs/heads/release
##[info]DefaultBranch: refs/heads/dev
##[info]Result: Skipping scan. Reason: Pipeline is not in-scope for automatic open source vulnerability scans and not default branch.
```
--------
It also skips running when CFS is not enabled, that's why CG is not running in dev branch.
> If the pip report …

{CI} Enable component detection in release branch

---

.githooks/pre-push.ps1
.githooks/pre-push.sh

Optimize the pre-push Git hook to support interactive mode.
---

{CI} Optimize azure-cli githook

---

src/azure-cli/azure/cli/command_modules/cdn/custom/custom_afdx.py

Fix 
"enable" spell for https://github.com/Azure/azure-cli/issues/30018
size error in help doc for https://github.com/Azure/azure-cli/issues/30016

{AFD} fix doc for #30018 #30016

---

build_scripts/windows/scripts/build.cmd
scripts/release/debian/build.sh

Bump Python to latest version
https://www.python.org/downloads/release/python-3128/
[Core] Resolve CVE-2024-50602

{Packaging} Bump embedded Python version to 3.12.8

---

src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_access_restriction_commands.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

Backport #30289, #30313 as these tests are blocking CI:
https://dev.azure.com/azclitools/public/_build/results?buildId=211865&view=logs&jobId=3791f883-8843-5e94-fc79-c8ca993c0a42&j=3791f883-8843-5e94-fc79-c8ca993c0a42&t=fc099b28-42bc-5603-6ee8-d61b88ef47c8
```
2024-12-18T08:36:50.2916288Z self = <azure.cli.command_modules.appservice.custom._FunctionAppStackRuntimeHelper object at 0x7fc82fce51f0>
2024-12-18T08:36:50.2916559Z runtime = 'dotnet', version = '6'
2024-12-18T08:36:50.2916647Z 
2024-12-18T08:36:50.2916849Z     def validate_end_of_life_date(self, runtime, version):
2024-12-18T08:36:50.2917091Z         from dateutil.relativedelta import relativedelta
2024-12-18T08:36:50.2917303Z         today = datetime.datetime.now(datetime.timezone.utc) …
```

{LTS} Backport #30289, #30313

---

src/azure-cli/azure/cli/command_modules/keyvault/custom.py
src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_key.yaml
src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py

`az keyvault key sign/verify`
Fix https://github.com/Azure/azure-cli/issues/27631, https://github.com/Azure/azure-cli/issues/28027
`--digest` now accepts base64 encoded string
```
> echo "HelloWorld" | openssl dgst -sha256 -binary | openssl base64
Pz8hPx8/Pz9mP11RFj8/Mz8/bj91PwRhPz8JQ2k/eGMNCg==
> az keyvault key sign -n $rsaKey --vault-name $testVault -a RS256 --digest Pz8hPx8/Pz9mP11RFj8/Mz8/bj91PwRhP
{
"algorithm": "RS256",
"keyId": "https://$testVault.vault.azure.net/keys/......",
"signature": "UZmopfF5fHtGs+qu8............=="
}
> az keyvault key verify -n $rsaKey --vault-name $testVault -a RS256 --digest Pz8hPx8/Pz9mP11RFj8/Mz8/bj91PwRhP --signature "UZmopfF5fHtGs+qu8............=="
{
"algorithm": "RS256",
"isValid": true, …
```

[Keyvault] `az keyvault key sign/verify`: Fix `--digest` to accept base64 encoded string

---

src/azure-cli/azure/cli/command_modules/storage/_help.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_table_main_scenario.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_table_scenarios.py

{Storage} `az storage entity insert`: Add instructions for specifying odata type
Fix #30377 
---

{Storage} Fix #30377: `az storage entity insert`: Add instructions for specifying odata type

---

src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py

{AKS}: _get_outbound_type should return None and natgateway profile hould be validaated
{AKS} `az aks create/update`: Outbound type should not be updated if it is not set
---

{AKS} `az aks create/update`: Outbound type should not be updated if it is not set

---

src/azure-cli-core/azure/cli/core/auth/identity.py
src/azure-cli-core/azure/cli/core/auth/tests/test_identity.py
src/azure-cli-core/azure/cli/core/auth/util.py
src/azure-cli/azure/cli/command_modules/profile/_help.py
src/azure-cli/azure/cli/command_modules/profile/custom.py

Backport #30092
[Profile] BREAKING CHANGE: `az login`: `--password` no longer accepts a service principal certificate. Use `--certificate` to pass a service principal certificate

[LTS] Backport #30092

---

src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_common.py

`az postgres flexible-server upgrade` 
PG 12 is no longer being supported by community, ability to select version will be blocked during provisioning and migration version upgrade.
Manually
postgres' 'flexible-server' 'upgrade' '-g' 'nasc-runner' '--name' 'nasc-pg11-delete' '--version' '12'                  
WARNING: Unable to load extension 'rdbms-connect: local variable 'command_loader' referenced before assignment'. Use --debug for more information.
Upgrading major version in server nasc-pg11-delete is irreversible. The action you're about to take can't be undone. Going further will initiate major version upgrade to the selected version on this server. (y/n): y
**WARNING: Support for PostgreSQL 12 has officially ended. As a result, …

{RDBMS} Add warnings that selecting PG version 12 will no longer be supported in `az postgres flexible-server upgrade` 

---

src/azure-cli-core/azure/cli/core/extension/operations.py

Default log in sufficient for debugging.
`-vv` generates more than 9000 lines of log when running `az extension add -n ssh --debug`.

{Extension} Remove verbose log in pip

---

src/azure-cli/azure/cli/command_modules/storage/_validators.py
src/azure-cli/azure/cli/command_modules/storage/operations/fileshare.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_azcopy_scenarios.py

Fix when wildcard `*` is in `--source-file-path`
Fix #29929 
[Storage] Fix #29929: `az storage copy`: Fix when wildcard `*` is in `--source-file-path`
---

[Storage] Fix #29929: `az storage copy`: Fix when wildcard `*` is in `--source-file-path`

---

src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/watcher/flow_log/_create.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/watcher/flow_log/_delete.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/watcher/flow_log/_list.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/watcher/flow_log/_show.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/watcher/flow_log/_update.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/watcher/flow_log/_wait.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_nw_flow_log.py

**Related commands**
```
az network watcher flow-log create --location eastus2euap --resource-group riddhi_rg3 --name vnet-eastus2euap-flowlog --vnet vnet-eastus2euap --storage-account riddhisa3  --filtering-criteria "dstip=20.252.145.59 || DstPort=443"
az network watcher flow-log show --location eastus2euap --name vnet-eastus2euap-flowlog
```
This PR introduces a new optional field, "filtering-criteria," for the creation and update of the Flowlogs resource. Necessary validations for this field have already been implemented in NRP. Unit tests for this feature have been added as part of this PR.
Additionally, screenshots of the testing performed, beyond unit tests, are included below.
Help command shows the new field and its proper explanation:
`az network …

{cli} Changes for adding an optional field for Filtering to Azure Cli commands for flowlogs resource creation and updation

---

src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py
src/azure-cli/azure/cli/command_modules/rdbms/_params.py
src/azure-cli/azure/cli/command_modules/rdbms/validators.py

Adding case-insensitive support for `--public-access` parameter
{RDBMS} `az postgres flexible-server create`: Support Case-Insensitive Input for `--public-access`
---

{RDBMS} `az postgres flexible-server create`: Support Case-Insensitive Input for `--public-access`

---

src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py

az postgres flexible-server identity_remove
Add a check to determine whether the user identity is used for geo backup data encryption
Local testing
{RDBMS} `az postgres flexible-server identity_remove`: Add a check to determine whether the user identity is used for geo backup data encryption
---

{RDBMS} `az postgres flexible-server identity_remove`: Add a check to determine whether the user identity is used for geo backup data encryption

---

src/azure-cli/azure/cli/command_modules/role/_msgrpah/_graph_objects.py
src/azure-cli/azure/cli/command_modules/role/_params.py
src/azure-cli/azure/cli/command_modules/role/custom.py
src/azure-cli/azure/cli/command_modules/role/linter_exclusions.yml
src/azure-cli/azure/cli/command_modules/role/tests/latest/recordings/test_app_create_idempotent.yaml
src/azure-cli/azure/cli/command_modules/role/tests/latest/recordings/test_app_scenario.yaml
src/azure-cli/azure/cli/command_modules/role/tests/latest/test_graph.py

`az ad app create/update`
Add `--requested-access-token-version` argument for Microsoft Graph application's `api.requestedAccessTokenVersion` property:
- https://learn.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0#properties
- https://learn.microsoft.com/en-us/graph/api/resources/apiapplication?view=graph-rest-1.0#properties
`api.requestedAccessTokenVersion` property can be specified in 2 ways:
1. Creating an application:
```
az ad app create --display-name APP_DISPLAY_NAME --requested-access-token-version 2
```
2. Updating an existing application:
```
az ad app update --id APP_ID --requested-access-token-version 2
```
```sh
az ad app create --display-name azure-cli-test20241031 …
```

[Microsoft Entra ID] `az ad app create/update`: Add `--requested-access-token-version` argument

---

scripts/release/debian/verify_debian_in_docker.sh
scripts/release/rpm/verify_rpm_in_docker.sh

We need to install a specific version to verify the LTS version. Update the script to install `CLI_VERSION` instead of the latest one.
`docker run -e CLI_VERSION=2.66.0 -v ./verify_debian_in_docker.sh:/verify_debian_in_docker.sh ubuntu:24.04 bash ./verify_debian_in_docker.sh`
`docker run -e CLI_VERSION=2.66.0 -v ./verify_debian_in_docker.sh:/verify_debian_in_docker.sh debian:12 bash ./verify_debian_in_docker.sh`
`docker run -e CLI_VERSION=2.66.0 -e IMPORT_KEY=false -e DNF_COMMAND=tdnf -v ./verify_rpm_in_docker.sh:/verify_rpm_in_docker.sh mcr.microsoft.com/cbl-mariner/base/core:2.0  bash ./verify_rpm_in_docker.sh`
`docker run -e CLI_VERSION=2.66.0 -e IMPORT_KEY=false -e DNF_COMMAND=tdnf -v ./verify_rpm_in_docker.sh:/verify_rpm_in_docker.sh …

{CI} Install specific version in script

---

src/azure-cli/azure/cli/command_modules/container/custom.py

Reproduction steps:
```bash
az container exec \
--container-name "container" \
-g "$RESOURCE_GROUP" \
-n "$ACI_NAME" \
--exec-command "echo Hello" > ./stdout < /dev/null 2>./stderr
```
Expected behavior:
./stdout should contain "Hello"
Actual behavior:
Command crashes without running the command. Error:
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: (25, 'Inappropriate ioctl for device')
File "/opt/az/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
raise ex
File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.p …

[Container] `az container exec`: Fix exception when stdin is not a tty

---

src/azure-cli/azure/cli/command_modules/appservice/_params.py
src/azure-cli/azure/cli/command_modules/rdbms/_params.py
src/azure-cli/azure/cli/command_modules/storage/_help.py

This is a supplement for the batch mitigating pr: https://github.com/Azure/azure-cli/pull/30424 for this sprint change.
---

{doc} Fix disallowed html tags

---

src/azure-cli/azure/cli/command_modules/network/operations/load_balancer.py

fix: https://github.com/Azure/azure-cli/issues/30535
The Vnet is added to the backend pool, so when customers try to pass in the Vnet via this command we get an NRP error. When no Vnet is applied we hit an error saying "Vnet or subnet is required" <- this limit should be removed.
---

[Network] Fix #30535: `az network lb address-pool address add`: Address level may not have virtual network property

---

src/azure-cli-core/azure/cli/core/aaz/_field_type.py
src/azure-cli-core/azure/cli/core/tests/test_aaz_field.py

The python SDK support to transform string to simple types such as int, bool, float. This PR added those support in aaz dev commands as well to backward compatible with the existing SDK command migration.
---

[Core] `aaz`: Support simple type parsed from string value

---

src/azure-cli/azure/cli/command_modules/storage/azcopy/util.py

Since the old links have been deprecated https://learn.microsoft.com/en-us/azure/cdn/edgio-retirement-faq
Switching to links using FrontDoor endpoint.
For customers wanting to use later versions than 10.13.0 please use this link
https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10?tabs=dnf#download-the-azcopy-portable-binary
Fix #30635 
{Storage} Fix #30635: `az storage copy`: Use Azure FrontDoor instead of Edgio endpoint for the installation link which has been deprecated
---

{Storage} Fix #30635: `az storage copy`: Use Azure FrontDoor instead of Edgio endpoint for the installation link which has been deprecated

---

src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
src/azure-cli/azure/cli/command_modules/serviceconnector/_validators.py

[ServiceConnector] `az webapp connection create redis`: Add `--system-identity` param

---

src/azure-cli-core/azure/cli/core/util.py

`az --version`
Show the config directory location actually used by Azure CLI in the output of `az --version`.
The default config directory is `$HOME/.azure` and can be overridden with `AZURE_CONFIG_DIR`: https://learn.microsoft.com/en-us/cli/azure/azure-cli-configuration#cli-configuration-file
Currently, it is not very convenient to get the config directory location: https://github.com/actions/runner-images/pull/11173#discussion_r1916144221. It is only shown in the `--debug` log.
```
> az --version
azure-cli                         2.68.0
core                              2.68.0
telemetry                          1.1.0
Extensions:
ssh                                2.0.6
Dependencies:
msal                              1.31.0 …
```

{Misc.} `az --version`: Show config directory location

---

src/azure-cli/azure/cli/command_modules/keyvault/custom.py

`az keyvault update/update-hsm`
When updating keyvault/MHSM network rule with `--default-action Deny`, the `--bypass` param is mistakenly set to `AzureServices` by default by Azure CLI.
_Note: This only happens when the old network rule is Null_
---

[Keyvault] `az keyvault update/update-hsm`: Fix `--bypass` overriding by default when specifying `--default-action Deny`

---

src/azure-cli/azure/cli/command_modules/role/_help.py
src/azure-cli/azure/cli/command_modules/role/_params.py
src/azure-cli/azure/cli/command_modules/role/commands.py
src/azure-cli/azure/cli/command_modules/role/custom.py
src/azure-cli/azure/cli/command_modules/role/tests/latest/recordings/test_built_in_role_definition_scenario.yaml
src/azure-cli/azure/cli/command_modules/role/tests/latest/test_role.py

`az role definition show`
For `az role definition list`, https://github.com/Azure/azure-cli/pull/30587 started to use `roleName` filter when `--name` is a non-GUID string, but if the provided `--name` is a GUID, this command still uses a client-side filter which is inefficient. 
`name` cannot be used as a `filter` and the API fails with:
```
Code: UnsupportedFilter
Message: The filter 'name eq 'Reader'' is not supported. Supported filters are either roleName eq '{value}' or type eq 'BuiltInRole|CustomRole'.
```
We can internally switch to [Role Definitions - Get](https://learn.microsoft.com/en-us/rest/api/authorization/role-definitions/get?view=rest-authorization-2022-04-01&tabs=HTTP) API when `--name`  is a GUID and convert the result to a list, but …

[Role] Add `az role definition show` command

---

src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_frontend_ip_zone.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

`az network lb create`
According to [Swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2024-05-01/loadBalancer.json#L1797-L1822), FrontendIPConfiguration.Zone should be able to accept multiple values 
close https://github.com/Azure/azure-cli/issues/30502
---

[Network] `az network lb create`: Refine `--frontend-ip-zone` to support multiple zones

---

src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py

az postgres flexible-server backup delete
Change user confirmation so it refers to server name instead of resource group
Manual testing
{RDBMS} `az postgres flexible-server backup delete`: change user confirmation so it refers to server name instead of resource group
---

{RDBMS} `az postgres flexible-server backup delete`: change user confirmation so it refers to server name instead of resource group

---

azure-linux.dockerfile

Call `az version` during docker build to generate command index. This should accelerate the first command execution speed. 
It adds these files in `~/.azure`, and only `commandIndex.json` is kept in the image.
```
root [ ~/.azure ]# ls  ~/.azure
az.json  az.sess  az_survey.json  azureProfile.json  commandIndex.json  commands  config  logs  telemetry  versionCheck.json
```
This reminds me of https://github.com/Azure/azure-cli/issues/19183, where the user complains that the first invocation is slow.
-------------
CLI also tries to get latest version from GitHub and save `versionCheck.json` in fresh installation, which takes 2s on my machine. I believe it's also not necessary. Source code: https://github.com/Azure/azure-cli/blob/a29d2e78ac30942b98427627e4f2c4a598bc1eeb/src/azu …

{Packaging} Accelerate command execution in Docker image with warm start

---

src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
src/azure-cli/azure/cli/command_modules/rdbms/validators.py

az postgres flexible-server backup create
Add backup name validator
Manual testing
{RDBMS} `az postgres flexible-server backup create`: add backup name validator
---

{RDBMS} `az postgres flexible-server backup create`: add backup name validator

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/azure-cli/azure/cli/command_modules/profile/__init__.py
src/azure-cli/azure/cli/command_modules/profile/_help.py
src/azure-cli/azure/cli/command_modules/profile/custom.py
src/azure-cli/azure/cli/command_modules/profile/tests/latest/test_profile_custom.py

Close https://github.com/Azure/azure-cli/issues/29480
`az login` currently reuses `--username` for 3 types of IDs. This has several disadvantages:
1. It is inefficient, as it uses a trial-and-error approach to detect the ID type.
2. It pollutes managed identity's server telemetry as it makes failed calls on purpose.
3. It is confusing, as username is a concept related to user flow, such as auth code flow, device code flow and username password (ROPC) flow.
4. It may have security risk of sending data (may contain PII) to unexpected places.
With the recent initiative of moving to password-free authentication methods, managed identity authentication is becoming more important. 
```sh
az login --identity --client-id …
```

[Profile] `az login`: Add `--client-id`, `--object-id` and `--resource-id` for authenticating with user-assigned managed identity

---

src/azure-cli/azure/cli/command_modules/rdbms/_params.py
src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
src/azure-cli/azure/cli/command_modules/rdbms/validators.py

az postgres flexible-server geo-restore
Add optional `--restore-time` parameter. From [_params.py](https://github.com/Azure/azure-cli/blob/fc511f6a1ef7ade727b42d836a76539c6e737322/src/azure-cli/azure/cli/command_modules/rdbms/_params.py#L475-L479), the default value is `get_current_time()`, which is the exact value we're passing without the argument. Therefore, this is not a breaking change.
Manual testing
[RDBMS] `az postgres flexible-server geo-restore`: add `--restore-time` parameter
---

[RDBMS] `az postgres flexible-server geo-restore`: add optional `--restore-time` parameter

---

src/azure-cli/azure/cli/command_modules/acr/_docker_utils.py

az acr login 
Fix login issue on SAW https://github.com/Azure/azure-cli/issues/30041 due to a special package used to replace the standard python requests package. Since the standard python package cannot be used on SAW for security reasons, CLI team replaced requests with windows-http. The different positional argument sequence between requests and windows-http caused this issue to occur on SAW. I had a discussion with Hang Lei and the quickest way to resolve this is to use keyword arguments instead of positional arguments. We will have to wait until the next CLI release to SAW for the issue to be resolved. 
az acr login -n myregistry
---

{ACR} Fix #30041: `az acr`:  Fix the "multiple values for keyword argument" error when the acr commands running on SAW

---

src/azure-cli/azure/cli/command_modules/vm/custom.py

`az vm/vmss create`
Close: #30516
---

[Compute] `az vm/vmss create`: Install guest attestation extension when security type set to ConfidentialVM

---

src/azure-cli/azure/cli/command_modules/appservice/_params.py
src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_create_slot_https_only_default_true.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_create_slot_https_only_false.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_create_slot_https_only_true.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py

`az functionapp deployment slot create` 
Resolves https://github.com/Azure/Azure-Functions/issues/1647
Resolves https://github.com/Azure/azure-cli/issues/14165
Changes:
- When a new slot is created, we set the https-only param to true by default. 
- Additionally, we now allow users to set the https-only param when creating a slot.
1. Create a function app (`az functionapp create -g <resourceGroup> -n <appName> -p <planName> -s <storageName> --runtime <runtime> --functions-version 4`)
2. Create a slot and set its https-only value (`az functionapp deployment slot create -g <resourceGroup> -n <appName> -s <slotName> --https-only=<True or False>`)
--- …

[App Service] `az functionapp deployment slot create`: Add `--https-only` parameter for slot creation command

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py

`az webapp list-runtimes`
App Service Linux uses internal variants of the JBoss EAP runtimes with a `_byol` suffix in their name and those should be removed from the output to avoid confusion.
Running `az webapp list-runtimes --os linux` should not contain any entries which had `_byol` in their runtime name.
Before:
```
> az webapp list-runtimes --os linux
[
...(omitted)...
"JBOSSEAP:8-java17",
"JBOSSEAP:8-java11",
"JBOSSEAP:8-java17_byol",
"JBOSSEAP:8-java11_byol",
"JBOSSEAP:7-java17",
"JBOSSEAP:7-java11",
"JBOSSEAP:7-java8",
"JBOSSEAP:7-java17_byol",
"JBOSSEAP:7-java11_byol",
"JBOSSEAP:7-java8_byol",
...(omitted)...
```
After:
```
az webapp list-runtimes --os linux
[
...(omitted)...
"JBOSSEAP:8-java17",
"JBOSSEAP:8-java11", …
```

[AppService] `az webapp list-runtimes`: Remove the JBoss '_byol' entries from the output for webapps with Linux OS

---

src/azure-cli/azure/cli/command_modules/iot/custom.py

`az iot hub policy renew-key`
This moves key generation for IoT Hub policy key renewals to the service side, rather than the client.
This change is completely hidden from the user interface. The following example command should continue to renew policy keys for the IoT Hub:
`az iot hub policy renew-key --name {policyName} --hub-name {hubName} --resource-group {resourceGroupName} --rk primary` 
---

{IoT} `az iot hub policy renew-key`: Service-side HIS renewal of IoT Hub policy keys

---

src/azure-cli-core/setup.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

`az account get-access-token`
Bump MSAL to 1.31.2b1 to adopt https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/785 which fixes https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/784.
After migrating Cloud Shell authentication to MSAL (https://github.com/Azure/azure-cli/pull/29637), in Cloud Shell, `az account get-access-token` fails if `--resource` is a GUID:
```
$ az account get-access-token --resource 6dae42f8-4368-4678-94ff-3960e28e3630
A Cloud Shell credential problem occurred. When you report the issue with the error below, please mention the hostname 'SandboxHost-638736411959985933'
Audience 6dae42f8-4368-4678-94ff-3960e28e3630/.default is not a supported MSI token audience.
```
This PR fixes …

{Core} Bump MSAL to 1.31.2b1

---

src/azure-cli-core/azure/cli/core/commands/arm.py
src/azure-cli-core/azure/cli/core/tests/test_util.py
src/azure-cli-core/azure/cli/core/util.py

{core} Fixed generic update issue.

---

src/azure-cli/azure/cli/command_modules/rdbms/_params.py
src/azure-cli/azure/cli/command_modules/rdbms/validators.py

az postgres flexible-server firewall-rule create
Modify firewall rule name validator
Manual testing
{RDBMS} `az postgres flexible-server firewall-rule create`: modify firewall rule name validator
---

{RDBMS} `az postgres flexible-server firewall-rule create`: modify firewall rule name validator

---

src/azure-cli/azure/cli/command_modules/rdbms/validators.py

az postgres flexible-server update
Modify the error message for `_pg_storage_validator`
Manual testing
{RDBMS} `az postgres flexible-server create/update`: modify the error message for `_pg_storage_validator`
---

{RDBMS} `az postgres flexible-server create/update`: modify the error message for `_pg_storage_validator`

---

src/azure-cli/azure/cli/command_modules/acs/_validators.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_validators.py

Before this change, users could use `--asg-ids` alone without specifying `--allowed-host-ports`, which did nothing at all. This PR will now show an error message if that happens.
---

[AKS] `az aks create/az aks nodepool add`: Emit error message when using `--asg-ids` alone without `--allowed-host-ports`

---

src/azure-cli/service_name.json

The following Azure CLI reference groups are no longer being published but still exist in the `service_name.json` file. This is creating build warnings in MicrosoftDocs/azure-docs-cli.

{doc} Remove invalid command group ref in `service_name.json`

---

src/azure-cli/azure/cli/command_modules/dls/_client_factory.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

Upgrade `azure-datalake-store` SDK to `1.0.0a0`. As listed in SDK release history
```
1.0.0-alpha0 (2024-07-12)
- Use generic azure token credential for auth instead of custom lib.auth
```
This will unblock us from dropping `signed_session()` interface in #29631 
---

{dls} Upgrade azure-datalake-store to 1.0.0a0

---

src/azure-cli/azure/cli/command_modules/acs/custom.py

az aks nodepool upgrade
fix the issue that `az aks nodepool upgrade` cannot set node_soak_duration to 0
---

[AKS] `az aks nodepool upgrade`: Fix `--node-soak-duration` cannot be set to 0

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py

Calling `get_token()` without `scopes` is no longer supported (https://github.com/Azure/azure-cli/pull/29690). After Track 1 SDK authentication removal (https://github.com/Azure/azure-cli/pull/29631), these tests fails
```
FAILED src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py::AppServiceLogTest::test_download_win_web_log
FAILED src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py::WebappZipDeployScenarioTest::test_deploy_zip
FAILED src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py::WebappDeploymentLogsScenarioTest::test_webapp_list_deployment_logs
FAILED src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_w …
```

{App Service} Call `get_token()` with `scopes`

---

src/azure-cli/azure/cli/command_modules/containerapp/_utils.py

Mgmt-plane SDK client should be created by `get_mgmt_service_client`, not manually created.

{Containerapp} Use `get_mgmt_service_client` to create `ServiceLinkerManagementClient`

---

src/azure-cli/azure/cli/command_modules/ams/operations/sp.py

Track 1 SDK authentication will be dropped by https://github.com/Azure/azure-cli/pull/29631.
Actually, the returned credential is discarded, so no access token is retrieved.

{AMS} Remove unnecessary `resource` argument

---

src/azure-cli/azure/cli/command_modules/batch/_client_factory.py
src/azure-cli/azure/cli/command_modules/batch/_validators.py

`az batch`
The Track 2 migration for `azure-batch` SDK (https://github.com/Azure/azure-cli/pull/30501) is incomplete - it doesn't set `credential_scopes` when creating `BatchClient`.
This will cause failure in sovereign clouds as different clouds have different `batch_resource_id`:
https://github.com/Azure/azure-cli/blob/58145231ac574303e8f64e38044cc0a39ca90013/src/azure-cli-core/azure/cli/core/cloud.py#L365
https://github.com/Azure/azure-cli/blob/58145231ac574303e8f64e38044cc0a39ca90013/src/azure-cli-core/azure/cli/core/cloud.py#L402
https://github.com/Azure/azure-cli/blob/58145231ac574303e8f64e38044cc0a39ca90013/src/azure-cli-core/azure/cli/core/cloud.py#L433
https://github.com/Azure/azure-cli/blob/58145231ac574303e8f64e38044cc0a39ca90013/src/azure-cli …

{Batch} Set `credential_scopes` when creating `BatchClient`

---

src/azure-cli/azure/cli/command_modules/dls/_client_factory.py

The Track 2 migration for `azure-datalake-store` SDK (https://github.com/Azure/azure-cli/pull/30770) is incomplete - it doesn't set `scopes` when creating `AzureDLFileSystem`.

{dls} Set `scopes` when creating `AzureDLFileSystem`

---

src/azure-cli/azure/cli/command_modules/synapse/manual/_client_factory.py

`credential_scopes` is not set when creating `azure.synapse` clients.
This will cause failure in sovereign clouds as different clouds have different `synapse_analytics_resource_id`:
https://github.com/Azure/azure-cli/blob/58145231ac574303e8f64e38044cc0a39ca90013/src/azure-cli-core/azure/cli/core/cloud.py#L378
https://github.com/Azure/azure-cli/blob/58145231ac574303e8f64e38044cc0a39ca90013/src/azure-cli-core/azure/cli/core/cloud.py#L414
https://github.com/Azure/azure-cli/blob/58145231ac574303e8f64e38044cc0a39ca90013/src/azure-cli-core/azure/cli/core/cloud.py#L445

{Synapse} Set `credential_scopes` when creating clients

---

azure-pipelines.yml

Supplement of https://github.com/Azure/azure-cli/pull/29866. Use CFS in the LTS release, such as `release-lts-2.66`.

{CI} Use CFS in LTS release

---

azure-pipelines.yml

Backport https://github.com/Azure/azure-cli/pull/30554, use CFS in LTS.

{LTS} Backport #30554

---

build_scripts/windows/scripts/build.cmd

There are 2072 empty `__pycache__` folders in 2.69.0 zip package. For example: `Lib/site-packages/__pycache__`. (The only non-empty folder is `Scripts\__pycache__`)
```
fd --type directory --type empty __pycache__ | wc
2072    2072  167666
```
In `build.cmd`, we only remove `__pycache__` files in `pip` folder. The empty `__pycache__` folders are never been removed. Since msi package ingores emtpy folder by default, this issue does not happen in msi.
> Because folders created by the installer are deleted when they become empty, you must author an entry into the CreateFolder table to install a component that consists of an empty folder. 
-- https://learn.microsoft.com/en-us/windows/win32/msi/createfolder-table?redirectedfrom=MSDN 
2.69.0 zip package:
new …

{Packaging} Remove empty `__pycache__` folder in zip package

---

src/azure-cli-core/azure/cli/core/telemetry.py
src/azure-cli-core/setup.py

We want a shared deviceId in the telemetry to join CLI telemetry and VS code telemetry. VS code provides https://pypi.org/project/py-deviceid/ lib to generate the same device id for each device which can be used by VS code and CLI (or any other client tools)
---

{Core} Add deviceId in CLI telemetry to share with VS code

---

src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_common.py
src/azure-cli/azure/cli/command_modules/rdbms/validators.py

az postgres flexible-server firewall-rule
az postgres flexible-server firewall-rule create needs to validate that either --start-ip-address or --end-ip-address are passed. Otherwise, it constructs a request with an empty body that returns an InternalServerError.''
Change the text of this error, to the following:
Firewall rule operations cannot be requested for a server that doesn't have public access enabled.
Manual
Validate stat or end has to be passed
Update error text
--- …

{RDBMS} `az postgres flexible-server firewall-rule`: Update validations and message for fire wall rule commands

---

src/azure-cli/azure/cli/command_modules/acr/_constants.py
src/azure-cli/azure/cli/command_modules/acr/cache.py

```
az acr cache create
az acr cache update
```
`az acr cache create` and `az acr cache update` are used to create and update cache rules under Azure Container Registry. A _cache rule_ is a sub resource of a container registry.
Currently, when the above two operations are performed, the code first makes a GET request to _registry_ resource, only to get the id of the resource by its name. It needs the registry id in order to create credential set id which is needed when creating and updating a cache rule. The credential set id can be determined without making the above GET request. This GET request is made on the registry resource, which implies the executing user must have 'Reader' role of the registry. This could lead to user overprivileging roles, …

{ACR} Remove unnecessary network call in `az acr cache` subcommand

---

src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
src/azure-cli/azure/cli/command_modules/rdbms/validators.py

`az postgres flexible-server update`
SSDv2 currently does not support online disk scaling operations which means any disk change operation results in restart. We need to display the restart message to customer both from CLI and Portal for SSDv2.
Find max iops value for ssdv2 server during create/update was being handled incorrectly.
Manual
Warning message:
Range validation fix.
---

{RDBMS} `az postgres flexible-server update`: Show warning for scaling operations on SSDV2 servers and correct validation

---

src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_up_commands.py

az webapp up
Fixes #25882 
azdev test test_webapp_up_dotnet6_e2e --live
---

{App Service} Fix #25882: `az webapp up`: AttributeError: module 'os' has no attribute 'join' in `test_webapp_up_dotnet6_e2e`

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py

az webapp create
Fixes #28374
Improves error message to explain that if the name is not globally unique, the create will fail. Previous error message didn't make this clear if this was the error.
---

[App Service] Fix #28374: `az webapp create`: Improve error message for globally unique name for new app create

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py

az webapp traffic-routing set
Fixes https://github.com/Azure/azure-cli/issues/26285
Host names are truncated based on a character limit. This command forms the hostname, but failed to truncate according to the 40 character limit. 
az webapp traffic-routing set \
--resource-group MyResourceGroup \
--name this-app-service-has-a-name-that-is-too-long  \
--distribution predeploy=0
The `actionHostParameter` should return a truncated value for the app name in the response body.
--- …

{App Service} Fix #26285: `az webapp traffic-routing set`: slot truncation to 40 characters

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py

`az appservice plan create`
Fixes: #28183
az appservice plan create
--location northeurope
--resource-group rg
--name name
--is-linux
--number-of-workers 1
--sku P0V3
--tags workload=infra SLA=full
--debug
---

{App Service} Fix #28183: `az appservice plan create`: Fix warning log for `Readonly attribute name will be ignored in class AppServicePlan`

---

src/azure-cli-core/azure/cli/core/aaz/__init__.py
src/azure-cli-core/azure/cli/core/aaz/_arg.py
src/azure-cli-core/azure/cli/core/aaz/_arg_action.py
src/azure-cli-core/azure/cli/core/aaz/_arg_browser.py
src/azure-cli-core/azure/cli/core/aaz/_arg_fmt.py
src/azure-cli-core/azure/cli/core/aaz/_content_builder.py
src/azure-cli-core/azure/cli/core/aaz/_field_type.py
src/azure-cli-core/azure/cli/core/aaz/_field_value.py
src/azure-cli-core/azure/cli/core/aaz/_help.py
src/azure-cli-core/azure/cli/core/aaz/_utils.py
src/azure-cli-core/azure/cli/core/tests/test_aaz_arg.py
src/azure-cli-core/azure/cli/core/tests/test_aaz_content_builder.py
src/azure-cli-core/azure/cli/core/tests/test_aaz_field.py

This PR add support of `Any` type for aaz commands. The aaz runtime enhanced the shorthand syntax so that the full value can be supported for `Any` type.
The `Any` type is a type allowing a value in `string`, `int`, `float`, `bool`, `list` and `dict`, which are basic types used in json. The `null` value is also accepted for **nullable** `Any` type.
The shorthand syntax will try to convert the input string to possible types, for example `1` will be convert as int type and `false` will be convert as bool type. If you want to input a string of `1`, it can be wrapped in a single quote string. Below are some examples:
- Assign int `1` value
``` bash
az some-command create --any-type-arg 1
az some-command create --any-type-arg "1"
```
- Assign float `1.1` …

[Core] `aaz`: Support `Any` type with full value shorthand syntax allowed

---

src/azure-cli/azure/cli/command_modules/resource/_bicep.py

`az bicep`
If `az bicep` is called by multiple processes or threads the code has a race condition. By simply allowing for the directory to exist, the same behavior as before is achieved without failing in concurrent usages.
---

[ARM] `az bicep`: Fix installation check for concurrent usages

---

src/azure-cli/azure/cli/command_modules/synapse/manual/_client_factory.py
src/azure-cli/azure/cli/command_modules/synapse/tests/latest/recordings/test_spark_job.yaml
src/azure-cli/azure/cli/command_modules/synapse/tests/latest/recordings/test_spark_session_and_statements.yaml
src/azure-cli/azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

update artifact version
Update azure synapse artifact version to 0.20.0
Update azure synapse spark to 0.7.0
---

{Synapse} Update azure synapse artifact version to 0.20.0 and spark to 0.7.0

---

src/azure-cli-core/azure/cli/core/aaz/_arg_action.py
src/azure-cli-core/azure/cli/core/tests/test_aaz_arg.py

This change will convert the `int` number to `float` number when assign to a float type argument for backward compatible with existing behaviors.
---

{core} `aaz`: Fix bug for int value to float value convert

---

.azure-pipelines/templates/azdev_setup.yml

Bypass `disallowed_html_tag_from_command` rule in `Check CLI Linter`
```
-  FAIL - HIGH severity: disallowed_html_tag_from_command
Command: `acr login` - Disallowed html tags ['<registry url>'] in long summary. If content is a placeholder, please remove <> or wrap it with backtick. For more info please refer to: https://review.learn.microsoft.com/en-us/help/platform/validation-ref/disallowed-html-tag?branch=main
Command: `batchai cluster node list` - Disallowed html tags ['<public ip>', '<admin user name>', "<node's SSH port number>"] in long summary. If content is a placeholder, please remove <> or wrap it with backtick. For more info please refer to: https://review.learn.microsoft.com/en-us/help/platform/validation-ref/disallowed-html-tag?branch=main
Command: `batchai …
```

{CI} Pin azdev to 0.1.90

---

src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py

'az aks create/update'
Fix error message when outbound type validation failed. 
update cluster and set vnet_subnet_id with outbound type loadbalancer.
[aks] `az aks`: Fix error message when outbound type validation failed
---

{AKS} Fix outbound type validation error msg

---

scripts/release/pypi/build.sh

The `pypi` build artifact of ec3172dd54637aadb24ab78cdfb7c7b956d26cd2 contains the `post` suffix:
These packages are incorrectly published to PyPI: https://pypi.org/project/azure-cli/2.66.1.post20250227030620/#files
We should not add `post` suffix for branches starting with `release` including `release-lts-2.66`.
Create a new branch `release-lts-2.66-test` and trigger the release pipeline. Make sure the artifacts does not contain `post` suffix.

{LTS} Do not add `post` suffix for branches starting with `release`

---

src/azure-cli/azure/cli/command_modules/rdbms/validators.py

az postgres flexible-server update
Change the error message for SKU name validator
Manual testing
{RDBMS} `az postgres flexible-server create/update`: change the error message for SKU name validator
---

{RDBMS} `az postgres flexible-server create/update`: change the error message for SKU name validator

---

scripts/release/debian/test_deb_package.py
scripts/release/rpm/test_rpm_package.py

In https://github.com/Azure/azure-cli/pull/30238, we upgrade to 4-core agent form 2 core.
Recently, we upgraded to 8-core agent, and pytest has 4 workers.
This PR doubles the number of workers by using logical core instead of physical core.
It saves 5-20% of time.
`Test Rpm Package Azure Linux 3.0 AMD64`  1h 20m 57s -> 1h 10m 39s
`Test Deb Packages Bookworm AMD64` 1h 13m 36s -> 59m 41s
`Test Deb Packages Noble AMD64` 1h 8m 11s -> 1h 5m 2s
`Test Rpm Package Azure Linux 3.0 AMD64` 1h 20m 57s -> 1h 10m 39s

{CI} Increase pytest worker number

---

src/azure-cli/azure/cli/command_modules/role/custom.py

`az role assignment list`
Fix https://github.com/Azure/azure-cli/issues/25078
Currently `--include-inherited` only works for "normal" Azure resource ID, up to tenant level, such as 
```
Tenant scope:           /
Subscription scope:     /subscriptions/00000000-0000-0000-0000-000000000000
Resource group scope:   /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg
```
This reason is explained in https://github.com/Azure/azure-cli/issues/25078#issuecomment-1383604640.
This PR includes role assignments inherited from management groups:
```
Management group scope: /providers/Microsoft.Management/managementGroups/testmg
```
```
az role assignment list --include-inherited
```
The result will now include role assignments like: …

[Role] `az role assignment list`: Include role assignments inherited from management groups

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/auth/constants.py
src/azure-cli-core/azure/cli/core/auth/credential_adaptor.py
src/azure-cli-core/azure/cli/core/auth/identity.py
src/azure-cli-core/azure/cli/core/auth/msal_credentials.py
src/azure-cli-core/azure/cli/core/auth/util.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/azure-cli-testsdk/azure/cli/testsdk/patches.py

This PR mainly changes the functionality and logic of MSAL credentials and `CredentialAdaptor`:
Decouple MSAL credentials from SDK's `get_token` protocol. Make MSAL credentials implement `acquire_token` and return MSAL token `dict`.
`CredentialAdaptor` was initially introduced as an adaptor for both Track 1 and Track 2 SDKs by implementing both `signed_session` and `get_token` protocol. As Track 1 SDK and `signed_session` support has been dropped (https://github.com/Azure/azure-cli/pull/29631), `CredentialAdaptor` is now repurposed as an adaptor between Track 2 SDK and MSAL credentials. So we move `AccessToken`'s building logic to `CredentialAdaptor` and make `CredentialAdaptor` implement `get_token()`.
In the future, `CredentialAdaptor` will be changed to implement the new …

{Core} Decouple MSAL credentials from SDK `get_token` protocol

---

src/azure-cli/azure/cli/command_modules/serviceconnector/_help.py
src/azure-cli/azure/cli/command_modules/serviceconnector/_params.py
src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
src/azure-cli/azure/cli/command_modules/serviceconnector/custom.py
src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_webapp_neon_postgres_e2e.yaml
src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/test_webpp_connection_scenario.py

[ServiceConnector] `az {} connection create neon-postgres`: Add command for Neon Postgres Serverless

---

src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/recordingrules/create.py

```az aks create -n kaveeshcli22 -g kaveeshcli --location westeurope --enable-azure-monitor-metrics --azure-monitor-workspace-resource-id "{full_id}" --grafana-resource-id "{full_id}"```
```az aks create -n kaveeshcli22 -g kaveeshcli --disable-azure-monitor-metrics ```
The recording rules manifest has been updated in TiP and will soon be deployed to production which will include other alerts rule recommendations. I'm updating the CLI code to filter down to the rule groups that the managed prometheus needs for onboarding in this PR.
Scenario 1 : Region where TiP manifest is available
- Enable Microsoft.AlertsManagement/testinproduction in your subscription
- Use the command with and without the azure-monitor-workspace-resource-id …

[AKS] `az aks create/update`: Update recording rule group create logic for managed prometheus addon

---

src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py

az postgres flexible-server replica create
Fix the issue with cross-server resource check
Manual test
{RDBMS} `az postgres flexible-server replica create`: Fix the issue with cross-server resource check
---

{RDBMS} `az postgres flexible-server replica create`: Fix the issue with cross-server resource check

---

src/azure-cli-core/azure/cli/core/tests/test_credential_helper.py
src/azure-cli-core/setup.py

Pick up regex patterns' updates from https://github.com/microsoft/security-utilities/tree/main/GeneratedRegexPatterns
---

{Core} Bump `microsoft-security-utilities-secret-masker` to `1.0.0b4`

---

src/azure-cli-core/azure/cli/core/auth/identity.py

`az login`
Part of #25959
`Identity` will never be used for managed identity authentication, as managed identity inherently differs from user or service principal:
- User or service principal talks to Microsoft Entra eSTS, so it requires an `authority`. Also, because the network request is expensive, a local token cache is used. 
- Managed identity talks to IMDS on the local machine, so no `authority` is required. As IMDS has its own token cache, a local token cache is not necessary.
Of course, it is possible to make `authority` optional and `Identity` work for managed identity, but this requires more effort and blurs `Identity`'s boundary. According to https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-auth-code-flow, the public-facing …

{Auth} Clarify `Identity` class's boundary

---

src/azure-cli/azure/cli/command_modules/role/_params.py

`az ad`
Fix https://github.com/Azure/azure-cli/pull/27296#issuecomment-1878581800
Currently, the global `--subscription` argument is ignored on `az ad` command group (#6516).
When generating reference doc, all `command_loaders` are loaded:
https://github.com/Azure/azure-cli/blob/dc4393dfe5319df8ce4190f12f3f981ff8f49563/src/azure-cli-core/azure/cli/core/__init__.py#L497-L502
If `role` command module is loaded before the `ad` extension, commands under `az ad ds` (https://github.com/Azure/azure-cli-extensions/pull/2842) will not have `--subscription`.
This PR moves `c.ignore('_subscription')` to subgroups to avoid affecting other groups under `az ad`, including `az ad ds`:
```
> az ad -h
...
Subgroups:
app            : Manage Microsoft Entra applications. …
```

{Microsoft Entra ID} `az ad`: Ignore global `--subscription` in subgroups

---

.github/workflows/TriggerReferenceDocsCI.yml

To support LTS package docs auto generation from package release, and make LTS and latest co-exist on Learn site docs reference.
- LTS docs pipeline
- ⁠manually run: use lts-latest branch in azure-cli repo
- ⁠trigger by GitHub package release: use github.event.release.target_commitish branch in azure-cli repo (this branch always starts with "release-lts-")
- production docs pipeline
- ⁠manually run & daily schedule run: use main branch in azure-cli repo
- ⁠trigger by GitHub package release: use github.event.release.target_commitish branch in azure-cli repo (this branch is always "release")
To-do by azure-cli dev: delete secrets.ADO_DocsReference_JumpPipeline_ID, add secrets.ADO_DocsReference_LTS_Pipeline_ID & …

{CI} Use target_commitish branch in release to trigger Reference Docs CI

---

src/azure-cli-core/azure/cli/core/__init__.py

Should be all commands when batch export the help files. Examples: `az acr query`, `az ad ds create`, `az mysql down`.
We found random output of arguments while batch getting help files, it is because of the random sequence of command loaders. 
The random output is introduced by ___for looping a set___, as set in Python is unordered, every execution can lead to different result, and that makes the help files randomly get wrong parameter detail and wrong parameter group info when exporting it in a batch by calling `load_arguments()` in *line 487*. 
After making change to sort the command loader list, the output become steady and correct in my local test. So, we need a steady sequence with the correct order (extension loaders first) here to get a steady …

{Core} Sort command loaders to avoid random diff in docs

---

src/azure-cli-core/azure/cli/core/breaking_change.py

Fix #31047 
This issue is caused by an unverified modification I made while reusing code in Knack. I copied and modified the code, directly using the variable name `command_loader` and appending `cli_ctx.invocation.` before it. However, the correct field name is `commands_loader`. 
In fact, there's no need to use `commands_loader` because we already have `cli_ctx`.
---

{Core} Fix #31047:  Remove unnecessary field get in action retrieval

---

src/azure-cli/azure/cli/command_modules/role/_breaking_change.py
src/azure-cli/azure/cli/command_modules/role/_params.py

`az role assignment list --include-classic-administrators`
Migrate https://github.com/Azure/azure-cli/pull/29404 to the new breaking change announcement framework: https://github.com/Azure/azure-cli/blob/dev/doc/how_to_introduce_breaking_changes.md
```
az role assignment list --include-classic-administrators
az role assignment list -h
```

{Role} `az role assignment list`: Announce `--include-classic-administrators` deprecation breaking change

---

src/azure-cli-core/azure/cli/core/auth/credential_adaptor.py
src/azure-cli-core/azure/cli/core/auth/msal_credentials.py
src/azure-cli-core/azure/cli/core/auth/tests/test_credential_adaptor.py
src/azure-cli-core/azure/cli/core/auth/util.py

`az login`
Require https://github.com/Azure/azure-cli/issues/29955
Close https://github.com/Azure/azure-cli/issues/29967
Support the new `get_token_info` protocol introduced by `azure-core` 1.31.0 (https://github.com/Azure/azure-sdk-for-python/pull/36565).
`azure-core` was bumped to 1.31.0 in #29944.

{Auth} Support `get_token_info` protocol

---

src/azure-cli/azure/cli/command_modules/acs/_breaking_change.py

az aks create
This PR introduces an announcement for breaking changes in az aks create. The default value of --node-vm-size will be changing from 'Standard_DS2_V2 (Linux), Standard_DS2_V3 (Windows)' to being dynamically selected by the AKS resource provider based on quota and capacity.
Behavior is not changed
---
- [ x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).
- [ x] I adhere to the …

{AKS} `az aks create`: Add upcoming breaking change announcement

---

src/azure-cli-core/azure/cli/core/util.py

Patch the missing part of dropping `msrestazure`.
See https://github.com/Azure/azure-cli/pull/29856#issuecomment-2735157157
`msrestazure.azure_exceptions.CloudError` is used by track1 SDK.
The alternative for track2 SDK is `azure.core.exceptions.HttpResponseError`.
After all modules migrated to track2 SDK, the error handling function `empty_on_404` in cli core should also be migrated
---

{Core} Migrate `empty_on_404` from track1 `CloudError` to track2 `HttpResponseError`

---

src/azure-cli/azure/cli/command_modules/resource/_bicep.py
src/azure-cli/azure/cli/command_modules/resource/_bicep_config.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_bicep.py

- `az deployment`
- `az stack`
- `az bicep`
This PR resolves two issues affecting the az deployment, az stack, and az bicep commands:
- The commands sometimes incorrectly check for the latest Bicep version, even when `use_binary_from_path` is set to `true` and `check_version` is `false`.
- On aarch64 architecture, the `bicep install/upgrade` command downloads the x64 binary instead of the ARM binary.
Closes https://github.com/Azure/azure-cli/issues/29809.
Closes https://github.com/Azure/azure-cli/issues/29435.
- Run `az deployment tenant/mg/sub/group create` with a `.bicepparam` file.
- Run `bicep install/upgrade` on an aarch64 machine.
[ARM] Fix #29809: `az deployment` / `az stack` / `az bicep`: Fix an issue where …

[ARM] Fix various issues with `az bicep`

---

src/azure-cli/azure/cli/command_modules/aro/custom.py

`az aro create`
This PR updates the **VM SKU** for Azure Red Hat OpenShift (ARO) in accordance with the Upstream CLI v5 default changes. This aligns with the latest recommended defaults for performance and stability.
**What Changed?**
- Modified custom.py to update the SKU in the ARO create command.
- Ensured compatibility with existing configurations.
**Effect of Changes**
- New ARO clusters will use the updated VM SKU.
- No breaking changes for existing users.**Testing Guide**
[ARO] `az aro create`: Update VM SKU to align with best practices
---

[ARO] `az aro create`: Update VM SKU to align with best practices

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli/azure/cli/command_modules/profile/_breaking_change.py
src/azure-cli/azure/cli/command_modules/profile/custom.py

`az login --identity --username`
Migrate #30525 to the new breaking change announcement framework: https://github.com/Azure/azure-cli/blob/dev/doc/how_to_introduce_breaking_changes.md
```
az login --identity --username 111
```

{Profile} `az login`: Announce `--username` breaking change for managed identity

---

src/azure-cli/azure/cli/command_modules/cloud/_breaking_change.py
src/azure-cli/azure/cli/command_modules/cloud/custom.py

[Cloud] `az cloud register/update`: Add upcoming breaking change announcement

---

src/azure-cli/azure/cli/command_modules/acs/_consts.py
src/azure-cli/azure/cli/command_modules/acs/_help.py
src/azure-cli/azure/cli/command_modules/acs/_params.py
src/azure-cli/azure/cli/command_modules/acs/_validators.py
src/azure-cli/azure/cli/command_modules/acs/custom.py
src/azure-cli/azure/cli/command_modules/acs/linter_exclusions.yml
src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_network_isolated_cluster.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py

`az aks create/update`
This PR is to add command to create/update a [network isolated cluster](https://learn.microsoft.com/en-us/azure/aks/concepts-network-isolated).
The newly added parameters are bootstrap profile and outbound type none.
- `bootstrap_artifact_source`
- `bootstrap_container_registry_resource_id`
- the enum value `none` for `outbound_type`
[AKS] `az aks create/update`: Add `--bootstrap-artifact-source` parameter to configure artifact source when bootstraping the cluster
[AKS] `az aks create/update`: Add `--bootstrap-container-registry-resource-id` parameter to configure container registry resource ID
[AKS] `az aks create/update`: Add new option `none` for `--outbound-type` parameter
---
This checklist …

[AKS] `az aks create/update`: Add command to create/update a network isolated cluster

---

src/azure-cli/azure/cli/command_modules/mysql/_breaking_change.py
src/azure-cli/azure/cli/command_modules/mysql/custom.py

mysql flexible-server create
mysql flexible-server update
---

{MYSQL} Remove parameter restriction for `--high-availability` and add breaking change annoucement

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py

az webapp config appsetting set
az webapp config connection-string set
az webapp config container set
az webapp config set
and similar functionapp commands
Fixes #27724 
Run any of the above commands and the warning message "App settings have been redacted. Use..." will no longer appear in the output.
---

[App Service] Fix: #27724: `az webapp config appsettings set`: Remove redaction warning message from output

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_slot_clone.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

[App Service] Fix #26920: `az webapp deployment slot create`: Make the command consistent with the portal behavior

---

src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/test_appconfig_aad_auth.py

Fix https://github.com/Azure/azure-cli/pull/30983#discussion_r2009667404
These 2 tests from #30983 are incorrect as they should not assume the credential type. It is Azure CLI Core's internal implementation. Azure CLI Core only guarantees `get_token` is implemented. 
`test_azconfig_mi_token_override` blocks https://github.com/Azure/azure-cli/pull/31092 as `cli_ctx` is a `mock.MagicMock()`, forcing `cli_ctx.config.getboolean('core', 'use_msal_managed_identity', fallback=False)` to be a `MagicMock` (`True`). In this case, a `CredentialAdaptor` is returned, instead of `MSIAuthenticationWrapper`.

{Appconfig} Disable incorrect test cases

---

src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/afd/endpoint/_purge.py
src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/afd/origin/_create.py
src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/afd/origin_group/_create.py
src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/afd/rule/_list.py

Fix https://github.com/azure/azure-cli/issues/30585 by deleting the spam message in the example CLI.
and https://github.com/azure/azure-cli/issues/30586 by add examples with --enable-health-probe true

{afd} `az afd origin create` clean spam message, `az afd origin-group create` add `--enable-health-probe true`

---

src/azure-cli/azure/cli/command_modules/storage/_params.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_file_share_premium_scenario.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_file_share_scenarios.py

Add `--enable-snapshot-virtual-directory-access` to `az storage share create`
[Storage] `az storage share create`: Support `--enable-snapshot-virtual-directory-access`
---

[Storage] `az storage share create`: Support `--enable-snapshot-virtual-directory-access`

---

src/azure-cli/azure/cli/command_modules/appservice/_params.py
src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py

az functionapp list-flexconsumption-locations
Add --details and --runtime parameter to az functionapp list-flexconsumption-locations. The --details parameter will provide more details about the locations including the supported runtimes, and the --runtime parameter will filter the locations based on the runtime.
- az functionapp list-flexconsumption-locations --details
- az functionapp list-flexconsumption-locations --runtime java --details
---

[App Service] `az functionapp list-flexconsumption-locations`: Add `--details` and `--runtime` parameters to provide more details

---

.azure-pipelines/templates/variables.yml
azure-pipelines.yml

Partially revert https://github.com/Azure/azure-cli/pull/30996.
Arm agent raises `docker: Error response from daemon: open /sys/fs/cgroup/user.slice/user-1000.slice/cgroup.controllers: no such file or directory` when run docker command. Revert to Ubuntu 20.04 to unblock release.
Ref: https://dev.azure.com/azclitools/public/_build/results?buildId=230090&view=logs&jobId=f970374f-0f25-5e15-cb2e-539daf27ea54&j=f970374f-0f25-5e15-cb2e-539daf27ea54&t=04e949c8-23b2-574b-c689-3d7f03b1f36c

{CI} Revert to Ubuntu 20.04 on ARM agent

---

scripts/ci/credscan/CredScanSuppressions.json

Credential Scanner raises
```
##[error]1. Credential Scanner Error CSCAN-GENERAL0030 - File: src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py:src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py. Line: 193. Column 3. 
Signature: 4437f095d08224d8fa3ba459bdf3c04eda1552b093c54217622502e91385ca39
Tool: Credential Scanner: Rule: CSCAN-GENERAL0030 (User Login Credentials). https://aka.ms/credscan
A potential secret was detected in 'flexible_server_custom_postgres.py':(CSCAN-GENERAL0030 User Login Credentials) Validate file contains secrets, remove, roll credential, and use approved store. For additional information on secret remediation see https://aka.ms/credscan.
```
This seems to be a false positive. This line does …

{CI} Add exception in Credential Scanner

---

src/azure-cli-core/setup.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

Pick up MSAL 1.32.0: https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/799
The most valuable change is the resurrection of https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/754 by https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/795.
Managed identity can again be tested on a local machine through port mapping:
```sh
ssh -L 8000:169.254.169.254:80 -o "StrictHostKeyChecking no" $username@$ip
export AZURE_POD_IDENTITY_AUTHORITY_HOST=http://localhost:8000 
az login --identity
```

{Core} Bump MSAL to 1.32.0

---

src/azure-cli/azure/cli/command_modules/aro/custom.py

`az aro update`
The current implementation of the `ensure_resource_permissions` function, called during `az aro create` and `az aro update --refresh-credentials`, and which is responsible for ensuring an ARO cluster's service principal has the required permissions over the cluster's network resources (vnet, subnet, route tables, NAT Gateways, NSGs), has a bug where if a cluster was either created with a specific subnet provided for the worker nodes that has since been deleted, or the cluster currently has an invalid machineset pointing to a nonexistent subnet (e.g. following the instructions in https://learn.microsoft.com/en-us/azure/openshift/howto-segregate-machinesets incorrectly), we will fail to ensure the required resource permissions over this …

[ARO] `az aro update`: Fix update for clusters created with subnets that are now deleted 

---

src/azure-cli/azure/cli/command_modules/network/azure_stack/zone_file/parse_zone_file.py
src/azure-cli/azure/cli/command_modules/network/zone_file/parse_zone_file.py

ERROR: /mnt/vss/_work/1/s/src/azure-cli/azure/cli/command_modules/network/azure_stack/zone_file/parse_zone_file.py:292:5: F824 `global SUPPORTED_RECORDS` is unused: name is never assigned in scope
/mnt/vss/_work/1/s/src/azure-cli/azure/cli/command_modules/network/azure_stack/zone_file/parse_zone_file.py:292:5: F824 `global SUPPORTED_RECORDS` is unused: name is never assigned in scope
/mnt/vss/_work/1/s/src/azure-cli/azure/cli/command_modules/network/zone_file/parse_zone_file.py:296:5: F824 `global SUPPORTED_RECORDS` is unused: name is never assigned in scope
/mnt/vss/_work/1/s/src/azure-cli/azure/cli/command_modules/network/zone_file/parse_zone_file.py:296:5: F824 `global SUPPORTED_RECORDS` is unused: name is never assigned in scope
4     F824 `global …

{CI} Remove unused globals

---

src/azure-cli-core/azure/cli/core/_breaking_change.py
src/azure-cli-core/azure/cli/core/cloud.py

The following warning messages will be displayed when using azure-stack profiles:
---

{Core} Add breaking change warning for azure stack users

---

src/azure-cli/azure/cli/command_modules/network/_breaking_change.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet/subnet/_create.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet/subnet/_update.py

{Network} `az network vnet subnet`: Update the short summary of `--default-outbound-access`

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/telemetry.py

`az login`
Add telemetry for `use_msal_managed_identity` (https://github.com/Azure/azure-cli/pull/31092).
```
az config set core.use_msal_managed_identity=true
az login --identity
```

{Auth} Add telemetry for `use_msal_managed_identity`

---

src/azure-cli/azure/cli/command_modules/acr/_utils.py
src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_task.yaml
src/azure-cli/azure/cli/command_modules/acr/tests/latest/taskfilesample.yaml
src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_task_commands.py

`az acr task show`
This pr removes the added version line to a file created encoded tasks.
fix #31130 
Create a file created encoded task and run
`az acr task show -n <TaskName>-r <ResourceGroup> --query step.encodedTaskContent -o tsv | base64 --decode`
no extra version line added.
---

[ACR] Fix #31130: Fix extra version line in encodedTask created by file

---

src/azure-cli/azure/cli/command_modules/vm/aaz/latest/sig/image_version/_create.py
src/azure-cli/azure/cli/command_modules/vm/aaz/latest/sig/image_version/_update.py
src/azure-cli/azure/cli/command_modules/vm/custom.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_image_version_vhd.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_image_version_create_os_vhd.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

`az sig image-version create`
Close: #30942
There's an email for "Upcoming Breaking Changes to Azure Compute Gallery Image Publishing".
> If you use blobs as source to create ACG Image versions:
> If you're using the old property ‘properties.storageProfile.[osDiskImage/dataDiskImages].source.Id,‘ you should move to the property ’properties.storageProfile.osDiskImage.source.storageAccountId’. This property requires minimum api-version 2022-03-03.
aaz PR: https://github.com/Azure/aaz/pull/733
[Compute] BREAKING CHANGE: `az sig image-version`: Change the `--os-vhd-storage-account` parameter mapping to the `properties.storageProfile.osDiskImage.source.storageAccountId` property
[Compute] BREAKING CHANGE: `az sig …

[Compute] BREAKING CHANGE: `az sig image-version create`: Move to new properties

---

src/azure-cli/azure/cli/command_modules/resource/_bicep.py
src/azure-cli/azure/cli/command_modules/resource/custom.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_bicep.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_custom.py

My previous PR (https://github.com/Azure/azure-cli/pull/31041) fixed several Bicep-related issues but uncovered another: when verifying if certain Bicep features are supported by the installed version, Azure CLI incorrectly uses the binary from its cache folder, even when it's configured to use the one on the system path in an CI environment. This PR fixes that behavior.
Run `az deployment group create -f main.bicep ...` in an ADO pipeline.
---

[ARM] `az deployment`: Fix issue where Bicep is not found in CI environments

---

src/azure-cli-core/azure/cli/core/auth/identity.py

`az login`
MSAL  hides the original `AADSTS` error when WAM is used (https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/698).
This PR uses `enable_pii_log` from https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/590 to print the original `AADSTS` error.
~We should carefully inspect that no PII is sent to the telemetry before merging this PR.~
As confirmed by MSAL (https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/590#issuecomment-2113956923), `enable_pii_log` only affects logs, not telemetry. In other words, the telemetry will not contain PII even when `enable_pii_log` is set to `True`.
Before:
```
> az login --scope https://graph.microsoft.com/User.ReadWrite …
```

{Auth} Enable PII log for WAM

---

src/azure-cli/azure/cli/command_modules/role/_help.py
src/azure-cli/azure/cli/command_modules/role/_params.py
src/azure-cli/azure/cli/command_modules/role/custom.py
src/azure-cli/azure/cli/command_modules/role/tests/latest/recordings/test_role_assignment_no_graph.yaml
src/azure-cli/azure/cli/command_modules/role/tests/latest/test_role.py

`az role assignment list`
`az role assignment delete`
Close https://github.com/Azure/azure-cli/issues/30436
Fix #20349, #30428
With more encouragement on managed identity and more strict permission/access control, supporting `--assignee-object-id` to bypass Graph query is a necessary feature for role assignment’s management experience.
Similar to https://github.com/Azure/azure-cli/pull/5273 which added `--assignee-object-id` to `az role assignment create` to bypass Graph query, this PR adds `--assignee-object-id` to `az role assignment list/delete`.
```
az role assignment list --assignee
az role assignment list --assignee-object-id
az role assignment delete --assignee
az role assignment delete --assignee-object-id
``` …

[Role] `az role assignment list/delete`: Add `--assignee-object-id`

---

src/azure-cli/azure/cli/command_modules/role/_help.py
src/azure-cli/azure/cli/command_modules/role/_params.py
src/azure-cli/azure/cli/command_modules/role/custom.py
src/azure-cli/azure/cli/command_modules/role/tests/latest/recordings/test_create_for_rbac_no_password.yaml
src/azure-cli/azure/cli/command_modules/role/tests/latest/test_role.py

`az ad sp create-for-rbac` fails in Microsoft tenant:
```
> az ad sp create-for-rbac
Credential type not allowed as per assigned policy '538f1913-366a-440a-95a0-e195cb55b282'.
```
This PR adds `--create-password` argument to disable creating password credential.
```
az ad sp create-for-rbac --create-password false
```
[Microsoft Entra ID] `az ad sp create-for-rbac`: Add `--create-password` argument. Use `--create-password false` to disable creating password credential

[Microsoft Entra ID] `az ad sp create-for-rbac`: Add `--create-password` argument

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py

az webapp config storage-account add
Validation was added Fix #21721, however this validation doesn't work as intended so removing it until this can be further investigated. There's commentary in #30990 that explains the issues and why this change needs to be rolled back.
 
az webapp config storage-account add -g <RESSOURCE_GROUP_NAME> -n <APP_SERVICE_NAME> --custom-id "test-az-cli" --storage-type AzureFiles --account-name <STORAGE_ACCOUNT_NAME> --share-name <FILE_SHARE_NAME> --access-key <STORAGE_ACCOUNT_ACCESS_KEY> --mount-path <MOUNT_PATH_ON_APP_SERVICE_FS>
[Component Name 2] `az command b`: Add some customer-facing …

{App Service} `az webapp config storage-account add`: Remove FileShare validation

---

src/azure-cli/azure/cli/command_modules/resource/custom.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_lock_with_namespace.yaml
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_locks.py

`az lock delete`
'az lock delete' is exhibiting inconsistent behavior regarding the case sensitivity of the namespace
close https://github.com/Azure/azure-cli/issues/31188
---

[ARM] Fix issue #31188: `az lock delete`: Fix the case sensitivity of `--namespace` parameter validation

---

src/azure-cli/azure/cli/command_modules/vm/_params.py
src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
src/azure-cli/azure/cli/command_modules/vm/custom.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_placement.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

`az vm create/update`
Add placement (AnyZone) support CLI
close https://github.com/Azure/azure-cli/issues/30826
[Compute] `az vm create`: Add new parameter `--zone-placement-policy` to support setting vm placement to create a zonal VM
[Compute] `az vm create`: Add new parameter `--include-zones` to support setting vm placement to create a zonal VM
[Compute] `az vm create`: Add new parameter `--exclude-zones` to support setting vm placement to create a zonal VM
[Compute] `az vm create/update`: Add new parameter `--align-regional-disks-to-vm-zone` to support setting regional disks attached to the VM to be converted to zonal
---

[Compute] `az vm create`: Add new parameter `--zone-placement-policy` to support setting vm placement to create a zonal VM

---

src/azure-cli/azure/cli/command_modules/vm/_help.py
src/azure-cli/azure/cli/command_modules/vm/_params.py
src/azure-cli/azure/cli/command_modules/vm/linter_exclusions.yml

`az sig image-version create/update`
Mail: Request to support "blockDeletionBeforeEndOfLife" via CLI
Rename the shorter alias for `--block-deletion-before-end-of-life` parameter to `--block-delete-before-eol`
---

[Compute] `az sig image-version create/update`: Rename shorter alias for `--block-deletion-before-end-of-life` parameter

---

.github/actions/env-setup/action.yml
.github/workflows/AzdevLinter.yml
.github/workflows/AzdevStyle.yml

Add `azdev style & linter` task into github workflow, with no dependency on token or pr write permission.
Test pr: https://github.com/AllyW/azure-cli/pull/2
---

{CI} Add github workflows for `azdev style & linter`

---

src/azure-cli/azure/cli/command_modules/serviceconnector/_help.py

az webapp/containerapp/spring connection create <target-service> -h
As stated in https://github.com/azure/azure-cli/issues/30896, `--system-identity` help description is not clear enough that it is used as a flag
az webapp connection create storage-blob -h
---

[Service Connector] `az webapp connection create -h`: Clarify that system identity is a flag

---

src/azure-cli-testsdk/azure/cli/testsdk/base.py
src/azure-cli-testsdk/azure/cli/testsdk/utilities.py
src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_private_endpoint_connection.yaml

During recording tests, we may unintentionally record real email addresses in recording yaml files. This PR adds EmailAddressReplacer for ScenarioTests during live run to replace all microsoft email addresses with test@example.com
Please note that this replacer will only work during live run, so no existing recording files will be affected
See the new test recording file `test_keyvault_private_endpoint_connection.yaml` in commit
To try by yourself, run `azdev test $TEST_NAME --live` with any test that may record real email address and see the new recording file
[Component Name 2] `az command b`: Add some customer-facing …

{Test} Add email replacer for cli scenario test

---

src/azure-cli/azure/cli/command_modules/consumption/custom.py

Handle None UsageStart in consumption usage list and exclude from results
`az consumption usage list`: Enhanced handling of `usageStart` and `usageEnd` in `custom.py`:
- Updated `_output` function from `result = list([transform_usage_output(item) for item in result])` to `result = list(filter(None, [transform_usage_output(item) for item in result]))` to exclude `None` values returned by `transform_usage_output`.
- Modified `transform_usage_output` function to:
- Use `result.get('usageStart', None)` and `result.get('usageEnd', None)` for safe attribute access.
- Add conditional check `if usageStart and usageEnd` to return `None` if either is missing, ensuring invalid entries are filtered out.
- Format valid `usageStart` and `usageEnd` to ISO 8601 strings (e.g., …

[Consumption] `az consumption usage list`: Enhanced handling of `usageStart` and `usageEnd` when missing

---

src/azure-cli/azure/cli/__main__.py

Fix #20473
The full error is 
```
File "C:\Users\kk\Developer\azure-cli\src\azure-cli\azure\cli\__main__.py", line 84, in <module>
if parse(VERSIONS['versions']['core']['local']) < parse(VERSIONS['versions']['core']['pypi']):  # pylint: disable=line-too-long
KeyError: 'pypi'
```
So it's easy to fix. But the cause is pretty tricky.
CLI gets latest version from GitHub.
https://github.com/Azure/azure-cli/blob/57577782547064257d69da916683a46e7c25e1af/src/azure-cli-core/azure/cli/core/util.py#L316-L330
`pypi` is added in line 327. If `check_connectivity` or `get_latest_from_github` fails, this key does not exist.
A wrong `~/.azure/versionCheck.json` is also generated with this content:
`{"versions": {"azure-cli": {"local": "2.47.0"}, "core": …

{Upgrade} Fix KeyError: 'pypi' when auto upgrade

---

src/azure-cli/azure/cli/command_modules/profile/custom.py

`az login`
Show different ROPC flow warning messages in different clouds.
Azure Public:
> Starting July 01, 2025, MFA will be gradually enforced for Azure public cloud. The authentication with username and password in the command line is not supported with MFA. Consider using one of the compatible authentication methods. For more details,  see https://go.microsoft.com/fwlink/?linkid=2276314
Other clouds:
> Using authentication with username and password in the command line is strongly discouraged. Consider using one of the recommended authentication methods. For more details, see https://go.microsoft.com/fwlink/?linkid=2276314
```
> az cloud set --name azurecloud
> az login --username xxx --password xxx
Starting July 01, 2025, MFA will …
```

{Profile} Show different ROPC flow warning messages in different clouds

---

linter_exclusions.yml
src/azure-cli-core/azure/cli/core/profiles/_shared.py
src/azure-cli/azure/cli/command_modules/role/_breaking_change.py
src/azure-cli/azure/cli/command_modules/role/_help.py
src/azure-cli/azure/cli/command_modules/role/_params.py
src/azure-cli/azure/cli/command_modules/role/custom.py
src/azure-cli/azure/cli/command_modules/role/tests/latest/test_role.py

`az role assignment list`
Close https://github.com/Azure/azure-cli/issues/27199
https://github.com/Azure/azure-cli/pull/29404 added deprecation message for `--include-classic-administrators`. This PR drops `--include-classic-administrators` argument.
```
az role assignment list -h
az role assignment list --include-classic-administrators
```

[BREAKING CHANGE] `az role assignment list`: Drop `--include-classic-administrators` argument

---

azure-pipelines.yml
scripts/release/rpm/azure-cli.spec
scripts/release/rpm/test_rpm_in_docker.sh
scripts/release/rpm/ubi.dockerfile

This PR bumps the Python dependency to 3.12. **Some extensions may need to be reinstalled if they become non-functional**: `az extension remove -n xxx && az extension add -n xxx`
After this PR, Mariner 2.0 is the only one relies on Python 3.9, the rest of the distros use 3.12.

[Packaging] Bump Python to 3.12 on RHEL and CentOS Stream

---

azure-pipelines.yml

Similar to https://github.com/Azure/azure-cli/pull/28942
Ubuntu 20.04 will reach its EOL in May 2025, and our next release is also in May.
Ref: https://wiki.ubuntu.com/Releases
PS: ADO is retiring it earlier:
> The Ubuntu-20.04 retirement date for Microsoft-hosted agents has been moved to **April 15**.
-- https://devblogs.microsoft.com/devops/upcoming-updates-for-azure-pipelines-agents-images/#ubuntu

[Packaging] Drop Ubuntu 20.04 support

---

linter_exclusions.yml
src/azure-cli/azure/cli/command_modules/role/_params.py
src/azure-cli/azure/cli/command_modules/role/linter_exclusions.yml

`az role`
`az ad`
Clean up linter exclusion rules.

{Role} Clean up linter exclusion rules

---

src/azure-cli/azure/cli/command_modules/storage/_help.py

{storage} `az storage`: Drop examples for azure stack profiles

---

src/azure-cli/azure/cli/command_modules/rdbms/_params.py
src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands.py

Set the default value of parameter `--create-default-database` to Disabled
Manual testing
[RDBMS] BREAKING CHANGE: `az postgres flexible-server create`: Set the default value of parameter `--create-default-database` to Disabled
---

[RDBMS] BREAKING CHANGE: `az postgres flexible-server create`: Set the default value of parameter `--create-default-database` to Disabled

---

src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

Close https://github.com/Azure/azure-cli/issues/31322
---

{Packaging} Bump `azure-mgmt-core` to 1.5.0

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py

`az login`
Close #25860, #22677
https://github.com/Azure/azure-cli/pull/31092 added support for MSAL managed identity. It can be opted in by setting `core.use_msal_managed_identity=true` config option.
This PR makes `core.use_msal_managed_identity=true` the default, but `core.use_msal_managed_identity` is kept so that it is possible to revert to the old `msrestazure` implementation by setting `core.use_msal_managed_identity=false`.
```sh
az login --identity
az login --identity --client-id xxx
az login --identity --object-id xxx
az login --identity --resource-id /subscriptions/xxx/resourcegroupsxxx/providers/microsoft.managedidentity/userassignedidentities/xxx
az group list
az account get-access-token
```
[Core] Use …

[Core] Use MSAL for managed identity authentication

---

src/azure-cli/azure/cli/command_modules/vm/_params.py
src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
src/azure-cli/azure/cli/command_modules/vm/custom.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_with_automatic_zone_rebalancing_policy.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

`az vmss create/update`
support VMSS auto balance policy
close https://github.com/Azure/azure-cli/issues/31163
[Compute] `az vmss create/update`: Add new parameters `--enable-automatic-zone-balancing` to support setting automatic zone rebalancing policy
[Compute] `az vmss create/update`: Add new parameters `--automatic-zone-balancing-strategy` to support setting automatic zone rebalancing policy
[Compute] `az vmss create/update`: Add new parameters `--automatic-zone-balancing-behavior` to support setting automatic zone rebalancing policy
---

[Compute] `az vmss create/update`: Add new parameters `--enable-automatic-zone-balancing` to support setting automatic zone rebalancing policy

---

src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet/_create.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet/_list.py
src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet/_update.py
src/azure-cli/azure/cli/command_modules/network/custom.py

`az network vnet update`
Fix https://github.com/Azure/azure-cli/issues/31294
Ignore address prefixes as an empty array only when ipam pool has non-empty value.
aaz https://github.com/Azure/aaz/pull/747
---

[Network] Fix #31294: `az network vnet update`: Refine processing logic of `--address-prefixes`

---

src/azure-cli-core/azure/cli/core/cloud.py

Part of https://github.com/Azure/azure-cli/pull/31307
Only show messages and apply the latest profile fix when the active cloud profile is azure stack profiles.
---

{core} Fix warning message display issue

---

src/azure-cli-core/azure/cli/core/tests/test_credential_helper.py
src/azure-cli-core/setup.py

Backport #30993
<details>
<summary>CI Log</summary>
```
2025-04-27T09:22:37.8305256Z ____________ TestCredentialHelper.test_redact_credential_for_string ____________
2025-04-27T09:22:37.8305565Z self = <azure.cli.core.tests.test_credential_helper.TestCredentialHelper testMethod=test_redact_credential_for_string>
2025-04-27T09:22:37.8305723Z 
2025-04-27T09:22:37.8305884Z     def test_redact_credential_for_string(self):
2025-04-27T09:22:37.8306156Z         with mock.patch('azure.cli.core.credential_helper.get_secret_masker', side_effect=self._get_test_secret_masker):
2025-04-27T09:22:37.8306450Z             creation_time = '2024-03-07T02:50:56.464790+00:00'
2025-04-27T09:22:37.8306688Z >           result = redact_credential_for_string(creation_time) …
```

{LTS} Backport #30993

---

src/azure-cli/azure/cli/command_modules/network/azure_stack/zone_file/parse_zone_file.py
src/azure-cli/azure/cli/command_modules/network/zone_file/parse_zone_file.py

{LTS} Backport #31159

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py

az functionapp plan update
Updating `az functionapp plan update` to add support to update zone redundant for Flex apps.
1. az functionapp create -g [rg] -n [name] -s [storage-account-name] --functions-version 4 --runtime python --runtime-version 3.11 --flexconsumption-location eastasia
1. az functionapp plan update --id [planid]  --set zoneRedundant=true
---

[App Service] `az functionapp plan update`: Add zone redundant update support for Flex

---

src/azure-cli/azure/cli/command_modules/serviceconnector/_help.py
src/azure-cli/azure/cli/command_modules/serviceconnector/_params.py
src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
src/azure-cli/azure/cli/command_modules/serviceconnector/_validators.py
src/azure-cli/azure/cli/command_modules/serviceconnector/action.py
src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_webapp_mongodb_atlas_e2e.yaml
src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/test_webpp_connection_scenario.py

az webapp connection create mongodb-atlas --secret secret=xxx
add mongodb-atlas target service support in service connector
az webapp connection create mongodb-atlas --secret secret=xxx
---

[Service Connector] `az webapp connection create mongodb-atlas`

---

src/azure-cli/azure/cli/command_modules/netappfiles/custom.py

[NetAppFiles] remove breaking changes properties

---

src/azure-cli/azure/cli/command_modules/dms/_help.py
src/azure-cli/azure/cli/command_modules/dms/scenario_inputs.py

az dms project task create ...
Our team has enabled a different way to enable consistency for migrations using the lockless method. This change removes the CLI default of setting consistent snapshot as the default method for enabling consistency and adds the ability to also set the lockless option.
az dms project task create ... --database-options-json file.json
where file.json contains:
```
{
"selected_databases": [...],
"enable_consistent_backup_without_locks": "true"
}
```
---

[DMS] `az dms project task create`: Add ability to use a lockless option for ensuring data consistency

---

src/azure-cli-core/azure/cli/core/auth/msal_credentials.py

`az ssh vm`
Fix #30519
When supporting WAM (#23828), interactive re-authentication was not included.
When getting SSH certificate requires step-up, CLI fails with
```
ValueError: parent_window_handle is required when you opted into using broker. You need to provide the window
handle of your GUI application, or use msal.PublicClientApplication.CONSOLE_WINDOW_HANDLE when and only when
your application is a console app.
```
This PR sets `parent_window_handle` during interactive re-authentication so that it can work with WAM too.
`az ssh vm`
To directly trigger interactive re-authentication, replace L56~L57
```py
result = self._msal_app.acquire_token_silent_with_error(
scopes, self._account, claims_challenge=claims_challenge, **kwargs)
``` …

{Auth} Support interactive re-authentication with WAM

---

src/azure-cli/azure/cli/command_modules/appservice/_help.py
src/azure-cli/azure/cli/command_modules/appservice/_params.py
src/azure-cli/azure/cli/command_modules/appservice/_validators.py
src/azure-cli/azure/cli/command_modules/appservice/appservice_environment.py
src/azure-cli/azure/cli/command_modules/appservice/commands.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_app_service_environment_commands_thru_mock.py
src/azure-cli/azure/cli/command_modules/appservice/utils.py

`az appservice ase`
The PR is removing support for ASEv2 as it has been deprecated and all instances have been removed world wide. The PR removes the command support, cleans up code and updates help text to reflect the change.
[App Service] BREAKING CHANGE: `az appservcie ase create/update/delete`: Remove support for ASEv2
---

[App Service] BREAKING CHANGE: Remove support for ASEv2

---

src/azure-cli/azure/cli/command_modules/acr/_params.py

az acr create --allow-trusted-services
az acr update --allow-trusted-services
remove preview flag from `--allow-trusted-services` in `az acr create` and `az acr update` commands
az acr create --help 
az acr update --help
[ACR] `az acr create`: Remove preview flag from `--allow-trusted-services`
---

[ACR] `az acr create`: Remove preview flag from `--allow-trusted-services`

---

build_scripts/windows/scripts/build.cmd
scripts/release/debian/build.sh

Bump embedded Python to 3.12.10: https://docs.python.org/release/3.12.10/whatsnew/changelog.html#python-3-12-10
One of the important changes is:
> [gh-131423](https://github.com/python/cpython/issues/131423): Update bundled version of OpenSSL to 3.0.16.
According to https://github.com/openssl/openssl/releases/tag/openssl-3.0.16
> - Fixed timing side-channel in ECDSA signature computation. ([CVE-2024-13176](https://www.openssl.org/news/vulnerabilities.html#CVE-2024-13176))
> - Fixed possible OOB memory access with invalid low-level GF(2^m) elliptic curve parameters. ([CVE-2024-9143](https://www.openssl.org/news/vulnerabilities.html#CVE-2024-9143))
[Core] Resolve CVE-2024-13176
[Core] Resolve CVE-2024-9143

{Packaging} Bump embedded Python to 3.12.10

---

src/azure-cli-core/azure/cli/core/profiles/_shared.py
src/azure-cli/azure/cli/command_modules/keyvault/_client_factory.py
src/azure-cli/azure/cli/command_modules/keyvault/_completers.py
src/azure-cli/azure/cli/command_modules/keyvault/_params.py
src/azure-cli/azure/cli/command_modules/keyvault/commands.py
src/azure-cli/azure/cli/command_modules/keyvault/custom.py

`az keyvault`
Since we have dropped azure stack profiles in https://github.com/Azure/azure-cli/pull/31307, we should also clear the logic for azure stack handling in Keyvault module
---

{Keyvault} Remove azure stack logic

---

src/azure-cli/azure/cli/command_modules/mysql/custom.py

[Mysql] `az mysql flexible-server create`: Change default storage redundancy for BC SKU to local redundancy
---

[Mysql] `az mysql flexible-server create`: Change default storage redundancy for BC SKU to local redundancy

---

src/azure-cli/azure/cli/command_modules/acs/_help.py

xref: https://github.com/Azure/AKS/issues/4897
Fixed help text inaccuracies with defaults and updated longer summary text to reflect current CNI options
`--network-plugin` no longer defaults to kubenet
[AKS] `--network-plugin`: Update longer summary to show "azure" is default instead of kubenet
---

[AKS] Update network plugin defaults and long summary

---

src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

Close https://github.com/Azure/azure-cli/issues/31519
`semver` was pinned to `2.13.0` by https://github.com/Azure/azure-cli/pull/16857. [`2.13.0`](https://pypi.org/project/semver/2.13.0/) was released 5 years ago.

{Packaging} Bump `semver` to 3.0.4

---

src/azure-cli/azure/cli/command_modules/batch/_help.py

[Batch] `az batch`: Add some new command examples

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py

az webapp set config -n -g --number-of-workers
Client side validation is not needed, this is handled by ARM.
az webapp set config -n -g --number-of-workers
Previously, this limited you to 20 workers. You can now request as many as needed and if the request is not supported, ARM will handle validation and error message.
---

[App Service] `az webapp config set`: Remove number of workers validation

---

src/azure-cli/azure/cli/command_modules/netappfiles/custom.py
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_create_get_list_delete_volume_group.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_oracle_volume_groups.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/test_volumegroup_commands.py

az netappfiles volume-group
Adds support for Oracle Volume Groups
[NetAppFiles] `az netappfiles volume-group create`: Add support for Oracle in ANF Volume Groups
---

[NetAppFiles] `az netappfiles volume-group create`: Add support for Oracle in ANF Volume Groups

---

src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_container_app_mount_azurefile_e2e.yaml
src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_create_with_environment_id.yaml
src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_env_e2e.yaml
src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_env_mtls.yaml

The shared keys in container app test recording files (generated by https://github.com/Azure/azure-cli/pull/31449) were not detected by `azdev scan` because it locates in low confidence level rules. However, they are scanned by `Credential Scanner`. This PR manually replces the shared keys in the test recordings with fake values though the test resources have been deleted and the logged shared keys are no longer valid
---

{ContainerApp} Fix Cred Scan failure: Replace shared keys in container app test recordings

---

src/azure-cli/azure/cli/command_modules/cdn/custom/custom_afdx.py
src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_afd_origin_group_disable_probe.yaml

https://github.com/Azure/azure-cli/issues/30698
https://github.com/Azure/azure-cli/issues/30761

{AFD} Add health probe parameters validation for `afd origin-group` and rewrite doc string

---

src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/recordingrules/create.py
src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/recordingrules/delete.py
src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/recordingrules/tests/test_create.py
src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/recordingrules/tests/test_delete.py

```az aks create -n kaveeshcli22 -g kaveeshcli --location westeurope --enable-azure-monitor-metrics --azure-monitor-workspace-resource-id "{full_id}" --grafana-resource-id "{full_id}" --enable-windows-recording-rules```
```az aks create -n kaveeshcli22 -g kaveeshcli --disable-azure-monitor-metrics ```
This PR updates the create_rules function to conditionally enable or disable Windows-specific Prometheus recording rule groups based on a new parameter, enable_windows_recording_rules. It ensures Windows rules are only applied when explicitly enabled, while general and Linux rules remain always enabled. Additionally, the rule group creation logic is streamlined and duplicated calls are handled per rule group index.
Scenario 1:
- Use the …

[AKS] `az aks create`: Simplify logic and enable correct recording rule groups for managed prom

---

azure-pipelines.yml
scripts/release/rpm/README.md
scripts/release/rpm/azure-cli.spec
scripts/release/rpm/azurelinux.dockerfile
scripts/release/rpm/pipeline_azurelinux.sh

Azure Linux 2.0 will reach its End of Life (EOL) on July 2025. [Azure CLI 2.74.0](https://github.com/Azure/azure-cli/milestone/156) (release date: 2025-06-03) will be the last version that supports Azure Linux 2.0. [Azure CLI 2.75.0](https://github.com/Azure/azure-cli/milestone/157) (release date: 2025-07-01) will not be released for Azure Linux 2.0.
References:
- https://eng.ms/docs/products/azure-linux/overview/20eol
- Email: 🚨 ACTION REQUIRED: Azure Linux 2.0 End of Life – Upgrade to Azure Linux 3.0

[Packaging] Drop Azure Linux (Mariner) 2.0 support

---

src/azure-cli/azure/cli/command_modules/aro/custom.py

`az aro update`
- Updates the credential update/refresh process within `az aro update` to tolerate clusters with invalid machinesets - these are propagated on the ARO cluster resource under the `workerProfilesStatus` field, and currently cause the CLI to fail due to missing a valid subnet property, with the following error:
```
ERROR: (ValidationError) Failed to validate subnet 'None'. Please retry, if issue persists raise azure support ticket
```
Against an ARO cluster containing a machineset considered "invalid" (has 0 ready machines):
- Run `az aro update --refresh-credentials` on the latest Azure CLI release - will fail
- Run `az aro update --refresh-credentials` with this change - should pass
[ARO] `az aro …

[ARO] `az aro update`: Fix credential refresh to handle clusters with invalid machinesets

---

src/azure-cli/azure/cli/command_modules/keyvault/_transformers.py

Fix https://github.com/Azure/azure-cli/issues/31529
This PR is just a workaround. We need SDK fix to better support us transforming SDK model to json dict https://github.com/Azure/azure-sdk-for-python/issues/41261
---

{Keyvault} `az keyvault key show`: Fix output format

---

src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/azure-cli/azure/cli/command_modules/acs/_validators.py

Remove more direct calls to `msrestazure` that are not covered by
- https://github.com/Azure/azure-cli/pull/29856
- https://github.com/Azure/azure-cli/pull/31577

{Misc.} Remove more direct calls to `msrestazure`

---

doc/sphinx/azhelpgen/__init__.py
doc/sphinx/cligroup/__init__.py
src/azure-cli/azure/cli/command_modules/maps/tests/__init__.py
src/azure-cli/azure/cli/command_modules/maps/tests/latest/__init__.py
tools/automation/verify/verify_packages.py

`pkg_resources` is deprecated and importing it in setuptools 80.9.0 raises this warning:
```
[root@1197773e3b76 /]# python3.12 -c 'import pkg_resources'
<string>:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
```
This PR removes its usage.
Related issue: https://github.com/Azure/azure-cli/issues/31591

{Misc.} Remove `pkg_resources`

---

azure-pipelines.yml

This PR adds `continueOnError: true` to the SBOM task in the pipeline to prevent CI failures when SBOM generation encounters issues.
---

{CI} Continue on Error for SBOM task

---

azure-pipelines.yml
scripts/ci/codegen_report.py

{CI} Optimize codegen report to support module data and run on manual and Batch CI triggers due to increased execution time

---

src/azure-cli-core/azure/cli/core/profiles/_shared.py

Add None version for ResourceType.DATA_STORAGE_TABLE as using get_sdk requires it in extension for https://github.com/Azure/azure-cli-extensions/pull/8878
The reason that the value is None is because get_sdk() by default will search for parent folder with the version number unless this specific value of None is provided, and the DATA_STORAGE_TABLE package is single-api, therefore having no parent folder with a version number. 
---

{Storage}: Add None version for ResourceType.DATA_STORAGE_TABLE

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py

`az login`
`MsiAccountTypes` is used for managed identity authentication, but the name "MSI" is no longer accurate as it has been renamed to "managed identity". The official document doesn't even mention the name "MSI" anymore: https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview
Service principal authentication has its dedicated class `azure.cli.core.auth.identity.ServicePrincipalAuth`. So should managed identity authentication. This PR renames `azure.cli.core._profile.MsiAccountTypes` to `ManagedIdentityAuth`.
In addition, the `user_assigned_identity_id` argument of `azure.cli.core._profile.Profile._normalize_properties` is renamed to `assigned_identity_info` to better reflect its meaning.
`az …

{Auth} Refactor `MsiAccountTypes`

---

src/azure-cli/azure/cli/command_modules/storage/_params.py
src/azure-cli/azure/cli/command_modules/storage/operations/account.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_sas_expiration_policy.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_with_key_and_sas_policy.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py

`az stroage account create/update`
Add `--sas-expiration-action` to block expired sas policies.
[Storage] `az storage account create/update`: Add `--sas-expiration-action` to sas policy
---

[Storage] `az storage account create/update`: Add `--sas-expiration-action` to sas policy

---

src/azure-cli-testsdk/azure/cli/testsdk/utilities.py

{Test} Update the response processing in EmailAddressReplacer. In some scenario tests, we may download some binary files, which cannot be converted to utf8-encoded strings, resulting in errors. Related to #31262.
The following is a sample error when running test case [test_aks_install_kubectl](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py#L6180), which downloads the binary kubectl
```
azEnv/lib/python3.12/site-packages/vcr/config.py:178: in before_record_response
response = function(response)
^^^^^^^^^^^^^^^^^^
azure-cli/src/azure-cli-testsdk/azure/cli/testsdk/scenario_tests/base.py:209: in _process_response_recording
response = processor.process_response(response) …
```

{Test} Update the response processing in EmailAddressReplacer

---

src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_default.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_service_no_wait_msi.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py

{AKS} Fix several test cases
---

{AKS} Fix several test cases

---

src/azure-cli/azure/cli/command_modules/containerapp/_help.py

[Containerapp] `az containerapp job create`: Fix message with `--help`

---

src/azure-cli/azure/cli/command_modules/storage/commands.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_batch_operations.py

`az storage`
Allows the `az storage file upload-batch` and `az storage file download-batch` commands to use OAuth (`--auth-mode login`) for workload identities.
I have run the two new tests to confirm they pass.
[Storage] `az storage file upload-batch/download-batch`: Add OAuth login support
---

[Storage] `az storage file upload-batch/download-batch`: Add OAuth login support

---

src/azure-cli/azure/cli/command_modules/containerapp/custom.py

`az containerapp revision copy`
Fix: https://github.com/Azure/azure-cli/issues/31480
---

[Containerapp] Fix #31480: `az containerapp revision copy`: Only return `containerapp does not exist` when got 404

---

src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

Close https://github.com/Azure/azure-cli/issues/31704
[Core] Resolve CVE-2024-47081

{Packaging} Bump requests to 2.32.4

---

src/azure-cli-core/azure/cli/core/auth/util.py

This change was part of https://github.com/Azure/azure-cli/pull/28954, but was postponed.
Showing the MSAL error in the debug log can be very helpful for troubleshooting, especially in a managed identity or Cloud Shell environment where changing the source code is difficult (https://github.com/Azure/azure-cli/pull/31743#discussion_r2177112870).
As confirmed with MSAL team, the MSAL error will only contain PII but not any credentials. Azure CLI doesn't send debug log to telemetry, so it is safe to display the MSAL error in the debug log.
```
> az account get-access-token --scope https://my-invalid-scope --debug
...
cli.azure.cli.core.auth.util: MSAL error: {'error': 'invalid_scope', 'error_description': "AADSTS70011: The provided request must include a …
```

{Auth} Show raw MSAL error in debug log

---

src/azure-cli/azure/cli/command_modules/consumption/_help.py

[Consumption] `az consumption budget create`: Add command example

---

src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

Changes in this PR were part of #31699, because #31699 requires `azure-mgmt-core==1.6.0`:
> `ARMChallengeAuthenticationPolicy` adopt `on_challenge` in `BearerTokenCredentialPolicy` of `azure-core` to support complete CAE challenges.
However, `azure-mgmt-core` 1.6.0 depends on `azure-core>=1.32.0` and bumping `azure-core` is a big change, so this PR is created as a separate one.

{Packaging} Bump `azure-mgmt-core` to 1.6.0 and `azure-core` to 1.35.0

---

src/azure-cli-core/azure/cli/core/auth/util.py

`az login`
Previously, `broker_error` is dedicated to denote **getting VM SSH certificate error in Cloud Shell** (#22162) and the re-authentication message (error recommendation) is:
> Please explicitly log in with:
This is because in Cloud Shell, Azure CLI is _implicitly_ authenticated and no explicit `az login --identity` is required.
On a local machine, the re-authentication message for Entra errors is
> Interactive authentication is needed. Please run:
After supporting Windows broker (#23828), an Entra error such as `AADSTS50076` is also returned as `broker_error` in the `error` property of the MSAL result, making it impossible to tell if the error is from Cloud Shell or Entra. The re-authentication message for Entra errors is also
> Please …

{Auth} Remove `broker_error` detection for re-authentication message

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/auth/identity.py
src/azure-cli-core/azure/cli/core/util.py
src/azure-cli/azure/cli/command_modules/profile/__init__.py
src/azure-cli/azure/cli/command_modules/profile/custom.py

`az login`
During the MSAL migration (https://github.com/Azure/azure-cli/pull/19853), interactive re-authentication with claims challenge is already supported by core via `**kwargs`, but is not exposed via `az login` and AAD error handling, because:
1. This aligns with Azure PowerShell's `Connect-AzAccount` cmdlet which doesn't support claims challenge.
2. Re-authenticating without claims challenge can already solve known CAE errors.
As now MFA policy returns a claims challenge, re-authenticating without this claims challenge will not trigger the MFA process.
Similar to https://github.com/Azure/azure-cli/pull/17778 which added `--scope`, this PR adds `--claims-challenge` argument to `az login` in order to trigger the MFA process during interactive …

[Profile] `az login`: Support `--claims-challenge` in auth code flow

---

src/azure-cli-core/azure/cli/core/util.py

All cli commands
Previously we added dict transformation for typespec generated SDK models in https://github.com/Azure/azure-cli/pull/30339, we called typespec generated SDK model's `as_dict` func to get each attribute name and attribute value. But this still causes issues like https://github.com/Azure/azure-cli/issues/31529 reported when
- the attribute is renamed during SDK generation
- the attribute has some formatter defined in the SDK model
We can take the `expired` attribute from [Keyvault SDK](https://github.com/Azure/azure-sdk-for-python/blob/d85023107fade43aa9a05f46ce4c1ae8b73597ed/sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_generated/models/_models.py#L410-L412) as an example:
```Python
expires: Optional[datetime.datetime] = …
```

{Core} Adopt serialization func from azure-core for CLI's `todict` formatting

---

src/azure-cli/azure/cli/command_modules/sql/_help.py
src/azure-cli/azure/cli/command_modules/sql/_params.py
src/azure-cli/azure/cli/command_modules/sql/custom.py
src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py

sql db ltr-policy set 
Remove an unused parameter backup_storage_access_tier from Az sql ltr-policy set command. 
**Benefit**
This change will remove the unused parameter backup_storage_access_tier from the Az sql ltr-policy set command, which will make cmd simple
'sql db ltr-policy set -g {rg} -s {server_name} -n {database_name}'
' --weekly-retention {weekly_retention} --monthly-retention {monthly_retention}'
' --yearly-retention {yearly_retention} --week-of-year {week_of_year}'
' --make-backups-immutable {make_backups_immutable}
[Component Name 1] BREAKING CHANGE: `az command a`: Az sql ltr-policy set 
---
- [ x] I adhere to …

[Sql] `az sql ltr-policy set`: Remove ltr backup policy unused parameter `--access-tier`

---

src/azure-cli/azure/cli/command_modules/rdbms/_params.py

{rdbms} Fix typo in help text for `--allow-push` argument in GitHub action parameters

---

src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py

This PR removes a duplicated test method, `test_storage_account_with_files_adds_sam_account_name`, from the `StorageAccountTests` class. The method was defined twice with identical content. In Python, this results in the second definition overwriting the first, meaning only one instance of the test was effectively being run. This change removes the redundant definition to improve code clarity and prevent potential confusion.
Run the `StorageAccountTests` test suite.
---

{Storage} Remove duplicate test for Files AD DS SAM account name configuration

---

src/azure-cli-testsdk/azure/cli/testsdk/utilities.py

There could be some cases that request body is not string (for example a zip file). EmailReplacer will fail on `_byte_to_str` with `UnicodeDecodeError`. In such case, there's no need to replace anything so skipping EmailReplacer directly
---

{Test} Skip email replacer if the request body is not string

---

src/azure-cli/azure/cli/command_modules/acs/_help.py
src/azure-cli/azure/cli/command_modules/acs/_params.py
src/azure-cli/azure/cli/command_modules/acs/custom.py
src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_migrate_vmas_to_vms.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py

az aks update --migrate-vmas-to-vms
[Migrate from Availability Sets in Azure Kubernetes Service (AKS)](https://learn.microsoft.com/en-us/azure/aks/availability-sets-on-aks)
```
az aks show -g <> -n <>
az aks update -g <> -n <> --migrate-vmas-to-vms
```
---

[AKS] `az aks update`: Support VMAS to VMS agent pool migration in AKS commands

---

linter_exclusions.yml
src/azure-cli/azure/cli/command_modules/acs/_consts.py
src/azure-cli/azure/cli/command_modules/acs/_help.py
src/azure-cli/azure/cli/command_modules/acs/_params.py
src/azure-cli/azure/cli/command_modules/acs/custom.py
src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_node_provisioning_profile.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_update_node_provisioning_profile.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py

`az aks`
Add two new options to the AKS CLI --node-provisioning-mode and --node-provisioning-default-pools.
These options are related to the node auto-provisioning (aka.ms/nap) feature GA.
```
aks create --resource-group={resource_group} --name={name} --location={location}
--ssh-key-value={ssh_key_value} --node-count=1 --enable-managed-identity --network-plugin azure
--network-plugin-mode overlay --network-dataplane cilium --node-provisioning-mode=Auto
--node-provisioning-default-pools=Auto
aks update --resource-group={resource_group} --name={name} --node-provisioning-mode=Auto
```
---

[AKS] `az aks`: Add `--node-provisioning-mode` and `--node-provisioning-default-pools` parameters

---

src/azure-cli/azure/cli/command_modules/backup/_params.py
src/azure-cli/azure/cli/command_modules/backup/custom.py
src/azure-cli/azure/cli/command_modules/backup/custom_base.py
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_cvm_os_des_id.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/test_backup_commands.py

`az backup restore restore-disks`
In this PR new optional parameter `--cvm-os-des-id` is added. This parameter will take DES id as input and use that for encrypting OS disk restored confidential VM.
[Backup] `az backup restore restore-disks`: Add new parameter `--cvm-os-des-id` to specify the Disk Encryption Set ID to use for OS disk encryption
---

[Backup] `az backup restore restore-disks`: Add new parameter `--cvm-os-des-id` to specify the Disk Encryption Set ID to use for OS disk encryption

---

src/azure-cli/azure/cli/command_modules/container/custom.py
src/azure-cli/azure/cli/command_modules/container/tests/latest/recordings/test_container_reuse_from_standbypool_outbound.yaml
src/azure-cli/azure/cli/command_modules/container/tests/latest/recordings/test_container_reuse_from_standbypool_vnet.yaml
src/azure-cli/azure/cli/command_modules/container/tests/latest/test_container_commands.py

The changes are related to this command - `az container create`
- Ideally, we should not be initializing any default values on our end for the standby pool reuse scenario case which was introduced in API Version - 2024-05-01-preview. 
- However, a bug was identified where we are still setting up values for properties like ports, protocol and ip address which has been fixed. 
- This is an expected behavior when standby pool profile id is provided. 
Currently, while we try to reuse a cg from a given standby pool with delegated subnet, we get the below error - 
Code: BadRequest
Message: ContainerGroup properties other than config map are not allowed
This change would fix that, now if a customer runs the following command for example, they …

[Container] `az container create`: Remove default values for container group to support standby pool reuse scenario

---

src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_virtual_network.py

az postgresql flexible-server create
If the IP address check to ipify.org fails, the server creation command fails with no explanation of how to resolve it.  This will fail 100% of the time in USSec and USNat if the server is not VNet, the user does not provide an IP address or IP range, or the user does not specify that public access is disabled.
---

[rdbms] `az postgresql flexible-server create`: Handle failed IP address check

---

src/azure-cli/azure/cli/command_modules/servicefabric/custom.py

`az sf cluster create`
`az sf cluster create`: add more options for parameter `--vm-os` to fix https://github.com/Azure/azure-cli/issues/30381
[Service Fabric] `az sf cluster create`: Add more options for parameter `--vm-os`
---

[Service Fabric] `az sf cluster create`: Add more options for parameter `--vm-os`

---

src/azure-cli/azure/cli/command_modules/servicefabric/_help.py
src/azure-cli/azure/cli/command_modules/servicefabric/_params.py
src/azure-cli/azure/cli/command_modules/servicefabric/operations/managed_node_types.py
src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/recordings/test_node_type_update.yaml
src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/test_sf_managed_cluster.py

`az sf managed-node-type update`
Add parameters `--vm-size` and `--tags`.
See tests and help.md
[ServiceFabric] `az sf managed-node-type update`: Add parameters `--vm-size` and `--tags`
---

[ServiceFabric] `az sf managed-node-type update`: Add parameters `--vm-size` and `--tags`

---

src/azure-cli-core/azure/cli/core/profiles/_shared.py
src/azure-cli/azure/cli/command_modules/acs/_roleassignments.py
src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_public_cluster.yaml
src/azure-cli/azure/cli/command_modules/resource/custom.py
src/azure-cli/azure/cli/command_modules/role/_params.py
src/azure-cli/azure/cli/command_modules/role/commands.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

`az role`
Similar to https://github.com/Azure/azure-cli/pull/31526, https://github.com/Azure/azure-cli/pull/31801, this PR bumps `azure-mgmt-authorization` to single-API SDK.
A [private package](https://github.com/Azure/azure-sdk-for-python/pull/42095#issuecomment-3100727491) generated from [package-2024-09-01-preview](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/authorization/resource-manager/readme.md#tag-package-2024-09-01-preview) has been tested. It contains all necessary API versions CLI declares:
https://github.com/Azure/azure-cli/blob/a7e596e3826fe1fda81d99a1f899801bd6779113/src/azure-cli-core/azure/cli/core/profiles/_shared.py#L195-L197
Luckily, no API version bump is introduced, so there is no need to record tests …

{Role} `az role`: Bump `azure-mgmt-authorization` to single-API SDK

---

src/azure-cli/azure/cli/command_modules/vm/disk_encryption.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_encryption_e2e.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

`az vm encryption enable/disable`
Fix https://github.com/Azure/azure-cli/issues/31885
---

[Compute] Fix #31885: `az vm encryption`: Fix request body serialization

---

src/azure-cli-core/azure/cli/core/profiles/_shared.py
src/azure-cli/azure/cli/command_modules/acs/_completers.py
src/azure-cli/azure/cli/command_modules/acs/_params.py
src/azure-cli/azure/cli/command_modules/acs/commands.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_agentpool_decorator.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_base_decorator.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

{AKS} Bump SDK to adopt singleapi 
---

{AKS} Bump SDK to adopt singleapi 

---

src/azure-cli/azure/cli/command_modules/acs/_help.py

Change mention of `CBLMariner` to `AzureLinux` in `--os-sku` description.
CBLMariner is EOL'd, should not use it.
`az aks create --resource-group rg ... --os-sku AzureLinux`
---

[AKS] `az aks create`: Change description for `--os-sku` parameter

---

src/azure-cli/azure/cli/command_modules/containerapp/custom.py
src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerappjob_update_min_max_executions_zero_e2e.yaml
src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerappjob_crud.py

[Container App] `az containerapp job update`: Fix `--min-executions` and `--max-executions` not accepting 0 values

---

src/azure-cli-core/azure/cli/core/profiles/_shared.py
src/azure-cli/azure/cli/command_modules/iot/_help.py
src/azure-cli/azure/cli/command_modules/iot/commands.py
src/azure-cli/azure/cli/command_modules/iot/custom.py
src/azure-cli/azure/cli/command_modules/iot/tests/latest/test_iot_commands.py

az iot hub devicestream
Removes the `az iot hub devicestream` command group from this code base. The commands are moved to the azure-iot extension with the same functionality (https://github.com/Azure/azure-iot-cli-extension/pull/748)
This way we can keep one version of the IoT Hub API in this repository.
Removed the command from test_iot_hub, ran the recorded tests, and ran the tests live. The recorded tests did not change.
[IoT] Remove `az iot hub devicestream`. To use this command, please install the latest version of the extension azure-iot.
---

[IoT] BREAKING CHANGE: Migrate `az iot hub devicestream` command group to CLI extension

---

src/azure-cli-core/azure/cli/core/util.py
src/azure-cli/azure/cli/command_modules/acr/helm.py
src/azure-cli/azure/cli/command_modules/acs/custom.py
src/azure-cli/azure/cli/command_modules/appservice/custom.py

Azure CLI now only supports Python 3.9+:
https://github.com/Azure/azure-cli/blob/d7e8a34a277107b4de5d53b7f36e5aa0c1dc0592/src/azure-cli-core/setup.py#L85
and there is no Windows Cloud Shell, so this piece of code will never be hit.
For code cleanness, this PR removes the unreachable code.

{Misc.} Remove unreachable code for creating SSL context

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py

`az account get-access-token`
Resolve https://github.com/Azure/azure-sdk-for-python/issues/41875
#11798 forbids passing `--tenant` to `az account get-access-token`.
However, when Key Vault data-plane SDK receives a challenge, it will always pass the `tenant_id` to `AzureCliCredential` and `az account get-access-token`. If the current account is a Cloud Shell or managed identity account, `az account get-access-token` will fail:
https://github.com/Azure/azure-cli/blob/bc6c4d9769729f3a8e64e2c2c55c87c881fdd731/src/azure-cli-core/azure/cli/core/_profile.py#L370-L373
As it is impossible for SDK to know which account type is used by Azure CLI and pass `--tenant` conditionally, it is better for CLI to allow `--tenant` with the current tenant.
This PR allows …

[Profile] `az account get-access-token`: Allow specifying `--tenant` with the current tenant

---

scripts/regression_test/extension_regression_test.yml
scripts/regression_test/regression_test.yml

In https://github.com/Azure/azure-cli/pull/31760, some CLI tasks were mistakenly updated to simple bash tasks. Actually there's `az keyvault secret show` within the bash script to fetch github token which needs CLI environment. This PR will fix the issue
---

{CI} Fix cli login issue for regression test pipeline

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/auth/identity.py
src/azure-cli-core/setup.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

`az login --use-device-code`
https://github.com/Azure/azure-cli/pull/31778 didn't add `--claims-challenge` for device code flow because of MSAL limitation https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/834.
After MSAL fixes it in https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/839, this PR adds `--claims-challenge` for device code flow.
```
az login --use-device-code --tenant 3f145493-536c-40aa-8a6d-ca91dd64cd3b --claims-challenge eyJhY2Nlc3NfdG9rZW4iOnsiYWNycyI6eyJlc3NlbnRpYWwiOnRydWUsInZhbHVlcyI6WyJwMSJdfX19
az account get-access-token
```
Then verify the access token's `amr` (Authentication Methods Reference) claim contains `mfa`:
```
"amr": [
"fido",
"mfa"
],
```
**History …

[Profile] `az login`: Support `--claims-challenge` in device code flow

---

src/azure-cli/azure/cli/command_modules/appservice/_help.py
src/azure-cli/azure/cli/command_modules/appservice/_params.py
src/azure-cli/azure/cli/command_modules/appservice/commands.py
src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py

`az functionapp flex-migration list` 
`az functionapp flex-migration start`
Linux Consumption customers have to run these steps manually in order to migrate their apps to Flex Consumption: https://learn.microsoft.com/en-us/azure/azure-functions/migration/migrate-plan-consumption-to-flex?tabs=azure-cli%2Clinux%2Csystem-assigned%2Ccontinuous%2Ctraces-table
With the `az functionapp flex-migration list` command, customers will get a list of the Linux Consumption apps that are eligible for the migration to Flex. 
Additionally, with the `az functionapp flex-migration start` command, customers will be able to create a Flex Consumption app from their Linux Consumption (CV1) app`. The command will migrate the relevant CV1 configurations to the Flex app. After …

[AppService] `az functionapp flex-migration`: Create commands to migrate CV1 apps to Flex

---

scripts/ci/test_extensions.sh

In latest `aks-preview` extension, it adds dependency `holmesgpt==0.12.4`, which installs latest `pydantic`.
https://github.com/Azure/azure-cli-extensions/commit/fb7fc37b18c5f53e25ddc8b3026e50babd7c8a01#diff-f03813f1ac4bc03269805bd456fdb6b2260a6b6009d9416d8c0ccc440cea22b5R27
However, `partnercenter` is not compatible with `pydantic` 2.11.7 in Test Extensions Loading task:
```
File "/opt/az/azcliextensions/partnercenter/azext_partnercenter/operations/marketplace_offer_plan_technicalconfiguration/custom.py", line 7, in <module>
from azext_partnercenter.vendored_sdks.production_ingestion.models import (ContainerCnabPlanTechnicalConfigurationProperties, CnabReference)
File "/opt/az/azcliextensions/partnercenter/azext_partnercenter/vendored_sdks/production_ingestion/models/__ini …
```

{CI} Disable `partnercenter` extension test

---

src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/test_cosmosdb_commands.py

[**Related](url) command**
A future time was incorrectly used. 
---

{CosmosDB} `az cosmosdb restore`: Fix test where a future time is incorrectly used

---

src/azure-cli/azure/cli/command_modules/acs/addonconfiguration.py

az aks enable-addons --addon monitoring
if the workspace already exists in the ampls, when enable container insights addon with amplsId for the first time, there will be an resource conflict error.
1. add a workspace to ampls.
2. then run the
`
az aks enable-addons --addon monitoring --name {cluster-name} --resource-group {resource-group-name} --workspace-resource-id {law-id} --ampls-resource-id {ampls-id}
`
- without this fix, there will be following error, and container insights feature can't be enabled.
---
(azure-cli-dev-env-dev-fork) <User>azureuser</User>@<Host>jumpbox-vm</Host>:/azure-cli-dev-fork$ deactivate
<User>azureuser</User>@<Host>jumpbox-vm</Host>:~/azure-cli-dev-fork$ az aks enable-addons \
--addon monitoring \
--name …

{AKS} `az aks enable-addons --addon monitoring`: handle existing linked resource in AMPLS gracefully

---

src/azure-cli/azure/cli/command_modules/mysql/_params.py
src/azure-cli/azure/cli/command_modules/mysql/custom.py

az mysql flexible-server upgrade --version
Add new version option 8.4 to upgrade command
az mysql flexible-server upgrade --version 8.4
---

[MySQL] `az mysql flexible-server upgrade`: Add new version 8.4

---

src/azure-cli/azure/cli/command_modules/servicefabric/custom.py
src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/recordings/test_create_cluster_with_location_different_from_resource_group.yaml
src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/test_sf_cluster.py

`az sf cluster create`
Fix https://github.com/Azure/azure-cli/issues/5338 by changing the location of the KeyVault to match the location of the cluster instead of the location of the Resource Group.
---

[Service Fabric] Fix #5338: `az sf cluster create`: Fix the bug where key-vault not placed in location specifed by `--location`

---

src/azure-cli/azure/cli/command_modules/servicefabric/custom.py

`az sf cluster create`
Fixes https://github.com/Azure/azure-cli/issues/5180 where at the end of a deployment using a template, the client attempts to poll for the cluster status at end of creation with assumption that `--cluster_name` == `--resource_group_name` if `--cluster-name` is not provided. Changed code to read `--cluster_name` parameter from parameter file.
{Service Fabric} `az sf cluster create`: Change behavior to read cluster_name from parameters file if provided to fix issue #5180
---

[Service Fabric] Fix #5180: `az sf cluster create`: Change behavior to read cluster_name from parameters file if provided

---

azure-pipelines.yml

{CI} Update SBOM task conditions to trigger on BatchedCI

---

src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_natgateway_basic.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_public_ip_sku.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_natgateway_commands.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

`az network nat gateway create`
`az network public-ip create`
Scenario tests based on https://github.com/Azure/azure-cli/pull/32050
---

{Network} NAT Gateway and Public IP StandardV2 sku scenario tests

---

src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

Bump `packaging` to 25.0 to fix CI error
https://dev.azure.com/azclitools/public/_build/results?buildId=269015&view=logs&j=01b4a72e-3869-52eb-110d-7f0d8b784d9a&t=eabdfe33-575f-55d9-45e8-de3a854831ca&l=947
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tox 4.29.0 requires packaging>=25, but you have packaging 24.2 which is incompatible.
pyproject-api 1.9.1 requires packaging>=25, but you have packaging 24.2 which is incompatible.
```
Luckily, this error is not causing any functionality error.

{Packaging} Bump `packaging` to 25.0

---

src/azure-cli-core/azure/cli/core/commands/arm.py
src/azure-cli/azure/cli/command_modules/acs/_roleassignments.py
src/azure-cli/azure/cli/command_modules/role/custom.py
src/azure-cli/azure/cli/command_modules/synapse/manual/operations/accesscontrol.py

`az role assignment create`
Resolve #31995
`az role assignment create` command relies on the response message (`'role assignment already exists' in ex.message`) to implement idempotence. The code was introduced by https://github.com/Azure/azure-cli/pull/9108 in 2019 and hasn't been changed since then.
However, recently ARM is making a breaking change to the response message on the existing API version `2022-04-01` without an API version update. This breaks the idempotence of `az role assignment create` command.
This PR uses the error code (`ex.error.code == 'RoleAssignmentExists'`) to detect if there is an existing role assignment.
```sh
az role assignment create --assignee a7003d8c-e50f-4371-91a6-ef37bba4ab23 --role reader --scope …
```

{Role} `az role assignment create`: Use `RoleAssignmentExists` error code to implement idempotence

---

src/azure-cli/azure/cli/command_modules/resource/_utils.py

Starting from roughly 1-2 months ago, az-cli started to not show the actual validation error if ARM/Bicep template validation fails, and instead just shows "The content for this response was already consumed".  This was raised in issue
#31581.
A fix was attempted in 6c88666bcc, but this did not resolve the issue, because the "response was already consumed" exception was a RuntimeError (as per request 2.32.4), and the commit only caught StreamClosedError and StreamConsumedError. http_error.response.internal_response is a requests.models.Response, and StreamClosedError and StreamConsumedError are defined in azure sdk, so the request module would never throw them anyway.
A fix could be to catch the RuntimeError, however upon further thinking and looking at the discussion in issue #31709 I …

[ARM] Fix #31581: `az deployment group create`: Fix error message being hidden when template validation fails

---

src/azure-cli/azure/cli/command_modules/vm/custom.py

`az sig image-version`
close: #31198
---

[Compute] Fix #31198: `az sig image-version`: Fix `--no-wait` not working

---

.azure-pipelines/templates/azdev_setup.yml

Azure CLI's editable installation doesn't work with setuptools 80.9.0: 
```
No module named azure.cli.__main__; 'azure.cli' is a package and cannot be directly executed
```
More details: 
- https://github.com/Azure/azure-cli/issues/32042
This PR follows the same approach as https://github.com/Azure/azure-cli-dev-tools/pull/524 to pin `setuptools` to 70.0.0.

{LTS} Pin `setuptools` to 70.0.0

---

src/azure-cli/azure/cli/command_modules/monitor/aaz/latest/monitor/diagnostic_settings/_create.py
src/azure-cli/azure/cli/command_modules/monitor/operations/diagnostics_settings.py

az monitor diagnostic-settings
Improve casing and spacing of help messages.
---

{Monitor} `az monitor diagnostic-settings`: Fix casing and spacing on help texts for clarity

---

src/azure-cli/azure/cli/command_modules/acs/azurecontainerstorage/_validators.py
src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py

az aks create
This PR makes minor fixes on "az aks create --enable-azure-container-storage <pooltype> --container-storage-version 1" to not fail when vm_sku was empty.
az aks create -g test-rg -n test-cluster --enable-azure-container-storage azureDisk --container-storage-version 1
---

[AKS] `az aks create`: Fix the issue where enabling v1 container storage does not fail if the VM SKU field is left empty

---

src/azure-cli-core/HISTORY.rst
src/azure-cli/HISTORY.rst

Add history notes for 2.66.1.
This PR should have been part of https://github.com/Azure/azure-cli/pull/30848
The history notes are copied from https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.66.1

{LTS} Add history notes for 2.66.1

---

.azure-pipelines/sync-alias.yml
.azure-pipelines/templates/variables.yml
azure-pipelines.yml
scripts/live_test/CLITest.yml

Backport #30996
```
git cherry-pick -x 131634d374fe704920862a2e5b0745e61af9bc89
```

{LTS} Backport #30996: Update Azure Pipelines to use Ubuntu 22.04 pools

---

src/azure-cli/azure/cli/command_modules/storage/azcopy/util.py

Fix #32048 `az storage blob sync`: Fix using azcopy with account-key without logging into azcli
[Storage] Fix #32048: `az storage blob sync`: Fix using azcopy with account-key without login into azcli
---

[Storage] Fix #32048: `az storage blob sync`: Fix using azcopy with account-key without login into azcli

---

src/azure-cli/azure/cli/command_modules/sql/_help.py

az sql db ltr-policy 
Add extra help to command for az sql db ltr-policy
---

{Sql} `az sql db ltr-policy`: Add extra help on setting ltr policy

---

scripts/ci/install_docker.sh

Part of https://github.com/Azure/azure-cli/issues/32053
Backport https://github.com/Azure/azure-cli/pull/31158
```
git cherry-pick -x 2fa70b03fda01027a87e7efd5ed1d52c93bb2609
```
https://github.com/Azure/azure-cli/pull/30996 already bumped `ubuntu_arm64_pool` to `pool-ubuntu-latest-arm64`, but got reverted to `ubuntu-arm64-2004-pool` by https://github.com/Azure/azure-cli/pull/31123 due to failure in `scripts/ci/install_docker.sh`.
Later, https://github.com/Azure/azure-cli/pull/31158 fixed `scripts/ci/install_docker.sh` and bumped `ubuntu_arm64_pool` back to `pool-ubuntu-latest-arm64`, so there is no need to update `ubuntu_arm64_pool` to `pool-ubuntu-latest-arm64` again.

{LTS} Backport #31158: Use Ubuntu 24.04 on ARM agent

---

src/azure-cli/azure/cli/command_modules/mysql/_validators.py
src/azure-cli/azure/cli/command_modules/mysql/custom.py

az mysql flexible-server create --accelerated-logs
az mysql flexible-server udapte --accelerated-logs
Support enable accelerated logs for GeneralPurpose mysql server. 
---

[MySQL] `az mysql flexible-server create/update`: Support Accelerated Logs for GeneralPurpose
