Azure/azure-cli

src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/recordings/latest/test_sql_vnet_mgmt.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/test_sql_commands.py

Remove location from vnet test

---

scripts/ci/a01/Dockerfile.py36
scripts/ci/build.sh
scripts/ci/build_droid.sh

Let's talk about it tomorrow.
Reference: https://github.com/troydai/a01droid

Build container image for automation in Kubernetes

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_custom_image_with_plan.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

This avoids test errors caused by default name getting rejected by CRP

vm test: ensure admin username is always specified

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_acr_integration.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/recordings/latest/test_sql_db_import_export_mgmt.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/recordings/latest/test_sql_tdebyok.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/recordings/latest/test_sql_vnet_mgmt.yaml

Addressing items mentioned in #4922 #4919 

test: bring backs test which were blocked on knack conversion

---

scripts/ci/a01/Dockerfile.py36
scripts/ci/a01/future.travis.yaml
scripts/ci/build_droid.sh
scripts/ci/login_cr.sh
scripts/ci/version.sh

1. Support build droid image locally and publish end to end
2. Add script assisting login Azure Container Registry
3. Add a travis yaml prototype for building droid container.
4. Update the py36 dockerfile to derive from a stable base image
5. Update the version.sh to support timestamp as version.
---

Update the droid build script

---

src/command_modules/azure-cli-iot/HISTORY.rst
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/_help.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/commands.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/custom.py
src/command_modules/azure-cli-iot/setup.py

* Added deprecation messages in commands and command help.
* Added IoT run once check to warn users about the availability of the IoT Extension.
* Increment history and version.
---

Preparation for IoT Extension

---

src/command_modules/azure-cli-iot/HISTORY.rst
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/_help.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/commands.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/custom.py
src/command_modules/azure-cli-iot/setup.py

This PR was merged to KnackConversion. This PR simply verifies it is still green and merges into KnackFinal_2.0.24.

Preparation for IoT Extension (#5181)

---

doc/authoring_command_modules/README.md

@lmazuel This was the note that we talked about before.

Add documentation for local installed SDK into venv

---

doc/authoring_command_modules/README.md

PR #5094 was merged into KnackConversion. This simply commits this change to KnackFinal_2.0.24.

Add documentation for local installed SDK into venv (#5094)

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_linux_webapp.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_webapp_config.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_webapp_slot.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vmss_public_ip_per_vm_custom_domain_name.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

Fix #5145 (2 webapp live test failures were caused by PR #4907)

test: fix live test failures in vm & appservice

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/recordings/latest/test_sp_create_scenario.yaml
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/test_graph.py

test: fix rbac related live tests

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Restores some [changes](https://github.com/Azure/azure-cli/pull/5086/files#diff-5c470120efc875c84089542c7132d2d7L1384) to `az aks get-credentials` that were lost in the Knack merge.
Note that this may fail tests still--see #5141.
Closes #5218.

[AKS] fix get-credentials command

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/setup.py

Change AKS module version (fixes CI)

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/latest/test_network_active_active_cross_premise_connection.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py
src/command_modules/azure-cli-network/setup.py

Fixes #5198.  cc @anzaman 
---

[Network] Fix vnet gateway update command

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_template_builder.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

[Network] Application Gateway: add support for HTTP2

---

.travis.yml

Limit the test container build to push action only

---

src/azure-cli-core/azure/cli/core/commands/parameters.py

Fixes #5245.  cc/ @chrmarti 
---

Fix generic resource completer

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py

Fix VM example typos.

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/test_service_principals.py

[AKS] role assignment is not needed anymore

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vm_os_disk_swap.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

vm: (Preview) support osdisk swap on a stopped VM

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/recordings/latest/test_aks_create_default_service.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/recordings/latest/test_aks_create_with_upgrade.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/test_acs_commands.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/test_aks_commands.py

I'll create another PR or add a commit here when I figure out the problem with the remaining `AzureContainerServiceKubernetesScenarioTest`.
Refs #5141.

 [AKS] reenable and re-record two scenario tests

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/disk_encryption.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_custom_vm_commands.py

[VM] Port over PR #4743.

---

src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/azure/cli/core/commands/__init__.py
src/command_modules/azure-cli-eventgrid/HISTORY.rst
src/command_modules/azure-cli-eventgrid/azure/cli/command_modules/eventgrid/custom.py
src/command_modules/azure-cli-eventgrid/setup.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-storage/setup.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/__init__.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py

[Stack] Fix command --help failures on Azure Stack

---

src/command_modules/azure-cli-interactive/HISTORY.rst
src/command_modules/azure-cli-interactive/azclishell/configuration.py
src/command_modules/azure-cli-interactive/setup.py

Fix az interactive on Python 2

---

src/command_modules/azure-cli-monitor/HISTORY.rst
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/__init__.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_params.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/commands.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/operations/diagnostics_settings.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/recordings/latest/test_monitor_diagnostic_settings.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/test_monitor_diagnostic_settings.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/validators.py
src/command_modules/azure-cli-monitor/setup.py

Enable multiple diagnostic settings in monitor

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/custom.py

Fixes https://github.com/Azure/azure-cli/issues/4843
Fixes https://github.com/Azure/azure-cli/issues/5075
---

[ACR] Add acr login fallback on wincred errors, improve error messages

---

src/command_modules/azure-cli-interactive/HISTORY.rst
src/command_modules/azure-cli-interactive/azclishell/__init__.py
src/command_modules/azure-cli-interactive/azclishell/app.py

Addresses https://github.com/Azure/azure-cli/issues/5278

Interactive fixes

---

src/command_modules/azure-cli-servicefabric/HISTORY.rst
src/command_modules/azure-cli-servicefabric/azure/cli/command_modules/servicefabric/commands.py
src/command_modules/azure-cli-servicefabric/azure/cli/command_modules/servicefabric/tests/test_sf_commands.py

Fixes #5279.  Issue #4328 needs to be addressed to prevent this regression from happening again.
---

[ServiceFabric] Fix missing client issue

---

src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/custom.py
src/command_modules/azure-cli-interactive/azclishell/_dump_commands.py

[Interactive] Updates for command table dump

---

Dockerfile
README.md
build_scripts/docker/README.md

Closes https://github.com/Azure/azure-cli/issues/570

Docker image moved to microsoft/azure-cli

---

src/command_modules/azure-cli-batch/HISTORY.rst
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_command_type.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/test_batch_commands.py
src/command_modules/azure-cli-batch/setup.py

Fix batch cli bug when handling enum

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
src/command_modules/azure-cli-acs/setup.py

[AKS] add long-summary help for `az aks browse --disable-browser`

---

azure-cli.pyproj
src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/commands/__init__.py

[Core] Change configured default message to INFO level

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/acs_client.py

[AKS] also checking ssh_config_file is a file

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/commands.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

[AKS] fix "az acs [dcos|k8s] install-cli" requiring login

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_asg.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py

Fixes #5359. Adds ASG scenario test to protect against future regressions.
---

[Network] Fix missing client with `asg create`

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/account.py
src/command_modules/azure-cli-storage/setup.py

---
-Only create a new NetworkRuleSet for account if it is missing and "default_action" is provided.

Fixed logic for networkruleset update

---

src/azure-cli-testsdk/azure/cli/testsdk/patches.py
src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/blob.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/file.py

Closes: https://github.com/Azure/azure-cli/issues/4744
Closes: https://github.com/Azure/azure-cli/issues/4543

Adds progress reporting for all upload/download commands.

---

src/azure-cli-core/azure/cli/core/commands/__init__.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/repository.py

Fix telemetry issue

---

src/command_modules/azure-cli-cosmosdb/HISTORY.rst
src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_params.py
src/command_modules/azure-cli-cosmosdb/setup.py

Fixed parameter description for failover policies

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_format.py

---
Closes: https://github.com/Azure/azure-cli/issues/2780

Added snapshot column to table output

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_with_defaults.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py

[Network] Remove `app-gateway update` default value for sku

---

src/command_modules/azure-cli-eventgrid/HISTORY.rst
src/command_modules/azure-cli-eventgrid/azure/cli/command_modules/eventgrid/custom.py
src/command_modules/azure-cli-eventgrid/azure/cli/command_modules/eventgrid/tests/latest/recordings/test_create_event_subscriptions_to_arm_resource_group.yaml
src/command_modules/azure-cli-eventgrid/azure/cli/command_modules/eventgrid/tests/latest/recordings/test_create_event_subscriptions_to_resource.yaml
src/command_modules/azure-cli-eventgrid/azure/cli/command_modules/eventgrid/tests/latest/recordings/test_create_event_subscriptions_with_filters.yaml
src/command_modules/azure-cli-eventgrid/azure/cli/command_modules/eventgrid/tests/latest/recordings/test_create_topic.yaml
src/command_modules/azure-cli-eventgrid/azure/cli/command_modules/eventgrid/tests/latest/recordings/test_topic_types.yaml
src/command_modules/azure-cli-eventgrid/setup.py

EventGrid CLI: Updated to use the 0.4.0 version of Python SDK

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py

Fixes https://github.com/Azure/azure-cli/issues/5337
---

[ACR] Improve manifest sha256 example

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/blob.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_metrics_operations.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_upload_midsize_file.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_upload_small_file.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_file_main_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_batch_operations.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_blob_scenarios.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_file_scenarios.py

---
Fixes: https://github.com/Azure/azure-cli/issues/5308
-fixed instances of `--max-connections` as well
-added `--max-connections` arg to `storage blob download-batch` to be consistent with other commands
-small fix for failing live tests, and added test coverage 

Fixed storage args, added "max-connections" arg to `blob download-batch`

---

requirements.txt

update requirements.txt to use the latest adal

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_msi_no_scope.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_explicit_msi.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_explicit_msi.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_msi.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

msi: output principal id on enabling system assigned identity

---

src/azure-cli-core/azure/cli/core/telemetry.py

Change the parameter name in telemetry

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/setup.py

//cc: @panchagnula 
I still keep `_get_sku_name`, and will remove once your code uses new one w/o `_`

add comments showing common routines used by web site extension

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/test_acs_commands.py

Makes the ACS scenario tests more readable. See also #5392.

[AKS] Refactor ACS tests to use kwargs style instead of .format()

---

.gitignore
build_scripts/debian/build.sh
build_scripts/debian/dir_creator.sh
tools/automation/__main__.py
tools/automation/clibuild/__init__.py
tools/automation/clipublish/__init__.py
tools/setup.py

Closes https://github.com/Azure/azure-cli/issues/3720

Build all 6 debian packages & Add debian yum publish script

---

azure-cli2017.pyproj
src/azure-cli-core/azure/cli/core/commands/template_create.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_watcher.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py

Fixes the missing client issue for certain Network Watcher commands.  Restores network watcher tests that would have prevented the regression.
---

[Network] Fix Network Watcher commands

---

src/command_modules/azure-cli-extension/HISTORY.rst
src/command_modules/azure-cli-extension/azure/cli/command_modules/extension/__init__.py
src/command_modules/azure-cli-extension/azure/cli/command_modules/extension/custom.py
src/command_modules/azure-cli-extension/azure/cli/command_modules/extension/tests/latest/test_extension_commands.py
src/command_modules/azure-cli-extension/setup.py

Added the extra-index-urls change to az extension add and update commands

---

src/command_modules/azure-cli-container/HISTORY.rst
src/command_modules/azure-cli-container/README.rst
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_format.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_params.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/commands.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py
src/command_modules/azure-cli-container/setup.py

---
**Not really sure how to add tests for streaming commands. Please advise.**

[Container] Add streaming commands

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py

remove 'preview' from run-command's help

---

src/azure-cli-core/azure/cli/core/commands/__init__.py
src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/commands.py
src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/tests/latest/recordings/test_cdn_custom_domain.yaml
src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/tests/latest/recordings/test_cdn_profile_crud.yaml
src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/tests/latest/recordings/test_edge_node_crud.yaml
src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/tests/latest/recordings/test_endpoint_crud.yaml
src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/tests/latest/recordings/test_endpoint_load_and_purge.yaml
src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/tests/latest/recordings/test_endpoint_start_and_stop.yaml
src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/tests/latest/recordings/test_origin_list_and_show.yaml
src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/tests/latest/scenario_mixin.py
src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/tests/latest/test_profile_scenarios.py

[CDN] Add support for custom domain enable/disable custom HTTPS.

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Since landing a binary in an appropriate location is tricky, esp. on Windows, this should provide some help for users.
Refs #5446 #5374
---

[AKS] add post-download help message to `az aks install-cli`

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/util.py

Consolidated pattern matching logic in storage

---

src/command_modules/azure-cli-extension/azure/cli/command_modules/extension/__init__.py

Experimental pip arguments section for 'az extension' pip arguments

---

scripts/ci/a01/Dockerfile.py36

Fix droid image

---

tools/automation/tests/nose_helper.py

Arbitrary but necessary fix. THanks @williexu for finding this!
---

Fix #5519.

---

src/command_modules/azure-cli-sql/HISTORY.rst
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_params.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_util.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/custom.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_server_dns_alias_mgmt.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/recordings/latest/test_sql_server_dns_alias_mgmt.yaml
src/command_modules/azure-cli-sql/setup.py

Added sql server dns-alias commands

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/setup.py

**This is for the next release**

azure-cli azure-cli-core version bump

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_options.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_update_instance_disks.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
src/command_modules/azure-cli-vm/setup.py

vmss instance update: support attach/detach disks on an individual instance

---

src/command_modules/azure-cli-cognitiveservices/HISTORY.rst
src/command_modules/azure-cli-cognitiveservices/azure/cli/command_modules/cognitiveservices/custom.py
src/command_modules/azure-cli-cognitiveservices/setup.py

Update notice terms after PMs confirmed with CELA.
---

Update 'Notice' of Cognitive Services

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/setup.py

[ACS] Fix the SPN Insufficient Permission Issue for Virtual Kubelet installed by `aks install-connector`

---

src/command_modules/azure-cli-container/HISTORY.rst
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_params.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_validators.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/tests/latest/recordings/test_container_create.yaml
src/command_modules/azure-cli-container/azure/cli/command_modules/container/tests/latest/test_container_commands.py
src/command_modules/azure-cli-container/setup.py

Add secrets for container instances on create/update.
---

[Container]  Add secrets for container instances

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/commands.py

See https://github.com/Azure/azure-cli/pull/5475#discussion_r166372612 for more context.
---

[ACS] remove deprecation notice from `az aks get-versions` 

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_vpn_client_package.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py
src/command_modules/azure-cli-network/setup.py

Fixes #5559. Also, removes `@api_version_constraint` from existing Network tests and removes tests which don't apply to latest profile.
---

[Network] Fix `vpn-client generate` command`

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/blob.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/file.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_batch_operations.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/util.py
src/command_modules/azure-cli-storage/setup.py

---
Closes: https://github.com/Azure/azure-cli/issues/5577
-also normalize paths to improve some displayed results

Enable adding destination path to storage upload/copy batch commands.

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/setup.py

Fix missing endpoint_suffix in batch copy command

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py

Filled missing help for --destination-path

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_accelerated_networking.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_and_modify.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_custom_data.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_default_app_gateway.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_existing_ids_options.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_existing_options.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_idempotent.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_linux_secrets.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_none_options.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_options.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_single_zone.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_with_app_gateway.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_with_low_priority.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_x_zones.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_disk_encryption_e2e.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_existing_lb.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_explicit_msi.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_extension.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_lb_sku.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_nics.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_public_ip_per_vm_custom_domain_name.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_rolling_upgrade.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_update_instance_disks.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_vms.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_with_ilb.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_windows_vm_vmss_license_type.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

vmss create: default priority to None

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py

Fixes #5681.  Fixes other occurrences where default values are applied on update commands.
---

[Network] Remove default values from update commands.

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

 [ACS] warn user that `aks browse` won't work in Cloud Shell 

---

scripts/ci/a01/docker_app/metadata.yml
scripts/ci/a01/dockerfiles/py36/Dockerfile
scripts/ci/build_droid.sh

Update droid image

---

doc/authoring_help.md

Based on review with LocationBasedServices, removes some erroneous guidance here.

Small help_authoring changes

---

src/azure-cli-nspkg/HISTORY.rst
src/azure-cli-nspkg/setup.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py

Consolidate feedback from #5660, #5476 and #4895.  
cc/ @twitchax, @markjbrown 
---

[Network] Documentation Update

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_x_zones.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

test: add test coverage for provisioning web servers on x-zone vmss

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/command_modules/azure-cli-profile/HISTORY.rst
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
src/command_modules/azure-cli-profile/setup.py

With this change, I am re-enabling login/logout commands so batch/dls command users will get unblocked

cloud shell login: use msi token endpoint to retrieve creds

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py

Fix default value, check for None before assigning Public IP SKU

---

src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/__init__.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/tests/latest/test_profile_custom.py

msi: propagate default over

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_params.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/commands.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/custom.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/repository.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/latest/test_acr_commands_mock.py
src/command_modules/azure-cli-acr/setup.py

Fixes https://github.com/Azure/azure-cli/issues/4057
This PR refactors/improves `az acr repository` command group. Existing commands should be able to run without breaking but parameter/help messages are replaced with new commands.
---

[ACR] Improve az acr repository command group

---

src/azure-cli-core/azure/cli/core/_profile.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py

Bring back the legacy code, hopefully I can remove again soon
//CC: @derekbekoe @jluk @yangl900 @mayurid 

cloud shell login: bring back the raw token support as the shell is not ready to switch

---

src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/custom.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/validators.py

Limit storage mb to 1023GB for PostgreSQL and MySQL.

---

src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/custom.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/validators.py

Revert "Limit storage mb to 1023GB for PostgreSQL and MySQL."

---

src/command_modules/azure-cli-lab/HISTORY.rst
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/_help.py
src/command_modules/azure-cli-lab/setup.py
src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/setup.py

Some fixes to the help files

---

scripts/ci/build.sh
scripts/ci/build_droid.sh

Update test Image building

---

scripts/ci/a01/docker_app/metadata.yml

Automation run will send a report to these aliases.
---

Add owners' aliases to the test images metadata

---

src/command_modules/azure-cli-interactive/HISTORY.rst
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/__init__.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/app.py

---
Fixes: https://github.com/Azure/azure-cli/issues/5807

Fix `--style` parameter for `az interactive command`

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/setup.py

[ACS] fix downloading of files when in Cloud Shell / PS

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/setup.py

Fixes:#5101-Add support to enable HTTPS only for webapps

---

src/command_modules/azure-cli-acs/HISTORY.rst

fix bad history file

---

src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/commands.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/test_role_commands_thru_mock.py

rbac: new command to list/delete credentials

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py

---
Some network doc updates that did not make it as the updates moved across PRs.

Network doc updates lost in translation.

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_idempotent.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_actions.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_defaults.py

vmss: allocate big enough subnet with address space for over-provision

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/setup.py
src/command_modules/azure-cli-extension/HISTORY.rst
src/command_modules/azure-cli-extension/azure/cli/command_modules/extension/custom.py
src/command_modules/azure-cli-extension/setup.py
src/command_modules/azure-cli-sql/HISTORY.rst
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/custom.py
src/command_modules/azure-cli-sql/setup.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py

Fix the style issues raised by new Pylint

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py

Fixes:#5795:MSI support for slots

---

src/command_modules/azure-cli-dls/HISTORY.rst
src/command_modules/azure-cli-dls/setup.py

updated the adls version to latest

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/disk_encryption.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_custom_vm_commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

Closes https://github.com/Azure/azure-cli/issues/5815

azure-cli-vm support Autorest 3.0

---

azure-cli2017.pyproj
src/command_modules/azure-cli-monitor/HISTORY.rst
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_params.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/actions.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/operations/activity_log_alerts.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/operations/metric_alert.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_metric_alert_basic_scenarios.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_action_group_basic_scenario.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_activity_log_alert_update_action.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_activity_log_alert_update_condition.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_activity_log_alert_update_scope.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_basic.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_fixed.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_recurring.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_rules.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_create_default_activity_log_alert.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_create_disabled_activity_log_alert.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_create_full_fledged_activity_log_alert.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_create_log_profile.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_diagnostic_settings_scenario.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_metrics_scenario.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/test_monitor_metrics.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/util.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/validators.py
src/command_modules/azure-cli-monitor/setup.py
src/command_modules/azure-cli-role/setup.py

Closes #5785.  Fixes #4529.
---

[Monitor] Add metric namespace support

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py

Update az cors add help doc

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/disk_encryption.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_disk_encryption_e2e.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

Ported from the PS the counter part https://github.com/Azure/azure-powershell/pull/5764
//cc: @ejarvi  @SudhakaraReddyEvuri

VMSS disk encryption: report better status through disk instance view

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py

azure policy - updated _help.py to revise policy definition create

---

src/command_modules/azure-cli-rdbms/HISTORY.rst
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/__init__.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/_params.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/commands.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/custom.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_proxy_resources_mgmt.yaml
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_server_mgmt.yaml
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_proxy_resources_mgmt.yaml
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_server_mgmt.yaml
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/validators.py
src/command_modules/azure-cli-rdbms/setup.py

RDBMS CLI 0.2.0 Release with SDK generated using Autorest 3.0.

---

src/command_modules/azure-cli-interactive/HISTORY.rst
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/_dump_commands.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/app.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/az_completer.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/az_lexer.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/command_tree.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/configuration.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/frequency_heuristic.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/gather_commands.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/threads.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/tests/latest/cache/help_dump_test.json
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/tests/latest/test_completion.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/tests/latest/test_query_injection.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/tests/latest/test_tree.py

---
-Rewrote a large portion of completer logic for conciseness and readability and some fixes: Closes: https://github.com/Azure/azure-cli/issues/5630
-command tree built using dictionaries instead of lists
-partially addresses: https://github.com/Azure/azure-cli/issues/5746
-try to create lexer again after command dump if first time failed

Interactive: Fixes to completer logic, lexer reinstantiated, better tests

---

src/command_modules/azure-cli-container/HISTORY.rst
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_client_factory.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_params.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/commands.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py
src/command_modules/azure-cli-container/setup.py

Adding Container Exec Command for Azure Container Instance

---

src/command_modules/azure-cli-container/HISTORY.rst
src/command_modules/azure-cli-container/azure/cli/command_modules/container/commands.py
src/command_modules/azure-cli-container/setup.py

Fixing Table Output Support for Create Container Group

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/msi_imds_authentication.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/command_modules/azure-cli-profile/HISTORY.rst
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/tests/latest/test_profile_custom.py

login: switch to IMDS endpoints for msi login

---

src/command_modules/azure-cli-container/HISTORY.rst
src/command_modules/azure-cli-container/setup.py

I found a typo so decided to change the version no. back as well.

Container fixes after PR

---

src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py

Add Windows Client Support For Container Exec Command

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

[AKS] always create SPN with 5 years expiration time

---

src/command_modules/azure-cli-container/HISTORY.rst
src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py
src/command_modules/azure-cli-container/setup.py

Closes https://github.com/Azure/azure-cli/issues/5926

Fix container exec with --container-name

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_no_wait.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py

[Network] Fix tag support on application-gateway create

---

src/command_modules/azure-cli-cosmosdb/HISTORY.rst
src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_client_factory.py
src/command_modules/azure-cli-cosmosdb/setup.py

Allow other cloud/environments to make data plane operations in azure-cli-cosmosdb

---

src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py

Making exec-command required for Container Exec

---

src/command_modules/azure-cli-batch/HISTORY.rst
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_command_type.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_format.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_parameter_format.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/custom.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/generate_full_cli_help
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/generate_full_cli_help.bat
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/cli-3.1.11.help.txt
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/cli-3.2.0.help.txt
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_application_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_certificate_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_job_list_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_jobs_and_tasks.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_pool_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_pools_and_nodes.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_task_create_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/test_batch_commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/test_batch_data_plane_commands.py
src/command_modules/azure-cli-batch/setup.py

Update Batch cli to use latest python SDK.

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/.vscode/settings.json
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py

Fixes to massive Networking CLI examples update

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/setup.py

---
Fixes: https://github.com/Azure/azure-cli/issues/5939

More informative exception message for malformed connection string

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/azure/cli/core/commands/events.py
src/azure-cli-core/azure/cli/core/parser.py
src/command_modules/azure-cli-interactive/HISTORY.rst
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/__init__.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/az_completer.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/events.py

Allow other sources to add additional tab completion choices via event hook

---

.vscode/launch.json

added vscode config for running azdev scripts

---

src/command_modules/azure-cli-eventhubs/HISTORY.rst
src/command_modules/azure-cli-eventhubs/setup.cfg
src/command_modules/azure-cli-eventhubs/setup.py
src/command_modules/azure-cli-servicebus/HISTORY.rst
src/command_modules/azure-cli-servicebus/setup.cfg
src/command_modules/azure-cli-servicebus/setup.py
tools/automation/verify/verify_packages.py

Closes https://github.com/Azure/azure-cli/issues/5934

Fix: [CI] test_integration has test failures but still marked as green

---

src/command_modules/azure-cli-sql/HISTORY.rst
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_params.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_util.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_db_operation_mgmt.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_elastic_pool_operation_mgmt.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
src/command_modules/azure-cli-sql/setup.py

Add new azure-cli commands.
- List elastic pool operations on an elastic pool.
- Cancel operation on an elastic pool
Add test for the new added command.
---

Add new azure-cli commands on List/Cancel elastic pool operation, use new published SDK-python package 0.8.6

---

src/command_modules/azure-cli-container/HISTORY.rst
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_params.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_validators.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/tests/latest/recordings/test_container_git_repo_volume_mount.yaml
src/command_modules/azure-cli-container/azure/cli/command_modules/container/tests/latest/test_container_commands.py
src/command_modules/azure-cli-container/setup.py

Add Git Repo volume mount support
---

[container] add Git Repo volume mount support

---

azure-cli2017.pyproj
src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/linter_exclusions.yml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py

Various fixes to Network, identified by the command linter tool. 
---

[Network] Command Linter fixes

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

test:skip webapp back up test under live run as it hard codes an invalid sas token

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_express_route.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_express_route_ipv6_peering.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py
src/command_modules/azure-cli-network/setup.py

Fix #5998.
Whitelist was updated and the test was adjusted for the service's breaking changes. The CLI was already fixed to account for breaking changes.
---

Restore Express Routes tests.

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_blob_copy_scenarios.py
src/command_modules/azure-cli-storage/setup.py

---
Closes: https://github.com/Azure/azure-cli/issues/6018

Allow --sas-token to apply to source if no source account key or sas provided

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_diagnostics_extension_install.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_msi.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_secret_e2e_test.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

vm diagnostics set: detect VM's OS type reliably

---

src/command_modules/azure-cli-batch/HISTORY.rst
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_command_type.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_format.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_validators.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/custom.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_task_create_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/test_batch_data_plane_commands.py
src/command_modules/azure-cli-batch/setup.py
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/custom.py

1. Use more robust json file loading
2. Add new table format for node-agent-skus list
3. Make test more stable
4. Update batch-extension version.
---

Some updates to batch-cli

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/repository.py
src/command_modules/azure-cli-acr/setup.py

[ACR] Improve repository commands error messages

---

.gitignore
src/azure-cli-testsdk/azure/cli/testsdk/base.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_active_active_cross_premise_connection.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_with_existing_subnet.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_asg.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_express_route.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_local_gateway.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_nsg.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_public_ip.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_public_ip_sku.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_route_filter.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_route_table_operation.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_traffic_manager.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_vpn_gateway.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_private_dns.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_dns_commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py
tools/automation/coverage/run_command_coverage.py

Closes #1666.
I can see this being moved into a Knack-based standalone tool along with some other things in order to leverage the output, help and querying frameworks. However, I wanted to get this into azdev so it can start providing value. 
---
- [N/A] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

Command and Parameter Test Coverage Script

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_config.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

Adding support for MIN_TLS_VERSION & Https2.0 for web apps

---

src/command_modules/azure-cli-batchai/HISTORY.rst
src/command_modules/azure-cli-batchai/setup.py

The version was not updated but should have been.
---

Fix BatchAI Version

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/recordings/test_acs_create_default_service.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_default_service.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_service_no_wait.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_with_upgrade.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py

Fixes the `test_aks_create_with_upgrade` scenario test to work in `--live` mode. Still working on issues with the `test_acs_create_kubernetes` case, which I will fix in a separate PR.
---

Update ACS scenario tests

---

src/command_modules/azure-cli-servicebus/azure/cli/command_modules/servicebus/tests/latest/recordings/test_sb_alias.yaml
src/command_modules/azure-cli-servicebus/azure/cli/command_modules/servicebus/tests/latest/recordings/test_sb_namespace.yaml
src/command_modules/azure-cli-servicebus/azure/cli/command_modules/servicebus/tests/latest/recordings/test_sb_queue.yaml
src/command_modules/azure-cli-servicebus/azure/cli/command_modules/servicebus/tests/latest/recordings/test_sb_rules.yaml
src/command_modules/azure-cli-servicebus/azure/cli/command_modules/servicebus/tests/latest/recordings/test_sb_subscription.yaml
src/command_modules/azure-cli-servicebus/azure/cli/command_modules/servicebus/tests/latest/recordings/test_sb_topic.yaml

Service Bus: updated test recordings

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_express_route.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_express_route_ipv6_peering.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py

ExpressRoute team asked us to switch the provider for our tests.
---

Update ExpressRoute tests.

---

tools/automation/cli_linter/__init__.py
tools/automation/cli_linter/linter.py
tools/automation/cli_linter/rule_decorators.py
tools/automation/cli_linter/rules/ci_exclusions.yml
tools/automation/cli_linter/rules/command_group_rules.py
tools/automation/cli_linter/rules/command_rules.py
tools/automation/cli_linter/rules/parameter_rules.py
tools/automation/cli_linter/util.py

---
Closes: https://github.com/Azure/azure-cli/issues/6082

Added module-level ci exclusions, other minor stuff

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/setup.py

fix appservice's history doc

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_format.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/commands.py

- Mostly restructure `_format.py` for better isolation and readability.
- Fix ordering of columns (to be consistent with Azure Portal).
- Fix datetime formatting (remove milliseconds, see following as an example).
```
ID                                    ACTION    IMAGE          HTTP STATUS    TIMESTAMP
------------------------------------  --------  -------------  -------------  --------------------
42f07d41-d640-4c94-8030-46abb11462ea  ping                     200 OK         2018-04-06T19:02:04Z
dcd1be7d-97bc-4bbe-b12b-072c666f1946  delete    python         200 OK         2018-03-27T00:48:22Z
```
- Add/Remove columns for a few commands (see following)
`acr list` (remove `STATUS`)
```
NAME               RESOURCE GROUP    LOCATION       SKU       LOGIN SERVER                  CREATION …
```

[ACR] Update table columns and ordering

---

src/command_modules/azure-cli-rdbms/HISTORY.rst
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/custom.py
src/command_modules/azure-cli-rdbms/setup.py

Fix help message in create command for MySQL and PostgreSQL.

---

src/command_modules/azure-cli-batchai/HISTORY.rst
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/_params.py
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/custom.py
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/tests/latest/test_batchai_custom.py
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/tests/latest/test_batchai_scenario.py
src/command_modules/azure-cli-batchai/setup.py

BatchAI. Fix for VM priority configured via config file.

---

src/command_modules/azure-cli-resource/HISTORY.rst
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py
src/command_modules/azure-cli-resource/setup.py

fixed link id

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
src/command_modules/azure-cli-acs/setup.py

added clarity to get-credentials

---

src/command_modules/azure-cli-container/HISTORY.rst
src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/tests/latest/test_container_commands.py
src/command_modules/azure-cli-container/setup.py

Container Instance: Add Better ACR Registry Creds Experience

---

tools/automation/cli_linter/rules/ci_exclusions.yml

Allow Linter to run on VM module for CI

---

src/azure-cli-core/azure/cli/core/tests/test_help.py

Remove test_help_long_description_from_docstring

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/parser.py

Display command suggestions on error if the command is misspelled

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_with_low_priority.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

vmss: support eviction policy for low priority scaleset

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/latest/recordings/test_delete_dependent_resources.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/latest/test_resource.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/latest/test_resource_id_deletes.py

Fix resource test

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/linter_exclusions.yml
tools/automation/cli_linter/rules/ci_exclusions.yml

app service: clear cli lint violations

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
tools/automation/cli_linter/rules/ci_exclusions.yml

fixed storage linter violations

---

src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/tests/latest/test_lab.py

Skip DevTest Lab tests

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/custom.py

Fixes https://github.com/Azure/azure-cli/issues/5961
Fixes https://github.com/Azure/azure-cli/issues/5729
Fixes https://github.com/Azure/azure-cli/issues/5663
---

[ACR] Improve acr login in non-standard consoles and WSL

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py

app service: fix a typo

---

tools/automation/clibuild/__init__.py

This is for https://github.com/Azure/azure-cli/issues/5731

Add Ubuntu bionic builds

---

src/command_modules/azure-cli-batch/setup.py

Fix keyring module not found CI error

---

src/command_modules/azure-cli-interactive/HISTORY.rst
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/app.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/util.py

No longer throw error with input '\' in interactive

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py

---
Fixes: https://github.com/Azure/azure-cli/issues/6194

fixed --marker param for storage entity query

---

src/command_modules/azure-cli-batch/HISTORY.rst
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_pool_cmd.yaml
src/command_modules/azure-cli-batch/setup.py

Use latest azure-batch and azure-batch-extension dependency

---

src/command_modules/azure-cli-cognitiveservices/HISTORY.rst
src/command_modules/azure-cli-cognitiveservices/azure/cli/command_modules/cognitiveservices/_help.py
src/command_modules/azure-cli-cognitiveservices/setup.py

Closes https://github.com/Azure/azure-cli/issues/5603

Fix typo with cognitiveservices example

---

tools/automation/verify/verify_module_load_times.py

This unblocks us in CI.
Haven't done a root cause analysis to understand *why* the load time in Travis CI has gone up for this module but locally, it seems fine and looking at the code, nothing has changed in this module over the last day.

Increase module perf. threshold for SQL

---

src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/validators.py

Fix incorrect validator of event-hub

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_slot.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

Fix #6063. In hindsight, we should not have exposed the -`-slot` to provide another way to delete a slot. Guess it is too late now.
//CC @panchagnula

webapp: fix a bug in deleting a slot

---

src/command_modules/azure-cli-profile/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_actions.py

disk create: fix a bug that source detection is not accurate

---

tools/automation/tests/__init__.py

Improves the regex for getting module name so that it works with the azure-cli-pr repo.
---

Make discovery regex more specific.

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/test_role.py

role: fix live tests

---

src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_params.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_validators.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/commands.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/custom.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_certificate_contacts.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_certificate_crud.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_certificate_get_default_policy.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_certificate_issuers.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_key.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_mgmt.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_pending_certificate.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_secret.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_storage_account.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py

storage account updates tests and fixes

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py

vm: put write-accelerator arg under storage

---

src/azure-cli-core/azure/cli/core/_help.py

include documentation of '--version' option.  
Solves Issue #6096 
---

Update _help.py to include --version

---

scripts/ci/test_integration.sh

Disable telemetry during command verification

---

src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_params.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/commands.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_storage_account.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py

adding regenerate-key command to keyvault storage

---

src/command_modules/azure-cli-container/HISTORY.rst
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_params.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/commands.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py
src/command_modules/azure-cli-container/setup.py

Adding Yaml Support for Create and Export Container Group

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
src/command_modules/azure-cli-acs/setup.py

Typo: generate was spelled gemerate

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/setup.py

[Network] Fix NetworkWatcher validator

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_actions.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_extension.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
src/command_modules/azure-cli-vm/setup.py

For: https://icm.ad.msft.net/imp/v3/incidents/details/68590693/home

vm/vmss extension: fix an incorrect extension image matching logic

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/__init__.py
src/command_modules/azure-cli-storage/setup.py

added completer for storage account name

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_table_main_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_table_scenarios.py

---
Fixes: https://github.com/Azure/azure-cli/issues/6353

Fixed entity query bug

---

scripts/ci/build.sh
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_download_linux_web_log.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp_multicontainer_create.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp_quick_create.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/sample-compose.yml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

remove hardcorded resource, move lukems and naziml images to patle

---

tools/automation/cli_linter/linter.py

---
Fixes: https://github.com/Azure/azure-cli/issues/6367

Fixed bug with rule inclusion

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_appservice_utils.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_deploy_zip.yaml

Updating Zip deploy to using async api & display status of deployment

---

src/command_modules/azure-cli-interactive/HISTORY.rst
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/az_completer.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/gather_commands.py
src/command_modules/azure-cli-interactive/setup.py

---
Fixes: https://github.com/Azure/azure-cli/issues/6350
Fixes: https://github.com/Azure/azure-cli/issues/6382

Mute parser for interactive completions

---

src/command_modules/azure-cli-batch/HISTORY.rst
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_format.py
src/command_modules/azure-cli-batch/setup.py

Batch CLI bug fix for issue #4378 
@xingwu1 for review :)

[Batch] Fix for pool list table

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/repository.py

Fixes https://github.com/Azure/azure-cli/issues/6325
---

[ACR] Improve manifest delete confirmation on tags

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/build.py
src/command_modules/azure-cli-acr/setup.py

- Allows VSTS to bypass the remote source location filtering
- Minor spelling change.
Signed-off-by: Eric Hotinger <erhoting@microsoft.com>
---
/cc @NatalieGong @sajayantony @northtyphoon @djyou 

[ACR] Allows VSTS to bypass the remote source location filtering

---

src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/tests/latest/preparers.py

Fixing issue with VM creation in test preparer

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_accelerated_networking.yaml

This is temporary. The long term target is to support across all vm sizes.

accelerator network: only enable on vm with 8+ cores

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/util.py
src/command_modules/azure-cli-storage/setup.py

---
Fixes: https://github.com/Azure/azure-cli/issues/6257
Fixes: https://github.com/Azure/azure-cli/issues/6402

Added mimetypes for json and javascript files

---

.gitignore
src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/telemetry.py
src/azure-cli-core/azure/cli/core/telemetry_upload.py

Update telemetry upload process start configuration

---

src/command_modules/azure-cli-interactive/HISTORY.rst
src/command_modules/azure-cli-interactive/setup.py

Fix dependencies issue in the interactive module

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/setup.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
src/command_modules/azure-cli-batch/HISTORY.rst
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_task_create_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/test_batch_data_plane_commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/test_batch_mgmt_commands.py
src/command_modules/azure-cli-batch/setup.py

[Batch] Remove dependency and update live test case

---

src/command_modules/azure-cli-sql/HISTORY.rst
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/custom.py

Try to avoid StopIteration error when no sql capabilities are available.

---

src/azure-cli-core/azure/cli/core/parser.py
tools/automation/cli_linter/linter.py
tools/automation/cli_linter/rules/parameter_rules.py

Removed check for short multi-char options in parser, added to linter.

---

src/azure-cli-core/azure/cli/core/_profile.py

Fix Auth_url for AAD env (stack) (#6500)

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/setup.py

This will resolve the urllib conflict with requests.
---

Update AppService dependencies

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/setup.py

[Network] Fixed `--endpoint-status` in TrafficManager.

---

src/azure-cli-core/azure/cli/core/telemetry.py

Fix for CLI core

---

src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/commands.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/setup.py

ad: bug fixes on error handling and sp creating from external apps

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/setup.py

- Adding --update option to update the dev spaces componenets and update the extension
---

 Updating options/params of use-dev-spaces command under aks module

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/setup.py

Fixed bug in new functions app code to allow app service in other RG - https://github.com/Azure/azure-cli/issues/6532
---

Functions app creation bugfix

---

src/command_modules/azure-cli-rdbms/HISTORY.rst
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/_help.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/_params.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/custom.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_commands.py
src/command_modules/azure-cli-rdbms/setup.py

CLI code changes for Boundaryscaling feature

---

doc/command_guidelines.md

extensions must pass style checks

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-storage/setup.py

---
-Will make the output for -otable more informative and better ordered.
-before the columns in the table were: `Deleted`, and `name` (in that order)

Added table transformer for `storage blob download`

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/setup.py
src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_validators.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_default_service.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_service_no_wait.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/test_custom.py
src/command_modules/azure-cli-acs/setup.py

This is for a quick review of the merge conflict I resolved. Please DO NOT merge this through the github. I will do it on the command line as soon as the CI passes and reviewers approve.

Merge release 2.0.36 and 2.0.37 back to dev

---

src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/setup.py

To avoid the unhandled exception mentioned in #6447

role definition: add data validation on create/update

---

src/azure-cli-core/azure/cli/core/telemetry.py

Extra check before telemetry is uploaded

---

src/azure-cli-core/azure/cli/core/telemetry.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/telemetry.py

Added interactive indicator to ShellType sent for telemetry

Added interactive tag to shell-type event property

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/setup.py

Bump core version to 2.0.39

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone2_import.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_dns_commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/zone_files/zone2.txt
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/zone_files/zone2.txt_export.txt
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/zone_files/zone4.txt
src/command_modules/azure-cli-network/azure/cli/command_modules/network/zone_file/parse_zone_file.py
src/command_modules/azure-cli-network/setup.py

[Network] Fix case sensitivity in DNS zone import.

---

doc/extensions/README.md
doc/extensions/extension_summary_guidelines.md

Added extension summary guidelines to docs

---

build_scripts/windows/azure-cli.wixproj
build_scripts/windows/scripts/build.cmd
src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/setup.py

1. Only remove redundent *.py for azure.* packages.
2. Move artifacts folder from user profile to local repo.
3. Clean up build.cmd
---

Update Windows Build Script

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py

[ACR] Slightly improve help messages for image delete commands

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_constants.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_params.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_utils.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/custom.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/replication.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/latest/test_acr_commands_mock.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/webhook.py

Fixes https://github.com/Azure/azure-cli/issues/6562
---

[ACR] Allow case insensitive enum values

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_utils.py

Closes https://github.com/Azure/azure-cli/issues/5619
---

[ACR] Fix incorrect sub id in error messages

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_docker_utils.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_params.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_utils.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/credential.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/repository.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/latest/test_acr_commands_mock.py

Reopened stale PR https://github.com/Azure/azure-cli/pull/6401
Fixes https://github.com/AzureCR/azure-cli/issues/150
Fixes https://github.com/Azure/azure-cli/issues/5385
Closes https://github.com/Azure/azure-cli/issues/4773
Closes https://github.com/Azure/azure-cli/issues/4050
---

[ACR] Add top and orderby parameters for show-manifests, general improvement

---

src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py

Add sql server & firewall-rule examples

---

build_scripts/windows/scripts/build.cmd

setup: skip trimming .py files on pip

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py

Update the help text for the --node-osdisk-size parameter

---

src/azure-cli-core/azure/cli/core/api.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-find/HISTORY.rst
src/command_modules/azure-cli-find/azure/cli/command_modules/find/custom.py
src/command_modules/azure-cli-find/setup.py
src/command_modules/azure-cli-interactive/HISTORY.rst
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/app.py
src/command_modules/azure-cli-interactive/setup.py

Refactory the core code. Consolidate the utility methods and remove unnecssary `_`-initialzed module.

Introduce azure.cli.core.api to provide unified interfaces module

---

build_scripts/windows/azure-cli.wixproj
build_scripts/windows/scripts/build.cmd
src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/setup.py

Hotfix 2.0.39

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_explicit_msi.yaml

vmss: remove a workaround for VMSS patch service bug

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py

[AKS] Use the latest helm chart to install VK

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Reload module when we use --update option

---

requirements.txt
src/azure-cli-core/setup.py
src/command_modules/azure-cli-acs/setup.py
src/command_modules/azure-cli-container/setup.py
tools/setup.py

Pin PyYaml version to 3.12

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_explicit_msi.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_msi.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_msi.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

//cc: @troydai, this is a pretty low risk change, I suggest we take it for the current release

identity: support removing system assigned identity

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_assign_system_identity.yaml

Adding support to disable identity feature and removing preview tags

---

src/command_modules/azure-cli-batchai/HISTORY.rst
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/custom.py
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/tests/latest/test_batchai_live.py
src/command_modules/azure-cli-batchai/setup.py

BatchAI. Fix job exec command and live unit tests

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_constants.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_params.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/build.py

Add OS type parameter to build command

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/util.py

login: support browser based login in WSL bash window

---

.gitignore
Pipfile
requirements.txt

The older version will cause test failures in Python 3.7
---

Upgrade paramiko to 2.4.1

---

src/azure-cli-core/azure/cli/core/util.py

---
Fixes: https://github.com/Azure/azure-cli/issues/6707

Fixed browser support for az login in py2

---

scripts/ci/test_extensions.sh
src/command_modules/azure-cli-batch/HISTORY.rst
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_client_factory.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_command_type.py
src/command_modules/azure-cli-batch/setup.py

[Batch] Enable token credential for cloudshell

---

src/azure-cli-core/azure/cli/core/tests/test_util.py

test: add coverage for the recent login bug found on py2

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_validators.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_bad_inputs.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_default_service.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_service_no_wait.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
src/command_modules/azure-cli-acs/setup.py

This prevents an error where the dashboard or another supporting pod eventually fails to start.
cc: @sauryadas
---

[AKS] error if --max-pods is less than 5

---

src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/test_batch_mgmt_commands.py

Remove is_live since it is LiveTest

---

.travis.yml
scripts/ci/test_automation.sh
tools/automation/tests/__init__.py

also, remove code coverage for now.

Add automation on 2.7 back to CI

---

src/command_modules/azure-cli-cognitiveservices/azure/cli/command_modules/cognitiveservices/_help.py

---
- [ n/a] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).
- [ n/a] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

cognitive services examples

---

src/command_modules/azure-cli-container/HISTORY.rst
src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py
src/command_modules/azure-cli-container/setup.py

Fixing Output Error When Creating From Yaml File - Container Instances

---

src/command_modules/azure-cli-sql/HISTORY.rst
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_format.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py

Add table formatters for sql server and firewall-rule commands

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/setup.py

allow premiumv2 skus
fixes https://github.com/Azure/azure-cli/issues/6663
---

allow premiumv2 skus

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_params.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/commands.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/repository.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/latest/test_acr_commands_mock.py

[ACR] Add attributes commands and detail flag under acr repository group

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_and_modify.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
src/command_modules/azure-cli-vm/setup.py

Fix #5970. A planned breaking change.

 vmss create: update default instance size to Standard_DS1_v2

---

scripts/ci/test_extensions.sh
src/azure-cli-core/azure/cli/core/__init__.py
tools/automation/verify/verify_load_all.py

---
Uses a new event to check failure of extensions being loaded.
Adds to CI check for extensions.

Added check for properly loading extensions `azdev verify load_all`

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/blob.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_upload_midsize_file.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_upload_small_file.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_blob_live_scenarios.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_blob_scenarios.py

---
Closes: https://github.com/Azure/azure-cli/issues/6754

Added page_range property to 'blob show' for page blobs

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_params.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/build_task.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/repository.py

[ACR] Add support to get build details or logs by an image

---

src/command_modules/azure-cli-servicefabric/azure/cli/command_modules/servicefabric/tests/__init__.py
src/command_modules/azure-cli-servicefabric/azure/cli/command_modules/servicefabric/tests/latest/__init__.py

Remove empty service fabric tests folder

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_progress.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_msi.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_msi.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

vm test: fix live test failures

---

requirements.txt
src/azure-cli-core/setup.py
src/command_modules/azure-cli-container/HISTORY.rst
src/command_modules/azure-cli-container/setup.py
src/command_modules/azure-cli-interactive/HISTORY.rst
src/command_modules/azure-cli-interactive/setup.py
tools/setup.py

Pin PyYAML version to 3.13 instead of 4.2b

---

src/command_modules/azure-cli-acs/setup.py

Missed in previous commit.
---

Update PyYAML dependency

---

scripts/ci/test_static.sh
tools/setup.py

pin pylint at 1.9.2 for static check

---

src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_subscription_usages.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py

Fixed live test failure in test_sql_subscription_usages

---

src/azure-cli-core/azure/cli/core/_completers.py
src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/api.py
src/azure-cli-core/azure/cli/core/commands/arm.py
src/command_modules/azure-cli-profile/HISTORY.rst
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/__init__.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_completers.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/tests/latest/test_profile_custom.py
src/command_modules/azure-cli-profile/setup.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_completers.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py

Fix https://github.com/Azure/azure-cli/issues/6813
---

Move _load_subscriptions from profile to core

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/setup.py
src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/setup.py

---
Closes: https://github.com/Azure/azure-cli/issues/6608

use multiapi 0.2.2

---

src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/setup.py

Handle https://icm.ad.msft.net/imp/v3/incidents/details/76749036/home

role assignment: bug fix in output to handle when the role could be missing

---

src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/test_role_commands_thru_mock.py
src/command_modules/azure-cli-role/setup.py

Will not close the underlying issue because this creates a workaround.  
---

[RBAC] Fix `ad app update` 

---

src/command_modules/azure-cli-container/HISTORY.rst
src/command_modules/azure-cli-container/README.rst
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_params.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py
src/command_modules/azure-cli-container/setup.py

Do not require --log-analytics-workspace-key when passing in the Name or ID

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py

Fix arg help typo in vm image --urn

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/setup.py
src/command_modules/azure-cli-servicebus/HISTORY.rst
src/command_modules/azure-cli-servicebus/azure/cli/command_modules/servicebus/_help.py
src/command_modules/azure-cli-servicebus/setup.py
src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py

Consolidates changes from other PRs that are failing due to the author's not bumping the versions.
---

Consolidate help fix PRs

---

src/command_modules/azure-cli-batch/HISTORY.rst
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/custom.py
src/command_modules/azure-cli-batch/setup.py

[Batch] Fixes bug when show AAD token in cloudshell

---

src/azure-cli-core/azure/cli/core/profiles/_shared.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py

@lmazuel, can you please review?

minor bug fixes: typo, invalid samples

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py

Fixed typo "detatch" to "detach"

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py

Fixed typo "unamanged" to "unmanaged"

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_availset.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_storage_sku.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_asg.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

Changes are mostly straightforward, so I combine them.
I can split into 2 or 3 PRs if preferred.

vm/vmss: support for StandardSSD storage sku, Azure Security Group, list av-set by subscriptions.

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py

Added an example for local-gateway and 5 for ddos-protection

---

src/command_modules/azure-cli-eventhubs/HISTORY.rst
src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/_params.py
src/command_modules/azure-cli-eventhubs/setup.py
src/command_modules/azure-cli-servicebus/azure/cli/command_modules/servicebus/tests/latest/test_servicebus_commands.py

---
* updated help for the parameter --partition-count of eventhub

EventHub: updated help for the parameter --partition-count of eventhub

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/setup.py

---
Fixes: https://github.com/Azure/azure-cli/issues/6915

Fix appservice example

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/account.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_create_storage_account.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
src/command_modules/azure-cli-storage/setup.py

---
Closes: https://github.com/Azure/azure-cli/issues/1073

Make --resource-group optional for storage account commands

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/setup.py

 core: use knack/0.4.2 with fix towards numeric value display in table output

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py

vm: fix examples of assigning managed identities to VM/VMSS

---

src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/test_role.py
src/command_modules/azure-cli-role/setup.py

[role assignment] fix a recent regression that principalName is missing

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_deploy_zip.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_e2e.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
src/command_modules/azure-cli-appservice/setup.py

Fix #6918 
Fix #6760 
Fix #6527
And also input checks to ensure webapp exists. This is due to breaking change from azure-mgmt-web that 404 became a valid error code (a mistake)

[appservice] bug fixes in function-app create, zip deployment, doc, etc

---

src/command_modules/azure-cli-container/HISTORY.rst
src/command_modules/azure-cli-container/README.rst
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_params.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py
src/command_modules/azure-cli-container/setup.py

Container Instance: Adding Secure Environment Variables

---

src/azure-cli-core/tox.ini

Run Azure CLI Core unit test on tox

---

src/command_modules/azure-cli-sql/HISTORY.rst
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_params.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_util.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/custom.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_failover_group_mgmt.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py

Azure CLI implementation for Failover Groups (AutoDR)

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/blob.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/file.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/util.py

---
Fixes: https://github.com/Azure/azure-cli/issues/6960

[Storage] precondition message changes and remove delete-batch output

---

doc/sphinx/azhelpgen/doc_source_map.json
src/command_modules/azure-cli-iotcentral/HISTORY.rst
src/command_modules/azure-cli-iotcentral/MANIFEST.in
src/command_modules/azure-cli-iotcentral/README.rst
src/command_modules/azure-cli-iotcentral/azure/__init__.py
src/command_modules/azure-cli-iotcentral/azure/cli/__init__.py
src/command_modules/azure-cli-iotcentral/azure/cli/command_modules/__init__.py
src/command_modules/azure-cli-iotcentral/azure/cli/command_modules/iotcentral/__init__.py
src/command_modules/azure-cli-iotcentral/azure/cli/command_modules/iotcentral/_client_factory.py
src/command_modules/azure-cli-iotcentral/azure/cli/command_modules/iotcentral/_help.py
src/command_modules/azure-cli-iotcentral/azure/cli/command_modules/iotcentral/_params.py
src/command_modules/azure-cli-iotcentral/azure/cli/command_modules/iotcentral/commands.py
src/command_modules/azure-cli-iotcentral/azure/cli/command_modules/iotcentral/custom.py
src/command_modules/azure-cli-iotcentral/azure/cli/command_modules/iotcentral/tests/__init__.py
src/command_modules/azure-cli-iotcentral/azure/cli/command_modules/iotcentral/tests/latest/__init__.py
src/command_modules/azure-cli-iotcentral/azure/cli/command_modules/iotcentral/tests/latest/recordings/test_iotcentral_app.yaml
src/command_modules/azure-cli-iotcentral/azure/cli/command_modules/iotcentral/tests/latest/test_iotcentral_commands.py
src/command_modules/azure-cli-iotcentral/azure_bdist_wheel.py
src/command_modules/azure-cli-iotcentral/setup.cfg
src/command_modules/azure-cli-iotcentral/setup.py

Command line support for create/list/update/delete of IoT Central applications on http://aka.ms/iotcentral
---
//cc @zzcodework @amrenbin

Add iotcentral commands

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/repository.py

Fixes https://github.com/Azure/azure-cli/issues/6977
---

[ACR] Fix empty repository

---

src/command_modules/azure-cli-iotcentral/azure/cli/command_modules/iotcentral/_help.py
src/command_modules/azure-cli-iotcentral/azure/cli/command_modules/iotcentral/tests/latest/recordings/test_iotcentral_app.yaml
src/command_modules/azure-cli-iotcentral/setup.py

* Update azure-mgmt-iotcentral to 0.2.0 to support the GA version 2018-09-01
* Remove PREVIEW prefix from iotcentral command summary
* Update test recording data for 2018-09-01
This package wasn't available yesterday when the original PR went through to add *iotcentral* commands, so I am adding it in this PR.
---
//cc @tjprescott

Update IotCentral dependency to 0.2.0

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/test_custom.py

[aks/windows]: install kubectl to under %USERPROFILE%\.azure-kubectl

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/latest/recordings/test_group_deployment_thru_uri.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/latest/test_resource.py

test: turn test_group_deployment_thru_uri back to regular scenario test

---

scripts/release/rpm/azure-cli.spec

Add telemetry module to RPM release script

---

src/command_modules/azure-cli-rdbms/HISTORY.rst
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/_params.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/validators.py
src/command_modules/azure-cli-rdbms/setup.py

[RDBMS] Remove implicit dependency on SQL command module

---

src/command_modules/azure-cli-batchai/HISTORY.rst
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/_params.py
src/command_modules/azure-cli-batchai/setup.py

[BatchAI] Remove implicit dependency on VM command module

---

src/command_modules/azure-cli-iot/HISTORY.rst
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/custom.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/tests/latest/recordings/test_dps_lifecycle.yaml
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/tests/latest/test_iot_dps_commands.py
src/command_modules/azure-cli-iot/setup.py

* Increment DPS mgmt SDK requirement
* Fix internal breaking changes for SDK usage patterns
* Apply work around (back rev API) for assocating a linked-hub due to swagger/sdk
mismatch with API.
* Update tests and DPS recording
* Addresses [issue 6973](https://github.com/Azure/azure-cli/issues/6973)
---

Update for IoT command modules use of DPS SDK 0.2.0

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_batch_operations.py

Fixed tests for delete-batch commands to pass live test

---

src/command_modules/azure-cli-lab/HISTORY.rst
src/command_modules/azure-cli-lab/setup.py

[DevTestLab] Update DevTestLab dependency

---

src/command_modules/azure-cli-servicefabric/HISTORY.rst
src/command_modules/azure-cli-servicefabric/setup.py

[ServiceFabric] Update azure-mgmt-servicefabric dependency to 2.0.0

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/setup.py

Add adal as dependency to core

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_acl_scenarios.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_batch_operations.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_validators.py

---
Fixes blob_delete_batch test and some style fixes

[Storage] Minor fixes to tests

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/setup.py
src/command_modules/azure-cli-backup/HISTORY.rst
src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/commands.py
src/command_modules/azure-cli-backup/setup.py
src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/setup.py
src/command_modules/azure-cli-resource/HISTORY.rst
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py
src/command_modules/azure-cli-resource/setup.py
src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-storage/setup.py
src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/setup.py

---
Commands that were missed; added exception handling to exit with 3.

Some remaining show commands without handling

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_cors.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_cors.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

Fix #4565 
Expose `az functionapp cors add/remve/show` and `as webapp cors add/remove/show`. This is to be consistent with portal, which expose "cors" as a top level tab

webapp/functionapp: support cors

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/_session.py

[Core] Reset the configuration file when it is empty

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py

[vm] handle possible failure on getting default admin user

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/setup.py
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/_help.py
src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/_help.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
tools/automation/cli_linter/linter.py
tools/automation/cli_linter/rules/ci_exclusions.yml
tools/automation/cli_linter/rules/help_rules.py
tools/automation/cli_linter/util.py

---
Fixes: https://github.com/Azure/azure-cli/issues/7031
Fixed violations for a couple of services

Added linter rule to check for command name in example

---

src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/_help.py

---
Fixes: https://github.com/Azure/azure-cli/issues/6637

Updated error in eventhubs help example.

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_customer_managed_key.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py

Removed live-only and recorded test for customer_managed_key

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_traffic_manager.yaml
src/command_modules/azure-cli-network/setup.py

[Network] Update trafficmanager SDK dependency

---

src/command_modules/azure-cli-redis/HISTORY.rst
src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/_params.py
src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/_validators.py
src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/commands.py
src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/custom.py
src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache.yaml
src/command_modules/azure-cli-redis/setup.py

[Redis] Update dependencies

---

scripts/move-tests.sh
src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/profiles/__init__.py
src/azure-cli-core/azure/cli/core/profiles/_shared.py
src/azure-cli-core/azure/cli/core/tests/test_cloud.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/account.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py

Feedback from the meeting included.
---

[Stack] Consolidated PR for CLI code changes wrt 2018-03-01-hybrid profile

---

.github/CODEOWNERS
src/command_modules/azure-cli-dls/setup.py

---
-v0.0.24 or above is required to acquire retry policy implementation
-updated to latest

Update sdk and add codeowner

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py

[Stack] Fix provider operation show for stack profile

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/setup.py

---
Fixes CI for new PRs after recent release.

bump core version

---

src/command_modules/azure-cli-batch/HISTORY.rst
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_command_type.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_help.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_parameter_format.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_params.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/custom.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_account_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_application_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_certificate_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_job_list_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_jobs_and_tasks.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_pool_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_pools_and_nodes.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_task_create_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/test_batch_commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/test_batch_data_plane_commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/test_batch_mgmt_commands.py
src/command_modules/azure-cli-batch/setup.py

Closes #3715, Closes #5142, Closes #6751, Closes #6914, Closes #6916
Update adding tasks through --json-file to support AddTaskCollectionParameter syntax
Update documentation of accepted --json-file formats
Add --max-tasks-per-node-option to az batch pool create
Update show behavior of az batch account to show currently logged in account if no options are specified.
Separate test case needing advanced permissions to allow for remaining tests to be executed
---

Update Batch command module

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_params.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/build.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/build_task.py
src/command_modules/azure-cli-acr/setup.py

[ACR] Add a flag for displaying build logs to fix Unicode Encode Error

---

src/command_modules/azure-cli-batch/HISTORY.rst
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/custom.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/data/batch-pool-create-invalid.json
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/data/batch-pool-create.json
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/data/batchCreatePool.json
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/data/batchCreateTestPool.json
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/cli-3.4.0.help.txt
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_certificate_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_job_list_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_jobs_and_tasks.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_pool_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_pools_and_nodes.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_task_create_cmd.yaml
src/command_modules/azure-cli-batch/setup.py

Update Batch Cli with latest SDK

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_bad_inputs.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_default_service.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_default_service_with_monitoring_addon.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_default_service_without_skip_role_assignment.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_service_no_wait.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py

Fixes the failing nightly AKS tests when run `--live`.
cc: @troydai 
---

[AKS] update VCR tests for RP changes

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

**NOTE**: Merge to IgniteNetwork branch
Closes #7181.
---

[NetworkIgnite] ExpressRoute `--allow-global-reach`

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

Hi all,
Just noticed some annoying typos in some of the appservice code, this fixes those.
Cheers,
Daniel
---

Fix some typos in appservice

---

src/azure-cli-core/azure/cli/core/profiles/_shared.py
src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_subnet_delegation.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py

**NOTE**: Merge to IgniteNetwork branch.
Closes #6941. cc/ @irrogozh 
---

[IgniteNetwork] Subnet delegation

---

src/command_modules/azure-cli-storage/HISTORY.rst

---
Related to https://github.com/Azure/azure-cli/pull/7113

[Storage] Add missed history for Oauth feature.

---

src/azure-cli-core/setup.py
src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/setup.py
src/command_modules/azure-cli-servicefabric/setup.py
src/command_modules/azure-cli-vm/setup.py

**NOTE**: Merge to IgniteNetwork
Fix #7146. Fix #7191. Fix #7213.
Small bug fixes for Network issues that should ship with the Ignite release. Also, bumps the version of Knack because of a bug in Knack's deprecation options logic.
---

[IgniteNetwork] Ignite Release Bug Fixes

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_config.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

Adding support for ftpsState property of site config

---

src/azure-cli-core/azure/cli/core/_profile.py

login: output error when opening socket failed

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

**NOTE**: Merge to IgniteNetwork branch.
Closes #7242.
---

Close #7242.

---

src/command_modules/azure-cli-cognitiveservices/HISTORY.rst
src/command_modules/azure-cli-cognitiveservices/azure/cli/command_modules/cognitiveservices/_params.py
src/command_modules/azure-cli-cognitiveservices/setup.py

Solves https://github.com/Azure/azure-cli/issues/7157
--

[Cognitive Services] Add completer for  `--sku`, `--kind`, `--location`

---

src/command_modules/azure-cli-network/setup.py
src/command_modules/azure-cli-servicefabric/setup.py
src/command_modules/azure-cli-vm/setup.py

[Network] Update Network SDK. Remove private WHL

---

src/azure-cli-core/azure/cli/core/profiles/_shared.py
src/command_modules/azure-cli-resource/HISTORY.rst
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py

---
Fix: https://github.com/Azure/azure-cli/issues/7259

Fix broken az feature commands in non latest profiles

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_client_factory.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_profile.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py

Adds limited support for network profile: `show`, `list`, `delete`.
Closes #6984.
---

[Network] Add network profile commands.

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_docker_utils.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_params.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/commands.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/custom.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/helm.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/repository.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/latest/test_acr_commands_mock.py

Resolve https://github.com/AzureCR/azure-cli/issues/244
---

[ACR] Add helm command group to support managing helm charts

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/account.py

---
ICM ticket: https://icm.ad.msft.net/imp/v3/incidents/details/83117490/home
Once a proper new sdk is released, I will undo this fix.

[Storage] Temp fix to allow idempotent storage account creates

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py

[Storage] Set min_api for worm feature

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_client_factory.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_express_route_global_reach.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py

Adds `express-route peering connection` commands to support global reach scenarios.
cc/ @dedhar, @syfarogh
--

[Network] Add express-route peering connection commands.

---

src/azure-cli-core/azure/cli/core/keys.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py

[VM] Update helps and text

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

Fixes breaking SDK issue with DDOS protection create.
---

[Network] Fix issue with ddos-protection create.

---

scripts/dependency/requirements.Darwin.external.txt
scripts/dependency/requirements.Linux.external.txt
src/command_modules/azure-cli-rdbms/HISTORY.rst
src/command_modules/azure-cli-rdbms/README.rst
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/_client_factory.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/_help.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/_params.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/commands.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/custom.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mariadb_proxy_resources_mgmt.yaml
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mariadb_server_mgmt.yaml
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_commands.py
src/command_modules/azure-cli-rdbms/setup.py

This is for MariaDB service in Azure. 
---

 Support MariaDB service in module rdbms

---

src/command_modules/azure-cli-container/setup.py
src/command_modules/azure-cli-network/setup.py
src/command_modules/azure-cli-servicefabric/setup.py
src/command_modules/azure-cli-vm/setup.py

Needed due to Network Profile Swagger hotfix.

[Network] Bump Network SDK to 2.2.1

---

src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py

Container Instance: Fixing delegation Naming

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/setup.py

[Core] Bump core version

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/task.py

Add yml as a reserved task file type, which is often used on Windows.
/cc @djyou @northtyphoon @ankurkhemani 
---

[ACR] Add yml as a reserved task file type

---

src/command_modules/azure-cli-interactive/HISTORY.rst
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/app.py
src/command_modules/azure-cli-interactive/setup.py

---
Regression introduced with https://github.com/Azure/azure-cli/commit/5873166369cf5e19ff4ef05cab93ce33ec2976aa#diff-1d1b6d8ade910f4842412259a0e41e63
in 2.0.44

Pass along sys.stdout to output function

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/helm.py

Fixes https://github.com/Azure/azure-cli/issues/7357
---

[ACR] Support pushing helm packages with path reference

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py

http:// homepage no longer valid. Change to https://

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Add support for AKS browse in the cloud console.

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/test_custom.py

Fixes #7077
@mboersma @yugangw-msft

Fix merge credentials to properly handle duplicate entries, or error out.

---

doc/authoring_tests.md

Small updates to authoring_tests.md.
---

Updated authoring_tests.md.

---

src/command_modules/azure-cli-acs/setup.py
src/command_modules/azure-cli-servicefabric/HISTORY.rst
src/command_modules/azure-cli-servicefabric/setup.py
src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_managed_disk.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
src/command_modules/azure-cli-vm/setup.py

[vm]: fix the empty 'accessSas' field in the result of 'disk grant-access'

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_config.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

update byos tests to use prod

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py

[run-command]: update argument description of --command-id

---

src/command_modules/azure-cli-iot/HISTORY.rst
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/__init__.py
src/command_modules/azure-cli-iot/setup.py

Added extension installation instructions to IoT command module banner message

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_on_linux.yaml

fixes #7426 
set linux fx version when using a custom docker image
---

add container kind when using containers

---

src/command_modules/azure-cli-container/HISTORY.rst
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_params.py
src/command_modules/azure-cli-container/setup.py

Container Instance: Updating the Memory and Cpu Help Text

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_archive_utils.py

Fixes https://github.com/Azure/azure-cli/issues/7343
---

[ACR] Remove import builtin

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py

[Network] Misc help fixes.

---

src/azure-cli/setup.py

[Core] Add missing dependencies to azure-cli

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

[Network] Fix AppGateway SKU tier logic. 

---

src/command_modules/azure-cli-resource/HISTORY.rst
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py
src/command_modules/azure-cli-resource/setup.py

Updated the "Create a policy parameter definition with the following example" to provide a proper example for #5810
---

Fixed policy parameter definition example

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_format.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/setup.py

[Network] Add table format to `nic list-effective-nsg` and `nic show-effective-route-table`

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/latest/recordings/test_provider_registration.yaml

provider register: do not emit out the wait message if the target state is already met

---

src/command_modules/azure-cli-container/HISTORY.rst
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_format.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_params.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_validators.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py
src/command_modules/azure-cli-container/setup.py

* Add warning message when trying to create a container instance using an image that does not have a long running process.
* Fix the table output for az container list when the instance view state is null.
---

Container Instance: Better Warning and Table Output Fix

---

src/command_modules/azure-cli-batch/HISTORY.rst
src/command_modules/azure-cli-batch/setup.py

[Batch] Update Batch Cli with latest SDK

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic_app_gateway.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py

[Network] Add AppGateway backend pool arguments to NIC commands.

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/setup.py

[Core]Bump core version

---

src/command_modules/azure-cli-container/HISTORY.rst
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_params.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/tests/latest/recordings/test_container_create.yaml
src/command_modules/azure-cli-container/azure/cli/command_modules/container/tests/latest/recordings/test_container_create_msi.yaml
src/command_modules/azure-cli-container/azure/cli/command_modules/container/tests/latest/recordings/test_container_create_with_acr.yaml
src/command_modules/azure-cli-container/azure/cli/command_modules/container/tests/latest/recordings/test_container_create_with_msi.yaml
src/command_modules/azure-cli-container/azure/cli/command_modules/container/tests/latest/recordings/test_container_create_with_vnet.yaml
src/command_modules/azure-cli-container/azure/cli/command_modules/container/tests/latest/recordings/test_container_git_repo_volume_mount.yaml
src/command_modules/azure-cli-container/azure/cli/command_modules/container/tests/latest/test_container_commands.py
src/command_modules/azure-cli-container/setup.py

Container Instance: Add Assign MSI Identity for container create

---

README.md

Document was renamed due to which the link is broken in the Readme.md
---

Updated VCR tests link in readme.md

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/setup.py
src/command_modules/azure-cli-batchai/HISTORY.rst
src/command_modules/azure-cli-batchai/setup.py

Upgrade azure-storage-blob pinned dependencies to latest version (1.1.0 to 1.3.1)
This includes multiple bugfixes and features for azure-storage-blob: https://github.com/Azure/azure-storage-python/blob/master/azure-storage-blob/ChangeLog.md -- no breaking changes.
---

Upgrade azure-storage-blob pinned dependency to latest version.

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py

---
Docs team asking for this fix.

[VM] remove faulty url

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_cors_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_cors_scenarios.py

---
Followup from: https://github.com/Azure/azure-cli/pull/7496 to add testing

[Storage] added testing for multiple cors additions

---

scripts/dependency/requirements.Darwin.external.txt
scripts/dependency/requirements.Linux.external.txt
src/azure-cli-core/setup.py

update knack 0.4.4

---

src/azure-cli-testsdk/azure/cli/testsdk/utilities.py

Make scrubbed over value valid base64

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/setup.py

2.0.49 build created. Bumping versions.
---

Bump versions to 2.0.50 for next release

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/setup.py

[Network] Fix issue with `--peer-circuit ID` when created ER peering connection

---

scripts/ci/precheck_pep8.sh

pin flake8 to 3.5.0

---

src/command_modules/azure-cli-profile/HISTORY.rst
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/__init__.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_help.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
src/command_modules/azure-cli-profile/setup.py

Adds a hidden command `az self-test` that can be run on any installation to detect packaging error like the kind we experience with Homebrew.
---

Add hidden self-test command.

---

azure-cli2017.pyproj
src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/setup.py
tools/automation/verify/verify_packages.py

Allow retrieving output format and logging verbosity from the namespace.
---

Bump Knack version.

---

.travis.yml
scripts/ci/test_profile_integration.sh

---
-'Integration for profiles' checks all profiles, and is more thorough
-it also takes less than 5 mins compared to the 20-30 mins of the other check

[CI] Change integration check

---

src/command_modules/azure-cli-rdbms/HISTORY.rst
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/_client_factory.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/_help.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/_params.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/commands.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/custom.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_replica_mgmt.yaml
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_commands.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/validators.py
src/command_modules/azure-cli-rdbms/setup.py

Add mysql replica commands

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/setup.py

Remove Flag for Cloud Shell Proxy

---

src/command_modules/azure-cli-servicebus/HISTORY.rst
src/command_modules/azure-cli-servicebus/setup.py

The last (I hope) Homebrew installation snafu.
---

Fix ServiceBus SDK for Homebrew installation.

---

scripts/ci/precheck_pep8.sh

---
Followup from https://github.com/Azure/azure-cli/pull/7695 that got merged before expected.

unpin flake8 in precheck

---

src/azure-cli-core/setup.py

The way we were specifying conditional dependencies in azure-cli-core's `setup.py` was incorrect, resulting in problematic behavior in Python 2.7.
---

Fix conditional dependencies in core setup.py.

---

src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/custom.py

---
-small improvement to help user experience while waiting for install.

[Interactive] tell the user that the extension is being installed/updated

---

src/command_modules/azure-cli-acs/setup.py
src/command_modules/azure-cli-ams/HISTORY.rst
src/command_modules/azure-cli-ams/setup.py
src/command_modules/azure-cli-keyvault/HISTORY.rst
src/command_modules/azure-cli-keyvault/setup.py
src/command_modules/azure-cli-lab/HISTORY.rst
src/command_modules/azure-cli-lab/setup.py
src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/commands.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/recordings/test_graph_app_cred_e2e.yaml
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/recordings/test_graph_required_access_e2e.yaml
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/recordings/test_set_graph_owner.yaml
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/test_graph.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/test_role_commands_thru_mock.py
src/command_modules/azure-cli-role/setup.py
src/command_modules/azure-cli-servicefabric/HISTORY.rst
src/command_modules/azure-cli-servicefabric/setup.py

[graph] support API permission management, signed-in-user, and application password & certificate credential management

---

doc/sphinx/azhelpgen/doc_source_map.json

Add the missing edit mapping to doc_source_map.json

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_params.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/build.py

Use default Dockerfile if it's not specified in build command

---

src/azure-cli-core/azure/cli/core/__init__.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/__init__.py

---
-added ability to ask user to update when suppressing extension.
-interactive suppresses older version of alias

[Core, Interactive] ask to update alias if present

---

src/command_modules/azure-cli-container/HISTORY.rst
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_params.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_validators.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py
src/command_modules/azure-cli-container/setup.py

Container: Add Retry Logic For Role Assignment

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py

Fix #6897  
- Modified validator to better handle incorrect image arguments. More specifically, validator does not assume an image argument with some valid scheme is a vhd uri.
- Updated help text for --image to clarify URN format.
---

[VM(SS)] Modified validator. Updated help text.

---

.vscode/launch.json
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_client_factory.py

---
- addresses initial problem raised by: https://github.com/Azure/azure-cli/issues/4347
- clarifies behavior of specifying data-plane parameters.

[Storage] update msg to clarify behavior when only account name is known

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py

Updated vmss create --image help text.

---

src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_params.py

Change keyvault imports to work with MSI fixes. Also bumps msrestazure version.
---

Fix keyvault imports.

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py

---
Close: https://github.com/Azure/azure-cli/issues/6598

[Storage] added incremental copy example

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp.yaml

fixes https://github.com/Azure/azure-cli/issues/7730
---

fix get_fx_version returning null

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py

Updated example publisher name to MicrosoftWindowsServer.
Closes #7647 
---

[vm] Update publisher name in vm image list-offers example

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/setup.py

Bump CLI versions.

---

azure-cli2017.pyproj
src/azure-cli-core/azure/cli/core/extension/__init__.py

The old PR got closed because I deleted the underlying branch, but this pretty much makes the change you suggested @williexu
---

Pull extensions directory from config OR environment variable

---

src/command_modules/azure-cli-rdbms/HISTORY.rst
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/_client_factory.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/_help.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/_params.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/commands.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_commands.py
src/command_modules/azure-cli-rdbms/setup.py

Add MariaDB vnet commands

---

tools/automation/cli_linter/__init__.py
tools/automation/utilities/const.py
tools/automation/utilities/path.py

---
-Now checks installed extension for the presence of exclusion file to be used when linting.

[Linter] added rule exclusions for extensions

---

src/command_modules/azure-cli-cognitiveservices/HISTORY.rst
src/command_modules/azure-cli-cognitiveservices/azure/cli/command_modules/cognitiveservices/_help.py
src/command_modules/azure-cli-cognitiveservices/setup.py

cognitive service link to docs URL

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/account.py

---
Fixes: https://github.com/Azure/azure-cli/issues/7688

[Storage] enable creation of sas_token connection-strings

---

azure-cli2017.pyproj
src/command_modules/azure-cli-iotcentral/HISTORY.rst
src/command_modules/azure-cli-iotcentral/azure/cli/command_modules/iotcentral/custom.py
src/command_modules/azure-cli-iotcentral/azure/cli/command_modules/iotcentral/tests/latest/recordings/test_iotcentral_app.yaml
src/command_modules/azure-cli-iotcentral/setup.py

* Updated to latest version of azure-mgmt-iotcentral python sdk
* Added check for subdomain uniqueness.
---

Update sdk version and check for subdomain uniqueness

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py
src/command_modules/azure-cli-storage/setup.py

---
Add help for `storage share create` to replace the summary from the sdk.
Closes: https://github.com/Azure/azure-cli/issues/1587

[Storage] help for share

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py

webapp: capture unhandled exception on configuring VSTS CI/CD

---

doc/configuring_your_machine.md

Update develop doc.

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py

---
Closes: https://github.com/Azure/azure-cli/issues/1787

[Storage] recommend use blob show to see result of a copy

---

src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/azure/cli/core/commands/client_factory.py

Support for ARM param tracking

---

doc/authoring_command_modules/authoring_commands.md

[doc] Authoring doc update

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/blob.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/file.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_sas_tokan_url_scenarios.py

---
- Fixed issue with sas_token parameter not being included within the resulting url.
- also added much needed testing of using the sas_token to make a request

[Storage] pass along sas_token to blob/file url and added testing

---

src/command_modules/azure-cli-dls/HISTORY.rst
src/command_modules/azure-cli-dls/setup.py

---
- [] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).
NA

Updated adls version to 0.0.38

---

src/command_modules/azure-cli-cosmosdb/HISTORY.rst
src/command_modules/azure-cli-cosmosdb/setup.py

Recently enabled " ignore_missing_vnet_service_endpoint" as a property of a virtual network rules object.
---

Updating to most recent azure-mgmt-cosmosdb package

---

src/command_modules/azure-cli-keyvault/HISTORY.rst
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_command_type.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/hybrid_2018_03_01/recordings/test_keyvault_certificate_issuers.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/hybrid_2018_03_01/test_keyvault_commands.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_certificate_issuers.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
src/command_modules/azure-cli-keyvault/setup.py

keyvault: surface CLI command error 

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py

[Snapshot] Add wait/no-wait support for snapshots.

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py

vm: remove preview flag from os disk swap

---

src/command_modules/azure-cli-keyvault/HISTORY.rst
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_command_type.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/hybrid_2018_03_01/recordings/test_keyvault_key.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_key.yaml

Fix #7844  Fix #7333 
- [ x The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

keyvault: do not drop legit exceptions

---

src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/grammar/MetricAlertConditionValidator.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_metric_alert_v2_scenario.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_fixed.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_create_log_profile.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/test_monitor_log_profile.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/test_monitor_unittest.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_route_filter.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_subnet_delegation.yaml

Based on live test failures.
---

[Monitor] Fixes for monitor live tests.

---

azure-cli2017.pyproj
src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_validators.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_deploy_zip.yaml

Updating the default time for polling the status of zipdeployment from 2.5 to 5 mins & adding a property for users to customize this polling interval

---

src/azure-cli-core/azure/cli/core/commands/__init__.py

---
- Fixes: https://github.com/Azure/azure-cli/issues/4087
- Fixes multiple deprecation warnings per --ids invocation
- Moved majority of code out of `--ids` invocation loop to prepare for parallel execution.

resolve multi deprecation and confirmation

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/repository.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/latest/test_acr_commands_mock.py

Fixes https://github.com/Azure/acr/issues/146
---

[ACR] Better support of top/orderby in show-tags/manifests commands (#294)

---

src/azure-cli-core/setup.py

Fix requests version > 2.20

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/setup.py

[vm] extension. Deprecate and hide expand param.

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/commands/arm.py

Properly handle parsing of ids from -o tsv on windows.

---

src/command_modules/azure-cli-appservice/HISTORY.rst

ci: fix build break

---

src/command_modules/azure-cli-dls/HISTORY.rst
src/command_modules/azure-cli-dls/setup.py

Updated adls version to 0.0.39

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

[Network] Fix DNS zone update `--registration-vnets` and `--resolution-vnets`

---

doc/sphinx/azhelpgen/azhelpgen.py
scripts/ci/precheck_header.sh

[doc] Fix doc gen issue. Command option help now properly loaded

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

[AKS] Add network policy support to aks subcommand

---

doc/sphinx/azhelpgen/azhelpgen.py
scripts/ci/precheck_header.sh

Doc gen fixes; re-enable version checks.

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

[Network] Add flow log format to NSG flow logs

---

scripts/ci/test_help_doc_arguments.py
scripts/ci/test_ref_doc.sh
src/azure-cli-core/azure/cli/core/file_util.py

[Doc] Test that doc params are consistent with CLI help params.

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_explicit_msi.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_msi.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_msi_no_scope.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_explicit_msi.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_msi.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
src/command_modules/azure-cli-vm/setup.py

Fixes #7747 
Fixes #7738 
Fixes #6102 
---

[VM] doc updates. Fix in vm identity remove

---

scripts/ci/precheck_header.sh
src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/setup.py
src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/setup.py
src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/setup.py

Check module versions for release.

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_windows_runtime.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_windows_without_runtime.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

[functionapp] Fixes #7534 - add runtime parameter for windows apps

---

src/command_modules/azure-cli-iotcentral/HISTORY.rst
src/command_modules/azure-cli-iotcentral/azure/cli/command_modules/iotcentral/custom.py
src/command_modules/azure-cli-iotcentral/azure/cli/command_modules/iotcentral/tests/latest/recordings/test_iotcentral_app.yaml
src/command_modules/azure-cli-iotcentral/azure/cli/command_modules/iotcentral/tests/latest/test_iotcentral_commands.py
src/command_modules/azure-cli-iotcentral/setup.py

---
This PR changes the api call used when calling `az iotcentral app update` . Before, we were using `createOrUpdate` when it should have been `update`.

[IoTCentral] Update command was using incorrect api call

---

scripts/release/rpm/check-signature.sh

Adding a script that will verify that all RPM packages passed to it are signed.
It also automatically installs Microsoft public key.

Add RPM signing check script

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/account.py

[Storage] fix bug with setting use_subdomain property

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_create_util.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py

webapp: Fixes to az webapp up command where the location value was incorrect causing errors

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

This should prevent failures like [this](https://dashboard.azclitest.com/task/466724) from happening for VMAvailSetScenarioTest.test_vm_availset
---

[vm] Flakey test fix

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_client_factory.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/setup.py

vm/vmss: support cross tenant image reference

---

src/command_modules/azure-cli-hdinsight/HISTORY.rst
src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/_client_factory.py
src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/_help.py
src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/_params.py
src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/commands.py
src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/custom.py
src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_application.yaml
src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_cluster_kafka.yaml
src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_cluster_kafka_with_optional_disk_args.yaml
src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_cluster_min_args.yaml
src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_cluster_resize.yaml
src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_cluster_rserver.yaml
src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_cluster_with_cluster_config.yaml
src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_cluster_with_component_version.yaml
src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_cluster_with_ssh_creds.yaml
src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_oms.yaml
src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_script_action.yaml
src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_usage.yaml
src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/test_hdinsight_commands.py
src/command_modules/azure-cli-hdinsight/setup.py

[HDInsight] - Add more commands
* Applications
* Script actions
* OMS
* Regional Usages
---

[HDInsight] - Add more commands

---

src/azure-cli-testsdk/azure/cli/testsdk/utilities.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_file_main_scenario.yaml

---
Scrubber now preserves bytes information sent over wire in recording

[Testing] update scrubber to preserve dev tools file payload

---

src/command_modules/azure-cli-acr/setup.py
src/command_modules/azure-cli-appservice/setup.py
src/command_modules/azure-cli-batchai/setup.py
src/command_modules/azure-cli-servicefabric/setup.py
src/command_modules/azure-cli-sql/setup.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/account.py
src/command_modules/azure-cli-storage/setup.py

-can't test change as a domain name is required and service returns the same response whether or not the property is set
@lmazuel for awareness
---

[Storage] update storage mgmt sdk and change to fixed subdomain property

---

azure-cli2017.pyproj
src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp_ssh.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tunnel.py
src/command_modules/azure-cli-appservice/setup.py

add webapp ssh

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py
src/command_modules/azure-cli-acr/setup.py
src/command_modules/azure-cli-appservice/setup.py

[ACR] add helm actions to webhook

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_docker_utils.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/helm.py

Fixes https://github.com/Azure/acr/issues/142
Fixes https://github.com/AzureCR/azure-cli/issues/296
Partially addresses https://github.com/Azure/azure-cli/issues/7814 by removing client side validation.
Includes https://github.com/Azure/azure-cli/pull/7820
---

[ACR] Improve registry/helm operations

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/blob.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_update_service_properties.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_blob_scenarios.py

[Storage] changed parameter naming to remove units and add to test

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_vm_diagnostics_templates.py

[vm] update `diagnostics set` example.  Fix bug in `diagnostics get-default-config  --is-windows-os`

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/account.py

---
Fixes: https://github.com/Azure/azure-cli/issues/7296
fix on sdk side has made this unecessary

[Storage] removed temp fix

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_active_active_vnet_connection.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py

Fix ddos-protection bug. Close #7977.
---

[Network] Live test failure fixes

---

src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/azure/cli/core/commands/arm.py
src/azure-cli-core/azure/cli/core/commands/parameters.py
src/azure-cli-core/azure/cli/core/decorators.py
src/azure-cli-core/azure/cli/core/extension/operations.py
src/azure-cli-core/azure/cli/core/telemetry.py
src/azure-cli-core/azure/cli/core/util.py
src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/operations/content_key_policy.py
src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/bot_template_deployer.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_autoscale_util.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/actions.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/operations/autoscale_settings.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/operations/metric_alert.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_vm_utils.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/disk_encryption.py

Moving forward, Pylint will not run on Python 3.7 unless we bump the dependency. That means a whole new slew of pylint standards. I plan to slowly update them all over the next several releases before me make the CI enforce them. 
---

Pylint updates (Network, Monitor, Resource, Role, Core)

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

[AKS] Add support for new ACI Regions

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_constants.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_create_util.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py

webapp: Updating default SKU of Linux used by azwebapp up

---

src/command_modules/azure-cli-ams/HISTORY.rst
src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/_help.py
src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/commands.py
src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/operations/content_key_policy.py
src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/tests/latest/recordings/test_ams_asset_list_streaming_locators.yaml
src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/tests/latest/recordings/test_ams_streaming_locator_list_content_keys.yaml
src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/tests/latest/test_ams_asset_scenarios.py
src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/tests/latest/test_ams_streaming_locator_scenarios.py
src/command_modules/azure-cli-ams/setup.py

ams asset get-streaming-locators renamed to ams asset-list-streaming-locators
ams streaming-locator get-content-keys renamed to ams streaming-locator list-content-keys
Tests updated.
---

Breaking change - rename get-<objects> to list-<objects>

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/setup.py

Fixes live test failure of DDOS protection update command.
---

[Network] Fix DDOS Protection set comprehension

---

src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/tests/latest/recordings/test_ams_streaming_endpoint_create.yaml
src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/tests/latest/recordings/test_ams_streaming_endpoint_create_with_akamai.yaml
src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/tests/latest/recordings/test_ams_streaming_endpoint_delete.yaml
src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/tests/latest/recordings/test_ams_streaming_endpoint_scale.yaml
src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/tests/latest/recordings/test_ams_streaming_endpoint_show.yaml
src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/tests/latest/recordings/test_ams_streaming_endpoint_update.yaml
src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/tests/latest/test_ams_streaming_endpoint_scenarios.py

No customer facing changes; just test code and recordings.
---

Normalize filenames passed as parameters in tests.

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_docker_utils.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_params.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/custom.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/helm.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/repository.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/latest/test_acr_commands_mock.py

[ACR] Add login server tenant suffix parameter

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_params.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/commands.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/custom.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/network_rule.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_network_rule.yaml
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/latest/test_acr_network_rule_commands.py
src/command_modules/azure-cli-acr/setup.py

Fixes https://github.com/AzureCR/azure-cli/issues/297
---

[ACR] Add support for VNet/IP rules

---

src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_params.py

[Monitor] Improve `metrics list` help text.

---

src/command_modules/azure-cli-sqlvirtualmachine/azure/cli/command_modules/sqlvm/_help.py

Fix bad SQL VM example. This had passed CI and was approved before @adewaleo's example checker was merged.
---

Fix failing dev branch

---

src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/__init__.py

--resource-type (Ex: 'Microsoft.Compute/virtualMachines)') Issue : Fixes #8259 
---

--resource-type (Ex: 'Microsoft.Compute/virtualMachines)') #8259

---

src/command_modules/azure-cli-monitor/HISTORY.rst
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/operations/metric_alert.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_metric_alert_v2_scenario.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/test_monitor_metric_alert_scenarios.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/validators.py

Fixes issue where --add/remove-action may not work due to case differences in action IDs.
---

[Monitor] `metrics alert update`: Make ID comparison case insensitive.

---

src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/azure/cli/__init__.py
src/azure-cli/setup.py

This comes after releasing 2.0.55 on January 15, 2019.

Updating core version number strings to 2.0.56.

---

src/command_modules/azure-cli-resource/HISTORY.rst
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/latest/recordings/test_group_deployment.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/latest/test_resource.py

[resource]:  support uri based parameters file in 'group deployment create'

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_vm_utils.py

Fix icm ticket at https://icm.ad.msft.net/imp/v3/incidents/details/99545102/home
//CC : @adewaleo

vmss: fix an invalid error on cross subscription vnet reference

---

src/command_modules/azure-cli-sqlvirtualmachine/azure/cli/command_modules/sqlvm/__init__.py

Updated the init to remove extension if customer has already installed.
---

Update __init__.py in SQL VM to suppress extension if installed.

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_app_service_plan.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

\cc @ahmedelnably @panchagnula @Nking92  @jeffhollan 
---

functionapp: Add support for app service plan creation (With EP)

---

src/azure-cli-core/azure/cli/core/commands/arm.py

---
Fixes: https://github.com/Azure/azure-cli/issues/8195

[Core] set _ids to be list if parsed

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/setup.py

Fix issue unable to disable virtual-node

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/setup.py

webapp: Updating the help command for az appservice plan update command

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py

Guess no one is really using this flag, but since I found it when investigated the icm ticket of "https://icm.ad.msft.net/imp/v3/incidents/details/101603394/home", so I am fixing this

list-skus: --all should be a flag

---

doc/authoring_tests.md

Closes #5155. Updates the test authoring guidance for how to assert specific errors occur. No additional infrastructure work is needed in the CLI to support this.
---

Add recommended syntax for asserting errors.

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_update_webapp_settings_thru_json.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

appservice: support updating configuration through json

---

src/command_modules/azure-cli-keyvault/HISTORY.rst
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_validators.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/hybrid_2018_03_01/recordings/test_keyvault_secret.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/hybrid_2018_03_01/test_keyvault_commands.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_secret.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
src/command_modules/azure-cli-keyvault/setup.py

[KeyVault] Fixes https://github.com/Azure/azure-cli/issues/8371

---

src/command_modules/azure-cli-ams/HISTORY.rst
src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/_help.py
src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/commands.py
src/command_modules/azure-cli-ams/setup.py

There are no customer facing changes.
---

Decorate commands that support --no-wait with g.wait_command('wait')

---

azure-pipelines.yml
src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/azure/cli/core/extension/tests/latest/test_index_get.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/setup.py
src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/acs_client.py
src/command_modules/azure-cli-acs/setup.py
src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
src/command_modules/azure-cli-vm/setup.py

Fixing Missing Command Module Requirements

---

src/azure-cli-core/azure/cli/core/commands/__init__.py

---
Fixes: https://github.com/Azure/azure-cli/issues/8397
Fixes: https://github.com/Azure/azure-cli/issues/8320
Fixes: https://github.com/Azure/azure-cli/issues/8314

[Core] Fix running validators with subscription param

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_params.py

Had to update a couple of examples and description of the flag. 
This adds to the platform flag added in this PR: 
https://github.com/Azure/azure-cli/pull/8302
---

Add more clarity to platform message and update examples

---

src/azure-cli/HISTORY.rst
src/command_modules/azure-cli-keyvault/HISTORY.rst
src/command_modules/azure-cli-keyvault/setup.py
src/command_modules/azure-cli-rdbms/HISTORY.rst
src/command_modules/azure-cli-rdbms/setup.py

Fixing issues currently causing other PRs to fail CI.

Fixing Headers blocking CI

---

scripts/curl_install_pypi/install

Updated curl install script

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py

Correct validation error message reported in #8411

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone1_import.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone2_import.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone3_import.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone4_import.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone5_import.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone6_import.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/zone_files/zone1.txt_export.txt
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/zone_files/zone2.txt_export.txt
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/zone_files/zone3.txt
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/zone_files/zone3.txt_export.txt
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/zone_files/zone4.txt_export.txt
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/zone_files/zone5.txt_export.txt
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/zone_files/zone6.txt_export.txt

[Network] Fix CNAME export on DNS zone export

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_rules.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic_address_pools.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic_ag_address_pools.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic_lb_address_pools.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic_subresources.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py

[Network] Make `nic ip-config address-pool` commands work with LB or AppGateway backend pools

---

.github/ISSUE_TEMPLATE/Service_team_request.md

Adds a new issue template for service team feature requests. This is to help CLI team ensure the right minimum information needed to properly plan and implement the feature.

Add service team feature request template.

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_acr_deployment_function_app.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_acr_integration_function_app.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

Need to confirm the environment variable settings with @balag0 
\cc @panchagnula @dariagrigoriu @ahmedelnably 
---

[functionapp] - add ability to create functionapp from acr

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py

[Network] Update VNET peering create example

---

src/command_modules/azure-cli-monitor/HISTORY.rst
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/grammar/MetricAlertCondition.g4
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/grammar/MetricAlertConditionLexer.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/grammar/MetricAlertConditionListener.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/grammar/MetricAlertConditionParser.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_metric_alert_v2_scenario.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/test_monitor_metric_alert_scenarios.py

[Monitor] Allow dimension values to include *

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py

Fix DNS zone export example

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/disk_encryption.py

[vmss] encryption enable. Fix bug where command fails if ran previously.

---

src/command_modules/azure-cli-dla/HISTORY.rst
src/command_modules/azure-cli-dla/setup.py
src/command_modules/azure-cli-dls/HISTORY.rst
src/command_modules/azure-cli-dls/setup.py
src/command_modules/azure-cli-iot/HISTORY.rst
src/command_modules/azure-cli-iot/setup.py
src/command_modules/azure-cli-iotcentral/HISTORY.rst
src/command_modules/azure-cli-iotcentral/setup.py
src/command_modules/azure-cli-monitor/HISTORY.rst
src/command_modules/azure-cli-monitor/setup.py
src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/setup.py
src/command_modules/azure-cli-resource/HISTORY.rst
src/command_modules/azure-cli-resource/setup.py
src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/setup.py
src/command_modules/azure-cli-sql/HISTORY.rst
src/command_modules/azure-cli-sql/setup.py
src/command_modules/azure-cli-vm/HISTORY.rst

Fixing up trouble discovered by `azdev verify version`

Updating Version Numbers

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/_profile.py

Sanitize Error When invalid MSI ID is provided

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py

[Network] Tweak table format for `public-ip list/show`

---

src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/operations/sp.py

@tjprescott while testing new autorest found this.

Fix graphrbac import

---

src/azure-cli-core/azure/cli/core/_help_loaders.py

closes #8500 
I won't be adding a History.rst change because the help project was merged into dev after the release.
---

Remove unnecessary logging by HelpLoaderV1.

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_docker_utils.py

[ACR] Improve error message when not able to connect to registry

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_template_builder.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

Adds `--express-route-gateway-bypass` flag to `vpn-connection create/update`. Close #8360.
---

[Network] VPN connection create/update. Add flag.

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_constants.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_run_polling.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/build.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/run.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/task.py

The second (and last) batch to fix https://github.com/Azure/azure-cli/issues/8265
---

[ACR] Remove hard-coded SDK import

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_docker_utils.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_utils.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/custom.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/helm.py

This is mostly to help debug customers' sessions since we usually provide a more user friendly message but hide the exception.
---

[ACR] Add a few exception logs to assist debugging

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Closes https://github.com/Azure/azure-cli/issues/7914
---

Add port-forward listen-address option

---

README.md
doc/use_cli_effectively.md

2 things:
1. let us review to make sure the content is good that we can use it resolve a slew of doc bugs
2. We can discuss if there is a better place to park this doc

doc: pro tips of using CLI

---

build_scripts/windows/Product.wxs
build_scripts/windows/azure-cli.wixproj
build_scripts/windows/resources/CLI_LICENSE.rtf
build_scripts/windows/resources/ThirdPartyNotices.txt

brand: change to Microsoft Azure CLI

---

src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/recordings/test_application_set_scenario.yaml
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/test_graph.py

az ad app create/update: support app roles

---

src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/custom.py

Update KeyVault command module to use `get_models` instead of `get_sdk`.

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py

closes #6051 
closes #8518 
---

[vm] minor doc updates.

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

add cluster spn with metric publisher role to aks cluster resource during monitoring addon onboarding

---

doc/use_cli_effectively.md

Dedicated pass for wording. Added some extra stuff (space-separated lists for example).
---

Tweaks to CLI tips

---

.github/CODEOWNERS
src/azure-cli-core/azure/cli/core/extension/__init__.py
src/command_modules/azure-cli-batch/HISTORY.rst
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_client_factory.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_help.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_parameter_format.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_params.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_validators.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/custom.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/data/batchCreateJob.json
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/data/batchCreateJobScheduleForJobTests.json
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/generate_full_cli_help
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/generate_full_cli_help.bat
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_account_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_application_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_certificate_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_job_list_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_jobs_and_tasks.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_pool_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_pools_and_nodes.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_task_create_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/test_batch_commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/test_batch_data_plane_commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/test_batch_mgmt_commands.py
src/command_modules/azure-cli-batch/setup.py

---
@xingwu1 for review.
Fixes #8148 
Waiting on us publishing an updated version of our extension other wise there will likely be breakage

Update Batch CLI for latest REST API

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_format.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_ipsec.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_vpn_connection_ipsec.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py

Closes #8543. Closes #8359.
---

[Network] Vnet Gateway gaps

---

src/azure-cli-core/azure/cli/core/_profile.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/__init__.py

Clarifying `az account show --sdk-auth` error text.

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_client_factory.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

[Network] Fix VPN Connnection cross-subscription update scenario

---

src/azure-cli-core/setup.py

Remove upper limit on tabulate dependency.

---

src/azure-cli/HISTORY.rst
src/command_modules/azure-cli-servicefabric/HISTORY.rst
src/command_modules/azure-cli-servicefabric/azure/cli/command_modules/servicefabric/custom.py

issue-7910 fix service fabric list command

---

src/azure-cli-core/setup.py

Adding a guard to the `futures` requirement in azure-cli-core.

---

doc/use_cli_effectively.md

To clarify a few things encountered by Java team using fiddler to capture CLI's traffics.
//Cc: @iscai-msft  @anuchandy @praries880

doc: a few updates on how to use proxy

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_constants.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_on_linux.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

\cc @balag0 @ahmelsayed @panchagnula  @ahmedelnably 
---

[functionapp] fixes #8553 - set correct docker images

---

.travis.yml
scripts/ci/reject_master_prs.sh

Add check in CI to reject PRs to master branch

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/cloud.py
src/azure-cli-core/azure/cli/core/tests/test_cloud.py

Fix #8641 
I will add a couple of tests once CI is green

 bug: fix bogus error on switching clouds

---

tools/automation/cli_linter/rules/help_rules.py

This only adds nested args as commands if they are interpolation / substitution arguments.
---

[linter] Permit examples to contain arguments that start with 'az ' or contain a pipe '|' .

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

- Inform users of specific behaviours when they try to upgrade a cluster
to the current version of that cluster.
Skipped the HISTORY.rst since this is only logging, can add if prompted by maintainers (or anyone who disagrees).
---

[AKS] Improve messages for upgrade command

---

scripts/dependency/requirements.Darwin.external.txt
scripts/dependency/requirements.Linux.external.txt
src/command_modules/azure-cli-rdbms/HISTORY.rst
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mariadb_proxy_resources_mgmt.yaml
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mariadb_server_mgmt.yaml
src/command_modules/azure-cli-rdbms/setup.py

Update azure-mgmt-rdbms version to 1.7.0

---

src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/recordings/test_role_create_scenario.yaml
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/test_role.py

role definition update: use id to resolve definition correctly

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_params.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/import.py

[ACR] Fix a few unresolved comments in PR #8613

---

doc/use_cli_effectively.md
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py

help: add samples to feature register command

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py

Clarify that disabling OS disk encryption is unsupported on linux VMs.
#8671 
#8672 
---

[VM] Update encryption documentation

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_validators.py

Also clean up a few minor grammar mistakes.
---

[AKS] update old k8s versions in help and validation strings

---

scripts/temp_help/help_convert.py
src/azure-cli-core/azure/cli/core/_help_loaders.py
src/azure-cli-core/setup.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/test_custom.py
src/command_modules/azure-cli-acs/setup.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/tests/latest/recordings/test_container_export.yaml
src/command_modules/azure-cli-container/azure/cli/command_modules/container/tests/latest/test_container_commands.py
src/command_modules/azure-cli-container/setup.py
src/command_modules/azure-cli-find/azure/cli/command_modules/find/_gather_commands.py
tools/automation/cli_linter/__init__.py
tools/automation/cli_linter/linter.py
tools/setup.py

This PR:
- Restores pyyaml to non-beta version.
- Updates instances of yaml.load with yaml.safe_load
- Updates instances of yaml.dump with yaml.safe_dump
- Updates knack version for other work.
- Fixes #8703.
---

PyYaml fixes. Bump knack version.

---

src/command_modules/azure-cli-eventhubs/HISTORY.rst
src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/_params.py
src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/custom.py
src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/tests/latest/recordings/test_eh_alias.yaml
src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/tests/latest/recordings/test_eh_consumergroup.yaml
src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/tests/latest/recordings/test_eh_eventhub.yaml
src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/tests/latest/recordings/test_eh_namespace.yaml
src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/tests/latest/test_eventhub_commands.py
src/command_modules/azure-cli-eventhubs/setup.py

Added : eventhubs eventhub create/update: Added --skip-empty-archives flag to support empty archives in capture.
---

EventHubs: Added --skip-empty-archives flag to support empty archives in eventhub capture.

---

src/azure-cli-core/azure/cli/core/tests/test_cloud.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/azure-cli-core/azure/cli/core/tests/test_util.py
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/tests/latest/test_batchai_custom.py
src/command_modules/azure-cli-search/azure/cli/command_modules/search/tests/latest/test_admin_key.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

convert deprecated assertEquals

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/setup.py
src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-container/HISTORY.rst
src/command_modules/azure-cli-container/setup.py
src/command_modules/azure-cli-hdinsight/HISTORY.rst
src/command_modules/azure-cli-hdinsight/setup.py
src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/setup.py
src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/setup.py
src/command_modules/azure-cli-servicefabric/HISTORY.rst
src/command_modules/azure-cli-servicefabric/setup.py

Update Dev with previous release notes etc from release branch. 

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/file.py

---
Closes: https://github.com/Azure/azure-cli/issues/5662

[storage] add snapshot for file download-batch

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/blob.py

---
Fixes: https://github.com/Azure/azure-cli/issues/6364

[Storage] Improve progress reporting for blob upload/download batch commands

---

azure-cli2017.pyproj
src/azure-cli-core/azure/cli/core/cloud.py
src/command_modules/azure-cli-cloud/HISTORY.rst
src/command_modules/azure-cli-cloud/azure/cli/command_modules/cloud/custom.py
src/command_modules/azure-cli-cloud/azure/cli/command_modules/cloud/tests/latest/test_cloud.py

[Cloud] Fix cloud set name case sensitive

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/account.py

---
Fixes: https://github.com/Azure/azure-cli/issues/8715

[Storage] Storage encryption

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/azure/cli/core/util.py
src/azure-cli-testsdk/azure/cli/testsdk/patches.py

Direct users to github when unexpected error is raised.

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_client_factory.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_oauth.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_oauth.py

---
Fixes: https://github.com/Azure/azure-cli/issues/8759
Also, added testing for `blob show` in the oauth test suite, which is likely why the error went unnoticed.

[storage] fix bug with blob show using oauth

---

scripts/ci/test_automation.sh
src/command_modules/azure-cli-find/azure/cli/command_modules/find/custom.py

[find] remove nbsp

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py

webapp: az webapp up is not handling the empty code or unknown code case correctly

---

src/command_modules/azure-cli-resource/HISTORY.rst
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py

[Resource] Accept type `secureObject`

---

src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/recordings/test_graph_app_cred_e2e.yaml
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/test_graph.py

graph: support --end-date on credential reset

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_docker_utils.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_params.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/build.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/commands.py

Fixes https://github.com/Azure/azure-cli/issues/8798
Fixes https://github.com/AzureCR/azure-cli/issues/306
---

[ACR] Usability improvements, add '--no-wait' to 'acr build'

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py

Minor Doc Updates to `az ad` and `az vm encryption`

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py

This looks like it is probably just a typo

Fix incorrect populator command in vm image list-skus

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/acl.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/blob.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/file.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/table.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/sdkutil.py

[storage] pylint fixes for storage

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py

Document @<json_file> --settings parameter.

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py

[compute] pylint fixes for vm

---

azure-pipelines.yml

Invoke azdev to test command_module versions before release

---

.github/CODEOWNERS
src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/setup.py

[vm] Added image update. Added examples.

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py

webapp: Fixes SSL binding command for slots

---

src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/_params.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/custom.py

Add  --hub-name for show-connection-string command

---

azure-pipelines.yml

This will speed-up people doing the release.

Enable VerifyVersions phase for any activity against the release branch.

---

azure-pipelines.yml

Re-Enable Version Check in CI

---

requirements.txt
scripts/dependency/requirements.Darwin.external.txt
scripts/dependency/requirements.Linux.external.txt
src/command_modules/azure-cli-cdn/HISTORY.rst
src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/tests/latest/recordings/test_cdn_microsoft_standard_sku.yaml
src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/tests/latest/recordings/test_cdn_profile_delete_not_found.yaml
src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/tests/latest/test_profile_scenarios.py
src/command_modules/azure-cli-cdn/setup.py

- Added support for updated CDN SKUs (Standard_ChinaCdn, Standard_Microsoft)
- Added a test to verify #3304
- Changed the requirements.txt to not wipe out newer versions of pip
- Bumped the module version for CDN
- Sent mail to CDN team about adding a new specification for API Version 2018-04-02 (see #4475)
---

Add support for updated CDN SKUs

---

src/command_modules/azure-cli-kusto/HISTORY.rst
src/command_modules/azure-cli-kusto/setup.py

kusto dependency bug fix

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/extension/__init__.py

[Extensions] Fix version "Unknown"

---

scripts/dependency/requirements.Darwin.external.txt
scripts/dependency/requirements.Linux.external.txt
src/command_modules/azure-cli-container/setup.py
src/command_modules/azure-cli-hdinsight/setup.py
src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_completers.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_rewrite_rulesets.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py
src/command_modules/azure-cli-network/setup.py
src/command_modules/azure-cli-servicefabric/setup.py
src/command_modules/azure-cli-vm/setup.py

[Network] AppGateway RewriteRule GET commands

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/__init__.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_copy_cancel_nopendingcopyoperation_error.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_blob_scenarios.py

Only show the error instead of exception for NoPendingCopyOperation

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py

[Storage] Update the help message for lease_id

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py

[Storage] Add param help for public-access

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py

Update aks create --generate-ssh-keys help text.

---

README.md

Fixes #8602 
Fixes #8605
A new Release pipeline has been created which uploads the latest Homebrew formula and MSI each time the `dev` branch is updated. With the updates to our documentation, this is sufficient to close the issues enumerated above.
That is not to say that there are no improvements that could be made from here on our Edge build system. However, this is a good place to start.

Updating Edge installation instructions

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/blob.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_generate_sas_full_uri.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_blob_scenarios.py
src/command_modules/azure-cli-storage/setup.py

[Storage] Support --full-uri for storage blob generate-sas

---

src/azure-cli-core/azure/cli/core/util.py

Fixes #8762.
Adds a utility method `check_connectivity` to speed up the process of timing out on connectivity problems. Previously we just sent the request and waited for it to fail, but this proved far too slow. This method is designed to fail fast by default (though a connectivity failure is still slower than a success).
---

`az --version`: fail-fast on connectivity problems

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/blob.py

[Storage] Add more help message for storage blob delete-batch --dryrun

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_constants.py

\cc @ahmelsayed @ahmedelnably 
@yugangw-msft, given that this is just renaming our images, I am guessing this does not need an update to `HISTORY.rst`. Please correct me if I wrong and I can add an entry.

[functionapp] Update docker images name

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_file_copy_snapshot_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_file_scenarios.py

[Storage] Add snapshot support for az storage file copy start

---

doc/use_cli_effectively.md

Fixing minor typos

---

src/azure-cli-core/azure/cli/core/profiles/__init__.py
src/azure-cli-core/azure/cli/core/profiles/_shared.py
src/azure-cli-core/azure/cli/core/tests/test_help.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-storage/setup.py
src/command_modules/azure-cli-vm/setup.py

Add 2019-03-01-hybrid profile for Stack

---

src/command_modules/azure-cli-find/azure/cli/command_modules/find/custom.py

fix spaces and json conversion

---

src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/recordings/test_graph_app_cred_e2e.yaml
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/test_graph.py

create-for-rbac: fix a regression in handling --years

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py

[Storage] Remove blob delete result

---

src/azure-cli-core/azure/cli/core/extension/operations.py
src/azure-cli-core/azure/cli/core/extension/tests/latest/test_extension_commands.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-extension/azure/cli/command_modules/extension/custom.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/custom.py

Add interactive messages when extension install is in progress.

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_app_service_plan_linux.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

@ahmedelnably @dariagrigoriu @panchagnula 
---

[functionapp] fixes #8887 - add --is-linux support to functions plans

---

src/command_modules/azure-cli-monitor/HISTORY.rst
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/actions.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/grammar/MetricAlertConditionValidator.py

Fix missing aggregation "count"

---

src/azure-cli-core/azure/cli/core/extension/operations.py

---
Missed this in PR #8946 There is still a small time gap before I see the first message.

Minor improvement to interactive extension install experience

---

azure-cli2017.pyproj
src/command_modules/azure-cli-resource/HISTORY.rst
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_exception_handler.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py

Fix deployment create with empty params

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_move_plan_to_elastic.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

@panchagnula @jeffhollan @alexkarcher-msft @ahmedelnably 
---

[functionapp] fixes #8913 - allow function apps to change plan

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_format.py

[Network] Fix `list-bgp-peer-status` table output

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_constants.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_create_util.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_assign_system_identity.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

1. Node default version for Linux updated to 10.14 #8914
2. Added support to enable and view streaming logs using --logs argument (thank you @yugangw-msft ) #8666
3. the default naming convention for RG & ASP uses the logged in user name instead of appsvc as the prefix
4. Updated the help text for az webapp up
5. Zip deployment automatically enables logs & displays log (not streaming) before marking the deployment as Failure
---

webapp: az webapp up improvements

---

README.md

Now that our ADO pipeline has been tested for a month or so, and made a required part of PR validation, we should have a badge for it.

Adding ADO Badge to Readme

---

azure-cli2017.pyproj
src/command_modules/azure-cli-resource/HISTORY.rst
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py

Fix issues with `az resource` commands using ARM IDs.

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_docker_utils.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/helm.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/repository.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/latest/test_acr_commands_mock.py
src/command_modules/azure-cli-acr/setup.py

[ACR] Cleanup runtime access token scope

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_actions.py

Fix typo in `vm image show` error message.

---

src/command_modules/azure-cli-ams/HISTORY.rst
src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/operations/account_filter.py
src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/operations/asset_filter.py
src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/operations/job.py
src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/operations/sp.py
src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/tests/latest/recordings/test_ams_sp_create_reset.yaml
src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/tests/latest/test_ams_sp_scenarios.py
src/command_modules/azure-cli-ams/setup.py

Fix filter update bugs and pylint warnings

---

src/command_modules/azure-cli-sql/HISTORY.rst
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/custom.py

[SQL] Add wait/no-wait support for SQL server command group

---

src/command_modules/azure-cli-sql/HISTORY.rst

Moved elastic pool name history entry into correct release

---

src/command_modules/azure-cli-feedback/azure/cli/command_modules/feedback/custom.py

Tweaks the formatting and some wording of the generated template. Removes the "reaction" logic as it is not useful for debugging.

az feedback - Clean up formatting. Remove emoji.

---

.github/ISSUE_TEMPLATE/Bug_report.md

[feedback] update Bug_report.md to recommend az feedback.

---

.github/ISSUE_TEMPLATE/Bug_report.md
src/command_modules/azure-cli-feedback/azure/cli/command_modules/feedback/custom.py

az feedback - Minor style updates.

---

src/command_modules/azure-cli-eventgrid/azure/cli/command_modules/eventgrid/_help.py

Update help text for destination endpoint per customer feedback

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/disk_encryption.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/hybrid_2018_03_01/test_custom_vm_commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/test_custom_vm_commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_custom_vm_commands.py

ADE team has implemented this at the service end.

vm encryption: remove client end distro check

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/setup.py

Replaces #8561. cc: @brendandburns 
---

[AKS] add optional overwrite for duplicate kubeconfig values

---

scripts/dev_setup.py

Added new dev setup instructions to dev_setup.py

---

src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_format.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py

Include sku name in db & pool list-editions table

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py

[functionapp] Remove unused app settings for consumption plan

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp_ssh.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tunnel.py

https://github.com/Azure/azure-cli/pull/9098 without the ASE test
---

webapp ssh handles ASEs

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_create_util.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py

webapp: az webapp up supports an optional parameter to launch app in browser

---

src/command_modules/azure-cli-acs/setup.py
src/command_modules/azure-cli-servicefabric/setup.py
src/command_modules/azure-cli-vm/setup.py

Updating azure-mgmt-compute dependency

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py

[Resource] `role definition create` - fix typo.

---

src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py

create-for-rbac: hide --password as the preparations to pull the plug in 2019 May

---

src/command_modules/azure-cli-batch/HISTORY.rst
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_validators.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/README.md
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_pools_and_nodes.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/latest/test_batch_commands.py
src/command_modules/azure-cli-batch/setup.py

Please wait on @xingwu1 for merge---

Fix Batch application package reference bug

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py

[Network] Fix VNET peering help text

---

azure-pipelines.yml

Deleting previously commented-out Debian, Wheezy build, and adding Ubuntu, Disco build.

Support Ubuntu Disco Dingo

---

.vscode/launch.json
src/azure-cli-core/azure/cli/core/util.py

Adds msrest.exception.ValidationError to the global error handler so a stack trace is not thrown. These are not "unexpected" errors.
---

Globally handle msrest ValidationError

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp_ssh.yaml

customer was using a self-signed cert, so ssl check fails
add option to skip ssl check
---

webapp ssh handles AZURE_CLI_DISABLE_CONNECTION_VERIFICATION

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py

AKS: Remove preview flag for --network-policy

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/cloud.py
src/azure-cli-core/azure/cli/core/tests/test_cloud.py
src/azure-cli-core/setup.py
src/command_modules/azure-cli-configure/HISTORY.rst
src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/_params.py
src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/custom.py
src/command_modules/azure-cli-configure/setup.py

[configure] Add local configure support

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_constants.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_create_util.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py

webapp: Appservice plan free SKU support based on GeoRegions

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_validators.py

[ACR] Support build arg value propagated from environment variable

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp_remote_debug.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp_remote_ssh.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tunnel.py

port remote-connection to cli-core
---

webapp add remote-connection

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp_remote_debug.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp_remote_ssh.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp_ssh.yaml

reran tests for create-remote-connection
---

[webapp] create-remote-connection tests

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py

webapp create checking SKU name fix

---

doc/use_cli_effectively.md

It was mentioned in https://github.com/Azure/azure-cli/issues/8766 that this page should be updated with usage instructions.
---

Document use of AZURE_CONFIG_DIR

---

doc/authoring_command_modules/README.md

Thank to Mike Kinsman for the link!

Add docs generation link to command authoring table of contents.
