azure-cli.pyproj
src/azure/cli/commands/client_factory.py
src/azure/cli/utils/vcr_test_base.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/generated.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/recordings/test_role_assignment_scenario.yaml
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/test_role.py

Notes:
1. The main focus is on the role assignment creation. The PR also contains graph object query command and `user create` so that i can test end to end
2. The new command greatly simplifies the interface, with no function loss, this PR shrinks parameters number from 10 down to 4
xplat's
```
role assignment create [objectId] [signInName] [spn] [roleName] [roleId] [scope] [resource-group] [resource-type] [resource-name]
```
cli's
```
role assignment create <assignee> <role> [resource_group] [resource_id]
Arguments
--assignee [Required]: Represent a user, group, or service principal. supported format: object
id, user sign-in name, or service principal name.
--role     [Required]: Role name or id.
--resource-group -g  : Name of resource group.
--resource-id        : Resource id.
```

RBAC: role assignment creation

---

azure-cli.pyproj
scripts/command_modules/pylint.py
src/azure/cli/commands/__init__.py
src/azure/cli/commands/_introspection.py
src/azure/cli/commands/arm.py
src/azure/cli/tests/test_command_registration.py
src/azure/cli/tests/test_generic_update.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py

Allows an update command to be registered, which then updates fields with a generic
set/add/remove syntax.  I added az vm update along with the infrastructure.
```
Command
az vm update: Update VM properties.
Update VM objects and properties using paths that correspond to 'az vm show'.  See examples.
Arguments
--add              : Add an object to a list of objects by specifying a path and key value
pairs.  Example: --add property1.list id=<id>.
--api-version      : Client Api Version.  Default: 2016-03-30.
--expand           : The expand expression to apply on the operation.
--ids              : ID of resource.
--name -n          : The name of the virtual machine.
--remove           : Remove a property or an element from a list.  Example: --remove
property1.list <index>.
--resource-group …
```

Generic Update Command support.  

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py

NIC names were not being completed.
e.g.
`az network nic show -g myrg -n <tab>`
Should list the available nics in myrg but this did not happen.
This PR resolves this.

Add missing completer for network_interface_name parameter

---

src/azure/cli/_profile.py
src/azure/cli/tests/test_profile.py

@ahmetalpbalkan , i do it on newly created file, just in case people might have tweaked to other permissions they prefer.

fix #571: accessTokens.json is 0644

---

src/azure/cli/_help.py

Fixes #581.
Example output:
```
$ az --help
For version info, use 'az --version'
...
```

Document 'az --version' under 'az --help' command

---

src/command_modules/azure-cli-component/azure/cli/command_modules/component/generated.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/generated.py

This PR focuses on the get/list/show commands.

VM table outputs

---

azure-cli.pyproj
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_params.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/generated.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/generated.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/recordings/test_application_set_scenario.yaml
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/recordings/test_sp_create_scenario.yaml
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/test_graph.py

1. Create
2. Update
3. show and delete get improved by accepting both object id or logic identifier names
4. Move `account create-sp` to `ad sp create-for-rbac`

graph: full support for applications and service principals

---

src/azure/cli/commands/arm.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/generated.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/test_network_load_balancer_subresources.yaml

Adds commands for application gateway subresources. Due to the performance issues with app-gateways, there are currently no VCR tests for the subresource commands.
Also, note that there are no update commands for these subresources, for a couple reasons:
1. XPlat does not have set/update commands for these.
2. You can use the generic `az network application-gateway update --set [...]` to update.

Application-Gateway Commands

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/__init__.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_factory.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/custom.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/generated.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_queue_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_table_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage.py

This PR adds the bulk of the commands required by issue #641 and #642. There will be a third PR that puts the finishing touches on certain commands across all four services. Known issues:
- `table batch` commands currently do not work
- `queue/table stats` commands require no parameters, but throw exceptions (possible service issue)
- `entity query` currently uses an OData filter. This may or may not be acceptable.
- `blob/file/table/queue generate-sas` commands will be addressed in the next PR.
- `blob/file/table/queue service-properties update` will be addressed, if possible, in the next PR.

Storage Module Updates Part 2: Table and Queue

---

src/azure/cli/commands/__init__.py
src/azure/cli/commands/arm.py
src/azure/cli/parser.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_command_type.py

After our discussion today, and after experimenting with a more complex mechanism, I believe this simple implementation is sufficient to cover items #656, #676 and #677. Some things to point out:
- The ordering in --help is not ideal. Global args should be at the bottom. However, this would necessitate changes to the help formatter that can be addressed in a separate PR.
- I removed any "dynamic help" so that the help output is consistent from one invocation to the next.
- Having help text for the group (either a paragraph or usage string) is not advisable for a few reasons. (1) it would necessitate changes to the help file format (which currently doesn't allow argument group help), (2) text does not wrap well and (3) all groups are backed by a validator which will give a useful error if …

Custom Argument Groups

---

appveyor.yml

* By default, python 2.7 is in PATH of AppVeyor build machine. We want to use python 3.5 for Sphinx to make xml.
* Pass repo branch url for AzCliDocPreprocessor

Use python 3.5 explicitly for document CI and pass repo url

---

azure-cli.pyproj
src/azure/cli/commands/__init__.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_factory.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/custom.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/generated.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_blob_acl_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_file_acl_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_queue_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_table_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_validators.py

Addresses issues #421, #640, #641 and #642.
- Enhancements to ACL policy and SAS permissions
- Adds the following storage subcommands: cors, logging, metrics
- Renames `share contents` to `file list`
- Adds support for previously unsupported parameters (`encryption`, `content-settings`)

[Storage] Storage Updates Round 3

---

scripts/dump_help.py

Adds a simple utility script to dump command help for the purpose of service team reviews.
Example usage:
`python scripts\dump_help.py --commands storage > storage_help.txt`

Add dump_help.py script.

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/generated.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vmss_diagnostics_install.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vmss_extension_install.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

Implements part of #555 and follows the same pattern as vm extensions

enable diagnostics and extensions in vmss profile

---

src/azure/cli/commands/parameters.py
src/command_modules/azure-cli-component/azure/cli/command_modules/component/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_params.py
src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/_params.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/_params.py

Removes all instances of the old anti-pattern and replaces them with the current best-practices.
```Python
register_cli_argument('scope', 'dest', CliArgumentType(a=b, c=d))  # anti-pattern!
register_cli_argument('scope', 'dest', a=b, c=d) # do it this way
myarg = CliArgumentType(x=y, m=n) # only do this if you will reuse the definition
register_cli_argument('scope1', 'dest', myarg) # direct reuse
register_cli_argument('scope2', 'dest', myarg, m=p) # reuse with modification
```
Addresses issue #742.

Remove inline CliArgumentType(...) registrations

---

azure-cli.pyproj
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/mgmt_vmss/azuredeploy.json
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/mgmt_vmss/lib/models/deployment_vmss.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/mgmt_vmss/lib/models/template_link.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/mgmt_vmss/lib/operations/vmss_operations.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/mgmt_vmss/nested_templates/nat_rules_new.json
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/mgmt_vmss/nested_templates/nat_rules_none.json
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/mgmt_vmss/swagger_create_vmss.json

Add NAT Rules to VMSS create that allow SSH/RDP by default

---

src/azure/cli/_output.py
src/azure/cli/tests/test_output.py

Fixes the issue with caps from issue #147.  Now the output would look like:
```
$ az vm list --out list --query "[].{NAME: name, alsoNAME: name}"
Name : vm1
Also Name  : vm1
```

Update regular expression to fix issue #147

---

src/azure/cli/_config.py
src/azure/cli/application.py
src/azure/cli/tests/test_config.py
src/command_modules/azure-cli-configure/README.rst
src/command_modules/azure-cli-configure/azure/__init__.py
src/command_modules/azure-cli-configure/azure/cli/__init__.py
src/command_modules/azure-cli-configure/azure/cli/command_modules/__init__.py
src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/__init__.py
src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/_help.py
src/command_modules/azure-cli-configure/setup.py

Fixes https://github.com/Azure/azure-cli/issues/657
- Allows user to set default output type.
- Infrastructure for CLI configurations also implemented.
```
$ az configure
Welcome to the Azure CLI! This command will guide you through logging in and setting some default values.
Your global settings can be found at /Users/derek/.azure/config
Your current environment settings can be found at /Users/derek/.azure/env_config/default
Your current configuration is as follows:
[core]
output = json
Environment variables:
AZURE_STORAGE_ACCOUNT = derekstorageaccount
Do you wish to change your global settings? (y/N): y
What default output format would you like?
[1] json - JSON formatted output that most closely matches API responses
[2] jsonc - Colored JSON formatted output that most closely matches …
```

'az configure' experience (default output format)

---

requirements.txt
setup.py
src/azure/cli/_output.py
src/azure/cli/application.py
src/azure/cli/tests/test_output.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py

Fixes #705, fixes #704, fixes #652
- Table output is generic and automatically extracts fields from the result.
- No longer use simple_output_query as it was specific for commands and as packages will support multiple API versions, this solution is no longer feasible.

Table format revisions

---

src/command_modules/azure-cli-feedback/azure/cli/command_modules/feedback/__init__.py

Fixes #594. Note that depending on what threads are running when you press Ctrl+C you may get a stack trace for other reasons.

[Feedback] Catch EOFError during 'az feedback'

---

doc/authoring_command_modules/authoring_commands.md
src/azure/cli/_output.py
src/azure/cli/application.py
src/azure/cli/commands/__init__.py
src/azure/cli/commands/arm.py
src/command_modules/azure-cli-component/azure/cli/command_modules/component/generated.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/generated.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/generated.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/generated.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/generated.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_command_type.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/generated.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/generated.py

- Clean up from the table revisions.
- Removal of simple_output_query with JMESPath as it wasn't dynamic enough for our needs.

Table revisions prt 2 (clean up)

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/test_feature_list.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/test_group_deployment.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/test_provider_registration.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/test_resource_group.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/test_resource_move.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/test_resource_policy.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/test_resource_scenario.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/test_tag_scenario.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_resource.py

Fixes #763. Also partially addresses #675 for the resource module.

[Resource] Resource Tag Fix (issue 763)

---

appveyor.yml

Due to changes of content repo structure, we only delete certain files and all subfolders in yml output folder during Document CI.

Only delete certain files in yml output folder during Document CI

---

src/azure/cli/commands/arm.py
src/azure/cli/tests/test_generic_update.py

This PR fixes #686 and fixes #728.
Allows indexing into a collection via unique key instead of just index.

Generic Update enhancements.

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/generated.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/generated.py

cmd: use plurals for list-* command naming

---

src/azure/cli/_help.py

Certain SDK docstrings contain unicode characters that cause the help system to throw an error. This PR handles that case.

[Help] Fix UnicodeError When Importing SDK DocStrings

---

src/azure/cli/application.py

Fix config not taking default output type from config file after section name change from 'core' to 'default'.

Load default output type from config correctly.

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py

fix #700, fix #703
1. Ensure to parse `years` parameter as integer
2. Avoid referencing guid in the output of `create-for-rbac`

rbac: bug fixes on create sp for rbac commands

---

src/azure/cli/application.py
src/azure/cli/commands/client_factory.py

Also fixed an issue where the command name header was not set for any calls happening in the validate arguments phase.

Provide UA string and x-ms-client-request-id for storage data plane operations

---

scripts/dump_command_table.py
src/azure/cli/application.py
src/azure/cli/commands/__init__.py
src/azure/cli/commands/arm.py
src/azure/cli/tests/test_resource_id.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py

Fixes #732, fixes #656. Follows the guidance that if we cannot directly access the object of interest with `--ids`, we do not expose `--ids` at all. 
Makes updates so that `--ids` correctly appears in the command table when using the `dump_command_table.py` script.
Adds common language to the IDs parameter help text "If provides, no other 'Resource Id' arguments should be specified."

Clean-up IDs parameters

---

src/azure/cli/application.py
src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/__init__.py

- 'core' will correspond to the core module of the CLI. We will have a module called 'core' anyway.
- 'default' is a special section in ConfigParser that operates differently from other sections.
On Python 2.7, we get a `ValueError` using the section name default:
```
root@d662de122eab:/# az configure
Welcome to the Azure CLI! This command will guide you through logging in and setting some default values.
Your global settings can be found at /root/.azure/config
What default output format would you like?
[1] json - JSON formatted output that most closely matches API responses
[2] jsonc - Colored JSON formatted output that most closely matches API responses
[3] table - Human-readable output format
[4] tsv - Tab and Newline delimited, great for GREP, AWK, etc.
Please enter a choice [1]: …
```

Change section name from 'default' to 'core'

---

azure-cli.pyproj
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/generated.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/test_network_dns_zone_import_export.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/zone.txt
src/command_modules/azure-cli-network/azure/cli/command_modules/network/zone_file/__init__.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/zone_file/configs.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/zone_file/exceptions.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/zone_file/make_zone_file.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/zone_file/parse_zone_file.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/zone_file/record_processors.py
src/command_modules/azure-cli-network/setup.py

List record sets (one line change), dns zone import and dns zone export.  Fixes #721 
Export Data flow: load all record sets from the zone, for each record set and each record set’s records, create a dict of the fields that conforms to the zone_file format (most of our changes), then zone_file converts the dict to the canonical zone file format.
The import data flow is the reverse of export.  We don't allow import over the top of existing zones; this is a difference compared to xplat, which has a “force” option.  Given that the force option implementation would essentially be deleting and re-creating the record sets, I left it to the user to delete their record set if they run into a situation where they want to create it from scratch again.
Zone_file: the zone_file library lives at …

DNS Zone import/export.  

---

doc/sphinx/azhelpgen/azhelpgen.py
src/azure/cli/_help.py

Add group ordering system so Global Arguments is at the bottom again.  Unblock doc generation script so --ids show in the output and unicode characters don't fail the sphinx build.

Help polish, unblock doc generation

---

doc/sphinx/azhelpgen/azhelpgen.py

fix doc generation error:
`AttributeError: 'str' object has no attribute 'decode'`

should not use str.decode because doc CI uses Python 3

---

src/azure-cli-core/azure/cli/core/tests/test_help.py

Python lstrip removes any of the provided characters from the left end of the string.
```
'aaaaaaaabbbbbbbc'.lstrip('ab') => 'c'
'az account list'.lstrip('az ') => 'ccount list'
'az account list'[len('az '):] => 'account list'
```

Updated command name parsing

---

src/azure-cli-core/azure/cli/core/adal_authentication.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_params.py

fix #856
Also simplify the parameter name from `--subscription-or-id` to `--subscription`. The old one is too verbose, and the description in help has called out both id and name can work

login: capture error caused by expired refresh token

---

src/azure-cli/azure/cli/__main__.py

tested that Ctrl+C is not blocked by the telemetry thread on Windows and Linux

Fixes #883 Telemetry on Ctrl+C

---

src/azure-cli-core/azure/cli/core/commands/arm.py
src/azure-cli-core/azure/cli/core/tests/test_generic_update.py

This PR:
- Fixes #824
- Fixes #851
- Adds the ability to add scalars to a list as well as empty lists and dictionaries. Consecutive key=value entries are grouped into a single dict entry. Non-consecutive key=value entries get placed into separate dicts.

[Generic Update] Fixes and Enhancements

---

src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/custom.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/tests/test_webapp_commands.py

otherwise, the command emit out errors when the output format is `table`

webapp: use json when return git url

---

scripts/nightly/nightly-build.sh

Adding .dev<DATE> to a version number actually makes the version LESS than the published version.
e.g. 0.1.0b4 > 0.1.0b4.dev20160920
In this fix, we would modify 0.1.0b4 to 0.1.0b4+1.dev20160920
and 0.1.0b4+1.dev20160920 > 0.1.0b4.dev20160920

Fix nightly version modification

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/_util.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py

With this PR, access token persisting is consistent with the rest system

use common utils to persist accessTokens.json

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/commands/client_factory.py
src/azure-cli-core/azure/cli/core/utils/vcr_test_base.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/test_role.py

It is a pretty useful under RBAC context. The resource id could come from another subscriptions
Also, the change inside core will be used in near future when we introduce the global flag `--subscription` #807.

Able to create role assignments under other subscriptions

---

src/azure-cli-core/azure/cli/core/commands/parameters.py
src/azure-cli-core/azure/cli/core/commands/validators.py
src/azure-cli-core/azure/cli/core/tests/test_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

This was something we did initially because Xplat does this, but we use space-separated lists everywhere else. Figured it would be good to make tags behave the same way before Ignite.

Update tags type to be space separated, not semicolon separated

---

src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/_params.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/custom.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/tests/test_webapp_commands.py

The background is webapp team updated it in xplat this week, in order to push the `sku` concept, so azure-cli follow.
Because the sku's naming and type definition are quite confusing in SDK, so in code, i still keep the `tier`, and just do alias at the command layer.

webapp: change '--tier' to '--plan'

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py

Breaking details: parameters order were changed. Because those are body bound ones rather request url bound, our VCR tests are not able to catch it. I am still trying to figure out how the regression testing should be written

fix breaks caused by SDK change

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py

Added examples and links to capture related commands for a demo of the upcoming doc system.
```
$ ./az vm capture -h
Command
az vm capture: Captures the VM by copying virtual hard disks of the VM and outputs a
template that can be used to create similar VMs.
See https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-capture-
image/ for an end-to-end tutorial.
Arguments
--vhd-name-prefix [Required]: The VHD name prefix specify for the VM disks.
--overwrite                 : Overwrite the existing disk file.  Default: True.
--storage-container         : The storage account container name to save the disks.  Default:
vhds.
Resource Id Arguments
--ids                       : One or more resource IDs. If provided, no other 'Resource Id'
arguments should be specified. …
```

Updated capture related commands with examples

---

src/azure-cli-core/azure/cli/core/_output.py
src/azure-cli-core/azure/cli/core/commands/client_factory.py
src/azure-cli-core/azure/cli/core/tests/test_output.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py

Fixes #968, fixes #940, fixes #893 
- Handles table output when using [].[props...] notation instead of [].{key:val..} notation by using generic headers.
- Enables tab completion for `az storage file/blob upload/download`
- Prints a more useful error message when improperly formatted connection parameters prevent creating a storage data client.

Fixes #968, #940, #893

---

README.rst

- Also, I've added the '$ sudo apt-get install apt-transport-https' though on Ubuntu it should come already installed and you'd just get 'apt-transport-https is already the newest version.'.

Use APT repository instead of Azure Storage blob container & update docs

---

src/azure-cli-core/azure/cli/core/commands/client_factory.py
src/azure-cli-core/azure/cli/core/utils/vcr_test_base.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/generated.py

Fixes #956. This is a workaround only until https://github.com/Azure/azure-rest-api-specs/issues/570 is fixed.

[VMSS] Temporarily override api-version for 'vmss nic' operations

---

src/azure-cli-core/azure/cli/core/_help.py
src/azure-cli-core/azure/cli/core/tests/test_help.py

[Help] Fix inherited line breaks in help long summary

---

src/azure-cli-core/azure/cli/core/_help.py
src/azure-cli-core/azure/cli/core/tests/test_help.py

Fixes #976. Previously any group not within the static "priorities" dictionary in the _help.py file was assigned a priority of 1, meaning many groups shared the same priority. When the parameters were then sorted alphabetically, it could result in multiple group labels being printed. This solution ensures argument groups not in the static dictionary (a) don't need to be added and (b) don't have overlapping priorities.

[Help] Fix argument group ordering.

---

src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/_help.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/_params.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/custom.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/generated.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/tests/recordings/test_webapp_config.yaml
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/tests/test_webapp_commands.py

Note: had to rename to "resource_group" to "resource_group_name", so tab completion would work
```bash 
Command
az appservice web config hostname add: Bind a hostname(custom domain) to the app.
Arguments
--slot             : The name of the slot. Default to the productions slot if not specified.
Resource Id Arguments
--ids              : One or more resource IDs. If provided, no other 'Resource Id' arguments
should be specified.
--name -n          : Hostname assigned to the site, such as custom domains.
--resource-group -g: Name of resource group.
--webapp           : Webapp name.
Command
az appservice web config hostname list: List all hostname bindings.
Arguments
--slot             : The name of the slot. Default to the productions slot if not specified.
Resource Id Arguments
--ids …
```

webapp: support hostname

---

src/azure-cli/az
src/azure-cli/az.bat
src/azure-cli/azure/cli/__main__.py
src/azure-cli/setup.py

Reverts Azure/azure-cli#1014
Using the entry_points/console_scripts feature of setuptools has some drawbacks so reverting back to our own script files.
Drawbacks:
- It can be slow.
- In the script that setuptools creates, it imports `pkg_resource` which takes a significant time of the total 'az' load time (~50%).
- It does some version checking that can prevent 'az' from loading when 'az' can in-fact load fine.

Revert "Use setuptools entry_points for az executable"

---

.travis.yml

.travis.yml should use dev_setup.py install of duplicating the same functionality.
This means changes to dev_setup.py would reflect in CI straightaway.

.travis.yml should use dev_setup.py

---

src/azure-cli-core/azure/cli/core/commands/parameters.py
src/azure-cli-core/azure/cli/core/tests/test_parser.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/_params.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/_params.py
src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/tests/test_redis_params.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/_params.py

Fixes #829.  We had a lot of wonkiness centered around choice lists within the CLI. Due to confusion on the meaning of "modelAsString" some enums were exposed as completers, others had a choice list without the 'str.lower' component to make them case insensitve, etc. Also, that approach generally destroyed the case information when displayed in help so an enum value that was `MixedCasedForReadabilty` would appear as `mixedcaseforreadability`.
This PR creates a simple way of exposing SDK-style enums.
```Python
from azure.cli.core.commands.parameters import enum_choice_list
register_cli_argument('scope', 'dest', **enum_choice_list(MyEnum))
```
This essentially adds a consistent `choices` entry that does a case insensitive comparison of the value against the enum values, as well as a …

Case insensitive choice lists

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/generated.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_resource.py

1. Move `resource provider` to top:  `provider`
2. Enable tab completion on `provider` commands
3. Enable tab completion on `resource show --resource-type`
4. Remove `exists` command. ARM team has started the API will retire in near future.
Fix portion of #1033, portion of #1039

ARM: provider command and resource show command improvements

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py

//cc:@derekbekoe @ahmetalpbalkan 
This does what we want; however the shortcoming (minor, imo) is I hard code on json text to stdout. This ensures samples(logged by command to stderr) comes after the stdout. Normally dumping result to stdout is handled by core module after the custom handler exits, but this will cause sample commands get dumped before the SP info, which is odd.
It is very doable to share code at [core module](https://github.com/Azure/azure-cli/blob/master/src/azure-cli/azure/cli/main.py#L37-L39) to manipulate the format at command level, but not so sure whether it is worthwhile, considering the command has its own unique output format anyway.
```bash
{
"client_secret": "c24fb79b-c0c7-48e3-a939-123456789012", 
"client_id": "8c25c617-8ee3-45fa-836b-123456789012", …
```

create-for-rbac: output sp information in json format to stdout for easy scripting

---

src/azure-cli-core/azure/cli/core/commands/__init__.py

As discussed, this is a temporary work-around as https://github.com/Azure/azure-cli/issues/1110 has not been implemented yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/azure-cli/1111)

Logic to allow acs commands to be loaded from multiple modules

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/win_proxy.py

With this change, IE and Edge will route the traffic through the proxy. For Chrome, this setting was not needed as it worked without it.

Adding <-loopback> to the exceptions list

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/generated.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

Notes:
1. Expose `scale` command which updates the private agent count, a common scenario.
2 Hide the `update`, as there are nothing else people can tweak. The `tagging` coming with the generic update can be accomplished by `az resource tag`.

acs: expose scale command

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/_util.py
src/azure-cli-core/azure/cli/core/cloud.py
src/azure-cli-core/azure/cli/core/commands/client_factory.py
src/azure-cli-core/azure/cli/core/context.py
src/azure-cli-core/azure/cli/core/tests/test_cloud.py
src/azure-cli-core/azure/cli/core/tests/test_context.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/azure-cli-core/azure/cli/core/tests/test_util.py
src/command_modules/azure-cli-cloud/azure/cli/command_modules/cloud/custom.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_validators.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_factory.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py

Making this change based off feedback from the previous PR https://github.com/Azure/azure-cli/pull/1098#discussion_r84160252
(this is an internal change and doesn't affect the 'az cloud' or 'az context' commands)

Use objects for CloudEndpoints and CloudSuffixes instead of dicts

---

src/command_modules/azure-cli-component/azure/cli/command_modules/component/custom.py

1. Fix should return error exit code if the command fails
2. Show 'Permission denied.' instead of full stacktrace if user attempts operation they don't have permissions for.
3. Send pip logs to CLI debug logs.
Fixes https://github.com/Azure/azure-cli/issues/1049, fixes https://github.com/Azure/azure-cli/issues/1050, fixes

Improvements to the 'az component' commands

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py

commands: fix invalid helo texts in 'role' and 'resource' modules

---

scripts/curl_install_pypi/install.py

Instead of using command.split(), pass in the command to execute as a list always
See https://github.com/Azure/azure-cli/issues/1070
virtualenv and pip don't work well with spaces in paths though so installs with spaces will still fail until that's addressed:
https://github.com/pypa/virtualenv/issues/53
https://github.com/pypa/pip/issues/923

Fixes curl install with space in custom install path

---

src/command_modules/azure-cli-vsts/azure/cli/command_modules/vsts/custom.py

Verifies docker-compose and docker file exist somewhere in the repo, not just the root

Maduong/bugfix/282569 the cli should look for a compose file anywhere in the folder (not just at the root)

---

scripts/command_modules/package_verify.py
src/command_modules/azure-cli-acr/setup.cfg
src/command_modules/azure-cli-acs/setup.cfg
src/command_modules/azure-cli-cloud/setup.cfg
src/command_modules/azure-cli-component/setup.cfg
src/command_modules/azure-cli-configure/setup.cfg
src/command_modules/azure-cli-context/setup.cfg
src/command_modules/azure-cli-feedback/setup.cfg
src/command_modules/azure-cli-iot/setup.cfg
src/command_modules/azure-cli-keyvault/setup.cfg
src/command_modules/azure-cli-network/setup.cfg
src/command_modules/azure-cli-profile/setup.cfg
src/command_modules/azure-cli-redis/setup.cfg
src/command_modules/azure-cli-resource/setup.cfg
src/command_modules/azure-cli-role/setup.cfg
src/command_modules/azure-cli-storage/setup.cfg
src/command_modules/azure-cli-taskhelp/setup.cfg
src/command_modules/azure-cli-vm/setup.cfg
src/command_modules/azure-cli-vsts/setup.cfg
src/command_modules/azure-cli-webapp/setup.cfg

When publishing on PyPI, we should publish both .tar.gz and .whl files.
Add setup.cfg files
- Update package-verify and nightly-build to use bdist_wheel also

Support packaging as .whl files

---

doc/sphinx/azhelpgen/doc_source_map.json
src/azure-cli/setup.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/generated.py

@rgardler @ahowe
This is my first PR to the Azure CLI, please advise if I'm doing it wrong...

Add a simple command that knows how to download the dcos client.

---

src/azure-cli/setup.py
src/command_modules/azure-cli-acs/setup.py

With a recent commit, the `six` dependency was added to the azure-cli module when it should have been added for azure-cli-acs.

Move six dependency to the correct command module

---

src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/_help.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/_params.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/custom.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/generated.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/mgmt_iot_hub_device/lib/operations/iot_hub_devices_operations.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/mgmt_iot_hub_device/swagger_iot_hub_device_identity.json
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/tests/recordings/test_iot_hub.yaml
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/tests/test_iot_commands.py

Help messages for each command are listed as below. Global arguments are omitted.
```bash
>az iot hub show -h
Command
az iot hub show: Show non-security metadata of an IoT Hub.
Arguments
--name -n [Required]: The IoT Hub name.
--resource-group -g : Name of resource group.
```
```
>az iot device show -h
Command
az iot device show: Show metadata of a device in an IoT Hub.
Arguments
--device-id -d [Required]: Device Id.
--hub-name     [Required]: The IoT Hub name.
--resource-group -g      : Name of resource group.
```
```
>az iot device delete -h
Command
az iot device delete: Delete a device from target Azure IoT Hub.
Arguments
--device-id -d [Required]: Device Id.
--hub-name     [Required]: The IoT Hub name.
--etag                   : ETag of the target device. It is used for the purpose of …
```

[IoT] add commands `iot hub show`, `iot device show` and `iot device delete`

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/generated.py

Address #1162
This contains a managable hack around azure/autorest#1558. We are working actively to fix that at autorest.

VM:  lro poller for vm create should use shorter timeout of 5 seconds

---

requirements.txt
src/azure-cli-core/setup.py
src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/_consts.py
src/command_modules/azure-cli-profile/setup.py

adal:upgrade to 0.4.2

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_format.py

Fixes #1220 
new table output:
```
NAME              RESOURCE GROUP      LOCATION        LOGIN SERVER                     CREATION DATE                     ADMIN ENABLED
----------------  ------------------  --------------  -------------------------------  --------------------------------  ---------------
sivagtest8        myrg1               eastus          sivagtest8-exp.azurecr.io        2016-11-03T20:48:56.901793+00:00  True
kevinregistry3    kevinrg             southcentralus  kevinregistry3-exp.azurecr.io    2016-11-03T17:15:57.735790+00:00  True
kevinregistry4    kevinrg             southcentralus  kevinregistry4-exp.azurecr.io    2016-11-03T17:32:58.403066+00:00  True
```

remove unnecessary columns in acr table output: fixes #1220

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/application.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_help.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_params.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/commands.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py

account: expose show command

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/setup.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_acs_create_update.yaml
src/command_modules/azure-cli-vm/setup.py

Upgrade the container/compute library to 0.32.0

---

.gitignore
scripts/command_modules/_common.py
scripts/command_modules/test.py

Running test modules in parallel. On my machine it reduces running time from 16 minutes to around 9 minutes.
The actual running time is shorter then that. I'm going to profile the test further to figure out where were the time spent on.
```
Summary
========================
acr        skipped                     
acs        passed  16:38:04  16:38:07  
cloud      skipped                     
component  skipped                     
configure  skipped                     
container  skipped                     
context    skipped                     
feedback   skipped                     
iot        passed  16:38:04  16:38:13  
keyvault   passed  16:38:04  16:38:31  
network    passed  16:38:04  16:42:15  
profile    skipped                     
redis      passed  16:38:04  16:38:07 …
```

Run module tests in parallel

---

src/azure-cli-core/azure/cli/core/commands/arm.py

Fixes #1254.
The validator for the `--ids` parameter raised a CLIError if it failed. After change #1037, CLIErrors thrown from a validator no longer cause the usage string to be printed. Thus, to ensure that a usage string is thrown when `--ids` usage is incorrect, this error was changed to a ValueError, which is the most common approach used by existing validators.

Ensure '--ids' validation failure prints usage string

---

azure-cli.pyproj
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_util.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py

Fixes #1239, fixes #1240.
Plan to defer merging this until #1059 is merged.

[Network] Fix Network Bugs 1239, 1240

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/recordings/test_acr.yaml
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/test_acr_commands.py

To address issue https://github.com/Azure/azure-cli/issues/1201

Added tests for acr command module

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/acs_client.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/commands.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/setup.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

@yugang-msft
Thanks!
--brendan

Add Kubernetes support to ACS.

---

azure-cli.pyproj
src/command_modules/azure-cli-acr/README.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_params.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/credential.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/custom.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/repository.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/test_acr_commands.py

This PR renames --admin-user-enabled to --admin-enabled on create and update operations.
Usage:
- az acr update -n ... [--admin-enabled true/false]
- az acr create ... [--admin-enabled true/false]
Also removed short flags -a and -s in readme for update operation. Additionally, updates descriptions to match new swagger file.

rename to --admin-enabled on update/create for acr operations

---

src/azure-cli-core/azure/cli/core/commands/validators.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_command_type.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_params.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_validators.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/commands.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/custom.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/recordings/test_keyvault_certificate.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/recordings/test_keyvault_secret.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/test_keyvault_commands.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/test_secret.txt

Closes #885.
This PR updates the `secret set` command and adds the `secret download` and `certificate download` commands. With this, the entire KeyVault data plane functionality should be exposed.
Plan to defer merging this until #1059 is merged.

[KeyVault] KeyVault Round 4 Commands

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/test_webapp_slot.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py

Ensure supports from create, link to git, swap, to deploy. Those are still the minimum, but enough to get basic functions.  This will get #1255 resolved.
In the next period, we should consider to 
1. enable private git repo.
2. create slot from existing configuration sources
3. extend `slot delete` to support auto delete site, etc

web: initial slot end to end support

---

scripts/run_pylint.py

The full output pollutes CI output and makes it hard to find the pylint errors.
Reporting was disabled before the recent pylint perf change and I think it should still be disabled now.

Prevent CI pylint from showing the full report

---

doc/sphinx/azhelpgen/azhelpgen.py

- Fix error running azhelpgen.py
-- To load the full command table with all parameter values, we iterate over the command table running -h on each command.

Fix Document CI error due to command params not being loaded

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/commands.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Fixes https://github.com/Azure/azure-cli/issues/1321
@lostintangent

Add `az acs kubernetes browse` and also open a web browser.

---

README.rst

Add temporary note for workaround for https://github.com/Azure/azure-cli/issues/1360.

Update install page with workaround for requests bug

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_params.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py

Per ask from java sdk team. Fix #1097. I updated some naming so this whole thing won't look odd.
Once we are fine with the change, i will add one test

account: dump extra information on account or newly created service principal

---

.mention-bot

- Don’t mention BurtBiel
- And allow mention bot to auto assign to what it thinks is the best reviewer.
- Always notify for JasonRShaver for docs/help

Mention bot config

---

src/command_modules/azure-cli-component/azure/cli/command_modules/component/_params.py
src/command_modules/azure-cli-component/azure/cli/command_modules/component/custom.py

Logs are sent to logger.debug now so we should utilize that instead of having another flag named `--show-logs`.
If user wants logs, it’s expected that they should just use `—debug` instead of `—debug` and `—show-logs`

[component update] Remove redundant show-logs flags

---

src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py

Added exception handling for missing command "git remote get-url" in git versions less than 2.7.0

Added exception handling for missing command "git remote get-url" in git versions less than 2.7.0

---

.mention-bot

The missing quote prevented mention-bot from using the configuration

Fix typo in mention-bot config

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py

W/o it, the local time could be taken as UTC, so if you are in timezone ahead, the password might take hours to be effective.
Fix at least one seemingly flakiness in #1332

ad: use utc time on setting app's password start date

---

azure-cli.pyproj
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_format.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py

Fixes #1066, fixes #1003, fixes #1002, fixes #1266.
Creates custom callables for various table output formats in storage. Updates help text.

[Storage] Fix storage table outputs and help text.

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

Closes #741.
This PR adds logic to various VM tests that should be ResourceGroupVCRTestBase instead of VCRTestBase. These tests will fail to re-record and inform the dev that these tests should be updated.

[Test] Prevent Re-recording Tests That Use Old VCRTestBase

---

src/azure-cli-core/azure/cli/core/_pkg_util.py
src/azure-cli-core/azure/cli/core/parser.py
src/command_modules/azure-cli-component/azure/cli/command_modules/component/commands.py
src/command_modules/azure-cli-component/azure/cli/command_modules/component/custom.py

‘az component list-available’ command
Check if the module is available if parsing fails due to command_package error
Resolves https://github.com/Azure/azure-cli/issues/863

Component Discovery

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py

This PR addresses #1431, by simply adding a short-hand alias for the `--plan` argument of the `az appservice web create` command. I couldn't find any other instances where this argument needed to be aliased, and I wasn't sure whether the existing unit tests needed to be updated, since they're already testing this argument and I'm not removing the existing long-form alias.

Aliasing plan argument with shorthand for appservice web create command

---

src/azure-cli-core/azure/cli/core/application.py
src/azure-cli-core/azure/cli/core/tests/test_application.py

Fixes #1379
Fixes #1419 
@jmspring @yugang-msft

interpret the '@' syntax if something higher hasn't already done that.

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_acs_create_update.yaml

Fixes https://github.com/Azure/azure-cli/issues/1309

Add auto-registration for resource providers.

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/blob.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/storage_url_helpers.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/.gitignore
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/integration_test_base.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/integration_test_blob_download.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/integration_test_blob_upload.py

Resolve issue https://github.com/Azure/azure-cli/issues/1432
```
10:21 $ az storage blob upload-batch -h
Command
az storage blob upload-batch: Upload files to storage container as blobs.
Arguments
--destination -d [Required]: The string represents the destination of this upload operation. The
source can be the container URL or the container name. When the
source is the container URL, the storage account name will parsed
from the URL.
--source -s      [Required]: The directory where the files to be uploaded.
--dryrun                   : Show the summary of the operations to be taken instead of actually
upload the file(s).
--lease-id                 : Required if the blob has an active lease.
--metadata                 : Metadata in space-separated key=value pairs. This overwrites any …
```

Introduce batch upload and download for blob

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py

PR #1425 added status to the default table format for the `resource list` command, but if the value of properties is `null` then the table transformation will fail (due a TypeError) and you will get the "no table format" error.

Fix resource list table

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

acs: *_install_cli mark cli as executable

---

README.rst

Add mounting of the home directory for the Docker instructions.

Move around the order of install instructions.

---

azure-cli.pyproj
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_format.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_local_gateway/azuredeploy.json
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_local_gateway/lib/local_gateway_creation_client.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_local_gateway/lib/models/basic_dependency.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_local_gateway/lib/models/dependency.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_local_gateway/lib/models/deployment_extended.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_local_gateway/lib/models/deployment_local_gateway.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_local_gateway/lib/models/deployment_properties_extended.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_local_gateway/lib/models/parameters_link.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_local_gateway/lib/models/provider.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_local_gateway/lib/models/provider_resource_type.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_local_gateway/lib/models/template_link.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_local_gateway/lib/operations/local_gateway_operations.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_local_gateway/swagger_create_local_gateway.json

Fixes #1416. Fixes #1435. Adds parameters to `network local-gateway create` to support setting BGP settings at creation. Additionally, exposes the same parameters as convenience arguments on the update command. Adds a table transformer for the list command to match Xplat's list format.

[Network] Add BGP Peering to local-network create and update

---

src/azure-cli-core/azure/cli/core/application.py
src/azure-cli-core/azure/cli/core/tests/test_application.py

Replace the regex from PR #1423.
- no longer requires the arg start with -- (for example `--set tags=@file.json` would not work with previous regex
- removes checks for quotes and associated test. By the time the check is reached, quotes have already been processed and thus we don't need to check for them (since they aren't there!)

Update for @file matching

---

src/azure-cli-core/azure/cli/core/commands/arm.py

Fixes #793 and fixes issue seen in PR #1426. 
Previously, the logic of the IDs parameter would have unpredictable and ambiguous results if you supplied --ids along with --foo-name. In PR #1426, the team wishes to have a default value for one of the name parameters, which means that name component will always have a value even if --ids is used. In that case, it caused a crash.
This PR checks for an existing value and explicitly overwrites it if exists, logging a warning. Absent some mechanism to know whether a parameter was populated by the user or a default value (technically there is one but it's so ugly so as not to recommend anyone do it) this is reasonable compromise.

Fix Ambiguity When Using Names and --IDS

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_params.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_utils.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_validators.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/custom.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/template.json
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/recordings/test_acr.yaml
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/test_acr_commands.py

1. Prefix storage account name with registry name.
2. Add tags to storage account.
3. Add registry name validation to avoid creating storage account when registry name is not available.

[ACR] Prefix storage account name with registry name

---

src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/azure/cli/core/commands/_introspection.py
src/azure-cli-core/azure/cli/core/commands/arm.py
src/azure-cli-core/azure/cli/core/commands/parameters.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/test_network_app_gateway_no_wait.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/test_group_deployment_no_wait.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/test_resource_group_no_wait.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_resource.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_create_vm_no_wait.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

Submit it to leverage CI to catch regressions. Still finalizing the change, but feel free to put in comments.
Fix #1071, Fix #1169
This change enable author to expose `--no-wait` from long running command, and also expose `wait` commands to wait on any conditions based on `read` api.
```
Command
az vm wait
Arguments
Resource Id Arguments
--ids              : One or more resource IDs. If provided, no other 'Resource Id' arguments
should be specified.
--name -n          : The name of the virtual machine.
--resource-group -g: Name of resource group.
Wait Condition Arguments
--created          : Wait till created with 'provisioningState' at 'Succeeded'.
--custom           : Wait until the condition satisfies a custom JMESPath query. E.g.
provisioningState!='InProgress', …
```

Support Wait/No-Wait

---

.travis.yml
requirements.txt

reduce test time for 20 seconds

Use nosetests to run azure-cli core tests in parallel

---

scripts/nightly/nightly-build.sh
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/azure/cli/__init__.py
src/azure-cli/setup.py
src/command_modules/azure-cli-acr/setup.py
src/command_modules/azure-cli-acs/setup.py
src/command_modules/azure-cli-appservice/setup.py
src/command_modules/azure-cli-cloud/setup.py
src/command_modules/azure-cli-component/azure/cli/command_modules/component/custom.py
src/command_modules/azure-cli-component/setup.py
src/command_modules/azure-cli-configure/setup.py
src/command_modules/azure-cli-container/setup.py
src/command_modules/azure-cli-context/setup.py
src/command_modules/azure-cli-feedback/setup.py
src/command_modules/azure-cli-iot/setup.py
src/command_modules/azure-cli-keyvault/setup.py
src/command_modules/azure-cli-network/setup.py
src/command_modules/azure-cli-profile/setup.py
src/command_modules/azure-cli-redis/setup.py
src/command_modules/azure-cli-resource/setup.py
src/command_modules/azure-cli-role/setup.py
src/command_modules/azure-cli-storage/setup.py
src/command_modules/azure-cli-taskhelp/setup.py
src/command_modules/azure-cli-vm/setup.py

- Also, the dev versions have all command modules installed by default
- If the user really wants to install another module, from some unknown location, they can use pip directly
- * pip doesn’t support mixing editable packages with regular packages *
pip install --editable and pip install clash for namespace packages #3
https://github.com/pypa/pip/issues/3
And, Fix nightly build version patching as well

[Component] Prevent the use of ‘component’ commands in dev mode

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Fix a bug where command line flags would be ignored
Validate that the service principal still exists
@colemickens for sanity checking
Fixes https://github.com/Azure/azure-cli/issues/1442

[ACS] Update the handling of service principals.

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/recordings/test_create_for_rbac.yaml
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/recordings/test_sp_create_scenario.yaml
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/test_graph.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/test_role.py

Fix #1190, Fix #1332
Includes:
1. Make it reliable with retires, while the root cause of the replicate latency is being tracked by ICM ticket and investigated by AAD service team  
2. Default to create a role assignment, using the scope of current subscription root with role of "contributor".
3. Support re-entry in the command. Say, if you have SP created in the previous run, you can run it again to continue to the end
//cc: @colemickens, @ahmetalpbalkan

rbac: improve 'create-for-rbac'

---

azure-cli.pyproj
src/azure-cli-core/azure/cli/core/test_utils/vcr_test_base.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/test_acr_commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/tests/test_iot_commands.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/test_keyvault_commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/test_network_traffic_manager.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_resource.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/test_role.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

This PR improves the performance of test recording by updating the framework to work with the newly released --no-wait feature.
- The `resource group delete` operation at the end of ResourceGroupVCRTestBase tests (and StorageAccountVCRTestBase tests) adds --no-wait so you don't have to wait for the RG to delete.
- A random four character tag is appended to the resource group name during recording (in the format `_{tag}_`) so that you can begin re-recording a test while a previous test's resource group is deleting.
There are limits: namely, for resources whose name must form a unique URL, trying to recreate that resource will fail if it already exists in a resource group being deleted (for example KeyVaults, Storage Accounts, etc.)

[Test] Improve test recording

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/test_network_traffic_manager.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py

- Adds convenience arguments to `profile/endpoint update` commands for parity with Xplat (#818)
- Adds validator logic to partially address #1481 for `endpoint create`.

[Network] Traffic manager command improvements

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/commands.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Fixes https://github.com/Azure/azure-cli/issues/1358

[ACS] Add support for top-level browse and install-cli commands.

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/recordings/test_create_for_rbac.yaml

This used to work for first party applications like cli, but now AAD service no longer support it.
Hence I am cleaning up the code and just use retries.

rbac: remove usages of session key as it offers no guarantee for reliable graph read

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vnet/azuredeploy.json
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vnet/azuredeploy_empty.json
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vnet/lib/models/basic_dependency.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vnet/lib/models/dependency.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vnet/lib/models/deployment_extended.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vnet/lib/models/deployment_properties_extended.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vnet/lib/models/deployment_vnet.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vnet/lib/models/parameters_link.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vnet/lib/models/provider.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vnet/lib/models/provider_resource_type.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vnet/lib/models/template_link.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vnet/lib/operations/vnet_operations.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vnet/lib/vnet_creation_client.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vnet/swagger_create_vnet.json

Closes #1503.
- Updates the long-summary for `vnet create` to note that subnet creation is optional at the time of VNet creation.
- Makes the creation of a subnet at the time of VNet creation optional. If omitted, the VNet will be created with no subnet. **BREAKING CHANGE**
- `vnet create` dynamically determines the default subnet prefix. If the VNet mask is < 24 bits, the subnet mask is 24 bits. If the VNet mask is greater than 24 bits, the subnet mask is the same size as the VNet mask. **BREAKING CHANGE**
- For `subnet create` --address-prefix is now a required parameter. Any default could only be used once, after which relying on it will cause an error without complex logic to determine a viable prefix. **BREAKING CHANGE**

[Network] Update Subnet Create Default

---

README.rst

Closes https://github.com/Azure/azure-cli/issues/1509

[Docs] Add [arch=amd64] to apt-get install instructions for 64bit versions

---

src/azure-cli-nspkg/setup.py

The version number for azure-cli-nspkg did not include +dev

---

README.rst
scripts/curl_install_pypi/README.md

- curl install at top since we’ve made improvements to it and it’s the easiest for new users
- Instructions on uploading new install scripts to storage account

[Docs] Curl install at top of README

---

.travis.yml

Remove 3.5-dev for now until this version on CI is fixed.

[CI] Remove 3.5-dev python version from travis ci

---

scripts/smoke_test_install/README.md
src/azure-cli/README.rst

Couple of places where we still reference 'resource group' instead of 'group'.

[Docs] Fix docs ‘resource group’ to ‘group’

---

src/azure-cli/az.completion.sh

Closes https://github.com/Azure/azure-cli/issues/1342
This is not full-proof as $SHELL is not always set to zsh (e.g. zsh isn’t your default shell).
However, it will enable the compatibility mode if it is set.
In the future, https://github.com/Azure/azure-cli/issues/630 will likely remove this file altogether.

Enable zsh compatibility mode for zsh shell.

---

.travis.yml

Since 3.5-dev refers to the development version of Python beyond 3.5.2, it is a moving target that can break (it updates every day or two).
So still run CI on 3.5-dev but don’t cause a failure in this version to fail CI.

[CI] Allow failures on 3.5-dev Python version

---

homebrew/README.md
homebrew/azure-cli-2.rb
homebrew/patch_component_custom.py

This PR will mean the CLI can be installed with `brew install azure-cli-2`. Merging this PR will not automatically make `brew install azure-cli-2` available as a separate PR has to be submitted to https://github.com/Homebrew/homebrew-core.
The package is built *from source*, not from the packages published on PyPI.
All command modules will be installed and now components cannot be installed after install-time.
If there's a new update to a component or a new component is added, a new Homebrew package is required.
A patch has been applied to `az component` commands as `brew` should be used to manage the Homebrew version of the CLI.
e.g.:
```
$ az component update
This operation is not available in the Homebrew version of the CLI.
Components cannot be updated. Run 'brew update'.
```
--- …

Homebrew Formula for Azure CLI 2.0

---

azure-cli.pyproj
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/blob.py

Temporary fix for issue #1105. When Python SDK issue https://github.com/Azure/azure-storage-python/issues/190 is fixed, this workaround should be removed.

[Storage] Workaround for blob upload SDK bug

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/test_network_express_route.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py

Closes #1575.
Prevents attempting to create MicrosoftPeering settings with SKU type "Standard" as the server does not currently validate this.
Prevents attempting to create peering settings if the VLAN id is already in use on that circuit as the server does not currently validate this.

[Network] ExpressRoute peering client-side validation workaround

---

src/azure-cli-core/azure/cli/core/application.py

Fixes #1109. Expand user when using @~/path syntax
Fixes #1577. Allows use of '@' as a value (for DNS commands for example)

Fix issues with @syntax

---

README.rst

The heading was changed from ‘Docker’ to ‘Docker (versioned)’ and I forgot to change the anchor link also.

[Docs] Fix html anchor reference in README

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/test_webapp_e2e.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py

Fix #1501 
`appservice` commands work are supposed to be frozen till we migrate to new SDK. But the SDK's swagger spec is not finalized yet, so the good version for cli to depend on won't come out soon. Based on that, for now I will still address important issue as long as the fix is simple which won't accumulate debt for future migrations.

appservice: add webapp start

---

src/azure-cli-core/azure/cli/core/commands/parameters.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

Fixes #1129 (and pieces of other DNS issues).
- Updates help text
- Adds the following parameters to `dnz record-set create`: `--metadata`, `--if-match`, `--if-none-match`
- Removes record type SOA from the --type enum because that type cannot be created, only updated.
- Adds `-t` alias for `--type` and `-z` alias for `--zone-name`

[Network] DNS Record Set Create Updates

---

src/azure-cli-core/azure/cli/core/cloud.py

Was getting this error:
```
The access token has been obtained from wrong audience or resource
'https://management.core.usgovcloudapi.net'. It should exactly match
(including forward slash) with one of the allowed audiences
'https://management.core.usgovcloudapi.net/','https://management.usgovcloudapi.net/'.
```

Correct endpoints for USGov

---

requirements.txt
scripts/dev_setup.py

Since 12/12/2016, the CI build on python 3.5-dev began failing while running pylint. The errors are import-error. The error was caused by setuptools. The python 3.5-dev build uses the latest setuptools. A change introduced between 30.4.0 and 31.0.0 add additional `.pth` file to the installation folder under virtualenv. The files obviously confused the pylint cause `import-error` in turn. 
This change will fix the setuptools version to 30.4.0 to mitigate this issue.

Mitigate the pylint error caused by setuptools

---

src/command_modules/azure-cli-component/azure/cli/command_modules/component/custom.py

Closes https://github.com/Azure/azure-cli/issues/1578
The pip —ignore-installed flag would sometimes cause a seg fault.
Removing it prevents the seg fault.
It isn’t required now anyway.

Fix pip seg fault on 'az component update'

---

doc/configuring_your_machine.md

From
`python -m unittest discover -s src/azure/cli/tests` to 
`python -m unittest discover -s src/azure-cli/azure/cli/tests`

Correcting unittest location in docs

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vnet_gateway/azuredeploy.json
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vnet_gateway/lib/models/deployment_vnet_gateway.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vnet_gateway/lib/models/template_link.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vnet_gateway/lib/operations/vnet_gateway_operations.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vnet_gateway/swagger_create_vnet_gateway.json
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/test_network_app_gateway_no_wait.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/test_network_app_gateway_with_defaults.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_scaleset_create_simple.yaml

Fixes #1638, fixes #1635.
- Raises an error if user tries to add a root certificate to a vnet-gateway that has no VPN client configuration (Fixes #1638)
- Displays the resulting object after `vnet-gateway create`. (Fixes #1635)
- Adds the ability to add address prefixes to the vnet-gateway at creation time.

[Network] VNet Gateway Fixes and Enhancements

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

This change will make test run avoid the conflict during parallel run.

Name private_config.json differently in VM test

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_blob_scenario.yaml

The blob_type cannot be set to `append` because of this validator, such as in `az storage blob upload` command by `--type` argument.

Fix blob type validator

---

src/azure-cli/azure/cli/__main__.py
src/azure-cli/azure/cli/main.py
src/azure-cli/setup.py

Log:
```
[file:.\src\azure-cli\setup.py]
[file:.\src\azure-cli\azure\cli\__init__.py]
[file:.\src\azure-cli\azure\cli\__main__.py]
--->  Applying global fix for E265
--->  Applying global fix for W602
[file:.\src\azure-cli\azure\__init__.py]
--->  Applying global fix for E265
--->  Applying global fix for E265
--->  Applying global fix for W602
--->  0 issue(s) to fix {}
--->  Applying global fix for W602
--->  4 issue(s) to fix {'E261': {18, 38}, 'E262': {18, 38}}
--->  1 issue(s) to fix {'E401': {22}}
[file:.\src\azure-cli\azure\cli\main.py]
[file:.\src\azure-cli\azure\cli\tests\__init__.py]
--->  0 issue(s) to fix {}
--->  Applying global fix for E265
--->  Applying global fix for W602
--->  0 issue(s) to fix {}
--->  0 issue(s) to fix {}
--->  Applying global fix for E265
---> …
```

Fix PEP8 for azure-cli

---

requirements.txt
scripts/automation/style/pep8.py
scripts/dev_setup.py
scripts/run_coverage.sh
scripts/run_pylint.sh
scripts/run_tests.sh
scripts/setup.py

1. Install automation code as a development package. The outcome is that the automation code can be invoked without add ./scripts folder to the PYTHONPATH.
2. Add PEP8 scripts to fix PEP8 automatically

Change the automation code

---

scripts/automation/release/README.md
scripts/automation/release/__init__.py
scripts/automation/release/run.py
scripts/automation/release/version_patcher.py
scripts/automation/utilities/path.py

NOTE: These **are not** `az` CLI commands. This is a separate, simple interface for automating building and packaging of components.
Examples of use
---------------
Show help
```
$ python -m automation.release.run -h
usage: run.py [-h] --component COMPONENT [--no-version-patch] [--repo REPO]
[--repo-username REPO_USERNAME] [--repo-password REPO_PASSWORD]
Automated build and release of a component. To only build, don't specify the
repo parameters.
optional arguments:
-h, --help            show this help message and exit
--component COMPONENT, -c COMPONENT
Component name (e.g. azure-cli, azure-cli-vm, etc.)
--no-version-patch    By default, we patch the version number of the package
to remove '+dev' if it exists.
--repo REPO, -r REPO  Repository URL for release (e.g. …
```

Automated building and releasing of a component (with version patching)

---

README.rst

Closes https://github.com/Azure/azure-cli/issues/1690 - Clarify that curl install not supported on Windows.
Closes https://github.com/Azure/azure-cli/issues/1691 - Correct PATH for `pip install --user` on Windows.
refs: https://docs.python.org/2/library/site.html#site.USER_BASE
https://pip.pypa.io/en/stable/user_guide/#user-installs

[Docs] Carify Windows pip install

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vpn_connection/azuredeploy.json
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vpn_connection/lib/models/deployment_vpn_connection.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vpn_connection/lib/models/template_link.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vpn_connection/lib/operations/vpn_connection_operations.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/mgmt_vpn_connection/swagger_create_vpn_connection.json
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/test_network_vpn_gateway.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py

Fixes #1607, fixes #1608.
- adds `--enable-bgp` flag to create and update commands (#1608)
- fixes bug where shared key was not used for VNET to VNET connection (#1607)
- adds validation to ensure that shared key is provided for VNET-to-VNET and site-to-site connections but not for ExpressRoute connections.
- adds `--authorization-key` parameter to match Powershell
- implements workaround for issue where `vpn-connection update` command would fail due to the service returning only the IDs of its connected objects rather than the objects themselves.  (https://github.com/Azure/azure-rest-api-specs/issues/850)

[Network] VPN connection fixes

---

scripts/automation/release/README.md
scripts/automation/release/check.py

Examples:
```
$ python -m scripts.automation.release.check -h
usage: check.py [-h] [--component COMPONENT] --git-revision-start
GIT_REVISION_START [--git-revision-end GIT_REVISION_END]
Check for changes made to a component since a git commit or tag. Empty
response means no changes.
optional arguments:
-h, --help            show this help message and exit
--component COMPONENT, -c COMPONENT
Component name (e.g. azure-cli, azure-cli-vm, etc.).
If not specified, all component changes are shown.
--git-revision-start GIT_REVISION_START, -s GIT_REVISION_START
Git tag (or commit) to use as the start of the
revision range. (e.g. release-azure-cli-vm-0.1.0)
--git-revision-end GIT_REVISION_END, -e GIT_REVISION_END
Git tag (or commit) to use as the end of the revision
range.
```
```
$ python -m …
```

Release management - Check for changes made to a component since a git commit or tag

---

src/azure-cli-core/azure/cli/core/_help.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/_help.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/_params.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/_validators.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/commands.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/custom.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/tests/recordings/test_iot_hub.yaml
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/tests/test_iot_commands.py
src/command_modules/azure-cli-iot/requirements.txt
src/command_modules/azure-cli-iot/setup.py

1. Upgrade IoT management SDK to latest version 0.2.1
2. Add new commands to 'iot hub' and 'iot device' group
Help messages of new commands:
```bash
>az iot hub update -h
Command
az iot hub update: Update non-security metadata of an IoT Hub.
Arguments
Resource Id Arguments
--ids              : One or more resource IDs. If provided, no other 'Resource Id' arguments
should be specified.
--name -n          : IoT Hub name.
--resource-group -g: Name of resource group.
Generic Update Arguments
--add              : Add an object to a list of objects by specifying a path and key value
pairs.  Example: --add property.listProperty <key=value, string or JSON
string>.
--remove           : Remove a property or an element from a list.  Example: --remove
property.list <indexToRemove> OR --remove …
```

[IoT] update IoT management SDK and add missing commands

---

src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py

If you were logged in with a service principal and tried to use any of the az container commands, it would fail (token not found) because we assumed you were logged in as a user.

Get the token for service principal when service principal is being use.

---

src/azure-cli-core/azure/cli/core/_debug.py
src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/commands/client_factory.py
src/azure-cli-core/azure/cli/core/test_utils/vcr_test_base.py
src/azure-cli-core/azure/cli/core/tests/test_connection_verify.py

1. Make sure tracing works during login. The bug is during login, the subscription client created doesn't respect related env var. The reason is it can't go through the common factory method, which is only usable at post login
2. I will also hide ADAL env var for proxy tracing, CLI will turn it on automatically

Bug fix in proxy tracing during cli login command

---

scripts/github_bot/HISTORY.rst
scripts/github_bot/README.md
scripts/github_bot/api/Dockerfile
scripts/github_bot/api/app.py

- In Dockerfile, upgrade pip
- Add fix for calling the automation script after a recent change to how automation works
- Run on port 80
- Use alpine docker image as base
- Bot comment on opened Release PR with checklist
- Bot comment if release successful or not
- Bot apply release label automatically
- Bot create a GitHub release
- Add HISTORY.rst for github bot changelog

Azure CLI GitHub bot for Release PRs

---

src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/params.py

Fix for #1769 
Output after the fix
```
(env) vishrut@visshamac azure-cli (sql-db-test) $ az sql elastic-pools create -h
Command
az sql elastic-pools create: Creates a new Azure SQL elastic pool or updates an existing Azure
SQL elastic pool.
Arguments
--elastic-pool-name [Required]: The name of the Azure SQL Elastic Pool to be operated on
(Updated or created).
--resource-group -g [Required]: Name of resource group.
--server-name       [Required]: The name of the Azure SQL server.
Creating Arguments
--location -l       [Required]: Location.
--database-dtu-max            : The maximum DTU any one SQL Azure Database can consume.
--database-dtu-min            : The minimum DTU all SQL Azure Databases are guaranteed.
--dtu                         : The total shared DTU for the SQL Azure …
```

Expanding ElasticPool while creating elastic-pool

---

src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/help.py

Fix for #1777 
```
(env) vishrut@mac azure-cli (fix-elastic-pools-database-help) $ az sql elastic-pools database -h
Group
az sql elastic-pools database: Command to manage databases activities in database elastic pools.
Commands:
list         : Returns information about an Azure SQL database inside of an Azure SQL elastic
pool.
show         : Gets information about an Azure SQL database inside of an Azure SQL elastic pool.
show-activity: Returns information about activity on Azure SQL databases inside of an Azure SQL
elastic pool.
(env) vishrut@mac azure-cli (fix-elastic-pools-database-help) $ az sql elastic-pools database show -h
Command
az sql elastic-pools database show: Gets information about an Azure SQL database inside of an
Azure SQL elastic pool.
Arguments
--database-name …
```

Database is a sub-group instead of command for az sql elastic-pools 

---

requirements.txt
src/azure-cli-core/azure/cli/core/parser.py
src/azure-cli-core/setup.py

Fixes https://github.com/Azure/azure-cli/issues/1792.
- Prev. argcomplete.autocomplete() could not take a default_completer. Now, it does so we can’t subclass CompletionFinder anymore.
- Require argcomplete 1.8.0 now as the change isn’t backwards compatible.
Will release an update to azure-cli-core once this PR is merged...

Fix argcomplete 'default_completer' error

---

doc/authoring_command_modules/authoring_commands.md
src/azure-cli-core/azure/cli/core/_prompting.py
src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/azure/cli/core/test_utils/vcr_test_base.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py
src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/_utils.py
src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_resource.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

Closes https://github.com/Azure/azure-cli/issues/1355
- When registering a command, add `confirmation=True` to enable user confirmation. Also supports a string message or callable.
- Add a —force flag for commands that support this feature.
- Integrated with configuration system so it can be enabled/disabled by setting AZURE_CORE_DISABLE_CONFIRM_PROMPT
Added for the following commands:
az group delete
az vm delete
az network dns zone delete
---
EXAMPLES:
```
$ az group delete -n debekoe-a3
Are you sure you want to perform this operation? (y/n): n
Operation cancelled.
```
Only accepts appropriate values.
```
$ az group delete -n debekoe-a3
Are you sure you want to perform this operation? (y/n): 1
Are you sure you want to perform this operation? (y/n): 2
Are you sure you want to perform …
```

Support Force & Confirm

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py

fix #1438.
The new command of `az vm access reset-linux-ssh` takes no specific argument, other than the resource group, vm name, and resource-id
For test,  I did following manual verification as it is hard to automate them 
1.  SSH to the VM
2.  Update /etc/ssh/sshd_config say change the port to 23
3.  restart VM
4.  SSH should fail
5.  Run the new reset command which will reset the port back to 22
6. SSH again, it should work

vm: support reset ssh

---

README.rst
packaged_releases/HISTORY.md
packaged_releases/README.md
packaged_releases/az.completion
packaged_releases/debian/README.md
packaged_releases/debian/debian_build.sh
packaged_releases/debian/debian_dir_creator.sh
packaged_releases/docker/Dockerfile
packaged_releases/docker/README.md
packaged_releases/homebrew/README.md

* Include az.completion inside the release archive that's used by all packaged releases.
* Apply the patches directly in the archive rather than relying on each package manager to apply the patch.
- Remove Homebrew from README.rst as pushed-back for now.
Also closes https://github.com/Azure/azure-cli/issues/1768

Packaged release 0.1.7 for Debian & Docker

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage.py

The change is inspired by #1564 and #1565. Though the change doesn't entirely address the issue.
The change is simple. Instead of returning following structure to indicate if the operation of creation and deletion failed:
``` JSON
{ "success": false }
```
It will return these
``` JSON
{ "created": false }
{ "deleted": false } 
```
The goal is simply to give a clear response in the situation where there is not a fatal error but the operation doesn't take any effect. Currently, as the original issue stated, there are two pieces of return information: 1) exit code; 2) JSON printed to stdout. This prompts a lengthy discussion between me and Johen about what should be the convention for us to return errors. And here's the conclusion:
For operation end with a fatal error, the exit code is …

Rename the property names in storage op results

---

src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/help.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/recordings/test_sql_elastic_pools_mgmt.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/test_sql_commands.py

**Change 1** : Adds nose unit tests and recording for
```
az sql elastic-pools db list
az sql elastic-pools db show
az sql elastic-pools db show-activity
```
**Change 2** : Update documentation for `recommended` sub-group of elastic-pools command. It was showing empty short summary. 
```
(env) vishrut@mac azure-cli (more-elastic-pools) $ az sql elastic-pools recommended -h
Group
az sql elastic-pools recommended: Commands to see information about an Azure SQL Recommended
Elastic Pools.
Subgroups:
db          : Commands to see information about an Azure SQL database inside of Recommended
Elastic Pool.
Commands:
list        : Returns information about Azure SQL Recommended Elastic Pools.
show        : Gets information about an Azure SQL Recommended Elastic Pool.
show-metrics: Returns …
```

[Sql] More elastic-pools + command name correction

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_show_list_sizes_list_ip_addresses.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_parameters.py

Fix #154, fix #679
1. add flag `--show-details -d  : Show public ip address, FQDN, and power states. command will run slow.`
2. remove `--expand` flag from `vm show`. The functionality is already covered by `get-instance-view` command, also few end users will understand the flag's meaning

expose flags to show vm ip-address, power state

---

.travis.yml
doc/authoring_command_modules/example_module_template/setup.py
scripts/build_in_travis.sh
scripts/setup.py
src/azure-cli-core/azure/cli/core/test_utils/vcr_test_base.py
src/azure-cli-core/setup.py
src/azure-cli-nspkg/setup.py
src/azure-cli/setup.py
src/command_modules/azure-cli-acr/setup.py
src/command_modules/azure-cli-acs/setup.py
src/command_modules/azure-cli-appservice/setup.py
src/command_modules/azure-cli-batch/setup.py
src/command_modules/azure-cli-cloud/setup.py
src/command_modules/azure-cli-component/setup.py
src/command_modules/azure-cli-configure/setup.py
src/command_modules/azure-cli-container/setup.py
src/command_modules/azure-cli-context/setup.py
src/command_modules/azure-cli-feedback/setup.py
src/command_modules/azure-cli-iot/setup.py
src/command_modules/azure-cli-keyvault/setup.py
src/command_modules/azure-cli-network/setup.py
src/command_modules/azure-cli-profile/setup.py
src/command_modules/azure-cli-redis/setup.py
src/command_modules/azure-cli-resource/setup.py
src/command_modules/azure-cli-role/setup.py
src/command_modules/azure-cli-sql/setup.py
src/command_modules/azure-cli-storage/setup.py
src/command_modules/azure-cli-taskhelp/setup.py
src/command_modules/azure-cli-vm/setup.py

Closes https://github.com/Azure/azure-cli/issues/1626

Add Python 3.6 to CI

---

src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/commands.py

Closes https://github.com/Azure/azure-cli/issues/1257
```
Name                           CloudName    SubscriptionId                        State      IsDefault
-----------------------------  -----------  ------------------------------------  -------  -----------
Graph2                         AzureCloud   00000000-0000-0000-0000-000000000000  Enabled            1
Azure Subscription 1           AzureCloud   00000000-0000-0000-0000-000000000000  Enabled
Visual Studio Subscription     AzureCloud   00000000-0000-0000-0000-000000000000  Enabled
Visual Studio - 1              AzureCloud   00000000-0000-0000-0000-000000000000  Enabled
My Own Subscription            AzureCloud   00000000-0000-0000-0000-000000000000  Enabled
Azure Subscription 2           AzureCloud …
```

Add subscription id to ‘az account list’ table format

---

src/azure-cli-core/azure/cli/core/parser.py

- Also, parse error now sent to logger instead of stderr directly so it is colorized also.
Closes https://github.com/Azure/azure-cli/issues/1472
BEFORE:
```
$ az vm list sdfsdf
usage: az [-h] [--output {json,tsv,list,table,jsonc}] [--verbose] [--debug]
[--query JMESPATH]
{sql,redis,network,batch,iot,account,group,vm,appservice,storage,feature,vmss,cloud,policy,keyvault,logout,acs,acr,container,role,tag,ad,provider,resource,context,component,feedback,taskhelp,login,configure}
...
az: error: unrecognized arguments: sdfsdf
```
AFTER:
```
$ az vm list sdfsdf
az: error: unrecognized arguments: sdfsdf
usage: az [-h] [--output {json,tsv,list,table,jsonc}] [--verbose] [--debug]
[--query JMESPATH]
{sql,redis,network,batch,iot,account,group,vm,appservice,storage,feature,vmss,cloud,policy,keyvault,lo …
```

Print parse error before usage statement

---

azure-cli.pyproj
src/azure-cli-core/azure/cli/core/commands/parameters.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_params.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py

Fixes #1614 and fixes #1307.
Creates a "file_type" in core which simply calls the os.path.expanduser method and assigns this type to parameters which could accept a local path with ~. This is fine for parameters which are of the "JSON object or path" type since the expanduser method only expands a leading ~, so JSON would not be modified.

Add path expansion to file type parameters

---

azure-cli.pyproj
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_format.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/test_network_dns.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py

Fixes #1718. Fixes #1719. Addresses parts of #1131.
- Automatically creates a record set when using `az record _ add` if the set does not already exist. (#1719)
- Adds the ability to filter `dns record-set list` by `--type`. (#1131)
- **BC**: Removes the `--top` parameter from `dns record-set list`. (#1131)
- Adjusts the table format of `dns record-set list` (#1131) (#1718)

[Network] DNS Fixes

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py

fix #519 , also remove the punctuation on windows urn example, so it can be copied and pasted

vm: doc update

---

src/azure-cli-core/azure/cli/core/_util.py
src/azure-cli-core/azure/cli/core/application.py
src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/azure/cli/core/commands/client_factory.py
src/azure-cli-core/azure/cli/core/tests/test_util.py
src/azure-cli/azure/cli/main.py

- This caps the full command table from being printed.
- I did not fully remove this log message as there are other events that are logged that are of value (e.g. CommandParser.loaded, etc.).
- Add truncate_text util method with tests.
- Change some log messages from .info() to .debug() so they only show with the ‘—debug’ flag
Closes https://github.com/Azure/azure-cli/issues/1628
Closes https://github.com/Azure/azure-cli/issues/1010
Closes https://github.com/Azure/azure-cli/issues/1030

Cap logging of ‘Application event’ to 500 chars.

---

scripts/curl_install_pypi/install

- After uploading the script, the sha256 had changed.
- set -e exits the script if a command exits with non-zero exit code (like checksum failure)

Change SHA256 hash & exit script if error

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage.py

Fixes #1553 
Example 
```
$ az storage account keys list --resource-group trdai_test_disposable -n trdaitest03 -otable
KeyName    Permissions    Value
---------  -------------  ----------------------------------------------------------------------------------------
key1       Full           j5RkvkNy0EVpku8SXlLrtCikwE2doskBBvLzr8MHXiliNA8cbfTSTXf7E845Jf9eAbGI3ZbOTSnp1300m1OLqA==
key2       Full           YizdSHwaL72bGgTJNHlHCPUfa1Oo5rOGz+zCZ5p6/29Q0/h5G3TmyIuZ3YoOIs5Ol6C/s6nVjvuuo2/YtSmJMw==
$ az storage account keys list --resource-group trdai_test_disposable -n trdaitest03 -otsv
key1    Full    j5RkvkNy0EVpku8SXlLrtCikwE2doskBBvLzr8MHXiliNA8cbfTSTXf7E845Jf9eAbGI3ZbOTSnp1300m1OLqA==
key2    Full    YizdSHwaL72bGgTJNHlHCPUfa1Oo5rOGz+zCZ5p6/29Q0/h5G3TmyIuZ3YoOIs5Ol6C/s6nVjvuuo2/YtSmJMw== …
```

Fix #1553: Unwrap StorageAccountListKeysResult

---

src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/test_batch_mgmt_commands.py

`tear_down` is not called in playback mode so the file was not removed.
Now, like other tests, we use a temp file instead.

Batch mgmt test not clearing up test file

---

src/azure-cli-core/azure/cli/core/test_utils/vcr_test_base.py
src/azure-cli/azure/cli/main.py

- Handle JSON falsy values in NoneCheck
https://docs.python.org/2/library/json.html#json.JSONDecoder
Closes https://github.com/Azure/azure-cli/issues/794

Return empty array '[]' instead of nothing for json output

---

src/azure-cli-core/azure/cli/core/parser.py

If this operation fails, the whole CLI shouldn’t throw another exception.
We should catch it.
On Python 3.6, macOS Sierra and specific versions of OpenSSL on macOS, users may see `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)` whilst running a command of a module that doesn't exist or isn't installed.
Now, we catch the exception and just show the normal usage error as the module was not found.
Thanks for the report @oakeyc!
Related:
- https://bugs.python.org/issue28150
- http://stackoverflow.com/questions/40038246/ssl-sslerror-ssl-certificate-verify-failed-certificate-verify-failed-ssl-c
- http://stackoverflow.com/questions/41691327/ssl-sslerror-ssl-certificate-verify-failed-certificate-verify-failed-ssl-c/41692664
- …

Catch all exceptions whilst trying to check if PyPI module available.

---

src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/azure/cli/core/prompting.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/repository.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/custom.py
src/command_modules/azure-cli-feedback/azure/cli/command_modules/feedback/custom.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_actions.py

- Promote _prompting to prompting
- Use prompt() to check TTY before getting user input
Closes https://github.com/Azure/azure-cli/issues/1349

Centralized interactive input() function that checks if STDIN is a TTY

---

src/azure-cli-core/azure/cli/core/test_utils/vcr_test_base.py

- Some kwargs are required whilst recording. Before, we ignored all kwargs.
- Now, we only remove the kwarg that was causing the issue in Python 3.6
Closes https://github.com/Azure/azure-cli/issues/1869

Fix ‘Cannot record any VCR tests’

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_format.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage.py

I add a transform method to both `file list` and `directory list`. It adds additional properties to indicate entity type and remove the unused `content` property so that the number of properties are aligned between file and directory. The goal is to ensure the column numbers are the same for file and directory in tsv format.
Outcome:
```
$ az storage directory list -stest01 -otable
Name       Content Length    Type    Last Modified
---------  ----------------  ------  ---------------
python01/                    dir
python02/                    dir
python03/                    dir
python04/                    dir
$ az storage directory list -stest01 -otsv
None    python01                dir
None    python02                dir
None    python03                dir
None    python04 …
```

Fix #1591: Transform the file and directory list result

---

.gitignore
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_params.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_blob_acl_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_blob_copy_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_blob_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_file_acl_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_file_copy_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_file_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_queue_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_table_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_validators.py

Fix storage seconds

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py

Found minor missing help docs while playing around :)
**Before:**
```
az group -h
Group
az group: Commands to manage resource groups.
Subgroups:
deployment: Commands to execute or manage ARM deployments.
Commands:
create    : Create a new resource group.
delete    : Delete resource group.
exists    : Checks whether resource group exists.
export    : Captures a resource group as a template.
list      : List resource groups, optionally filtered by a tag.
show      : Get a resource group.
update
wait
```
**After:**
```
az group -h
Group
az group: Commands to manage resource groups.
Subgroups:
deployment: Commands to execute or manage ARM deployments.
Commands:
create    : Create a new resource group.
delete    : Delete resource group.
exists    : Checks whether resource group exists.
export …
```

Adding more help docs for az group commands

---

src/azure-cli-core/azure/cli/core/_output.py
src/azure-cli-core/azure/cli/core/test_utils/vcr_test_base.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_account_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage.py

resolves #1906
Return bools as lower case rather than upper case (python bool case) to provide boolean scripting consistency.

ensure bools are lower case in tsv

---

src/azure-cli-core/azure/cli/core/application.py
src/azure-cli-core/azure/cli/core/commands/__init__.py

This means that multiple modules cannot contribute to a top-level command anymore.
A workaround is in place for ‘acs’ as currently, they have commands in both ‘acs’ and ‘vm’ modules.

Only load 1 module when we can

---

src/azure-cli-core/azure/cli/core/test_utils/vcr_test_base.py
src/azure-cli/azure/cli/main.py

- This prevents commands from printing ‘null’ in JSON output
- But still keeps ‘[]’, ‘{}’, and ‘false’ as valid JSON results
Closes https://github.com/Azure/azure-cli/issues/1908

Fix ‘null’ output if command doesn’t return

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/test_resource_group.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/test_resource_group_no_wait.yaml

Remove the superfluous exists check. Subsequent PUTs will either succeed (if the location is the same) or fail (if you try to change the location). This is consistent with other create commands in the CLI.

Fixes #1938

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/test_network_nsg.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py

Closes #1678.
- **Breaking Change**: Removes the default value of 1000 from `--priority`. This is now a required parameter.
- Reduces the number of required parameters from 11 to 4. Defaults are borrowed from Xplat CLI except for source/dest-address-prefix, which default to '*'. This would result in a default rule allowing inbound traffic to port 80 from any IP range.
- Updates the help text for NSG rule commands
- Fixes issue where `--ids` parameter was exposed for `nsg rule create`.

[Network] NSG rule help updates and sensible defaults

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

A bug in the enum references in the `express-route peering create` command resulted in being unable to send the necessary MicrosoftPeering config to the SDK. This corrects that issue.

[Network] Fix ExpressRoute enum references

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/storage_url_helpers.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage.py

1. The split usage is not python 2.7 compatible; fix it.
2. The environment variable is not popped in the test which expect no credential.

Fix two issues with storage

---

azure-cli.pyproj
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/vm_create_test_plan.md
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/vmss_create_test_plan.md

Fixes #1943. 
- If admin_username is < 6 characters or 'root' (either specified or by default), prompts for a valid username. If no TTY available, fails.
- Fixes an issue where the OS disk name would be incorrectly generated when specifying an existing storage account by ID.
- Restores the VM/VMSS create test plans that were deleted when the fat client was removed. Updates the scenarios slightly.

[Compute] VM Create Fixes

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_format.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py

[Network] Fix DNS Zone Show/List Table Format

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

Fixes #1843. Now if you run a child resource create command and the parent already has that resource, you will receive a warning and the original object will be replaced, as opposed to getting a weird "Cannot parse request" error.

[Network] Make child resource create commands goal seeking

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py

Fixes bug with adding hostname to web app.

---

azure-cli.pyproj
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/test_resource_id_scenario.yaml

Fixes #1902.
Ensures that the resource delete operation returns the response from the server, as it may include an error message.

Make resource delete return the server response.

---

src/azure-cli-core/azure/cli/core/_output.py
src/azure-cli-core/azure/cli/core/application.py
src/azure-cli-core/azure/cli/core/tests/test_output.py

Fixes #1883. JSON output is the supported "readable" format. Closes #1881.

Remove list output type.

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_defaults.py

Addresses 2 things:
1. do not reuse existing subnet unless the it is big enough to contain scaleset's instances 
2. use more accurate algorithm to figure out the subnet prefix

VMSS: improve the default logic on the subnets

---

src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py

Fixes https://github.com/Azure/azure-cli/issues/2031
We modify ‘’environmentName’ to ‘cloudName’ and this changed the object referenced by the file.
So later on, when another change was made, this change was saved to file!

Fixes KeyError: 'environmentName' after log in

---

scripts/automation/style/run.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/__init__.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/acs_client.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/commands.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/proxy.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/test_acs_client.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/test_custom.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/test_service_principals.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/win_proxy.py

/cc @brendandburns
All changes are trivial. The goal is to ensure all PEP8 rules are followed. Moving forward the style checker will be run against acs module code in CI.

Make ACS modules code PEP8 compliant and turn on style check in CI.

---

packaged_releases/docker/Dockerfile
packaged_releases/docker/README.md

There is a drive from some within the container community towards a standard label schema for container images.
> Label Schema Convention DRAFT (1.0.0-rc.1)
> http://label-schema.org/rc1/
> 
> Docker Inc. express a preference that container labels should be namespaced. Label Schema is a community project to provide a shared namespace for use by multiple tools, specifically org.label-schema.
>
> By providing a shared and community owned namespace we aim to:
> - Avoid duplication in cases where the same information is needed in multiple labels
> - Encourage the use of labels, both by image creators and by tool builders which might consume them
> - Codify good community practice in a way that is easy to consume and keep up-to-date with
There are some blog posts that discuss this:
- [Building …

Added Dockerfile labels from label-schema.org

---

packaged_releases/docker/README.md

Need to escape backticks for Markdown format from https://github.com/Azure/azure-cli/pull/2046

Fix Docker packaging README formatting

---

src/command_modules/azure-cli-component/azure/cli/command_modules/component/_params.py
src/command_modules/azure-cli-component/azure/cli/command_modules/component/custom.py

Added a `--allow-third-party` flag.
```
$ az component update --help
Command
az component update: Update Azure CLI 2.0 (Preview) and all of the installed components.
Arguments
--add              : The names of additional components to install (space separated).
--allow-third-party: Allow installation of 3rd party command modules. This option is assumed
with --private.
--link -l          : If a url or path to an html file, parse for links to archives. If local
path or file:// url that's a directory, then look for archives in the
directory listing.
--pre              : Include pre-release versions.
--private          : Include packages from a private server.
```

'component update' Check additional component author on PyPI

---

azure-cli.pyproj
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_existing_ids_options.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vmss_create_existing_ids_options.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

Fixes #2081. However, this bug wasn't just limited to VMSS create.
I added two additional tests that use create options only with IDs to protect against future regressions.

[VM/VMSS] Fix broken name or ids logic in VM/VMSS Create

---

scripts/automation/commandlint/__init__.py
scripts/automation/commandlint/run.py

Dumps the names of all the commands and parameters that don't have descriptions
Example output:
network lb probe create port
appservice web list
vm boot-diagnostics get-boot-log
vm boot-diagnostics get-boot-log vm_name
network application-gateway url-path-map rule create
network application-gateway url-path-map rule create paths
network application-gateway url-path-map rule create item_name
network application-gateway url-path-map rule create no_wait
network application-gateway url-path-map rule create application_gateway_name
network application-gateway url-path-map rule create http_settings
network application-gateway url-path-map rule create address_pool
network application-gateway url-path-map rule create url_path_map_name
network dns record a add
network dns record a add ipv4_address …

commandlint script

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_client_factory.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/commands.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/test_custom.py
src/command_modules/azure-cli-acs/setup.py

This is part of Task 2 of work Item #1329. 
1. Porting the logic from azure-cli-role to azure-cli-acs for `create_service_principal`, `create_role_assignment`, `create_application` & `show_service_principal`. 
2. Taking dependency on `azure-mgmt-authorization` & `azure-graphrbac` SDKs for `azure-cli-acs` command module.
@yugangw-msft @derekbekoe @tjprescott @troydai Please review this as you get a chance. 
**CC:** 
@brendandburns, @@yugangw-msft
Thanks!

Decouple azure-cli-acs and azure-cli-role module

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py

Also, expose the `--lun` for attaching managed disk to VM. This is to be consistent with portal and  commands for unmanaged disk.
No test adjustment is needed

vm/av-set: remove domain count defaults

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/test_network_dns.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py

Fixes #2087. Fixes #1134.
Restructures the DNS command tree. cc/ @jtuliani
**Breaking Changes**
- The `record` subgroup has been removed.
- A subgroup for each record type has been added to the `record-set` subgroup.
- The add/remove commands that were previously in `record` are now listed in `record-type <type>` as `add-record`/`remove-record`.
- A new command `record-set list` was added that lists all record sets in the zone. This was previously triggered by an optional parameter.
- The show/delete/update/etc. commands for each type of record set no longer require the type parameter. It is determined behind the scenes.
- The `soa` subgroup now has two commands: show and update. Name is no longer required (it is always '@').
- The `add` command for CNAME records has been renamed …

[Network] Restructure DNS Commands

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_actions.py

Reported by an internal customer. It turned out the blob uri is handled in case sensitive manner at server side.

vm image: do not normalize casing on blob uri

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py

**Before:**
```
(env) vishrut@mac azure-cli (master) $ az acs -h
Group
az acs: Commands to manage Azure container services.
Subgroups:
dcos       : Commands to manage a DCOS orchestrated Azure container service.
kubernetes
Commands:
browse     : Opens a browser to the web interface for the cluster orchestrator.
create     : Create a new Acs.
delete     : Deletes the specified container service.
install-cli
list       : List Container Services.
scale
show       : Gets the properties of the specified container service.
```
**After:**
```
(env) vishrut@mac azure-cli (update-acs-docs) $ az acs -h
Group
az acs: Commands to manage Azure container services.
Subgroups:
dcos       : Commands to manage a DCOS orchestrated Azure container service.
kubernetes : Commands to manage a kubernetes …
```

Updating help docs for missing az acs commands

---

.travis.yml
scripts/automation/setup/install_modules.py
scripts/automation/utilities/path.py
scripts/build.sh

- move build_in_travis.sh to build.sh
- fix up the grabbing modules locally for style checks so we don't grab empty folders
- ensure we don't run check_style if running py 3.6
To ensure you are receiving the same results as the server, run `./scripts/build.sh`

make ci build run locally

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py

fix #2189, fix partial #2187 (update help to point to a msdn page rather a broken command)

webapp: update help info on plan creation failure and fix tab completion on hostname command

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

Closes #2167. Closes #2177.
- Adds --host-name parameter to `application-gateway http-listener create/update` commands to support multisite operation. Automatically sets the SNI variable based on host-name and protocol.
- Updates help text and argument grouping for `application-gateway url-path-map create` to resolve confusion that may result from the fact that this command does two things.

[Network] AppGateway Fixes

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

Fixes issue where using the `--local-address-prefixes` convenience parameter for `local-gateway update` would raise a 404 Not Found error.

[Network] Fix bug with local-gateway update  convenience parameter

---

scripts/curl_install_pypi/install
scripts/curl_install_pypi/install.py

If ~/.bashrc and ~/.bash_profile exist on macOS, prefer .bash_profile.
Previously, we preferred ~/.bashrc but got reports on macOS that users have a ~/.bashrc that isn't sourced in their ~/.bash_profile file.

[Install script] On macOS, prefer .bash_profile over .bashrc

---

scripts/automation/release/check.py

Infer component name from the git tag specified so there's only 1 thing to change
- Exclude tests directory from change tracking
- Cleaner error messages

Improve script that reports changes made since a git tag

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/recordings/test_create_for_rbac.yaml
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/test_role.py

1. Remove a warn which is no longer valid because we are not going through `raw` mode to create the service principal, hence no response  to dump out. This fixes #2209 
2. Fix #1886, by erroring out when the service principal exists 
3. Per AAD folk's suggestion, increase the wait period for server replication to 3 minutes

rbac: make create-for-rbac reliable

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_params.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/custom.py

Fixing
https://github.com/Azure/azure-cli/issues/1897

--admin-enabled no longer requires a input value

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

The value is incorrect from the GET since we hide the secret, so clear it all, we don't want to update it anyway...

On scale, clear the service principal profile

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

There was one more place were the acs module required vm still.
(Not for Sprint 12)
Repro with:
```
$ pip install --pre azure-cli --extra-index-url https://azureclinightly.blob.core.windows.net/packages
$ az component remove -n vm
$ az acs --debug
Command arguments ['acs']
Installed command modules ['acs', 'appservice', 'batch', 'cloud', 'component', 'configure', 'container', 'documentdb', 'feedback', 'iot', 'keyvault', 'network', 'profile', 'redis', 'resource', 'role', 'sql', 'storage']
Error loading command module 'acs'
File "/usr/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 263, in get_command_table
import_module('azure.cli.command_modules.' + mod).load_commands()
File …
```

Remove acs - vm dependency

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_diagnostics_extension_install.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_boot_diagnostics.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vmss_extension.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vmss_nics.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vmss_vms.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

1. For 2 Test failures caused by storage account name being taken, the change here is to mitigate it since we are heading to non recording based test methodology.
2. Fixed failures caused by missing `--admin-user-name` on `vm create` 
3. Fixed test verification code in vm image query command. It hard coded the expected number which may change.

vm: fix test issues in live test run

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py

When CLI telemetry attempts to get installation id, it would modify the user `~/.azure/azureProfile.json` saving incorrect data into it.
We fix this by returning deep copies of subscriptions to prevent later modification (e.g. by telemetry).
https://github.com/Azure/azure-cli/issues/2031

Fix KeyError: 'environmentName' on 'az account list'

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/custom.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_account_scenario.yaml

Fixes #2341, which prevented setting a custom domain on a storage account.
Additionally:
- **BC**: removed `--use-subdomain` from the storage account create command, as the SDK documentation (and testing) confirm that this parameter can only be set on update. This is technically a breaking change. While any existing scripts that used this didn't do what was intended, its omission will break any existing scripts that use `--use-subdomain` in create calls. 
- altered the storage account update command to use the SDK's update method instead of create.

[Storage] Fix issue with storage account custom domain.

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Add support for windows clusters.

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

Fixes a regression in PR #2345 that causes the `nic ip-config address-pool/inbound-nat-rule add` commands to fail to add a second object because the key on which to try and match the collection objects was set to "name" instead of "id".  Added logic to the `_upsert` method to raise an error if the key value being matched results in None as this is an error case and would have caused the VCR tests to fail instead of having to be caught by the live test.

[Network] Fix failing NIC Subresource live test

---

src/azure-cli-core/azure/cli/core/_util.py
src/azure-cli-core/azure/cli/core/extensions/transform.py
src/azure-cli-core/azure/cli/core/test_utils/vcr_test_base.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_params.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_validators.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/commands.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/custom.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/recordings/test_keyvault_certificate.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/recordings/test_keyvault_key.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/recordings/test_keyvault_mgmt.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/recordings/test_keyvault_secret.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/test_keyvault_commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/keyvault/policy.json
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_linux_secrets.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_windows_secrets.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vmss_create_linux_secrets.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_custom_vm_commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py
src/command_modules/azure-cli-vm/setup.py

- add --secrets for VM and VMSS so that it takes a file or string content in the shape of ARM vm secrets
- add `az keyvault certificate get-default-policy`
- add `az vm format-secret` 
- add tests for VM and VMSS
- add transformer for x509 certificates so that base64 thumbprint is also shown as hex as it is named in the file system when provisioned for Linux VM and VMSS. 
```
$ az keyvault certificate get-default-policy -h
Command
az keyvault certificate get-default-policy: Get a default policy for a self-signed certificate.
This default policy can be used in conjunction with `az keyvault create` to create a self-
signed certificate. The policy can also be used as a base to manipulate to create other
permutations of Key Vault certificates.
Arguments
--debug    : Increase …
```

Add --secrets for VM and VMSS

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/test_linux_webapp.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/test_webapp_config.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/test_webapp_slot.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py

Fix #1895: so people can specify that an appsetting shouldn't participate in a swap
Fix #1870: Add a short name alias for the slot parameter
Fix #1868: Help text for creating a deployment slot isn't completely clear
Fix #1867: Deployment slot list doesn't provide the actual "raw" slot name

appservice: fix slot related bugs

---

src/azure-cli-core/azure/cli/core/commands/__init__.py

@vishrutshah can you take a look?
The workaround is no longer needed as https://github.com/Azure/azure-cli/pull/2098 is merged.

Remove workaround for ‘acs’ module loading

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/cloud.py
src/azure-cli-core/azure/cli/core/profiles/__init__.py
src/azure-cli-core/azure/cli/core/profiles/_shared.py
src/azure-cli-core/azure/cli/core/tests/test_cloud.py
src/azure-cli-core/setup.py
src/command_modules/azure-cli-cloud/azure/cli/command_modules/cloud/_help.py
src/command_modules/azure-cli-cloud/azure/cli/command_modules/cloud/_params.py
src/command_modules/azure-cli-cloud/azure/cli/command_modules/cloud/commands.py
src/command_modules/azure-cli-cloud/azure/cli/command_modules/cloud/custom.py

- Modify ‘az cloud register’ and ‘az cloud update’ to include the ‘—profile’ parameter
- Add ability to view all supported API versions without querying a cloud
- Use ARM 'resource manager' endpoint if ASM 'management' endpoint not set
note: With this change, switching profile will not change anything as they are just example profiles.
FYI @lmazuel For the `_shared.py` file change. This would contain the resource type to api version map.
Closes https://github.com/Azure/azure-cli/issues/2280
Closes https://github.com/Azure/azure-cli/issues/2279
Closes https://github.com/Azure/azure-cli/issues/2265

Add profile switching params and profile listing command

---

.gitignore
src/azure-cli-core/azure/cli/core/telemetry_upload.py

This is requested by VS business insights. The application insight SDK will convert numeric value in the `properties` values to string type. To allow these values types unchanged, numeric values should be saved through `measurements` argument on `track_event` method. It is a odd design, but it is what it is.

Mitigate AI SDK's problem with numeric in properties

---

src/azure-cli-core/azure/cli/core/commands/arm.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_api_check.py

Fixes https://github.com/Azure/azure-cli/issues/2248

Fix resource_id parsing to accept 'resourcegroups'

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_diagnostics_extension_install.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_state_modifications.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_extension.yaml

Otherwise, vm agent might reject for more than 2 handlers
There is subtle difference on extension API between VM and VMSS, and this change handles both

VM/VMSS: reuse existing extension instance name on update

---

src/command_modules/azure-cli-vm/tests/recordings/test_acs_create_update.yaml
src/command_modules/azure-cli-vm/tests/recordings/test_vm_image_list_by_alias.yaml
src/command_modules/azure-cli-vm/tests/test_vm_commands.py

Cause:
1. 14.04 ubuntu image is removed from the alias doc, so the test must adjust
2. Remove verification on the `masterProfile.count`. It is changing and not the test wants to verify anyway
3. Remove the testing on using custom images. It is being tracked at #2417

test:fix vm live test failures in the latest round

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/acs_client.py

Fixes: https://github.com/Azure/azure-cli/issues/1773

Enable password protected SSH keys.

---

src/command_modules/azure-cli-acr/README.rst

Made the storage account more obvious that developers don't need, and shouldn't try to use an existing storage account unless it was previously created by a registry.

ACR: Update descriptions for storage

---

requirements.txt

After a recent run of dev_setup.py I have been experiencing  the following error:
```
\keyvault\custom.py", line 12, in <module>
from OpenSSL import crypto
File "C:\Users\trpresco\Documents\github\azure-cli\env\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
from OpenSSL import rand, crypto, SSL
File "C:\Users\trpresco\Documents\github\azure-cli\env\lib\site-packages\OpenSSL\SSL.py", line 112, in <module>
SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: module 'lib' has no attribute 'SSL_ST_INIT'
```
This occurs on both Python 2 and 3 (though it manifests worse in Python 2). Updating the pyOpenSSL version fixes this issue.

Update pyOpenSSL version

---

src/azure-cli-core/azure/cli/core/commands/__init__.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_params.py

Fixes #2456. Previously, providing an options list like `options_list=('--foo')` would cause a cryptic, hard to diagnose error because it was lacking a comma.  This PR wraps anything of this form as a list internally, which doesn't require the comma.

Fix issue with "single tuple" options_list

---

src/command_modules/azure-cli-datalake/setup.py

FYI @begoldsm
Currently the __init__.py of azure.cli.command_modules.datalake is not included in the package.

Add datalake package to setup.py

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/disk_encryption.py

The exception type of `json.decoder.JSONDecodeError` is only available on Python 3+, so the code might break on python 2.7. I can find a more universal json decode exception to catch, but on a second thought, it might better off to be the same like [xplat version](https://github.com/Azure/azure-xplat-cli/blob/dev/lib/commands/arm/vm/vmClient._js#L2036). The encryption extension is not very well documented, so capturing a general exception might end up being the best option.

vm:catch more general exception on querying encryption extension's status

---

src/azure-cli-core/azure/cli/core/commands/parameters.py
src/azure-cli-core/azure/cli/core/commands/validators.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_params.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_validators.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/commands.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/custom.py
src/command_modules/azure-cli-keyvault/tests/recordings/test_keyvault_certificate.yaml
src/command_modules/azure-cli-keyvault/tests/recordings/test_keyvault_key.yaml
src/command_modules/azure-cli-keyvault/tests/recordings/test_keyvault_mgmt.yaml
src/command_modules/azure-cli-keyvault/tests/recordings/test_keyvault_secret.yaml
src/command_modules/azure-cli-keyvault/tests/test_keyvault_commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py

- Fixes #2332. Adds METAVAR for vault
- Fixes #2362. Makes resource group required for keyvault create. 
- Adds reusable method in core to get location from resource group. Updates references. Makes location optional for keyvault create.
- Fixes #2420. Fixes #2361. Adds "three_state_flag" to core parameters to allow true/false or flag-like behavior (avoids breaking changes and allows create/update consistency).
- Closes #2421. Adds convenience parameters for this update command.
- Fixes #2418. Corrects bug with enabled/disabled flags. Makes keyvault certificate create idempotent.

[KeyVault] Command fixes

---

scripts/github_bot/HISTORY.rst
scripts/github_bot/api/app.py

* Return 200 if webhook is skipped by the bot instead of 400.
* Create release on async thread to prevent GitHub webhook timeouts.
* Clone and tag the correct commit to prevent race conditions with multiple merges to the repo at once.

Release bot updates

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/setup.py
src/command_modules/azure-cli-appservice/tests/recordings/test_webapp_e2e.yaml
src/command_modules/azure-cli-appservice/tests/test_webapp_commands.py
src/command_modules/azure-cli-appservice/tests/test_webapp_commands_thru_mock.py

Fix #2399 
This command will convert xml to json so users can user jmespath query to retrieve all they want. For example, `az appservice web deployment list-publishing-profiles --query "[?publishMethod=='FTP'].publishUrl" -otsv` would return the ftp endpoint

appservice: support list publishing profiles

---

src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_params.py

Closes #2422. Hides attributes that are not marked readonly by the SDK but are not in fact supported by the API.

[KeyVault] Suppress unsuppported update parameters

---

src/azure-cli-core/azure/cli/core/prompting.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-resource/tests/test_resource_list_odata_filter.py

Fixes https://github.com/Azure/azure-cli/issues/1778

Add prompting for missing template parameters.

---

src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_util.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/custom.py
src/command_modules/azure-cli-sql/tests/test_sql_commands.py

Only commands that are irreversible are included. For example delete firewall rule does not require confirmation because it can be easily undone.

Require confirmation for destructive SQL commands.

---

doc/authoring_command_modules/example_module_template/HISTORY.rst
doc/authoring_command_modules/example_module_template/azure/cli/command_modules/example/__init__.py
doc/authoring_command_modules/example_module_template/azure/cli/command_modules/example/_help.py
doc/authoring_command_modules/example_module_template/azure/cli/command_modules/example/_params.py
doc/authoring_command_modules/example_module_template/azure/cli/command_modules/example/commands.py
doc/authoring_command_modules/example_module_template/azure/cli/command_modules/example/custom.py
doc/authoring_command_modules/example_module_template/setup.py
doc/authoring_command_modules/example_module_template/tests/__init__.py

Now, it can be installed directly and works with latest code in master.
‘pip install -e .’
Closes https://github.com/Azure/azure-cli/issues/2464

Update example command module template

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/disk_encryption.py
src/command_modules/azure-cli-vm/tests/test_custom_vm_commands.py

vm:fix distro check mechanism used by disk encryption

---

src/command_modules/azure-cli-sql/tests/test_sql_commands.py

The assertion error is:
JMESPathCheckAssertionError: Query '[1].name' doesn't yield expected value 'master', instead the actual value is 'cliautomationdb01'.
The fix is to sort the database names returned from the service so that it's guaranteed they are in order.

Fixed test failure in test_sql_db_mgmt.

---

src/azure-cli-core/azure/cli/core/commands/arm.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/tests/recordings/test_network_app_gateway_with_private_ip.yaml
src/command_modules/azure-cli-network/tests/recordings/test_network_express_route.yaml
src/command_modules/azure-cli-network/tests/test_network_commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/tests/test_vm_commands.py

Adds `wait` command for the following: `express-route, local-gateway, vnet-gateway, vmss`
Add `--no-wait` parameters to the following: 
**vm**: `create, delete, deallocate, generalize, stop, start, restart, redeploy, resize`
**vm user**: `update, delete, reset-ssh`
**vmss**: `create, delete, update, deallocate, delete-instances, stop, restart, start, update-instances, reimage, scale`
**vnet-gateway**: `delete`
**local-gateway**: `create, delete, update`
**express-route**: `create, delete, update`

Add wait commands and --no-wait support

---

src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/_params.py

This PR simply adds a short name option for the recently added `az configure --defaults` flag. As I've been using it recently, I've just found it helpful to have the alias.

[Configure] Adding short name alias for the --defaults flag

---

packaged_releases/README.md
scripts/automation/release/packaged.py

Saves a couple of hours during each release for Docker/Debian 😄

Script that creates packaged releases package archive

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/tests/test_vm_actions.py
src/command_modules/azure-cli-vm/tests/test_vm_commands.py
src/command_modules/azure-cli-vm/tests/test_vm_defaults.py

VM/VMSS: incorporate credentials validation logic used by portal

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/tests/test_vm_commands.py

Closes #2497.
- VMSS create no longer adds template variables regarding storage account unless storage accounts will be created. While these didn't do anything before if storage accounts weren't created, it was confusing when you would view the template.
- Adds an alias to `vm/vmss create` for OS disk caching. The existing `--storage-caching` exists alongside `--os-caching`. The intent is that `--storage-caching` will be deprecated and removed in the future. (Issue #2523)
- Adds `--data-caching` to `vm/vmss create` which is the caching type used for data disks.
- Adds `--caching` to `vm disk/vmss disk/vm unmanaged-disk attach` command.
- Reflects on the SDK's CachingType object to expose all caching types (including None). Due to a bug in the Swagger …

[VM/VMSS] Improved disk caching support

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_format.py

Fixes #2542.  The output transformer was swallowing errors, resulting in an output of `{}` instead of raising the error.

[Network] Fix network create format bug

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py

This PR simply adds a short name alias to the `--orchestrator-type` flag (on the `az acs create` command), since it is very common to set.

[ACS] Provide a short name alias for the orchestrator type flag

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py

This PR simply allows calling `az configure --defaults acs=<name>` in order to specify the default ACS cluster name. This allows calling `az acs` commands without needing to explicitly specify the `-n` flag, which can be really nice when working with the same cluster frequently.
<image src="https://cloud.githubusercontent.com/assets/116461/24076700/9d490a58-0bf4-11e7-94c4-2486eb8d88d2.png" width="400px" />

[ACS] Adding support for configuring a default ACS cluster

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_validators.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/tests/recordings/test_appservice_error_polish.yaml
src/command_modules/azure-cli-appservice/tests/recordings/test_webapp_git.yaml
src/command_modules/azure-cli-appservice/tests/recordings/test_webapp_simple_create.yaml
src/command_modules/azure-cli-appservice/tests/test_webapp_commands.py
src/command_modules/azure-cli-appservice/tests/test_webapp_validators.py

Fix #1369 
```bash
1.	az group create -n myRG -l eastus
2.	az webapp create -g myRG -n myWeb1 
(this should automatically create a plan named ‘myWeb1_Plan’. CLI will output a warning to communicate)
3.	az webapp create -g myRG -n myWeb2
(CLI will detect whether there is a plan in myRG to use, and then create myWeb2 into ‘myWeb1_Plan’)
4.	az webapp create -g myRG -n myWeb3 –plan myWeb1_Plan
(You can always call out the plan name and CLI will use it if exists; otherwise it will create one)
5.	az group create -n myRG2 -l estsus
6.	az webapp create -g myRG2 -n myWeb4 –plan /subscriptions/…/resourceGroups/myRG/providers/Microsoft.Web/serverfarms/ myWeb1_Plan
(If you create a web in a different group, you can always reference an existing plan by using full id)
```

appservice: support to create plan when create a webapp

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py

This is to workaround a known server replication issue, and we were suggested by AAD team to retry. 
Note, the graph error code list is not published with the API, so I had to fall back to error text match.  
There will be no big consequences from over-matching, as the CLI command will just re-try a bit more times

rbac: catch more graph errors before retry

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/tests/test_profile.py

login: set default subscription to one with the state of "Enabled"

---

src/command_modules/azure-cli-network/tests/test_network_commands.py

The ExpressRoute service updated the service to return a useful error message rather than "An error occured." Updated the test to check for this new error.

[Network] Fix ExpressRoute live test

---

src/azure-cli-core/azure/cli/core/_help.py

This is intended to improve readability of examples. #2535

Add blank line after each example.

---

src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_util.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/commands.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/custom.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/help.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/params.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/validators.py

Fixes https://github.com/Azure/azure-cli/issues/2582
```
(env) vishrut@mac azure-cli (monitor-2582) $ az monitor diagnostic-settings create -h
Command
az monitor diagnostic-settings create: Creates diagnostic settings for the specified resource.
Arguments
--resource-id [Required]: The identifier of the resource.
--logs                  : JSON encoded list of logs settings. Use @{file} to load from a file.
--metrics               : JSON encoded list of metric settings. Use @{file} to load from a file.
--resource-group -g     : Name of the resource group.
--storage-account       : Name or ID of the storage account to which you would like to send
Diagnostic Logs.
--tags                  : Space separated tags in 'key[=value]' format. Use '' to clear existing
tags.
--workspace             : …
```

[Monitor] Refactoring diagnostic-settings create parameters

---

src/azure-cli-core/azure/cli/core/sdk/__init__.py
src/azure-cli-core/azure/cli/core/sdk/util.py
src/azure-cli-core/azure/cli/core/sdk/validators.py
src/azure-cli-core/setup.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/commands.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/params.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/validators.py

Moving the common utility commands related to sdk reflection to be used in devtestlabs. 
Feel free to suggest better command module name then `sdk` :)
Haven't moved sql utils as [it's been changed heavily](https://github.com/Azure/azure-cli/blame/master/src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_util.py) and may require more time to understand and move them.

Refactoring SDK reflection utils into azure.cli.core.sdk

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/tests/recordings/test_webapp_ssl.yaml
src/command_modules/azure-cli-appservice/tests/test_webapp_commands.py
src/command_modules/azure-cli-appservice/tests/test_webapp_commands_thru_mock.py

fix #2561
(per standard, wildcard only covers one level of subdomains)

appservice: support binding wildcard certificates

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/tests/test_profile.py

Fix #2591. 
The context is users might have tenant where his account is disabled by admin, failing the whole login flow is not the optimal experience as this blocks them from using subscription in legit tenants.

Login: skip erroneous tenant

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/tests/test_webapp_commands_thru_mock.py

appservice: support to get external ip address used for DNS A records

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_client_factory.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/tests/recordings/test_webapp_config.yaml
src/command_modules/azure-cli-appservice/tests/recordings/test_webapp_slot.yaml
src/command_modules/azure-cli-appservice/tests/test_webapp_commands.py

It was reported by support folks. It turns out the webapp's slot creation never really picks up the site config client code provided. After cross checked with java sdk team, i am applying the workaround to explicitly set the config after creation.  Also added a test for this

appservice: include site config on cloning slot

---

src/azure-cli/setup.py

Adding lab and monitor previews as default cli install

---

src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/validators.py

Fixes https://github.com/Azure/azure-cli/issues/2674
@ericame Can you please see whether this would be the right defaulting logic for the "Shared IP configuration" ?

[DevTestLab] Verify existence of inbound nat rules before defaulting to Shared IP configuration

---

packaged_releases/windows/build.cmd

msbuild was not added to the path correctly due to the spaces in the path.
Now fixed.

Fix msi path to include msbuild in path

---

scripts/automation/release/packaged.py

Fix None Type error on os.path.expanduser(…)
If archive_dest was None, the call to expanduser would fail.

Fix TypeError on a release script

---

Dockerfile

`pip install` is not installing the local wheels but picking up packages from index, hence the change.

Dockerfile pip install from local wheels

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py

Make argument parameters match up.

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py

Add some more error checking/handling.

---

doc/authoring_command_modules/README.md
doc/authoring_command_modules/authoring_commands.md
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/params.py

This module has moved to azure.cli.core.commands

Fix doc references to azure.cli.commands

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
doc/authoring_command_modules/README.md

Add clearer guidelines on modifying changelog

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py

Fixes https://github.com/Azure/azure-cli/issues/2184
@tjprescott

Error out if you try to list resources for a group that doesn't exist.

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py

Part of https://github.com/Azure/azure-cli/issues/2694

Add docs for az lock update.

---

src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/custom.py
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/help.py
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/params.py
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/validators.py

Fixes https://github.com/Azure/azure-cli/issues/2687
Until now user were allowed to use them but not explicitly. This enables supplying the name of the secrets to be used from the lab's secret store itself. 
Reference: https://azure.microsoft.com/en-us/updates/azure-devtest-labs-keep-your-secrets-safe-and-easy-to-use-with-the-new-personal-secret-store/
**NOTE**: I'll be sending new PRs on DTL work but it's not necessary for us to ship them with this release so feel free to label it as team prefers

[DevTestLab] Explicitly enable usage of saved secrets while lab vm creation

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/tests/recordings/test_network_active_active_cross_premise_connection.yaml
src/command_modules/azure-cli-network/tests/recordings/test_network_active_active_vnet_vnet_connection.yaml
src/command_modules/azure-cli-network/tests/test_network_commands.py

Closes #2050.
Adds support for active-active VNet gateways according to: https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-activeactive-rm-powershell
Essentially these scenarios all boil down to the number of public IP addresses associated with the gateway. Active-standby gateways have only one, while active-active gateways have 2. So the CLI will accept 1 or 2 public IP addresses on create or update and enables or disables active-active mode accordingly. This simplifies the scenarios as they exist in Powershell with minimal expansion of the CLI command's surface area.
-------------------------
(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring …

[Network] Support active-active VNet gateways

---

src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/azure/cli/core/parser.py
src/command_modules/azure-cli-find/azure/cli/command_modules/find/_gather_commands.py

- [n/a ] The PR has modified HISTORY.rst with an appropriate description of the change.
This change is infrastructure only, no az cli facing functionality has been changed.
- [ n/a] Each command and parameter has a meaningful description.
- [ n/a] Each new command has a test.
Loading descriptions for commands can be expensive (inspecting/parsing doc strings for handlers). This change allows for a caller to provide a callable for the description parameter. The az parser overrides the default argparse description handling to delay load the description if callable was passed. 
The PR also …

Performance: Allow delay-loading of command descriptions

---

src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_params.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_validators.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/commands.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/custom.py

This pull request provides better documentation for Key Vault certificate importing showing the path for creating a service principal, importing the cert into key vault, and using it to provision a vm via secrets.
This pull request also fixes an issue where we `az keyvault certificate import` was not sniffing the type of certificate and properly specifying the content type. Now, we sniff out either PEM or PFX and properly encode the payload for the server.

Enable better certificate importing for Key Vault

---

src/azure-cli-core/azure/cli/core/commands/validators.py
src/azure-cli-core/tests/test_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/tests/recordings/test_diagnostics_extension_install.yaml

This will fix VM/VMSS diagnostics live test failure
- ~[] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log))~.
- ~[ ] Each command and parameter has a meaningful description.~
- [x ] Each new command has a test.

vm:load json file correctly for setting extensions

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_format.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/tests/recordings/test_network_active_active_cross_premise_connection.yaml
src/command_modules/azure-cli-network/tests/test_network_commands.py

Closes #1602. 
Adds test coverage for the previously not covered `vpn-connection shared-key` commands. Fixes the output of the vpn-connection create command, which previously exposed the deployment "wrapping". This is technically a breaking change (and called out as such in the HISTORY). 
---

[Network] VPN-connection shared key fixes

---

src/azure-cli-testsdk/azure/cli/testsdk/base.py
src/command_modules/azure-cli-storage/tests/recordings/test_storage_blob_incremental_copy.yaml
src/command_modules/azure-cli-storage/tests/recordings/test_storage_blob_upload_128mb_file.yaml
src/command_modules/azure-cli-storage/tests/recordings/test_storage_blob_upload_64mb_file.yaml
src/command_modules/azure-cli-storage/tests/recordings/test_storage_blob_upload_midsize_file.yaml
src/command_modules/azure-cli-storage/tests/recordings/test_storage_blob_upload_small_file.yaml
src/command_modules/azure-cli-storage/tests/storage_test_util.py
src/command_modules/azure-cli-storage/tests/test_storage_blob_copy_scenarios.py
src/command_modules/azure-cli-storage/tests/test_storage_blob_live_scenarios.py
src/command_modules/azure-cli-storage/tests/test_storage_blob_scenarios.py

_There isn't product change included in this pull request._
---

Add live test case for blob copy scenario

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/tests/test_webapp_commands_thru_mock.py

SSL certificates are associated with the the app service plan/server farm in Azure, so use the web app's `server_farm_id` to extract the associated resource group for any `bind`, `unbind`, or `upload` actions. Fixes #2750

Use the app service plan's resource group for cert operations

---

scripts/curl_install_pypi/install
scripts/curl_install_pypi/install.py

- Check anaconda and improve tab completion set up
- Clearer message for native dependencies
- Change SHA256 as script contents changed
Closes https://github.com/Azure/azure-cli/issues/2377
Closes https://github.com/Azure/azure-cli/issues/2679
NOTE: After PR merged, upload new scripts to storage account.

Install script improvements

---

azure-cli.pyproj
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_validators.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/tests/recordings/test_functionapp_e2e.yaml
src/command_modules/azure-cli-appservice/tests/recordings/test_webapp_e2e.yaml
src/command_modules/azure-cli-appservice/tests/recordings/test_webapp_ssl.yaml
src/command_modules/azure-cli-appservice/tests/test_webapp_commands.py
src/command_modules/azure-cli-find/tests/test_find.py

1. For commands that function app shares the implementation with the existing webapp ones, add a validator to ensure the command works on the right app type. This prevents the situation that user invokes "az functionapp show/list", but see a webapp dumped out
2. Fix CI break caused by `find` index bugs #2805

appservice: add type validators

---

doc/configuring_your_machine.md
doc/recording_vcr_tests.md

Fix Markdown formatting in a couple of doc files

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/tests/recordings/test_network_dns_zone_import_export.yaml

Fixes #2752.  Note that issue #2824 remains and can only be addressed by a service side fix.
---

[Network] Make DNS Zone record imports relative

---

src/command_modules/azure-cli-find/HISTORY.rst
src/command_modules/azure-cli-find/azure/cli/command_modules/find/custom.py
src/command_modules/azure-cli-find/tests/test_find.py

Fixes #2805
```
$ az find -q keyvault list
`az keyvault list`
List key vaults.
`az keyvault key list`
List keys in the specified vault.
`az keyvault certificate list`
List certificates in the specified vault.
`az keyvault secret list`
List secrets in the specified vault.
`az keyvault certificate list-versions`
List the versions of a certificate.
`az keyvault secret list-versions`
List the versions of the specified secret.
`az keyvault key list-versions`
List the versions of the specified key.
`az keyvault certificate issuer list`
List certificate issuers for the specified vault.
`az keyvault certificate issuer admin list`
List admins for a specified certificate issuer.
`az keyvault certificate contact list`
Gets the certificate contacts for the specified vault.
```

Improve `az find` search results

---

src/azure-cli-core/azure/cli/core/application.py
src/azure-cli-core/azure/cli/core/parser.py

Fixed regression introduced by the performance work that made the help subsystem confused about commands vs. command groups (we now replace command groups we know won't match the arguments passed in with a dummy command). 
Fixes #2830 
---
- [n/a ] Each command and parameter has a meaningful description.

Fix #2830 - subgroups incorrectly shows as commands in help

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/tests/recordings/test_network_traffic_manager.yaml
src/command_modules/azure-cli-network/tests/test_network_commands.py

Fixes #2839. Clarifies that `--type` is a required part of the endpoint ID and no longer attempts to update the endpoint type in `az traffic-manager endpoint update`. Adds test coverage for all traffic manager commands.
---

[Network] Fix Traffic Manager type handling 

---

.gitignore
Jenkinsfile
scripts/jenkins_archive.sh
scripts/jenkins_build.sh
scripts/jenkins_perf.sh
scripts/performance/measure.py

1. Add build task
2. Add basic performance test task
3. Add performance measure script
---

Initiate Jenkins pipeline

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/tests/test_profile.py

login: fix a failure when login twice using the same sp

---

src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_util.py

Use SQL RP URI and subscription id from environment variables in order to skip AAD and connect directly to the resource provider. This is used for SQL internal testing where there is no AAD/ARM frontend so the user has authority to use any subscription id.
---

SQL - ability to connect directly to resource provider

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/telemetry.py
src/azure-cli-core/tests/test_profile.py

We loaded adal modules even though we didn't need any credentials et.al. Refactored the Profile class a bit so we don't load them until they are actually needed.
---

Performance: avoid loading adal and friends for telemetry purposes

---

azure-cli.pyproj
src/command_modules/azure-cli-redis/HISTORY.rst
src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/_help.py
src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/_params.py
src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/commands.py
src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/custom.py
src/command_modules/azure-cli-redis/tests/recordings/test_create_redis_cache.yaml
src/command_modules/azure-cli-redis/tests/test_redis_params.py
src/command_modules/azure-cli-redis/tests/test_redis_scenario.py

Adding ability to scale for Redis Cache, adding tests

---

src/command_modules/azure-cli-resource/HISTORY.rst
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-resource/tests/recordings/test_resource_create.yaml
src/command_modules/azure-cli-resource/tests/test_resource.py

Fix #2606 
1. Support inidividual args like rg, name
2. Support full resource id
3. Support full resource object, or just properties for request payload
4. Checkout the test for usages
//cc: @davidebbo 

resource: support generic resource create

---

src/azure-cli-core/tests/test_arm.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py

This isn't strictly necessary, but it improves the user UX.
If the user asks us to delete a lock that we can find in a different scope, print better error messages to help the user do the right thing.
Addresses:
https://github.com/Azure/azure-cli/issues/2688

Improve UX for Management Lock delete

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py

Be more explicitly tell users that they need to back up files

vm/vmss: improve the warning text when generate ssh key pair

---

src/command_modules/azure-cli-resource/HISTORY.rst
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_client_factory.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-resource/setup.py
src/command_modules/azure-cli-resource/tests/recordings/test_provider_operation.yaml
src/command_modules/azure-cli-resource/tests/test_resource.py

Fix #2908 
I thought for a while and felt the `azure-cli-resource` command module is a better place  than the `azure-cli-role` module because other `provider` commands are already there. Having a command module depend on multiple SDK packages is not a new thing and we have done it on other command modules as well.

Support 'provider operation' commands

---

src/azure-cli-core/azure/cli/core/_help.py
src/azure-cli-core/azure/cli/core/cloud.py
src/azure-cli-core/azure/cli/core/profiles/__init__.py
src/azure-cli-core/azure/cli/core/profiles/_shared.py
src/azure-cli-core/tests/test_cloud.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py

- Specify `min_profile` and/or `max_profile` on any help examples you want to only appear for given profiles.
- Currently implemented for `storage account create -h`
Other changes:
- Change sample profiles to be dates instead of just YYYY-sample.
- API version comparison function supports 'latest'
- Default to 'latest' if a given profile version is not valid.
--- …

Help examples can specify the profiles they belong to

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/tests/test_profile.py
src/command_modules/azure-cli-profile/HISTORY.rst
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_params.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py

This is not a common thing, so users should use a flag of `--allow-no-subscriptions` to opt-in
Fix #2560 

login: support login when there are no subscriptions

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/custom.py

Closes #2928.  Uses the resource group location as the default for storage account create--consistent with other create commands. 
---
[N/A] Each new command has a test.

[Storage] Make 'location' optional in storage account create

---

src/azure-cli-core/azure/cli/core/commands/__init__.py

fixes #2941
Within a command an exception will now cause the error to bubble up with trace. This will help in cases like this issue: #2939
```python
raise Exception("hello world") 
```
```
hello world
File "/Users/david/code/azure/azure-cli/src/azure-cli/azure/cli/main.py", line 36, in main
cmd_result = APPLICATION.execute(args)
File "/Users/david/code/azure/azure-cli/src/azure-cli-core/azure/cli/core/application.py", line 201, in execute
result = expanded_arg.func(params)
File "/Users/david/code/azure/azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 404, in _execute_command
reraise(*sys.exc_info())
File "/Users/david/code/azure/azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 399, in _execute_command
result …
```

reraise rather than raise

---

src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/commands.py
src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/custom.py

Fixes #2952
- Don't load azure.mgmt.redis or msrest modules as part of redis command module load (performance)
- Standardize on exception handling between commands (register exception handler instead of handling the exception in the custom redis create command)
---
- [N.A] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

Performance: avoid loading msrest and azure.mgmt.redis modules as part of redis command package load

---

src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/custom.py
src/command_modules/azure-cli-keyvault/tests/test_keyvault_commands.py

Ran into an issue with ASN1 not parsing correctly due to lack of import of datetime.parser. This should fix this. Also added a unit test to ensure no regression.
```
module 'dateutil' has no attribute 'parser'
File "/Users/david/code/azure/azure-cli/src/azure-cli/azure/cli/main.py", line 36, in main
cmd_result = APPLICATION.execute(args)
File "/Users/david/code/azure/azure-cli/src/azure-cli-core/azure/cli/core/application.py", line 201, in execute
result = expanded_arg.func(params)
File "/Users/david/code/azure/azure-cli/src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_command_type.py", line 76, in _execute_command
result = op(client, **kwargs)
File "/Users/david/code/azure/azure-cli/src/command_modules/azure-cli-keyvault/azure/c …
```

fix asn1 date parse

---

src/command_modules/azure-cli-keyvault/HISTORY.rst
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_params.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_validators.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/custom.py

Due to https://github.com/Azure/azure-rest-api-specs/issues/1153, the `--expires` and `--not-before` parameters for certificate creation do not work. 
This PR:
- **BC:** Removes these parameters from `keyvault certificate create`. A previous PR already removed them from the update command.
- Updates the `keyvault certificate get-default-policy` command to remove these two parameters (all of attributes actually) and to expose the previously deleted `validity_in_months` attribute, which is the only correct way to set the expiration for the certificate.
- Adds a `--validity` convenience argument to `keyvault certificate create` so that the default policy can be used but can be essentially "patched" with the value specified here.  This is necessary to enable the scenario described in #2836. …

[KeyVault] Fix issues with KeyVault create and get-default-policy

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/acs_client.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Might help with https://github.com/Azure/azure-cli/issues/2612
Judging by:
http://docs.paramiko.org/en/2.1/api/client.html
the 'connect' call will load `$HOME/.ssh/id_rsa` if it exists anyway, so don't default it everywhere...

Simplify SSH key handling.

---

src/azure-cli-core/azure/cli/core/util.py

Example:
```
$ az --version
azure-cli (2.0.3+dev)
acr (2.0.1+dev)
acs (2.0.3+dev)
appservice (0.1.3+dev)
batch (2.0.1+dev)
cloud (2.0.1+dev)
component (2.0.1+dev)
configure (2.0.3+dev)
container (0.1.3+dev)
core (2.0.3+dev)
dla (0.0.2+dev)
dls (0.0.2+dev)
documentdb (0.1.3+dev)
feedback (2.0.1+dev)
find (0.0.2+dev)
iot (0.1.3+dev)
keyvault (2.0.1+dev)
lab (0.0.2+dev)
monitor (0.0.2+dev)
network (2.0.3+dev)
nspkg (2.0.0+dev)
profile (2.0.3+dev)
redis (0.2.0+dev)
resource (2.0.3+dev)
role (2.0.2+dev)
sql (2.0.1+dev)
storage (2.0.3+dev)
taskhelp (0.1.1b4+dev)
testsdk (0.1.0+dev)
utility-automation (0.1.1)
vm (2.0.3+dev)
Python (Darwin) 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
Python location …
```

Add Python location to ‘az —version’

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/main.py

Fixes #2926.
Added a alias for the "--version" parameter as requested in #2926 
now ````az -v```` can be used as equivalent to ````az --version````
History maintained.
---
- [ x] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

add alias for az --version (#2926) 

---

src/azure-cli-testsdk/azure/cli/testsdk/base.py
src/azure-cli-testsdk/azure/cli/testsdk/utilities.py

@jaredmoo, please try this out in your SQL test recording.
This pull request replaced the original SHA256 based unique identifier generating algorithm with a system cryptographic-use random bytes base32 encode string. The change will offer higher randomness.

Change the random name generating algorithm

---

src/command_modules/azure-cli-sql/HISTORY.rst
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py
src/command_modules/azure-cli-sql/tests/recordings/test_sql_db_mgmt.yaml
src/command_modules/azure-cli-sql/tests/recordings/test_sql_server_mgmt.yaml
src/command_modules/azure-cli-sql/tests/test_sql_commands.py

These commands were originally called show-usage. I had removed these
commands before GA in order to scope down the design work. Re-adding these
now.
---
```
(env) D:\git\azure-cli [usages ≡]> az sql db list-usages -h
Command
az sql db list-usages: Returns database usages.
Arguments
--name -n           [Required]: Name of the Azure SQL Database.
--resource-group -g [Required]: Name of resource group. You can configure the default group
using 'az configure --defaults group=<name>'.
--server -s         [Required]: Name of the Azure SQL server.
--debug …
```

Added sql server/db list-usages.

---

src/azure-cli-testsdk/azure/cli/testsdk/base.py

I remove this method from the base class in previous change. It breaks the live test cases.

Fix create random name method missing

---

src/azure-cli-core/azure/cli/core/util.py
src/command_modules/azure-cli-keyvault/HISTORY.rst
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_params.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/custom.py
src/command_modules/azure-cli-keyvault/tests/test_keyvault_commands.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/tests/test_role_commands_thru_mock.py

- Quick update to the docs for `--cert`
- Change `az keyvault certificate download` to better reflect the encoding options (PEM and DER).
```
$ az keyvault certificate download -h
Command
az keyvault certificate download: Download a certificate from a KeyVault.
Arguments
--file -f    [Required]: File to receive the binary certificate contents.
--name -n    [Required]: Name of the certificate.
--vault-name [Required]: Name of the key vault.
--encoding -e          : Encoding of the certificate. DER will create a binary DER formatted
x509 certificate, and PEM will create a base64 PEM x509 certificate.
Allowed values: DER, PEM.  Default: PEM.
--version -v           : The certificate version. If omitted, uses the latest version.
--debug                : Increase logging …
```

Enhanced Key Vault Certificate Download and AAD SP Integration

---

src/azure-cli-testsdk/azure/cli/testsdk/utilities.py

I reckon that I underestimate the chances when a short name is required.

Shorten the limitation on random name requirement

---

src/azure-cli-core/azure/cli/core/util.py
src/azure-cli-core/tests/test_util.py

The hex fingerprint of a Key Vault certificate returns as bytes in py3. This corrects that and returns a str as the method says it should.
```bash
$ az keyvault certificate show --vault-name testvaultdj -n testcert --query "x509ThumbprintHex" -o tsv
b'73863FFDAD3BA0E7C08BAEFBAD09F661298341C6'
```
After the fix
```bash
$ az keyvault certificate show --vault-name testvaultdj -n testcert --query "x509ThumbprintHex" -o tsv
73863FFDAD3BA0E7C08BAEFBAD09F661298341C6
```

Fix bytes returned from hex fingerprint -o tsv

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_client_factory.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/setup.py
src/command_modules/azure-cli-appservice/tests/recordings/test_linux_webapp.yaml
src/command_modules/azure-cli-appservice/tests/recordings/test_linux_webapp_quick_create.yaml
src/command_modules/azure-cli-appservice/tests/recordings/test_webapp_e2e.yaml
src/command_modules/azure-cli-appservice/tests/recordings/test_webapp_git.yaml
src/command_modules/azure-cli-appservice/tests/recordings/test_webapp_slot.yaml
src/command_modules/azure-cli-appservice/tests/recordings/test_webapp_ssl.yaml
src/command_modules/azure-cli-appservice/tests/recordings/test_win_webapp_quick_create.yaml
src/command_modules/azure-cli-appservice/tests/test_webapp_commands.py

Changes at high level:
1. Create `webapp` to replace `appservice web` (will maintain `appservice web` for 2 releases before removing)
2. Integrate deployment, and runtime stack configurations on `webapp create`
3. Expose `webapp list-runtimes`
Note, the deprecating mechanism to warn on using old `appservice web` will be submitted as a separate PR which will go through team discussions
Sample:
```
(env) D:\sdk\azure-cli>az webapp list-runtimes
[
...
"node|6.0",
"node|6.1"
...
]
az webapp create -n web1 --plan plan1 --deployment-local-git -r "node|6.1"
az webapp create -n linuxweb1 --plan plan2 -i naziml/ruby-hello

appservice: improvements on create, runtime stack configurations

---

scripts/automation/style/run.py
src/command_modules/azure-cli-documentdb/azure/cli/command_modules/documentdb/__init__.py
src/command_modules/azure-cli-documentdb/azure/cli/command_modules/documentdb/_client_factory.py
src/command_modules/azure-cli-documentdb/azure/cli/command_modules/documentdb/_command_type.py
src/command_modules/azure-cli-documentdb/azure/cli/command_modules/documentdb/_exception_handler.py
src/command_modules/azure-cli-documentdb/azure/cli/command_modules/documentdb/_help.py
src/command_modules/azure-cli-documentdb/azure/cli/command_modules/documentdb/_params.py
src/command_modules/azure-cli-documentdb/azure/cli/command_modules/documentdb/commands.py
src/command_modules/azure-cli-documentdb/azure/cli/command_modules/documentdb/custom.py

Enabling `flake8` check on DocumentDB code results in new PEP8 compliance issue. I fixed all of them in this pull request. Moving forward, style check will be run on DocumentDB for each commit.
Many changes are caused by the removal of `pylint: disable` statement. These switches are not recommended. Disabling a check for the entire scope of a file should be cautious about. I removed most of the `line-too-long` exempts and narrows the scope of other exempts.

Improve code style and readability for DocumentDB

---

scripts/automation/tests/nose_helper.py
scripts/automation/tests/run.py

- Not all tests start with ‘test_’ . Tests can have docstrings explaining what they do and nose will show that string instead of the method name (eg. https://github.com/Azure/azure-cli/pull/3126/files#diff-7781589306c33626caa49df372858dfcR144).
- Also as a fail safe, check that the success value was false. This would have at least not showed TESTS  PASSED when it actually didn’t.
Screenshot below highlights the issue that this fixes.
cc: @troydai

Fix nose test reporting

---

src/azure-cli/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py

Fixes the example cluster name for `az acs create`. The following error message snippet tells the story:
```
Provisioning of resource(s) for container service 'MyContainer_service' in resource group 'MyResourceGroup' failed.\nMessage: 'The domain name label mycontainer_service-myresourcegroup-9d1a89 is invalid. It must conform to the following regular expression: ^[a-z][a-z0-9-]{1,61}[a-z0-9]$.
```
The purpose of this PR is to improve the documentation at this resource:
https://docs.microsoft.com/en-us/cli/azure/acs#create
Fixes #3024

Working example cluster name for `az acs create`

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/tests/test_profile.py

- [x ] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

login: avoid the bad exception when the user account has no subscription and no tenants

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/acs_client.py

It seems after a recent change none of the loaded keys are being used. I have been getting the error:
```
No authentication methods available
File "C:\Users\paverma\AppData\Local\Continuum\Miniconda3\lib\site-packages\azure\cli\main.py", line 36, in main
cmd_result = APPLICATION.execute(args)
File "C:\Users\paverma\AppData\Local\Continuum\Miniconda3\lib\site-packages\azure\cli\core\application.py", line 201, in execute
result = expanded_arg.func(params)
File "C:\Users\paverma\AppData\Local\Continuum\Miniconda3\lib\site-packages\azure\cli\core\commands\__init__.py", line 417, in _execute_command
reraise(*sys.exc_info())
File "C:\Users\paverma\AppData\Local\Continuum\Miniconda3\lib\site-packages\six.py", line 686, in reraise
raise value
File …
```

BugFix: Use one of the loaded keys.

---

src/azure-cli-core/azure/cli/core/application.py

Some command packages want to inspect the set of arguments before they are fed to the parser (i.e. to deprecate/hide commands and give the appropriate error message)
---

Expose application event to notify clients before arguments are fed to parser

---

src/azure-cli-core/azure/cli/core/commands/__init__.py

This change is to preserve the argument's default name (or configured_default) and required flag for later access and better informed tooling support.
This also allows for reloading the configuration with potentially changed defaults without having to reload the entire command table.
Not sure if the change is in the spirit of the existing code, let me know if I can improve on it.

Preserve default name and required flag

---

src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/azure/cli/core/parser.py
src/azure-cli-core/tests/test_parser.py
src/command_modules/azure-cli-batch/tests/test_batch_commands.py

Before, the intent was that the command would be called through the CliCommand's execute method. However, this was accidentally bypassed, and the CliCommand's handler was directly called instead.
This change makes the CliCommand into a pure callable, and the application framework will now call the callable when executing a command.
This was done in preparation for being able to deprecate commands by setting a 'deprecated' flag on the command. Without calling through the CliCommand, there is no way for the command handler to actually make use of the deprecated attribute. 
---
- [N/A] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change …

Infrastucture: Make sure that the command handler is called through CliCommand's __call__ method instead of directly calling the registered handler

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/tests/test_vm_commands.py

Chatted with CRP folks, for usability we will have client side default at 2, which is the minimum of all public regions

avail-set: make FD domain counts optional

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/setup.py
src/command_modules/azure-cli-vm/setup.py

Adds `network watcher test-connectivity` command.
Adds support for `--filters` to `network watcher packet-capture create`.
---

[Network] Network Watcher fixes

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/tests/test_profile.py

Fix #2603. This boosts the perf for commands involving lots of rest calls such as datalake commands transferring TB size file 
It is hard to test at unit test level, but i will start a live run once the PR gets merged 
//cc:@begoldsm

auth: persist adal token cache in memory till process exits

---

src/command_modules/azure-cli-dla/HISTORY.rst
src/command_modules/azure-cli-dla/azure/cli/command_modules/dla/custom.py
src/command_modules/azure-cli-dla/setup.py

These are strings and not enums. This was fixed but must not have made
it in the merge.
Update version and readme
---

Merge bug in ADLA

---

.gitignore
src/command_modules/azure-cli-sf/HISTORY.rst
src/command_modules/azure-cli-sf/MANIFEST.in
src/command_modules/azure-cli-sf/README.rst
src/command_modules/azure-cli-sf/azure/__init__.py
src/command_modules/azure-cli-sf/azure/cli/__init__.py
src/command_modules/azure-cli-sf/azure/cli/command_modules/__init__.py
src/command_modules/azure-cli-sf/azure/cli/command_modules/sf/__init__.py
src/command_modules/azure-cli-sf/azure/cli/command_modules/sf/_factory.py
src/command_modules/azure-cli-sf/azure/cli/command_modules/sf/_help.py
src/command_modules/azure-cli-sf/azure/cli/command_modules/sf/_params.py
src/command_modules/azure-cli-sf/azure/cli/command_modules/sf/cluster_auth.py
src/command_modules/azure-cli-sf/azure/cli/command_modules/sf/commands.py
src/command_modules/azure-cli-sf/azure/cli/command_modules/sf/custom.py
src/command_modules/azure-cli-sf/azure_bdist_wheel.py
src/command_modules/azure-cli-sf/setup.cfg
src/command_modules/azure-cli-sf/setup.py
src/command_modules/azure-cli-sf/tests/__init__.py
src/command_modules/azure-cli-sf/tests/manual_scenario_sf_commands.py
src/command_modules/azure-cli-sf/tests/manual_sf_commands.py

This PR introduces the following set of changes
- New command module designed to manage Service Fabric clusters once they have been provisioned. This includes managing the cluster entities such as nodes and applications
- New preparer for scenario tests that require an active cluster connection
- Small set of unit tests that cover basic commands that do not actively alter the state of the Service Fabric cluster

Adding support for Service Fabric client commands

---

src/command_modules/azure-cli-sf/azure/cli/command_modules/sf/commands.py
src/command_modules/azure-cli-sf/azure/cli/command_modules/sf/custom.py
src/command_modules/azure-cli-sf/setup.py

This fixes a few critical problems in the Service Fabric commands:
- Correctly maps `application manifest` to `get_application_manifest`. Previously was erroneously mapped to a health command
- Fixes custom commands having to create multiple clients, and having duplicate parameters.
- Improves argument validation for `create service` and fixes argument passing for correlated services when no correlation services specified.

Improvements to ServiceFabric commands

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/tests/test_webapp_commands_thru_mock.py

The spec was wrong, but too late for webapp team to correct it for //build

appservice: workaround a command error caused by a sdk library bug

---

src/azure-cli-core/azure/cli/core/parser.py

The detection logic for determining if a parser represented a group or an individual comand was recently regressed

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/tests/test_webapp_commands_thru_mock.py

Fix #3227 
This was broken by the latest functionapp integration. Add unit test coverage as functional test for log streaming is not applicable to run as an automation test

webapp: fix broken log tail command

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py

The `appservice web` to be gone in June, removing it causes less confusions

appservice: update short summary of appservice group to exclude webapp

---

scripts/automation/tests/verify_packages.py

Verifies the following as part of CI:
A valid command module .whl for the CLI should:
- Not contain any __init__.py files in directories above azure.cli.command_modules.
Does the package have a azure_bdist_wheel.py file?
Does the package have a setup.cfg file?
Does setup.py include 'cmdclass=cmdclass'?
---
(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/au …

Verify command packages have the wheel extension applied

---

src/azure-cli-core/azure/cli/core/commands/__init__.py

`MissingSubscriptionRegistration` could surface during LRO polling, which was not caught by out current code. I had to expand the scope to capture it. 
The code change is trivial, as i just put the whole handler invocation into a loop body with count at 2 Feel free to propose neater coding practice. I have tried to extract to a individual method, but it doesn't look better
//cc: @derekbekoe @johanste

RP Auto-Reg: capture missing subscription registration error on LRO

---

Jenkinsfile

Running live test for every commit deems to be too much a burden of our infrastructure as the scale of the tests keeps increasing. This change reverses the live test cadence to be daily.

Reverse Jenkins build cadence to daily

---

scripts/dev_setup.py

To avoid errors like:
```bash
Run pylint
Modules: azure-cli-core
************* Module azure.cli.core.commands.parameters
E: 23, 4: No name 'mgmt' in module 'azure' (no-name-in-module)
E: 23, 4: Unable to import 'azure.mgmt.resource' (import-error)
```

dev-setup: install azure-mgmt-nspkg to avoid errors of no-name-in-module

---

azure-cli.pyproj
src/command_modules/azure-cli-vm/tests/test_vm_parameters.py

Added a unit test in support of TS issue #3005. This ensures that, for a consistent input order, the generated template code has a consistent order.
---

[VM] Add unit test to verify stability of multi-NIC ordering

---

requirements.txt
src/azure-cli-core/setup.py
src/azure-cli-core/tests/test_output.py

Brief:
1. Fix `tabulate` to 0.7.7 and remove it from `requirements.txt`.
2. Fix the output test in Core.

Fix output tests for core and pin tabulate version

---

scripts/automation/release/notes.py

Closes https://github.com/Azure/azure-cli/issues/2547
Iterate through all modules, find`HISTORY.rst` files and collate the release notes after a given date.
Example usage:
```
$ python -m scripts.automation.release.notes -d 2017-04-03 > notes.txt
$
```
```
$ cat notes.txt
AZURE-CLI
---------
* notes for this module...
AZURE-CLI-COMMAND_MODULES-NSPKG
-------------------------------
* Initial release
AZURE-CLI-CORE
--------------
*core: Cloud configuration - use 'resource manager' endpoint if 'management' endpoint not set
AZURE-CLI-ACR
-------------
* Minor fixes.
AZURE-CLI-ACS
-------------
* remove windows profile before PUT call for scale command (#2755)
AZURE-CLI-APPSERVICE
--------------------
* Use the app service plan's resource group for cert operations (#2750)
AZURE-CLI-BATCH …
```

Script to generate release notes

---

src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py

Ran into it when tried to create a AAD app
Fix #1068
~~- [ ] Each new command has a test.~~

ad:mention time format in descriptions for --start-date/--end-date

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py

Fix #3342 
Drop the `cloud console` mentioning which has a perm storage now. Moving forward let us try not to mention other products any more, as their evolvings will render the cLI text not accurate any more

vm: update the warning text on generating ssh keys

---

src/command_modules/azure-cli-profile/HISTORY.rst
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_params.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py

Was exposed for java sdk team. They confirmed they have updated their end and no longer require this function anymore.

output deprecating message on using --expanded-view

---

azure-cli.pyproj
src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/application.py
src/azure-cli-core/tests/test_application.py
src/command_modules/azure-cli-rdbms/tests/recordings/test_mysql_proxy_resources_mgmt.yaml
src/command_modules/azure-cli-rdbms/tests/recordings/test_postgres_proxy_resources_mgmt.yaml
src/command_modules/azure-cli-rdbms/tests/test_rdbms_commands.py

Closes #3325.
1. Command path and command name are no longer case sensitive
2. Long and short options REMAIN case-sensitive
---

Case insensitive command path

---

azure-cli.pyproj
src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/tests/recordings/test_vm_open_port.yaml
src/command_modules/azure-cli-vm/tests/test_vm_commands.py

Closes #3322.
With the change, the `vm open-port` command will no longer attempt to update the NIC or subnet unless a NSG was not already found and had to be created.  Avoids an unnecessary REST call and opportunity for failure. 
---

[VM] `vm open-port` fix

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/tests/recordings/test_vm_extension.yaml
src/command_modules/azure-cli-vm/tests/test_vm_commands.py

Fix bugs I ran into when I investigated diagnostics support. Since related change is trivial, I combine them
* vm: fix "vm extension list" crash if the VM has no extensions
* vmss: update arg description for 'vmss delete-instances --instance-ids'
* vmss: hide arg 'vmss show --ids', which is not supposed to work because of 'instance-id' arg

vmss/vm: misc bug fixes

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py

Closes #2215. Partial addresses #1528.
---

Add wait/no-wait support to "az disk" commands.

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/tests/recordings/test_vmss_vms.yaml
src/command_modules/azure-cli-vm/tests/test_vm_commands.py

~For #2962, the change is fairly trivial, but we just can't do it now as it is a breaking change. So emit out a warn and do it for the next release~
EDIT: Fix #2962 very few users are using this command, so I go ahead and just submit the change 
```json
{
"instance 0": "13.64.254.52:50000",
"instance 1": "13.64.254.52:50001"
}
```

vmss: let 'list_vmss_instance_connectio_info' include instance id in the output

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/tests/test_profile.py

Fix #3319 
Note, from ADAL's aspect, the tenant should be 'adfs', which means in the  `login` command users should supply `--tenant adfs`, but I decided not to enforce this from CLI as it is a bit odd for on-prem user. So users  can just configure in the cloud context using original authority url `.../adfs`, and then run `az login -u <user> -p <pwd>`
//cc: @bganapa

login: expose ADFS flow for azure stack env

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/blob.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/custom.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/file.py

Conditionally removing the use of validate_content for the older api
---

profile support: validate_content parameter is not supported in 2015-04-05 data storage sdk

---

nose.cfg
scripts/automation/tests/nose_helper.py
src/azure-cli-testsdk/azure/cli/testsdk/base.py
src/azure-cli-testsdk/azure/cli/testsdk/vcr_test_base.py

1. Print the executed commands and exit code when a test is failed.
2. Print the failed commands' output.
3. Hide msrest, vcr, or any other logger.
---

Fix #2513: Update logging effect in automation

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/tests/test_profile.py
src/command_modules/azure-cli-profile/HISTORY.rst

This was broken by the latest resource SDK with new paging support based on generators. I am adding new tests for it. 

login:  support login with a user account with no associated subscriptions

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_format.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py

Fix #2684. 
This is the same fix I applied for VM list-usage.
---

[Network] Fix output format for list-usages.

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/cloud.py
src/azure-cli-core/tests/test_cloud.py

When initializing cloud config, write all clouds once instead of writing for each cloud
Closes https://github.com/Azure/azure-cli/issues/3255
---

Fix concurrent invocations of ‘az’ due to cloud config writes

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

Fixes #3377.
Attempts to default things like frontend IP, backend address pool, HTTP settings and HTTP listener when the collection contains only a single item. This is normally the case since we create these automatically when creating AppGateways/LoadBalancers.
---

[Network] Improvements to App-Gateway and LB defaults

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/tests/recordings/test_vmss_create_none_options.yaml
src/command_modules/azure-cli-vm/tests/recordings/test_vmss_create_with_app_gateway.yaml
src/command_modules/azure-cli-vm/tests/test_vm_actions.py
src/command_modules/azure-cli-vm/tests/test_vm_commands.py
src/command_modules/azure-cli-vm/tests/test_vm_defaults.py

Fix one scenario mentioned in the #3051
Do it only when we create a new vnet for the scale-set , which is the majority case. 
When reuse vnet, we will prompt still. I had change to supply the defaults as well, but backed out as the complexity is not worth it.

vmss: provide default app-gateway subnet suffix 

---

scripts/automation/tests/verify_dependencies.py
src/command_modules/azure-cli-appservice/setup.py

I hope this will get #3498  fixed, maybe #3497 as well
This was triggered by the [msrest 0.4.8](https://github.com/Azure/msrest-for-python/releases/tag/v0.4.8) released last week. The new requests package pulled in now throws on any lower version of urllib3. 
Note, the change of fixing the version in the command module was done when urllib3 had not released a fix yet.  

fix a set up break triggered by new versions of requests and msrest

---

scripts/github_bot/api/app.py

Adds link to https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli in GitHub release notes.
e.g. https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.0.7

Add release notes link to GitHub releases

---

scripts/automation/style/pylint_disable_check.py
scripts/setup.py

The tool will scan all the source files and generate a report of the status of all the pylint disables in our code base. There are many unnecessary escapes we can remove from the source code and this tool helps us to organize the effort.
Here's the rules we escaped today:
```
rule                               count
-------------------------------  -------
line-too-long                        196
no-member                            134
unused-argument                      120
too-few-public-methods                78
unused-variable                       66
redefined-outer-name                  62
unused-import                         55
protected-access                      33
no-self-use                           32
too-many-instance-attributes          30
broad-except …
```

Add tool to summarize pylint disable statement in source

---

src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-testsdk/azure/cli/testsdk/preparers.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_command_type.py
src/command_modules/azure-cli-batch/tests/batch_preparers.py
src/command_modules/azure-cli-cloud/azure/cli/command_modules/cloud/custom.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/custom.py
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/custom.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-sf/azure/cli/command_modules/sf/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/disk_encryption.py

The rule too-many-arguments is disabled project-wise.

Eliminating too-many-arguments pylint disable rule

---

src/azure-cli-testsdk/azure/cli/testsdk/base.py

This change removes the fallback mechanism added in the previous commit. As all the recordings are moved to latest folder and CI passed successfully the fallback mechanism is not required.

Remove backward compatible feature in test recording seeking

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/acs_client.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

When using `acs create`, the CLI assumes the use of `~/.ssh/id_rsa` if not otherwise specified. In `acs kubernetes get-credentials`, it only tries to load the specified --ssh-key-file or what ever is in the ssh agent at the time. This will fail if `~/.ssh/id_rsa` is not added to the agent or not specified on the command line.
This pull request will load `~/.ssh/id_rsa` if no keys are found in the ssh agent and no key is specified via --ssh-key-file. It will also provide a better message to the user in the case no keys are found.
Fixes #2403 #3605
---

fix acs kube get-credentials ssh-key loading

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py

Fix #3625 
The change is on a command just implemented in this sprint, hence no history doc update

webapp: fix a typo in arg name

---

src/azure-cli-core/azure/cli/core/util.py
src/azure-cli-core/tests/test_util.py
src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/tests/recordings/latest/test_vm_create_ubuntu.yaml
src/command_modules/azure-cli-vm/tests/recordings/latest/test_vmss_create_idempotent.yaml
src/command_modules/azure-cli-vm/tests/recordings/test_vmss_create_idempotent.yaml
src/command_modules/azure-cli-vm/tests/test_vm_commands.py

Fixes #3563.  Uses a hash algorithm to generate a deterministic hash. For VM and VMSS create, we hash the ID as that is sufficient, but you could seed it with additional strings if needed.
Added tests for VM and VMSS create to verify idempotency, as well as unit tests of the "hash_string" utility method.
I've checked the other template creates and they did not use the "random_string" method, so they are fine.
---

[VM/VMSS] Fix idempotency for VM/VMSS create

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py

webapp: ensure default browser is used on osx and w/o error on launching

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/cloud.py
src/azure-cli-core/tests/test_cloud.py
src/azure-cli-testsdk/azure/cli/testsdk/utilities.py

Closes https://github.com/Azure/azure-cli/issues/3617
Only init known clouds once (when _profile is loaded) rather than on each call to get_clouds.
This means at most, we write to clouds.config once.
---

Improve concurrent handling of clouds.config file

---

scripts/curl_install_pypi/install

Add sha256sum(1) as a backup for shasum(1) when verifying checksum; shasum is not included by default in some linux distros (e.g. redhat).
Modify shasum check to use the command(1) builtin.
Refactor command checks not to rely on value of `$?`.

shasum fallback to sha256sum

---

scripts/curl_install_pypi/install
scripts/curl_install_pypi/install.py

`urlretrieve` of `urllib` does not respect corporate proxy settings for some reason. `urllib2` in python 2.7 works as intended. This PR changes `urlretrieve` to `urlopen` and saves the file manually.
---

Use urlopen instead of urlretrieve

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/tests/test_webapp_commands.py

webapp: mask docker registry passwords from 'webapp appsettings/container' commands' output

---

Dockerfile
packaged_releases/docker/Dockerfile

Something somewhere changed so not we require `make` to build the Docker image.
Closes https://github.com/Azure/azure-cli/issues/3657

Fix failing Docker builds by adding 'make' as dependency

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_actions.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py

Fix #3649 
`lsof -p <p-id>` showed the active socket number peeked at less than 100 vs 1000 before the change.
A whole live query returns 4000+ images after around 50 seconds. Supplying either `--publisher` or `--offer` take way less time at < 10 seconds.

vm: fix the error of 'Too many open files' when do 'vm image list --all'

---

azure-cli.pyproj
src/command_modules/azure-cli-resource/HISTORY.rst
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_validators.py
src/command_modules/azure-cli-resource/tests/recordings/latest/test_group_deployment.yaml
src/command_modules/azure-cli-resource/tests/test-params.json
src/command_modules/azure-cli-resource/tests/test-template.json
src/command_modules/azure-cli-resource/tests/test_custom.py
src/command_modules/azure-cli-resource/tests/test_resource.py

Fixes #3729.
Ensures that `--parameters <JSON String>` or `--parameters @<file>` no longer are ignored if the contents contain an = sign.  Enhances existing test to protect against regressions for this scenario.
---

[ARM] Fix issue with deployment parameter parsing

---

src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/_help.py

Fix copy-paste typo and replace `load` with `purge` command in "Purge content for Javascript and CSS styles" example.

Fix "az cdn endpoint purge" command example in documentation

---

pylintrc

This PR does two things. One, it switches from pylint's cryptic codes for checkers to their short names which are much easier to reason about.
Two, I added naming hints (which are off by default due to `invalid-name` being disabled). At PyCon US 2017 I talked with @troydai about adding a few things to this pylintrc to help promote its use within Microsoft and this change is (currently) it.

Touch up pylintrc

---

src/azure-cli-core/HISTORY.rst

To get CI's readme validating task pass
- [N/A ] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).
- [ N/A] Each command and parameter has a meaningful description.
- [ N/A] Each new command has a test.

update seperator in the history.rst of azure-cli-core

---

doc/recording_vcr_tests.md
src/azure-cli-testsdk/azure/cli/testsdk/__init__.py
src/azure-cli-testsdk/azure/cli/testsdk/base.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/test_role.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage_batch_operations.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage_blob_copy_scenarios.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage_blob_live_scenarios.py

After moving to the devtools, the original LiveTest stop working because
of the missing cmd function. The newly created LiveScenarioTest will
take over its place. The LiveTest will be eventually removed from the
devtools package since the live_only decorator is sufficent.
---

Replace dependencies of LiveTest with LiveScenarioTest

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py

Fix #3572 
1. Remove the `sas` term from the help text for the `blob uri`. Sas uri is not supported as image/disk/snapshot source 
2. Call out `same region` on the `--source` argument . #3809 was logged to track server bad error
3. Make `--source` mandatory. Honestly, I don't remember why I used `register_extra_cli_argument` on a custom command, but now i am removing it
No new test coverage is needed. The main production code change is to make `--source` mandatory, a petty simple one. 

vm image create: improve doc and error messages for the --source argument 

---

src/azure-cli-core/setup.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/setup.py

A bit clean up after #3105 was merged. Since ssh key gen was moved to azure-cli-core, the `paramiko` should become its dependency, and vm command module no longer needs it
//CC: @brendandburns , @troydai 
- [ na] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).
- [ na] Each command and parameter has a meaningful description.
- [ na] Each new command has a test.

vm: remove dead code and move 'paramiko' dependency to azure-cli-core

---

src/azure-cli-core/azure/cli/core/commands/arm.py
src/azure-cli-core/azure/cli/core/tests/test_arm.py
src/command_modules/azure-cli-resource/HISTORY.rst
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/latest/test_resource_id_scenario.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_resource.py

Partially addresses #3479.
Enhances the parse_resource_id code to yield parameters that conform to the syntax required by the resource commands.
`providers/{resource_namespace}/{resource_parent}/{resource_type}/{resource_name}`
Note that this results in some bizarre behavior:
`providers/Microsoft.Network/virtualNetworks/vnet1/providers/Microsoft.Authorization/locks/lock1`
parses into the following:
```
resource_namespace: Microsoft.Network
resource_parent: virtualNetworks/vnet1/providers/Microsoft.Authoriation/
resource_type: locks
resource_name: lock1
```
So the namespace doesn't match the actual target resource's type at all. This wonky format required is what is required to use the SDK. 
Adds additional unit tests to prevent regressions in this parsing. 
--- …

[ARM] Add `--ids` support to resource commands

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/command_modules/azure-cli-profile/HISTORY.rst
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_params.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py

//cc: @mayurid @jianghaolu @selvasingh
Per our discussion and following mail exchange
```bash
(env) D:\sdk\azure-cli>az ad sp create-for-rbac -n yugangwdelete --sdk-auth
{
"clientId": "56dc7894-2cb8-40d8-9a29-fdc8b6c66xxx",
"clientSecret": "2457b4e1-1e42-4cd8-98f2-3e510a502xxx",
"subscriptionId": "0b1f6471-1bf0-4dda-aec3-cb9272f09xxx",
"tenantId": "54826b22-38d6-4fb2-bad9-b7b93a3e9xxx",
"resourceManagerEndpointUrl": "https://management.azure.com/",
"activeDirectoryEndpointUrl": "https://login.microsoftonline.com"
}
```

support generate sdk auth info

---

LICENSE.txt

GitHub parses LICENSE files strictly and doesn't recognize this one as MIT due to its first line. This makes it conform, which enables a nifty link to the user's rights and responsibilities as shown here:
I copied this MIT license from [Azure/draft](https://github.com/Azure/draft) which we recently got approved, so I know CELA is ok with this formatting.

Refactor LICENSE.txt to make GitHub happy.

---

src/command_modules/azure-cli-sql/HISTORY.rst
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/params.py

This param was not intentionally added and is unusable. A different param which sets server identity will be added in a separate change.
Additionally removed 'Authentication' arg group from sql server create because it was confusingly applied to all args, not just authentication-related args.
---

Removed sql server create --identity param.

---

doc/sphinx/azhelpgen/azhelpgen.py

This is for the Help CI system (ref docs.) and not product code.

Skip invalid commands when generating help

---

src/command_modules/azure-cli-interactive/azclishell/app.py
src/command_modules/azure-cli-interactive/azclishell/gather_commands.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/tests/test_gather.py

Uses cached values for terminal size so performance change isn't noticeable
---

Removing resizing from loops to affect performance for interactive in python2.7

---

src/azure-cli-testsdk/azure/cli/testsdk/utilities.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_resource.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

Fix #3804
1. Have to make the tests live only as under playback the tests run too fast and timing based progress logic doesn't have a chance to get involved.
2. A bit surprising (and pain) that I had to write non trivial code to force the verbose logging so the test can get the progress output to verify. Let me know if can be simplified

test: add progress specific tests for vm & deployment create

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py

Issue: https://github.com/Azure/azure-cli/issues/3745
The marker option never works in the CLI context because the commands never return the marker value when --num-results is specified. A fix is being worked to improve overall paging mechanism in CLI. In the meantime, this option is removed to reduce confusing.
---

Remove marker options from blob, container, and share list commands

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_managed_disk.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

To get consistent with `vm create`, `vm disk attach` commands; otherwise the `image create` might not work when import a VM's data disks
So far, there are no asks to expose the `lun`, so I just fix the consistency issue.

vm: ensure image's data disk's lun start with 0

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

Nic creation in Azure Stack failed because network api supported by stack doesn't recognize `'enable_accelerated_networking' `argument for nic creation. This fix adds a check for supported api version.
Closes  #4007 
---

Fix Nic creation issue in stack

---

src/azure-cli-core/azure/cli/core/commands/__init__.py

This PR is going to add 'container' command module to azure cli to support container instance commands.
---

Remove 'container' from blacklisted mods

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_custom_vm_commands.py

Fix #3995 Fix #3936 
I couldn't reproduce this even I de-allocated the VM, but the 2 issues had stack traces both pointing out the `type` could be unavailable, so I am still fixing it

vm: handle the case when an extension's type could be None

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py

output sdk auth info for service principals with certificates

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py

To help out #2866, while appservice team has no immediate plans to add strong typed commands. The old
example creates an app service plan which is less meaningful since we have strong typed commands for that already.
- [na] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

doc: update 'resource create' command's example to create an api app

---

scripts/automation/tests/verify_dependencies.py

Now we check just MAJOY and MINOR version

Fix dep. check after azure-common release

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py

---
Profile 2017-03-09-profile doesn't support `vm availability-set convert `cmd. So this should be hidden from help content.
Closes #4079 

Add api-version condition to vm availability-set convert

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/command_modules/azure-cli-profile/HISTORY.rst
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_params.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py

account list: add '--refresh' to sycn up the latest subscriptions from server

---

scripts/automation/tests/run.py

Previously only work on Linux.  With this change, it will also work on Windows.
---

[Test] Make `run_tests --test` parameter work cross platform

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_msi_no_scope.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_actions.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

Per feedback, user might add identities to a AAD group and create one single role assignment using that group as rbac does support group expansion. Hence CLI should support to assign identity w/o creating the assignments

vm/vmss: support to assign identity w/o creating role assignments

---

src/azure-cli-core/azure/cli/core/_profile.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_docker_utils.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/custom.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/repository.py

- Fallback to authenticate with access token if refresh token is not available (such as in cloud console).
- Always fallback to admin user authentication if all preceding operations failed.
---

[ACR] Fix an issue with authentication when refresh token is not available

---

src/command_modules/azure-cli-container/HISTORY.rst
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_params.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/tests/test_container_commands.py

Fixes #4142.
---
- [ x ] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).
- [ x ] Each command and parameter has a meaningful description.
- [ x ] Each new command has a test.

Allow equals sign in an environment variable value

---

azure-cli.pyproj
src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/commands/parameters.py
src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_util.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/latest/test_network_ag_address_pool.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/latest/test_network_ag_frontend_ip_private.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/latest/test_network_ag_frontend_ip_public.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/latest/test_network_ag_frontend_port.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/latest/test_network_ag_http_listener.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/latest/test_network_ag_http_settings.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/latest/test_network_ag_probe.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/latest/test_network_ag_rule.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py

Partially addresses #3941.
Fixes issues where `--no-wait` was not honored for subresource deletes.
Fixes issues with three_state_flag when using custom labels.
Fixes issue where connection draining could not be disabled with `http-settings update`.
---

[Network] Add AppGateway subresource tests

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

spelling mistake kilobyes updated to kilobytes 
causing the following error when users runs -- az network vpn-connection ipsec-policy add 
__init__() got an unexpected keyword argument 'sa_data_size_kilobyes'
File "/usr/local/lib/python3.5/dist-packages/azure/cli/main.py", line 36, in main
cmd_result = APPLICATION.execute(args)
File "/usr/local/lib/python3.5/dist-packages/azure/cli/core/application.py", line 211, in execute
result = expanded_arg.func(params)
File "/usr/local/lib/python3.5/dist-packages/azure/cli/core/commands/__init__.py", line 351, in __call__
return self.handler(*args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/azure/cli/core/commands/__init__.py", line 550, in _execute_command
reraise(*sys.exc_info())
File …

[Network] Fix error - unexpected keyword argument 'sa_data_size_kilobyes'

---

scripts/automation/tests/verify_default_modules.py
scripts/build.sh

This is useful when new modules are added as sometimes, people forget to update https://github.com/Azure/azure-cli/blob/master/src/azure-cli/setup.py.
Now, CI will fail if it's missing from the file above unless you explicitly say you want it to be excluded in the script.

[CI] A simple script to verify the default module list

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py

az vmss list-instance-public-ips should be made available to 2017-03-09-profile
and az vmss reimage command should be available only to latest
It closes #4239 
---

az vmss list-instance-public-ips should be made available to 2017-03-09-profile

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/test_custom.py

[ACS] format default dns_name_prefix

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_auto_delete_plan.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_retain_plan.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_webapp_e2e.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py

The change is pretty straightforward, so i am combining a few 
1. Fix inconsistencies in the output of "az webapp config appsettings delete/set/list". Though it is only about output, but still a minor break as fields are changed to show whether the setting is slot specific or not. Fix #4071 
2. Per feedback from appservice team, add a new alias of '-i' for "az webapp config container set --docker-custom-image-name". This is to be consistent with a similar argument in `az webapp create`
3. Expose 'az webapp log show'. Fix #4149 
4. Expose new arguments from 'az webapp delete' to retain app service plan, metrics or dns registration. 
Fix #3958 
5. Detect a slot setting correctly 

webapp: bug fixes on output, logging, etc

---

packaged_releases/debian/debian_build.sh

Addresses https://github.com/Azure/azure-cli/issues/4154.
Once merged, this change will come into affect for the next CLI release.

Debian package: Pin cryptography version to 2.0 to fix WSL

---

scripts/releaser/HISTORY.rst
scripts/releaser/release.py

We now clone the repo again after pushing tags so we can use the new tags.
Before, the script would always fail at the very last step, 'Create Packaged Release archive', and I would wonder why.
It was because in order to create the packaged release (.tar.gz), we need the git tags so we need to clone the repo again **after** the github releases have been created.
I have already published 0.1.3 of the releaser Docker image so merging this code in is more of a formality.

[Release automation] Fix 'packaged release archive' creation step

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_actions.py

vm/vmss create: don't throw when failed to retrieve the image to extract out the plan information

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/custom.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage_validators.py

* Enable service encryption by customer managed key
* Breaking change: rename --encryption option to --encryption-services for az storage account create and az storage account update command.
* Fix #4220: az storage account update encryption - syntax mismatch
/cc @sptramer for the breaking change.
---

Enable customer managed key service encryption

---

src/command_modules/azure-cli-interactive/azclishell/app.py

Fixes: https://github.com/Azure/azure-cli/issues/4252
---
1) using --version/-v should now work in interactive
2) input in interactive mode should now account for trailing spaces
- [na ] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

fixed --version/-v in interactive plus some failure to parse spaces

---

doc/configuring_your_machine.md

When trying to run `az` unit tests locally, I found the commands in "Setting up your development environment" didn't work, so this is my attempt at fixing that to match current reality.

[Docs] update developer commands for running linters and tests

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_actions.py

Fix #4257. 
Compute RP is starting to deploy the fix this week, so starting this week, David and John should be able to create vm/vmss w/o problems.

vm/vmss create: remove human names from the admin name blacklist

---

src/command_modules/azure-cli-sf/HISTORY.rst
src/command_modules/azure-cli-sf/azure/cli/command_modules/sf/custom.py
src/command_modules/azure-cli-sf/setup.py

* Simplified registry user/pass rules for command.
* Fixed password prompt for user even after passing in the
param.
* Supports None registry_cred.
---

[SF] Refactored 'az sf compose create' params to be automation friendly.

---

src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py

//cc: @jluk @yangl900 
- [na ] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

block login flows when inside the cloud console

---

src/azure-cli-core/azure/cli/core/application.py
src/command_modules/azure-cli-interactive/azclishell/__main__.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/custom.py

Fixes https://github.com/Azure/azure-cli/issues/4287
---
Prevents new shell from being run in interactive mode.
If `interactive` is input in interactive mode, a message will inform user that he/she is already in the shell.
- [na ] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

prevent further interactive shells in interactive mode

---

src/command_modules/azure-cli-iot/HISTORY.rst
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/custom.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/tests/recordings/latest/test_iot_hub.yaml
src/command_modules/azure-cli-iot/setup.py

Iot hub policy delete was still deleting all policies rather
than the specified policy.
Observing the policies once seems to release the resources,
setting the desired policy list to empty [].
The fix was to pass a deepcopy of the original policy list into
_is_policy_existed to not prematurely observe the original policies.
---

[IOT] Fix for iot hub policy delete, deleting all policies.

---

.vscode/launch.json

I was trying to debug some `az` changes in VSCode, but hitting [F5] gave me this:
Indeed, this agrees with [current VSCode docs](https://code.visualstudio.com/docs/editor/debugging#_variable-substitution) on how to reference the `config`.
I can't tell when this syntax changed, but swapping the `.` for `:` in two places in launch.json allows debugging to proceed with VSCode 1.15.1.

Fix pythonPath reference in .vscode/launch.json

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_command_type.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_format.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/custom.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/util.py
src/command_modules/azure-cli-storage/setup.py
src/command_modules/azure-cli-vm/setup.py

```
10:24 $ az storage blob set-tier -h
Command
az storage blob set-tier: Sets the block or page blob tiers on the blob.
For block blob this command only supports block blob on standard storage accounts. For page
blob, this command only supports for page blobs on premium accounts.
Arguments
--container-name -c [Required]: The container name.
--name -n           [Required]: The blob name.
--tier              [Required]: The tier value to set the blob to.
--timeout                     : The timeout parameter is expressed in seconds. This method may
make multiple calls to the Azure service and the timeout will
apply to each call individually.
--type -t                     : The blob's type.  Allowed values: block, page.  Default: block.
Storage Account Arguments
--account-key …
```

Enable set blob tier

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/command_modules/azure-cli-profile/HISTORY.rst
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_help.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_params.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py

Support simpler login experience using VM's identity: `az login --msi`.  The `--msi-port` argument can be used if a different port was configured (very rare though).
(Mark it as `Do Not Merge` as server side change is not yet deployed, and also, the publisher of the MSI extension need to change to the official name once deployed.)

msi: simplify the login experience

---

src/command_modules/azure-cli-interactive/azclishell/az_completer.py

---
reenabled `interactive` completion in interactive mode as it is in help and is technically a valid command now.
- [na ] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

reenable interactive completer

---

src/azure-cli-core/azure/cli/core/extensions/transform.py
src/azure-cli-core/azure/cli/core/tests/test_add_resourcegroup_transform.py

[Extensions] _parse_id need to be case insensitive matching

---

.travis.yml
requirements.txt
scripts/automation/tests/verify_packages.py
scripts/build.sh

Closes https://github.com/Azure/azure-cli/issues/4224
This change also speeds up our CI jobs as it executes the two main tasks in parallel.
---

Run --help on all commands in CI task

---

src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_params.py

//CC: @derekbekoe, @tjprescott  @mayurid 
This is the PR to disable the msi login in case the service deployment can't go through by next Wednesday
- [na] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

MSI: disable msi login

---

src/command_modules/azure-cli-interactive/azclishell/app.py
src/command_modules/azure-cli-interactive/azclishell/configuration.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/tests/test_query_injection.py

---
1) symbol for querying using last command is now `??`
2) symbol can be used in two ways: 
a) at start of command to print out jmespath query result from the last command/s output. 
For example: 
`??` will print out the result from the last command
`??name` will print the 'name' attribute from a json object returned from last command and 
`??[].name` will print out the 'name' attributes of every json object from a json array returned from the last command
b) in the middle of your command to execute with arguments from the last command.
For example: 
`group show -n ??name` will execute `group show -n [name attribute of last json object]`
3) any objects returned from jmespath query will have its corresponding json string injected into your command. ***
4) changed tests to account for new …

cleaned and fixed some issues with jmespath querying from last command

---

src/azure-cli/az.bat

endlocal is implicit at the end of a batch file, cf. https://technet.microsoft.com/en-us/library/bb490898.aspx.
Right now, it masks the exit code of the python process; the batch file always returns exit code 0.
---

az.bat: fix exit code

---

scripts/automation/tests/verify_packages.py

- Reduce pool size to help concurrency issue.
- Show percentage for each individual percentage to reduce the log output. (Doing every 10% was too infrequent and would case the build to error out)

Improve CI script that runs --help on all commands

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/telemetry.py

Fix https://github.com/Azure/azure-cli/issues/4363
To register a correlation ID, call method `azure.cli.core.telemetry.set_module_correlation_data` in custom data or invoke it in a common path which all intended commands will go through (example: https://gist.github.com/troydai/cd2511d16ec242d7180bdc3d38169cd4)
---

Enable module to register its own correlation ID

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vm_msi.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vmss_msi.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

1. This change is according to a recent discussion with Portal folks so to have consistency between CLI and Portal
2. MSI is not a public feature yet, so removing the `subscription` from the output is not deemed as a breaking change. For context, `subscription` was added for users to login through `az login -u <subscription>@50342`; however, such usages have been simplified as `az login --msi`

MSI: use the same extension naming as portal does

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/adal_authentication.py
src/azure-cli-core/azure/cli/core/util.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py

Per discussion, output this field for cross checking kusto system so to nail down the root cause. Also I remove mentionings of `az login` when in a cloud shell

cloud shell: output hostname when runs into credential issues

---

src/azure-cli-testsdk/azure/cli/testsdk/base.py
src/command_modules/azure-cli-keyvault/HISTORY.rst
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_params.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_validators.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/recordings/latest/test_keyvault_certificate.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/recordings/latest/test_keyvault_key.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/recordings/latest/test_keyvault_mgmt.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/recordings/latest/test_keyvault_secret.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/recordings/latest/test_keyvault_softdelete.yaml
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/test_keyvault_commands.py
src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vmss_with_ilb.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

Fixes #4384. Intended to fix #4379.
1. Uses enum_choice_list to ensure that KeyVault permissions are case insensitive and simplify manually checking for membership in the valid set.
2. Ensures that the `--secret` parameter of `vm format-secret` works with the TSV output from a `secret list-versions` command.
---

[KeyVault] Fix permission case sensitivity and VM format-secret command

---

tools/automation/tests/verify_packages.py

Solving the timeout issue in the integration test. @yugangw-msft 
---

Print message during -h verification

---

src/command_modules/azure-cli-resource/HISTORY.rst
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/latest/test_show_built_in_policy.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_resource.py

It is a work around for #692. We have waited long enough for the service side fix which still has not happened, but we have to unblock users

policy: support to show built-in policy definition

---

src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/_help.py
src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/_params.py
src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/commands.py
src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/tests/test_backup_commands.py

Changes `backup restore-files ...` to `backup restore files` since "restore-files" sounds like a command.
Changes `backup restore-disks` to `backup restore restore-disks` so the restore-disks commands is in the same subgroup as the restore-files subgroup.
This maintains the CLI's subgroup/command naming consistency.

[Backup] Fix restore group names.

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/custom.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/latest/test_storage_account_service_endpoints.yaml

Due to the breaking change storage introduced in the latest management SDK, these commands now fail. This updates the references to the new field names. 
---

[Storage] Fix `network-rule` commands

---

src/command_modules/azure-cli-extension/azure/cli/command_modules/extension/_homebrew_patch.py
src/command_modules/azure-cli-extension/azure/cli/command_modules/extension/custom.py

Closes https://github.com/Azure/azure-cli/issues/4428
---

Apply Homebrew patch for 'az extension add'

---

src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/custom.py

Restore files mount-rp fails during script download when run on a linux machine with Python 3. Fix is tested on Linux machines with Python 2 and Python 3.
---

Fixing bug: restore files mount-rp command failure

---

src/command_modules/azure-cli-servicefabric/azure/cli/command_modules/servicefabric/custom.py

'pem_output_folder' not defined when -certificate-output-folder not

---

src/command_modules/azure-cli-keyvault/HISTORY.rst
src/command_modules/azure-cli-keyvault/setup.py
src/command_modules/azure-cli-role/setup.py
src/command_modules/azure-cli-vm/setup.py

Updating references to azure-keyvault to 0.3.7 as this has a workaround fix for **Azure Stack: ADFS: Keyvault Secret cmds don't work #4448**
See change: https://github.com/Azure/azure-sdk-for-python/pull/1466  for details
---

[KeyVault] upgrade azure-keyvault to 0.3.7

---

doc/configuring_your_machine.md

Corrects the paths to `check_style` and `run_tests` that broke in 24e3f93.

Fix paths to scripts in developer doc

---

Dockerfile
packaged_releases/docker/Dockerfile
scripts/github_bot/api/Dockerfile
scripts/releaser/Dockerfile

Adds flags to `pip` and `apk` commands in the Dockerfiles to prevent those tools from creating cache data which gets built into the Docker images.
YMMV in terms of space savings, but not caching these items is generally considered a best practice for containers.
```console
$ git checkout master && docker build -t azure-cli:before .
$ git checkout dont-cache-inside-docker-image && docker build -t azure-cli:after .
$ docker images
REPOSITORY         TAG       IMAGE ID            CREATED             SIZE
azure-cli          before    408d8e5affc2        3 days ago          500MB
azure-cli          after     285a1d5f2499        3 days ago          482MB
```

Don't build caches into Docker images

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

[Network] Make `--servers` optional for AppGateway backend address pool create.

---

.dockerignore

Adds a [`.dockerignore`](https://docs.docker.com/engine/reference/builder/#dockerignore-file) file to ensure that extraneous content is not built into `azure-cli` Docker images.
YMMV, but for me when building locally this makes a smaller development image and slightly faster build. 
```console
$ git checkout master && docker build --tag azure-cli:before .
$ git checkout add-dockerfile && docker build --tag azure-cli:after .
$ docker images
REPOSITORY        TAG       IMAGE ID            CREATED             SIZE
azure-cli         before    5a0c7ed1f850        3 days ago          500MB
azure-cli         after     fabdd3da2c7e        3 days ago          362MB
$ docker run --tty azure-cli:before ls -p /azure-cli
CONTRIBUTING.rst       azure-cli.pyproj       nose.cfg
Dockerfile …
```

Include only python sources in Docker images

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_diagnostics_extension_install.yaml

In PR #4579, @lmazuel is testing a change to msrest that rejects the default Python behavior of treating strings as iterables, which causes this test to fail. Instead of sending a string, we send the string wrapped in a list, which is what is intended. This causes no customer-facing changes. 
---
(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring …

[VMSS] Fix subtle issue with `VMSS diagnostics set`

---

src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/data/batchUpdatePool.json

Batch tests uses an incorrect JSON  data for the "PoolUpdatePropertiesParameter", since these three fields are supposed to be an array, not a dict:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-batch/azure/batch/models/pool_update_properties_parameter.py#L64-L66
new version of msrest refuses this, and then the file needs to be fixed.
Discussed with @tjprescott and @annatisch.

Fix Batch tests

---

src/command_modules/azure-cli-resource/HISTORY.rst
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py

Allows the user to specify `--name/-n` or `--resource-group/-g` to specify resource group name for the `az group` commands. Since `-g` is used literally everywhere else in the CLI, this convention is more firmly cemented in users minds than the heuristic we use for names (at least for me).  This non-breaking change simply allows both conventions. 
---

[Resource] Add --resource-group/-g alias to resource group commands

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_docker_utils.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/repository.py

- Avoid making `list-manifests` call when users wish to force delete a manifest either by digest or tag.
- Fix an issue with AAD authentication when logged in using read-access-only role service principal.
---

[ACR] Improve perf and fix permission in repository commands

---

src/command_modules/azure-cli-extension/azure/cli/command_modules/extension/custom.py

The source code of pip is not provided as an API so we should be calling pip through their command line interface instead.
Closes https://github.com/Azure/azure-cli/issues/4571
---
- [n/a] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

Extensions: Call pip as subprocess instead of importing directly

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py

Fix #4213 
//cc @bganapa @viananth 

Azure Stack: handle adfs authority url with a trailing slash

---

requirements.txt
src/azure-cli-core/setup.py
src/command_modules/azure-cli-profile/setup.py

Mainly for dev set up.
1. Older `requests` versions have caused test recordings to fail in my box with errors like 'ConnectionError' , so it is time to refresh.
2. `Adal-0.4.7` contains a fix for the Stack environment. I also updated setup.py to ensure it always gets picked up
Those newer versions have been used in our installers, and tested by customers. The change here is just to get things all sync'd
(see …

dev setup: pin to newer versions of requests and adal

---

src/azure-cli-core/azure/cli/core/commands/arm.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py

Fixes: https://github.com/Azure/azure-cli/issues/4288
-removed some redundant code
-correlation is now taken from the response header instead of from within the response message
---

removed redundant exception handler from commands, correlation id from header

---

src/azure-cli-core/azure/cli/core/util.py

In the old logic, if the first encoding failed, but binary was allowed, then the method would immediately return binary and the other encodings didn't get checked. Now it will cycle through all encodings and then, if binary is allowed, return the binary. 
--- …

Fix bug with read_file_content.

---

src/command_modules/azure-cli-sql/HISTORY.rst
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_util.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/params.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/recordings/latest/test_sql_db_operation_mgmt.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/test_sql_commands.py
src/command_modules/azure-cli-sql/setup.py

---
```
(env) C:\git\azure-cli [cancelop ≡]> az sql db op -h
Group
az sql db op: Manage operations on a database.
Commands:
cancel: Cancels the asynchronous operation on the database.
list  : Gets a list of operations performed on the database.
(env) C:\git\azure-cli [cancelop ≡]> az sql db op cancel -h
Command
az sql db op cancel: Cancels the asynchronous operation on the database.
Arguments
--database -d       [Required]: Name of the database.
--name -n           [Required]: The operation id.
--resource-group -g [Required]: Name of resource group. You can configure the default group …
```

Added sql db op list/cancel

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage_batch_operations.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage_blob_copy_scenarios.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage_blob_live_scenarios.py

---
backslashes in directory and file paths were seen as escapes

Fix storage tests on windows

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py

2 changes to get token expiration time a bit accurate inside the cloud shell so we have a better chance to capture #4333
1. Be consistent with ADAL, use local time
2. Set expiration time be 2700 seconds

cloud console: make sure the expiration time is 45 minutes away from local time

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/util.py

---
`FilePermissions` spelled wrong
was causing "StorageBatchOperationScenarios.test_storage_file_batch_copy" test to fail

fixed create_short_lived_share_sas() method that caused storage_batch_copy test to fail

---

src/azure-cli-core/azure/cli/core/tests/test_profile.py

2 things:
a. Fix a timing issues. The `test_connection_verify.py` changes the environment variable of `AZURE_CLI_DISABLE_CONNECTION_VERIFICATION` on the fly which could cause randomness on other tests running at the same time
b. More specific exception type check which I missed in #4647 

test: robustness fixes in azure-cli-core

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_win_webapp_quick_create_cd.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py

1. Fix #3598. 
2. Fix a recent regression that creating node js web would fail for redundant app-setting `WEBSITE_NODE_DEFAULT_VERSION`
3. code clean ups

webapp: misc bug fixes(create command, log download)

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py

Before the output is not useful as the state is missing
```
Name                      
------------------------ 
Microsoft.AAD/betaAccess
```
Now, we display it
```
Name                      RegistrationState
------------------------  -------------------
Microsoft.AAD/betaAccess  NotRegistered
```
//cc: @christiankuhtz 
(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_comma …

feature: fix table output of show & list command to show "state"

---

src/azure-cli-core/azure/cli/core/sdk/util.py
src/command_modules/azure-cli-monitor/HISTORY.rst
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_client_factory.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/action_groups.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/actions.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/commands.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/params.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/recordings/latest/test_monitor_action_group_basic_scenario.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/recordings/latest/test_monitor_create_empty_action_group.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/test_monitor_action_groups.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/transformers.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/util.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/validators.py
src/command_modules/azure-cli-monitor/setup.py

```
Group
az monitor action-group: Manage action groups.
Commands:
create: Create a new action group.
delete: Delete an action group.
list  : List action groups under a resource group or the current subscription.
show  : Show the details of an action group.
update: Update an action group.
```
```
Command
az monitor action-group list: List action groups under a resource group or the current
subscription.
Arguments
--resource-group -g: Name of the resource ground under which the action groups are being listed.
If it is omitted, all the action groups under the current subscription are
listed.
--debug            : Increase logging verbosity to show all debug logs.
--help -h          : Show this help message and exit.
--output -o        : Output format.  Allowed values: json, …
```

Add monitor action-group commands

---

build_scripts/debian/build.sh
build_scripts/docker/README.md
build_scripts/rpm/README.md
build_scripts/rpm/azure-cli.spec
build_scripts/windows/scripts/build.cmd

Addresses some of the points brought up in https://github.com/Azure/azure-cli/pull/4696

Address feedback from 'Support local builds for all installers' PR

---

.flake8
tools/setup.py

This is temporary. We must upgrade to 3.5 and newly introduced fix style issues in near future.

Skip two types of style errors in flake8.

---

src/command_modules/azure-cli-resource/HISTORY.rst
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_validators.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/latest/test_lock_with_resource_id.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_locks.py
src/command_modules/azure-cli-resource/setup.py

---
`--resource` argument
old `--resource-name` arg still allowed
`az resource lock delete -n lockName --resource /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyResourceGroup/providers/Microsoft.Network/virtualNetworks/myvnet` …

resource-level locks support using the id of the resource to be locked

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Tested interactively as well to verify we actually get Standard_D1_v2 VMs by default.
---

Change default VM for AKS to D1_v2.

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

`NamedTemporaryFile` has limitations on Windows, so this uses [`mkstemp`](https://docs.python.org/3/library/tempfile.html). Tested interactively on Windows 10, macOS, and Ubuntu Linux.

Fix `az aks browse` on Windows

---

Dockerfile

This PR updates the container image metadata to include the **version** value in the `org.label-schema.docker.cmd` label and also correctly render the `${HOME}` variable in that label.
**Existing:**
```powershell
PS> docker image inspect azuresdk/azure-cli-python:2.0.20 --format "{{json .Config.Labels}}" | ConvertFrom-Json | ConvertTo-Json
{
"org.label-schema.build-date":  "2017-10-19T18:26:52Z",
"org.label-schema.description":  "The Azure CLI 2.0 is the new Azure CLI and is applicable when you use the Resource Manager deployment model.",
"org.label-schema.docker.cmd":  "docker run -v :/root -it azuresdk/azure-cli-python:\u003cversion\u003e",
"org.label-schema.license":  "MIT",
"org.label-schema.name":  "Azure CLI 2.0",
"org.label-schema.schema-version":  "1.0",
"org.label-schema.url": …
```

Fix metadata, update base image version.

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/blob.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/file.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage_batch_operations.py

---
Closes: https://github.com/Azure/azure-cli/issues/3757
delete-batch commands will delete multiple files/blobs using a pattern to glob
deletes will use the same connection and hence be faster then running a delete command for each file/blob. …

`storage blob/file delete-batch` commands

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/test_custom.py

To make ACS more robust to msrest changes
See too: https://github.com/Azure/azure-cli/pull/4787

Remove some mock in ACS tests

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/latest/test_metrics_operations.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage_account_scenarios.py

---
Fixed: https://github.com/Azure/azure-cli/issues/4203
-Enabling storage metrics would disable them instead.
-Added a test for enabling said metrics.
- [ y] Each new command has a test.

Fixed storage metrics update bug

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_custom_image_with_plan.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_actions.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

Applicable on images with billing information. Fix #4233 
Note, CLI has existing logic to retrieve such information if available in the image, so essentially these new arguments will only be useful to create a vm/vmss from custom images captured by users themselves. 
```
Marketplace Image Plan Arguments
--plan-name                        : Plan name.
--plan-product                     : Plan product.
--plan-promotion-code              : Plan promotion code.
--plan-publisher                   : Plan publisher.
```

vm/vmss: expose image plan related arguments

---

src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/custom.py
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/tests/test_batchai_custom.py

Make --storage-account-name and --storage-account-key work for Azure File share and Azure Storage container specified on command line.
---

BatchAI. Storage account key and name options

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vmss_create_none_options.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

Cross checked different api-versions and confirmed service can figure out the tier from the sku, hence setting the `tier` in the template is unnecessary
Fix #4801. 
I will hold on tweaking the balancer default which is already complex; also, the service rejects pretty quick, so i suggest we live with it till we have more user voices

vmss: support basic tier of vms

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

`NamedTemporaryFile` can't be opened more than once on Windows, so this uses [`mkstemp`](https://docs.python.org/3/library/tempfile.html). Tested interactively on Windows 10, macOS, and Ubuntu Linux.

Fix `az aks get-credentials` on Windows

---

src/azure-cli-core/azure/cli/core/commands/arm.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_assign_identity.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

For less code redundancy, I extracted some common role assignments logic and moved to azure-cli-core.

appservice: support assign managed service identity to webapp/functionapp

---

src/command_modules/azure-cli-extension/azure/cli/command_modules/extension/_help.py

Since extension names won't have underscore, the examples probably shouldn't have underscore either.

Extension examples small improvement

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py

In a recent SDK update there was a regression with getting locations for PremiumV2. 
This will fix that.
---

Fixing appservice list-locations

---

src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/test_role_commands_thru_mock.py
src/command_modules/azure-cli-role/setup.py

ad sp reset-credentials: support to add credentials instead of overwriting 

---

src/command_modules/azure-cli-sql/HISTORY.rst
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_util.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/params.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/recordings/latest/test_sql_subscription_usages.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/test_sql_commands.py
src/command_modules/azure-cli-sql/setup.py

```
(env) D:\git\azure-cli [subscriptionUsages ≡]> az sql show-usage -h
Command
az sql show-usage: Gets a subscription usage metric.
Arguments
--location -l [Required]: Location. You can configure the default location using `az configure
--defaults location=<location>`.
--usage -u    [Required]: Name of usage metric to return.
--debug                 : Increase logging verbosity to show all debug logs.
--help -h               : Show this help message and exit.
--output -o             : Output format.  Allowed values: json, jsonc, table, tsv.  Default:
json.
--query                 : JMESPath query string. See http://jmespath.org/ for more information
and examples.
--verbose               : Increase logging verbosity. Use --debug for full debug logs.
(env) D:\git\azure-cli …
```

Add az sql show-usage/list-usages

---

build_scripts/debian/build.sh

Remove the cryptography workaround as it works in WSL now and we had to update cryptography

Debian Build: Remove the cryptography workaround

---

src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/azure/cli/core/_help.py
src/azure-cli-core/azure/cli/core/commands/parameters.py

- Fixes #4993. Cloud Errors should no longer produce a stack trace.
- Fixes #4943. ASCII art no longer looks wonky.
- Fixes #5001. Uses the `ensure_dirs` stuff from the latest Knack.
- Fixes #4999. Resource group and location completers now work. Also updated generic_completer even though nothing uses it today.

Knack bug fixes

---

src/azure-cli-core/azure/cli/core/commands/__init__.py

Example:
```
command authoring error: extra argument 'noodle' cannot be registered to a group-level scope 'resource'. It must be registered to a specific command.
File "C:\Users\trpresco\Documents\github\azure-cli\env\lib\site-packages\knack\cli.py", line 193, in invoke
File "c:\users\trpresco\documents\github\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 241, in execute
self.commands_loader.load_arguments(command)
File "c:\users\trpresco\documents\github\azure-cli\src\azure-cli-core\azure\cli\core\__init__.py", line 204, in load_arguments
loader.load_arguments(command)  # this adds entries to the argument registries
File "c:\users\trpresco\documents\github\azure-cli\src\command_modules\ …
```

Prevent using "extra" on a non-command argument context.

---

scripts/ci/build.sh
scripts/ci/test_static.sh
src/command_modules/azure-cli-consumption/azure/cli/command_modules/consumption/__init__.py
src/command_modules/azure-cli-consumption/azure/cli/command_modules/consumption/_client_factory.py
src/command_modules/azure-cli-consumption/azure/cli/command_modules/consumption/_params.py
src/command_modules/azure-cli-consumption/azure/cli/command_modules/consumption/commands.py
src/command_modules/azure-cli-consumption/azure/cli/command_modules/consumption/custom.py
src/command_modules/azure-cli-consumption/azure/cli/command_modules/consumption/tests/test_consumption_commands.py

Closes https://github.com/Azure/azure-cli/issues/4928
-changed tests to record-only

Knack Conversion for consumption module

---

src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/azure/cli/core/commands/arm.py
src/azure-cli-core/azure/cli/core/commands/parameters.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/batch_preparers.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/recordings/batch_help_full.txt
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/commands.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-servicefabric/azure/cli/command_modules/servicefabric/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py

Replaces "till" with "until" and inserts the required hyphen into the phrase "long-running."

Fix some grammar issues

---

.flake8
scripts/ci/build.sh
scripts/ci/test_static.sh
src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/_params.py
src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/custom.py
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/__init__.py
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/_client_factory.py
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/_params.py
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/commands.py
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/custom.py
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/tests/test_batchai_custom.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/tests/recordings/latest/test_mysql_proxy_resources_mgmt.yaml
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/tests/recordings/latest/test_postgres_proxy_resources_mgmt.yaml

Implements #4925. Tests to be re-enabled in future PR.

[BatchAI] BatchAI module Knack conversion

---

src/azure-cli-core/azure/cli/core/__init__.py

fixes knack regression
Fixes the following:
Actual:
```
$ az image copy -h
This command is from the following extension: azext_imagecopy
```
Expected:
```
$ az image copy -h
This command is from the following extension: azure-cli-image-copy-extension
```

Use the actual extension name rather than the module name

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vmss_create_default_app_gateway.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py
src/command_modules/azure-cli-vm/setup.py

Same with #5137, but target to the `KnackConversion` branch.
As long as this PR can catch up with the Jan 17 release, I am fine with any branch to target. Looks like KnackConversion is lagging behind, so the CI failure at this moment is not caused by this PR  

vmss: ensure app-gateway has a name when defaults to it for large scalesets

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Improves built-in help messages for `az aks` and some `az acs` commands. Moves many of them out of code into `_help.py` as recommended.

[AKS] Knack - improve help messages

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/setup.py

For vendored SDKs, the dynamic smartness of `client_arg_name = 'client' if operation.startswith(('azure.cli', 'azext')) else 'self'` is not reliable.
This PR allows the user to override this.

Allow user to specify custom client_arg_name

---

src/azure-cli-core/azure/cli/core/profiles/_shared.py

This is an alternative and conservative solution to PR #5167. The change is limited to "replacing" `namedtuple` with a more performant data structure. The PR doesn't fix the issue where operation_group is not considered during command registration.
If we decide that #5167 is too risky this is a safer fallback.

Replace namedtuple with ApiVersions class

---

src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/cloud.py
src/azure-cli-core/azure/cli/core/commands/client_factory.py
src/azure-cli-core/azure/cli/core/telemetry.py
src/azure-cli-core/azure/cli/core/tests/test_cloud.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/azure-cli/azure/cli/__main__.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_docker_utils.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_client_factory.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/vsts_cd_provider.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_client_factory.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/custom.py
src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/custom.py
src/command_modules/azure-cli-dls/azure/cli/command_modules/dls/_client_factory.py
src/command_modules/azure-cli-interactive/azclishell/app.py
src/command_modules/azure-cli-interactive/azclishell/telemetry.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_client_factory.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_completers.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/custom.py
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/validators.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_client_factory.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_validators.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-servicefabric/azure/cli/command_modules/servicefabric/custom.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_vm_utils.py

Fixes #5199. Allows creation of a default CLI instance if one is not supplied when creating a Profile object or calling `get_active_cloud`.

Updates to avoid breaking azure.common dependencies.

---

src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-testsdk/azure/cli/testsdk/utilities.py

This should get `test_vm_create_progress` pass

core: bring progress info back

---

src/azure-cli-core/azure/cli/core/_profile.py

@tjprescott, @lmazuel 
Currently the profile still tries to use the cli_ctx that was passed as a parameter even though it might be None.

Fixed cli_ctx in Profile

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_client_factory.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_defaults.py
src/command_modules/azure-cli-vm/setup.py

Fix #5135
No command signature change. CLI just starts to respect every piece of information in the resource id, including the subscription id.

 vm: support image sharing across subscriptions

---

azure-cli2017.pyproj
src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/setup.py

Fixes#4988:Certificates uploaded through CLI is not useable to bind to an app

---

src/azure-cli-core/azure/cli/core/util.py
src/command_modules/azure-cli-feedback/HISTORY.rst
src/command_modules/azure-cli-feedback/azure/cli/command_modules/feedback/custom.py
src/command_modules/azure-cli-feedback/setup.py
tools/automation/verify/verify_packages.py

`pip` is moving it's internal methods to be private in the future so we should no longer rely on them.
https://pip.pypa.io/en/latest/user_guide/#using-pip-from-your-program
---

Use pkg_resources instead of pip internal methods

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py

for a slot the publishing credentials is obtained using the list_publishing_credentials_slot, however the 
_get_site_credential was not supporting this logic updated this to obtain the right credentials & updated get _streaming_log & enable_zip_deploy to get the right credentials (NOTE: this however needs to be done to all places the _get_site_credentials is called
---

Fixes #4953: Updating getSiteCredentials to get the correct credentials

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/recordings/latest/test_acs_create_kubernetes.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/test_acs_commands.py

The issue was a missing `cli_ctx` parameter when creating the SP role assignment. This is a regression that breaks `az acs create --orchestrator-type Kubernetes`, so I hope this can be merged today.
Closes #5141.

[AKS] fix SP role assignment and reenable last scenario test

---

src/command_modules/azure-cli-servicefabric/HISTORY.rst
src/command_modules/azure-cli-servicefabric/azure/cli/command_modules/servicefabric/custom.py
src/command_modules/azure-cli-servicefabric/setup.py

This provides a fix for #4790 which is a frustration when deploying Service Fabric clusters. It's not easy to find out what caused a validation error as detailed error messages aren't emitted. The PR adds these messages into the output to assist users. 
I'm unsure if this change warrants an entry, what do you think?
I haven't modified any commands. 

Added detailed error to 'az sf cluster create' when template validiation fails

---

src/command_modules/azure-cli-rdbms/HISTORY.rst
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/_help.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/commands.py
src/command_modules/azure-cli-rdbms/setup.py

In 2.0.23, the command was commented out.
Post-knack change, it was re-added but it should still be commented out.
https://github.com/Azure/azure-cli/blob/azure-cli-2.0.23/src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/commands.py#L95

Hide mysql/postgres db create/delete/show

---

src/command_modules/azure-cli-acs/setup.py
src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vmss_create_with_low_priority.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py
src/command_modules/azure-cli-vm/setup.py

Counterpart of `spot instances` from EC2
```bash
--priority                         : (PREVIEW)Priority. Use 'Low' to run short-lived workloads
in a cost-effective way.  Allowed values: Low, Regular.
Default: Regular.
```

vmss:(PREVIEW) support low priority

---

doc/authoring_command_modules/README.md

Original links pointed to master, which is not up-to-date. Since these documents are for developers anyways, pointing to dev is probably the right answer anyways.

Update links in README.md to point to dev branch

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/custom.py

Fixes https://github.com/Azure/azure-cli/issues/5341
---

[ACR] Improve error message in running acr login in cloud shell

---

tools/automation/tests/__init__.py

Fixes #5366.  Tested on Win10 CMD.exe, OSX bash. cc/ @mboersma 
Note: This fix does *not* work on bash on Windows.  While it will avoid the error (it is seen as sys.platform = linux2), it will "successfully" run 0 tests in 0.000 sec.  Since there isn't a lot of demand to run tests on bash on Windows, I suggest merging this fix.
---
- [N/A] Each new command has …

Ensure run_tests works on bash/Windows

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_actions.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_with_market_place_image.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
src/command_modules/azure-cli-vm/setup.py

2 things:
1. Through the new command of `az vm image accept-term`, users can accept the term to use some market-place images with its own billing. Before, they have to do it through portal. This fixes #3411.
2. Update `az vm image show` to support `--urn`, so users can supply the urn returned from `az vm image list` and get the billing plan information easily
The flow looks like
```
urn = $(az vm image list --all --publisher kemptech --offer vlm-azure --sku basic-byol --query '[0].urn')
az vm image accept-term --urn $urn
az vm create -g rg -n vm1 --image $urn
```

VM: improve supports for using marketplace images

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_completers.py

Currently, hitting [TAB] for a `--vm-size`-type argument returns all VM sizes available for a location, as returned by the Compute Service. But AKS only supports [a subset](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-containerservice/azure/mgmt/containerservice/models/container_service_client_enums.py#L21) of those sizes, so the list can be misleading.
This changes the `get_vm_size_completion_list` completer function to return the intersection of the VM sizes allowed by the ACS SDK with those returned by the Compute Service.
```shell
$ az aks create --location eastus -s # [TAB]
$ az aks create --location eastus -s Standard_ # [TAB]
Display all 114 possibilities? (y or n)
Standard_A0             Standard_D12            Standard_D4_v2_Promo    Standard_DS2_v2 …
```

[AKS] improve tab completion for VM sizes

---

src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/azure/cli/core/commands/__init__.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-interactive/HISTORY.rst
src/command_modules/azure-cli-interactive/azclishell/_dump_commands.py
src/command_modules/azure-cli-interactive/azclishell/app.py
src/command_modules/azure-cli-interactive/azclishell/configuration.py
src/command_modules/azure-cli-interactive/azclishell/gather_commands.py
src/command_modules/azure-cli-interactive/setup.py
src/command_modules/azure-cli-keyvault/HISTORY.rst
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py
src/command_modules/azure-cli-monitor/HISTORY.rst
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_params.py
src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_params.py

Fix #5284.  Fixes the logic to build the command table and merge it with the help files.  Please verify using the PR sample container.
Additionally, over the course of fixing this issue, I discovered numerous other problems with help files that had not been updated and in the case of `vnet-gateway root-cert/revoked-cert` commands that had been lost during the knack conversion. 
These kinds of checks should be part of PR validation. This is tracked under issue #3188.
---

[Interactive]  Fix `az interactive` broken options

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_default_service.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_service_no_wait.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_with_upgrade.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py

Adds `az aks delete`, `wait`, and `get-versions` as well as some variations to the existing tests.

[AKS] add more commands to scenario tests

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_default_service.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_with_upgrade.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
src/command_modules/azure-cli-acs/setup.py

Changes the default Kubernetes VM node size for `az aks create` to `Standard_DS1_v2`.
cc: @sauryadas @slack 
---

[AKS] change default node size to Standard_DS1_v2

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_custom_vm_commands.py
src/command_modules/azure-cli-vm/setup.py

vm boot-diagnostic: fix the broken get log command

---

src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/test_role_commands_thru_mock.py
src/command_modules/azure-cli-role/setup.py

ad app update: expose '--available-to-other-tenants'

---

.travis.yml
scripts/ci/test_perf.sh
tools/automation/verify/verify_module_load_times.py

Closes #5326. 
This PR runs `azdev verify module-load-perf` on a separate stage to detect and prevent significant performance regressions. 
I will remove the DNM label once I have done the following:

Add module loading performance check to CI

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py

auth: key on both subscription id and name on msi login

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/setup.py

It wasn't possible to specify tags when creating a public IP. The tags
weren't parsed in the command callback resulting in an incorrect
format (array instead of object) and a python error on validation.
The fix is a one-liner adding the missing validate_tags() call.
---

Fix the tags option of the "az network public-ip create" command.

---

src/command_modules/azure-cli-interactive/HISTORY.rst
src/command_modules/azure-cli-interactive/azclishell/app.py
src/command_modules/azure-cli-interactive/setup.py

---
Closes: https://github.com/Azure/azure-cli/issues/5421
- `az login` from the cli caches its subscription and profile inside the ".azure" directory.
- interactive mode would look inside ".azure-shell" and require a separate login from within interactive mode (which is disabled in CloudShell).

Make interaction use azureProfile.json from .azure

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/command_modules/azure-cli-interactive/HISTORY.rst
src/command_modules/azure-cli-profile/HISTORY.rst
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
src/command_modules/azure-cli-profile/setup.py

---
Fixes: https://github.com/Azure/azure-cli/issues/5452
This change flushes the token information into disk without waiting for the command process to end.

Turn async persist off when logging in

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Makes finding the k8s dashboard pod more robust by returning the last string segment following a `/` character, if there is one.
Closes Azure/AKS#159

[AKS] fix `az aks browse` if dashboard isn't prefixed by "pods/"

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_validators.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

This allows the RP to set the default version if the user doesn't supply one explicitly. Currently that's Kubernetes 1.7.9, but should bump up to 1.7.12 soon.
Setting the default on the server lets us to stop updating the CLI just to chase newer versions.
---

[AKS] remove k8s default version from CLI 

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/disk_encryption.py

Fix #5436 
This is a mitigation level of fix, as most likely the service end has a bug. It is a windows VM being encrypted and the encryption setting is supposed to be available immediately. But nonetheless, this PR avoids the unhandled exception. 
I manually tested the change and will add automation once confirmed the glitch is by-design

vm encryption: avoid the crash when vm encryption setting might not be fully initialized

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/azure/cli/core/commands/events.py

Trigger 'CommandInvoker.OnPreTruncateCommandTable' event before truncating the command table

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_format.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_transformers.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/blob.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/directory.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/file.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_list_paging.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_file_list_paging.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_queue_list_paging.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_table_list_paging.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_blob_scenarios.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_file_scenarios.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_queue_scenarios.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_table_scenarios.py

---
Closes: https://github.com/Azure/azure-cli/issues/3745
-"nextMarker" property added to every result of list output
-`list` commands now have `--num-result` and `--marker` as parameters.
-minor fixes, and added tests

Added paging support for storage list commands.

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Rather than dumping a stack trace in this case, emit an error that is useful and actionable by the user. Also creates a `load_kubernetes_configuration` function to avoid code duplication.
Closes Azure/AKS#158
---

[AKS] handle UnicodeDecodeError when loading Kubernetes configuration files

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py

To avoid confusion, the `ad` commands are only for RBAC, so let us make it clear
@derekbekoe, since it is a low-risk help update, can we merge it for current release? 
//CC: @skwan 

ad: update help be more accurate

---

src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-testsdk/azure/cli/testsdk/base.py
src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/tests/latest/test_backup_commands.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/test_monitor_diagnostic_settings.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/latest/test_resource.py

This PR does two things:
1. Fixes #5055. Now, when any of the command authoring commands that accept kwargs are invoked, the supplied kwargs will be validated and any errors will be raised instead of silently ignored.
2. Similiarly, this fixes an issue in the test base when using the `self.kwargs` feature so that kwarg mis-spellings in commands raise an actionable error instead of manifesting in strange, hard-to-diagnose ways.
---
- [N/A] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change- …

Improve core error handling

---

src/command_modules/azure-cli-resource/HISTORY.rst
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-resource/setup.py

Fixes #3889.
The command will now output the template object. If there are failures, it will output a warning about the failures, following by an error message for each failure.  Example:
```
{
<partial ARM template>
}
Export template operation completed with errors. Some resources were not exported. Please see details for more information.
Could not get resources of the type 'Microsoft.Sql/servers/connectionPolicies'. Resources of this type will not be exported.
Could not get resources of the type 'Microsoft.Sql/servers/disasterRecoveryConfiguration'. Resources of this type will not be exported.
Could not get resources of the type 'Microsoft.Sql/servers/databases/advisors'. Resources of this type will not be exported.
Could not get resources of the type …
```

`az group export` fix output on failure

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_list_locations_free_sku.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
src/command_modules/azure-cli-appservice/setup.py

Fixes#5538: list_locations supports 'Free' and 'shared' as valid parameters

---

src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/azure/cli/core/telemetry.py

Update telemetry data format

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/telemetry.py
src/azure-cli-core/azure/cli/core/telemetry_upload.py

Azure CLI extensions can now use `add_extension_event` from `azure.cli.core.telemetry` to add telemetry events to Azure CLI application insight.
In addition, extensions can specify their own application insight instrumentation key when calling `add_extension_event`. If no instrumentation key is specified, the telemetry will be sent to Azure CLI application insight.

Expose Azure CLI core telemetry to extension

---

src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/azure/cli/core/profiles/_shared.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py

Fix #5484.
Previously, if the `resource_type` kwarg was not supplied to `azure.cli.core.profiles._shared.supported_api_version` then it would assume the PROFILE_TYPE. This led to subtle bugs as observed in #5484. Making this required would prevent this subtle bug by forcing commands to specify PROFILE_TYPE for resource type (I don't know of anywhere that actually has to do that).
---
- [N/A] Each command and parameter has a …

Make `resource_type`  a required parameter for `supported_api_version`

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/commands/client_factory.py

This PR is in response to https://github.com/Azure/msrest-for-python/pull/86

Enable HTTP logger after msrest change

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_acr_integration.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp_quick_create.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp_quick_create_cd.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_backup_config.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_backup_restore.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_config.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_e2e.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_git.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_scale.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_slot.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_slot_swap.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_update.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_win_webapp_quick_create.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_win_webapp_quick_create_cd.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_win_webapp_quick_create_runtime.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
src/command_modules/azure-cli-appservice/setup.py

This cli update is being pushed in correlation to the "available stacks api" update in our swagger: [PR #2506](https://github.com/Azure/azure-rest-api-specs/commit/b81f70b01faff8dc54885ffb379cb5181b998b6f). Do not merge until a new sdk is generated.
I have locally generated the new sdk myself and re-tested/re-recorded functionality of our existing commands.
Changes include:
-az webapp list-runtimes --linux calls "get_available_stacks" instead of using a hard-coded list
-fix backup/restore commands
-some changes to tests
---

webapp available stacks update + sdk revamp

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__main__.py

Closes https://github.com/Azure/azure-cli/issues/5184
---

Bug fix for 'ValueError: field 6 out of range (need a 48-bit value)'

---

scripts/dev_setup.py

This will avoid problems where `python` and `pip` on PATH do not map to the version of Python that the script was started with.
I already contributed a similar change to the https://github.com/Azure/azure-sdk-for-python/pull/2062

Makes dev_setup.py script more portable

---

doc/generating_sphinx_docs.md

1.7 was released a few days ago and the script doesn't support that version as some imports were removed.
cc: @georgechenchao though I think in your appveyor scripts you've already pinned to a specific version of sphinx.

Ref doc gen script supports sphinx==1.6.7

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py

The context is the IMDS we need to migrate in March only supports GET, also the cloud shell which will leverage CLI's msi login supports GET as well for token retrieval, so to make the code migration easier, I am just switching to GET so the same flow can be used for both MSI and cloud shell authentications.
This also fix #5465; and also rewires the global creds cache (needed by datalake service for better perf 
for large file transfer) which appeared lost during knack conversion
---
- [na] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change …

login: switch to http GET for msi login and bring back the global cred cache 

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_assign_system_identity.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
src/command_modules/azure-cli-appservice/setup.py
src/command_modules/azure-cli-profile/HISTORY.rst
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/__init__.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_help.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_explicit_msi.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_explicit_msi.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

Main change
1. `az vm/vmss/webapp/functionapp assign-identity/remove-identity` gets moved to under `az vm/vmss/webnapp/functionapp identity assign/remove`
2. author `az vm/vmss/webapp/functionapp identity show`
3. `az login --msi --msi-port 1234` get changed to `az login --identity --identity-port`
4. Old commands/argument still work (for 2 releases). Deprecation information is emitted on old commands
//cc: @skwan, @arluca @mayurid @twitchax 

msi: terminology update to identity

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/blob.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/util.py

---
Closes: https://github.com/Azure/azure-cli/issues/5286
-batch commands should not fail upon preconditions set by user

Batch commands no longer throw error upon precondition failures.

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_ubuntu.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_with_unmanaged_data_disks.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_actions.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_defaults.py

2 things
1. Make it possible to attach to unmanaged disks with specified caching mode. Right now, CLI blocks it
This should Fix #5684 Fix #5579, and related ICM ticket https://icm.ad.msft.net/imp/IncidentDetails.aspx?id=59499672
2. Expand `--data-disk-caching` to support individual disk caching using lun e.g. `0=None 1=ReadOnly`

vm/vmss: improve disk caching support

---

src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/__init__.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/custom.py

Fix for az interactive's display of IoT warning on first run as referenced in issue #5730
Extension warning/notification is implemented via knack event handler instead.
No command behavior changes.
---

Fix for az interactive's display of IoT warning on first run

---

src/azure-cli/az

On at least FreeBSD, bash does not live at `/bin/bash`. This may be the case on some other operating systems as well (likely the other *BSDs). Using `/usr/bin/env bash` solves this since `env` should live at this absolute path on any Unix-like system.
--- …

Allow for unusual location of bash in az script

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/blob.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_append.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_blob_scenarios.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/util.py
src/command_modules/azure-cli-storage/setup.py

---
Fixes: https://github.com/Azure/azure-cli/issues/4049

Fix append blob condition parameters

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_vm_utils.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_defaults.py

Closes #5107.
This change primarily pins the API version used in many VM module network calls to a specific value when using profile "latest" so that network API bumps do not require re-recording.  Many tests still create network resources and thus would need to be re-recorded. To fix that would require quite a bit more work.
This change reduces the impact of a Network API change to re-recording 90 tests, down from 125. 
Best news: it eliminates the need to re-record the incredibly time consuming Backup tests!! 🙌
---
- [N/A] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change …

Reduce test re-recording impact for Network API bumps

---

azure-cli.pyproj
src/command_modules/azure-cli-interactive/HISTORY.rst
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/app.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/az_completer.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/threads.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/tests/latest/test_completion.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/tests/latest/test_feedback.py
src/command_modules/azure-cli-interactive/setup.py

---
-Completers now kick in as soon as the table is loaded, no need to clear the command line and try commands until completions are seen.
-some logic changes
-updated project file to account for https://github.com/Azure/azure-cli/commit/dd75a3c347d10197ba830f80d58cef2703bbf654

Better Completer responsiveness in interactive after command table loaded

---

azure-cli.pyproj
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_basic.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_fixed.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_recurring.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_rules.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/test_monitor_autoscale.py

These were converted to LiveScenarioTests in the Autoscale PR because the CI kept failing on them.
---

[Monitor] Re-enable Autoscale recorded tests

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_customer_managed_key.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_validators.py

Closes: https://github.com/Azure/azure-cli/issues/5820
We overlooked three options in storage account update command during knack conversion. This is the change to bring them back.
```
Command
az storage account update: Update the properties of a storage account.
Arguments
--access-tier           : The access tier used for billing StandardBlob accounts. Cannot be set
for StandardLRS, StandardGRS, StandardRAGRS, or PremiumLRS account
types. It is required for StandardBlob accounts during creation.
Allowed values: Cool, Hot.
--assign-identity       : Generate and assign a new Storage Account Identity for this storage
account for use with key management services like Azure KeyVault.
--custom-domain         : User domain assigned to the storage account. Name is the CNAME source.
Use "" to …
```

Fix regression: Correctly expose the CMK encryption vault properties

---

doc/sphinx/make.bat

Under some circumstances the doc/sphinx/make.bat produces an exit code of 1 despite success (apparently due to arcane .BAT rules about error propagation). While this is fine in the AppVeyor build, it is blocking the migration to a VSTS-based build. (In a VSTS Build Definition, the Task for running .bat files cannot be instructed to ignore the exit code.)
This change explicitly sets the exit code to 0 on success for the cases that need to be run as part of the documentation CI build being ported to VSTS.

Prevent make.bat returning exit code of 1 on success

---

doc/authoring_command_modules/README.md
doc/authoring_tests.md
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/test_monitor_log_profile.py
tools/automation/tests/__init__.py
tools/automation/utilities/path.py

Closes #5554. Closes #5629.
The PR does the following:
- Removes the `--module` parameter from `azdev test` as it is no longer needed and its usage proved confusing.
- Removed the `--test` parameter. This is now positional.
- Running `azdev test` without any positional arguments will no longer run all tests. Instead it will run none.  This also allows you to run `azdev test --discover` to rebuild the index without running anything.
- Allows tests with name collisions to be added to the index. They are resolved using `<mod/ext_name>.<test_name>`. (#5629)
- Allows you to discover and run tests for extensions. The syntax is the same as for a module. (#5554)

[Test] Enhance `azdev test` script

---

src/command_modules/azure-cli-lab/HISTORY.rst
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/validators.py
src/command_modules/azure-cli-lab/setup.py

BUG: formulas with artifacts will fail with an implementation error message of "'ArtifactInstallProperties' object has no attribute 'get'"
If a formula artifact has parameters, output error message that the user need to use the --artifacts parameter
---

DevTestLabs: Require --artifacts param if formula artifacts has parameters

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py

For scaelset with 100+ instances, the default balancer will become SLB, not app-gateway anymore. For the release next week, users will see a warning, then in the next release, I will commit the change.
//CC @gatneil  @christiankuhtz

vmss create: warn on upcoming breaking changes on default balancer type

---

src/azure-cli-core/azure/cli/core/_profile.py
src/command_modules/azure-cli-profile/HISTORY.rst
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
src/command_modules/azure-cli-profile/setup.py
tools/automation/tests/__init__.py

Pretty much revert #5772 which reverted the right behavior as ansible cli was not able to integrate with cloud shell at the same time. Hope this time we can get it in
//CC: @jluk @yangl900

login: bring back the msi model for creds management in the cloud shell

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/blob.py
src/command_modules/azure-cli-storage/setup.py

For the moment we get a error when we try to upload a blob file with size between 195GB and 200GB with CLI.
`The block list may not contain more than 50,000 blocks.`
A fix was apply during https://github.com/Azure/azure-cli/pull/4820 in order to manage file with size up to 200GB. But with block size set to 4MB, the real limit is not 200GB but 195,31GB (50000 * 4 * 1024 * 1024).
So I have updated the calcul to increase the block size to 100MB when the real limit is reached.
---

Fix issue of upload file with size between 195GB and 200GB

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_custom_ip.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

Fixing issues when go over live test failures
//CC @mboersma 

acs create: fix SP creation failures caused by new graph sdk libs

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_dns_commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/zone_files/zone2.txt
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/zone_files/zone7.txt
src/command_modules/azure-cli-network/azure/cli/command_modules/network/zone_file/parse_zone_file.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/zone_file/record_processors.py
src/command_modules/azure-cli-network/setup.py

We now support RFC 1035 DNS TXT record escape sequences in the Azure DNS service in order to support non-printable ASCII characters. The service will take care of all the escape sequences inside of TXT records.
Adding support in the CLI to forward these escape sequences to the Azure DNS service.
---

Support TXT record escape sequences in Azure DNS CLI

---

azure-cli.pyproj
src/azure-cli-core/azure/cli/core/commands/validators.py
src/command_modules/azure-cli-monitor/HISTORY.rst
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/__init__.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_params.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/validators.py
src/command_modules/azure-cli-monitor/setup.py

Fixes #5802.
Also fixes an issue in the `get_default_location_from_resource_group` validator when the resource group isn't found.
---

[Monitor] Fix erroneous usage strings

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/setup.py

I am giving up waiting for that appservice team would ever update the spec so not to treat 400 as a valid return code on GET any more
Fix #5816

webapp/functionapp: capture the error when plan can be None

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-profile/HISTORY.rst
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/__init__.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
src/command_modules/azure-cli-profile/setup.py
src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

remove deprecated identity related commands

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/command_modules/azure-cli-profile/HISTORY.rst
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_format.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py

Those accounts come from CLI 1.0/ASM mode, because they have no "state" inforamtion, that causes CLI to throw unhandled exceptions
Fix #5846 Fix #5911

account: handle RDFE based accounts

---

src/azure-cli-core/setup.py

In #3313 Tabulate was pinned to 0.7.7.  Pinning to this older version creates installation challenges and general irritation for users.
I understand the way the tests are written it is currently helpful to minimize change in this package, but I have verified that `TestCoreCLIOutput` tests work with all versions between `0.7.7` and `0.8.2` (latest) - so we can at least expand dependencies to that range.

Expand Tabulate package versions in core

---

src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py

This is a help content-only change (`_help.py`) that removes the "(PREVIEW)" tag on the [az container command reference](https://docs.microsoft.com/cli/azure/container).
---
Cc: @jluk @yangl900

[ACI] (docs only) remove PREVIEW branding

---

src/command_modules/azure-cli-interactive/HISTORY.rst
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/az_completer.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/tests/latest/test_completion.py
src/command_modules/azure-cli-interactive/setup.py

---
completions were ignoring unrecognized command args
ex: 'vm group ' would show 'vm' completions: 'create, show, etc...'

Completions ignore unrecognized command args

---

scripts/ci/publish.sh

1. Add quotes in script
2. Upgrade azure-storage-blob dependencies
---

Update publish script

---

doc/xplat_cli_migration.md

Replace dead Azure CLI install link with a working one that points to the official docs.
---

Fix broken install link.

---

src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py
src/command_modules/azure-cli-role/setup.py

ad app create/update: document update on permissions support

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py

Fix #6045
//CC: @gatneil 
I don't know whether it is possible to force trigger a maintenance so to write an end to end test, but i did run the command and see the request got rejected for a relevant error: `Operation 'performMaintenance' is not allowed on VM 'yg-ss_0' since the Subscription of this VM is not eligible.` 
Let me know other verification I can do.

vmss: expose 'az vmss perform-maintenance'

---

src/azure-cli-core/azure/cli/core/commands/client_factory.py
src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_client_factory.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_socket_timeout.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_blob_scenarios.py

---
Addresses https://github.com/Azure/azure-cli/issues/5896

Expose `--socket-timeout` for blob uploads and downloads

---

src/command_modules/azure-cli-batch/HISTORY.rst
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_help.py
src/command_modules/azure-cli-monitor/HISTORY.rst
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py
src/command_modules/azure-cli-monitor/setup.py
src/command_modules/azure-cli-redis/HISTORY.rst
src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/_help.py
src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/commands.py
src/command_modules/azure-cli-redis/setup.py
src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
tools/automation/cli_linter/linter.py
tools/automation/cli_linter/rules/command_group_rules.py
tools/automation/cli_linter/rules/command_rules.py

---
-Also deprecated `redis patch-schedule patch-schedule show`
-addresses command group help rule for https://github.com/Azure/azure-cli/issues/6021

Fixed up rules violations for command group help, `redis patch-schedule show`

---

scripts/ci/precheck_header.sh
src/command_modules/azure-cli-advisor/azure/cli/command_modules/advisor/_params.py
tools/automation/tests/verify_package_versions.py

Closes https://github.com/Azure/azure-cli/issues/6038

Verify package versions with last CLI release (as well as pyPI)

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/blob.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_batch_operations.py

---
Closes: https://github.com/Azure/azure-cli/issues/5837
-blob names starting with forward slashes are treated as relative paths.
-if multiple blob names would resolve to the same local file path, a CLIerror is thrown

Resolve batch download of blobs with names starting with forward slash

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_blob_copy_scenarios.py

---
Fixes: https://github.com/Azure/azure-cli/issues/6073

Take care of sas token inputs for `storage blob copy` source with query char

---

src/command_modules/azure-cli-lab/HISTORY.rst
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/commands.py
src/command_modules/azure-cli-lab/setup.py

---
Fixes: https://github.com/Azure/azure-cli/issues/6089
Fixes: https://github.com/Azure/azure-cli/issues/5677

Only apply transformer to table output for `lab vm show`

---

tools/automation/tests/verify_package_versions.py

Fix for https://github.com/Azure/azure-cli/commit/44771acb5dc3202627f09422329b6ba820065307 for case where module didn't exist before.

Version check fix: If module not found, it is not in the base repo

---

src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/commands.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/test_graph.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/test_role.py

rbac: remove deprecated 'az ad sp reset-credentials'

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/azure/cli/core/commands/arm.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_ids_query.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py

Fixes #5591. Ensures `--query` works as expected for commands that use `--ids`.
Closes #4829. Allows `--ids` to work with the input from a list command's JSON output.
Partially implements #4340. Allows `--ids` to work with a list command's JSON ouput without having to use `--query. Allows `--ids` to work with the TSV output (query IS required though).
Adds tests for these scenarios.
---

`--ids` fixes

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py

Fix #5658 
Another fallout from the breaking change of azure-mgmt-web that 404 is not treated as an error code

webapp: misc bug fixes

---

src/azure-cli-core/azure/cli/core/commands/arm.py

Fixes 2 issues:
1. Previously, if you submitted an ID that was too short (for example, feed a VNET ID to a `subnet show` command) you would receive a stack trace. 
2. Updates the logic from the previous PR so that the JSON simplification will work for commands that return a JSON object. The old version only works for JSON Arrays.
---

Improve ID parsing

---

doc/configuring_your_machine.md

The current invocation results in an error when pasted into a terminal:
```
python3: can't open file '–m': [Errno 2] No such file or directory
```

Switch ldash to dash for better cut/paste

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

Per suggestion from @cgillum, this configuration is not expected to be used by lots of people and will be revisited in future; also the telemetry data shows no usage in the last 6 months. So let us make it no-so discoverable by pulling it out.

webapp: remove '--runtime-version' from 'az webapp auth update'

---

src/command_modules/azure-cli-interactive/HISTORY.rst
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/_dump_commands.py
src/command_modules/azure-cli-interactive/setup.py

---
Fixes: https://github.com/Azure/azure-cli/issues/6109
-help dumping was broken with positional args, this fixes it.

Fixed broken interactive completers with positional arguments

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/commands/__init__.py

---
Currently, if you type `az ''` or `az <some commands> ''`, it will output an unfriendly error message:
This fix will output a more user-friendly error message:

Minor fix in _rudimentary_get_command

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py

The example is an 'create' command while this is actually an 'update' command.
Closes https://github.com/Azure/azure-cli/issues/5504
---

Remove incorrect example for 'az role definition update'

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/azure/cli/core/commands/client_factory.py
src/azure-cli-core/azure/cli/core/profiles/__init__.py
src/azure-cli-core/azure/cli/core/profiles/_shared.py
src/azure-cli-core/azure/cli/core/tests/test_api_profiles.py

- Only list through RTs in the current profile instead of all (no need to go through all)
Marked as DNM for now to get feedback and also, it includes a change to storage that we wouldn't want to actually merge.

Support custom resource types being added to API_PROFILES

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/disk_encryption.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_encryption_e2e.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_disk_encryption_e2e.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_custom_vm_commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

Old 2 passes flow is still supported through detecting mechanism proposed by ADE team. Supported linux disto list is also updated.
//CC @SudhakaraReddyEvuri

vm: single pass encryption support

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_docker_utils.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/latest/test_acr_commands_mock.py

Fixes https://github.com/Azure/azure-cli/issues/6131
---

[ACR] Always use access token for acr login

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_actions.py

vm create: fix invalid detection logics on vhd blobs
