- src/azure-cli-core/azure/cli/core/commands/parameters.py
There is a check to ensure that a given command only has a single positional argument. The linter loads parameters twice, which triggers this check to fail (it will see the previous registration).  This change modifies the check so that if the positional arg being registered is already registered, this is okay. Should fix issue with PR #6241.
---
> Make positional args check more robust.

- src/command_modules/azure-cli-vm/HISTORY.rst
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_msi_no_scope.yaml
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_explicit_msi.yaml
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_msi.yaml
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_explicit_msi.yaml
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_msi.yaml
- src/command_modules/azure-cli-vm/setup.py
(Not for //build release)
The main purpose is to by-pass the access check on linked resources which otherwise would block the whole operation e.g. if the users has access to the VMSS, but not on the LB.
> vm/vmss: use patch for updating identities

- src/azure-cli-core/azure/cli/core/telemetry_upload.py
This is used to avoid uploader from run into the situation when
Applicaiton Insight service is unresponsive.
---
> Add timeout to the telemetry sender

- src/azure-cli-testsdk/HISTORY.rst
- src/azure-cli-testsdk/setup.py
To avoid a new version to be selected unintentionally.
Long story:
About to release 1.0.0 of `azure-devtools`. However, the newer version will introduce test error. It should not be picked up until the test recordings are rebased. This change will prevent 1.0.0 from being picked up unless the setup is intentionally updated.
---
> Update dependency on azure-devtools

- src/command_modules/azure-cli-monitor/HISTORY.rst
- src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_exception_handler.py
- src/command_modules/azure-cli-monitor/setup.py
Partially address #6120. Makes the Monitor exception handling logic case-insensitive for the payload keys to ensure that the Code is displayed as intended.
The rest of that issue belongs with the service team.
---
> [Monitor] Make Monitor exception handler case insensitive.

- src/azure-cli-core/azure/cli/core/commands/arm.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
- src/command_modules/azure-cli-resource/HISTORY.rst
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py
- src/command_modules/azure-cli-resource/setup.py
- src/command_modules/azure-cli-vm/HISTORY.rst
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
- src/command_modules/azure-cli-vm/setup.py
Closes #6231.
Adds the unwrapping logic to all template-based creates, although the original issue was only reported with VM. The issue might be limited to compute, but adding the logic doesn't hurt Network or Resource.
---
> Add exception unwrapping for template-based creates.

- src/command_modules/azure-cli-appservice/HISTORY.rst
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_consumption_e2e.yaml
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_e2e.yaml
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_update.yaml
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
- src/command_modules/azure-cli-appservice/setup.py
> appservice: generic update for web/functionapp

- scripts/ci/a01/dockerfiles/py36/Dockerfile
- scripts/ci/build_droid.sh
- src/azure-cli-testsdk/HISTORY.rst
- src/azure-cli-testsdk/setup.py
> Update the dependency of azure-devtools to 1.0.0

- doc/authoring_tests.md
Also clean up the markdown lint errors.
---
> Add policy regarding live test

- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Addressed 4 failures, `test_vm_generic_update`, `test_vm_create_progress`, `test_vm_os_disk_swap`, and `test_vm_write_accelerator_e2e`
//cc: @troydai    
> test: fix the vm live test failure

- src/command_modules/azure-cli-keyvault/HISTORY.rst
- src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_client_factory.py
- src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_command_type.py
- src/command_modules/azure-cli-keyvault/setup.py
> keyvault: make commands work in cloud shell or vms with identity

- src/command_modules/azure-cli-network/HISTORY.rst
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
- src/command_modules/azure-cli-network/setup.py
Fix #6326.
Regression due to Autorest3 and the fact that the Network Watcher tests don't re-record reliably.
---
> [Network] Fix Network Watcher Show-Topology

- requirements.txt
- src/azure-cli-core/setup.py
- src/command_modules/azure-cli-batchai/HISTORY.rst
- src/command_modules/azure-cli-batchai/setup.py
- src/command_modules/azure-cli-profile/HISTORY.rst
- src/command_modules/azure-cli-profile/setup.py
msrestazure already depends on adal, so I will rely on msrest to do the right thing. This is to avoid random CI break caused by version out-of-sync when a new ADAL gets released.
//cc: @lmazuel 
> auth: remove adal dependencies from cli and rely on msrestazure instead

- src/azure-cli-core/azure/cli/core/commands/arm.py
- src/azure-cli-core/azure/cli/core/tests/test_generic_update.py
- src/command_modules/azure-cli-role/HISTORY.rst
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/commands.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/recordings/test_application_set_scenario.yaml
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/test_graph.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/test_role_commands_thru_mock.py
Fix #6097 
@tjprescott, could you please take a look? Note, I have tried to apply the generic update pattern, but because the AD App has its own PATCH operation and own model type which disconnects the generic getter from the generic setter, hence my code was quite hacky.  
But let me know if there is still a nice way to accomplish through the generic update.
> ad app update: allow setting random properties

- src/command_modules/azure-cli-vm/HISTORY.rst
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_vm_utils.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_write_accelerator_e2e.yaml
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_actions.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
The goal is to control the complexity of `vm create` by not exposing something which few people will need, say this accelerator flag which requires 64+ cores VM. This command argument was introduced in the last sprint, and but was too late to revert. CRP team was fine with the change, and the telemetry data shows no usage since release, so it is fine to pull it out.
> vm create:remove `--write-accelerator` from `vm create`

- src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/az_completer.py
---
Following from feedback on https://github.com/Azure/azure-cli/pull/6381
> blanket try-catch to ensure following unpatch code

- build_scripts/windows/scripts/build.cmd
Based on [pep-3147](https://www.python.org/dev/peps/pep-3147/), I rearranged the pyc files. Done a few testing, saw nothing broken. 
> setup: deploy pyc files only

- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands_thru_mock.py
@yugangw-msft This is rewriting this test in a more generic way that does not assume some "msrest" internals (using private attributes). Otherwise my latest "msrest" breaks this CLI test, even if the test does not really care about "msrest".
This fix works with all "msrest" version.
> Improve AppService tests to not rely on a specific msrest

- src/azure-cli-core/azure/cli/core/parser.py
Throws a command authoring error if the developer attempts to use a multi-character short option.
---
> Prevent multi-character short options

- doc/extensions/README.md
This change adds help text for extension developers so that they know to use wheel 0.29.0 or 0.30.0 to package their extension, per the comment in #6441
---
> Add wheel version note for extension developers

- src/command_modules/azure-cli-acs/HISTORY.rst
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
- src/command_modules/azure-cli-acs/setup.py
`az aks get-credentials` would create the ~/.kube/config file with permission for others to read and write it. This instead creates the file with `0600` permissions on non-Windows platforms, and warns the user if an existing config file doesn't have those permissions.
---
> [AKS] try to ensure kube config file has secure perms

- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
It will be a while to sort out the plan to either absorb or revert the [ADAL change] (https://github.com/AzureAD/azure-activedirectory-library-for-python/pull/151/files#diff-03f44f824a1959ef23cc5f4861b150a5) . At the same time, I am submitting this change to get CI unblocked
> stack: fix login failure caused by recent ADAL change

- tools/automation/verify/verify_module_load_times.py
See issue #6224, #6218 and PR #6426.
We have a "perf bubble" in the CLI that, depending on the PR, moves between modules. Rather than chasing it by changing the threshold, this script allows one small bubble (<30 ms load time) to still pass, regardless of which module it is in. The second detected bubble will fail the script. 
This should be a more stable workaround until the underlying cause is identified.
---
- [N/A] I …
> Allow one "bubble" in the perf script.

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/adal_authentication.py
- src/azure-cli-core/azure/cli/core/commands/client_factory.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
- src/command_modules/azure-cli-network/HISTORY.rst
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_client_factory.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
- src/command_modules/azure-cli-network/setup.py
A scaled down version of #6423 with only vnet peering
> support vnet peering across tenant

- src/command_modules/azure-cli-sql/HISTORY.rst
- src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py
- src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_params.py
- src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_util.py
- src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_validators.py
- src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py
- src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/custom.py
- src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_managed_db_mgmt.yaml
- src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_managed_instance_mgmt.yaml
- src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
- src/command_modules/azure-cli-sql/setup.py
* Added new Managed instance and Managed database CRUD commands.
* Managed instance commands:
* az sql mi create
* az sql mi show
* az sql mi list
* az sql mi update
* az sql mi delete
* Managed database commands:
* az sql midb create
* az sql midb show
* az sql midb list
* az sql midb restore
* az sql midb delete
- [x ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).
- [x ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md …
> Adding CRUD azure cli commands for Managed instance and Managed database resources

- src/azure-cli-core/azure/cli/core/parser.py
- tools/automation/cli_linter/linter.py
- tools/automation/cli_linter/rules/parameter_rules.py
---
This broke the [iot extension](https://github.com/Azure/azure-iot-cli-extension)
> Reverted check for bad short options in parser and added linter rule

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/setup.py
- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/__init__.py
- src/azure-cli/setup.py
We reserved `2.0.36` for the intermediate before next normal release cycle.
---
> Bump version to 2.0.37

- src/azure-cli-core/azure/cli/core/_profile.py
AzureStack AAD login fails with 
> The authority url must be of the format https://login.microsoftonline.com/your_tenant
This is because AzureStack ARM returns loginEndpoint with a trailing slash “/” for metadata endpoint query:
"loginEndpoint":"https://login.windows.net/”
And [this ](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/_profile.py#L77)line adds another trailing slash which causes the auth_url look like this: 
> https://login.windows.net//tenant_id
and fails the validation. This can be fixed if we strip the trailing slash before adding another one like this:
```
is_adfs = bool(re.match('.+(/adfs|/adfs/)$', authority_url, re.I)) 
if is_adfs: 
authority_url = authority_url.rstrip('/') # workaround: ADAL is known to reject auth urls with trailing / …
```
> Fix Auth_url for AAD env (stack)

- src/azure-cli-core/azure/cli/core/commands/arm.py
---
-This is to enable client factories that require/utilize arguments passed to them.
@troydai this is part of the change needed to allow generic_update to be used for storage data-plane commands.
> Pass in handler arguments to client_factory in generic_update/wait

- src/command_modules/azure-cli-dls/HISTORY.rst
- src/command_modules/azure-cli-dls/setup.py
Updating ADL versions to latest to fix a "msrest" dependency problem. CLI should not be impacted.
FYI @milanchandna
> Update ADL to latest

- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/_help.py
- src/azure-cli-core/azure/cli/core/commands/__init__.py
- src/azure-cli-core/azure/cli/core/parser.py
- tools/automation/cli_linter/__init__.py
- tools/automation/cli_linter/linter.py
- tools/automation/cli_linter/tests/linter_exclusions.yml
- tools/automation/cli_linter/tests/test_linter.py
- tools/automation/cli_linter/util.py
- tools/automation/tests/__init__.py
---
-`cmd.command_source` also used to persist command module source for non-extension commands
-added basic testing for linter for mod/ext filtering and rule exclusion
> Support for extension filtering when running linter

- src/azure-cli-core/azure/cli/core/extension.py
- src/command_modules/azure-cli-extension/HISTORY.rst
- src/command_modules/azure-cli-extension/azure/cli/command_modules/extension/custom.py
- src/command_modules/azure-cli-extension/azure/cli/command_modules/extension/tests/latest/test_extension_commands.py
- src/command_modules/azure-cli-extension/setup.py
---
`extension list-available` will only show extensions compatible with the version of the CLI being used.
Closes: https://github.com/Azure/azure-cli-extensions/issues/187
Closes: https://github.com/Azure/azure-cli/issues/6419
> Extension list-available will only list extensions available for CLI version

- src/command_modules/azure-cli-acs/HISTORY.rst
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
- src/command_modules/azure-cli-acs/setup.py
The idea for this pull request is to support customized local port for kubernetes dashboard in case the default port is used or unavailable.
---
> Support specific port for k8s dashboard

- src/azure-cli-core/azure/cli/core/parser.py
- src/azure-cli-core/azure/cli/core/tests/test_parser.py
---
Added testing for spellchecker and msg choice
Fixes: https://github.com/Azure/azure-cli/issues/6562
> Fixed parser bug assuming value parsed is part of command

- src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/operations/autoscale_settings.py
not all VMSS autoscale settings has notifications, we need to verify before iteration to avoid StopIteration exception
without the change, following command will hit StopIteration exception
az monitor autoscale update --resource-group vmssRgName --name AutoScaleName --count 5
---
> check notifications before enumeration

- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
Fixes #6654.  `--ip-address` is required, but due to reflection on the SDK which has a default of None, it appeared as optional. 
---
> Fix `vnet check-ip-address` help

- src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/latest/test_acr_commands.py
> [ACR] Add record only flag to import and build-task tests

- .travis.yml
- src/command_modules/azure-cli-network/HISTORY.rst
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_format.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
- src/command_modules/azure-cli-resource/HISTORY.rst
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py
- src/command_modules/azure-cli-vm/HISTORY.rst
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
Adds `--no-wait` support to various VM and VMSS extension, NIC and Deployment commands. Adds some `wait` commands where not previously supported (except VMSS extension, which did not work with generic wait).
---
> Add `--no-wait` support to various commands

- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_client_factory.py
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/test_custom.py
The Log Analytics workspace is often in a different subscription from the AKS cluster it connects to. This changes those API calls to use the subscription ID embedded in the --workspace-resource-id argument, which fixes this use case.
Also raises an error when the user enables monitoring when it's already enabled, since changing the config this way doesn't work yet. We can remove this error catching when the behavior is fixed.
---
> [AKS] handle monitoring solution through its subscription ID

- src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/__init__.py
> Suppress rdbms vnet extension

- .travis.yml
- tools/automation/tests/main.py
I'm looking into the recent automation failure on 2.7. At this point, I have some clue what happened. But it won't be fixed shortly. This PR will disable the automation to enable other works.
> Temporarily disable automation on 2.7

- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
FYI @troydai @williexu 
I got a issue from customer that KV and MSI didn't work anymore since azure-keyvault 1.0.0. Turned out this was two bugs:
- MSIAuthentication should get the token in the `__init__` and not in `signed_session`. That's the contract of msrestazure that KV expects to do some credentials magic. It was working in azure-keyvault 0.3.7 by chance. https://github.com/Azure/msrestazure-for-python/issues/106
- MSIAuthentication should support set `resource`, in order for KV magic to work. This was broken by the IMDS work. https://github.com/Azure/msrestazure-for-python/issues/109
Bug 1 is fixed in msrestazure 0.4.34, but CLI was built on the incorrect behavior that `set_token` was a required call. This PR simplifies the code according to the expected behavior.
Bug 2 is in a PR …
> Fix MSI for msrestazure 0.4.34

- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/tests/test_util.py
- src/azure-cli-core/azure/cli/core/util.py
This should address #6717. The existing logic would catch the exception and fallback to the device code, but for situations we know it would never work, this change would skip instead of even trying.
> login: check GUI is available before launch the browser

- src/azure-cli-core/azure/cli/core/commands/__init__.py
- src/azure-cli-core/azure/cli/core/commands/arm.py
- src/azure-cli-core/azure/cli/core/file_util.py
- src/azure-cli-core/azure/cli/core/tests/test_help.py
- src/azure-cli-testsdk/azure/cli/testsdk/__init__.py
- src/command_modules/azure-cli-interactive/HISTORY.rst
- src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/_dump_commands.py
- src/command_modules/azure-cli-interactive/setup.py
- src/command_modules/azure-cli-network/HISTORY.rst
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
Closes #6062.
Also, fixes a logic bug in the global subscription ID parameter.
---
> [Network] Deprecate `--ids` on certain list commands

- Dockerfile.spot
Support creating 'Spots' directly from PRs in the repo.
> Proposal: Add Dockerfile.spot?

- src/command_modules/azure-cli-resource/HISTORY.rst
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py
Closes #6720.
The subscription-level deployment commands are only supported on the 2018-05-01 API version or higher. They should not appear on the stack profile at all.
---
> [Resource] Suppress "deployment" commands on Stack profile

- src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/_help.py
According to the other help, it might be right.
This pull request is the fix of this issue. 
https://github.com/Azure/azure-cli/issues/6674
This pull request is only for help text.
---
- [ x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).
> fix the wrong help

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/commands/arm.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet.yaml
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/latest/recordings/test_resource_group.yaml
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/latest/test_resource.py
Adds support for the `--tags` convenience argument to `group update`. Also, adds global support to generic update for `--force-string` which signals the code to not try and evaluate the contents of a supplied string, but simply to treat the input as a string.  Fixes #6605.
---
> Add `--force-string` flag to generic update.

- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
Fix #6729
I have verified the storage table is getting populated with the perf data from the vm
I guess there have been a few recent change from the diagnostics extension, as the old timestamp did work last year
> vm: fix wrong timestamps on creating sas token in vm diagnostics samples

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/setup.py
- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/__init__.py
- src/azure-cli/setup.py
- src/command_modules/azure-cli-acs/HISTORY.rst
- src/command_modules/azure-cli-acs/setup.py
The current release package already pin paramiko at 2.4.1. This change
merely ensure user who PIP installed CLI can avoid vulnerability.
---
> Add version constraint of paramiko

- src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
Managed instance tests have hardcoded instance id due to long time to provision. This prevents them from passing in live tests.
---
> Skip managed instance live tests

- src/command_modules/azure-cli-extension/azure/cli/command_modules/extension/_index.py
---
-"https://aka.ms/azure-cli-extension-index-v1" seems to be more consistent, so adding back
-will work with all CLI versions in case we need to change the underlying blob url/storage account
-added retry logic in case reliability drops again
> Adding retry logic and use aka.ms url

- src/azure-cli-core/azure/cli/core/profiles/_shared.py
- src/azure-cli-core/azure/cli/core/tests/test_api_profiles.py
KeyVault data-plane latest API version is "7.0", which won't work in the Profile package right now, because every API versions used to discriminate are supposed to be date (e.g. "2018-06-01").
This introduces:
- The ability to get models from an API version that uses semver
- Ordering of semver
- Ordering of semver against date. This is subtle, we have no reason to consider 7.0 against 2016-07-01 as one older than the other. For now, *I consider date API Version are always older than SemVer*. This fits the KeyVault scenario, and if one day we have another service team that says the opposite, we could add a flag or something in the profile definition. I tend by default to reduce technical debt and not try to solve an hypothetic problem, so didn't add that flag today :).
> Allow SemVer APIVersion

- src/command_modules/azure-cli-acs/HISTORY.rst
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
Closes #6737. 
This also changes the return code from a non-interactive `az aks browse` command from 1 (error) to 0 (success). Since the command itself instructs the user to press [Ctrl+C], it seems incorrect to return an error code on `KeyboardInterrupt`.
---
> [AKS] handle [Ctrl+C] gracefully in "az aks browse"

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/setup.py
The version of the Core was bumped prematurely. The version `2.0.43` hasn't been used yet.
> Revise Azure CLI Core version to 2.0.43.

- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
Improves on the hand-rolled deprecation notice in #6648 by using the framework added in #6472.
```console
$ az aks create -h
Command
az aks create : Create a new managed Kubernetes cluster.
Arguments
...
--enable-addons -a             : Enable the Kubernetes addons in a comma-separated list.
These addons are available:
http_application_routing - configure ingress with automatic public DNS name creation.
monitoring - turn on Log Analytics monitoring. Uses the Log Analytics Default Workspace
if it exists, else creates one. Specify "--workspace-resource-id" to use an existing
workspace.
--enable-rbac -r  [Deprecated] : Enable Kubernetes Role-Based Access Control. Default:
enabled.
Argument 'enable_rbac' has been deprecated and will be removed in a future release. Use
'--disable-rbac' …
```
> [AKS] properly deprecate "az aks create --enable-rbac" argument

- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_validators.py
Added the calculation of minimum number of pods based on node_count to enable at least 1 pod in default namespace for --max-pods.
---
> validate_max_pods must calculate min # of pods

- src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/operations/sp.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
Role assignment transitivity for service principals is now supported, so
update the documentation on the --include-groups flag to indicate this.
---
> Update doc for SP role assignment include_groups

- src/command_modules/azure-cli-vm/HISTORY.rst
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
- src/command_modules/azure-cli-vm/setup.py
Fix #6904. It appears the `min_api` doesn't work when used in the constructor of  CliCommandType
> run-command: bug fix so it doesn't show up under stack profile

- src/command_modules/azure-cli-acs/HISTORY.rst
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
- src/command_modules/azure-cli-acs/setup.py
Modification to `az aks install-connector` command to handle RBAC correctly.  The virtual kubelet helm chart recently updated to enable RBAC by default. In an RBAC enabled cluster, this creates the needed clusterrolebinding and service account for virtual kubelet. On a non-RBAC cluster, these should not be created. The virtual-kubelet helm chart has a flag to drive this. This PR fetches the cluster info to determine if `enable-rbac` is true and drives the helm install or upgrade off of that. 
This PR fixes #6922. 
---
> Modification to az aks install-connector command to handle RBAC

- src/azure-cli/setup.py
Add azure-cli-search to azure-cli dependencies.
So when user install azure-cli via "pip install azure-cli", search command will be supported.
---
> Add azure-cli-search to azure-cli dependencies

- .gitignore
- .travis.yml
- scripts/ci/unittest.sh
- src/azure-cli-telemetry/azure/cli/telemetry/components/records_collection.py
- src/azure-cli-telemetry/azure/cli/telemetry/components/telemetry_logging.py
- src/azure-cli-telemetry/azure/cli/telemetry/components/telemetry_note.py
- src/azure-cli-telemetry/azure/cli/telemetry/tests/test_telemetry_client.py
- src/azure-cli-telemetry/azure/cli/telemetry/tests/test_telemetry_logging.py
- src/azure-cli-telemetry/azure/cli/telemetry/tests/test_telemetry_note.py
- src/azure-cli-telemetry/azure/cli/telemetry/util.py
- src/azure-cli-telemetry/setup.cfg
- src/azure-cli-telemetry/setup.py
- src/azure-cli-telemetry/tox.ini
> Make telemetry be compatible with Python 2

- src/command_modules/azure-cli-acr/HISTORY.rst
- src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/build.py
Fix #6798 - follow unix glob pattern to match dot character. NB: Unable to use python fnmatch module as it handles * different from docker.
Fix #6896 - handle the ignore case in which the parent folder is excluded but its child items are included.
@djyou @ehotinger 
---
> Handle .dockerignore file properly in acr build comand

- src/command_modules/azure-cli-batchai/HISTORY.rst
- src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/custom.py
- src/command_modules/azure-cli-batchai/setup.py
Changes logger output on `az batchai cluster create` to specify that the resource type it's creating is a resource **group**.
* was: Creating %s resource for auto-storage account
* now: Creating %s resource group for auto-storage account
Unsure if this counts as **docs only**. If it doesn't, let me know and I'll update HISTORY.rst. Thanks!
---
> [batchai] logger: specify 'group' resource type

- src/azure-cli-core/setup.py
- src/command_modules/azure-cli-acr/setup.py
- src/command_modules/azure-cli-appservice/setup.py
- src/command_modules/azure-cli-dla/HISTORY.rst
- src/command_modules/azure-cli-dla/setup.py
- src/command_modules/azure-cli-iot/setup.py
- src/command_modules/azure-cli-monitor/HISTORY.rst
- src/command_modules/azure-cli-monitor/setup.py
- src/command_modules/azure-cli-network/HISTORY.rst
- src/command_modules/azure-cli-network/setup.py
- src/command_modules/azure-cli-resource/HISTORY.rst
- src/command_modules/azure-cli-resource/setup.py
- src/command_modules/azure-cli-search/HISTORY.rst
- src/command_modules/azure-cli-search/setup.py
- src/command_modules/azure-cli-servicefabric/HISTORY.rst
- src/command_modules/azure-cli-servicefabric/setup.py
- src/command_modules/azure-cli-vm/setup.py
This change including a revert of previous commit (#6983). The original thought was to add the dependency to the individual command modules, therefore, avoid indirect dependency. However, the `azure-mgmt-resource` proves to be a crucial dependency. After the #6983 was made, newly added module `iotcentral` also takes a dependency on it while didn't declare it. Hence explicit declare at command module is not a sustainable approach.
In this change, the dependency will be declared in the core so that all the command module will indirectly share the dependency and the versioning of the dependency is centrally controlled.
> Declare explicit dependency on azure-mgmt-resource in core and subsequently remove dependencies of it from command modules.

- src/command_modules/azure-cli-storage/HISTORY.rst
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/blob.py
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_batch_operations.py
---
- Closes: https://github.com/Azure/azure-cli/issues/1434
- Use command validators to specify order. Previously, if container url/ENV variable were both present, the account-name would be set depending on which validator was called first.
- Consolidated batch validator code for parsing container url
> [Storage] Get sas-token from container url and cleanup code

- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Test runner failed because of the recording only decorators
> test: fix vm live test errors

- src/command_modules/azure-cli-appservice/HISTORY.rst
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_ssl.yaml
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
- src/command_modules/azure-cli-appservice/setup.py
It is long overdue that appservice create command don't accept tags like other commands. This PR adds that.
> appservice: tag support on create

- doc/authoring_command_modules/authoring_commands.md
Add guidance and examples for deprecation.
---
- [N/A] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).
> Add deprecation to command authoring docs

- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_client_factory.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_public_ip_prefix.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py
**Note**: This is a merge into a dedicated branch for Ignite networking work. It won't pass CI right now and I'm only looking for code review so that specific features can be reviewed in small pieces instead of a huge PR later.
Adds commands to create Public IP prefixes.
cc/ @anilingle-ms 
---
> [Network] Public IP Prefix

- azure-cli2017.pyproj
- src/command_modules/azure-cli-cognitiveservices/HISTORY.rst
- src/command_modules/azure-cli-cognitiveservices/azure/cli/command_modules/cognitiveservices/_params.py
- src/command_modules/azure-cli-cognitiveservices/azure/cli/command_modules/cognitiveservices/custom.py
- src/command_modules/azure-cli-cognitiveservices/azure/cli/command_modules/cognitiveservices/tests/latest/recordings/test_cognitiveservices_create_api_properties.yaml
- src/command_modules/azure-cli-cognitiveservices/azure/cli/command_modules/cognitiveservices/tests/latest/test_api_properties.py
- src/command_modules/azure-cli-cognitiveservices/setup.py
Add a new parameter --api-properties for create command.
--api-properties could be either key=value key=value pairs or JSON string.
---
> [Cognitive Services] Support ApiProperties which enable creating QnAMaker

- src/command_modules/azure-cli-acr/HISTORY.rst
- src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/build.py
- src/command_modules/azure-cli-acr/setup.py
> ignore files in vcs (eg, .git) direcotry

- src/command_modules/azure-cli-acr/HISTORY.rst
- src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_docker_utils.py
- src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/custom.py
- src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/repository.py
- src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/latest/test_acr_commands_mock.py
- src/command_modules/azure-cli-acr/setup.py
> [ACR] Provide a workaround for runtime operations without ARM requests

- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
Resolves #6494.
I did not make major changes to the `az vm run-command` short summaries, to keep in line with other Azure documentation ([SDKs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.fluent.virtualmachineruncommandsoperationsextensions?view=azure-dotnet) and [rest AP](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2018-06-01/runCommands.json)I). 
However, I did include a long summary that links to two webpages that explain Azure's Run Command Feature. 
It appears that long summaries are shown on the command line but not on the online reference. So I am not sure how helpful it would be to the person who raised this issue.
Please let me know your thoughts on the changes made. …
> Run command help issue

- src/command_modules/azure-cli-acr/HISTORY.rst
- src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/build.py
- src/command_modules/azure-cli-acr/setup.py
**Purpose of the PR**:
- Change ACR build's client log polling logic to be strictly client-side instead of intertwining client and server times. Now, it's strictly logical and client based. This prevents issues where some clients' clocks aren't synchronized causing builds to exit early but eventually be successful, as well as potential issues where clients' clocks synchronize and skip time in the middle of builds.
**Fixes #7096**
cc @djyou @northtyphoon @SteveLasker 
---
> [ACR] Use client-side logical time for log polling

- azure-cli2017.pyproj
- src/command_modules/azure-cli-network/HISTORY.rst
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_client_factory.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_completers.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_service_endpoints.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py
- src/command_modules/azure-cli-network/setup.py
**Note:** This is a merge into a dedicated branch for Ignite networking work. It won't pass CI right now and I'm only looking for code review so that specific features can be reviewed in small pieces instead of a huge PR later.
This adds support for service endpoint policies and policy definitions.
Closes #6932. cc/ @chandrasekarsrinivasan 
---
> [Network] Service endpoint policies

- azure-cli2017.pyproj
- src/command_modules/azure-cli-network/HISTORY.rst
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_load_balancer_outbound_rules.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Adds support for Standard LB outbound rules.  **Note**: CI will not pass due to SDK not being released. This is a merge to a separate branch (not dev) to facilitate easier code review. 
cc/ @christiankuhtz 
Closes #6931.
---
> [Network] Load Balancer Outbound Rules

- src/command_modules/azure-cli-vm/HISTORY.rst
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
- tools/automation/cli_linter/rules/parameter_rules.py
Deprecate `--storage-caching` option in `vm create`. cc/ @dend @EdisonDa 
---
> [Compute] Deprecate `--storage-caching` option in VM create.

- src/command_modules/azure-cli-network/HISTORY.rst
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
cc/ @christiankuhtz 
**Note**: Merging to IgniteNetwork branch
Adds `--enable-tcp-reset` (added with outbound-rules) to the create/update commands for LB rule, inbound-nat-rule and inbound-nat-pool.
---
> [IgniteNetwork] Add `--enable-tcp-reset` to existing commands

- .github/CODEOWNERS
- src/command_modules/azure-cli-dms/HISTORY.rst
- src/command_modules/azure-cli-dms/linter_exclusions.yml
- src/command_modules/azure-cli-dms/setup.py
- src/command_modules/azure-cli-eventhubs/HISTORY.rst
- src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/_help.py
- src/command_modules/azure-cli-eventhubs/setup.py
- src/command_modules/azure-cli-iotcentral/HISTORY.rst
- src/command_modules/azure-cli-iotcentral/azure/cli/command_modules/iotcentral/_help.py
- src/command_modules/azure-cli-iotcentral/setup.py
- src/command_modules/azure-cli-network/HISTORY.rst
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
- src/command_modules/azure-cli-network/setup.py
- src/command_modules/azure-cli-relay/HISTORY.rst
- src/command_modules/azure-cli-relay/azure/cli/command_modules/relay/_help.py
- src/command_modules/azure-cli-relay/setup.py
- src/command_modules/azure-cli-servicebus/HISTORY.rst
- src/command_modules/azure-cli-servicebus/azure/cli/command_modules/servicebus/_help.py
- src/command_modules/azure-cli-servicebus/setup.py
- src/command_modules/azure-cli-servicefabric/HISTORY.rst
- src/command_modules/azure-cli-servicefabric/azure/cli/command_modules/servicefabric/_help.py
- src/command_modules/azure-cli-servicefabric/setup.py
- src/command_modules/azure-cli-sql/HISTORY.rst
- src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py
- src/command_modules/azure-cli-sql/linter_exclusions.yml
- src/command_modules/azure-cli-sql/setup.py
- tools/automation/cli_linter/rules/ci_exclusions.yml
---
Fixes: https://github.com/Azure/azure-cli/issues/6576
Fixes: https://github.com/Azure/azure-cli/issues/5912
> Cleaned up rest of faulty examples

- src/command_modules/azure-cli-batchai/HISTORY.rst
- src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/custom.py
- src/command_modules/azure-cli-batchai/setup.py
Fix batch ai cluster auto storage account creation [issue](https://github.com/Azure/azure-cli/issues/7129)
---
> Fix batch ai cluster auto storage account creation issue

- azure-cli2017.pyproj
- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/commands/arm.py
- src/command_modules/azure-cli-network/HISTORY.rst
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
- src/command_modules/azure-cli-role/HISTORY.rst
**Merge to IgniteNetwork branch**
Fixes #7065. Fixes #7066.
Adds a "get_arm_resource_by_id" method to core that allows us to get basic info on any resource (including classic resources) with an ARM ID. This unblocks the scenario to allow flow-log configuration on a classic NSG. 
cc/ @zwswim
---
> [IgniteNetwork] Fix issues with Network Watcher flog-log configure

- src/command_modules/azure-cli-keyvault/HISTORY.rst
- src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/custom.py
- src/command_modules/azure-cli-keyvault/setup.py
- Replace multiple calls to `rsa_key.private_numbers()` to avoid unnecessary
allocations
- Fix typo when accessing the DQ and DP values of the RSA private key (fixes #7151)
---
> Fix key vault key import for RSA keys

- src/azure-cli-core/azure/cli/core/_session.py
When session files are missing (e.g. in a new instance of a build agent) we do not wish to log at warning level as this breaks existing CI/CD systems not expecting this output.
Do log warnings for invalid JSON data (corrupted / malformed files) however.
Inspired by VSTS agents broken by using az cli 2.0.45 and failing during az login. :)
---
> Variable log level when session files are invalid

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/keys.py
- src/azure-cli-core/azure/cli/core/tests/test_keys.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/hybrid_2018_03_01/test_vm_actions.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_actions.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/profile_2017_03_09/test_vm_actions.py
Fixes #4725 and #6780 by using `id_rsa` as the private key file (if it exists) to generate a new public key instead of generating a new private-public key pair (which overwrites `id-rsa`).
I tested this fix by deleting my public key and running `az vm create ... --ssh-key-gen`.
A new public key was generated in `id_rsa.pub` and I was able to ssh into the newly created VM. I was able to create another vm using the existing keys pair and ssh into it.
Please let me know your thoughts on this PR.
---
> Addressing -ssh-key-gen bug.

- src/command_modules/azure-cli-network/HISTORY.rst
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_client_factory.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_interface_endpoints.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_subnet_delegation.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py
**NOTE**: Merge to IgniteNetwork branch.
cc/ @rupalivohra 
Adds support for `network interface-endpoint show/list`.  `create`, `update`, `delete` code is included but blocked since the service does not fully support those operations. These will be enabled at the service team's request, tracked via issue #7271.
---
> [IgniteNetwork] Read-only support for InterfaceEndpoints

- src/azure-cli-core/azure/cli/core/commands/__init__.py
- src/azure-cli-core/azure/cli/core/util.py
--
Fixes: https://github.com/Azure/azure-cli/issues/7196
> Allow update/wait/show registering methods to inherit commandtype kwargs

- src/command_modules/azure-cli-resource/HISTORY.rst
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
- src/command_modules/azure-cli-resource/setup.py
Fixes issue #7238.
Fixed bug in create_application() for marketplace managedapps where positional arguments were being passed into Plan object's __init__ instead of key-word arguments.
This bug was introduced through a change to the `Plan` model signature in this [commit](https://github.com/Azure/azure-sdk-for-python/commit/0ff3ea47c5c622c17e7e9d63d6e93ec6aac1dc86#diff-aa15f09e1f1ef7d92f246bd786dc244c) to the azure SDK. According to the release history file for `azure-mgmt-resource` from this commit onwards all model signatures use only keyword-argument syntax.
---
> Fixed bug in create_application() for marketplace managedapps.

- src/command_modules/azure-cli-acs/HISTORY.rst
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/commands.py
- src/command_modules/azure-cli-acs/setup.py
We will be replacing the `install-connector` command with a new add-on in AKS. This PR begins the process of deprecating the `install-connector` command. 
---
- [ x ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).
- [ x ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).
> [ACS] Starting the install-connector deprecation process

- src/command_modules/azure-cli-acs/HISTORY.rst
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/commands.py
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
- src/command_modules/azure-cli-acs/setup.py
Virtual Kubelet supports providing the MASTER_URI as a parameter to the helm chart. This PR grabs the masterfqdn from the instance and uses that when installing the chart.  
* NOTE: This also removed deprecation that was done in #7263. The replacement won't happen before Ignite. 
---
- [ x ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).
- [ x ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).
> [ACS] Updates the install-connector command to use the master FQDN, undo deprecation

- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
Regressed by service end change with property renaming
> sign image-version show: fix table output

- src/command_modules/azure-cli-interactive/HISTORY.rst
- src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/_dump_commands.py
- src/command_modules/azure-cli-interactive/setup.py
---
-keys in dictionaries are ignored
- values are converted to their deprecated target.
> Deal with deprecation objects within the command table by ignoring them

- src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/build.py
Adds a deprecation message for `{{ .Build.ID }}` style expressions, indicating that we're no longer supporting it and users should use `.Run.ID` instead.
See also: https://github.com/Azure/acr-builder/issues/287
/cc @northtyphoon @djyou @SteveLasker @sajayantony 
---
> [ACR] Add a deprecation message for Build ID expressions

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/tests/test_util.py
- src/azure-cli-core/azure/cli/core/util.py
- src/azure-cli/HISTORY.rst
Fixes issue #7202.
According to @lmazuel, the default behavior for the SDK when a request fails with an error is to throw a `CloudError`. However some teams modify this behavior through swagger by throwing a custom error response exception which inherits from `HttpOperationError`. So all autorest generated SDK's throw a CloudError or an instance of HttpOperationError. If an SDK is not autorest generated it might not throw either of these exceptions in the event of a bad request, so we might not catch it.
Moreover, ARM error responses are based on the [odata v4 error response](http://docs.oasis-open.org/odata/odata-json-format/v4.01/cs01/odata-json-format-v4.01-cs01.html#sec_ErrorResponse). This informs the logic in the if statement for handling `HttpOperationError` exceptions.
Please let …
> Added logic to handle_exception() to handle bad requests.

- src/command_modules/azure-cli-network/HISTORY.rst
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
- src/command_modules/azure-cli-network/setup.py
Fixes #6052. 
Removed location parameter in create_dns_zone and made it a local variable. This prevents the configured default location being passed in as the location. DNS Zone's are global.
---
> [Network] dns zone create works even if default location is configured.

- src/command_modules/azure-cli-acs/HISTORY.rst
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
- src/command_modules/azure-cli-acs/setup.py
@mboersma @yugangw-msft 
There's no reason to force the user to specify a tenant id when we have it in their subscription profile.
> On AKS create, load the tenant id from profile if it isn't specified.

- src/command_modules/azure-cli-monitor/HISTORY.rst
- src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py
- src/command_modules/azure-cli-monitor/setup.py
Updated _help.py to help differentiate classic metric alerts and new metric alerts.
---
> Differentiate classic and new metric alert rules

- src/command_modules/azure-cli-extension/HISTORY.rst
- src/command_modules/azure-cli-extension/azure/cli/command_modules/extension/custom.py
- src/command_modules/azure-cli-extension/azure/cli/command_modules/extension/tests/latest/test_extension_commands.py
- src/command_modules/azure-cli-extension/setup.py
This is a philosophical change in the extension command module for the add extension functionality. Thought behind this is, 'if a resource I need is already installed, why would that cause an error?'.
At a basic level, this simplifies Azure CLI's extension CI/CD experience particularly when reusing an environment. Without this change a user has to explicitly handle the above stated scenario as its common for CI workflows to fail when an executed element returns a none zero exit code.
---
> Attempting to add an extension that is already installed will not raise an exception

- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
A recent policy change began rejecting creation when a SP name isn't an SSL URL. Prepending `https://` seems to fix it.
See #7375 for more background.
cc: @yugangw-msft 
---
> [AKS] fix service principal creation

- build_scripts/windows/scripts/build.cmd
The `pycparser` 2.19 is breaking windows build script. Before the problem is resolved, pin the version to 2.18
> Patch Windows build script

- doc/authoring_command_modules/authoring_commands.md
Added some explanation of what the arg_group kwarg does. Please let me know how I can reword or illustrate how to use the argument better. Should I create a section elsewhere in the doc to show an example?
---
> Added documentation on arg_group kwarg.

- src/command_modules/azure-cli-role/HISTORY.rst
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/commands.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/test_role_commands_thru_mock.py
- src/command_modules/azure-cli-role/setup.py
Adds support for `az ad app owner list` and `az ad sp owner list`.
---
> [Role] Adds support for listing app and service principal owners

- src/command_modules/azure-cli-vm/HISTORY.rst
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_template_builder.py
> [vmss create] reserve large enough frontend port range for overprovision

- src/command_modules/azure-cli-vm/HISTORY.rst
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_attach_detach.yaml
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
The current logic is not right by deriving the default from existing disk count. This not only might conflict but also might exceed the limit of 64
Fix #6965
> [vm/vmss]: default lun to the first available spot

- src/command_modules/azure-cli-network/HISTORY.rst
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_peering.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_peering_different_resource_groups.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Addressed #7016:
- Deprecated `--remote-vnet-id` in favor of `--remote-vnet`. 
- Passing remote vnet's name instead of resource ID through `--remote-vnet` / ` --remote-vnet-id` does not crash CLI.
- Can also specify resource group of remote vnet if only name is provided through --remote-vnet-rg. 
---
> [Network] vnet peering: deprecated --remote-vnet-id in favor of --remote-vnet

- src/azure-cli/setup.py
Closes https://github.com/Azure/azure-cli/issues/7448.
The homebrew formula generating process fails to bring in `azure-mgmt-botservice` dependency because of this missing reference.
> [Core] Add bot service to azure-cli setup

- src/azure-cli-core/azure/cli/core/commands/parameters.py
- src/command_modules/azure-cli-network/HISTORY.rst
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
Closes #7318.
Updates the subnet create/update command and vnet create command to allow multiple subnet prefixes. This is currently blocked behind a feature flag, so some logic is required to populate *either* the `address_prefix` or `address_prefixes` property. 
---
> [Network] Add support for multiple address prefixes on a subnet

- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
> [sig] fix a parameter name inconsistency on 'sig image-version delete'

- tools/automation/verify/verify_module_load_times.py
Bumps CI module load thresholds to avoid spurious failures.
---
> Bump load thresholds.

- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
The short descriptions for ```--service-cidr``` and ```--docker-bridge-address``` are inconsistent. Both require a CIDR notation IP range. However, while the description of ```--service-cidr``` call it a CIDR notation IP range in the ```--docker-bridge-address``` description it is mentioned as an IP address and netmask. I've noticed this creates confusion among less experienced users.
---
> Cleared up inconsistent language.

- src/command_modules/azure-cli-storage/HISTORY.rst
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_transformers.py
- src/command_modules/azure-cli-storage/setup.py
This PR fixes the issue #7409 https://github.com/Azure/azure-cli/issues/7409.
Steps to reproduce the issue:
1. Set AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_KEY variables (refer to the documentation if necessary: https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-cli)
1. Add 2 or more CORS rules of same type (here are file rules from original issue).
```
#!/bin/bash
az storage cors clear --services f
az storage cors add \
--allowed-headers "x-api-key" \
--methods GET \
--origins http://localhost:5000 \
--exposed-headers "x-ms-request-id, x-ms-lease-status" \
--max-age 10 \
--services f
az storage cors add \
--allowed-headers "content-type" \
--methods GET \
--origins http://localhost:5001 \
--exposed-headers "x-*" \
--max-age 5 \
--services f
az storage cors add \ …
```
> Fix Issue 7409 (az storage cors list missing "Service" field)

- build_scripts/windows/scripts/build.cmd
Add the VS 2017 to the probing path instead of using a full path which broke the local build in my dev box w/o VS 2017
> msi: remove the hard coded msbuild full path

- README.md
The slack shield on README.md appears to be broken. A new shield generated from [shields.io](https://shields.io/#/) has been added
---
> Updates slack shield on README

- src/command_modules/azure-cli-monitor/HISTORY.rst
- src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py
- src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_params.py
- src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/operations/activity_log.py
- src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/validators.py
- src/command_modules/azure-cli-monitor/setup.py
Fix #5274. Fix #5698. Fix #7418.
Allow user to specify name or ID for `--event-hub` and `--event-hub-rule`. For `--event-hub`, if ID is provided, only the name is extracted. For `--event-hub-rule`, if only name is supplied, then ID is built using `--event-hub NAME`.  If ID is provided and `--event-hub` is NOT provided, then `--event-hub` is extracted from the `--event-hub-rule ID`. 
This allows you to use different hubs for `--event-hub` and `--event-hub-rule` but allows the smart extract of data when the hubs are the same without a lot of redundancy.
---
> [Monitor] Improve EventHub validation for `diagnostic-settings create`.

- src/command_modules/azure-cli-vm/HISTORY.rst
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
- src/command_modules/azure-cli-vm/setup.py
This should be the last update before we get the capacity check support through /listSkus
> vm: add more VM sizes with accelerated networking support

- src/command_modules/azure-cli-vm/HISTORY.rst
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_vm_utils.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/hybrid_2018_03_01/test_vm_defaults.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_actions.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_defaults.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/profile_2017_03_09/test_vm_defaults.py
Compute service has no capacity to cross check the cache mode, hence they are asking CLI to do it
> vm/vmss create: ensure caching mode is None for Lv/Lv2 machines

- src/command_modules/azure-cli-acr/HISTORY.rst
- src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_archive_utils.py
- src/command_modules/azure-cli-acr/setup.py
Fixes #7546 
io.open is the default interface in python3
---
> use io.open that supports encoding option in python2

- src/azure-cli-core/azure/cli/core/commands/arm.py
Closes #7552.
Adds validation for generic update so that if the user provides an insufficient --ids string they will get a better error and not a stack trace.
---
> Add validation to generic update

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/commands/__init__.py
- src/azure-cli-core/azure/cli/core/commands/arm.py
- src/azure-cli-core/azure/cli/core/commands/client_factory.py
- src/azure-cli-core/azure/cli/core/file_util.py
- src/azure-cli-core/azure/cli/core/tests/test_help.py
- src/azure-cli-core/setup.py
- src/command_modules/azure-cli-interactive/HISTORY.rst
- src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/azclishell/_dump_commands.py
- src/command_modules/azure-cli-interactive/setup.py
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/latest/recordings/test_global_ids.yaml
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/latest/test_resource.py
- Fixes the behavior when `--ids` and `--subscription` are used together. Previously, the subscription from `--subscription` would override the value in `--ids`.  Now the values in the IDs take precedence.
- Issues an explicit warning when name parameters (`--subscription`, `--resource-group`, `--name`, etc) are used in conjunction with `--ids` to inform the user that the named parameters will be ignored. This used to happen for resource-group and name, but ONLY if they preceded `--ids` on the command line. Now the warning will also show for subscription and will show regardless of where the named arguments appear relative to `--ids`.
- bumps knack version to 0.4.4 to fix issue with argument deprecations.
- ensures `--subscription` parameter appears in `az interactive`. 🥂 
Items remaining …
> `--ids` parameter fixes

- README.md
Moved exit code examples into a table to improve legibility.
> Add table for exit codes

- src/azure-cli-testsdk/azure/cli/testsdk/__init__.py
- src/azure-cli-testsdk/azure/cli/testsdk/patches.py
- src/azure-cli-testsdk/azure/cli/testsdk/preparers.py
- src/command_modules/azure-cli-acs/HISTORY.rst
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
- src/command_modules/azure-cli-acs/setup.py
- src/command_modules/azure-cli-ams/HISTORY.rst
- src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/operations/sp.py
- src/command_modules/azure-cli-ams/setup.py
- src/command_modules/azure-cli-keyvault/HISTORY.rst
- src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/custom.py
- src/command_modules/azure-cli-keyvault/setup.py
- src/command_modules/azure-cli-lab/HISTORY.rst
- src/command_modules/azure-cli-lab/setup.py
- src/command_modules/azure-cli-role/HISTORY.rst
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/commands.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/recordings/test_graph_ownership.yaml
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/test_graph.py
- src/command_modules/azure-cli-role/setup.py
- src/command_modules/azure-cli-servicefabric/HISTORY.rst
- src/command_modules/azure-cli-servicefabric/setup.py
> Graph: support add/remove/list owners on app, sp, and group

- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
It is just a bug in our code. Storage account pool won't work with unmanaged custom image. We already have code to [skip it](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py#L680), but there is one falling through the crack.
I have manually tested it. Because the code change is simple and it is pretty time consuming to test custom images with zero test dependency, I am asking to let this change in w/o automation coverage.
> vmss: avoid producing useless stroage accounts with unmanaged scaleset

- src/azure-cli-core/azure/cli/core/_help.py
CLI now prints extension messages. E.g. "This extension is in preview" or "The behavior of this command has been altered by the following extension: storage-preview".
---
> CLI now prints extension warnings upon '-h'

- .github/CODEOWNERS
- src/command_modules/azure-cli-acs/HISTORY.rst
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
- src/command_modules/azure-cli-acs/setup.py
> Removing Warnings for Cloudshell Proxy

- src/command_modules/azure-cli-role/HISTORY.rst
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/commands.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
- src/command_modules/azure-cli-role/setup.py
> Az ad app grant command

- src/azure-cli-core/azure/cli/core/util.py
This is a workaround for [This bug](https://bugs.python.org/msg322439) in Python 3.7
Fixes #7033
---
> Retry webbrowser.open() after a TypeError

- src/command_modules/azure-cli-vm/HISTORY.rst
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
- src/command_modules/azure-cli-vm/setup.py
> Fixed bug where --no-wait option causes vm resize to crash.

- src/command_modules/azure-cli-rdbms/HISTORY.rst
- src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/_help.py
- src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/_params.py
- src/command_modules/azure-cli-rdbms/setup.py
> Update rdbms help examples text from Gen4 to Gen5

- src/command_modules/azure-cli-acr/HISTORY.rst
- src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_format.py
- src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_params.py
- src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/task.py
- src/command_modules/azure-cli-acr/setup.py
- src/command_modules/azure-cli-appservice/HISTORY.rst
- src/command_modules/azure-cli-appservice/setup.py
ACR Task will now support both commit and pull request source trigger events types.
> ACR: Add Pull Request Event to Task Source Trigger

- src/command_modules/azure-cli-role/HISTORY.rst
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/test_role_commands_thru_mock.py
> ad: clarify the confusion between displayName and service principal name

- src/command_modules/azure-cli-network/HISTORY.rst
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_private_endpoints.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Closes #7536. Deprecates `interface-endpoint` so that the commands continue to appear for now.
---
> [Network] Rename `interface-endpoint` command group to `private-endpoint`

- build_scripts/windows/scripts/build.cmd
Will take it out only if I understand why the workaround was added originally.
> setup: add back the workaround of pinning pycparser==2.18

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/commands/__init__.py
- src/azure-cli-core/azure/cli/core/commands/arm.py
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/latest/test_resource.py
Fixed bug where if update --remove is called with --ids, the correct params aren't passed in subsequent iterations of the update command.
This applies to all generic update commands that use the --ids and --remove (and possibly those that use the--add) parameters.
Fix #6767 
---
> Fixed bug with update --remove --ids

- src/command_modules/azure-cli-vm/HISTORY.rst
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_format.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/disk_encryption.py
Fixes #7410:
`vm encryption enable` shows "- Running .." during long running operations.
`vm encryption --disk-encryption-keyvault`  show outputs table data when `-o table` option is used.
---
> [VM] encryption changes

- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
clarify help to Mounting Azure Storage is only supported on Linux Web Apps and in Windows Containers Web Apps 
```
C:\Users\patle>az webapp config storage-account -h
Group
az webapp config storage-account : Manage a web app's Azure storage account configurations.
(Linux Web Apps and Windows Containers Web Apps Only).
Commands:
add    : Add an Azure storage account configuration to a web app. (Linux Web Apps and Windows
Containers Web Apps Only).
delete : Delete a web app's Azure storage account configuration. (Linux Web Apps and Windows
Containers Web Apps Only).
list   : Get a web app's Azure storage account configurations. (Linux Web Apps and Windows
Containers Web Apps Only).
update : Update an existing Azure storage account configuration on a web app. (Linux Web Apps
and Windows …
```
> add linux only help for webapp config storage-account

- src/command_modules/azure-cli-storage/HISTORY.rst
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
- src/command_modules/azure-cli-storage/setup.py
Storage services should be able to be accessed only with a SAS and relevant endpoint specifiers, as described in https://docs.microsoft.com/azure/storage/common/storage-configure-connection-string , however cli ends up with the following error:
```
$  AZURE_STORAGE_CONNECTION_STRING='BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;SharedConnectionString=xxxx' az storage container list
Connection-string: BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;SharedConnectionString=xxxx, is malformed. Some shell environments require the connection string to be surrounded by quotes.
```
This patch addresses the problem.
---
> Allow connection to storage services with SharedAccessSignature

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
- src/azure-cli-core/setup.py
- src/command_modules/azure-cli-profile/HISTORY.rst
- src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/__init__.py
- src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
- src/command_modules/azure-cli-profile/setup.py
The goal is to support automatic certificate rolls. The tenant must be pre-configured with only accepting certain issuers  such as AME.
Mark it as `do not merge` as we are waiting for a new release of adal to have the capacity. Once it happens, i will update the PR with test coverage.
> auth: support service principal sn+issuer auth

- src/command_modules/azure-cli-appservice/HISTORY.rst
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
This fixes a bug that is preventing users from setting a new backup schedule. Right now, when trying to update the backup schedule with 'az webapp config backup update', if the app does not have a backup schedule configured, then an error will be returned:
Backup configuration not found for site 'site' with slot 'Production'
---
> Webapps backup - fix detection of unset schedule in upade_backup_schedule

- src/command_modules/azure-cli-appservice/HISTORY.rst
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp.yaml
- src/command_modules/azure-cli-appservice/setup.py
fixes #2672 
```
(env) C:\Users\patle\work\azure-cli>az appservice plan create -g patle-sku -n patle-sku --is-linux --sku F1
Free and Shared SKUs are not available for apps running on Linux.
(env) C:\Users\patle\work\azure-cli>az appservice plan create -g patle-sku -n patle-sku --is-linux --sku S1
{
"adminSiteName": null,
"freeOfferExpirationTime": null,
"geoRegion": "West US 2",
"hostingEnvironmentProfile": null,
"hyperV": null,
"id": "/subscriptions/ce678eba-8ab3-4a0c-9610-97fee4ee6b34/resourceGroups/patle-sku/providers/Microsoft.Web/serverfarms/patle-sku",
"isSpot": false,
"isXenon": false,
"kind": "linux",
"location": "West US 2",
"maximumNumberOfWorkers": 10,
"name": "patle-sku",
"numberOfSites": 0,
"perSiteScaling": false,
"provisioningState": "Succeeded",
"reserved": true, …
```
> remove client side sku check for linux ASP

- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_blob_live_scenarios.py
I found the aks nodes are indeed under disk pressure.  And the temp files created by the blob tests are indeed too big for node which only has 30G spaces overall, and I don't see the large temp files are getting recycled in time when test is running in parallel.
So to stabilize the live run, I am disabling the tests, and will let Martin work with Java team to improve the infrastructure and then bring the tests back
//CC @tjprescott @williexu  @anuchandy
> test: disable tests on large blob to avoid disk pressure of live run server

- src/command_modules/azure-cli-storage/HISTORY.rst
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/blob.py
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/hybrid_2018_03_01/test_storage_validators.py
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_validators.py
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/profile_2017_03_09/test_storage_validators.py
---
- specifying uri and sas-token form a new uri with the sas-token.
- validate that both source sas and key are not specified when the source-account is not specified
- deal with oauth incapability to use the token credentials for both source and destination when both the source and destination are the same account.
- query for account key if sas-token not given for source and not in source uri
Closes: https://github.com/Azure/azure-cli/issues/1479
Closes: https://github.com/Azure/azure-cli/issues/7652
> [Storage] fixed bugs and improvements for copy commands

- src/command_modules/azure-cli-role/HISTORY.rst
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
- src/command_modules/azure-cli-role/setup.py
>  graph: output warnings to communicate breaking changes in the near future

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
> [core] maintain the logical subscription name on log-in with msi

- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_blob_live_scenarios.py
I chose to skip it on a01 test launcher which is a more correct place
> [test]: remove the skip on blob live tests

- src/command_modules/azure-cli-appservice/HISTORY.rst
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_slot.yaml
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_slot_swap.yaml
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
> webapps: Updating default node version used during creates

- src/command_modules/azure-cli-vm/HISTORY.rst
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
Validate that `--vnet-name` is not a resource id when creating a VM or VMSS
---
> [vm] Validate network params

- src/command_modules/azure-cli-appservice/HISTORY.rst
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
Minor change to ensure that we do not exit with a key error if the zipdeploy returns a json without a status key. In that case, we want to continue with our retries.
---
> Fixes #7813 - fix keyerror

- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_batch_operations.py
-copies from within the same storage account will use the destination account credentials
> [Storage]removed unecessary use of src sas tokens for copies from same acc

- src/command_modules/azure-cli-storage/HISTORY.rst
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
---
- blob/container list will current page by default for any specified number of `--num-results` through the sdk.
- warn users that list commands will output 5000 in a future release.
> [Storage] fixed incorrect help for list commands and warning for future break

- src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_address_pool.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_auth_cert.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_frontend_ip_private.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_frontend_ip_public.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_frontend_port.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_http_listener.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_http_settings.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_probe.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_rule.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_zone.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_no_wait.yaml
Live test caught regression in #7789. Removed default value for `--min-capacity` since the service fails if both values are provided.
---
> [Network] Fix `min-capacity` default value.

- src/command_modules/azure-cli-vm/HISTORY.rst
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_extension_instance_name.yaml
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_extension_instance_name.yaml
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Can now specify the instance name of an extension when setting an extension on a VM/SS with  `VM/SS extension set`.
---
> [VM/SS] expose --extension-instance-name parameter

- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
Take into account listen_port while doing aks_browse from within the Azure Cloud Shell.
Fix #7724 
---
> [AKS] Take into account listen_port while doing aks_browse from within the Azure Cloud Shell

- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_sas_tokan_url_scenarios.py
---
-Un-hardcode dates for failing live tests.
> [Storage] Use datetime to form expiration time for sas-tokens

- src/command_modules/azure-cli-servicefabric/azure/cli/command_modules/servicefabric/custom.py
change method objects.get_current_user that has been removed from azure.graphrbac now we should use signed_in_user.get
---
> fix get curren user id azure-graphrbac Breaking change fixes #7839

- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
> test: make webjob tests record only as create command is unavailable

- src/command_modules/azure-cli-vm/HISTORY.rst
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_state_modifications.yaml
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Added --force option to force restart of a vm by redeploying it.
---
> [vm] restart: added --force option

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
- src/azure-cli-core/setup.py
> core: support cross tenant resource provisioning for multi-tenant service principal

- src/azure-cli-core/azure/cli/core/_profile.py
It was broken by my commit this morning. Do apologize.
I suggest get this in first as it blocks live run. I will cross check tomorrow morning for why no UT catches this.
> core: fix the error on matching SP creds

- src/azure-cli-testsdk/HISTORY.rst
- src/azure-cli-testsdk/azure/cli/testsdk/checkers.py
- src/azure-cli-testsdk/setup.py
- src/command_modules/azure-cli-network/HISTORY.rst
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_waf_config.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_waf_v2_config.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py
- src/command_modules/azure-cli-network/setup.py
Closes #7528.
Also, adds some validation for the test SDK's "check" method to help diagnose errors in JMESPath queries.
---
> [Network] Implement AppGateway WAF exclusions

- src/command_modules/azure-cli-vm/HISTORY.rst
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_managed_disk.yaml
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
This parameter is used if the source is not a vm (i.e source is is disk blob, managed os disk or os snapshot). It is not currently possible to modify the os disk caching or any attribute of the os disk when creating an image from a VM. See #7648.
---
> [image] create. Add --os-disk-caching parameter.

- azure-cli2017.pyproj
- src/command_modules/azure-cli-appservice/HISTORY.rst
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_constants.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_create_util.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
Fixes #7713,  #7942,  #7812, #7943
---
> webapp: Adding support for az webapp up

- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
@williexu , this is the test debt for #7946  #7923
> test: add test coverage for regression from auth

- src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/_help.py
Extra dash in the create eventhub example
---
> EventHub create: fix extra dash

- src/command_modules/azure-cli-acs/HISTORY.rst
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
- src/command_modules/azure-cli-acs/setup.py
The AAD-related arguments to `az aks create` are supported and no longer considered preview features.
cc: @amanohar @weinong 
---
> [AKS] Remove "(PREVIEW)" from AAD arguments 

- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/custom.py
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/kudu_client.py
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/tests/latest/recordings/test_create_v3_js_webapp_bot.yaml
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/tests/latest/recordings/test_create_v3_webapp_bot.yaml
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/tests/latest/recordings/test_create_v4_js_webapp_bot.yaml
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/tests/latest/recordings/test_prepare_publish_should_raise_cli_error_when_version_is_v4.yaml
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/tests/latest/recordings/test_prepare_publish_with_registration_bot_should_raise_error.yaml
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/tests/latest/recordings/test_prepare_publish_with_unregistered_bot_name_should_fail.yaml
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/tests/latest/test_bot_commands.py
Fixes:
- bug when installing npm dependencies for Node.js bots.
- logging bug in the `az bot publish` command.
---
> Bug fixes for azure-cli-botservice

- src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/_help.py
Fixes #7937. Fixes #7938.
This is also testing that help text PRs made from the GitHub UI are not blocked by our CI.
---
> EventHubs help fixes

- src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
Call `SubResource(id=x)` instead of `SubResource(x)` in list comprehension, since the latter introduced a `TypeError` and prevented `az network lb outbound-rule update` from being used with the `--frontend-ip-configs` flag
This fixes GH-7973
> Fix 7973 - Call SubResource correctly in list comprehension

- src/command_modules/azure-cli-maps/HISTORY.rst
- src/command_modules/azure-cli-maps/azure/cli/command_modules/maps/_params.py
- src/command_modules/azure-cli-maps/azure/cli/command_modules/maps/tests/latest/recordings/test_create_maps_account.yaml
- src/command_modules/azure-cli-maps/azure/cli/command_modules/maps/tests/latest/test_maps_commands.py
- src/command_modules/azure-cli-maps/setup.py
feat) Add support for the `S1` SKU parameter
---
- [x ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).
> feat) add support for "S1" SKU

- src/azure-cli-core/azure/cli/core/__init__.py
> [Core] revert break in core

- src/command_modules/azure-cli-appservice/HISTORY.rst
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp.yaml
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp_multicontainer_create.yaml
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp_multicontainer_slot.yaml
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_slot.yaml
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/sample-compose-slot.yml
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
- src/command_modules/azure-cli-appservice/setup.py
bugfix: az webapp config container now honor --slot parameter
RDBug 14239718
---
> bugfix: multicontainer honors slots

- src/command_modules/azure-cli-storage/HISTORY.rst
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/logging.py
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/services_wrapper.py
---
Change is needed to support changes in displaying diagnostics logs, in new versions (newest, 2.0).
> [Storage] add ability to update version of logging for storage services

- src/command_modules/azure-cli-acs/HISTORY.rst
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/commands.py
ACS will be retired as a standalone service on January 31, 2020.
The changes in this PR lead to this output:
```console
$ az acs -h
Group
az acs : Manage Azure Container Services.
ACS will be retired as a standalone service on January 31, 2020.
If you use the Kubernetes orchestrator, please migrate to AKS by January 31, 2020. This
command group has been deprecated and will be removed in a future release. Use 'aks'
instead.
Subgroups:
dcos           : Commands to manage a DC/OS-orchestrated Azure Container Service.
kubernetes     : Commands to manage a Kubernetes-orchestrated Azure Container Service.
Commands:
browse         : Show the dashboard for a service container's orchestrator in a web browser.
create         : Create a new container service.
...
$ az acs create -h
Command
az acs …
```
> [AKS] mark `az acs` commands as deprecated 

- src/azure-cli-core/azure/cli/core/commands/__init__.py
- src/azure-cli-core/azure/cli/core/tests/test_telemetry.py
> core: fix a bug in parameter name extracting

- Dockerfile
- Dockerfile.spot
Tweaking some of the Dockerfiles in the root of this repository so that:
- We can always inject the desired version of python by providing the flag `--build-arg PYTHON_VERSION="3.7.1"` when running a `docker build`.
- Structuring dependencies in such a way that more will be cached between docker builds. Should speed up local docker build times significantly during inner-dev-loop.
> Fixing Dockerfile nits

- src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py
- Updates ACR help commands for task create and build to include a Windows example.
Closes #6870 (`build task` is deprecated at this point, so I'm leaving the docs as-is, in favor of `task`)
/cc @northtyphoon @djyou @ankurkhemani 
---
> Updates ACR help commands for task create and build

- src/command_modules/azure-cli-cosmosdb/HISTORY.rst
- src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_client_factory.py
- src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_params.py
- src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/custom.py
- src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_keys_database_account.yaml
- src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_list_databases.yaml
- src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/tests/latest/test_cosmosdb_commands.py
- src/command_modules/azure-cli-cosmosdb/setup.py
It allows users to switch their account from multi-master to single master and vice-versa. This change fixes a bug that prevents existing multi-master accounts from updating.
It also includes a fix to a problem that prevented using the database account name and account key when performing database operations.
These changes address the following open issues:
https://github.com/Azure/azure-cli/issues/7969
https://github.com/Azure/azure-cli/issues/7396
https://github.com/Azure/azure-cli/issues/6770
---
> Cosmos DB allow users to enable multi master on update

- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/extension/__init__.py
- src/azure-cli-core/azure/cli/core/extension/operations.py
- src/azure-cli-core/azure/cli/core/extension/tests/latest/test_extension_commands.py
- src/azure-cli-core/azure/cli/core/tests/test_command_registration.py
- src/azure-cli-core/azure/cli/core/tests/test_extension.py
- src/azure-cli-core/azure/cli/core/tests/test_parser.py
- src/azure-cli-core/azure/cli/core/util.py
Changes to the core CLI needed to better support extension development scenarios alongside production scenarios.
Collects sources of development extensions (identified by egg-info instead of dist-info) from a config entry or ENV variable called AZURE_EXTENSION_DEV_SOURCES which accepts a comma-separated list. These core changes will be leveraged in the new `azdev` to streamline development tasks for extension developers.
---
> Support dev extensions

- src/command_modules/azure-cli-acs/HISTORY.rst
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_validators.py
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
This fixes a bug where if the AKS node pool didn't have the expected "nodepool1" name, an `az aks scale` operation would fail silently.
cc: @shanepeckham @zqingqing1
---
> [AKS] Don't require name to scale if there's a single nodepool

- Dockerfile
Fixes #8050
The underlying problem is that we can't control how people have configured their line-endings when developing on Windows. Git, for example, has an option to always checkout Windows line endings and checkin Unix line endings. To account for folks wanting to build images from Docker for Windows, we can protect them by passing anything we write from the local repository through the utility "dos2unix" which is so prevalent it's even in Alpine Linux.
---
> Convert line-endings in generated bash scripts

- src/command_modules/azure-cli-acs/HISTORY.rst
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
- src/command_modules/azure-cli-acs/setup.py
This PR adds the Virtual Node add-on functionality to the az aks enable-addons command.
Virtual Nodes is entering public preview so we wanted to add this command. Previously, we provided
a private extension to do this, so this will replace that.
---
- [ x ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).
- [ x ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).
> Adding virtual-node addon

- src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py
> doc: fix a wrong example in "ad app permission grant"

- Dockerfile
This reverts commit 8c89211372638a0106c4d961e91907dfa9b53c8d.
Investigation is not complete yet, but #8087 doesn't repro when this is reverted. This means that #8050 will need to be reopened.
> Revert "Convert line-endings in generated bash scripts. (#8056)"

- doc/sphinx/azhelpgen/azhelpgen.py
- src/azure-cli-core/azure/cli/core/util.py
- src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/custom.py
- src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/custom.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
Moved get_default_admin_username from vm to core. Updated usages of getpass.getusername to use get_default_admin_username which catches getuser's exception.
Fixes #2100 and when completed will fix #7711.
---
> Moved get_default_admin_username from vm to core

- Dockerfile
Instead of using pipes, use the simpler syntax, where one just passes file names to the tool directly. Hopefully this should avoid the mess that was introduced before and caused #8087.
Fixes #8050
> Normalize line-endings using dos2unix attempt 2.

- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
Updated help.
Added logger warning to inform users that `az vm/ss stop` does not deallocate the VM.
Closes #3026 
---
> [VM/SS] stop.  Clarify VM/SS stop's usage. 

- src/command_modules/azure-cli-consumption/azure/cli/command_modules/consumption/custom.py
When creating a budget on a resource group, the wrong function was being called which was causing a stacktrace at runtime. It's now fixed by calling the correct function create_or_update_by_resource_group_name().
This fixes issue: https://github.com/Azure/azure-cli/issues/7775
---
> Fix: Traceback when creating a budget on a resource group

- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
This PR updates the help commands for `az aks create` and `az aks enable-addons` to show the virtual-node addon in the relevant help section. 
HISTORY.rst isn't updated, as this is just an update to the help output. 
---
> Adding virtual-node to the help message for aks create and enable-addons

- src/command_modules/azure-cli-vm/HISTORY.rst
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_custom_image_name_conflict.yaml
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
- src/command_modules/azure-cli-vm/setup.py
`image create --source` now identifies disk from ID instead of vm, when there is a naming conflict.
Closes #4814 
---
> [image] create --source now identifies disk from ID instead of vm, when there is a naming conflict.

- src/command_modules/azure-cli-acr/HISTORY.rst
- src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_archive_utils.py
- src/command_modules/azure-cli-acr/setup.py
Fixes https://github.com/Azure/azure-cli/issues/8140
@djyou @northtyphoon 
@tjprescott not sure what exactly the guidelines here are for handling errors. Seems to be inconsistent in the code base for `CloudError`. I don't see much harm in treating 5xx and 4xx errors here the same and displaying them to users, since the message itself will contain the relevant information. We could also simply remove the catch for `CloudError` altogether.
---
> ACR: Include the original error from log SAS URL upload

- azure-pipelines.yml
- scripts/release/homebrew/docker/formula_generate.py
- scripts/release/homebrew/docker/formula_template.txt
Before we enable this build to execute on PRs from forks, we need to prevent arbitrary access to upload files into our Azure Storage account. This PR removes those steps, and tweaks the Homebrew build phase to not require any assets that we host. Instead, for Homebrew it relies on archives created by GitHub for an arbitrary ref (not just tags as some previous iterations had.)
> Remove Publishing Steps from Build Pipeline

- src/command_modules/azure-cli-acs/HISTORY.rst
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
- src/command_modules/azure-cli-acs/setup.py
Fixes an issue where this addon config key is unexpectedly lowercased, which causes a `KeyError` we've seen happen a couple times.
---
> [AKS] fix for lowercase logAnalyticsWorkspaceResourceID key 

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/_output.py
- src/azure-cli-core/azure/cli/core/tests/test_output.py
- src/command_modules/azure-cli-configure/HISTORY.rst
- src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/_consts.py
- src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/tests/__init__.py
- src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/tests/latest/__init__.py
- src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/tests/latest/test_configure.py
- src/command_modules/azure-cli-configure/setup.py
Add '--output none'. Add test to make sure configurable options match actual output options.
closes #5667 
---
> [core/configure] add '--output none'.

- .dockerignore
- .gitignore
- scripts/release/debian/Dockerfile
- scripts/release/debian/README.md
- scripts/release/rpm/Dockerfile
- scripts/release/rpm/README.md
- scripts/release/rpm/pipeline.sh
Before these changes, we had scripts defined that would allow us to use containers to execute builds. With my changes, the two are married together, so that the build is defined as part of the container definition. This is the first step in looking to enable any interested party in issuing a command like the following to experiment with changes made in any given PR:
``` bash
docker run -it microsoft/azure-cli:pr7996
```
> Dockerize Linux Builds

- doc/authoring_help.md
Not critical because of the redirects github sets up, but should still be merged.
> Change references to point to new docs repo name.

- src/azure-cli-core/azure/cli/core/commands/arm.py
- src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_exception_handler.py
- src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/recordings/test_metric_alert_v2_scenario.yaml
- src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/latest/test_monitor_metric_alert_scenarios.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/hybrid_2018_03_01/recordings/test_network_ag_http_settings.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/hybrid_2018_03_01/test_network_commands.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_http_settings.yaml
- Fixes #8230: Incomplete `--ids` parameter set throws CLIError instead of ValueError (which created a stack trace)
- Fixes #8224: Ensures `--connection-draining-timeout` works for app gateways created via portal.
- Ensures stack trace not thrown for certain instances (#8228) but this is ultimately a server-side issue.
---
> Small network and monitor fixes.

- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Now that network watcher is configured by default on subscriptions with VNets, the code in these tests to configure the network watcher is unnecessary and in fact causes problems in the live test environment.
---
> [Network] Update Network Watcher tests.

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
- src/command_modules/azure-cli-profile/HISTORY.rst
- src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
> auth: enable tenant level account for managed service identity

- src/command_modules/azure-cli-appservice/HISTORY.rst
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_with_app_insights_key.yaml
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
- src/command_modules/azure-cli-appservice/setup.py
Currently, azure-cli does not support creation or management of app insights. Therefore, there was no simple way to delete the App insights directly created by my tests. Would this be OK or should I look into other ways of deleting the App Insights created by tests (maybe by deleting the resource group, or using appinsights-sdk)
/cc @ahmedelnably @ahmelsayed @panchagnula 
---
> [functionapp] add support for app insights #7890

- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_transformers.py
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_table_main_scenario.yaml
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_table_scenarios.py
As described in #8021, the CLI crashes for binary data because it is decoded from Base64 and then attempted to be displayed on the screen. The fix goes through the returned entities for `az storage entity query` and `az storage entity show` and transforms binary properties into Base64 strings so they can be displayed on the screen.
---
> Fixes #8021, binary data is encoded in Base 64 when returned

- Dockerfile
Fix #8284 
Note: the image size increases from 497MB to 666MB, but extension installation must work so build dep has to stay
> docker: do not remove build dep which might be needed by extension

- src/command_modules/azure-cli-hdinsight/HISTORY.rst
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/_client_factory.py
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/_completers.py
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/_help.py
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/_params.py
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/_validators.py
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/commands.py
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/custom.py
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_application.yaml
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_cluster_kafka.yaml
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_cluster_kafka_with_optional_disk_args.yaml
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_cluster_min_args.yaml
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_cluster_resize.yaml
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_cluster_rserver.yaml
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_cluster_with_cluster_config.yaml
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_cluster_with_component_version.yaml
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_cluster_with_ssh_creds.yaml
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_oms.yaml
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_script_action.yaml
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/recordings/test_hdinsight_usage.yaml
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/tests/latest/test_hdinsight_commands.py
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/util.py
- src/command_modules/azure-cli-hdinsight/setup.py
- Feature update. See [Change](#Change).
- Move test into East US. Re-record tests.
* **BREAKING CHANGE**: `create`, `application create`: Removed the `--virtual-network` and `--subnet-name` parameters.
`create`: Change the `--storage-account` to accept name or id of storage account instead of blob endpoints.
* `create`: added the `--vnet-name` and `--subnet-name` parameters.
* `create`: added support for Enterprise Security Package and disk encryption
* Added `rotate-disk-encryption-key` command
* Added `update` command
---
> [HDInsight] - Support ESP, BYOK and update tags

- azure-pipelines.yml
While trying to setup our private build/release pipelines in devdiv.visualstudio.com, I discovered that it only supports a newer syntax than what this file was originally tooled in. This PR looks to make our build definition portable between both dev.azure.com/azure-public/azcli and devdiv.visualstudio.com
An overview of the difference in syntax can be found here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=vsts&tabs=yaml
> Update Dev-Ops Syntax

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/commands/arm.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Fix #8197. Updates the test to account for both behaviors. `test_network_vnet_ids_query` now passes all scenarios.
---
> Fix JSON input to `--ids` in bash

- src/command_modules/azure-cli-appservice/HISTORY.rst
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/fabric_license
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tunnel.py
- src/command_modules/azure-cli-appservice/setup.py
fixes #8282  #8281, #8280 , #8279
uses fabric ssh library which as a BSD 2-clause license
Added license at  src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/fabric_license
im not sure if that is the correct place top out it.
---
> Bug fix for webapp ssh

- azure-pipelines.yml
Reduce the number of jobs that are executed by the CLI for PR validation. Leave them on for CI jobs.
> Only execute Deb/RPM builds for CI jobs, not PR validation

- src/command_modules/azure-cli-botservice/HISTORY.rst
- src/command_modules/azure-cli-botservice/setup.py
BotService version number conflicts due to GitHub race condition.
> Fix dev branch broken CI

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/util.py
- src/command_modules/azure-cli-cdn/setup.py
Fixes #7815. Quick proof of concept for what an improve `az --version` could look like where we can communicate to users that updates are available. 
TODO:
Example of what output looks like:
```
(env) E:\github>az --version
azure-cli                         2.0.55 *
acr                               2.1.13
acs                               2.3.14 *
advisor                            2.0.0
ams                                0.4.0
appservice                        0.2.11 *
backup                             1.2.1
batch                              3.4.1
batchai                            0.4.6 *
billing                            0.2.0
botservice                         0.1.4 *
cdn                                0.2.0
cloud                              2.1.0
cognitiveservices …
```
> Add update available notification on `az --version`

- src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
> doc: better descriptions for 'create-for-rbac --skip-assignment'

- src/command_modules/azure-cli-acs/HISTORY.rst
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
> [AKS] clarify that --output is ignored for "az aks get-credentials" 

- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/disk_encryption.py
Added logic to make vmss encryption enable safer.
I am not sure if this is necessary, as when I set extensions to None, the service sets vmss.virtual_machine_profile.extension_profile.extensions to an empty list. So it seems this value should always be iterable.
---
> Minor updates to vmss encryption enable.

- scripts/release/homebrew/docker/requirements.txt
In https://github.com/Azure/azure-cli/pull/8324, a new contraint was create that put a ceiling on the version of cryptography that we can support. However, that constraint never made its way to our requirements.txt file in our Homebrew build. Because the largest version at the time was 2.4.x, there wasn't a problem up to a few days ago when 2.5 was finally available for download in our CI environment. Because there is another library that requires cryptography, and doesn't have this constraint, and because we do not use `pip freeze` or `pipenv` to lock our dependencies ahead of time, pip greedily installs the largest version available when it first sees the cryptography requirement then fails later when it first sees the trouble.
> Adding new constraint to Homebrew requirements.txt

- src/command_modules/azure-cli-role/azure/cli/command_modules/role/commands.py
@yugangw-msft this allows GraphRbac to work with both Autorest V3 (as this PR shows) and Autorest V4 (as this PR https://github.com/Azure/azure-cli/pull/8498 shows).
I'd recommend to merge it.
> Simplify operations_tmpl for graphrbac

- src/azure-cli-core/azure/cli/core/_profile.py
- src/command_modules/azure-cli-acr/HISTORY.rst
- src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_docker_utils.py
- src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/commands.py
- src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/repository.py
- src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/latest/test_acr_commands_mock.py
This PR uses a fallback approach to handle different endpoints/routes for Managed vs. Classic registries, rather than proactively ask ARM for the SKU.
When not logged into Azure, runtime commands (i.e., `acr login`, `acr repository`, and `acr helm`) will prompt for username/password to access registry rather than throwing an error for `az login`. This also allows users to provide `--username`/`--password` to access registry without `az login`.
---
> [ACR] Improve error handling for runtime commands when not logged into Azure

- src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/operations/content_key_policy.py
> ams command-module: Bug fix in parser logics for --play-ready-template option input.

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/_profile.py
This is a somewhat academic problem, as this is a developer tool running on localhost and not running across a network. However, according to https://tools.ietf.org/html/rfc6749#section-4.1.1 state should be opaque (e.g. hard to guess.) The easiest way for us to accomodate that is to generate a random value for each login request through the CLI and validate that it is what we get back.
---
> Generate random OAuth state instead of using 'code' as state.

- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/commands/parameters.py
- src/command_modules/azure-cli-network/HISTORY.rst
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/__init__.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_client_factory.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_util.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
Closes #8357.
This PR:
- Moves commands from the ExpressRoute extension into the CLI. (`express-route gateway`, express-route port` command groups)
- Updates azure-cli-core to allow modules to specify multiple extension suppressions, since now Network needs to suppress the DNS and ExpressRoute extensions.
- Converts all outdated tuple syntax for options_list to list or string syntax in the Network module.
- Cleans up repetitive statements with an UpdateContext class pulled from the ExpressRoute extension. This might move into core later.
- Adds missing `--legacy-mode` and `--allow-classic-operations` flags to certain ExpressRoute commands.
---
> [Network] Express Route commands and features

- src/command_modules/azure-cli-resource/HISTORY.rst
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
> Make type-check for deployment template prompts case insensitive

- src/command_modules/azure-cli-botservice/HISTORY.rst
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/__init__.py
- src/command_modules/azure-cli-botservice/setup.py
- Updates version number to 0.1.7
- Supresses the `botservice` extension (0.4.3)
- This functionality is now in the core CLI and should not be used.
- Fixes: #8464
> BotService [0.1.7]: Supress 0.4.3 extension

- src/azure-cli-core/azure/cli/core/tests/test_help_loaders.py
Names that begin with Test are picked up by pytest as tests. However, because this class is not a test, and contains an __init__ method, it pollutes the output of `azdev test` with warnings. Renaming the class fixes this.
---
> Fix issue with TestHelpLoader and pytest

- src/command_modules/azure-cli-appservice/HISTORY.rst
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
Currently, it appears the `az webapp auth update` command prints the arguments the user types which seems to be a mistake.
Closes https://github.com/Azure/azure-cli/issues/8609
---
> Remove debug print statement for 'az webapp auth update'

- src/command_modules/azure-cli-container/HISTORY.rst
- src/command_modules/azure-cli-container/azure/cli/command_modules/container/commands.py
> [Container] Support --no-wait on container start/restart.

- src/command_modules/azure-cli-hdinsight/HISTORY.rst
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/_help.py
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/_params.py
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/_validators.py
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/custom.py
- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/util.py
- src/command_modules/azure-cli-hdinsight/setup.py
- Update `azure-mgmt-hdinsight` SDK version to 0.2.1
- `az hdinsight create`: added the `--storage-account-managed-identity` parameter to support ADLS Gen2 MSI.
---
> [HDInsight] - Support ADLS Gen2 MSI

- src/command_modules/azure-cli-role/HISTORY.rst
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/recordings/test_application_set_scenario.yaml
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/test_graph.py
> `ad app credential reset`: drop the assumption that app's service principal always exists

- src/command_modules/azure-cli-acs/HISTORY.rst
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
- src/command_modules/azure-cli-acs/setup.py
#8408 relied on a new `--address` argument that only appears in `kubectl` v1.13.x and later, so it effectively broke `az aks browse` for most users. This adds fallback logic to call `kubectl` without that argument if need be.
I've tested this with various versions of `kubectl`.
---
> [AKS] handle older kubectl versions in "az aks browse" 

- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/test_custom.py
On global azure, `/usr/local/bin/kubectl` would be downloaded from https://storage.googleapis.com which is ok, while on Azure China, it did not work, this PR would download `/usr/local/bin/kubectl` from https://mirror.azure.cn/kubernetes/kubectl/ if cloud env is set as `AzureChinaCloud`
I have tested this PR by following way:
```
docker build --no-cache -t andyzhangx/azure-cli:mooncake-kubectl -f ./Dockerfile .
docker run -v ${HOME}:/root -it andyzhangx/azure-cli:mooncake-kubectl
root@09feb993f352:/# az aks install-cli
Downloading client to "/usr/local/bin/kubectl" from "https://storage.googleapis.com/kubernetes-release/release/v1.13.4/bin/linux/amd64/kubectl"
Please ensure that /usr/local/bin is in your search PATH, so the `kubectl` command can be found.
root@09feb993f352:/# az cloud set …
```
> add "az aks install-cli" support for Azure China

- doc/authoring_help.md
- scripts/temp_help/help_convert.py
- src/azure-cli-core/azure/cli/core/_help.py
- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/tests/test_help.py
- src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
- tools/automation/cli_linter/rules/help_rules.py
Cli examples should have a supported_profiles field instead of min_profile / max_profile fields.
closes #8354 
Todo:
---
> Add code to handle supported_profiles in examples.

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/extension/__init__.py
- src/azure-cli-core/azure/cli/core/extension/operations.py
- src/command_modules/azure-cli-interactive/HISTORY.rst
- src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/custom.py
---
interactive did not work with dev extensions because methods in core assumed only reg extensions exist
> [interactive] adjust some methods to account for dev extensions

- src/command_modules/azure-cli-resource/HISTORY.rst
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py
> deployment: improve table output

- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
Using the required parameter --address-prefixes
in example makes it clear we can pass in multiple CIDR ranges.   While  --address-prefix  works, it is not documented and is not clear it accepts more than one CIDR range.  The change is for example: "Create new subnet attached to an NSG with a custom route table."
Found here: ### https://docs.microsoft.com/en-us/cli/azure/network/vnet/subnet?view=azure-cli-latest#feedback
---
> Using required parameters in help examples.

- azure-pipelines.yml
- scripts/release/homebrew/docker/formula_generate.py
- scripts/release/homebrew/docker/formula_template.txt
- scripts/release/homebrew/docker/run.sh
- src/azure-cli-core/azure/cli/core/extension/__init__.py
- src/azure-cli-core/azure/cli/core/extension/_resolve.py
- src/azure-cli-core/azure/cli/core/extension/operations.py
- src/azure-cli-core/setup.py
- src/command_modules/azure-cli-extension/setup.py
> Update Homebrew Formula to install in Virtualenv

- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
- src/command_modules/azure-cli-role/HISTORY.rst
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
> ad sp delete: skip role assignment delete if the current account has no subscription

- src/command_modules/azure-cli-backup/HISTORY.rst
- src/command_modules/azure-cli-backup/setup.py
- src/command_modules/azure-cli-dla/HISTORY.rst
- src/command_modules/azure-cli-dla/setup.py
Fixes #6973
This is made possible by @lmazuel's awesome assistance, as well as PRs:
Azure/azure-sdk-for-python#4541
Azure/azure-sdk-for-python#4542
Azure/azure-sdk-for-python#3543
---
> Add tolerance to key management library packages.

- azure-pipelines.yml
Ubuntu Artful reached end of life support on [July 19, 2018](https://wiki.ubuntu.com/Releases). For that reason, we're going to cease publishing new bits for this platform.
Once this PR is merged, I'll need to update our release pipeline as well.
> Stop building Ubuntu:Artful packages

- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
---
-hook does not get added if the callback if never called (happens when no file/blobs are found with a batch upload/download).
-Moving this outside ensures the hook is always added.
> [Storage] move hook addition outside of function def

- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/sample-repo-for-deployment-test/package.json
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/sample-repo-for-deployment-test/process.json
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/sample-repo-for-deployment-test/server.js
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Fix #4680. Creating a public repository under Azure organization is a over-kill, but this PR backs the code for people to rebuild hte repository later.
> test: backup the repository for git deployment testing

- src/command_modules/azure-cli-cosmosdb/HISTORY.rst
- src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/custom.py
- src/command_modules/azure-cli-cosmosdb/setup.py
This change removes the CLIError when users attempt to switch the --enable-multiple-write-locations flag from false to true on Cosmos DB account update.
---
> Allow enable-multiple-write-locations on Cosmos DB account update

- src/command_modules/azure-cli-cdn/HISTORY.rst
- src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/_params.py
- src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/commands.py
- src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/custom.py
Adds `--no-wait` to several `cdn endpoint` commands, as requested in #1528.
---
> [CDN] Add --no-wait support to CDN endpoint commands.

- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
Fixes: https://github.com/Azure/azure-cli/issues/8731
AAD has updated SP secrets to require special characters when the tenant is a Microsoft tenant. 
- A special character is added at random
- I tested creating service principals with each of these secrets and none of them throw an error on creation, however, I don't have an official list of secret characters
---
> [AKS] update SP secret to include special characters for aad

- Dockerfile
Adds zip binaries for use in `az webapp deployment source config-zip` since tgz is not supported
> Add Zip Binaries

- src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/commands.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
With this, CLI will do exactly like the "Grant Permission" button in portal and hence both "Application" and "Delegated" permissions can be handled.
This addresses the lingering ask in #7177 and #8310 
//CC @paolosalvatori @jianghaolu
> graph: support admin consent

- src/command_modules/azure-cli-role/HISTORY.rst
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/recordings/test_native_app_create_scenario.yaml
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/recordings/test_web_app_no_identifier_uris_other_tenants_create_scenario.yaml
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/test_graph.py
- `ad app create` no longer requires `--identifier-uris`
- `--identifier-uris` defaults to `[]` if not provided
- rerecorded tests and added new test
- minor refactoring around identifier-uris and native app creation
---
> ad app create: identifier-uris defaults to [] if not provided

- src/azure-cli-telemetry/setup.py
Fixing our edge build.
Until Microsoft/ApplicationInsights-Python#161 is fixed, we cannot adopt newer versions of this library.
> Apply max version of 0.11.7 to applicationinsights.

- LICENSE
GitHub looks for files named `LICENSE` to determine the kind of license used by a repo.
I have modified the contents for more conformance to standards.
> refactor LICENSE.txt to make github even more happier

- src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
Per suggestion from security team, we need to pull the plug earlier, so unlikely we will wait till 2.1.
I plan to remove it in May
> create-for-rbac: remove the deprecation version on --password

- scripts/release/homebrew/docker/requirements.txt
Adding constraints to applicationsinsights version on Homebrew installer. This should fix the dev branch's build.
> Update Homebrew requirements file with applicationinsights ceiling

- README.md
It is not required to have the LICENSE section in the README.md as we have a separate LICENSE file already.
FYI @marstr
> Remove the LICENSE part from README.md

- src/command_modules/azure-cli-botservice/HISTORY.rst
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/_help.py
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/_params.py
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/commands.py
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/custom.py
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/tests/latest/recordings/test_botservice_create_should_create_registration_bot_without_endpoint.yaml
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/tests/latest/recordings/test_botservice_prepare_deploy_csharp.yaml
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/tests/latest/recordings/test_botservice_prepare_deploy_csharp_fail_if_deployment_file_exists.yaml
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/tests/latest/recordings/test_botservice_prepare_deploy_csharp_no_proj_file.yaml
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/tests/latest/recordings/test_botservice_prepare_deploy_node.yaml
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/tests/latest/recordings/test_botservice_prepare_deploy_node_fail_if_web_config_exists.yaml
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/tests/latest/recordings/test_botservice_prepare_deploy_node_should_fail_with_proj_file_path.yaml
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/tests/latest/recordings/test_botservice_prepare_deploy_should_fail_if_code_dir_doesnt_exist.yaml
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/tests/latest/test_bot_commands.py
- src/command_modules/azure-cli-botservice/setup.py
- Adds `az bot prepare-deploy` _once_ which is to be used before deploying bots using `az webapp`
- Add tests for `az bot prepare-deploy`
- Cleaned up imports order in `test_bot_commands.py`
---
> BotService 0.1.9: add prepare-deploy and update az bot create

- src/azure-cli-core/azure/cli/core/file_util.py
- src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
Fix #8846.
`get_all_help` is used in several different use cases. In many of those cases, you do not want the operation to fail because of an error. You want a non-failing best effort. For self-test, we DO want the command to fail for any help authoring errors. So, this introduces a kwarg (which defaults to False to be a non-breaking change) which lets the developer decide whether authoring errors fail `get_all_help`.  Here's the output of `az self-test` with a problematic command (you'll have to image the pretty colors):
```
(env) E:\github>az self-test
This command has been deprecated and will be removed in a future release.
Running CLI self-test.
Loading all commands and arguments...
Commands loaded OK.
Retrieving all help...
Error occurred loading help!
{'load_help': …
```
> [Core] Improve `get_all_help` and `az self-test`

- src/command_modules/azure-cli-role/HISTORY.rst
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/test_role_commands_thru_mock.py
> role assignment delete: prompt when delete all assignments under the subscription unconditionally

- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
> Re-allow adv networking clusters with only a vnetsubnet

- src/command_modules/azure-cli-network/HISTORY.rst
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
Fixes a bug where running update on an express-route port throws an
unknown attribute error.
---
- [N/A] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).
> Fix az network express-route port update

- src/azure-cli-core/setup.py
- src/command_modules/azure-cli-extension/setup.py
CLI extensions rely on wheel files containing metadata and thus require they be built using wheel 0.29.0 or 0.30.0.  Recent releases are not compatible and updating the CLI results in wheel 0.31.1.  This PR pins the version.
---
> Pin wheel version.

- azure-pipelines.yml
This will enable white-listing of branches for private-preview drops in our edge release pipeline.
> Run CI for all branches in this repo by default.

- src/azure-cli-core/azure/cli/core/commands/transform.py
- src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/tests/latest/test_iot_certificate_commands.py
- src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/tests/latest/test_iot_commands.py
- src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/tests/latest/test_iot_dps_commands.py
Adding a case-insensitive check to ignore adding a key("resourceGroup") in the output.
---
> Restricting duplicate key in output json

- src/azure-cli/setup.py
Having the command module missing from this manifest means poet doesn't discover it's dependencies when it goes to create a Homebrew manifest.
> Fix the dev branch build

- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
This PR updates the help text for the `az aks enable-addons` command to show the correct additional parameter name needed when enabling the Virtual Nodes add-on.
The [CLI reference doc](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-enable-addons) correctly shows this as being `--subnet-name`, not `--subnet_name` as output in the CLI help.
CC: @srrengar
> [AKS] Correct --subnet-name parameter for Virtual Nodes add-on

- .github/CODEOWNERS
- src/command_modules/azure-cli-feedback/azure/cli/command_modules/feedback/tests/latest/test_feedback.py
Fix a bug in one of az feedback's test where the test fails if alias was already installed.
This bug was because of a [change in the signature of `add_extension`](https://github.com/Azure/azure-cli/pull/8946) during development of `az feedback`
---
> Test doesn't crash if user has alias installed.

- src/azure-cli-core/azure/cli/core/tests/test_help.py
> [core] Profiles are no longer hardcoded in help example / supported-profile tests.

- src/azure-cli-core/azure/cli/core/util.py
Closes #7740  
Note:
We should discuss sometime whether or not the CLI should accept python dict string syntax. I am not sure how often this syntax is used by CLI users. 
Moreover, it complicates the logic in `shell_safe_json_parse`. if a string uses python dict single quotes (invalid json) and also has a syntactical error common to both json and dict strings (extra comma), it is hard to know which error is more relevant to the user. As shell_safe_json_parse technically supports both syntaxes.
---
> [core] Improve error message when get_file_json / shell_safe_json_parse fails.

- src/command_modules/azure-cli-storage/HISTORY.rst
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
- src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/test_storage_blob_scenarios.py
- src/command_modules/azure-cli-storage/setup.py
> [Storage] Fix az storage blob generate-sas returns double url-encoded sas

- doc/command_guidelines.md
Add service team guidance for implementing network rule command groups in the CLI. This is the official recommendation after review all current implementations of this feature in the CLI.
> Add guidance for network rules.

- src/command_modules/azure-cli-resource/HISTORY.rst
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/latest/recordings/test_resource_link_scenario.yaml
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/latest/test_resource.py
Fixes #9100.
- Deprecates `--filter-string` in favor of `--filter`
- Deprecates `--link-id` in favor of `--link`
- Deprecates `--target-id` in favor of `--target`
The UX of these commands is still terrible, but I wanted to address the blocking bug first. Revamping the commands may not be worth the effort.
---
> [Resource] Fix some issues with `resource link` commands

- azure-cli2017.pyproj
- src/command_modules/azure-cli-appservice/HISTORY.rst
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/azure_devops_build_iteractive.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/azure_devops_build_provider.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_devops_build_commands.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_devops_build_commands_thru_mock.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/utils.py
- src/command_modules/azure-cli-appservice/setup.py
1. Separate Github repository flow from Azure DevOps repository flow
2. Add Github personal access token authenticated client for Github V3 API request (see [azure-functions-devops-build](https://github.com/Azure/azure-functions-devops-build/commit/3e29984539c6169a384ca3367f16bb6f67bd5c95))
3. Add a feature to check `host.json` and `local.settings.json` files in a Github repository
4. Add a feature to commit `azure-pipelines.yml` to a Github repository
5. Allow Azure DevOps to create a Github service endpoint against a Github repository
6. Allow Github to create a push webhook to Azure DevOps pipelines
1. We now support deploying a powershell application via Azure DevOps pipelines.
2. If the powershell functionapp has an extensions.csproj in its directory, we will do a `dotnet restore` …
> [functionapp] Add Github integration in devops-build commands

- src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_params.py
Before: `Argument 'os_type' has been deprecated and will be removed in a future release. Use 'platform' instead.`
After: `Option '--os' has been deprecated and will be removed in a future release. Use 'platform' instead.`
Relates to #9024
/cc @tjprescott  -  not sure if #9024 should be closed after this; maybe there's a better issue for managing the deprecation information on docs?
/cc @djyou  + @northtyphoon as fyi
---
> ACR: update os_type deprecation info to point to the correct flag

- azure-pipelines.yml
Fixes #9133
This will install the CLI using the MSI built in the previous phase, the run an `az --version` and an `az self-test`
> Add MSI Test Job to ADO

- README.md
I'm thinking we'd want to add the `--rm` flag to clean up the Docker container after usage?
---
> Add --rm to clean up container after exiting.

- src/azure-cli-core/azure/cli/core/commands/__init__.py
Should fix the VSCode CLI extension. Adds comments to identify what this logic is and why it should stick around.
---
> Restore "required_tooling" and "default_name_tooling" metadata.

- src/command_modules/azure-cli-appservice/HISTORY.rst
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
This adds support for `powershell` as a runtime option on Windows for `az functionapp create`.
---
> Add powershell to WINDOWS_RUNTIMES

- azure-pipelines.yml
* Support Ubuntu Disco Dingo
These change were already approved and tested in #9202. This PR applies these changes to the `master` branch so that we can extend the previous release to Ubuntu, Disco Dingo.
> Support Ubuntu Disco Dingo (#9202)

- .vscode/launch.json
- azure-cli2017.pyproj
- src/azure-cli-core/azure/cli/core/commands/__init__.py
- src/azure-cli-testsdk/azure/cli/testsdk/base.py
- src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/_consts.py
- src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/_help.py
- src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/commands.py
- src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/custom.py
- src/command_modules/azure-cli-network/HISTORY.rst
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic_ag_address_pools.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic_app_gateway.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_caching.yaml
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py
- src/command_modules/azure-cli-network/setup.py
- Fixes #9182.
- Revises caching UX:
- Removes `--cache` argument
- Adds `--defer` flag which is equivalent to `--cache write`
- Default behavior of `cached_put` is now the same as `--cache write-through`
- Adds ability to set `cache_ttl` via `az config`
- Default behavior of `cached_get` is to retrieve the object from the cache. If that fails, it will pull from Azure and issue logger.debug. If the cache is stale, it will issue a warning and pull from Azure.
- Renamed "last_touched" to "last_saved" and modified the behavior so the time is only updated when something is saved to the cache. With previously implementation, the object would never be deemed stale.
Example of new UX:
```
az network vnet create -g myrg -n vnet1 --defer
az network subnet create -g myrg --vnet-name vnet1  -n …
```
> Cache UX Revision and Enhancements

- scripts/release/debian/Dockerfile.install_test
- scripts/release/debian/deb_install.sh
- scripts/release/debian/test_deb_install.sh
- scripts/release/debian/test_deb_installer.ps1
/cc @achandmsft @sptramer
This consolidates the instructions that are currently found [here](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest) into a single script. The idea is that we can tell Debian/Ubuntu users to just execute `sudo curl -sL https://aka.ms/InstallAzureCLIDeb | bash`.
Because they will need to use `sudo` to do this, I've added a conspicuous warning that they should try to refrain from sudo executing scripts from sources other than well trusted entities.
> Adding script that consolidates our existing install instructions

- scripts/dependency/requirements.Darwin.external.txt
- scripts/dependency/requirements.Linux.external.txt
- src/command_modules/azure-cli-policyinsights/HISTORY.rst
- src/command_modules/azure-cli-policyinsights/azure/cli/command_modules/policyinsights/_help.py
- src/command_modules/azure-cli-policyinsights/azure/cli/command_modules/policyinsights/_params.py
- src/command_modules/azure-cli-policyinsights/azure/cli/command_modules/policyinsights/_validators.py
- src/command_modules/azure-cli-policyinsights/azure/cli/command_modules/policyinsights/custom.py
- src/command_modules/azure-cli-policyinsights/azure/cli/command_modules/policyinsights/tests/latest/recordings/test_policy_insights.yaml
- src/command_modules/azure-cli-policyinsights/azure/cli/command_modules/policyinsights/tests/latest/test_policyinsights_scenario.py
- src/command_modules/azure-cli-policyinsights/setup.py
Add support for `az policy state list --expand PolicyEvaluationDetails` to query policy evaluation details on the resource.
---
> Add a new argument '--expand' to 'az policy state list'

- src/command_modules/azure-cli-appservice/HISTORY.rst
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_create_util.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
Fix #9132 ,  Fix #9205, Fix #9050
---
> webapp up: Supports resourcegroup and plan as optional arguments & uses local configuration

- src/azure-cli-core/azure/cli/core/tests/test_util.py
- src/azure-cli-core/azure/cli/core/util.py
- src/command_modules/azure-cli-configure/HISTORY.rst
- src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/_params.py
- src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/custom.py
- src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/tests/latest/test_configure.py
CC @limingu  @panchagnula 
To do it in command:
```
az configure --defaults web=web1 --scope local
az configure --list-defaults --scope local
```
To do it in code
```python
with ConfiguredDefaultSetter(cmd.cli_ctx.config, True):
cmd.cli_ctx.config.set_value('defaults', 'group', rg_name)
cmd.cli_ctx.config.set_value('defaults', 'sku', full_sku)
cmd.cli_ctx.config.set_value('defaults', 'plan', asp)
cmd.cli_ctx.config.set_value('defaults', 'location', location)
cmd.cli_ctx.config.set_value('defaults', 'web', name)
```
> az configure: supports configuring local defaults 

- README.md
After #9235, I found some documentation that was out-of-date.
> Fixing Docker image reference in README

- azure-pipelines.yml
It seems that msiexec isn't enough, and that the updated Azure CLI is not being tested after it's installed on the agent. We need to take a look at this, but until we get it working we'll have to manually test the MSI installer.
> Disable MSI Test

- src/command_modules/azure-cli-redis/HISTORY.rst
- src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/custom.py
- src/command_modules/azure-cli-redis/setup.py
This fixes the issue #9287.
As the module `azure-mgmt-redis` expects named args,
https://github.com/Azure/azure-sdk-for-python/blob/400f9b9bc9dd316222e75f636fd7dd6717d46293/azure-mgmt-redis/azure/mgmt/redis/models/export_rdb_parameters_py3.py#L39
```
def __init__(self, *, prefix: str, container: str, format: str=None, **kwargs) -> None:
```
This PR updates the module `azure-cli-redis` 0.4.2 to align with the `azure-mgmt-redis` 6.0.0 .
---
> Fix redis export args

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/adal_authentication.py
> auth: polish common AAD service errors with actionables to overcome

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/extension/operations.py
- src/azure-cli-core/azure/cli/core/tests/test_command_registration.py
- src/azure-cli-core/azure/cli/core/tests/test_parser.py
- src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/custom.py
Fixes #9241.
While the extension add command prevents installing extensions which are not compatible with the core, if an extension is installed and then the CLI is updated such that the extension is no longer compatible, the CLI would still load that extension, resulting in a potential crash.
This PR ensures that the CLI checks the compatibility of each extension during loading and issues a warning and skips that extension if it is no longer compatible.
Example for `az interactive`:
```
(env) D:\github>az interactive
The 'interactive' extension is not compatible with this version of the CLI.
You have CLI core version 2.0.64 and this extension requires a min of 2.0.50.dev0 and max of 2.0.61.
Run `az interactive --update` and try again.
```
Added custom logic to az interactive to add the …
> Skip loading extensions which are not compatible with azure-cli-core version.

- src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/tests/latest/test_ams_streaming_endpoint_scenarios.py
@BrianBlum, I will log an issue to track the investigation, but right now I  need to do it to unblock other PRs which are impacted by these 2 test failures.
I am not able to reproduce it in my dev box with 2.7, and git history has not shown any related change. Same tests are passing at #9317, so more likely a flaky test?
> test: skip 2 ams tests under Python 2.7 to unblock CI

- src/command_modules/azure-cli-role/azure/cli/command_modules/role/_validators.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/commands.py
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/recordings/test_role_assignment_handle_conflicted_assignments.yaml
- src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/test_role.py
Fix #6178 
This could become a general pattern that I can move the code to core, but so far only `role assignment` commands have such a ask, hence I am holding on that.
> role assignment: drop default group name when --scope is provided

- README.md
We're migrating our build pipeline into a different Azure Dev Ops organization. Most of this work is complete, and has been running for a few weeks. This updates the badge on the README.
> Updating CI Badge

- src/command_modules/azure-cli-vm/HISTORY.rst
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
This parameter defaults to standard on the service side if it is not specified.
---
> [ppg] create: `--type` is now optional.

- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
> webapp: az webapp up is not logging the ASP name in the output json

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/_output.py
- src/azure-cli-core/azure/cli/core/tests/test_output.py
Fix bug where --query cannot be used with --output yaml
The yaml formatter fails in this scenario because [knack's `--query` implementation converts the result to an OrderedDict](https://github.com/microsoft/knack/blob/af674bfea793ff42ae31a381a21478bae4b71d7f/knack/query.py#L46). 
closes #9263 
---
> [core] Fix bug where --query cannot be used with --output yaml

- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
> auth: handle unicode in subscription name when under python 2.7

- scripts/release/rpm/Dockerfile.centos
- scripts/release/rpm/Dockerfile.fedora
- scripts/release/rpm/README.md
- scripts/release/rpm/azure-cli.spec
RHEL 8 is changing the way Python is distributed. [See this blog post](https://developers.redhat.com/blog/2018/11/14/python-in-rhel-8/).
This change gives us the flexibility needed to build this RPM in either an EL7 or EL8 environment. To test it, I spun up a RHEL8 VM in Azure and ssh'd in, and ran the centos7 Docker image defined in the repository to make sure there wasn't a regression.
In theory, this change should also let us build and distribute Fedora specific packages that also use Python3 instead of Python2.
Related to #8780
> Make the RPM Spec flexible to EL7 vs EL8

- src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/repository.py
- src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/latest/test_acr_commands_mock.py
Fixes https://github.com/Azure/acr/issues/212
Also remove deprecated classic registry error handling
---
> [ACR] Return patch response directly for acr repository update

- scripts/release/rpm/pipeline.sh
Looks like the RPM spec build is missing a change.
> Fixing Dockerfile name of RPM builder for centos in pipeline definition

- src/command_modules/azure-cli-resource/HISTORY.rst
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/latest/test_resource_custom.py
- src/command_modules/azure-cli-resource/setup.py
Fix #3876
When performing a resource group deployment, if no TTY is available,
a CLIError will be raised detailing the parameters that were not
provided.
I took the liberty of bumping to a new version.
---
> Added Error Message when no TTY is available

- scripts/dependency/requirements.Darwin.external.txt
- scripts/dependency/requirements.Linux.external.txt
- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/_help.py
- src/azure-cli-core/azure/cli/core/commands/__init__.py
- src/azure-cli-core/azure/cli/core/commands/arm.py
- src/azure-cli-core/azure/cli/core/commands/constants.py
- src/azure-cli-core/azure/cli/core/parser.py
- src/azure-cli-core/setup.py
- src/command_modules/azure-cli-acs/HISTORY.rst
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
- src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/commands.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
- src/command_modules/azure-cli-batchai/HISTORY.rst
- src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/commands.py
- src/command_modules/azure-cli-dla/azure/cli/command_modules/dla/_help.py
- src/command_modules/azure-cli-dla/azure/cli/command_modules/dla/commands.py
- src/command_modules/azure-cli-dls/azure/cli/command_modules/dls/__init__.py
- src/command_modules/azure-cli-dls/azure/cli/command_modules/dls/_help.py
- src/command_modules/azure-cli-dls/azure/cli/command_modules/dls/commands.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
- src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
- src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
Closes #5969.
Updates the CLI to use the latest knack.
- <del>Removes the command suggestion code since it now happens in knack</del> Turns out there is CLI-specific logic in the spellchecker so I have to keep the logic in place. It just means that knack now has a limited implementation of this feature (it doesn't handle values)
- Uses the Preview status tag from the latest knack to annotate commands, groups, and arguments in preview. 
- Deprecates and hides BatchAI commands (service is being retired)
- Hides already deprecated ACS commands.
---
> Update CLI to use Knack 0.6.2 (preview mechanism)

- src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/custom.py
HDInsight Fix can not support --ssh-public-key when create cluster
---
> [HDInsight] support ssh_public_key

- src/command_modules/azure-cli-sql/HISTORY.rst
- src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/custom.py
- src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
The issue is that Hyperscale service objectives have null supportedMaxSizes. This is by design, since Hyperscale has unlimited size. However the CLI command isn't handling this correctly.
Fixes #9411
---
> Fixed NoneType iterable error in sql db list-editions --available

- src/azure-cli-core/setup.py
- src/command_modules/azure-cli-acs/setup.py
A new version of paramiko (2.5.0) was released today (10th of June) and it broke the ci, as it requires:
ERROR: paramiko 2.5.0 has requirement cryptography>=2.5, but you'll have cryptography 2.4.2 which is incompatible.
Cryptography can't be upgraded to 2.5.0 as in appservice we have:
'cryptography<2.5',
for some reason.
> fixing version of paramiko

- src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/_help.py
- src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/_params.py
- src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/commands.py
- src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/tests/latest/test_iot_commands.py
Gave bad guidance during the review of #9586. While "renew" and "regenerate" are both used in the CLI, the most common usage is "renew". This PR adopts the more consistent name.
---
> Rename `regenerate-key` to `renew-key`

- src/azure-cli-core/azure/cli/core/tests/test_util.py
- src/azure-cli-core/azure/cli/core/util.py
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py
- src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
Add a few optimizations towards the e2e experience by starting with referencing ARM rest API doc:
1. A full uri is not required. If host is missing, assume ARM endpoint
2. Replace the  `{subscriptionId}` token with real id
Also add telemetry data.
//CC: @achandmsft  
Related issue: #7618
> rest: simplifications on uri and add telemetry

- src/command_modules/azure-cli-hdinsight/HISTORY.rst
- src/command_modules/azure-cli-hdinsight/setup.py
This PR is in order to update azure-hdinsight version which is related to previsous PR[ [HDInsight] support ssh_public_key ](https://github.com/Azure/azure-cli/pull/9512)
---
> [HDInsight] Update hdinsight version related to support ssh-public-key parameter

- src/azure-cli-core/azure/cli/core/commands/__init__.py
Fixes reported issue where, when declaring a command group to be in preview, using commands in that group resulted in a double warning.  
Before (not that the `az group` command group is not actually in preview):
```
(env) D:\github>az group list
This command group is in preview. It may be changed/removed in a future release.
Command group 'group' is in preview. It may be changed/removed in a future release.
```
After:
```
(env) D:\github>az group list
This command group is in preview. It may be changed/removed in a future release.
```
---
- [N/A] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see …
> Small fix for `is_preview` messages.

- src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
We plan to remove the deprecated **az functionapp devops-build** command since it has been renamed to **az functionapp devops-pipeline**.
We are giving a two-week notice to our customers before removal. We will remove the command in the next sprint.
@ahmedelnably 
---
> [functionapp] Add warning to remove functionapp devops-build command

- src/command_modules/azure-cli-botservice/HISTORY.rst
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/_help.py
- src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/custom.py
Add warning message indicating plans to discontinue v3 bot creation support.
_For more information on the discontinued support for creating v3 SDK bots, please read this blog post: **https://blog.botframework.com/2019/06/07/v3-bot-broadcast-message/**_
---
> [BotService]: add deprecation warnings for v3 SDK bot creation

- src/command_modules/azure-cli-appservice/setup.py
fixes #9629, fixes #8364
paramiko has been upgraded, we can use cryptography >= 2.5
---
> crypto >= 2.5

- src/azure-cli-telemetry/setup.py
Trying to package this for [Nixpkgs](https://github.com/NixOS/nixpkgs). And just wanted to submit bump the dependencies here rather than doing text edits as part of the nixpkg installation.
Tested that azure-cli-telemetry's unit tests worked with applicationinsights at 0.11.9 and portalocker at 1.4
Couldn't run through all the tests with `azdev test` but they also fail spectacularly on dev either due to permissions and too many file handles open. 
---
> Bump cli telemetry version bounds

- Dockerfile
In order to run the 'azure-devops' extension from the docker
container, these libraries must installed: libintl and icu-libs.
Without these library using `az artifacts universal publish ...`
would display these error lines:
Universal Packages is currently in preview.
Failed to parse structured output from Universal Packages tooling (ArtifactTool)
Exception: Expecting value: line 1 column 1 (char 0)
Log line: Failed to load @6U, error: Error loading shared library libintl.so.8: No such file or directory
(needed by /root/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_alpine-x64_0.2.99/libcoreclr.so)
Failed to parse structured output from Universal Packages tooling (ArtifactTool)
Exception: Expecting value: line 1 column 1 (char 0)
Log line: Failed to bind to CoreCLR at …
> Added installation of libintl and icu-libs in Dockerfile

- .travis.yml
After the flatten branch was merged, CI is failing because the linter can't pick up the new command module locations. This PR will reduce noise until I can get it fixed.
> Disable linter temporarily

- src/azure-cli-command_modules-nspkg/setup.py
- src/azure-cli-core/setup.py
- src/azure-cli-nspkg/setup.py
- src/azure-cli-telemetry/setup.py
- src/azure-cli-testsdk/setup.py
- src/azure-cli/setup.py
They've been distributed on MacOS using Python 3.7 for quite some time. It's good empirical evidence that we have the capacity to work with Python 3.7.
Note: Because this is targeting the `flatten` branch, we have many fewer places where this notation needs to be added.
> Annotate packages as supporting Python 3.7.

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/extension/operations.py
Fix #9674. Reported by Machine Learning team.
> extension removal: surface io errors as warnings instead of verbose info

- src/azure-cli-core/azure/cli/core/commands/__init__.py
- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/vm/_actions.py
with vm/ss extension image list --latest and vmss create --no-wait
closes #9631. closes #9460 
---
> [compute] Fix minor compute bugs 

- src/azure-cli/setup.py
This was missed during initial migration
> Adding missing package_data entries

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/cosmosdb/_params.py
- src/azure-cli/azure/cli/command_modules/cosmosdb/custom.py
- src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_collection.yaml
- src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/test_cosmosdb_commands.py
This change allows users to specify '0' as the `--default-ttl` of a Cosmos DB collection during create or update to disable TTL. This addresses issue: https://github.com/Azure/azure-cli/issues/7508
---
> Support for disabling TTL on Cosmos DB Container

- scripts/ci/dependency_check.sh
Looks like something didn't get caught Travis CI builds for #9785, and a previously unseen error is occurring for other PRs now.
> Add dep diagnostics

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/appservice/commands.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
\cc @panchagnula @ahmedelnably @yugangw-msft 
Fixes https://github.com/Azure/azure-cli/issues/9767
The expiry tokens, zip file format etc is kept consistent with `azure-functions-core-tools` publish command.
I used `print` statements because we need to show the users information and these are not warnings. And it would be difficult to show a progress bar using `logger`.
Additionally, we don't need to show them any json.
```
Uploading...
============================== 100.0%
Upload to storage complete.
Syncing Triggers...
Deployment completed successfully.
```
---
> Add deploy support to Linux Consumption

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/batch/_validators.py
- src/azure-cli/azure/cli/command_modules/batch/tests/latest/test_batch_commands.py
Fixes #9426
Caused by confusion in difference between create app package parameters https://docs.microsoft.com/en-us/rest/api/batchmanagement/applicationpackage/create and values used when creating the app package reference https://docs.microsoft.com/en-us/rest/api/batchservice/pool/add#applicationpackagereference
---
> Fix app package validator to conform with data plane naming

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/acs/custom.py
Azure/azure-cli#7336 introduced support for az aks browse in cloud shell using a special localhost endpoint to manage opening and closing ports for the underlying port-forward. However, the close was not wrapped in a check of whether the user was actually in cloud shell, causing an ugly (albeit innocuous) error message when users terminated the browse command.
Fixes #7686 
---
> Check for cloud shell before calling localhost endpoint to close port

- README.md
We have some out of date edge-install instructions in our README, cleaning them up for now. I opened #9949 to track adding back publishing to a PEP503 repository as an edge install mechanism.
> Removing out of date edge-build instructions.

- src/azure-cli/azure/cli/command_modules/interactive/color_styles.py
- src/azure-cli/requirements.py2.Darwin.txt
- src/azure-cli/requirements.py2.Linux.txt
- src/azure-cli/requirements.py2.windows.txt
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
We ran into a problem when trying to install `azure-cli` on top of a conda environment.  The problem is that `azure-cli` specifies an old version of `prompt-toolkit`, and installing it forces a downgrade and that breaks the jupyter kernel.
This PR updates the version to the one that is current in conda.
> Update `prompt-toolkit` to 2.0.9

- src/azure-cli-core/azure/cli/core/profiles/_shared.py
- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/_validators.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_create_with_standard_zrs_sku.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_create_with_standard_zrs_sku.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
1. Bug fix on loading storage sku enum   
2. Add back the client end dafaulting for `--single-placement-group`
3. Use newer api-version for `az vm list-skus`, which is needed for users to get `zone details`
```
az vm list-skus --location NorthEurope   --query "[?name=='Standard_E64s_v3'].locationInfo"
{
"location": "northeurope",
"zoneDetails": [
{
"Name": [
"3",
"2",
"1"
],
"capabilities": [
{
"name": "UltraSSDAvailable",
"value": "True"
}
],
"name": null
}
],
"zones": [
"3",
"2",
"1"
]
}
```
> VM: api-version update and related bug fixes 

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_consumption_ragrs_storage_e2e.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_e2e_ragrs_storage.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Fix https://github.com/Azure/azure-cli/issues/9840
Accept Standard_RAGRS in storage account type validation.
@ankitkumarr 
---
> Fix functionapp creation does not accept Standard_RAGRS storage account type

- src/azure-cli-testsdk/azure/cli/testsdk/base.py
- src/azure-cli-testsdk/azure/cli/testsdk/preparers.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_azcopy_scenarios.py
New preparer logic was added that forces self.moniker to be called each time a preparer creates a resource. This was so that self.create_random_name which depends on self.resource_count would be consistent during recording and playback for a ScenarioTest when generating random resource names.
However previously, preparers did not have reason to call self.moniker for LiveScenarioTests, so this bug of self.moniker (defined for AbstractPreparers in azure_devtools ) failing due to no test_resource_count, was never detected.
---
> [Test] Fix bug where self.moniker crashes when self is a LiveScenarioTest.

- src/azure-cli/azure/cli/command_modules/acs/_format.py
Small PR that updates:
1. Get-versions adds the required preview suffix in the `-o table` mode as seen on the cli-extension
2. Get-upgrades fix allows it to run properly in `-o table` mode
---
> update get-version and get-upgrade table formatters

- src/azure-cli/azure/cli/command_modules/network/_help.py
Adjusted the language for the second example of the az network lb create to specifically highlight that the command will create a new lb on a NEW vnet and subnet, and not create a new lb on a specific vnet and subnet that already exists.
---
> Clarifying language for az network lb create

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/cloud.py
- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/profile/__init__.py
- src/azure-cli/azure/cli/command_modules/profile/custom.py
Because OSS RDBMS clients such as psql are community-supported, direct integration of AAD authentication into such clients is not possible. As a convenient workaround, customers can generate access tokens using the `az account get-access-token` command for use with these clients. 
Although the existing command `az account get-access-token` with the `--resource` parameter set to the ossrdbmsResourceId from `az cloud show` would work, it requires the user to type multiple commands and copy/paste the correct resourceId value.
The solution here is to add a new parameter `--resource-type` to `az account get-access-token`. The new parameter takes one of an enumerated set of well-known resource types. These types are then mapped to a resourceId field in cloud_endpoints.
For example, instead of …
> Add --resource-type to az account get-access-token

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/monitor/grammar/MetricAlertCondition.g4
- src/azure-cli/azure/cli/command_modules/monitor/grammar/MetricAlertConditionLexer.py
- src/azure-cli/azure/cli/command_modules/monitor/grammar/MetricAlertConditionListener.py
- src/azure-cli/azure/cli/command_modules/monitor/grammar/MetricAlertConditionParser.py
- src/azure-cli/azure/cli/command_modules/monitor/grammar/MetricAlertConditionValidator.py
- src/azure-cli/azure/cli/command_modules/monitor/grammar/README.md
> Monitor metrics alerts: Support custom namespace. Add guidance for using ANTLR code-gen.

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/cosmosdb/custom.py
Removing warning that disabling multiple write locations will take 24 hours to complete.
---
> Remove warning for Cosmos DB update

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/keyvault/_validators.py
> keyvault: fix the bug in secret set command that igores the expires argument

- src/azure-cli/azure/cli/command_modules/acs/custom.py
Removes an old comment that could be distracting to readers of the code. (The answer to its question was "no": we shouldn't ever use the admin version of the kubeconfig for accessing the dashboard.)
---
> aks: remove outdated comment

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
Starting a Webjob while specifying a slot was not using the slots API, so the slot was being seen as a custom header
---
> Fix the Webjobs command to use slots API when starting a Webjob (#9116)

- src/azure-cli/azure/cli/command_modules/find/_help.py
The examples originally use single quotes, but that doesn't work on Windows cmd.exe:
C:\Users\mikebaz>az find 'arm template'
az: error: unrecognized arguments: template'
Double quotes works correctly.  This may be a lingering issue throughout the commands - this is fixing one that just caught me.
---
> Make "find" examples work on Windows

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/network/_client_factory.py
- src/azure-cli/azure/cli/command_modules/network/_help.py
- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/_validators.py
- src/azure-cli/azure/cli/command_modules/network/commands.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_alias.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_delegation.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone1_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone2_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone3_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone4_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone5_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone6_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone7_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone8_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_private_endpoints.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_private_link_service.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_dns.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
> [Network]: Command Onboard for Private Endpoint and Private Link Service 

- src/azure-cli-core/azure/cli/core/commands/__init__.py
- src/azure-cli/azure/cli/command_modules/configure/_consts.py
Move `DEFAULT_CACHE_TTL` to `src/azure-cli-core/azure/cli/core/commands/__init__.py` to break loop reference between `azure.cli.core` and `azure.cli.command_modules`.
> Fix: azure.cli.core refers to azure.cli.command_modules

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/acs/_client_factory.py
- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/commands.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
Add support of ACR integration, which includes
* Add `--attach-acr <acr-name-or-resource-id>` to `az aks create` command, which allows for attach the ACR to AKS cluster.
* Add `--attach-acr <acr-name-or-resource-id>` and `--detach-acr <acr-name-or-resource-id>` to `az aks update` command, which allows to attach or detach the ACR from AKS cluster.
---
> [AKS] Add support of ACR integration

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/network/_help.py
- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/_template_builder.py
- src/azure-cli/azure/cli/command_modules/network/_validators.py
- src/azure-cli/azure/cli/command_modules/network/commands.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_with_identity.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Fixes #10073 
Fixes #8244 
Fixes #10072 
---
> [Network] Add support for setting identity in Application-Gateway

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/storage/commands.py
Fix #10228
---
Because --auth-mode is not supported for file share now, original --auth-mode argument cannot work and will confuse customers. Remove this argument now and add back when service side is ready.
> [Storage] Fix #10228: Remove --auth-mode in az storage remove

- src/azure-cli/azure/cli/command_modules/storage/operations/account.py
---
Fix  https://msazure.visualstudio.com/One/_workitems/edit/4909160. Because default storage account change is a breaking change, announce a warning first and change in a month. 
> [Storage] add warning to inform default storage account change in future

- src/azure-cli-core/MANIFEST.in
- src/azure-cli-telemetry/MANIFEST.in
- src/azure-cli-testsdk/MANIFEST.in
- src/azure-cli/MANIFEST.in
`pip wheel SDIST_SOURCE` may throw "command 'bdist_wheel' has no
such option 'azure_namespace_package'". We need to include
azure_bdist_wheel.py in MANIFEST.in to avoid such errors.
---
> Put azure_bdist_wheel.py in MANIFEST.in file.

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/ams/_utils.py
- src/azure-cli/azure/cli/command_modules/profile/__init__.py
- src/azure-cli/azure/cli/command_modules/profile/_validators.py
- src/azure-cli/azure/cli/command_modules/role/custom.py
Fix #8840: Convert tenant domain name to GUID if it is not.
> Fix #8840: Tenant domain name is not accepted by Key Vault

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/eventgrid/_help.py
- src/azure-cli/azure/cli/command_modules/eventgrid/_params.py
Port #10376 which has the conflicts hard to resolve; hence I am opening a new one.
CC @ahamad-MS
> EventGrid: Fix help text to point to the right endpoint parameter in Event Subscriptions commands

- src/azure-cli/azure/cli/command_modules/profile/_validators.py
Patch #10418: Fix broken `az login`. Only resolve tenant domain name when `not None`.
> Only resolve tenant domain name when not None

- scripts/release/debian/deb_install.sh
This script is being published via https://aka.ms/InstallAzureCLIDeb and being used in a `curl | bash` way. In order to avoid partial execution in case of incomplete transfers, wrap the whole setup in a bash function which is called when the transfer is completed.
---
> Ensure transfer is complete before execution

- src/azure-cli/azure/cli/command_modules/storage/_client_factory.py
- src/azure-cli/azure/cli/command_modules/storage/_validators.py
- src/azure-cli/azure/cli/command_modules/storage/commands.py
- src/azure-cli/azure/cli/command_modules/storage/operations/account.py
@lmazuel, please let me know whether the patch here is sustainable, otherwise, we need to expose a hook from the pipeline for client applications to redact in anyway they prefer; or any other options you would suggest.
CC @Juliehzl
> POC: redact sensitive storage account info from debug logger

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/access_restrictions.py
- src/azure-cli/azure/cli/command_modules/appservice/commands.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_add.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_add_scm.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_add_service_endpoint.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_remove.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_remove_scm.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_set_complex.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_set_simple.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_show.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_slot.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_access_restriction_add.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_access_restriction_add_scm.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_access_restriction_add_service_endpoint.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_access_restriction_remove.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_access_restriction_remove_scm.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_access_restriction_set_complex.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_access_restriction_set_simple.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_access_restriction_show.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_access_restriction_slot.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_access_restriction_commands.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_access_restriction_commands.py
Fixes #8407
Commands for working with Access Restrictions in Web Apps. You can add and remove IP based and vNet based restrictions as well as inherit main site restrictions in the scm site.
---
> Appservice access restriction cmds

- src/azure-cli-core/azure/cli/core/util.py
```
> az --version
azure-cli                         2.0.73
command-modules-nspkg               2.0.3
core                              2.0.73
nspkg                              3.0.4
telemetry                          1.0.3
testsdk                            0.2.4
```
⬇
```
> az --version
azure-cli                         2.0.73
command-modules-nspkg              2.0.3   << Aligned
core                              2.0.73
nspkg                              3.0.4
telemetry                          1.0.3
testsdk                            0.2.4
```
> Fix alignment in az --version

- src/azure-cli/azure/cli/command_modules/network/_params.py
> [Network] Fix help information for "--timeout" in "az network traffic-manager profile"

- azure-pipelines.yml
Update CI. Increase timeout for Run Automation, Python 2/3
I have seen this timeout error more than once. The normal lasting time for this task is 50+ minutes. Sometimes, it’s over 60 minutes. We use a default timeout, which is 60 minutes. It’s not enough. We are adding more and more test cases, so we need a larger timeout.
```
Run Automation, Python 3
2 error(s), 0 warning(s)
The job running on agent Azure Pipelines 47 has exceeded the maximum execution time of 60. For more information, see https://go.microsoft.com/fwlink/?linkid=2077134
The operation was canceled. 
```
---
> Update CI. Increase timeout for Run Automation, Python 2/3

- src/azure-cli/azure/cli/command_modules/monitor/_help.py
Fix small inconsistency in the help of the cli I encountered in `az monitor metrics`:
Change `list-definition` (wrong) into `list-definitions` (correct)
---
> Az CLI: monitor help: fix references (typo)

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
> webapp: Updating webapp up to not use F1 as the default

- scripts/release/homebrew/docker/formula_template.txt
As requested by homebrew maintainer [here ](https://github.com/Homebrew/homebrew-core/pull/44128#discussion_r323129572), need to use open ssl 1.1
> use openssl 1.1 for homebrew formula

- .travis.yml
This is to unblock CI. I have opened a tracking issue https://github.com/Azure/azure-cli/issues/10721
> ci: disable 'Integration for profiles'

- src/azure-cli/azure/cli/command_modules/vm/_validators.py
Currently the Azure CLI does not work in environments without public internet access when trying to use the managed disk image in `#5` of the _parse_image_argument function. 
This fix ignores the ConnectionError in `#4` when trying to lookup the aliases doc from `githubusercontent.com` and proceeds to `#5`. If `#5` does not match then it will return the error message:
```
Failed to connect to remote source of image aliases. Invalid image "{}". Use a valid image URN, customer image name, customer image id, or VHD blob URI.
See vm create -h for more information on specifying an image.
```
---
> Continue parsing image argument if aliases doc unreachable

- src/azure-cli/azure/cli/command_modules/appservice/_params.py
Adds additional documentation to `--resource-group` and `--name` params clarifying when they need to be provided.
---
> Add required flag to --ids param for connection-string set 

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/network/_params.py
> [Network][BREAKING CHANGE] network vnet subnet list: Fix #10401. `--resource-group` and `--vnet-name` are required now.

- src/azure-cli-testsdk/azure/cli/testsdk/preparers.py
- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/operations/azcopy.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_azcopy_scenarios.py
> Fix #10630: Add --preserve-s2s-access-tier parameter for az storage copy

- src/azure-cli-testsdk/HISTORY.rst
- src/azure-cli-testsdk/azure/cli/testsdk/preparers.py
```
class VMCreateSpecialName(ScenarioTest):
@ResourceGroupPreparer(name_prefix='cli_test_vm create_special_name_')
def test_vm_create_special_name(self, resource_group):
```
Once a time, I miss a '_' in name_prefix, then the following error occurs, which is confusing. It cost me many minutes to find cause. 
```
ERROR: az: error: unrecognized arguments: create_special_name_2xlzojtmqjmvlv4ukdmwj3r7q5oawd5jpz67lvmmrei
usage: az [-h] [--verbose] [--debug]
[--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]
{group} ...
```
Now the error message becomes:
```
azure.cli.testsdk.exceptions.CliTestError: An error caused by the CLI test harness failed the test: Error: Space character in resource group name prefix 'cli_test_vm create_special_name_'
```
, which is more understandable.
--- …
> [Testsdk] Add resource group name prefix validator in resource group preparer

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/vm/_help.py
- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_extension_with_id.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Issue #9592 
Fix bug where users could not set an extension on a VM with --ids.
Changes:
1. Move --name and --extension-instance-name outside Resource Id Arguments group
2. Update --extension-instance-name help text
3. Add example
It's a small breaking change. According to data explorer, --ids usage:
30 day, 13 request
1 day, 9 requests, (I ran tests)
So no problem.
---
> [Compute] vm extension set: Fix bug where users could not set an extension on a VM with --ids

- azure-pipelines.yml
Given Catalina was just released, and High Sierra is now 2 years old, I think we should at least be targeting Mojave
---
> Replace macOS High Sierra with Mojave

- src/azure-cli/azure/cli/command_modules/security/_params.py
Corrected the required parameters documentation for CLI commands for the auto-provisioning-setting to correctly use the --auto-provision values of On/Off rather than on/off (the latter causes an error).
---
> Update _help.py - Capitalization in CLI

- scripts/release/rpm/azure-cli.spec
We use python2 for rpm packages. And the command `python` no longer links to python2 in some newly released linux distros, such as Fedora 31(#10752), RHEL 8 (#10779), need to use the python command with a version.
> fix python in rpm spec

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/role/custom.py
- src/azure-cli/azure/cli/command_modules/role/tests/latest/recordings/test_application_set_scenario.yaml
- src/azure-cli/azure/cli/command_modules/role/tests/latest/test_graph.py
Fix #10807: `az ad app update --id {} --display-name {}` doesn't work
---
> [RBAC] Fix #10807: `az ad app update --id {} --display-name {}` doesn't work

- src/azure-cli/azure/cli/command_modules/acr/_help.py
- src/azure-cli/azure/cli/command_modules/acr/_params.py
- src/azure-cli/azure/cli/command_modules/acr/_utils.py
- src/azure-cli/azure/cli/command_modules/acr/scope_map.py
- src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_token.py
- src/azure-cli/azure/cli/command_modules/acr/token.py
This is to support fast ramp up on repository level of access control. One command will set up all for users. 
Notes:
1. For consistency, I also renamed the `--add` to `--repositories` to be consistent with `az acr token create`, but do let me know if you feel the `--add` is better. 
2. When the existing scope-map is detected, if the actions are the same, CLI will accept it; otherwise it will throw. This is to support command level idempotency that you can run the same command again and again.
> acr: support "--repositories" on token creation command

- README.md
When mounting the home directory the container should not be running without the current user id and group id.
Otherwise all files that azure-cli writes will be written as root - in the container and on the host.
See also [https://medium.com/redbubble/running-a-docker-container-as-a-non-root-user-7d2e00f8ee15](https://medium.com/redbubble/running-a-docker-container-as-a-non-root-user-7d2e00f8ee15)
---
> Updated Readme for non-root docker usage

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/servicefabric/template/linux/template.json
- src/azure-cli/azure/cli/command_modules/servicefabric/template/windows/template.json
az sf cluster fix issue #10916 migrate vmss node disk storage to managed disks for consistency
---
- [ x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).
- making storage for service fabric deployments consistent.
- tested both linux and windows deployment template file changes.
- used https://docs.microsoft.com/en-us/azure/virtual-machines/windows/migrate-to-manage …
> az sf cluster fix issue #10916 migrate vmss node disk storage to managed disks for consistency

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/network/_help.py
- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/commands.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Add features requested in #10747
- Support to configure identity in `az network express-route port identity`
- Support to configure MACsec in `az network express-route port link`
- Support enable/disable admin state in `az network express-route port link`
---
> Add Identity configurability to ExpressRoute Port and MACsec configurability to ExpressRoute Link

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/acr/build.py
- src/azure-cli/azure/cli/command_modules/acr/run.py
> [ACR] Add default value to timeout flag for acr run and acr build

- src/azure-cli-core/azure/cli/core/_help.py
This update informs users about the `az find` command when they use `-h` on a command with examples. The goal is to increase adoption of the command by making more people aware of it. It will print in a format like this:
```
Examples
Redeploy a VM.
az vm redeploy -g MyResourceGroup -n MyVm
Redeploy all VMs in a resource group.
az vm redeploy --ids $(az vm list -g MyResourceGroup --query "[].id" -o tsv)
For more specific examples, use: az find 'az vm redeploy'
```
As this solely modifies help, I haven't updated the HISTORY.rst file.
---
>  Add reference to az find from help

- src/azure-cli/azure/cli/command_modules/acr/_help.py
- src/azure-cli/azure/cli/command_modules/acr/_params.py
- src/azure-cli/azure/cli/command_modules/acr/_utils.py
- src/azure-cli/azure/cli/command_modules/acr/scope_map.py
- src/azure-cli/azure/cli/command_modules/acr/token.py
Addressed review comments by @ankurkhemani in this PR: 
https://github.com/Azure/azure-cli/pull/10864/files
1. Using `TokenStatus` model to fetch permissible values for `status` argument
2. Using `ScopeMapAction` enum instead of hardcoded strings
3. Displaying the duplicate actions entered by users for `acr scope-map update`
4. Changed description for auto-generated scope map "Created by token: \<tokenName\>"
5. Changed the shortened URL redirecting to Official Docs 
(The shortened URL https://aka.ms/acr/repo-permissions must be activated by 11/04 - IMPORTANT)
---
> [ACR] Scope map actions enum, typo fixes and showing duplicate actions to user

- src/azure-cli/azure/cli/command_modules/acr/_utils.py
This will enable task to be run on v1.1.0 (which makes use of Aliases)
So instead of, 
```
az acr run -r MyRegistry --cmd "{{.Run.Registry}}/MyImage" /dev/null
```
You can do
```
az acr run -r MyRegistry --cmd "\$Registry/MyImage" /dev/null
```
---
> default task to v1.1.0 on run cmd

- src/azure-cli/azure/cli/command_modules/acs/_helpers.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_helpers.py
Fixes two bugs:
1. On `az aks update  --api-server-authorized-ip-ranges ""` which is used to disable the resulting input to RP should be [] not ['']
2. On `az aks create` there is a bug on vm sku type naming that prevents clusters from being created 
Both bugs were introduced in a previous (non-released) PR: https://github.com/Azure/azure-cli/pull/10865
---
> fix create and update bugs

- src/azure-cli/azure/cli/command_modules/acr/import.py
Warn users if 'acr import' specifies the source registry twice in --registry and --source.
Expected input
```
(venv) PS C:\Users\oladewal\source\azure-cli\azure-cli> az acr import -n tosinreg2 --source hello-world:v1 -t hello-world:v3 -r "ovatestregistry.azurecr.io" --force
```
Erroneous input with warning added in this pr.
```
(venv) PS C:\Users\oladewal\source\azure-cli\azure-cli> az acr import -n tosinreg2 --source ovatestregistry.azurecr.io/hello-world:v1 -t hello-world:v3 -r "ovatestregistry.azurecr.io"  
Importing image 'ovatestregistry.azurecr.io/ovatestregistry.azurecr.io/hello-world:v1'...
Please ensure that '--source' is a source image and not a fully qualified source, as the source registry was specified via '--registry'
Deployment failed. Correlation ID: …
```
> [acr] import warn users if 'acr import' specifies the source registry twice

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_e2e.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
> Support setting 'Per Site Scaling' on AppService plan create

- src/azure-cli-command_modules-nspkg/setup.py
- src/azure-cli-core/azure/cli/core/_session.py
- src/azure-cli-core/setup.py
- src/azure-cli-nspkg/setup.py
- src/azure-cli-telemetry/setup.py
- src/azure-cli-testsdk/setup.py
- src/azure-cli/setup.py
time.clock() was deprecated in Python 3.3, and removed in Python 3.8. Python 3.8 will be released on 14th October. See [PEP 596](https://www.python.org/dev/peps/pep-0569/) for more info.
Tested locally against Python 3.8.0rc1.
---
> Python 3.8 support

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/profile/custom.py
Polish error when using `az login -u {} -p {}` with Microsoft account, raised in #10979.
The original error message is not clear: 
> Unsupported wstrust endpoint version. Current support version is wstrust2005 or wstrust13.
Incorporate [error message from MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/af5d63820a29786263b22f7ee7702077dccae2e4/msal/application.py#L633-L636).
Current error message:
> Authentication failed due to error of 'Unsupported wstrust endpoint version. Current support version is wstrust2005 or wstrust13.' This typically happens when attempting a Microsoft account, which requires interactive login. Please invoke 'az login' to cross check. More details are available at https://github.com/AzureAD/microsoft-authentication-library-for-pyth …
> [profile] Polish error when using `az login -u {} -p {}` with Microsoft account

- Dockerfile
Updated dockerfile to use Alpine 3.10, involves also upgrading python to version 3.6.9 which is the release of python in 3.6 release that has an available docker image.
---
> Updated Dockerfile to use Alpine 3.10

- doc/use_cli_effectively.md
- src/azure-cli-core/azure/cli/core/adal_authentication.py
- src/azure-cli-core/azure/cli/core/util.py
- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/profile/custom.py
Polish `SSLError` reported in issues #11069, #11068, #10921, #10860, #10272 ...
Changed 3 places:
- `src/azure-cli/azure/cli/command_modules/profile/custom.py` when logging in
- `src/azure-cli-core/azure/cli/core/adal_authentication.py` when retrieving tokens
- `src/azure-cli-core/azure/cli/core/util.py` when making REST requests
To test, replace `<virtual env>\Lib\site-packages\certifi\cacert.pem` with some self-signed certificate like Fiddler's:
```
-----BEGIN CERTIFICATE-----
MIIDsjCCApqgAwIBAgIQP8ptgN302YBPYVf50e6xfDANBgkqhkiG9w0BAQsFADBn
MSswKQYDVQQLDCJDcmVhdGVkIGJ5IGh0dHA6Ly93d3cuZmlkZGxlcjIuY29tMRUw
EwYDVQQKDAxET19OT1RfVFJVU1QxITAfBgNVBAMMGERPX05PVF9UUlVTVF9GaWRk
bGVyUm9vdDAeFw0xODA3MzAxMjQ4MzFaFw0yMTEwMjgxMjQ4MzFaMGcxKzApBgNV …
```
> Polish SSLError

- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/util.py
- src/azure-cli/HISTORY.rst
Fix #10578: `az login` hangs when more than one instances of `az login` are launched at the same time on Windows or WSL
The root cause is that `HTTPServer` can't detect port is in-use on Windows. 
To repro, launch `az login` but do not continue in the browser. Then run `az login` from another terminal and continue with the login. One of the `az` instance will get stuck. 
This PR disables `HTTPServer.allow_reuse_address` so that the correct routine is resumed. 
---
> Fix #10578: `az login` hangs

- .travis.yml
- src/azure-cli-core/setup.py
- tools/setup.py
**Temporarily** lock six version to ~=1.12 until next Sprint due to [upgrade of package six from ~1.12.0 to 1.13.0](https://pypi.org/project/six/#history) in Nov 6, 2019 breaks dependency, which failed Travis CI
Related PR:  #11051
---
> Lock six version to ~=1.12 temporarily to let Travis CI pass

- src/azure-cli/azure/cli/command_modules/acr/custom.py
> acr: warn on using registry name with uppercase

- src/azure-cli/azure/cli/command_modules/acr/check_health.py
This is per ask on supportability that helm is less used and should not block other more important checks. Yes we have `--ignore-errors` flag, but people usually forget it.
> acr: move helm check to the latest step of check-health command

- scripts/release/rpm/Dockerfile.centos
- scripts/release/rpm/azure-cli.spec
- scripts/release/rpm/build.sh
Fixes https://github.com/Azure/azure-cli/issues/11234 https://github.com/Azure/azure-cli/issues/11206
---
> Switch Centos 7 build of azure-cli to use Python 3

- scripts/curl_install_pypi/install
- scripts/curl_install_pypi/install.py
* Fix https://github.com/Azure/azure-cli/issues/11239 , `platform.linux_distribution()` deprecation probelm in Python 3.8
* Add SLES (SUSE Linux Enterprise Server) support
* Fix PEP8 code style error
---
> Fix Python 3.8 platform.linux_distribution() deprecation problem

- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli/HISTORY.rst
Fix #11238: After renaming a subscription, logging in with MSI will result in the same subscription appearing twice
Now **subscription name** is not assembled like `MSI@50342` anymore and is bound to the **subscription ID**. So change `_set_subscriptions` to "key by ID". If subscription is renamed, relogin will cause the previous subscription to be overwritten. 
---
> [Profile] Change MSI login's subscription list to key by ID

- scripts/curl_install_pypi/install
- scripts/curl_install_pypi/install.py
- src/azure-cli/HISTORY.rst
virtualenv==15.0.0 is too old for Python 3.8. One of dependency `platform.linux_distribution()` it used is deprecated.
* Fix https://github.com/Azure/azure-cli/issues/11344
---
> Upgrade virtuelenv to 16.7.7 to support Python 3.8

- src/azure-cli/azure/cli/command_modules/iotcentral/custom.py
---
Remove resource name check for idempotent, resource name check would block the request
> [IotCentral] Remove resource name check for idempotent

- .travis.yml
- src/azure-cli-core/setup.py
- Fix https://github.com/Azure/azure-cli/issues/11127
- One of our dependencies astroid's bug that block CI has been fixed [Update six version](https://github.com/PyCQA/astroid/issues/718), remove unnecessary restriction
---
> Remove six~=1.12.0 restriction in Travis CI since astroid's bug has been fixed

- src/azure-cli/azure/cli/command_modules/storage/operations/account.py
The warning `The default kind for created storage account will change to 'StorageV2' from 'Storage' in the future` is now always shown on creation of a storage account. This warning is only applicable when using no value.
---
> Warn StorageV2 for Storage Account creation only when applicable

- src/azure-cli/azure/cli/command_modules/network/_params.py
Fix https://github.com/Azure/azure-cli/issues/9410
Number of private DNS zones with virtual network auto-registration (--registration-vnes) enabled is 1. If user want to increase this limit, he needs to contact Azure Support
---
> [Network] Update help message for misleading option --registration-vnets in dns zone

- src/azure-cli-testsdk/azure/cli/testsdk/base.py
- src/azure-cli-testsdk/azure/cli/testsdk/checkers.py
Azure doesn't distinguish between upper case and lower case names. Current "equals" checks in testing framework is case_sensitive, which blocks the testing in some circumstances. In this PR, I add a case_sensitive option.
---
> [TestSDK] Add case_sensitive option for checks

- azure-pipelines.yml
- src/azure-cli/HISTORY.rst
All current Ubuntu releases can be checked [here](https://wiki.ubuntu.com/Releases).
Will modify Release Pipeline later to reflect this change.
> Add Ubuntu eoan package

- src/azure-cli/azure/cli/command_modules/vm/_params.py
Added information to use '""' or --% operator in PowerShell for parameters:
--public-ip-address
--nsg
---
> Added information for empty parameter when using Azure CLI in PowerShell

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
The sentence *Deployment endpoint responses with status code* should be *Deployment endpoint responded with status code*
---
> English grammer in deployment warning

- src/azure-cli-core/azure/cli/core/util.py
Fix #11424: `az rest` in AzureChinaCloud fails on missing `active_directory_data_lake_resource_id`
This is because `send_raw_request` can't handle `CloudEndpointNotSetException` when the endpoint is `None`.
> [REST] az rest: fix "endpoint not set" 

- src/azure-cli/azure/cli/command_modules/acr/_help.py
Single quote is included in the value string passed into the command in windows cmd shell. No need to use quote in the command so remove it from the examples.
---
> remove single quote from acr task credential example

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/network/_client_factory.py
- src/azure-cli/azure/cli/command_modules/network/_help.py
- src/azure-cli/azure/cli/command_modules/network/commands.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_service_aliases.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
> [Network]support list service aliases

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/keyvault/_params.py
---
Fix #11084
The help message of `--encoding` param in command `az keyvault secret download` is a little bit confused. 
This is a good example: 
https://github.com/Azure/azure-cli/blob/4f89b707cc28658d41b38a1e03bb240894975f15/src/azure-cli/azure/cli/command_modules/keyvault/_params.py#L256-L258
> Fix #11084: Confusing encoding information

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_probe.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Feature requested in #10027.
---
> [Network] Add --port to application-gateway probe create/update

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/redis/_params.py
- src/azure-cli/azure/cli/command_modules/redis/custom.py
- src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_list_firewall_and_server_link_works.yaml
- src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_list_keys.yaml
- src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_list_works.yaml
- src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_patch_schedule.yaml
- src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_with_mandatory_args.yaml
- src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_with_tags_and_zones.yaml
- src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_with_tlsversion_and_settings.yaml
- src/azure-cli/requirements.py2.Darwin.txt
- src/azure-cli/requirements.py2.Linux.txt
- src/azure-cli/requirements.py2.windows.txt
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
Added preview param `--replicas-per-master` to `az redis create` command and updated azure-mgmt-redis from `6.0.0` to `7.0.0rc1`
---
> Support ReplicasPerMaster property for Redis Cache creation

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/keyvault/_params.py
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_certificate_crud.yaml
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_key.yaml
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_secret.yaml
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_secret_soft_delete.yaml
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
> Fix #8921: Command `az keyvault key/secret/certificate list/list-deleted/list-versions` with parameter `--maxresults` do not work as intended

- src/azure-cli/azure/cli/command_modules/acs/_format.py
This PR fixes the `az aks nodepool list` custom formatter to reference the correct property name for the Kubernetes version, which is `orchestratorVersion`. This ensures that the Kubernetes version actually shows up when nodepools are listed.
---
> Fix property name for Kubernetes version to show in az aks nodepool list

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/storage/_help.py
- src/azure-cli/azure/cli/command_modules/storage/_validators.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_azcopy_scenarios.py
> [Storage] Fix#11043: Support remove whole container/share in az storage remove command

- src/azure-cli-core/azure/cli/core/_profile.py
Survey link is removed from `az login` because printing to `stdout` may break downstream script if `stdout` is used there as the result is no longer a valid JSON.
> revert survey link in login

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_osa_commands.py
Issue https://github.com/Azure/azure-cli/issues/6949#issuecomment-456492503 describes this problem across AKS and Azure Red Hat Openshift when trying to use monitoring when creating clusters.  To clearly distinguish the parameter that Azure Red Hat Openshift needs to create a cluster with monitoring, changing this parameter to `workspace-resource` and providing the context in the help menu when using `az openshift create -h` will allow the user to see what is expected.  The conversation was in PR #10775 and settled on the former but subsequent work will create issues of handling the id with future commands. 
---
> Change flag workspace-resource-id to workspace-resource

- src/azure-cli/azure/cli/command_modules/acr/check_health.py
Removed `re.I` flag since it's better to enforce a case sensitive regex match (`re.I` will have a case insensitive regex match). 
helm2 version:  `Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}`
helm3 version: `version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}`
---
> [ACR] check-health regex fix for Helm3

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
Fix #11586: `az login`'s **list subscription** requests not appearing in server telemetry
Root cause: when [creating `SubscriptionClient`](https://github.com/Azure/azure-cli/blob/465c0e9707d665ad9183522fae40a4b00c5cf7d8/src/azure-cli-core/azure/cli/core/_profile.py#L753-L762), CLI is not calling [`configure_common_settings`](https://github.com/Azure/azure-cli/blob/d1613b0d235327c766e448f89362526e2c15fb90/src/azure-cli-core/azure/cli/core/commands/client_factory.py#L79), where `User-Agent` is configured and additional header `CommandName`, `ParameterSetName` are added.
CLI can't use `azure.cli.core.commands.client_factory.get_mgmt_service_client` like other modules because `SubscriptionClient` has different `__init__` signature, and without a successful login, `get_mgmt_service_client` …
> [login] apply configure_common_settings when creating SubscriptionClient

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/acr/_params.py
- src/azure-cli/azure/cli/command_modules/acr/_utils.py
- src/azure-cli/azure/cli/command_modules/acr/pack.py
---
- Deprecate os parameter completely.
- use task v1.1.0 template for `pack` command
> deprecate os parameter

- CredScanSuppressions.json
- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_e2e.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_hybridconnectionE2E.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_vnetDelegation.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_vnetE2E.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
> [App Service] On webapp up set httpsonly true

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/backup/_help.py
- src/azure-cli/azure/cli/command_modules/backup/_params.py
- src/azure-cli/azure/cli/command_modules/backup/commands.py
- src/azure-cli/azure/cli/command_modules/backup/custom.py
- src/azure-cli/azure/cli/command_modules/backup/custom_base.py
- src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_disk_exclusion.yaml
- src/azure-cli/azure/cli/command_modules/backup/tests/latest/test_backup_commands.py
> [RecoveryServices Backup]Added disk exclusion Feature for IAASVM

- src/azure-cli/azure/cli/command_modules/resource/tests/hybrid_2018_03_01/sample_policy_set.json
- src/azure-cli/azure/cli/command_modules/resource/tests/hybrid_2018_03_01/test_resource.py
Fix the test of test_resource_policyset
issue: #6008
I ran the test again and found that the problem could not be repeated. So I removed @live_only to add this test case to the CI process.
---
> [ARM] Fix the test of test_resource_policyset

- Dockerfile
> [Docker] add libc6-compat in dockerfile

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/appservice/_create_util.py
- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_hybridconnectionE2E.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_vnetDelegation.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_vnetE2E.yaml
> [App Service] Add az webapp up flag for HTML static sites

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/vm/_help.py
- src/azure-cli/azure/cli/command_modules/vm/commands.py
> [Compute] Feature issue #11203 Add new reapply command action for az vm

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/storage/_help.py
- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/_validators.py
- src/azure-cli/azure/cli/command_modules/storage/operations/account.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_update_delete_retention_policy.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
This PR is to support #11423 which add new parameters for account blob service properties to manage delete retention policy
- `--enable-delete-retention`: Indicate whether delete retention policy is enabled for the Blob service.
- `--delete-retention-days`: Indicate the number of days that the deleted blob should be retained. The minimum specified value can be 1 and the maximum value can be 365. It must be provided when enabling delete retention policy or when --enable-delete-retention is true.
---
> [Storage] Added new parameters for account blob service properties to manage delete retention policy

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/role/custom.py
- src/azure-cli/azure/cli/command_modules/role/tests/latest/recordings/test_app_show_exit_code.yaml
- src/azure-cli/azure/cli/command_modules/role/tests/latest/recordings/test_sp_show_exit_code.yaml
- src/azure-cli/azure/cli/command_modules/role/tests/latest/test_graph.py
Fix #11712: `az ad sp show` does not return exit code 3 when the sp does not exist 
**Root cause**: `_resolve_application` and `_resolve_service_principal` don't raise `CLIError` with attribute `status_code=404`
https://github.com/Azure/azure-cli/blob/4d5b1a942e48ce6f8674420f2b18d50f19ed860e/src/azure-cli/azure/cli/command_modules/role/custom.py#L1043
https://github.com/Azure/azure-cli/blob/4d5b1a942e48ce6f8674420f2b18d50f19ed860e/src/azure-cli/azure/cli/command_modules/role/custom.py#L1197
Thus `show_exception_handler` fails to handle the exception: https://github.com/Azure/azure-cli/blob/e47ee99ea2ff1476d3943d81f0403b4dcc638221/src/azure-cli-core/azure/cli/core/commands/arm.py#L755
For manual test, run
```sh
az ad app show --id non-exist-identifierUris
echo %ERRORLEVEL%
az ad app show …
```
> [RBAC] Return exit code 3 if app or sp doesn't exist

- azure-pipelines.yml
Fix: https://github.com/Azure/azure-cli/pull/11798#issuecomment-571942554
tox can find system-wide Python which is Python 2.7 in ubuntu 16.04. 
Even though CI job "**Unit Test for Core and Telemetry**" can run pre-set Python version to test but also run an extra test on system-wide Python which is Python 2.7
So I add environment variable to let tox use the specific Python version I want.
---
> Fix: tox can find system-wide default Python 2.7 in ADO

- scripts/release/homebrew/docker/formula_template.txt
Requested by Homebrew to use python 3.8 in the formulae. Ref: https://github.com/Homebrew/homebrew-core/issues/47274
> python3.8 migration for homebrew

- src/azure-cli/azure/cli/command_modules/acs/_help.py
> Update AKS Create example help text to reflect change of defaults to Standard LB and VMSS

- src/azure-cli/azure/cli/command_modules/backup/_format.py
- src/azure-cli/azure/cli/command_modules/backup/commands.py
> [Backup] Add table output to backup commands

- doc/install_troubleshooting.md
Update solution for https://github.com/Azure/azure-cli/issues/11819 in troubleshooting doc.
> Update fedora install troubleshooting doc

- azure-pipelines.yml
Disable temporary until CredScan task of **Microsoft Security Code Analysis (Preview)** installed.
---
> Chore: disable CredScan job temporary for ADO security concern

- src/azure-cli-core/azure/cli/core/commands/parameters.py
Fix https://github.com/Azure/azure-cli/issues/7112 , feature request about updating --tags help content.
---
> refact: update global --tags help content

- src/azure-cli/azure/cli/command_modules/resource/custom.py
`--method -m` in `az rest`  is self-contradictory. It has default value but is `[Required]`.
```
--method -m      [Required] : HTTP request method.  Allowed values: delete, get, head, options,
patch, post, put.  Default: get.
```
This is fixed by making `method` optional in `rest_call`. 
To test, run 
```
> az rest -h
--method -m                 : HTTP request method.  Allowed values: delete, get, head, options,
patch, post, put.  Default: get.
> az rest --uri https://management.azure.com/
```
> [Rest] Make --method -m optional

- az.completion
- src/azure-cli/HISTORY.rst
Fix #6371
According to [Bach spec](https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion-Builtins.html), 
> **bashdefault**
> Perform the rest of the default Bash completions if the compspec generates no matches.
>
> **default**
> Use Readline’s default filename completion if the compspec generates no matches.
Thus `-o default` enables filename completion and `-o bashdefault` enables environment variable completion.
**argcomplete** currently by default doesn't use `-o bashdefault` for individual commands. After PR https://github.com/kislyuk/argcomplete/pull/284 gets merged, CLI needs to update **argcomplete**'s version so that `src/azure-cli/az.completion.sh` uses the latest **argcomplete**.
Related discussion on https://github.com/kislyuk/argcomplete/issues/67
To …
> [Core] Support filename and environment variable completion

- .github/CODEOWNERS
As mentioned in PR https://github.com/Azure/azure-cli/pull/11795#issuecomment-574464985, add  @shenmuxiaosen and @avanigupta as owners (reviewers) for appconfig command
---
> Chore: add code owner for command module appconfig

- src/azure-cli/requirements.py2.Darwin.txt
- src/azure-cli/requirements.py2.Linux.txt
- src/azure-cli/requirements.py2.windows.txt
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
Bump argcomplete version to 1.11.1 to incorporate https://github.com/kislyuk/argcomplete/pull/284
As instructed by [configuring_your_machine.md](https://github.com/Azure/azure-cli/blob/dev/doc/configuring_your_machine.md#preparing-your-machine), [az.completion.sh](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/az.completion.sh) can use the latest registration script from argcomplete. 
Since `azdev setup -c` doesn't update dependencies, to update the installed argcomplete, we can use `-U --upgrade-strategy eager` to forcely update dependencies while satisfying the requirements. 
```
pip install -U --upgrade-strategy eager -e azure-cli/src/azure-cli-core
```
Then run `source <clone root>/src/azure-cli/az.completion.sh` and verify auto-complete for Azure CLI commands, parameters, …
> [Core] Bump argcomplete version

- src/azure-cli-core/azure/cli/core/tests/test_cloud.py
To repro, activate a Python 3.8 virtual env on Windows and run
```
pytest azure-cli\src\azure-cli-core\azure\cli\core\tests\test_cloud.py::TestCloud::test_get_clouds_concurrent -s
```
`-s` stands for `--capture=no` - no stream redirection. If `-s` is not provided, pytest will simply hang forever. 
With the original `pool_size = 100`, error will rise:
```
azure-cli\src\azure-cli-core\azure\cli\core\tests\test_cloud.py Exception in thread Thread-1:
File "C:\Users\{}\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
self.run()
File "C:\Users\{}\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File …
```
> [Core] Fix test_get_clouds_concurrent on python 3.8 windows

- src/azure-cli/azure/cli/command_modules/sql/_params.py
> Documented sql db restore time format

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/resource/custom.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_resource_group.yaml
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
Fix `az group export` command does not support `--query` and `--output` parameters
Issue: #11658
---
> [ARM] Fix az group export command does not support --query and --output parameters

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/acr/custom.py
- src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_commands.py
- src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_network_rule_commands.py
- src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_task_commands.py
(Resolve #11490 )
1. Add a prompt that asks user "Are you sure you want to delete the registry '$resgistryName'?" for command "az acr delete"
2. Update test cases accordingly. (Add -y to omit confirmation)
**Before:**
```
> az acr delete -n test
To avoid accidental removal, in a future release "az acr delete" will prompt for confirmation
```
**After:**
```
> az acr delete -n test
Are you sure you want to delete the registry 'test'? (y/n):
```
---
> [ACR]: Add a prompt for command "az acr delete" to avoid accidental operation

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/storage/_validators.py
Fix #11415
---
For `--auth-mode login`, we will use login credentials for storage client authentication. 
> [Storage] Fix errors for storage blob update

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/storage/_help.py
- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/azcopy/util.py
- src/azure-cli/azure/cli/command_modules/storage/operations/azcopy.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_azcopy_scenarios.py
Fix #11735
---
Feature description：
1. Upgrade Azcopy 10.3.3 to utilize some new features
2. If no azcopy in target folder or the version is not the same as what we expect, we will install for users.
3. --include-pattern/--include-path/--exclude-pattern/--exclude-path are involved to improve the performance for target operation.
The new parameters have behaviour that is better defined in complex situations (such as
recursion). The * wildcard is supported in the pattern parameters, but not in the path ones.
> [Storage] Upgrade Azcopy for storage copy/remove and blob sync

- scripts/release/homebrew/docker/requirements.txt
- src/azure-cli/requirements.py2.Darwin.txt
- src/azure-cli/requirements.py2.Linux.txt
- src/azure-cli/requirements.py2.windows.txt
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
Remove `pydocumentdb` package dependency, it's replaced by `azure-cosmos`.
See #11879
---
> {Packaging} Remove pydocumentdb

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/commands.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_openshift_monitoring_enable.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_osa_commands.py
Adds `monitor` subgroup to manage Azure Red Hat OpenShift cluster monitoring. 
---
> [Azure Red Hat OpenShift] Add `monitor` subgroup to manage Log Analytics monitoring in Azure Red Hat OpensShift cluster

- src/azure-cli/azure/cli/command_modules/network/custom.py
http listener protocol is auto determined based on cert_data alone,
adding key_vault_secret_id to allow listener protocol to be correctly
set when cert is provided via key vault
Addresses: #11973
---
> {Network} az network application-gateway create: set https when key_vault_secret_id provided

- scripts/release/homebrew/docker/formula_generate.py
To resolve #11839.
Add the method to generate a new homebrew formula based on the latest existing formula in `formula_generate.py`. And it's the default way now.
Invoke `formula_generate.py` with `-b use_template` option to generate the formula using a template which is the old way.
> {Packaging} Generate Homebrew formula by updating existing one by default

- .github/pull_request_template.md
- doc/authoring_command_modules/README.md
The new temaple of PR will be like the following:
---
> {Document} Modify PR template and document

- src/azure-cli/azure/cli/command_modules/acs/custom.py
> add support for the aks 1.16/1.17 in "aks browse" command.

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/sql/custom.py
In case the policy is enabled and there are no audit actions and groups (Was overridden when disabling the policy, or removed while enabling), set the default value
---
> [SQL] az sql db audit-policy: Fix for empty audit actions and groups

- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_consumption_linux_java.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_on_linux_app_service_java.yaml
This PR fixes [release CI failure](https://dev.azure.com/azure-sdk/public/_build/results?buildId=248651&view=logs&j=201a69fb-575c-5f90-d252-d1ed1e360cc3&t=fb98e434-311f-5204-eaf4-065ec0de8a99&l=7730):
```
FAIL: test_functionapp_consumption_linux_java (azure.cli.command_modules.appservice.tests.latest.test_webapp_commands.FunctionAppWithLinuxConsumptionPlanTest)
----------------------------------------------------------------------
No match for the request (<Request (GET) https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Web/geoRegions?sku=Dynamic&api-version=2019-08-01>) was found.
Found 1 similar requests with 1 different matcher(s) :
1 - (<Request (GET) https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/provid …
```
> {functionapp} hotfix: Re-run functionapp tests

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/ams/commands.py
> [AMS] az ams is GA now.

- src/azure-cli/azure/cli/command_modules/vm/custom.py
replace `Pleae` with `Please`, adding missing `s`
> {Compute} Fix typo in error message when attaching unmanaged disk

- src/azure-cli/azure/cli/command_modules/keyvault/_params.py
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_key.yaml
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
Support for #12003
This is a part of BYOK feature. Currently we use a monkey patch to support new value for `--ops` as the latest data-plane SDK is not released. Once the SDK is released, we should deprecate this monkey patch and use SDK struct directly.
---
> [KeyVault] az keyvault key create: add a new value `import` for parameter `--ops`

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/appconfig/_params.py
- src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/export_features.json
- src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/export_features_prop.json
- src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/export_features_yaml.json
> [AppConfig] Revise help message to exclude unsupported key/label filter. 

- scripts/curl_install_pypi/install.py
Fix the incorrect package name on openSUSE Leap/TW to pass native dependencies checking. 
---
> {Packaging} Fix incorrect openssl-devel package name by zypper

- Dockerfile
> {Packaging} add perl in docker

- src/azure-cli/azure/cli/command_modules/acr/_help.py
- src/azure-cli/azure/cli/command_modules/acr/_params.py
- src/azure-cli/azure/cli/command_modules/acr/custom.py
1. Add a new argument '--expose-token' for 'az acr login' to expose access token. 
2. Update help manual accordingly.
Close #9442
**Behavior:**
[specify --expose-token]
[docker command error]
[help manual]
---
> [ACR] Add a new argument '--expose-token' for 'az acr login' 

- src/azure-cli-core/azure/cli/core/util.py
Issue: #10714
Some services executed asynchronously will put useful information into the header, like: location URL, Retry-After, etc. So I print the header of response for `az rest`.
---
> [ARM] az rest: Print the header of response (#10714)

- src/azure-cli/azure/cli/command_modules/acr/_format.py
- src/azure-cli/azure/cli/command_modules/acr/commands.py
Add a table transformer for `az acr task identity show -n Name -r Registry -o table`
(Fix #11868 )
**Before:**
**After:**
[User Assigned Identities]
[System Assigned Identity]
---
> [ACR] Fix the incorrect output of `az acr task identity show -n Name -r Registry -o table`

- scripts/curl_install_pypi/install
sha256sum of install.py changed due to #12000
---
> {Packaging} Update sha256sum of install.py

- src/azure-cli/azure/cli/command_modules/keyvault/_params.py
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_key.yaml
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
Make the behavior consistent with other operations of key.
For operations: `backup/delete/download/list-versions/purge/recover/set-attributes/show/show-deleted`, we should support the following both command types:
1. `az keyvault key {operation} -n {key_name} --vault-name {kv}`
2. `az keyvault key {operation} --id {key_id}`
Also for `az keyvault secret` and `az keyvault certificate`.
---
> [KeyVault] az keyvault key list-versions: support parameter `--id` for specifying keys

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Skip `test_linux_webapp_ssh` on Windows as it will fail at
https://github.com/Azure/azure-cli/blob/c5b5772ab958e755a9649e455a8e6bb17edc6400/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L3282-L3283
and break the test on `pytest` or `azdev test`.
> {AppService} Refine test_linux_webapp_ssh on Windows

- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/tests/hybrid_2018_03_01/recordings/test_storage_create_default_kind.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/hybrid_2018_03_01/test_storage_account_scenarios.py
- src/azure-cli/azure/cli/command_modules/storage/tests/hybrid_2019_03_01/recordings/test_storage_create_default_kind.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/hybrid_2019_03_01/test_storage_account_scenarios.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_create_default_kind.yaml
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
---
**Description**:
The feature is required for a long time. Given there is more and more feature only available in StorageV2 Kind, we need to switch the defualt kind to StoargeV2, which will be align with Powershell, two.
> [Storage] BREAKING CHANGE: az storage account create: Change default storage account kind to StorageV2

- src/azure-cli/azure/cli/command_modules/vm/commands.py
This PR is to fix #12026 
As api now is in stable version, we can remove the preview tag as the requests from service team.
---
> [Compute] `az vm host`: remove preview tag for `vm host` and `vm host group`

- src/azure-cli-core/HISTORY.rst
- src/azure-cli-core/azure/cli/core/_output.py
- src/azure-cli-core/azure/cli/core/tests/test_output.py
- src/azure-cli/azure/cli/command_modules/configure/_consts.py
Fix #7878
Support `--output yamlc` for colorized YAML. The code is copied from Knack's [`format_json_color`](https://github.com/microsoft/knack/blob/master/knack/output.py#L43-L45).
To test, run any command with `--output yamlc`.
---
> [core] Support `--output yamlc` for colorized YAML

- .github/CODEOWNERS
Remove outdated info for eventgrid code owner. PR https://github.com/Azure/azure-cli/pull/12095 is blocked by this. 
I will reach out to Eventgrid Team to find the right person as code owner.
---
> {Misc.} Update CODEOWNERS

- doc/version_management.md
- src/azure-cli-core/azure/cli/core/extension/operations.py
- src/azure-cli/azure/cli/command_modules/botservice/_params.py
- src/azure-cli/azure/cli/command_modules/eventgrid/_params.py
- src/azure-cli/azure/cli/command_modules/monitor/_params.py
- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/vm/_params.py
Updated documentation for our version management policy.
Our next release version will be 2.1.0. Extended the expiration version to 3.0.0. Feel free to remove the deprecated parameters if you think they are no longer needed.
---
> {Packaging} Update version management policy

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2018_03_01/recordings/test_vm_create_state_modifications.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/recordings/test_vm_create_state_modifications.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_auto_create_subnet.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_state_modifications.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
This PR is to fix #10728 
Previously, when user use below command:
`
az vm create -n MyRG --image Win2019Datacenter --size Standard_D2s_v3 --nsg sql-server --vnet-name MyRG-vnet
`
As subnet is not specified here, Azure CLI will generate a default value for it (the format is {VMName}Subnet, in this case, subnet value will be MyRGSubnet).
Azure CLI will try to create/update the vnet with this subnet. So if the vnet exists and already has subnets, the behavior here will be that remove all existing subnets first and then add this new one. This is wrong.
After a discussion, we decide to update the logic to add this new subnet to the list instead of clearing the list. To reduce the impacts to the least, the code change only impact such case: vnet is specified with a existing value and subnet is …
> [Compute] BREAKING CHANGE: Fix #10728: `az vm create`: create subnet automatically if vnet is specified and subnet not exists

- src/azure-cli/azure/cli/command_modules/vm/_actions.py
Issue #11767 
In this command's implementation,
Step 1. use `client.virtual_machine_images.list_publishers(location)` to get publishers
Step 2. use `client.virtual_machine_images.list_offers(location, publisher)` to get offers
Step 2 fails for some publishers retrieved from step 1, then the whole command fails. It's a data inconsistency from service.
Anyway, add try-catch. Use `logger.warning` if exception occurs.
--- …
> [Compute] Increase robustness of vm image list

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/appservice/_help.py
- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/commands.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands_thru_mock.py
> [AppService] Add az webapp|functionapp config ssl create

- doc/command_guidelines.md
- doc/debug/debug_in_vs_code.md
- doc/extensions/authoring.md
- doc/install_linux_prerequisites.md
- src/azure-cli-core/setup.py
- src/azure-cli-nspkg/setup.py
- src/azure-cli-telemetry/setup.py
- src/azure-cli-testsdk/setup.py
> {Packaging} Remove Python 2 in setup and doc

- src/azure-cli-core/azure/cli/core/commands/arm.py
Some service returns lower-cased 'succeeded' provisioning state, such as blueprint assignment create. 
---
> {Core} Use caseless matching for provisioning_state

- src/azure-cli/azure/cli/command_modules/acr/custom.py
Fix #11355 
If there are errors returned by docker command, the CLI exit code will be non-zero 
---
> [ACR] `az acr login`: Throw a CLIError if there are errors returned by docker command

- requirements.txt
Remove `urllib3==1.24.2` from `requirements.txt` as this will let `azdev` install an old version. But CI will install (currently 1.25.8) per
https://github.com/Azure/azure-cli/blob/031525fd06169bed88d9a6547f44885c978b5f25/src/azure-cli/setup.py#L144
There is a breaking change between 1.24 and 1.25. Version 1.25 trims `.` in URL, causing issue https://github.com/Azure/azure-cli/pull/11886#issuecomment-576572788
> {azdev} Remove urllib3==1.24.2 from requirements.txt

- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/_validators.py
---
`Because resource group is not required in commandline, but it is required by SDK. In this way, we need to get resource group by ourselves when no resource group name provided.`
> {Storage} az storage share-rm: Add process_resource_group for resource group

- src/azure-cli/azure/cli/command_modules/signalr/commands.py
> [SignalR] Fix #9904: "Signalr show" fails with unexpected error when the resource doesn't exist

- src/azure-cli/azure/cli/command_modules/acr/custom.py
Raise error only if docker returns non-zero, otherwise print error messages to stderr
---
> [ACR] Fix: `az acr login` wrongly raise error

- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_rewrite_rulesets.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
> [Network] az network application-gateway rewrite-rule create: support url configuration

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_e2e.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Fixes #12258 , #12247, #12229
---
> [AppService] Fix #2258: Fixing issue where trying to create a webapp with certain runtimes was failing

- src/azure-cli/azure/cli/command_modules/network/_params.py
Fix https://github.com/Azure/azure-cli/issues/11406
---
> {Network} Supplemnt help message for --source-address-prefixes and --destination-address-prefixes for nsg rule creation

- doc/sphinx/azhelpgen/azhelpgen.py
- doc/sphinx/cligroup/cligroup.py
sphinx.util.compat is deprecated since 1.6 and removed in 1.7.
http://www.sphinx-doc.org/en/master/extdev/deprecated.html
> {doc} Import Directive from docutils.parsers.rst

- src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py
- src/azure-cli/azure/cli/command_modules/cosmosdb/_params.py
- src/azure-cli/azure/cli/command_modules/cosmosdb/commands.py
- src/azure-cli/azure/cli/command_modules/cosmosdb/custom.py
- src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_sql_stored_procedure.yaml
- src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_sql_trigger.yaml
- src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_sql_user_defined_function.yaml
- src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/test_cosmosdb_commands.py
> [CosmosDB] Add Sql stored procedure, udf and trigger cmdlets

- azure-pipelines.yml
Ubuntu Cosmic has reached end-of-life since July 2019. Ubuntu repo no longer provides the release file for Cosmic. See https://wiki.ubuntu.com/Releases
Will update corresponding ADO tasks as well.
---
> {Packaging/Ubuntu} Remove cosmic packaging

- scripts/release/homebrew/docker/formula_generate.py
[jmespath ](https://github.com/Homebrew/homebrew-core/blob/master/Formula/azure-cli.rb#L486) has upgraded and the patch in Homebrew formula is no longer needed. The patch should be removed when upgrading.
---
> {Packaging/Homebrew} Remove patch when upgrade

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_specialized.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
#12299 
Add parameter
--data-snapshot-luns                     : LUNs (space-delimited) of data disk snapshots.
---
> [Compute] sig image-version: add --data-snapshot-luns

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
Resolves #11893 
[AppService] az functionapp deployment source config-zip: Add an error message if resource group or function name are invalid/don't exist.
---
> [AppService] functionapp: Added error message to deployment command if resource group/function name invalid

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
[functionapp] (az command: functionapp create) This fixes the warning message that appears with `functionapp create` today which cites a `--functions_version` flag but erroneously uses a `_` instead of a `-` in the flag name.
> [functionapp] fixing flag cited in warning message

- src/azure-cli/azure/cli/command_modules/acr/_help.py
- src/azure-cli/azure/cli/command_modules/acr/_params.py
- src/azure-cli/azure/cli/command_modules/acr/commands.py
- src/azure-cli/azure/cli/command_modules/acr/helm.py
`az acr helm install-cli`:  To download and install Helm command-line tool
Close #8974
---
> [ACR] Add new command `az acr helm install-cli`

- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/_validators.py
- src/azure-cli/azure/cli/command_modules/appservice/access_restrictions.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_add_ip_address_validation.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_access_restriction_add_ip_address_validation.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_access_restriction_commands.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_access_restriction_commands.py
> {AppService} Add ip-address validation

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/appservice/_constants.py
- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_on_linux.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_on_linux_app_service_java.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_on_linux_functions_version.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_on_linux_version.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Resolves #11257 
[AppService] az functionapp create: Updated the way linuxFxVersion and container image name were being set for linux function apps.
---
> [AppService] functionapp: Updated container image configuration for Linux apps

- src/azure-cli/azure/cli/command_modules/network/_client_factory.py
- src/azure-cli/azure/cli/command_modules/network/_help.py
- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/_validators.py
- src/azure-cli/azure/cli/command_modules/network/commands.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_nw_flow_log_create.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_nw_flow_log_delete.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_nw_flow_log_show.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_nw_flow_log_update.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_nw_flow_log.py
[Network] az network watcher flow-log create/list/delete/update: add new commands to manage watcher flow log and exposing --location to identify watcher explicitly.
[Network] az network watcher flow-log configure: deprecated.
[Network] az network watcher flow-log show: support --location and --name to get ARM-formatted result, deprecated old formatted output.
---
> [Network] Add new commands to manage flow-log and deprecate old configure command

- src/azure-cli/az.bat
> {Packaging/windows pip} Use local python for az.bat

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_helpers.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_helpers.py
[AKS] aks create: add `--enable-private-cluster`
---
> [AKS] Add support of creating private cluster

- src/azure-cli/azure/cli/command_modules/keyvault/_validators.py
Scenario: 
If I created a vault named `kvTest` and I want to query it this way: `az keyvault show -n kvtest` (lowercase), the CLI will throw an exception: `cli.azure.cli.core.util : The Resource 'Microsoft.KeyVault/vaults/kvtest' not found within subscription.`
But if I specified the `-g`, everything works well.
Why didn't I add tests for this:
Since our test framework always records the lowercase, so it's nearly impossible for me to add tests for this without any change on test framework itself. The code change is minor and I have done the manual test in my local machine, so I think it's fine.
---
> {KeyVault} Fix the case sensitive issue while running commands without specifying resource group name

- src/azure-cli/azure/cli/command_modules/storage/_help.py
> {Storage} az storage file copy start: add examples for snapshot

- doc/private_endpoint_connection_command_guideline.md
- src/azure-cli-core/azure/cli/core/commands/transform.py
- src/azure-cli-core/azure/cli/core/tests/test_util.py
- src/azure-cli-core/azure/cli/core/util.py
- src/azure-cli/azure/cli/command_modules/network/_params.py
Documentation for onboarding Private Endpoint Connection and Private Link Resource.
Fix #11667
---
> {Documentation}Command guideline for private endpoint connection and private link resource

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/_validators.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_default_service.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_nodepool_create_scale_delete.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_validators.py
[AKS] add --nodepool-labels when creating azure kubernetes cluster
[AKS] add --labels when adding a new nodepool to azure kubernetes cluster
---
> [AKS] add support for creation time node labels

- src/azure-cli-core/azure/cli/core/cloud.py
- src/azure-cli-core/azure/cli/core/telemetry.py
- src/azure-cli-core/azure/cli/core/tests/test_telemetry.py
- src/azure-cli/azure/cli/command_modules/configure/_consts.py
- src/azure-cli/azure/cli/command_modules/configure/custom.py
Resolve #12373 
Resolve #12285
---
> {Telemetry} Disable telemetry for some clouds

- src/azure-cli/azure/cli/command_modules/vm/custom.py
Fix error in issues
#11533
#11785
Add None check to vmss.virtual_machine_profile
---
- [ x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).
> {Compute} fix none check when list vmss extension.

- src/azure-cli/azure/cli/command_modules/resource/_params.py
> [ARM] az policy assignment create: Add a description to the `--location` parameter (#11477)

- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/commands/client_factory.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
- src/azure-cli/azure/cli/command_modules/resource/_params.py
- src/azure-cli/azure/cli/command_modules/resource/custom.py
- src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
> [ARM] az group deployment create: Add parameter `--aux-tenants` to support cross tenants (#11765)

- src/azure-cli/azure/cli/command_modules/acr/_help.py
- src/azure-cli/azure/cli/command_modules/acr/commands.py
- src/azure-cli/azure/cli/command_modules/acr/custom.py
> [ACR] add 'private-link-resource list' command

- doc/private_endpoint_connection_command_guideline.md
> {Documentation}fix documenttation

- src/azure-cli/azure/cli/command_modules/cdn/_actions.py
- src/azure-cli/azure/cli/command_modules/cdn/_client_factory.py
- src/azure-cli/azure/cli/command_modules/cdn/_help.py
- src/azure-cli/azure/cli/command_modules/cdn/_params.py
- src/azure-cli/azure/cli/command_modules/cdn/_validators.py
- src/azure-cli/azure/cli/command_modules/cdn/commands.py
- src/azure-cli/azure/cli/command_modules/cdn/custom.py
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_cdn_custom_domain.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_cdn_microsoft_standard_sku.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_cdn_profile_crud.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_cdn_profile_delete_not_found.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_cdn_waf_endpoint_link.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_cdn_waf_managed_rule_set_crud.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_cdn_waf_policy_crud.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_edge_node_crud.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_endpoint_crud.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_endpoint_different_profiles.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_endpoint_load_and_purge.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_endpoint_start_and_stop.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_origin_list_and_show.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_rule_engine_crud.yaml
- src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_waf_scenarios.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
[CDN] Add CDN WAF commands.
---
> [CDN] Add CDN WAF commands

- src/azure-cli-core/azure/cli/core/cloud.py
This is a PR to achieve the request of #12185 .
Currently, only application insight channel endpoint is needed. As the offical document only have China/US cloud's endpoints, so we only add these 2 regions for user as they required.
---
> [Core] az cloud show: add application insights endpoint for China/US cloud

- src/azure-cli/azure/cli/command_modules/vm/_params.py
- src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
- src/azure-cli/azure/cli/command_modules/vm/_validators.py
- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_automatic_repairs_with_health_probe.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_update_automatic_repairs_with_health_extension.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_update_automatic_repairs_with_health_probe.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
This PR is adding support for automatic repairs, which was mentioned in this issue #12319 .
Please note that automatic repairs is still in preview, subscription must be added to the white list for testing.
There are 2 different scenarios if user want to enable automatic repairs for a vmss. A health probe or a health extension must provide. This PR add support for both these 2 scenarios.
**Health probe**
- Enable automatic repairs in az vmss create
`az vmss create -g xiaojianxu -n xxj-vmss-1 --load-balancer xxj-lb--1 --health-probe hp --automatic-repairs-grace-period 30`
> --load-balancer and --health-probe are also required if create vmss with --automatic-repairs-grace-period. The specified --load-balancer and --health-probe must exist, otherwise will report usage error.
- Enable …
> [Compute] az vmss create/update: support automatic repairs

- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_service_principals.py
> [AKS] az aks: Add aad session key support.

- scripts/release/generate_history_notes.py
Github has a rate limit of 60/hr for unauthed request, which may not be enough when querying the PRs of all customer-facing changes commits in a Sprint. Use PAT to increase to 5000/hr.
---
> {Release} Use PAT for github requests

- src/azure-cli-core/setup.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
- tools/setup.py
Fix #12428
Security issues with pyyaml==5.1.1 reported [here](https://nvd.nist.gov/vuln/detail/CVE-2019-20477#vulnCurrentDescriptionTitle).
---
> {Packaging} bump up pyyaml

- doc/configuring_your_machine.md
Additionally, link directly to VS 2015 on download page for old VS versions and update link to VS Python extension page.
I'm not sure what module this goes under. If it needs to change to, e.g., `Misc.`, let me know.
---
> {Document} Fix dead documentation link to Microsoft open source page

- src/azure-cli/azure/cli/command_modules/vm/commands.py
Delay `vm image accept-terms` expiration from `2.2.0` to `3.0.0`.
> {Compute} Delay vm image accept-terms expiration

- scripts/release/rpm/azure-cli.spec
This avoids issues with a user's PATH including other pythons which
might be incompatible.
> {Packaging} Use absolute path for python3 in az script on CentOS/RHEL

- src/azure-cli/azure/cli/command_modules/cdn/commands.py
Fix https://github.com/Azure/azure-cli/issues/12534: [CDN] High module load time
I put a breakpoint at `Lib/site-packages/azure/mgmt/cdn/models/__init__.py:13`:
```py
from ._models_py3 import CacheExpirationActionParameters
```
and by checking the callstack I saw this line was called when loading CDN module. So delay the `import` to when it is really needed.
> {CDN} Delay importing ErrorResponseException

- src/azure-cli-core/azure/cli/core/commands/__init__.py
When a command group is marked as preview:
```py
with self.command_group('vm', compute_vm_sdk, is_preview=True) as g:
```
during invocation, the warning message isn't very accurate - what is invoked is actually a command, not a command group.
```sh
> az vm list
This command group is in preview. It may be changed/removed in a future release.
```
This PR corrects the behavior by removing the inheritance of `preview_info` from command group to command, so that the implicit preview resolution is activated - it searches `preview_info` from the command to its parent group, then the parent group's parent group (if any). Otherwise, preview resolution stops at the command level (L711).
https://github.com/Azure/azure-cli/blob/d7d7a25236f360fbbb3b799b18f46d6cc206cd20/src/azure-cli-core/azure/cli/core …
> {Core} Fix is_preview for commands

- src/azure-cli-core/azure/cli/core/commands/arm.py
Fix the regression in https://github.com/Azure/azure-cli/pull/12154: `provisioning_state.casefold()` raises exception `AttributeError: 'NoneType' object has no attribute 'casefold'` when `provisioning_state` is `None`.
This causes issue to `az sql server wait` since sql server doesn't use `"provisioningState": "Succeeded"`, but `"state": "Ready"`: https://github.com/Azure/azure-cli/issues/12313
Only lower `provisioning_state` when it has value (not `None` or empty string `''`).
Tested with
```
az vm wait --ids {} --created
```
Also, use `lower()` to be consistent with other code.
> {Core} Only lower provisioning_state when it has value

- src/azure-cli/azure/cli/command_modules/network/_params.py
[Network] network watcher flow-log show: fix wrong deprecating info.
---
> [Network] fix wrong deprecating info of flow-log show

- src/azure-cli/azure/cli/command_modules/sql/_params.py
- src/azure-cli/azure/cli/command_modules/sql/commands.py
- src/azure-cli/azure/cli/command_modules/sql/custom.py
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_aad_admin.yaml
- src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
> {SQL} fix az sql server ad-admin update , az sql server ad-admin create calls

- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/_help.py
- src/azure-cli-core/azure/cli/core/commands/__init__.py
- src/azure-cli-core/azure/cli/core/commands/constants.py
- src/azure-cli-core/azure/cli/core/extension/operations.py
Fix #6080, #9903
This PR requires https://github.com/microsoft/knack/pull/171
Azure CLI can now disable color by
- Setting `AZURE_CORE_NO_COLOR` environment variable to `True`
- Using config
```
[core]
no_color=True
```
This PR removes unnecessary Colorama initializations as this is done centrally by Knack. Some command module still initializes Colorama by itself but that won't cause issue. We can gradually remove them in the future. 
Whether color should be enabled can now be retrieved at `cli_ctx.enable_color`. Using this field, the string literal of these two sentences are changed so that they can be shown without color. 
```
For more specific examples, use: az find "az vm list"
Please let us know how we are doing: https://aka.ms/clihats
```
> [Core] Allow disabling color

- src/azure-cli-core/azure/cli/core/_output.py
- src/azure-cli-core/azure/cli/core/tests/test_output.py
Correspond to https://github.com/microsoft/knack/pull/173
The functionality of YAML output is moved to Knack.
> Move yaml output to Knack

- src/azure-cli/azure/cli/command_modules/role/custom.py
Fix #12585: Fix typo in 'Role assignment already exists' message
---
> {RBAC} az ad sp create-for-rbac: Fix #12585: Fix typo in 'Role assignment already exists' message

- src/azure-cli/azure/cli/command_modules/acs/_helpers.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_cluster_with_apiserver_authorized_ranges_then_update.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_private_cluster_then_update.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_helpers.py
[AKS] Fix apiServerAccessProfile when updating --api-server-authorized-ip-ranges
---
Fixes #12587
> [AKS] Fix apiServerAccessProfile when updating --api-server-authorized-ip-ranges

- src/azure-cli/azure/cli/command_modules/acr/_help.py
- src/azure-cli/azure/cli/command_modules/acr/_params.py
- src/azure-cli/azure/cli/command_modules/acr/import.py
- src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_split_registry_and_image.py
Fix #10243
- Modify help and error message to clarify the usage of --source and --registry
- Modify example description
- Optimize code structure
- Add unit test for helper method
**[Behavior]**
Help:
Specify registry in both --source and --registry
---
> [ACR] `az acr import`: Modify help and error message to clarify the usage of --source and --registry

- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
Partially mitigate https://github.com/Azure/azure-cli/issues/6962. MFA cross-tenant trust is still under development by service team.
During `az login`, show warning for MFA error. This happens when the home tenant doesn't require MFA but the other tenants where the user is a guest of do. When getting access token with refresh token for those MFA tenants, CLI gives the raw error which isn't very instructive:
> AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'xxx'.
This PR checks the exception and provides instructions on how to work with MFA tenants:
> Tenant da086fa3-023f-4500-bf56-0f19d3065440 requires Multi-Factor Authentication (MFA). To access this tenant, use 'az login …
> [Profile] az login: Show warning for MFA error

- src/azure-cli/azure/cli/command_modules/vm/_params.py
Automatic repairs feature was already supported in 2.2.0. Service team ask to remove the Preview tag as they will GA at the end of March.
---
> [Compute] az vmss create/update: remove vmss automatic repairs preview tag

- src/azure-cli-core/azure/cli/core/extension/__init__.py
Temporary hotfix the name not found problem when an extension has incompatibility problem.
Fix https://github.com/Azure/azure-cli/issues/12597
CLI and extension currently relies on metadata.json to load/record meta info, which is generated from wheel <= 0.30.0 while packaging. However it's buggy and wheel starting from 0.32.0, has removed the metadata.json as wheel. 
Also, src/index.json use that that to update. and azdev and extension release pipeline
So, we cannot upgrade wheel for now until we decide to migrate metadata infrastructure. It takes a big effort
**That's why I named the PR title "hotfix"**. It involves how we extract metadata from Python package considering breaking changes of wheel. It's a small step of upgrade wheel.
**Additional context**
1. [request for upgrade …
> {Core} hotfix the name of extension of dev type is None if it has incompatibility problem

- doc/extensions/metadata.md
- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/_help.py
- src/azure-cli-core/azure/cli/core/commands/__init__.py
- src/azure-cli-core/azure/cli/core/extension/__init__.py
- src/azure-cli-core/azure/cli/core/extension/operations.py
- src/azure-cli-core/azure/cli/core/extension/tests/latest/test_extension_commands.py
- src/azure-cli-core/azure/cli/core/tests/test_command_registration.py
- src/azure-cli-core/azure/cli/core/tests/test_parser.py
An extension can now be marked as **experimental** by adding `"azext.isExperimental": true` to `azext_metadata.json`:
```jsonc
{
"azext.minCliCoreVersion": "2.0.46",
"azext.isPreview": true,
"azext.isExperimental": true   // Add here
}
```
Same as **preview**, **experimental** appears when 
```sh
> az extension add -n webapp
The installed extension 'webapp' is experimental and not covered by customer support. Please use with discretion.
```
This is newly added, also applies to preview
```sh
> az extension add -s "webapp-0.2.24-py2.py3-none-any.whl"
The installed extension 'webapp' is experimental and not covered by customer support. Please use with discretion.
```
```sh
> az webapp container up -h
This command is from the following extension: webapp
The extension is experimental and not …
```
> [Core] Add experimental tag for extensions

- src/azure-cli/azure/cli/command_modules/storage/operations/account.py
---
Fix issue #12153.
As mentioned in the issue, `--policy` is required parameter when for `create` command, but previous command interface doesn't have required flag for `--policy` as follows:
Currently the command shows up as follows:
> [Storage] az storage account management-policy create: Add [Required] flag for policy

- src/azure-cli-core/azure/cli/core/tests/test_util.py
- src/azure-cli-core/azure/cli/core/util.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
Fix #12566: `az rest` fails to retrieve access token and fail with 
> Get Token request returned http error: 400 and server response: 
> AADSTS65001: The user or administrator has not consented to use the application with ID '04b07795-8ddb-461a-bbee-02f9e1bf7b46' named 'Microsoft Azure CLI'. Send an interactive authorization request for this user and resource
To retrieve an access token for ARM API `--endpoint-resource-manager`, the client needs to provide a resource ID configured by `--endpoint-active-directory-resource-id` representing this API. The resource ID may or may not be the same as the API's URL. 
Say for public cloud `AzureCloud`
https://github.com/Azure/azure-cli/blob/a221f49b9af6cf889cde20bbe4b42956900acd37/src/azure-cli-core/azure/cli/core/cloud.py#L226 …
> [Rest] az rest: Use configured ARM's resource ID

- src/azure-cli/azure/cli/command_modules/role/custom.py
- src/azure-cli/azure/cli/command_modules/role/tests/latest/test_role.py
Resolve https://github.com/Azure/azure-cli/issues/12615
When the user creates an app but doesn't create the corresponding service principal, then does role assignment
```pwsh
$AppRegistrationName = 'myapp0317'
$appId = az ad app create --display-name $AppRegistrationName --reply-urls https://api.loganalytics.io/ --available-to-other-tenants false --query 'appId' --output tsv
$rgName = 'myrg0317'
az group create -n $rgName -l westus
az role assignment create --role Reader --assignee $appId --resource-group $rgName
```
`az role assignment create` fails with
> No matches in graph database for '64ba0967-d3b7-4346-b7b6-803fdea011a4'
This PR polishes the error message to make it more instructive:
> Cannot find user or service principal in graph database for …
> {RBAC} Polich error message for service principal resolution

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_up_commands.py
> [webapp] fix #12509: Remove the tag to az webapp up by default

- src/azure-cli/azure/cli/command_modules/keyvault/_params.py
- src/azure-cli/azure/cli/command_modules/keyvault/commands.py
- src/azure-cli/azure/cli/command_modules/keyvault/custom.py
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_certificate_crud.yaml
- src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
Support for: #11565 
Implemented the following commands:
```
az keyvault certificate backup
az keyvault certificate restore
```
---
> [KeyVault] Support certificate backup/restore

- src/azure-cli/azure/cli/command_modules/appservice/_params.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
Resolves #12627 
[AppService] az functionapp create: Updated --runtime-version help menu and added warning when user specifies --runtime-version for dotnet
---
> [AppService] functionapp: Updated runtime-version help menu and added warning for specifying dotnet runtime-version

- azure-pipelines.yml
- scripts/ci/test_automation.sh
- tools/automation/tests/__init__.py
- tools/automation/tests/main.py
Scenario of modified files:
1. Modified files in `src/azure-cli-core/azure/cli/core` (https://github.com/Azure/azure-cli/pull/12658) - 83mins
2. Modified files in `src/azure-cli-telemetry/` (https://github.com/Azure/azure-cli/pull/12662) - 53mins
3. Modified files in `src/azure-cli/azure/cli/command_modules/network` (https://github.com/Azure/azure-cli/pull/12661) take 11 mins.
4. Modified files in `srv/azure-cli/azure/cli/command_modules/vm` (https://github.com/Azure/azure-cli/pull/12664) take 11 mins.
5. Modified files in `src/azure-cli-testsdk/` (https://github.com/Azure/azure-cli/pull/12666) - 48mins
6. Modified files in vm and network (https://github.com/Azure/azure-cli/pull/12665) - 14mins.
7. Modified files in network and storage (https://github.com/Azure/azure-cli/pull/12676), - 14 …
> {CI} Enable incremental test on commnad modules only

- src/azure-cli-command_modules-nspkg/setup.cfg
- src/azure-cli-core/setup.cfg
- src/azure-cli-nspkg/setup.cfg
- src/azure-cli-telemetry/setup.cfg
- src/azure-cli-testsdk/setup.cfg
- src/azure-cli/setup.cfg
Remove `universal=1` so that PyPI doesn't mark the package as Python 2 supported: 
https://pypi.org/project/azure-cli/#files
azure_cli-2.2.0-py2.py3-none-any.whl (1.5 MB) | Wheel | py2.py3
-- | -- | --
> {Packaging} Remove universal=1

- src/azure-cli/azure/cli/command_modules/acr/_params.py
- src/azure-cli/azure/cli/command_modules/acr/_validators.py
Resolve #12631
Add a validator for argument 'registry_name' to omit login server endpoint suffix.
The validator applies to all `az acr` commands, except `az acr create` and `az acr check-name`. 
**Behavior**
(specify registry name with --registry)
(specify login server with --registry)
(specify login server with --name)
---
> [ACR] Add a validator for argument 'registry_name'

- src/azure-cli-core/azure/cli/core/_help.py
Extension preview/experimental warning is disabled because it can be confusing when displayed together with command or command group preview/experimental warning. See #12556
```sh
> az support services list -h
This command is from the following extension: support
The extension is experimental and not covered by customer support. Please use with discretion.
Command
az support services list : Lists all the Azure services available for support ticket creation.
Always use the service and it's corresponding problem classification(s) obtained
programmatically for support ticket creation. This practice ensures that you always have the
most recent set of service and problem classification Ids.
Command group 'support services' is in preview. It may be changed/removed in a future
release.
``` …
> {Core} Disable extension preview/experimental warning

- src/azure-cli/azure/cli/command_modules/storage/_params.py
- src/azure-cli/azure/cli/command_modules/storage/operations/azcopy.py
- src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_azcopy_scenarios.py
> [Storage] az storage copy: Add parameter --content-type to fix#6466

- src/azure-cli-core/azure/cli/core/tests/test_util.py
- src/azure-cli-core/azure/cli/core/util.py
[REST] az rest: do not retrieve token if `Authorization` header is already provided
[REST] az rest: support custom `User-Agent`
---
Refine #12117, #12580 
Also, when showing `Authorization` in the http dump, trim at least half of the token but keep at most 20 characters. For example, 
```
> az rest --uri /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/?api-version=2019-07-01 --headers "Authorization=abcdefg" --verbose
'Authorization': 'abc...'
```
```
> az rest --uri /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/?api-version=2019-07-01 --verbose
'Authorization': 'Bearer eyJ0eXAiOiJKV...'
```
Add more tests.
> {REST} az rest: Refinement

- src/azure-cli/azure/cli/command_modules/ams/_help.py
- src/azure-cli/azure/cli/command_modules/ams/_params.py
- src/azure-cli/azure/cli/command_modules/ams/operations/content_key_policy.py
- src/azure-cli/azure/cli/command_modules/ams/tests/latest/test_ams_content_key_policy_scenarios.py
Issue #12469 
When adding the ASK key to Fairplay content-key-policy CLI is expecting a bytearray when it should be expecting a 32 character hexadecimal string.
Reverting the changes made in this [PR ](https://github.com/Azure/azure-cli/pull/11240)
---
> [AMS] Fix #12469: adding Fairplay content-key-policy fails due to problems with 'ask' parameter

- src/azure-cli-core/azure/cli/core/commands/progress.py
- src/azure-cli-core/azure/cli/core/tests/test_progress.py
- src/azure-cli-core/setup.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
Fix #12283: Please support newer versions of humanfriendly
Tested with humanfriendly 8.0, and `az deployment group create -g {} --template-file template.json --parameters "@parameters.json"` works as expected:
```
- Running ..  
```
> {Core} Relax humanfriendly dependency

- src/azure-cli-core/azure/cli/core/commands/client_factory.py
- src/azure-cli-core/azure/cli/core/tests/test_util.py
- src/azure-cli-core/azure/cli/core/util.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
Extract `User-Agent` generation to `get_az_user_agent` so that PR https://github.com/Azure/azure-cli/pull/12717 can also apply to `az rest`.
The logic to append custom `User-Agent` via `AZURE_HTTP_USER_AGENT` env var is removed from mgmt and data client factory, as this is already [handled by msrest](https://github.com/Azure/msrest-for-python/blob/4cc8bc84e96036f03b34716466230fb257e27b36/msrest/pipeline/universal.py#L70) and causes duplication:
```pwsh
> $env:AZURE_HTTP_USER_AGENT='myua'
> az group list --debug
msrest.http_logger :     'User-Agent': 'python/3.8.2 (Windows-10-10.0.18362-SP0) msrest/0.6.1
1 myua msrest_azure/0.6.2 azure-mgmt-resource/8.0.1 Azure-SDK-For-Python AZURECLI/2.2.0 myua'
```
Note that `myua` appeared twice. 
On the other hand, this logic is added to `az rest` to …
> {Core} Extract User-Agent generation to get_az_user_agent

- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli-core/azure/cli/core/tests/test_profile.py
- src/azure-cli-core/setup.py
- src/azure-cli/setup.py
Refine and unify the warning messages for 
> The following tenants require Multi-Factor Authentication (MFA). Use 'az login --tenant TENANT_ID' to explicitly login to a tenant.
> da086fa3-023f-4500-bf56-0f19d3065440 'Inbarck Labs'
> ...
> The following tenants doesn't contain accessible subscriptions. Use 'az login --allow-no-subscriptions' to have tenant level access.
> 3f85f91a-b450-4dbb-b0f5-703606d9161f 'Contoso'
> ...
> Subscription 95350823-1b99-4afd-92f8-b1d6db6f7ab2 'Visual Studio Enterprise' can be accessed from tenants 72f988bf-86f1-41af-91ab-2d7cd011db47(default) and 2b8e6bbc-631a-4bf6-b0c6-d4947b3c79dd. To select a specific tenant when accessing this subscription, use 'az login --tenant TENANT_ID'.
⚠ azure-mgmt-resource SDK version is temporarily locked due to missing …
> {Profile} az login: Refine warning messages

- .vscode/launch.json
- Dockerfile
- build_scripts/windows/scripts/az.cmd
- scripts/release/debian/prepare.sh
- scripts/release/homebrew/docker/formula_template.txt
- scripts/release/rpm/azure-cli.spec
- src/azure-cli-core/azure/cli/core/telemetry.py
- src/azure-cli-core/azure/cli/core/tests/test_util.py
- src/azure-cli-core/azure/cli/core/util.py
- src/azure-cli/az
- src/azure-cli/az.bat
- src/azure-cli/azure/cli/command_modules/feedback/custom.py
> {Telemetry|Feedback} add installer data

- azure-pipelines-full-tests.yml
- tools/automation/tests/__init__.py
This pipeline is for cross verification for [Incremental Test](https://github.com/Azure/azure-cli/pull/12657).
Currently, incremental test has a bug that it cannot verify on scenario that one change on a single command module has potential bad impact on another command module. 
It can only run command modules based on modified files.
One of this scenario is bumping SDK. 
Adding this pipeline to collect statistic and provide a backup for verification.
This is the pipeline https://dev.azure.com/azure-sdk/public/_build?definitionId=1623&_a=summary
The exploit of Incremental Test will be fixed soon. 
---
> {CI} new pipeline to run full automation test for cross verification

- src/azure-cli/azure/cli/command_modules/monitor/_client_factory.py
- src/azure-cli/azure/cli/command_modules/monitor/_help.py
- src/azure-cli/azure/cli/command_modules/monitor/_params.py
- src/azure-cli/azure/cli/command_modules/monitor/commands.py
- src/azure-cli/azure/cli/command_modules/monitor/operations/general_operations.py
- src/azure-cli/azure/cli/command_modules/monitor/operations/monitor_clone_util.py
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_clone_public_ip_metric_alerts_always_scenario.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_clone_public_ip_metric_alerts_scenario.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_clone_storage_metric_alerts_across_subs_scenario.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_clone_storage_metric_alerts_always_scenario.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_clone_storage_metric_alerts_scenario.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_clone_vm_metric_alerts_scenario.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_general_operations.py
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_general_operations.py
- src/azure-cli/azure/cli/command_modules/monitor/util.py
**Background.**
Clone the metric alerts of one resource to another resource.
The alert rules and the resource must be in the same subscription. Thus, I add a requirement for this command right now that the source_resource and the target_resource must be in the same sub first.
---
> [Monitor] az monitor clone: support clone metric rules from one resource to another.

- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_alias.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_delegation.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_if_none_match.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone1_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone2_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone3_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone4_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone5_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone6_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone7_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone8_import.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_dns.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_dns_commands.py
Fix #11901 #11900 #2092
Now, if user provides `--if-none-match`, only the empty record-set would be created. The following command would fail by design. It won't bring any breaking change for existing users.
---
> [Network]support `--if-none-match` in `az network dns record-set {} add-record`

- src/azure-cli/azure/cli/command_modules/role/custom.py
Fix grammar errors in `az ad sp create-for-rbac`. Be consistent with the [doc change](https://github.com/MicrosoftDocs/azure-docs-cli/pull/1889/files#diff-5fcc6b8791abb8deec28c88634d4b424R88).
> {RBAC} az ad sp create-for-rbac: Fix grammar error

- src/azure-cli-core/azure/cli/core/extension/__init__.py
- src/azure-cli-core/setup.py
On Linux, check if there are extension in the system Python
library path (eg: /usr/lib/python3/dist-packages/azure-cli-extensions).
This allows extensions to be installed via system packages in
dist-packages, and registered by simply creating an extension directory
and symlinking the egg-info and the module.
EG:
$ ls -l /usr/lib/python3/dist-packages/azure-cli-extensions/azure-devops/
total 0
lrwxrwxrwx 1 root root 18 Feb 23 12:31 azext_devops -> ../../azext_devops
lrwxrwxrwx 1 root root 34 Feb 23 12:31 azure_devops-0.17.0.egg-info -> ../../azure_devops-0.17.0.egg-info
$ az extension list
[
{
"extensionType": "whl",
"name": "azure-devops",
"version": "0.17.0"
}
]
Locally installed extensions still have higher priority if available.
> [Extensions] Allow to install extensions in the system path via packages

- src/azure-cli-core/azure/cli/core/__init__.py
---
`Description:`
`ResourceType` is defined as enum with the following structure for each element:
`DATA_STORAGE = ('azure.multiapi.storage', None)`
If we have two Resource Types named `DATA_STORAGE` and `DATA_STORAGESYNC` with the following definition:
```
DATA_STORAGESYNC = ('azure.multiapi.storagesync.', None)
DATA_STORAGE = ('azure.multiapi.storage.', None)
```
and the following api versions in latest profile:
```
ResourceType.DATA_STORAGESYNC: '2015-12-01', …
```
> {Core} Add . in prefix for operation handler

- src/azure-cli/azure/cli/command_modules/acs/_format.py
`az aks list -o table` does not have fqdn info for private clusters. The fqdn of private cluster is in `.privateFqdn` for private clusters, while it is `.fqdn` for public clusters. This is to make cli show correct fqdn for private clusters.
`az aks list -o table` will show correct fqdn for private clusters
[Component Name 2] (BREAKING CHANGE:) (az command:) make …
> [AKS]az aks list -o table should show privateFqdn as fqdn for private clusters

- src/azure-cli/azure/cli/command_modules/monitor/operations/autoscale_settings.py
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_rules.yaml
- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_autoscale.py
> {Monitor}Bug fix for stop iteration

- src/azure-cli-core/azure/cli/core/_profile.py
- src/azure-cli/HISTORY.rst
Fix #12818: az login fails
The regression is introduced by #12726. `display_name` is only available since `/tenants?api-version=2018-06-01`, not available in `/tenants?api-version=2016-06-01`. We should retrieve `display_name` from `additional_properties` with a fallback. 
Actually this line shouldn't even be here due to the delay of REST spec fix and SDK release. 
```
> az cloud update -n AzureCloud --profile 2017-03-09-profile
> az login
The following tenants don't contain accessible subscriptions. Use 'az login --allow-no-subscriptions' to have tenant level access.
ca97aaa0-5a12-4ae3-8929-c8fb57dd93d6
> az cloud update -n AzureCloud --profile latest
> az login
The following tenants don't contain accessible subscriptions. Use 'az …
```
> {Profile} Hotfix: az login: fix KeyError: 'displayName'

- azure-pipelines-full-tests.yml
Add explicitly timeout limit to avoid CI job get cancelled implicitly by ADO like this [build](https://github.com/Azure/azure-cli/runs/550901673) which is against the configuration described [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#timeouts).
> To avoid taking up resources when your job is hung or waiting too long, it's a good idea to set a limit on how long your job is allowed to run. Use the job timeout setting to specify the limit in minutes for running the job. Setting the value to zero means that the job can run:
> - Forever on self-hosted agents
> - For 360 minutes (6 hours) on Microsoft-hosted agents with a public project and public repository
---
This checklist is used to make sure …
> {CI} Add explicitly timeout limit in Automation Full Test pipeline

- src/azure-cli/az.completion.sh
Fix #12046: Loading az completion in ZSH adds a debug line
This PR removes the message in zsh when registering auto-completion. 
To repro, make `/usr/bin/zsh` the default shell following [this guide](https://www.tecmint.com/change-a-users-default-shell-in-linux/), the re-login. The terminal shows:
```
Enabling ZSH compatibility mode
```
This line is now removed.
> {Core} Remove message in zsh when registering auto-completion

- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/extension/__init__.py
If you have extension installed which may be in dev mode or whl, the debug information will always show up the extension directory information in one specific value multiple times as shown below:
Here I have 4 extensions installed and `storage-ors-preview` is in dev mode, whose path should be local source path. But it still show up as `Extensions directory: 'C:\Users\zuh\.azure\cliextensions'`, which is not correct.
With the changes in PR, we can get accurate extension directory information as shown below:
(Fill in the following template if multiple notes are …
> {Core} Add accurate extension directory information in debug information

- src/azure-cli/azure/cli/command_modules/appservice/_constants.py
- src/azure-cli/azure/cli/command_modules/appservice/custom.py
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_on_linux_dotnet_consumption.yaml
- src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Resolves #12773 
This changes how linuxFxVersion is configured for linux dotnet function apps. Right now, the cli is incorrectly configuring this value and linux consumption apps are failing to be created. This should fix that issue.
A unit test was created for this: -- 
```
azdev test appservice test_functionapp_on_linux_dotnet_consumption`.
```
You can also ensure that the following command can create an app successfully --
```
az functionapp create --name name -g resource_group -s storage_account -c location --os-type linux --runtime dotnet
```
[AppService] az functionapp create: Changed the way linuxFxVersion was being set for dotnet linux function apps. This should fix a bug that was preventing dotnet linux consumption apps from being created. …
> [AppService] functionapp: Fixed configuration of container settings on linux dotnet function apps

- src/azure-cli/azure/cli/command_modules/storage/operations/blob.py
`Because timezone only supported in python3, CLI will be broken when user use python 2.`
`If we use the import at the top of file, all operations will be broken in blob.py, e.g. download-batch, move the timezone import to the function delete-batch to prevent breaking other operations.`
[Component Name 2] (BREAKING CHANGE:) (az command:) make some customer-facing …
> {Storage} import timezone when required

- src/azure-cli-testsdk/azure/cli/testsdk/preparers.py
`To support ADLS Gen2 account, we need to support more features in storage account.`
`Here we will expose --hns for StroageAccountPreparer().`
---
> {azure-cli-testsdk} Add hns support for storageAccountPreparer

- src/azure-cli-core/setup.py
- src/azure-cli/setup.py
antlr4 is used in monitor. We use 4.7.2 antlr4 tool to generate some codes in monitor. We still need a antlr4 runtime. But we didn't define it as a requirement in azure-cli before. In azure-cli-core, the version is not locked and the new version is 4.8.0. It would cause warning if two versions are not same.
Fix #12892
[Component Name 2] (BREAKING CHANGE:) (az …
> {Monitor} Move antlr4-python3-runtime to src/azure-cli/setup.py

- src/azure-cli/azure/cli/command_modules/acr/_utils.py
az acr run -r myregistry --cmd mcr.microsoft.com/dotnet/core/samples:dotnetapp /dev/null
The `dotnetapp` image sets the `workdir` to `/app` folder. Its `entrypoint` and `cmd` settings assume the current working directory is `/app` folder. However ACR Tasks by default launches the container using `/workspace` as the workdir so the above cli command will fail.
Since the main usage of `--cmd` is to launch the container image as it is, it's better to minimize the override behavior, especially avoid overriding the workdir folder.
So when generating the task step in the request, the cli command should pass `disableWorkingDirectoryOverride: true`
https://github.com/Azure/acr/issues/346
--- …
> [ACR] az acr run --cmd: disable working directory override

- src/azure-cli/azure/cli/command_modules/vm/custom.py
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_terminate_notification.yaml
- src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
This PR is to fix #12692 
Previously, if we enable terminate notification with update command, the parent object of `TerminateNotificationProfile`(`ScheduledEventsProfile`) may be None. Add logic to handle this case.
--- …
> [Compute] az vmss update: Fix terminate notification update issue

- src/azure-cli-core/azure/cli/core/util.py
#11968 
Azure CLI only outputs high-level error info. However, sometimes, it's not sufficient.
Command:
```
az vm create -g fytest2 -n a:1 --image centos --nsg-rule NONE
```
Output:
```
Azure Error: InvalidTemplateDeployment
Message: The template deployment 'vm_deploy_khqRswpYdSHi9beIynQazoai0oBD92c8' is not valid according to the validation procedure. The tracking id is 'c9518227-368e-4561-b92f-125921261026'. See inner errors for details.
Exception Details:
Error Code: TemplateFailedPrevalidation
Message: The template request has multiple validation failures involving one or more Microsoft.Network resources. Please check details for …
```
> [Core] Output error detail of exception

- src/azure-cli-core/azure/cli/core/azlogging.py
I am migrating test framwork from nose to pytest and found CLI would log every command's invocation output to a filep even though I configured in ~/.azure/config
```
[logging]
enable_log_file = no
```
And consequently, pytest wouldn't clear the AzCLI instance cleanly such that the test process would crash because of holding too many file descriptor (over the limit by OS):
**So, here, I want to enable the ability to repect the logging configuratin even though I won't use it in CI. I will fire another PR to fix the bug that CLI holding too many opened files.**
It affects two instance variables' assignment `command_logger_handler` and `command_metadata_logger`.
In the places they are referenced, there is a fault protection, so, it won't …
> {Core} Make CLI respect file logging configuration option: enable_log_file and AZURE_LOGGING_ENABLE_LOG_FILE env variable

- src/azure-cli/setup.py
As https://github.com/Azure/azure-cli/pull/12974 shows, azure-mgmt-loganalytics has a breaking change [from 0.3.0 to 0.2.0](https://pypi.org/project/azure-mgmt-loganalytics/0.3.0/) such that it breaks CI.
---
> {Monitor} pin azure-mgmt-loganalytics to 0.2

- src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_general_operations.py
As I migrating test framework from nose to pytest, the test in test_monitor_general_operations.py is strange, it can not pass and the result is running order dependent. :(
For example, it I tested _MonitorCloneStorageAccountScenarios_ then _MonitorCloneStorageAccountAlwaysScenarios_, the tests would fail as the second test _MonitorCloneStorageAccountAlwaysScenarios_ re-used the MagicMock generated in the first test _MonitorCloneStorageAccountScenarios_, So, the counter `test_guid_count` in the mocked method from ScenarioTest is unset, it kept growing, that's why it failed.
with the wrong mocking way, the mock instance comes with `mock.path` is 
Still using the tests above,
before test against this PR, try to print out the `self` in `create_guid` of …
> {Monitor} fix wrong mocking way in test_monitor_general_operations.py

- src/azure-cli/azure/cli/command_modules/vm/_params.py
Update help of `--ssh-dest-key-path` in `vm create`.
Destination file path on the VM for the SSH key. If the file already exists, the specified key(s) are appended to the file. Destination path for SSH public keys is currently limited to its default value "/home/username/.ssh/authorized_keys" due to a known issue in Linux provisioning agent.
Issue #12459 
`az vm create -h`
[Component Name 1] (BREAKING CHANGE:) (az command:) make some customer-facing …
> {Compute} Update help of vm create

- src/azure-cli/azure/cli/command_modules/servicefabric/_params.py
- src/azure-cli/azure/cli/command_modules/servicefabric/operations/applications.py
- src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/recordings/test_application.yaml
- src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/test_sf_application.py
Update application using --application-parameters replaces all the current parameters with the ones provided in the command instead of adding and updating them, so it will remove previous parameters that are not passed in the command. Merging new parameters with old ones to fix it and modify the tests to try this scenario.
---
> [Service Fabric] Fix #12891: az sf application update --application-parameters removes old parameters that are not in the request

- src/azure-cli-core/azure/cli/core/commands/arm.py
This PR is trying to fix #12119 
It is also a common problem for generic update.
When we try to remove an element from a list, previously we only catch the `IndexError`. However the list itself could also be None. So we also need to catch `AttributeError` here.
With this change, user will see a clean error message instead of previous trace stack.
`az vmss create -g myRG -n myVMSS --image UbuntuLTS`
`az vmss update --resource-group myRG--name myVMSS --remove virtualMachineProfile.networkProfile.networkInterfaceConfigurations[0].ipConfigurations[0].loadBalancerInboundNatPools 0`
`az vmss update --resource-group …
> [Core] fix generic remove property NoneType exception

- src/azure-cli/azure/cli/command_modules/resource/custom.py
Issue: #12241
Because the array of `deltails` object in `validation_result.error` cannot print the value of the property directly into the returned result (only the address of the object is printed out), so the information of returned error message  is lost.
Therefore, through the `dict()` method, all the attribute values in `validation_result.error` are parsed and printed into the returned results to solve the problem.
**For example:**
before:
```
{'additional_properties': {}, 'code': 'InvalidTemplate', 'message': "Deployment template validation failed: 'The template parameters 'name' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters …
```
> [ARM] az deployment group/mg/sub/tenant validate: Improve the error message when deployment verification fails (#12241)

- src/azure-cli/azure/cli/command_modules/role/_help.py
- src/azure-cli/azure/cli/command_modules/role/_params.py
- src/azure-cli/azure/cli/command_modules/role/custom.py
- src/azure-cli/azure/cli/command_modules/role/tests/latest/recordings/test_application_optional_claims.yaml
- src/azure-cli/azure/cli/command_modules/role/tests/latest/test_graph.py
This PR is to fix #11534 
There are three attributes of optional claims, `idToken`, `accessToken` and `samlToken`.
As a result of the graph api version problem, version 2.0 has deprecated `samlToken` and use a new `saml2Token` instead. Although we use version 1.6, service side still not accept `samlToken` any more. So Azure CLI will only support `idToken` and `accessToken`.
This may change if we migrate to the latest Microsoft Graph API in the future.
Please reference the case in test_graph.py.
[Component Name 2] …
> [RBAC] az ad app create/update: support --optional-claims as a parameter

- azure-pipelines.yml
Ubuntu Disco has reached end-of-life since January 23, 2020. And now Ubuntu repo no longer provides the release file for Disco. See https://wiki.ubuntu.com/Releases
Will update corresponding ADO tasks as well.
---
> [Packaging] Drop support for Ubuntu/Disco package

- src/azure-cli/azure/cli/command_modules/resource/commands.py
Make `az version` from #11680 GA. Otherwise the preview warning breaks the terminal color when calling
```pwsh
Measure-Command {az version}
```
We need to run/demo this line for performance baseline evaluation. 
Besides, the command is already stable. 
```pwsh
> az version
{
"azure-cli": "2.3.1",
"azure-cli-command-modules-nspkg": "2.0.3",
"azure-cli-core": "2.3.1",
"azure-cli-nspkg": "3.0.4",
"azure-cli-telemetry": "1.0.4",
"azure-cli-testsdk": "0.2.4",
"extensions": {
"interactive": "0.4.4",
"support": "0.1.1",
"timeseriesinsights": "0.1.0"
}
}
> Measure-Command {az version}
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 2
Milliseconds      : 80
Ticks             : 20807594
TotalDays         : …
```
> {Misc} az version: GA

- src/azure-cli-core/azure/cli/core/tests/test_parser.py
The overwrited way in `src/azure-cli-core/azure/cli/core/tests/test_parser.py`:
https://github.com/Azure/azure-cli/blob/8b7f3f6ef29b48be610ede323a10b9f41360708a/src/azure-cli-core/azure/cli/core/tests/test_parser.py#L49-L54
makes global impact while running tests **in serial**. 
With the way it overwrites, all tests in CLI after running with those tests, the instance method `error` of `AzCliCommandParser` will be replaced by `<azure.cli.core.tests.test_parser.VerifyError object at 0x7ff5efebbc88>` if you print it out in your test method.
**Background**:
```Python
def parse_args(self, args=None, namespace=None):
args, argv = self.parse_known_args(args, namespace)
if argv:
msg = _('unrecognized arguments: %s')
self.error(msg % ' '.join(argv))
return args
``` …
> {Core} Fix bug in core test test_parser that will affect exception stack while existing if argument parse raise Exception

- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/_environment.py
- src/azure-cli-core/azure/cli/core/telemetry.py
- src/azure-cli-core/azure/cli/core/tests/test_util.py
- src/azure-cli-core/azure/cli/core/util.py
- src/azure-cli/azure/cli/command_modules/feedback/custom.py
We can now rely on the `AZ_INSTALLER` env variable to know how the running Azure CLI is installed, so we can show specific instructions on how to update Azure CLI.
Example for Ubuntu:
> You have 2 updates available. Consider updating your CLI installation with 'sudo apt-get update && sudo apt-get install --only-upgrade -y azure-cli'. Detailed instructions can be found at https://aka.ms/doc/UpdateAzureCliApt
For windows, for simplicity let's just recommend the MSI link for upgrading(The upgrade cmdlet on powershell needs to be run as Administrator and I'm still looking for the alternative to [psutil](https://github.com/Azure/azure-cli/pull/11665) to decide if CLI is running in Powershell):
> You have 2 updates available. Consider updating your CLI installation with …
> [Core] az --version: Show command instruction and detailed instruction link when updates available

- src/azure-cli/azure/cli/command_modules/acs/_params.py
This PR aims to fix the issue #12745, since there was a type in the documentation.
Running the comand 
```
az aks create -h
```
Should give the correct help message.
---
> [AKS] Fixing typo in the help command

- src/azure-cli/HISTORY.rst
- src/azure-cli/azure/cli/command_modules/cosmosdb/_client_factory.py
- src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py
- src/azure-cli/azure/cli/command_modules/cosmosdb/_params.py
- src/azure-cli/azure/cli/command_modules/cosmosdb/_validators.py
- src/azure-cli/azure/cli/command_modules/cosmosdb/commands.py
- src/azure-cli/azure/cli/command_modules/cosmosdb/custom.py
- src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_private_endpoint.yaml
- src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_private_link_resource.yaml
- src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/test_cosmosdb_commands.py
> [CosmosDB]Support az cosmosdb private-link-resource and private-endpoint-connection

- src/azure-cli-core/azure/cli/core/__init__.py
- src/azure-cli-core/azure/cli/core/_help.py
- src/azure-cli-core/azure/cli/core/commands/constants.py
1. The survey link now can be turned off by setting environment variable `AZURE_OUTPUT_SHOW_SURVEY_LINK=no` or add the following in `~/.azure/config`:
```
[output]
show_survey_link = no
```
The environment variable has higher priority.
2. Added a UX study survey link in `az --version` and `az --help` (but not in `az some-command --help`).
The output looks like this in `az --version` :
```
az --version
az --help
export AZURE_OUTPUT_SHOW_SURVEY_LINK=no
az --version
az --help
az vm --help
```
---
> [Survey] Add switch to turn off survey link

- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_local_context.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
This PR is try to enable local context feature for vnet/subnet.
We will save vnet/subnet value to local context in `create` command and use these values in `update`, `show` and some other commands. One exception is for `delete` command. For `delete` command, user still need to specify vnet or subnet name even if local context is turned on.
`az network vnet create -g RG -n vnetName --subnet-name subnetName`
`az network vnet show`
`az network vnet subnet show`
`az network vnet subnet delete` (prompt error)
`az network vnet delete` (prompt error)
`az network vnet subnet delete -n subnetName`
`az network vnet delete -n vnetName`
[Component …
> [Network] Enable local context feature for vnet/subnet parameter

- src/azure-cli/azure/cli/command_modules/role/tests/latest/test_role.py
When running these 2 tests in serial:
1. test_role.py::RoleAssignmentScenarioTest::test_role_assignment_handle_conflicted_assignments
2. test_role.py::RoleAssignmentScenarioTest::test_role_assignment_mgmt_grp
The second one will fail on Linux but succeed on Windows.
**Why failed on Linux**?
At the beginning, the 1st test would chdir to a temporary dir.
https://github.com/Azure/azure-cli/blob/280692d3b080685846c9b9a71dbe5c10dbd0ce94/src/azure-cli/azure/cli/command_modules/role/tests/latest/test_role.py#L351-L354
and at the end the of test, it would try to switch back but actually it didn't because the `basr_dir` is a relative path. So, the original directory is lost and the test procedure would stay at the temporary directory. …
> {Role} fix test fail when running in serial due to buggy way to swtich tempory folder back

- src/azure-cli/azure/cli/command_modules/vm/_params.py
https://github.com/Azure/azure-cli/issues/11961
--version
The version of the extension. If you want to use the exact version number specified, please specify --no-auto-upgrade.
Auto upgrade is on by default. So remind users.
---
> {Compute} Update help of --version of vm/vmss extension

- src/azure-cli/azure/cli/command_modules/vm/custom.py
This PR is to fix #11144
When we try to detach lun from a vmss without data disk, we will meet a NoneType exception.
I add a check here for data disk, and will raise `Data disk doesn't exist` error for this case.
`az vmss create -g RG -n vmssName --image UbuntuLTS --load-balancer ""`
`az vmss disk detach -g RG --vmss-name vmssName --lun 0` (prompt error instead of exception)
---
> [Compute] az vmss disk detach: fix data disk NoneType issue

- src/azure-cli/azure/cli/command_modules/aro/_format.py
- src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_show.yaml
- src/azure-cli/azure/cli/command_modules/aro/tests/latest/test_aro_commands.py
Fixes a bug in `az aro {command} --output table` (`az aro list --output table`, for example) when the comamnd fails due to not taking into account potential `None` values in data in some edge cases table output currently fails. For example:
* When there are no worker profiles (cluster only has masters or we failed to get data from API server)
* When a worker profile does not have count (machine set was scaled to 0)
Create an ARO cluster, scale all machine sets to 0 and try to run `az aro list --output table`.
[ARO] az aro: Fix table output
---
> [ARO] az aro: Fix table output

- src/azure-cli-core/azure/cli/core/azlogging.py
- src/azure-cli-core/setup.py
- src/azure-cli/azure/cli/__main__.py
- src/azure-cli/azure/cli/command_modules/feedback/tests/latest/test_feedback.py
- src/azure-cli/requirements.py3.Darwin.txt
- src/azure-cli/requirements.py3.Linux.txt
- src/azure-cli/requirements.py3.windows.txt
- src/azure-cli/setup.py
This PR mainly did is to To make CLI instance close logger file after it's invoked, specifically:
1. Fix the bug that would leak file handler and its corresponding fd (Fix https://github.com/Azure/azure-cli/issues/12882, Fix https://github.com/Azure/azure-cli/issues/10435)
2. Fix the edge bug that file logger would write to previous file handler like `test_feedback.py` because of cli never clean up only when it exists.
3. Bump knack to 0.7.0rc4 because need its new feature support
The original discussion list [here](https://github.com/Azure/azure-cli/pull/12971).
With the [PR of knack](https://github.com/microsoft/knack/pull/199/files) which make knack be aware of SystemExit and the timing to raise EVENT_CLI_POST_EXECUTE  is merged, the test should be fine.
**Testing …
> [Core] fix logging file fd leaking

- src/azure-cli/azure/cli/command_modules/appservice/custom.py
There is no need to sleep before parsing the response from the SCM server.  Unless the status needs to continue to loop, this should return instantly.
---
> [AppService] az webapp deployment source config-zip: remove sleep after request.get()

- src/azure-cli/azure/cli/command_modules/network/_client_factory.py
- src/azure-cli/azure/cli/command_modules/network/_help.py
- src/azure-cli/azure/cli/command_modules/network/_params.py
- src/azure-cli/azure/cli/command_modules/network/commands.py
- src/azure-cli/azure/cli/command_modules/network/custom.py
- src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_security_partner_provider.yaml
- src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
new commands. az network security-partner CRUD
fix #13075 
---
> [Network] az network security-partner: support security partner provider

- src/azure-cli/azure/cli/command_modules/acs/_help.py
- src/azure-cli/azure/cli/command_modules/acs/_params.py
- src/azure-cli/azure/cli/command_modules/acs/custom.py
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_with_windows.yaml
- src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
This will allow cx to create a k8s cluster and then add Windows agent pools without aks-preview.
AZURE_CLI_TEST_DEV_SP_NAME=1f3a7c5e-1812-4aa7-bffe-b5ef651cbab2 AZURE_CLI_TEST_DEV_SP_PASSWORD='6997d05f-3cae-4bcc-95f0-b74cf5444860' CAZURE_CLI_TEST_MODULES=acs azdev test test_aks_create_with_windows --discover --live
---
> [AKS] az aks create: Add support for Windows

- src/azure-cli/azure/cli/command_modules/acr/_errors.py
I found two small typos while surfing the code.
I don't think testing is needed...
---
> {ACR} Fix small typos

- src/azure-cli-core/azure/cli/core/tests/test_help.py
Make tests of `src/azure-cli-core/azure/cli/core/tests/test_help.py` complete pass core under different profiles.
Currently, jobs like **Automation Test** running under different profiles didn't run with azure-cli-core module, which is incomplete for our tests and it would fail if running under 2019 and 2017 profiles.
I discovered it with the latest change on azdev https://github.com/Azure/azure-cli-dev-tools/pull/188, and the tests `src/azure-cli-core/azure/cli/core/tests/test_help.py::TestHelpLoads` would fail if running under profile 2019-03-01-hybrid beause of the help entries would behave differently under 2019 and 2017 profiles but the tests are expected to assert everything under every profile. 
That's why they failed.
On original branch, …
> [Core] fix core tests failed under certain profiles

- src/azure-cli/azure/cli/command_modules/privatedns/_help.py
- src/azure-cli/azure/cli/command_modules/privatedns/_params.py
- src/azure-cli/azure/cli/command_modules/privatedns/commands.py
- src/azure-cli/azure/cli/command_modules/privatedns/custom.py
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/README.md
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/recordings/test_Private_Dns_Zone1_Import.yaml
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/recordings/test_Private_Dns_Zone2_Import.yaml
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/recordings/test_Private_Dns_Zone3_Import.yaml
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/recordings/test_Private_Dns_Zone4_Import.yaml
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/recordings/test_Private_Dns_Zone5_Import.yaml
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/recordings/test_Private_Dns_Zone6_Import.yaml
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/recordings/test_Private_Dns_Zone7_Import.yaml
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/recordings/test_Private_Dns_Zone8_Import.yaml
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/recordings/test_Private_Dns_Zone_Local_Import.yaml
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/test_privatedns_commands.py
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/zone_files/zone.local.txt
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/zone_files/zone1.txt
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/zone_files/zone2.txt
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/zone_files/zone3.txt
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/zone_files/zone4.txt
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/zone_files/zone5.txt
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/zone_files/zone6.txt
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/zone_files/zone7.txt
- src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/zone_files/zone8.txt
This PR contains the changes for importing and exporting zone files to private dns zone. This is added as new feature in private dns zone. This feature was already present in public Azure DNS, incorporating similar changes for Private DNS zone.
az network private-dns zone import -g MyResourceGroup -n MyZone -f /path/to/zone/file
az network private-dns zone export -g MyResourceGroup -n www.mysite.com -f mysite_com_zone.txt
---
> [Privatedns] Add feature in private DNS zone to import export zone file
