Azure/azure-cli

src/azure/cli/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

Fixes #498.  Fixes #844.
Also have a fix for help groups that keeps Arguments separate from un-indexed groups

Fixes #498.  Add route table option to subnet create and update.

---

azure-cli.pyproj

Cleans up the VS project file after merging #828.

Update VS Project File

---

src/azure-cli-core/azure/cli/core/utils/vcr_test_base.py

Fix handle_exceptions not being mocked after recent change

---

azure-cli.pyproj

Fix VS Startup File

---

README.rst

this'll work exactly the same way

simplify docker instructions

---

scripts/install/install.py

(after azure-cli-core change, the --upgrade param was not included)

Allow install script to upgrade nightly packages

---

src/azure-cli/azure/cli/__main__.py

Catch KeyboardInterrupt

---

src/azure-cli-core/azure/cli/core/extensions/transform.py
src/azure-cli-core/azure/cli/core/tests/test_add_resourcegroup_transform.py

Fix add resource group not dealing with ids that are dicts and not string types
Fixes #884

Fix Resource group deployment list raises TypeError

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py

Public IP test ran fine for me, so adding back the removed checks.

Fixes #886.

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py

rbac: ensure role assignment creation on newly created service principal work reliably

---

src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_help.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/custom.py

minor bug fixes on login samples and webapp browse support

---

src/azure-cli-core/azure/cli/core/_config.py
src/azure-cli-core/azure/cli/core/application.py
src/azure-cli-core/azure/cli/core/parser.py
src/azure-cli-core/azure/cli/core/telemetry.py
src/azure-cli/azure/cli/main.py
src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/__init__.py
src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/_consts.py

Currently opt in, will change to opt out if we get the go ahead
Fixes #881

Fixes #881.  Opt in/out of telemetry in az configure

---

src/azure-cli-core/azure/cli/core/_output.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/custom.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/generated.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_blob_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage.py

Fixes #800, fixes #916, fixes #917. Wraps return types that are scalars so they work with table format. Adds a table format callable for storage list commands.

[Output Formats] Table Output Enhancements and Storage Specific Fixes

---

src/command_modules/azure-cli-component/azure/cli/command_modules/component/_params.py
src/command_modules/azure-cli-component/azure/cli/command_modules/component/custom.py
src/command_modules/azure-cli-component/azure/cli/command_modules/component/generated.py

Fixes #888 - Simplify 'az component' commands

Simplify 'az component' commands

---

src/azure-cli-core/azure/cli/core/_help.py
src/azure-cli-core/azure/cli/core/tests/test_help.py

Help should only add fullstop if there isn't a terminal point already

---

src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/tests/recordings/test_key_vault_mgmt.yaml
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/generated.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/test_graph.py
src/command_modules/azure-cli-role/requirements.txt
src/command_modules/azure-cli-role/setup.py

Upgrade graphrbac and mgmt-authorization to rc6

---

src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/_help.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/_params.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/custom.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/generated.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/tests/recordings/test_webapp_config.yaml
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/tests/test_webapp_commands.py

1. Move 'plan' to top level per webapp team ask. This is to be consistent with xplat
2. Add support for site configurations update, including app settings.

webapp: app service plan and site configurations

---

src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/_help.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/_params.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/custom.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/generated.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/mgmt_iot_hub_device/lib/operations/iot_hub_devices_operations.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/mgmt_iot_hub_device/swagger_iot_hub_device_identity.json
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/tests/recordings/test_iot_device_create.yaml
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/tests/recordings/test_iot_hub_create.yaml
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/tests/test_iot_commands.py

Add below commands in IoT module to show connection string.
```bash
az iot hub show-connection-string
az iot device show-connection-string
```
@aovechki @ZhijunZhao @shizn

[IoT] add show-connection-string command for hub and device

---

doc/sphinx/azhelpgen/azhelpgen.py
doc/sphinx/azhelpgen/doc_source_map.json
src/azure-cli-core/azure/cli/core/_help.py

1. Fix doc build error because choices may be types other than str
2. Update arguments sort method to align with core code

sync help doc generation with core code

---

src/azure-cli-core/azure/cli/core/commands/__init__.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/mgmt_vmss/azuredeploy.json
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/mgmt_vmss/lib/models/deployment_vmss.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/mgmt_vmss/lib/models/template_link.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/mgmt_vmss/lib/operations/vmss_operations.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/mgmt_vmss/swagger_create_vmss.json
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_custom_ip.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_multinic.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_none_options.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_ubuntu.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_scaleset_create_existing_options.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_scaleset_create_options.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_scaleset_create_simple.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vmss_create_none_options.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

1.  Show correlation ID when a long running operation fails or is cancelled
2.  Add better error message for creating LBs with no public IP
3.  Update vm/vmss help
4.  Remove faulty properties from VMSS when non-new LB is used

Fixes #934, Fixes #882, Fixes #879

---

src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py

polish some well known unfriendly AAD server errors

---

src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/azure/cli/__init__.py
src/azure-cli/setup.py
src/command_modules/azure-cli-component/setup.py
src/command_modules/azure-cli-configure/setup.py
src/command_modules/azure-cli-feedback/setup.py
src/command_modules/azure-cli-iot/setup.py
src/command_modules/azure-cli-keyvault/setup.py
src/command_modules/azure-cli-network/setup.py
src/command_modules/azure-cli-profile/setup.py
src/command_modules/azure-cli-redis/setup.py
src/command_modules/azure-cli-resource/setup.py
src/command_modules/azure-cli-role/setup.py
src/command_modules/azure-cli-storage/setup.py
src/command_modules/azure-cli-taskhelp/setup.py
src/command_modules/azure-cli-vm/setup.py
src/command_modules/azure-cli-webapp/setup.py

Current published version is 0.1.0b4 to moving forward to 0.1.0b6

Modify version of all modules to 0.1.0b6

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py

changing order of some examples in preparation for internal demo

example re-ordering

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_custom_ip.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_existing_options.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_multinic.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_none_options.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_state_modifications.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_ubuntu.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

While issue #974 was fixed by updating the live templates, the fact that the templates were incorrect should have been caught. This PR modifies existing VM tests to check the following:
- VM can be created in a region other than West US
- When `--location` is specified, all appropriate resources are created in that location rather than inheriting from the resource group (which is in a different region).

[VM] Update to test scenarios

---

README.rst

Instructions that will work on systems w/o curl.

Add wget instructions since Debian (and others) don't ship curl by default

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py

[VM] Storage-type TAB completion and Location clarification

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py

Reverts Azure/azure-cli#997. The fix doesn't address the formats

Revert "Updating to preserve line breaks"

---

azure-cli.pyproj
src/azure-cli-core/azure/cli/core/commands/parameters.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_actions.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_custom_ip.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_existing_options.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_multinic.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_none_options.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_ubuntu.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_data_disk.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_generalize.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_scaleset_create_existing_options.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_scaleset_create_options.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_scaleset_create_simple.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_show_list_sizes_list_ip_addresses.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vmss_create_none_options.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_defaults.py

Fix VNET and storage account defaulting logic.

---

appveyor.yml
doc/sphinx/azhelpgen/azhelpgen.py

#1022 It is broken in commit https://github.com/Azure/azure-cli/commit/90c7b7de3159e41160c96dbaffd13f94e20c3874 because get_group_priority has changed in _help.py but not in azhelpgen.py

Fix #1022: Document CI is Broken

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py

bug:account clear should reset subscriptions to empty array, not empty object

---

src/azure-cli-core/azure/cli/core/adal_authentication.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py

auth: handle connection failures

---

azure-cli.pyproj
src/azure-cli-core/azure/cli/core/commands/__init__.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/custom.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/tests/recordings/test_appservice_error_polish.yaml
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/tests/test_webapp_commands.py

It will be a while the bug will be fixed from webapp services.
Related with #140

webapp: polish LRO failures

---

scripts/dev_setup.py

[dev_setup.py] Install requirements.txt last

---

src/azure-cli-core/azure/cli/core/_help.py
src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/_util.py
src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/azure/cli/core/commands/arm.py
src/azure-cli-core/azure/cli/core/commands/parameters.py
src/azure-cli-core/azure/cli/core/help_files.py
src/azure-cli-core/azure/cli/core/parser.py
src/azure-cli-core/azure/cli/core/telemetry.py
src/azure-cli/azure/cli/main.py
src/command_modules/azure-cli-component/azure/cli/command_modules/component/custom.py

- 60% improvement in loading of the core of the CLI
- Changes to the command modules themselves will come later

Improve CLI loading speed (not including command modules themselves)

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/generated.py

Fixes part of https://github.com/Azure/azure-cli/issues/1039 and https://github.com/Azure/azure-cli/issues/1040

Show resource type in 'az resource list -otable' (table output)

---

README.rst

Fixes https://github.com/Azure/azure-cli/issues/1075, fixes https://github.com/Azure/azure-cli/issues/1053

Update docs to reference Bash for Windows instructions

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_validators.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/generated.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/test_group_deployment_thru_uri.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/test_provider_registration.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_resource.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_validators.py

Address following feedback from ARM team documented at #1033
1. Remove the waiting on `provider registering`
2. Support uri based template and parameter file on `group deployment`
3. `group deployment name` should be optional

arm: fix deployment commands per review feedback

---

README.rst

Fixes https://github.com/Azure/azure-cli/issues/1072

Add tab completion instructions to README for pip install

---

appveyor.yml
doc/sphinx/azhelpgen/doc_source_map.json

Fix #1151 
cc @sanar-microsoft @mayurid @BurtBiel
Please help take care of doc_source_map.json if there are modules added, removed or updated. Thanks a lot! 😄

[Document CI] Fix failure of doc generation due to devops module renamed to vsts

---

src/azure-cli/LICENSE.txt
src/azure-cli/MANIFEST.in

Add LICENSE.txt file to MANIFEST.in

---

src/command_modules/azure-cli-vsts/azure/cli/command_modules/vsts/custom.py

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/282564

Bug 282564:If the user passes a Remote-URL we should not check the local directory for a compose file

---

src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/_help.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/_params.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/custom.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/generated.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/tests/recordings/test_webapp_git.yaml
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/tests/sample_web/.gitignore
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/tests/sample_web/package.json
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/tests/sample_web/server.js
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/tests/test_webapp_commands.py
src/command_modules/azure-cli-webapp/setup.py

Also include:
1. Add help short summary
2. Fix the incorrect logic of retrieving scm url for logs
3. Expose the node js version to config

webapp: integrate with source control system of GIT and Mercurial 

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py

Address the inconsistency in discussed in #1178

create-for-rbac: update field name of the output

---

doc/recording_vcr_tests.md

Update guidelines for VCR test authoring.

[Test] Update test authoring guidelines

---

scripts/dev_setup.py

1. Make it executable
2. Update shebang
3. Colorize the output and improve the readability

Update dev_setup.py script

---

Dockerfile

Closes https://github.com/Azure/azure-cli/issues/1027

[Docker] Use Python based on Alpine for Dockerfile

---

src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py

Changed the request endpoint and operation currently being used by list releases to act as long running operation

Fixing list releases to run as long running operation.

---

src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/_params.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/custom.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/tests/test_webapp_commands.py

per review with webapp team
//cc:@naziml

webapp: add shortcut for docker related arguments

---

src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/custom.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/generated.py
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/tests/recordings/test_webapp_e2e.yaml
src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/tests/test_webapp_commands.py

webapp: support list plans across subscription

---

appveyor.yml

update nuget source which belongs to VSC organization

update nuget source

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py

[Compute] Update Misleading VMSS instance-ids help text.

---

doc/authoring_command_modules/authoring_commands.md

Added guidance to using the `cli_generic_update_command` method for teams onboarding update commands so they can include the generic update arguments.

Add generic update guidance to command authoring guide

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/commands.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py

role:update help and table output format

---

src/command_modules/azure-cli-component/azure/cli/command_modules/component/custom.py

Closes https://github.com/Azure/azure-cli/issues/1192

[Install] Add note about using sudo when there's an error with 'az component'

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py

[ExpressRoute] Fix MicrosoftPeering issues.

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py

Issue: https://github.com/Azure/azure-cli/issues/1121

[Fix #1121] Update help documents for 'az network dns zone'

---

src/azure-cli-core/azure/cli/core/telemetry.py

Hope this will fix the common break in the master branch

Fix a null ref issue at telemetry.py

---

src/azure-cli-core/azure/cli/core/commands/__init__.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py

polish errors caused by unregistered namespace or feature

---

scripts/command_modules/_common.py
scripts/command_modules/_task.py
scripts/command_modules/pylint.py
scripts/command_modules/test.py

1. extract the parallel utility thread to its own file
2. make pylint tasks run in parallel
This reduce the pylint time from 80s to 16s

Run pylint in parallel

---

README.rst

Addresses https://github.com/Azure/azure-cli/issues/1242

Pip install instructions should recommend --user

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/setup.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/setup.py

The beginning of fixing some of the hacks prior to the Kubernetes + ACS launch.

Upgrade to azure-mgmt-vm 0.32.1

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Fixes https://github.com/Azure/azure-cli/issues/1305
@lostintangent @yugang-msft

Add some documentation for service-principal and client-secret

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Fixes https://github.com/Azure/azure-cli/issues/1323
@derekboe

Fix bugs in download URLS

---

src/command_modules/azure-cli-component/azure/cli/command_modules/component/_params.py
src/command_modules/azure-cli-component/azure/cli/command_modules/component/custom.py

Closes https://github.com/Azure/azure-cli/issues/1222

Support install multiple additional components with 'az component'

---

Dockerfile

Closes https://github.com/Azure/azure-cli/issues/769
Also closes https://github.com/Azure/azure-cli/issues/1343

Add tools jp, jq, jpterm, ssh-keygen to Docker image

---

src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/_help.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/_params.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/commands.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/custom.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/mgmt_iot_hub_device/lib/models/authentication.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/mgmt_iot_hub_device/lib/models/device_description.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/mgmt_iot_hub_device/lib/models/symmetric_key.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/mgmt_iot_hub_device/lib/models/x509_thumbprint.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/mgmt_iot_hub_device/lib/operations/iot_hub_devices_operations.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/mgmt_iot_hub_device/swagger_iot_hub_device_identity.json
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/tests/recordings/test_iot_hub.yaml
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/tests/test_iot_commands.py

1. Add `job` sub-group to `iot hub`
2. Add `show-stats` and `show-quota-metrics` commands to `iot hub`
3. Add `message` sub-group to `iot device`
4. Minor refinement
Help messages for new commands are listed as below.
```bash
>az iot hub job list -h
Command
az iot hub job list: List all jobs in an IoT Hub.
Arguments
--hub-name [Required]: IoT Hub name.
--resource-group -g  : Name of resource group.
>az iot hub job show -h
Command
az iot hub job show: Show a job in an IoT Hub.
Arguments
--hub-name [Required]: IoT Hub name.
--job-id   [Required]: Job Id.
--resource-group -g  : Name of resource group.
>az iot hub job cancel -h
Command
az iot hub job cancel: Cancel a job in an IoT Hub.
Arguments
--hub-name [Required]: IoT Hub name.
--job-id   [Required]: Job Id.
--resource-group -g  : Name of …
```

[IoT] add more commands to `iot hub` and `iot device` command group

---

src/azure-cli-core/azure/cli/core/_output.py
src/azure-cli-core/azure/cli/core/tests/test_output.py

output: fix issues in jmespath object projection 

---

azure-cli.pyproj
scripts/lintall
scripts/lintall.bat
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/custom.py

[Storage] Add EndpointSuffix to storage connection string command

---

doc/authoring_command_modules/authoring_commands.md

To support #1372 and any future contributors.

Add `--ids` to the command authoring guide

---

requirements.txt
src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/setup.py
src/command_modules/azure-cli-profile/setup.py

Bring in 3 bug fixes with details documented in the [release notes](https://github.com/AzureAD/azure-activedirectory-library-for-python/releases/tag/0.4.3), which are all needed for cli.

adal: use new version 0.4.3

---

src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_command_type.py

[KeyVault] Handle Adal errors during challenge callback

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/blob.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py

What's in the change:
1. Enable the command to copy files between containers and/or storage accounts in batch.
2. Enable recursively copy to keep the original folder structure.
3. Replace some parameters with a more user-friendly ones. For example, --if-modified-since is replaced by --exclude-new.

Improve blob copy command.

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_format.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py

Fixes #1103
@colemickens @yugang-msft

Add table formatting for resource group list (and add 'status')

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py

Fixes #1139
@JasonRShaver @yugang-msft

Add table formatting for deployments and sort by timestmap.

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/test_network_public_ip.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py

- Adds convenience arguments to `public-ip update` to achieve functional parity with Xplat.
- Updates poor quality SDK-reflected help text.

[Network] Public IP fixes

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_acs_create_update.yaml

Fixes https://github.com/Azure/azure-cli/issues/1338

Check for the existence of a resource group before create.

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/test_custom.py

Fixes https://github.com/Azure/azure-cli/issues/1350
Fixes https://github.com/Azure/azure-cli/issues/1311
@lostintangent

Merge credentials for kubernetes if credentials already exist.

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Fixes https://github.com/Azure/azure-cli/issues/1470

Get the user name from the cluster info.

---

appveyor.yml

add script to merge toc and ref toc

update build script to support conceptual docs

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py

Fixes https://github.com/Azure/azure-cli/issues/1394
@lostintangent @colemickens

Add formatting to acs list.

---

scripts/command_modules/test.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/file.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/files_helpers.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/storage_url_helpers.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/.gitignore
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/integration_test_base.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/integration_test_blob_download.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/integration_test_blob_upload.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/integration_test_file_download.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/integration_test_file_upload.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/run_integration.sh
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/unittest_storage_url_helpers.py

Feature: Download / Upload storage files in batch

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/commands.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Addresses #1446.
cc: @brendandburns

acs: get-credentials accepts --output-file

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Remove k8s-master from dns names

---

README.rst

Closes https://github.com/Azure/azure-cli/issues/1491

[Docs] Change 'Unix' to 'Linux'

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Synthesize `--dns-prefix` if it's not provided.
@colemickens @lostintangent

Remove dns-prefix as a required field.

---

src/command_modules/azure-cli-component/azure/cli/command_modules/component/custom.py

Closes https://github.com/Azure/azure-cli/issues/1482

[Component] 'az component update' - support user install

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Fixes https://github.com/Azure/azure-cli/issues/1489

Move client secret to parameters so it gets hidden by ARM

---

README.rst

Add link to README.rst for developer setup

---

src/azure-cli-core/azure/cli/core/application.py

Fix Noun Parsing on Linux (issue 1529)

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Fixes https://github.com/Azure/azure-cli/issues/1477

Clean up kubectl browse somewhat.

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py

Fixes https://github.com/Azure/azure-cli/issues/1415

Add --operation-ids to 'az resource group deployment operations show'

---

src/command_modules/azure-cli-sql/README.rst
src/command_modules/azure-cli-sql/azure/__init__.py
src/command_modules/azure-cli-sql/azure/cli/__init__.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/__init__.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/__init__.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_util.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/custom.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/help.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/params.py
src/command_modules/azure-cli-sql/requirement.txt
src/command_modules/azure-cli-sql/setup.cfg
src/command_modules/azure-cli-sql/setup.py

This is the first SQL server command added to the CLI. This PR is intended to set up the skeleton for the SQL command module.

Add first Azure SQL Server Command

---

src/azure-cli-core/azure/cli/core/test_utils/vcr_test_base.py
src/azure-cli-core/azure/cli/core/tests/test_vcr_security.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_resource.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_account_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_blob_acl_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_blob_copy_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_blob_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_file_acl_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_file_copy_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_file_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_queue_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_table_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage.py

Fixes #1631 . Adds tests for using the name parameters to copy instead of simply the URI.

Fix copy source convenience parameters

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py

Fixes https://github.com/Azure/azure-cli/issues/1611

Add a table transform for acs show to match acs list.

---

src/azure-cli-core/azure/cli/core/commands/_introspection.py

Fix parameter name parsing regex

---

src/azure-cli-core/azure/cli/core/commands/_introspection.py

Update regex of parsing sdk function argument comments

---

src/azure-cli-core/azure/cli/core/application.py
src/azure-cli-core/azure/cli/core/tests/test_application.py

Improve @file handling logic

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/test_service_principals.py

Add unit tests for load/store.

Update service principal creation so that it is subscription specific.

---

src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_util.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/help.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/params.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/validators.py

Following commands are added:
- az sql server *
- az sql server service-objective *
- az sql server firewall *
- az sql db *
- az sql elastic-pools *

Add Azure SQL Server commands

---

.flake8
scripts/automation/style/run.py
scripts/automation/utilities/path.py
scripts/check_style
scripts/check_style.bat
scripts/setup.py

Included:
1. The automation package will install these two scripts to the virtual environment's bin folder so that shortcut command `check_style` can be used to run pylint directly.
2. Add flake8 to the automation.style for PEP8 check.

Automation scripts improvements

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

[Network] Improvements to ExpressRoute update commands

---

src/azure-cli-core/azure/cli/core/application.py
src/azure-cli-core/azure/cli/core/telemetry.py
src/azure-cli-core/azure/cli/core/tests/test_telemetry.py
src/azure-cli/azure/cli/__main__.py

1. Hide global variables
2. Introduce TelemetryService class to gather the key functionalities
3. Improve readability and enforce PEP8
4. Improve code flow and exception handling
This change serves as the first step towards incoming changes to the data model. It improves maintainability and reduces the exposed surface of `telemetry` module.

Improve telemetry code readabilty and organization

---

src/azure-cli-core/azure/cli/core/telemetry.py

fix https://github.com/Azure/azure-cli/issues/1696

Remove CI specific code in telemetry

---

src/azure-cli-core/azure/cli/core/commands/arm.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/test_multi_id_show.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py

Fix for broken --ids

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/recordings/test_sp_create_scenario.yaml
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/test_graph.py

create-for-rbac:accept displayname

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/test_custom.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/test_service_principals.py

Part of fixing: https://github.com/Azure/azure-cli/issues/1689 and https://github.com/Azure/azure-cli/issues/1620

Actually detect service principal errors and raise a message.

---

src/azure-cli-core/MANIFEST.in
src/azure-cli-nspkg/MANIFEST.in
src/azure-cli/MANIFEST.in
src/command_modules/azure-cli-acr/MANIFEST.in
src/command_modules/azure-cli-acs/MANIFEST.in
src/command_modules/azure-cli-appservice/MANIFEST.in
src/command_modules/azure-cli-batch/MANIFEST.in
src/command_modules/azure-cli-cloud/MANIFEST.in
src/command_modules/azure-cli-component/MANIFEST.in
src/command_modules/azure-cli-configure/MANIFEST.in
src/command_modules/azure-cli-container/MANIFEST.in
src/command_modules/azure-cli-context/MANIFEST.in
src/command_modules/azure-cli-feedback/MANIFEST.in
src/command_modules/azure-cli-iot/MANIFEST.in
src/command_modules/azure-cli-keyvault/MANIFEST.in
src/command_modules/azure-cli-network/MANIFEST.in
src/command_modules/azure-cli-profile/MANIFEST.in
src/command_modules/azure-cli-redis/MANIFEST.in
src/command_modules/azure-cli-resource/MANIFEST.in
src/command_modules/azure-cli-role/MANIFEST.in
src/command_modules/azure-cli-sql/MANIFEST.in
src/command_modules/azure-cli-storage/MANIFEST.in
src/command_modules/azure-cli-taskhelp/MANIFEST.in
src/command_modules/azure-cli-vm/MANIFEST.in

These files are needed when building with sdist since the HISTORY.rst files were added

Add missing MANIFEST.in files

---

src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/params.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/recordings/test_sql_firewall_mgmt.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/recordings/test_sql_service_objective_mgmt.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/test_sql_commands.py

This PR adds basic nose unit tests and recording for
```
az sql server firewall create
az sql server firewall show
az sql server firewall update
az sql server firewall list
az sql server firewall delete
```
```
az sql server service-objective list
az sql server service-objective show
```
The only bug I found was the required parameters were not correctly documents but looks like it's the swaggers fault instead of the cli. 
```
(env) vishrut@visshamac azure-cli (sql-server-firewall-test) $ az sql server firewall create -h
Command
az sql server firewall create: Create an Azure SQL server firewall rule.
Arguments
--firewall-rule-name [Required]: The name of the Azure SQL server firewall rule.
--resource-group -g  [Required]: Name of resource group.
--server-name        [Required]: The name …
```

More sql server tests for firewall and service-objective

---

scripts/automation/release/run.py
scripts/github_bot/HISTORY.rst
scripts/github_bot/api/Dockerfile
scripts/github_bot/api/app.py

Bot can now upload source code, .tar.gz and .whl assets to the GitHub release

0.1.0 release of GitHub bot

---

src/azure-cli-core/azure/cli/core/application.py
src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/azure/cli/core/decorators.py
src/azure-cli-core/azure/cli/core/parser.py
src/azure-cli-core/azure/cli/core/telemetry.py
src/azure-cli-core/azure/cli/core/telemetry_upload.py
src/azure-cli-core/azure/cli/core/tests/test_telemetry.py
src/azure-cli/azure/cli/__main__.py
src/azure-cli/azure/cli/main.py
src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/custom.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/custom.py

1. Redefine the properties;
2. Introduce concept of command scope. The errors happen during a
command scope are associated with the command

Adopt VS Telemetry DataModel

---

scripts/automation/style/run.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/__init__.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_command_type.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_factory.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_format.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/custom.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/storage_url_helpers.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/integration_test_blob_download.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/unittest_storage_url_helpers.py

Most of the changes are trivial. I'll comment on the non-trivial ones.

PEP8: Update storage command module code style

---

src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/recordings/test_sql_elastic_pools_mgmt.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/test_sql_commands.py

This PR adds nose unit tests and recording for
```
az sql elastic-pools create
az sql elastic-pools list
az sql elastic-pools show
az sql elastic-pools update
az sql elastic-pools delete
```
@troydai / @derekbekoe / @tjprescott Please have a look when you get a chance. Thanks

Adding sql elastic-pools scenario tests

---

packaged_releases/HISTORY.md
packaged_releases/debian/README.md
packaged_releases/debian/debian_build.sh
packaged_releases/debian/debian_dir_creator.sh
packaged_releases/docker/Dockerfile
packaged_releases/homebrew/README.md

Squashed commits:
[9076c73] Debian - Packaged release version 0.1.6 changes
[bdabec2] Docker - Packaged release version 0.1.6

Release notes for packaged release 0.1.6

---

src/azure-cli-core/azure/cli/core/telemetry_upload.py

A new application insights service was created to accept track events in the new format. The goal is to separate the exported data from the data in the old format.

Update instrumentation key for telemetry

---

scripts/curl_install_pypi/install
scripts/curl_install_pypi/install.py

Closes https://github.com/Azure/azure-cli/issues/1776
After the PR is merged, the scripts should be uploaded to the storage account.

Add checksums to curl script to verify downloads

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py

Rename storage account keys list parameter

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

fix #1738, fix #1680, fix #1676, fix #1555

vm: doc and output related bug fixes

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/custom.py

Fixes #1561. Solution: when user creates ACL for a blob container, the public_access property of the container will be extracted and specific in the properties with the set of policies.

Fix #1561: Retain container permission

---

src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_params.py

Adds path completion to file type parameters in KeyVault. Fixes #1786.

[KeyVault] KeyVault path completers

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/recordings/test_acr.yaml
src/command_modules/azure-cli-acr/setup.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/recordings/test_batch_account_mgmt.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_account_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_blob_acl_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_blob_copy_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_blob_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_file_acl_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_file_copy_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_file_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_queue_scenario.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/test_storage_table_scenario.yaml
src/command_modules/azure-cli-storage/setup.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_create_vm_no_wait.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_custom_ip.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_existing_options.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_none_options.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_state_modifications.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_ubuntu.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_data_disk.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_enable_disable_boot_diagnostic.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_generalize.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_multi_nic_scenario.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_show_list_sizes_list_ip_addresses.yaml

The azure-mgmt-storage dependency to the latest stable version and update tests.

Update azure-mgmt-storage dependnecy

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/test_batch_mgmt_commands.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

- az appservice plan delete
- az storage account delete
- az vmss delete

Add confirmation prompt to more delete operations

---

src/azure-cli-core/azure/cli/core/_output.py
src/azure-cli-core/azure/cli/core/tests/test_output.py

Closes https://github.com/Azure/azure-cli/issues/1829

Table alphabetical sort if no query or table transformer set

---

src/azure-cli-core/azure/cli/core/_output.py

Closes https://github.com/Azure/azure-cli/issues/1277
```
$ az group list -otsv
/subscriptions/f3b12b9e-d468-4dc9-8adc-000000000000/resourceGroups/debekoe-啊阿锕	westus	None	debekoe-啊阿锕		None
```

Fix TSV output unable to decode non-ascii characters

---

src/azure-cli-core/azure/cli/core/azlogging.py
src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/_consts.py
src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/custom.py

Enabling file logging should be supported through 'az configure' and the CLI config system
Closes https://github.com/Azure/azure-cli/issues/1399

File logging configuration

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/test_custom.py

Fixes https://github.com/Azure/azure-cli/issues/1621

Add help text for get credentials.

---

src/azure-cli-core/azure/cli/core/_output.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py

[Network] Help text fixes

---

src/azure-cli-core/azure/cli/core/_util.py
src/azure-cli-core/azure/cli/core/application.py
src/azure-cli-core/azure/cli/core/tests/test_application.py

core: handle bom on reading file

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_client_factory.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py

Complete support for management locks

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py

[Network] Remove location parameter from Traffic Manager profile create

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_open_port.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

Closes #1982.
- **Breaking Change**: Adds required parameter: `--port`. The old default of * doesn't make sense.

[VM] Enhance vm open-port command

---

src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/azure/cli/core/test_utils/vcr_test_base.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_client_factory.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_command_type.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/test_batch_commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/test_batch_data_plane_commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/test_batch_mgmt_commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/test_batch_pool_commands.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_resource.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

Closes https://github.com/Azure/azure-cli/issues/1911

Fixes ‘Prompts for yes / no should use the -y option rather than --force #1911’

---

src/azure-cli-core/azure/cli/core/commands/arm.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

- Add documentation to the groups where available and applicable
- Tried to add at least 2 examples to each of the commands
- Reformatted the help strings so that all are similarly spaced and indented
@twitchax please give these a look

Add documentation for all of the `az vm` commands

---

azure-cli.pyproj
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_command_type.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/recordings/test_batch_jobs.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/test_batch_job_commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/test_batch_pool_commands.py

Batch enum bug fix + more tests

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Closes https://github.com/Azure/azure-cli/issues/1861

Make some documentation more generic.

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_client_factory.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py

Add support for resource links

---

scripts/automation/setup/install_modules.py
src/azure-cli-core/azure/cli/core/_util.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_custom_data.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vmss_create_custom_data.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

- add --custom-data to VM and VMSS create
- add help example for --custom-data
- add tests for both VM and VMSS --custom-data
- fix ./scripts/dev_setup.py to skip over empty folders and not fail
fixes #1382

Add --custom-data to VM and VMSS create

---

src/azure-cli-core/azure/cli/core/commands/client_factory.py

Enable the user of the CLI to specify a value to the AZURE_HTTP_USER_AGENT environment variable so as to append additional information to the user agent header.

Append AZURE_HTTP_USER_AGENT to the user agent

---

README.rst

Closes https://github.com/Azure/azure-cli/issues/2020

[Docs] Indicate update procedure

---

doc/authoring_command_modules/README.md

Based on user feedback, added links to supporting documentation necessary for authoring command modules (the actual commands themselves, help and tests)

[Docs] Update module authoring readme.

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_state_modifications.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

VM: command renaming on "access' related command

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_managed_disk.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_vm_create_ubuntu.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

vm: use same storage account defaults like portal

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/test_appservice_error_polish.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/test_linux_webapp.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/test_webapp_config.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/test_webapp_e2e.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/test_webapp_git.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/test_webapp_scale.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/test_webapp_slot.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py
src/command_modules/azure-cli-appservice/setup.py

//cc: @lmazuel, please release the azure-mgmt-web on Monday, otherwise the PR won't pass CI

Integrate newer azure-mgmt-web 

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py

vm list: avoid add None mac addresss

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py

Fix #2004: not to query key when sas presents

---

scripts/curl_install_pypi/install
scripts/curl_install_pypi/install.py

After this PR is merged, the scripts should be uploaded/published according to https://github.com/Azure/azure-cli/blob/master/scripts/curl_install_pypi/README.md.

Suggest ‘az component update’ if install dir is not empty

---

src/azure-cli-core/azure/cli/core/_config.py
src/azure-cli-core/azure/cli/core/cloud.py
src/azure-cli-core/azure/cli/core/tests/test_config.py
src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/custom.py

Also, make config file only r/w accessible to user.

Extend _config.py to support updating the config

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py

[Network] VNET-Gateway Create/Update: make peer address optional

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/credential.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/repository.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/recordings/test_acr.yaml
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/test_acr_commands.py

Fixes https://github.com/Azure/azure-cli/issues/1898 and fixes https://github.com/Azure/azure-cli/issues/1890

[ACR] Polish error messages for repository/credential commands

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_utils.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/template.json
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/recordings/test_acr.yaml

1. Check to prevent using premium storage account.
2. Increase storage api-version in template.

[ACR] Add storage account sku validation

---

src/azure-cli-core/azure/cli/core/test_utils/vcr_test_base.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/recordings/test_sql_db_mgmt.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/recordings/test_sql_elastic_pools_mgmt.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/recordings/test_sql_firewall_mgmt.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/recordings/test_sql_mgmt.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/recordings/test_sql_service_objective_mgmt.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/test_sql_commands.py

- Remove check on number of activities for elastic pool 
- Re-recorded all tests at once to make sure they do not conflict

[Sql][Test] Remove check on number of activities for elastic pool 

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/test_webapp_backup_config.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/test_webapp_backup_restore.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py

This implements the backup and restore features for web apps. Tests are tricky because I need a storage account and a database to thoroughly test everything, so I'm skipping them for now in favor of early feedback and making the code complete date.

[Web Apps] Implemented backup and restore commands for Azure CLI

---

src/azure-cli-core/azure/cli/core/_util.py
src/azure-cli-core/azure/cli/core/commands/__init__.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/commands.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/commands.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_command_type.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py

Closes https://github.com/Azure/azure-cli/issues/1952

Show commands should return empty string with exit code 0 for 404 responses

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py

[Network] Fix issues with some App-Gateway subresource creates

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py

Starting with the top 10 right now (next 20 on the way)!

Add examples for most popular network commands.

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_api_check.py

Fixes https://github.com/Azure/azure-cli/issues/1975
```sh
>az resource show -n azure-cli-buildagent-02-ip
--resource-group/-g is required.
```
```sh
>az resource show -n azure-cli-buildagent-02-ip --namespace microsoft.network
--resource-group/-g is required.
```
@troydai

Fix a bad flag check.

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

Fix #2185, where updating the threshold parameter would not work.

[Network] AppGateway Fix

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py

Fix #2176: fixes for SDK changes for AppService.

---

src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/custom.py

Closes https://github.com/Azure/azure-cli/issues/2194

Switch question ordering for ‘az configure’

---

src/command_modules/azure-cli-acs/setup.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/test_acs_create_update.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py
src/command_modules/azure-cli-vm/setup.py

Rev compute package to 0.33.rc1

---

src/azure-cli-core/azure/cli/core/_help.py

```
$ az
Welcome to Azure CLI!
---------------------
Use `az -h` to see available commands or go to https://aka.ms/cli.
Telemetry
---------
The Azure CLI collects usage data in order to improve your experience.
The data is anonymous and does not include commandline argument values.
The data is collected by Microsoft and shared with the community.
You can change your telemetry settings with `az configure`.
/\
/  \    _____   _ _ __ ___
/ /\ \  |_  / | | | \'__/ _ \
/ ____ \  / /| |_| | | |  __/
/_/    \_\/___|\__,_|_|  \___|
Welcome to the cool new Azure CLI!
Here are the base commands:
account   : Manage subscriptions.
acr       : Manage Azure container registries.
acs       : Manage Azure Container Services.
...
```
A config value is stored like so:
```
[core]
first_run = yes
```

Show privacy statement on first invocation of ‘az’ command

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_defaults.py

Please take this fix for the upcomign release. This impacts to create VM from windows custom image

VM: fix a casing issue on check os type

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py

Closes #2180.
This matches the portal behavior.

[Network] Add delete confirmation for DNS record-set delete.

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py

[Network] Fix VPN connection create shared-key validator.

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py

Fixes #2258. Fixes #2259.  @johanste recommend we include this in the release.

[Compute] Fix command name and erroneous help entries

---

src/azure-cli-core/azure/cli/core/_help.py

Update privacy statement

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_params.py

core:support login to specific tenant

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands_thru_mock.py

It appears using mock's autospec might generate mock object which can not be de-serialized by python sdk runtime, so fall back to manual faked object.

AppService/Test: fix 2 unit tests

---

azure-cli.pyproj
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_unit_tests.py

Fixes #2336.  Adds unit tests to protect against regression.

[Network] Fix NIC subresource add command

---

src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/help.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/params.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/test_sql_commands.py

The service objective API is replaced by the capabilities API. Capabilities commands will be implemented in the near future.

Removed SQL service-objective commands.

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands_thru_mock.py

appservice: fix a bug on detecting argument value for site configs

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py

[AppService] Remove tab completion from 'appservice plan create' plan parameter

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py

[VM] Fix bug in vm show

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/test_network_nic_convenience_commands.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py

Fixes issues with network live tests:
- Fixes issue with NicConvenienceScenarioTest where the supplied username was rejected
- Fixes issue with VnetPeeringCreate where commands in the set up steps hadn't been updated for a command change.

[Network] Network live test fixes

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Partially fixes https://github.com/Azure/azure-cli/issues/2402

Reduce the default number of masters.

---

azure-cli2017.pyproj
azure-cli2017.sln

Creates a solution and proj file for VS2017 (Preview) and updates which folders are included for recent changes to the structure. The old 2015 project file is preserved under the original name. The new solution and project files have 2017 after the end.

Create VS2017 version of proj file.

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/test_custom.py

Do a better job merging credentials

---

src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_command_type.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_params.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_validators.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/custom.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/data/batch-pool-create.json
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/data/batchCreatePool.json
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/data/batchCreateTask.json
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/recordings/test_batch_account_mgmt.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/recordings/test_batch_application_mgmt.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/recordings/test_batch_certificate_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/recordings/test_batch_job_list_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/recordings/test_batch_jobs.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/recordings/test_batch_pool_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/recordings/test_batch_pools.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/recordings/test_batch_task_create_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/test_batch_commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/test_batch_data_plane_command_base.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/test_batch_data_plane_commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/test_batch_job_commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/test_batch_mgmt_commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/test_batch_pool_commands.py
src/command_modules/azure-cli-batch/setup.py

@troydai, @xingwu1, @derekbekoe
Here are the latest changes for the new Batch API.
The test suite will not pass until the new Mgmt SDK goes public (today) but because we want this merged before next release if would be great if we could start reviewing.
The breaking change is that the --run-elevated flag is no longer available on several create commands (so a net reduction in command flags).
We've also added a --keyvault flag to the account create command.
Thanks,
Anna

[Batch] Latest Batch Commands

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py

Fixes https://github.com/Azure/azure-cli/issues/2381
@lostintangent

Add some docs for az lock, remove an unused flag, rename another.

---

src/azure-cli-core/azure/cli/core/_profile.py

Closes https://github.com/Azure/azure-cli/issues/2266

Fix token "management" endpoint is being used in the place of "activeDirectoryResourceId"

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py

Closes https://github.com/Azure/azure-cli/issues/2247

Improve docs for template deployments

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/tests/test_custom_vm_commands.py

vmss: support * to list instance view across vms

---

src/command_modules/azure-cli-datalake/HISTORY.rst

Release azure-cli-datalake 0.0.1b1

---

src/command_modules/azure-cli-vm/tests/recordings/test_vmss_create_options.yaml
src/command_modules/azure-cli-vm/tests/test_vm_commands.py

The root cause was, the test was recorded before CLI adjusted the default lun number on data disks

test: fix a vm live test issue(hope it is the last one)

---

scripts/automation/release/check.py

Show module changes in simple format (full git log format still available with —git-log-verbose flag)

Module release changes check script improvements

---

src/azure-cli-core/azure/cli/core/commands/__init__.py
src/command_modules/azure-cli-batch/tests/test_batch_job_commands.py

This reverts commit f7c708d7b3f987bc8755edb515e5716221f36fa4.
Closes https://github.com/Azure/azure-cli/issues/2515
cc: @oakeyc

Revert "get choices for completion (#2476)"

---

scripts/automation/style/run.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/__init__.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_client_factory.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_validators.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/tests/test_webapp_commands.py
src/command_modules/azure-cli-appservice/tests/test_webapp_commands_thru_mock.py
src/command_modules/azure-cli-appservice/tests/test_webapp_validators.py

appservice: enable pep8 check

---

src/azure-cli-testsdk/azure/cli/testsdk/base.py
src/azure-cli-testsdk/azure/cli/testsdk/checkers.py
src/azure-cli-testsdk/azure/cli/testsdk/patches.py
src/azure-cli-testsdk/azure/cli/testsdk/preparers.py
src/azure-cli-testsdk/azure/cli/testsdk/recording_processors.py
src/command_modules/azure-cli-storage/tests/recordings/test_storage_blob_upload_midsize_file.yaml
src/command_modules/azure-cli-storage/tests/recordings/test_storage_blob_upload_small_file.yaml
src/command_modules/azure-cli-storage/tests/test_storage_blob_scenarios.py

1. Update two storage blob test cases to prepare for LBB related scenario tests.
2. Allow preparer to use existing resource during developing time.

Improve ScenarioTest and update storage test.

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py

appservice:improve table output format of web show/list

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/tests/test_custom_vm_commands.py

vm: fix the bug that missing fallback default using 'next'

---

azure-cli.pyproj
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_util.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/custom.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/help.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/params.py
src/command_modules/azure-cli-sql/setup.py
src/command_modules/azure-cli-sql/tests/recordings/test_sql_db_import_export_mgmt.yaml
src/command_modules/azure-cli-sql/tests/test_sql_commands.py

Add custom code to support Sas key being passed in without a "?" prefix.
Add Sas key coverage to E2E testing.
Add examples to help section.

Import/Export CLI changes for SAS key

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Fixes https://github.com/Azure/azure-cli/issues/2506

Fix kubectl version, always use latest stable.

---

src/azure-cli-core/azure/cli/core/commands/arm.py
src/azure-cli-core/tests/test_generic_update.py

[GenericUpdate] Allow values with equal sign

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-resource/tests/recordings/test_resource_id_scenario.yaml
src/command_modules/azure-cli-resource/tests/test_resource.py

//cc:@davidebbo.
Samples:
```bash
az resource update --id /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/yugangw3/providers/Microsoft.Web/sites/yugangw3-webapp/logs --set properties.applicationLogs.fileSystem.level=Information
az resource update --id /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/yugangw3/providers/Microsoft.Web/sites/yugangw3-webapp/config/web --set properties.phpVersion=5.6
az resource update --id /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/yugangw3/providers/Microsoft.Network/virtualNetworks/yugangw3-vnet --set properties.addressSpace.addressPrefixes[0]=11.0.0.0/16
```

resource: support resource id for generic resource update

---

src/azure-cli-core/azure/cli/core/_config.py
src/azure-cli-core/azure/cli/core/cloud.py
src/azure-cli-core/tests/test_cloud.py
src/azure-cli-core/tests/test_config.py
src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/custom.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/custom.py
src/command_modules/azure-cli-keyvault/tests/recordings/test_keyvault_certificate.yaml
src/command_modules/azure-cli-keyvault/tests/recordings/test_keyvault_key.yaml
src/command_modules/azure-cli-keyvault/tests/recordings/test_keyvault_mgmt.yaml
src/command_modules/azure-cli-keyvault/tests/recordings/test_keyvault_secret.yaml
src/command_modules/azure-cli-keyvault/tests/test_keyvault_commands.py
src/command_modules/azure-cli-vm/tests/recordings/test_vm_create_linux_secrets.yaml
src/command_modules/azure-cli-vm/tests/recordings/test_vm_create_windows_secrets.yaml
src/command_modules/azure-cli-vm/tests/recordings/test_vm_usage.yaml
src/command_modules/azure-cli-vm/tests/recordings/test_vmss_create_linux_secrets.yaml

Fixes an issue where querying graph during KeyVault creation fails for LiveID (Outlook, Hotmail, etc) accounts.

[KeyVault] KeyVault create fix

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/disk_encryption.py
src/command_modules/azure-cli-vm/tests/test_custom_vm_commands.py

[Compute] Fix VM help text.

---

src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/custom.py
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/help.py
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/params.py
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/validators.py

[DevTestLab] Enable Shared/Public/Private IP configuration setting on lab vm

---

src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_params.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
src/command_modules/azure-cli-profile/tests/__init__.py
src/command_modules/azure-cli-profile/tests/test_custom.py

account: do not show not enabled subscription by default

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/tests/test_custom.py

role: fix the error when supply role in guid format

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/tests/recordings/test_vmss_create_options.yaml

this surfaces when run `test_vmss_create_options` live

vmss: bug fixes on ip address handling

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py

Fixes https://github.com/Azure/azure-cli/issues/1945

Add better error messages if --namespace is missing.

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Closes https://github.com/Azure/azure-cli/issues/2528

Add GitHub templates for issues and PRs

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py

@tjprescott
Part of https://github.com/Azure/azure-cli/issues/2694

Fix lock create and delete if parent-resource-path is None

---

src/command_modules/azure-cli-dls/azure/cli/command_modules/dls/_help.py

missed help for access show. adding it.

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Fixes https://github.com/Azure/azure-cli/issues/2700

Upgrade a log from info to warning so that it is always printed.

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/_profile.py

Fix #2605. This is to be used by cloud console only
- ~[ ] Each command and parameter has a meaningful description.~
- ~[ ] Each new command has a test.~

expose an env variable for access token file

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/tests/recordings/test_vm_open_port.yaml
src/command_modules/azure-cli-vm/tests/recordings/test_vm_show_list_sizes_list_ip_addresses.yaml
src/command_modules/azure-cli-vm/tests/test_vm_actions.py
src/command_modules/azure-cli-vm/tests/test_vm_commands.py

VM/VMSS: support create from a market place image which requires plan info

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/tests/recordings/test_webapp_e2e.yaml
src/command_modules/azure-cli-appservice/tests/recordings/test_webapp_slot.yaml
src/command_modules/azure-cli-appservice/tests/test_webapp_commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/tests/recordings/test_vm_availset.yaml

Necessary fixes due to recent update of msrest to 0.4.7. Fixes #2757.
<del>- [ ] The PR has modified HISTORY.rst with an appropriate description of the change.</del>
<del>- [ ] Each command and parameter has a meaningful description.</del>
<del>- [ ] Each new command has a test.</del>

Fixes issues due to MSRest update.

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_format.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py

Fixes #1615.
<del>- [ ] Each command and parameter has a meaningful description. </del>
<del>- [ ] Each new command has a test. </del>

[Network] Remove nulls from VPN connection show/list output

---

doc/authoring_command_modules/README.md

Update test docs for running individual test and all tests in mod

---

src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/commands.py
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/validators.py
src/command_modules/azure-cli-lab/tests/lab_template.json
src/command_modules/azure-cli-lab/tests/recordings/test_lab_gallery_vm_mgmt.yaml
src/command_modules/azure-cli-lab/tests/test_lab_vm.py

[DevTestLabs] Adding scenario test to create simple Linux + Windows VM in lab

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/tests/test_command_with_configured_defaults.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py

Fix #2703 
- ~[] Each command and parameter has a meaningful description.~
- ~[x] Each new command has a test.~

core: apply configured defaults on optional arg

---

src/command_modules/azure-cli-dla/azure/cli/command_modules/dla/_help.py

---
(no changes besides help text)
(no new commands)

Minor help text fixes for ADLA help

---

src/azure-cli-core/azure/cli/core/sdk/util.py
src/command_modules/azure-cli-lab/HISTORY.rst
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/commands.py
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/help.py
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/params.py
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/validators.py
src/command_modules/azure-cli-lab/tests/__init__.py
src/command_modules/azure-cli-lab/tests/test_validators.py

fixes https://github.com/Azure/azure-cli/issues/2706

[DevTestLabs] Adding export-artifacts commands on formula

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_factory.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-storage/tests/recordings/test_storage_blob_incremental_copy.yaml
src/command_modules/azure-cli-storage/tests/test_storage.py
src/command_modules/azure-cli-storage/tests/test_storage_blob_scenarios.py
src/command_modules/azure-cli-storage/tests/test_storage_validators.py

Incremental blob copy

---

src/azure-cli-core/azure/cli/core/commands/arm.py
src/azure-cli-core/tests/test_arm.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py

Also add some tests.
Fixes https://github.com/Azure/azure-cli/issues/2695

Fix resource parsing and api version lookup.

---

src/azure-cli-core/azure/cli/core/commands/arm.py
src/azure-cli-core/azure/cli/core/commands/parameters.py
src/azure-cli-core/azure/cli/core/commands/validators.py
src/azure-cli-core/azure/cli/core/profiles/shared.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-dls/azure/cli/command_modules/dls/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_client_factory.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_vm_utils.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py

changes for 2015-* profile to work against azure stack 

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Improve error handling to hopefully help resolve:
https://github.com/Azure/azure-cli/issues/2403
See meta-parimiko discussion here:
https://github.com/paramiko/paramiko/issues/521
https://github.com/paramiko/paramiko/issues/387

Test for the existence of the private key file.

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py

Add short summary for incremental copy

---

src/azure-cli-core/azure/cli/core/_debug.py
src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/commands/client_factory.py
src/azure-cli-core/azure/cli/core/test_utils/vcr_test_base.py
src/azure-cli-core/tests/test_connection_verify.py

Closes https://github.com/Azure/azure-cli/issues/2267

Custom ca certs - Setting Requests_ca_bundle environment variable

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/tests/recordings/test_functionapp_asp_e2e.yaml
src/command_modules/azure-cli-appservice/tests/recordings/test_functionapp_consumption_e2e.yaml
src/command_modules/azure-cli-appservice/tests/test_webapp_commands.py

create function apps

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/tests/recordings/test_functionapp_asp_e2e.yaml
src/command_modules/azure-cli-appservice/tests/recordings/test_functionapp_consumption_e2e.yaml
src/command_modules/azure-cli-appservice/tests/test_webapp_commands.py

fixes in create function apps

---

Jenkinsfile

Run performance test for master and performance branches only.

---

scripts/performance/measure.py

Add az cloud list perf scenario

---

scripts/performance/measure.py

Added a couple of additional perf scenarios to capture the following use cases:
- Run a command with a first noun that does not exist (surrogate for time to do completion for az<tab>)
- Run a command with a second noun that does not exist (surrogate for time to do completion for az cloud<tab>)
- Run a command an incorrect parameter (surrogate for time to do completion of parameter names for a given command)
---
- [N/A] Each …

Performance: added more surrogate perf scenarios (infrastructure)

---

azure-cli.pyproj
src/azure-cli-core/azure/cli/core/commands/arm.py
src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/commands.py

Fixes #2864.  
---
- N/A (not customer facing) The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).
- N/A Each command and parameter has a meaningful description.
- N/A Each new command has a test.

Support 'exception_handler' kwarg for generic update/wait

---

src/command_modules/azure-cli-monitor/HISTORY.rst
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/custom.py
src/command_modules/azure-cli-monitor/setup.py

Updating monitor SDKs based on new release of azure-mgmt-monitor version [0.2.0](https://pypi.python.org/pypi/azure-mgmt-monitor/0.2.0) and azure-monitor version [0.3.0](https://pypi.python.org/pypi/azure-monitor/0.3.0). 
---

[Monitor] Update azure-mgmt-monitor to v0.2.0 and azure-monitor to v0.3.0

---

Jenkinsfile
scripts/jenkins_build.sh
scripts/jenkins_perf.sh
scripts/performance/measure.py

Add performance configuration

---

README.md

Add instruction for updating nightly builds to pass `--upgrade` option.
cc:/ @devigned

Add information for upgrading nightly builds

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_format.py

Fix #2972.
---
N/A Each command and parameter has a meaningful description.
N/A Each new command has a test.

[Network] Fix issues with `vpn-connection create` parameters `--no-wait` and `--validate`.

---

src/command_modules/azure-cli-dla/azure/cli/command_modules/dla/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py

Enclose inline code in backticks

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Fixes https://github.com/Azure/azure-cli/issues/2594

Fix up some help text

---

src/command_modules/azure-cli-find/setup.py

Change find version no.

---

src/command_modules/azure-cli-lab/HISTORY.rst
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/_client_factory.py
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/commands.py
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/help.py
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/params.py

This is part of feature https://github.com/Azure/azure-cli/issues/2860
---

[DevTestLabs] Adding show, delete & list commands for environment in the lab

---

src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_validators.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/commands.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/tests/recordings/test_graph_group_scenario.yaml
src/command_modules/azure-cli-role/tests/test_graph.py

rbac: add full support for 'ad group'

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Fixes https://github.com/Azure/azure-cli/issues/2693

Fix support for tags in the 'acs' commands.

---

src/command_modules/azure-cli-monitor/HISTORY.rst
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/params.py

[Monitor] Modeling --actions of az monitor alert-rules create to consume JSON string

---

src/azure-cli-testsdk/azure/cli/testsdk/base.py
src/azure-cli-testsdk/azure/cli/testsdk/patches.py

Patch away the time.sleep

---

src/azure-cli-testsdk/azure/cli/testsdk/utilities.py

Fix random name generator for python 2

---

scripts/automation/release/run.py
scripts/jenkins_build.sh

Build infrastructure: bdist_wheel before sdists for jenkins and release script

---

src/azure-cli-core/azure/cli/core/_help.py
src/azure-cli-core/azure/cli/core/profiles/__init__.py
src/azure-cli-core/azure/cli/core/profiles/_shared.py
src/azure-cli-core/tests/test_api_profiles.py

Add tests for get_api_version & supported_api_version

---

src/command_modules/azure-cli-acr/setup.py
src/command_modules/azure-cli-appservice/setup.py
src/command_modules/azure-cli-batch/setup.py
src/command_modules/azure-cli-configure/azure_bdist_wheel.py
src/command_modules/azure-cli-dla/setup.py
src/command_modules/azure-cli-dls/setup.py
src/command_modules/azure-cli-documentdb/setup.py
src/command_modules/azure-cli-iot/setup.py
src/command_modules/azure-cli-keyvault/setup.py
src/command_modules/azure-cli-network/setup.py
src/command_modules/azure-cli-shell/azure_bdist_wheel.py
src/command_modules/azure-cli-vm/setup.py

This does not change the API version of any of the SDKs. It only bumped the version of the SDK reference for SDK packages where the only change was to build with the azure_bdist_wheel extension.
---

Update sdk references to newer versions of the Azure SDK for Python

---

src/command_modules/azure-cli-monitor/setup.py

[Monitor] Update azure_mgmt_monitor to 0.2.1

---

src/command_modules/azure-cli-lab/HISTORY.rst
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/commands.py

Minor improvement: Adding table formatter for `az lab artifact-source` & `az lab arm-template`
---

[DevTestLab] Adding table formatter for arm-template and artifact-source

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py

fixes typo

---

scripts/curl_install_pypi/install
scripts/curl_install_pypi/install.py

Closes https://github.com/Azure/azure-cli/issues/2963

Install script: Show python2vs3 dependencies & check python on path

---

src/command_modules/azure-cli-dla/tests/recordings/test_dla_catalog_mgmt.yaml
src/command_modules/azure-cli-dla/tests/test_dla_commands.py

Address feedback for test readability in ADLA

---

src/command_modules/azure-cli-shell/azclishell/app.py

Allow user to use 'quit'/'exit' in any scope

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_validators.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-resource/tests/test_resource_validators.py

Addresses https://github.com/Azure/azure-cli/issues/2771
@tjprescott

Move the lock validation out to a _validator.

---

src/command_modules/azure-cli-documentdb/azure/cli/command_modules/documentdb/_command_type.py
src/command_modules/azure-cli-documentdb/azure/cli/command_modules/documentdb/_exception_handler.py
src/command_modules/azure-cli-documentdb/azure/cli/command_modules/documentdb/_params.py

* updates help description for credentials
* minor change to formatting of failure error message
* --coll-name changed to --collection-name
---

documentdb cli minor improvement

---

src/command_modules/azure-cli-shell/README.md
src/command_modules/azure-cli-shell/README.rst
src/command_modules/azure-cli-shell/azclishell/app.py
src/command_modules/azure-cli-shell/azclishell/util.py

Change clear -> clear-history to be more clear, make 'clear' clear the screen

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/cloud.py
src/azure-cli-core/tests/test_cloud.py

Closes https://github.com/Azure/azure-cli/issues/2905
---

Bug fix: New endpoints in cloud config should be saved in config for the known clouds

---

scripts/curl_install_pypi/install
scripts/curl_install_pypi/install.py
src/command_modules/azure-cli-component/azure/cli/command_modules/component/custom.py

az component update fix

---

scripts/dev_setup.py

Fix dev setup so that it reinstalls the azure-nspkg in order to get t…he declare namespace into azure/__init__.py for dev installs
---

Infrastructure: update dev_setup to ensure azure/__init__.py has the namespace package declaration for dev installs

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/tests/recordings/test_vm_availset.yaml
src/command_modules/azure-cli-vm/tests/test_vm_commands.py

This leverages server defaults 

avail-set: make "--platform-update-domain-count" arg optional

---

src/azure-cli-core/azure/cli/core/parser.py

Fix: https://github.com/Azure/azure-cli/issues/3134
Before:
After:
---

Remove option list from error logging.

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py

add git source during create

---

src/command_modules/azure-cli-shell/azclishell/argfinder.py
src/command_modules/azure-cli-shell/azclishell/az_completer.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py

a patch for #3055 so that it doesn't dump out.
---

A quick patch for storage completion errors

---

src/azure-cli/HISTORY.rst
src/azure-cli/setup.py

Include dla, dls in defaults

---

src/command_modules/azure-cli-sf/setup.py

sf: fix an invalid adal dependency which broke CI

---

packaged_releases/debian/README.md
packaged_releases/debian/debian_build.sh
packaged_releases/debian/debian_dir_creator.sh

- remove usage of dh_virtualenv now as we do it manually.

Package python in apt-get install

---

src/azure-cli/setup.py
src/command_modules/azure-cli-rdbms/HISTORY.rst
src/command_modules/azure-cli-rdbms/setup.py

Add rdbms to default install & fix version no.

---

src/command_modules/azure-cli-cognitiveservices/azure/cli/command_modules/cognitiveservices/_help.py

Fixes https://github.com/Azure/azure-cli/issues/3248
---

Add cognitive services description

---

doc/sphinx/azhelpgen/doc_source_map.json
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/_help.py

Add link to blog in ‘az interactive —help’

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py

Update short summary of managedapp

---

packaged_releases/windows/Product.wxs
packaged_releases/windows/README.md
packaged_releases/windows/azure-cli.wixproj
packaged_releases/windows/resources/ThirdPartyNotices.txt
packaged_releases/windows/scripts/prepareBuild.cmd

- Apply pip install --force-reinstall --upgrade azure-nspkg azure-mgmt-nspkg
- Remove `pip` exe.s
- Change version.
- Improve build instructions.

MSI Improvements

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_vm_diagnostics_templates.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/tests/recordings/test_diagnostics_extension_install.yaml
src/command_modules/azure-cli-vm/tests/sample-public.json
src/command_modules/azure-cli-vm/tests/test_vm_commands.py

[LAD] Updates for Linux diagnostic-related changes

---

src/command_modules/azure-cli-keyvault/setup.py
src/command_modules/azure-cli-vm/setup.py

Update KeyVault dataplane to 0.3.2.

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py

[VM-LinuxDiagnostic] Update help for vm diagnostics

---

azure-cli.pyproj
src/command_modules/azure-cli-rdbms/tests/__init__.py
src/command_modules/azure-cli-rdbms/tests/recordings/test_mysql_proxy_resources_mgmt.yaml
src/command_modules/azure-cli-rdbms/tests/recordings/test_mysql_server_mgmt.yaml
src/command_modules/azure-cli-rdbms/tests/recordings/test_postgres_proxy_resources_mgmt.yaml
src/command_modules/azure-cli-rdbms/tests/recordings/test_postgres_server_mgmt.yaml
src/command_modules/azure-cli-rdbms/tests/test_rdbms_commands.py

[RDBMS] Add Test Scenarios

---

src/command_modules/azure-cli-dls/HISTORY.rst
src/command_modules/azure-cli-dls/setup.py

This addresses a perf issue when pyOpenSSL is installed.
---

Update ADLS CLI to use latest filesystem SDK

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/tests/recordings/test_windows_vm_license_type.yaml
src/command_modules/azure-cli-vm/tests/test_vm_actions.py
src/command_modules/azure-cli-vm/tests/test_vm_commands.py

Fix #3195 
1. Expose license type for windows VM
2. Expose storage account resource id for disk/snapshot creation (only when the source is blob)

vm: trivial bugs fixes

---

src/command_modules/azure-cli-lab/HISTORY.rst
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/commands.py
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/help.py
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/params.py
src/command_modules/azure-cli-lab/tests/recordings/test_lab_gallery_vm_mgmt.yaml
src/command_modules/azure-cli-lab/tests/test_lab.py

[DevTestLabs] Adding command for claiming vm from lab

---

src/command_modules/azure-cli-monitor/HISTORY.rst
src/command_modules/azure-cli-monitor/setup.py

Fixes https://github.com/Azure/azure-cli/issues/3349
Thanks @derekbekoe for helping me validate this fix!
---

[monitor] Include autoscale template param file

---

src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/help.py

Fix MySQL and PostgreSQL help

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py

[VMSS] Update-instances fix erroneous help text

---

src/command_modules/azure-cli-lab/HISTORY.rst
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/_help.py
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/commands.py
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/custom.py
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/params.py
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/validators.py
src/command_modules/azure-cli-lab/tests/recordings/test_lab_gallery_vm_mgmt.yaml
src/command_modules/azure-cli-lab/tests/test_lab.py

This is a part of feature https://github.com/Azure/azure-cli/issues/3317
Tests are part of https://github.com/Azure/azure-cli/issues/2709
---

[DevTestLab] Adding support for claiming any VM in the lab

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/tests/recordings/test_network_watcher.yaml
src/command_modules/azure-cli-network/tests/test_network_commands.py

[Network] Fix location default for show-topology

---

azure-cli.pyproj
src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/commands/parameters.py
src/command_modules/azure-cli-monitor/HISTORY.rst
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_client_factory.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_exception_handler.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/actions.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/commands.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/custom.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/params.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/validators.py
src/command_modules/azure-cli-monitor/tests/recordings/test_monitor.yaml
src/command_modules/azure-cli-monitor/tests/test_custom.py
src/command_modules/azure-cli-monitor/tests/test_monitor.py

Closes #3135. Closes #3100. Closes #3059. Fixes #3052. Fixes #3334.
cc/ @jefffall
---

[Monitor] Revised Alert Rule Commands

---

src/command_modules/azure-cli-interactive/azclishell/app.py

Scrubs Outside Commands to just the first noun

---

src/command_modules/azure-cli-rdbms/tests/recordings/test_mysql_proxy_resources_mgmt.yaml
src/command_modules/azure-cli-rdbms/tests/recordings/test_postgres_proxy_resources_mgmt.yaml
src/command_modules/azure-cli-rdbms/tests/test_rdbms_commands.py

Seems to be failing basically every PR. <del>Bad merge/rebase perhaps?</del>
Nope, the issue was that the list log command returns only logs for the past 72 hours, so after 3 days, the test fails. Thanks to @derekbekoe for pointing this out!  I changed the test to use the --file-last-written argument to ensure the test should succeed for years (literally).
cc/ @Suna-MS

[RDBMS] Fix Proxy Tests

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_validators.py

[RBAC] Fix --key-vault help references in role module

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Addresses https://github.com/Azure/azure-cli/issues/2525

Add explicit SSL version for Python 2.7.x

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-resource/tests/test_custom.py

Fixes https://github.com/Azure/azure-cli/issues/3001

Fix some problems with prompting for parameters.

---

src/azure-cli-core/azure/cli/core/commands/parameters.py

Fix https://github.com/Azure/azure-cli/issues/3343

---

src/command_modules/azure-cli-rdbms/HISTORY.rst
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/commands.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/custom.py
src/command_modules/azure-cli-rdbms/tests/recordings/test_mysql_server_mgmt.yaml
src/command_modules/azure-cli-rdbms/tests/recordings/test_postgres_server_mgmt.yaml
src/command_modules/azure-cli-rdbms/tests/test_rdbms_commands.py

[RDBMS]Support list servers across a subscription

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/tests/recordings/test_storage_blob_upload_midsize_file.yaml
src/command_modules/azure-cli-storage/tests/recordings/test_storage_blob_upload_small_file.yaml
src/command_modules/azure-cli-storage/tests/test_storage_blob_scenarios.py

fix: https://github.com/Azure/azure-cli/issues/3430
---

Correct the parameter type of --num-results

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/tests/recordings/test_network_express_route.yaml
src/command_modules/azure-cli-network/tests/recordings/test_network_load_balancer_ip_config.yaml
src/command_modules/azure-cli-network/tests/recordings/test_network_nic_convenience_commands.yaml

Partially addresses #3386.
Also, fixes some additional express-route issues reported via email.
---

[Network] Fix Express-Route RouteFilter issue

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py

Fixes #3165.
**Table Format**
```
Name                                CurrentValue    Limit
--------------------------------  --------------  -------
Availability Sets                              0     2000
Total Regional Cores                          19      100
Virtual Machines                              16    10000
```
**TSV Format**
```
0       2000    Availability Sets
16      100     Total Regional Cores
13      10000   Virtual Machines
```
---
- [N/A] Each command and parameter …

Add table and output formatter.

---

src/azure-cli-core/azure/cli/core/_profile.py

Fix #3166. 
The change gets rid of the `global` usage and simplifies the code by just initializing the creds cache. The perf impact is minimum as the constructor of `CredsCache` has no heavy initialization logics.
Attaching profiling date for reference:
```bash
python -m cProfile D:\sdk\azure-cli\src\azure-cli\azure\cli\__main__.py
...
Ordered by: standard name
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
...
1    0.000    0.000    0.000    0.000 _profile.py:485(CredsCache)
```
No extra test coverage is needed.
~- [ ] Each command and parameter has a …

Auth: remove the 'global' keyword usages when initializes CredsCache instance

---

src/command_modules/azure-cli-vm/tests/recordings/test_custom_image.yaml
src/command_modules/azure-cli-vm/tests/test_vm_commands.py

test: add coverages for creating vm/vmss from custom images

---

src/azure-cli-core/azure/cli/core/profiles/_shared.py
src/azure-cli-testsdk/azure/cli/testsdk/recording_processors.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-network/tests/recordings/test_network_watcher.yaml
src/command_modules/azure-cli-network/tests/test_network_commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_actions.py

Fixes #3142.  Also, converts the Network Watcher tests to Scenario Test.
---

[Network] Add Nework Watcher test-connectivity test

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_vm_diagnostics_templates.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/tests/recordings/test_diagnostics_extension_install.yaml
src/command_modules/azure-cli-vm/tests/test_vm_commands.py

 vm/vmss diagnostics: provide protected settings samples, handle extension major version upgrade, etc.

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/tests/recordings/test_managed_disk.yaml
src/command_modules/azure-cli-vm/tests/test_vm_commands.py

disk/snapshot/image: expose '--tags' in the create command

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py

Fix a few code which fell through the crack.

profile: update code to load model types through get_sdk call

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_validators.py
src/command_modules/azure-cli-resource/tests/recordings/test_list_locks.yaml
src/command_modules/azure-cli-resource/tests/recordings/test_lock_create_list_delete.yaml
src/command_modules/azure-cli-resource/tests/recordings/test_lock_create_list_delete_resource_group.yaml
src/command_modules/azure-cli-resource/tests/test_locks.py
src/command_modules/azure-cli-resource/tests/test_resource_validators.py

Fix up the validator for locks

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

ensure master and agent count to be integer

---

packaged_releases/README.md
packaged_releases/bundled/README.md
packaged_releases/bundled/build-bundle.py
packaged_releases/bundled/installer

Closes https://github.com/Azure/azure-cli/issues/3376
Closes https://github.com/Azure/azure-cli/issues/3058

Bundled/versioned installer for the CLI

---

scripts/automation/tests/verify_dependencies.py

make the suppression work on minor version change

---

src/command_modules/azure-cli-dls/HISTORY.rst
src/command_modules/azure-cli-dls/azure/cli/command_modules/dls/_help.py
src/command_modules/azure-cli-dls/azure/cli/command_modules/dls/commands.py
src/command_modules/azure-cli-dls/tests/recordings/test_dls_account_mgmt.yaml
src/command_modules/azure-cli-dls/tests/test_dls_commands.py

ADLS: Add enable-key-vault command and test.

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/tests/recordings/test_vm_disk_attach_detach.yaml
src/command_modules/azure-cli-vm/tests/test_vm_commands.py

support configuring disk caching on attaching a managed disk

---

README.md

Added slack badge to readme.

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/acs_client.py

Fixes https://github.com/Azure/azure-cli/issues/3049

Change a message so as not to confuse MacOS users.

---

README.md
scripts/github_bot/HISTORY.rst
scripts/github_bot/api/app.py

- Fix formatting of Slack badge on readme
- Change version for github bot

Small fix for README badge & bot version no. change

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_factory.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/custom.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/services_wrapper.py
src/command_modules/azure-cli-storage/tests/recordings/test_metrics_operations.yaml
src/command_modules/azure-cli-storage/tests/recordings/test_show_usage.yaml
src/command_modules/azure-cli-storage/tests/test_storage_account_scenarios.py
src/command_modules/azure-cli-storage/tests/test_storage_validators.py

1. Enable them property accept account credential from environment.
2. Fix CORS command when services options are not given properly
---

Update storage metrics, logging and CORS commands

---

scripts/package_verify.sh
scripts/setup.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

I'm not going to wait for the approval since it is fixing a build break. Leave your concerns as comments.

Fix master branch failure in Travis

---

src/azure-cli-core/azure/cli/core/commands/_introspection.py
src/azure-cli-core/azure/cli/core/commands/arm.py
src/command_modules/azure-cli-interactive/azclishell/az_completer.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py

Please review the changes carefully.

Fix the too-many-nested-blocks pylint issues

---

src/azure-cli-core/azure/cli/core/_config.py
src/azure-cli-core/azure/cli/core/application.py
src/azure-cli-core/azure/cli/core/decorators.py
src/azure-cli-core/azure/cli/core/profiles/_shared.py
src/azure-cli-core/azure/cli/core/telemetry_upload.py
src/azure-cli-core/tests/test_command_registration.py
src/azure-cli-core/tests/test_help.py
src/azure-cli-core/tests/test_output.py
src/azure-cli-core/tests/test_profile.py
src/azure-cli-core/tests/test_progress.py
src/azure-cli-testsdk/azure/cli/testsdk/vcr_test_base.py
src/command_modules/azure-cli-appservice/tests/test_webapp_commands_thru_mock.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_command_type.py
src/command_modules/azure-cli-batch/tests/test_batch_commands.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-sf/azure/cli/command_modules/sf/custom.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_format.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/tests/test_custom_vm_commands.py
src/command_modules/azure-cli-vm/tests/test_vm_commands.py

I pick the pylint disable statements with fewer occurrences and begin eliminating them. In most of the cases, the statements are not needed anymore. And for others, I made some minor change.

Remove various pylint disable statements

---

src/azure-cli-core/azure/cli/core/_output.py
src/azure-cli-core/tests/test_output.py
src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py

output: add support for picking table output fields through jmespath query 

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/tests/recordings/latest/test_network_local_gateway.yaml
src/command_modules/azure-cli-network/tests/test_network_commands.py

Fixes #3562. This was caused by using positional parameters to create an SDK object rather than keyword arguments. As such, I did a scan of all network commands to identify where this kind of bug could occur due to an SDK change in the future and change them all to use kwargs. 
Also, improved the local-gateway create test to include this parameter to protect again regressions.
---

[Network] Fix local gateway create

---

src/command_modules/azure-cli-resource/HISTORY.rst
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-resource/tests/test_custom.py

Fixes part of https://github.com/Azure/azure-cli/issues/3492

Fix up some parsing and error messages.

---

src/command_modules/azure-cli-acs/tests/recordings/latest/test_acs_create_kubernetes.yaml
src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/commands.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/tests/recordings/latest/test_revoke_sp_for_rbac.yaml
src/command_modules/azure-cli-role/tests/test_graph.py

rbac: clean up role assignments and related AAD application when delete a service principal

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-resource/tests/recordings/latest/test_group_deployment_thru_uri.yaml
src/command_modules/azure-cli-resource/tests/test_resource.py

Fixes https://github.com/Azure/azure-cli/issues/3603
@tjprescott (since he was assigned...)

Add parameter checking for template link templates

---

doc/configuring_your_machine.md

Small fix to the machine config doc
---

Fix path for virtual environment activation

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/tests/test_vm_actions.py

fix typos in error message

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/blob.py

Fix #3592: covert generator to list in batch download dryrun

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/services_wrapper.py

Rephrase exception message from CORS add

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/commands/client_factory.py
src/azure-cli-core/azure/cli/core/commands/parameters.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_client_factory.py

core: Create subscription clients with right SDK profile

---

src/command_modules/azure-cli-network/tests/recordings/latest/test_network_watcher_packet_capture.yaml
src/command_modules/azure-cli-network/tests/recordings/latest/test_network_watcher_troubleshooting.yaml
src/command_modules/azure-cli-network/tests/test_network_commands.py

[Network] Re-enable Network Watcher tests

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/tests/recordings/latest/test_vm_create_by_attach_os_and_data_disks.yaml
src/command_modules/azure-cli-vm/tests/recordings/latest/test_vm_create_by_attach_unmanaged_os_and_data_disks.yaml
src/command_modules/azure-cli-vm/tests/test_vm_commands.py

vm: support attaching data disks on vm create

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py

Fix text in "az vm get-boot-log".
---

Fixed _help.py for get-boot-log

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py

Fix #3600 
- [x ] Each command and parameter has a meaningful description.

webapp: improve the help of 'az webapp log tail/download'

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py

Fixes https://github.com/Azure/azure-cli/issues/3253

Add a bunch of help text for resource link commands

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/tests/recordings/latest/test_network_nic.yaml
src/command_modules/azure-cli-network/tests/recordings/latest/test_network_vnet.yaml
src/command_modules/azure-cli-network/tests/test_network_commands.py

Closes #3558. Closes #3615. Partial fix for #3386.
@troydai I tried converting this to a scenario test, but ran into bizarre behavior when I tried to record the test. When I record the test with the old test base, it works fine, so I kept it as is.
---

[Network] Add support for --dns-servers to NIC create/update and VNET update.

---

doc/recording_vcr_tests.md

Update document: recording_vcr_tests.md

---

azure-cli2017.pyproj
src/azure-cli-core/azure/cli/core/commands/template_create.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_params.py

Closes #675.
Also removes the dead code for the old folded parameters that the Fat Client used to use.
---

Remove final instances of argparse.SUPPRESS

---

scripts/curl_install_pypi/install

Closes https://github.com/Azure/azure-cli/issues/3363

Install script: Fix sha256sum missing space & Use sha256sum with shasum as fallback

---

src/azure-cli-core/azure/cli/core/application.py
src/azure-cli-core/azure/cli/core/commands/client_factory.py
src/azure-cli-core/tests/test_application.py
src/azure-cli-testsdk/azure/cli/testsdk/base.py

Address issue: https://github.com/Azure/azure-cli/issues/3647
---

Refresh client request id for each command execution.

---

src/command_modules/azure-cli-network/tests/recordings/latest/test_network_nic.yaml
src/command_modules/azure-cli-network/tests/test_network_commands.py

Work was already done for troubleshooting #3647. With #3655 merged, this now succeeds.
---

[Network] Convert NIC test to ScenarioTest base

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py

Release azure-cli-core 2.0.8

---

src/command_modules/azure-cli-redis/HISTORY.rst

Release azure-cli-redis 0.2.5

---

src/command_modules/azure-cli-profile/HISTORY.rst

Take 2, this commit tweak the history file to trigger release bot again.
---

Release azure-cli-profile 2.0.6

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py

Fixed bad managed app example

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py

Release azure-cli-core 2.0.9

---

src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py

ad: add missing comment helps

---

packaged_releases/HISTORY.md

Update package release history

---

src/azure-cli-core/azure/cli/core/commands/__init__.py

Add a Safe Check to template deployment values

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py

Correct resource group arguments in vm user help

---

src/azure-cli-core/azure/cli/core/commands/__init__.py

Safe Get Key Error for Template Progress

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_vm_diagnostics_templates.py
src/command_modules/azure-cli-vm/tests/recordings/latest/test_diagnostics_extension_install.yaml
src/command_modules/azure-cli-vm/tests/sample-public.json

[LAD] Fix a typo in default Linux Diagnostic extension config

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/tests/recordings/latest/test_network_nic.yaml
src/command_modules/azure-cli-network/tests/test_network_commands.py

Add accelerated networking flag to NIC update/create

---

doc/scenario_base_tests.md

This PR updates `scenario_base_tests.md` with information about the relationship to [azure-devtools](https://github.com/Azure/azure-python-devtools).
It didn't need much modification to the samples as the compatibility layer in `azure.cli.testsdk` ensures the tests run without changes. However, I did a bunch of proofreading as well.

Devtools doc update

---

src/command_modules/azure-cli-cloud/HISTORY.rst
src/command_modules/azure-cli-cloud/azure/cli/command_modules/cloud/custom.py

Closes https://github.com/Azure/azure-cli/issues/3339
---

Provide an option to select the profile while selecting default cloud

---

src/azure-cli-core/azure/cli/core/telemetry.py
src/azure-cli-core/azure/cli/core/telemetry_upload.py

Update telemetry to report parameters in a better form

---

src/command_modules/azure-cli-interactive/HISTORY.rst

Fix Master failure for history.rst checks

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py

acr              : Manage Azure container registries.
acs              : Manage Azure Container Services.
---

Change help to be consistent with ACS and others

---

src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-testsdk/azure/cli/testsdk/patches.py
src/azure-cli-testsdk/azure/cli/testsdk/vcr_test_base.py
src/azure-cli/azure/cli/main.py

stop the template progress calls that don't have verbose

---

packaged_releases/bundled/build-bundle.py

Closes https://github.com/Azure/azure-cli/issues/3800

Add the 'packaging' package and it's required on some distros

---

src/command_modules/azure-cli-batch/HISTORY.rst
src/command_modules/azure-cli-batch/setup.py

Release azure-cli-batch 3.0.2

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/setup.py

Release azure-cli-acs 2.0.9

---

src/command_modules/azure-cli-consumption/HISTORY.rst
src/command_modules/azure-cli-consumption/setup.py

Release azure-cli-consumption 0.1.2

---

src/command_modules/azure-cli-cdn/HISTORY.rst
src/command_modules/azure-cli-cdn/setup.py

Release azure-cli-cdn 0.0.5

---

src/command_modules/azure-cli-lab/HISTORY.rst
src/command_modules/azure-cli-lab/setup.py

Release azure-cli-lab 0.0.7

---

src/command_modules/azure-cli-profile/HISTORY.rst
src/command_modules/azure-cli-profile/setup.py

Release azure-cli-profile 2.0.7

---

src/command_modules/azure-cli-dls/HISTORY.rst
src/command_modules/azure-cli-dls/setup.py

Release azure-cli-dls 0.0.9

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/setup.py

Release azure-cli-network 2.0.9

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py

Release azure-cli-core 2.0.10

---

src/command_modules/azure-cli-find/HISTORY.rst
src/command_modules/azure-cli-find/setup.py

Release azure-cli-find 0.2.5

---

src/command_modules/azure-cli-dla/HISTORY.rst
src/command_modules/azure-cli-dla/setup.py

Release azure-cli-dla 0.0.9

---

src/command_modules/azure-cli-taskhelp/HISTORY.rst
src/command_modules/azure-cli-taskhelp/setup.py

Release azure-cli-taskhelp 0.1.4

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/setup.py

Release azure-cli-vm 2.0.9

---

src/command_modules/azure-cli-rdbms/HISTORY.rst
src/command_modules/azure-cli-rdbms/setup.py

Release azure-cli-rdbms 0.0.4

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/setup.py

Release azure-cli-storage 2.0.9

---

src/command_modules/azure-cli-sf/HISTORY.rst
src/command_modules/azure-cli-sf/setup.py

Release azure-cli-sf 1.0.4

---

src/command_modules/azure-cli-monitor/HISTORY.rst
src/command_modules/azure-cli-monitor/setup.py

Release azure-cli-monitor 0.0.7

---

src/command_modules/azure-cli-iot/HISTORY.rst
src/command_modules/azure-cli-iot/setup.py

Release azure-cli-iot 0.1.8

---

src/command_modules/azure-cli-configure/HISTORY.rst
src/command_modules/azure-cli-configure/setup.py

Release azure-cli-configure 2.0.9

---

src/command_modules/azure-cli-redis/HISTORY.rst
src/command_modules/azure-cli-redis/setup.py

Release azure-cli-redis 0.2.6

---

src/command_modules/azure-cli-cloud/HISTORY.rst
src/command_modules/azure-cli-cloud/setup.py

Release azure-cli-cloud 2.0.5

---

src/command_modules/azure-cli-resource/HISTORY.rst
src/command_modules/azure-cli-resource/setup.py

Release azure-cli-resource 2.0.9

---

src/command_modules/azure-cli-billing/HISTORY.rst
src/command_modules/azure-cli-billing/setup.py

Release azure-cli-billing 0.1.2

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/setup.py

Release azure-cli-appservice 0.1.9

---

src/command_modules/azure-cli-interactive/HISTORY.rst
src/command_modules/azure-cli-interactive/setup.py

Release azure-cli-interactive 0.3.5

---

src/command_modules/azure-cli-keyvault/HISTORY.rst
src/command_modules/azure-cli-keyvault/setup.py

Release azure-cli-keyvault 2.0.7

---

src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/setup.py

Release azure-cli-role 2.0.7

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/setup.py

Release azure-cli-acr 2.0.7

---

src/command_modules/azure-cli-cognitiveservices/HISTORY.rst
src/command_modules/azure-cli-cognitiveservices/setup.py

Release azure-cli-cognitiveservices 0.1.5

---

src/command_modules/azure-cli-cosmosdb/HISTORY.rst
src/command_modules/azure-cli-cosmosdb/setup.py

Release azure-cli-cosmosdb 0.1.9

---

src/command_modules/azure-cli-sql/HISTORY.rst
src/command_modules/azure-cli-sql/setup.py

Release azure-cli-sql 2.0.6

---

src/command_modules/azure-cli-feedback/HISTORY.rst
src/command_modules/azure-cli-feedback/setup.py

Release azure-cli-feedback 2.0.5

---

src/azure-cli-testsdk/setup.py

Update azure-cli-testsdk dependency

---

src/azure-cli-core/azure/cli/core/keys.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_actions.py

Fixes https://github.com/Azure/azure-cli/issues/2827

Fix up ssh key generation dependencies.

---

src/azure-cli-core/azure/cli/core/profiles/_shared.py
src/command_modules/azure-cli-acr/setup.py
src/command_modules/azure-cli-acs/setup.py
src/command_modules/azure-cli-network/setup.py
src/command_modules/azure-cli-resource/setup.py
src/command_modules/azure-cli-vm/setup.py

azure-mgmt-resource was updated to 1.1.0 and azure-mgmt-compute to 1.0.0  to support AzureStack. This PR makes necessary changes to consume these packages in CLI.
---

2017-03-09-profile updates to api versions

---

scripts/setup.py
src/azure-cli-testsdk/setup.py

Ping azure-devtools version

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/latest/test_list_locks.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/latest/test_lock_create_list_delete.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/latest/test_lock_create_list_delete_resource_group.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_locks.py

Add support for resource level locks.

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_validators.py

Fixes https://github.com/Azure/azure-cli/issues/3758

Add some validation for empty parameters

---

src/azure-cli-core/azure/cli/core/commands/__init__.py

Send Template Progress Requests every 10 seconds instead of every 1 second

---

scripts/batch/app/install.sh
scripts/batch/app/run_test.sh
scripts/batch/app/schedule.py
scripts/batch/app/schedule.sh
scripts/batch/build_all.sh
src/azure-cli-core/azure/cli/core/tests/test_api_profiles.py
src/azure-cli-core/azure/cli/core/tests/test_cloud.py
src/azure-cli-core/azure/cli/core/tests/test_output.py
src/azure-cli-core/azure/cli/core/tests/test_progress.py
src/azure-cli-core/azure/cli/core/tests/test_telemetry.py
src/azure-cli-testsdk/setup.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/__init__.py
src/command_modules/azure-cli-cognitiveservices/azure/cli/command_modules/cognitiveservices/tests/__init__.py
src/command_modules/azure-cli-find/azure/cli/command_modules/find/tests/__init__.py
src/command_modules/azure-cli-interactive/azclishell/gather_commands.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/tests/test_completion.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/tests/test_feedback.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/tests/test_gather.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/tests/test_query_injection.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/tests/test_shell_progress.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/tests/test_telemetry.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/tests/test_tree.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/__init__.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_api_check.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/__init__.py

1. Build scripts for build both product and test codes.
2. Application scripts for dispatch and set up tests in Azure Batch.
1. Make tests themselves packages.
2. Remove docstring in test methods so that when listing tests using
nosetests, their method names are exposed correctly.

Add supporting scripts for running automation in Azure Batch

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_acr_integration.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py
src/command_modules/azure-cli-appservice/setup.py

webapp: support to retrieve creds from acr

---

src/command_modules/azure-cli-storage/__init__.py

Remove __init__.py from storage command module foldee

---

src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/recordings/latest/test_sql_dw_mgmt.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/test_sql_commands.py

Fixed DW live test failure and rerecord

---

src/command_modules/azure-cli-interactive/azclishell/app.py

Specify output for interactive mode on windows

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/latest/test_group_deployment.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/latest/test_group_deployment_thru_uri.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/latest/test_list_locks.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/latest/test_lock_create_list_delete.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/latest/test_lock_create_list_delete_resource_group.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/latest/test_managedappdef.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/latest/test_resource_group.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_locks.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/test_sql_commands.py

Fix: https://github.com/Azure/azure-cli/issues/3890
---

Update resource tests

---

scripts/__init__.py
scripts/automation/tests/nose_helper.py
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/azure/cli/core/azlogging.py
src/azure-cli-core/azure/cli/core/tests/test_logging.py
src/azure-cli-testsdk/azure/cli/testsdk/base.py
src/azure-cli-testsdk/azure/cli/testsdk/vcr_test_base.py
src/azure-cli/azure/cli/main.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py

fix issues: https://github.com/Azure/azure-cli/issues/3895
pave the way for resolving: https://github.com/Azure/azure-cli/issues/3878
this change also includes an extensive overhaul of azlogging.py. the logger will be class based and offer cleaner layout of the code.

Update automation mechanism

---

.gitignore
src/command_modules/azure-cli-acr/setup.py
src/command_modules/azure-cli-sql/setup.py
src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/custom.py
src/command_modules/azure-cli-storage/setup.py

Fix: https://github.com/Azure/azure-cli/issues/3930
---

Enable https only storage account creation.

---

azure-cli.pyproj
src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vmss_create_none_options.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vmss_create_options.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vmss_existing_lb.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

[VMSS] Fix issue when creating scale set with existing LB/AG

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_linux_webapp.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py

webapp:fix the bug that listing linux webapp returns nothing

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/azure-cli-testsdk/azure/cli/testsdk/base.py
src/command_modules/azure-cli-profile/HISTORY.rst
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_help.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vm_msi.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vmss_msi.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py
src/command_modules/azure-cli-vm/setup.py

vm/vmss: support managed identity

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Add orchestrator DockerCE for acs module

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vmss_public_ip_per_vm_custom_domain_name.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

vmss: fix a bug that dnsserver is not configured right

---

src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/tests/test_gather.py

Remove docstring in test code, which is breaking automation.

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/azure-cli-core/setup.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/tests/test_custom.py

- [n/a ] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

login: port cloud console login flow from CLI 1.0 to 2.0

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py

Fixed typo "assiggnment" to "assignment"

---

src/command_modules/azure-cli-cosmosdb/HISTORY.rst
src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/custom.py

Added missing kind parameter required when adding a partition key

---

src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_client_factory.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/latest/test_network_subnet_private_access.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/latest/test_network_subnet_set.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py
src/command_modules/azure-cli-network/setup.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vmss_nics.yaml
src/command_modules/azure-cli-vm/setup.py

[Network] VNET Private Access feature

---

scripts/automation/tests/verify_dependencies.py
src/command_modules/azure-cli-cloud/HISTORY.rst
src/command_modules/azure-cli-cloud/azure/cli/command_modules/cloud/custom.py

Change API version for cloud metadata endpoint

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/util.py

Fix #4012: Make batch doownload error consistent

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vmss_create_with_app_gateway.yaml

Next time, for big methods with lots of conditions, let us do less common code extracting unless we have unit tests
- [n/a ] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

vmss: fix the regression on creating with app-gateway

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_client_factory.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vm_create_ubuntu.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vmss_public_ip_per_vm_custom_domain_name.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

---
- [n/a ] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).
- [ n/a] Each command and parameter has a meaningful description.
- [ n/a] Each new command has a test.

vm: fix live test failure

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/latest/test_network_app_gateway_redirect_config.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py

Fixes #4063 and adds test scenario. 
---

[Network] Fix issues with redirect-config create/update

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

acs module fix help messages

---

doc/sphinx/azhelpgen/doc_source_map.json
src/command_modules/azure-cli-container/README.rst

Fix container module readme style

---

scripts/automation/tests/nose_helper.py
scripts/automation/tests/run.py

Add --test option to run_tests command

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/2017-03-09-profile/test_network_nic_stack.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py

Add nic tests for targeting stack cloud using 2017-03-09-profile
---

Add NIC tests for AzureStack

---

src/command_modules/azure-cli-batch/HISTORY.rst
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/__init__.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_client_factory.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_help.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_validators.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/custom.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/generate_full_cli_help.bat
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/recordings/batch_help_full.txt
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/recordings/batch_short_help.txt
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/recordings/latest/test_batch_certificate_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/recordings/latest/test_batch_job_list_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/recordings/latest/test_batch_jobs_and_tasks.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/recordings/latest/test_batch_pool_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/recordings/latest/test_batch_pools_and_nodes.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/recordings/latest/test_batch_task_create_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/test_batch_commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/test_batch_data_plane_commands.py
src/command_modules/azure-cli-batch/setup.py

Updated to latest Batch SDK

---

src/command_modules/azure-cli-container/azure/cli/command_modules/container/tests/__init__.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/tests/recordings/latest/test_container_create.yaml
src/command_modules/azure-cli-container/azure/cli/command_modules/container/tests/recordings/latest/test_container_create_with_acr.yaml
src/command_modules/azure-cli-container/azure/cli/command_modules/container/tests/test_container_commands.py

Add scenario test for `container` module

---

src/command_modules/azure-cli-dls/HISTORY.rst
src/command_modules/azure-cli-dls/azure/cli/command_modules/dls/custom.py
src/command_modules/azure-cli-dls/setup.py

Enable dls progress controller #4072

---

src/command_modules/azure-cli-container/HISTORY.rst

cc: @tjprescott 
@vjrantal also though code review should have caught this :)
I would like to automate this check but haven't found a way to do it yet.
Will keep it in mind.

Fix history for container module

---

.gitignore
src/azure-cli-core/azure/cli/core/profiles/_shared.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/latest/test_storage_queue_stats.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/latest/test_storage_table_stats.yaml
src/command_modules/azure-cli-storage/setup.py
src/command_modules/azure-cli-vm/setup.py

Fix issue in storage api version and command reg

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py

add more acs preview regions

---

src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py

- Can't use uppercase letter  for --name option
- Need specify memory and cpu options for Windows
---

Modify typo and add options

---

scripts/automation/tests/verify_dependencies.py

Closes https://github.com/Azure/azure-cli/issues/4163

CI: Allow an exception for requests and idna

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py

Wire up url-path-map rule create validator.

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py

related to #4184 
---
--  NN: Documentation update only
--  NN: Documentation update only

improve doc for app gw rule settings

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_command_type.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py

Fix two command issues in 2017-03-09 profile

---

src/command_modules/azure-cli-appservice/setup.py

Locking vsts-cd-manager to version 0.118.0

---

appveyor.yml
doc/sphinx/azhelpgen/azhelpgen.py
doc/sphinx/make.bat

1. Update the make.bat to support profile (version)
2. Update the CI script
2.1 Generate *.yml for all profiles
2.2 Delete all *.yml and folders in docs-ref-autogen
2.3 Change robocopy

Update CI for Azure CLI

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

correct sshMaster0 port number

---

doc/sphinx/azhelpgen/azhelpgen.py

Fix the command group duplication error

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_linux_webapp_quick_create_cd.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_win_webapp_quick_create_cd.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py

webapp: fix an exception when create a new git based linux webapp

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py

remove eastus out of acs preview regions

---

src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py

Fix parameter name in help for az container create

---

cli_license_terms.md
src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/util.py

Add legal note to --version

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py

[VM] Fix --no-wait option on `availability-set create`

---

appveyor.yml

Fix the environment parameter error in build

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vmss_with_ilb.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

vmss create:  fix a crash when create a scale-set with an internal LB

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py

Fixes https://github.com/Azure/azure-cli/issues/2376
---
- [ na] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).
- [ na] Each command and parameter has a meaningful description.
- [ na] Each new command has a test.

changed docs for generate ssh key location

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/test_custom.py

This is just to trigger Travis using a dev version of msrest

Msrest 0.4.12/13 fix

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/test_custom.py

[ACS] Using progress bar and logger instead of sys.out.write

---

src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py

'container' and 'environment' spelled incorrectly
---

fix typos in container help

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/commands.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/commands.py
src/command_modules/azure-cli-billing/azure/cli/command_modules/billing/commands.py
src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/commands.py
src/command_modules/azure-cli-cognitiveservices/azure/cli/command_modules/cognitiveservices/commands.py
src/command_modules/azure-cli-consumption/azure/cli/command_modules/consumption/commands.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/commands.py
src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/commands.py
src/command_modules/azure-cli-dla/azure/cli/command_modules/dla/commands.py
src/command_modules/azure-cli-dls/azure/cli/command_modules/dls/commands.py
src/command_modules/azure-cli-eventgrid/azure/cli/command_modules/eventgrid/commands.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/commands.py
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/commands.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/commands.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/commands.py
src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/commands.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/commands.py
src/command_modules/azure-cli-sf/azure/cli/command_modules/sf/commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py
src/command_modules/azure-cli-taskhelp/azure/cli/command_modules/taskhelp/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py

az help should hide unsupported content for Azure Stack profile

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

improve documents of ACS

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py

[VMSS] Fix issue with `get-instance-view *`

---

scripts/automation/tests/verify_dependencies.py
src/command_modules/azure-cli-acs/setup.py
src/command_modules/azure-cli-lab/setup.py
src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/commands.py
src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/custom.py
src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/tests/recordings/latest/test_create_redis_cache.yaml
src/command_modules/azure-cli-redis/setup.py
src/command_modules/azure-cli-resource/setup.py
src/command_modules/azure-cli-role/setup.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/setup.py

Some of the allowed errors are no longer required.
If the CI passes, we know we can safely remove them.
Closes https://github.com/Azure/azure-cli/issues/4300
Helps us address https://github.com/Azure/azure-cli/issues/643

Fix dependency mismatches with Azure SDK

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vm_msi.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

- [n/a ] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

use official msi extension publisher name

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/2017-03-09-profile/test_network_nsg.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/latest/test_network_extended_nsg.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/latest/test_network_nsg.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py

Closes #4139.  Because the new parameters have the same names as the old ones (except plural) all existing scripts will continue to work.
New help text:
```
Command
az network nsg rule create: Create an NSG rule.
Arguments
--name -n           [Required]: Name of the network security group rule.
--nsg-name          [Required]: Name of the network security group.
--priority          [Required]: Rule priority, between 100 (highest priority) and 4096 (lowest
priority). Must be unique for each rule in the collection.
--resource-group -g [Required]: Name of resource group. You can configure the default group
using `az configure --defaults group=<name>`.
--access                      : Allowed values: Allow, Deny.  Default: Allow.
--description                 : Rule description.
--direction …
```

[Network] Enhance NSG rule create/update port ranges and prefixes

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/custom.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/latest/test_create_storage_account.yaml

Fix an issue detected in live test. In short, the account update storage update SDK API doesn't accept a default `Encryption` instance. Therefore, when user doesn't intend to update encryption related configuration, such instance should not be created.
Test failure trace:
```
======================================================================
ERROR: test_create_storage_account (azure.cli.command_modules.storage.tests.test_storage_account_scenarios.StorageAccountTests)
----------------------------------------------------------------------
File "/mnt/batch/tasks/shared/venv/local/lib/python2.7/site-packages/azure_devtools/scenario_tests/preparers.py", line 60, in _preparer_wrapper
fn(test_class_instance, **kwargs)
File …
```

Fix regression introduced by CMK feature

---

.github/PULL_REQUEST_TEMPLATE.md

Clarify guidance on HISTORY.rst entries

---

src/command_modules/azure-cli-servicefabric/azure/cli/command_modules/servicefabric/commands.py

Hide servicefabric cmds from stack profile

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_webapp_e2e.yaml

Various minor updates

---

src/command_modules/azure-cli-keyvault/HISTORY.rst
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/custom.py

[KeyVault] Fix resolution of secret encoding

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/commands.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/test_custom.py

[ACS] add acs list-locations command

---

src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_params.py

This reverts commit 4dc0381b7ed7c6d5105a17710d667deca4d418f3.
Reverts https://github.com/Azure/azure-cli/pull/4322 as MSI deployment is complete.

Revert "MSI: disable msi login (#4322)"

---

src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_command_type.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_validators.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_params.py

*environment* was misspelled in several error messages.

Fix some typos

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py

fix using --ids in documentation

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_custom_image.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

vm/vmss create: storage sku is not applied on data disks coming with an image

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py

[ACS] add --ssh-key-file param with default

---

src/azure-cli-testsdk/azure/cli/testsdk/base.py
src/azure-cli-testsdk/setup.py

---
Connected to https://github.com/Azure/azure-python-devtools/pull/31
Merge after^
Added processor on cli side

added record processor for slashes

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/telemetry_upload.py

Fix telemetry issue in diagnostics mode

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_create_in_different_group.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_win_webapp_quick_create.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py

webapp: able to create a webapp in a resource group other than the service plan's

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vm_msi.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_actions.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

1. `--scope` no longer has a default of current resource group, as implicit access is not favor'd
2. update msi based account field values to be more correct 

msi: improvement per review with AAD folks

---

src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_util.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/custom.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/recordings/latest/test_aad_admin.yaml
src/command_modules/azure-cli-sql/setup.py

Update SQL commands to latest SDK

---

src/command_modules/azure-cli-cdn/HISTORY.rst
src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/_help.py
src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/custom.py

[Network] Fix CDN custom-domain create

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/latest/test_group_deployment.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/latest/test_group_deployment_crossrg.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/latest/test_group_deployment_lite.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/latest/test_managedappdef.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/latest/test_resource_policy.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_resource.py

---
tests failed when creating resource with already existing name
randomized names for resources using ScenarioTest.create_random_name() 

randomized names to be more robust

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

[ACS] add orchestrator-release option for acs preview regions

---

src/command_modules/azure-cli-sql/HISTORY.rst
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/custom.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/recordings/latest/test_sql_server_mgmt.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/test_sql_commands.py

List all SQL servers in a subscription

---

src/azure-cli-core/azure/cli/core/sdk/util.py
src/command_modules/azure-cli-sql/HISTORY.rst
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/custom.py

Enable --no-wait for sql db create/update commands

---

src/command_modules/azure-cli-extension/azure/cli/command_modules/extension/custom.py

Extensions: CLI core version in debug and warn message

---

src/command_modules/azure-cli-sf/azure/cli/command_modules/sf/custom.py

Service fabric app upload concurrent file upload

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

[ACS] only expose orchestrator-release for version 2017-07-01 or above

---

src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py

Per review with //@jluk, @yangl900 

cloud console: downgrade error to warning when login/logout is invoked

---

src/command_modules/azure-cli-acs/setup.py
src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_client_factory.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_run_command_e2e.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_run_command_with_parameters.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py
src/command_modules/azure-cli-vm/setup.py

VM : support runcommand

---

src/command_modules/azure-cli-vm/HISTORY.rst

doc:add a missing heading

---

appveyor-mooncake.yml
doc/sphinx/make.bat

Add configurations for mooncake

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py

Tracking: https://github.com/Azure/azure-cli/issues/4450
---

Skip test_vpn_client_package test in CI

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_webapp_authentication.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py

---
Fixes https://github.com/Azure/azure-cli/issues/3553
authenticate using active-directory, fb, google, twitter, or microsoft
new commands: 
1. az webapp auth show
2. az webapp auth update 
- [n ] Each new command has a test.

Enable updating of authentication settings for a webapp

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/disk_encryption.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vmss_disk_encryption_e2e.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_custom_vm_commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

FYI, for above normal level of client side validations, I have notified ADE team to incorporate those into their extension component by GA.

vmss encryption: (PREVIEW) support vmss disk encryptions

---

src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/validators.py

- Fix help text typos.
- Fix incorrect error message (TYPE is required, NAMESPACE is optional)
- Fix markup formatting to use { } instead of < >

[Monitor] Fix monitor help text.

---

scripts/batch/app/install.sh
scripts/batch/app/run_test.sh
scripts/batch/app/schedule.py
scripts/batch/app/schedule.sh

These scripts were moved prematurely. It was planned to change the packaging strategy for our live test framework. However, the Morocco service isn't ready yet. Add these files back for now.
---

Add scripts for live test framework back

---

src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py

Continuation of PR #4346 - Some information was missing when that PR was accepted early.

Additional helpfile copyediting to clarify technical issues.

---

README.md

Update readme for edge build update

---

src/azure-cli-testsdk/azure/cli/testsdk/base.py

Fixes: https://github.com/Azure/azure-cli/issues/4481
---

Init applog in base to prevent from test random failure

---

src/command_modules/azure-cli-servicefabric/azure/cli/command_modules/servicefabric/_params.py
src/command_modules/azure-cli-servicefabric/azure/cli/command_modules/servicefabric/custom.py
src/command_modules/azure-cli-servicefabric/azure/cli/command_modules/servicefabric/template/linux/parameter.json

[Service Fabric] Add pfx and output

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py

It is auto-command authoring. I am still waiting for the CRP team to give me a bit context so to test it appropriately 

vm: expose perform maintenance on a vm

---

packaged_releases/homebrew/README.md
src/command_modules/azure-cli-storage/setup.py
src/command_modules/azure-cli-vm/setup.py

- Also had to change azure-multiapi-storage from 0.1.3 to 0.1.4 as 0.1.3 was a bad source distribution that was fixed in 0.1.4.

Add Homebrew packaging instructions

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/util.py

_Automation are still running. Recordings update will come up later._
---

Fix #4490: reverse to original encoding for upload

---

src/command_modules/azure-cli-servicefabric/azure/cli/command_modules/servicefabric/template/linux/template.json
src/command_modules/azure-cli-servicefabric/azure/cli/command_modules/servicefabric/template/windows/template.json

Enable DNS by default. 

---

packaged_releases/HISTORY.md

Update packaged release notes for 2.0.18

---

src/command_modules/azure-cli-billing/azure/cli/command_modules/billing/tests/test_billing_commands.py
src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/tests/test_lab.py

Tests for neither modules are ready for live test.
Follow up:
* https://github.com/Azure/azure-cli/issues/4513
* https://github.com/Azure/azure-cli/issues/4514

Skip DevTest lab and Billing tests in live test

---

src/command_modules/azure-cli-resource/HISTORY.rst
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/latest/test_invoke_action.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_resource.py

---
Fixes https://github.com/Azure/azure-cli/issues/2607
Samples (on vm resource):
`az resource invoke-action --action powerOff --ids <vm_id>`
`az resource invoke-action --action capture --ids <vm_id> --parameters {"vhdPrefix":"myPrefix","destinationContainerName":"container","overwriteVhds":"true"}`
`az resource invoke-action --action capture --ids <vm_id> --parameters @{file}`

support generic resource action invoke

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/cloud.py
src/azure-cli-core/azure/cli/core/tests/test_cloud.py
src/azure-cli-testsdk/azure/cli/testsdk/utilities.py

Closes https://github.com/Azure/azure-cli/issues/3897
Closes https://github.com/Azure/azure-cli/issues/3617
---

Address problems with 'AzureCloud' in non-concurrent scenarios

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/latest/test_resource_move.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_resource.py

---
Fixed failing test for `resource move` command. 
Changed test to new ScenarioTest format

fixed test failure with resource move

---

src/azure-cli-core/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py

[AvSet] Fix stack issue with AvailSet create

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_webapp_config.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py

---
Build failing webapp config test, fixed test and changed to new ScenarioTest format.

fixed webapp config test, changed to scenario test

---

scripts/releaser/Dockerfile
scripts/releaser/HISTORY.rst
scripts/releaser/README.md
scripts/releaser/release-homebrew.py
scripts/releaser/release.py

This can be used for new Homebrew releases.

Automate Homebrew formula generation

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/cloud.py

Closes https://github.com/Azure/azure-cli/issues/3905
---

More user-friendly handling of invalid cloud configurations

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_set_os_disk_size.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vm_create_by_attach_os_and_data_disks.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

Notes:
1. only applicable on vm, not on vmss
2. applicable on both creating and attaching

vm create: expose --os-disk-size-gb

---

src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_help.py

login/msi: fix a help error

---

src/command_modules/azure-cli-sql/HISTORY.rst
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_util.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/custom.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/params.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/recordings/latest/test_sql_db_restore_deleted.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/test_sql_commands.py

Added `az sql db list-deleted` command and `az sql db restore --deleted-time` parameter so that now deleted db's can be found and restored. 
---

Implement sql deleted database restore

---

requirements.txt
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_params.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/latest/test_delete_dependent_resources.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_resource_id_deletes.py

Fixes https://github.com/Azure/azure-cli/issues/3902
---

loops through resources to delete any possible

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_client_factory.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_webapp_update.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py

---
Fixes https://github.com/Azure/azure-cli/issues/892

webapp generic update, with test and recording

---

src/command_modules/azure-cli-storage/setup.py
src/command_modules/azure-cli-vm/setup.py

Closes https://github.com/Azure/azure-cli/issues/3988

Update azure-multiapi-storage package to take 'futures' fix

---

README.md

Closes https://github.com/Azure/azure-cli/issues/4601

Remove curl install from README

---

src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/_params.py
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/custom.py
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/tests/test_batchai_custom.py

BatchAI. CR feedback and the last minute fix.

---

src/command_modules/azure-cli-batch/HISTORY.rst
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/__init__.py
src/command_modules/azure-cli-batch/setup.py

This PR includes changes to the Batch module to support the new extension model:
- Removes imports for old extension model
- Includes azure-namespace dependencies required by new extension package
---

[Batch] Updates for new extension model

---

requirements.txt
src/azure-cli-core/azure/cli/core/commands/client_factory.py
src/azure-cli-core/azure/cli/core/profiles/_shared.py
src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_factory.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/custom.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/file.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/sdkutil.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/services_wrapper.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/util.py
src/command_modules/azure-cli-storage/setup.py
src/command_modules/azure-cli-vm/setup.py

@derekbekoe @tjprescott ping me when you're available. We need to review this together.

File Share Snapshot

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vm_lb_integration.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

Ensure we don't break this basic flow for simple scaling

test: add an end to end test for simple scale through LB

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py

When a account name is implicitly specified in the destination URI.
---

Try to fetch account key in blob batch upload

---

src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/custom.py
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/tests/test_batchai_custom.py
src/command_modules/azure-cli-batchai/setup.py

BatchAI. Switching to azure-mgmt-batchai 0.2.0

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_create_vm_from_existing_nic.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

vm show: fix a bug when using '-d' might crash

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_docker_utils.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/custom.py

[ACR] Improve login/access authorization to registries

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage_blob_scenarios.py

Quote the file paths to escape backslash
Fix #4354 
---

Fix storage test issues on Windows

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/latest/test_managedappdefInline.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/recordings/latest/test_managedappdef_inline.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_resource.py

---
Minor change to fix live test failing
Appliance -> Application

Fixed managedappdefInline test `Appliance` to `Application`

---

src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/params.py

Updated the parameter description only. 
---
- [ y] Each command and parameter has a meaningful description.
- [ na] Each new command has a test.

Enable AllowAllAzureServices by allowing start and end ip being 0.0.0.0

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py

resource: fix warning text after registered a feature

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/acs_client.py

[ACS] check existence before loading ssh_config_file

---

src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/custom.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/params.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/test_sql_commands.py
src/command_modules/azure-cli-sql/tests/recordings/test_sql_db_conn_str.yaml

Implement az sql db show-connection-string

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_format.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/commands.py

Fixes https://github.com/Azure/azure-cli/issues/4614
---

[ACR] Add table format for webhook list-events

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py

core: capture errors caused by token file corruption and make it actionable

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_functionapp_consumption_e2e.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py

---
live test was failing because function-name was taken

Fix function app test by randomizing name and convert to ScenarioTests

---

src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py

---
Fixes: https://github.com/Azure/azure-cli/issues/4653
was trying to log resource id when subscription not available

fixed problem with reforming id when missing subscription

---

requirements.txt

---
Unable to run tests in in python3 environment with older minimum versions. Updating solves these problems.

updated requirements to use latest requests and vcrpy packages

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage_blob_copy_scenarios.py

---
-problem in test where blob not yet copied before download operation
-poll until copy finished

fixed test storage blob copy

---

src/command_modules/azure-cli-resource/HISTORY.rst
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py

[Resource] Fix incompatibility with msrest 0.4.15

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/custom.py

Fixes https://github.com/Azure/azure-cli/issues/4678
---

[ACR] Change SubprocessError to CalledProcessError

---

.github/ISSUE_TEMPLATE.md

Shorter issue template

---

scripts/ci/test_static.sh
tools/automation/tests/verify_package_versions.py

This will not pass until https://github.com/Azure/azure-cli/pull/4684 is merged.

Verify package versions in CI

---

.travis.yml

Publish to edge build from dev branch

---

src/azure-cli-core/azure/cli/core/_profile.py

To better diagnose issues like #2339 

account: improve the error message when account set failed

---

src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py

Fix scenario spelling in test case name

---

src/command_modules/azure-cli-batch/HISTORY.rst
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_validators.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/batch_preparers.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/recordings/latest/test_batch_pool_cmd.yaml
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/test_batch_data_plane_commands.py
src/command_modules/azure-cli-batch/setup.py

The change was approved and accidentally merged to the master branch by me. I now create a new PR to merge it to the dev branch instead.

[Batch] pool create bug fix for --image

---

src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_command_type.py

Partially react to https://github.com/Azure/azure-cli/issues/4347
---

Update storage account help

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_params.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/custom.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/latest/test_storage_create_default_sku.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage_account_scenarios.py
src/command_modules/azure-cli-storage/setup.py

---
Fixes: https://github.com/Azure/azure-cli/issues/1950

default sku to Standard_RAGRS for storage account create

---

src/command_modules/azure-cli-container/setup.py

Fix container instance sdk version because we're publishing new sdk

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

[ACS] add retries for aks/acs create commands

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_acr_integration.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_appservice_error_polish.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_auto_delete_plan.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_create_in_different_group.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_functionapp_asp_e2e.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_functionapp_consumption_e2e.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_linux_webapp.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_linux_webapp_quick_create.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_linux_webapp_quick_create_cd.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_retain_plan.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_traffic_routing.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_webapp_authentication.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_webapp_config.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_webapp_e2e.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_webapp_git.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_webapp_scale.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_webapp_slot.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_webapp_slot_swap.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_webapp_ssl.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_webapp_update.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_win_webapp_quick_create.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_win_webapp_quick_create_cd.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py
src/command_modules/azure-cli-appservice/setup.py

Fix #4739, a prerequisite to start MSI work.
Most change is re-recording tests for good verification. Did fix a couple of test steps to align with #4674 

webapp: integrate azure-mgmt-web 0.34.1

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

[ACS] replace orchestrator_release with version and refactor

---

src/command_modules/azure-cli-backup/HISTORY.rst
src/command_modules/azure-cli-backup/setup.py
src/command_modules/azure-cli-dla/HISTORY.rst
src/command_modules/azure-cli-dla/setup.py
src/command_modules/azure-cli-dls/HISTORY.rst
src/command_modules/azure-cli-dls/setup.py
src/command_modules/azure-cli-iot/HISTORY.rst
src/command_modules/azure-cli-iot/setup.py
src/command_modules/azure-cli-keyvault/HISTORY.rst
src/command_modules/azure-cli-keyvault/setup.py
src/command_modules/azure-cli-lab/HISTORY.rst
src/command_modules/azure-cli-lab/setup.py
src/command_modules/azure-cli-monitor/HISTORY.rst
src/command_modules/azure-cli-monitor/setup.py
src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/setup.py
src/command_modules/azure-cli-rdbms/HISTORY.rst
src/command_modules/azure-cli-rdbms/setup.py
src/command_modules/azure-cli-servicefabric/HISTORY.rst
src/command_modules/azure-cli-servicefabric/setup.py
src/command_modules/azure-cli-sql/HISTORY.rst
src/command_modules/azure-cli-sql/setup.py
src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/setup.py

---
changed version of command-modules affected by: https://github.com/Azure/azure-cli/commit/53eb065f820203aa843eb3a5dbef954fbce0e909

Fixed versions from pr #4704

---

src/command_modules/azure-cli-cosmosdb/HISTORY.rst
src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_client_factory.py
src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_params.py
src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/commands.py
src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/custom.py
src/command_modules/azure-cli-cosmosdb/setup.py

Upgrade azure-mgmt-cosmosdb version to 0.2.1

---

azure-cli2017.pyproj
src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/latest/test_network_dns.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/latest/test_network_dns_zone_import_export.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_dns_zone_import.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/zone_files/zone1.txt
src/command_modules/azure-cli-network/azure/cli/command_modules/network/zone_file/configs.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/zone_file/make_zone_file.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/zone_file/parse_zone_file.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/zone_file/record_processors.py
src/command_modules/azure-cli-network/setup.py

Closes #4770. Fixes #4676. 
---

[DNS] Add CAA Record Support

---

azure-cli.pyproj
src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/latest/test_network_traffic_manager.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py

Addresses #4734.  Will keep the issue open to track removal of the workaround.
---

[Network] Fix traffic-manager update command.

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage_validators.py

---
Fixes: https://github.com/Azure/azure-cli/issues/4749
fixed validator logic and added tests

fixed copy batch commands that failed upon using `--source-uri`

---

src/command_modules/azure-cli-batchai/HISTORY.rst
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/_client_factory.py
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/_help.py
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/_params.py
src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/commands.py
src/command_modules/azure-cli-batchai/setup.py

BatchAI. Minor fixes

---

src/command_modules/azure-cli-container/HISTORY.rst
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_params.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/tests/recordings/latest/test_container_azure_file_volume_mount.yaml
src/command_modules/azure-cli-container/azure/cli/command_modules/container/tests/recordings/latest/test_container_create.yaml
src/command_modules/azure-cli-container/azure/cli/command_modules/container/tests/test_container_commands.py
src/command_modules/azure-cli-container/setup.py

Apply container instance service 10-01-preview API

---

src/command_modules/azure-cli-sql/HISTORY.rst
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/params.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/recordings/latest/test_sql_vnet_mgmt.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/test_sql_commands.py
src/command_modules/azure-cli-sql/setup.py

Adding migration flag to sql vnet commands

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

[Network] Fix issue with `--dns-servers` on VNET update

---

doc/authoring_command_modules/authoring_commands.md

Add table and completer guidance. Update --ids guidance.

Update command authoring guidance

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py

---
Fixes: https://github.com/Azure/azure-cli/issues/3940

better error messages for `deployment user set`

---

build_scripts/homebrew/formula-generate.py
build_scripts/pypi/README.md
build_scripts/pypi/build.py
build_scripts/wheels/README.md
tools/automation/__main__.py
tools/automation/clibuild/__init__.py
tools/automation/style/run.py
tools/automation/tests/run.py
tools/automation/tests/verify_package_versions.py
tools/automation/utilities/display.py
tools/automation/utilities/pypi.py
tools/scripts/azdev
tools/scripts/azdev.bat
tools/scripts/check_style
tools/scripts/check_style.bat
tools/scripts/run_tests
tools/scripts/run_tests.bat
tools/setup.py

Use entry points instead of custom scripts
Closes https://github.com/Azure/azure-cli/issues/4361 as it implements most of it for what we need right now.

‘azdev build’ for Debian, RPM, Docker, Python wheels, Homebrew

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_vm_utils.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/disk_encryption.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/recordings/latest/test_vm_secret_e2e_test.yaml
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

```bash
az vm secret add -g myGroup -n myVM --keyvault myKVInTheSameGroup --cert mycert
az vm secret delete -g myGroup -n myVM --keyvault myKVInTheSameGroup --cert mycert
az vm secret show g myGroup -n myVM
```

vm: support "vm secret add/delete/show"

---

src/command_modules/azure-cli-monitor/HISTORY.rst
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_client_factory.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_exception_handler.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/activity_log_alerts.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/commands.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/params.py
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/recordings/latest/test_monitor_activity_log_alert_update_action.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/recordings/latest/test_monitor_activity_log_alert_update_condition.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/recordings/latest/test_monitor_activity_log_alert_update_scope.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/recordings/latest/test_monitor_create_default_activity_log_alert.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/recordings/latest/test_monitor_create_disabled_activity_log_alert.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/recordings/latest/test_monitor_create_full_fledged_activity_log_alert.yaml
src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/test_monitor_activity_log_alert.py

```
(az36) troyd@TROY-THINKPAD25 C:\Users\troyd\Code\azure-cli                                                   
> az monitor activity-log alert -h                                                                           
Group                                                                                                        
az monitor activity-log alert: Manage activity log alerts.                                               
Subgroups:                                                                                                   
action: Manage action groups for activity log alerts.                                                    
scope                                                                                                    
Commands: …
```

Add activity log alert commands.

---

.flake8
src/azure-cli-core/azure/cli/core/commands/_introspection.py
src/azure-cli-core/azure/cli/core/extension.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/test_acr_commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/vsts_cd_provider.py
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/tests/test_iot_commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/test_network_commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/zone_file/parse_zone_file.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/test_resource.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/test_sql_commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_vm_commands.py

* Remove E126 escape
* Remove E741 escape
* Annotate the .flake8 file
* Fixes style violation surfaced from escape removal
---

Update flake8 setting and fix style violations

---

src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/disk_encryption.py

expose Encrypt-Format-All and Extension publisher/name options

---

src/command_modules/azure-cli-dla/HISTORY.rst
src/command_modules/azure-cli-dla/azure/cli/command_modules/dla/custom.py
src/command_modules/azure-cli-dla/azure/cli/command_modules/dla/tests/recordings/latest/test_dla_account_mgmt.yaml
src/command_modules/azure-cli-dla/azure/cli/command_modules/dla/tests/recordings/latest/test_dla_job_mgmt.yaml
src/command_modules/azure-cli-dla/setup.py
src/command_modules/azure-cli-dls/HISTORY.rst
src/command_modules/azure-cli-dls/azure/cli/command_modules/dls/tests/recordings/latest/test_dls_account_mgmt.yaml
src/command_modules/azure-cli-dls/setup.py

[ADLA - ADLS] - Object refactor

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/replication.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/webhook.py
src/command_modules/azure-cli-acr/setup.py

[ACR] Add location in creating webhooks

---

src/command_modules/azure-cli-servicefabric/azure/cli/command_modules/servicefabric/_help.py

Update example to match entry from arguments list

Update Service Fabric _help.py

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py

cloud shell: handle the case that 'oid' could be missing in a token

---

src/command_modules/azure-cli-cloud/HISTORY.rst
src/command_modules/azure-cli-cloud/azure/cli/command_modules/cloud/custom.py
src/command_modules/azure-cli-cloud/setup.py

If these endpoints are missed, the CLI fails to load.
---

Cloud registration: Prevent users from registering clouds that have missing endpoints

---

doc/configuring_your_machine.md

---
Updated the dev setup docs
-explanation on where the test and style scripts are installed. 
-updated commands to run scripts

Updated configuring_your_machine doc to not reference scripts by path

---

doc/configuring_your_machine.md

---
'clone root' for consistency

Small fix to dev setup docs.

---

src/azure-cli-core/azure/cli/core/application.py
src/azure-cli-core/azure/cli/core/commands/client_factory.py
src/azure-cli-core/azure/cli/core/parser.py
src/azure-cli-core/azure/cli/core/telemetry.py

Closes https://github.com/Azure/azure-cli/issues/4651
---

Add extension name to telemetry and UA header

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/custom.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/latest/test_create_storage_account_with_assigned_identity.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/latest/test_storage_account_service_endpoints.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/recordings/latest/test_update_storage_account_with_assigned_identity.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage_account_scenarios.py

[Storage] Fix issue with storage account create/update

---

src/command_modules/azure-cli-extension/azure/cli/command_modules/extension/_params.py

Extensions `az extension add` --yes param fix

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/recordings/latest/test_network_dns_zone_import_export.yaml

[DNS] Fix issue with DNS zone import names

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/test_custom.py
src/command_modules/azure-cli-acs/setup.py
src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/test_role_commands_thru_mock.py

Per feedback from regional directors and MVP

rbac: polish error caused by missing the permission to register graph applications

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/cloud.py
src/azure-cli-core/setup.py

Modified AzureUSGov Endpoint to .US

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_validators.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_functionapp_consumption_e2e.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_linux_webapp.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py
src/command_modules/azure-cli-appservice/setup.py

webapp/functionapp: ensure list/show display correct set of apps

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py
src/command_modules/azure-cli-acr/setup.py

[acr] typo fix in help

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/recordings/latest/test_webapp_ssl.yaml
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py

webapp: fix a bug in the cert name generation

---

src/command_modules/azure-cli-find/azure/cli/command_modules/find/__init__.py
src/command_modules/azure-cli-find/azure/cli/command_modules/find/_gather_commands.py
src/command_modules/azure-cli-find/azure/cli/command_modules/find/_params.py
src/command_modules/azure-cli-find/azure/cli/command_modules/find/commands.py
src/command_modules/azure-cli-find/azure/cli/command_modules/find/custom.py
src/command_modules/azure-cli-find/azure/cli/command_modules/find/tests/test_find.py

---
Closes: https://github.com/Azure/azure-cli/issues/4934

Knack Conversion for Find

---

src/command_modules/azure-cli-container/HISTORY.rst
src/command_modules/azure-cli-container/azure/cli/command_modules/container/_params.py
src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py
src/command_modules/azure-cli-container/setup.py

Fix container module default ports

---

doc/authoring_command_modules/authoring_commands.md
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/azure/cli/core/_help.py
src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/cloud.py
src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/azure/cli/core/commands/arm.py
src/azure-cli-core/azure/cli/core/parser.py
src/azure-cli-core/azure/cli/core/sdk/util.py
src/azure-cli-core/azure/cli/core/tests/test_cloud.py
src/azure-cli-core/azure/cli/core/util.py
src/azure-cli-core/setup.py
src/azure-cli-testsdk/azure/cli/testsdk/utilities.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_command_type.py
src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/__init__.py
src/command_modules/azure-cli-cloud/azure/cli/command_modules/cloud/__init__.py
src/command_modules/azure-cli-configure/azure/cli/command_modules/configure/__init__.py
src/command_modules/azure-cli-extension/azure/cli/command_modules/extension/__init__.py
src/command_modules/azure-cli-feedback/azure/cli/command_modules/feedback/__init__.py
src/command_modules/azure-cli-interactive/azure/cli/command_modules/interactive/__init__.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_command_type.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/__init__.py
src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/__init__.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/__init__.py
src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/__init__.py
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/__init__.py
src/command_modules/azure-cli-role/azure/cli/command_modules/role/__init__.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/__init__.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/__init__.py

- Remove `self.module_name` as no longer needed in knack 0.3.0
Closes https://github.com/Azure/azure-cli/issues/4944

Update knack dep to 0.3.0 and pin it

---

src/command_modules/azure-cli-sql/HISTORY.rst
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_util.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/commands.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/custom.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/params.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/recordings/latest/test_sql_server_connection_policy.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/test_sql_commands.py

Added sql server conn-policy show/update commands

---

src/azure-cli-core/azure/cli/core/commands/__init__.py

Fixes a bug introduced by #4893.

Fix delayed progress controller.

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py

Add description for `az role definition update`
---

Updated help

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/setup.py
src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/setup.py

Related: https://github.com/Azure/azure-multiapi-storage-python/pull/9/files
---

Update storage command module to new multiapi SDK

---

src/command_modules/azure-cli-billing/azure/cli/command_modules/billing/__init__.py
src/command_modules/azure-cli-billing/azure/cli/command_modules/billing/_client_factory.py
src/command_modules/azure-cli-billing/azure/cli/command_modules/billing/_params.py
src/command_modules/azure-cli-billing/azure/cli/command_modules/billing/commands.py
src/command_modules/azure-cli-billing/azure/cli/command_modules/billing/tests/test_billing_commands.py

Knack conversion for billing module

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py

fixed a typo in command documentation

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/recordings/latest/test_acs_create_default_service.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/recordings/latest/test_acs_create_kubernetes.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/recordings/latest/test_aks_create_default_service.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/recordings/latest/test_aks_create_with_upgrade.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/test_acs_commands.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/test_aks_commands.py

Closes #4849.
Closes Azure/AKS#42.

[AKS] fix get-credentials without directory

---

src/command_modules/azure-cli-advisor/azure/cli/command_modules/advisor/_params.py
src/command_modules/azure-cli-advisor/azure/cli/command_modules/advisor/tests/recordings/latest/test_generate_recommendations.yaml
src/command_modules/azure-cli-advisor/azure/cli/command_modules/advisor/tests/recordings/latest/test_get_set_configurations_resource_group.yaml
src/command_modules/azure-cli-advisor/azure/cli/command_modules/advisor/tests/recordings/latest/test_get_set_configurations_subscription.yaml

Using enum_choice_list to specify allowed values for parameters.

---

scripts/ci/build.sh
src/azure-cli-core/azure/cli/core/__init__.py

Limit the automation run in Travis

---

.gitignore
src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/azure/cli/core/commands/client_factory.py
src/azure-cli-core/azure/cli/core/profiles/__init__.py
src/azure-cli-core/azure/cli/core/profiles/_shared.py
src/azure-cli-testsdk/azure/cli/testsdk/vcr_test_base.py
src/command_modules/azure-cli-acs/setup.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/disk_encryption.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/tests/test_custom_vm_commands.py
src/command_modules/azure-cli-vm/setup.py

Not tested when I open this PR.

Support SDK profile for Compute 3.1.0rc1

---

requirements.txt
src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/telemetry_upload.py
src/azure-cli-core/setup.py

Related: https://github.com/Microsoft/ApplicationInsights-Python/issues/60
Fixes: #3177 #4649 
---

Fix inifinite retry issue in telemetry upload

---

src/azure-cli-core/azure/cli/core/commands/parameters.py

Ensure get_enum_type works with lists

---

src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/azure/cli/core/commands/arm.py

support extensions in client loading

---

src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py

Azure Container Instances: fix incorrect order of parameters

---

.flake8
.vscode/launch.json
scripts/ci/build.sh
scripts/ci/test_static.sh
src/azure-cli-core/azure/cli/core/commands/arm.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/__init__.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_client_factory.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_docker_utils.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_params.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_utils.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_validators.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/commands.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/credential.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/custom.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/replication.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/repository.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/recordings/latest/test_acr_create_replication.yaml
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/recordings/latest/test_acr_create_webhook.yaml
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/recordings/latest/test_acr_create_with_existing_storage.yaml
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/recordings/latest/test_acr_create_with_managed_registry.yaml
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/recordings/latest/test_acr_create_with_new_storage.yaml
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/recordings/latest/test_check_name_availability.yaml
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/test_acr_commands.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/webhook.py

Closes https://github.com/Azure/azure-cli/issues/4920
Style checks and tests re-recorded:
@djyou Please review. You can use the prompt.ws service below to do some ad-hoc testing of the commands (It takes 2/3 minutes to load so refresh the page afterwards).

ACR module knack conversion

---

src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/recordings/latest/test_sql_db_operation_mgmt.yaml

Was not able to record as the `az sql db op cancel` command always failed for service side errors, but they no longer occur
---

test: update test_sql_db_operation_mgmt test recording

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/setup.py

add korea south and korea central to acs preview regions

---

src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/batch_preparers.py
src/command_modules/azure-cli-container/HISTORY.rst
src/command_modules/azure-cli-container/setup.py
src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/setup.py

Fixes failing CI from https://github.com/Azure/azure-cli/pull/5029

Update versions of container and vm modules

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py
src/command_modules/azure-cli-appservice/setup.py

Fixes #5048: updating the zip deploy help documentation

---

azure-cli.pyproj
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/azure/cli/core/commands/__init__.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/recordings/latest/test_acr_create_replication.yaml
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/recordings/latest/test_acr_create_webhook.yaml
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/recordings/latest/test_acr_create_with_existing_storage.yaml
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/recordings/latest/test_acr_create_with_managed_registry.yaml
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/recordings/latest/test_acr_create_with_new_storage.yaml
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/tests/recordings/latest/test_check_name_availability.yaml
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/commands.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/tests/test_batch_commands.py
src/command_modules/azure-cli-billing/azure/cli/command_modules/billing/commands.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_command_type.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/commands.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/commands.py

Knack kwarg simplification.

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_params.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_validators.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

[AKS] Update the aks install/remove connector to use virtual-kubelet

---

scripts/ci/build.sh
scripts/ci/test_static.sh
src/command_modules/azure-cli-advisor/azure/cli/command_modules/advisor/__init__.py
src/command_modules/azure-cli-advisor/azure/cli/command_modules/advisor/_client_factory.py
src/command_modules/azure-cli-advisor/azure/cli/command_modules/advisor/_params.py
src/command_modules/azure-cli-advisor/azure/cli/command_modules/advisor/_validators.py
src/command_modules/azure-cli-advisor/azure/cli/command_modules/advisor/commands.py
src/command_modules/azure-cli-advisor/azure/cli/command_modules/advisor/tests/recordings/latest/test_generate_recommendations.yaml
src/command_modules/azure-cli-advisor/azure/cli/command_modules/advisor/tests/recordings/latest/test_get_set_configurations_resource_group.yaml
src/command_modules/azure-cli-advisor/azure/cli/command_modules/advisor/tests/recordings/latest/test_get_set_configurations_subscription.yaml
src/command_modules/azure-cli-advisor/azure/cli/command_modules/advisor/tests/test_advisor_commands.py

knack conversion for advisor module

---

src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/azure/cli/core/commands/_introspection.py
src/azure-cli-core/azure/cli/core/commands/arm.py
src/azure-cli-core/azure/cli/core/commands/parameters.py
src/command_modules/azure-cli-iot/HISTORY.rst
src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/commands.py
src/command_modules/azure-cli-iot/setup.py
src/command_modules/azure-cli-keyvault/HISTORY.rst
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/custom.py
src/command_modules/azure-cli-keyvault/setup.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-servicefabric/HISTORY.rst
src/command_modules/azure-cli-servicefabric/azure/cli/command_modules/servicefabric/custom.py
src/command_modules/azure-cli-servicefabric/setup.py
src/command_modules/azure-cli-vm/HISTORY.rst
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py
src/command_modules/azure-cli-vm/setup.py

Makes the same cleanup changes that #5081 did against the KnackConversion branch.

Fix some grammar issues

---

src/command_modules/azure-cli-cloud/azure/cli/command_modules/cloud/custom.py

Our method was copied to msrestazure so use that.

Use msrestazure method to autodetect metadata endpoints

---

README.md

Markdown button that launches cloud shell in a new browser window - suggestion to help users test drive right from the browser
---

embed cloud shell

---

azure-cli.pyproj
src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/__init__.py
src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/_client_factory.py
src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/_format.py
src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/_params.py
src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/commands.py
src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/custom.py
src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/tests/preparers.py

Implements #4921.  Tests to be re-enabled in a future PR.

[Backup] Convert Backup module to Knack

---

.flake8
azure-cli.pyproj
scripts/ci/build.sh
scripts/ci/test_static.sh
src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/__init__.py
src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_client_factory.py
src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_command_type.py
src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_exception_handler.py
src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_params.py
src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_validators.py
src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/commands.py
src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/custom.py
src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/tests/recordings/latest/test_create_database_account.yaml
src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/tests/test_documentdb_commands.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_completers.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_params.py
src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_validators.py
src/command_modules/azure-cli-rdbms/azure/cli/command_modules/rdbms/tests/recordings/latest/test_postgres_server_mgmt.yaml

Implements #4930.
WARNING: There is 0 test coverage of the data plane commands and only the most limited testing of the management plane. You will need to validate these manually.

[CosmosDB] Convert CosmosDB to Knack

---

src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_command_type.py

In A0 machine, reduce load time from 0.8s to 0.07s. This change delay the operation hander fetching.
This is a concept need more rigorous testing.

Improve batch module load performance on Knach

---

src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_command_type.py

Similar to the fix in the batch module, delay load the operation handler.
Reduce load time from `0.9s` to `0.03s`

Improve Keyvault module load time
