Azure/azure-cli

src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py

Closes #9223. Highlight the CREATE functionality of the SET command when a secret does not exist in the vault.
---

Update az keyvault secret set command description

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_params.py

@djyou @sajayantony 
https://github.com/Azure/acr/issues/213
---

update acr command append parameter doc

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_params.py

Follow up the comments in #9226
@djyou @tjprescott @SteveLasker @sajayantony 
---

update acr command document

---

src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py

Fix inconsistency in sql db import/export examples

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py

webapp: az webapp up updates to use local configuration & other updates

---

src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
src/command_modules/azure-cli-acs/setup.py

This is fixing the `az openshift create` command when used with custom AAD application
---

OSA -  Fix using custom AAD

---

src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/tests/latest/recordings/test_botservice_keep_node_modules_should_not_empty_node_modules_or_install_dependencies.yaml
src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/tests/latest/recordings/test_botservice_publish_remove_node_iis_files_if_not_already_local.yaml
src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/tests/latest/test_bot_commands.py

Fixes two broken tests that somehow slipped through:
- `test_botservice_keep_node_modules_should_not_empty_node_modules_or_install_dependencies`
- `test_botservice_publish_remove_node_iis_files_if_not_already_local`
Build in question that showed the broken tests: https://dashboard.azclitest.com/run/1487
@tjprescott, @yugangw-msft FYI
---

botservice: fix automation tests

---

src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py

Update service principal secret for windows node pools

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/cloud.py

Remove clouds.config file if it is bad

---

src/command_modules/azure-cli-consumption/HISTORY.rst
src/command_modules/azure-cli-consumption/azure/cli/command_modules/consumption/custom.py

Added the required argument when calling list_by_billing_period
Fixes #6902

Added required positional argument

---

src/command_modules/azure-cli-appservice/HISTORY.rst
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_params.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/azure_devops_build_iteractive.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/azure_devops_build_provider.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py
src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/latest/test_devops_build_commands_thru_mock.py
src/command_modules/azure-cli-appservice/setup.py

1. Add log streaming feature to show Azure DevOps progress when waiting for build.
2. Remove the unnecessary "--use_local_settings" flag and warn user in HISTORY.rst because currently the azure-functions-devops-build library does not support it.
3. Improve Azure DevOps release detection to prevent creation of duplicate
1. Fix info/warn messages including "Azure DevOps" spelling and wording.
---

[functionapps] Improvements of devops-pipeline command

---

Dockerfile

Curl must follow redirects. Fixes #9435

Fix JP installer line

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/_params.py

role: update the help of --assignee-object-id

---

src/command_modules/azure-cli-batch/HISTORY.rst
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_client_factory.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_validators.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/custom.py
src/command_modules/azure-cli-batch/setup.py

@xingwu1 
Fixes #8978 , #9165
---

Update error logging for reported unclear issues

---

src/command_modules/azure-cli-role/azure/cli/command_modules/role/tests/latest/test_graph.py

test: fix a flaky test

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/setup.py
src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-batch/HISTORY.rst
src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/setup.py
src/command_modules/azure-cli-vm/HISTORY.rst

Minor updates to history.rst and setup.py 
---

Release 2.0.66 - Fix versions

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/setup.py
src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-batch/HISTORY.rst
src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/setup.py
src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/setup.py
src/command_modules/azure-cli-vm/HISTORY.rst

Release 2.0.66 - bump azure-cli-role version

---

src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone8_import.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_dns_commands.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/zone_files/zone8.txt
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/zone_files/zone8.txt_export.txt
src/command_modules/azure-cli-network/azure/cli/command_modules/network/zone_file/parse_zone_file.py

Fix DNS zone import for wildcard records

---

azure-cli2017.pyproj
src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_watcher_flow_log.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/recordings/test_network_watcher_flow_log2.yaml
src/command_modules/azure-cli-network/azure/cli/command_modules/network/tests/latest/test_network_commands.py

[Network] Fix flow-log configure for CanadaEast

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py
src/command_modules/azure-cli-storage/setup.py

[storage] generate-sas needs key

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py

[ACR] Improve Readability of Command Examples

---

src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py

Added CLI example for creating a new LB on a subnet in a pre-existing virtual network resource.
---

Added cli example for LB on pre-existing subnet

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/setup.py
src/command_modules/azure-cli-acs/HISTORY.rst
src/command_modules/azure-cli-batch/HISTORY.rst
src/command_modules/azure-cli-network/HISTORY.rst
src/command_modules/azure-cli-network/setup.py
src/command_modules/azure-cli-role/HISTORY.rst
src/command_modules/azure-cli-role/setup.py
src/command_modules/azure-cli-vm/HISTORY.rst

Folding changes made in the release branch back into dev.

Merge Release Changes back to `dev`

---

src/command_modules/azure-cli-acr/HISTORY.rst
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_docker_utils.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_errors.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_params.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/check_health.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/commands.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/custom.py
src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/helm.py
src/command_modules/azure-cli-acr/setup.py

PR for new ACR command for self-diagnosis `az acr check-health`.
More information can be found here:
https://gist.github.com/ni-reis/a9ef51a6f08a2694482be401b068e558
Examples of the command:
---

[ACR] Add `az acr check-health` command

---

src/command_modules/azure-cli-resource/HISTORY.rst
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py

Fix `policy assignment list`

---

scripts/ci/test_extensions.sh

Test all extensions instead of testing each one

---

src/azure-cli-testsdk/azure/cli/testsdk/__init__.py
src/azure-cli-testsdk/azure/cli/testsdk/base.py
src/azure-cli-testsdk/azure/cli/testsdk/preparers.py
src/azure-cli-testsdk/azure/cli/testsdk/utilities.py
src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_service_no_wait.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/hybrid_2019_03_01/recordings/test_resource_group.yaml
src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/latest/recordings/test_resource_group.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/hybrid_2019_03_01/recordings/test_storage_account_service_endpoints.yaml
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_service_endpoints.yaml

undo #9431 test preparer update.

---

src/command_modules/azure-cli-storage/HISTORY.rst
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/azcopy/util.py
src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/azcopy.py

[storage] Fix blob sync in Linux

---

src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_params.py

Moved sql mi --capacity into perf level arg group

---

src/command_modules/azure-cli-sql/HISTORY.rst
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_params.py
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_server_mgmt.yaml
src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
src/command_modules/azure-cli-sql/setup.py

sql server & sql mi: use rg location

---

azure-pipelines.yml

Use replacement tasks for publishing and downloading artifacts

---

build_scripts/windows/scripts/build.cmd
scripts/release/homebrew/docker/requirements.txt
scripts/release/rpm/azure-cli.spec

Couple of places in our build infrastructure where we rely on having a src/command_modules folder

Fixing up CI failures

---

src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/_params.py
src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/custom.py

EventHub: fix for issue 7085 and 6676

---

src/command_modules/azure-cli-batch/HISTORY.rst
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_client_factory.py
src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_validators.py
src/command_modules/azure-cli-batch/setup.py

@tjprescott fixes an AAD regression introuduced in 4.0.2
---

Fix Batch AAD Regression

---

src/azure-cli-core/azure/cli/core/extension/operations.py

Add colorama init to display spinner correctly in windows

---

src/command_modules/azure-cli-natgateway/HISTORY.rst
src/command_modules/azure-cli-natgateway/azure/cli/command_modules/natgateway/_help.py
src/command_modules/azure-cli-natgateway/azure/cli/command_modules/natgateway/_params.py
src/command_modules/azure-cli-natgateway/azure/cli/command_modules/natgateway/custom.py
src/command_modules/azure-cli-natgateway/azure/cli/command_modules/natgateway/tests/latest/recordings/test_natgateway.yaml
src/command_modules/azure-cli-natgateway/azure/cli/command_modules/natgateway/tests/latest/test_natgateway_commands.py
src/command_modules/azure-cli-natgateway/setup.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/_params.py
src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py

 Update Nat Gateway with Zone parameter

---

azure-pipelines.yml

This _should_ fix branch-based CI builds. But it won't be tested by a PR run.

Renaming artifacts

---

src/azure-cli-core/setup.py

Remove constraint on paramiko version

---

src/command_modules/azure-cli-find/azure/cli/command_modules/find/custom.py

Changing I am an AI bot message from az find command
---

Changing first message in az find

---

src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/task.py

Dockerfile not found error handling

---

src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py
src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_params.py

Add powershell examples. Update vm and vmss run-command invoke help text.
closes #9658, #9513, #9455
---

[vm/vmss run-command invoke]Add powershell examples. Update help text.

---

scripts/ci/test_extensions.sh

Bring back verifying load extensions

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/role/commands.py

ad signed-in-user: fix a crash on listing owned objects

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/appservice/_params.py
src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_unavailable_location_app_insights.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_with_default_app_insights.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_with_no_default_app_insights.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

Fixes #7890 
@ahmedelnably @panchagnula 
---

Create Application Insights by default when creating Function Apps

---

src/azure-cli/azure/cli/command_modules/acr/_help.py

Changing create documentation

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/rdbms/_client_factory.py
src/azure-cli/azure/cli/command_modules/rdbms/_help.py
src/azure-cli/azure/cli/command_modules/rdbms/_params.py
src/azure-cli/azure/cli/command_modules/rdbms/commands.py
src/azure-cli/azure/cli/command_modules/rdbms/custom.py
src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mariadb_replica_mgmt.yaml

Add MariaDB support for replication

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/role/_params.py
src/azure-cli/azure/cli/command_modules/role/_validators.py
src/azure-cli/azure/cli/command_modules/role/custom.py

rbac: remove --password from create-for-rbac

---

src/azure-cli/azure/cli/command_modules/ams/operations/mru.py

Only internal method call change.
---

Replace call to profile.get_refresh_token() with profile.get_raw_token()

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_slot_appsetting_update.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_slot_creation.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_slot_swap.yaml

Fix a minor issue caused by slots. Backend takes care of creating the correct site config. It doesn't need to be explicitly copied by the CLI.
This should not need an update to History.rst.
\cc @panchagnula @yugangw-msft

Fix functionapp slots deployment issue

---

src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py

Change test_aks_create_service_no_wait to live only.

Restore CI to passing

---

src/azure-cli/azure/cli/command_modules/appservice/_help.py

Updating cors remove documentation that was confusing. Fixes #8514

---

src/azure-cli/azure/cli/command_modules/network/zone_file/parse_zone_file.py

Fixed dns zone file import for cnames, include hyphens in the alias

---

src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/azure/cli/core/commands/constants.py
src/azure-cli-core/azure/cli/core/mock.py

support defer argument in azure-cli-extensions

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/vm/_params.py
src/azure-cli/azure/cli/command_modules/vm/_validators.py
src/azure-cli/azure/cli/command_modules/vm/custom.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_proximity_placement_group.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_defaults.py

Removed client side validation. ppg create --type now takes standard alone.
---

Minor compute updates

---

src/azure-cli-testsdk/azure/cli/testsdk/__init__.py
src/azure-cli-testsdk/azure/cli/testsdk/base.py
src/azure-cli-testsdk/azure/cli/testsdk/preparers.py
src/azure-cli-testsdk/azure/cli/testsdk/utilities.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_slot_appsetting_update.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_slot_creation.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_slot_swap.yaml
src/azure-cli/azure/cli/command_modules/resource/tests/hybrid_2018_03_01/recordings/test_resource_group.yaml
src/azure-cli/azure/cli/command_modules/resource/tests/hybrid_2019_03_01/recordings/test_resource_group.yaml
src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_resource_group.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/hybrid_2019_03_01/recordings/test_storage_account_service_endpoints.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_service_endpoints.yaml

Add new GraphClient replacer. Update preparers. GeneralNameReplacer. Re-record tests.
Properly handle python3 bytes.
---

[Test] Traffic is not recorded by default in resource preparers

---

src/azure-cli/azure/cli/command_modules/acr/check_health.py

Issue https://github.com/Azure/acr/issues/243
**New changes have been tested and corresponding screenshots have been added below.**
**Default behavior**
**New changes - helm version < 2.11.0**
**New changes - helm version regex pattern changed; default output is shown**
**Note**: 
1. Azure-cli codebase was refactored. History file has not been modified.
2. Pylint ignore comment has been added to prevent merge failures.
@ni-reis 
---

[ACR] Helm version validation added

---

azure-pipelines.yml
src/azure-cli-command_modules-nspkg/HISTORY.rst
src/azure-cli-command_modules-nspkg/setup.py
src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli-nspkg/HISTORY.rst
src/azure-cli-nspkg/setup.py
src/azure-cli-telemetry/HISTORY.rst
src/azure-cli-telemetry/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/requirements.py2.Darwin.txt
src/azure-cli/requirements.py2.Linux.txt
src/azure-cli/requirements.py2.windows.txt
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

Minor release notes fixes, etc that happened in the release notes.

Merging 2.0.68 release changes back to dev

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/appservice/_validators.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_e2e.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

appservice: restore the idempotency of 'appservice plan create' and 'webapp create'

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/storage/operations/blob.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_update_service_properties.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_blob_scenarios.py

[storage] Fix az storage blob service-properties update --set

---

src/azure-cli/azure/cli/command_modules/batch/_help.py
src/azure-cli/requirements.py2.Darwin.txt
src/azure-cli/requirements.py2.Linux.txt
src/azure-cli/requirements.py2.windows.txt
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

@adewaleo please mention which issues this is fixing.
Also, the will fix the CI which started failing due to #9750.

Update to Knack 0.6.3.

---

azure-cli2017.pyproj
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/appservice/_help.py
src/azure-cli/azure/cli/command_modules/appservice/_validators.py
src/azure-cli/azure/cli/command_modules/appservice/commands.py
src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_assign_system_identity.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_e2e.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_hyperv_e2e.yaml

Fixes #8022, Fixes #6727, Fixes #9663
---

webapp: Adding validation to az webapp identity commands & other minor changes

---

src/azure-cli/azure/cli/command_modules/acr/_utils.py
src/azure-cli/azure/cli/command_modules/acr/run.py
src/azure-cli/azure/cli/command_modules/acr/task.py

Substituted get_yaml_and_values with get_yaml_template

---

doc/authoring_command_modules/authoring_commands.md

Updates documentation to reference preview items.

Add guidance for preview items.

---

scripts/release/rpm/azure-cli.spec

Fixes https://github.com/Azure/azure-cli/issues/9912
---

Fix requirements for RPM package

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/role/custom.py

role update: search all assigned scopes for existing role definitions

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/sql/custom.py

Improve error messages for sql offer unavailability

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/role/_help.py
src/azure-cli/azure/cli/command_modules/role/_params.py
src/azure-cli/azure/cli/command_modules/role/commands.py
src/azure-cli/azure/cli/command_modules/role/custom.py
src/azure-cli/azure/cli/command_modules/role/tests/latest/recordings/test_graph_group_scenario.yaml
src/azure-cli/azure/cli/command_modules/role/tests/latest/test_graph.py

aad: new command 'az ad user update'

---

src/azure-cli/azure/cli/command_modules/sql/_params.py

Minor refactoring

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic_app_gateway.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone1.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone2.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone3.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone4.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone5.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone6.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone7.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone8.txt_export.txt

---
Fixes https://github.com/Azure/azure-cli/issues/9861

Network.NIC: Remove --ids from the parameters

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/appservice/_validators.py
src/azure-cli/azure/cli/command_modules/appservice/commands.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_ssl.yaml

webapp: Adding validation to az webapp config ssl

---

doc/authoring_tests.md
doc/use_cli_effectively.md

Document CLI environment variables.

---

src/azure-cli/azure/cli/command_modules/keyvault/_params.py

Added more descriptive info regarding `--policy` parameter for Azure Key Vault

---

src/azure-cli/azure/cli/command_modules/role/custom.py
src/azure-cli/azure/cli/command_modules/role/tests/latest/recordings/test_application_set_scenario.yaml
src/azure-cli/azure/cli/command_modules/role/tests/latest/test_graph.py

graph: fix bug on 'app update' command

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/appservice/_create_util.py

webapp: Updating az webapp up discovering the language selection to work across all python versions

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone1.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone2.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone3.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone4.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone5.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone6.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone7.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone8.txt_export.txt

Fixes https://github.com/Azure/azure-cli/issues/9965
---

network:  add support of --subscription in "az dns record-set ns create"

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/storage/__init__.py
src/azure-cli/azure/cli/command_modules/storage/_validators.py
src/azure-cli/azure/cli/command_modules/storage/tests/hybrid_2018_03_01/recordings/test_storage_blob_upload_midsize_file.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/hybrid_2018_03_01/recordings/test_storage_blob_upload_small_file.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/hybrid_2018_03_01/recordings/test_storage_file_main_scenario.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/hybrid_2019_03_01/recordings/test_storage_blob_upload_midsize_file.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/hybrid_2019_03_01/recordings/test_storage_blob_upload_small_file.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/hybrid_2019_03_01/recordings/test_storage_file_main_scenario.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_upload_midsize_file.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_upload_small_file.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_file_main_scenario.yaml

 [storage] Add --clear-content-settings for storage blob update

---

src/azure-cli/azure/cli/command_modules/storage/_params.py
src/azure-cli/azure/cli/command_modules/storage/operations/account.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_create_storage_account_with_files_aadds.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_create_storage_account_with_files_aadds_false.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_create_storage_account_with_files_aadds_true.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py

[storage] Add --enable-files-aadds for blob create command

---

src/azure-cli/azure/cli/command_modules/storage/__init__.py

Remove "Preview" to fix issue #9938

---

src/azure-cli/azure/cli/command_modules/acr/_params.py
src/azure-cli/azure/cli/command_modules/acr/check_health.py

Screenshots with the latest changes.
@ni-reis @tjprescott 
---

[ACR] check-health: logger, print statements, faq, --ignore-errors and stderr fixes

---

src/azure-cli/azure/cli/command_modules/eventhubs/_help.py

Sometimes it's faster to create PR instead of issue.
Just fixing two things:
**--maximum-throughput-units** must be <=20
when **--maximum-throughput-units** is specified, **--enable-auto-inflate** must be set to true
Error messages:
"validation error: Parameter 'EHNamespace.maximum_throughput_units' must be less than 20"
"Cannot set MaximumThroughputUnits property if AutoInflate is not enabled"
Also displayed validation error is wrong as **20** actually works for me.

fix eventhub namespace example

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/custom.py

https://github.com/Azure/azure-cli/issues/9845
https://github.com/Azure/azure-cli/issues/9844
Update the doc, add check and update the error messages.
---

Network: Correct the error messages and help message for the `--vm` and `--nic` arguments for watcher test-ip-flow command

---

.gitignore
src/azure-cli/azure/cli/command_modules/storage/__init__.py

tool: ignore ./vscode files

---

src/azure-cli/azure/cli/command_modules/acr/_docker_utils.py
src/azure-cli/azure/cli/command_modules/acr/_errors.py

[ACR] Add documentation link to CONNECTIVITY_FORBIDDEN_ERROR

---

src/azure-cli/azure/cli/command_modules/netappfiles/_help.py
src/azure-cli/azure/cli/command_modules/netappfiles/custom.py
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_active_directory.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_create_delete_account.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_create_delete_pool.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_create_delete_snapshots.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_create_delete_volumes.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_create_pool_string_size.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_create_pool_too_small.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_export_policy.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_get_account_by_name.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_get_pool_by_name.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_get_snapshot.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_get_volume_by_name.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_list_accounts.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_list_mount_targets.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_list_pools.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_list_snapshots.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_list_volumes.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_update_account.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_update_pool.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_update_volume.yaml

Fixes #9452 
Associated with Azure issue Azure#9976
---

Provide missing resource id support for vnet and subnet (#46)

---

src/azure-cli/azure/cli/command_modules/lab/_help.py

Addresses issue #6840. 
x The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see Modifying change log).
x I adhere to the Command Guidelines.

Fixing the format of the expiration date in the documentation

---

src/azure-cli/azure/cli/command_modules/keyvault/_client_factory.py

Fix #6958
@schaabs, is this hack managable, till we pick up the GA version of the new keyvault dataplane library from your group?

key-vault: support proxy

---

src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_virtual_cluster_mgmt.yaml
src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py

Including additional route with next-hop-type VnetLocal when creating MI. This route was mada neccessary for successfull MI creation
---

Virtual Cluster scenario test fix

---

src/azure-cli/azure/cli/command_modules/acs/custom.py

Fixes https://github.com/Azure/azure-cli/issues/10045

Better handling for an edge error case.

---

src/azure-cli/azure/cli/command_modules/netappfiles/custom.py
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_create_delete_volumes.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_export_policy.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_export_policy_non_default.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_list_volumes.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_update_volume.yaml
src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/test_volume_commands.py

By applying the unspecified patch values from the instance.
---

ANF-146 fix add export policy (#47)

---

doc/authoring_help.md

Updated 'here' link text for accessibility

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/util.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/feedback/custom.py
src/azure-cli/azure/cli/command_modules/vm/_help.py
src/azure-cli/azure/cli/command_modules/vm/_params.py
src/azure-cli/setup.py

Minor updates to compute and to core general error handling

---

src/azure-cli/azure/cli/command_modules/appservice/commands.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_auto_delete_plan.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp_remote_ssh.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp_ssh.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_retain_plan.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_e2e.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_slot.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_ssl.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

Re-enabling webapp ssh tests and validation to some most used commands

---

src/azure-cli/azure/cli/command_modules/acs/custom.py

Fixes https://github.com/Azure/azure-cli/issues/9657

Add some better error messages for an edge case.

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/servicefabric/_params.py
src/azure-cli/azure/cli/command_modules/servicefabric/custom.py

Add supported vm_os this fixes #6112 and fix for cert validation fixes #6536

---

src/azure-cli/HISTORY.rst

Some notes were merged to the section of released version. This PR moved them to the right place

release: fix notes

---

.gitignore

update .gitignore for user files in .vscode

---

src/azure-cli/azure/cli/command_modules/storage/commands.py

mark commands using azcopy in preview

---

doc/configuring_your_machine.md

doc: add setup details for VS 2015

---

src/azure-cli/azure/cli/command_modules/acs/_params.py
src/azure-cli/azure/cli/command_modules/acs/custom.py

Fixes https://github.com/Azure/azure-cli/issues/8934

Add an optional flag for renaming the Kubernetes Context.

---

src/azure-cli/azure/cli/command_modules/storage/azcopy/util.py

Fix#10024: Change default installation location without root privileges

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/appservice/_create_util.py
src/azure-cli/azure/cli/command_modules/appservice/_help.py
src/azure-cli/azure/cli/command_modules/appservice/custom.py

webapp:Fixing the Webjobs command to use the slots API, & other fixes

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/network/commands.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_dns_commands.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone1.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone2.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone3.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone4.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone5.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone6.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone7.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone8.txt_export.txt

[Network] Support --yes argument for "dns record-set cname" to align the behavior with other dns type.

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/acs/custom.py

Support for logging into Kubernetes Dashbaord

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/requirements.py2.Darwin.txt
src/azure-cli/requirements.py2.Linux.txt
src/azure-cli/requirements.py2.windows.txt
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

update version and history

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/requirements.py2.Darwin.txt
src/azure-cli/requirements.py2.Linux.txt
src/azure-cli/requirements.py2.windows.txt
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

Update release notes

---

src/azure-cli/azure/cli/command_modules/acr/_errors.py
src/azure-cli/azure/cli/command_modules/acr/check_health.py

GitHub Issue: https://github.com/Azure/acr/issues/256
---

[ACR] Handling SSL Error in check health

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/requirements.py2.Darwin.txt
src/azure-cli/requirements.py2.Linux.txt
src/azure-cli/requirements.py2.windows.txt
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

Release Azure CLI 2.0.71

---

doc/use_cli_effectively.md

doc: updates for proxy

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/role/custom.py

Fix `az ad app update --homepage` not updating homepage.

---

.vscode/launch.json
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/storage/_help.py
src/azure-cli/azure/cli/command_modules/storage/_params.py
src/azure-cli/azure/cli/command_modules/storage/commands.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py

[strorage] Add revoke-delegation-keys command

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/appservice/_create_util.py
src/azure-cli/azure/cli/command_modules/appservice/_params.py

webapp: az webapp up detects the 'env' folder for python & removes this from the zip folder used for deployment

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/_template_builder.py
src/azure-cli/azure/cli/command_modules/network/custom.py
src/azure-cli/azure/cli/command_modules/network/tests/hybrid_2018_03_01/recordings/test_network_active_active_cross_premise_connection.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_zone.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone1.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone2.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone3.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone4.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone5.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone6.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone7.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone8.txt_export.txt
src/azure-cli/requirements.py2.Darwin.txt
src/azure-cli/requirements.py2.Linux.txt
src/azure-cli/requirements.py2.windows.txt
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

[Network] support private-ip-address-version for network lb

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_acr_deployment_function_app.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

Description
---
This is a fix for https://github.com/Azure/azure-cli/issues/4348

Use list_publishing_credentials to get the SCM URL

---

src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/custom.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_private_link_service.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

[Network] Fix the "--disable-private-endpoint-network-policies" for vnet subnet

---

src/azure-cli/HISTORY.rst

just adding history entries for prs i have merged that were missing these entries

history update

---

src/azure-cli/azure/cli/command_modules/acs/custom.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_custom.py

Fixes https://github.com/Azure/azure-cli/issues/9777

Refactor and remove a custom way of getting subscriptions that was broken

---

src/azure-cli/azure/cli/command_modules/vm/_help.py

Update vm create -h. --size. Use populator-commands to add "Values from" message.

---

src/azure-cli-core/azure/cli/core/adal_authentication.py

Authentication: Polish AAD exception AADSTS50173

---

src/azure-cli/azure/cli/command_modules/vm/_help.py

Maybe the redundant blank line make docs system misunderstand syntax.
---

[VM]Delete redundant blank lines in help

---

src/azure-cli/azure/cli/command_modules/vm/_help.py

fix: list-publishers command has missing argument

---

doc/authoring_command_modules/authoring_commands.md

Modify some typos in authoring_commands md

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/keyvault/custom.py
src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_network_rule.yaml
src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py

Fix #10286: Unable to delete network rules due to subnet ID getting converted to lowercase by keyvault service.

Fix #10286: Unable to delete network rules

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/hdinsight/_params.py
src/azure-cli/azure/cli/command_modules/hdinsight/commands.py

* resize: Made --workernode-count/-c required
* GA release
---

[HDInsight] - GA release

---

src/azure-cli/azure/cli/command_modules/network/_params.py

[Network]update help for network nsg rule --source-args and --destination-args

---

src/azure-cli/azure/cli/command_modules/network/_help.py

[Network] update help info for list-service-tags

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/keyvault/custom.py
src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_network_rule.yaml
src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py

Fix: Duplicated subnets and IP addresses can be added to network rules

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/profiles/_shared.py
src/azure-cli/azure/cli/command_modules/appservice/__init__.py

Multi-API: add resource type for appservice for consistency

---

src/azure-cli/azure/cli/command_modules/acr/_help.py
src/azure-cli/azure/cli/command_modules/acr/_params.py

Update acr tasks cli help doc for platform and managed identity.
---

update acr tasks cli help doc

---

src/azure-cli/requirements.py2.Darwin.txt
src/azure-cli/requirements.py2.Linux.txt
src/azure-cli/requirements.py2.windows.txt
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

updating msrest 0.6.7 -> 0.6.9

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/network/_client_factory.py
src/azure-cli/azure/cli/command_modules/network/_help.py
src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/commands.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_express_route_peer_connection.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

[Network] Support list and show commands for express route peer connection

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/acr/_help.py
src/azure-cli/azure/cli/command_modules/acr/_params.py
src/azure-cli/azure/cli/command_modules/acr/task.py

[ACR] Default Disable the Pull Request Trigger for Task

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/acr/commands.py

[ACR] add preview for retention commands

---

src/azure-cli/azure/cli/command_modules/resource/custom.py

---
Fix ICM [137568973](https://icm.ad.msft.net/imp/v3/incidents/details/137568973/home)

[ARM] depracate register in management-groups

---

src/azure-cli/azure/cli/command_modules/profile/__init__.py

Add missing word to --help text

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/acr/_docker_utils.py
src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_commands_mock.py

[acr] login: support cross tenant login

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/custom.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vpn_gateway.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

[Network]Support "--custom-routes" argument for "az network vnet-gateway create/update"

---

src/azure-cli/azure/cli/command_modules/vm/_help.py

Delete unnecessary spaces in `vmss update` help message
---

[Compute] vmss update: Update help message

---

src/azure-cli/azure/cli/command_modules/acs/custom.py

Default workspace mapping for Fairfax

---

azure-pipelines.yml
scripts/release/debian/test_deb_install.sh
scripts/release/debian/test_deb_installer.ps1

modifying pipelines to add buster

Adding buster

---

src/azure-cli/azure/cli/command_modules/acr/_constants.py
src/azure-cli/azure/cli/command_modules/acr/_docker_utils.py
src/azure-cli/azure/cli/command_modules/acr/check_health.py

[Link to the Issue](https://msazure.visualstudio.com/One/_boards/board/t/Azure%20Container%20Registry/Backlog%20items/?workitem=5015420).
Screenshots have been updated.
---

[ACR] Check health suggestion on command failure and error deep link

---

scripts/release/debian/deb_install.sh

add comments and indent as a follow up of #10358

install: add comments on debian script

---

src/azure-cli/azure/cli/command_modules/acs/_params.py

[ACS] Fix CI error. Add parameter help
---

[ACS] Fix CI error. Add parameter help

---

src/azure-cli/azure/cli/command_modules/appservice/_create_util.py
src/azure-cli/azure/cli/command_modules/appservice/_params.py
src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_vnetE2E.yaml

webapp: az webapp up code refactoring

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/acr/_help.py
src/azure-cli/azure/cli/command_modules/acr/_params.py
src/azure-cli/azure/cli/command_modules/acr/policy.py
src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_commands.py

- Add required `--type` parameter to retention command
- use `-r` for registry name instead of `-n` for `config` command group.
- separate out `status` params
---

[ACR] Update some policy params

---

src/azure-cli/requirements.py2.Darwin.txt
src/azure-cli/requirements.py2.Linux.txt
src/azure-cli/requirements.py2.windows.txt
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

---
Add  jsmin in requirements.txt for PR#10389

add  jsmin in requirements.txt

---

src/azure-cli-core/setup.py
src/azure-cli/requirements.py2.Darwin.txt
src/azure-cli/requirements.py2.Linux.txt
src/azure-cli/requirements.py2.windows.txt
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

Update azrestazure version to 0.6.2
Fix #9436
https://github.com/Azure/msrestazure-for-python/pull/135
---

Update azrestazure version to 0.6.2. Fix #9436

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/requirements.py2.Darwin.txt
src/azure-cli/requirements.py2.Linux.txt
src/azure-cli/requirements.py2.windows.txt
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

Update Azure CLI to 2.0.74
---

Update Azure CLI to 2.0.74

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/ams/_help.py
src/azure-cli/azure/cli/command_modules/ams/_params.py
src/azure-cli/azure/cli/command_modules/ams/commands.py
src/azure-cli/azure/cli/command_modules/ams/tests/latest/test_ams_job_scenarios.py

Job creation names

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/requirements.py2.Darwin.txt
src/azure-cli/requirements.py2.Linux.txt
src/azure-cli/requirements.py2.windows.txt
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

Update Azure CLI to 2.0.74 (#10585)
---

Update Azure CLI to 2.0.74 (#10585)

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/vm/_params.py
src/azure-cli/azure/cli/command_modules/vm/custom.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_options.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

[Compute] Add --computer-name-prefix to vmss create
Implement #9362 
---

 [Compute] Add --computer-name-prefix to vmss create

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/appservice/_params.py
src/azure-cli/azure/cli/command_modules/appservice/_validators.py
src/azure-cli/azure/cli/command_modules/appservice/commands.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_auto_delete_plan.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_scale.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_vnetE2E.yaml
src/azure-cli/azure/cli/command_modules/appservice/utils.py

webapp: Appservice plan update supports Isolated SKU

---

src/azure-cli/azure/cli/command_modules/resource/_params.py

Fix #10268: Update `az rest --body` help message.

[REST] Fix #10268: Update rest --body help message

---

src/azure-cli/azure/cli/command_modules/vm/_params.py

[Compute] vm/vmss create: --ultra-ssd-enabled, remove preview status
---

[Compute] vm/vmss create: --ultra-ssd-enabled, remove preview status

---

src/azure-cli-telemetry/HISTORY.rst
src/azure-cli-telemetry/setup.py
src/azure-cli/requirements.py2.Darwin.txt
src/azure-cli/requirements.py2.Linux.txt
src/azure-cli/requirements.py2.windows.txt
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

code fixed previously by PR https://github.com/Azure/azure-cli/pull/10497 for issue #10232, need to upgrade the version to release the change.

upgrade telemetry version

---

src/azure-cli/azure/cli/command_modules/acr/_help.py

Explain the corn expression used in `acr task timer add` example
---
- [] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

clarify 'acr task timer add' example

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/acs/custom.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_default_setting.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py

AKS default to SLB and VMSS

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli/azure/cli/command_modules/resource/commands.py

Fix#10479: add transform function fo `az resource invoke-action`

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/vm/_client_factory.py
src/azure-cli/azure/cli/command_modules/vm/_params.py
src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
src/azure-cli/azure/cli/command_modules/vm/custom.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_with_monitor.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_linux_secrets.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

[Monitor]Support "--workspace" for "vm create"

---

src/azure-cli/azure/cli/command_modules/acr/_help.py

acr: mention how to logout in the help for 'az acr login'

---

src/azure-cli/azure/cli/command_modules/vm/_params.py

[Monitor]add preview for az vm create --workspace

---

src/azure-cli/azure/cli/command_modules/acs/_help.py

Update some docs for Virtual Kubelet and AKS

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py

**Summary of changes**
- exits --> exists
- add missing period

Fix spelling error in az web app up message

---

src/azure-cli/azure/cli/command_modules/role/_help.py

Per: https://github.com/MicrosoftDocs/azure-docs-cli/pull/1611
---

Fix typo in "az ad sp create-for-rbac" help text.

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/backup/custom.py

added error detail for force vault delete

---

src/azure-cli/azure/cli/command_modules/appservice/_help.py

Removes a small typo in help text.
---

[AppService] Remove extra '}'

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/acs/_client_factory.py
src/azure-cli/azure/cli/command_modules/acs/_format.py
src/azure-cli/azure/cli/command_modules/acs/_help.py
src/azure-cli/azure/cli/command_modules/acs/_params.py
src/azure-cli/azure/cli/command_modules/acs/_validators.py
src/azure-cli/azure/cli/command_modules/acs/commands.py
src/azure-cli/azure/cli/command_modules/acs/custom.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_availability_zones.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_nodepool_create_scale_delete.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py

add nodepools and zones support for CLI

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/profile/custom.py

Fixes typo in reference to Microsoft Graph endpoint, to align with typo fixes in https://github.com/Azure/azure-cli/pull/1004
---

Fix typo in reference to microsoft_graph_resource_id endpoint

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/custom.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_public_ip_prefix.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

Add --version to az network public-ip prefix in creation

---

src/azure-cli/azure/cli/command_modules/sql/_help.py

end-ip-address must be larger than start-ip-address.
---

fix "az sql server firewall-rule update" example

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py
src/azure-cli/azure/cli/command_modules/cosmosdb/_params.py
src/azure-cli/azure/cli/command_modules/cosmosdb/custom.py
src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_gremlin_graph.yaml
src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_sql_container.yaml
src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/test_cosmosdb_commands.py

Add parameters for sql container and gremlin graph commands

---

src/azure-cli/HISTORY.rst

Fix ordering in src/azure-cli/HISTORY.rst for **Backup**.

Fix ordering in src/azure-cli/HISTORY.rst

---

src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/storage/operations/account.py

Addresses issue #10849. Initially the warning message's grammar was fixed, but after further discussion within the comments the entire message was removed. Also addresses issue ##10848 for incorrect grammar.
---

incorrect grammar fixes

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/storage/util.py

This would resolve #8708.  We've run into the same issue with WebAssembly files being uploaded through the CLI in an Ansible playbook.
---

Adds mimetype detection for WebAssembly files

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_ssl.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

Adding the fix to not remove tags when performing ssl bind operation

---

src/azure-cli/azure/cli/command_modules/apim/_params.py

Add required flag to --publisher-name for apim create.

---

Dockerfile.nanoserver

Use image from mcr;
fix outdated folder when building python packages

fix nanoserver dockerfile

---

src/azure-cli/azure/cli/command_modules/acr/_format.py
src/azure-cli/azure/cli/command_modules/acr/_params.py
src/azure-cli/azure/cli/command_modules/acr/_utils.py
src/azure-cli/azure/cli/command_modules/acr/scope_map.py
src/azure-cli/azure/cli/command_modules/acr/token.py

1. `az acr token list -o table` fix to display `PASS1 EXPIRY` and `PASS2 EXPIRY` in order
**Before fix**
**After fix**
2. `scope-map update` command fix to prevent inconsistencies with `--add` and `--remove` actions
3. Adding period to few sentences. Few fixes to help texts.
---

[ACR] Token list table formatting, scope map update and help text fixes

---

src/azure-cli/azure/cli/command_modules/acr/scope_map.py
src/azure-cli/azure/cli/command_modules/acr/token.py

Premium sku validation removed for tbac in cli.
---

Removing cli validation for premium sku

---

scripts/release/homebrew/docker/formula_template.txt

remove obsolete line in homebrew

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/cosmosdb/commands.py

Add deprecation information

---

src/azure-cli/azure/cli/command_modules/network/_client_factory.py
src/azure-cli/azure/cli/command_modules/network/_help.py
src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/_validators.py
src/azure-cli/azure/cli/command_modules/network/commands.py
src/azure-cli/azure/cli/command_modules/network/custom.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_virtual_router_scenario.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone1.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone2.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone3.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone4.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone5.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone6.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone7.txt_export.txt
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone8.txt_export.txt

[Network]Support virtual router and virtual router peering

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/acr/_params.py
src/azure-cli/azure/cli/command_modules/acr/custom.py
src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_create_with_audits.yaml
src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_commands.py

acr: support to enable audits on create

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_acr_create_function_app.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

Quick fix for Ignite release
@ahmedelnably @Hazhzeng

Fix ACR linuxFxVersion for function apps

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/vm/custom.py
src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2018_03_01/test_custom_vm_commands.py
src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/test_custom_vm_commands.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_custom_vm_commands.py

[Compute] Update VMAccessForLinux to 1.5

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/acr/build.py
src/azure-cli/azure/cli/command_modules/acr/run.py

[ACR] Revert adding default timeout to az acr run and az acr build (not yet released)

---

src/azure-cli/HISTORY.rst

[ACR]:update release log for Repository-scoped RBAC

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/custom.py

[Network]add --internet-security for express-route gateway connection

---

src/azure-cli/azure/cli/command_modules/resource/_help.py
src/azure-cli/azure/cli/command_modules/resource/custom.py

remove breaking change notice in deployment commands.

---

src/azure-cli/azure/cli/command_modules/acr/_help.py

[ACR] Update docs to show alias

---

src/azure-cli/azure/cli/command_modules/storage/_params.py

[Storage] Fix #11028: Remove unused [link here] in storage copy help

---

src/azure-cli/azure/cli/command_modules/acs/custom.py

fix: Cli assumes compute pool is index zero on scale command

---

scripts/release/debian/deb_install.sh

fix xterm popup #10793

---

scripts/ci/dependency_check.bat
scripts/install_full.bat
src/azure-cli/requirements.py3.windows.txt

* Bug fix: issue #9853 to make dependency check valid on Windows platform
---

Bug Fix: wrong invokation to call ./scripts/install_all.bat which let dependency check always pass on Windows platform

---

doc/use_cli_effectively.md

Fix typos and reformat doc/use_cli_effectively.md

Fix typos and reformat doc/use_cli_effectively.md

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/appservice/custom.py

[AppService] Fix bug in create_app_service_plan when use webapp up

---

src/azure-cli/azure/cli/command_modules/appservice/_params.py

Fixed typo related to functionapp documentation
---

fixed typo related to functionapp documentation

---

scripts/release/homebrew/docker/formula_template.txt

fix follow discussion here: https://github.com/Homebrew/homebrew-core/pull/46244

add homebrew fix for Xcode 11

---

src/azure-cli-core/azure/cli/core/commands/template_create.py
src/azure-cli/azure/cli/command_modules/network/_help.py

[Network]az network lb create: update help and example for --subnet

---

.vscode/launch.json
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/redis/custom.py

Avoid setting memory configs for Basic SKU cache. Fixes #2902
---

Trim memory configuration for Basic SKU redis cache

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/iot/_help.py
src/azure-cli/azure/cli/command_modules/iot/commands.py
src/azure-cli/azure/cli/command_modules/iot/custom.py
src/azure-cli/azure/cli/command_modules/iot/tests/latest/test_iot_commands.py

[IoT Hub] Fix #2531: Add convenience arguments for hub update

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/storage/_params.py
src/azure-cli/azure/cli/command_modules/storage/operations/account.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_create_with_hns.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_create_with_hns_false.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_create_with_hns_true.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py

[Storage]: Enable Hierarchical Namespace for storage account

---

src/azure-cli/azure/cli/command_modules/acr/_params.py

This will group all trigger arguments together. 
---

Tasks parameter cleanup

---

src/azure-cli/azure/cli/command_modules/batch/_params.py
src/azure-cli/azure/cli/command_modules/batch/_validators.py
src/azure-cli/azure/cli/command_modules/batch/tests/latest/test_batch_commands.py

Change blob_source to http_url

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_vnetDelegation.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

---
- [x ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

Fixing add vnet-integration so that delegation is case insensitive 

---

src/azure-cli/azure/cli/command_modules/storage/_validators.py

[Storage] Fixes dictionary changes error to support Python 3.8

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/vm/_params.py
src/azure-cli/azure/cli/command_modules/vm/custom.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_managed_disk.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

[Compute] image create: Add --data-disk-caching to allow specifying caching setting of data disks

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/vm/_client_factory.py
src/azure-cli/azure/cli/command_modules/vm/_format.py
src/azure-cli/azure/cli/command_modules/vm/_help.py
src/azure-cli/azure/cli/command_modules/vm/_params.py
src/azure-cli/azure/cli/command_modules/vm/commands.py
src/azure-cli/azure/cli/command_modules/vm/custom.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_with_monitor.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
src/azure-cli/requirements.py2.Darwin.txt
src/azure-cli/requirements.py2.Linux.txt
src/azure-cli/requirements.py2.windows.txt
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

[Monitor]az vm monitor log show: support query log over linked log analytics workspace.

---

src/azure-cli-core/azure/cli/core/__init__.py

As requested in #11302, #10250, adding instructions on how to update CLI.
---

[Core] Add link for updating CLI

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/commands/arm.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

[Core]improve help and error message for --ids

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/backup/_help.py
src/azure-cli/azure/cli/command_modules/backup/_params.py
src/azure-cli/azure/cli/command_modules/backup/custom.py
src/azure-cli/azure/cli/command_modules/backup/custom_base.py

[Backup] Added optional parameter backupManagementType  in backup policy list-associated-items 

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/iot/_help.py
src/azure-cli/azure/cli/command_modules/iot/_params.py
src/azure-cli/azure/cli/command_modules/iot/custom.py
src/azure-cli/azure/cli/command_modules/iot/tests/latest/test_iot_commands.py

[IoTHub] Add missing parameter to create storage endpoint

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/resource/_help.py
src/azure-cli/azure/cli/command_modules/resource/_params.py
src/azure-cli/azure/cli/command_modules/resource/commands.py

`az rest` is GA, add examples.
---

[Rest] az rest is GA, add examples

---

src/azure-cli/azure/cli/command_modules/iotcentral/custom.py

---
Remove subdomain check for creating Iot central application, we would create application idempotently. minor changes

[IotCentral] Remove subdomain check for idempotent

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/storage/_params.py
src/azure-cli/azure/cli/command_modules/storage/commands.py

[Storage] GA Release User Delegation SAS token Support

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/storage/_params.py

[Storage] GA Release LFS

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/iot/_help.py
src/azure-cli/azure/cli/command_modules/iot/_params.py
src/azure-cli/azure/cli/command_modules/iot/custom.py
src/azure-cli/azure/cli/command_modules/iot/tests/latest/test_iot_commands.py

[IoTHub] Breaking Changes for manual-failover command

---

CredScanSuppressions.json
azure-pipelines.yml
src/azure-cli/azure/cli/command_modules/servicefabric/_help.py

Add CredScan job to CI

---

src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/custom.py

* Fix https://github.com/Azure/azure-cli/issues/10520
* Add --ttl to dns recrod-set cname set-record
* Add --ttl to dns for all types of record-set's add-record
---

[Network] Support --ttl in dns record update

---

src/azure-cli/azure/cli/command_modules/vm/_help.py

Fix https://github.com/Azure/azure-cli/issues/9766
---

[VM] Correct wrong syntax of reading a file on az vm help message

---

src/azure-cli/azure/cli/command_modules/network/_params.py

[Network]update help message for az network vnet subnet update --route-table

---

src/azure-cli/azure/cli/command_modules/monitor/_help.py

[Monitor]add example for diagnostic-settings categories list

---

src/azure-cli/azure/cli/command_modules/network/_help.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_with_identity.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

- Fix wrong usage of `application-gateway ssl-cert` in test cast _test_network_app_gateway_with_identity_ . Which discovered in https://github.com/Azure/azure-cli/issues/10651#issuecomment-561517520
- Add examples for complex usage of `application-gateway ssl-cert create`
---

[Network] Fix wrong usage of `application-gateway ssl-cert` in test case test_network_app_gateway_with_identity

---

src/azure-cli/azure/cli/command_modules/monitor/_help.py

[Monitor]add example for az monitor activity-log alert scope add

---

src/azure-cli/azure/cli/command_modules/acr/custom.py

acr: add a warning that delete command will prompt in a future release

---

src/azure-cli/azure/cli/command_modules/rdbms/_params.py

[RDBMS] Update firewall_rule_name help message

---

src/azure-cli-core/azure/cli/core/parser.py

Fix Azure/azure-cli-extensions#1071
---

[Core]refine help message when the command cannot be find.

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/keyvault/_validators.py
src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_secret.yaml
src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py

Fix #10846: Calling az keyvault secret show-deleted --id <value> still says secret_name "can not" be none

---

doc/command_guidelines.md
scripts/ci/build.sh
src/azure-cli-command_modules-nspkg/setup.py
src/azure-cli-core/setup.py
src/azure-cli-nspkg/setup.py
src/azure-cli-telemetry/setup.py
src/azure-cli-testsdk/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/setup.py
tools/setup.py

remove python 3.4 support

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/appservice/_params.py
src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_ssl.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

Add support for uploading cert to a slot

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/keyvault/_help.py

Fix #8095: Misleading command descriptions

---

src/azure-cli/azure/cli/command_modules/batch/_params.py

---
- [X ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

Add Os-Family 6 to enum

---

src/azure-cli-core/azure/cli/core/cloud.py

fix: add app insights + log analytics cloud endpoints

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/keyvault/_help.py
src/azure-cli/azure/cli/command_modules/keyvault/_params.py
src/azure-cli/azure/cli/command_modules/keyvault/custom.py

Fix #10512: Exception while trying to set key vault policy

---

azure-cli.pyproj
azure-cli2017.pyproj
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/servicefabric/custom.py
src/azure-cli/azure/cli/command_modules/servicefabric/template/linux/template.json
src/azure-cli/azure/cli/command_modules/servicefabric/template/windows/template.json
src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/policy.json
src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/test_sf_commands.py

Fix add node type logic, fixes #10963.
Update sf vm extension version to 1.1 in creation template
---

Service Fabric Fix add node type logic

---

src/azure-cli/azure/cli/command_modules/vm/_help.py

[Compute] Update `vm user update` doc

---

src/azure-cli/azure/cli/command_modules/apim/_help.py
src/azure-cli/azure/cli/command_modules/apim/_params.py
src/azure-cli/azure/cli/command_modules/apim/custom.py
src/azure-cli/azure/cli/command_modules/apim/tests/latest/recordings/test_apim_core_service.yaml
src/azure-cli/azure/cli/command_modules/apim/tests/latest/test_apim_scenario.py

Fix for apim backup to incorporate the parameters for storage account.

[APIManagement][Fix]az apim backup: fix the bug of this command.

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/backup/_client_factory.py
src/azure-cli/azure/cli/command_modules/backup/_help.py
src/azure-cli/azure/cli/command_modules/backup/_params.py
src/azure-cli/azure/cli/command_modules/backup/commands.py
src/azure-cli/azure/cli/command_modules/backup/custom.py
src/azure-cli/azure/cli/command_modules/backup/custom_base.py
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_softdelete.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_vault.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/test_backup_commands.py

[Recoveryservices Backup]  Added Soft-delete features

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_mgmt.yaml
src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py

---
This is a minor change, change `--enable-for-deploymen` to `--enable-for-deployment`.

Fix typo in `KeyVaultMgmtScenarioTest`

---

.github/CODEOWNERS

remove @zikalino from code owner
---

[General][Minor]Update Code Onwers

---

.github/CODEOWNERS

update codeowner for resource

---

src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_managedapp.yaml
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py

Fix the test of test_managedapp
issue: #5110 
- Because the group of Azure Active Directory which used in the case was deleted, I changed it to a new group-id
- The matching parameters of the template were not added to the previous command，So I changed the template which case used and give the matching parameters of the template.
---

[ARM] Fix the test of test_managedapp

---

.github/CODEOWNERS

Add codeonwer for sql

---

src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_metric_alert_v2_scenario.yaml
src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_metric_alert_scenarios.py

fix: az monitor metric alert create. Fix test failure.

---

src/azure-cli/azure/cli/command_modules/appservice/commands.py

updating BYOS commands to mark them as preview

---

.github/CODEOWNERS

[Help] update CODEOWNERS

---

src/azure-cli/HISTORY.rst

Noticed this typo while updating `History.rst` in my own PR.

Fix typo in History.rst

---

src/azure-cli/azure/cli/command_modules/keyvault/_help.py

Fix: https://github.com/Azure/azure-cli-extensions/issues/1063
---

[KeyVault] Add example for container sas-definition

---

src/azure-cli/azure/cli/command_modules/acr/_errors.py
src/azure-cli/azure/cli/command_modules/acr/check_health.py
src/azure-cli/azure/cli/command_modules/acr/notary.py

This adds a notary compatibility check since notary version 0.6.1 reports authentication failure for remote operations.
---

Add notary version compatibility checks

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/network/custom.py

[Network]az  network dns record-set add/remove: show warning when a new record-set is created automatically

---

azure-pipelines.yml

{CI} Add PR title check

---

azure-pipelines.yml
scripts/ci/credscan/CredScanSuppressions.json

{CI} Enable CredScan task of Microsoft Security Code Analysis (Preview)

---

src/azure-cli/azure/cli/command_modules/monitor/_client_factory.py
src/azure-cli/azure/cli/command_modules/monitor/commands.py
src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_diagnostic_settings_scenario.yaml
src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_diagnostic_settings.py

{Monitor} az monitor diagnostic-settings category list: fix bug

---

src/azure-cli-core/setup.py
src/azure-cli/requirements.py2.Darwin.txt
src/azure-cli/requirements.py2.Linux.txt
src/azure-cli/requirements.py2.windows.txt
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

Bump to `azure-mgmt-resource~=8.0.1` to isolate test hang issue in #12021

{Resource} Bump to azure-mgmt-resource~=8.0.1

---

src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/command_modules/appconfig/_params.py
src/azure-cli/azure/cli/command_modules/appconfig/commands.py

[AppConfig]Remove preview tag for most commands excluding managed identity and feature flags

---

doc/extensions/README.md

Fix https://github.com/Azure/azure-cli/issues/6454
---

{Doc} Added Extension installation section in doc/extensions/README.md

---

scripts/curl_install_pypi/install
scripts/curl_install_pypi/install.py

{Packaging} Use Python 3 by default for curl install script

---

src/azure-cli/azure/cli/command_modules/sql/_help.py
src/azure-cli/azure/cli/command_modules/sql/_params.py

{SQL} Add example for sql db create hyperscale

---

src/azure-cli/azure/cli/command_modules/storage/_help.py

{Storage} Add example for file copy start

---

src/azure-cli/azure/cli/command_modules/backup/custom_afs.py

[Backup] Fix for item level recovery flow in OLR

---

src/azure-cli/azure/cli/command_modules/acs/custom.py

[AKS] fix the aks browse in cloud shell.

---

src/azure-cli/azure/cli/command_modules/acs/custom.py

[AKS] az aks: Fix monitoring addon and agentpool NoneType errors.

---

.dockerignore

Save close to 400MB on docker images size.
---

{Docker} Slim down docker images

---

src/azure-cli/azure/cli/command_modules/network/custom.py

Fix #7907 
Currently the usage will be around 200 sub per months. So I don't want to bring in breaking change suddenly.
---

[Network] az network dns zone import: --zone-name will be case insensitive in the future.

---

src/azure-cli/azure/cli/command_modules/apim/_params.py

{APIM} az apim show: fix import bug

---

doc/install_troubleshooting.md

{Document} update install troubleshooting

---

src/azure-cli/azure/cli/command_modules/network/_params.py

Fix https://github.com/Azure/azure-cli/issues/11468
---

{Network} Fix wrong import ZoneType of DNS

---

.github/CODEOWNERS

Update Codeowner to latest.
---
- [-] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).
- [-] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

{Misc}: update codeowners

---

src/azure-cli/azure/cli/command_modules/storage/_params.py
src/azure-cli/azure/cli/command_modules/storage/tests/hybrid_2019_03_01/recordings/test_storage_create_default_kind.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/hybrid_2019_03_01/test_storage_account_scenarios.py

{Storage} Change api version range for storage account kind

---

src/azure-cli/azure/cli/command_modules/network/commands.py

[Network] az network private-endpoint/private-link-service: remove preview label.

---

src/azure-cli/azure/cli/command_modules/network/_help.py
src/azure-cli/azure/cli/command_modules/network/commands.py
src/azure-cli/azure/cli/command_modules/network/custom.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_list_available_ips.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

[Network] az network vnet list-available-ips: support list available ips in a vnet

---

src/azure-cli/azure/cli/command_modules/monitor/commands.py

{Monitor}show command should return 3

---

src/azure-cli/azure/cli/command_modules/acs/custom.py

[AKS] add missing / in the dashboard url.

---

src/azure-cli/azure/cli/command_modules/monitor/grammar/MetricAlertCondition.g4
src/azure-cli/azure/cli/command_modules/monitor/grammar/MetricAlertConditionLexer.py
src/azure-cli/azure/cli/command_modules/monitor/grammar/MetricAlertConditionListener.py
src/azure-cli/azure/cli/command_modules/monitor/grammar/MetricAlertConditionParser.py
src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_metric_alert_special_char_scenario.yaml
src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_metric_alert_scenarios.py

[Monitor] az monitor metrics alert create: support `~` in `--condition`.

---

.github/CODEOWNERS

{CODEOWNER} update codeowners for storage and resource modules

---

src/azure-cli/azure/cli/command_modules/acs/_params.py

[AKS] az aks: Validate network plugin to be either "azure" or "kubenet".

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_backup_with_name.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

[AppService] Fix #5720946: az webapp backup fails to set name

---

src/azure-cli/azure/cli/command_modules/rdbms/custom.py
src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mariadb_proxy_resources_mgmt.yaml
src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_proxy_resources_mgmt.yaml
src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_proxy_resources_mgmt.yaml
src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_commands.py

[RDBMS] Updating RDBMS Private Endpoint Tests

---

src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/custom.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_waf_policy_with_application_gateway.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

[Network] az network application-gateway waf-policy managed-rule rule-set add: support Microsoft_BotManagerRuleSet

---

src/azure-cli/azure/cli/command_modules/backup/_help.py
src/azure-cli/azure/cli/command_modules/backup/_params.py
src/azure-cli/azure/cli/command_modules/backup/custom_afs.py
src/azure-cli/azure/cli/command_modules/backup/tests/latest/preparers.py
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_afs_backup_restore.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/test_afs_commands.py
src/azure-cli/azure/cli/command_modules/backup/tests/latest/test_workload_commands.py

[Backup] Added multiple files restore capabilities

---

src/azure-cli-testsdk/azure/cli/testsdk/preparers.py

{azure-cli-testsdk} Enable https-only property for storage accont to fit security policy

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py

{AppService} az webapp config ssl import: Fix to allow key vault in other subscription

---

.github/CODEOWNERS

[IoT] Add codeowner

---

Dockerfile

Signed-off-by: Daniel Sutton <daniel@ducksecops.uk>
---

[Docker] Update to Alpine 3.11 and Python 3.6.10

---

src/azure-cli/azure/cli/command_modules/vm/_help.py

{Compute} Fix help of `vm create`

---

src/azure-cli/azure/cli/command_modules/maps/custom.py

{Maps} az maps account create: updated terms text displayed during account creation process per CELA guidance.  
---

{Maps} update terms text for create account

---

src/azure-cli/azure/cli/command_modules/acr/task.py

Acr task update null pointer exception
Fixes issue #12276

[ACR] 'az acr task update': null pointer exception.

---

src/azure-cli/azure/cli/command_modules/vm/_params.py

Update help text of vm/vmss create
#11857
---

{Compute} vm/vmss create: update help of --priority and --eviction-policy

---

README.md

{Misc} Remove Travis status badge

---

src/azure-cli/azure/cli/command_modules/acs/_help.py
src/azure-cli/azure/cli/command_modules/acs/_loadbalancer.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_loadbalancer.py

Twin: https://github.com/Azure/azure-cli-extensions/pull/1383

[AKS] aks update: Override outbound IPs with input values when update.

---

azure-pipelines.yml

Align with https://github.com/Azure/azure-cli-extensions/pull/1388
---

{CI} update PR trigger condition

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md
.github/ISSUE_TEMPLATE/Service_team_request.md

{Misc} wrap issue templates hint messages.

---

src/azure-cli/azure/cli/command_modules/storage/commands.py
src/azure-cli/azure/cli/command_modules/storage/operations/blob.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_sas_tokan_url_scenarios.py

[Storage] az storage blob generate-sas: Fix#11643 to support encoding blob url

---

src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
src/azure-cli/azure/cli/command_modules/vm/custom.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_with_monitor.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_with_workspace_linux.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_with_workspace_windows.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_metric_tail.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_update_with_workspace_linux.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_update_with_workspace_windows.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

[Compute] az vm update: Support --workspace

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_windows_runtime_java.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

Resolves #12616 
[AppService] az functionapp create: Updated the way javaVersion was being set for Windows function apps
---

[AppService] functionapp: Updated Java configuration for Windows apps

---

src/azure-cli/azure/cli/command_modules/cosmosdb/commands.py

[Cosmos DB] Fix missing --type option for deprecation redirections (#12526)

---

src/azure-cli/azure/cli/command_modules/acr/_params.py

[ACR] `az acr login`:Remove the preview flag on '--expose-token'

---

src/azure-cli-core/azure/cli/core/extension/_resolve.py
src/azure-cli-core/azure/cli/core/extension/tests/latest/test_resolve.py

{Extension} az extension add/update: remove py2.py3 check for wheel name

---

.vscode/extensions.json

The repository is currently set up with launch settings for Visual Studio Code. [The documentation](https://github.com/Azure/azure-cli/blob/dev/doc/configuring_your_machine.md#visual-studio-code-any-platform) recommends installing the Microsoft Python extension. This pull request adds it as a recommended extension so Visual Studio Code will prompt developers to install it.
I don't know what component this is supposed to be under. Let me know if I need to change the pull request title.
---

{Dev Experience} Add Microsoft Python extension as recommended Visual Studio Code extension

---

.github/pull_request_template.md

{Github} Update PR template

---

src/azure-cli/azure/cli/command_modules/acr/private_endpoint_connection.py
src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_with_private_endpoint.yaml

[ACR] handle python sdk breaking change and re-record test

---

src/azure-cli/azure/cli/command_modules/resource/_help.py

[ARM] az lock create: Add examples of creating subresource in the help documentation (#12268)

---

src/azure-cli/azure/cli/command_modules/vm/_help.py

Clarify that 'vm user delete' also removes the home directory on Linux systems.
[Compute] (az vm user delete:) Clarify that 'vm user delete' also removes the home directory on Linux systems.
---

{Compute} Doc fix for 'vm user delete'

---

src/azure-cli/azure/cli/command_modules/resource/custom.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_resource_group_deployment.yaml
src/azure-cli/azure/cli/command_modules/resource/tests/latest/simple_deploy.json

Issue: #11995
When commenting at the bottom of all elements in a JSON object, jsmin has a bug that will wrap lines.
It will affect the subsequent multi-line processing logic, so deal with this situation in advance.
---

[ARM] az deployment: Fix the parse bug for comment under the last argument (#11995)

---

src/azure-cli/azure/cli/command_modules/storage/_help.py
src/azure-cli/azure/cli/command_modules/storage/_params.py
src/azure-cli/azure/cli/command_modules/storage/operations/account.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_update_versioning.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py

[Storage] az storage account blob-service-properties update: Add --enable-versioning to support versioning for storage account

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

{ACR} Hotfix: fix azure-mgmt-containerregistry version

---

src/azure-cli/azure/cli/command_modules/vm/_params.py

#11909 
Describe --location more precisely. Tell users it will inherit from location of resource group if not specified. There are many other commands do not state it explicitly. And we can't modify it in global parameter definition because inheritance from location of resource group is a customized behavior of each command.
`az disk create -h`
`az snapshot create -h`
[Component Name 1] (BREAKING CHANGE:) (az command:) make some customer-facing …

{Compute} Update help of disk/snapshot create

---

src/azure-cli/azure/cli/command_modules/keyvault/_help.py

Customers need examples for `az keyvault key download`
---

{KeyVault} az keyvault key download: add examples

---

src/azure-cli-core/setup.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

[Core] Upgrade msrestazure to 0.6.3
Fix a bug: cannot raise exception when error string contains non-ascii character.
https://github.com/Azure/msrestazure-for-python/pull/144
https://github.com/Azure/azure-cli/issues/12199
https://github.com/Azure/azure-cli/issues/12207
https://github.com/Azure/azure-cli/issues/12315
[Component Name 2] (BREAKING CHANGE:) (az …

[Core] Upgrade msrestazure to 0.6.3

---

src/azure-cli/azure/cli/command_modules/network/_params.py

Fix #12570 
sku cannot be updated after creation for public ip.
---

[Network]deprecate sku for public ip update command

---

scripts/release/homebrew/docker/run.sh

Fix a package failure. This line is out-of-date.
---

{Package} Remove stale code in homebrew release

---

src/azure-cli/azure/cli/command_modules/batch/_parameter_format.py
src/azure-cli/azure/cli/command_modules/batch/_params.py
src/azure-cli/azure/cli/command_modules/batch/_validators.py
src/azure-cli/azure/cli/command_modules/batch/commands.py
src/azure-cli/azure/cli/command_modules/batch/tests/latest/data/batch-pool-create.json
src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_certificate_cmd.yaml
src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_job_list_cmd.yaml
src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_jobs_and_tasks.yaml
src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_pool_cmd.yaml
src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_pools_and_nodes.yaml
src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_task_create_cmd.yaml
src/azure-cli/azure/cli/command_modules/batch/tests/latest/test_batch_commands.py
src/azure-cli/azure/cli/command_modules/batch/tests/latest/test_batch_data_plane_commands.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

[Batch] Update Batch API

---

src/azure-cli/azure/cli/command_modules/appconfig/_help.py
src/azure-cli/azure/cli/command_modules/appconfig/_kv_helpers.py
src/azure-cli/azure/cli/command_modules/appconfig/_params.py
src/azure-cli/azure/cli/command_modules/appconfig/_validators.py
src/azure-cli/azure/cli/command_modules/appconfig/keyvalue.py

[Appconfig]Bug fix for list key values

---

src/azure-cli/azure/cli/command_modules/resource/_params.py
src/azure-cli/azure/cli/command_modules/resource/custom.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_resource_group_deployment.yaml
src/azure-cli/azure/cli/command_modules/resource/tests/latest/simple_extra_param_deploy.json
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py

Feature request: #11972 
`--no-prompt` is an option to disable the prompt of missing parameters for ARM template. When the value is true, the prompt requiring users to provide missing parameter will be ignored. The default value is false.
Add parameters `--no-prompt` when deploying ARM template.
---

[ARM] az deployment create/validate: Add parameter `--no-prompt` to support skipping the prompt of missing parameters for ARM template (#11972)

---

src/azure-cli/azure/cli/command_modules/vm/_params.py
src/azure-cli/azure/cli/command_modules/vm/_validators.py

https://github.com/Azure/azure-cli/issues/12838
az sig image-version create: Add storage account type Premium_LRS
az sig image-version create -g fytest --gallery-name gallery1 --gallery-image-definition image1 --gallery-image-version version --target-regions centraluseuap=1=premium_lrs  --managed-image img1 --replica-count 1
Please replace "version" with a version that does not exist yet. All the dependent resources have been created for testing. …

[Compute] az sig image-version create: Add storage account type Premium_LRS

---

.github/pull_request_template.md
azure-pipelines.yml
doc/authoring_command_modules/README.md
scripts/release/generate_history_notes.py

{Misc} Update history generation, PR template and doc

---

src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_nw_flow_log_delete.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_nw_flow_log.py

The find assertion is incorrect, fix it.
---

{Network} fix wrong usage example in test_nw_flow_log_delete

---

.github/CODEOWNERS

update codeonwers for pr review
---

{Misc} Update codeowners for pr review

---

src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/azure/cli/core/commands/__init__.py
src/azure-cli-core/azure/cli/core/commands/parameters.py
src/azure-cli-core/azure/cli/core/local_context.py
src/azure-cli/azure/cli/command_modules/resource/_params.py

Per design spec review, we will use SET/GET as the action name of local context.
---

{Core} Rename local context action from STORE/USE to SET/GET

---

src/azure-cli/azure/cli/command_modules/keyvault/custom.py

The original error message is ambiguous. Confirmed with Key Vault PM.
---

{KeyVault} Refine error messages

---

src/azure-cli/azure/cli/command_modules/resource/_params.py

[ARM] az deployment: Remove `is_preview` for parameter `--handle-extended-json-format` (#12943)

---

src/azure-cli/azure/cli/command_modules/acr/_help.py
src/azure-cli/azure/cli/command_modules/acr/_params.py
src/azure-cli/azure/cli/command_modules/acr/commands.py
src/azure-cli/azure/cli/command_modules/acr/custom.py
src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_with_dedicated_data_endpoints.yaml
src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_commands.py

Onboard dedicated data endpoint support
"az acr update -n myreg --data-endpoint-enabled"
"az acr show-endpoints"
---

[ACR] dedicated data endpoint

---

src/azure-cli/azure/cli/command_modules/vm/_help.py
src/azure-cli/azure/cli/command_modules/vm/_params.py
src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
src/azure-cli/azure/cli/command_modules/vm/_validators.py
src/azure-cli/azure/cli/command_modules/vm/custom.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_specialized_image.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

Add `--specialized` parameter for `az vm create` and `az vmss create` to support creating vm/vmss from a specialized image version
Create a VM from a specialized image version.
```
az vm create -g MyResourceGroup -n MyVm --image $id --specialized
```
Create a Linux VM scale set from a specialized image version.
```
az vmss create -n MyVmss -g MyResourceGroup --image $id --specialized
```
See `test_specialized_image()` for more detail about how to prepare specialized image version.
--- …

[Compute] az vm/vmss create: Add support for specialized image version

---

src/azure-cli/azure/cli/command_modules/acs/_help.py
src/azure-cli/azure/cli/command_modules/acs/_params.py
src/azure-cli/azure/cli/command_modules/acs/custom.py

[AKS] Add node public IP support in CLI extension.

---

src/azure-cli-core/setup.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

Change experimental tag color to cyan, corresponding to https://github.com/microsoft/knack/pull/196.
```
az <experimental extension>
```

{Core} Change experimental tag color to cyan

---

src/azure-cli/azure/cli/command_modules/storage/_params.py
src/azure-cli/azure/cli/command_modules/storage/_validators.py
src/azure-cli/azure/cli/command_modules/storage/docs/Storage Encryption .md
src/azure-cli/azure/cli/command_modules/storage/docs/Storage Encryption.md
src/azure-cli/azure/cli/command_modules/storage/operations/account.py
src/azure-cli/azure/cli/command_modules/storage/tests/hybrid_2019_03_01/test_storage_validators.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_customer_managed_key.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_validators.py

` In order to support implicit key rotation, we propose that the customer provide a reference to the un-versioned key name under “keyvaultproperties”. `
`SRP will introduce a new read-only attribute under key vault properties “currentVersionedKeyIdentifier” which represents the fully qualified object identifier of the versioned Key Vault key that is in use by XStore for protecting the Account Encryption Key (AEK). `
`Additionally, we also include a read-only “lastKeyRotationTimestamp” to indicate the time when the AEK was last wrapped with a new key version. `
`This will cause SRP to retain the specified key version for …

[Storage] az storage account update: Enable key auto-rotated for CMK

---

src/azure-cli/azure/cli/command_modules/network/_client_factory.py
src/azure-cli/azure/cli/command_modules/network/_help.py
src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/_validators.py
src/azure-cli/azure/cli/command_modules/network/commands.py
src/azure-cli/azure/cli/command_modules/network/custom.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_private_endpoint_private_dns_zone_group.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

Support private dns zone group in private endpoint
---

[Network] az network private-endpoint: Support private dns zone group.

---

src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_private_link_scope_scenario.yaml

Since we're using extension in our main repo's tests, once the api-version changed in the extension, main repo's CI would be blocked.
---

{CI}re-recording

---

src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_private_link_scope_scenario.yaml

{CI}fix ci

---

src/azure-cli/azure/cli/command_modules/network/_help.py
src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/commands.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_security_partner_provider.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

{Network}rename security-partner to security-partner-provider

---

src/azure-cli/azure/cli/command_modules/vm/_params.py

"<>" displays incorrectly in HTML. It is treated as a HTML tag.
Only at release time can I see the HTML page. This is the problem!
Plain text:
```
Space-separated list of customer managed keys for encrypting the OS and data disks in the gallery artifact for each region. Format for one region: “<os_des>,<lun1>,<lun1_des>,<lun2>,<lun2_des>”. Use "null" as a placeholder.
```
HTML page:
---

{Compute} Update doc of image-version

---

src/azure-cli/azure/cli/command_modules/vm/_format.py
src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/test_vm_commands.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

https://github.com/Azure/azure-cli/issues/13079
Table output is too long to fit in screen.
Delete "capabilities" column.
Before:
After:
az vm list-skus -l westus2 -o table
---

[Compute] az vm list-skus: Fix display problem of table format

---

src/azure-cli-core/azure/cli/core/_identity.py
src/azure-cli-core/azure/cli/core/_profile.py

[MSAL] persist access token

---

src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_sku.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py

GZRS is a new feature for storage account, which is added in enum list. Here is to add test for validation the feature.
---

[Storage] Support GZRS for storage account creation and update

---

src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_private_link_scope_scenario.yaml

{CI} fix CI issue by re-run one test

---

src/azure-cli/azure/cli/command_modules/vm/custom.py

https://github.com/Azure/azure-cli/issues/12013
Fix key error of dict read
---

[Compute] vm list-ip-addresses: Error handling

---

src/azure-cli/azure/cli/command_modules/network/_help.py

Fix https://github.com/Azure/azure-cli/issues/12614
---

{Network} fix duplicated quotes for private-endpoint example

---

src/azure-cli-core/azure/cli/core/_identity.py
src/azure-cli-core/azure/cli/core/_profile.py

{MSAL} persist ADAL cache fix bug

---

.gitattributes
build_scripts/windows/scripts/az
build_scripts/windows/scripts/build.cmd

Resolve #8560, Resolve #13033
Copy and paste the `build_scripts/windows/scripts/az` script under `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin`. Run `az -h` command on git bash/cygwin.
---

[Packaging] Add az script for Git Bash/Cygwin on Windows

---

src/azure-cli/azure/cli/command_modules/vm/_help.py
src/azure-cli/azure/cli/command_modules/vm/_params.py
src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
src/azure-cli/azure/cli/command_modules/vm/custom.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_options.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

https://github.com/Azure/azure-cli/issues/13148
[Compute] vmss create: Add --os-disk-size-gb
az vmss create -n MyVmss -g MyResourceGroup --instance-count 5 --image Win2016Datacenter --data-disk-sizes-gb 2 --os-disk-size-gb 40
---

[Compute] vmss create: Add --os-disk-size-gb

---

src/azure-cli/azure/cli/command_modules/storage/_help.py
src/azure-cli/azure/cli/command_modules/storage/_params.py
src/azure-cli/azure/cli/command_modules/storage/commands.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_failover.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py

It is been in storage-preview extension for a long time.
Here is to move it from extension.
---

[Storage] `az storage account failover`: Add support for grs/gzrs storage account failover

---

src/azure-cli/azure/cli/command_modules/storage/_client_factory.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_encryption_scope_scenarios.py

{Storage}  Support connection string

---

src/azure-cli/azure/cli/command_modules/backup/custom.py

Fixed a bug where warning message was shown in wrong scenarios
---

[Backup] Fix in IaasVM restore-disks Command

---

src/azure-cli/azure/cli/command_modules/appservice/_params.py
src/azure-cli/azure/cli/command_modules/appservice/custom.py

fix #10664 , #13257 
**Why this PR?** While trying to add VNet-integration to the webapp, getting following error:
The app and the vnet resources are in different locations. Cannot integrate a regional VNET to an app in a different region
**What is changed?**
Removed the region validation up on the confirmation from SME (@panchagnula)
**What is the effect?**
Regional check will not happen whether both the resources are in the same region or not.
**Steps to reproduce:**
`az group create -n olavs-test-rg -l westeurope`
`az appservice plan create -g olavs-test-rg -n olavs-plan -l westeurope --sku S1`
`az webapp create -g olavs-test-rg -p olavs-plan -n olavs-app`
`az network vnet create -g olavs-test-rg -n olavs-vnet --address-prefixes 10.0.0.0/8`
`az …

[AppService] fix #10664- VNet Integration - Location Check Issue & fix #13257- az webapp up failing when RG needs to be created

---

src/azure-cli/azure/cli/command_modules/network/_params.py

Fix #12807. New help message is 
---

{Network} az network private-endpoint create: refine help message for --subnet

---

src/azure-cli/azure/cli/command_modules/network/_help.py
src/azure-cli/azure/cli/command_modules/network/_validators.py

az network public-ip create: Inform customers of a coming breaking change:
- Show warning when customers running command `az network public-ip create`
- Show extra information when customers running command `az network public-ip create -h`
---

[Network] az network public-ip create: Inform customers of a coming breaking change

---

src/azure-cli/azure/cli/command_modules/aro/_help.py

[ARO] Add examples to az aro create, list, list-credentials, show, delete

---

src/azure-cli/azure/cli/command_modules/acr/_params.py
src/azure-cli/azure/cli/command_modules/acr/import.py
src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_token.py
src/azure-cli/azure/cli/command_modules/acr/token.py

2 ACR command updates, see history notes below for details
Added e2e test for token creation
Conducted manual test on image bug fixes
[ACR] az acr token create: expose --days argument
[ACR] az acr import: accept --source argument values which contain login in server name through client end correction

[ACR]: bug fixes on token create and image import commands

---

doc/configuring_your_machine.md
doc/debug/debug_in_vs_code.md

Updates for setting up a development environment to debug this project in VS Code

{Docs} Documentation update for configuring machine in VS Code

---

src/azure-cli/azure/cli/command_modules/resource/custom.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/Japanese-characters-template.json
src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_resource_group_deployment.yaml
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py

Issue: #13137 #13316
The reason for this problem is that the pipeline configuration of the requesting client was modified during the processing of `handle_extended_json_format`, resulting in incorrect request encoding:
> 'latin-1' codec can't encode characters in position 376-388: Body ('ここに日本語で説明します。') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
As prompted by the error message, change the encoding of the request to `utf-8`.
Use ARM templates with special encoding characters which not supported by `latin-1` for deployment or validation.
[Component Name 2] az command b: Add some customer-facing …

[ARM] az deployment: Fix the problem that deployment/validate does not support specially encoded character (#13137)

---

src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/resource_providers/__init__.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_mariadb_private_link_scenario.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_mysql_private_link_scenario.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_postgres_private_link_scenario.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py

[Network] az network private-endpoint-connection: Support mysql, postgre and mariadb types

---

src/azure-cli/azure/cli/command_modules/acr/commands.py

In a previous PR, the "preview" flag was removed, but after considered possible change in future, I feel more comfortable to stay in "preview" for a while. This PR must be merged by the upcoming release; otherwise, we will not be able to move back to preview

{ACR} keep show-endpoints command in preview

---

src/azure-cli-core/azure/cli/core/_help.py
src/azure-cli-core/azure/cli/core/commands/arm.py
src/azure-cli-core/azure/cli/core/commands/parameters.py
src/azure-cli-core/azure/cli/core/tests/test_generic_update.py
src/azure-cli/azure/cli/command_modules/ams/operations/content_key_policy.py
src/azure-cli/azure/cli/command_modules/ams/operations/sp.py
src/azure-cli/azure/cli/command_modules/ams/tests/latest/test_ams_job_scenarios.py
src/azure-cli/azure/cli/command_modules/appservice/azure_devops_build_interactive.py
src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
src/azure-cli/azure/cli/command_modules/batchai/custom.py
src/azure-cli/azure/cli/command_modules/network/custom.py
src/azure-cli/azure/cli/command_modules/resource/tests/hybrid_2018_03_01/test_locks.py
src/azure-cli/azure/cli/command_modules/resource/tests/hybrid_2018_03_01/test_resource.py
src/azure-cli/azure/cli/command_modules/resource/tests/hybrid_2019_03_01/test_locks.py
src/azure-cli/azure/cli/command_modules/resource/tests/hybrid_2019_03_01/test_resource.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_locks.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_formatters.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_utils.py
src/azure-cli/azure/cli/command_modules/role/custom.py
src/azure-cli/azure/cli/command_modules/sql/custom.py
src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
src/azure-cli/azure/cli/command_modules/vm/_image_builder.py
src/azure-cli/azure/cli/command_modules/vm/_vm_utils.py
src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2018_03_01/test_vm_commands.py
src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/test_vm_commands.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

Fix https://github.com/Azure/azure-cli/issues/13448
---

[CI] Support flake8 3.8.0

---

src/azure-cli/azure/cli/command_modules/network/_help.py
src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/_validators.py
src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/resource_providers/__init__.py
src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/resource_providers/keyvault_provider.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_cosmosdb.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_link_resource_cosmosdb.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py

rename `service-name` to `resource-name`
---

[Network] az network private-endpoint-connection: Support cosmosdb types

---

.azure-pipelines/templates/azdev_setup.yml
azure-pipelines.yml

{CI} Code style check use latest azdev

---

src/azure-cli-core/azure/cli/core/_identity.py
src/azure-cli-core/azure/cli/core/_profile.py

Store Service principal in MSAL secret store 

---

azure-pipelines.yml
scripts/ci/credscan/CredScanSuppressions.json

Follow up of https://github.com/Azure/azure-cli/pull/13388
---

{CI} Re-enable CredScan

---

src/azure-cli-testsdk/azure/cli/testsdk/base.py

Previous PR only turn off local context, not delete the persisted file. Add this.
Run test and there is no local context file left.
---

{TestSDK} Delete local context file when local context scenario test is finished

---

src/azure-cli/azure/cli/command_modules/aro/custom.py

During `az aro create`, the random string that would be created would fail the install because cluster names must start with a lowercase letter.  This change will add the function to generate the name with the first character being a lowercase letter.
---

[ARO]Add generate_random_id function 

---

src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_formatters.py

The previous merged PR https://github.com/Azure/azure-cli/commit/a6381302fe4e0b0fad2407d6bc03c2d8cfb42553 break the code style
---

{Resource} Remove unused f-string to fix code style

---

src/azure-cli/azure/cli/command_modules/backup/_format.py
src/azure-cli/azure/cli/command_modules/backup/_params.py

Added "MAB" BackupManagementType to item list command
---

[Backup] Add "MAB" BackupManagementType to item list command

---

src/azure-cli/azure/cli/command_modules/backup/_params.py
src/azure-cli/azure/cli/command_modules/backup/custom_base.py
src/azure-cli/azure/cli/command_modules/backup/custom_wl.py
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_wl_sql_policy.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/test_workload_commands.py

added support for retrying policy update for failed items.
---

[Backup] Add support for retrying policy update for failed items.

---

src/azure-cli/azure/cli/command_modules/backup/custom.py
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_policy.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/test_backup_commands.py

Added support to specify ResourceGroup for stroing instantRP during Create or Modify Policy 
---

[Backup] Add support to specify ResourceGroup for storing instantRP during Create or Modify Policy 

---

doc/use_cli_effectively.md
src/azure-cli/azure/cli/command_modules/resource/_help.py

Fix https://github.com/Azure/azure-cli/issues/10731
---

{Resource} Add example to tell how to pass array to --parameters

---

azure-pipelines.yml
scripts/release/debian/pipeline.sh

[Packaging] Add Ubuntu Focal Package

---

src/azure-cli/azure/cli/command_modules/aro/tests/latest/test_aro_helpers.py

Add test to confirm `generate_random_id()` in `src/azure-cli/azure/cli/command_modules/aro/custom.py` validates return value starts with a string and contains alphanumeric chars with a length of 8.
---

[Aro]Add tests for generate_random_id function

---

src/azure-cli/azure/cli/command_modules/monitor/_params.py
src/azure-cli/azure/cli/command_modules/monitor/operations/diagnostics_settings.py
src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_diagnostic_settings_scenario.yaml
src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_diagnostic_settings.py

[Monitor] az monitor diagnostic-settings create: support --export-to-specific-resource argument

---

src/azure-cli/azure/cli/command_modules/monitor/operations/autoscale_settings.py
src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_autoscale.py

{Monitor} az monitor autoscale profile show: bug fix

---

doc/extensions/authoring.md

Fix typo in extension authoring doc
`adev` -> `azdev`.
The command is `azdev`, not `adev`.
n/a. Doc change.
n/a
---
- [n/a] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).
- [n/a] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

{Misc.} Fix typo in extension authoring doc

---

src/azure-cli/azure/cli/command_modules/network/_help.py

This PR fixed #13157:  
`az network vpn-connection ipsec-policy`: change the --sa-lifetime and --sa-max-size to larger values in example.
---

[Network] az network vpn-connection ipsec-policy: change the --sa-lifetime and --sa-max-size to larger values in example

---

src/azure-cli-core/azure/cli/core/commands/arm.py
src/azure-cli/azure/cli/command_modules/monitor/_help.py
src/azure-cli/azure/cli/command_modules/monitor/_params.py
src/azure-cli/azure/cli/command_modules/monitor/operations/metric_alert.py

[Monitor] az monitor metrics alert: refine several help messages

---

README.md

Resolve #8603
Resolve #8604
---

{Install} Update edge build instruction

---

src/azure-cli/azure/cli/command_modules/acr/token.py

[ACR] fix a typo in an error message of token create

---

azure-pipelines.yml
src/azure-cli-testsdk/azure/cli/testsdk/base.py
src/azure-cli-testsdk/azure/cli/testsdk/patches.py
src/azure-cli/azure/cli/command_modules/dla/tests/latest/recording_processors.py
src/azure-cli/azure/cli/command_modules/dls/tests/latest/test_dls_commands.py
src/azure-cli/setup.py

{CI} Hack solution to unblock CI first

---

src/azure-cli/azure/cli/command_modules/resource/custom.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_group_deployment.yaml
src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_resource_group_deployment.yaml
src/azure-cli/azure/cli/command_modules/resource/tests/latest/simple_deploy_invalid.json
src/azure-cli/azure/cli/command_modules/resource/tests/latest/simple_deploy_parameters_invalid.json
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py

Issue: #13159
When the JSON format of the template file or parameter file is not correct, the following error will be reported:
```pwsh
Expecting value: line 1 column 337 (char 336)
```
There are two problems with it:
1. Because the processing of removing comments and compression in the method `_remove_comments_from_json` will lead to misplacement of error location in error message, so the error message should be wrapped.
2. It does not prompt the specific error file. It may be a template file or a parameter file.
Deploy or verify the template file or parameter file with incorrect JSON format. …

[ARM] az deployment: Fix the problem of incorrect message of JSON after removing comments and compressing (#13159)

---

src/azure-cli/azure/cli/command_modules/hdinsight/_params.py

Change get_json_object to shell_safe_json_parse to avoide converting json key to snake case
---

[HDInsight] Change get_json_object to shell_safe_json_parse

---

src/azure-cli/azure/cli/command_modules/monitor/_params.py
src/azure-cli/azure/cli/command_modules/monitor/operations/diagnostics_settings.py
src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_diagnostic_settings.py

[Monitor] az monitor diagnostic-settings create: support --export-to-resource-specific argument

---

src/azure-cli/azure/cli/command_modules/network/_params.py

{Network} Refine help message

---

src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_event_grid_domain.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_event_grid_topic.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_link_resource_event_grid.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py

[Network] az network private-endpoint-connection: support event grid

---

src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/commands.py
src/azure-cli/azure/cli/command_modules/network/custom.py

Fix https://github.com/Azure/azure-cli/issues/13162
---

[Network] express-route list-route-tables: fix bug that cannot list routes as table

---

doc/private_endpoint_connection_command_guideline.md

{Network} refine guidance doc for private link scenario

---

src/azure-cli/azure/cli/command_modules/resource/_help.py

[ARM] Improve the examples for the resource module (#12906) 

---

src/azure-cli-core/azure/cli/core/parser.py
src/azure-cli-core/azure/cli/core/telemetry.py
src/azure-cli/azure/cli/__main__.py

Add error of command result to telemetry when it's not added inside the module.
Example data:
```
{"name": "azurecli/fault",
"properties": {
"Reserved.DataModel.EntityType": "Fault",
"Reserved.DataModel.Fault.Description": "",
"Reserved.DataModel.Correlation.1": "7a3155c0-7237-4ae2-8500-f547e99713d5,UserTask,",
"Reserved.DataModel.Fault.TypeString": "CLIError",
"Reserved.DataModel.Fault.Exception.Message": "Please provide subscription id or unique name.",
"Reserved.DataModel.Fault.Exception.StackTrace": "[]",
...}
}
```
--- …

{Telemetry} Log exception

---

src/azure-cli-core/azure/cli/core/extension/operations.py

Resolve #13706 
`_run_pip` is also used by the azure-devops extension, make it backward-compatible.
---

{Extension} Fix _run_pip

---

src/azure-cli/azure/cli/command_modules/storage/_help.py

Fix #13131 
Add one more example for subnet in another resource group.
---

{Storage} `az storage account network-rule add`: add example for subnet usage

---

src/azure-cli/azure/cli/command_modules/dls/tests/latest/recordings/test_dls_account_mgmt.yaml
src/azure-cli/azure/cli/command_modules/storage/operations/logging.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_logging_operations.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py

Fix #11969 
When storage account is BlobStorage or PremiumStorage, we cannot logging for some storage services and the RetryError will be thrown as shown in the issue, which is not  user friendly.
1. prepare a blob storage account or premium storage account
2. `az storage logging show`
---

[Storage ] `az storage logging`: Fix issue #11969 to refine error message

---

.github/CODEOWNERS
linter_exclusions.yml

{CI} Add global linter exclusions for new linter rules

---

src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_encryption_set_update.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

Key rotation in disk encryption set was not supported in previous version of service. Now the service has supported it.
---

{Compute} testing disk encryption set update

---

src/azure-cli/azure/cli/command_modules/appconfig/keyvalue.py

{AppConfig} Remove warning when updating KeyVault reference

---

src/azure-cli/azure/cli/command_modules/keyvault/_params.py
src/azure-cli/azure/cli/command_modules/keyvault/_validators.py
src/azure-cli/azure/cli/command_modules/keyvault/custom.py
src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_key.yaml
src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py

This PR implements the feature request #13685 
Just run the test suite, f. e. "azdev test keyvault"
[Keyvault] 'az keyvault key import' now supports importing from strings via two new parameters.

[KeyVault] Add functionality to import a key from string

---

src/azure-cli/azure/cli/command_modules/monitor/_client_factory.py
src/azure-cli/azure/cli/command_modules/monitor/_help.py
src/azure-cli/azure/cli/command_modules/monitor/_params.py
src/azure-cli/azure/cli/command_modules/monitor/commands.py
src/azure-cli/azure/cli/command_modules/monitor/operations/log_analytics_workspace.py
src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_log_analytics_workspace_saved_search.yaml
src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_log_analytics_workspace.py

Fix #13562. Fix Azure/azure-cli-extensions#1613
---

[Monitor] az monitor log-analytics workspace saved-search: Support new commands for saved search

---

src/azure-cli-core/azure/cli/core/_identity.py
src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/authentication.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile_v2016_06_01.py
src/azure-cli/azure/cli/command_modules/appconfig/_kv_helpers.py
src/azure-cli/azure/cli/command_modules/keyvault/_completers.py
src/azure-cli/azure/cli/command_modules/profile/__init__.py
src/azure-cli/azure/cli/command_modules/role/custom.py
src/azure-cli/azure/cli/command_modules/servicefabric/custom.py
src/azure-cli/azure/cli/command_modules/vm/_vm_utils.py

[MSAL] fix style errors

---

src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/_validators.py
src/azure-cli/azure/cli/command_modules/network/custom.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_with_subnet_nsg.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

[Network] az network vnet create: support --nsg argument

---

src/azure-cli/azure/cli/command_modules/monitor/_params.py
src/azure-cli/azure/cli/command_modules/monitor/operations/log_analytics_workspace.py
src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_log_analytics_workspace_saved_search.yaml

{Monitor} az monitor log-analytics workspace saved-search: remove --version argument

---

src/azure-cli/azure/cli/command_modules/acs/_validators.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_validators.py

{AKS}: Correct the error message when the label has more than 63 chars

---

doc/use_cli_effectively.md

The visibility of "_Quoting issues with PowerShell_" is still not high enough, leading to https://github.com/Azure/azure-cli/issues/13882.
Moving it to the top of the section.

{Doc} Increase visibility of "Quoting issues with PowerShell"

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/azure/cli/core/_identity.py
src/azure-cli-core/azure/cli/core/_msal.py
src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/authentication.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile_v2016_06_01.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__init__.py
src/azure-cli/azure/cli/command_modules/profile/__init__.py
src/azure-cli/azure/cli/command_modules/profile/tests/latest/test_profile_custom.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

[MSAL] fix issues in profile test

---

src/azure-cli-core/azure/cli/core/commands/constants.py

The new link is for the Qualtrics in-tool HaTS survey.
The old link is for survey monkey.
---

{Survey} Update HaTS survey link

---

src/azure-cli-core/setup.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

[MSAL] upgrade azure-identity

---

src/azure-cli-core/setup.py
src/azure-cli/azure/cli/command_modules/resource/_help.py
src/azure-cli/azure/cli/command_modules/resource/commands.py
src/azure-cli/azure/cli/command_modules/resource/custom.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_feature_unregister.yaml
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

Add az feature unregister api
Issue Raised: https://github.com/Azure/azure-cli/issues/8941

[ARM] Add az feature unregister api

---

src/azure-cli-testsdk/azure/cli/testsdk/preparers.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_adls_filesystem_scenarios.yaml

{azure-cli-testsdk} Change StoragePreparer() behavior for hns

---

doc/extensions/authoring.md

External companies might wonder how to release an extension such as HashiCorp as discussed in email.
---

{Doc} Refine extension release notes

---

doc/use_cli_with_git_bash.md

Create an intial doc for Azure CLI usage on Git Bash. Best practice or workaround for issues with Git Bash can be put in this doc.
---

{Doc} Add Git Bash doc

---

src/azure-cli/azure/cli/command_modules/storage/_params.py
src/azure-cli/azure/cli/command_modules/storage/_validators.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_logging_operations.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py

Fix issue #13232 
For table service, the supported version is only 1.0 . 
`az storage logging update`
---

[Storage] `az storage logging update`: Add check for logging version

---

src/azure-cli/azure/cli/command_modules/network/_actions.py
src/azure-cli/azure/cli/command_modules/network/_help.py
src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/custom.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_address_pool_addresses.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test-address-pool-config.json
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

{Network} az network lb address-pool create: support global --vnet argument

---

src/azure-cli/azure/cli/command_modules/network/_validators.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_nic_app_gateway.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

[Network] az network application-gateway address-pool: fix for --add argument

---

src/azure-cli/azure/cli/command_modules/storage/_validators.py

Fix #13708 to refine error message
---

[Storage] Fix issue 13708 to refine warning message for credential

---

src/azure-cli/azure/cli/command_modules/storage/oauth_token_util.py

Here is to reduce time buffer for token valid time, which also will satisfy the change for MSAL.
---

{Storage} Change the valid token left expire time to 3min

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp_remote_debug.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp_remote_ssh.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
src/azure-cli/azure/cli/command_modules/appservice/tunnel.py

This PR improves the error message(s) and adds fail fast scenarios for the customers using Azure CLI to SSH to their App Service on Linux instances. We leverage the new version of the status API to determine if an app container exposes the port 2222 and and provide fail fast errors with links to the documentation for customers who have incorrectly configured the SSH setup on their custom docker images.  

[AppService] Improved error messages for SSH Tunnel Connection

---

doc/use_cli_effectively.md
src/azure-cli/azure/cli/command_modules/util/_help.py
src/azure-cli/azure/cli/command_modules/util/_params.py

{Rest} az rest: Add examples to --url-parameters

---

src/azure-cli/azure/cli/command_modules/acs/custom.py

1. allow scale nodepool to zero count
2. If autoscaler is enabled for a nodepool, manual scale will be blocked.
Create a user nodepool without autoscaler enabled, scale it to 0 node using the following command should be supported.
az aks nodepool scale --cluster-name <cluster name>--name <nodepool name>--resource-group <rg> --node-count 0
Enable autoscaler for that nodepool, use the command above, and changed the node-count to a different number, the manual should be blocked by cli.
--- …

[AKS] Change to support 0 node agent pool and block manual scale for CAS enabled pool

---

src/azure-cli-testsdk/azure/cli/testsdk/__init__.py
src/azure-cli-testsdk/azure/cli/testsdk/preparers.py

[TestSDK] add VirtualNetworkPreparer, VnetNicPreparer

---

src/azure-cli/azure/cli/command_modules/acr/_stream_utils.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

Handle new parameter logArtifactLink when streaming logs.
This new parameter will point to a registry artifact which contains the task run logs

[ACR] Handle log artifact link from Registry to stream logs

---

src/azure-cli/azure/cli/command_modules/monitor/commands.py

This PR will remove "Preview" flag for commands under Log Analytics workspace.
---

[Monitor] Remove preview flag for commands under Log Analytics workspace

---

src/azure-cli/azure/cli/command_modules/network/_params.py

{Network} az network dns record-set cname: refine help message for `--cname`

---

src/azure-cli/azure/cli/command_modules/appconfig/_help.py
src/azure-cli/azure/cli/command_modules/appconfig/_params.py

[AppConfig]Add example for using --fields in appconfig revision 

---

src/azure-cli/azure/cli/command_modules/vm/_params.py

Resolve https://github.com/Azure/azure-cli/issues/13918
Remove preview label of `--eviction-policy` in `vmss create`
---

{Compute} Remove preview label of --eviction-policy in vmss create

---

src/azure-cli/azure/cli/command_modules/storage/_client_factory_azure_stack.py
src/azure-cli/azure/cli/command_modules/storage/_format.py
src/azure-cli/azure/cli/command_modules/storage/_transformers_azure_stack.py
src/azure-cli/azure/cli/command_modules/storage/_validators_azure_stack.py
src/azure-cli/azure/cli/command_modules/storage/commands.py
src/azure-cli/azure/cli/command_modules/storage/commands_azure_stack.py
src/azure-cli/azure/cli/command_modules/storage/operations/blob_azure_stack.py
src/azure-cli/azure/cli/command_modules/storage/operations/directory_azure_stack.py
src/azure-cli/azure/cli/command_modules/storage/operations/file_azure_stack.py

To separate Azure Cloud and Azure Stack in storage module, we need to build different context with separated file system:
- commands.py : command table
- _params.py: argument context
- _client_factory.py: client factory
- _transformers.py: transform operations
- _validators.py: validate functions
Note：
- _formats.py is used for table transformer operations
- _transformer.py is used for transform operations
`azdev test storage`
`azdev test storage --profile 2019-03-01-hybrid`
---

{Storage} Build azure stack context 

---

src/azure-cli/azure/cli/command_modules/acs/custom.py

Description -
Changes for container monitoring for USNat and USSec.

{Container monitoring} -Changes for container monitoring to support USNat and USSec

---

scripts/release/debian/build.sh
scripts/release/rpm/azure-cli.spec
scripts/release/rpm/build.sh

[MSAL] fix build error in Linux setup build

---

scripts/release/debian/build.sh
scripts/release/rpm/Dockerfile.centos
scripts/release/rpm/Dockerfile.fedora

[MSAL]Fix build error for linux setup

---

src/azure-cli-core/azure/cli/core/authentication.py

[MSAL]Fix get token failure use track2 SDK

---

scripts/release/debian/build.sh
src/azure-cli-core/azure/cli/core/authentication.py

[MSAL]Fix build error in trusty

---

src/azure-cli/azure/cli/command_modules/storage/oauth_token_util.py

For managed identity, users will be blocked by exception. Because token should be valid and refreshed by server side and we honor it, removing the check should be no effect and add logger to find why users sometimes will get token to be expired in 3mins.
---

[Storage] Remove check in token credential

---

scripts/release/debian/build.sh
scripts/release/rpm/Dockerfile.centos
scripts/release/rpm/Dockerfile.fedora

[MSAL]Fix rpm build error

---

azure-pipelines.yml
scripts/release/debian/build.sh
scripts/release/rpm/Dockerfile.centos
scripts/release/rpm/Dockerfile.fedora

[MSAL]Install dependency in deb test

---

src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_oauth.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_filedatalake_oauth.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_oauth.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_oauth_track2.py

record_only() will make the test skipped in live mode.
`azdev test test_storage_blob_oauth --live`
`azdev test test_storage_filedatalake_oauth --live`
---

{Storage} Oauth tests can be run in live mode

---

src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_metric_alert_scenarios.py

{Monitor} add record only for the deprecated commands

---

azure-pipelines.yml
scripts/release/debian/build.sh
scripts/release/debian/prepare.sh

[MSAL]Fix debian dependency in 14.04

---

.github/CODEOWNERS

Remove the ownership for document.
---

{Doc} Change code owner

---

azure-pipelines.yml

[MSAL]Fix debian build hang issue

---

src/azure-cli/azure/cli/command_modules/storage/track2_util.py

Add transform util for track2 to support underline to hump.
---

{Storage} Add transform util for track2

---

src/azure-cli/azure/cli/command_modules/network/_validators.py

{Network} az network private-endpoint-connection: fix error message

---

src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_blob_scenarios.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_container_immutability_policy.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_container_legal_hold.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_file_rm_scenarios.py

AllowLargeResponse() cannot be added in class level, which will cause pytest cannot find related tests, so fix it   
---

{Storage} Fix test error for AllowLargeResponse()

---

src/azure-cli/azure/cli/command_modules/network/_help.py
src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/custom.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_express_route_connection_routing_configuration.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

This PR supports routing configuration on express-route connection in #12959.
`az network express-route gateway connection create/update --gateway-name MyGateway -n MyExpressRouteConnection -g MyResourceGroup --peering /subscriptions/MySub/resourceGroups/MyResourceGroup/providers/Microsoft.Network/expressRouteCircuits/MyCircuit/peerings/AzurePrivatePeering --associated-route-table /MySub/resourceGroups/MyResourceGroup/providers/Microsoft.Network/virtualHubs/MyHub/hubRouteTables/MyRouteTable1 --propagated-route-tables /MySub/resourceGroups/MyResourceGroup/providers/Microsoft.Network/virtualHubs/MyHub/hubRouteTables/MyRouteTable1 /MySub/resourceGroups/MyResourceGroup/providers/Microsoft.Network/virtualHubs/MyHub/hubRouteTables/MyRouteTable2 --labels …

[Network] az network express-route gateway connection: support routing configuration

---

src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py

Modify aux_subscription to be generic one in cross tenant case.
> Let’s use Azure CLI Tests with TTL = 2 Days(1c638cf4-608f-4ee6-b680-c329e824c3a8) for cross tenant cases from now on. 
> We will use this subscription for all cross tenant case, and it will help Feiyue’s live test go through all these cases.
---

{ARM} az deployment: Modify aux_subscription to be generic one in cross tenant case 

---

src/azure-cli/azure/cli/command_modules/resource/custom.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_tag_update_by_patch.yaml
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py

[ARM] az resource tag: Fix the problem of tagging resources with resource type `Microsoft.ContainerInstance/containerGroups`

---

scripts/release/rpm/azure-cli.spec

[MSAL]Fix centos8 setup isue

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py

Fix for #14208 
---
@panchagnula 
FYI - @jvano

[AppService] Fix #14208 multi-container app creation fails

---

src/azure-cli/azure/cli/command_modules/storage/_validators.py
src/azure-cli/azure/cli/command_modules/storage/_validators_azure_stack.py

{Storage} Fix typo stoarge -> storage

---

scripts/release/rpm/Dockerfile.centos
scripts/release/rpm/Dockerfile.fedora
scripts/release/rpm/azure-cli.spec

[MSAL]Remove centos setup dependency

---

src/azure-cli/azure/cli/command_modules/vm/_help.py

Resolves https://github.com/MicrosoftDocs/azure-docs/issues/58102
---

{Compute} update help of sig image-version update

---

scripts/release/rpm/Dockerfile.centos
scripts/release/rpm/Dockerfile.fedora
scripts/release/rpm/azure-cli.spec

[MSAL]Fix centos setup dependency

---

src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_taskrun_commands.py
src/azure-cli/azure/cli/command_modules/batch/tests/latest/test_batch_data_plane_commands.py
src/azure-cli/azure/cli/command_modules/batchai/tests/latest/test_batchai_custom.py
src/azure-cli/azure/cli/command_modules/batchai/tests/latest/test_batchai_scenario.py
src/azure-cli/azure/cli/command_modules/deploymentmanager/tests/latest/test_deploymentmanager_scenario.py
src/azure-cli/azure/cli/command_modules/resource/tests/hybrid_2018_03_01/test_resource.py
src/azure-cli/azure/cli/command_modules/resource/tests/hybrid_2019_03_01/test_resource.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_image_builder_commands.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

1. Add double quotes for file path parameters to make it still work when there're spaces in the file path.
2. Use `os.path.join()` to join file path, so the tests work across Windows and Posix systems. 
3. Add `--admin-username` in `vm/vmss create` explicitly due to #14265 
---

{Test} Make tests more robust

---

.azure-pipelines/templates/azdev_setup.yml
azure-pipelines.yml

Fix https://github.com/Azure/azure-cli/issues/14301
---

{CI} Revert to use azdev release version

---

azure-pipelines.yml
scripts/release/debian/build.sh

[MSAL]verify remove deb setup dependency

---

azure-pipelines.yml
scripts/release/debian/build.sh

[MSAL] improve deb setup dependency

---

src/azure-cli/azure/cli/command_modules/network/custom.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_address_pool_addresses.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

{Network} az network lb address-pool: refine error message

---

src/azure-cli/azure/cli/command_modules/acr/check_health.py
src/azure-cli/azure/cli/command_modules/acr/custom.py

Simple error polishing. Fix #12936, Fix #14196

[acr] simple error polish

---

src/azure-cli/azure/cli/command_modules/storage/oauth_token_util.py

{Storage} Use total seconds to compute expiresIn time for storage data plane Oauth scenarios

---

src/azure-cli/azure/cli/command_modules/monitor/grammar/MetricAlertCondition.g4
src/azure-cli/azure/cli/command_modules/monitor/grammar/MetricAlertConditionLexer.py
src/azure-cli/azure/cli/command_modules/monitor/grammar/MetricAlertConditionListener.py
src/azure-cli/azure/cli/command_modules/monitor/grammar/MetricAlertConditionParser.py
src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_unittest.py

{Monitor} az monitor metrics alert: support `|` and `,` in dimension value.

---

src/azure-cli/azure/cli/command_modules/storage/__init__.py
src/azure-cli/azure/cli/command_modules/storage/_params.py

[Storage] Fix issue #14138: make some permissions optional

---

.github/CODEOWNERS

{codeowner} update codeowner for storage

---

src/azure-cli/azure/cli/command_modules/network/_help.py

{Network} az network nsg rule: fix help message

---

src/azure-cli/azure/cli/command_modules/monitor/actions.py

Fix https://github.com/Azure/azure-cli/pull/14402#discussion_r457210399
---

{Monitor} fix typo

---

doc/onboarding_guide.md

{Docs} Add reference to code gen onboarding doc

---

src/azure-cli/azure/cli/command_modules/appconfig/_params.py
src/azure-cli/azure/cli/command_modules/appconfig/_utils.py
src/azure-cli/azure/cli/command_modules/appconfig/custom.py
src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/export.json
src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/export_features.json
src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/export_features_prop.json
src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/export_features_yaml.json

[AppConfig]Default to standard sku if not specified 

---

src/azure-cli/azure/cli/command_modules/aro/_rbac.py
src/azure-cli/azure/cli/command_modules/aro/custom.py
src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_create.yaml
src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_delete.yaml
src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_list.yaml
src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_list_credentials.yaml
src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_show.yaml
src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_update.yaml
src/azure-cli/azure/cli/command_modules/aro/tests/latest/test_aro_commands.py

The ARO integration testing was failing due to unstable UUID  for [role assingment](https://github.com/Azure/azure-cli/blob/b38e150c5d41f80859b329612f8cd70c9d1efc2a/src/azure-cli/azure/cli/command_modules/aro/_rbac.py#L39).
The issue is solved using mock GUID generation.
---

{ARO} Fix integration tests for aro subcommand

---

src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

{Network} add @AllowLargeResponse for three tests

---

src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_soft_delete.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_batch_operations.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_blob_live_scenarios.py

{Storage} Fix live test

---

src/azure-cli/azure/cli/command_modules/storage/operations/azcopy.py

{Misc} Fix typo trandfer -> transfer

---

src/azure-cli/azure/cli/command_modules/monitor/_exception_handler.py
src/azure-cli/azure/cli/command_modules/monitor/_params.py
src/azure-cli/azure/cli/command_modules/monitor/commands.py
src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_log_analytics_workspace_data_export.yaml
src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_log_analytics_workspace.py
src/azure-cli/azure/cli/command_modules/monitor/validators.py

[Monitor] az monitor log-analytics workspace data-export: support event hub namespace as the destination.

---

src/azure-cli/azure/cli/command_modules/sqlvm/tests/latest/recordings/test_sqlvm_add_and_remove.yaml
src/azure-cli/azure/cli/command_modules/sqlvm/tests/latest/recordings/test_sqlvm_create_and_delete.yaml
src/azure-cli/azure/cli/command_modules/sqlvm/tests/latest/recordings/test_sqlvm_group_mgmt.yaml
src/azure-cli/azure/cli/command_modules/sqlvm/tests/latest/test_sqlvm_commands.py

This PR has been created to address the issue: https://github.com/Azure/azure-cli/issues/14291 
sql vm tests where not properly running. Removing the unit test skipping and adding the yaml files with the new recordings. 
Please note that there are no command changes. Just created the storage account initially a StorageV2 instead of setting it later on. This unblocked the one error we were seeing on one of the tests. The other test was just re-run without issues. 
This is internal, no external CLI changes. 
{sqlvm} running failed tests and adding new recordings. 
---

{sqlvm} Re-running sql vm tests that were failing. 

---

src/azure-cli/azure/cli/command_modules/cognitiveservices/tests/latest/recordings/test_cognitiveservices_network_rules.yaml
src/azure-cli/azure/cli/command_modules/cognitiveservices/tests/latest/recordings/test_cognitiveservices_private_endpoint.yaml
src/azure-cli/azure/cli/command_modules/cognitiveservices/tests/latest/recordings/test_cognitiveservices_private_endpoint_connection.yaml
src/azure-cli/azure/cli/command_modules/cognitiveservices/tests/latest/test_private_endpoint.py
src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py

Add private endpoint support for Cognitive Services.
{Cognitive Services} Add private endpoint support for Cognitive Services.---

{Cognitive Services} Add private endpoint support for Cognitive Services.

---

src/azure-cli/azure/cli/command_modules/vm/_client_factory.py
src/azure-cli/azure/cli/command_modules/vm/_help.py
src/azure-cli/azure/cli/command_modules/vm/commands.py

azure stack support has already been done in our extension repo. https://github.com/Azure/azure-cli-extensions/pull/1817

{Monitor} Remove unnecessary code from vm module, support azure stack and add example

---

src/azure-cli/azure/cli/command_modules/storage/commands.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_filedatalake_oauth.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_oauth_track2.py

[Storage] `az storage fs access`: Support AAD credential in managing access control for ADLS Gen2 account

---

src/azure-cli/azure/cli/command_modules/network/_help.py
src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/commands.py
src/azure-cli/azure/cli/command_modules/network/custom.py

Fix https://github.com/Azure/azure-cli/issues/14311
---

[Network] application-gateway private-link add: Support to specify an existing subnet by ID

---

.github/CODEOWNERS

Update code owner to reduce noise for the teammate.

{Mics} Update code owner

---

.flake8
src/azure-cli-core/azure/cli/core/telemetry.py
src/azure-cli/azure/cli/__main__.py

{Telemetry} Add command init and invoke time in telemetry

---

src/azure-cli/azure/cli/command_modules/acr/custom.py
src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_with_dedicated_data_endpoints.yaml

remove client end validation because service end has already added the check

{acr} remove client end validation

---

.github/CODEOWNERS

{Container} Modify the code owner of container

---

src/azure-cli/azure/cli/command_modules/network/_util.py

{Network} az network application-gateway auth-cert show: refine error message

---

src/azure-cli/azure/cli/command_modules/network/_params.py

{Network} az nework private-endpoint: refine help message for --group-id

---

src/azure-cli/azure/cli/command_modules/acs/_help.py
src/azure-cli/azure/cli/command_modules/acs/commands.py
src/azure-cli/azure/cli/command_modules/acs/custom.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_nodepool_create_scale_delete.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py

This PR add the command to support customer get the available upgrade versions  for an agent pool of the managed Kubernetes cluster. The corresponding REST API entry: https://docs.microsoft.com/en-us/rest/api/aks/agentpools/getupgradeprofile
az aks get-upgrades --resource-group MyResourceGroup --cluster-name MyManagedCluster --nodepool-name MyNodePool
---

[AKS] Add az aks nodepool get-upgrades command

---

src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/custom.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_waf_policy_with_application_gateway.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_waf_policy_with_version_and_type.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

[Network] az network application-gateway waf-policy create: support version and type

---

src/azure-cli/azure/cli/command_modules/storage/_params.py

{Storage} GA release for --allow-blob-public-access and --min-tls-version

---

src/azure-cli/azure/cli/command_modules/resource/_formatters.py
src/azure-cli/azure/cli/command_modules/resource/_help.py
src/azure-cli/azure/cli/command_modules/resource/_params.py
src/azure-cli/azure/cli/command_modules/resource/_utils.py
src/azure-cli/azure/cli/command_modules/resource/commands.py
src/azure-cli/azure/cli/command_modules/resource/custom.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_management_group_level_what_if.yaml
src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_tenant_level_what_if.yaml
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_custom.py
src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_utils.py

The PR adds new commands/parameters to support MG-level and tenant-level deployment What-If.
`az deployment mg what-if -m <mg_id> -f <path_to_deployment_file> -l <location>`
`az deployment tenant what-if -f <path_to_deployment_file> -l <location>`
`az deployment mg create -m <mg_id> -f <path_to_deployment_file> -l <location> -c`
`az deployment tenant create -f <path_to_deployment_file> -l <location> -c`
[ARM] az deployment mg/tenant what-if: Add support to management group and tenant level deployment What-If
[ARM] az deployment mg/tenant create: Add --confirm-with-what-if/-c parameter.
[ARM] az deployment mg/tenant create: Add --what-if-result-format/-r parameter.
[ARM] az deployment mg/tenant create: Add …

[ARM] az deployment mg/tenant what-if: Add support to management group and tenant level deployment What-If

---

src/azure-cli-core/azure/cli/core/cloud.py

The suffixes in [ARM metadata](https://management.azure.com/metadata/endpoints?api-version=2019-05-01) do not start with `.` while in CLI hard-coded endpoints, some suffixes start with `.`. To make ARM metadata compatible with existing CLI code, this PR patches some suffixes from ARM metadata to begin with `.`
This PR also patches some endpoints that do not exist in ARM metadata yet.
1. Get the output of `az cloud list`
2. Set metadata url env:
`export ARM_CLOUD_METADATA_URL='https://management.azure.com/metadata/endpoints?api-version=2019-05-01'`
2. Run `az cloud list` and compare the results with the previous output.
[Component Name 2] …

{Cloud} Patch some suffixes and missing endpoints from ARM metadata

---

src/azure-cli/azure/cli/command_modules/vm/_validators.py
src/azure-cli/azure/cli/command_modules/vm/custom.py

Resolve https://github.com/Azure/azure-cli/issues/14602
{Compute} Fix an issue in vmss create, VM orchestration mode
---

{Compute} Fix an issue in vmss create, VM orchestration mode

---

src/azure-cli-core/azure/cli/core/commands/client_factory.py
src/azure-cli/azure/cli/command_modules/storage/_client_factory.py
src/azure-cli/azure/cli/command_modules/storage/_validators.py

{Storage} Fix secondary storage account read access

---

src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_assign_user_identity.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_create_with_msi.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_remove_identity.yaml

https://github.com/Azure/azure-cli/pull/14233/files The CI in this PR didn't sync with resource's latest change. The api-version in three recording files are not correct.

{CI} replace 2019-07-01 with 2020-06-01

---

.azure-pipelines/templates/azdev_setup.yml
azure-pipelines.yml

Since we want to enable medium and low rule as well. But we don't plan to suppress them all for those old commands. So we have to run linter based on the diff so that customers won't receive too much noisy message.

{CI} Run linter based on diff

---

scripts/ci/credscan/CredScanSuppressions.json
src/azure-cli/azure/cli/command_modules/appconfig/_help.py
src/azure-cli/azure/cli/command_modules/appconfig/_params.py
src/azure-cli/azure/cli/command_modules/appconfig/custom.py
src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/recordings/test_azconfig_public_network_access.yaml
src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/test_appconfig_commands.py

We updated our management plane swagger to add some properties in store object for private endpoint feature. Although to add private endpoint, we leverage network CLI, there is one feature we need to support for publicNetworkAccess in our side. 
Like some existing store properties (sku, tags), publicNetworkAccess is another one to allow public data plane access even though private endpoint has been turned on. 
This PR will add support for enabling/disabling publicNetworkAccess with "az appconfig create" command.
This will create a new store called MyStore, with publicNetworkAccess enabled:
`az appconfig create -n MyStore -g ResourceGroupName -l westus --enable-public-network`
This will create a new store called MyStore, with publicNetworkAccess …

[AppConfig] Support enabling/disabling PublicNetworkAccess during store creation

---

.github/CODEOWNERS

Add code owner @jsntcy to Azure CLI core to work on 
1. Azure Identity
2. MSAL
3. Credential
4. Track 2 SDK
5. Command Index

{Misc} Update code owner

---

linter_exclusions.yml

Add two kinds of suppression for existing commands
- option_length_too_long
- option_should_not_contain_under_score
Remove one kind of suppression since the severity become medium
- parameter_should_not_end_in_resource_group

{CI} Linter: add suppression for two coming new rules.

---

linter_exclusions.yml

{CI} add four more suppression.

---

linter_exclusions.yml

{CI} bring suppression back which are removed by accident

---

.github/CODEOWNERS

{codeowner} update storage code owner

---

.azure-pipelines/templates/azdev_setup.yml
linter_exclusions.yml

0.1.24 has two more linter rules.

{CI} bump azdev to 0.1.24

---

src/azure-cli/azure/cli/command_modules/storage/operations/blob.py

[Storage] `az storage blob upload-batch`: Fix issue #14660 with unpositional arguments

---

src/azure-cli/azure/cli/command_modules/network/custom.py

{Network} fix NoneType Error

---

src/azure-cli-core/setup.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

Update the azure-mgmt-core version as az codegen has rely on the new version
---

{Release} Update Version of azure-mgmt-core to 1.2.0

---

src/azure-cli/azure/cli/command_modules/storage/operations/blob.py

Fix #6018 
`az storage blob copy start-batch` with `--source-sas`
---

[Storage] `az storage blob copy start-batch`: Fix #6018 for --source-sas

---

src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_container.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_disk_exclusion.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_item.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_job.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_policy.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_protection.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_restore.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_rp.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_scenario.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_softdelete.yaml
src/azure-cli/azure/cli/command_modules/backup/tests/latest/test_backup_commands.py

[Backup] Added VM tests

---

src/azure-cli/azure/cli/command_modules/network/custom.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone1_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone2_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone3_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone4_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone5_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone6_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone7_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_dns_zone8_import.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_dns_commands.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/zone_files/zone1.txt
src/azure-cli/azure/cli/command_modules/network/zone_file/record_processors.py

[Network] az network dns export: export FQDN for MX, PTR, NS and SRV type instead of relative path

---

src/azure-cli/azure/cli/command_modules/aro/__init__.py
src/azure-cli/azure/cli/command_modules/aro/_aad.py
src/azure-cli/azure/cli/command_modules/aro/_help.py
src/azure-cli/azure/cli/command_modules/aro/_params.py
src/azure-cli/azure/cli/command_modules/aro/_rbac.py
src/azure-cli/azure/cli/command_modules/aro/_validators.py
src/azure-cli/azure/cli/command_modules/aro/custom.py
src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_create.yaml
src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_delete.yaml
src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_list.yaml
src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_list_credentials.yaml
src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_show.yaml
src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_update.yaml
src/azure-cli/azure/cli/command_modules/aro/tests/latest/test_aro_commands.py

The updates here are the latest development features to be added to Azure Red Hat OpenShift az cli client.
- enhanced permissions validation
- logging improvements
- type checking
None
These are teh enhancements that we use for our Azure cli in the github.com/Azure/ARO-RP repository.
None
---

[ARO] CLI enhancements, including route table checking permissions

---

linter_exclusions.yml
src/azure-cli/azure/cli/command_modules/acs/_help.py
src/azure-cli/azure/cli/command_modules/acs/_params.py
src/azure-cli/azure/cli/command_modules/acs/custom.py

feat: add AKS CMK argument in cluster creation
test done:
```
docker build --no-cache -t andyzhangx/azure-cli:rc2.10.1-cmk -f ./Dockerfile .
docker run -v ${HOME}:/root -it andyzhangx/azure-cli:rc2.10.1-cmk
--node-osdisk-diskencryptionset-id -d     : ResourceId of the disk encryption set to use for
enabling encryption at rest on agent node os disk.
az aks create -g MyResourceGroup -n MyManagedCluster --node-osdisk-diskencryptionset-id
```
---

[AKS] add AKS CMK argument in cluster creation

---

src/azure-cli/azure/cli/command_modules/acs/custom.py

[AKS] Set network profile when using basic load balancer.

---

src/azure-cli/azure/cli/command_modules/backup/tests/latest/preparers.py
src/azure-cli/azure/cli/command_modules/monitor/_params.py
src/azure-cli/azure/cli/command_modules/monitor/operations/metric_alert.py
src/azure-cli/azure/cli/command_modules/monitor/operations/monitor_clone_util.py
src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_metric_alert_for_rg_and_sub.yaml
src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_metric_alert_scenarios.py
src/azure-cli/azure/cli/command_modules/monitor/validators.py

[Monitor] az monitor metrics alert create: support RG and Sub as the scope values

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py

fix issue: https://github.com/Azure/azure-cli/issues/14701
This PR implements  `az functionapp create --assign-identity`
No tests added, since identity assigning of functionapp and webapp is calling exactly the same implementation.
---

[App Service] Fix #14701: implement functionapp create --assign-identity

---

src/azure-cli-telemetry/azure/cli/telemetry/__init__.py

Resolve #11613 
`pywin32.pth` is now honored by the embeddable Python in MSI and the patch is no longer needed.
---

{Pywin32} Remove win32 search path patch

---

src/azure-cli/azure/cli/command_modules/keyvault/_help.py

The original link was invalid, changed to a proper new one.
---

{KeyVault} Fix the bad link

---

NOTICE.txt

Last PR doesn't add all dependencies to NOTICE.txt, this PR add all listed in https://dev.azure.com/azure-sdk/public/_componentGovernance/120576?_a=alerts&typeId=824857&alerts-view-option=active
---

{Misc} Update NOTICE.txt

---

azure-cli2017.pyproj
src/azure-cli/azure/cli/command_modules/ams/commands.py
src/azure-cli/azure/cli/command_modules/synapse/_client_factory.py
src/azure-cli/azure/cli/command_modules/synapse/_help.py
src/azure-cli/azure/cli/command_modules/synapse/_params.py
src/azure-cli/azure/cli/command_modules/synapse/_validators.py
src/azure-cli/azure/cli/command_modules/synapse/commands.py
src/azure-cli/azure/cli/command_modules/synapse/constant.py
src/azure-cli/azure/cli/command_modules/synapse/operations/spark.py
src/azure-cli/azure/cli/command_modules/synapse/tests/latest/recordings/test_spark_job.yaml
src/azure-cli/azure/cli/command_modules/synapse/tests/latest/recordings/test_spark_session_and_statements.yaml
src/azure-cli/azure/cli/command_modules/synapse/tests/latest/test_synapse_scenario.py
src/azure-cli/azure/cli/command_modules/synapse/util.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

[Data Plane] -- Add synapse spark job releated commands based on track2 sdk
See details: #14722
az synapse spark job -h
az synapse spark session -h
az synapse spark statement -h
[commands](https://github.com/sunsw1994/azure-cli/blob/dfb4f6e380bb34f2ca3df89813e0c31a40b85fd5/src/azure-cli/azure/cli/command_modules/synapse/commands.py)
---

[Synapse] Add spark job releated commands based on track2 sdk

---

src/azure-cli/azure/cli/command_modules/util/tests/latest/recordings/test_rest_arm.yaml
src/azure-cli/azure/cli/command_modules/util/tests/latest/recordings/test_rest_microsoft_graph.yaml
src/azure-cli/azure/cli/command_modules/util/tests/latest/recordings/test_rest_storage.yaml
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

To fix https://github.com/Azure/azure-cli-extensions/issues/2082
The current msrest version 0.6.9 will throw an error when serializing a flattened 3-layer property. The latest 0.6.18 can support it.
`az extension add -n datafactory`
`az datafactory factory create -n testfactory -g testrg`
`az datafactory pipeline create --factory-name "testfactory" --name "pipeline1" --resource-group testrg --pipeline '@pipeline.json'`
Content for `pipeline.json`:
```
{
"activities": [
{
"name":"Wait1",
"type":"Wait",
"dependsOn":[],
"userProperties": [],
"typeProperties": {
"waitTimeInSeconds": 5
}
}
],
"annotations": []
}
```
Without this PR, when serializing `properties.folder.name` (same value as `name`), a NoneType error will be thrown. …

{Packaging} Bump msrest to 0.6.18

---

.azure-pipelines/templates/azdev_setup.yml

This PR is to upgrade azdev version to 0.1.26
---

{Package} upgrade azdev to 0.1.26

---

src/azure-cli/azure/cli/command_modules/storage/__init__.py
src/azure-cli/azure/cli/command_modules/storage/_client_factory.py
src/azure-cli/azure/cli/command_modules/storage/_help.py
src/azure-cli/azure/cli/command_modules/storage/_params.py
src/azure-cli/azure/cli/command_modules/storage/_validators.py
src/azure-cli/azure/cli/command_modules/storage/commands.py
src/azure-cli/azure/cli/command_modules/storage/operations/account.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_or_policy.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_ors.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py

Move from extension to main repo for GA release
`az storage account or-policy`
---

[Storage] `az storage account or-policy`: Support storage account object replication policy

---

src/azure-cli/azure/cli/command_modules/monitor/validators.py

{Monitor} Refine error message

---

src/azure-cli/azure/cli/command_modules/storage/_params.py
src/azure-cli/azure/cli/command_modules/storage/commands.py
src/azure-cli/azure/cli/command_modules/storage/operations/blob.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_upload_small_file.yaml

ICM https://portal.microsofticm.com/imp/v3/incidents/details/199846087/home
`az storage blob list`
---

[Storage] `az storage blob list`: Fix next_marker issue 

---

src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/private_endpoint_arm_templates/appconfiguration_configurationstores_parameters.json
src/azure-cli/azure/cli/command_modules/network/tests/latest/private_endpoint_arm_templates/appconfiguration_configurationstores_template.json
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_app_configuration.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py

[Network] az network private-endpoint-connection: support app configuration

---

src/azure-cli/azure/cli/command_modules/dls/tests/latest/recordings/test_dls_file_mgmt.yaml
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

Fix #14545 
`az dls fs join`
---

[Datalake Store]Fix issue #14545 for data lake join operation

---

.github/CODEOWNERS

{dls} add code owner

---

scripts/release/debian/test_deb_in_docker.sh

gcc is needed in debian package test
---

{Test} Add gcc in deb test script

---

src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_simulate_eviction.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_simulate_eviction.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

This PR adjusts the live test cases for `vm simulate-eviction` and `vmss simulate-eviction` to avoid violating security policy.
Not applicable.

{VM} Adjust vm/vmss simulate-eviction tests to avoid violating security policy

---

src/azure-cli/azure/cli/command_modules/network/_params.py

Fix https://github.com/Azure/azure-cli/issues/14400
---

[Network] Fix help message of options about connection-monitor endpoint

---

src/azure-cli/azure/cli/command_modules/network/_params.py

{Network} refine help message for PowerShell

---

src/azure-cli/azure/cli/command_modules/acr/_params.py

Update help section with new Isolated Tier for Agent pools
---

[ACR] Add Isolated Tier to Agent Pool

---

src/azure-cli-core/azure/cli/core/util.py

Resolve #14939
When fetching the latest versions from github master branch fails, we should still writes the local versions in the `versionCheck.json` file, it will still be helpful in checking whether local CLI has been updated and avoiding fetching the latest verison every time when the file is empty. It makes the `pypi` key may not exist, we should add error handling for it.
Turn off your network, remove `~/.azure/versionCheck.json`, run `az -h`, you should not see an error.
---

{Upgrade} Fix version check

---

src/azure-cli-telemetry/HISTORY.rst
src/azure-cli-telemetry/azure/cli/telemetry/__init__.py
src/azure-cli-telemetry/setup.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

{Telemetry} Bump version

---

doc/try_new_features_before_release.md

Add a new part "Install from source code".
Motivation is a user said he could't install from wheel. So let's provide more choices.
---

{Doc} doc/try_new_features_before_release.md

---

src/azure-cli/azure/cli/command_modules/vm/_params.py

Resolve https://github.com/Azure/azure-cli/issues/14735
[Compute] Add new license_type in vm create/update: RHEL_BYOS, SLES_BYOS
```
az vm create --license-type RHEL_BYOS
az vm update --license-type RHEL_BYOS
```
---

[Compute] Add new license_type in vm create/update: RHEL_BYOS, SLES_BYOS

---

src/azure-cli/azure/cli/command_modules/network/custom.py
src/azure-cli/azure/cli/command_modules/network/linter_exclusions.yml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_subnet_with_private_endpoint_and_private_Link_options.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_subnet_with_private_endpoint_option.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

Fix https://github.com/Azure/azure-cli/issues/14762
---

[Network] az network vnet subnet: Support --disable-private-endpoint-network-policies and --disable-private-link-service-network-policies

---

.github/CODEOWNERS
doc/try_new_features_before_release.md

Update `doc/try_new_features_before_release.md`.

{Doc} Update doc/try_new_features_before_release.md

---

src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_disk_encryption_e2e.yaml
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_image_builder_commands.py
src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py

{Compute} Fix tests, test_vmss_disk_encryption_e2e, test_image_build_managed_image, test_image_build_shared_image
---

{Compute} Fix tests, test_vmss_disk_encryption_e2e, test_image_build_managed_image, test_image_build_shared_image

---

src/azure-cli-core/setup.py

With `pip install --upgrade azure-cli` to update existing `azure-cli` package, `azure-cli-telemetry` will not be updated as there is no version requirement for it. We should pin its version as the latest `azure-cli` does not work with previous `azure-cli-telemetry` versions.
---

{Packaging} Pin telemetry version in setup.py

---

src/azure-cli/azure/cli/command_modules/kusto/_help.py
src/azure-cli/azure/cli/command_modules/kusto/commands.py

[Kusto] Add deprecating message

---

src/azure-cli/azure/cli/command_modules/network/custom.py

Fix https://github.com/Azure/azure-cli/issues/14996
---

[Network] Fix bug while updateing flow-log when its subproperty network_watcher_flow_analytics_configuration is None

---

.github/CODEOWNERS

Add @jsntcy as the code owner of Role.

{Misc} Update code owner of Role

---

src/azure-cli/azure/cli/command_modules/network/_help.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py

- live-only an unstable test `test_manage_appgw_private_endpoint`
- Update usage example for new parameters of endpoint of CMv2
---

{Network} Update usage example for new parameters of endpoint of Connection Monitor V2

---

src/azure-cli/azure/cli/command_modules/storage/docs/Azure Storage File Share.md

Here is a sample document for file share usage in storage.
---

{Storage} Add main scenario usage for file share

---

src/azure-cli/azure/cli/command_modules/iot/commands.py
src/azure-cli/azure/cli/command_modules/iot/custom.py

[IoTCentral] CLI: App delete operation should be long running operation
---

[IoTCentral] CLI: App delete operation should be long running operation

---

src/azure-cli/azure/cli/command_modules/storage/_params.py
src/azure-cli/azure/cli/command_modules/storage/_validators.py
src/azure-cli/azure/cli/command_modules/storage/operations/account.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_update_container_delete_retention_policy.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py

One part of Ignite feature for Container Soft Delete
---

[Storage] `az storage account blob-service-properties update`: Add container delete retention policy support

---

src/azure-cli/azure/cli/command_modules/appservice/_constants.py
src/azure-cli/azure/cli/command_modules/appservice/custom.py
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_acr_create_function_app.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py

Resolves #14795 
This fixes and issue where if a customer is using a linux custom container image for their function, the `FUNCTIONS_WORKER_RUNTIME` app setting was being set incorrectly.
Fixed an existing test to make sure this scenario is validated.
```
azdev test test_acr_create_function_app
```
[AppService] functionapp create: Fixed issue where app setting was being incorrectly set for linux custom images
---

[AppService] functionapp: Fixed issue where app setting was being incorrectly set for linux custom images

---

src/azure-cli/azure/cli/command_modules/eventhubs/_client_factory.py
src/azure-cli/azure/cli/command_modules/eventhubs/_help.py
src/azure-cli/azure/cli/command_modules/eventhubs/_params.py
src/azure-cli/azure/cli/command_modules/eventhubs/_validator.py
src/azure-cli/azure/cli/command_modules/eventhubs/commands.py
src/azure-cli/azure/cli/command_modules/eventhubs/custom.py
src/azure-cli/azure/cli/command_modules/eventhubs/tests/latest/recordings/test_eh_cluster.yaml
src/azure-cli/azure/cli/command_modules/eventhubs/tests/latest/recordings/test_eh_namespace.yaml
src/azure-cli/azure/cli/command_modules/eventhubs/tests/latest/test_cluster_commands.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

…
Added new Cluster commands and trusted_service_access_enabled parameter for Networkruleset in az eventhubs namespace create/update commands
> az eventhubs cluster create
example: 
az eventhubs cluster create --resource-group myresourcegroup --name mycluster --location mylocation --capacity 1 --tags tag=value
> az eventhubs cluster show
example: 
az eventhubs cluster show --resource-group myresourcegroup --name mycluster  --tags tag=value
> az eventhubs cluster update
example: 
az eventhubs cluster update --resource-group myresourcegroup --name mycluster
> az eventhubs cluster available-region
example: 
az eventhubs cluster available-region
> az eventhubs cluster namespace list
example: 
az eventhubs cluster namespace list --resource-group …

[Eventhub] Added Cluster commands and trusted_service_access_enabled parameter for Networkruleset

---

src/azure-cli/azure/cli/command_modules/network/_params.py

Fix https://github.com/Azure/azure-cli/issues/14674
---

{Network} application-gaetway update: update help message for --host-names for clearer usage

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py

Resolves #15172 
This resolves an issue where `az functionapp deployment source config-zip` would throw an exception even if successful when pushing to linux consumption apps.
[AppService] az functionapp deployment source config-zip: Fixed an issue where config-zip could throw an exception on success on linux consumption 
---

[AppService] functionapp: Fixed an issue where config-zip could throw an exception even if successful

---

scripts/ci/credscan/CredScanSuppressions.json
src/azure-cli/azure/cli/command_modules/storage/_params.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_incremental_copy.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_blob_copy_scenarios.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_blob_scenarios.py

previous `--destination-if-modified-since` and `--destination-if-unmodified-since` should be datetime object with rfc format, which will cause error in command line.
Using ISO format is typical method for time related change. Here is to accept iso string as date time.
[Storage] BREAKING CHANGE: `az storage blob copy start`: Fix format issue for `--destination-if-modified-since` and `--destination-if-unmodified-since`
[Storage] BREAKING CHANGE: `az storage blob incremental-copy start`: Fix format issue for `--destination-if-modified-since` and `--destination-if-unmodified-since`
---

[Storage] Change datetime for copy

---

src/azure-cli/setup.py

`azure-mgmt-keyvault==7.0.0b3`
---

{KeyVault} Lock SDK version

---

src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/custom.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_rule.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

Close https://github.com/Azure/azure-cli/issues/15050
---

[Network] application-gateway rule: Support --priority option

---

src/azure-cli/azure/cli/command_modules/apim/_help.py

[APIM] api import: Update short summary

---

src/azure-cli/setup.py

Merge `release` back into `dev`
---

{Release} Merge release back into dev

---

src/azure-cli/azure/cli/command_modules/acs/_help.py
src/azure-cli/azure/cli/command_modules/acs/_params.py
src/azure-cli/azure/cli/command_modules/acs/custom.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_custom.py

Be able to create with virtual node enabled. 
[AKS] support virtual-node with aks create: `az aks create --enable-addons virtual-node`
---

[AKS] Be able to create AKS with virtual node enabled

---

doc/use_cli_in_airgapped_clouds.md

Add current instructions to use azure cli in airgapped clouds.
---

{Doc} Add instructions to use Azure CLI in Airgapped Clouds

---

src/azure-cli/azure/cli/command_modules/network/_template_builder.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_with_defaults.yaml

Fix https://github.com/Azure/azure-cli/issues/15130
1. Able to create appgw without specifying any public and private IP.
2. Able to create appgw with either public or private IP specified.
3. Able to create appgw with both public and private IP specified.
---

[Network] az network application-gateway create: Fix bug that cannot create without public IP sepcified

---

src/azure-cli/azure/cli/command_modules/storage/_client_factory.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_adls_filesystem_scenarios.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_adls_gen2_scenarios.py

Fix ADLS track2 issue with connection string
---

[Storage] `az storage fs`: Fix connection string issue

---

src/azure-cli/azure/cli/command_modules/network/_help.py
src/azure-cli/azure/cli/command_modules/network/_params.py

Fix https://github.com/Azure/azure-cli/issues/15249
---

{Network} Update help message for vrouter

---

src/azure-cli/azure/cli/command_modules/keyvault/_help.py

Fix: #15016 
Added 3 examples.
---

{KeyVault} Add examples for `az keyvault set-policy`

---

src/azure-cli/azure/cli/command_modules/lab/custom.py

Fixes https://github.com/Azure/azure-cli/issues/14127
az lab custom-image create --lab-name {} --resource-group {} --name {} --author {} --description {} --os-type {} --os-state {} --source-vm-id {} --debug
[Lab] Fix #14127: __init__() takes 1 positional argument but 2 were given
---

[Lab]  Fix for issue #14127 __init__() takes 1 positional argument but 2 were given

---

export_keyvault.json
src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/test_appconfig_commands.py

[AppConfig]Fix test bug

---

.github/CODEOWNERS

{codeowner} update codeowner

---

.github/CODEOWNERS

add codeowner for hdinsight

---

src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt

Resolve https://github.com/Azure/azure-cli/issues/15054
Remove limitation of FD count in Python SDK
az vm host group create -l eastus --name zonalHGwith5FD -g fy4 --platform-fault-domain-count 5 -z 1 --automatic-placement true
---

[Compute] Fix host group creation FD count limitation

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__main__.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

{Release} Hotfix: Upgrade version to 2.12.1

---

src/azure-cli/azure/cli/command_modules/storage/_params.py
src/azure-cli/azure/cli/command_modules/storage/commands.py

According to service requirement, we will make access tier GA in CLI.
---

[Storage] `az storage share-rm`: GA release access tier

---

src/azure-cli/azure/cli/command_modules/appservice/resources/LinuxFunctionsStacks.json
src/azure-cli/azure/cli/command_modules/appservice/resources/WindowsFunctionsStacks.json

Resolves #15350 
This is only a visual help menu change
[AppService] az functionapp create: Removed the preview flag from Java 11 when creating a new function app
---

[AppService] functionapp: Removed the preview flag from Java 11 when creating new function apps

---

src/azure-cli-core/azure/cli/core/telemetry.py

This PR catches the psutil importing error on cygwin. Otherwise, the exception will be thrown in --debug output.
---

{Core} Catch psutil importing error on cygwin

---

scripts/release/generate_history_notes.py

Code modification to reflect the PR description template change.
---

{History} Fix note extraction in description

---

src/azure-cli-core/azure/cli/core/command_recommender.py

This pr adds the recommended command to Telemetry for analysis.
If the recommended command is from Aladdin
```
"Context.Default.AzureCLI.debug_info":"AladdinRecommendCommand: ..."
```
If from example
```
"Context.Default.AzureCLI.debug_info":"ExampleRecommendCommand: ..."
```
---

{Core} Add recommended command to Telemetry

---

src/azure-cli/azure/cli/command_modules/acr/_constants.py
src/azure-cli/azure/cli/command_modules/acr/_params.py
src/azure-cli/azure/cli/command_modules/acr/build.py
src/azure-cli/azure/cli/command_modules/acr/run.py
src/azure-cli/azure/cli/command_modules/acr/task.py
src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_agentpool.yaml
src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_create_replication.yaml
src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_create_webhook.yaml
src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_create_with_audits.yaml
src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_create_with_managed_registry.yaml
src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_encryption_with_cmk.yaml
src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_identity.yaml
src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_network_rule.yaml
src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_task.yaml
src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_taskrun.yaml
src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_with_dedicated_data_endpoints.yaml
src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_with_private_endpoint.yaml
src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_with_public_network_access.yaml
src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_check_name_availability.yaml
src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_repository_token_create.yaml
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

* Add log template changes to task, run, build
* Add systemtask changes to task
---

[ACR] Add logtemplate and systemtask changes for ACR Tasks

---

src/azure-cli/azure/cli/command_modules/network/_help.py
src/azure-cli/azure/cli/command_modules/network/_params.py
src/azure-cli/azure/cli/command_modules/network/_validators.py
src/azure-cli/azure/cli/command_modules/network/commands.py
src/azure-cli/azure/cli/command_modules/network/custom.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_waf_policy_managed_rules.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

Fix https://github.com/Azure/azure-cli/issues/15019
[Network] az network application-gateway waf-policy managed-rule rule-set add: Expose server error to user to give more intuitive hint message.  
[Network] az network application-gateway waf-policy managed-rule rule-set update: Support to change rule set type version.
---

[Network] az network application-gateway waf-policy managed-rule rule-set: Expose server error to user to give more intuitive hint message

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/azure/cli/core/cloud.py
src/azure-cli-core/azure/cli/core/tests/test_cloud.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__main__.py
src/azure-cli/azure/cli/command_modules/keyvault/_validators.py
src/azure-cli/azure/cli/command_modules/rdbms/_flexible_server_util.py
src/azure-cli/azure/cli/command_modules/rdbms/_params.py
src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_mysql.py
src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_virtual_network.py
src/azure-cli/azure/cli/command_modules/rdbms/validators.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

Fix diverged **dev** and **release** introduced by squash merging in #15360.

{Branch Management} Merge release 2.12.1 back to dev 

---

src/azure-cli/azure/cli/command_modules/storage/_validators.py

{Storage} Fix #15379: `az storage copy` crashes with amazon source url

---

src/azure-cli/azure/cli/command_modules/appservice/custom.py

--xml option  returns escaped string. Handling to remove the escape chars from XML.
`az webapp deployment list-publishing-profiles 
--name <webapp-name> 
--resource-group <webapp-resource-group> 
--xml`
---

[App Service] fix#-13777-Fix to remove escape chars from XML

---

src/azure-cli/azure/cli/command_modules/network/_params.py

Fix https://github.com/Azure/azure-cli/issues/15136
---

{Network} private-endpoint create: Update help to make meaning of --group-ip more clear

---

src/azure-cli/azure/cli/command_modules/vm/_help.py

A link in help text is out-of-date. Fix it.
Resolve https://github.com/Azure/azure-cli/issues/15026
---

{Compute} Fix vm create help text

---

src/azure-cli/azure/cli/command_modules/apim/custom.py

[APIM]Fix issue with creating consumption tier instance

---

src/azure-cli/azure/cli/command_modules/keyvault/_validators.py

No big changes, please see code diff for detail.
---

{KeyVault} Fix a wrong condition while processing storage uri

---

src/azure-cli/azure/cli/command_modules/vm/commands.py

Fix issue in https://dev.azure.com/azure-sdk/public/_build/results?buildId=574805&view=logs&jobId=9a2ea557-fd95-524b-061f-735a0fe23124&j=9a2ea557-fd95-524b-061f-735a0fe23124&t=f97196d1-ee52-5a46-6164-961f0c96a9f9
---

{Compute} Add min api information for list_associated_resources

---

doc/quoting-issues-with-powershell.md

Update `quoting-issues-with-powershell.md` to link to the centralized issue https://github.com/Azure/azure-cli/issues/15529.

{Doc} Update quoting-issues-with-powershell.md

---

src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

Update Cognitive Services SDK, allowing more optional fields are added to API Properties.
{Cognitive Services} Update Cognitive Services SDK
---

{Cognitive Services} Update Cognitive Services SDK

---

src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py
src/azure-cli/azure/cli/command_modules/cosmosdb/_params.py
src/azure-cli/azure/cli/command_modules/cosmosdb/_validators.py
src/azure-cli/azure/cli/command_modules/cosmosdb/actions.py
src/azure-cli/azure/cli/command_modules/cosmosdb/custom.py
src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_sql_container_analytical_ttl.yaml
src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/test_cosmosdb_commands.py

Updates the error message user sees when supplying invalid key name for the "locations" parameter during update or create. Helps address issue https://github.com/Azure/azure-cli/issues/14627.
Fix bug preventing removing ip range filter via command line (handle empty string). Helps address issue https://github.com/Azure/azure-cli/issues/15291.
Add analytical storage ttl support for SQL containers.
Fixed typo in help text to address https://github.com/Azure/azure-cli/issues/15524
az cosmosdb update -g {g} -n {n} --locations regionName=EastUS failoverPriorit=0
az cosmosdb update -g {g} -n {n} --ip-range-filter ""
[Cosmos DB] az cosmosdb create/update: Improve error message from incorrect --locations input
[Cosmos DB] az cosmosdb sql …

[Cosmos DB] az cosmosdb create/update: Improve error message from incorrect --locations input

---

azure-pipelines.yml

Currently Test Homebrew Formula will fail and report blow error:
> Error: 5 problems in 1 formula detected
> azure-cli:
>   * 1: col 1: Class has too many lines. [594/100]
>   * 1: col 1: Missing top-level class documentation comment.
>   * 1: col 1: Missing frozen string literal comment.
>   * 714: col 3: Assignment Branch Condition size for install is too high. [<3, 21, 3> 21.42/17]
>   * 714: col 3: Method has too many lines. [17/10]
It's because homebrew has updated the audit rule and our formula will not pass the check. So remove this check first.
---
This checklist …

{Package} remove brew audit --strict check

---

src/azure-cli/HISTORY.rst

{Release} remove revert PR from HISTORY.rst

---

azure-pipelines.yml
doc/authoring_command_modules/README.md

Update doc for hotfix PR to describe the correct workflow to merge `release` back to `dev`.

{Doc} Update doc for hotfix PR

---

src/azure-cli/azure/cli/command_modules/storage/operations/filesystem.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_adls_filesystem_scenarios.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_adls_gen2_scenarios.py

Fix issue #15600 
`az storage fs exists` with filesystem not existed and `false` will be returned.
---

[Storage] Fix issue #15600: az storage fs exists: in case fs does not exist ResourceNotFoundError is returned

---

src/azure-cli/azure/cli/command_modules/cloud/_help.py

{Cloud} az cloud register: Fix the example

---

.github/CODEOWNERS

{Misc} Update Network and Monitor codeowner

---

src/azure-cli-core/azure/cli/core/azclierror.py

This PR adjusts
- The `set_recommendation` method in the base error class to accept either a string or a list as recommendations.
- The class descriptions of some error types.
The changes should have not any impact for users.

{Error Handling} Refine the error types and provide more class descriptions

---

src/azure-cli/azure/cli/command_modules/find/custom.py

@fengzhou-msft let me know that the User ID we were sending was not the intended one, so this PR switches it to the pseudo ID we wanted.
**Testing Guide** 
N/A
---

{Find} az find: Update to use the appopriate User ID

---

src/azure-cli/azure/cli/command_modules/vm/_help.py

Issue https://github.com/Azure/azure-cli/issues/15765
Update help.
Attach a managed persistent disk to a VM. Please note that --ids only supports one disk.
---

{Compute} Update help of vm disk attach

---

src/azure-cli/azure/cli/command_modules/appservice/_help.py
src/azure-cli/azure/cli/command_modules/appservice/_params.py
src/azure-cli/azure/cli/command_modules/appservice/_validators.py
src/azure-cli/azure/cli/command_modules/appservice/access_restrictions.py

Fixes to reported issues #11698 #15198 #14862 #15409 for config access-restriction add command. 
#15409 Improved the error description to suggest using --Action Deny
#14862 #15198 (duplicate) Included check for scm_site in validation code
#11698 Improve help text and examples with subnet resource id as well as adding a --vnet-resource-group to explicitly be able to specify this.
Add Access Restriction opening (Allow) named remote_agents in vNet 'corp01' in rg 'vnets' with
subnet 'agents'
az webapp config access-restriction add -g ResourceGroup -n AppName --rule-name
remote_agents --action Allow --vnet-name corp01 --subnet agents --priority 500 --vnet-
resource-group vnets
Add Access Restriction to both scm site and main site
az webapp config …

[AppService] Fix #11698 #15198 #14862 #15409: az webapp/functionapp config access-restriction add

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__main__.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

Upgrade version to **2.14.1** for hotfix
Hotfix PR: #15760
---

{Release} Hotfix: Upgrade version for hotfix

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__main__.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

{Release} Hot fix release 2.14.2

---

src/azure-cli-core/azure/cli/core/azclierror.py

This PR 
- adds `FileOperationError` into the new error type
- provides `UnknownError` as a fallback error type of UserFault
Developer related. No changes for user experience.

{Error Improvement} Add new error types

---

doc/command_guidelines.md
doc/error_handling_guidelines.md

This PR provides the developer guidelines to onboard the new error handling methods and the new error output formats. Generally, it covers what the command group authors need to do, which mainly includes
- Apply the new error types
- Authoring the actionable error messages
- Provide necessary failure recommendations
Fo reference #15314

{Error Handling} Developer guidelines to onboad the new error output

---

.github/pull_request_template.md

Trim trailing whitespace in `.github/pull_request_template.md`

{Misc.} Trim trailing whitespace in .github/pull_request_template.md

---

src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_flexible_server_vnet_mgmt_supplied_subnet_id_in_different_rg.yaml
src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_flexible_server_vnet_mgmt_supplied_subnetid.yaml
src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_flexible_server_vnet_mgmt_supplied_vname_and_subnetname.yaml
src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_flexible_server_vnet_mgmt_supplied_vnet.yaml
src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_public_access_mgmt.yaml
src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_vnet_mgmt.yaml
src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_vnet_mgmt_supplied_subnet_id_in_different_rg.yaml
src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_vnet_mgmt_supplied_subnetid.yaml
src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_vnet_mgmt_supplied_vname_and_subnetname.yaml
src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_vnet_mgmt_supplied_vnet.yaml
src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands.py

Description
The PR introduces tests for vnet, subnet and public-access for flexible-server commands.
Testing Guide
azdev test FlexibleServerVnetMgmtScenarioTest
azdev test FlexibleServerPublicAccessMgmtScenarioTest --live

{RDBMS} Introduce tests for Vnet/Subnet and public-access in Flexible-server commands.

---

src/azure-cli/azure/cli/command_modules/iot/_params.py
src/azure-cli/azure/cli/command_modules/iot/custom.py
src/azure-cli/azure/cli/command_modules/iot/tests/latest/recordings/test_dps_lifecycle.yaml
src/azure-cli/azure/cli/command_modules/iot/tests/latest/test_iot_dps_commands.py

Fix partial https://github.com/Azure/azure-cli/issues/13497
---

[DPS] Allow tags in IoT DPS create command

---

doc/use_cli_in_airgapped_clouds.md

Add a list of known unsupported features in airgapped clouds.
---

{Doc} Update instructions on using airgapped clouds

---

scripts/live_test/HISTORY.rst
scripts/live_test/generate_index.py
scripts/live_test/sendemail.py

0.8.0
++++++
* Optimize index.html CSS style.
* Support a permanent link of latest testing results.
---

{Test} Live test 0.8.0

---

src/azure-cli/azure/cli/command_modules/acs/_client_factory.py
src/azure-cli/azure/cli/command_modules/acs/_help.py
src/azure-cli/azure/cli/command_modules/acs/_params.py
src/azure-cli/azure/cli/command_modules/acs/_validators.py
src/azure-cli/azure/cli/command_modules/acs/custom.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_control_plane_user_assigned_identity.yaml
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_validators.py

The feature "bring-your-own control plane identity" is going to GA. This PR adds cli support for it.
Added unit test and e2e recording.
---

[AKS] Support BYO control plane identity

---

src/azure-cli/HISTORY.rst

{Misc} Fix format in HISTORY.rst

---

src/azure-cli/azure/cli/command_modules/network/tests/latest/test_dns_commands.py
src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/test_privatedns_commands.py

https://clitestresultstac.blob.core.windows.net/20201113-054322-540793/network.report.parallel.html
---

{Network} Fix live test that caused by there is no self.skip() method

---

src/azure-cli/azure/cli/command_modules/network/_validators.py
src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_http_listener_with_waf_policy.yaml
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py

Fix https://github.com/Azure/azure-cli/issues/15592. Misspell the ID of WAF policy cause this bug.
---

[Network] az network application-gateway http-listener: Fix bug that cannot create and update with WAF policy name

---

src/azure-cli/azure/cli/command_modules/storage/_validators.py
src/azure-cli/azure/cli/command_modules/storage/commands.py
src/azure-cli/azure/cli/command_modules/storage/operations/account.py
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_file_delete_retention_policy.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_share_rm_soft_delete.yaml
src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py

Fix the scenario when no property is specified.
If there is no property specified, an assignment error will be reported.
`az storage account file-service-properties update`:
---

{Storage} `az storage account file-service-properties update`: fix the scenario when no property is specified

---

src/azure-cli/azure/cli/command_modules/aro/__init__.py
src/azure-cli/azure/cli/command_modules/aro/_rbac.py
src/azure-cli/azure/cli/command_modules/aro/custom.py

The updates here are the latest development features to be added to Azure Red Hat OpenShift az cli client.
- extension suppression
- logging improvements
- narrow permissions  
None
These are the enhancements that we use for our Azure cli in the github.com/Azure/ARO-RP repository.

{ARO} minor CLI enhancements, including extension suppression

---

src/azure-cli/azure/cli/command_modules/backup/custom_afs.py
src/azure-cli/azure/cli/command_modules/backup/custom_base.py
src/azure-cli/azure/cli/command_modules/backup/custom_help.py
src/azure-cli/azure/cli/command_modules/backup/custom_wl.py

Replaced ValueError with ResourceNotFoundError to eliminate traceback from the error shown. Added a few more validation functions in custom_help.py to customize ResourceNotFoundError message. Added some validations/checks to eliminate AttributeError.
---

[BACKUP] Fix #14976: CLI error improvements for ValueError and AttributeError cases

---

src/azure-cli/azure/cli/command_modules/keyvault/_command_type.py
src/azure-cli/azure/cli/command_modules/keyvault/_params.py
src/azure-cli/azure/cli/command_modules/keyvault/_transformers.py
src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_key.yaml
src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_secret.yaml

Fix: #14706 , add a parameter `--include-managed` for `az keyvault key/secret list` to list managed resources.
Usage:
`az keyvault key list --vault-name {kv} --include-managed -o table`
`az keyvault secret list --vault-name {kv} --include-managed -o table`
---

[KeyVault] Add a parameter `--include-managed` for `az keyvault key/secret list` to list managed resources

---

src/azure-cli/azure/cli/command_modules/search/_help.py
src/azure-cli/azure/cli/command_modules/search/_params.py

This PR addresses an issue about not having SKU options present in Azure Search documentation. We want to add this to the _help.py file, which will autogenerate the relating documentation.
Fix #15813
Testing is not relevant for this PR. If there is a way to preview the resulting document changes, that would be nice though.
---

[Search] Add SKU option

---

src/azure-cli/azure/cli/command_modules/backup/custom_base.py
src/azure-cli/azure/cli/command_modules/backup/custom_wl.py
src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_softdelete.yaml

Added command to undelete protection for AzureWorkload using CLI.
az backup protection undelete --container-name {c} --item-name {i} --resource-group {rg} --vault-name {v} --backup-management-type AzureWorkload --workload-type {SAPHanaDatabase/SQLDatabase}
---

[BACKUP] az backup protection undelete: Added support for AzureWorkload protection undelete using CLI

---

src/azure-cli-core/HISTORY.rst
src/azure-cli-core/azure/cli/core/__init__.py
src/azure-cli-core/azure/cli/core/_profile.py
src/azure-cli-core/azure/cli/core/tests/test_profile.py
src/azure-cli-core/setup.py
src/azure-cli/HISTORY.rst
src/azure-cli/azure/cli/__main__.py
src/azure-cli/requirements.py3.Darwin.txt
src/azure-cli/requirements.py3.Linux.txt
src/azure-cli/requirements.py3.windows.txt
src/azure-cli/setup.py

Merge `release` back to `dev`.

{Branch Management} Merge release 2.15.1 back to dev
